#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Fisher Cats @ Yard Goats
<2018-04-05 Thu 18:05-21:05>
:PROPERTIES:
:ID:       EpessUkmNmMuxf6PoOlIS7mm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Yard Goats Fisher Cats @ Yard Goats

Buy tickets here  https //stza.co/~vLnp

Follow on MiLB First Pitch  https //stza.co/+vLnp-3i

Shop  https //stza.co/+vLnp-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Yard Goats
END:VALARM
DTSTART:20180405T230500Z
DTEND:20180406T020500Z
UID:EpessUkmNmMuxf6PoOlIS7mm@stanza.co
SUMMARY:Fisher Cats @ Yard Goats
DESCRIPTION:Fisher Cats @ Yard Goats\n\nBuy tickets here: https://stza.co/~vLnp\n\nFollow on MiLB First Pitch: https://stza.co/+vLnp-3i\n\nShop: https://stza.co/+vLnp-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Yard Goats
<2018-04-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       1NFB0u_LkygMjaS6dXCSLQQ5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Yard Goats Fisher Cats @ Yard Goats

Buy tickets here  https //stza.co/~vLnq

Follow on MiLB First Pitch  https //stza.co/+vLnq-1p

Shop  https //stza.co/+vLnq-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Yard Goats
END:VALARM
DTSTART:20180406T230500Z
DTEND:20180407T020500Z
UID:1NFB0u_LkygMjaS6dXCSLQQ5@stanza.co
SUMMARY:Fisher Cats @ Yard Goats
DESCRIPTION:Fisher Cats @ Yard Goats\n\nBuy tickets here: https://stza.co/~vLnq\n\nFollow on MiLB First Pitch: https://stza.co/+vLnq-1p\n\nShop: https://stza.co/+vLnq-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Yard Goats
<2018-04-07 Sat 17:05-20:05>
:PROPERTIES:
:ID:       KKUbE90s4A9Nd9moVj2yjOP3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Yard Goats Fisher Cats @ Yard Goats

Buy tickets here  https //stza.co/~vLnr

Follow on MiLB First Pitch  https //stza.co/+vLnr-m

Shop  https //stza.co/+vLnr-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Yard Goats
END:VALARM
DTSTART:20180407T220500Z
DTEND:20180408T010500Z
UID:KKUbE90s4A9Nd9moVj2yjOP3@stanza.co
SUMMARY:Fisher Cats @ Yard Goats
DESCRIPTION:Fisher Cats @ Yard Goats\n\nBuy tickets here: https://stza.co/~vLnr\n\nFollow on MiLB First Pitch: https://stza.co/+vLnr-m\n\nShop: https://stza.co/+vLnr-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Yard Goats
<2018-04-08 Sun 12:05-15:05>
:PROPERTIES:
:ID:       Zwi2Ln4x5bcQMoHt7nl5jv2q@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Yard Goats Fisher Cats @ Yard Goats

Buy tickets here  https //stza.co/~vLns

Follow on MiLB First Pitch  https //stza.co/+vLns-2e

Shop  https //stza.co/+vLns-2S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Yard Goats
END:VALARM
DTSTART:20180408T170500Z
DTEND:20180408T200500Z
UID:Zwi2Ln4x5bcQMoHt7nl5jv2q@stanza.co
SUMMARY:Fisher Cats @ Yard Goats
DESCRIPTION:Fisher Cats @ Yard Goats\n\nBuy tickets here: https://stza.co/~vLns\n\nFollow on MiLB First Pitch: https://stza.co/+vLns-2e\n\nShop: https://stza.co/+vLns-2S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Thunder
<2018-04-09 Mon 18:00-21:00>
:PROPERTIES:
:ID:       B7ePtUD6GpNT5-uGilGa4dZO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Thunder Fisher Cats @ Thunder

Follow on MiLB First Pitch  https //stza.co/+v9S_-F

Shop  https //stza.co/+v9S_-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Thunder
END:VALARM
DTSTART:20180409T230000Z
DTEND:20180410T020000Z
UID:B7ePtUD6GpNT5-uGilGa4dZO@stanza.co
SUMMARY:Fisher Cats @ Thunder
DESCRIPTION:Fisher Cats @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+v9S_-F\n\nShop: https://stza.co/+v9S_-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Thunder
<2018-04-10 Tue 18:00-21:00>
:PROPERTIES:
:ID:       OXluvMLj6ZPlObC_LvVy_xLt@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Thunder Fisher Cats @ Thunder

Follow on MiLB First Pitch  https //stza.co/+v9S$-Y

Shop  https //stza.co/+v9S$-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Thunder
END:VALARM
DTSTART:20180410T230000Z
DTEND:20180411T020000Z
UID:OXluvMLj6ZPlObC_LvVy_xLt@stanza.co
SUMMARY:Fisher Cats @ Thunder
DESCRIPTION:Fisher Cats @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+v9S$-Y\n\nShop: https://stza.co/+v9S$-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Thunder
<2018-04-11 Wed 18:00-21:00>
:PROPERTIES:
:ID:       UUcERivfqC7KGbqTsgQC7jna@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Thunder Fisher Cats @ Thunder

Follow on MiLB First Pitch  https //stza.co/+v9T0-3J

Shop  https //stza.co/+v9T0-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Thunder
END:VALARM
DTSTART:20180411T230000Z
DTEND:20180412T020000Z
UID:UUcERivfqC7KGbqTsgQC7jna@stanza.co
SUMMARY:Fisher Cats @ Thunder
DESCRIPTION:Fisher Cats @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+v9T0-3J\n\nShop: https://stza.co/+v9T0-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Yard Goats
<2018-04-13 Fri 17:35-20:35>
:PROPERTIES:
:ID:       61G0fk8nPzKFyap1Nb-IDvU1@stanza.co
:LOCATION: Magnet Schedule Giveaway
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Yard Goats The first 2,500 fans will receive a 2018 Magnet Schedule courtesy of EnergyNorth Propane!

Join us after the game for a spectacular Beatles Fireworks show courtesy of Atlas Fireworks!

Follow on MiLB First Pitch  https //stza.co/+vLnA-2s

Shop  https //stza.co/+vLnA-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Yard Goats
END:VALARM
DTSTART:20180413T223500Z
DTEND:20180414T013500Z
UID:61G0fk8nPzKFyap1Nb-IDvU1@stanza.co
SUMMARY:Fisher Cats vs. Yard Goats
DESCRIPTION:The first 2,500 fans will receive a 2018 Magnet Schedule courtesy of EnergyNorth Propane!\n\nJoin us after the game for a spectacular Beatles Fireworks show courtesy of Atlas Fireworks!\n\nFollow on MiLB First Pitch: https://stza.co/+vLnA-2s\n\nShop: https://stza.co/+vLnA-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Magnet Schedule Giveaway
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Yard Goats
<2018-04-14 Sat 17:35-20:35>
:PROPERTIES:
:ID:       orZbT3siaKfsS-zdr1qOP0ai@stanza.co
:LOCATION: Taylor Swift Fireworks
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Yard Goats Join us after the game for a spectacular Taylor Swift Fireworks show courtesy of Atlas Fireworks!

Join us as we recognize participants in the 2018 Reading Challenge, presented by Velcro Companies! Come dressed in your favorite pair of PJ's, plus play catch on the field before the game!

Follow on MiLB First Pitch  https //stza.co/+vLnC-m

Shop  https //stza.co/+vLnC-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Yard Goats
END:VALARM
DTSTART:20180414T223500Z
DTEND:20180415T013500Z
UID:orZbT3siaKfsS-zdr1qOP0ai@stanza.co
SUMMARY:Fisher Cats vs. Yard Goats
DESCRIPTION:Join us after the game for a spectacular Taylor Swift Fireworks show courtesy of Atlas Fireworks!\n\nJoin us as we recognize participants in the 2018 Reading Challenge, presented by Velcro Companies! Come dressed in your favorite pair of PJ's, plus play catch on the field before the game!\n\nFollow on MiLB First Pitch: https://stza.co/+vLnC-m\n\nShop: https://stza.co/+vLnC-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Taylor Swift Fireworks
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Yard Goats
<2018-04-15 Sun 12:35-15:35>
:PROPERTIES:
:ID:       ASTdMY7h2Ju7b3QPHtZeYZp8@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Yard Goats Join us as we recognize participants in the 2018 Reading Challenge, presented by Velcro Companies! Come wearing your favorite sports jersey, plus play catch on the field before the game!

Kids run the bases after every Sunday day game!

Follow on MiLB First Pitch  https //stza.co/+vLnE-K

Shop  https //stza.co/+vLnE-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Yard Goats
END:VALARM
DTSTART:20180415T173500Z
DTEND:20180415T203500Z
UID:ASTdMY7h2Ju7b3QPHtZeYZp8@stanza.co
SUMMARY:Fisher Cats vs. Yard Goats
DESCRIPTION:Join us as we recognize participants in the 2018 Reading Challenge, presented by Velcro Companies! Come wearing your favorite sports jersey, plus play catch on the field before the game!\n\nKids run the bases after every Sunday day game!\n\nFollow on MiLB First Pitch: https://stza.co/+vLnE-K\n\nShop: https://stza.co/+vLnE-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Rumble Ponies
<2018-04-16 Mon 17:35-20:35>
:PROPERTIES:
:ID:       W_8K6WBFIvSShyRJyadXhq5x@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Rumble Ponies Fisher Cats vs. Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLnH-2p

Shop  https //stza.co/+vLnH-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Rumble Ponies
END:VALARM
DTSTART:20180416T223500Z
DTEND:20180417T013500Z
UID:W_8K6WBFIvSShyRJyadXhq5x@stanza.co
SUMMARY:Fisher Cats vs. Rumble Ponies
DESCRIPTION:Fisher Cats vs. Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLnH-2p\n\nShop: https://stza.co/+vLnH-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Rumble Ponies
<2018-04-17 Tue 17:35-20:35>
:PROPERTIES:
:ID:       URytt_frHo33RS3Ghr6dOrd0@stanza.co
:LOCATION: Tall Boy Tuesdays
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Rumble Ponies $5 Miller, Coors, & Twisted Tea - 24oz - in the Brewhouse & Tiki Bar.  Available until First Pitch.

Follow on MiLB First Pitch  https //stza.co/+vLnI-21

Shop  https //stza.co/+vLnI-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Rumble Ponies
END:VALARM
DTSTART:20180417T223500Z
DTEND:20180418T013500Z
UID:URytt_frHo33RS3Ghr6dOrd0@stanza.co
SUMMARY:Fisher Cats vs. Rumble Ponies
DESCRIPTION:$5 Miller, Coors, & Twisted Tea - 24oz - in the Brewhouse & Tiki Bar.  Available until First Pitch.\n\nFollow on MiLB First Pitch: https://stza.co/+vLnI-21\n\nShop: https://stza.co/+vLnI-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Tall Boy Tuesdays
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Rumble Ponies
<2018-04-18 Wed 17:35-20:35>
:PROPERTIES:
:ID:       nqXt3ZZPh9rjxs24lu2R1kTE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Rumble Ponies Fisher Cats vs. Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLnL-3j

Shop  https //stza.co/+vLnL-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Rumble Ponies
END:VALARM
DTSTART:20180418T223500Z
DTEND:20180419T013500Z
UID:nqXt3ZZPh9rjxs24lu2R1kTE@stanza.co
SUMMARY:Fisher Cats vs. Rumble Ponies
DESCRIPTION:Fisher Cats vs. Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLnL-3j\n\nShop: https://stza.co/+vLnL-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Rumble Ponies
<2018-04-19 Thu 09:35-12:35>
:PROPERTIES:
:ID:       SCngr7dwR6WyGP6hCiADJi-K@stanza.co
:LOCATION: Manchester Schools Day
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Rumble Ponies Students from around New Hampshire join us for a day of educational fun, with special games & entertainment, all in the name of learning!

Follow on MiLB First Pitch  https //stza.co/+vLnM-3L

Shop  https //stza.co/+vLnM-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Rumble Ponies
END:VALARM
DTSTART:20180419T143500Z
DTEND:20180419T173500Z
UID:SCngr7dwR6WyGP6hCiADJi-K@stanza.co
SUMMARY:Fisher Cats vs. Rumble Ponies
DESCRIPTION:Students from around New Hampshire join us for a day of educational fun, with special games & entertainment, all in the name of learning!\n\nFollow on MiLB First Pitch: https://stza.co/+vLnM-3L\n\nShop: https://stza.co/+vLnM-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Manchester Schools Day
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Fightin Phils
<2018-04-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       gUCMNYdCF0ehPfJANRGgP3s2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Fightin Phils Fisher Cats @ Fightin Phils

Buy tickets here  https //stza.co/~vLpW

Follow on MiLB First Pitch  https //stza.co/+vLpW-P

Shop  https //stza.co/+vLpW-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Fightin Phils
END:VALARM
DTSTART:20180420T230500Z
DTEND:20180421T020500Z
UID:gUCMNYdCF0ehPfJANRGgP3s2@stanza.co
SUMMARY:Fisher Cats @ Fightin Phils
DESCRIPTION:Fisher Cats @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vLpW\n\nFollow on MiLB First Pitch: https://stza.co/+vLpW-P\n\nShop: https://stza.co/+vLpW-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Fightin Phils
<2018-04-21 Sat 17:05-20:05>
:PROPERTIES:
:ID:       li8SpVgZFP2zq01ZJL2BuY-I@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Fightin Phils Fisher Cats @ Fightin Phils

Buy tickets here  https //stza.co/~vLpX

Follow on MiLB First Pitch  https //stza.co/+vLpX-1Y

Shop  https //stza.co/+vLpX-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Fightin Phils
END:VALARM
DTSTART:20180421T220500Z
DTEND:20180422T010500Z
UID:li8SpVgZFP2zq01ZJL2BuY-I@stanza.co
SUMMARY:Fisher Cats @ Fightin Phils
DESCRIPTION:Fisher Cats @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vLpX\n\nFollow on MiLB First Pitch: https://stza.co/+vLpX-1Y\n\nShop: https://stza.co/+vLpX-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Fightin Phils
<2018-04-22 Sun 13:05-16:05>
:PROPERTIES:
:ID:       e9yuqjHhR3tSybsbFazQfHv5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Fightin Phils Fisher Cats @ Fightin Phils

Buy tickets here  https //stza.co/~vLpY

Follow on MiLB First Pitch  https //stza.co/+vLpY-6

Shop  https //stza.co/+vLpY-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Fightin Phils
END:VALARM
DTSTART:20180422T180500Z
DTEND:20180422T210500Z
UID:e9yuqjHhR3tSybsbFazQfHv5@stanza.co
SUMMARY:Fisher Cats @ Fightin Phils
DESCRIPTION:Fisher Cats @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vLpY\n\nFollow on MiLB First Pitch: https://stza.co/+vLpY-6\n\nShop: https://stza.co/+vLpY-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Rumble Ponies
<2018-04-23 Mon 17:35-20:35>
:PROPERTIES:
:ID:       3E1UiooJCluyPqmApzhl9eGM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Rumble Ponies Fisher Cats @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLn5-2$

Shop  https //stza.co/+vLn5-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Rumble Ponies
END:VALARM
DTSTART:20180423T223500Z
DTEND:20180424T013500Z
UID:3E1UiooJCluyPqmApzhl9eGM@stanza.co
SUMMARY:Fisher Cats @ Rumble Ponies
DESCRIPTION:Fisher Cats @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLn5-2$\n\nShop: https://stza.co/+vLn5-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Rumble Ponies
<2018-04-24 Tue 17:35-20:35>
:PROPERTIES:
:ID:       A9Mfiy0HdzosJ3g7414eUQQ3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Rumble Ponies Fisher Cats @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLn6-2q

Shop  https //stza.co/+vLn6-1J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Rumble Ponies
END:VALARM
DTSTART:20180424T223500Z
DTEND:20180425T013500Z
UID:A9Mfiy0HdzosJ3g7414eUQQ3@stanza.co
SUMMARY:Fisher Cats @ Rumble Ponies
DESCRIPTION:Fisher Cats @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLn6-2q\n\nShop: https://stza.co/+vLn6-1J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Rumble Ponies
<2018-04-25 Wed 17:35-20:35>
:PROPERTIES:
:ID:       l-O9VxU3fIUVDEtKhkUk7Z7v@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Rumble Ponies Fisher Cats @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLn7-2Y

Shop  https //stza.co/+vLn7-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Rumble Ponies
END:VALARM
DTSTART:20180425T223500Z
DTEND:20180426T013500Z
UID:l-O9VxU3fIUVDEtKhkUk7Z7v@stanza.co
SUMMARY:Fisher Cats @ Rumble Ponies
DESCRIPTION:Fisher Cats @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLn7-2Y\n\nShop: https://stza.co/+vLn7-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Thunder
<2018-04-27 Fri 17:35-20:35>
:PROPERTIES:
:ID:       IjYTbI8rY-yJwAJODXj0iswR@stanza.co
:LOCATION: Hood Kids Club Game
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Thunder Hood Kids Club Members will get an exclusive tour of Northeast Delta Dental Stadium before the game!

Join us after the game for a spectacular Atlas Fireworks show!

Follow on MiLB First Pitch  https //stza.co/+vLnP-3K

Shop  https //stza.co/+vLnP-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Thunder
END:VALARM
DTSTART:20180427T223500Z
DTEND:20180428T013500Z
UID:IjYTbI8rY-yJwAJODXj0iswR@stanza.co
SUMMARY:Fisher Cats vs. Thunder
DESCRIPTION:Hood Kids Club Members will get an exclusive tour of Northeast Delta Dental Stadium before the game!\n\nJoin us after the game for a spectacular Atlas Fireworks show!\n\nFollow on MiLB First Pitch: https://stza.co/+vLnP-3K\n\nShop: https://stza.co/+vLnP-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Hood Kids Club Game
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Thunder
<2018-04-28 Sat 17:35-20:35>
:PROPERTIES:
:ID:       S6JQZ-vx8_W7KSS5xsitjFDu@stanza.co
:LOCATION: 80's Hits Fireworks
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Thunder Join us after the game for a spectacular 80's Hits Fireworks show courtesy of Atlas Fireworks!

Join us as we recognize participants in the 2018 Reading Challenge, presented by Velcro Companies! Come with crazy hair, or your favorite crazy hat, plus play catch on the field before the game!

Follow on MiLB First Pitch  https //stza.co/+vLnQ-3r

Shop  https //stza.co/+vLnQ-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Thunder
END:VALARM
DTSTART:20180428T223500Z
DTEND:20180429T013500Z
UID:S6JQZ-vx8_W7KSS5xsitjFDu@stanza.co
SUMMARY:Fisher Cats vs. Thunder
DESCRIPTION:Join us after the game for a spectacular 80's Hits Fireworks show courtesy of Atlas Fireworks!\n\nJoin us as we recognize participants in the 2018 Reading Challenge, presented by Velcro Companies! Come with crazy hair, or your favorite crazy hat, plus play catch on the field before the game!\n\nFollow on MiLB First Pitch: https://stza.co/+vLnQ-3r\n\nShop: https://stza.co/+vLnQ-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:80's Hits Fireworks
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Thunder
<2018-04-29 Sun 12:35-15:35>
:PROPERTIES:
:ID:       _v0ZmcVAsvCJrYNesyAznM9c@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Thunder Kids run the bases after every Sunday day game!

Join us as we recognize participants in the 2018 Reading Challenge, presented by Velcro Companies! Come dressed as your favorite Superhero, plus play catch on the field before the game!

Follow on MiLB First Pitch  https //stza.co/+vLnT-3U

Shop  https //stza.co/+vLnT-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Thunder
END:VALARM
DTSTART:20180429T173500Z
DTEND:20180429T203500Z
UID:_v0ZmcVAsvCJrYNesyAznM9c@stanza.co
SUMMARY:Fisher Cats vs. Thunder
DESCRIPTION:Kids run the bases after every Sunday day game!\n\nJoin us as we recognize participants in the 2018 Reading Challenge, presented by Velcro Companies! Come dressed as your favorite Superhero, plus play catch on the field before the game!\n\nFollow on MiLB First Pitch: https://stza.co/+vLnT-3U\n\nShop: https://stza.co/+vLnT-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Fightin Phils
<2018-04-30 Mon 17:35-20:35>
:PROPERTIES:
:ID:       1VNM69LoYmXCDB3R3iIQPWVd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Fightin Phils Fisher Cats vs. Fightin Phils

Follow on MiLB First Pitch  https //stza.co/+vLnV-2r

Shop  https //stza.co/+vLnV-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Fightin Phils
END:VALARM
DTSTART:20180430T223500Z
DTEND:20180501T013500Z
UID:1VNM69LoYmXCDB3R3iIQPWVd@stanza.co
SUMMARY:Fisher Cats vs. Fightin Phils
DESCRIPTION:Fisher Cats vs. Fightin Phils\n\nFollow on MiLB First Pitch: https://stza.co/+vLnV-2r\n\nShop: https://stza.co/+vLnV-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Fightin Phils
<2018-05-01 Tue 17:35-20:35>
:PROPERTIES:
:ID:       BUcYEgIn8yGDXdGMWCuG3Awd@stanza.co
:LOCATION: Tall Boy Tuesdays
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Fightin Phils $5 Miller, Coors, & Twisted Tea - 24oz - in the Brewhouse & Tiki Bar.  Available until First Pitch.

Follow on MiLB First Pitch  https //stza.co/+vLnX-3q

Shop  https //stza.co/+vLnX-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Fightin Phils
END:VALARM
DTSTART:20180501T223500Z
DTEND:20180502T013500Z
UID:BUcYEgIn8yGDXdGMWCuG3Awd@stanza.co
SUMMARY:Fisher Cats vs. Fightin Phils
DESCRIPTION:$5 Miller, Coors, & Twisted Tea - 24oz - in the Brewhouse & Tiki Bar.  Available until First Pitch.\n\nFollow on MiLB First Pitch: https://stza.co/+vLnX-3q\n\nShop: https://stza.co/+vLnX-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Tall Boy Tuesdays
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Fightin Phils
<2018-05-02 Wed 09:35-12:35>
:PROPERTIES:
:ID:       jqCJFaX8DyG8mhieSxsd6eO6@stanza.co
:LOCATION: Educational Day
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Fightin Phils Students from around New Hampshire join us for a day of educational fun, with special games & entertainment, all in the name of learning!

Follow on MiLB First Pitch  https //stza.co/+vLnY-1B

Shop  https //stza.co/+vLnY-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Fightin Phils
END:VALARM
DTSTART:20180502T143500Z
DTEND:20180502T173500Z
UID:jqCJFaX8DyG8mhieSxsd6eO6@stanza.co
SUMMARY:Fisher Cats vs. Fightin Phils
DESCRIPTION:Students from around New Hampshire join us for a day of educational fun, with special games & entertainment, all in the name of learning!\n\nFollow on MiLB First Pitch: https://stza.co/+vLnY-1B\n\nShop: https://stza.co/+vLnY-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Educational Day
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Rumble Ponies
<2018-05-03 Thu 17:35-20:35>
:PROPERTIES:
:ID:       WCaqhcCfQhhdkOEjdsetsiXo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Rumble Ponies Fisher Cats @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLn8-8

Shop  https //stza.co/+vLn8-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Rumble Ponies
END:VALARM
DTSTART:20180503T223500Z
DTEND:20180504T013500Z
UID:WCaqhcCfQhhdkOEjdsetsiXo@stanza.co
SUMMARY:Fisher Cats @ Rumble Ponies
DESCRIPTION:Fisher Cats @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLn8-8\n\nShop: https://stza.co/+vLn8-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Rumble Ponies
<2018-05-04 Fri 18:05-21:05>
:PROPERTIES:
:ID:       S_WKFi82eSBLiOyV1WKptupV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Rumble Ponies Fisher Cats @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLn9-3o

Shop  https //stza.co/+vLn9-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Rumble Ponies
END:VALARM
DTSTART:20180504T230500Z
DTEND:20180505T020500Z
UID:S_WKFi82eSBLiOyV1WKptupV@stanza.co
SUMMARY:Fisher Cats @ Rumble Ponies
DESCRIPTION:Fisher Cats @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLn9-3o\n\nShop: https://stza.co/+vLn9-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Rumble Ponies
<2018-05-05 Sat 14:05-17:05>
:PROPERTIES:
:ID:       m7xQM13QzUhXSu8wv1m_a-QF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Rumble Ponies Fisher Cats @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLna-1y

Shop  https //stza.co/+vLna-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Rumble Ponies
END:VALARM
DTSTART:20180505T190500Z
DTEND:20180505T220500Z
UID:m7xQM13QzUhXSu8wv1m_a-QF@stanza.co
SUMMARY:Fisher Cats @ Rumble Ponies
DESCRIPTION:Fisher Cats @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLna-1y\n\nShop: https://stza.co/+vLna-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Rumble Ponies
<2018-05-06 Sun 13:05-16:05>
:PROPERTIES:
:ID:       OQxI5KUhheMk2EH5KjcxjA2j@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Rumble Ponies Fisher Cats @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLnb-3m

Shop  https //stza.co/+vLnb-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Rumble Ponies
END:VALARM
DTSTART:20180506T180500Z
DTEND:20180506T210500Z
UID:OQxI5KUhheMk2EH5KjcxjA2j@stanza.co
SUMMARY:Fisher Cats @ Rumble Ponies
DESCRIPTION:Fisher Cats @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLnb-3m\n\nShop: https://stza.co/+vLnb-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Sea Dogs
<2018-05-07 Mon 17:35-20:35>
:PROPERTIES:
:ID:       YtKWgrDaW4hPoM5TKLIiuynk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Sea Dogs Fisher Cats vs. Sea Dogs

Follow on MiLB First Pitch  https //stza.co/+vLn$-1S

Shop  https //stza.co/+vLn$-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Sea Dogs
END:VALARM
DTSTART:20180507T223500Z
DTEND:20180508T013500Z
UID:YtKWgrDaW4hPoM5TKLIiuynk@stanza.co
SUMMARY:Fisher Cats vs. Sea Dogs
DESCRIPTION:Fisher Cats vs. Sea Dogs\n\nFollow on MiLB First Pitch: https://stza.co/+vLn$-1S\n\nShop: https://stza.co/+vLn$-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Sea Dogs
<2018-05-08 Tue 17:35-20:35>
:PROPERTIES:
:ID:       WNqtQhbtDn5xXs6kHQ_qlILL@stanza.co
:LOCATION: Tall Boy Tuesdays
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Sea Dogs $5 Miller, Coors, & Twisted Tea - 24oz - in the Brewhouse & Tiki Bar.  Available until First Pitch.

Follow on MiLB First Pitch  https //stza.co/+vLo1-3x

Shop  https //stza.co/+vLo1-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Sea Dogs
END:VALARM
DTSTART:20180508T223500Z
DTEND:20180509T013500Z
UID:WNqtQhbtDn5xXs6kHQ_qlILL@stanza.co
SUMMARY:Fisher Cats vs. Sea Dogs
DESCRIPTION:$5 Miller, Coors, & Twisted Tea - 24oz - in the Brewhouse & Tiki Bar.  Available until First Pitch.\n\nFollow on MiLB First Pitch: https://stza.co/+vLo1-3x\n\nShop: https://stza.co/+vLo1-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Tall Boy Tuesdays
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Sea Dogs
<2018-05-09 Wed 17:35-20:35>
:PROPERTIES:
:ID:       lkt5UC-2ee94OhRbCOEvZIph@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Sea Dogs Fisher Cats vs. Sea Dogs

Follow on MiLB First Pitch  https //stza.co/+vLo2-

Shop  https //stza.co/+vLo2-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Sea Dogs
END:VALARM
DTSTART:20180509T223500Z
DTEND:20180510T013500Z
UID:lkt5UC-2ee94OhRbCOEvZIph@stanza.co
SUMMARY:Fisher Cats vs. Sea Dogs
DESCRIPTION:Fisher Cats vs. Sea Dogs\n\nFollow on MiLB First Pitch: https://stza.co/+vLo2-\n\nShop: https://stza.co/+vLo2-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Senators
<2018-05-10 Thu 18:00-21:00>
:PROPERTIES:
:ID:       Zls_Y5yZfTbgOuotdnGdbqNv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Senators Fisher Cats @ Senators

Follow on MiLB First Pitch  https //stza.co/+vLnl-2X

Shop  https //stza.co/+vLnl-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Senators
END:VALARM
DTSTART:20180510T230000Z
DTEND:20180511T020000Z
UID:Zls_Y5yZfTbgOuotdnGdbqNv@stanza.co
SUMMARY:Fisher Cats @ Senators
DESCRIPTION:Fisher Cats @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLnl-2X\n\nShop: https://stza.co/+vLnl-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Senators
<2018-05-11 Fri 18:00-21:00>
:PROPERTIES:
:ID:       -CA6EtLgJM_jH7oIvBxpYpcr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Senators Fisher Cats @ Senators

Follow on MiLB First Pitch  https //stza.co/+vLnm-1Z

Shop  https //stza.co/+vLnm-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Senators
END:VALARM
DTSTART:20180511T230000Z
DTEND:20180512T020000Z
UID:-CA6EtLgJM_jH7oIvBxpYpcr@stanza.co
SUMMARY:Fisher Cats @ Senators
DESCRIPTION:Fisher Cats @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLnm-1Z\n\nShop: https://stza.co/+vLnm-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Senators
<2018-05-12 Sat 17:00-20:00>
:PROPERTIES:
:ID:       J3kVXcbHKWXACJxljSak8MgB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Senators Fisher Cats @ Senators

Follow on MiLB First Pitch  https //stza.co/+vLnn-3T

Shop  https //stza.co/+vLnn-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Senators
END:VALARM
DTSTART:20180512T220000Z
DTEND:20180513T010000Z
UID:J3kVXcbHKWXACJxljSak8MgB@stanza.co
SUMMARY:Fisher Cats @ Senators
DESCRIPTION:Fisher Cats @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLnn-3T\n\nShop: https://stza.co/+vLnn-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Senators
<2018-05-13 Sun 12:30-15:30>
:PROPERTIES:
:ID:       38a-Fb-cI6ktZKZuJUULtVmi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Senators Fisher Cats @ Senators

Follow on MiLB First Pitch  https //stza.co/+vLno-3l

Shop  https //stza.co/+vLno-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Senators
END:VALARM
DTSTART:20180513T173000Z
DTEND:20180513T203000Z
UID:38a-Fb-cI6ktZKZuJUULtVmi@stanza.co
SUMMARY:Fisher Cats @ Senators
DESCRIPTION:Fisher Cats @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLno-3l\n\nShop: https://stza.co/+vLno-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Yard Goats
<2018-05-14 Mon 18:05-21:05>
:PROPERTIES:
:ID:       2ANJuwqOKL82hloalRXqaQQU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Yard Goats Fisher Cats @ Yard Goats

Buy tickets here  https //stza.co/~vLnt

Follow on MiLB First Pitch  https //stza.co/+vLnt-u

Shop  https //stza.co/+vLnt-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Yard Goats
END:VALARM
DTSTART:20180514T230500Z
DTEND:20180515T020500Z
UID:2ANJuwqOKL82hloalRXqaQQU@stanza.co
SUMMARY:Fisher Cats @ Yard Goats
DESCRIPTION:Fisher Cats @ Yard Goats\n\nBuy tickets here: https://stza.co/~vLnt\n\nFollow on MiLB First Pitch: https://stza.co/+vLnt-u\n\nShop: https://stza.co/+vLnt-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Yard Goats
<2018-05-15 Tue 18:05-21:05>
:PROPERTIES:
:ID:       Uwfy41o5M0nVPGDtOwKlOdtD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Yard Goats Fisher Cats @ Yard Goats

Buy tickets here  https //stza.co/~vLnu

Follow on MiLB First Pitch  https //stza.co/+vLnu-28

Shop  https //stza.co/+vLnu-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Yard Goats
END:VALARM
DTSTART:20180515T230500Z
DTEND:20180516T020500Z
UID:Uwfy41o5M0nVPGDtOwKlOdtD@stanza.co
SUMMARY:Fisher Cats @ Yard Goats
DESCRIPTION:Fisher Cats @ Yard Goats\n\nBuy tickets here: https://stza.co/~vLnu\n\nFollow on MiLB First Pitch: https://stza.co/+vLnu-28\n\nShop: https://stza.co/+vLnu-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Yard Goats
<2018-05-16 Wed 09:35-12:35>
:PROPERTIES:
:ID:       tIj-YOCUP1d8YFtgxFJn5QkE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Yard Goats Fisher Cats @ Yard Goats

Buy tickets here  https //stza.co/~vLnv

Follow on MiLB First Pitch  https //stza.co/+vLnv-o

Shop  https //stza.co/+vLnv-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Yard Goats
END:VALARM
DTSTART:20180516T143500Z
DTEND:20180516T173500Z
UID:tIj-YOCUP1d8YFtgxFJn5QkE@stanza.co
SUMMARY:Fisher Cats @ Yard Goats
DESCRIPTION:Fisher Cats @ Yard Goats\n\nBuy tickets here: https://stza.co/~vLnv\n\nFollow on MiLB First Pitch: https://stza.co/+vLnv-o\n\nShop: https://stza.co/+vLnv-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Rumble Ponies
<2018-05-17 Thu 17:35-20:35>
:PROPERTIES:
:ID:       a7JSVJwq_iH4jedQ5rf6CWCk@stanza.co
:LOCATION: Thirsty Thursdays
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Rumble Ponies $3 Domestics and $4 Import drafts - 12oz - from the 1st & 3rd Base Concession Stands.

Follow on MiLB First Pitch  https //stza.co/+vLo5-6

Shop  https //stza.co/+vLo5-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Rumble Ponies
END:VALARM
DTSTART:20180517T223500Z
DTEND:20180518T013500Z
UID:a7JSVJwq_iH4jedQ5rf6CWCk@stanza.co
SUMMARY:Fisher Cats vs. Rumble Ponies
DESCRIPTION:$3 Domestics and $4 Import drafts - 12oz - from the 1st & 3rd Base Concession Stands.\n\nFollow on MiLB First Pitch: https://stza.co/+vLo5-6\n\nShop: https://stza.co/+vLo5-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursdays
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Rumble Ponies
<2018-05-18 Fri 17:35-20:35>
:PROPERTIES:
:ID:       4uKpQSd9mnWId8oNfNcEIoHP@stanza.co
:LOCATION: Post-Game Atlas Fireworks
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Rumble Ponies Join us after the game for a spectacular Atlas Fireworks show!

Bring the whole troop and sleep on the field after the game! Each scout will receive a special Fisher Cats patch for attending the game, and can enjoy a movie on the video board after the final out. Pre-registration required. 

Follow on MiLB First Pitch  https //stza.co/+vLo6-3_

Shop  https //stza.co/+vLo6-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Rumble Ponies
END:VALARM
DTSTART:20180518T223500Z
DTEND:20180519T013500Z
UID:4uKpQSd9mnWId8oNfNcEIoHP@stanza.co
SUMMARY:Fisher Cats vs. Rumble Ponies
DESCRIPTION:Join us after the game for a spectacular Atlas Fireworks show!\n\nBring the whole troop and sleep on the field after the game! Each scout will receive a special Fisher Cats patch for attending the game, and can enjoy a movie on the video board after the final out. Pre-registration required. \n\nFollow on MiLB First Pitch: https://stza.co/+vLo6-3_\n\nShop: https://stza.co/+vLo6-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Post-Game Atlas Fireworks
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Rumble Ponies
<2018-05-19 Sat 17:35-20:35>
:PROPERTIES:
:ID:       s4vNziz0YfhzSEZ8PKEnKc-6@stanza.co
:LOCATION: Rolling Stones Fireworks
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Rumble Ponies Join us after the game for a spectacular Rolling Stones Fireworks show courtesy of Atlas Fireworks!



Follow on MiLB First Pitch  https //stza.co/+vLo9-2l

Shop  https //stza.co/+vLo9-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Rumble Ponies
END:VALARM
DTSTART:20180519T223500Z
DTEND:20180520T013500Z
UID:s4vNziz0YfhzSEZ8PKEnKc-6@stanza.co
SUMMARY:Fisher Cats vs. Rumble Ponies
DESCRIPTION:Join us after the game for a spectacular Rolling Stones Fireworks show courtesy of Atlas Fireworks!\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+vLo9-2l\n\nShop: https://stza.co/+vLo9-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Rolling Stones Fireworks
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Rumble Ponies
<2018-05-20 Sun 12:35-15:35>
:PROPERTIES:
:ID:       5pw0sQmR5XEAKQZidKQ-DACC@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Rumble Ponies The awesome morning begins at 11 30 a.m. and includes unlimited pancakes with oodles of toppings, breakfast sausage links, scrambled eggs, fruit salad and breakfast beverages. Take photos with and receive table visits from princesses, superheroes, and more! Participate in a sing-a-long before the game, but most importantly-start your day with smiles and family memories that will last a lifetime. Tickets for this event are limited and available in Fisher Cats Online Team Store.

Kids run the bases after every Sunday day game!

Hood Kid's Club Members will get to join the Fisher Cats on-field for the National Anthem!

Follow on MiLB First Pitch  https //stza.co/+vLob-1Q

Shop  https //stza.co/+vLob-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Rumble Ponies
END:VALARM
DTSTART:20180520T173500Z
DTEND:20180520T203500Z
UID:5pw0sQmR5XEAKQZidKQ-DACC@stanza.co
SUMMARY:Fisher Cats vs. Rumble Ponies
DESCRIPTION:The awesome morning begins at 11:30 a.m. and includes unlimited pancakes with oodles of toppings, breakfast sausage links, scrambled eggs, fruit salad and breakfast beverages. Take photos with and receive table visits from princesses, superheroes, and more! Participate in a sing-a-long before the game, but most importantly-start your day with smiles and family memories that will last a lifetime. Tickets for this event are limited and available in Fisher Cats Online Team Store.\n\nKids run the bases after every Sunday day game!\n\nHood Kid's Club Members will get to join the Fisher Cats on-field for the National Anthem!\n\nFollow on MiLB First Pitch: https://stza.co/+vLob-1Q\n\nShop: https://stza.co/+vLob-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Fightin Phils
<2018-05-22 Tue 17:35-20:35>
:PROPERTIES:
:ID:       3sJUpoaxrdNpwB09vMg_XU58@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Fightin Phils Fisher Cats @ Fightin Phils

Buy tickets here  https //stza.co/~vLpZ

Follow on MiLB First Pitch  https //stza.co/+vLpZ-3J

Shop  https //stza.co/+vLpZ-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Fightin Phils
END:VALARM
DTSTART:20180522T223500Z
DTEND:20180523T013500Z
UID:3sJUpoaxrdNpwB09vMg_XU58@stanza.co
SUMMARY:Fisher Cats @ Fightin Phils
DESCRIPTION:Fisher Cats @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vLpZ\n\nFollow on MiLB First Pitch: https://stza.co/+vLpZ-3J\n\nShop: https://stza.co/+vLpZ-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Fightin Phils
<2018-05-23 Wed 17:35-20:35>
:PROPERTIES:
:ID:       OBWZUn38YOF-7ltA305xTJoZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Fightin Phils Fisher Cats @ Fightin Phils

Buy tickets here  https //stza.co/~v9SS

Follow on MiLB First Pitch  https //stza.co/+v9SS-2_

Shop  https //stza.co/+v9SS-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Fightin Phils
END:VALARM
DTSTART:20180523T223500Z
DTEND:20180524T013500Z
UID:OBWZUn38YOF-7ltA305xTJoZ@stanza.co
SUMMARY:Fisher Cats @ Fightin Phils
DESCRIPTION:Fisher Cats @ Fightin Phils\n\nBuy tickets here: https://stza.co/~v9SS\n\nFollow on MiLB First Pitch: https://stza.co/+v9SS-2_\n\nShop: https://stza.co/+v9SS-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Fightin Phils
<2018-05-24 Thu 10:35-13:35>
:PROPERTIES:
:ID:       Ka2XIE3KMGNJkW3eNiKmPKvO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Fightin Phils Fisher Cats @ Fightin Phils

Buy tickets here  https //stza.co/~v9ST

Follow on MiLB First Pitch  https //stza.co/+v9ST-3O

Shop  https //stza.co/+v9ST-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Fightin Phils
END:VALARM
DTSTART:20180524T153500Z
DTEND:20180524T183500Z
UID:Ka2XIE3KMGNJkW3eNiKmPKvO@stanza.co
SUMMARY:Fisher Cats @ Fightin Phils
DESCRIPTION:Fisher Cats @ Fightin Phils\n\nBuy tickets here: https://stza.co/~v9ST\n\nFollow on MiLB First Pitch: https://stza.co/+v9ST-3O\n\nShop: https://stza.co/+v9ST-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Yard Goats
<2018-05-25 Fri 17:35-20:35>
:PROPERTIES:
:ID:       ZMeC6-JyB-ZDYWMmOMrjDSfr@stanza.co
:LOCATION: Post-Game Atlas Fireworks
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Yard Goats Join us after the game for a spectacular Atlas Fireworks show!

Follow on MiLB First Pitch  https //stza.co/+vLod-1H

Shop  https //stza.co/+vLod-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Yard Goats
END:VALARM
DTSTART:20180525T223500Z
DTEND:20180526T013500Z
UID:ZMeC6-JyB-ZDYWMmOMrjDSfr@stanza.co
SUMMARY:Fisher Cats vs. Yard Goats
DESCRIPTION:Join us after the game for a spectacular Atlas Fireworks show!\n\nFollow on MiLB First Pitch: https://stza.co/+vLod-1H\n\nShop: https://stza.co/+vLod-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Post-Game Atlas Fireworks
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Yard Goats
<2018-05-26 Sat 17:35-20:35>
:PROPERTIES:
:ID:       u8E8SbrwiDgbuEfcslG_Dw5A@stanza.co
:LOCATION: Nickelodeon Night featuring the Teenage Mutant Ninja Turtles
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Yard Goats 

Join us after the game for a spectacular 90's Hits Fireworks show!

Follow on MiLB First Pitch  https //stza.co/+vLof-2

Shop  https //stza.co/+vLof-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Yard Goats
END:VALARM
DTSTART:20180526T223500Z
DTEND:20180527T013500Z
UID:u8E8SbrwiDgbuEfcslG_Dw5A@stanza.co
SUMMARY:Fisher Cats vs. Yard Goats
DESCRIPTION:\n\nJoin us after the game for a spectacular 90's Hits Fireworks show!\n\nFollow on MiLB First Pitch: https://stza.co/+vLof-2\n\nShop: https://stza.co/+vLof-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Nickelodeon Night featuring the Teenage Mutant Ninja Turtles
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Yard Goats
<2018-05-27 Sun 12:35-15:35>
:PROPERTIES:
:ID:       KyyQ0KhAELwgHiC2i945Y_go@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Yard Goats Kids run the bases after every Sunday day game!

Join us as we recognize participants in the 2018 Reading Challenge, presented by Velcro Companies! Come  dressed in Red, White and Blue as we celebrate the USA, plus play catch on the field before the game!

Follow on MiLB First Pitch  https //stza.co/+vLoh-L

Shop  https //stza.co/+vLoh-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Yard Goats
END:VALARM
DTSTART:20180527T173500Z
DTEND:20180527T203500Z
UID:KyyQ0KhAELwgHiC2i945Y_go@stanza.co
SUMMARY:Fisher Cats vs. Yard Goats
DESCRIPTION:Kids run the bases after every Sunday day game!\n\nJoin us as we recognize participants in the 2018 Reading Challenge, presented by Velcro Companies! Come  dressed in Red, White and Blue as we celebrate the USA, plus play catch on the field before the game!\n\nFollow on MiLB First Pitch: https://stza.co/+vLoh-L\n\nShop: https://stza.co/+vLoh-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Yard Goats
<2018-05-28 Mon 12:35-15:35>
:PROPERTIES:
:ID:       UxELiwbQGElvpGM73tYqCTSF@stanza.co
:LOCATION: Memorial Day Welcome Home Event
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Yard Goats Join us as we celebrate America and welcome home those who served to protect it on Memorial Day.

Follow on MiLB First Pitch  https //stza.co/+vLoj-3h

Shop  https //stza.co/+vLoj-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Yard Goats
END:VALARM
DTSTART:20180528T173500Z
DTEND:20180528T203500Z
UID:UxELiwbQGElvpGM73tYqCTSF@stanza.co
SUMMARY:Fisher Cats vs. Yard Goats
DESCRIPTION:Join us as we celebrate America and welcome home those who served to protect it on Memorial Day.\n\nFollow on MiLB First Pitch: https://stza.co/+vLoj-3h\n\nShop: https://stza.co/+vLoj-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Memorial Day Welcome Home Event
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Sea Dogs
<2018-05-29 Tue 17:35-20:35>
:PROPERTIES:
:ID:       WrTL4YaCshL4nyYrpen5xMlr@stanza.co
:LOCATION: Tall Boy Tuesdays
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Sea Dogs $5 Miller, Coors, & Twisted Tea - 24oz - in the Brewhouse & Tiki Bar.  Available until First Pitch.

Follow on MiLB First Pitch  https //stza.co/+vLok-3_

Shop  https //stza.co/+vLok-2S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Sea Dogs
END:VALARM
DTSTART:20180529T223500Z
DTEND:20180530T013500Z
UID:WrTL4YaCshL4nyYrpen5xMlr@stanza.co
SUMMARY:Fisher Cats vs. Sea Dogs
DESCRIPTION:$5 Miller, Coors, & Twisted Tea - 24oz - in the Brewhouse & Tiki Bar.  Available until First Pitch.\n\nFollow on MiLB First Pitch: https://stza.co/+vLok-3_\n\nShop: https://stza.co/+vLok-2S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Tall Boy Tuesdays
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Sea Dogs
<2018-05-30 Wed 17:35-20:35>
:PROPERTIES:
:ID:       KAaEfsaFDkd9rOFiMJngPuk_@stanza.co
:LOCATION: Uncle Sam Hat Giveaway
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Sea Dogs The first 1,000 fans will receive an Uncle Sam Hat!

Follow on MiLB First Pitch  https //stza.co/+vLom-1i

Shop  https //stza.co/+vLom-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Sea Dogs
END:VALARM
DTSTART:20180530T223500Z
DTEND:20180531T013500Z
UID:KAaEfsaFDkd9rOFiMJngPuk_@stanza.co
SUMMARY:Fisher Cats vs. Sea Dogs
DESCRIPTION:The first 1,000 fans will receive an Uncle Sam Hat!\n\nFollow on MiLB First Pitch: https://stza.co/+vLom-1i\n\nShop: https://stza.co/+vLom-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Uncle Sam Hat Giveaway
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Sea Dogs
<2018-05-31 Thu 10:35-13:35>
:PROPERTIES:
:ID:       SrNHbLTp6jyDBTsnFVfZRP0L@stanza.co
:LOCATION: NH Scholars Day
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Sea Dogs The Fisher Cats and the NH College & University Council honors New Hampshire's Scholars at the ballpark. Join us during a pre-game ceremony to recognize these outstanding high school students.

Follow on MiLB First Pitch  https //stza.co/+vLoo-1t

Shop  https //stza.co/+vLoo-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Sea Dogs
END:VALARM
DTSTART:20180531T153500Z
DTEND:20180531T183500Z
UID:SrNHbLTp6jyDBTsnFVfZRP0L@stanza.co
SUMMARY:Fisher Cats vs. Sea Dogs
DESCRIPTION:The Fisher Cats and the NH College & University Council honors New Hampshire's Scholars at the ballpark. Join us during a pre-game ceremony to recognize these outstanding high school students.\n\nFollow on MiLB First Pitch: https://stza.co/+vLoo-1t\n\nShop: https://stza.co/+vLoo-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:NH Scholars Day
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Rumble Ponies
<2018-06-01 Fri 18:05-21:05>
:PROPERTIES:
:ID:       EY2Asx9I4OHeimXDXYz-0-mT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Rumble Ponies Fisher Cats @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLnc-3Y

Shop  https //stza.co/+vLnc-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Rumble Ponies
END:VALARM
DTSTART:20180601T230500Z
DTEND:20180602T020500Z
UID:EY2Asx9I4OHeimXDXYz-0-mT@stanza.co
SUMMARY:Fisher Cats @ Rumble Ponies
DESCRIPTION:Fisher Cats @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLnc-3Y\n\nShop: https://stza.co/+vLnc-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Rumble Ponies
<2018-06-02 Sat 17:05-20:05>
:PROPERTIES:
:ID:       e_TpYD8gzwGatDTSahDuBdSB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Rumble Ponies Fisher Cats @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLnd-3F

Shop  https //stza.co/+vLnd-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Rumble Ponies
END:VALARM
DTSTART:20180602T220500Z
DTEND:20180603T010500Z
UID:e_TpYD8gzwGatDTSahDuBdSB@stanza.co
SUMMARY:Fisher Cats @ Rumble Ponies
DESCRIPTION:Fisher Cats @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLnd-3F\n\nShop: https://stza.co/+vLnd-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Rumble Ponies
<2018-06-03 Sun 13:05-16:05>
:PROPERTIES:
:ID:       NWpdmDXJDl_SrmXurqLphtNk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Rumble Ponies Fisher Cats @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLne-2L

Shop  https //stza.co/+vLne-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Rumble Ponies
END:VALARM
DTSTART:20180603T180500Z
DTEND:20180603T210500Z
UID:NWpdmDXJDl_SrmXurqLphtNk@stanza.co
SUMMARY:Fisher Cats @ Rumble Ponies
DESCRIPTION:Fisher Cats @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLne-2L\n\nShop: https://stza.co/+vLne-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. RubberDucks
<2018-06-05 Tue 17:35-20:35>
:PROPERTIES:
:ID:       WMbNP0KAWTxShBwr6NbFCLWk@stanza.co
:LOCATION: Reading Challenge Night
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. RubberDucks Join us as we recognize participants in the 2018 Reading Challenge, presented by Velcro Companies! Come dressed in your future career's attire, plus play catch on the field before the game!

$5 Miller, Coors, & Twisted Tea - 24oz - in the Brewhouse & Tiki Bar.  Available until First Pitch.

Follow on MiLB First Pitch  https //stza.co/+vLoq-N

Shop  https //stza.co/+vLoq-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. RubberDucks
END:VALARM
DTSTART:20180605T223500Z
DTEND:20180606T013500Z
UID:WMbNP0KAWTxShBwr6NbFCLWk@stanza.co
SUMMARY:Fisher Cats vs. RubberDucks
DESCRIPTION:Join us as we recognize participants in the 2018 Reading Challenge, presented by Velcro Companies! Come dressed in your future career's attire, plus play catch on the field before the game!\n\n$5 Miller, Coors, & Twisted Tea - 24oz - in the Brewhouse & Tiki Bar.  Available until First Pitch.\n\nFollow on MiLB First Pitch: https://stza.co/+vLoq-N\n\nShop: https://stza.co/+vLoq-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Reading Challenge Night
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. RubberDucks
<2018-06-06 Wed 09:35-12:35>
:PROPERTIES:
:ID:       X4-Ed-J5GGWIB8dNUlLfN7aG@stanza.co
:LOCATION: Educational Day
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. RubberDucks Students from around New Hampshire join us for a day of educational fun, with special games & entertainment, all in the name of learning!

Follow on MiLB First Pitch  https //stza.co/+vLos-j

Shop  https //stza.co/+vLos-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. RubberDucks
END:VALARM
DTSTART:20180606T143500Z
DTEND:20180606T173500Z
UID:X4-Ed-J5GGWIB8dNUlLfN7aG@stanza.co
SUMMARY:Fisher Cats vs. RubberDucks
DESCRIPTION:Students from around New Hampshire join us for a day of educational fun, with special games & entertainment, all in the name of learning!\n\nFollow on MiLB First Pitch: https://stza.co/+vLos-j\n\nShop: https://stza.co/+vLos-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Educational Day
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. RubberDucks
<2018-06-07 Thu 17:35-20:35>
:PROPERTIES:
:ID:       Ht6RzSQVBqV2H7mZfqJX1P13@stanza.co
:LOCATION: Pennant Banner Giveaway
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. RubberDucks The first 1,000 fans will receive a Pennant Banner commemorating our 15th Anniversary Season!

$3 Domestics and $4 Import drafts - 12oz - from the 1st & 3rd Base Concession Stands.

Follow on MiLB First Pitch  https //stza.co/+vLov-3d

Shop  https //stza.co/+vLov-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. RubberDucks
END:VALARM
DTSTART:20180607T223500Z
DTEND:20180608T013500Z
UID:Ht6RzSQVBqV2H7mZfqJX1P13@stanza.co
SUMMARY:Fisher Cats vs. RubberDucks
DESCRIPTION:The first 1,000 fans will receive a Pennant Banner commemorating our 15th Anniversary Season!\n\n$3 Domestics and $4 Import drafts - 12oz - from the 1st & 3rd Base Concession Stands.\n\nFollow on MiLB First Pitch: https://stza.co/+vLov-3d\n\nShop: https://stza.co/+vLov-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Pennant Banner Giveaway
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Baysox
<2018-06-08 Fri 17:35-20:35>
:PROPERTIES:
:ID:       xUB3wIVhnjXj5ZlpJiNUkkOz@stanza.co
:LOCATION: Manchester Community College Night
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Baysox 

Join us after the game for a spectacular Atlas Fireworks show!

Attention all Girl Scouts!  Join us for a night of baseball fun, as we celebrate the scouts.  Stick around post-game, as we are allowing Girl Scouts to spend the night on the field!

Follow on MiLB First Pitch  https //stza.co/+vLow-3B

Shop  https //stza.co/+vLow-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Baysox
END:VALARM
DTSTART:20180608T223500Z
DTEND:20180609T013500Z
UID:xUB3wIVhnjXj5ZlpJiNUkkOz@stanza.co
SUMMARY:Fisher Cats vs. Baysox
DESCRIPTION:\n\nJoin us after the game for a spectacular Atlas Fireworks show!\n\nAttention all Girl Scouts!  Join us for a night of baseball fun, as we celebrate the scouts.  Stick around post-game, as we are allowing Girl Scouts to spend the night on the field!\n\nFollow on MiLB First Pitch: https://stza.co/+vLow-3B\n\nShop: https://stza.co/+vLow-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Manchester Community College Night
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Baysox
<2018-06-09 Sat 17:35-20:35>
:PROPERTIES:
:ID:       NzhLp139JFSOp0_VK-eyb4oN@stanza.co
:LOCATION: Beach Boys Fireworks
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Baysox Join us after the game for a spectacular Beach Boys Fireworks show courtesy of Atlas Fireworks!



Follow on MiLB First Pitch  https //stza.co/+vLoz-1p

Shop  https //stza.co/+vLoz-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Baysox
END:VALARM
DTSTART:20180609T223500Z
DTEND:20180610T013500Z
UID:NzhLp139JFSOp0_VK-eyb4oN@stanza.co
SUMMARY:Fisher Cats vs. Baysox
DESCRIPTION:Join us after the game for a spectacular Beach Boys Fireworks show courtesy of Atlas Fireworks!\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+vLoz-1p\n\nShop: https://stza.co/+vLoz-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Beach Boys Fireworks
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Baysox
<2018-06-10 Sun 12:35-15:35>
:PROPERTIES:
:ID:       XUBPpllnCKstINZ7NlZtT1AT@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Baysox The first 2,500 fans will receive a Fisher Cats Poster courtesy of Spectrum Marketing!

Kids run the bases after every Sunday day game!

Follow on MiLB First Pitch  https //stza.co/+vLoA-3C

Shop  https //stza.co/+vLoA-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Baysox
END:VALARM
DTSTART:20180610T173500Z
DTEND:20180610T203500Z
UID:XUBPpllnCKstINZ7NlZtT1AT@stanza.co
SUMMARY:Fisher Cats vs. Baysox
DESCRIPTION:The first 2,500 fans will receive a Fisher Cats Poster courtesy of Spectrum Marketing!\n\nKids run the bases after every Sunday day game!\n\nFollow on MiLB First Pitch: https://stza.co/+vLoA-3C\n\nShop: https://stza.co/+vLoA-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ RubberDucks
<2018-06-12 Tue 18:05-21:05>
:PROPERTIES:
:ID:       jA6YgZ4uZ1ihTOdJ8GMgHzsH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ RubberDucks Fisher Cats @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLm$-1a

Shop  https //stza.co/+vLm$-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ RubberDucks
END:VALARM
DTSTART:20180612T230500Z
DTEND:20180613T020500Z
UID:jA6YgZ4uZ1ihTOdJ8GMgHzsH@stanza.co
SUMMARY:Fisher Cats @ RubberDucks
DESCRIPTION:Fisher Cats @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLm$-1a\n\nShop: https://stza.co/+vLm$-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ RubberDucks
<2018-06-13 Wed 18:05-21:05>
:PROPERTIES:
:ID:       O_C_N5UB1bd7Ogpn2V8INEz6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ RubberDucks Fisher Cats @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLn0-2a

Shop  https //stza.co/+vLn0-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ RubberDucks
END:VALARM
DTSTART:20180613T230500Z
DTEND:20180614T020500Z
UID:O_C_N5UB1bd7Ogpn2V8INEz6@stanza.co
SUMMARY:Fisher Cats @ RubberDucks
DESCRIPTION:Fisher Cats @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLn0-2a\n\nShop: https://stza.co/+vLn0-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ RubberDucks
<2018-06-14 Thu 18:05-21:05>
:PROPERTIES:
:ID:       38wW4aqrEQRmWatKvjkCVCsJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ RubberDucks Fisher Cats @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLn1-1s

Shop  https //stza.co/+vLn1-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ RubberDucks
END:VALARM
DTSTART:20180614T230500Z
DTEND:20180615T020500Z
UID:38wW4aqrEQRmWatKvjkCVCsJ@stanza.co
SUMMARY:Fisher Cats @ RubberDucks
DESCRIPTION:Fisher Cats @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLn1-1s\n\nShop: https://stza.co/+vLn1-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Curve
<2018-06-15 Fri 18:00-21:00>
:PROPERTIES:
:ID:       ixuv86UyQTRK79ok0xiLHl-Q@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Curve Fisher Cats @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLn2-V

Shop  https //stza.co/+vLn2-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Curve
END:VALARM
DTSTART:20180615T230000Z
DTEND:20180616T020000Z
UID:ixuv86UyQTRK79ok0xiLHl-Q@stanza.co
SUMMARY:Fisher Cats @ Curve
DESCRIPTION:Fisher Cats @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLn2-V\n\nShop: https://stza.co/+vLn2-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Curve
<2018-06-16 Sat 17:00-20:00>
:PROPERTIES:
:ID:       WGOH7ncO80PmKV4poK8CBw0D@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Curve Fisher Cats @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLn3-2V

Shop  https //stza.co/+vLn3-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Curve
END:VALARM
DTSTART:20180616T220000Z
DTEND:20180617T010000Z
UID:WGOH7ncO80PmKV4poK8CBw0D@stanza.co
SUMMARY:Fisher Cats @ Curve
DESCRIPTION:Fisher Cats @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLn3-2V\n\nShop: https://stza.co/+vLn3-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Curve
<2018-06-17 Sun 17:00-20:00>
:PROPERTIES:
:ID:       iQFOUSNIjYoSWi2L9YMRJtNG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Curve Fisher Cats @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLn4-M

Shop  https //stza.co/+vLn4-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Curve
END:VALARM
DTSTART:20180617T220000Z
DTEND:20180618T010000Z
UID:iQFOUSNIjYoSWi2L9YMRJtNG@stanza.co
SUMMARY:Fisher Cats @ Curve
DESCRIPTION:Fisher Cats @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLn4-M\n\nShop: https://stza.co/+vLn4-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ SeaWolves
<2018-06-18 Mon 18:05-21:05>
:PROPERTIES:
:ID:       0rStt_gOdm4ivvbOn-ChRElN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ SeaWolves Fisher Cats @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLni-O

Shop  https //stza.co/+vLni-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ SeaWolves
END:VALARM
DTSTART:20180618T230500Z
DTEND:20180619T020500Z
UID:0rStt_gOdm4ivvbOn-ChRElN@stanza.co
SUMMARY:Fisher Cats @ SeaWolves
DESCRIPTION:Fisher Cats @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLni-O\n\nShop: https://stza.co/+vLni-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ SeaWolves
<2018-06-19 Tue 18:05-21:05>
:PROPERTIES:
:ID:       cJ3S465V-jmB8t-g26md6j3e@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ SeaWolves Fisher Cats @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLnj-7

Shop  https //stza.co/+vLnj-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ SeaWolves
END:VALARM
DTSTART:20180619T230500Z
DTEND:20180620T020500Z
UID:cJ3S465V-jmB8t-g26md6j3e@stanza.co
SUMMARY:Fisher Cats @ SeaWolves
DESCRIPTION:Fisher Cats @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLnj-7\n\nShop: https://stza.co/+vLnj-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ SeaWolves
<2018-06-20 Wed 11:05-14:05>
:PROPERTIES:
:ID:       XmGR2oDVz4dmZsZoQYjgIBy7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ SeaWolves Fisher Cats @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLnk-3Z

Shop  https //stza.co/+vLnk-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ SeaWolves
END:VALARM
DTSTART:20180620T160500Z
DTEND:20180620T190500Z
UID:XmGR2oDVz4dmZsZoQYjgIBy7@stanza.co
SUMMARY:Fisher Cats @ SeaWolves
DESCRIPTION:Fisher Cats @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLnk-3Z\n\nShop: https://stza.co/+vLnk-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Fightin Phils
<2018-06-22 Fri 18:05-21:05>
:PROPERTIES:
:ID:       rNvolo6J4CwUmj6S93mL7D9c@stanza.co
:LOCATION: Post-Game Atlas Fireworks
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Fightin Phils Join us after the game for a spectacular Atlas Fireworks show!

Follow on MiLB First Pitch  https //stza.co/+vLoD-3i

Shop  https //stza.co/+vLoD-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Fightin Phils
END:VALARM
DTSTART:20180622T230500Z
DTEND:20180623T020500Z
UID:rNvolo6J4CwUmj6S93mL7D9c@stanza.co
SUMMARY:Fisher Cats vs. Fightin Phils
DESCRIPTION:Join us after the game for a spectacular Atlas Fireworks show!\n\nFollow on MiLB First Pitch: https://stza.co/+vLoD-3i\n\nShop: https://stza.co/+vLoD-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Post-Game Atlas Fireworks
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Fightin Phils
<2018-06-23 Sat 18:05-21:05>
:PROPERTIES:
:ID:       ya00yDfv9ar5h8QfcwdpMiZ6@stanza.co
:LOCATION: NH Poutine Fest
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Fightin Phils The Fisher Cats have partnered with the Franco-American Centre to host a the NH Poutine Fest.  All fans at the game will be able to purchase poutine from concession areas within Northeast Delta Dental Stadium.

Join us after the game for a spectacular Rush Fireworks show courtesy of Atlas Fireworks!

Follow on MiLB First Pitch  https //stza.co/+vLoE-1R

Shop  https //stza.co/+vLoE-3_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Fightin Phils
END:VALARM
DTSTART:20180623T230500Z
DTEND:20180624T020500Z
UID:ya00yDfv9ar5h8QfcwdpMiZ6@stanza.co
SUMMARY:Fisher Cats vs. Fightin Phils
DESCRIPTION:The Fisher Cats have partnered with the Franco-American Centre to host a the NH Poutine Fest.  All fans at the game will be able to purchase poutine from concession areas within Northeast Delta Dental Stadium.\n\nJoin us after the game for a spectacular Rush Fireworks show courtesy of Atlas Fireworks!\n\nFollow on MiLB First Pitch: https://stza.co/+vLoE-1R\n\nShop: https://stza.co/+vLoE-3_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:NH Poutine Fest
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Fightin Phils
<2018-06-24 Sun 12:35-15:35>
:PROPERTIES:
:ID:       IZLCBEs-RfzcnVKO07etQ7d1@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Fightin Phils The first 1,000 fans will receive a Fisher Cats Rally Towel!

Join us for a healthy summer kickoff at the first Yoga in the Park presented by Yoga Balance! This one-hour session is held outdoors on the Northeast Delta Dental Stadium outfield from 11 30 a.m. - 12 30 a.m. prior to the Fisher Cats game at 1 35 p.m.  Open to all ages, levels and abilities. Full details and registration in Fisher Cats Online Team Store.

Kids run the bases after every Sunday day game!

Follow on MiLB First Pitch  https //stza.co/+vLoG-1l

Shop  https //stza.co/+vLoG-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Fightin Phils
END:VALARM
DTSTART:20180624T173500Z
DTEND:20180624T203500Z
UID:IZLCBEs-RfzcnVKO07etQ7d1@stanza.co
SUMMARY:Fisher Cats vs. Fightin Phils
DESCRIPTION:The first 1,000 fans will receive a Fisher Cats Rally Towel!\n\nJoin us for a healthy summer kickoff at the first Yoga in the Park presented by Yoga Balance! This one-hour session is held outdoors on the Northeast Delta Dental Stadium outfield from 11:30 a.m. - 12:30 a.m. prior to the Fisher Cats game at 1:35 p.m.  Open to all ages, levels and abilities. Full details and registration in Fisher Cats Online Team Store.\n\nKids run the bases after every Sunday day game!\n\nFollow on MiLB First Pitch: https://stza.co/+vLoG-1l\n\nShop: https://stza.co/+vLoG-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Sea Dogs
<2018-06-25 Mon 18:05-21:05>
:PROPERTIES:
:ID:       92lU4NVlVWDv5P6Zw0TOeZaJ@stanza.co
:LOCATION: NHIAA 2018 "Champion of Champions" Night
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Sea Dogs We'll be honoring 2018 NHIAA High School State Championship teams & athletes from the spring sports.  Representatives from each championship team will also compete on-field to be crowned the 'Champion of Champions'!

Hood Kid's Club Members will have their name on our Video Board during the game!

Follow on MiLB First Pitch  https //stza.co/+vLoJ-S

Shop  https //stza.co/+vLoJ-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Sea Dogs
END:VALARM
DTSTART:20180625T230500Z
DTEND:20180626T020500Z
UID:92lU4NVlVWDv5P6Zw0TOeZaJ@stanza.co
SUMMARY:Fisher Cats vs. Sea Dogs
DESCRIPTION:We'll be honoring 2018 NHIAA High School State Championship teams & athletes from the spring sports.  Representatives from each championship team will also compete on-field to be crowned the 'Champion of Champions'!\n\nHood Kid's Club Members will have their name on our Video Board during the game!\n\nFollow on MiLB First Pitch: https://stza.co/+vLoJ-S\n\nShop: https://stza.co/+vLoJ-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:NHIAA 2018 "Champion of Champions" Night
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Sea Dogs
<2018-06-26 Tue 18:05-21:05>
:PROPERTIES:
:ID:       6cgScVA8EEDPejxf4afuXVCw@stanza.co
:LOCATION: Oral Health Challenge
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Sea Dogs Kids can receive two free tickets to the Fisher Cats courtesy of the Oral Health Challenge, presented by Northeast Delta Dental. All they have to do is fill out the Oral Health Challenge form on our Community page when they brush twice and floss once each day during a one-week period.

$5 Miller, Coors, & Twisted Tea - 24oz - in the Brewhouse & Tiki Bar.  Available until First Pitch.

Follow on MiLB First Pitch  https //stza.co/+vLoL-3q

Shop  https //stza.co/+vLoL-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Sea Dogs
END:VALARM
DTSTART:20180626T230500Z
DTEND:20180627T020500Z
UID:6cgScVA8EEDPejxf4afuXVCw@stanza.co
SUMMARY:Fisher Cats vs. Sea Dogs
DESCRIPTION:Kids can receive two free tickets to the Fisher Cats courtesy of the Oral Health Challenge, presented by Northeast Delta Dental. All they have to do is fill out the Oral Health Challenge form on our Community page when they brush twice and floss once each day during a one-week period.\n\n$5 Miller, Coors, & Twisted Tea - 24oz - in the Brewhouse & Tiki Bar.  Available until First Pitch.\n\nFollow on MiLB First Pitch: https://stza.co/+vLoL-3q\n\nShop: https://stza.co/+vLoL-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Oral Health Challenge
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Sea Dogs
<2018-06-27 Wed 18:05-21:05>
:PROPERTIES:
:ID:       gSFUNj1CQ64AP_bqHNZJOqLy@stanza.co
:LOCATION: Replica On-Field Hat Giveaway
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Sea Dogs Join us as we're giving away FREE Replica on-field Hats!

Follow on MiLB First Pitch  https //stza.co/+vLoM-1E

Shop  https //stza.co/+vLoM-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Sea Dogs
END:VALARM
DTSTART:20180627T230500Z
DTEND:20180628T020500Z
UID:gSFUNj1CQ64AP_bqHNZJOqLy@stanza.co
SUMMARY:Fisher Cats vs. Sea Dogs
DESCRIPTION:Join us as we're giving away FREE Replica on-field Hats!\n\nFollow on MiLB First Pitch: https://stza.co/+vLoM-1E\n\nShop: https://stza.co/+vLoM-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Replica On-Field Hat Giveaway
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Sea Dogs
<2018-06-28 Thu 18:05-21:05>
:PROPERTIES:
:ID:       m-uwjNIuoqeCl0Ys6X17cHBv@stanza.co
:LOCATION: Community "Hunger Games" Night
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Sea Dogs Representatives from local community groups will battle it out on the field during the game to raise money and awareness for their organization!

$3 Domestics and $4 Import drafts - 12oz - from the 1st & 3rd Base Concession Stands.

Join us after the game for a spectacular Atlas Fireworks show!

Follow on MiLB First Pitch  https //stza.co/+vLoO-3t

Shop  https //stza.co/+vLoO-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Sea Dogs
END:VALARM
DTSTART:20180628T230500Z
DTEND:20180629T020500Z
UID:m-uwjNIuoqeCl0Ys6X17cHBv@stanza.co
SUMMARY:Fisher Cats vs. Sea Dogs
DESCRIPTION:Representatives from local community groups will battle it out on the field during the game to raise money and awareness for their organization!\n\n$3 Domestics and $4 Import drafts - 12oz - from the 1st & 3rd Base Concession Stands.\n\nJoin us after the game for a spectacular Atlas Fireworks show!\n\nFollow on MiLB First Pitch: https://stza.co/+vLoO-3t\n\nShop: https://stza.co/+vLoO-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Community "Hunger Games" Night
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Thunder
<2018-06-29 Fri 18:00-21:00>
:PROPERTIES:
:ID:       gSX5PWCCmUkyksZi5rQOMP6h@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Thunder Fisher Cats @ Thunder

Follow on MiLB First Pitch  https //stza.co/+v9T1-1i

Shop  https //stza.co/+v9T1-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Thunder
END:VALARM
DTSTART:20180629T230000Z
DTEND:20180630T020000Z
UID:gSX5PWCCmUkyksZi5rQOMP6h@stanza.co
SUMMARY:Fisher Cats @ Thunder
DESCRIPTION:Fisher Cats @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+v9T1-1i\n\nShop: https://stza.co/+v9T1-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Thunder
<2018-06-30 Sat 18:00-21:00>
:PROPERTIES:
:ID:       6R-O56P1GJYK3mG8AnFQsNo0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Thunder Fisher Cats @ Thunder

Follow on MiLB First Pitch  https //stza.co/+v9T2-2c

Shop  https //stza.co/+v9T2-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Thunder
END:VALARM
DTSTART:20180630T230000Z
DTEND:20180701T020000Z
UID:6R-O56P1GJYK3mG8AnFQsNo0@stanza.co
SUMMARY:Fisher Cats @ Thunder
DESCRIPTION:Fisher Cats @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+v9T2-2c\n\nShop: https://stza.co/+v9T2-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Thunder
<2018-07-01 Sun 12:00-15:00>
:PROPERTIES:
:ID:       AfKhWxt2SEpD7Nle57l9TobF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Thunder Fisher Cats @ Thunder

Follow on MiLB First Pitch  https //stza.co/+v9T3-Q

Shop  https //stza.co/+v9T3-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Thunder
END:VALARM
DTSTART:20180701T170000Z
DTEND:20180701T200000Z
UID:AfKhWxt2SEpD7Nle57l9TobF@stanza.co
SUMMARY:Fisher Cats @ Thunder
DESCRIPTION:Fisher Cats @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+v9T3-Q\n\nShop: https://stza.co/+v9T3-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Thunder
<2018-07-02 Mon 18:00-21:00>
:PROPERTIES:
:ID:       s9Ar8Dim6sjbmpmyK72XzGbo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Thunder Fisher Cats @ Thunder

Follow on MiLB First Pitch  https //stza.co/+v9T4-39

Shop  https //stza.co/+v9T4-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Thunder
END:VALARM
DTSTART:20180702T230000Z
DTEND:20180703T020000Z
UID:s9Ar8Dim6sjbmpmyK72XzGbo@stanza.co
SUMMARY:Fisher Cats @ Thunder
DESCRIPTION:Fisher Cats @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+v9T4-39\n\nShop: https://stza.co/+v9T4-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Thunder
<2018-07-03 Tue 18:00-21:00>
:PROPERTIES:
:ID:       nKGvh9HV-_MAuZC5N8AVg3YR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Thunder Fisher Cats @ Thunder

Follow on MiLB First Pitch  https //stza.co/+v9T5-2j

Shop  https //stza.co/+v9T5-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Thunder
END:VALARM
DTSTART:20180703T230000Z
DTEND:20180704T020000Z
UID:nKGvh9HV-_MAuZC5N8AVg3YR@stanza.co
SUMMARY:Fisher Cats @ Thunder
DESCRIPTION:Fisher Cats @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+v9T5-2j\n\nShop: https://stza.co/+v9T5-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Fightin Phils
<2018-07-04 Wed 18:05-21:05>
:PROPERTIES:
:ID:       py_CD5uGLhh9X4uV5KPue9D_@stanza.co
:LOCATION: 4th of July MEGA-BLAST FIREWORKS
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Fightin Phils Stick around after the game for a spectacular MEGA-BLAST Atlas Fireworks show, the largest show in Fisher Cats History!

Follow on MiLB First Pitch  https //stza.co/+vLoQ-H

Shop  https //stza.co/+vLoQ-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Fightin Phils
END:VALARM
DTSTART:20180704T230500Z
DTEND:20180705T020500Z
UID:py_CD5uGLhh9X4uV5KPue9D_@stanza.co
SUMMARY:Fisher Cats vs. Fightin Phils
DESCRIPTION:Stick around after the game for a spectacular MEGA-BLAST Atlas Fireworks show, the largest show in Fisher Cats History!\n\nFollow on MiLB First Pitch: https://stza.co/+vLoQ-H\n\nShop: https://stza.co/+vLoQ-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:4th of July MEGA-BLAST FIREWORKS
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Fightin Phils
<2018-07-05 Thu 18:05-21:05>
:PROPERTIES:
:ID:       l8csp6OVAeWrwDutMyjpwlly@stanza.co
:LOCATION: Robert Hight - NHRA Funny Car Champion - Bobblehead
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Fightin Phils The first 1,000 fans will receive a Robert Hight - NHRA Funny Car Champion - Bobblehead.



$3 Domestics and $4 Import drafts - 12oz - from the 1st & 3rd Base Concession Stands.

Follow on MiLB First Pitch  https //stza.co/+vLoT-2C

Shop  https //stza.co/+vLoT-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Fightin Phils
END:VALARM
DTSTART:20180705T230500Z
DTEND:20180706T020500Z
UID:l8csp6OVAeWrwDutMyjpwlly@stanza.co
SUMMARY:Fisher Cats vs. Fightin Phils
DESCRIPTION:The first 1,000 fans will receive a Robert Hight - NHRA Funny Car Champion - Bobblehead.\n\n\n\n$3 Domestics and $4 Import drafts - 12oz - from the 1st & 3rd Base Concession Stands.\n\nFollow on MiLB First Pitch: https://stza.co/+vLoT-2C\n\nShop: https://stza.co/+vLoT-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Robert Hight - NHRA Funny Car Champion - Bobblehead
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Fightin Phils
<2018-07-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       eWPbxuuRq3oh5VN5nXl3LaJQ@stanza.co
:LOCATION: Post-Game Atlas Fireworks
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Fightin Phils Join us after the game for a spectacular Atlas Fireworks show!

Follow on MiLB First Pitch  https //stza.co/+vLoV-1

Shop  https //stza.co/+vLoV-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Fightin Phils
END:VALARM
DTSTART:20180706T230500Z
DTEND:20180707T020500Z
UID:eWPbxuuRq3oh5VN5nXl3LaJQ@stanza.co
SUMMARY:Fisher Cats vs. Fightin Phils
DESCRIPTION:Join us after the game for a spectacular Atlas Fireworks show!\n\nFollow on MiLB First Pitch: https://stza.co/+vLoV-1\n\nShop: https://stza.co/+vLoV-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Post-Game Atlas Fireworks
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Fightin Phils
<2018-07-07 Sat 18:05-21:05>
:PROPERTIES:
:ID:       w1o078fA2QdEgCxrU_ekzTZ-@stanza.co
:LOCATION: Margaritaville Night
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Fightin Phils 

Join us after the game for a spectacular Atlas Fireworks show!

Follow on MiLB First Pitch  https //stza.co/+vLoX-3s

Shop  https //stza.co/+vLoX-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Fightin Phils
END:VALARM
DTSTART:20180707T230500Z
DTEND:20180708T020500Z
UID:w1o078fA2QdEgCxrU_ekzTZ-@stanza.co
SUMMARY:Fisher Cats vs. Fightin Phils
DESCRIPTION:\n\nJoin us after the game for a spectacular Atlas Fireworks show!\n\nFollow on MiLB First Pitch: https://stza.co/+vLoX-3s\n\nShop: https://stza.co/+vLoX-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Margaritaville Night
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Fightin Phils
<2018-07-08 Sun 12:35-15:35>
:PROPERTIES:
:ID:       6LUlEeGzXzJxBcZWwpSFBhSv@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Fightin Phils We're giving away FREE Replica Jerseys to the first 1,000 fans!

Join us as we look back our 15 seasons of baseball with What Could Have Been Day!  We'll celebrate the potential names and logos of our past!

Kids run the bases after every Sunday day game!

Hood Kid's Club Members will get to meet the Fisher Cats with an on-field autograph session before the game!

Follow on MiLB First Pitch  https //stza.co/+vLoZ-1G

Shop  https //stza.co/+vLoZ-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Fightin Phils
END:VALARM
DTSTART:20180708T173500Z
DTEND:20180708T203500Z
UID:6LUlEeGzXzJxBcZWwpSFBhSv@stanza.co
SUMMARY:Fisher Cats vs. Fightin Phils
DESCRIPTION:We're giving away FREE Replica Jerseys to the first 1,000 fans!\n\nJoin us as we look back our 15 seasons of baseball with What Could Have Been Day!  We'll celebrate the potential names and logos of our past!\n\nKids run the bases after every Sunday day game!\n\nHood Kid's Club Members will get to meet the Fisher Cats with an on-field autograph session before the game!\n\nFollow on MiLB First Pitch: https://stza.co/+vLoZ-1G\n\nShop: https://stza.co/+vLoZ-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Sea Dogs
<2018-07-12 Thu 18:00-21:00>
:PROPERTIES:
:ID:       Ah65Jf9N00v4PlQ-As9UWPEK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Sea Dogs Fisher Cats @ Sea Dogs

Buy tickets here  https //stza.co/~vLpM

Follow on MiLB First Pitch  https //stza.co/+vLpM-2b

Shop  https //stza.co/+vLpM-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Sea Dogs
END:VALARM
DTSTART:20180712T230000Z
DTEND:20180713T020000Z
UID:Ah65Jf9N00v4PlQ-As9UWPEK@stanza.co
SUMMARY:Fisher Cats @ Sea Dogs
DESCRIPTION:Fisher Cats @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vLpM\n\nFollow on MiLB First Pitch: https://stza.co/+vLpM-2b\n\nShop: https://stza.co/+vLpM-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Sea Dogs
<2018-07-13 Fri 18:00-21:00>
:PROPERTIES:
:ID:       frR-dqzj51h6Sc7tfvnlmRMl@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Sea Dogs Fisher Cats @ Sea Dogs

Buy tickets here  https //stza.co/~vLpN

Follow on MiLB First Pitch  https //stza.co/+vLpN-L

Shop  https //stza.co/+vLpN-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Sea Dogs
END:VALARM
DTSTART:20180713T230000Z
DTEND:20180714T020000Z
UID:frR-dqzj51h6Sc7tfvnlmRMl@stanza.co
SUMMARY:Fisher Cats @ Sea Dogs
DESCRIPTION:Fisher Cats @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vLpN\n\nFollow on MiLB First Pitch: https://stza.co/+vLpN-L\n\nShop: https://stza.co/+vLpN-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Sea Dogs
<2018-07-14 Sat 17:00-20:00>
:PROPERTIES:
:ID:       EwCWs5FLloUOvc376VKuZ_MZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Sea Dogs Fisher Cats @ Sea Dogs

Buy tickets here  https //stza.co/~vLpO

Follow on MiLB First Pitch  https //stza.co/+vLpO-W

Shop  https //stza.co/+vLpO-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Sea Dogs
END:VALARM
DTSTART:20180714T220000Z
DTEND:20180715T010000Z
UID:EwCWs5FLloUOvc376VKuZ_MZ@stanza.co
SUMMARY:Fisher Cats @ Sea Dogs
DESCRIPTION:Fisher Cats @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vLpO\n\nFollow on MiLB First Pitch: https://stza.co/+vLpO-W\n\nShop: https://stza.co/+vLpO-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Sea Dogs
<2018-07-15 Sun 12:00-15:00>
:PROPERTIES:
:ID:       dr8h38rkiaF8jtgj8Ndin-oZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Sea Dogs Fisher Cats @ Sea Dogs

Buy tickets here  https //stza.co/~vLpP

Follow on MiLB First Pitch  https //stza.co/+vLpP-J

Shop  https //stza.co/+vLpP-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Sea Dogs
END:VALARM
DTSTART:20180715T170000Z
DTEND:20180715T200000Z
UID:dr8h38rkiaF8jtgj8Ndin-oZ@stanza.co
SUMMARY:Fisher Cats @ Sea Dogs
DESCRIPTION:Fisher Cats @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vLpP\n\nFollow on MiLB First Pitch: https://stza.co/+vLpP-J\n\nShop: https://stza.co/+vLpP-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Thunder
<2018-07-16 Mon 18:05-21:05>
:PROPERTIES:
:ID:       a6h6xBKfqMtNstHfKqeli5pv@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Thunder Fisher Cats vs. Thunder

Follow on MiLB First Pitch  https //stza.co/+vLo$-29

Shop  https //stza.co/+vLo$-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Thunder
END:VALARM
DTSTART:20180716T230500Z
DTEND:20180717T020500Z
UID:a6h6xBKfqMtNstHfKqeli5pv@stanza.co
SUMMARY:Fisher Cats vs. Thunder
DESCRIPTION:Fisher Cats vs. Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vLo$-29\n\nShop: https://stza.co/+vLo$-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Thunder
<2018-07-17 Tue 18:05-21:05>
:PROPERTIES:
:ID:       FWy2XMYCRSl_R3sRYPNG331o@stanza.co
:LOCATION: Tall Boy Tuesdays
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Thunder $5 Miller, Coors, & Twisted Tea - 24oz - in the Brewhouse & Tiki Bar.  Available until First Pitch.

Follow on MiLB First Pitch  https //stza.co/+vLp1-36

Shop  https //stza.co/+vLp1-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Thunder
END:VALARM
DTSTART:20180717T230500Z
DTEND:20180718T020500Z
UID:FWy2XMYCRSl_R3sRYPNG331o@stanza.co
SUMMARY:Fisher Cats vs. Thunder
DESCRIPTION:$5 Miller, Coors, & Twisted Tea - 24oz - in the Brewhouse & Tiki Bar.  Available until First Pitch.\n\nFollow on MiLB First Pitch: https://stza.co/+vLp1-36\n\nShop: https://stza.co/+vLp1-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Tall Boy Tuesdays
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Thunder
<2018-07-18 Wed 11:05-14:05>
:PROPERTIES:
:ID:       sQoUKLdiS-8cG5hujWrdSHL0@stanza.co
:LOCATION: Camp "Color Wars"
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Thunder Every camps favorite time of the year is the 'Color War' and we're bring it to the ballpark. Camps will compete on the field and we'll crown a winner during the game!

Follow on MiLB First Pitch  https //stza.co/+vLp3-d

Shop  https //stza.co/+vLp3-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Thunder
END:VALARM
DTSTART:20180718T160500Z
DTEND:20180718T190500Z
UID:sQoUKLdiS-8cG5hujWrdSHL0@stanza.co
SUMMARY:Fisher Cats vs. Thunder
DESCRIPTION:Every camps favorite time of the year is the 'Color War' and we're bring it to the ballpark. Camps will compete on the field and we'll crown a winner during the game!\n\nFollow on MiLB First Pitch: https://stza.co/+vLp3-d\n\nShop: https://stza.co/+vLp3-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Camp "Color Wars"
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Senators
<2018-07-19 Thu 18:05-21:05>
:PROPERTIES:
:ID:       F9gpXAyqxa1_29CvlYFK6VHW@stanza.co
:LOCATION: Goodwill of Northern New England Night
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Senators Bring a donation of new or gently used household items or clothing for Goodwill of Northern New England and earn ticket to a future Fisher Cats game!

Join us after the game for a spectacular Atlas Fireworks show!

$3 Domestics and $4 Import drafts - 12oz - from the 1st & 3rd Base Concession Stands.

Follow on MiLB First Pitch  https //stza.co/+vLp5-2d

Shop  https //stza.co/+vLp5-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Senators
END:VALARM
DTSTART:20180719T230500Z
DTEND:20180720T020500Z
UID:F9gpXAyqxa1_29CvlYFK6VHW@stanza.co
SUMMARY:Fisher Cats vs. Senators
DESCRIPTION:Bring a donation of new or gently used household items or clothing for Goodwill of Northern New England and earn ticket to a future Fisher Cats game!\n\nJoin us after the game for a spectacular Atlas Fireworks show!\n\n$3 Domestics and $4 Import drafts - 12oz - from the 1st & 3rd Base Concession Stands.\n\nFollow on MiLB First Pitch: https://stza.co/+vLp5-2d\n\nShop: https://stza.co/+vLp5-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Goodwill of Northern New England Night
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Senators
<2018-07-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       4t2TIwPWZJFpfHH_XoZ3228K@stanza.co
:LOCATION: Fungo Wizard Bobblehead Giveaway
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Senators Join us as we celebrate all things Wizard and Witch by giving away FREE Fungo Wizard Bobblehead!

Kids can receive two free tickets to the Fisher Cats courtesy of the Oral Health Challenge, presented by Northeast Delta Dental. All they have to do is fill out the Oral Health Challenge form on our Community page when they brush twice and floss once each day during a one-week period.

Follow on MiLB First Pitch  https //stza.co/+vLp6-2t

Shop  https //stza.co/+vLp6-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Senators
END:VALARM
DTSTART:20180720T230500Z
DTEND:20180721T020500Z
UID:4t2TIwPWZJFpfHH_XoZ3228K@stanza.co
SUMMARY:Fisher Cats vs. Senators
DESCRIPTION:Join us as we celebrate all things Wizard and Witch by giving away FREE Fungo Wizard Bobblehead!\n\nKids can receive two free tickets to the Fisher Cats courtesy of the Oral Health Challenge, presented by Northeast Delta Dental. All they have to do is fill out the Oral Health Challenge form on our Community page when they brush twice and floss once each day during a one-week period.\n\nFollow on MiLB First Pitch: https://stza.co/+vLp6-2t\n\nShop: https://stza.co/+vLp6-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fungo Wizard Bobblehead Giveaway
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Senators
<2018-07-21 Sat 18:05-21:05>
:PROPERTIES:
:ID:       4lquayVWa-7vKgPzS0VIYRlZ@stanza.co
:LOCATION: May the force be with you! Come check out Stars Wars Night at the park
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Senators Star Wars Night returns to Manchester with an EPIC celebration of all things Star Wars.  Join us for music, movie clips, your favorite characters and more!

The Human Cannonball will be part of the entertainment on July 21, when David 'The Bullet' Smith will be shot from a cannon in front of the home crowd.

Join us after the game for a spectacular Atlas Fireworks show!

Join us after the game for a spectacular Star Wars Remix Fireworks show courtesy of Atlas Fireworks!

Follow on MiLB First Pitch  https //stza.co/+vLp8-3S

Shop  https //stza.co/+vLp8-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Senators
END:VALARM
DTSTART:20180721T230500Z
DTEND:20180722T020500Z
UID:4lquayVWa-7vKgPzS0VIYRlZ@stanza.co
SUMMARY:Fisher Cats vs. Senators
DESCRIPTION:Star Wars Night returns to Manchester with an EPIC celebration of all things Star Wars.  Join us for music, movie clips, your favorite characters and more!\n\nThe Human Cannonball will be part of the entertainment on July 21, when David 'The Bullet' Smith will be shot from a cannon in front of the home crowd.\n\nJoin us after the game for a spectacular Atlas Fireworks show!\n\nJoin us after the game for a spectacular Star Wars Remix Fireworks show courtesy of Atlas Fireworks!\n\nFollow on MiLB First Pitch: https://stza.co/+vLp8-3S\n\nShop: https://stza.co/+vLp8-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:May the force be with you! Come check out Stars Wars Night at the park
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Senators
<2018-07-22 Sun 12:35-15:35>
:PROPERTIES:
:ID:       TP6vpKpFrqFjnILqHJf02odK@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Senators The first 1,000 fans will receive a Fisher Cats Baseball Glove!

Kids run the bases after every Sunday day game!



Follow on MiLB First Pitch  https //stza.co/+vLpb-3v

Shop  https //stza.co/+vLpb-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Senators
END:VALARM
DTSTART:20180722T173500Z
DTEND:20180722T203500Z
UID:TP6vpKpFrqFjnILqHJf02odK@stanza.co
SUMMARY:Fisher Cats vs. Senators
DESCRIPTION:The first 1,000 fans will receive a Fisher Cats Baseball Glove!\n\nKids run the bases after every Sunday day game!\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+vLpb-3v\n\nShop: https://stza.co/+vLpb-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Fightin Phils
<2018-07-23 Mon 18:05-21:05>
:PROPERTIES:
:ID:       v2zFN9y4gOErlh6SetbV3IQB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Fightin Phils Fisher Cats @ Fightin Phils

Buy tickets here  https //stza.co/~v9SU

Follow on MiLB First Pitch  https //stza.co/+v9SU-4

Shop  https //stza.co/+v9SU-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Fightin Phils
END:VALARM
DTSTART:20180723T230500Z
DTEND:20180724T020500Z
UID:v2zFN9y4gOErlh6SetbV3IQB@stanza.co
SUMMARY:Fisher Cats @ Fightin Phils
DESCRIPTION:Fisher Cats @ Fightin Phils\n\nBuy tickets here: https://stza.co/~v9SU\n\nFollow on MiLB First Pitch: https://stza.co/+v9SU-4\n\nShop: https://stza.co/+v9SU-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Fightin Phils
<2018-07-24 Tue 18:05-21:05>
:PROPERTIES:
:ID:       j_YlKdS2RRX21ks8outpFRyR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Fightin Phils Fisher Cats @ Fightin Phils

Buy tickets here  https //stza.co/~v9SV

Follow on MiLB First Pitch  https //stza.co/+v9SV-3T

Shop  https //stza.co/+v9SV-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Fightin Phils
END:VALARM
DTSTART:20180724T230500Z
DTEND:20180725T020500Z
UID:j_YlKdS2RRX21ks8outpFRyR@stanza.co
SUMMARY:Fisher Cats @ Fightin Phils
DESCRIPTION:Fisher Cats @ Fightin Phils\n\nBuy tickets here: https://stza.co/~v9SV\n\nFollow on MiLB First Pitch: https://stza.co/+v9SV-3T\n\nShop: https://stza.co/+v9SV-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Fightin Phils
<2018-07-25 Wed 11:05-14:05>
:PROPERTIES:
:ID:       WTCJQAqZY4zemGjdRMZp5uCM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Fightin Phils Fisher Cats @ Fightin Phils

Buy tickets here  https //stza.co/~v9SW

Follow on MiLB First Pitch  https //stza.co/+v9SW-w

Shop  https //stza.co/+v9SW-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Fightin Phils
END:VALARM
DTSTART:20180725T160500Z
DTEND:20180725T190500Z
UID:WTCJQAqZY4zemGjdRMZp5uCM@stanza.co
SUMMARY:Fisher Cats @ Fightin Phils
DESCRIPTION:Fisher Cats @ Fightin Phils\n\nBuy tickets here: https://stza.co/~v9SW\n\nFollow on MiLB First Pitch: https://stza.co/+v9SW-w\n\nShop: https://stza.co/+v9SW-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Yard Goats
<2018-07-26 Thu 18:05-21:05>
:PROPERTIES:
:ID:       yLhnFNYlVphIjm55sUDQktFB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Yard Goats Fisher Cats @ Yard Goats

Buy tickets here  https //stza.co/~vLnw

Follow on MiLB First Pitch  https //stza.co/+vLnw-2Z

Shop  https //stza.co/+vLnw-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Yard Goats
END:VALARM
DTSTART:20180726T230500Z
DTEND:20180727T020500Z
UID:yLhnFNYlVphIjm55sUDQktFB@stanza.co
SUMMARY:Fisher Cats @ Yard Goats
DESCRIPTION:Fisher Cats @ Yard Goats\n\nBuy tickets here: https://stza.co/~vLnw\n\nFollow on MiLB First Pitch: https://stza.co/+vLnw-2Z\n\nShop: https://stza.co/+vLnw-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Yard Goats
<2018-07-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       stQWg5x2_dBCA4q_iuzvcC_v@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Yard Goats Fisher Cats @ Yard Goats

Buy tickets here  https //stza.co/~vLnx

Follow on MiLB First Pitch  https //stza.co/+vLnx-3Y

Shop  https //stza.co/+vLnx-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Yard Goats
END:VALARM
DTSTART:20180727T230500Z
DTEND:20180728T020500Z
UID:stQWg5x2_dBCA4q_iuzvcC_v@stanza.co
SUMMARY:Fisher Cats @ Yard Goats
DESCRIPTION:Fisher Cats @ Yard Goats\n\nBuy tickets here: https://stza.co/~vLnx\n\nFollow on MiLB First Pitch: https://stza.co/+vLnx-3Y\n\nShop: https://stza.co/+vLnx-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Yard Goats
<2018-07-28 Sat 17:05-20:05>
:PROPERTIES:
:ID:       8MgbgWJtLxuHGt2GaK_hbd5D@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Yard Goats Fisher Cats @ Yard Goats

Buy tickets here  https //stza.co/~vLny

Follow on MiLB First Pitch  https //stza.co/+vLny-2S

Shop  https //stza.co/+vLny-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Yard Goats
END:VALARM
DTSTART:20180728T220500Z
DTEND:20180729T010500Z
UID:8MgbgWJtLxuHGt2GaK_hbd5D@stanza.co
SUMMARY:Fisher Cats @ Yard Goats
DESCRIPTION:Fisher Cats @ Yard Goats\n\nBuy tickets here: https://stza.co/~vLny\n\nFollow on MiLB First Pitch: https://stza.co/+vLny-2S\n\nShop: https://stza.co/+vLny-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Yard Goats
<2018-07-29 Sun 16:05-19:05>
:PROPERTIES:
:ID:       gyeGS24d1t3rg654SAE3Bib6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Yard Goats Fisher Cats @ Yard Goats

Buy tickets here  https //stza.co/~vLnz

Follow on MiLB First Pitch  https //stza.co/+vLnz-39

Shop  https //stza.co/+vLnz-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Yard Goats
END:VALARM
DTSTART:20180729T210500Z
DTEND:20180730T000500Z
UID:gyeGS24d1t3rg654SAE3Bib6@stanza.co
SUMMARY:Fisher Cats @ Yard Goats
DESCRIPTION:Fisher Cats @ Yard Goats\n\nBuy tickets here: https://stza.co/~vLnz\n\nFollow on MiLB First Pitch: https://stza.co/+vLnz-39\n\nShop: https://stza.co/+vLnz-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Flying Squirrels
<2018-07-31 Tue 18:05-21:05>
:PROPERTIES:
:ID:       jWJOCr5nswAJxj5g5SzzM1mc@stanza.co
:LOCATION: Tall Boy Tuesdays
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Flying Squirrels $5 Miller, Coors, & Twisted Tea - 24oz - in the Brewhouse & Tiki Bar.  Available until First Pitch.

Follow on MiLB First Pitch  https //stza.co/+vLpc-j

Shop  https //stza.co/+vLpc-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Flying Squirrels
END:VALARM
DTSTART:20180731T230500Z
DTEND:20180801T020500Z
UID:jWJOCr5nswAJxj5g5SzzM1mc@stanza.co
SUMMARY:Fisher Cats vs. Flying Squirrels
DESCRIPTION:$5 Miller, Coors, & Twisted Tea - 24oz - in the Brewhouse & Tiki Bar.  Available until First Pitch.\n\nFollow on MiLB First Pitch: https://stza.co/+vLpc-j\n\nShop: https://stza.co/+vLpc-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Tall Boy Tuesdays
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Flying Squirrels
<2018-08-01 Wed 11:05-14:05>
:PROPERTIES:
:ID:       3h6bEUcgGktw5edNMVqZJNYV@stanza.co
:LOCATION: Camp "Color Wars"
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Flying Squirrels Every camps favorite time of the year is the 'Color War' and we're bring it to the ballpark. Camps will compete on the field and we'll crown a winner during the game!

Follow on MiLB First Pitch  https //stza.co/+vLpe-3o

Shop  https //stza.co/+vLpe-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Flying Squirrels
END:VALARM
DTSTART:20180801T160500Z
DTEND:20180801T190500Z
UID:3h6bEUcgGktw5edNMVqZJNYV@stanza.co
SUMMARY:Fisher Cats vs. Flying Squirrels
DESCRIPTION:Every camps favorite time of the year is the 'Color War' and we're bring it to the ballpark. Camps will compete on the field and we'll crown a winner during the game!\n\nFollow on MiLB First Pitch: https://stza.co/+vLpe-3o\n\nShop: https://stza.co/+vLpe-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Camp "Color Wars"
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Flying Squirrels
<2018-08-02 Thu 18:05-21:05>
:PROPERTIES:
:ID:       2CNJqrM1NY1k8626BZAGcSo6@stanza.co
:LOCATION: Post-Game Atlas Fireworks
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Flying Squirrels Join us after the game for a spectacular Atlas Fireworks show!

$3 Domestics and $4 Import drafts - 12oz - from the 1st & 3rd Base Concession Stands.

Follow on MiLB First Pitch  https //stza.co/+vLpg-3C

Shop  https //stza.co/+vLpg-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Flying Squirrels
END:VALARM
DTSTART:20180802T230500Z
DTEND:20180803T020500Z
UID:2CNJqrM1NY1k8626BZAGcSo6@stanza.co
SUMMARY:Fisher Cats vs. Flying Squirrels
DESCRIPTION:Join us after the game for a spectacular Atlas Fireworks show!\n\n$3 Domestics and $4 Import drafts - 12oz - from the 1st & 3rd Base Concession Stands.\n\nFollow on MiLB First Pitch: https://stza.co/+vLpg-3C\n\nShop: https://stza.co/+vLpg-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Post-Game Atlas Fireworks
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. SeaWolves
<2018-08-03 Fri 18:05-21:05>
:PROPERTIES:
:ID:       9dmCTH_dnClAD31qSO6X1L-v@stanza.co
:LOCATION: Comic-Con Night
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. SeaWolves Celebrate Comic-Con with the Fisher Cats & Double Midnight Comics!  Come dressed as your favorite comic book & movie characters, meet superheroes, and more!

Join us as we're giving away FREE t-shirts to the first 1,000 fans!

Bring the whole troop and sleep on the field after the game! Each scout will receive a special Fisher Cats patch for attending the game, and can enjoy a movie on the video board after the final out. Pre-registration required. 

Follow on MiLB First Pitch  https //stza.co/+vLpi-2y

Shop  https //stza.co/+vLpi-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. SeaWolves
END:VALARM
DTSTART:20180803T230500Z
DTEND:20180804T020500Z
UID:9dmCTH_dnClAD31qSO6X1L-v@stanza.co
SUMMARY:Fisher Cats vs. SeaWolves
DESCRIPTION:Celebrate Comic-Con with the Fisher Cats & Double Midnight Comics!  Come dressed as your favorite comic book & movie characters, meet superheroes, and more!\n\nJoin us as we're giving away FREE t-shirts to the first 1,000 fans!\n\nBring the whole troop and sleep on the field after the game! Each scout will receive a special Fisher Cats patch for attending the game, and can enjoy a movie on the video board after the final out. Pre-registration required. \n\nFollow on MiLB First Pitch: https://stza.co/+vLpi-2y\n\nShop: https://stza.co/+vLpi-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Comic-Con Night
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. SeaWolves
<2018-08-04 Sat 18:05-21:05>
:PROPERTIES:
:ID:       90XgU2J_nqA1-d3GjjP9Cf7q@stanza.co
:LOCATION: Love Your Heart Night
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. SeaWolves Wear Red to the ballpark for Love Your Heart Night and participate in free screenings while you're here.  Learn about ways to protect your heart and show it the love that it deserves.

Join us after the game for a spectacular Dirty Dancing Fireworks show courtesy of Atlas Fireworks!

Follow on MiLB First Pitch  https //stza.co/+vLpl-3Y

Shop  https //stza.co/+vLpl-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. SeaWolves
END:VALARM
DTSTART:20180804T230500Z
DTEND:20180805T020500Z
UID:90XgU2J_nqA1-d3GjjP9Cf7q@stanza.co
SUMMARY:Fisher Cats vs. SeaWolves
DESCRIPTION:Wear Red to the ballpark for Love Your Heart Night and participate in free screenings while you're here.  Learn about ways to protect your heart and show it the love that it deserves.\n\nJoin us after the game for a spectacular Dirty Dancing Fireworks show courtesy of Atlas Fireworks!\n\nFollow on MiLB First Pitch: https://stza.co/+vLpl-3Y\n\nShop: https://stza.co/+vLpl-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Love Your Heart Night
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. SeaWolves
<2018-08-05 Sun 12:35-15:35>
:PROPERTIES:
:ID:       OkvJ9LFOyhilzrptdhLtsRZs@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. SeaWolves Join us as we're giving away FREE Autographed Baseballs!

Kids run the bases after every Sunday day game!

Kids can receive two free tickets to the Fisher Cats courtesy of the Oral Health Challenge, presented by Northeast Delta Dental. All they have to do is fill out the Oral Health Challenge form on our Community page when they brush twice and floss once each day during a one-week period.

Hood Kid's Club Members will help welcome the Fisher Cats to the field as part of our High Five Tunnel!

Follow on MiLB First Pitch  https //stza.co/+vLpn-1Y

Shop  https //stza.co/+vLpn-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. SeaWolves
END:VALARM
DTSTART:20180805T173500Z
DTEND:20180805T203500Z
UID:OkvJ9LFOyhilzrptdhLtsRZs@stanza.co
SUMMARY:Fisher Cats vs. SeaWolves
DESCRIPTION:Join us as we're giving away FREE Autographed Baseballs!\n\nKids run the bases after every Sunday day game!\n\nKids can receive two free tickets to the Fisher Cats courtesy of the Oral Health Challenge, presented by Northeast Delta Dental. All they have to do is fill out the Oral Health Challenge form on our Community page when they brush twice and floss once each day during a one-week period.\n\nHood Kid's Club Members will help welcome the Fisher Cats to the field as part of our High Five Tunnel!\n\nFollow on MiLB First Pitch: https://stza.co/+vLpn-1Y\n\nShop: https://stza.co/+vLpn-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Baysox
<2018-08-07 Tue 18:05-21:05>
:PROPERTIES:
:ID:       e3dz65BPfdm7tonL_Ux-j12O@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Baysox Fisher Cats @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vLnf-3R

Shop  https //stza.co/+vLnf-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Baysox
END:VALARM
DTSTART:20180807T230500Z
DTEND:20180808T020500Z
UID:e3dz65BPfdm7tonL_Ux-j12O@stanza.co
SUMMARY:Fisher Cats @ Baysox
DESCRIPTION:Fisher Cats @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLnf-3R\n\nShop: https://stza.co/+vLnf-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Baysox
<2018-08-08 Wed 18:05-21:05>
:PROPERTIES:
:ID:       nYZeDSyyrvEaLEmOMwmC5aTo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Baysox Fisher Cats @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vLng-r

Shop  https //stza.co/+vLng-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Baysox
END:VALARM
DTSTART:20180808T230500Z
DTEND:20180809T020500Z
UID:nYZeDSyyrvEaLEmOMwmC5aTo@stanza.co
SUMMARY:Fisher Cats @ Baysox
DESCRIPTION:Fisher Cats @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLng-r\n\nShop: https://stza.co/+vLng-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Baysox
<2018-08-09 Thu 10:05-13:05>
:PROPERTIES:
:ID:       XxbKg2FoY3vNWPweNKba45cB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Baysox Fisher Cats @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vLnh-2X

Shop  https //stza.co/+vLnh-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Baysox
END:VALARM
DTSTART:20180809T150500Z
DTEND:20180809T180500Z
UID:XxbKg2FoY3vNWPweNKba45cB@stanza.co
SUMMARY:Fisher Cats @ Baysox
DESCRIPTION:Fisher Cats @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLnh-2X\n\nShop: https://stza.co/+vLnh-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Flying Squirrels
<2018-08-10 Fri 18:05-21:05>
:PROPERTIES:
:ID:       hBmaht5GixmlggD9-5p1SkR0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Flying Squirrels Fisher Cats @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+v9SX-3Q

Shop  https //stza.co/+v9SX-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Flying Squirrels
END:VALARM
DTSTART:20180810T230500Z
DTEND:20180811T020500Z
UID:hBmaht5GixmlggD9-5p1SkR0@stanza.co
SUMMARY:Fisher Cats @ Flying Squirrels
DESCRIPTION:Fisher Cats @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+v9SX-3Q\n\nShop: https://stza.co/+v9SX-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Flying Squirrels
<2018-08-11 Sat 17:05-20:05>
:PROPERTIES:
:ID:       UBtJLPXeZiwljzW7IcoubkLE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Flying Squirrels Fisher Cats @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+v9SY-1i

Shop  https //stza.co/+v9SY-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Flying Squirrels
END:VALARM
DTSTART:20180811T220500Z
DTEND:20180812T010500Z
UID:UBtJLPXeZiwljzW7IcoubkLE@stanza.co
SUMMARY:Fisher Cats @ Flying Squirrels
DESCRIPTION:Fisher Cats @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+v9SY-1i\n\nShop: https://stza.co/+v9SY-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Flying Squirrels
<2018-08-12 Sun 12:05-15:05>
:PROPERTIES:
:ID:       Cng4CRtJMZ9xCpvNt9nC0SrO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Flying Squirrels Fisher Cats @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+v9SZ-Z

Shop  https //stza.co/+v9SZ-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Flying Squirrels
END:VALARM
DTSTART:20180812T170500Z
DTEND:20180812T200500Z
UID:Cng4CRtJMZ9xCpvNt9nC0SrO@stanza.co
SUMMARY:Fisher Cats @ Flying Squirrels
DESCRIPTION:Fisher Cats @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+v9SZ-Z\n\nShop: https://stza.co/+v9SZ-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Curve
<2018-08-14 Tue 18:05-21:05>
:PROPERTIES:
:ID:       W4bjQ8J_p55iQ6-Wxzmok65E@stanza.co
:LOCATION: Tall Boy Tuesdays
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Curve $5 Miller, Coors, & Twisted Tea - 24oz - in the Brewhouse & Tiki Bar.  Available until First Pitch.

Follow on MiLB First Pitch  https //stza.co/+vLpo-F

Shop  https //stza.co/+vLpo-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Curve
END:VALARM
DTSTART:20180814T230500Z
DTEND:20180815T020500Z
UID:W4bjQ8J_p55iQ6-Wxzmok65E@stanza.co
SUMMARY:Fisher Cats vs. Curve
DESCRIPTION:$5 Miller, Coors, & Twisted Tea - 24oz - in the Brewhouse & Tiki Bar.  Available until First Pitch.\n\nFollow on MiLB First Pitch: https://stza.co/+vLpo-F\n\nShop: https://stza.co/+vLpo-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Tall Boy Tuesdays
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Curve
<2018-08-15 Wed 18:05-21:05>
:PROPERTIES:
:ID:       C7SYj-gFP_DWrIQIWEeXbBuj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Curve Fisher Cats vs. Curve

Follow on MiLB First Pitch  https //stza.co/+vLpq-34

Shop  https //stza.co/+vLpq-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Curve
END:VALARM
DTSTART:20180815T230500Z
DTEND:20180816T020500Z
UID:C7SYj-gFP_DWrIQIWEeXbBuj@stanza.co
SUMMARY:Fisher Cats vs. Curve
DESCRIPTION:Fisher Cats vs. Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLpq-34\n\nShop: https://stza.co/+vLpq-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Curve
<2018-08-16 Thu 18:05-21:05>
:PROPERTIES:
:ID:       J_Wwrpy0UvN8jdpfdUsV-TVp@stanza.co
:LOCATION: Post-Game Atlas Fireworks
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Curve Join us after the game for a spectacular Atlas Fireworks show!

$3 Domestics and $4 Import drafts - 12oz - from the 1st & 3rd Base Concession Stands.

Follow on MiLB First Pitch  https //stza.co/+vLpt-1y

Shop  https //stza.co/+vLpt-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Curve
END:VALARM
DTSTART:20180816T230500Z
DTEND:20180817T020500Z
UID:J_Wwrpy0UvN8jdpfdUsV-TVp@stanza.co
SUMMARY:Fisher Cats vs. Curve
DESCRIPTION:Join us after the game for a spectacular Atlas Fireworks show!\n\n$3 Domestics and $4 Import drafts - 12oz - from the 1st & 3rd Base Concession Stands.\n\nFollow on MiLB First Pitch: https://stza.co/+vLpt-1y\n\nShop: https://stza.co/+vLpt-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Post-Game Atlas Fireworks
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Thunder
<2018-08-17 Fri 18:00-21:00>
:PROPERTIES:
:ID:       bcBCa7175Bvp7w0iLdhA4CWZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Thunder Fisher Cats @ Thunder

Follow on MiLB First Pitch  https //stza.co/+v9T6-1r

Shop  https //stza.co/+v9T6-1J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Thunder
END:VALARM
DTSTART:20180817T230000Z
DTEND:20180818T020000Z
UID:bcBCa7175Bvp7w0iLdhA4CWZ@stanza.co
SUMMARY:Fisher Cats @ Thunder
DESCRIPTION:Fisher Cats @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+v9T6-1r\n\nShop: https://stza.co/+v9T6-1J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Thunder
<2018-08-18 Sat 18:00-21:00>
:PROPERTIES:
:ID:       bGUMQKEKBpF9jQ6tqHC61gqf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Thunder Fisher Cats @ Thunder

Follow on MiLB First Pitch  https //stza.co/+v9T7-2B

Shop  https //stza.co/+v9T7-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Thunder
END:VALARM
DTSTART:20180818T230000Z
DTEND:20180819T020000Z
UID:bGUMQKEKBpF9jQ6tqHC61gqf@stanza.co
SUMMARY:Fisher Cats @ Thunder
DESCRIPTION:Fisher Cats @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+v9T7-2B\n\nShop: https://stza.co/+v9T7-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Thunder
<2018-08-19 Sun 16:00-19:00>
:PROPERTIES:
:ID:       nwMddjWAkeBWy0286N-kVBnR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Thunder Fisher Cats @ Thunder

Follow on MiLB First Pitch  https //stza.co/+v9T8-2k

Shop  https //stza.co/+v9T8-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Thunder
END:VALARM
DTSTART:20180819T210000Z
DTEND:20180820T000000Z
UID:nwMddjWAkeBWy0286N-kVBnR@stanza.co
SUMMARY:Fisher Cats @ Thunder
DESCRIPTION:Fisher Cats @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+v9T8-2k\n\nShop: https://stza.co/+v9T8-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Sea Dogs
<2018-08-20 Mon 18:00-21:00>
:PROPERTIES:
:ID:       WLAN3ACEdFAlfjS19JPGc6xJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Sea Dogs Fisher Cats @ Sea Dogs

Buy tickets here  https //stza.co/~vLpQ

Follow on MiLB First Pitch  https //stza.co/+vLpQ-35

Shop  https //stza.co/+vLpQ-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Sea Dogs
END:VALARM
DTSTART:20180820T230000Z
DTEND:20180821T020000Z
UID:WLAN3ACEdFAlfjS19JPGc6xJ@stanza.co
SUMMARY:Fisher Cats @ Sea Dogs
DESCRIPTION:Fisher Cats @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vLpQ\n\nFollow on MiLB First Pitch: https://stza.co/+vLpQ-35\n\nShop: https://stza.co/+vLpQ-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Sea Dogs
<2018-08-21 Tue 17:00-20:00>
:PROPERTIES:
:ID:       tufsMpJCNb_FmT2ypnZw_haz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Sea Dogs Fisher Cats @ Sea Dogs

Buy tickets here  https //stza.co/~vLpR

Follow on MiLB First Pitch  https //stza.co/+vLpR-W

Shop  https //stza.co/+vLpR-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Sea Dogs
END:VALARM
DTSTART:20180821T220000Z
DTEND:20180822T010000Z
UID:tufsMpJCNb_FmT2ypnZw_haz@stanza.co
SUMMARY:Fisher Cats @ Sea Dogs
DESCRIPTION:Fisher Cats @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vLpR\n\nFollow on MiLB First Pitch: https://stza.co/+vLpR-W\n\nShop: https://stza.co/+vLpR-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Sea Dogs
<2018-08-22 Wed 18:05-21:05>
:PROPERTIES:
:ID:       _efrrq4F-OBIUnH_dpjLUhpR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Sea Dogs Fisher Cats vs. Sea Dogs

Follow on MiLB First Pitch  https //stza.co/+vLpv-1K

Shop  https //stza.co/+vLpv-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Sea Dogs
END:VALARM
DTSTART:20180822T230500Z
DTEND:20180823T020500Z
UID:_efrrq4F-OBIUnH_dpjLUhpR@stanza.co
SUMMARY:Fisher Cats vs. Sea Dogs
DESCRIPTION:Fisher Cats vs. Sea Dogs\n\nFollow on MiLB First Pitch: https://stza.co/+vLpv-1K\n\nShop: https://stza.co/+vLpv-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Sea Dogs
<2018-08-23 Thu 18:05-21:05>
:PROPERTIES:
:ID:       gbrpBubijjo88ecrj6BsV3L6@stanza.co
:LOCATION: Post-Game Atlas Fireworks
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Sea Dogs Join us after the game for a spectacular Atlas Fireworks show!

$3 Domestics and $4 Import drafts - 12oz - from the 1st & 3rd Base Concession Stands.

Follow on MiLB First Pitch  https //stza.co/+vLpx-3r

Shop  https //stza.co/+vLpx-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Sea Dogs
END:VALARM
DTSTART:20180823T230500Z
DTEND:20180824T020500Z
UID:gbrpBubijjo88ecrj6BsV3L6@stanza.co
SUMMARY:Fisher Cats vs. Sea Dogs
DESCRIPTION:Join us after the game for a spectacular Atlas Fireworks show!\n\n$3 Domestics and $4 Import drafts - 12oz - from the 1st & 3rd Base Concession Stands.\n\nFollow on MiLB First Pitch: https://stza.co/+vLpx-3r\n\nShop: https://stza.co/+vLpx-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Post-Game Atlas Fireworks
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Rumble Ponies
<2018-08-24 Fri 18:05-21:05>
:PROPERTIES:
:ID:       8xm4ZGNT1RedJR9WXxSd1VAF@stanza.co
:LOCATION: Football Giveaway
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Rumble Ponies Join us a we're giving away FREE Fisher Cats footballs!

Follow on MiLB First Pitch  https //stza.co/+vLpy-1A

Shop  https //stza.co/+vLpy-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Rumble Ponies
END:VALARM
DTSTART:20180824T230500Z
DTEND:20180825T020500Z
UID:8xm4ZGNT1RedJR9WXxSd1VAF@stanza.co
SUMMARY:Fisher Cats vs. Rumble Ponies
DESCRIPTION:Join us a we're giving away FREE Fisher Cats footballs!\n\nFollow on MiLB First Pitch: https://stza.co/+vLpy-1A\n\nShop: https://stza.co/+vLpy-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Football Giveaway
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Rumble Ponies
<2018-08-25 Sat 18:05-21:05>
:PROPERTIES:
:ID:       XbXHKcoNmcyMtck_56c2bdTC@stanza.co
:LOCATION: Ford Night!
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Rumble Ponies 

Join us after the game for a spectacular Billy Joel Fireworks show!



Follow on MiLB First Pitch  https //stza.co/+vLpB-q

Shop  https //stza.co/+vLpB-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Rumble Ponies
END:VALARM
DTSTART:20180825T230500Z
DTEND:20180826T020500Z
UID:XbXHKcoNmcyMtck_56c2bdTC@stanza.co
SUMMARY:Fisher Cats vs. Rumble Ponies
DESCRIPTION:\n\nJoin us after the game for a spectacular Billy Joel Fireworks show!\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+vLpB-q\n\nShop: https://stza.co/+vLpB-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ford Night!
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Rumble Ponies
<2018-08-26 Sun 12:35-15:35>
:PROPERTIES:
:ID:       3JQSDf5hyNCo-3qifLP7BUb7@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Rumble Ponies Join us as we're giving away FREE Kids Backpacks!

Kids run the bases after every Sunday day game!

Follow on MiLB First Pitch  https //stza.co/+vLpC-I

Shop  https //stza.co/+vLpC-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Rumble Ponies
END:VALARM
DTSTART:20180826T173500Z
DTEND:20180826T203500Z
UID:3JQSDf5hyNCo-3qifLP7BUb7@stanza.co
SUMMARY:Fisher Cats vs. Rumble Ponies
DESCRIPTION:Join us as we're giving away FREE Kids Backpacks!\n\nKids run the bases after every Sunday day game!\n\nFollow on MiLB First Pitch: https://stza.co/+vLpC-I\n\nShop: https://stza.co/+vLpC-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Sea Dogs
<2018-08-27 Mon 18:00-21:00>
:PROPERTIES:
:ID:       fWn0Ozgt5K4yGMFRdde7CLrQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Sea Dogs Fisher Cats @ Sea Dogs

Buy tickets here  https //stza.co/~vLpS

Follow on MiLB First Pitch  https //stza.co/+vLpS-2d

Shop  https //stza.co/+vLpS-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Sea Dogs
END:VALARM
DTSTART:20180827T230000Z
DTEND:20180828T020000Z
UID:fWn0Ozgt5K4yGMFRdde7CLrQ@stanza.co
SUMMARY:Fisher Cats @ Sea Dogs
DESCRIPTION:Fisher Cats @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vLpS\n\nFollow on MiLB First Pitch: https://stza.co/+vLpS-2d\n\nShop: https://stza.co/+vLpS-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Sea Dogs
<2018-08-28 Tue 18:00-21:00>
:PROPERTIES:
:ID:       Effub-whQ2jDyjq0IGTH66X7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Sea Dogs Fisher Cats @ Sea Dogs

Buy tickets here  https //stza.co/~vLpT

Follow on MiLB First Pitch  https //stza.co/+vLpT-17

Shop  https //stza.co/+vLpT-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Sea Dogs
END:VALARM
DTSTART:20180828T230000Z
DTEND:20180829T020000Z
UID:Effub-whQ2jDyjq0IGTH66X7@stanza.co
SUMMARY:Fisher Cats @ Sea Dogs
DESCRIPTION:Fisher Cats @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vLpT\n\nFollow on MiLB First Pitch: https://stza.co/+vLpT-17\n\nShop: https://stza.co/+vLpT-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Sea Dogs
<2018-08-29 Wed 18:00-21:00>
:PROPERTIES:
:ID:       bkRTGqgv-r0wDRsJM5Gs5nlR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Sea Dogs Fisher Cats @ Sea Dogs

Buy tickets here  https //stza.co/~vLpU

Follow on MiLB First Pitch  https //stza.co/+vLpU-3i

Shop  https //stza.co/+vLpU-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Sea Dogs
END:VALARM
DTSTART:20180829T230000Z
DTEND:20180830T020000Z
UID:bkRTGqgv-r0wDRsJM5Gs5nlR@stanza.co
SUMMARY:Fisher Cats @ Sea Dogs
DESCRIPTION:Fisher Cats @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vLpU\n\nFollow on MiLB First Pitch: https://stza.co/+vLpU-3i\n\nShop: https://stza.co/+vLpU-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats @ Sea Dogs
<2018-08-30 Thu 18:00-21:00>
:PROPERTIES:
:ID:       BxGxRxxt7J_LkLy9KcZIc9Dx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fisher Cats @ Sea Dogs Fisher Cats @ Sea Dogs

Buy tickets here  https //stza.co/~vLpV

Follow on MiLB First Pitch  https //stza.co/+vLpV-2b

Shop  https //stza.co/+vLpV-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats @ Sea Dogs
END:VALARM
DTSTART:20180830T230000Z
DTEND:20180831T020000Z
UID:BxGxRxxt7J_LkLy9KcZIc9Dx@stanza.co
SUMMARY:Fisher Cats @ Sea Dogs
DESCRIPTION:Fisher Cats @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vLpV\n\nFollow on MiLB First Pitch: https://stza.co/+vLpV-2b\n\nShop: https://stza.co/+vLpV-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Yard Goats
<2018-08-31 Fri 18:05-21:05>
:PROPERTIES:
:ID:       OWn-eErZEV4lD0tCTSj5P8QJ@stanza.co
:LOCATION: UNH Night
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Yard Goats 

Join us after the game for a spectacular Atlas Fireworks show!

Follow on MiLB First Pitch  https //stza.co/+vLpE-1w

Shop  https //stza.co/+vLpE-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Yard Goats
END:VALARM
DTSTART:20180831T230500Z
DTEND:20180901T020500Z
UID:OWn-eErZEV4lD0tCTSj5P8QJ@stanza.co
SUMMARY:Fisher Cats vs. Yard Goats
DESCRIPTION:\n\nJoin us after the game for a spectacular Atlas Fireworks show!\n\nFollow on MiLB First Pitch: https://stza.co/+vLpE-1w\n\nShop: https://stza.co/+vLpE-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:UNH Night
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Yard Goats
<2018-09-01 Sat 18:05-21:05>
:PROPERTIES:
:ID:       Sx5-5f3Kj26JUHpavmlZWB72@stanza.co
:LOCATION: Earth\, Wind and Fireworks
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Yard Goats Join us after the game for a spectacular Earth, Wind and Fireworks show courtesy of Atlas Fireworks!

Hood Kid's Club Members will get to participate in a pre-game whiffle ball game on the field before the game!

Follow on MiLB First Pitch  https //stza.co/+vLpH-3F

Shop  https //stza.co/+vLpH-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Yard Goats
END:VALARM
DTSTART:20180901T230500Z
DTEND:20180902T020500Z
UID:Sx5-5f3Kj26JUHpavmlZWB72@stanza.co
SUMMARY:Fisher Cats vs. Yard Goats
DESCRIPTION:Join us after the game for a spectacular Earth, Wind and Fireworks show courtesy of Atlas Fireworks!\n\nHood Kid's Club Members will get to participate in a pre-game whiffle ball game on the field before the game!\n\nFollow on MiLB First Pitch: https://stza.co/+vLpH-3F\n\nShop: https://stza.co/+vLpH-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Earth\, Wind and Fireworks
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Yard Goats
<2018-09-02 Sun 12:35-15:35>
:PROPERTIES:
:ID:       IYiymjC1Q7blnJv5sHovyg21@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Yard Goats Join us for a special pre-game catch on the field from 12 15pm - 12 45pm!

Kids run the bases after every Sunday day game!

Follow on MiLB First Pitch  https //stza.co/+vLpI-1a

Shop  https //stza.co/+vLpI-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Yard Goats
END:VALARM
DTSTART:20180902T173500Z
DTEND:20180902T203500Z
UID:IYiymjC1Q7blnJv5sHovyg21@stanza.co
SUMMARY:Fisher Cats vs. Yard Goats
DESCRIPTION:Join us for a special pre-game catch on the field from 12:15pm - 12:45pm!\n\nKids run the bases after every Sunday day game!\n\nFollow on MiLB First Pitch: https://stza.co/+vLpI-1a\n\nShop: https://stza.co/+vLpI-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Fisher Cats vs. Yard Goats
<2018-09-03 Mon 12:35-15:35>
:PROPERTIES:
:ID:       3tlKzjD0s46cGTH6Wdk_W4u7@stanza.co
:LOCATION: Fan Appreciation Day
:STATUS:   CONFIRMED
:END:

Fisher Cats vs. Yard Goats It's our final game of the season.  Join us for a day of FEROCIOUS FUN and come help us celebrate the end of our 15th season!

Follow on MiLB First Pitch  https //stza.co/+vLpK-

Shop  https //stza.co/+vLpK-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fisher Cats vs. Yard Goats
END:VALARM
DTSTART:20180903T173500Z
DTEND:20180903T203500Z
UID:3tlKzjD0s46cGTH6Wdk_W4u7@stanza.co
SUMMARY:Fisher Cats vs. Yard Goats
DESCRIPTION:It's our final game of the season.  Join us for a day of FEROCIOUS FUN and come help us celebrate the end of our 15th season!\n\nFollow on MiLB First Pitch: https://stza.co/+vLpK-\n\nShop: https://stza.co/+vLpK-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fan Appreciation Day
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
