#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Cyclones @ Yankees
<2018-06-15 Fri>--<2018-06-14 Thu>
:PROPERTIES:
:ID:       jhXMMRn0VS249hQD8cOFoLDV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones @ Yankees Cyclones @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xMkx-2D

Shop  https //stza.co/+xMkx-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180615
DTEND;VALUE=DATE:20180615
UID:jhXMMRn0VS249hQD8cOFoLDV@stanza.co
SUMMARY:Cyclones @ Yankees
DESCRIPTION:Cyclones @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMkx-2D\n\nShop: https://stza.co/+xMkx-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. Yankees
<2018-06-16 Sat>--<2018-06-15 Fri>
:PROPERTIES:
:ID:       omeRtAP3KuMmEeBLOu7jIp-K@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cyclones vs. Yankees Cyclones vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xMj7-1l

Shop  https //stza.co/+xMj7-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. Yankees
END:VALARM
DTSTART;VALUE=DATE:20180616
DTEND;VALUE=DATE:20180616
UID:omeRtAP3KuMmEeBLOu7jIp-K@stanza.co
SUMMARY:Cyclones vs. Yankees
DESCRIPTION:Cyclones vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMj7-1l\n\nShop: https://stza.co/+xMj7-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ Yankees
<2018-06-17 Sun>--<2018-06-16 Sat>
:PROPERTIES:
:ID:       3XW1oeb14O-2awtMiARqra5r@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones @ Yankees Cyclones @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xMky-1t

Shop  https //stza.co/+xMky-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180617
DTEND;VALUE=DATE:20180617
UID:3XW1oeb14O-2awtMiARqra5r@stanza.co
SUMMARY:Cyclones @ Yankees
DESCRIPTION:Cyclones @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMky-1t\n\nShop: https://stza.co/+xMky-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. Renegades
<2018-06-18 Mon>--<2018-06-17 Sun>
:PROPERTIES:
:ID:       BZDdMlcRxqGwLAPz96_9zf7D@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones vs. Renegades Cyclones vs. Renegades

Follow on MiLB First Pitch  https //stza.co/+xMja-1O

Shop  https //stza.co/+xMja-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. Renegades
END:VALARM
DTSTART;VALUE=DATE:20180618
DTEND;VALUE=DATE:20180618
UID:BZDdMlcRxqGwLAPz96_9zf7D@stanza.co
SUMMARY:Cyclones vs. Renegades
DESCRIPTION:Cyclones vs. Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xMja-1O\n\nShop: https://stza.co/+xMja-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. Renegades
<2018-06-19 Tue>--<2018-06-18 Mon>
:PROPERTIES:
:ID:       zNlK5hdO3mcCmZIw5lfhJ4Ao@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cyclones vs. Renegades Cyclones vs. Renegades

Follow on MiLB First Pitch  https //stza.co/+xMjb-3p

Shop  https //stza.co/+xMjb-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. Renegades
END:VALARM
DTSTART;VALUE=DATE:20180619
DTEND;VALUE=DATE:20180619
UID:zNlK5hdO3mcCmZIw5lfhJ4Ao@stanza.co
SUMMARY:Cyclones vs. Renegades
DESCRIPTION:Cyclones vs. Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xMjb-3p\n\nShop: https://stza.co/+xMjb-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. Renegades
<2018-06-20 Wed>--<2018-06-19 Tue>
:PROPERTIES:
:ID:       gZmFohaY_QKv_lUJ9TufaJ92@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones vs. Renegades Cyclones vs. Renegades

Follow on MiLB First Pitch  https //stza.co/+xMje-2p

Shop  https //stza.co/+xMje-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. Renegades
END:VALARM
DTSTART;VALUE=DATE:20180620
DTEND;VALUE=DATE:20180620
UID:gZmFohaY_QKv_lUJ9TufaJ92@stanza.co
SUMMARY:Cyclones vs. Renegades
DESCRIPTION:Cyclones vs. Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xMje-2p\n\nShop: https://stza.co/+xMje-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ Tigers
<2018-06-21 Thu>--<2018-06-20 Wed>
:PROPERTIES:
:ID:       _p6xg1LOifqz5LZD5YOR4vmg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones @ Tigers Cyclones @ Tigers

Follow on MiLB First Pitch  https //stza.co/+xMkj-3r

Shop  https //stza.co/+xMkj-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ Tigers
END:VALARM
DTSTART;VALUE=DATE:20180621
DTEND;VALUE=DATE:20180621
UID:_p6xg1LOifqz5LZD5YOR4vmg@stanza.co
SUMMARY:Cyclones @ Tigers
DESCRIPTION:Cyclones @ Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMkj-3r\n\nShop: https://stza.co/+xMkj-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ Tigers
<2018-06-22 Fri>--<2018-06-21 Thu>
:PROPERTIES:
:ID:       vHFqBwhbxDy80t9wQxSY2NfN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cyclones @ Tigers Cyclones @ Tigers

Follow on MiLB First Pitch  https //stza.co/+xMkk-2F

Shop  https //stza.co/+xMkk-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ Tigers
END:VALARM
DTSTART;VALUE=DATE:20180622
DTEND;VALUE=DATE:20180622
UID:vHFqBwhbxDy80t9wQxSY2NfN@stanza.co
SUMMARY:Cyclones @ Tigers
DESCRIPTION:Cyclones @ Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMkk-2F\n\nShop: https://stza.co/+xMkk-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ Tigers
<2018-06-23 Sat>--<2018-06-22 Fri>
:PROPERTIES:
:ID:       QmDyNqKeIsEJD1tA4TTUhLeK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones @ Tigers Cyclones @ Tigers

Follow on MiLB First Pitch  https //stza.co/+xMkl-1Y

Shop  https //stza.co/+xMkl-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ Tigers
END:VALARM
DTSTART;VALUE=DATE:20180623
DTEND;VALUE=DATE:20180623
UID:QmDyNqKeIsEJD1tA4TTUhLeK@stanza.co
SUMMARY:Cyclones @ Tigers
DESCRIPTION:Cyclones @ Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMkl-1Y\n\nShop: https://stza.co/+xMkl-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. Spinners
<2018-06-24 Sun>--<2018-06-23 Sat>
:PROPERTIES:
:ID:       e1FViD3jorUZIAz66NHkB328@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones vs. Spinners Cyclones vs. Spinners

Follow on MiLB First Pitch  https //stza.co/+xMjg-2F

Shop  https //stza.co/+xMjg-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. Spinners
END:VALARM
DTSTART;VALUE=DATE:20180624
DTEND;VALUE=DATE:20180624
UID:e1FViD3jorUZIAz66NHkB328@stanza.co
SUMMARY:Cyclones vs. Spinners
DESCRIPTION:Cyclones vs. Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMjg-2F\n\nShop: https://stza.co/+xMjg-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. Spinners
<2018-06-25 Mon>--<2018-06-24 Sun>
:PROPERTIES:
:ID:       Ka9e99oSX7drIgSUYsj7SdOk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cyclones vs. Spinners Cyclones vs. Spinners

Follow on MiLB First Pitch  https //stza.co/+xMji-1u

Shop  https //stza.co/+xMji-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. Spinners
END:VALARM
DTSTART;VALUE=DATE:20180625
DTEND;VALUE=DATE:20180625
UID:Ka9e99oSX7drIgSUYsj7SdOk@stanza.co
SUMMARY:Cyclones vs. Spinners
DESCRIPTION:Cyclones vs. Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMji-1u\n\nShop: https://stza.co/+xMji-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. Spinners
<2018-06-26 Tue>--<2018-06-25 Mon>
:PROPERTIES:
:ID:       lT9aAFT2H5B1uYf2xSwP4a9Y@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones vs. Spinners Cyclones vs. Spinners

Follow on MiLB First Pitch  https //stza.co/+xMjk-C

Shop  https //stza.co/+xMjk-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. Spinners
END:VALARM
DTSTART;VALUE=DATE:20180626
DTEND;VALUE=DATE:20180626
UID:lT9aAFT2H5B1uYf2xSwP4a9Y@stanza.co
SUMMARY:Cyclones vs. Spinners
DESCRIPTION:Cyclones vs. Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMjk-C\n\nShop: https://stza.co/+xMjk-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ Lake Monsters
<2018-06-28 Thu>--<2018-06-27 Wed>
:PROPERTIES:
:ID:       uAXdE5_w0U276IQcqgMrNBI6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones @ Lake Monsters Cyclones @ Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMkJ-3y

Shop  https //stza.co/+xMkJ-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180628
DTEND;VALUE=DATE:20180628
UID:uAXdE5_w0U276IQcqgMrNBI6@stanza.co
SUMMARY:Cyclones @ Lake Monsters
DESCRIPTION:Cyclones @ Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMkJ-3y\n\nShop: https://stza.co/+xMkJ-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ Lake Monsters
<2018-06-29 Fri>--<2018-06-28 Thu>
:PROPERTIES:
:ID:       5yYGR4721C02rb9QtVWZlUSl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cyclones @ Lake Monsters Cyclones @ Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMkK-p

Shop  https //stza.co/+xMkK-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180629
DTEND;VALUE=DATE:20180629
UID:5yYGR4721C02rb9QtVWZlUSl@stanza.co
SUMMARY:Cyclones @ Lake Monsters
DESCRIPTION:Cyclones @ Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMkK-p\n\nShop: https://stza.co/+xMkK-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ Lake Monsters
<2018-06-30 Sat>--<2018-06-29 Fri>
:PROPERTIES:
:ID:       1xl1-CqoCdONW5HHLIbb0s5B@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones @ Lake Monsters Cyclones @ Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMkL-7

Shop  https //stza.co/+xMkL-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180630
DTEND;VALUE=DATE:20180630
UID:1xl1-CqoCdONW5HHLIbb0s5B@stanza.co
SUMMARY:Cyclones @ Lake Monsters
DESCRIPTION:Cyclones @ Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMkL-7\n\nShop: https://stza.co/+xMkL-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. Yankees
<2018-07-01 Sun>--<2018-06-30 Sat>
:PROPERTIES:
:ID:       NWCnVS5t9f9f7ZeGj4JFgmEW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones vs. Yankees Cyclones vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xMjl-c

Shop  https //stza.co/+xMjl-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. Yankees
END:VALARM
DTSTART;VALUE=DATE:20180701
DTEND;VALUE=DATE:20180701
UID:NWCnVS5t9f9f7ZeGj4JFgmEW@stanza.co
SUMMARY:Cyclones vs. Yankees
DESCRIPTION:Cyclones vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMjl-c\n\nShop: https://stza.co/+xMjl-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ Yankees
<2018-07-02 Mon>--<2018-07-01 Sun>
:PROPERTIES:
:ID:       TX3xqtDKPipf6XLyEyz0MXFP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cyclones @ Yankees Cyclones @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xMkz-2o

Shop  https //stza.co/+xMkz-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180702
DTEND;VALUE=DATE:20180702
UID:TX3xqtDKPipf6XLyEyz0MXFP@stanza.co
SUMMARY:Cyclones @ Yankees
DESCRIPTION:Cyclones @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMkz-2o\n\nShop: https://stza.co/+xMkz-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. Yankees
<2018-07-03 Tue>--<2018-07-02 Mon>
:PROPERTIES:
:ID:       JcsD_Q35fHAR4lxefUksGNzz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones vs. Yankees Cyclones vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xMjn-2S

Shop  https //stza.co/+xMjn-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. Yankees
END:VALARM
DTSTART;VALUE=DATE:20180703
DTEND;VALUE=DATE:20180703
UID:JcsD_Q35fHAR4lxefUksGNzz@stanza.co
SUMMARY:Cyclones vs. Yankees
DESCRIPTION:Cyclones vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMjn-2S\n\nShop: https://stza.co/+xMjn-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. IronBirds
<2018-07-04 Wed>--<2018-07-03 Tue>
:PROPERTIES:
:ID:       kVNlLYfJcoxWtFzzFBIS-ZuX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones vs. IronBirds Cyclones vs. IronBirds

Follow on MiLB First Pitch  https //stza.co/+xMjq-k

Shop  https //stza.co/+xMjq-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. IronBirds
END:VALARM
DTSTART;VALUE=DATE:20180704
DTEND;VALUE=DATE:20180704
UID:kVNlLYfJcoxWtFzzFBIS-ZuX@stanza.co
SUMMARY:Cyclones vs. IronBirds
DESCRIPTION:Cyclones vs. IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xMjq-k\n\nShop: https://stza.co/+xMjq-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. IronBirds
<2018-07-05 Thu>--<2018-07-04 Wed>
:PROPERTIES:
:ID:       0-mxBC7f5LfdISuWuzHNtMmu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cyclones vs. IronBirds Cyclones vs. IronBirds

Follow on MiLB First Pitch  https //stza.co/+xMjr-1s

Shop  https //stza.co/+xMjr-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. IronBirds
END:VALARM
DTSTART;VALUE=DATE:20180705
DTEND;VALUE=DATE:20180705
UID:0-mxBC7f5LfdISuWuzHNtMmu@stanza.co
SUMMARY:Cyclones vs. IronBirds
DESCRIPTION:Cyclones vs. IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xMjr-1s\n\nShop: https://stza.co/+xMjr-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. IronBirds
<2018-07-06 Fri>--<2018-07-05 Thu>
:PROPERTIES:
:ID:       EIZXlvkUG5BjcgS22YlzEclp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones vs. IronBirds Cyclones vs. IronBirds

Follow on MiLB First Pitch  https //stza.co/+xMjt-b

Shop  https //stza.co/+xMjt-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. IronBirds
END:VALARM
DTSTART;VALUE=DATE:20180706
DTEND;VALUE=DATE:20180706
UID:EIZXlvkUG5BjcgS22YlzEclp@stanza.co
SUMMARY:Cyclones vs. IronBirds
DESCRIPTION:Cyclones vs. IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xMjt-b\n\nShop: https://stza.co/+xMjt-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ Yankees
<2018-07-07 Sat>--<2018-07-06 Fri>
:PROPERTIES:
:ID:       yPo4jsT1HHcm89vWh6hJWRPc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones @ Yankees Cyclones @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xMkA-28

Shop  https //stza.co/+xMkA-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180707
DTEND;VALUE=DATE:20180707
UID:yPo4jsT1HHcm89vWh6hJWRPc@stanza.co
SUMMARY:Cyclones @ Yankees
DESCRIPTION:Cyclones @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMkA-28\n\nShop: https://stza.co/+xMkA-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. Yankees
<2018-07-08 Sun>--<2018-07-07 Sat>
:PROPERTIES:
:ID:       G_2IcH8LyQm9k-7gzs6ZoOAo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cyclones vs. Yankees Cyclones vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xMjv-1d

Shop  https //stza.co/+xMjv-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. Yankees
END:VALARM
DTSTART;VALUE=DATE:20180708
DTEND;VALUE=DATE:20180708
UID:G_2IcH8LyQm9k-7gzs6ZoOAo@stanza.co
SUMMARY:Cyclones vs. Yankees
DESCRIPTION:Cyclones vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMjv-1d\n\nShop: https://stza.co/+xMjv-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ Yankees
<2018-07-09 Mon>--<2018-07-08 Sun>
:PROPERTIES:
:ID:       3bnW5v2Q8xaRTAmRlqEFEsf4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones @ Yankees Cyclones @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xMkB-2p

Shop  https //stza.co/+xMkB-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180709
DTEND;VALUE=DATE:20180709
UID:3bnW5v2Q8xaRTAmRlqEFEsf4@stanza.co
SUMMARY:Cyclones @ Yankees
DESCRIPTION:Cyclones @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMkB-2p\n\nShop: https://stza.co/+xMkB-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ IronBirds
<2018-07-11 Wed 18:05-21:05>
:PROPERTIES:
:ID:       O9ncEIUFA5l7CUlqP-wmffi7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones @ IronBirds Cyclones @ IronBirds

Follow on MiLB First Pitch  https //stza.co/+xXTQ-3H

Shop  https //stza.co/+xXTQ-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ IronBirds
END:VALARM
DTSTART:20180711T230500Z
DTEND:20180712T020500Z
UID:O9ncEIUFA5l7CUlqP-wmffi7@stanza.co
SUMMARY:Cyclones @ IronBirds
DESCRIPTION:Cyclones @ IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xXTQ-3H\n\nShop: https://stza.co/+xXTQ-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ IronBirds
<2018-07-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       FBJnUH44dc_Kj3CEOTvtbALs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cyclones @ IronBirds Cyclones @ IronBirds

Follow on MiLB First Pitch  https //stza.co/+xXTR-1H

Shop  https //stza.co/+xXTR-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ IronBirds
END:VALARM
DTSTART:20180712T230500Z
DTEND:20180713T020500Z
UID:FBJnUH44dc_Kj3CEOTvtbALs@stanza.co
SUMMARY:Cyclones @ IronBirds
DESCRIPTION:Cyclones @ IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xXTR-1H\n\nShop: https://stza.co/+xXTR-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ IronBirds
<2018-07-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       BRrFbHYblrOHggldOsIdkvIY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones @ IronBirds Cyclones @ IronBirds

Follow on MiLB First Pitch  https //stza.co/+xXTS-1v

Shop  https //stza.co/+xXTS-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ IronBirds
END:VALARM
DTSTART:20180713T230500Z
DTEND:20180714T020500Z
UID:BRrFbHYblrOHggldOsIdkvIY@stanza.co
SUMMARY:Cyclones @ IronBirds
DESCRIPTION:Cyclones @ IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xXTS-1v\n\nShop: https://stza.co/+xXTS-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. Crosscutters
<2018-07-14 Sat>--<2018-07-13 Fri>
:PROPERTIES:
:ID:       4UCGccIREv2ccRRXbVoaHuQy@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones vs. Crosscutters Cyclones vs. Crosscutters

Follow on MiLB First Pitch  https //stza.co/+xMjy-2S

Shop  https //stza.co/+xMjy-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. Crosscutters
END:VALARM
DTSTART;VALUE=DATE:20180714
DTEND;VALUE=DATE:20180714
UID:4UCGccIREv2ccRRXbVoaHuQy@stanza.co
SUMMARY:Cyclones vs. Crosscutters
DESCRIPTION:Cyclones vs. Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+xMjy-2S\n\nShop: https://stza.co/+xMjy-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. Crosscutters
<2018-07-15 Sun>--<2018-07-14 Sat>
:PROPERTIES:
:ID:       mIhSBoMUanyJAgDImpuXt84Y@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cyclones vs. Crosscutters Cyclones vs. Crosscutters

Follow on MiLB First Pitch  https //stza.co/+xMjz-P

Shop  https //stza.co/+xMjz-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. Crosscutters
END:VALARM
DTSTART;VALUE=DATE:20180715
DTEND;VALUE=DATE:20180715
UID:mIhSBoMUanyJAgDImpuXt84Y@stanza.co
SUMMARY:Cyclones vs. Crosscutters
DESCRIPTION:Cyclones vs. Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+xMjz-P\n\nShop: https://stza.co/+xMjz-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. Crosscutters
<2018-07-16 Mon>--<2018-07-15 Sun>
:PROPERTIES:
:ID:       2LtZxILD6bDmLVIHumLcs6ad@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones vs. Crosscutters Cyclones vs. Crosscutters

Follow on MiLB First Pitch  https //stza.co/+xMjC-2r

Shop  https //stza.co/+xMjC-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. Crosscutters
END:VALARM
DTSTART;VALUE=DATE:20180716
DTEND;VALUE=DATE:20180716
UID:2LtZxILD6bDmLVIHumLcs6ad@stanza.co
SUMMARY:Cyclones vs. Crosscutters
DESCRIPTION:Cyclones vs. Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+xMjC-2r\n\nShop: https://stza.co/+xMjC-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ ValleyCats
<2018-07-17 Tue>--<2018-07-16 Mon>
:PROPERTIES:
:ID:       1hijajAfsFrIGv17Z6OPA9U1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones @ ValleyCats Cyclones @ ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMkD-x

Shop  https //stza.co/+xMkD-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180717
DTEND;VALUE=DATE:20180717
UID:1hijajAfsFrIGv17Z6OPA9U1@stanza.co
SUMMARY:Cyclones @ ValleyCats
DESCRIPTION:Cyclones @ ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMkD-x\n\nShop: https://stza.co/+xMkD-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ ValleyCats
<2018-07-18 Wed>--<2018-07-17 Tue>
:PROPERTIES:
:ID:       _qUOqfi4dFL2UJUBlCMWaCxh@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cyclones @ ValleyCats Cyclones @ ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMkE-1l

Shop  https //stza.co/+xMkE-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180718
DTEND;VALUE=DATE:20180718
UID:_qUOqfi4dFL2UJUBlCMWaCxh@stanza.co
SUMMARY:Cyclones @ ValleyCats
DESCRIPTION:Cyclones @ ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMkE-1l\n\nShop: https://stza.co/+xMkE-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ ValleyCats
<2018-07-19 Thu>--<2018-07-18 Wed>
:PROPERTIES:
:ID:       MpGf1EjoP9SfEniQY0VsHYw_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones @ ValleyCats Cyclones @ ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMkF-38

Shop  https //stza.co/+xMkF-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180719
DTEND;VALUE=DATE:20180719
UID:MpGf1EjoP9SfEniQY0VsHYw_@stanza.co
SUMMARY:Cyclones @ ValleyCats
DESCRIPTION:Cyclones @ ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMkF-38\n\nShop: https://stza.co/+xMkF-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. Spinners
<2018-07-20 Fri>--<2018-07-19 Thu>
:PROPERTIES:
:ID:       ZxOx7UDs1rV5dDu1XVAs4dMJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones vs. Spinners Cyclones vs. Spinners

Follow on MiLB First Pitch  https //stza.co/+xMjE-37

Shop  https //stza.co/+xMjE-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. Spinners
END:VALARM
DTSTART;VALUE=DATE:20180720
DTEND;VALUE=DATE:20180720
UID:ZxOx7UDs1rV5dDu1XVAs4dMJ@stanza.co
SUMMARY:Cyclones vs. Spinners
DESCRIPTION:Cyclones vs. Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMjE-37\n\nShop: https://stza.co/+xMjE-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. Spinners
<2018-07-21 Sat>--<2018-07-20 Fri>
:PROPERTIES:
:ID:       8LoOKa0xpyNFnyUXsA6YOVGD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cyclones vs. Spinners Cyclones vs. Spinners

Follow on MiLB First Pitch  https //stza.co/+xMjF-1d

Shop  https //stza.co/+xMjF-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. Spinners
END:VALARM
DTSTART;VALUE=DATE:20180721
DTEND;VALUE=DATE:20180721
UID:8LoOKa0xpyNFnyUXsA6YOVGD@stanza.co
SUMMARY:Cyclones vs. Spinners
DESCRIPTION:Cyclones vs. Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMjF-1d\n\nShop: https://stza.co/+xMjF-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. Spinners
<2018-07-22 Sun>--<2018-07-21 Sat>
:PROPERTIES:
:ID:       nwbFiWmU1u1PvWAIMvmDKrRE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones vs. Spinners Cyclones vs. Spinners

Follow on MiLB First Pitch  https //stza.co/+xMjI-11

Shop  https //stza.co/+xMjI-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. Spinners
END:VALARM
DTSTART;VALUE=DATE:20180722
DTEND;VALUE=DATE:20180722
UID:nwbFiWmU1u1PvWAIMvmDKrRE@stanza.co
SUMMARY:Cyclones vs. Spinners
DESCRIPTION:Cyclones vs. Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMjI-11\n\nShop: https://stza.co/+xMjI-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ Scrappers
<2018-07-24 Tue>--<2018-07-23 Mon>
:PROPERTIES:
:ID:       3IxEImxjmiJzHhO7I8BZ1sIb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones @ Scrappers Cyclones @ Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMku-c

Shop  https //stza.co/+xMku-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180724
DTEND;VALUE=DATE:20180724
UID:3IxEImxjmiJzHhO7I8BZ1sIb@stanza.co
SUMMARY:Cyclones @ Scrappers
DESCRIPTION:Cyclones @ Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMku-c\n\nShop: https://stza.co/+xMku-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ Scrappers
<2018-07-25 Wed>--<2018-07-24 Tue>
:PROPERTIES:
:ID:       fR31ON03Bd9wIzgTS70rumwp@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cyclones @ Scrappers Cyclones @ Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMkv-3K

Shop  https //stza.co/+xMkv-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180725
DTEND;VALUE=DATE:20180725
UID:fR31ON03Bd9wIzgTS70rumwp@stanza.co
SUMMARY:Cyclones @ Scrappers
DESCRIPTION:Cyclones @ Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMkv-3K\n\nShop: https://stza.co/+xMkv-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ Scrappers
<2018-07-26 Thu>--<2018-07-25 Wed>
:PROPERTIES:
:ID:       129rdcKnZiH8OR0Fp_odWPOP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones @ Scrappers Cyclones @ Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMkw-X

Shop  https //stza.co/+xMkw-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180726
DTEND;VALUE=DATE:20180726
UID:129rdcKnZiH8OR0Fp_odWPOP@stanza.co
SUMMARY:Cyclones @ Scrappers
DESCRIPTION:Cyclones @ Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMkw-X\n\nShop: https://stza.co/+xMkw-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ Black Bears
<2018-07-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       nuYUIiHRTNwGHShvekk4xs01@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones @ Black Bears Cyclones @ Black Bears

Follow on MiLB First Pitch  https //stza.co/+xV_u-X

Shop  https //stza.co/+xV_u-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ Black Bears
END:VALARM
DTSTART:20180727T230500Z
DTEND:20180728T020500Z
UID:nuYUIiHRTNwGHShvekk4xs01@stanza.co
SUMMARY:Cyclones @ Black Bears
DESCRIPTION:Cyclones @ Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xV_u-X\n\nShop: https://stza.co/+xV_u-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ Black Bears
<2018-07-28 Sat 18:05-21:05>
:PROPERTIES:
:ID:       s9kp0IKPXPp2uhjy90D17Urk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cyclones @ Black Bears Cyclones @ Black Bears

Follow on MiLB First Pitch  https //stza.co/+xV_v-13

Shop  https //stza.co/+xV_v-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ Black Bears
END:VALARM
DTSTART:20180728T230500Z
DTEND:20180729T020500Z
UID:s9kp0IKPXPp2uhjy90D17Urk@stanza.co
SUMMARY:Cyclones @ Black Bears
DESCRIPTION:Cyclones @ Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xV_v-13\n\nShop: https://stza.co/+xV_v-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ Black Bears
<2018-07-29 Sun 15:05-18:05>
:PROPERTIES:
:ID:       bPFgmNexSD8mS8wSsRwJJGQC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones @ Black Bears Cyclones @ Black Bears

Follow on MiLB First Pitch  https //stza.co/+xV_w-3q

Shop  https //stza.co/+xV_w-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ Black Bears
END:VALARM
DTSTART:20180729T200500Z
DTEND:20180729T230500Z
UID:bPFgmNexSD8mS8wSsRwJJGQC@stanza.co
SUMMARY:Cyclones @ Black Bears
DESCRIPTION:Cyclones @ Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xV_w-3q\n\nShop: https://stza.co/+xV_w-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. ValleyCats
<2018-07-30 Mon>--<2018-07-29 Sun>
:PROPERTIES:
:ID:       f1FVs3CIqgI_lyY5Pk0Cp6wB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones vs. ValleyCats Cyclones vs. ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMjK-1Z

Shop  https //stza.co/+xMjK-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180730
DTEND;VALUE=DATE:20180730
UID:f1FVs3CIqgI_lyY5Pk0Cp6wB@stanza.co
SUMMARY:Cyclones vs. ValleyCats
DESCRIPTION:Cyclones vs. ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMjK-1Z\n\nShop: https://stza.co/+xMjK-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. ValleyCats
<2018-07-31 Tue>--<2018-07-30 Mon>
:PROPERTIES:
:ID:       LLtufdz-K2upSJkmlyhv-f6p@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cyclones vs. ValleyCats Cyclones vs. ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMjM-3v

Shop  https //stza.co/+xMjM-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180731
DTEND;VALUE=DATE:20180731
UID:LLtufdz-K2upSJkmlyhv-f6p@stanza.co
SUMMARY:Cyclones vs. ValleyCats
DESCRIPTION:Cyclones vs. ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMjM-3v\n\nShop: https://stza.co/+xMjM-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. ValleyCats
<2018-08-01 Wed>--<2018-07-31 Tue>
:PROPERTIES:
:ID:       8lAK06hfM-lSCdG7P-FTmMRE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones vs. ValleyCats Cyclones vs. ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMjO-1M

Shop  https //stza.co/+xMjO-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180801
DTEND;VALUE=DATE:20180801
UID:8lAK06hfM-lSCdG7P-FTmMRE@stanza.co
SUMMARY:Cyclones vs. ValleyCats
DESCRIPTION:Cyclones vs. ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMjO-1M\n\nShop: https://stza.co/+xMjO-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. IronBirds
<2018-08-02 Thu>--<2018-08-01 Wed>
:PROPERTIES:
:ID:       98SdEYReyG6SarRvWVJkavey@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones vs. IronBirds Cyclones vs. IronBirds

Follow on MiLB First Pitch  https //stza.co/+xMjQ-1p

Shop  https //stza.co/+xMjQ-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. IronBirds
END:VALARM
DTSTART;VALUE=DATE:20180802
DTEND;VALUE=DATE:20180802
UID:98SdEYReyG6SarRvWVJkavey@stanza.co
SUMMARY:Cyclones vs. IronBirds
DESCRIPTION:Cyclones vs. IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xMjQ-1p\n\nShop: https://stza.co/+xMjQ-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. IronBirds
<2018-08-03 Fri>--<2018-08-02 Thu>
:PROPERTIES:
:ID:       C2K07GNloISb_JRuUCradlfJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cyclones vs. IronBirds Cyclones vs. IronBirds

Follow on MiLB First Pitch  https //stza.co/+xMjR-26

Shop  https //stza.co/+xMjR-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. IronBirds
END:VALARM
DTSTART;VALUE=DATE:20180803
DTEND;VALUE=DATE:20180803
UID:C2K07GNloISb_JRuUCradlfJ@stanza.co
SUMMARY:Cyclones vs. IronBirds
DESCRIPTION:Cyclones vs. IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xMjR-26\n\nShop: https://stza.co/+xMjR-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. IronBirds
<2018-08-04 Sat>--<2018-08-03 Fri>
:PROPERTIES:
:ID:       K5H7-Q5HnBB6wZPH_IuODrTp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones vs. IronBirds Cyclones vs. IronBirds

Follow on MiLB First Pitch  https //stza.co/+xMjT-3v

Shop  https //stza.co/+xMjT-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. IronBirds
END:VALARM
DTSTART;VALUE=DATE:20180804
DTEND;VALUE=DATE:20180804
UID:K5H7-Q5HnBB6wZPH_IuODrTp@stanza.co
SUMMARY:Cyclones vs. IronBirds
DESCRIPTION:Cyclones vs. IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xMjT-3v\n\nShop: https://stza.co/+xMjT-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ Renegades
<2018-08-05 Sun 16:05-19:05>
:PROPERTIES:
:ID:       rM1u_Jl1MdGFYrc9M8Q_o3v3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones @ Renegades Cyclones @ Renegades

Follow on MiLB First Pitch  https //stza.co/+xV_o-11

Shop  https //stza.co/+xV_o-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ Renegades
END:VALARM
DTSTART:20180805T210500Z
DTEND:20180806T000500Z
UID:rM1u_Jl1MdGFYrc9M8Q_o3v3@stanza.co
SUMMARY:Cyclones @ Renegades
DESCRIPTION:Cyclones @ Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xV_o-11\n\nShop: https://stza.co/+xV_o-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ Renegades
<2018-08-06 Mon 18:05-21:05>
:PROPERTIES:
:ID:       vFV59nLXlPLmxih7J47vxVe0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cyclones @ Renegades Cyclones @ Renegades

Follow on MiLB First Pitch  https //stza.co/+xV_p-2L

Shop  https //stza.co/+xV_p-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ Renegades
END:VALARM
DTSTART:20180806T230500Z
DTEND:20180807T020500Z
UID:vFV59nLXlPLmxih7J47vxVe0@stanza.co
SUMMARY:Cyclones @ Renegades
DESCRIPTION:Cyclones @ Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xV_p-2L\n\nShop: https://stza.co/+xV_p-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ Renegades
<2018-08-07 Tue 18:05-21:05>
:PROPERTIES:
:ID:       XB5mn0qYXW5X1YGbsbLfwZ98@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones @ Renegades Cyclones @ Renegades

Follow on MiLB First Pitch  https //stza.co/+xV_q-2a

Shop  https //stza.co/+xV_q-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ Renegades
END:VALARM
DTSTART:20180807T230500Z
DTEND:20180808T020500Z
UID:XB5mn0qYXW5X1YGbsbLfwZ98@stanza.co
SUMMARY:Cyclones @ Renegades
DESCRIPTION:Cyclones @ Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xV_q-2a\n\nShop: https://stza.co/+xV_q-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. Tigers
<2018-08-08 Wed>--<2018-08-07 Tue>
:PROPERTIES:
:ID:       GJ5CZ3g8SVF7XF3MriN5TaL_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones vs. Tigers Cyclones vs. Tigers

Follow on MiLB First Pitch  https //stza.co/+xMjW-w

Shop  https //stza.co/+xMjW-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. Tigers
END:VALARM
DTSTART;VALUE=DATE:20180808
DTEND;VALUE=DATE:20180808
UID:GJ5CZ3g8SVF7XF3MriN5TaL_@stanza.co
SUMMARY:Cyclones vs. Tigers
DESCRIPTION:Cyclones vs. Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMjW-w\n\nShop: https://stza.co/+xMjW-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. Tigers
<2018-08-09 Thu>--<2018-08-08 Wed>
:PROPERTIES:
:ID:       YHg-fPjInd4hfPMc-ffOE478@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cyclones vs. Tigers Cyclones vs. Tigers

Follow on MiLB First Pitch  https //stza.co/+xMjX-1O

Shop  https //stza.co/+xMjX-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. Tigers
END:VALARM
DTSTART;VALUE=DATE:20180809
DTEND;VALUE=DATE:20180809
UID:YHg-fPjInd4hfPMc-ffOE478@stanza.co
SUMMARY:Cyclones vs. Tigers
DESCRIPTION:Cyclones vs. Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMjX-1O\n\nShop: https://stza.co/+xMjX-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. Tigers
<2018-08-10 Fri>--<2018-08-09 Thu>
:PROPERTIES:
:ID:       v-c06iGzTL5y6GjRmJrC8YFL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones vs. Tigers Cyclones vs. Tigers

Follow on MiLB First Pitch  https //stza.co/+xMjZ-s

Shop  https //stza.co/+xMjZ-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. Tigers
END:VALARM
DTSTART;VALUE=DATE:20180810
DTEND;VALUE=DATE:20180810
UID:v-c06iGzTL5y6GjRmJrC8YFL@stanza.co
SUMMARY:Cyclones vs. Tigers
DESCRIPTION:Cyclones vs. Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMjZ-s\n\nShop: https://stza.co/+xMjZ-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ Spinners
<2018-08-11 Sat>--<2018-08-10 Fri>
:PROPERTIES:
:ID:       T13PpdF-9Sxw6SzxZlnM34lB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones @ Spinners Cyclones @ Spinners

Follow on MiLB First Pitch  https //stza.co/+xMks-d

Shop  https //stza.co/+xMks-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ Spinners
END:VALARM
DTSTART;VALUE=DATE:20180811
DTEND;VALUE=DATE:20180811
UID:T13PpdF-9Sxw6SzxZlnM34lB@stanza.co
SUMMARY:Cyclones @ Spinners
DESCRIPTION:Cyclones @ Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMks-d\n\nShop: https://stza.co/+xMks-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ Spinners
<2018-08-12 Sun>--<2018-08-11 Sat>
:PROPERTIES:
:ID:       x6p0z06jFob1TXVEI2LkDzj2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cyclones @ Spinners Cyclones @ Spinners

Follow on MiLB First Pitch  https //stza.co/+xMkt-g

Shop  https //stza.co/+xMkt-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ Spinners
END:VALARM
DTSTART;VALUE=DATE:20180812
DTEND;VALUE=DATE:20180812
UID:x6p0z06jFob1TXVEI2LkDzj2@stanza.co
SUMMARY:Cyclones @ Spinners
DESCRIPTION:Cyclones @ Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMkt-g\n\nShop: https://stza.co/+xMkt-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. Lake Monsters
<2018-08-15 Wed>--<2018-08-14 Tue>
:PROPERTIES:
:ID:       CDqTt-TE7tSL200NKReL3VbH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones vs. Lake Monsters Cyclones vs. Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMj$-2N

Shop  https //stza.co/+xMj$-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180815
DTEND;VALUE=DATE:20180815
UID:CDqTt-TE7tSL200NKReL3VbH@stanza.co
SUMMARY:Cyclones vs. Lake Monsters
DESCRIPTION:Cyclones vs. Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMj$-2N\n\nShop: https://stza.co/+xMj$-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. Lake Monsters
<2018-08-16 Thu>--<2018-08-15 Wed>
:PROPERTIES:
:ID:       q5mwJOEiXJlnSSRGLRM3gvxr@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones vs. Lake Monsters Cyclones vs. Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMk1-T

Shop  https //stza.co/+xMk1-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180816
DTEND;VALUE=DATE:20180816
UID:q5mwJOEiXJlnSSRGLRM3gvxr@stanza.co
SUMMARY:Cyclones vs. Lake Monsters
DESCRIPTION:Cyclones vs. Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMk1-T\n\nShop: https://stza.co/+xMk1-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ Renegades
<2018-08-17 Fri 18:05-21:05>
:PROPERTIES:
:ID:       KAZsxAljhuN5oKu9WyO4uYJV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cyclones @ Renegades Cyclones @ Renegades

Follow on MiLB First Pitch  https //stza.co/+xV_r-1Z

Shop  https //stza.co/+xV_r-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ Renegades
END:VALARM
DTSTART:20180817T230500Z
DTEND:20180818T020500Z
UID:KAZsxAljhuN5oKu9WyO4uYJV@stanza.co
SUMMARY:Cyclones @ Renegades
DESCRIPTION:Cyclones @ Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xV_r-1Z\n\nShop: https://stza.co/+xV_r-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ Renegades
<2018-08-18 Sat 17:05-20:05>
:PROPERTIES:
:ID:       3OigtwEav0-Vm6Sue7OJ9-Kn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones @ Renegades Cyclones @ Renegades

Follow on MiLB First Pitch  https //stza.co/+xV_s-2C

Shop  https //stza.co/+xV_s-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ Renegades
END:VALARM
DTSTART:20180818T220500Z
DTEND:20180819T010500Z
UID:3OigtwEav0-Vm6Sue7OJ9-Kn@stanza.co
SUMMARY:Cyclones @ Renegades
DESCRIPTION:Cyclones @ Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xV_s-2C\n\nShop: https://stza.co/+xV_s-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ Renegades
<2018-08-19 Sun 16:05-19:05>
:PROPERTIES:
:ID:       h6rzG1V3u4CVuKUptfBEn7_s@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones @ Renegades Cyclones @ Renegades

Follow on MiLB First Pitch  https //stza.co/+xV_t-3H

Shop  https //stza.co/+xV_t-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ Renegades
END:VALARM
DTSTART:20180819T210500Z
DTEND:20180820T000500Z
UID:h6rzG1V3u4CVuKUptfBEn7_s@stanza.co
SUMMARY:Cyclones @ Renegades
DESCRIPTION:Cyclones @ Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xV_t-3H\n\nShop: https://stza.co/+xV_t-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ ValleyCats
<2018-08-20 Mon>--<2018-08-19 Sun>
:PROPERTIES:
:ID:       1CMB37rB9q-YQ16hccij1nKV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cyclones @ ValleyCats Cyclones @ ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMkG-3h

Shop  https //stza.co/+xMkG-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180820
DTEND;VALUE=DATE:20180820
UID:1CMB37rB9q-YQ16hccij1nKV@stanza.co
SUMMARY:Cyclones @ ValleyCats
DESCRIPTION:Cyclones @ ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMkG-3h\n\nShop: https://stza.co/+xMkG-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ ValleyCats
<2018-08-21 Tue>--<2018-08-20 Mon>
:PROPERTIES:
:ID:       b5ve94gdDnK8k6Hhl_44OUMW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones @ ValleyCats Cyclones @ ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMkH-2m

Shop  https //stza.co/+xMkH-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180821
DTEND;VALUE=DATE:20180821
UID:b5ve94gdDnK8k6Hhl_44OUMW@stanza.co
SUMMARY:Cyclones @ ValleyCats
DESCRIPTION:Cyclones @ ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMkH-2m\n\nShop: https://stza.co/+xMkH-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ ValleyCats
<2018-08-22 Wed>--<2018-08-21 Tue>
:PROPERTIES:
:ID:       L-pKCI8VI7BC1nIjmRMoj7bJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones @ ValleyCats Cyclones @ ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMkI-b

Shop  https //stza.co/+xMkI-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180822
DTEND;VALUE=DATE:20180822
UID:L-pKCI8VI7BC1nIjmRMoj7bJ@stanza.co
SUMMARY:Cyclones @ ValleyCats
DESCRIPTION:Cyclones @ ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMkI-b\n\nShop: https://stza.co/+xMkI-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. Tigers
<2018-08-23 Thu>--<2018-08-22 Wed>
:PROPERTIES:
:ID:       uGWUzPqySZveH8qT_BK3YZ-b@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cyclones vs. Tigers Cyclones vs. Tigers

Follow on MiLB First Pitch  https //stza.co/+xMk3-39

Shop  https //stza.co/+xMk3-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. Tigers
END:VALARM
DTSTART;VALUE=DATE:20180823
DTEND;VALUE=DATE:20180823
UID:uGWUzPqySZveH8qT_BK3YZ-b@stanza.co
SUMMARY:Cyclones vs. Tigers
DESCRIPTION:Cyclones vs. Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMk3-39\n\nShop: https://stza.co/+xMk3-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. Tigers
<2018-08-24 Fri>--<2018-08-23 Thu>
:PROPERTIES:
:ID:       aMj7PakxOhzEMunTRrp1yZBy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones vs. Tigers Cyclones vs. Tigers

Follow on MiLB First Pitch  https //stza.co/+xMk6-3e

Shop  https //stza.co/+xMk6-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. Tigers
END:VALARM
DTSTART;VALUE=DATE:20180824
DTEND;VALUE=DATE:20180824
UID:aMj7PakxOhzEMunTRrp1yZBy@stanza.co
SUMMARY:Cyclones vs. Tigers
DESCRIPTION:Cyclones vs. Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMk6-3e\n\nShop: https://stza.co/+xMk6-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. Tigers
<2018-08-25 Sat>--<2018-08-24 Fri>
:PROPERTIES:
:ID:       V2Ec0HSH4GDKX1ziXL6Gx65_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones vs. Tigers Cyclones vs. Tigers

Follow on MiLB First Pitch  https //stza.co/+xMk8-3j

Shop  https //stza.co/+xMk8-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. Tigers
END:VALARM
DTSTART;VALUE=DATE:20180825
DTEND;VALUE=DATE:20180825
UID:V2Ec0HSH4GDKX1ziXL6Gx65_@stanza.co
SUMMARY:Cyclones vs. Tigers
DESCRIPTION:Cyclones vs. Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMk8-3j\n\nShop: https://stza.co/+xMk8-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ Lake Monsters
<2018-08-26 Sun>--<2018-08-25 Sat>
:PROPERTIES:
:ID:       uqoTG4yPBO8A8WzwOnYZjfDo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cyclones @ Lake Monsters Cyclones @ Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMkM-3q

Shop  https //stza.co/+xMkM-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180826
DTEND;VALUE=DATE:20180826
UID:uqoTG4yPBO8A8WzwOnYZjfDo@stanza.co
SUMMARY:Cyclones @ Lake Monsters
DESCRIPTION:Cyclones @ Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMkM-3q\n\nShop: https://stza.co/+xMkM-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ Lake Monsters
<2018-08-27 Mon>--<2018-08-26 Sun>
:PROPERTIES:
:ID:       2hI9ZA2NZxWsW_3xHNKJE0iE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones @ Lake Monsters Cyclones @ Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMkN-3M

Shop  https //stza.co/+xMkN-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180827
DTEND;VALUE=DATE:20180827
UID:2hI9ZA2NZxWsW_3xHNKJE0iE@stanza.co
SUMMARY:Cyclones @ Lake Monsters
DESCRIPTION:Cyclones @ Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMkN-3M\n\nShop: https://stza.co/+xMkN-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ Lake Monsters
<2018-08-28 Tue>--<2018-08-27 Mon>
:PROPERTIES:
:ID:       1MKOk4ZeBsru3JkPqL_liPda@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones @ Lake Monsters Cyclones @ Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMkO-3U

Shop  https //stza.co/+xMkO-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180828
DTEND;VALUE=DATE:20180828
UID:1MKOk4ZeBsru3JkPqL_liPda@stanza.co
SUMMARY:Cyclones @ Lake Monsters
DESCRIPTION:Cyclones @ Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMkO-3U\n\nShop: https://stza.co/+xMkO-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. Renegades
<2018-08-29 Wed>--<2018-08-28 Tue>
:PROPERTIES:
:ID:       _21WyrLZlFjd1kriEA-PJyPf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cyclones vs. Renegades Cyclones vs. Renegades

Follow on MiLB First Pitch  https //stza.co/+xMka-2V

Shop  https //stza.co/+xMka-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. Renegades
END:VALARM
DTSTART;VALUE=DATE:20180829
DTEND;VALUE=DATE:20180829
UID:_21WyrLZlFjd1kriEA-PJyPf@stanza.co
SUMMARY:Cyclones vs. Renegades
DESCRIPTION:Cyclones vs. Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xMka-2V\n\nShop: https://stza.co/+xMka-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. Renegades
<2018-08-30 Thu>--<2018-08-29 Wed>
:PROPERTIES:
:ID:       ZeNBzCjt5AOpl8OqmHfbTLbk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones vs. Renegades Cyclones vs. Renegades

Follow on MiLB First Pitch  https //stza.co/+xMkc-3H

Shop  https //stza.co/+xMkc-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. Renegades
END:VALARM
DTSTART;VALUE=DATE:20180830
DTEND;VALUE=DATE:20180830
UID:ZeNBzCjt5AOpl8OqmHfbTLbk@stanza.co
SUMMARY:Cyclones vs. Renegades
DESCRIPTION:Cyclones vs. Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xMkc-3H\n\nShop: https://stza.co/+xMkc-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. Renegades
<2018-08-31 Fri>--<2018-08-30 Thu>
:PROPERTIES:
:ID:       eRU6aWQ0IPm1aZHjGcA_7_v4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones vs. Renegades Cyclones vs. Renegades

Follow on MiLB First Pitch  https //stza.co/+xMkd-3e

Shop  https //stza.co/+xMkd-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. Renegades
END:VALARM
DTSTART;VALUE=DATE:20180831
DTEND;VALUE=DATE:20180831
UID:eRU6aWQ0IPm1aZHjGcA_7_v4@stanza.co
SUMMARY:Cyclones vs. Renegades
DESCRIPTION:Cyclones vs. Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xMkd-3e\n\nShop: https://stza.co/+xMkd-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. Yankees
<2018-09-01 Sat>--<2018-08-31 Fri>
:PROPERTIES:
:ID:       3BGb-F0x1p7vw6NuBLPWd34f@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cyclones vs. Yankees Cyclones vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xMkf-2G

Shop  https //stza.co/+xMkf-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. Yankees
END:VALARM
DTSTART;VALUE=DATE:20180901
DTEND;VALUE=DATE:20180901
UID:3BGb-F0x1p7vw6NuBLPWd34f@stanza.co
SUMMARY:Cyclones vs. Yankees
DESCRIPTION:Cyclones vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMkf-2G\n\nShop: https://stza.co/+xMkf-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones @ Yankees
<2018-09-02 Sun>--<2018-09-01 Sat>
:PROPERTIES:
:ID:       AKjJYTed6eljC7AL5q9MNG6z@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones @ Yankees Cyclones @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xMkC-2H

Shop  https //stza.co/+xMkC-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cyclones @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180902
DTEND;VALUE=DATE:20180902
UID:AKjJYTed6eljC7AL5q9MNG6z@stanza.co
SUMMARY:Cyclones @ Yankees
DESCRIPTION:Cyclones @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMkC-2H\n\nShop: https://stza.co/+xMkC-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Cyclones vs. Yankees
<2018-09-03 Mon>--<2018-09-02 Sun>
:PROPERTIES:
:ID:       dAsWmUeVagQaEudYsA4mHct9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cyclones vs. Yankees Cyclones vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xMki-1w

Shop  https //stza.co/+xMki-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cyclones vs. Yankees
END:VALARM
DTSTART;VALUE=DATE:20180903
DTEND;VALUE=DATE:20180903
UID:dAsWmUeVagQaEudYsA4mHct9@stanza.co
SUMMARY:Cyclones vs. Yankees
DESCRIPTION:Cyclones vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMki-1w\n\nShop: https://stza.co/+xMki-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
