#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Ports vs. Storm
<2018-04-05 Thu 21:10>--<2018-04-06 Fri 00:10>
:PROPERTIES:
:ID:       RvCDshjDSoa7IHQQ8GiXwgIl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Storm Ports vs. Storm

Follow on MiLB First Pitch  https //stza.co/+vM2o-1A

Shop  https //stza.co/+vM2o-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Storm
END:VALARM
DTSTART:20180406T021000Z
DTEND:20180406T051000Z
UID:RvCDshjDSoa7IHQQ8GiXwgIl@stanza.co
SUMMARY:Ports vs. Storm
DESCRIPTION:Ports vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+vM2o-1A\n\nShop: https://stza.co/+vM2o-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Storm
<2018-04-06 Fri 21:10>--<2018-04-07 Sat 00:10>
:PROPERTIES:
:ID:       GSgykfJxIC3a6UhIiAE8hzTa@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports vs. Storm Ports vs. Storm

Follow on MiLB First Pitch  https //stza.co/+vM2r-1y

Shop  https //stza.co/+vM2r-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Storm
END:VALARM
DTSTART:20180407T021000Z
DTEND:20180407T051000Z
UID:GSgykfJxIC3a6UhIiAE8hzTa@stanza.co
SUMMARY:Ports vs. Storm
DESCRIPTION:Ports vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+vM2r-1y\n\nShop: https://stza.co/+vM2r-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Storm
<2018-04-07 Sat 21:10>--<2018-04-08 Sun 00:10>
:PROPERTIES:
:ID:       D91ET2iWzdXCk39aG907laYi@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Storm Ports vs. Storm

Follow on MiLB First Pitch  https //stza.co/+vM2s-2H

Shop  https //stza.co/+vM2s-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Storm
END:VALARM
DTSTART:20180408T021000Z
DTEND:20180408T051000Z
UID:D91ET2iWzdXCk39aG907laYi@stanza.co
SUMMARY:Ports vs. Storm
DESCRIPTION:Ports vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+vM2s-2H\n\nShop: https://stza.co/+vM2s-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Storm
<2018-04-08 Sun 16:09-19:09>
:PROPERTIES:
:ID:       CgNshQmmO5A56d2ES8JXxw8U@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Storm Ports vs. Storm

Follow on MiLB First Pitch  https //stza.co/+vM2v-3a

Shop  https //stza.co/+vM2v-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Storm
END:VALARM
DTSTART:20180408T210900Z
DTEND:20180409T000900Z
UID:CgNshQmmO5A56d2ES8JXxw8U@stanza.co
SUMMARY:Ports vs. Storm
DESCRIPTION:Ports vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+vM2v-3a\n\nShop: https://stza.co/+vM2v-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Quakes
<2018-04-09 Mon 21:10>--<2018-04-10 Tue 00:10>
:PROPERTIES:
:ID:       IyvIGQAhYAPBGwEu6xynRxJm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports vs. Quakes Ports vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+vM2w-1R

Shop  https //stza.co/+vM2w-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Quakes
END:VALARM
DTSTART:20180410T021000Z
DTEND:20180410T051000Z
UID:IyvIGQAhYAPBGwEu6xynRxJm@stanza.co
SUMMARY:Ports vs. Quakes
DESCRIPTION:Ports vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+vM2w-1R\n\nShop: https://stza.co/+vM2w-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Quakes
<2018-04-10 Tue 13:10-16:10>
:PROPERTIES:
:ID:       NGKUUA2Epr4BquKlS5xOfvzd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Quakes Ports vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+vM2y-37

Shop  https //stza.co/+vM2y-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Quakes
END:VALARM
DTSTART:20180410T181000Z
DTEND:20180410T211000Z
UID:NGKUUA2Epr4BquKlS5xOfvzd@stanza.co
SUMMARY:Ports vs. Quakes
DESCRIPTION:Ports vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+vM2y-37\n\nShop: https://stza.co/+vM2y-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Quakes
<2018-04-11 Wed 21:10>--<2018-04-12 Thu 00:10>
:PROPERTIES:
:ID:       tV4xdAzvkbIa8hHmOReiIfHl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Quakes Ports vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+vM2A-h

Shop  https //stza.co/+vM2A-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Quakes
END:VALARM
DTSTART:20180412T021000Z
DTEND:20180412T051000Z
UID:tV4xdAzvkbIa8hHmOReiIfHl@stanza.co
SUMMARY:Ports vs. Quakes
DESCRIPTION:Ports vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+vM2A-h\n\nShop: https://stza.co/+vM2A-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Giants
<2018-04-12 Thu 21:00>--<2018-04-13 Fri 00:00>
:PROPERTIES:
:ID:       n2yBwtXXZGclDJI1l5iXXwZy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports @ Giants Ports @ Giants

Follow on MiLB First Pitch  https //stza.co/+xEYB-r

Shop  https //stza.co/+xEYB-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Giants
END:VALARM
DTSTART:20180413T020000Z
DTEND:20180413T050000Z
UID:n2yBwtXXZGclDJI1l5iXXwZy@stanza.co
SUMMARY:Ports @ Giants
DESCRIPTION:Ports @ Giants\n\nFollow on MiLB First Pitch: https://stza.co/+xEYB-r\n\nShop: https://stza.co/+xEYB-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Giants
<2018-04-13 Fri 21:00>--<2018-04-14 Sat 00:00>
:PROPERTIES:
:ID:       Mkl2fesPNW2LvwO8siQUU6Gr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Giants Ports @ Giants

Follow on MiLB First Pitch  https //stza.co/+xEYC-2d

Shop  https //stza.co/+xEYC-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Giants
END:VALARM
DTSTART:20180414T020000Z
DTEND:20180414T050000Z
UID:Mkl2fesPNW2LvwO8siQUU6Gr@stanza.co
SUMMARY:Ports @ Giants
DESCRIPTION:Ports @ Giants\n\nFollow on MiLB First Pitch: https://stza.co/+xEYC-2d\n\nShop: https://stza.co/+xEYC-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Giants
<2018-04-14 Sat 20:00-23:00>
:PROPERTIES:
:ID:       INgA3HivlmN2fljIg9I7ZOnb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Giants Ports @ Giants

Follow on MiLB First Pitch  https //stza.co/+xKKL-3W

Shop  https //stza.co/+xKKL-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Giants
END:VALARM
DTSTART:20180415T010000Z
DTEND:20180415T040000Z
UID:INgA3HivlmN2fljIg9I7ZOnb@stanza.co
SUMMARY:Ports @ Giants
DESCRIPTION:Ports @ Giants\n\nFollow on MiLB First Pitch: https://stza.co/+xKKL-3W\n\nShop: https://stza.co/+xKKL-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Giants
<2018-04-15 Sun 15:00-18:00>
:PROPERTIES:
:ID:       3PMQ8jAbo5anwj4tSSf8HivL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports @ Giants Ports @ Giants

Follow on MiLB First Pitch  https //stza.co/+xEYE-1Z

Shop  https //stza.co/+xEYE-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Giants
END:VALARM
DTSTART:20180415T200000Z
DTEND:20180415T230000Z
UID:3PMQ8jAbo5anwj4tSSf8HivL@stanza.co
SUMMARY:Ports @ Giants
DESCRIPTION:Ports @ Giants\n\nFollow on MiLB First Pitch: https://stza.co/+xEYE-1Z\n\nShop: https://stza.co/+xEYE-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Nuts
<2018-04-16 Mon 21:05>--<2018-04-17 Tue 00:05>
:PROPERTIES:
:ID:       eRH-YQd51QYSocMv2GeKFMFa@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Nuts Ports @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xA0h-1m

Shop  https //stza.co/+xA0h-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Nuts
END:VALARM
DTSTART:20180417T020500Z
DTEND:20180417T050500Z
UID:eRH-YQd51QYSocMv2GeKFMFa@stanza.co
SUMMARY:Ports @ Nuts
DESCRIPTION:Ports @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xA0h-1m\n\nShop: https://stza.co/+xA0h-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Nuts
<2018-04-17 Tue 21:05>--<2018-04-18 Wed 00:05>
:PROPERTIES:
:ID:       tZZ1hKf9hGH0Eozpx99cpeLu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Nuts Ports @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xA0j-H

Shop  https //stza.co/+xA0j-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Nuts
END:VALARM
DTSTART:20180418T020500Z
DTEND:20180418T050500Z
UID:tZZ1hKf9hGH0Eozpx99cpeLu@stanza.co
SUMMARY:Ports @ Nuts
DESCRIPTION:Ports @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xA0j-H\n\nShop: https://stza.co/+xA0j-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Nuts
<2018-04-18 Wed 21:05>--<2018-04-19 Thu 00:05>
:PROPERTIES:
:ID:       K7V1VfAeBdV-YcbcN0taQkks@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports @ Nuts Ports @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xB3h-G

Shop  https //stza.co/+xB3h-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Nuts
END:VALARM
DTSTART:20180419T020500Z
DTEND:20180419T050500Z
UID:K7V1VfAeBdV-YcbcN0taQkks@stanza.co
SUMMARY:Ports @ Nuts
DESCRIPTION:Ports @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xB3h-G\n\nShop: https://stza.co/+xB3h-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Rawhide
<2018-04-19 Thu 21:10>--<2018-04-20 Fri 00:10>
:PROPERTIES:
:ID:       Xos-zLrbxqp_9c0xfrYftXMr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Rawhide Ports vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM2C-2t

Shop  https //stza.co/+vM2C-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Rawhide
END:VALARM
DTSTART:20180420T021000Z
DTEND:20180420T051000Z
UID:Xos-zLrbxqp_9c0xfrYftXMr@stanza.co
SUMMARY:Ports vs. Rawhide
DESCRIPTION:Ports vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM2C-2t\n\nShop: https://stza.co/+vM2C-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Rawhide
<2018-04-20 Fri 21:10>--<2018-04-21 Sat 00:10>
:PROPERTIES:
:ID:       os_DMUq6cRnYbWeNSfN29JZS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Rawhide Ports vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM2F-18

Shop  https //stza.co/+vM2F-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Rawhide
END:VALARM
DTSTART:20180421T021000Z
DTEND:20180421T051000Z
UID:os_DMUq6cRnYbWeNSfN29JZS@stanza.co
SUMMARY:Ports vs. Rawhide
DESCRIPTION:Ports vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM2F-18\n\nShop: https://stza.co/+vM2F-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Rawhide
<2018-04-21 Sat 21:10>--<2018-04-22 Sun 00:10>
:PROPERTIES:
:ID:       mxf0GZ4uhW6muI_xehcNt0Zb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports vs. Rawhide Ports vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM2H-1H

Shop  https //stza.co/+vM2H-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Rawhide
END:VALARM
DTSTART:20180422T021000Z
DTEND:20180422T051000Z
UID:mxf0GZ4uhW6muI_xehcNt0Zb@stanza.co
SUMMARY:Ports vs. Rawhide
DESCRIPTION:Ports vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM2H-1H\n\nShop: https://stza.co/+vM2H-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Rawhide
<2018-04-22 Sun 16:09-19:09>
:PROPERTIES:
:ID:       iirLF2QIEVWZfAufXYHy8pV9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Rawhide Ports vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM2J-2G

Shop  https //stza.co/+vM2J-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Rawhide
END:VALARM
DTSTART:20180422T210900Z
DTEND:20180423T000900Z
UID:iirLF2QIEVWZfAufXYHy8pV9@stanza.co
SUMMARY:Ports vs. Rawhide
DESCRIPTION:Ports vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM2J-2G\n\nShop: https://stza.co/+vM2J-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Quakes
<2018-04-24 Tue 21:05>--<2018-04-25 Wed 00:05>
:PROPERTIES:
:ID:       YPwEXMvm3rVpLBc0aeOThrBQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Quakes Ports @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xA1b-H

Shop  https //stza.co/+xA1b-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Quakes
END:VALARM
DTSTART:20180425T020500Z
DTEND:20180425T050500Z
UID:YPwEXMvm3rVpLBc0aeOThrBQ@stanza.co
SUMMARY:Ports @ Quakes
DESCRIPTION:Ports @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xA1b-H\n\nShop: https://stza.co/+xA1b-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Quakes
<2018-04-25 Wed 21:05>--<2018-04-26 Thu 00:05>
:PROPERTIES:
:ID:       6oIqWgPCKSvHyRL5GCZ4nSa8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports @ Quakes Ports @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xA1e-1j

Shop  https //stza.co/+xA1e-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Quakes
END:VALARM
DTSTART:20180426T020500Z
DTEND:20180426T050500Z
UID:6oIqWgPCKSvHyRL5GCZ4nSa8@stanza.co
SUMMARY:Ports @ Quakes
DESCRIPTION:Ports @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xA1e-1j\n\nShop: https://stza.co/+xA1e-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Quakes
<2018-04-26 Thu 21:05>--<2018-04-27 Fri 00:05>
:PROPERTIES:
:ID:       A-Sa5dx9c55aRmw0TfRTAazC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Quakes Ports @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xA1h-2u

Shop  https //stza.co/+xA1h-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Quakes
END:VALARM
DTSTART:20180427T020500Z
DTEND:20180427T050500Z
UID:A-Sa5dx9c55aRmw0TfRTAazC@stanza.co
SUMMARY:Ports @ Quakes
DESCRIPTION:Ports @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xA1h-2u\n\nShop: https://stza.co/+xA1h-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Storm
<2018-04-27 Fri 21:00>--<2018-04-28 Sat 00:00>
:PROPERTIES:
:ID:       rwVO8ZQOSeps4GmaTnDQ5Owd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Storm Ports @ Storm

Follow on MiLB First Pitch  https //stza.co/+xA0d-37

Shop  https //stza.co/+xA0d-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Storm
END:VALARM
DTSTART:20180428T020000Z
DTEND:20180428T050000Z
UID:rwVO8ZQOSeps4GmaTnDQ5Owd@stanza.co
SUMMARY:Ports @ Storm
DESCRIPTION:Ports @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xA0d-37\n\nShop: https://stza.co/+xA0d-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Storm
<2018-04-28 Sat 20:00-23:00>
:PROPERTIES:
:ID:       VWbOpfGuYCctCLoS7HIGs-K_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports @ Storm Ports @ Storm

Follow on MiLB First Pitch  https //stza.co/+xA0e-2X

Shop  https //stza.co/+xA0e-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Storm
END:VALARM
DTSTART:20180429T010000Z
DTEND:20180429T040000Z
UID:VWbOpfGuYCctCLoS7HIGs-K_@stanza.co
SUMMARY:Ports @ Storm
DESCRIPTION:Ports @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xA0e-2X\n\nShop: https://stza.co/+xA0e-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Storm
<2018-04-29 Sun>--<2018-04-28 Sat>
:PROPERTIES:
:ID:       eFIhrUp0sfrgpMX_h2Lwn1p_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Storm Ports @ Storm

Follow on MiLB First Pitch  https //stza.co/+vfvG-3X

Shop  https //stza.co/+vfvG-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Storm
END:VALARM
DTSTART;VALUE=DATE:20180429
DTEND;VALUE=DATE:20180429
UID:eFIhrUp0sfrgpMX_h2Lwn1p_@stanza.co
SUMMARY:Ports @ Storm
DESCRIPTION:Ports @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+vfvG-3X\n\nShop: https://stza.co/+vfvG-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. JetHawks
<2018-04-30 Mon 21:10>--<2018-05-01 Tue 00:10>
:PROPERTIES:
:ID:       -H-1uJ1xwvHa3cjVH9N-wJ5G@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. JetHawks Ports vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+vM2L-1V

Shop  https //stza.co/+vM2L-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. JetHawks
END:VALARM
DTSTART:20180501T021000Z
DTEND:20180501T051000Z
UID:-H-1uJ1xwvHa3cjVH9N-wJ5G@stanza.co
SUMMARY:Ports vs. JetHawks
DESCRIPTION:Ports vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vM2L-1V\n\nShop: https://stza.co/+vM2L-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. JetHawks
<2018-05-01 Tue 21:10>--<2018-05-02 Wed 00:10>
:PROPERTIES:
:ID:       SGQUl_YY8-EoDfQa1ANwf6eC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports vs. JetHawks Ports vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+vM2N-C

Shop  https //stza.co/+vM2N-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. JetHawks
END:VALARM
DTSTART:20180502T021000Z
DTEND:20180502T051000Z
UID:SGQUl_YY8-EoDfQa1ANwf6eC@stanza.co
SUMMARY:Ports vs. JetHawks
DESCRIPTION:Ports vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vM2N-C\n\nShop: https://stza.co/+vM2N-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. JetHawks
<2018-05-02 Wed 21:10>--<2018-05-03 Thu 00:10>
:PROPERTIES:
:ID:       03SaJqhZ-dbot-r3kYwu4dYN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. JetHawks Ports vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+vM2O-1L

Shop  https //stza.co/+vM2O-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. JetHawks
END:VALARM
DTSTART:20180503T021000Z
DTEND:20180503T051000Z
UID:03SaJqhZ-dbot-r3kYwu4dYN@stanza.co
SUMMARY:Ports vs. JetHawks
DESCRIPTION:Ports vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vM2O-1L\n\nShop: https://stza.co/+vM2O-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. JetHawks
<2018-05-03 Thu 13:10-16:10>
:PROPERTIES:
:ID:       41MP6PMFUBPFJVnm_O31qKLc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. JetHawks Ports vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+vM2Q-p

Shop  https //stza.co/+vM2Q-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. JetHawks
END:VALARM
DTSTART:20180503T181000Z
DTEND:20180503T211000Z
UID:41MP6PMFUBPFJVnm_O31qKLc@stanza.co
SUMMARY:Ports vs. JetHawks
DESCRIPTION:Ports vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vM2Q-p\n\nShop: https://stza.co/+vM2Q-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. 66ers
<2018-05-04 Fri 21:10>--<2018-05-05 Sat 00:10>
:PROPERTIES:
:ID:       p82SDdw7aEUJv4RWU8LQqtxR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports vs. 66ers Ports vs. 66ers

Follow on MiLB First Pitch  https //stza.co/+vM2S-3w

Shop  https //stza.co/+vM2S-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. 66ers
END:VALARM
DTSTART:20180505T021000Z
DTEND:20180505T051000Z
UID:p82SDdw7aEUJv4RWU8LQqtxR@stanza.co
SUMMARY:Ports vs. 66ers
DESCRIPTION:Ports vs. 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+vM2S-3w\n\nShop: https://stza.co/+vM2S-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. 66ers
<2018-05-05 Sat 21:10>--<2018-05-06 Sun 00:10>
:PROPERTIES:
:ID:       Qe1gSFdppTFNuaxiM90ONqYA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. 66ers Ports vs. 66ers

Follow on MiLB First Pitch  https //stza.co/+vM2U-32

Shop  https //stza.co/+vM2U-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. 66ers
END:VALARM
DTSTART:20180506T021000Z
DTEND:20180506T051000Z
UID:Qe1gSFdppTFNuaxiM90ONqYA@stanza.co
SUMMARY:Ports vs. 66ers
DESCRIPTION:Ports vs. 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+vM2U-32\n\nShop: https://stza.co/+vM2U-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. 66ers
<2018-05-06 Sun 16:09-19:09>
:PROPERTIES:
:ID:       JwySWkC8vW1qfGGanedNlIx2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. 66ers Ports vs. 66ers

Follow on MiLB First Pitch  https //stza.co/+vM2X-u

Shop  https //stza.co/+vM2X-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. 66ers
END:VALARM
DTSTART:20180506T210900Z
DTEND:20180507T000900Z
UID:JwySWkC8vW1qfGGanedNlIx2@stanza.co
SUMMARY:Ports vs. 66ers
DESCRIPTION:Ports vs. 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+vM2X-u\n\nShop: https://stza.co/+vM2X-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Rawhide
<2018-05-08 Tue>--<2018-05-07 Mon>
:PROPERTIES:
:ID:       g7cAreRDF8NUYPucMKQgsinQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports @ Rawhide Ports @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM4A-

Shop  https //stza.co/+vM4A-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180508
DTEND;VALUE=DATE:20180508
UID:g7cAreRDF8NUYPucMKQgsinQ@stanza.co
SUMMARY:Ports @ Rawhide
DESCRIPTION:Ports @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM4A-\n\nShop: https://stza.co/+vM4A-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Rawhide
<2018-05-09 Wed>--<2018-05-08 Tue>
:PROPERTIES:
:ID:       2pPD07ASSGrQ-lvOqAAveXjn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Rawhide Ports @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM4B-3g

Shop  https //stza.co/+vM4B-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180509
DTEND;VALUE=DATE:20180509
UID:2pPD07ASSGrQ-lvOqAAveXjn@stanza.co
SUMMARY:Ports @ Rawhide
DESCRIPTION:Ports @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM4B-3g\n\nShop: https://stza.co/+vM4B-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Rawhide
<2018-05-10 Thu>--<2018-05-09 Wed>
:PROPERTIES:
:ID:       qo-A--iD8NwmhYrCNS2FH_Iy@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Rawhide Ports @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM4C-1y

Shop  https //stza.co/+vM4C-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180510
DTEND;VALUE=DATE:20180510
UID:qo-A--iD8NwmhYrCNS2FH_Iy@stanza.co
SUMMARY:Ports @ Rawhide
DESCRIPTION:Ports @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM4C-1y\n\nShop: https://stza.co/+vM4C-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ 66ers
<2018-05-11 Fri 21:05>--<2018-05-12 Sat 00:05>
:PROPERTIES:
:ID:       32s3nkHzzJgd6qU4o3WmDsbc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports @ 66ers Ports @ 66ers

Follow on MiLB First Pitch  https //stza.co/+y0D7-3F

Shop  https //stza.co/+y0D7-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ 66ers
END:VALARM
DTSTART:20180512T020500Z
DTEND:20180512T050500Z
UID:32s3nkHzzJgd6qU4o3WmDsbc@stanza.co
SUMMARY:Ports @ 66ers
DESCRIPTION:Ports @ 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+y0D7-3F\n\nShop: https://stza.co/+y0D7-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ 66ers
<2018-05-12 Sat 20:05-23:05>
:PROPERTIES:
:ID:       pMnbMnm7H5X_MKEPFxbbxrh2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ 66ers Ports @ 66ers

Follow on MiLB First Pitch  https //stza.co/+y0D8-d

Shop  https //stza.co/+y0D8-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ 66ers
END:VALARM
DTSTART:20180513T010500Z
DTEND:20180513T040500Z
UID:pMnbMnm7H5X_MKEPFxbbxrh2@stanza.co
SUMMARY:Ports @ 66ers
DESCRIPTION:Ports @ 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+y0D8-d\n\nShop: https://stza.co/+y0D8-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ 66ers
<2018-05-13 Sun 16:05-19:05>
:PROPERTIES:
:ID:       de11VFZxYs0nMMsRbJathm8t@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ 66ers Ports @ 66ers

Follow on MiLB First Pitch  https //stza.co/+y0D9-D

Shop  https //stza.co/+y0D9-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ 66ers
END:VALARM
DTSTART:20180513T210500Z
DTEND:20180514T000500Z
UID:de11VFZxYs0nMMsRbJathm8t@stanza.co
SUMMARY:Ports @ 66ers
DESCRIPTION:Ports @ 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+y0D9-D\n\nShop: https://stza.co/+y0D9-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ 66ers
<2018-05-14 Mon 17:00-20:00>
:PROPERTIES:
:ID:       XB4ZXy973lDMOuGemPGDE_xE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports @ 66ers Ports @ 66ers

Follow on MiLB First Pitch  https //stza.co/+y0Da-p

Shop  https //stza.co/+y0Da-1w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ 66ers
END:VALARM
DTSTART:20180514T220000Z
DTEND:20180515T010000Z
UID:XB4ZXy973lDMOuGemPGDE_xE@stanza.co
SUMMARY:Ports @ 66ers
DESCRIPTION:Ports @ 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+y0Da-p\n\nShop: https://stza.co/+y0Da-1w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Quakes
<2018-05-15 Tue 21:10>--<2018-05-16 Wed 00:10>
:PROPERTIES:
:ID:       qZxIE_uE98QpuuBUB4_CNkTZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Quakes Ports vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+vM2Z-S

Shop  https //stza.co/+vM2Z-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Quakes
END:VALARM
DTSTART:20180516T021000Z
DTEND:20180516T051000Z
UID:qZxIE_uE98QpuuBUB4_CNkTZ@stanza.co
SUMMARY:Ports vs. Quakes
DESCRIPTION:Ports vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+vM2Z-S\n\nShop: https://stza.co/+vM2Z-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Quakes
<2018-05-16 Wed 21:10>--<2018-05-17 Thu 00:10>
:PROPERTIES:
:ID:       GlhBFjWQ1__Is0Ti73RsnMw1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Quakes Ports vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+vM2_-R

Shop  https //stza.co/+vM2_-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Quakes
END:VALARM
DTSTART:20180517T021000Z
DTEND:20180517T051000Z
UID:GlhBFjWQ1__Is0Ti73RsnMw1@stanza.co
SUMMARY:Ports vs. Quakes
DESCRIPTION:Ports vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+vM2_-R\n\nShop: https://stza.co/+vM2_-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Quakes
<2018-05-17 Thu 13:10-16:10>
:PROPERTIES:
:ID:       fDTPpRFFHDwCNAdMbGbjq7kP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports vs. Quakes Ports vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+vM31-3i

Shop  https //stza.co/+vM31-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Quakes
END:VALARM
DTSTART:20180517T181000Z
DTEND:20180517T211000Z
UID:fDTPpRFFHDwCNAdMbGbjq7kP@stanza.co
SUMMARY:Ports vs. Quakes
DESCRIPTION:Ports vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+vM31-3i\n\nShop: https://stza.co/+vM31-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Giants
<2018-05-18 Fri 21:10>--<2018-05-19 Sat 00:10>
:PROPERTIES:
:ID:       xca_8m8VbcPohSdx1m2tqe7T@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Giants Ports vs. Giants

Follow on MiLB First Pitch  https //stza.co/+vM33-N

Shop  https //stza.co/+vM33-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Giants
END:VALARM
DTSTART:20180519T021000Z
DTEND:20180519T051000Z
UID:xca_8m8VbcPohSdx1m2tqe7T@stanza.co
SUMMARY:Ports vs. Giants
DESCRIPTION:Ports vs. Giants\n\nFollow on MiLB First Pitch: https://stza.co/+vM33-N\n\nShop: https://stza.co/+vM33-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Giants
<2018-05-19 Sat 21:10>--<2018-05-20 Sun 00:10>
:PROPERTIES:
:ID:       jWhp0D4HbO3V0Qf_lv2IKdRw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Giants Ports vs. Giants

Follow on MiLB First Pitch  https //stza.co/+vM35-3V

Shop  https //stza.co/+vM35-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Giants
END:VALARM
DTSTART:20180520T021000Z
DTEND:20180520T051000Z
UID:jWhp0D4HbO3V0Qf_lv2IKdRw@stanza.co
SUMMARY:Ports vs. Giants
DESCRIPTION:Ports vs. Giants\n\nFollow on MiLB First Pitch: https://stza.co/+vM35-3V\n\nShop: https://stza.co/+vM35-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Giants
<2018-05-20 Sun 16:09-19:09>
:PROPERTIES:
:ID:       7t9I2jvc1o5L_AkkUAUWL57g@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports vs. Giants Ports vs. Giants

Follow on MiLB First Pitch  https //stza.co/+vM37-2c

Shop  https //stza.co/+vM37-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Giants
END:VALARM
DTSTART:20180520T210900Z
DTEND:20180521T000900Z
UID:7t9I2jvc1o5L_AkkUAUWL57g@stanza.co
SUMMARY:Ports vs. Giants
DESCRIPTION:Ports vs. Giants\n\nFollow on MiLB First Pitch: https://stza.co/+vM37-2c\n\nShop: https://stza.co/+vM37-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Quakes
<2018-05-22 Tue 21:05>--<2018-05-23 Wed 00:05>
:PROPERTIES:
:ID:       RTRyI2jF3umpQ71pFgkxqXmF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Quakes Ports @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xA1j-2X

Shop  https //stza.co/+xA1j-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Quakes
END:VALARM
DTSTART:20180523T020500Z
DTEND:20180523T050500Z
UID:RTRyI2jF3umpQ71pFgkxqXmF@stanza.co
SUMMARY:Ports @ Quakes
DESCRIPTION:Ports @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xA1j-2X\n\nShop: https://stza.co/+xA1j-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Quakes
<2018-05-23 Wed 21:05>--<2018-05-24 Thu 00:05>
:PROPERTIES:
:ID:       y0uCjLkL_nDs2ioGd313GbIT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Quakes Ports @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xA1l-B

Shop  https //stza.co/+xA1l-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Quakes
END:VALARM
DTSTART:20180524T020500Z
DTEND:20180524T050500Z
UID:y0uCjLkL_nDs2ioGd313GbIT@stanza.co
SUMMARY:Ports @ Quakes
DESCRIPTION:Ports @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xA1l-B\n\nShop: https://stza.co/+xA1l-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Quakes
<2018-05-24 Thu 21:05>--<2018-05-25 Fri 00:05>
:PROPERTIES:
:ID:       w6x2E1rbWQJklLF_O229vOLe@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports @ Quakes Ports @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xA1n-2u

Shop  https //stza.co/+xA1n-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Quakes
END:VALARM
DTSTART:20180525T020500Z
DTEND:20180525T050500Z
UID:w6x2E1rbWQJklLF_O229vOLe@stanza.co
SUMMARY:Ports @ Quakes
DESCRIPTION:Ports @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xA1n-2u\n\nShop: https://stza.co/+xA1n-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ JetHawks
<2018-05-25 Fri 20:35-23:35>
:PROPERTIES:
:ID:       0qsKZ2a7fw1OmOERNn8SrNiL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ JetHawks Ports @ JetHawks

Follow on MiLB First Pitch  https //stza.co/+vfw1-3O

Shop  https //stza.co/+vfw1-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ JetHawks
END:VALARM
DTSTART:20180526T013500Z
DTEND:20180526T043500Z
UID:0qsKZ2a7fw1OmOERNn8SrNiL@stanza.co
SUMMARY:Ports @ JetHawks
DESCRIPTION:Ports @ JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vfw1-3O\n\nShop: https://stza.co/+vfw1-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ JetHawks
<2018-05-26 Sat 20:05-23:05>
:PROPERTIES:
:ID:       512TDo8J0kS95PcPH6d2K4mE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ JetHawks Ports @ JetHawks

Follow on MiLB First Pitch  https //stza.co/+vfw7-3U

Shop  https //stza.co/+vfw7-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ JetHawks
END:VALARM
DTSTART:20180527T010500Z
DTEND:20180527T040500Z
UID:512TDo8J0kS95PcPH6d2K4mE@stanza.co
SUMMARY:Ports @ JetHawks
DESCRIPTION:Ports @ JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vfw7-3U\n\nShop: https://stza.co/+vfw7-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ JetHawks
<2018-05-27 Sun>--<2018-05-26 Sat>
:PROPERTIES:
:ID:       MpuPgcHDosPBGcLF5B-6hDzq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports @ JetHawks Ports @ JetHawks

Follow on MiLB First Pitch  https //stza.co/+vfwc-1n

Shop  https //stza.co/+vfwc-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ JetHawks
END:VALARM
DTSTART;VALUE=DATE:20180527
DTEND;VALUE=DATE:20180527
UID:MpuPgcHDosPBGcLF5B-6hDzq@stanza.co
SUMMARY:Ports @ JetHawks
DESCRIPTION:Ports @ JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vfwc-1n\n\nShop: https://stza.co/+vfwc-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Nuts
<2018-05-28 Mon 21:10>--<2018-05-29 Tue 00:10>
:PROPERTIES:
:ID:       E5PzAjj2zFXBLSXAMKAVkWrx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Nuts Ports vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+vM39-2n

Shop  https //stza.co/+vM39-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Nuts
END:VALARM
DTSTART:20180529T021000Z
DTEND:20180529T051000Z
UID:E5PzAjj2zFXBLSXAMKAVkWrx@stanza.co
SUMMARY:Ports vs. Nuts
DESCRIPTION:Ports vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+vM39-2n\n\nShop: https://stza.co/+vM39-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Nuts
<2018-05-29 Tue 21:10>--<2018-05-30 Wed 00:10>
:PROPERTIES:
:ID:       moJGuG5jzb6C1_Rvw-CdO7dl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Nuts Ports vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+vM3b-3U

Shop  https //stza.co/+vM3b-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Nuts
END:VALARM
DTSTART:20180530T021000Z
DTEND:20180530T051000Z
UID:moJGuG5jzb6C1_Rvw-CdO7dl@stanza.co
SUMMARY:Ports vs. Nuts
DESCRIPTION:Ports vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+vM3b-3U\n\nShop: https://stza.co/+vM3b-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Nuts
<2018-05-30 Wed 21:10>--<2018-05-31 Thu 00:10>
:PROPERTIES:
:ID:       HNgi13TH9qUMA2tvO0kEjaqq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports vs. Nuts Ports vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+vM3d-3b

Shop  https //stza.co/+vM3d-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Nuts
END:VALARM
DTSTART:20180531T021000Z
DTEND:20180531T051000Z
UID:HNgi13TH9qUMA2tvO0kEjaqq@stanza.co
SUMMARY:Ports vs. Nuts
DESCRIPTION:Ports vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+vM3d-3b\n\nShop: https://stza.co/+vM3d-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Nuts
<2018-05-31 Thu 21:10>--<2018-06-01 Fri 00:10>
:PROPERTIES:
:ID:       Cey_LeEV1NM_QBE-dprbuiTb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Nuts Ports vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+vM3f-3D

Shop  https //stza.co/+vM3f-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Nuts
END:VALARM
DTSTART:20180601T021000Z
DTEND:20180601T051000Z
UID:Cey_LeEV1NM_QBE-dprbuiTb@stanza.co
SUMMARY:Ports vs. Nuts
DESCRIPTION:Ports vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+vM3f-3D\n\nShop: https://stza.co/+vM3f-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Rawhide
<2018-06-01 Fri>--<2018-05-31 Thu>
:PROPERTIES:
:ID:       noF7Q_W2CahJm3pNitrfhkPA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Rawhide Ports @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM4D-2z

Shop  https //stza.co/+vM4D-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180601
DTEND;VALUE=DATE:20180601
UID:noF7Q_W2CahJm3pNitrfhkPA@stanza.co
SUMMARY:Ports @ Rawhide
DESCRIPTION:Ports @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM4D-2z\n\nShop: https://stza.co/+vM4D-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Rawhide
<2018-06-02 Sat>--<2018-06-01 Fri>
:PROPERTIES:
:ID:       7zfdJotxKmwSp4pNKTWbULko@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports @ Rawhide Ports @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM4E-2w

Shop  https //stza.co/+vM4E-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180602
DTEND;VALUE=DATE:20180602
UID:7zfdJotxKmwSp4pNKTWbULko@stanza.co
SUMMARY:Ports @ Rawhide
DESCRIPTION:Ports @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM4E-2w\n\nShop: https://stza.co/+vM4E-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Rawhide
<2018-06-03 Sun>--<2018-06-02 Sat>
:PROPERTIES:
:ID:       S5gh51ltJ_efEzhpme_XGFqX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Rawhide Ports @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM4F-W

Shop  https //stza.co/+vM4F-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180603
DTEND;VALUE=DATE:20180603
UID:S5gh51ltJ_efEzhpme_XGFqX@stanza.co
SUMMARY:Ports @ Rawhide
DESCRIPTION:Ports @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM4F-W\n\nShop: https://stza.co/+vM4F-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Giants
<2018-06-05 Tue 20:30-23:30>
:PROPERTIES:
:ID:       FtjEMpUEcVYocgeRFctMajcc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Giants Ports @ Giants

Follow on MiLB First Pitch  https //stza.co/+xEYF-1s

Shop  https //stza.co/+xEYF-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Giants
END:VALARM
DTSTART:20180606T013000Z
DTEND:20180606T043000Z
UID:FtjEMpUEcVYocgeRFctMajcc@stanza.co
SUMMARY:Ports @ Giants
DESCRIPTION:Ports @ Giants\n\nFollow on MiLB First Pitch: https://stza.co/+xEYF-1s\n\nShop: https://stza.co/+xEYF-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Giants
<2018-06-06 Wed 20:30-23:30>
:PROPERTIES:
:ID:       5XiI67zYfLqVaqVlj9CPrTMe@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports @ Giants Ports @ Giants

Follow on MiLB First Pitch  https //stza.co/+xEYG-1z

Shop  https //stza.co/+xEYG-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Giants
END:VALARM
DTSTART:20180607T013000Z
DTEND:20180607T043000Z
UID:5XiI67zYfLqVaqVlj9CPrTMe@stanza.co
SUMMARY:Ports @ Giants
DESCRIPTION:Ports @ Giants\n\nFollow on MiLB First Pitch: https://stza.co/+xEYG-1z\n\nShop: https://stza.co/+xEYG-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Giants
<2018-06-07 Thu 14:30-17:30>
:PROPERTIES:
:ID:       Zoz7487Qc5Skimfdtp2uoYy3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Giants Ports @ Giants

Follow on MiLB First Pitch  https //stza.co/+xEYH-2X

Shop  https //stza.co/+xEYH-1w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Giants
END:VALARM
DTSTART:20180607T193000Z
DTEND:20180607T223000Z
UID:Zoz7487Qc5Skimfdtp2uoYy3@stanza.co
SUMMARY:Ports @ Giants
DESCRIPTION:Ports @ Giants\n\nFollow on MiLB First Pitch: https://stza.co/+xEYH-2X\n\nShop: https://stza.co/+xEYH-1w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Rawhide
<2018-06-08 Fri 21:10>--<2018-06-09 Sat 00:10>
:PROPERTIES:
:ID:       FfbRRykr3VCm69Ikp-Xfdvk1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Rawhide Ports vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM3h-1V

Shop  https //stza.co/+vM3h-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Rawhide
END:VALARM
DTSTART:20180609T021000Z
DTEND:20180609T051000Z
UID:FfbRRykr3VCm69Ikp-Xfdvk1@stanza.co
SUMMARY:Ports vs. Rawhide
DESCRIPTION:Ports vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM3h-1V\n\nShop: https://stza.co/+vM3h-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Rawhide
<2018-06-09 Sat 21:10>--<2018-06-10 Sun 00:10>
:PROPERTIES:
:ID:       HZYaJkW0E_p_Unq_6jdeAbKh@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports vs. Rawhide Ports vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM3i-1x

Shop  https //stza.co/+vM3i-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Rawhide
END:VALARM
DTSTART:20180610T021000Z
DTEND:20180610T051000Z
UID:HZYaJkW0E_p_Unq_6jdeAbKh@stanza.co
SUMMARY:Ports vs. Rawhide
DESCRIPTION:Ports vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM3i-1x\n\nShop: https://stza.co/+vM3i-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Rawhide
<2018-06-10 Sun 16:09-19:09>
:PROPERTIES:
:ID:       kOS4H_kBX6n9TRi5tk0uqC7m@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Rawhide Ports vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM3l-2U

Shop  https //stza.co/+vM3l-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Rawhide
END:VALARM
DTSTART:20180610T210900Z
DTEND:20180611T000900Z
UID:kOS4H_kBX6n9TRi5tk0uqC7m@stanza.co
SUMMARY:Ports vs. Rawhide
DESCRIPTION:Ports vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM3l-2U\n\nShop: https://stza.co/+vM3l-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Giants
<2018-06-11 Mon 21:10>--<2018-06-12 Tue 00:10>
:PROPERTIES:
:ID:       HJtRiKwfIpO-jQ7m8CAqGzZI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Giants Ports vs. Giants

Follow on MiLB First Pitch  https //stza.co/+vM3m-1z

Shop  https //stza.co/+vM3m-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Giants
END:VALARM
DTSTART:20180612T021000Z
DTEND:20180612T051000Z
UID:HJtRiKwfIpO-jQ7m8CAqGzZI@stanza.co
SUMMARY:Ports vs. Giants
DESCRIPTION:Ports vs. Giants\n\nFollow on MiLB First Pitch: https://stza.co/+vM3m-1z\n\nShop: https://stza.co/+vM3m-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Giants
<2018-06-12 Tue 21:10>--<2018-06-13 Wed 00:10>
:PROPERTIES:
:ID:       nYMN_JGLSELipTo8VBDq5NWy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports vs. Giants Ports vs. Giants

Follow on MiLB First Pitch  https //stza.co/+vM3p-2J

Shop  https //stza.co/+vM3p-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Giants
END:VALARM
DTSTART:20180613T021000Z
DTEND:20180613T051000Z
UID:nYMN_JGLSELipTo8VBDq5NWy@stanza.co
SUMMARY:Ports vs. Giants
DESCRIPTION:Ports vs. Giants\n\nFollow on MiLB First Pitch: https://stza.co/+vM3p-2J\n\nShop: https://stza.co/+vM3p-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Giants
<2018-06-13 Wed 21:10>--<2018-06-14 Thu 00:10>
:PROPERTIES:
:ID:       PaI8pyivUDBB31iM9IVgyW2g@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Giants Ports vs. Giants

Follow on MiLB First Pitch  https //stza.co/+vM3r-1u

Shop  https //stza.co/+vM3r-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Giants
END:VALARM
DTSTART:20180614T021000Z
DTEND:20180614T051000Z
UID:PaI8pyivUDBB31iM9IVgyW2g@stanza.co
SUMMARY:Ports vs. Giants
DESCRIPTION:Ports vs. Giants\n\nFollow on MiLB First Pitch: https://stza.co/+vM3r-1u\n\nShop: https://stza.co/+vM3r-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Giants
<2018-06-14 Thu 21:10>--<2018-06-15 Fri 00:10>
:PROPERTIES:
:ID:       LsIQtEMxy2tRq4xNFhTQRfOd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Giants Ports vs. Giants

Follow on MiLB First Pitch  https //stza.co/+vM3t-U

Shop  https //stza.co/+vM3t-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Giants
END:VALARM
DTSTART:20180615T021000Z
DTEND:20180615T051000Z
UID:LsIQtEMxy2tRq4xNFhTQRfOd@stanza.co
SUMMARY:Ports vs. Giants
DESCRIPTION:Ports vs. Giants\n\nFollow on MiLB First Pitch: https://stza.co/+vM3t-U\n\nShop: https://stza.co/+vM3t-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Nuts
<2018-06-15 Fri 21:05>--<2018-06-16 Sat 00:05>
:PROPERTIES:
:ID:       35Y-Bf2yEPjQZyUI77VnN8s6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports @ Nuts Ports @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xB3j-1F

Shop  https //stza.co/+xB3j-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Nuts
END:VALARM
DTSTART:20180616T020500Z
DTEND:20180616T050500Z
UID:35Y-Bf2yEPjQZyUI77VnN8s6@stanza.co
SUMMARY:Ports @ Nuts
DESCRIPTION:Ports @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xB3j-1F\n\nShop: https://stza.co/+xB3j-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Nuts
<2018-06-16 Sat 21:05>--<2018-06-17 Sun 00:05>
:PROPERTIES:
:ID:       h719W4y8hvVLbc89zjLuncFk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Nuts Ports @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xB3o-3a

Shop  https //stza.co/+xB3o-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Nuts
END:VALARM
DTSTART:20180617T020500Z
DTEND:20180617T050500Z
UID:h719W4y8hvVLbc89zjLuncFk@stanza.co
SUMMARY:Ports @ Nuts
DESCRIPTION:Ports @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xB3o-3a\n\nShop: https://stza.co/+xB3o-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Nuts
<2018-06-17 Sun 16:05-19:05>
:PROPERTIES:
:ID:       DlxjDeN9gN6a6DOM9of3Byjm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Nuts Ports @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xB3u-2e

Shop  https //stza.co/+xB3u-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Nuts
END:VALARM
DTSTART:20180617T210500Z
DTEND:20180618T000500Z
UID:DlxjDeN9gN6a6DOM9of3Byjm@stanza.co
SUMMARY:Ports @ Nuts
DESCRIPTION:Ports @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xB3u-2e\n\nShop: https://stza.co/+xB3u-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Nuts
<2018-06-21 Thu 21:10>--<2018-06-22 Fri 00:10>
:PROPERTIES:
:ID:       0f0kURjmsA2EHNM3D4TG3FEN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports vs. Nuts Ports vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+vM3v-2P

Shop  https //stza.co/+vM3v-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Nuts
END:VALARM
DTSTART:20180622T021000Z
DTEND:20180622T051000Z
UID:0f0kURjmsA2EHNM3D4TG3FEN@stanza.co
SUMMARY:Ports vs. Nuts
DESCRIPTION:Ports vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+vM3v-2P\n\nShop: https://stza.co/+vM3v-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Nuts
<2018-06-22 Fri 21:10>--<2018-06-23 Sat 00:10>
:PROPERTIES:
:ID:       gFjxP39qkC4N8SkEntozLk5v@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Nuts Ports vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+vM3x-2g

Shop  https //stza.co/+vM3x-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Nuts
END:VALARM
DTSTART:20180623T021000Z
DTEND:20180623T051000Z
UID:gFjxP39qkC4N8SkEntozLk5v@stanza.co
SUMMARY:Ports vs. Nuts
DESCRIPTION:Ports vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+vM3x-2g\n\nShop: https://stza.co/+vM3x-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Nuts
<2018-06-23 Sat 21:10>--<2018-06-24 Sun 00:10>
:PROPERTIES:
:ID:       BPyH-CX1Qkl8sKs0-R-bqj5p@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Nuts Ports vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+vM3y-3m

Shop  https //stza.co/+vM3y-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Nuts
END:VALARM
DTSTART:20180624T021000Z
DTEND:20180624T051000Z
UID:BPyH-CX1Qkl8sKs0-R-bqj5p@stanza.co
SUMMARY:Ports vs. Nuts
DESCRIPTION:Ports vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+vM3y-3m\n\nShop: https://stza.co/+vM3y-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Nuts
<2018-06-24 Sun 20:10-23:10>
:PROPERTIES:
:ID:       wNFg7fiwfG3BgNEIOesOt90Y@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports vs. Nuts Ports vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+vM3B-23

Shop  https //stza.co/+vM3B-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Nuts
END:VALARM
DTSTART:20180625T011000Z
DTEND:20180625T041000Z
UID:wNFg7fiwfG3BgNEIOesOt90Y@stanza.co
SUMMARY:Ports vs. Nuts
DESCRIPTION:Ports vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+vM3B-23\n\nShop: https://stza.co/+vM3B-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Giants
<2018-06-25 Mon 21:00>--<2018-06-26 Tue 00:00>
:PROPERTIES:
:ID:       7PpbRYsQY5Wfnm229B0Dlo6_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Giants Ports @ Giants

Follow on MiLB First Pitch  https //stza.co/+xEYI-2J

Shop  https //stza.co/+xEYI-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Giants
END:VALARM
DTSTART:20180626T020000Z
DTEND:20180626T050000Z
UID:7PpbRYsQY5Wfnm229B0Dlo6_@stanza.co
SUMMARY:Ports @ Giants
DESCRIPTION:Ports @ Giants\n\nFollow on MiLB First Pitch: https://stza.co/+xEYI-2J\n\nShop: https://stza.co/+xEYI-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Giants
<2018-06-26 Tue 21:00>--<2018-06-27 Wed 00:00>
:PROPERTIES:
:ID:       A2XHhv6ywVTh88lVw9a8TCPX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Giants Ports @ Giants

Follow on MiLB First Pitch  https //stza.co/+xEYJ-z

Shop  https //stza.co/+xEYJ-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Giants
END:VALARM
DTSTART:20180627T020000Z
DTEND:20180627T050000Z
UID:A2XHhv6ywVTh88lVw9a8TCPX@stanza.co
SUMMARY:Ports @ Giants
DESCRIPTION:Ports @ Giants\n\nFollow on MiLB First Pitch: https://stza.co/+xEYJ-z\n\nShop: https://stza.co/+xEYJ-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Giants
<2018-06-27 Wed 21:00>--<2018-06-28 Thu 00:00>
:PROPERTIES:
:ID:       vGPmKgoYjrdtmQryBtJ9Ffj0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports @ Giants Ports @ Giants

Follow on MiLB First Pitch  https //stza.co/+xEYK-2G

Shop  https //stza.co/+xEYK-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Giants
END:VALARM
DTSTART:20180628T020000Z
DTEND:20180628T050000Z
UID:vGPmKgoYjrdtmQryBtJ9Ffj0@stanza.co
SUMMARY:Ports @ Giants
DESCRIPTION:Ports @ Giants\n\nFollow on MiLB First Pitch: https://stza.co/+xEYK-2G\n\nShop: https://stza.co/+xEYK-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Giants
<2018-06-28 Thu 14:30-17:30>
:PROPERTIES:
:ID:       T5aSWp2tHhdM8XUeBsolCGRH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Giants Ports @ Giants

Follow on MiLB First Pitch  https //stza.co/+xEYL-27

Shop  https //stza.co/+xEYL-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Giants
END:VALARM
DTSTART:20180628T193000Z
DTEND:20180628T223000Z
UID:T5aSWp2tHhdM8XUeBsolCGRH@stanza.co
SUMMARY:Ports @ Giants
DESCRIPTION:Ports @ Giants\n\nFollow on MiLB First Pitch: https://stza.co/+xEYL-27\n\nShop: https://stza.co/+xEYL-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. JetHawks
<2018-06-29 Fri 21:10>--<2018-06-30 Sat 00:10>
:PROPERTIES:
:ID:       AZ4L7WYm_DRbjIzqPBZf5pt4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. JetHawks Ports vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+vM3C-1Q

Shop  https //stza.co/+vM3C-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. JetHawks
END:VALARM
DTSTART:20180630T021000Z
DTEND:20180630T051000Z
UID:AZ4L7WYm_DRbjIzqPBZf5pt4@stanza.co
SUMMARY:Ports vs. JetHawks
DESCRIPTION:Ports vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vM3C-1Q\n\nShop: https://stza.co/+vM3C-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. JetHawks
<2018-06-30 Sat 21:10>--<2018-07-01 Sun 00:10>
:PROPERTIES:
:ID:       HnY0Mh11vhISE5hR-JiCeZaH@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports vs. JetHawks Ports vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+vM3F-2W

Shop  https //stza.co/+vM3F-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. JetHawks
END:VALARM
DTSTART:20180701T021000Z
DTEND:20180701T051000Z
UID:HnY0Mh11vhISE5hR-JiCeZaH@stanza.co
SUMMARY:Ports vs. JetHawks
DESCRIPTION:Ports vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vM3F-2W\n\nShop: https://stza.co/+vM3F-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. JetHawks
<2018-07-01 Sun 20:10-23:10>
:PROPERTIES:
:ID:       VNM8LBrOWxvQTq_eJoAvfP94@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. JetHawks Ports vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+vM3H-V

Shop  https //stza.co/+vM3H-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. JetHawks
END:VALARM
DTSTART:20180702T011000Z
DTEND:20180702T041000Z
UID:VNM8LBrOWxvQTq_eJoAvfP94@stanza.co
SUMMARY:Ports vs. JetHawks
DESCRIPTION:Ports vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vM3H-V\n\nShop: https://stza.co/+vM3H-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. JetHawks
<2018-07-02 Mon 21:10>--<2018-07-03 Tue 00:10>
:PROPERTIES:
:ID:       Lwrdd2TTZzZTEFQ8nDN28P1L@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. JetHawks Ports vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+vM3I-1f

Shop  https //stza.co/+vM3I-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. JetHawks
END:VALARM
DTSTART:20180703T021000Z
DTEND:20180703T051000Z
UID:Lwrdd2TTZzZTEFQ8nDN28P1L@stanza.co
SUMMARY:Ports vs. JetHawks
DESCRIPTION:Ports vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vM3I-1f\n\nShop: https://stza.co/+vM3I-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. JetHawks
<2018-07-03 Tue 20:30-23:30>
:PROPERTIES:
:ID:       _BWeaDhdpXkyFNeL1rxIe4BM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports vs. JetHawks Ports vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+vM3L-1F

Shop  https //stza.co/+vM3L-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. JetHawks
END:VALARM
DTSTART:20180704T013000Z
DTEND:20180704T043000Z
UID:_BWeaDhdpXkyFNeL1rxIe4BM@stanza.co
SUMMARY:Ports vs. JetHawks
DESCRIPTION:Ports vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vM3L-1F\n\nShop: https://stza.co/+vM3L-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ 66ers
<2018-07-04 Wed 21:05>--<2018-07-05 Thu 00:05>
:PROPERTIES:
:ID:       jvgFo2nCjqkjCT0zBeFuJuJU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ 66ers Ports @ 66ers

Follow on MiLB First Pitch  https //stza.co/+y0Db-3T

Shop  https //stza.co/+y0Db-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ 66ers
END:VALARM
DTSTART:20180705T020500Z
DTEND:20180705T050500Z
UID:jvgFo2nCjqkjCT0zBeFuJuJU@stanza.co
SUMMARY:Ports @ 66ers
DESCRIPTION:Ports @ 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+y0Db-3T\n\nShop: https://stza.co/+y0Db-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ 66ers
<2018-07-05 Thu 21:05>--<2018-07-06 Fri 00:05>
:PROPERTIES:
:ID:       _hN4nG3G7VSGMB2HLCXnO-lh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ 66ers Ports @ 66ers

Follow on MiLB First Pitch  https //stza.co/+y0Dc-31

Shop  https //stza.co/+y0Dc-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ 66ers
END:VALARM
DTSTART:20180706T020500Z
DTEND:20180706T050500Z
UID:_hN4nG3G7VSGMB2HLCXnO-lh@stanza.co
SUMMARY:Ports @ 66ers
DESCRIPTION:Ports @ 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+y0Dc-31\n\nShop: https://stza.co/+y0Dc-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ 66ers
<2018-07-06 Fri 21:05>--<2018-07-07 Sat 00:05>
:PROPERTIES:
:ID:       NKi0osZFMA99B9JsSnDP7XIL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports @ 66ers Ports @ 66ers

Follow on MiLB First Pitch  https //stza.co/+y0Dd-E

Shop  https //stza.co/+y0Dd-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ 66ers
END:VALARM
DTSTART:20180707T020500Z
DTEND:20180707T050500Z
UID:NKi0osZFMA99B9JsSnDP7XIL@stanza.co
SUMMARY:Ports @ 66ers
DESCRIPTION:Ports @ 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+y0Dd-E\n\nShop: https://stza.co/+y0Dd-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ 66ers
<2018-07-07 Sat 20:05-23:05>
:PROPERTIES:
:ID:       FgBr960JtIfQ7pGmDXXnrD2h@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ 66ers Ports @ 66ers

Follow on MiLB First Pitch  https //stza.co/+y0De-1d

Shop  https //stza.co/+y0De-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ 66ers
END:VALARM
DTSTART:20180708T010500Z
DTEND:20180708T040500Z
UID:FgBr960JtIfQ7pGmDXXnrD2h@stanza.co
SUMMARY:Ports @ 66ers
DESCRIPTION:Ports @ 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+y0De-1d\n\nShop: https://stza.co/+y0De-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ 66ers
<2018-07-08 Sun 19:35-22:35>
:PROPERTIES:
:ID:       I4wk6e1S0SmBRW8JztiLyt2C@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ 66ers Ports @ 66ers

Follow on MiLB First Pitch  https //stza.co/+y0Df-3E

Shop  https //stza.co/+y0Df-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ 66ers
END:VALARM
DTSTART:20180709T003500Z
DTEND:20180709T033500Z
UID:I4wk6e1S0SmBRW8JztiLyt2C@stanza.co
SUMMARY:Ports @ 66ers
DESCRIPTION:Ports @ 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+y0Df-3E\n\nShop: https://stza.co/+y0Df-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Giants
<2018-07-09 Mon 21:10>--<2018-07-10 Tue 00:10>
:PROPERTIES:
:ID:       5flL7JV_mwdhqk2-yEfN30Br@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports vs. Giants Ports vs. Giants

Follow on MiLB First Pitch  https //stza.co/+vM3N-p

Shop  https //stza.co/+vM3N-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Giants
END:VALARM
DTSTART:20180710T021000Z
DTEND:20180710T051000Z
UID:5flL7JV_mwdhqk2-yEfN30Br@stanza.co
SUMMARY:Ports vs. Giants
DESCRIPTION:Ports vs. Giants\n\nFollow on MiLB First Pitch: https://stza.co/+vM3N-p\n\nShop: https://stza.co/+vM3N-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Giants
<2018-07-10 Tue 21:10>--<2018-07-11 Wed 00:10>
:PROPERTIES:
:ID:       sFUILZKsGU1QfZ1TJbe__ZsD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Giants Ports vs. Giants

Follow on MiLB First Pitch  https //stza.co/+vM3P-2U

Shop  https //stza.co/+vM3P-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Giants
END:VALARM
DTSTART:20180711T021000Z
DTEND:20180711T051000Z
UID:sFUILZKsGU1QfZ1TJbe__ZsD@stanza.co
SUMMARY:Ports vs. Giants
DESCRIPTION:Ports vs. Giants\n\nFollow on MiLB First Pitch: https://stza.co/+vM3P-2U\n\nShop: https://stza.co/+vM3P-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Giants
<2018-07-11 Wed 21:10>--<2018-07-12 Thu 00:10>
:PROPERTIES:
:ID:       VI5Aj2xKF5pVwlmoHJv8HRqL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Giants Ports vs. Giants

Follow on MiLB First Pitch  https //stza.co/+vM3R-d

Shop  https //stza.co/+vM3R-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Giants
END:VALARM
DTSTART:20180712T021000Z
DTEND:20180712T051000Z
UID:VI5Aj2xKF5pVwlmoHJv8HRqL@stanza.co
SUMMARY:Ports vs. Giants
DESCRIPTION:Ports vs. Giants\n\nFollow on MiLB First Pitch: https://stza.co/+vM3R-d\n\nShop: https://stza.co/+vM3R-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Giants
<2018-07-12 Thu 21:10>--<2018-07-13 Fri 00:10>
:PROPERTIES:
:ID:       r2MJvlLq55I9q2EuepJcpydm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports vs. Giants Ports vs. Giants

Follow on MiLB First Pitch  https //stza.co/+vM3T-N

Shop  https //stza.co/+vM3T-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Giants
END:VALARM
DTSTART:20180713T021000Z
DTEND:20180713T051000Z
UID:r2MJvlLq55I9q2EuepJcpydm@stanza.co
SUMMARY:Ports vs. Giants
DESCRIPTION:Ports vs. Giants\n\nFollow on MiLB First Pitch: https://stza.co/+vM3T-N\n\nShop: https://stza.co/+vM3T-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Nuts
<2018-07-13 Fri 21:05>--<2018-07-14 Sat 00:05>
:PROPERTIES:
:ID:       vdj4RPQBI_9ciOm6dXOxAd8x@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Nuts Ports @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xB3y-1d

Shop  https //stza.co/+xB3y-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Nuts
END:VALARM
DTSTART:20180714T020500Z
DTEND:20180714T050500Z
UID:vdj4RPQBI_9ciOm6dXOxAd8x@stanza.co
SUMMARY:Ports @ Nuts
DESCRIPTION:Ports @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xB3y-1d\n\nShop: https://stza.co/+xB3y-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Nuts
<2018-07-14 Sat 21:05>--<2018-07-15 Sun 00:05>
:PROPERTIES:
:ID:       J6Hy5KorZyUweGlXs8T0100j@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Nuts Ports @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xB3A-W

Shop  https //stza.co/+xB3A-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Nuts
END:VALARM
DTSTART:20180715T020500Z
DTEND:20180715T050500Z
UID:J6Hy5KorZyUweGlXs8T0100j@stanza.co
SUMMARY:Ports @ Nuts
DESCRIPTION:Ports @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xB3A-W\n\nShop: https://stza.co/+xB3A-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Nuts
<2018-07-15 Sun 20:05-23:05>
:PROPERTIES:
:ID:       JWPmArBV8hHSZhStGpgdYc_q@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports @ Nuts Ports @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xB3C-1b

Shop  https //stza.co/+xB3C-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Nuts
END:VALARM
DTSTART:20180716T010500Z
DTEND:20180716T040500Z
UID:JWPmArBV8hHSZhStGpgdYc_q@stanza.co
SUMMARY:Ports @ Nuts
DESCRIPTION:Ports @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xB3C-1b\n\nShop: https://stza.co/+xB3C-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Nuts
<2018-07-16 Mon 21:05>--<2018-07-17 Tue 00:05>
:PROPERTIES:
:ID:       VTsQYLrYad_Vo7IoUT6_S1I5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Nuts Ports @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xB3F-F

Shop  https //stza.co/+xB3F-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Nuts
END:VALARM
DTSTART:20180717T020500Z
DTEND:20180717T050500Z
UID:VTsQYLrYad_Vo7IoUT6_S1I5@stanza.co
SUMMARY:Ports @ Nuts
DESCRIPTION:Ports @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xB3F-F\n\nShop: https://stza.co/+xB3F-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. JetHawks
<2018-07-18 Wed 21:10>--<2018-07-19 Thu 00:10>
:PROPERTIES:
:ID:       Tw7UM4zua2N6VdAzG3y5sYZj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. JetHawks Ports vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+vM3U-32

Shop  https //stza.co/+vM3U-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. JetHawks
END:VALARM
DTSTART:20180719T021000Z
DTEND:20180719T051000Z
UID:Tw7UM4zua2N6VdAzG3y5sYZj@stanza.co
SUMMARY:Ports vs. JetHawks
DESCRIPTION:Ports vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vM3U-32\n\nShop: https://stza.co/+vM3U-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. JetHawks
<2018-07-19 Thu 21:10>--<2018-07-20 Fri 00:10>
:PROPERTIES:
:ID:       agiyGataamIQ2F9fKOArRt_F@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports vs. JetHawks Ports vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+vM3X-2v

Shop  https //stza.co/+vM3X-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. JetHawks
END:VALARM
DTSTART:20180720T021000Z
DTEND:20180720T051000Z
UID:agiyGataamIQ2F9fKOArRt_F@stanza.co
SUMMARY:Ports vs. JetHawks
DESCRIPTION:Ports vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vM3X-2v\n\nShop: https://stza.co/+vM3X-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. JetHawks
<2018-07-20 Fri 21:10>--<2018-07-21 Sat 00:10>
:PROPERTIES:
:ID:       9pmWSKDnXIZUSMhoxCwyCQQ2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. JetHawks Ports vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+vM3Z-p

Shop  https //stza.co/+vM3Z-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. JetHawks
END:VALARM
DTSTART:20180721T021000Z
DTEND:20180721T051000Z
UID:9pmWSKDnXIZUSMhoxCwyCQQ2@stanza.co
SUMMARY:Ports vs. JetHawks
DESCRIPTION:Ports vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vM3Z-p\n\nShop: https://stza.co/+vM3Z-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. 66ers
<2018-07-21 Sat 21:10>--<2018-07-22 Sun 00:10>
:PROPERTIES:
:ID:       rx8ghIYgJmJ1CivE-DKc2EGF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. 66ers Ports vs. 66ers

Follow on MiLB First Pitch  https //stza.co/+vM3$-3z

Shop  https //stza.co/+vM3$-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. 66ers
END:VALARM
DTSTART:20180722T021000Z
DTEND:20180722T051000Z
UID:rx8ghIYgJmJ1CivE-DKc2EGF@stanza.co
SUMMARY:Ports vs. 66ers
DESCRIPTION:Ports vs. 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+vM3$-3z\n\nShop: https://stza.co/+vM3$-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. 66ers
<2018-07-22 Sun 20:10-23:10>
:PROPERTIES:
:ID:       byXl0lTrLPW5PKz72EdNNibD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports vs. 66ers Ports vs. 66ers

Follow on MiLB First Pitch  https //stza.co/+vM40-1U

Shop  https //stza.co/+vM40-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. 66ers
END:VALARM
DTSTART:20180723T011000Z
DTEND:20180723T041000Z
UID:byXl0lTrLPW5PKz72EdNNibD@stanza.co
SUMMARY:Ports vs. 66ers
DESCRIPTION:Ports vs. 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+vM40-1U\n\nShop: https://stza.co/+vM40-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. 66ers
<2018-07-23 Mon 21:10>--<2018-07-24 Tue 00:10>
:PROPERTIES:
:ID:       xFHKIEC3zsO_rxQp28lIgI0g@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. 66ers Ports vs. 66ers

Follow on MiLB First Pitch  https //stza.co/+vM42-2j

Shop  https //stza.co/+vM42-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. 66ers
END:VALARM
DTSTART:20180724T021000Z
DTEND:20180724T051000Z
UID:xFHKIEC3zsO_rxQp28lIgI0g@stanza.co
SUMMARY:Ports vs. 66ers
DESCRIPTION:Ports vs. 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+vM42-2j\n\nShop: https://stza.co/+vM42-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Nuts
<2018-07-24 Tue 21:05>--<2018-07-25 Wed 00:05>
:PROPERTIES:
:ID:       row-EhuSOnKWoyUfz5hGx0Z5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Nuts Ports @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xB3H-A

Shop  https //stza.co/+xB3H-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Nuts
END:VALARM
DTSTART:20180725T020500Z
DTEND:20180725T050500Z
UID:row-EhuSOnKWoyUfz5hGx0Z5@stanza.co
SUMMARY:Ports @ Nuts
DESCRIPTION:Ports @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xB3H-A\n\nShop: https://stza.co/+xB3H-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Nuts
<2018-07-25 Wed 21:05>--<2018-07-26 Thu 00:05>
:PROPERTIES:
:ID:       2myv2mf8R4xbP9wJ8EEdMpbi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports @ Nuts Ports @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xB3J-3X

Shop  https //stza.co/+xB3J-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Nuts
END:VALARM
DTSTART:20180726T020500Z
DTEND:20180726T050500Z
UID:2myv2mf8R4xbP9wJ8EEdMpbi@stanza.co
SUMMARY:Ports @ Nuts
DESCRIPTION:Ports @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xB3J-3X\n\nShop: https://stza.co/+xB3J-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Nuts
<2018-07-26 Thu 21:05>--<2018-07-27 Fri 00:05>
:PROPERTIES:
:ID:       kH4f60usMPSzFLIVG5gYQ7cI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Nuts Ports @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xA0W-7

Shop  https //stza.co/+xA0W-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Nuts
END:VALARM
DTSTART:20180727T020500Z
DTEND:20180727T050500Z
UID:kH4f60usMPSzFLIVG5gYQ7cI@stanza.co
SUMMARY:Ports @ Nuts
DESCRIPTION:Ports @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xA0W-7\n\nShop: https://stza.co/+xA0W-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Storm
<2018-07-27 Fri 21:00>--<2018-07-28 Sat 00:00>
:PROPERTIES:
:ID:       WIOOK-_Myet7E3Y617BlsuG5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Storm Ports @ Storm

Follow on MiLB First Pitch  https //stza.co/+xA0f-G

Shop  https //stza.co/+xA0f-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Storm
END:VALARM
DTSTART:20180728T020000Z
DTEND:20180728T050000Z
UID:WIOOK-_Myet7E3Y617BlsuG5@stanza.co
SUMMARY:Ports @ Storm
DESCRIPTION:Ports @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xA0f-G\n\nShop: https://stza.co/+xA0f-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Storm
<2018-07-28 Sat 20:00-23:00>
:PROPERTIES:
:ID:       gSozqQ1qmO8u-_QrQYTLDZKI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports @ Storm Ports @ Storm

Follow on MiLB First Pitch  https //stza.co/+xA0g-3H

Shop  https //stza.co/+xA0g-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Storm
END:VALARM
DTSTART:20180729T010000Z
DTEND:20180729T040000Z
UID:gSozqQ1qmO8u-_QrQYTLDZKI@stanza.co
SUMMARY:Ports @ Storm
DESCRIPTION:Ports @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xA0g-3H\n\nShop: https://stza.co/+xA0g-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Storm
<2018-07-29 Sun>--<2018-07-28 Sat>
:PROPERTIES:
:ID:       ZGcyvAx-wg6g7SdiUQakk4jo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Storm Ports @ Storm

Follow on MiLB First Pitch  https //stza.co/+vfvX-1q

Shop  https //stza.co/+vfvX-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Storm
END:VALARM
DTSTART;VALUE=DATE:20180729
DTEND;VALUE=DATE:20180729
UID:ZGcyvAx-wg6g7SdiUQakk4jo@stanza.co
SUMMARY:Ports @ Storm
DESCRIPTION:Ports @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+vfvX-1q\n\nShop: https://stza.co/+vfvX-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Nuts
<2018-07-31 Tue 21:10>--<2018-08-01 Wed 00:10>
:PROPERTIES:
:ID:       IuMhHIFXLigM5WQsNSkPr3a7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Nuts Ports vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+vM45-2s

Shop  https //stza.co/+vM45-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Nuts
END:VALARM
DTSTART:20180801T021000Z
DTEND:20180801T051000Z
UID:IuMhHIFXLigM5WQsNSkPr3a7@stanza.co
SUMMARY:Ports vs. Nuts
DESCRIPTION:Ports vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+vM45-2s\n\nShop: https://stza.co/+vM45-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Nuts
<2018-08-01 Wed 21:10>--<2018-08-02 Thu 00:10>
:PROPERTIES:
:ID:       Zvy56wW1Fkkws43J3-VWGwmo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports vs. Nuts Ports vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+vM46-1h

Shop  https //stza.co/+vM46-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Nuts
END:VALARM
DTSTART:20180802T021000Z
DTEND:20180802T051000Z
UID:Zvy56wW1Fkkws43J3-VWGwmo@stanza.co
SUMMARY:Ports vs. Nuts
DESCRIPTION:Ports vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+vM46-1h\n\nShop: https://stza.co/+vM46-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Nuts
<2018-08-02 Thu 21:10>--<2018-08-03 Fri 00:10>
:PROPERTIES:
:ID:       eMOCt6sx59bGXoiqw5zSAxXX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Nuts Ports vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+vM48-K

Shop  https //stza.co/+vM48-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Nuts
END:VALARM
DTSTART:20180803T021000Z
DTEND:20180803T051000Z
UID:eMOCt6sx59bGXoiqw5zSAxXX@stanza.co
SUMMARY:Ports vs. Nuts
DESCRIPTION:Ports vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+vM48-K\n\nShop: https://stza.co/+vM48-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Rawhide
<2018-08-03 Fri>--<2018-08-02 Thu>
:PROPERTIES:
:ID:       FSyOnK_VO3z_spFcfs-pJ4SB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Rawhide Ports @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM4G-x

Shop  https //stza.co/+vM4G-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180803
DTEND;VALUE=DATE:20180803
UID:FSyOnK_VO3z_spFcfs-pJ4SB@stanza.co
SUMMARY:Ports @ Rawhide
DESCRIPTION:Ports @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM4G-x\n\nShop: https://stza.co/+vM4G-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Rawhide
<2018-08-04 Sat>--<2018-08-03 Fri>
:PROPERTIES:
:ID:       N3Xugb5z0DbdcpK7LNs6EOAR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports @ Rawhide Ports @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM4H-2I

Shop  https //stza.co/+vM4H-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180804
DTEND;VALUE=DATE:20180804
UID:N3Xugb5z0DbdcpK7LNs6EOAR@stanza.co
SUMMARY:Ports @ Rawhide
DESCRIPTION:Ports @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM4H-2I\n\nShop: https://stza.co/+vM4H-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Rawhide
<2018-08-05 Sun>--<2018-08-04 Sat>
:PROPERTIES:
:ID:       ZUZWHHbDeSs_pYmrHL7hRDJe@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Rawhide Ports @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM4I-25

Shop  https //stza.co/+vM4I-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180805
DTEND;VALUE=DATE:20180805
UID:ZUZWHHbDeSs_pYmrHL7hRDJe@stanza.co
SUMMARY:Ports @ Rawhide
DESCRIPTION:Ports @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM4I-25\n\nShop: https://stza.co/+vM4I-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Nuts
<2018-08-07 Tue 21:05>--<2018-08-08 Wed 00:05>
:PROPERTIES:
:ID:       c3IoEW-OsKU3a0fodKe6T0fk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Nuts Ports @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xA0Y-K

Shop  https //stza.co/+xA0Y-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Nuts
END:VALARM
DTSTART:20180808T020500Z
DTEND:20180808T050500Z
UID:c3IoEW-OsKU3a0fodKe6T0fk@stanza.co
SUMMARY:Ports @ Nuts
DESCRIPTION:Ports @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xA0Y-K\n\nShop: https://stza.co/+xA0Y-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Nuts
<2018-08-08 Wed 21:05>--<2018-08-09 Thu 00:05>
:PROPERTIES:
:ID:       go1xm25FizWXT5TrpfSCWc06@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports @ Nuts Ports @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xA10-a

Shop  https //stza.co/+xA10-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Nuts
END:VALARM
DTSTART:20180809T020500Z
DTEND:20180809T050500Z
UID:go1xm25FizWXT5TrpfSCWc06@stanza.co
SUMMARY:Ports @ Nuts
DESCRIPTION:Ports @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xA10-a\n\nShop: https://stza.co/+xA10-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Nuts
<2018-08-09 Thu 21:05>--<2018-08-10 Fri 00:05>
:PROPERTIES:
:ID:       hKl7aJ1221U5vWLDGNk6eLSY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Nuts Ports @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xA12-2O

Shop  https //stza.co/+xA12-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Nuts
END:VALARM
DTSTART:20180810T020500Z
DTEND:20180810T050500Z
UID:hKl7aJ1221U5vWLDGNk6eLSY@stanza.co
SUMMARY:Ports @ Nuts
DESCRIPTION:Ports @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xA12-2O\n\nShop: https://stza.co/+xA12-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Giants
<2018-08-10 Fri 21:10>--<2018-08-11 Sat 00:10>
:PROPERTIES:
:ID:       TVHGlxwzPraQWBOejh5X0u99@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Giants Ports vs. Giants

Follow on MiLB First Pitch  https //stza.co/+vM4b-_

Shop  https //stza.co/+vM4b-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Giants
END:VALARM
DTSTART:20180811T021000Z
DTEND:20180811T051000Z
UID:TVHGlxwzPraQWBOejh5X0u99@stanza.co
SUMMARY:Ports vs. Giants
DESCRIPTION:Ports vs. Giants\n\nFollow on MiLB First Pitch: https://stza.co/+vM4b-_\n\nShop: https://stza.co/+vM4b-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Giants
<2018-08-11 Sat 21:10>--<2018-08-12 Sun 00:10>
:PROPERTIES:
:ID:       VQIkWx-apuZzDx4hEH5_AU_Y@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports vs. Giants Ports vs. Giants

Follow on MiLB First Pitch  https //stza.co/+vM4d-34

Shop  https //stza.co/+vM4d-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Giants
END:VALARM
DTSTART:20180812T021000Z
DTEND:20180812T051000Z
UID:VQIkWx-apuZzDx4hEH5_AU_Y@stanza.co
SUMMARY:Ports vs. Giants
DESCRIPTION:Ports vs. Giants\n\nFollow on MiLB First Pitch: https://stza.co/+vM4d-34\n\nShop: https://stza.co/+vM4d-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Giants
<2018-08-12 Sun 20:10-23:10>
:PROPERTIES:
:ID:       hdbb40W3JEHoH8drtDq7Q6ft@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Giants Ports vs. Giants

Follow on MiLB First Pitch  https //stza.co/+vM4e-2e

Shop  https //stza.co/+vM4e-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Giants
END:VALARM
DTSTART:20180813T011000Z
DTEND:20180813T041000Z
UID:hdbb40W3JEHoH8drtDq7Q6ft@stanza.co
SUMMARY:Ports vs. Giants
DESCRIPTION:Ports vs. Giants\n\nFollow on MiLB First Pitch: https://stza.co/+vM4e-2e\n\nShop: https://stza.co/+vM4e-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ JetHawks
<2018-08-14 Tue 20:35-23:35>
:PROPERTIES:
:ID:       TSXwMKhFg4REeoIWpg6z-pmq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ JetHawks Ports @ JetHawks

Follow on MiLB First Pitch  https //stza.co/+vfwh-1I

Shop  https //stza.co/+vfwh-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ JetHawks
END:VALARM
DTSTART:20180815T013500Z
DTEND:20180815T043500Z
UID:TSXwMKhFg4REeoIWpg6z-pmq@stanza.co
SUMMARY:Ports @ JetHawks
DESCRIPTION:Ports @ JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vfwh-1I\n\nShop: https://stza.co/+vfwh-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ JetHawks
<2018-08-15 Wed 20:35-23:35>
:PROPERTIES:
:ID:       1Mhei053J3x_LHTH-FuspUFb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports @ JetHawks Ports @ JetHawks

Follow on MiLB First Pitch  https //stza.co/+vfwk-L

Shop  https //stza.co/+vfwk-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ JetHawks
END:VALARM
DTSTART:20180816T013500Z
DTEND:20180816T043500Z
UID:1Mhei053J3x_LHTH-FuspUFb@stanza.co
SUMMARY:Ports @ JetHawks
DESCRIPTION:Ports @ JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vfwk-L\n\nShop: https://stza.co/+vfwk-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ JetHawks
<2018-08-16 Thu 20:35-23:35>
:PROPERTIES:
:ID:       OW_JX1SvNxkxwdfKb0IRaA6e@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ JetHawks Ports @ JetHawks

Follow on MiLB First Pitch  https //stza.co/+vg1Y-J

Shop  https //stza.co/+vg1Y-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ JetHawks
END:VALARM
DTSTART:20180817T013500Z
DTEND:20180817T043500Z
UID:OW_JX1SvNxkxwdfKb0IRaA6e@stanza.co
SUMMARY:Ports @ JetHawks
DESCRIPTION:Ports @ JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vg1Y-J\n\nShop: https://stza.co/+vg1Y-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Rawhide
<2018-08-17 Fri 21:10>--<2018-08-18 Sat 00:10>
:PROPERTIES:
:ID:       XXGTWC1096w9ixlC_K4N6U8Y@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Rawhide Ports vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM4h-37

Shop  https //stza.co/+vM4h-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Rawhide
END:VALARM
DTSTART:20180818T021000Z
DTEND:20180818T051000Z
UID:XXGTWC1096w9ixlC_K4N6U8Y@stanza.co
SUMMARY:Ports vs. Rawhide
DESCRIPTION:Ports vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM4h-37\n\nShop: https://stza.co/+vM4h-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Rawhide
<2018-08-18 Sat 21:10>--<2018-08-19 Sun 00:10>
:PROPERTIES:
:ID:       XnHkYkEW8_ojUeCmSFiOAhhh@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports vs. Rawhide Ports vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM4j-1g

Shop  https //stza.co/+vM4j-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Rawhide
END:VALARM
DTSTART:20180819T021000Z
DTEND:20180819T051000Z
UID:XnHkYkEW8_ojUeCmSFiOAhhh@stanza.co
SUMMARY:Ports vs. Rawhide
DESCRIPTION:Ports vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM4j-1g\n\nShop: https://stza.co/+vM4j-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Rawhide
<2018-08-19 Sun 20:10-23:10>
:PROPERTIES:
:ID:       yMygfdqdxqndM11tv7P2KV8C@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Rawhide Ports vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM4l-32

Shop  https //stza.co/+vM4l-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Rawhide
END:VALARM
DTSTART:20180820T011000Z
DTEND:20180820T041000Z
UID:yMygfdqdxqndM11tv7P2KV8C@stanza.co
SUMMARY:Ports vs. Rawhide
DESCRIPTION:Ports vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM4l-32\n\nShop: https://stza.co/+vM4l-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Nuts
<2018-08-21 Tue 21:10>--<2018-08-22 Wed 00:10>
:PROPERTIES:
:ID:       zOInS3nG9OIwQekc62Q824By@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Nuts Ports vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+vM4m-3w

Shop  https //stza.co/+vM4m-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Nuts
END:VALARM
DTSTART:20180822T021000Z
DTEND:20180822T051000Z
UID:zOInS3nG9OIwQekc62Q824By@stanza.co
SUMMARY:Ports vs. Nuts
DESCRIPTION:Ports vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+vM4m-3w\n\nShop: https://stza.co/+vM4m-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Nuts
<2018-08-22 Wed 21:10>--<2018-08-23 Thu 00:10>
:PROPERTIES:
:ID:       2Q2CJ_HwmVKKcbCD1Ug6QaKw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports vs. Nuts Ports vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+vM4p-M

Shop  https //stza.co/+vM4p-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Nuts
END:VALARM
DTSTART:20180823T021000Z
DTEND:20180823T051000Z
UID:2Q2CJ_HwmVKKcbCD1Ug6QaKw@stanza.co
SUMMARY:Ports vs. Nuts
DESCRIPTION:Ports vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+vM4p-M\n\nShop: https://stza.co/+vM4p-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Nuts
<2018-08-23 Thu 21:10>--<2018-08-24 Fri 00:10>
:PROPERTIES:
:ID:       kK35ifH0VN34XGdJ5iwzX5pa@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Nuts Ports vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+vM4r-2$

Shop  https //stza.co/+vM4r-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Nuts
END:VALARM
DTSTART:20180824T021000Z
DTEND:20180824T051000Z
UID:kK35ifH0VN34XGdJ5iwzX5pa@stanza.co
SUMMARY:Ports vs. Nuts
DESCRIPTION:Ports vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+vM4r-2$\n\nShop: https://stza.co/+vM4r-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Rawhide
<2018-08-24 Fri>--<2018-08-23 Thu>
:PROPERTIES:
:ID:       U-uc-iU-mXVoeiziTj61OR7P@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Rawhide Ports @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM4J-2x

Shop  https //stza.co/+vM4J-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180824
DTEND;VALUE=DATE:20180824
UID:U-uc-iU-mXVoeiziTj61OR7P@stanza.co
SUMMARY:Ports @ Rawhide
DESCRIPTION:Ports @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM4J-2x\n\nShop: https://stza.co/+vM4J-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Rawhide
<2018-08-25 Sat>--<2018-08-24 Fri>
:PROPERTIES:
:ID:       ZWcWggPGWsF3ufJ5LhDpYsQE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports @ Rawhide Ports @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM4K-1Z

Shop  https //stza.co/+vM4K-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180825
DTEND;VALUE=DATE:20180825
UID:ZWcWggPGWsF3ufJ5LhDpYsQE@stanza.co
SUMMARY:Ports @ Rawhide
DESCRIPTION:Ports @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM4K-1Z\n\nShop: https://stza.co/+vM4K-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Rawhide
<2018-08-26 Sun>--<2018-08-25 Sat>
:PROPERTIES:
:ID:       XdRqBmh-EqVs7r4Reb4K91X4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Rawhide Ports @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vfVN-1o

Shop  https //stza.co/+vfVN-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180826
DTEND;VALUE=DATE:20180826
UID:XdRqBmh-EqVs7r4Reb4K91X4@stanza.co
SUMMARY:Ports @ Rawhide
DESCRIPTION:Ports @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vfVN-1o\n\nShop: https://stza.co/+vfVN-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Rawhide
<2018-08-27 Mon>--<2018-08-26 Sun>
:PROPERTIES:
:ID:       926SoxqqZHTdA9njpnRhah_a@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Rawhide Ports @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vfVP-2A

Shop  https //stza.co/+vfVP-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180827
DTEND;VALUE=DATE:20180827
UID:926SoxqqZHTdA9njpnRhah_a@stanza.co
SUMMARY:Ports @ Rawhide
DESCRIPTION:Ports @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vfVP-2A\n\nShop: https://stza.co/+vfVP-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Giants
<2018-08-28 Tue 21:00>--<2018-08-29 Wed 00:00>
:PROPERTIES:
:ID:       ZuqG5qRvaP4hOqiXRL3AjLon@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports @ Giants Ports @ Giants

Follow on MiLB First Pitch  https //stza.co/+xEYM-2U

Shop  https //stza.co/+xEYM-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Giants
END:VALARM
DTSTART:20180829T020000Z
DTEND:20180829T050000Z
UID:ZuqG5qRvaP4hOqiXRL3AjLon@stanza.co
SUMMARY:Ports @ Giants
DESCRIPTION:Ports @ Giants\n\nFollow on MiLB First Pitch: https://stza.co/+xEYM-2U\n\nShop: https://stza.co/+xEYM-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Giants
<2018-08-29 Wed 21:00>--<2018-08-30 Thu 00:00>
:PROPERTIES:
:ID:       2AnsTEizPfd24wRUlKzOK8ey@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Giants Ports @ Giants

Follow on MiLB First Pitch  https //stza.co/+xEYN-3a

Shop  https //stza.co/+xEYN-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Giants
END:VALARM
DTSTART:20180830T020000Z
DTEND:20180830T050000Z
UID:2AnsTEizPfd24wRUlKzOK8ey@stanza.co
SUMMARY:Ports @ Giants
DESCRIPTION:Ports @ Giants\n\nFollow on MiLB First Pitch: https://stza.co/+xEYN-3a\n\nShop: https://stza.co/+xEYN-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports @ Giants
<2018-08-30 Thu 14:30-17:30>
:PROPERTIES:
:ID:       uH3UIk_FAwSvk2XmTWo0vgfc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports @ Giants Ports @ Giants

Follow on MiLB First Pitch  https //stza.co/+xEYO-1C

Shop  https //stza.co/+xEYO-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Ports @ Giants
END:VALARM
DTSTART:20180830T193000Z
DTEND:20180830T223000Z
UID:uH3UIk_FAwSvk2XmTWo0vgfc@stanza.co
SUMMARY:Ports @ Giants
DESCRIPTION:Ports @ Giants\n\nFollow on MiLB First Pitch: https://stza.co/+xEYO-1C\n\nShop: https://stza.co/+xEYO-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Rawhide
<2018-08-31 Fri 21:10>--<2018-09-01 Sat 00:10>
:PROPERTIES:
:ID:       74-DMTkqMlywDXHCMImwJPQg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports vs. Rawhide Ports vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM4t-1y

Shop  https //stza.co/+vM4t-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Rawhide
END:VALARM
DTSTART:20180901T021000Z
DTEND:20180901T051000Z
UID:74-DMTkqMlywDXHCMImwJPQg@stanza.co
SUMMARY:Ports vs. Rawhide
DESCRIPTION:Ports vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM4t-1y\n\nShop: https://stza.co/+vM4t-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Rawhide
<2018-09-01 Sat 21:10>--<2018-09-02 Sun 00:10>
:PROPERTIES:
:ID:       jQTkRpt7veqoEDvgjUrb6rH5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Rawhide Ports vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM4v-2x

Shop  https //stza.co/+vM4v-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Rawhide
END:VALARM
DTSTART:20180902T021000Z
DTEND:20180902T051000Z
UID:jQTkRpt7veqoEDvgjUrb6rH5@stanza.co
SUMMARY:Ports vs. Rawhide
DESCRIPTION:Ports vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM4v-2x\n\nShop: https://stza.co/+vM4v-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Rawhide
<2018-09-02 Sun 20:10-23:10>
:PROPERTIES:
:ID:       GZAoXJWCDNpZtlTyAnUe1yI1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Ports vs. Rawhide Ports vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM4w-1e

Shop  https //stza.co/+vM4w-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Rawhide
END:VALARM
DTSTART:20180903T011000Z
DTEND:20180903T041000Z
UID:GZAoXJWCDNpZtlTyAnUe1yI1@stanza.co
SUMMARY:Ports vs. Rawhide
DESCRIPTION:Ports vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM4w-1e\n\nShop: https://stza.co/+vM4w-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Ports vs. Rawhide
<2018-09-03 Mon 20:10-23:10>
:PROPERTIES:
:ID:       MwphpaCZlAlsHCtMQWrVrmNZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Ports vs. Rawhide Ports vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM4z-36

Shop  https //stza.co/+vM4z-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Ports vs. Rawhide
END:VALARM
DTSTART:20180904T011000Z
DTEND:20180904T041000Z
UID:MwphpaCZlAlsHCtMQWrVrmNZ@stanza.co
SUMMARY:Ports vs. Rawhide
DESCRIPTION:Ports vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM4z-36\n\nShop: https://stza.co/+vM4z-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
