#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Hops @ AquaSox
<2018-06-15 Fri 21:05>--<2018-06-16 Sat 00:05>
:PROPERTIES:
:ID:       K5YpXF5RmQHDXh4aWSxjNesY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops @ AquaSox Hops @ AquaSox

Follow on MiLB First Pitch  https //stza.co/+vO9l-3z

Shop  https //stza.co/+vO9l-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ AquaSox
END:VALARM
DTSTART:20180616T020500Z
DTEND:20180616T050500Z
UID:K5YpXF5RmQHDXh4aWSxjNesY@stanza.co
SUMMARY:Hops @ AquaSox
DESCRIPTION:Hops @ AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vO9l-3z\n\nShop: https://stza.co/+vO9l-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ AquaSox
<2018-06-16 Sat 21:05>--<2018-06-17 Sun 00:05>
:PROPERTIES:
:ID:       m7JjsXfclhyBg0FxVgQ8FHjo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hops @ AquaSox Hops @ AquaSox

Follow on MiLB First Pitch  https //stza.co/+vO9m-2y

Shop  https //stza.co/+vO9m-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ AquaSox
END:VALARM
DTSTART:20180617T020500Z
DTEND:20180617T050500Z
UID:m7JjsXfclhyBg0FxVgQ8FHjo@stanza.co
SUMMARY:Hops @ AquaSox
DESCRIPTION:Hops @ AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vO9m-2y\n\nShop: https://stza.co/+vO9m-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ AquaSox
<2018-06-17 Sun 18:05-21:05>
:PROPERTIES:
:ID:       QSx7JQvCZyaYgM_FbWGVRBtJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops @ AquaSox Hops @ AquaSox

Follow on MiLB First Pitch  https //stza.co/+vO9n-3s

Shop  https //stza.co/+vO9n-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ AquaSox
END:VALARM
DTSTART:20180617T230500Z
DTEND:20180618T020500Z
UID:QSx7JQvCZyaYgM_FbWGVRBtJ@stanza.co
SUMMARY:Hops @ AquaSox
DESCRIPTION:Hops @ AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vO9n-3s\n\nShop: https://stza.co/+vO9n-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ AquaSox
<2018-06-18 Mon 21:05>--<2018-06-19 Tue 00:05>
:PROPERTIES:
:ID:       zH8Rcr_AEtXarB9eAIMpen_4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops @ AquaSox Hops @ AquaSox

Follow on MiLB First Pitch  https //stza.co/+vO9o-1k

Shop  https //stza.co/+vO9o-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ AquaSox
END:VALARM
DTSTART:20180619T020500Z
DTEND:20180619T050500Z
UID:zH8Rcr_AEtXarB9eAIMpen_4@stanza.co
SUMMARY:Hops @ AquaSox
DESCRIPTION:Hops @ AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vO9o-1k\n\nShop: https://stza.co/+vO9o-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ AquaSox
<2018-06-19 Tue 21:05>--<2018-06-20 Wed 00:05>
:PROPERTIES:
:ID:       fdxHOywPbQt-fceAf03hebgg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hops @ AquaSox Hops @ AquaSox

Follow on MiLB First Pitch  https //stza.co/+vO9p-2w

Shop  https //stza.co/+vO9p-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ AquaSox
END:VALARM
DTSTART:20180620T020500Z
DTEND:20180620T050500Z
UID:fdxHOywPbQt-fceAf03hebgg@stanza.co
SUMMARY:Hops @ AquaSox
DESCRIPTION:Hops @ AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vO9p-2w\n\nShop: https://stza.co/+vO9p-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Emeralds
<2018-06-20 Wed 21:05>--<2018-06-21 Thu 00:05>
:PROPERTIES:
:ID:       Vqg_doxyWEBFoCcuQM3CpqNR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops vs. Emeralds Hops vs. Emeralds

Follow on MiLB First Pitch  https //stza.co/+vO9r-2H

Shop  https //stza.co/+vO9r-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Emeralds
END:VALARM
DTSTART:20180621T020500Z
DTEND:20180621T050500Z
UID:Vqg_doxyWEBFoCcuQM3CpqNR@stanza.co
SUMMARY:Hops vs. Emeralds
DESCRIPTION:Hops vs. Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+vO9r-2H\n\nShop: https://stza.co/+vO9r-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Emeralds
<2018-06-21 Thu 21:05>--<2018-06-22 Fri 00:05>
:PROPERTIES:
:ID:       6dmnU53uJXPsr23gJFtt9B1-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops vs. Emeralds Hops vs. Emeralds

Follow on MiLB First Pitch  https //stza.co/+vO9t-

Shop  https //stza.co/+vO9t-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Emeralds
END:VALARM
DTSTART:20180622T020500Z
DTEND:20180622T050500Z
UID:6dmnU53uJXPsr23gJFtt9B1-@stanza.co
SUMMARY:Hops vs. Emeralds
DESCRIPTION:Hops vs. Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+vO9t-\n\nShop: https://stza.co/+vO9t-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Emeralds
<2018-06-22 Fri 21:05>--<2018-06-23 Sat 00:05>
:PROPERTIES:
:ID:       5NOHJOu9vsLpXnRFKeeALGYE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hops vs. Emeralds Hops vs. Emeralds

Follow on MiLB First Pitch  https //stza.co/+vO9v-3y

Shop  https //stza.co/+vO9v-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Emeralds
END:VALARM
DTSTART:20180623T020500Z
DTEND:20180623T050500Z
UID:5NOHJOu9vsLpXnRFKeeALGYE@stanza.co
SUMMARY:Hops vs. Emeralds
DESCRIPTION:Hops vs. Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+vO9v-3y\n\nShop: https://stza.co/+vO9v-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Volcanoes
<2018-06-23 Sat 21:05>--<2018-06-24 Sun 00:05>
:PROPERTIES:
:ID:       AjfMX35zjMcipQDfUs1W7t7O@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops vs. Volcanoes Hops vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vO9x-1e

Shop  https //stza.co/+vO9x-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Volcanoes
END:VALARM
DTSTART:20180624T020500Z
DTEND:20180624T050500Z
UID:AjfMX35zjMcipQDfUs1W7t7O@stanza.co
SUMMARY:Hops vs. Volcanoes
DESCRIPTION:Hops vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vO9x-1e\n\nShop: https://stza.co/+vO9x-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Volcanoes
<2018-06-24 Sun 18:05-21:05>
:PROPERTIES:
:ID:       BCYGdcp3VVd93Fo6kUTTnBOE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops vs. Volcanoes Hops vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vO9z-19

Shop  https //stza.co/+vO9z-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Volcanoes
END:VALARM
DTSTART:20180624T230500Z
DTEND:20180625T020500Z
UID:BCYGdcp3VVd93Fo6kUTTnBOE@stanza.co
SUMMARY:Hops vs. Volcanoes
DESCRIPTION:Hops vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vO9z-19\n\nShop: https://stza.co/+vO9z-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Volcanoes
<2018-06-25 Mon 21:05>--<2018-06-26 Tue 00:05>
:PROPERTIES:
:ID:       nUlSU7eChNVytqJWZKIFmwcl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hops vs. Volcanoes Hops vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vO9A-2J

Shop  https //stza.co/+vO9A-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Volcanoes
END:VALARM
DTSTART:20180626T020500Z
DTEND:20180626T050500Z
UID:nUlSU7eChNVytqJWZKIFmwcl@stanza.co
SUMMARY:Hops vs. Volcanoes
DESCRIPTION:Hops vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vO9A-2J\n\nShop: https://stza.co/+vO9A-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Hawks
<2018-06-26 Tue 20:15-23:15>
:PROPERTIES:
:ID:       A0OXbGCXBv9n_sYVyhqWPEOa@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops @ Hawks Hops @ Hawks

Follow on MiLB First Pitch  https //stza.co/+xC87-c

Shop  https //stza.co/+xC87-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Hawks
END:VALARM
DTSTART:20180627T011500Z
DTEND:20180627T041500Z
UID:A0OXbGCXBv9n_sYVyhqWPEOa@stanza.co
SUMMARY:Hops @ Hawks
DESCRIPTION:Hops @ Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xC87-c\n\nShop: https://stza.co/+xC87-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Hawks
<2018-06-27 Wed 20:15-23:15>
:PROPERTIES:
:ID:       3szoIFqi1L4Q4Fd7-kiaVlvx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops @ Hawks Hops @ Hawks

Follow on MiLB First Pitch  https //stza.co/+xC8b-22

Shop  https //stza.co/+xC8b-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Hawks
END:VALARM
DTSTART:20180628T011500Z
DTEND:20180628T041500Z
UID:3szoIFqi1L4Q4Fd7-kiaVlvx@stanza.co
SUMMARY:Hops @ Hawks
DESCRIPTION:Hops @ Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xC8b-22\n\nShop: https://stza.co/+xC8b-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Hawks
<2018-06-28 Thu 20:15-23:15>
:PROPERTIES:
:ID:       7g98DPQtrRrZ6pOgmRo7MdL6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hops @ Hawks Hops @ Hawks

Follow on MiLB First Pitch  https //stza.co/+xC8e-2G

Shop  https //stza.co/+xC8e-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Hawks
END:VALARM
DTSTART:20180629T011500Z
DTEND:20180629T041500Z
UID:7g98DPQtrRrZ6pOgmRo7MdL6@stanza.co
SUMMARY:Hops @ Hawks
DESCRIPTION:Hops @ Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xC8e-2G\n\nShop: https://stza.co/+xC8e-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Indians
<2018-06-29 Fri 21:05>--<2018-06-30 Sat 00:05>
:PROPERTIES:
:ID:       cY1xnDqKBQtLrVh-2c6wMI4O@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops vs. Indians Hops vs. Indians

Follow on MiLB First Pitch  https //stza.co/+vO9D-1g

Shop  https //stza.co/+vO9D-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Indians
END:VALARM
DTSTART:20180630T020500Z
DTEND:20180630T050500Z
UID:cY1xnDqKBQtLrVh-2c6wMI4O@stanza.co
SUMMARY:Hops vs. Indians
DESCRIPTION:Hops vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+vO9D-1g\n\nShop: https://stza.co/+vO9D-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Indians
<2018-06-30 Sat 21:05>--<2018-07-01 Sun 00:05>
:PROPERTIES:
:ID:       ffN3PUUKEMzGFuvIBPvKTYIL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops vs. Indians Hops vs. Indians

Follow on MiLB First Pitch  https //stza.co/+vO9E-3i

Shop  https //stza.co/+vO9E-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Indians
END:VALARM
DTSTART:20180701T020500Z
DTEND:20180701T050500Z
UID:ffN3PUUKEMzGFuvIBPvKTYIL@stanza.co
SUMMARY:Hops vs. Indians
DESCRIPTION:Hops vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+vO9E-3i\n\nShop: https://stza.co/+vO9E-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Indians
<2018-07-01 Sun 18:05-21:05>
:PROPERTIES:
:ID:       vjpAmKxMJdFoxN91ejxSvkwz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hops vs. Indians Hops vs. Indians

Follow on MiLB First Pitch  https //stza.co/+vO9H-36

Shop  https //stza.co/+vO9H-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Indians
END:VALARM
DTSTART:20180701T230500Z
DTEND:20180702T020500Z
UID:vjpAmKxMJdFoxN91ejxSvkwz@stanza.co
SUMMARY:Hops vs. Indians
DESCRIPTION:Hops vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+vO9H-36\n\nShop: https://stza.co/+vO9H-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Indians
<2018-07-02 Mon 21:05>--<2018-07-03 Tue 00:05>
:PROPERTIES:
:ID:       gnuNGK4_owX1qmUA9jSJhElT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops vs. Indians Hops vs. Indians

Follow on MiLB First Pitch  https //stza.co/+vO9I-1d

Shop  https //stza.co/+vO9I-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Indians
END:VALARM
DTSTART:20180703T020500Z
DTEND:20180703T050500Z
UID:gnuNGK4_owX1qmUA9jSJhElT@stanza.co
SUMMARY:Hops vs. Indians
DESCRIPTION:Hops vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+vO9I-1d\n\nShop: https://stza.co/+vO9I-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Indians
<2018-07-03 Tue 21:05>--<2018-07-04 Wed 00:05>
:PROPERTIES:
:ID:       wNUAkqAWjiR-xPEt3FBrH2zT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops vs. Indians Hops vs. Indians

Follow on MiLB First Pitch  https //stza.co/+vO9L-2f

Shop  https //stza.co/+vO9L-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Indians
END:VALARM
DTSTART:20180704T020500Z
DTEND:20180704T050500Z
UID:wNUAkqAWjiR-xPEt3FBrH2zT@stanza.co
SUMMARY:Hops vs. Indians
DESCRIPTION:Hops vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+vO9L-2f\n\nShop: https://stza.co/+vO9L-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Volcanoes
<2018-07-04 Wed>--<2018-07-03 Tue>
:PROPERTIES:
:ID:       1fnXS_bsXCj_IyZnsZOVJ4f1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hops @ Volcanoes Hops @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vOaC-3Z

Shop  https //stza.co/+vOaC-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180704
DTEND;VALUE=DATE:20180704
UID:1fnXS_bsXCj_IyZnsZOVJ4f1@stanza.co
SUMMARY:Hops @ Volcanoes
DESCRIPTION:Hops @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vOaC-3Z\n\nShop: https://stza.co/+vOaC-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Volcanoes
<2018-07-05 Thu>--<2018-07-04 Wed>
:PROPERTIES:
:ID:       W0aTUdwsPyiaDWWvGA3Mzjqm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops @ Volcanoes Hops @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vOaD-e

Shop  https //stza.co/+vOaD-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180705
DTEND;VALUE=DATE:20180705
UID:W0aTUdwsPyiaDWWvGA3Mzjqm@stanza.co
SUMMARY:Hops @ Volcanoes
DESCRIPTION:Hops @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vOaD-e\n\nShop: https://stza.co/+vOaD-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Volcanoes
<2018-07-06 Fri>--<2018-07-05 Thu>
:PROPERTIES:
:ID:       YXYDjinOUcyM4SICeiI-93Fl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops @ Volcanoes Hops @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vOaE-2

Shop  https //stza.co/+vOaE-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180706
DTEND;VALUE=DATE:20180706
UID:YXYDjinOUcyM4SICeiI-93Fl@stanza.co
SUMMARY:Hops @ Volcanoes
DESCRIPTION:Hops @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vOaE-2\n\nShop: https://stza.co/+vOaE-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Emeralds
<2018-07-07 Sat 21:05>--<2018-07-08 Sun 00:05>
:PROPERTIES:
:ID:       xoV2JikaSvTBTXxNRSVxAK0F@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hops @ Emeralds Hops @ Emeralds

Follow on MiLB First Pitch  https //stza.co/+xWPh-3p

Shop  https //stza.co/+xWPh-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Emeralds
END:VALARM
DTSTART:20180708T020500Z
DTEND:20180708T050500Z
UID:xoV2JikaSvTBTXxNRSVxAK0F@stanza.co
SUMMARY:Hops @ Emeralds
DESCRIPTION:Hops @ Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xWPh-3p\n\nShop: https://stza.co/+xWPh-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Emeralds
<2018-07-08 Sun 19:05-22:05>
:PROPERTIES:
:ID:       RDSD72VPDBlWKLU6Jru2_1gM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops @ Emeralds Hops @ Emeralds

Follow on MiLB First Pitch  https //stza.co/+xWPi-21

Shop  https //stza.co/+xWPi-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Emeralds
END:VALARM
DTSTART:20180709T000500Z
DTEND:20180709T030500Z
UID:RDSD72VPDBlWKLU6Jru2_1gM@stanza.co
SUMMARY:Hops @ Emeralds
DESCRIPTION:Hops @ Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xWPi-21\n\nShop: https://stza.co/+xWPi-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Emeralds
<2018-07-09 Mon 21:05>--<2018-07-10 Tue 00:05>
:PROPERTIES:
:ID:       BH_5vm2f3Zi0FQp6CaNZXvbx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops @ Emeralds Hops @ Emeralds

Follow on MiLB First Pitch  https //stza.co/+xWPj-3_

Shop  https //stza.co/+xWPj-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Emeralds
END:VALARM
DTSTART:20180710T020500Z
DTEND:20180710T050500Z
UID:BH_5vm2f3Zi0FQp6CaNZXvbx@stanza.co
SUMMARY:Hops @ Emeralds
DESCRIPTION:Hops @ Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xWPj-3_\n\nShop: https://stza.co/+xWPj-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Dust Devils
<2018-07-11 Wed 21:05>--<2018-07-12 Thu 00:05>
:PROPERTIES:
:ID:       iYkWPSCwx9g02Ekpftqqq32V@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hops vs. Dust Devils Hops vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vO9N-3a

Shop  https //stza.co/+vO9N-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Dust Devils
END:VALARM
DTSTART:20180712T020500Z
DTEND:20180712T050500Z
UID:iYkWPSCwx9g02Ekpftqqq32V@stanza.co
SUMMARY:Hops vs. Dust Devils
DESCRIPTION:Hops vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vO9N-3a\n\nShop: https://stza.co/+vO9N-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Dust Devils
<2018-07-12 Thu 21:05>--<2018-07-13 Fri 00:05>
:PROPERTIES:
:ID:       wGno3XRIWM8T7TduS003rccU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops vs. Dust Devils Hops vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vO9O-2F

Shop  https //stza.co/+vO9O-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Dust Devils
END:VALARM
DTSTART:20180713T020500Z
DTEND:20180713T050500Z
UID:wGno3XRIWM8T7TduS003rccU@stanza.co
SUMMARY:Hops vs. Dust Devils
DESCRIPTION:Hops vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vO9O-2F\n\nShop: https://stza.co/+vO9O-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Dust Devils
<2018-07-13 Fri 21:05>--<2018-07-14 Sat 00:05>
:PROPERTIES:
:ID:       lc0sASp-031hZrp2VxxlRyei@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops vs. Dust Devils Hops vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vO9Q-1P

Shop  https //stza.co/+vO9Q-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Dust Devils
END:VALARM
DTSTART:20180714T020500Z
DTEND:20180714T050500Z
UID:lc0sASp-031hZrp2VxxlRyei@stanza.co
SUMMARY:Hops vs. Dust Devils
DESCRIPTION:Hops vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vO9Q-1P\n\nShop: https://stza.co/+vO9Q-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Dust Devils
<2018-07-14 Sat 21:05>--<2018-07-15 Sun 00:05>
:PROPERTIES:
:ID:       U5sMxAl8JvdxMJ3W4DCgeRFV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hops vs. Dust Devils Hops vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vO9T-37

Shop  https //stza.co/+vO9T-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Dust Devils
END:VALARM
DTSTART:20180715T020500Z
DTEND:20180715T050500Z
UID:U5sMxAl8JvdxMJ3W4DCgeRFV@stanza.co
SUMMARY:Hops vs. Dust Devils
DESCRIPTION:Hops vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vO9T-37\n\nShop: https://stza.co/+vO9T-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Dust Devils
<2018-07-15 Sun 18:05-21:05>
:PROPERTIES:
:ID:       oLrf9gX86N8eBopcq1HklUYu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops vs. Dust Devils Hops vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vO9U-x

Shop  https //stza.co/+vO9U-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Dust Devils
END:VALARM
DTSTART:20180715T230500Z
DTEND:20180716T020500Z
UID:oLrf9gX86N8eBopcq1HklUYu@stanza.co
SUMMARY:Hops vs. Dust Devils
DESCRIPTION:Hops vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vO9U-x\n\nShop: https://stza.co/+vO9U-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Hawks
<2018-07-16 Mon 21:05>--<2018-07-17 Tue 00:05>
:PROPERTIES:
:ID:       hk5eZ1sg3R_MmJWW7v5ryIED@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops vs. Hawks Hops vs. Hawks

Follow on MiLB First Pitch  https //stza.co/+vO9W-3z

Shop  https //stza.co/+vO9W-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Hawks
END:VALARM
DTSTART:20180717T020500Z
DTEND:20180717T050500Z
UID:hk5eZ1sg3R_MmJWW7v5ryIED@stanza.co
SUMMARY:Hops vs. Hawks
DESCRIPTION:Hops vs. Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+vO9W-3z\n\nShop: https://stza.co/+vO9W-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Hawks
<2018-07-17 Tue 21:05>--<2018-07-18 Wed 00:05>
:PROPERTIES:
:ID:       RbJ_s3tGELLgp8WyzJcFB9v4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hops vs. Hawks Hops vs. Hawks

Follow on MiLB First Pitch  https //stza.co/+vO9Y-2E

Shop  https //stza.co/+vO9Y-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Hawks
END:VALARM
DTSTART:20180718T020500Z
DTEND:20180718T050500Z
UID:RbJ_s3tGELLgp8WyzJcFB9v4@stanza.co
SUMMARY:Hops vs. Hawks
DESCRIPTION:Hops vs. Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+vO9Y-2E\n\nShop: https://stza.co/+vO9Y-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Hawks
<2018-07-18 Wed 15:05-18:05>
:PROPERTIES:
:ID:       VRhkVdhMAFt1Fd970L7WhUML@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops vs. Hawks Hops vs. Hawks

Follow on MiLB First Pitch  https //stza.co/+vO9_-1E

Shop  https //stza.co/+vO9_-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Hawks
END:VALARM
DTSTART:20180718T200500Z
DTEND:20180718T230500Z
UID:VRhkVdhMAFt1Fd970L7WhUML@stanza.co
SUMMARY:Hops vs. Hawks
DESCRIPTION:Hops vs. Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+vO9_-1E\n\nShop: https://stza.co/+vO9_-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Canadians
<2018-07-19 Thu 21:05>--<2018-07-20 Fri 00:05>
:PROPERTIES:
:ID:       lbljynq532z0x-hRVGzeT2Pa@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops @ Canadians Hops @ Canadians

Follow on MiLB First Pitch  https //stza.co/+xXUX-Q

Shop  https //stza.co/+xXUX-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Canadians
END:VALARM
DTSTART:20180720T020500Z
DTEND:20180720T050500Z
UID:lbljynq532z0x-hRVGzeT2Pa@stanza.co
SUMMARY:Hops @ Canadians
DESCRIPTION:Hops @ Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xXUX-Q\n\nShop: https://stza.co/+xXUX-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Canadians
<2018-07-20 Fri 15:05-18:05>
:PROPERTIES:
:ID:       nP-K7QE5Kd7cnuAPaNZ5Gd-4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hops @ Canadians Hops @ Canadians

Follow on MiLB First Pitch  https //stza.co/+xXUY-3i

Shop  https //stza.co/+xXUY-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Canadians
END:VALARM
DTSTART:20180720T200500Z
DTEND:20180720T230500Z
UID:nP-K7QE5Kd7cnuAPaNZ5Gd-4@stanza.co
SUMMARY:Hops @ Canadians
DESCRIPTION:Hops @ Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xXUY-3i\n\nShop: https://stza.co/+xXUY-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Canadians
<2018-07-21 Sat 21:05>--<2018-07-22 Sun 00:05>
:PROPERTIES:
:ID:       gz_AgYvBA9IUkJQFr2B46dv2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops @ Canadians Hops @ Canadians

Follow on MiLB First Pitch  https //stza.co/+xXUZ-6

Shop  https //stza.co/+xXUZ-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Canadians
END:VALARM
DTSTART:20180722T020500Z
DTEND:20180722T050500Z
UID:gz_AgYvBA9IUkJQFr2B46dv2@stanza.co
SUMMARY:Hops @ Canadians
DESCRIPTION:Hops @ Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xXUZ-6\n\nShop: https://stza.co/+xXUZ-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Canadians
<2018-07-22 Sun 15:05-18:05>
:PROPERTIES:
:ID:       3GPIiFR3Vs-_V_r5p2HLwDcD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops @ Canadians Hops @ Canadians

Follow on MiLB First Pitch  https //stza.co/+xXU_-2B

Shop  https //stza.co/+xXU_-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Canadians
END:VALARM
DTSTART:20180722T200500Z
DTEND:20180722T230500Z
UID:3GPIiFR3Vs-_V_r5p2HLwDcD@stanza.co
SUMMARY:Hops @ Canadians
DESCRIPTION:Hops @ Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xXU_-2B\n\nShop: https://stza.co/+xXU_-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Canadians
<2018-07-23 Mon 21:05>--<2018-07-24 Tue 00:05>
:PROPERTIES:
:ID:       ULn6GJEoZW5iMTUfwt0Tkxl_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hops @ Canadians Hops @ Canadians

Follow on MiLB First Pitch  https //stza.co/+xXU$-1n

Shop  https //stza.co/+xXU$-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Canadians
END:VALARM
DTSTART:20180724T020500Z
DTEND:20180724T050500Z
UID:ULn6GJEoZW5iMTUfwt0Tkxl_@stanza.co
SUMMARY:Hops @ Canadians
DESCRIPTION:Hops @ Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xXU$-1n\n\nShop: https://stza.co/+xXU$-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Hawks
<2018-07-24 Tue 21:05>--<2018-07-25 Wed 00:05>
:PROPERTIES:
:ID:       kA1qwshxVB0WOBO9GZGL2buk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops vs. Hawks Hops vs. Hawks

Follow on MiLB First Pitch  https //stza.co/+vOa0-21

Shop  https //stza.co/+vOa0-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Hawks
END:VALARM
DTSTART:20180725T020500Z
DTEND:20180725T050500Z
UID:kA1qwshxVB0WOBO9GZGL2buk@stanza.co
SUMMARY:Hops vs. Hawks
DESCRIPTION:Hops vs. Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+vOa0-21\n\nShop: https://stza.co/+vOa0-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Hawks
<2018-07-25 Wed 21:05>--<2018-07-26 Thu 00:05>
:PROPERTIES:
:ID:       7IRw6Gk4MFliVXWXMqfc_DUg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops vs. Hawks Hops vs. Hawks

Follow on MiLB First Pitch  https //stza.co/+vOa2-r

Shop  https //stza.co/+vOa2-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Hawks
END:VALARM
DTSTART:20180726T020500Z
DTEND:20180726T050500Z
UID:7IRw6Gk4MFliVXWXMqfc_DUg@stanza.co
SUMMARY:Hops vs. Hawks
DESCRIPTION:Hops vs. Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+vOa2-r\n\nShop: https://stza.co/+vOa2-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Hawks
<2018-07-26 Thu 21:05>--<2018-07-27 Fri 00:05>
:PROPERTIES:
:ID:       puSnYDA2-AuiiM8BXf4jAbB1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hops vs. Hawks Hops vs. Hawks

Follow on MiLB First Pitch  https //stza.co/+vOa5-2R

Shop  https //stza.co/+vOa5-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Hawks
END:VALARM
DTSTART:20180727T020500Z
DTEND:20180727T050500Z
UID:puSnYDA2-AuiiM8BXf4jAbB1@stanza.co
SUMMARY:Hops vs. Hawks
DESCRIPTION:Hops vs. Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+vOa5-2R\n\nShop: https://stza.co/+vOa5-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Indians
<2018-07-27 Fri 20:30-23:30>
:PROPERTIES:
:ID:       VftHFg4AqfkKSu88wtMrxtDn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops @ Indians Hops @ Indians

Follow on MiLB First Pitch  https //stza.co/+xC8_-26

Shop  https //stza.co/+xC8_-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Indians
END:VALARM
DTSTART:20180728T013000Z
DTEND:20180728T043000Z
UID:VftHFg4AqfkKSu88wtMrxtDn@stanza.co
SUMMARY:Hops @ Indians
DESCRIPTION:Hops @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xC8_-26\n\nShop: https://stza.co/+xC8_-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Indians
<2018-07-28 Sat 20:30-23:30>
:PROPERTIES:
:ID:       2tLo0Go9b3gwGrFZLVOZUHBF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops @ Indians Hops @ Indians

Follow on MiLB First Pitch  https //stza.co/+xC90-1n

Shop  https //stza.co/+xC90-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Indians
END:VALARM
DTSTART:20180729T013000Z
DTEND:20180729T043000Z
UID:2tLo0Go9b3gwGrFZLVOZUHBF@stanza.co
SUMMARY:Hops @ Indians
DESCRIPTION:Hops @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xC90-1n\n\nShop: https://stza.co/+xC90-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Indians
<2018-07-29 Sun 17:30-20:30>
:PROPERTIES:
:ID:       WIahSlhXXfZfwIQUkPL7t7Sk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hops @ Indians Hops @ Indians

Follow on MiLB First Pitch  https //stza.co/+xC94-25

Shop  https //stza.co/+xC94-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Indians
END:VALARM
DTSTART:20180729T223000Z
DTEND:20180730T013000Z
UID:WIahSlhXXfZfwIQUkPL7t7Sk@stanza.co
SUMMARY:Hops @ Indians
DESCRIPTION:Hops @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xC94-25\n\nShop: https://stza.co/+xC94-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Indians
<2018-07-30 Mon 20:30-23:30>
:PROPERTIES:
:ID:       kvjHa_GCZjT61UFEtqTkb-Hk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops @ Indians Hops @ Indians

Follow on MiLB First Pitch  https //stza.co/+xC97-1r

Shop  https //stza.co/+xC97-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Indians
END:VALARM
DTSTART:20180731T013000Z
DTEND:20180731T043000Z
UID:kvjHa_GCZjT61UFEtqTkb-Hk@stanza.co
SUMMARY:Hops @ Indians
DESCRIPTION:Hops @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xC97-1r\n\nShop: https://stza.co/+xC97-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Indians
<2018-07-31 Tue 20:30-23:30>
:PROPERTIES:
:ID:       tr6IZ00XIKRUI4IpR8jgRkq6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops @ Indians Hops @ Indians

Follow on MiLB First Pitch  https //stza.co/+xBij-o

Shop  https //stza.co/+xBij-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Indians
END:VALARM
DTSTART:20180801T013000Z
DTEND:20180801T043000Z
UID:tr6IZ00XIKRUI4IpR8jgRkq6@stanza.co
SUMMARY:Hops @ Indians
DESCRIPTION:Hops @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xBij-o\n\nShop: https://stza.co/+xBij-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Canadians
<2018-08-01 Wed 21:05>--<2018-08-02 Thu 00:05>
:PROPERTIES:
:ID:       xXYX7DaAFph7bJMdfU7-6Nx0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hops vs. Canadians Hops vs. Canadians

Follow on MiLB First Pitch  https //stza.co/+vOa6-1O

Shop  https //stza.co/+vOa6-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Canadians
END:VALARM
DTSTART:20180802T020500Z
DTEND:20180802T050500Z
UID:xXYX7DaAFph7bJMdfU7-6Nx0@stanza.co
SUMMARY:Hops vs. Canadians
DESCRIPTION:Hops vs. Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+vOa6-1O\n\nShop: https://stza.co/+vOa6-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Canadians
<2018-08-02 Thu 21:05>--<2018-08-03 Fri 00:05>
:PROPERTIES:
:ID:       0PiLk9-3CZtEBB9VpLBqe-pq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops vs. Canadians Hops vs. Canadians

Follow on MiLB First Pitch  https //stza.co/+vOa9-2s

Shop  https //stza.co/+vOa9-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Canadians
END:VALARM
DTSTART:20180803T020500Z
DTEND:20180803T050500Z
UID:0PiLk9-3CZtEBB9VpLBqe-pq@stanza.co
SUMMARY:Hops vs. Canadians
DESCRIPTION:Hops vs. Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+vOa9-2s\n\nShop: https://stza.co/+vOa9-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Canadians
<2018-08-03 Fri 21:05>--<2018-08-04 Sat 00:05>
:PROPERTIES:
:ID:       15GvzHK035lUsdlFP-0lRFdj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops vs. Canadians Hops vs. Canadians

Follow on MiLB First Pitch  https //stza.co/+vOab-2Y

Shop  https //stza.co/+vOab-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Canadians
END:VALARM
DTSTART:20180804T020500Z
DTEND:20180804T050500Z
UID:15GvzHK035lUsdlFP-0lRFdj@stanza.co
SUMMARY:Hops vs. Canadians
DESCRIPTION:Hops vs. Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+vOab-2Y\n\nShop: https://stza.co/+vOab-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Canadians
<2018-08-04 Sat 21:05>--<2018-08-05 Sun 00:05>
:PROPERTIES:
:ID:       TAvaj7HHWF2DnY4LSKwprUIR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hops vs. Canadians Hops vs. Canadians

Follow on MiLB First Pitch  https //stza.co/+vOac-1x

Shop  https //stza.co/+vOac-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Canadians
END:VALARM
DTSTART:20180805T020500Z
DTEND:20180805T050500Z
UID:TAvaj7HHWF2DnY4LSKwprUIR@stanza.co
SUMMARY:Hops vs. Canadians
DESCRIPTION:Hops vs. Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+vOac-1x\n\nShop: https://stza.co/+vOac-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Canadians
<2018-08-05 Sun 18:05-21:05>
:PROPERTIES:
:ID:       OptvyMBugx6H8VbSpxu5_-r5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops vs. Canadians Hops vs. Canadians

Follow on MiLB First Pitch  https //stza.co/+vOae-f

Shop  https //stza.co/+vOae-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Canadians
END:VALARM
DTSTART:20180805T230500Z
DTEND:20180806T020500Z
UID:OptvyMBugx6H8VbSpxu5_-r5@stanza.co
SUMMARY:Hops vs. Canadians
DESCRIPTION:Hops vs. Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+vOae-f\n\nShop: https://stza.co/+vOae-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Dust Devils
<2018-08-09 Thu 21:15>--<2018-08-10 Fri 00:15>
:PROPERTIES:
:ID:       ikl_clio_B4JkJhlKfAps52Y@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops @ Dust Devils Hops @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vOaN-Y

Shop  https //stza.co/+vOaN-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Dust Devils
END:VALARM
DTSTART:20180810T021500Z
DTEND:20180810T051500Z
UID:ikl_clio_B4JkJhlKfAps52Y@stanza.co
SUMMARY:Hops @ Dust Devils
DESCRIPTION:Hops @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vOaN-Y\n\nShop: https://stza.co/+vOaN-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Dust Devils
<2018-08-10 Fri 21:15>--<2018-08-11 Sat 00:15>
:PROPERTIES:
:ID:       q6w8oN3H3aS1IayarVNvi1d9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hops @ Dust Devils Hops @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vOaO-24

Shop  https //stza.co/+vOaO-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Dust Devils
END:VALARM
DTSTART:20180811T021500Z
DTEND:20180811T051500Z
UID:q6w8oN3H3aS1IayarVNvi1d9@stanza.co
SUMMARY:Hops @ Dust Devils
DESCRIPTION:Hops @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vOaO-24\n\nShop: https://stza.co/+vOaO-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Dust Devils
<2018-08-11 Sat 21:15>--<2018-08-12 Sun 00:15>
:PROPERTIES:
:ID:       7TuWUhsjUzze7NDdsVS3kkye@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops @ Dust Devils Hops @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vOaP-2X

Shop  https //stza.co/+vOaP-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Dust Devils
END:VALARM
DTSTART:20180812T021500Z
DTEND:20180812T051500Z
UID:7TuWUhsjUzze7NDdsVS3kkye@stanza.co
SUMMARY:Hops @ Dust Devils
DESCRIPTION:Hops @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vOaP-2X\n\nShop: https://stza.co/+vOaP-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Dust Devils
<2018-08-12 Sun 21:15>--<2018-08-13 Mon 00:15>
:PROPERTIES:
:ID:       kBWEk0C_Iw7CWA_VrRk-2ttp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops @ Dust Devils Hops @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vOaQ-X

Shop  https //stza.co/+vOaQ-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Dust Devils
END:VALARM
DTSTART:20180813T021500Z
DTEND:20180813T051500Z
UID:kBWEk0C_Iw7CWA_VrRk-2ttp@stanza.co
SUMMARY:Hops @ Dust Devils
DESCRIPTION:Hops @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vOaQ-X\n\nShop: https://stza.co/+vOaQ-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Dust Devils
<2018-08-13 Mon 21:15>--<2018-08-14 Tue 00:15>
:PROPERTIES:
:ID:       A3jFdn_a35R5yTwr9WPUzO8V@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hops @ Dust Devils Hops @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vOaR-3T

Shop  https //stza.co/+vOaR-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Dust Devils
END:VALARM
DTSTART:20180814T021500Z
DTEND:20180814T051500Z
UID:A3jFdn_a35R5yTwr9WPUzO8V@stanza.co
SUMMARY:Hops @ Dust Devils
DESCRIPTION:Hops @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vOaR-3T\n\nShop: https://stza.co/+vOaR-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Emeralds
<2018-08-14 Tue 21:05>--<2018-08-15 Wed 00:05>
:PROPERTIES:
:ID:       U35Yf5bVM2Ph5vgoI4ghtdC3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops @ Emeralds Hops @ Emeralds

Follow on MiLB First Pitch  https //stza.co/+xWPk-A

Shop  https //stza.co/+xWPk-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Emeralds
END:VALARM
DTSTART:20180815T020500Z
DTEND:20180815T050500Z
UID:U35Yf5bVM2Ph5vgoI4ghtdC3@stanza.co
SUMMARY:Hops @ Emeralds
DESCRIPTION:Hops @ Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xWPk-A\n\nShop: https://stza.co/+xWPk-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Emeralds
<2018-08-15 Wed 21:05>--<2018-08-16 Thu 00:05>
:PROPERTIES:
:ID:       U-lRZCU7n5MTSqAb1xYXmt6J@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops @ Emeralds Hops @ Emeralds

Follow on MiLB First Pitch  https //stza.co/+xWPl-3q

Shop  https //stza.co/+xWPl-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Emeralds
END:VALARM
DTSTART:20180816T020500Z
DTEND:20180816T050500Z
UID:U-lRZCU7n5MTSqAb1xYXmt6J@stanza.co
SUMMARY:Hops @ Emeralds
DESCRIPTION:Hops @ Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xWPl-3q\n\nShop: https://stza.co/+xWPl-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Emeralds
<2018-08-16 Thu 21:05>--<2018-08-17 Fri 00:05>
:PROPERTIES:
:ID:       zaP06Qp3q6CJa4TwBA_ACig9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hops @ Emeralds Hops @ Emeralds

Follow on MiLB First Pitch  https //stza.co/+xWPm-3q

Shop  https //stza.co/+xWPm-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Emeralds
END:VALARM
DTSTART:20180817T020500Z
DTEND:20180817T050500Z
UID:zaP06Qp3q6CJa4TwBA_ACig9@stanza.co
SUMMARY:Hops @ Emeralds
DESCRIPTION:Hops @ Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xWPm-3q\n\nShop: https://stza.co/+xWPm-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Volcanoes
<2018-08-17 Fri>--<2018-08-16 Thu>
:PROPERTIES:
:ID:       FOc_hXfzaG6qvcbQQix75Xk4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops @ Volcanoes Hops @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vOaF-e

Shop  https //stza.co/+vOaF-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180817
DTEND;VALUE=DATE:20180817
UID:FOc_hXfzaG6qvcbQQix75Xk4@stanza.co
SUMMARY:Hops @ Volcanoes
DESCRIPTION:Hops @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vOaF-e\n\nShop: https://stza.co/+vOaF-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Volcanoes
<2018-08-18 Sat>--<2018-08-17 Fri>
:PROPERTIES:
:ID:       67Ux2bS0FAQTCe4hJL4OQ8u2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops @ Volcanoes Hops @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vOaG-g

Shop  https //stza.co/+vOaG-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180818
DTEND;VALUE=DATE:20180818
UID:67Ux2bS0FAQTCe4hJL4OQ8u2@stanza.co
SUMMARY:Hops @ Volcanoes
DESCRIPTION:Hops @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vOaG-g\n\nShop: https://stza.co/+vOaG-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Volcanoes
<2018-08-19 Sun>--<2018-08-18 Sat>
:PROPERTIES:
:ID:       BwiKGYXClfV7_qt08UFbxNZf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hops @ Volcanoes Hops @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vOaH-p

Shop  https //stza.co/+vOaH-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180819
DTEND;VALUE=DATE:20180819
UID:BwiKGYXClfV7_qt08UFbxNZf@stanza.co
SUMMARY:Hops @ Volcanoes
DESCRIPTION:Hops @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vOaH-p\n\nShop: https://stza.co/+vOaH-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Emeralds
<2018-08-20 Mon 21:05>--<2018-08-21 Tue 00:05>
:PROPERTIES:
:ID:       DGyU7tUhJ66XqqBZcc-tsvdo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops vs. Emeralds Hops vs. Emeralds

Follow on MiLB First Pitch  https //stza.co/+vOag-D

Shop  https //stza.co/+vOag-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Emeralds
END:VALARM
DTSTART:20180821T020500Z
DTEND:20180821T050500Z
UID:DGyU7tUhJ66XqqBZcc-tsvdo@stanza.co
SUMMARY:Hops vs. Emeralds
DESCRIPTION:Hops vs. Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+vOag-D\n\nShop: https://stza.co/+vOag-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Emeralds
<2018-08-21 Tue 21:05>--<2018-08-22 Wed 00:05>
:PROPERTIES:
:ID:       IGgP5Szs-cOVJfT3fDm5SP6T@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops vs. Emeralds Hops vs. Emeralds

Follow on MiLB First Pitch  https //stza.co/+vOaj-2x

Shop  https //stza.co/+vOaj-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Emeralds
END:VALARM
DTSTART:20180822T020500Z
DTEND:20180822T050500Z
UID:IGgP5Szs-cOVJfT3fDm5SP6T@stanza.co
SUMMARY:Hops vs. Emeralds
DESCRIPTION:Hops vs. Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+vOaj-2x\n\nShop: https://stza.co/+vOaj-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Emeralds
<2018-08-22 Wed 21:05>--<2018-08-23 Thu 00:05>
:PROPERTIES:
:ID:       Q-IPj4J1CE1zH6uPsF3cxEbs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hops vs. Emeralds Hops vs. Emeralds

Follow on MiLB First Pitch  https //stza.co/+vOal-17

Shop  https //stza.co/+vOal-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Emeralds
END:VALARM
DTSTART:20180823T020500Z
DTEND:20180823T050500Z
UID:Q-IPj4J1CE1zH6uPsF3cxEbs@stanza.co
SUMMARY:Hops vs. Emeralds
DESCRIPTION:Hops vs. Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+vOal-17\n\nShop: https://stza.co/+vOal-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. AquaSox
<2018-08-23 Thu 21:05>--<2018-08-24 Fri 00:05>
:PROPERTIES:
:ID:       V55sQF8HPAHylshWov0qX-KM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops vs. AquaSox Hops vs. AquaSox

Follow on MiLB First Pitch  https //stza.co/+vOam-2T

Shop  https //stza.co/+vOam-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. AquaSox
END:VALARM
DTSTART:20180824T020500Z
DTEND:20180824T050500Z
UID:V55sQF8HPAHylshWov0qX-KM@stanza.co
SUMMARY:Hops vs. AquaSox
DESCRIPTION:Hops vs. AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vOam-2T\n\nShop: https://stza.co/+vOam-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. AquaSox
<2018-08-24 Fri 21:05>--<2018-08-25 Sat 00:05>
:PROPERTIES:
:ID:       ou5_SsfY4KGQMz7sTNsXQia3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops vs. AquaSox Hops vs. AquaSox

Follow on MiLB First Pitch  https //stza.co/+vOap-3e

Shop  https //stza.co/+vOap-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. AquaSox
END:VALARM
DTSTART:20180825T020500Z
DTEND:20180825T050500Z
UID:ou5_SsfY4KGQMz7sTNsXQia3@stanza.co
SUMMARY:Hops vs. AquaSox
DESCRIPTION:Hops vs. AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vOap-3e\n\nShop: https://stza.co/+vOap-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. AquaSox
<2018-08-25 Sat 21:05>--<2018-08-26 Sun 00:05>
:PROPERTIES:
:ID:       DM2tFIEqly0HDFP2UUxQXoi8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hops vs. AquaSox Hops vs. AquaSox

Follow on MiLB First Pitch  https //stza.co/+vOaq-2V

Shop  https //stza.co/+vOaq-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. AquaSox
END:VALARM
DTSTART:20180826T020500Z
DTEND:20180826T050500Z
UID:DM2tFIEqly0HDFP2UUxQXoi8@stanza.co
SUMMARY:Hops vs. AquaSox
DESCRIPTION:Hops vs. AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vOaq-2V\n\nShop: https://stza.co/+vOaq-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. AquaSox
<2018-08-26 Sun 18:05-21:05>
:PROPERTIES:
:ID:       dUrZuF1cZt4kluM7SmAV3Oxs@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops vs. AquaSox Hops vs. AquaSox

Follow on MiLB First Pitch  https //stza.co/+vOat-2e

Shop  https //stza.co/+vOat-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. AquaSox
END:VALARM
DTSTART:20180826T230500Z
DTEND:20180827T020500Z
UID:dUrZuF1cZt4kluM7SmAV3Oxs@stanza.co
SUMMARY:Hops vs. AquaSox
DESCRIPTION:Hops vs. AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vOat-2e\n\nShop: https://stza.co/+vOat-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. AquaSox
<2018-08-27 Mon 15:05-18:05>
:PROPERTIES:
:ID:       7IRZ1csfjVrRgdN0f1sk_A5Z@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops vs. AquaSox Hops vs. AquaSox

Follow on MiLB First Pitch  https //stza.co/+vOav-P

Shop  https //stza.co/+vOav-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. AquaSox
END:VALARM
DTSTART:20180827T200500Z
DTEND:20180827T230500Z
UID:7IRZ1csfjVrRgdN0f1sk_A5Z@stanza.co
SUMMARY:Hops vs. AquaSox
DESCRIPTION:Hops vs. AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vOav-P\n\nShop: https://stza.co/+vOav-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Hawks
<2018-08-29 Wed 20:15-23:15>
:PROPERTIES:
:ID:       lqiM8ob4mlxzWQRy9cMGb47s@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hops @ Hawks Hops @ Hawks

Follow on MiLB First Pitch  https //stza.co/+xC8g-2u

Shop  https //stza.co/+xC8g-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Hawks
END:VALARM
DTSTART:20180830T011500Z
DTEND:20180830T041500Z
UID:lqiM8ob4mlxzWQRy9cMGb47s@stanza.co
SUMMARY:Hops @ Hawks
DESCRIPTION:Hops @ Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xC8g-2u\n\nShop: https://stza.co/+xC8g-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Hawks
<2018-08-30 Thu 20:15-23:15>
:PROPERTIES:
:ID:       rCi5VPwFPUo7IrHZsm2PmfGB@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops @ Hawks Hops @ Hawks

Follow on MiLB First Pitch  https //stza.co/+xC8n-1H

Shop  https //stza.co/+xC8n-1w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Hawks
END:VALARM
DTSTART:20180831T011500Z
DTEND:20180831T041500Z
UID:rCi5VPwFPUo7IrHZsm2PmfGB@stanza.co
SUMMARY:Hops @ Hawks
DESCRIPTION:Hops @ Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xC8n-1H\n\nShop: https://stza.co/+xC8n-1w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops @ Hawks
<2018-08-31 Fri 20:15-23:15>
:PROPERTIES:
:ID:       6n2BTqB3v6cITWyCAt0GOKFA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops @ Hawks Hops @ Hawks

Follow on MiLB First Pitch  https //stza.co/+xC8q-1h

Shop  https //stza.co/+xC8q-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hops @ Hawks
END:VALARM
DTSTART:20180901T011500Z
DTEND:20180901T041500Z
UID:6n2BTqB3v6cITWyCAt0GOKFA@stanza.co
SUMMARY:Hops @ Hawks
DESCRIPTION:Hops @ Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xC8q-1h\n\nShop: https://stza.co/+xC8q-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Volcanoes
<2018-09-01 Sat 21:05>--<2018-09-02 Sun 00:05>
:PROPERTIES:
:ID:       L9imvmw78kZ-lKBLYfEFM_BM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hops vs. Volcanoes Hops vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vOax-23

Shop  https //stza.co/+vOax-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Volcanoes
END:VALARM
DTSTART:20180902T020500Z
DTEND:20180902T050500Z
UID:L9imvmw78kZ-lKBLYfEFM_BM@stanza.co
SUMMARY:Hops vs. Volcanoes
DESCRIPTION:Hops vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vOax-23\n\nShop: https://stza.co/+vOax-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Volcanoes
<2018-09-02 Sun 18:05-21:05>
:PROPERTIES:
:ID:       aZL5KfpTyxfqcoGHPNkkKCeJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops vs. Volcanoes Hops vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vOay-S

Shop  https //stza.co/+vOay-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Volcanoes
END:VALARM
DTSTART:20180902T230500Z
DTEND:20180903T020500Z
UID:aZL5KfpTyxfqcoGHPNkkKCeJ@stanza.co
SUMMARY:Hops vs. Volcanoes
DESCRIPTION:Hops vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vOay-S\n\nShop: https://stza.co/+vOay-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Hops vs. Volcanoes
<2018-09-03 Mon 15:05-18:05>
:PROPERTIES:
:ID:       UDF_qivbiNg8gWM24vnRe42d@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hops vs. Volcanoes Hops vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vOaB-1l

Shop  https //stza.co/+vOaB-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hops vs. Volcanoes
END:VALARM
DTSTART:20180903T200500Z
DTEND:20180903T230500Z
UID:UDF_qivbiNg8gWM24vnRe42d@stanza.co
SUMMARY:Hops vs. Volcanoes
DESCRIPTION:Hops vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vOaB-1l\n\nShop: https://stza.co/+vOaB-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
