#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Chukars vs. Raptors
<2018-06-15 Fri 20:15-23:15>
:PROPERTIES:
:ID:       xYxTN17fHgHXa061cIz_wWQn@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars vs. Raptors Chukars vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xZUQ-S

Shop  https //stza.co/+xZUQ-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Raptors
END:VALARM
DTSTART:20180616T011500Z
DTEND:20180616T041500Z
UID:xYxTN17fHgHXa061cIz_wWQn@stanza.co
SUMMARY:Chukars vs. Raptors
DESCRIPTION:Chukars vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xZUQ-S\n\nShop: https://stza.co/+xZUQ-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Raptors
<2018-06-16 Sat 20:15-23:15>
:PROPERTIES:
:ID:       ecZXx2JKht9pTm9YjHZ3fDM4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chukars vs. Raptors Chukars vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xZUR-1u

Shop  https //stza.co/+xZUR-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Raptors
END:VALARM
DTSTART:20180617T011500Z
DTEND:20180617T041500Z
UID:ecZXx2JKht9pTm9YjHZ3fDM4@stanza.co
SUMMARY:Chukars vs. Raptors
DESCRIPTION:Chukars vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xZUR-1u\n\nShop: https://stza.co/+xZUR-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Raptors
<2018-06-17 Sun 17:00-20:00>
:PROPERTIES:
:ID:       RAxlASCpbAamlFwL4SkfnpjC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars vs. Raptors Chukars vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xZUU-25

Shop  https //stza.co/+xZUU-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Raptors
END:VALARM
DTSTART:20180617T220000Z
DTEND:20180618T010000Z
UID:RAxlASCpbAamlFwL4SkfnpjC@stanza.co
SUMMARY:Chukars vs. Raptors
DESCRIPTION:Chukars vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xZUU-25\n\nShop: https://stza.co/+xZUU-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Raptors
<2018-06-18 Mon 20:15-23:15>
:PROPERTIES:
:ID:       NVXtKByYT8HFZFdQf9dBFI-J@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars vs. Raptors Chukars vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xZUW-3P

Shop  https //stza.co/+xZUW-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Raptors
END:VALARM
DTSTART:20180619T011500Z
DTEND:20180619T041500Z
UID:NVXtKByYT8HFZFdQf9dBFI-J@stanza.co
SUMMARY:Chukars vs. Raptors
DESCRIPTION:Chukars vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xZUW-3P\n\nShop: https://stza.co/+xZUW-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Rockies
<2018-06-19 Tue 19:40-22:40>
:PROPERTIES:
:ID:       AufHM6Eu8-b0Sx3gG9r9l8_d@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chukars @ Rockies Chukars @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ8c-3N

Shop  https //stza.co/+xJ8c-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Rockies
END:VALARM
DTSTART:20180620T004000Z
DTEND:20180620T034000Z
UID:AufHM6Eu8-b0Sx3gG9r9l8_d@stanza.co
SUMMARY:Chukars @ Rockies
DESCRIPTION:Chukars @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ8c-3N\n\nShop: https://stza.co/+xJ8c-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Rockies
<2018-06-20 Wed 19:40-22:40>
:PROPERTIES:
:ID:       AZe8IL9mq2gIsqx7KHaEE87J@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars @ Rockies Chukars @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ8d-3_

Shop  https //stza.co/+xJ8d-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Rockies
END:VALARM
DTSTART:20180621T004000Z
DTEND:20180621T034000Z
UID:AZe8IL9mq2gIsqx7KHaEE87J@stanza.co
SUMMARY:Chukars @ Rockies
DESCRIPTION:Chukars @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ8d-3_\n\nShop: https://stza.co/+xJ8d-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Rockies
<2018-06-21 Thu 19:40-22:40>
:PROPERTIES:
:ID:       jhXL5RljK2mZQjdurslSw8_Y@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars @ Rockies Chukars @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ8e-2n

Shop  https //stza.co/+xJ8e-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Rockies
END:VALARM
DTSTART:20180622T004000Z
DTEND:20180622T034000Z
UID:jhXL5RljK2mZQjdurslSw8_Y@stanza.co
SUMMARY:Chukars @ Rockies
DESCRIPTION:Chukars @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ8e-2n\n\nShop: https://stza.co/+xJ8e-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Rockies
<2018-06-22 Fri 19:40-22:40>
:PROPERTIES:
:ID:       YUmXWmXSdi8cU3WHnPAy8XEM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chukars @ Rockies Chukars @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ8f-p

Shop  https //stza.co/+xJ8f-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Rockies
END:VALARM
DTSTART:20180623T004000Z
DTEND:20180623T034000Z
UID:YUmXWmXSdi8cU3WHnPAy8XEM@stanza.co
SUMMARY:Chukars @ Rockies
DESCRIPTION:Chukars @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ8f-p\n\nShop: https://stza.co/+xJ8f-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Owlz
<2018-06-23 Sat 20:05-23:05>
:PROPERTIES:
:ID:       HQtipd-rC1NvE-ybkUpgx2ZT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars @ Owlz Chukars @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPBi-3a

Shop  https //stza.co/+xPBi-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Owlz
END:VALARM
DTSTART:20180624T010500Z
DTEND:20180624T040500Z
UID:HQtipd-rC1NvE-ybkUpgx2ZT@stanza.co
SUMMARY:Chukars @ Owlz
DESCRIPTION:Chukars @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPBi-3a\n\nShop: https://stza.co/+xPBi-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Owlz
<2018-06-24 Sun 17:05-20:05>
:PROPERTIES:
:ID:       NSQ95YclG_cZFqFMYwf22uzo@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars @ Owlz Chukars @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPBj-t

Shop  https //stza.co/+xPBj-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Owlz
END:VALARM
DTSTART:20180624T220500Z
DTEND:20180625T010500Z
UID:NSQ95YclG_cZFqFMYwf22uzo@stanza.co
SUMMARY:Chukars @ Owlz
DESCRIPTION:Chukars @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPBj-t\n\nShop: https://stza.co/+xPBj-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Owlz
<2018-06-25 Mon 20:05-23:05>
:PROPERTIES:
:ID:       Wfe9yeOmPrnNuOzXCRbZsbGW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chukars @ Owlz Chukars @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPBk-Z

Shop  https //stza.co/+xPBk-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Owlz
END:VALARM
DTSTART:20180626T010500Z
DTEND:20180626T040500Z
UID:Wfe9yeOmPrnNuOzXCRbZsbGW@stanza.co
SUMMARY:Chukars @ Owlz
DESCRIPTION:Chukars @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPBk-Z\n\nShop: https://stza.co/+xPBk-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Rockies
<2018-06-26 Tue 20:15-23:15>
:PROPERTIES:
:ID:       Jis2fGOFkiJdFijYgqaNYtvv@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars vs. Rockies Chukars vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+xZUY-39

Shop  https //stza.co/+xZUY-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Rockies
END:VALARM
DTSTART:20180627T011500Z
DTEND:20180627T041500Z
UID:Jis2fGOFkiJdFijYgqaNYtvv@stanza.co
SUMMARY:Chukars vs. Rockies
DESCRIPTION:Chukars vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xZUY-39\n\nShop: https://stza.co/+xZUY-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Rockies
<2018-06-27 Wed 20:15-23:15>
:PROPERTIES:
:ID:       xgkd9QdsG0tQ7IM1ROFhnVSE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars vs. Rockies Chukars vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+xZUZ-1n

Shop  https //stza.co/+xZUZ-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Rockies
END:VALARM
DTSTART:20180628T011500Z
DTEND:20180628T041500Z
UID:xgkd9QdsG0tQ7IM1ROFhnVSE@stanza.co
SUMMARY:Chukars vs. Rockies
DESCRIPTION:Chukars vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xZUZ-1n\n\nShop: https://stza.co/+xZUZ-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Rockies
<2018-06-28 Thu 20:15-23:15>
:PROPERTIES:
:ID:       E8iLvl6Wb_SFatZNCAJfhfQF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chukars vs. Rockies Chukars vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+xZV0-2j

Shop  https //stza.co/+xZV0-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Rockies
END:VALARM
DTSTART:20180629T011500Z
DTEND:20180629T041500Z
UID:E8iLvl6Wb_SFatZNCAJfhfQF@stanza.co
SUMMARY:Chukars vs. Rockies
DESCRIPTION:Chukars vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xZV0-2j\n\nShop: https://stza.co/+xZV0-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Rockies
<2018-06-29 Fri 20:15-23:15>
:PROPERTIES:
:ID:       MpW-D25Ikglx0P2zKyKpZBys@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars vs. Rockies Chukars vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+xZV1-2g

Shop  https //stza.co/+xZV1-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Rockies
END:VALARM
DTSTART:20180630T011500Z
DTEND:20180630T041500Z
UID:MpW-D25Ikglx0P2zKyKpZBys@stanza.co
SUMMARY:Chukars vs. Rockies
DESCRIPTION:Chukars vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xZV1-2g\n\nShop: https://stza.co/+xZV1-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Raptors
<2018-06-30 Sat 20:00-23:00>
:PROPERTIES:
:ID:       3WMxj5_3bYpcEd01SS9tyDhJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars @ Raptors Chukars @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$81-2z

Shop  https //stza.co/+x$81-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Raptors
END:VALARM
DTSTART:20180701T010000Z
DTEND:20180701T040000Z
UID:3WMxj5_3bYpcEd01SS9tyDhJ@stanza.co
SUMMARY:Chukars @ Raptors
DESCRIPTION:Chukars @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$81-2z\n\nShop: https://stza.co/+x$81-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Raptors
<2018-07-01 Sun 17:00-20:00>
:PROPERTIES:
:ID:       Zm_GHR3ZF3zCrynf8VsKJUsR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chukars @ Raptors Chukars @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$82-21

Shop  https //stza.co/+x$82-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Raptors
END:VALARM
DTSTART:20180701T220000Z
DTEND:20180702T010000Z
UID:Zm_GHR3ZF3zCrynf8VsKJUsR@stanza.co
SUMMARY:Chukars @ Raptors
DESCRIPTION:Chukars @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$82-21\n\nShop: https://stza.co/+x$82-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Raptors
<2018-07-02 Mon 20:00-23:00>
:PROPERTIES:
:ID:       VpUjr_AamxqCIo0PJeqtFtiZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars @ Raptors Chukars @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$83-2B

Shop  https //stza.co/+x$83-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Raptors
END:VALARM
DTSTART:20180703T010000Z
DTEND:20180703T040000Z
UID:VpUjr_AamxqCIo0PJeqtFtiZ@stanza.co
SUMMARY:Chukars @ Raptors
DESCRIPTION:Chukars @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$83-2B\n\nShop: https://stza.co/+x$83-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Raptors
<2018-07-03 Tue 20:00-23:00>
:PROPERTIES:
:ID:       QWpu-eEcre2TyZ7HwWXM2RCB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars @ Raptors Chukars @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$84-3b

Shop  https //stza.co/+x$84-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Raptors
END:VALARM
DTSTART:20180704T010000Z
DTEND:20180704T040000Z
UID:QWpu-eEcre2TyZ7HwWXM2RCB@stanza.co
SUMMARY:Chukars @ Raptors
DESCRIPTION:Chukars @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$84-3b\n\nShop: https://stza.co/+x$84-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Owlz
<2018-07-04 Wed 17:30-20:30>
:PROPERTIES:
:ID:       ilf8O0o8vFN7YNmpvbuF9z07@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chukars vs. Owlz Chukars vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+xZV3-s

Shop  https //stza.co/+xZV3-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Owlz
END:VALARM
DTSTART:20180704T223000Z
DTEND:20180705T013000Z
UID:ilf8O0o8vFN7YNmpvbuF9z07@stanza.co
SUMMARY:Chukars vs. Owlz
DESCRIPTION:Chukars vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xZV3-s\n\nShop: https://stza.co/+xZV3-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Owlz
<2018-07-05 Thu 20:15-23:15>
:PROPERTIES:
:ID:       6EIs2r0bK8AeMJeMtFJ3K2el@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars vs. Owlz Chukars vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+xZV6-i

Shop  https //stza.co/+xZV6-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Owlz
END:VALARM
DTSTART:20180706T011500Z
DTEND:20180706T041500Z
UID:6EIs2r0bK8AeMJeMtFJ3K2el@stanza.co
SUMMARY:Chukars vs. Owlz
DESCRIPTION:Chukars vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xZV6-i\n\nShop: https://stza.co/+xZV6-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Owlz
<2018-07-06 Fri 20:15-23:15>
:PROPERTIES:
:ID:       2N8WxmyxZnhSsI4ikx9hQgeN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars vs. Owlz Chukars vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+xZV7-2Z

Shop  https //stza.co/+xZV7-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Owlz
END:VALARM
DTSTART:20180707T011500Z
DTEND:20180707T041500Z
UID:2N8WxmyxZnhSsI4ikx9hQgeN@stanza.co
SUMMARY:Chukars vs. Owlz
DESCRIPTION:Chukars vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xZV7-2Z\n\nShop: https://stza.co/+xZV7-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Owlz
<2018-07-07 Sat 20:05-23:05>
:PROPERTIES:
:ID:       lGL3N2lmhFoUGkyXYTtzwDEd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chukars @ Owlz Chukars @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPBl-h

Shop  https //stza.co/+xPBl-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Owlz
END:VALARM
DTSTART:20180708T010500Z
DTEND:20180708T040500Z
UID:lGL3N2lmhFoUGkyXYTtzwDEd@stanza.co
SUMMARY:Chukars @ Owlz
DESCRIPTION:Chukars @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPBl-h\n\nShop: https://stza.co/+xPBl-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Owlz
<2018-07-08 Sun 17:05-20:05>
:PROPERTIES:
:ID:       m3_0p6pbhq4hmuHgBsrJ-JVW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars @ Owlz Chukars @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPBm-a

Shop  https //stza.co/+xPBm-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Owlz
END:VALARM
DTSTART:20180708T220500Z
DTEND:20180709T010500Z
UID:m3_0p6pbhq4hmuHgBsrJ-JVW@stanza.co
SUMMARY:Chukars @ Owlz
DESCRIPTION:Chukars @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPBm-a\n\nShop: https://stza.co/+xPBm-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Brewers
<2018-07-10 Tue 20:15-23:15>
:PROPERTIES:
:ID:       LCmBjpxpEoMem65oUVER2uBV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars vs. Brewers Chukars vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xZVa-2Y

Shop  https //stza.co/+xZVa-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Brewers
END:VALARM
DTSTART:20180711T011500Z
DTEND:20180711T041500Z
UID:LCmBjpxpEoMem65oUVER2uBV@stanza.co
SUMMARY:Chukars vs. Brewers
DESCRIPTION:Chukars vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xZVa-2Y\n\nShop: https://stza.co/+xZVa-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Brewers
<2018-07-11 Wed 20:15-23:15>
:PROPERTIES:
:ID:       0y5TmOcD1Gk1iAOepClN9Tzd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chukars vs. Brewers Chukars vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xZVb-1D

Shop  https //stza.co/+xZVb-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Brewers
END:VALARM
DTSTART:20180712T011500Z
DTEND:20180712T041500Z
UID:0y5TmOcD1Gk1iAOepClN9Tzd@stanza.co
SUMMARY:Chukars vs. Brewers
DESCRIPTION:Chukars vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xZVb-1D\n\nShop: https://stza.co/+xZVb-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Brewers
<2018-07-12 Thu 20:15-23:15>
:PROPERTIES:
:ID:       hTIVWjyJ1ogbt7eMlwG85Lv4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars vs. Brewers Chukars vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xZVe-3

Shop  https //stza.co/+xZVe-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Brewers
END:VALARM
DTSTART:20180713T011500Z
DTEND:20180713T041500Z
UID:hTIVWjyJ1ogbt7eMlwG85Lv4@stanza.co
SUMMARY:Chukars vs. Brewers
DESCRIPTION:Chukars vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xZVe-3\n\nShop: https://stza.co/+xZVe-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Brewers
<2018-07-13 Fri 20:15-23:15>
:PROPERTIES:
:ID:       ctg4DlcTM41QlP3BoVPtLG3O@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars vs. Brewers Chukars vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xZVg-

Shop  https //stza.co/+xZVg-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Brewers
END:VALARM
DTSTART:20180714T011500Z
DTEND:20180714T041500Z
UID:ctg4DlcTM41QlP3BoVPtLG3O@stanza.co
SUMMARY:Chukars vs. Brewers
DESCRIPTION:Chukars vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xZVg-\n\nShop: https://stza.co/+xZVg-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Osprey
<2018-07-14 Sat 20:15-23:15>
:PROPERTIES:
:ID:       L91pLPuuW0hl3JAbigooiegj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chukars vs. Osprey Chukars vs. Osprey

Follow on MiLB First Pitch  https //stza.co/+xZVi-l

Shop  https //stza.co/+xZVi-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Osprey
END:VALARM
DTSTART:20180715T011500Z
DTEND:20180715T041500Z
UID:L91pLPuuW0hl3JAbigooiegj@stanza.co
SUMMARY:Chukars vs. Osprey
DESCRIPTION:Chukars vs. Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xZVi-l\n\nShop: https://stza.co/+xZVi-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Osprey
<2018-07-15 Sun 17:00-20:00>
:PROPERTIES:
:ID:       ks64LR0AZ3FjnSI35Yu2ru4d@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars vs. Osprey Chukars vs. Osprey

Follow on MiLB First Pitch  https //stza.co/+xZVk-2N

Shop  https //stza.co/+xZVk-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Osprey
END:VALARM
DTSTART:20180715T220000Z
DTEND:20180716T010000Z
UID:ks64LR0AZ3FjnSI35Yu2ru4d@stanza.co
SUMMARY:Chukars vs. Osprey
DESCRIPTION:Chukars vs. Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xZVk-2N\n\nShop: https://stza.co/+xZVk-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Osprey
<2018-07-16 Mon 20:15-23:15>
:PROPERTIES:
:ID:       0vxXTK50AbUIOdK7_WBPtdf-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars vs. Osprey Chukars vs. Osprey

Follow on MiLB First Pitch  https //stza.co/+xZVm-V

Shop  https //stza.co/+xZVm-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Osprey
END:VALARM
DTSTART:20180717T011500Z
DTEND:20180717T041500Z
UID:0vxXTK50AbUIOdK7_WBPtdf-@stanza.co
SUMMARY:Chukars vs. Osprey
DESCRIPTION:Chukars vs. Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xZVm-V\n\nShop: https://stza.co/+xZVm-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Brewers
<2018-07-18 Wed>--<2018-07-17 Tue>
:PROPERTIES:
:ID:       ZXQWIAYgIpTHPSBn8gFosCcr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chukars @ Brewers Chukars @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCxn-1P

Shop  https //stza.co/+xCxn-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180718
DTEND;VALUE=DATE:20180718
UID:ZXQWIAYgIpTHPSBn8gFosCcr@stanza.co
SUMMARY:Chukars @ Brewers
DESCRIPTION:Chukars @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCxn-1P\n\nShop: https://stza.co/+xCxn-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Brewers
<2018-07-19 Thu>--<2018-07-18 Wed>
:PROPERTIES:
:ID:       fWF6UA0JeprsNU7XVEaMCe1A@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars @ Brewers Chukars @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCxo-3T

Shop  https //stza.co/+xCxo-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180719
DTEND;VALUE=DATE:20180719
UID:fWF6UA0JeprsNU7XVEaMCe1A@stanza.co
SUMMARY:Chukars @ Brewers
DESCRIPTION:Chukars @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCxo-3T\n\nShop: https://stza.co/+xCxo-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Brewers
<2018-07-20 Fri>--<2018-07-19 Thu>
:PROPERTIES:
:ID:       SFkr4n5bIDSeQVBcbdq9iVjj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars @ Brewers Chukars @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCxr-B

Shop  https //stza.co/+xCxr-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180720
DTEND;VALUE=DATE:20180720
UID:SFkr4n5bIDSeQVBcbdq9iVjj@stanza.co
SUMMARY:Chukars @ Brewers
DESCRIPTION:Chukars @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCxr-B\n\nShop: https://stza.co/+xCxr-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Osprey
<2018-07-21 Sat>--<2018-07-20 Fri>
:PROPERTIES:
:ID:       2HPKLsF8HRwWx7i9UUOGjZfz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chukars @ Osprey Chukars @ Osprey

Follow on MiLB First Pitch  https //stza.co/+xCyR-2x

Shop  https //stza.co/+xCyR-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Osprey
END:VALARM
DTSTART;VALUE=DATE:20180721
DTEND;VALUE=DATE:20180721
UID:2HPKLsF8HRwWx7i9UUOGjZfz@stanza.co
SUMMARY:Chukars @ Osprey
DESCRIPTION:Chukars @ Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xCyR-2x\n\nShop: https://stza.co/+xCyR-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Osprey
<2018-07-22 Sun>--<2018-07-21 Sat>
:PROPERTIES:
:ID:       j5HqZAEW004_xGJ1xCbzrxcg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars @ Osprey Chukars @ Osprey

Follow on MiLB First Pitch  https //stza.co/+xCyS-3t

Shop  https //stza.co/+xCyS-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Osprey
END:VALARM
DTSTART;VALUE=DATE:20180722
DTEND;VALUE=DATE:20180722
UID:j5HqZAEW004_xGJ1xCbzrxcg@stanza.co
SUMMARY:Chukars @ Osprey
DESCRIPTION:Chukars @ Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xCyS-3t\n\nShop: https://stza.co/+xCyS-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Osprey
<2018-07-23 Mon>--<2018-07-22 Sun>
:PROPERTIES:
:ID:       eeAN601_-6IMxrS-wW-240-3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars @ Osprey Chukars @ Osprey

Follow on MiLB First Pitch  https //stza.co/+xCyT-2d

Shop  https //stza.co/+xCyT-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Osprey
END:VALARM
DTSTART;VALUE=DATE:20180723
DTEND;VALUE=DATE:20180723
UID:eeAN601_-6IMxrS-wW-240-3@stanza.co
SUMMARY:Chukars @ Osprey
DESCRIPTION:Chukars @ Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xCyT-2d\n\nShop: https://stza.co/+xCyT-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Osprey
<2018-07-24 Tue>--<2018-07-23 Mon>
:PROPERTIES:
:ID:       XGf0QFMUs70GohM1LHS7vsh5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chukars @ Osprey Chukars @ Osprey

Follow on MiLB First Pitch  https //stza.co/+xCyU-3e

Shop  https //stza.co/+xCyU-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Osprey
END:VALARM
DTSTART;VALUE=DATE:20180724
DTEND;VALUE=DATE:20180724
UID:XGf0QFMUs70GohM1LHS7vsh5@stanza.co
SUMMARY:Chukars @ Osprey
DESCRIPTION:Chukars @ Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xCyU-3e\n\nShop: https://stza.co/+xCyU-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Owlz
<2018-07-25 Wed 20:15-23:15>
:PROPERTIES:
:ID:       Kyo0fGIvv37cQnpeIAniUFGL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars vs. Owlz Chukars vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+xZVo-1_

Shop  https //stza.co/+xZVo-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Owlz
END:VALARM
DTSTART:20180726T011500Z
DTEND:20180726T041500Z
UID:Kyo0fGIvv37cQnpeIAniUFGL@stanza.co
SUMMARY:Chukars vs. Owlz
DESCRIPTION:Chukars vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xZVo-1_\n\nShop: https://stza.co/+xZVo-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Owlz
<2018-07-26 Thu 20:15-23:15>
:PROPERTIES:
:ID:       WdKoURu-_y1_HJrZzwnAloCY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars vs. Owlz Chukars vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+xZVp-3_

Shop  https //stza.co/+xZVp-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Owlz
END:VALARM
DTSTART:20180727T011500Z
DTEND:20180727T041500Z
UID:WdKoURu-_y1_HJrZzwnAloCY@stanza.co
SUMMARY:Chukars vs. Owlz
DESCRIPTION:Chukars vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xZVp-3_\n\nShop: https://stza.co/+xZVp-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Owlz
<2018-07-27 Fri 20:15-23:15>
:PROPERTIES:
:ID:       jej4kCkoerviqPmpI6NlAGiV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chukars vs. Owlz Chukars vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+xZVs-h

Shop  https //stza.co/+xZVs-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Owlz
END:VALARM
DTSTART:20180728T011500Z
DTEND:20180728T041500Z
UID:jej4kCkoerviqPmpI6NlAGiV@stanza.co
SUMMARY:Chukars vs. Owlz
DESCRIPTION:Chukars vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xZVs-h\n\nShop: https://stza.co/+xZVs-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Raptors
<2018-07-28 Sat 20:00-23:00>
:PROPERTIES:
:ID:       l-VuEcrUZPU5sDJvFRxQsm3z@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars @ Raptors Chukars @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$85-3

Shop  https //stza.co/+x$85-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Raptors
END:VALARM
DTSTART:20180729T010000Z
DTEND:20180729T040000Z
UID:l-VuEcrUZPU5sDJvFRxQsm3z@stanza.co
SUMMARY:Chukars @ Raptors
DESCRIPTION:Chukars @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$85-3\n\nShop: https://stza.co/+x$85-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Raptors
<2018-07-29 Sun 17:00-20:00>
:PROPERTIES:
:ID:       rbBt7nP2t72T_187_-I4axTB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars @ Raptors Chukars @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$86-3V

Shop  https //stza.co/+x$86-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Raptors
END:VALARM
DTSTART:20180729T220000Z
DTEND:20180730T010000Z
UID:rbBt7nP2t72T_187_-I4axTB@stanza.co
SUMMARY:Chukars @ Raptors
DESCRIPTION:Chukars @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$86-3V\n\nShop: https://stza.co/+x$86-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Owlz
<2018-07-30 Mon 20:05-23:05>
:PROPERTIES:
:ID:       dja6zEcaYWOOhHOYxQZOUJVj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chukars @ Owlz Chukars @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPBn-1R

Shop  https //stza.co/+xPBn-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Owlz
END:VALARM
DTSTART:20180731T010500Z
DTEND:20180731T040500Z
UID:dja6zEcaYWOOhHOYxQZOUJVj@stanza.co
SUMMARY:Chukars @ Owlz
DESCRIPTION:Chukars @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPBn-1R\n\nShop: https://stza.co/+xPBn-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Owlz
<2018-07-31 Tue 20:05-23:05>
:PROPERTIES:
:ID:       3Xwuv0SkoqIpO2sNMXKxTxZq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars @ Owlz Chukars @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPBo-3j

Shop  https //stza.co/+xPBo-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Owlz
END:VALARM
DTSTART:20180801T010500Z
DTEND:20180801T040500Z
UID:3Xwuv0SkoqIpO2sNMXKxTxZq@stanza.co
SUMMARY:Chukars @ Owlz
DESCRIPTION:Chukars @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPBo-3j\n\nShop: https://stza.co/+xPBo-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Owlz
<2018-08-01 Wed 20:05-23:05>
:PROPERTIES:
:ID:       Nw2jWG0ePiClXNcXNPtRWO79@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars @ Owlz Chukars @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPBp-1G

Shop  https //stza.co/+xPBp-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Owlz
END:VALARM
DTSTART:20180802T010500Z
DTEND:20180802T040500Z
UID:Nw2jWG0ePiClXNcXNPtRWO79@stanza.co
SUMMARY:Chukars @ Owlz
DESCRIPTION:Chukars @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPBp-1G\n\nShop: https://stza.co/+xPBp-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Rockies
<2018-08-02 Thu 20:15-23:15>
:PROPERTIES:
:ID:       jubw9tJqHlDjQSSWAeH2w1hr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chukars vs. Rockies Chukars vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+xZVt-3_

Shop  https //stza.co/+xZVt-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Rockies
END:VALARM
DTSTART:20180803T011500Z
DTEND:20180803T041500Z
UID:jubw9tJqHlDjQSSWAeH2w1hr@stanza.co
SUMMARY:Chukars vs. Rockies
DESCRIPTION:Chukars vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xZVt-3_\n\nShop: https://stza.co/+xZVt-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Rockies
<2018-08-03 Fri 20:15-23:15>
:PROPERTIES:
:ID:       tAxOovjxtEXlKzGAWx6Gjhl6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars vs. Rockies Chukars vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+xZVv-1B

Shop  https //stza.co/+xZVv-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Rockies
END:VALARM
DTSTART:20180804T011500Z
DTEND:20180804T041500Z
UID:tAxOovjxtEXlKzGAWx6Gjhl6@stanza.co
SUMMARY:Chukars vs. Rockies
DESCRIPTION:Chukars vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xZVv-1B\n\nShop: https://stza.co/+xZVv-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Rockies
<2018-08-04 Sat 20:15-23:15>
:PROPERTIES:
:ID:       900VdaYNqXVpV9e6XDEAn36Z@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars vs. Rockies Chukars vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+xZVx-1s

Shop  https //stza.co/+xZVx-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Rockies
END:VALARM
DTSTART:20180805T011500Z
DTEND:20180805T041500Z
UID:900VdaYNqXVpV9e6XDEAn36Z@stanza.co
SUMMARY:Chukars vs. Rockies
DESCRIPTION:Chukars vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xZVx-1s\n\nShop: https://stza.co/+xZVx-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Rockies
<2018-08-05 Sun 17:00-20:00>
:PROPERTIES:
:ID:       POk-7Vmp7mJDcreDLJxwmfG8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chukars vs. Rockies Chukars vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+xZVA-3x

Shop  https //stza.co/+xZVA-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Rockies
END:VALARM
DTSTART:20180805T220000Z
DTEND:20180806T010000Z
UID:POk-7Vmp7mJDcreDLJxwmfG8@stanza.co
SUMMARY:Chukars vs. Rockies
DESCRIPTION:Chukars vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xZVA-3x\n\nShop: https://stza.co/+xZVA-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Voyagers
<2018-08-09 Thu>--<2018-08-08 Wed>
:PROPERTIES:
:ID:       av4Y4LBHeAO8NZcgpz10L-b_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars @ Voyagers Chukars @ Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCza-2i

Shop  https //stza.co/+xCza-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180809
DTEND;VALUE=DATE:20180809
UID:av4Y4LBHeAO8NZcgpz10L-b_@stanza.co
SUMMARY:Chukars @ Voyagers
DESCRIPTION:Chukars @ Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCza-2i\n\nShop: https://stza.co/+xCza-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Voyagers
<2018-08-10 Fri>--<2018-08-09 Thu>
:PROPERTIES:
:ID:       AdHNVISAaVEkkjwcyu-xafsN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars @ Voyagers Chukars @ Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCzb-17

Shop  https //stza.co/+xCzb-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180810
DTEND;VALUE=DATE:20180810
UID:AdHNVISAaVEkkjwcyu-xafsN@stanza.co
SUMMARY:Chukars @ Voyagers
DESCRIPTION:Chukars @ Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCzb-17\n\nShop: https://stza.co/+xCzb-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Voyagers
<2018-08-11 Sat>--<2018-08-10 Fri>
:PROPERTIES:
:ID:       m4DRZFOYzcmGnU01QI2KzpaT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chukars @ Voyagers Chukars @ Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCzc-8

Shop  https //stza.co/+xCzc-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180811
DTEND;VALUE=DATE:20180811
UID:m4DRZFOYzcmGnU01QI2KzpaT@stanza.co
SUMMARY:Chukars @ Voyagers
DESCRIPTION:Chukars @ Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCzc-8\n\nShop: https://stza.co/+xCzc-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Voyagers
<2018-08-12 Sun>--<2018-08-11 Sat>
:PROPERTIES:
:ID:       -XMd9bhEg3Q3aVDyluJRVk1O@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars @ Voyagers Chukars @ Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCzd-2g

Shop  https //stza.co/+xCzd-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180812
DTEND;VALUE=DATE:20180812
UID:-XMd9bhEg3Q3aVDyluJRVk1O@stanza.co
SUMMARY:Chukars @ Voyagers
DESCRIPTION:Chukars @ Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCzd-2g\n\nShop: https://stza.co/+xCzd-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Mustangs
<2018-08-13 Mon 20:05-23:05>
:PROPERTIES:
:ID:       Ha7Selxoz_JTHSUoIMKoZxyb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars @ Mustangs Chukars @ Mustangs

Follow on MiLB First Pitch  https //stza.co/+xSOK-35

Shop  https //stza.co/+xSOK-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Mustangs
END:VALARM
DTSTART:20180814T010500Z
DTEND:20180814T040500Z
UID:Ha7Selxoz_JTHSUoIMKoZxyb@stanza.co
SUMMARY:Chukars @ Mustangs
DESCRIPTION:Chukars @ Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xSOK-35\n\nShop: https://stza.co/+xSOK-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Mustangs
<2018-08-14 Tue 20:05-23:05>
:PROPERTIES:
:ID:       UEcC8ZvUoegS0PbPsRjpRNij@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chukars @ Mustangs Chukars @ Mustangs

Follow on MiLB First Pitch  https //stza.co/+xSOL-1A

Shop  https //stza.co/+xSOL-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Mustangs
END:VALARM
DTSTART:20180815T010500Z
DTEND:20180815T040500Z
UID:UEcC8ZvUoegS0PbPsRjpRNij@stanza.co
SUMMARY:Chukars @ Mustangs
DESCRIPTION:Chukars @ Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xSOL-1A\n\nShop: https://stza.co/+xSOL-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Mustangs
<2018-08-15 Wed 20:05-23:05>
:PROPERTIES:
:ID:       S7W-ACSBi2fd4EblS7l_EHE9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars @ Mustangs Chukars @ Mustangs

Follow on MiLB First Pitch  https //stza.co/+xSOM-3Q

Shop  https //stza.co/+xSOM-2S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Mustangs
END:VALARM
DTSTART:20180816T010500Z
DTEND:20180816T040500Z
UID:S7W-ACSBi2fd4EblS7l_EHE9@stanza.co
SUMMARY:Chukars @ Mustangs
DESCRIPTION:Chukars @ Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xSOM-3Q\n\nShop: https://stza.co/+xSOM-2S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Voyagers
<2018-08-17 Fri 20:15-23:15>
:PROPERTIES:
:ID:       rx2P4GjHuMaIoa6HsaM_CB6i@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars vs. Voyagers Chukars vs. Voyagers

Follow on MiLB First Pitch  https //stza.co/+xZVB-$

Shop  https //stza.co/+xZVB-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Voyagers
END:VALARM
DTSTART:20180818T011500Z
DTEND:20180818T041500Z
UID:rx2P4GjHuMaIoa6HsaM_CB6i@stanza.co
SUMMARY:Chukars vs. Voyagers
DESCRIPTION:Chukars vs. Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xZVB-$\n\nShop: https://stza.co/+xZVB-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Voyagers
<2018-08-18 Sat 20:15-23:15>
:PROPERTIES:
:ID:       kZoeEvnMp15Dctv9UbXMhE-r@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chukars vs. Voyagers Chukars vs. Voyagers

Follow on MiLB First Pitch  https //stza.co/+xZVE-25

Shop  https //stza.co/+xZVE-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Voyagers
END:VALARM
DTSTART:20180819T011500Z
DTEND:20180819T041500Z
UID:kZoeEvnMp15Dctv9UbXMhE-r@stanza.co
SUMMARY:Chukars vs. Voyagers
DESCRIPTION:Chukars vs. Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xZVE-25\n\nShop: https://stza.co/+xZVE-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Voyagers
<2018-08-19 Sun 17:00-20:00>
:PROPERTIES:
:ID:       6VFV5gjPKEXK_tDoMwnZJzRU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars vs. Voyagers Chukars vs. Voyagers

Follow on MiLB First Pitch  https //stza.co/+xZVG-_

Shop  https //stza.co/+xZVG-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Voyagers
END:VALARM
DTSTART:20180819T220000Z
DTEND:20180820T010000Z
UID:6VFV5gjPKEXK_tDoMwnZJzRU@stanza.co
SUMMARY:Chukars vs. Voyagers
DESCRIPTION:Chukars vs. Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xZVG-_\n\nShop: https://stza.co/+xZVG-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Mustangs
<2018-08-20 Mon 20:15-23:15>
:PROPERTIES:
:ID:       dL6ZE097XN9h6jQehozRPogA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars vs. Mustangs Chukars vs. Mustangs

Follow on MiLB First Pitch  https //stza.co/+xZVI-3H

Shop  https //stza.co/+xZVI-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Mustangs
END:VALARM
DTSTART:20180821T011500Z
DTEND:20180821T041500Z
UID:dL6ZE097XN9h6jQehozRPogA@stanza.co
SUMMARY:Chukars vs. Mustangs
DESCRIPTION:Chukars vs. Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xZVI-3H\n\nShop: https://stza.co/+xZVI-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Mustangs
<2018-08-21 Tue 20:15-23:15>
:PROPERTIES:
:ID:       6DrAZN1n-02skC2_13NiDMS0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chukars vs. Mustangs Chukars vs. Mustangs

Follow on MiLB First Pitch  https //stza.co/+xZVJ-s

Shop  https //stza.co/+xZVJ-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Mustangs
END:VALARM
DTSTART:20180822T011500Z
DTEND:20180822T041500Z
UID:6DrAZN1n-02skC2_13NiDMS0@stanza.co
SUMMARY:Chukars vs. Mustangs
DESCRIPTION:Chukars vs. Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xZVJ-s\n\nShop: https://stza.co/+xZVJ-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Mustangs
<2018-08-22 Wed 20:15-23:15>
:PROPERTIES:
:ID:       pc1mOn8JIwPt60Fj6kdyqnUq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars vs. Mustangs Chukars vs. Mustangs

Follow on MiLB First Pitch  https //stza.co/+xZVL-3P

Shop  https //stza.co/+xZVL-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Mustangs
END:VALARM
DTSTART:20180823T011500Z
DTEND:20180823T041500Z
UID:pc1mOn8JIwPt60Fj6kdyqnUq@stanza.co
SUMMARY:Chukars vs. Mustangs
DESCRIPTION:Chukars vs. Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xZVL-3P\n\nShop: https://stza.co/+xZVL-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Mustangs
<2018-08-23 Thu 20:15-23:15>
:PROPERTIES:
:ID:       kaKxCwmBMp33IfU7s7csv7Uh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars vs. Mustangs Chukars vs. Mustangs

Follow on MiLB First Pitch  https //stza.co/+xZVO-w

Shop  https //stza.co/+xZVO-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Mustangs
END:VALARM
DTSTART:20180824T011500Z
DTEND:20180824T041500Z
UID:kaKxCwmBMp33IfU7s7csv7Uh@stanza.co
SUMMARY:Chukars vs. Mustangs
DESCRIPTION:Chukars vs. Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xZVO-w\n\nShop: https://stza.co/+xZVO-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Rockies
<2018-08-25 Sat 19:40-22:40>
:PROPERTIES:
:ID:       Ihr4TKl8j5V6o3cWuGdHW5S5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chukars @ Rockies Chukars @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ8g-2I

Shop  https //stza.co/+xJ8g-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Rockies
END:VALARM
DTSTART:20180826T004000Z
DTEND:20180826T034000Z
UID:Ihr4TKl8j5V6o3cWuGdHW5S5@stanza.co
SUMMARY:Chukars @ Rockies
DESCRIPTION:Chukars @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ8g-2I\n\nShop: https://stza.co/+xJ8g-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Rockies
<2018-08-26 Sun 18:00-21:00>
:PROPERTIES:
:ID:       H7ElA6aT2qcFlUXRD1p_jV-1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars @ Rockies Chukars @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ8h-W

Shop  https //stza.co/+xJ8h-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Rockies
END:VALARM
DTSTART:20180826T230000Z
DTEND:20180827T020000Z
UID:H7ElA6aT2qcFlUXRD1p_jV-1@stanza.co
SUMMARY:Chukars @ Rockies
DESCRIPTION:Chukars @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ8h-W\n\nShop: https://stza.co/+xJ8h-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Rockies
<2018-08-27 Mon 19:40-22:40>
:PROPERTIES:
:ID:       4QCd86tna-HutOUuDsqfqqRu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars @ Rockies Chukars @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ8i-1i

Shop  https //stza.co/+xJ8i-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Rockies
END:VALARM
DTSTART:20180828T004000Z
DTEND:20180828T034000Z
UID:4QCd86tna-HutOUuDsqfqqRu@stanza.co
SUMMARY:Chukars @ Rockies
DESCRIPTION:Chukars @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ8i-1i\n\nShop: https://stza.co/+xJ8i-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Rockies
<2018-08-28 Tue 19:40-22:40>
:PROPERTIES:
:ID:       x43eEmWeAAArPEzUTcfFocoO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chukars @ Rockies Chukars @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ8j-3k

Shop  https //stza.co/+xJ8j-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Rockies
END:VALARM
DTSTART:20180829T004000Z
DTEND:20180829T034000Z
UID:x43eEmWeAAArPEzUTcfFocoO@stanza.co
SUMMARY:Chukars @ Rockies
DESCRIPTION:Chukars @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ8j-3k\n\nShop: https://stza.co/+xJ8j-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Raptors
<2018-08-29 Wed 19:30-22:30>
:PROPERTIES:
:ID:       wn84Cmhi_F0MEsQV43DxwssU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars @ Raptors Chukars @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$87-V

Shop  https //stza.co/+x$87-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Raptors
END:VALARM
DTSTART:20180830T003000Z
DTEND:20180830T033000Z
UID:wn84Cmhi_F0MEsQV43DxwssU@stanza.co
SUMMARY:Chukars @ Raptors
DESCRIPTION:Chukars @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$87-V\n\nShop: https://stza.co/+x$87-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars @ Raptors
<2018-08-30 Thu 19:30-22:30>
:PROPERTIES:
:ID:       8DptCbjgFiKwyGkFNHgFPO6N@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars @ Raptors Chukars @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$88-3O

Shop  https //stza.co/+x$88-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chukars @ Raptors
END:VALARM
DTSTART:20180831T003000Z
DTEND:20180831T033000Z
UID:8DptCbjgFiKwyGkFNHgFPO6N@stanza.co
SUMMARY:Chukars @ Raptors
DESCRIPTION:Chukars @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$88-3O\n\nShop: https://stza.co/+x$88-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Owlz
<2018-08-31 Fri 20:15-23:15>
:PROPERTIES:
:ID:       R3meqUfvmuoIRVPeol8nQIYF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chukars vs. Owlz Chukars vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+xZVP-b

Shop  https //stza.co/+xZVP-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Owlz
END:VALARM
DTSTART:20180901T011500Z
DTEND:20180901T041500Z
UID:R3meqUfvmuoIRVPeol8nQIYF@stanza.co
SUMMARY:Chukars vs. Owlz
DESCRIPTION:Chukars vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xZVP-b\n\nShop: https://stza.co/+xZVP-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Owlz
<2018-09-01 Sat 20:15-23:15>
:PROPERTIES:
:ID:       nefHROsXjW98wk1XpYnvELcN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars vs. Owlz Chukars vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+xZVS-12

Shop  https //stza.co/+xZVS-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Owlz
END:VALARM
DTSTART:20180902T011500Z
DTEND:20180902T041500Z
UID:nefHROsXjW98wk1XpYnvELcN@stanza.co
SUMMARY:Chukars vs. Owlz
DESCRIPTION:Chukars vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xZVS-12\n\nShop: https://stza.co/+xZVS-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Raptors
<2018-09-03 Mon 17:00-20:00>
:PROPERTIES:
:ID:       5bkn7Yq0c1dNg_TWuFLFxbS3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars vs. Raptors Chukars vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xZVU-M

Shop  https //stza.co/+xZVU-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Raptors
END:VALARM
DTSTART:20180903T220000Z
DTEND:20180904T010000Z
UID:5bkn7Yq0c1dNg_TWuFLFxbS3@stanza.co
SUMMARY:Chukars vs. Raptors
DESCRIPTION:Chukars vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xZVU-M\n\nShop: https://stza.co/+xZVU-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Raptors
<2018-09-04 Tue 20:15-23:15>
:PROPERTIES:
:ID:       Alep8ASwf97wiNoEwuSh9Xjz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chukars vs. Raptors Chukars vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xZVV-1e

Shop  https //stza.co/+xZVV-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Raptors
END:VALARM
DTSTART:20180905T011500Z
DTEND:20180905T041500Z
UID:Alep8ASwf97wiNoEwuSh9Xjz@stanza.co
SUMMARY:Chukars vs. Raptors
DESCRIPTION:Chukars vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xZVV-1e\n\nShop: https://stza.co/+xZVV-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Raptors
<2018-09-05 Wed 20:15-23:15>
:PROPERTIES:
:ID:       W1G2gNInNVzxy9qqI3xUdI5K@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars vs. Raptors Chukars vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xZVY-1S

Shop  https //stza.co/+xZVY-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Raptors
END:VALARM
DTSTART:20180906T011500Z
DTEND:20180906T041500Z
UID:W1G2gNInNVzxy9qqI3xUdI5K@stanza.co
SUMMARY:Chukars vs. Raptors
DESCRIPTION:Chukars vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xZVY-1S\n\nShop: https://stza.co/+xZVY-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* Chukars vs. Raptors
<2018-09-06 Thu 20:15-23:15>
:PROPERTIES:
:ID:       _VqEMy4ySt5xwDDKnnQCLMAq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chukars vs. Raptors Chukars vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xZV_-2Q

Shop  https //stza.co/+xZV_-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chukars vs. Raptors
END:VALARM
DTSTART:20180907T011500Z
DTEND:20180907T041500Z
UID:_VqEMy4ySt5xwDDKnnQCLMAq@stanza.co
SUMMARY:Chukars vs. Raptors
DESCRIPTION:Chukars vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xZV_-2Q\n\nShop: https://stza.co/+xZV_-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
