#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Braves vs. Yankees
<2018-06-19 Tue 18:00-21:00>
:PROPERTIES:
:ID:       QjG8NyIZ6zmeCdyqXp-k5Q4L@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Yankees Braves vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xDSp-3K

Shop  https //stza.co/+xDSp-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Yankees
END:VALARM
DTSTART:20180619T230000Z
DTEND:20180620T020000Z
UID:QjG8NyIZ6zmeCdyqXp-k5Q4L@stanza.co
SUMMARY:Braves vs. Yankees
DESCRIPTION:Braves vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xDSp-3K\n\nShop: https://stza.co/+xDSp-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Yankees
<2018-06-20 Wed 18:00-21:00>
:PROPERTIES:
:ID:       0TmsxYsqZyH7SyVRPOJVxwgF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Yankees Braves vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xDSr-1C

Shop  https //stza.co/+xDSr-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Yankees
END:VALARM
DTSTART:20180620T230000Z
DTEND:20180621T020000Z
UID:0TmsxYsqZyH7SyVRPOJVxwgF@stanza.co
SUMMARY:Braves vs. Yankees
DESCRIPTION:Braves vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xDSr-1C\n\nShop: https://stza.co/+xDSr-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Yankees
<2018-06-21 Thu 18:00-21:00>
:PROPERTIES:
:ID:       fkIC-bTo701OnSyFUGH2fZf4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Yankees Braves vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xDSv-1o

Shop  https //stza.co/+xDSv-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Yankees
END:VALARM
DTSTART:20180621T230000Z
DTEND:20180622T020000Z
UID:fkIC-bTo701OnSyFUGH2fZf4@stanza.co
SUMMARY:Braves vs. Yankees
DESCRIPTION:Braves vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xDSv-1o\n\nShop: https://stza.co/+xDSv-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Rays
<2018-06-22 Fri>--<2018-06-21 Thu>
:PROPERTIES:
:ID:       6N-DlY1fDkhdIosJGtysLv9H@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Rays Braves @ Rays

Follow on MiLB First Pitch  https //stza.co/+xCJB-1B

Shop  https //stza.co/+xCJB-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Rays
END:VALARM
DTSTART;VALUE=DATE:20180622
DTEND;VALUE=DATE:20180622
UID:6N-DlY1fDkhdIosJGtysLv9H@stanza.co
SUMMARY:Braves @ Rays
DESCRIPTION:Braves @ Rays\n\nFollow on MiLB First Pitch: https://stza.co/+xCJB-1B\n\nShop: https://stza.co/+xCJB-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Rays
<2018-06-23 Sat>--<2018-06-22 Fri>
:PROPERTIES:
:ID:       7QYqNxTVjJt7ZI8JTfJVA3te@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Rays Braves @ Rays

Follow on MiLB First Pitch  https //stza.co/+xCJC-3z

Shop  https //stza.co/+xCJC-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Rays
END:VALARM
DTSTART;VALUE=DATE:20180623
DTEND;VALUE=DATE:20180623
UID:7QYqNxTVjJt7ZI8JTfJVA3te@stanza.co
SUMMARY:Braves @ Rays
DESCRIPTION:Braves @ Rays\n\nFollow on MiLB First Pitch: https://stza.co/+xCJC-3z\n\nShop: https://stza.co/+xCJC-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Rays
<2018-06-24 Sun>--<2018-06-23 Sat>
:PROPERTIES:
:ID:       dDase18XrN5Rzwc67q1P_EBX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Rays Braves @ Rays

Follow on MiLB First Pitch  https //stza.co/+xCJD-z

Shop  https //stza.co/+xCJD-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Rays
END:VALARM
DTSTART;VALUE=DATE:20180624
DTEND;VALUE=DATE:20180624
UID:dDase18XrN5Rzwc67q1P_EBX@stanza.co
SUMMARY:Braves @ Rays
DESCRIPTION:Braves @ Rays\n\nFollow on MiLB First Pitch: https://stza.co/+xCJD-z\n\nShop: https://stza.co/+xCJD-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Royals
<2018-06-25 Mon>--<2018-06-24 Sun>
:PROPERTIES:
:ID:       82_3zzcxNEDJOEFynWGixTc5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Royals Braves @ Royals

Follow on MiLB First Pitch  https //stza.co/+xCJE-2Y

Shop  https //stza.co/+xCJE-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Royals
END:VALARM
DTSTART;VALUE=DATE:20180625
DTEND;VALUE=DATE:20180625
UID:82_3zzcxNEDJOEFynWGixTc5@stanza.co
SUMMARY:Braves @ Royals
DESCRIPTION:Braves @ Royals\n\nFollow on MiLB First Pitch: https://stza.co/+xCJE-2Y\n\nShop: https://stza.co/+xCJE-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Royals
<2018-06-26 Tue>--<2018-06-25 Mon>
:PROPERTIES:
:ID:       _Hm7hOgffhALVver1vEwLHRP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Royals Braves @ Royals

Follow on MiLB First Pitch  https //stza.co/+xCJF-q

Shop  https //stza.co/+xCJF-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Royals
END:VALARM
DTSTART;VALUE=DATE:20180626
DTEND;VALUE=DATE:20180626
UID:_Hm7hOgffhALVver1vEwLHRP@stanza.co
SUMMARY:Braves @ Royals
DESCRIPTION:Braves @ Royals\n\nFollow on MiLB First Pitch: https://stza.co/+xCJF-q\n\nShop: https://stza.co/+xCJF-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Twins
<2018-06-28 Thu 18:00-21:00>
:PROPERTIES:
:ID:       qWoE77WTafbIIITzl4IggNK-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Twins Braves vs. Twins

Follow on MiLB First Pitch  https //stza.co/+xDSw-2W

Shop  https //stza.co/+xDSw-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Twins
END:VALARM
DTSTART:20180628T230000Z
DTEND:20180629T020000Z
UID:qWoE77WTafbIIITzl4IggNK-@stanza.co
SUMMARY:Braves vs. Twins
DESCRIPTION:Braves vs. Twins\n\nFollow on MiLB First Pitch: https://stza.co/+xDSw-2W\n\nShop: https://stza.co/+xDSw-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Twins
<2018-06-29 Fri 18:00-21:00>
:PROPERTIES:
:ID:       VOsmcyc7zZXu2JxppyPLNnha@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Twins Braves vs. Twins

Follow on MiLB First Pitch  https //stza.co/+xDSB-33

Shop  https //stza.co/+xDSB-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Twins
END:VALARM
DTSTART:20180629T230000Z
DTEND:20180630T020000Z
UID:VOsmcyc7zZXu2JxppyPLNnha@stanza.co
SUMMARY:Braves vs. Twins
DESCRIPTION:Braves vs. Twins\n\nFollow on MiLB First Pitch: https://stza.co/+xDSB-33\n\nShop: https://stza.co/+xDSB-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Twins
<2018-06-30 Sat 18:00-21:00>
:PROPERTIES:
:ID:       T2lSOmBLgNbU8If70hRmoUHu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Twins Braves vs. Twins

Follow on MiLB First Pitch  https //stza.co/+xDSD-I

Shop  https //stza.co/+xDSD-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Twins
END:VALARM
DTSTART:20180630T230000Z
DTEND:20180701T020000Z
UID:T2lSOmBLgNbU8If70hRmoUHu@stanza.co
SUMMARY:Braves vs. Twins
DESCRIPTION:Braves vs. Twins\n\nFollow on MiLB First Pitch: https://stza.co/+xDSD-I\n\nShop: https://stza.co/+xDSD-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Pirates
<2018-07-01 Sun 15:00-18:00>
:PROPERTIES:
:ID:       rkWh_pYUsSI8BW2MrtrS6U7G@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Pirates Braves vs. Pirates

Follow on MiLB First Pitch  https //stza.co/+xDSE-H

Shop  https //stza.co/+xDSE-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Pirates
END:VALARM
DTSTART:20180701T200000Z
DTEND:20180701T230000Z
UID:rkWh_pYUsSI8BW2MrtrS6U7G@stanza.co
SUMMARY:Braves vs. Pirates
DESCRIPTION:Braves vs. Pirates\n\nFollow on MiLB First Pitch: https://stza.co/+xDSE-H\n\nShop: https://stza.co/+xDSE-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Pirates
<2018-07-02 Mon 18:00-21:00>
:PROPERTIES:
:ID:       cM23sqNN9KoCY3FnAyNsswPG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Pirates Braves vs. Pirates

Follow on MiLB First Pitch  https //stza.co/+xDSG-3O

Shop  https //stza.co/+xDSG-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Pirates
END:VALARM
DTSTART:20180702T230000Z
DTEND:20180703T020000Z
UID:cM23sqNN9KoCY3FnAyNsswPG@stanza.co
SUMMARY:Braves vs. Pirates
DESCRIPTION:Braves vs. Pirates\n\nFollow on MiLB First Pitch: https://stza.co/+xDSG-3O\n\nShop: https://stza.co/+xDSG-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Pirates
<2018-07-03 Tue 18:00-21:00>
:PROPERTIES:
:ID:       hvmgSeo0QZQnFEAtwCuxUacO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Pirates Braves vs. Pirates

Follow on MiLB First Pitch  https //stza.co/+xDSK-3x

Shop  https //stza.co/+xDSK-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Pirates
END:VALARM
DTSTART:20180703T230000Z
DTEND:20180704T020000Z
UID:hvmgSeo0QZQnFEAtwCuxUacO@stanza.co
SUMMARY:Braves vs. Pirates
DESCRIPTION:Braves vs. Pirates\n\nFollow on MiLB First Pitch: https://stza.co/+xDSK-3x\n\nShop: https://stza.co/+xDSK-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Astros
<2018-07-04 Wed>--<2018-07-03 Tue>
:PROPERTIES:
:ID:       9mN8gWodJyQFCqvLiys-WYPU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Astros Braves @ Astros

Follow on MiLB First Pitch  https //stza.co/+xCdw-13

Shop  https //stza.co/+xCdw-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Astros
END:VALARM
DTSTART;VALUE=DATE:20180704
DTEND;VALUE=DATE:20180704
UID:9mN8gWodJyQFCqvLiys-WYPU@stanza.co
SUMMARY:Braves @ Astros
DESCRIPTION:Braves @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xCdw-13\n\nShop: https://stza.co/+xCdw-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Astros
<2018-07-05 Thu>--<2018-07-04 Wed>
:PROPERTIES:
:ID:       SWFduYjqmySVV38U2FE5lopN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Astros Braves @ Astros

Follow on MiLB First Pitch  https //stza.co/+xCdH-3y

Shop  https //stza.co/+xCdH-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Astros
END:VALARM
DTSTART;VALUE=DATE:20180705
DTEND;VALUE=DATE:20180705
UID:SWFduYjqmySVV38U2FE5lopN@stanza.co
SUMMARY:Braves @ Astros
DESCRIPTION:Braves @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xCdH-3y\n\nShop: https://stza.co/+xCdH-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Astros
<2018-07-06 Fri>--<2018-07-05 Thu>
:PROPERTIES:
:ID:       K2Nn3wAgIuVRAQ0CtOq1bwb_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Astros Braves @ Astros

Follow on MiLB First Pitch  https //stza.co/+xCdW-2u

Shop  https //stza.co/+xCdW-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Astros
END:VALARM
DTSTART;VALUE=DATE:20180706
DTEND;VALUE=DATE:20180706
UID:K2Nn3wAgIuVRAQ0CtOq1bwb_@stanza.co
SUMMARY:Braves @ Astros
DESCRIPTION:Braves @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xCdW-2u\n\nShop: https://stza.co/+xCdW-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Twins
<2018-07-07 Sat>--<2018-07-06 Fri>
:PROPERTIES:
:ID:       gYnfclipxtstM9HE5y7HGLt_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Twins Braves @ Twins

Follow on MiLB First Pitch  https //stza.co/+xCe5-2Y

Shop  https //stza.co/+xCe5-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Twins
END:VALARM
DTSTART;VALUE=DATE:20180707
DTEND;VALUE=DATE:20180707
UID:gYnfclipxtstM9HE5y7HGLt_@stanza.co
SUMMARY:Braves @ Twins
DESCRIPTION:Braves @ Twins\n\nFollow on MiLB First Pitch: https://stza.co/+xCe5-2Y\n\nShop: https://stza.co/+xCe5-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Twins
<2018-07-08 Sun>--<2018-07-07 Sat>
:PROPERTIES:
:ID:       T8P18BLoKuph5Twnlj03Z4IB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Twins Braves @ Twins

Follow on MiLB First Pitch  https //stza.co/+xCec-3o

Shop  https //stza.co/+xCec-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Twins
END:VALARM
DTSTART;VALUE=DATE:20180708
DTEND;VALUE=DATE:20180708
UID:T8P18BLoKuph5Twnlj03Z4IB@stanza.co
SUMMARY:Braves @ Twins
DESCRIPTION:Braves @ Twins\n\nFollow on MiLB First Pitch: https://stza.co/+xCec-3o\n\nShop: https://stza.co/+xCec-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Twins
<2018-07-09 Mon>--<2018-07-08 Sun>
:PROPERTIES:
:ID:       hbv7E1pp7JIViQXonc9tBEap@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Twins Braves @ Twins

Follow on MiLB First Pitch  https //stza.co/+xCek-2q

Shop  https //stza.co/+xCek-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Twins
END:VALARM
DTSTART;VALUE=DATE:20180709
DTEND;VALUE=DATE:20180709
UID:hbv7E1pp7JIViQXonc9tBEap@stanza.co
SUMMARY:Braves @ Twins
DESCRIPTION:Braves @ Twins\n\nFollow on MiLB First Pitch: https://stza.co/+xCek-2q\n\nShop: https://stza.co/+xCek-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Royals
<2018-07-10 Tue 18:00-21:00>
:PROPERTIES:
:ID:       Uyy8sABLjsJUpG7ILehQnEI8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Royals Braves vs. Royals

Follow on MiLB First Pitch  https //stza.co/+xDSL-C

Shop  https //stza.co/+xDSL-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Royals
END:VALARM
DTSTART:20180710T230000Z
DTEND:20180711T020000Z
UID:Uyy8sABLjsJUpG7ILehQnEI8@stanza.co
SUMMARY:Braves vs. Royals
DESCRIPTION:Braves vs. Royals\n\nFollow on MiLB First Pitch: https://stza.co/+xDSL-C\n\nShop: https://stza.co/+xDSL-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Royals
<2018-07-11 Wed 18:00-21:00>
:PROPERTIES:
:ID:       iDwz42nu_WwDcAgbPnrC1Q9u@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Royals Braves vs. Royals

Follow on MiLB First Pitch  https //stza.co/+xDSO-2w

Shop  https //stza.co/+xDSO-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Royals
END:VALARM
DTSTART:20180711T230000Z
DTEND:20180712T020000Z
UID:iDwz42nu_WwDcAgbPnrC1Q9u@stanza.co
SUMMARY:Braves vs. Royals
DESCRIPTION:Braves vs. Royals\n\nFollow on MiLB First Pitch: https://stza.co/+xDSO-2w\n\nShop: https://stza.co/+xDSO-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Royals
<2018-07-12 Thu 18:00-21:00>
:PROPERTIES:
:ID:       SxkXqJVPeBaLQS2WlTXeihkP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Royals Braves vs. Royals

Follow on MiLB First Pitch  https //stza.co/+xDSR-2V

Shop  https //stza.co/+xDSR-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Royals
END:VALARM
DTSTART:20180712T230000Z
DTEND:20180713T020000Z
UID:SxkXqJVPeBaLQS2WlTXeihkP@stanza.co
SUMMARY:Braves vs. Royals
DESCRIPTION:Braves vs. Royals\n\nFollow on MiLB First Pitch: https://stza.co/+xDSR-2V\n\nShop: https://stza.co/+xDSR-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Royals
<2018-07-13 Fri 18:00-21:00>
:PROPERTIES:
:ID:       kCQWqsE452XkKR4npxEM8Cuu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Royals Braves vs. Royals

Follow on MiLB First Pitch  https //stza.co/+xDSS-3G

Shop  https //stza.co/+xDSS-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Royals
END:VALARM
DTSTART:20180713T230000Z
DTEND:20180714T020000Z
UID:kCQWqsE452XkKR4npxEM8Cuu@stanza.co
SUMMARY:Braves vs. Royals
DESCRIPTION:Braves vs. Royals\n\nFollow on MiLB First Pitch: https://stza.co/+xDSS-3G\n\nShop: https://stza.co/+xDSS-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Blue Jays
<2018-07-14 Sat>--<2018-07-13 Fri>
:PROPERTIES:
:ID:       EWgCwImrdXQy22D6klDCn6px@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Blue Jays Braves @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xCfe-1o

Shop  https //stza.co/+xCfe-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Blue Jays
END:VALARM
DTSTART;VALUE=DATE:20180714
DTEND;VALUE=DATE:20180714
UID:EWgCwImrdXQy22D6klDCn6px@stanza.co
SUMMARY:Braves @ Blue Jays
DESCRIPTION:Braves @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xCfe-1o\n\nShop: https://stza.co/+xCfe-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Blue Jays
<2018-07-15 Sun>--<2018-07-14 Sat>
:PROPERTIES:
:ID:       HHyXRATEzvuqBBabQMmr6hKi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Blue Jays Braves @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xCfq-2x

Shop  https //stza.co/+xCfq-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Blue Jays
END:VALARM
DTSTART;VALUE=DATE:20180715
DTEND;VALUE=DATE:20180715
UID:HHyXRATEzvuqBBabQMmr6hKi@stanza.co
SUMMARY:Braves @ Blue Jays
DESCRIPTION:Braves @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xCfq-2x\n\nShop: https://stza.co/+xCfq-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Blue Jays
<2018-07-16 Mon>--<2018-07-15 Sun>
:PROPERTIES:
:ID:       PDoiHXyPbjlUPHI4U0EbD5YU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Blue Jays Braves @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xCfx-2e

Shop  https //stza.co/+xCfx-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Blue Jays
END:VALARM
DTSTART;VALUE=DATE:20180716
DTEND;VALUE=DATE:20180716
UID:PDoiHXyPbjlUPHI4U0EbD5YU@stanza.co
SUMMARY:Braves @ Blue Jays
DESCRIPTION:Braves @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xCfx-2e\n\nShop: https://stza.co/+xCfx-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Yankees
<2018-07-18 Wed 18:00-21:00>
:PROPERTIES:
:ID:       LPnSuPOsUjsifTZJKBDSjBtx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Yankees Braves vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xDSU-1T

Shop  https //stza.co/+xDSU-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Yankees
END:VALARM
DTSTART:20180718T230000Z
DTEND:20180719T020000Z
UID:LPnSuPOsUjsifTZJKBDSjBtx@stanza.co
SUMMARY:Braves vs. Yankees
DESCRIPTION:Braves vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xDSU-1T\n\nShop: https://stza.co/+xDSU-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Yankees
<2018-07-19 Thu 18:00-21:00>
:PROPERTIES:
:ID:       9w6Vdmre4hXgx-zAjvTngH-C@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Yankees Braves vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xDSY-18

Shop  https //stza.co/+xDSY-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Yankees
END:VALARM
DTSTART:20180719T230000Z
DTEND:20180720T020000Z
UID:9w6Vdmre4hXgx-zAjvTngH-C@stanza.co
SUMMARY:Braves vs. Yankees
DESCRIPTION:Braves vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xDSY-18\n\nShop: https://stza.co/+xDSY-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Yankees
<2018-07-20 Fri 18:00-21:00>
:PROPERTIES:
:ID:       jsat3Oedy9hZrN1i9PfBgqMa@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Yankees Braves vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xDS_-2r

Shop  https //stza.co/+xDS_-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Yankees
END:VALARM
DTSTART:20180720T230000Z
DTEND:20180721T020000Z
UID:jsat3Oedy9hZrN1i9PfBgqMa@stanza.co
SUMMARY:Braves vs. Yankees
DESCRIPTION:Braves vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xDS_-2r\n\nShop: https://stza.co/+xDS_-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Cardinals
<2018-07-21 Sat 18:00-21:00>
:PROPERTIES:
:ID:       -_C6NtcKG2pFDJP_LNsDJpFT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Cardinals Braves vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xDT1-1l

Shop  https //stza.co/+xDT1-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Cardinals
END:VALARM
DTSTART:20180721T230000Z
DTEND:20180722T020000Z
UID:-_C6NtcKG2pFDJP_LNsDJpFT@stanza.co
SUMMARY:Braves vs. Cardinals
DESCRIPTION:Braves vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xDT1-1l\n\nShop: https://stza.co/+xDT1-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Cardinals
<2018-07-22 Sun 15:00-18:00>
:PROPERTIES:
:ID:       X8wkTHfoPAy65T7cjBH6ltc2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Cardinals Braves vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xDT2-2Z

Shop  https //stza.co/+xDT2-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Cardinals
END:VALARM
DTSTART:20180722T200000Z
DTEND:20180722T230000Z
UID:X8wkTHfoPAy65T7cjBH6ltc2@stanza.co
SUMMARY:Braves vs. Cardinals
DESCRIPTION:Braves vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xDT2-2Z\n\nShop: https://stza.co/+xDT2-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Cardinals
<2018-07-23 Mon 18:00-21:00>
:PROPERTIES:
:ID:       pqkzqMyxK7CXFLU6o1S4FdoK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Cardinals Braves vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xDT4-3W

Shop  https //stza.co/+xDT4-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Cardinals
END:VALARM
DTSTART:20180723T230000Z
DTEND:20180724T020000Z
UID:pqkzqMyxK7CXFLU6o1S4FdoK@stanza.co
SUMMARY:Braves vs. Cardinals
DESCRIPTION:Braves vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xDT4-3W\n\nShop: https://stza.co/+xDT4-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Mets
<2018-07-24 Tue>--<2018-07-23 Mon>
:PROPERTIES:
:ID:       xNPsPBlbipgohSN6LxowpzN4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Mets Braves @ Mets

Follow on MiLB First Pitch  https //stza.co/+xCgn-O

Shop  https //stza.co/+xCgn-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Mets
END:VALARM
DTSTART;VALUE=DATE:20180724
DTEND;VALUE=DATE:20180724
UID:xNPsPBlbipgohSN6LxowpzN4@stanza.co
SUMMARY:Braves @ Mets
DESCRIPTION:Braves @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xCgn-O\n\nShop: https://stza.co/+xCgn-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Mets
<2018-07-25 Wed>--<2018-07-24 Tue>
:PROPERTIES:
:ID:       G5LyidAgKk-OftP87rR8y_2w@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Mets Braves @ Mets

Follow on MiLB First Pitch  https //stza.co/+xCgv-1I

Shop  https //stza.co/+xCgv-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Mets
END:VALARM
DTSTART;VALUE=DATE:20180725
DTEND;VALUE=DATE:20180725
UID:G5LyidAgKk-OftP87rR8y_2w@stanza.co
SUMMARY:Braves @ Mets
DESCRIPTION:Braves @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xCgv-1I\n\nShop: https://stza.co/+xCgv-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Mets
<2018-07-26 Thu>--<2018-07-25 Wed>
:PROPERTIES:
:ID:       6rcHmbUXUotuPoWJ8qbayVRN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Mets Braves @ Mets

Follow on MiLB First Pitch  https //stza.co/+xCgG-33

Shop  https //stza.co/+xCgG-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Mets
END:VALARM
DTSTART;VALUE=DATE:20180726
DTEND;VALUE=DATE:20180726
UID:6rcHmbUXUotuPoWJ8qbayVRN@stanza.co
SUMMARY:Braves @ Mets
DESCRIPTION:Braves @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xCgG-33\n\nShop: https://stza.co/+xCgG-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Cardinals
<2018-07-27 Fri>--<2018-07-26 Thu>
:PROPERTIES:
:ID:       08Pa-ld3_a_QSqB3qxzth6_Z@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Cardinals Braves @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+xCgR-v

Shop  https //stza.co/+xCgR-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180727
DTEND;VALUE=DATE:20180727
UID:08Pa-ld3_a_QSqB3qxzth6_Z@stanza.co
SUMMARY:Braves @ Cardinals
DESCRIPTION:Braves @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xCgR-v\n\nShop: https://stza.co/+xCgR-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Cardinals
<2018-07-28 Sat>--<2018-07-27 Fri>
:PROPERTIES:
:ID:       SerwCb3_C0WZrVMtepNdLgJW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Cardinals Braves @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+xCg_-q

Shop  https //stza.co/+xCg_-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180728
DTEND;VALUE=DATE:20180728
UID:SerwCb3_C0WZrVMtepNdLgJW@stanza.co
SUMMARY:Braves @ Cardinals
DESCRIPTION:Braves @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xCg_-q\n\nShop: https://stza.co/+xCg_-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Cardinals
<2018-07-29 Sun>--<2018-07-28 Sat>
:PROPERTIES:
:ID:       c6hIURg9o3V2ZDxAUrmkzlBV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Cardinals Braves @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+xCh6-2L

Shop  https //stza.co/+xCh6-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180729
DTEND;VALUE=DATE:20180729
UID:c6hIURg9o3V2ZDxAUrmkzlBV@stanza.co
SUMMARY:Braves @ Cardinals
DESCRIPTION:Braves @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xCh6-2L\n\nShop: https://stza.co/+xCh6-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Rays
<2018-07-31 Tue 18:00-21:00>
:PROPERTIES:
:ID:       -wRLBJed2xlkNqWjCI0cuc-M@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Rays Braves vs. Rays

Follow on MiLB First Pitch  https //stza.co/+xDT6-J

Shop  https //stza.co/+xDT6-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Rays
END:VALARM
DTSTART:20180731T230000Z
DTEND:20180801T020000Z
UID:-wRLBJed2xlkNqWjCI0cuc-M@stanza.co
SUMMARY:Braves vs. Rays
DESCRIPTION:Braves vs. Rays\n\nFollow on MiLB First Pitch: https://stza.co/+xDT6-J\n\nShop: https://stza.co/+xDT6-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Rays
<2018-08-01 Wed 18:00-21:00>
:PROPERTIES:
:ID:       tSHeBkB22fBIIfsE5yQ5hKkv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Rays Braves vs. Rays

Follow on MiLB First Pitch  https //stza.co/+xDT9-B

Shop  https //stza.co/+xDT9-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Rays
END:VALARM
DTSTART:20180801T230000Z
DTEND:20180802T020000Z
UID:tSHeBkB22fBIIfsE5yQ5hKkv@stanza.co
SUMMARY:Braves vs. Rays
DESCRIPTION:Braves vs. Rays\n\nFollow on MiLB First Pitch: https://stza.co/+xDT9-B\n\nShop: https://stza.co/+xDT9-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Rays
<2018-08-02 Thu 18:00-21:00>
:PROPERTIES:
:ID:       ImHUNcwpropgbz8dysH-sjyu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Rays Braves vs. Rays

Follow on MiLB First Pitch  https //stza.co/+xDTb-3h

Shop  https //stza.co/+xDTb-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Rays
END:VALARM
DTSTART:20180802T230000Z
DTEND:20180803T020000Z
UID:ImHUNcwpropgbz8dysH-sjyu@stanza.co
SUMMARY:Braves vs. Rays
DESCRIPTION:Braves vs. Rays\n\nFollow on MiLB First Pitch: https://stza.co/+xDTb-3h\n\nShop: https://stza.co/+xDTb-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Blue Jays
<2018-08-03 Fri>--<2018-08-02 Thu>
:PROPERTIES:
:ID:       C0tCiZ9ZWWLnbPPRadoxhmQd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Blue Jays Braves @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xChK-2j

Shop  https //stza.co/+xChK-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Blue Jays
END:VALARM
DTSTART;VALUE=DATE:20180803
DTEND;VALUE=DATE:20180803
UID:C0tCiZ9ZWWLnbPPRadoxhmQd@stanza.co
SUMMARY:Braves @ Blue Jays
DESCRIPTION:Braves @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xChK-2j\n\nShop: https://stza.co/+xChK-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Blue Jays
<2018-08-04 Sat>--<2018-08-03 Fri>
:PROPERTIES:
:ID:       g0KrOP5Gc8nfb8AiEVYpGBB7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Blue Jays Braves @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xChS-3o

Shop  https //stza.co/+xChS-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Blue Jays
END:VALARM
DTSTART;VALUE=DATE:20180804
DTEND;VALUE=DATE:20180804
UID:g0KrOP5Gc8nfb8AiEVYpGBB7@stanza.co
SUMMARY:Braves @ Blue Jays
DESCRIPTION:Braves @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xChS-3o\n\nShop: https://stza.co/+xChS-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Blue Jays
<2018-08-05 Sun>--<2018-08-04 Sat>
:PROPERTIES:
:ID:       uZbEFAigsYdWOE4372V_SkTh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Blue Jays Braves @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xCi1-1s

Shop  https //stza.co/+xCi1-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Blue Jays
END:VALARM
DTSTART;VALUE=DATE:20180805
DTEND;VALUE=DATE:20180805
UID:uZbEFAigsYdWOE4372V_SkTh@stanza.co
SUMMARY:Braves @ Blue Jays
DESCRIPTION:Braves @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xCi1-1s\n\nShop: https://stza.co/+xCi1-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Royals
<2018-08-06 Mon 18:00-21:00>
:PROPERTIES:
:ID:       IePBUR6CTl9Ae9PHE2m-1Txt@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Royals Braves vs. Royals

Follow on MiLB First Pitch  https //stza.co/+xDTd-3C

Shop  https //stza.co/+xDTd-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Royals
END:VALARM
DTSTART:20180806T230000Z
DTEND:20180807T020000Z
UID:IePBUR6CTl9Ae9PHE2m-1Txt@stanza.co
SUMMARY:Braves vs. Royals
DESCRIPTION:Braves vs. Royals\n\nFollow on MiLB First Pitch: https://stza.co/+xDTd-3C\n\nShop: https://stza.co/+xDTd-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Royals
<2018-08-07 Tue 18:00-21:00>
:PROPERTIES:
:ID:       O4nnQjdRYa9D9zEQUD2LnItn@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Royals Braves vs. Royals

Follow on MiLB First Pitch  https //stza.co/+xDTh-e

Shop  https //stza.co/+xDTh-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Royals
END:VALARM
DTSTART:20180807T230000Z
DTEND:20180808T020000Z
UID:O4nnQjdRYa9D9zEQUD2LnItn@stanza.co
SUMMARY:Braves vs. Royals
DESCRIPTION:Braves vs. Royals\n\nFollow on MiLB First Pitch: https://stza.co/+xDTh-e\n\nShop: https://stza.co/+xDTh-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Royals
<2018-08-08 Wed 18:00-21:00>
:PROPERTIES:
:ID:       bC7039iqDVjsICT0uV4fIG25@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Royals Braves vs. Royals

Follow on MiLB First Pitch  https //stza.co/+xDTi-3T

Shop  https //stza.co/+xDTi-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Royals
END:VALARM
DTSTART:20180808T230000Z
DTEND:20180809T020000Z
UID:bC7039iqDVjsICT0uV4fIG25@stanza.co
SUMMARY:Braves vs. Royals
DESCRIPTION:Braves vs. Royals\n\nFollow on MiLB First Pitch: https://stza.co/+xDTi-3T\n\nShop: https://stza.co/+xDTi-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Mets
<2018-08-09 Thu 18:00-21:00>
:PROPERTIES:
:ID:       _Fs2w9dhZUu4BPp2PVMO9Qdr@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Mets Braves vs. Mets

Follow on MiLB First Pitch  https //stza.co/+xDTk-22

Shop  https //stza.co/+xDTk-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Mets
END:VALARM
DTSTART:20180809T230000Z
DTEND:20180810T020000Z
UID:_Fs2w9dhZUu4BPp2PVMO9Qdr@stanza.co
SUMMARY:Braves vs. Mets
DESCRIPTION:Braves vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xDTk-22\n\nShop: https://stza.co/+xDTk-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Mets
<2018-08-10 Fri 18:00-21:00>
:PROPERTIES:
:ID:       kNCkhwg3im9F2GqW8v6d_ZKH@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Mets Braves vs. Mets

Follow on MiLB First Pitch  https //stza.co/+xDTm-37

Shop  https //stza.co/+xDTm-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Mets
END:VALARM
DTSTART:20180810T230000Z
DTEND:20180811T020000Z
UID:kNCkhwg3im9F2GqW8v6d_ZKH@stanza.co
SUMMARY:Braves vs. Mets
DESCRIPTION:Braves vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xDTm-37\n\nShop: https://stza.co/+xDTm-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Mets
<2018-08-11 Sat 18:00-21:00>
:PROPERTIES:
:ID:       k80fAt1GL-LcF0I6SItw9Ocx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Mets Braves vs. Mets

Follow on MiLB First Pitch  https //stza.co/+xDTo-3i

Shop  https //stza.co/+xDTo-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Mets
END:VALARM
DTSTART:20180811T230000Z
DTEND:20180812T020000Z
UID:k80fAt1GL-LcF0I6SItw9Ocx@stanza.co
SUMMARY:Braves vs. Mets
DESCRIPTION:Braves vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xDTo-3i\n\nShop: https://stza.co/+xDTo-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Yankees
<2018-08-12 Sun>--<2018-08-11 Sat>
:PROPERTIES:
:ID:       Qkaanbf107uW9hpfFkDMzDSR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Yankees Braves @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xCiQ-3

Shop  https //stza.co/+xCiQ-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180812
DTEND;VALUE=DATE:20180812
UID:Qkaanbf107uW9hpfFkDMzDSR@stanza.co
SUMMARY:Braves @ Yankees
DESCRIPTION:Braves @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xCiQ-3\n\nShop: https://stza.co/+xCiQ-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Yankees
<2018-08-13 Mon>--<2018-08-12 Sun>
:PROPERTIES:
:ID:       oHdZi49z-q1CKy_WL8J7Dddk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Yankees Braves @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xCiZ-2J

Shop  https //stza.co/+xCiZ-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180813
DTEND;VALUE=DATE:20180813
UID:oHdZi49z-q1CKy_WL8J7Dddk@stanza.co
SUMMARY:Braves @ Yankees
DESCRIPTION:Braves @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xCiZ-2J\n\nShop: https://stza.co/+xCiZ-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Yankees
<2018-08-14 Tue>--<2018-08-13 Mon>
:PROPERTIES:
:ID:       QUV8QjpMpWcDMhHKBaqqInU4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Yankees Braves @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xCj8-2P

Shop  https //stza.co/+xCj8-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180814
DTEND;VALUE=DATE:20180814
UID:QUV8QjpMpWcDMhHKBaqqInU4@stanza.co
SUMMARY:Braves @ Yankees
DESCRIPTION:Braves @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xCj8-2P\n\nShop: https://stza.co/+xCj8-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Astros
<2018-08-16 Thu 18:00-21:00>
:PROPERTIES:
:ID:       erOHipvj1ll7JYk-kcAzVjFu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Astros Braves vs. Astros

Follow on MiLB First Pitch  https //stza.co/+xDTq-f

Shop  https //stza.co/+xDTq-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Astros
END:VALARM
DTSTART:20180816T230000Z
DTEND:20180817T020000Z
UID:erOHipvj1ll7JYk-kcAzVjFu@stanza.co
SUMMARY:Braves vs. Astros
DESCRIPTION:Braves vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xDTq-f\n\nShop: https://stza.co/+xDTq-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Astros
<2018-08-17 Fri 18:00-21:00>
:PROPERTIES:
:ID:       bpMrS3uHda-0VR6IsdhMj6KH@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Astros Braves vs. Astros

Follow on MiLB First Pitch  https //stza.co/+xDTs-3H

Shop  https //stza.co/+xDTs-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Astros
END:VALARM
DTSTART:20180817T230000Z
DTEND:20180818T020000Z
UID:bpMrS3uHda-0VR6IsdhMj6KH@stanza.co
SUMMARY:Braves vs. Astros
DESCRIPTION:Braves vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xDTs-3H\n\nShop: https://stza.co/+xDTs-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Astros
<2018-08-18 Sat 18:00-21:00>
:PROPERTIES:
:ID:       46HdsRX3qFQVtAKkTdeeEl25@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Astros Braves vs. Astros

Follow on MiLB First Pitch  https //stza.co/+xDTu-1y

Shop  https //stza.co/+xDTu-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Astros
END:VALARM
DTSTART:20180818T230000Z
DTEND:20180819T020000Z
UID:46HdsRX3qFQVtAKkTdeeEl25@stanza.co
SUMMARY:Braves vs. Astros
DESCRIPTION:Braves vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xDTu-1y\n\nShop: https://stza.co/+xDTu-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Royals
<2018-08-19 Sun>--<2018-08-18 Sat>
:PROPERTIES:
:ID:       zh6llypovEozhzW4dIRzETJa@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Royals Braves @ Royals

Follow on MiLB First Pitch  https //stza.co/+xCjS-2N

Shop  https //stza.co/+xCjS-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Royals
END:VALARM
DTSTART;VALUE=DATE:20180819
DTEND;VALUE=DATE:20180819
UID:zh6llypovEozhzW4dIRzETJa@stanza.co
SUMMARY:Braves @ Royals
DESCRIPTION:Braves @ Royals\n\nFollow on MiLB First Pitch: https://stza.co/+xCjS-2N\n\nShop: https://stza.co/+xCjS-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Royals
<2018-08-20 Mon>--<2018-08-19 Sun>
:PROPERTIES:
:ID:       J548S0Lz_6ovrvwPvhuxo7SB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Royals Braves @ Royals

Follow on MiLB First Pitch  https //stza.co/+xCk1-1H

Shop  https //stza.co/+xCk1-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Royals
END:VALARM
DTSTART;VALUE=DATE:20180820
DTEND;VALUE=DATE:20180820
UID:J548S0Lz_6ovrvwPvhuxo7SB@stanza.co
SUMMARY:Braves @ Royals
DESCRIPTION:Braves @ Royals\n\nFollow on MiLB First Pitch: https://stza.co/+xCk1-1H\n\nShop: https://stza.co/+xCk1-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Blue Jays
<2018-08-21 Tue 18:00-21:00>
:PROPERTIES:
:ID:       IUa47ZZE7aWjOS1HlxCi7M4S@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Blue Jays Braves vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xDTx-c

Shop  https //stza.co/+xDTx-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Blue Jays
END:VALARM
DTSTART:20180821T230000Z
DTEND:20180822T020000Z
UID:IUa47ZZE7aWjOS1HlxCi7M4S@stanza.co
SUMMARY:Braves vs. Blue Jays
DESCRIPTION:Braves vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xDTx-c\n\nShop: https://stza.co/+xDTx-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Blue Jays
<2018-08-22 Wed 18:00-21:00>
:PROPERTIES:
:ID:       LrJJ55CFhL5rrSilRoYPn-lH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Blue Jays Braves vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xDTy-1E

Shop  https //stza.co/+xDTy-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Blue Jays
END:VALARM
DTSTART:20180822T230000Z
DTEND:20180823T020000Z
UID:LrJJ55CFhL5rrSilRoYPn-lH@stanza.co
SUMMARY:Braves vs. Blue Jays
DESCRIPTION:Braves vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xDTy-1E\n\nShop: https://stza.co/+xDTy-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Blue Jays
<2018-08-23 Thu 18:00-21:00>
:PROPERTIES:
:ID:       S6My6_wg_JEUFjVrw1rtIqTQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Blue Jays Braves vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xDTA-35

Shop  https //stza.co/+xDTA-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Blue Jays
END:VALARM
DTSTART:20180823T230000Z
DTEND:20180824T020000Z
UID:S6My6_wg_JEUFjVrw1rtIqTQ@stanza.co
SUMMARY:Braves vs. Blue Jays
DESCRIPTION:Braves vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xDTA-35\n\nShop: https://stza.co/+xDTA-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Rays
<2018-08-24 Fri>--<2018-08-23 Thu>
:PROPERTIES:
:ID:       Jiv30tXsMn8h8RJ3gV7sClg_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Rays Braves @ Rays

Follow on MiLB First Pitch  https //stza.co/+xCkD-2B

Shop  https //stza.co/+xCkD-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Rays
END:VALARM
DTSTART;VALUE=DATE:20180824
DTEND;VALUE=DATE:20180824
UID:Jiv30tXsMn8h8RJ3gV7sClg_@stanza.co
SUMMARY:Braves @ Rays
DESCRIPTION:Braves @ Rays\n\nFollow on MiLB First Pitch: https://stza.co/+xCkD-2B\n\nShop: https://stza.co/+xCkD-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Rays
<2018-08-25 Sat>--<2018-08-24 Fri>
:PROPERTIES:
:ID:       b8O3Pnfxe_oifKYjnVA7v1R-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Rays Braves @ Rays

Follow on MiLB First Pitch  https //stza.co/+xCkO-3t

Shop  https //stza.co/+xCkO-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Rays
END:VALARM
DTSTART;VALUE=DATE:20180825
DTEND;VALUE=DATE:20180825
UID:b8O3Pnfxe_oifKYjnVA7v1R-@stanza.co
SUMMARY:Braves @ Rays
DESCRIPTION:Braves @ Rays\n\nFollow on MiLB First Pitch: https://stza.co/+xCkO-3t\n\nShop: https://stza.co/+xCkO-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Rays
<2018-08-26 Sun>--<2018-08-25 Sat>
:PROPERTIES:
:ID:       coFQtFzP-Blx3i6-DMqC2uLC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Rays Braves @ Rays

Follow on MiLB First Pitch  https //stza.co/+xCk_-D

Shop  https //stza.co/+xCk_-1w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Rays
END:VALARM
DTSTART;VALUE=DATE:20180826
DTEND;VALUE=DATE:20180826
UID:coFQtFzP-Blx3i6-DMqC2uLC@stanza.co
SUMMARY:Braves @ Rays
DESCRIPTION:Braves @ Rays\n\nFollow on MiLB First Pitch: https://stza.co/+xCk_-D\n\nShop: https://stza.co/+xCk_-1w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Pirates
<2018-08-27 Mon>--<2018-08-26 Sun>
:PROPERTIES:
:ID:       D3h0CPywVCCuKuxrGsoxrw_z@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Pirates Braves @ Pirates

Follow on MiLB First Pitch  https //stza.co/+xCk$-3r

Shop  https //stza.co/+xCk$-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Pirates
END:VALARM
DTSTART;VALUE=DATE:20180827
DTEND;VALUE=DATE:20180827
UID:D3h0CPywVCCuKuxrGsoxrw_z@stanza.co
SUMMARY:Braves @ Pirates
DESCRIPTION:Braves @ Pirates\n\nFollow on MiLB First Pitch: https://stza.co/+xCk$-3r\n\nShop: https://stza.co/+xCk$-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Pirates
<2018-08-28 Tue>--<2018-08-27 Mon>
:PROPERTIES:
:ID:       fQZ7pojHizm-TEejTD4v5Gph@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Pirates Braves @ Pirates

Follow on MiLB First Pitch  https //stza.co/+xCl2-x

Shop  https //stza.co/+xCl2-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Pirates
END:VALARM
DTSTART;VALUE=DATE:20180828
DTEND;VALUE=DATE:20180828
UID:fQZ7pojHizm-TEejTD4v5Gph@stanza.co
SUMMARY:Braves @ Pirates
DESCRIPTION:Braves @ Pirates\n\nFollow on MiLB First Pitch: https://stza.co/+xCl2-x\n\nShop: https://stza.co/+xCl2-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Pirates
<2018-08-29 Wed>--<2018-08-28 Tue>
:PROPERTIES:
:ID:       c2lxST8pD8abw7TwNgu5UjNJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Pirates Braves @ Pirates

Follow on MiLB First Pitch  https //stza.co/+xCl5-X

Shop  https //stza.co/+xCl5-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Pirates
END:VALARM
DTSTART;VALUE=DATE:20180829
DTEND;VALUE=DATE:20180829
UID:c2lxST8pD8abw7TwNgu5UjNJ@stanza.co
SUMMARY:Braves @ Pirates
DESCRIPTION:Braves @ Pirates\n\nFollow on MiLB First Pitch: https://stza.co/+xCl5-X\n\nShop: https://stza.co/+xCl5-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
