#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Bisons @ Red Wings
<2018-04-06 Fri 17:05-20:05>
:PROPERTIES:
:ID:       pC8MOR5u4uu73xNiY7fh4KS3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Red Wings Bisons @ Red Wings

Follow on MiLB First Pitch  https //stza.co/+vK2c-C

Shop  https //stza.co/+vK2c-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Red Wings
END:VALARM
DTSTART:20180406T220500Z
DTEND:20180407T010500Z
UID:pC8MOR5u4uu73xNiY7fh4KS3@stanza.co
SUMMARY:Bisons @ Red Wings
DESCRIPTION:Bisons @ Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vK2c-C\n\nShop: https://stza.co/+vK2c-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Red Wings
<2018-04-07 Sat 12:05-15:05>
:PROPERTIES:
:ID:       RlQQLPhukUhNSnf2w2q1z2Yi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bisons @ Red Wings Bisons @ Red Wings

Follow on MiLB First Pitch  https //stza.co/+vK2d-2u

Shop  https //stza.co/+vK2d-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Red Wings
END:VALARM
DTSTART:20180407T170500Z
DTEND:20180407T200500Z
UID:RlQQLPhukUhNSnf2w2q1z2Yi@stanza.co
SUMMARY:Bisons @ Red Wings
DESCRIPTION:Bisons @ Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vK2d-2u\n\nShop: https://stza.co/+vK2d-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Red Wings
<2018-04-08 Sun 12:05-15:05>
:PROPERTIES:
:ID:       rDLtDCUvVMimAYN8Bs7Uj0Zp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Red Wings Bisons @ Red Wings

Follow on MiLB First Pitch  https //stza.co/+vK2e-3y

Shop  https //stza.co/+vK2e-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Red Wings
END:VALARM
DTSTART:20180408T170500Z
DTEND:20180408T200500Z
UID:rDLtDCUvVMimAYN8Bs7Uj0Zp@stanza.co
SUMMARY:Bisons @ Red Wings
DESCRIPTION:Bisons @ Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vK2e-3y\n\nShop: https://stza.co/+vK2e-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Red Sox
<2018-04-09 Mon 17:15-20:15>
:PROPERTIES:
:ID:       NotIFihxXTEpjrWSKVJONmFQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Red Sox Bisons @ Red Sox

Buy tickets here  https //stza.co/~vK23

Follow on MiLB First Pitch  https //stza.co/+vK23-Y

Shop  https //stza.co/+vK23-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Red Sox
END:VALARM
DTSTART:20180409T221500Z
DTEND:20180410T011500Z
UID:NotIFihxXTEpjrWSKVJONmFQ@stanza.co
SUMMARY:Bisons @ Red Sox
DESCRIPTION:Bisons @ Red Sox\n\nBuy tickets here: https://stza.co/~vK23\n\nFollow on MiLB First Pitch: https://stza.co/+vK23-Y\n\nShop: https://stza.co/+vK23-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Red Sox
<2018-04-10 Tue 17:15-20:15>
:PROPERTIES:
:ID:       DqmCNNJAshnXfJ91TlYz6MIj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bisons @ Red Sox Bisons @ Red Sox

Buy tickets here  https //stza.co/~vK24

Follow on MiLB First Pitch  https //stza.co/+vK24-22

Shop  https //stza.co/+vK24-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Red Sox
END:VALARM
DTSTART:20180410T221500Z
DTEND:20180411T011500Z
UID:DqmCNNJAshnXfJ91TlYz6MIj@stanza.co
SUMMARY:Bisons @ Red Sox
DESCRIPTION:Bisons @ Red Sox\n\nBuy tickets here: https://stza.co/~vK24\n\nFollow on MiLB First Pitch: https://stza.co/+vK24-22\n\nShop: https://stza.co/+vK24-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Red Sox
<2018-04-11 Wed 11:05-14:05>
:PROPERTIES:
:ID:       KhnqktaI8dTrBgvV4J0ZNDis@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Red Sox Bisons @ Red Sox

Buy tickets here  https //stza.co/~vK25

Follow on MiLB First Pitch  https //stza.co/+vK25-2W

Shop  https //stza.co/+vK25-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Red Sox
END:VALARM
DTSTART:20180411T160500Z
DTEND:20180411T190500Z
UID:KhnqktaI8dTrBgvV4J0ZNDis@stanza.co
SUMMARY:Bisons @ Red Sox
DESCRIPTION:Bisons @ Red Sox\n\nBuy tickets here: https://stza.co/~vK25\n\nFollow on MiLB First Pitch: https://stza.co/+vK25-2W\n\nShop: https://stza.co/+vK25-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Indians
<2018-04-12 Thu 13:05-16:05>
:PROPERTIES:
:ID:       p9gtJOXL4lGavmB6-gD6y05r@stanza.co
:LOCATION: Opening Day - Magnetic Schedule Giveaway
:STATUS:   CONFIRMED
:END:

Bisons vs. Indians America's favorite past time returns as the Bisons open their home schedule vs the Indianapolis Indians.  The first 10,000 fans through the gates will receive a magnetic schedule presented by Falken Tires.

Follow on MiLB First Pitch  https //stza.co/+vJ$n-2B

Shop  https //stza.co/+vJ$n-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Indians
END:VALARM
DTSTART:20180412T180500Z
DTEND:20180412T210500Z
UID:p9gtJOXL4lGavmB6-gD6y05r@stanza.co
SUMMARY:Bisons vs. Indians
DESCRIPTION:America's favorite past time returns as the Bisons open their home schedule vs the Indianapolis Indians.  The first 10,000 fans through the gates will receive a magnetic schedule presented by Falken Tires.\n\nFollow on MiLB First Pitch: https://stza.co/+vJ$n-2B\n\nShop: https://stza.co/+vJ$n-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Opening Day - Magnetic Schedule Giveaway
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Indians
<2018-04-13 Fri 17:05-20:05>
:PROPERTIES:
:ID:       E4be2LCCy7D1TBAtacIFcqXy@stanza.co
:LOCATION: Meet up with some friends at today's Happy Hour game
:STATUS:   CONFIRMED
:END:

Bisons vs. Indians Our friday night Happy Hour returns featuring $3 beer from Resurgence Brewery!  

The first bash of the season and your chance to catch some April fireworks!

Follow on MiLB First Pitch  https //stza.co/+vJ$p-1K

Shop  https //stza.co/+vJ$p-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Indians
END:VALARM
DTSTART:20180413T220500Z
DTEND:20180414T010500Z
UID:E4be2LCCy7D1TBAtacIFcqXy@stanza.co
SUMMARY:Bisons vs. Indians
DESCRIPTION:Our friday night Happy Hour returns featuring $3 beer from Resurgence Brewery!  \n\nThe first bash of the season and your chance to catch some April fireworks!\n\nFollow on MiLB First Pitch: https://stza.co/+vJ$p-1K\n\nShop: https://stza.co/+vJ$p-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Meet up with some friends at today's Happy Hour game
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Indians
<2018-04-14 Sat 12:05-15:05>
:PROPERTIES:
:ID:       cXxrSmfyBEXv7PA8_1acb9Gm@stanza.co
:LOCATION: Anderson's Kids Weekend
:STATUS:   CONFIRMED
:END:

Bisons vs. Indians Discounted tickets for kids, and the first 100 kids through the gate will receive a FREE Cotton Candy!

The first 500 kids through the gates will receive a free ice-cream!

Follow on MiLB First Pitch  https //stza.co/+vJ$r-3j

Shop  https //stza.co/+vJ$r-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Indians
END:VALARM
DTSTART:20180414T170500Z
DTEND:20180414T200500Z
UID:cXxrSmfyBEXv7PA8_1acb9Gm@stanza.co
SUMMARY:Bisons vs. Indians
DESCRIPTION:Discounted tickets for kids, and the first 100 kids through the gate will receive a FREE Cotton Candy!\n\nThe first 500 kids through the gates will receive a free ice-cream!\n\nFollow on MiLB First Pitch: https://stza.co/+vJ$r-3j\n\nShop: https://stza.co/+vJ$r-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Anderson's Kids Weekend
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Indians
<2018-04-15 Sun 12:05-15:05>
:PROPERTIES:
:ID:       c65YULlr_M3wb3IrBN4jI5vL@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Bisons vs. Indians Discounted tickets for kids, and the first 100 kids through the gate will receive a FREE Cotton Candy!

Stick around after every Sunday game and watch your child run the bases, just like the Bisons do!

Follow on MiLB First Pitch  https //stza.co/+vJ$s-3i

Shop  https //stza.co/+vJ$s-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Indians
END:VALARM
DTSTART:20180415T170500Z
DTEND:20180415T200500Z
UID:c65YULlr_M3wb3IrBN4jI5vL@stanza.co
SUMMARY:Bisons vs. Indians
DESCRIPTION:Discounted tickets for kids, and the first 100 kids through the gate will receive a FREE Cotton Candy!\n\nStick around after every Sunday game and watch your child run the bases, just like the Bisons do!\n\nFollow on MiLB First Pitch: https://stza.co/+vJ$s-3i\n\nShop: https://stza.co/+vJ$s-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Bats
<2018-04-16 Mon 17:05-20:05>
:PROPERTIES:
:ID:       8dOn79JaZ_01Y4zeJinjBtYA@stanza.co
:LOCATION: Come out for our Mardown Monday game!
:STATUS:   CONFIRMED
:END:

Bisons vs. Bats Discounted tickets along with $1 ice-cream and $1 popcorn at the concession stands!

Follow on MiLB First Pitch  https //stza.co/+vJ$v-2N

Shop  https //stza.co/+vJ$v-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Bats
END:VALARM
DTSTART:20180416T220500Z
DTEND:20180417T010500Z
UID:8dOn79JaZ_01Y4zeJinjBtYA@stanza.co
SUMMARY:Bisons vs. Bats
DESCRIPTION:Discounted tickets along with $1 ice-cream and $1 popcorn at the concession stands!\n\nFollow on MiLB First Pitch: https://stza.co/+vJ$v-2N\n\nShop: https://stza.co/+vJ$v-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Come out for our Mardown Monday game!
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Bats
<2018-04-17 Tue 17:05-20:05>
:PROPERTIES:
:ID:       JqlfhbJzJH4MYF_8sRisLlaH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons vs. Bats Bisons vs. Bats

Follow on MiLB First Pitch  https //stza.co/+vJ$x-t

Shop  https //stza.co/+vJ$x-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Bats
END:VALARM
DTSTART:20180417T220500Z
DTEND:20180418T010500Z
UID:JqlfhbJzJH4MYF_8sRisLlaH@stanza.co
SUMMARY:Bisons vs. Bats
DESCRIPTION:Bisons vs. Bats\n\nFollow on MiLB First Pitch: https://stza.co/+vJ$x-t\n\nShop: https://stza.co/+vJ$x-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Bats
<2018-04-18 Wed 12:05-15:05>
:PROPERTIES:
:ID:       RyIOZxjvD_VGpQp7Eu8rhtzi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bisons vs. Bats Bisons vs. Bats

Follow on MiLB First Pitch  https //stza.co/+vJ$y-2N

Shop  https //stza.co/+vJ$y-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Bats
END:VALARM
DTSTART:20180418T170500Z
DTEND:20180418T200500Z
UID:RyIOZxjvD_VGpQp7Eu8rhtzi@stanza.co
SUMMARY:Bisons vs. Bats
DESCRIPTION:Bisons vs. Bats\n\nFollow on MiLB First Pitch: https://stza.co/+vJ$y-2N\n\nShop: https://stza.co/+vJ$y-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Tides
<2018-04-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       P6vxmSBss2ip6Y7y1TvN5dqU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Tides Bisons @ Tides

Follow on MiLB First Pitch  https //stza.co/+vK20-3E

Shop  https //stza.co/+vK20-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Tides
END:VALARM
DTSTART:20180420T230500Z
DTEND:20180421T020500Z
UID:P6vxmSBss2ip6Y7y1TvN5dqU@stanza.co
SUMMARY:Bisons @ Tides
DESCRIPTION:Bisons @ Tides\n\nFollow on MiLB First Pitch: https://stza.co/+vK20-3E\n\nShop: https://stza.co/+vK20-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Tides
<2018-04-21 Sat 18:05-21:05>
:PROPERTIES:
:ID:       GRV8sh-F3LoJysUIcoZqYrPT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Tides Bisons @ Tides

Follow on MiLB First Pitch  https //stza.co/+vK21-1s

Shop  https //stza.co/+vK21-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Tides
END:VALARM
DTSTART:20180421T230500Z
DTEND:20180422T020500Z
UID:GRV8sh-F3LoJysUIcoZqYrPT@stanza.co
SUMMARY:Bisons @ Tides
DESCRIPTION:Bisons @ Tides\n\nFollow on MiLB First Pitch: https://stza.co/+vK21-1s\n\nShop: https://stza.co/+vK21-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Tides
<2018-04-22 Sun 12:05-15:05>
:PROPERTIES:
:ID:       drE-T0-SGn03mhrlu8cMmgv4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bisons @ Tides Bisons @ Tides

Follow on MiLB First Pitch  https //stza.co/+vK22-h

Shop  https //stza.co/+vK22-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Tides
END:VALARM
DTSTART:20180422T170500Z
DTEND:20180422T200500Z
UID:drE-T0-SGn03mhrlu8cMmgv4@stanza.co
SUMMARY:Bisons @ Tides
DESCRIPTION:Bisons @ Tides\n\nFollow on MiLB First Pitch: https://stza.co/+vK22-h\n\nShop: https://stza.co/+vK22-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Bulls
<2018-04-23 Mon 18:05-21:05>
:PROPERTIES:
:ID:       GdCSJgVBT7EPcwO4SGzGNv_8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Bulls Bisons @ Bulls

Follow on MiLB First Pitch  https //stza.co/+vK1E-3c

Shop  https //stza.co/+vK1E-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Bulls
END:VALARM
DTSTART:20180423T230500Z
DTEND:20180424T020500Z
UID:GdCSJgVBT7EPcwO4SGzGNv_8@stanza.co
SUMMARY:Bisons @ Bulls
DESCRIPTION:Bisons @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+vK1E-3c\n\nShop: https://stza.co/+vK1E-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Bulls
<2018-04-24 Tue 18:05-21:05>
:PROPERTIES:
:ID:       mYJFY3W2esHyIDBhjc3qZOrv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Bulls Bisons @ Bulls

Follow on MiLB First Pitch  https //stza.co/+vK1F-Z

Shop  https //stza.co/+vK1F-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Bulls
END:VALARM
DTSTART:20180424T230500Z
DTEND:20180425T020500Z
UID:mYJFY3W2esHyIDBhjc3qZOrv@stanza.co
SUMMARY:Bisons @ Bulls
DESCRIPTION:Bisons @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+vK1F-Z\n\nShop: https://stza.co/+vK1F-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Bulls
<2018-04-25 Wed 09:35-12:35>
:PROPERTIES:
:ID:       HdZAr0Kf30RgnRo0nj0hNLie@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bisons @ Bulls Bisons @ Bulls

Follow on MiLB First Pitch  https //stza.co/+vK1G-1u

Shop  https //stza.co/+vK1G-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Bulls
END:VALARM
DTSTART:20180425T143500Z
DTEND:20180425T173500Z
UID:HdZAr0Kf30RgnRo0nj0hNLie@stanza.co
SUMMARY:Bisons @ Bulls
DESCRIPTION:Bisons @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+vK1G-1u\n\nShop: https://stza.co/+vK1G-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Red Sox
<2018-04-27 Fri 17:05-20:05>
:PROPERTIES:
:ID:       9astgCtrHl1w5ogD3Kbwt6Oa@stanza.co
:LOCATION: Meet up with some friends at today's Happy Hour game
:STATUS:   CONFIRMED
:END:

Bisons vs. Red Sox Our friday night Happy Hour returns featuring $3 beer from Resurgence Brewery!  



Follow on MiLB First Pitch  https //stza.co/+vJ$B-3I

Shop  https //stza.co/+vJ$B-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Red Sox
END:VALARM
DTSTART:20180427T220500Z
DTEND:20180428T010500Z
UID:9astgCtrHl1w5ogD3Kbwt6Oa@stanza.co
SUMMARY:Bisons vs. Red Sox
DESCRIPTION:Our friday night Happy Hour returns featuring $3 beer from Resurgence Brewery!  \n\n\n\nFollow on MiLB First Pitch: https://stza.co/+vJ$B-3I\n\nShop: https://stza.co/+vJ$B-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Meet up with some friends at today's Happy Hour game
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Red Sox
<2018-04-28 Sat 12:05-15:05>
:PROPERTIES:
:ID:       4Z8SKouqHGqi9uDs-hxfLxAY@stanza.co
:LOCATION: Dog Day
:STATUS:   CONFIRMED
:END:

Bisons vs. Red Sox Come and enjoy the game with man's best friend!

Follow on MiLB First Pitch  https //stza.co/+vJ$D-2s

Shop  https //stza.co/+vJ$D-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Red Sox
END:VALARM
DTSTART:20180428T170500Z
DTEND:20180428T200500Z
UID:4Z8SKouqHGqi9uDs-hxfLxAY@stanza.co
SUMMARY:Bisons vs. Red Sox
DESCRIPTION:Come and enjoy the game with man's best friend!\n\nFollow on MiLB First Pitch: https://stza.co/+vJ$D-2s\n\nShop: https://stza.co/+vJ$D-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dog Day
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Red Sox
<2018-04-29 Sun 12:05-15:05>
:PROPERTIES:
:ID:       HGcX7ghwYEQSAtuX9n757uoa@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Bisons vs. Red Sox Stick around after every Sunday game and watch your child run the bases, just like the Bisons do!

Follow on MiLB First Pitch  https //stza.co/+vJ$F-2F

Shop  https //stza.co/+vJ$F-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Red Sox
END:VALARM
DTSTART:20180429T170500Z
DTEND:20180429T200500Z
UID:HGcX7ghwYEQSAtuX9n757uoa@stanza.co
SUMMARY:Bisons vs. Red Sox
DESCRIPTION:Stick around after every Sunday game and watch your child run the bases, just like the Bisons do!\n\nFollow on MiLB First Pitch: https://stza.co/+vJ$F-2F\n\nShop: https://stza.co/+vJ$F-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ RailRiders
<2018-04-30 Mon 17:35-20:35>
:PROPERTIES:
:ID:       jNuDBSEYvjjQp-47pSJL9gSw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ RailRiders Bisons @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vK2m-1q

Shop  https //stza.co/+vK2m-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ RailRiders
END:VALARM
DTSTART:20180430T223500Z
DTEND:20180501T013500Z
UID:jNuDBSEYvjjQp-47pSJL9gSw@stanza.co
SUMMARY:Bisons @ RailRiders
DESCRIPTION:Bisons @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vK2m-1q\n\nShop: https://stza.co/+vK2m-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ RailRiders
<2018-05-01 Tue 17:35-20:35>
:PROPERTIES:
:ID:       NmgFtw1b8YaOU57dnMtZqQ5A@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ RailRiders Bisons @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vK2n-1t

Shop  https //stza.co/+vK2n-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ RailRiders
END:VALARM
DTSTART:20180501T223500Z
DTEND:20180502T013500Z
UID:NmgFtw1b8YaOU57dnMtZqQ5A@stanza.co
SUMMARY:Bisons @ RailRiders
DESCRIPTION:Bisons @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vK2n-1t\n\nShop: https://stza.co/+vK2n-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ RailRiders
<2018-05-02 Wed 09:35-12:35>
:PROPERTIES:
:ID:       L84Ld7MGVm7LMVnvgo6QjGQB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bisons @ RailRiders Bisons @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vK2o-2C

Shop  https //stza.co/+vK2o-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ RailRiders
END:VALARM
DTSTART:20180502T143500Z
DTEND:20180502T173500Z
UID:L84Ld7MGVm7LMVnvgo6QjGQB@stanza.co
SUMMARY:Bisons @ RailRiders
DESCRIPTION:Bisons @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vK2o-2C\n\nShop: https://stza.co/+vK2o-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Chiefs
<2018-05-03 Thu 17:05-20:05>
:PROPERTIES:
:ID:       cRIbTlDmN6B2o_-qxKyDX7YY@stanza.co
:LOCATION: National Chocolate Ice-Cream Day
:STATUS:   CONFIRMED
:END:

Bisons vs. Chiefs We'll celebrate the day with $1 chocolate ice-cream at the concession stand!

Follow on MiLB First Pitch  https //stza.co/+vJ$G-3z

Shop  https //stza.co/+vJ$G-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Chiefs
END:VALARM
DTSTART:20180503T220500Z
DTEND:20180504T010500Z
UID:cRIbTlDmN6B2o_-qxKyDX7YY@stanza.co
SUMMARY:Bisons vs. Chiefs
DESCRIPTION:We'll celebrate the day with $1 chocolate ice-cream at the concession stand!\n\nFollow on MiLB First Pitch: https://stza.co/+vJ$G-3z\n\nShop: https://stza.co/+vJ$G-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:National Chocolate Ice-Cream Day
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Chiefs
<2018-05-04 Fri 18:05-21:05>
:PROPERTIES:
:ID:       Z-QJb4yJ2GRMzNxGtm5mzLC-@stanza.co
:LOCATION: Meet up with some friends at today's Happy Hour game
:STATUS:   CONFIRMED
:END:

Bisons vs. Chiefs Our friday night Happy Hour returns featuring $3 beer from Resurgence Brewery!  

More details TBA

Follow on MiLB First Pitch  https //stza.co/+vJ$J-3i

Shop  https //stza.co/+vJ$J-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Chiefs
END:VALARM
DTSTART:20180504T230500Z
DTEND:20180505T020500Z
UID:Z-QJb4yJ2GRMzNxGtm5mzLC-@stanza.co
SUMMARY:Bisons vs. Chiefs
DESCRIPTION:Our friday night Happy Hour returns featuring $3 beer from Resurgence Brewery!  \n\nMore details TBA\n\nFollow on MiLB First Pitch: https://stza.co/+vJ$J-3i\n\nShop: https://stza.co/+vJ$J-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Meet up with some friends at today's Happy Hour game
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Chiefs
<2018-05-05 Sat 12:05-15:05>
:PROPERTIES:
:ID:       _vta5QDkT58JapyV5SCkKkIl@stanza.co
:LOCATION: Blue Jays Weekend
:STATUS:   CONFIRMED
:END:

Bisons vs. Chiefs More details to be announced.

Follow on MiLB First Pitch  https //stza.co/+vJ$K-2_

Shop  https //stza.co/+vJ$K-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Chiefs
END:VALARM
DTSTART:20180505T170500Z
DTEND:20180505T200500Z
UID:_vta5QDkT58JapyV5SCkKkIl@stanza.co
SUMMARY:Bisons vs. Chiefs
DESCRIPTION:More details to be announced.\n\nFollow on MiLB First Pitch: https://stza.co/+vJ$K-2_\n\nShop: https://stza.co/+vJ$K-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Blue Jays Weekend
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Chiefs
<2018-05-06 Sun 12:05-15:05>
:PROPERTIES:
:ID:       14SXdJfhXNB-QqbNYLaZU9Ff@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Bisons vs. Chiefs More details to be announced.

Stick around after every Sunday game and watch your child run the bases, just like the Bisons do!

Follow on MiLB First Pitch  https //stza.co/+vJ$N-$

Shop  https //stza.co/+vJ$N-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Chiefs
END:VALARM
DTSTART:20180506T170500Z
DTEND:20180506T200500Z
UID:14SXdJfhXNB-QqbNYLaZU9Ff@stanza.co
SUMMARY:Bisons vs. Chiefs
DESCRIPTION:More details to be announced.\n\nStick around after every Sunday game and watch your child run the bases, just like the Bisons do!\n\nFollow on MiLB First Pitch: https://stza.co/+vJ$N-$\n\nShop: https://stza.co/+vJ$N-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Red Wings
<2018-05-07 Mon 17:05-20:05>
:PROPERTIES:
:ID:       2M1i3WO6AVqvuAC68JYd9KDs@stanza.co
:LOCATION: Come out for our Mardown Monday game!
:STATUS:   CONFIRMED
:END:

Bisons vs. Red Wings Discounted tickets along with $1 ice-cream and $1 popcorn at the concession stands!

Follow on MiLB First Pitch  https //stza.co/+vJ$P-3q

Shop  https //stza.co/+vJ$P-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Red Wings
END:VALARM
DTSTART:20180507T220500Z
DTEND:20180508T010500Z
UID:2M1i3WO6AVqvuAC68JYd9KDs@stanza.co
SUMMARY:Bisons vs. Red Wings
DESCRIPTION:Discounted tickets along with $1 ice-cream and $1 popcorn at the concession stands!\n\nFollow on MiLB First Pitch: https://stza.co/+vJ$P-3q\n\nShop: https://stza.co/+vJ$P-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Come out for our Mardown Monday game!
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Red Wings
<2018-05-08 Tue 17:05-20:05>
:PROPERTIES:
:ID:       54npPB0zps-0YrGK1b2Xp_se@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons vs. Red Wings Bisons vs. Red Wings

Follow on MiLB First Pitch  https //stza.co/+vJ$Q-2U

Shop  https //stza.co/+vJ$Q-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Red Wings
END:VALARM
DTSTART:20180508T220500Z
DTEND:20180509T010500Z
UID:54npPB0zps-0YrGK1b2Xp_se@stanza.co
SUMMARY:Bisons vs. Red Wings
DESCRIPTION:Bisons vs. Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vJ$Q-2U\n\nShop: https://stza.co/+vJ$Q-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Red Wings
<2018-05-09 Wed 12:05-15:05>
:PROPERTIES:
:ID:       DPQJlDf1lu_gyjxE_XZ2Ry6b@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons vs. Red Wings Bisons vs. Red Wings

Follow on MiLB First Pitch  https //stza.co/+vJ$S-2r

Shop  https //stza.co/+vJ$S-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Red Wings
END:VALARM
DTSTART:20180509T170500Z
DTEND:20180509T200500Z
UID:DPQJlDf1lu_gyjxE_XZ2Ry6b@stanza.co
SUMMARY:Bisons vs. Red Wings
DESCRIPTION:Bisons vs. Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vJ$S-2r\n\nShop: https://stza.co/+vJ$S-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ IronPigs
<2018-05-10 Thu 18:05-21:05>
:PROPERTIES:
:ID:       yCCutHbyqV9gNl3prpERKmjj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bisons @ IronPigs Bisons @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+vK1O-3a

Shop  https //stza.co/+vK1O-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ IronPigs
END:VALARM
DTSTART:20180510T230500Z
DTEND:20180511T020500Z
UID:yCCutHbyqV9gNl3prpERKmjj@stanza.co
SUMMARY:Bisons @ IronPigs
DESCRIPTION:Bisons @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vK1O-3a\n\nShop: https://stza.co/+vK1O-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ IronPigs
<2018-05-11 Fri 18:05-21:05>
:PROPERTIES:
:ID:       t5gQQxIA38EMOov-x6JwsiAi@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ IronPigs Bisons @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+vK1P-3H

Shop  https //stza.co/+vK1P-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ IronPigs
END:VALARM
DTSTART:20180511T230500Z
DTEND:20180512T020500Z
UID:t5gQQxIA38EMOov-x6JwsiAi@stanza.co
SUMMARY:Bisons @ IronPigs
DESCRIPTION:Bisons @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vK1P-3H\n\nShop: https://stza.co/+vK1P-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ IronPigs
<2018-05-12 Sat 17:35-20:35>
:PROPERTIES:
:ID:       ICyEB9KzPnzwmShkHKou1d5F@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ IronPigs Bisons @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+vK1Q-3Y

Shop  https //stza.co/+vK1Q-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ IronPigs
END:VALARM
DTSTART:20180512T223500Z
DTEND:20180513T013500Z
UID:ICyEB9KzPnzwmShkHKou1d5F@stanza.co
SUMMARY:Bisons @ IronPigs
DESCRIPTION:Bisons @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vK1Q-3Y\n\nShop: https://stza.co/+vK1Q-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ IronPigs
<2018-05-13 Sun 12:35-15:35>
:PROPERTIES:
:ID:       pipIZol985EkI8s9mM9rqOW4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bisons @ IronPigs Bisons @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+vK1R-2R

Shop  https //stza.co/+vK1R-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ IronPigs
END:VALARM
DTSTART:20180513T173500Z
DTEND:20180513T203500Z
UID:pipIZol985EkI8s9mM9rqOW4@stanza.co
SUMMARY:Bisons @ IronPigs
DESCRIPTION:Bisons @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vK1R-2R\n\nShop: https://stza.co/+vK1R-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Red Sox
<2018-05-14 Mon 17:15-20:15>
:PROPERTIES:
:ID:       3QLonZmFGtlkjJCioec-OyZb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Red Sox Bisons @ Red Sox

Buy tickets here  https //stza.co/~vK26

Follow on MiLB First Pitch  https //stza.co/+vK26-3C

Shop  https //stza.co/+vK26-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Red Sox
END:VALARM
DTSTART:20180514T221500Z
DTEND:20180515T011500Z
UID:3QLonZmFGtlkjJCioec-OyZb@stanza.co
SUMMARY:Bisons @ Red Sox
DESCRIPTION:Bisons @ Red Sox\n\nBuy tickets here: https://stza.co/~vK26\n\nFollow on MiLB First Pitch: https://stza.co/+vK26-3C\n\nShop: https://stza.co/+vK26-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Red Sox
<2018-05-15 Tue 17:15-20:15>
:PROPERTIES:
:ID:       fXPKZQNVoaEBU3j_eh8-BqNk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Red Sox Bisons @ Red Sox

Buy tickets here  https //stza.co/~vK27

Follow on MiLB First Pitch  https //stza.co/+vK27-1C

Shop  https //stza.co/+vK27-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Red Sox
END:VALARM
DTSTART:20180515T221500Z
DTEND:20180516T011500Z
UID:fXPKZQNVoaEBU3j_eh8-BqNk@stanza.co
SUMMARY:Bisons @ Red Sox
DESCRIPTION:Bisons @ Red Sox\n\nBuy tickets here: https://stza.co/~vK27\n\nFollow on MiLB First Pitch: https://stza.co/+vK27-1C\n\nShop: https://stza.co/+vK27-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Red Sox
<2018-05-16 Wed 10:05-13:05>
:PROPERTIES:
:ID:       uGlxDqdq9KAJ2TjVnJirYFJa@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bisons @ Red Sox Bisons @ Red Sox

Buy tickets here  https //stza.co/~vK28

Follow on MiLB First Pitch  https //stza.co/+vK28-m

Shop  https //stza.co/+vK28-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Red Sox
END:VALARM
DTSTART:20180516T150500Z
DTEND:20180516T180500Z
UID:uGlxDqdq9KAJ2TjVnJirYFJa@stanza.co
SUMMARY:Bisons @ Red Sox
DESCRIPTION:Bisons @ Red Sox\n\nBuy tickets here: https://stza.co/~vK28\n\nFollow on MiLB First Pitch: https://stza.co/+vK28-m\n\nShop: https://stza.co/+vK28-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. RailRiders
<2018-05-18 Fri 18:05-21:05>
:PROPERTIES:
:ID:       gVsMfLnn3jqVIIpEsG_83Z47@stanza.co
:LOCATION: Meet up with some friends at today's Happy Hour game
:STATUS:   CONFIRMED
:END:

Bisons vs. RailRiders Our friday night Happy Hour returns featuring $3 beer from Resurgence Brewery!  

We'll feature One Hit Wonders on the sound system all night long, so be ready to send us your requests!

Follow on MiLB First Pitch  https //stza.co/+vJ$V-1Q

Shop  https //stza.co/+vJ$V-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. RailRiders
END:VALARM
DTSTART:20180518T230500Z
DTEND:20180519T020500Z
UID:gVsMfLnn3jqVIIpEsG_83Z47@stanza.co
SUMMARY:Bisons vs. RailRiders
DESCRIPTION:Our friday night Happy Hour returns featuring $3 beer from Resurgence Brewery!  \n\nWe'll feature One Hit Wonders on the sound system all night long, so be ready to send us your requests!\n\nFollow on MiLB First Pitch: https://stza.co/+vJ$V-1Q\n\nShop: https://stza.co/+vJ$V-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Meet up with some friends at today's Happy Hour game
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. RailRiders
<2018-05-19 Sat 12:05-15:05>
:PROPERTIES:
:ID:       fl4OWvr0_iaLQ0xSLqgZEwk2@stanza.co
:LOCATION: Armed Forces Day
:STATUS:   CONFIRMED
:END:

Bisons vs. RailRiders We'll honor our veterans along with current members of the Armed Forces.  More details to be announced.

Follow on MiLB First Pitch  https //stza.co/+vJ$X-2T

Shop  https //stza.co/+vJ$X-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. RailRiders
END:VALARM
DTSTART:20180519T170500Z
DTEND:20180519T200500Z
UID:fl4OWvr0_iaLQ0xSLqgZEwk2@stanza.co
SUMMARY:Bisons vs. RailRiders
DESCRIPTION:We'll honor our veterans along with current members of the Armed Forces.  More details to be announced.\n\nFollow on MiLB First Pitch: https://stza.co/+vJ$X-2T\n\nShop: https://stza.co/+vJ$X-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Armed Forces Day
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. RailRiders
<2018-05-20 Sun 12:05-15:05>
:PROPERTIES:
:ID:       -NLAHrLmK22QkerBk7FoOv1x@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Bisons vs. RailRiders The first 2,000 fans will receive a Dog Bowl for their furry friend!

Come and enjoy the game with man's best friend!

Stick around after every Sunday game and watch your child run the bases, just like the Bisons do!

Follow on MiLB First Pitch  https //stza.co/+vJ$Z-1L

Shop  https //stza.co/+vJ$Z-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. RailRiders
END:VALARM
DTSTART:20180520T170500Z
DTEND:20180520T200500Z
UID:-NLAHrLmK22QkerBk7FoOv1x@stanza.co
SUMMARY:Bisons vs. RailRiders
DESCRIPTION:The first 2,000 fans will receive a Dog Bowl for their furry friend!\n\nCome and enjoy the game with man's best friend!\n\nStick around after every Sunday game and watch your child run the bases, just like the Bisons do!\n\nFollow on MiLB First Pitch: https://stza.co/+vJ$Z-1L\n\nShop: https://stza.co/+vJ$Z-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Chiefs
<2018-05-21 Mon 17:05-20:05>
:PROPERTIES:
:ID:       lOUspEPQ6lpwEjY0XMNRZjyl@stanza.co
:LOCATION: Come out for our Mardown Monday game!
:STATUS:   CONFIRMED
:END:

Bisons vs. Chiefs Discounted tickets along with $1 ice-cream and $1 popcorn at the concession stands!

Follow on MiLB First Pitch  https //stza.co/+vJ$_-2x

Shop  https //stza.co/+vJ$_-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Chiefs
END:VALARM
DTSTART:20180521T220500Z
DTEND:20180522T010500Z
UID:lOUspEPQ6lpwEjY0XMNRZjyl@stanza.co
SUMMARY:Bisons vs. Chiefs
DESCRIPTION:Discounted tickets along with $1 ice-cream and $1 popcorn at the concession stands!\n\nFollow on MiLB First Pitch: https://stza.co/+vJ$_-2x\n\nShop: https://stza.co/+vJ$_-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Come out for our Mardown Monday game!
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Chiefs
<2018-05-22 Tue 17:05-20:05>
:PROPERTIES:
:ID:       JF7wSBlug8vd3ovCGpWBpoff@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons vs. Chiefs Bisons vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+vK01-22

Shop  https //stza.co/+vK01-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Chiefs
END:VALARM
DTSTART:20180522T220500Z
DTEND:20180523T010500Z
UID:JF7wSBlug8vd3ovCGpWBpoff@stanza.co
SUMMARY:Bisons vs. Chiefs
DESCRIPTION:Bisons vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+vK01-22\n\nShop: https://stza.co/+vK01-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Chiefs
<2018-05-23 Wed 17:05-20:05>
:PROPERTIES:
:ID:       cEKVFSwSJM3NrnsRuepgOQM8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons vs. Chiefs Bisons vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+vK03-2p

Shop  https //stza.co/+vK03-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Chiefs
END:VALARM
DTSTART:20180523T220500Z
DTEND:20180524T010500Z
UID:cEKVFSwSJM3NrnsRuepgOQM8@stanza.co
SUMMARY:Bisons vs. Chiefs
DESCRIPTION:Bisons vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+vK03-2p\n\nShop: https://stza.co/+vK03-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Chiefs
<2018-05-24 Thu 12:05-15:05>
:PROPERTIES:
:ID:       ZjwReuyr_SLZkAZ2HkP-NKNK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bisons vs. Chiefs Bisons vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+vK05-1S

Shop  https //stza.co/+vK05-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Chiefs
END:VALARM
DTSTART:20180524T170500Z
DTEND:20180524T200500Z
UID:ZjwReuyr_SLZkAZ2HkP-NKNK@stanza.co
SUMMARY:Bisons vs. Chiefs
DESCRIPTION:Bisons vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+vK05-1S\n\nShop: https://stza.co/+vK05-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Red Wings
<2018-05-25 Fri 18:05-21:05>
:PROPERTIES:
:ID:       q259j-5eZWnv5_e8KCuVRgmu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Red Wings Bisons @ Red Wings

Follow on MiLB First Pitch  https //stza.co/+vK2f-2h

Shop  https //stza.co/+vK2f-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Red Wings
END:VALARM
DTSTART:20180525T230500Z
DTEND:20180526T020500Z
UID:q259j-5eZWnv5_e8KCuVRgmu@stanza.co
SUMMARY:Bisons @ Red Wings
DESCRIPTION:Bisons @ Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vK2f-2h\n\nShop: https://stza.co/+vK2f-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Red Wings
<2018-05-26 Sat 18:05-21:05>
:PROPERTIES:
:ID:       9wnq4sjsBx2iH06VOgZnYAty@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Red Wings Bisons @ Red Wings

Follow on MiLB First Pitch  https //stza.co/+vK2g-T

Shop  https //stza.co/+vK2g-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Red Wings
END:VALARM
DTSTART:20180526T230500Z
DTEND:20180527T020500Z
UID:9wnq4sjsBx2iH06VOgZnYAty@stanza.co
SUMMARY:Bisons @ Red Wings
DESCRIPTION:Bisons @ Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vK2g-T\n\nShop: https://stza.co/+vK2g-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Red Wings
<2018-05-27 Sun 12:05-15:05>
:PROPERTIES:
:ID:       qxj4l-08Za9SJEHJFfpqRyqM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bisons @ Red Wings Bisons @ Red Wings

Follow on MiLB First Pitch  https //stza.co/+vK2h-35

Shop  https //stza.co/+vK2h-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Red Wings
END:VALARM
DTSTART:20180527T170500Z
DTEND:20180527T200500Z
UID:qxj4l-08Za9SJEHJFfpqRyqM@stanza.co
SUMMARY:Bisons @ Red Wings
DESCRIPTION:Bisons @ Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vK2h-35\n\nShop: https://stza.co/+vK2h-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Red Wings
<2018-05-28 Mon 12:05-15:05>
:PROPERTIES:
:ID:       YOaYzR4RFuMbAbh9M-sdKBB2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Red Wings Bisons @ Red Wings

Follow on MiLB First Pitch  https //stza.co/+vK2i-27

Shop  https //stza.co/+vK2i-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Red Wings
END:VALARM
DTSTART:20180528T170500Z
DTEND:20180528T200500Z
UID:YOaYzR4RFuMbAbh9M-sdKBB2@stanza.co
SUMMARY:Bisons @ Red Wings
DESCRIPTION:Bisons @ Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vK2i-27\n\nShop: https://stza.co/+vK2i-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Clippers
<2018-05-29 Tue 17:05-20:05>
:PROPERTIES:
:ID:       ntP2e664bsq4lQfQazdDrVSR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons vs. Clippers Bisons vs. Clippers

Follow on MiLB First Pitch  https //stza.co/+vK07-d

Shop  https //stza.co/+vK07-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Clippers
END:VALARM
DTSTART:20180529T220500Z
DTEND:20180530T010500Z
UID:ntP2e664bsq4lQfQazdDrVSR@stanza.co
SUMMARY:Bisons vs. Clippers
DESCRIPTION:Bisons vs. Clippers\n\nFollow on MiLB First Pitch: https://stza.co/+vK07-d\n\nShop: https://stza.co/+vK07-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Clippers
<2018-05-30 Wed 17:05-20:05>
:PROPERTIES:
:ID:       2FPcwhBU6yONu8nGXrSVsrzD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bisons vs. Clippers Bisons vs. Clippers

Follow on MiLB First Pitch  https //stza.co/+vK09-2l

Shop  https //stza.co/+vK09-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Clippers
END:VALARM
DTSTART:20180530T220500Z
DTEND:20180531T010500Z
UID:2FPcwhBU6yONu8nGXrSVsrzD@stanza.co
SUMMARY:Bisons vs. Clippers
DESCRIPTION:Bisons vs. Clippers\n\nFollow on MiLB First Pitch: https://stza.co/+vK09-2l\n\nShop: https://stza.co/+vK09-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Clippers
<2018-05-31 Thu 09:35-12:35>
:PROPERTIES:
:ID:       lgUuoRqx2vFCs69QHZGoHmuu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons vs. Clippers Bisons vs. Clippers

Follow on MiLB First Pitch  https //stza.co/+vK0b-h

Shop  https //stza.co/+vK0b-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Clippers
END:VALARM
DTSTART:20180531T143500Z
DTEND:20180531T173500Z
UID:lgUuoRqx2vFCs69QHZGoHmuu@stanza.co
SUMMARY:Bisons vs. Clippers
DESCRIPTION:Bisons vs. Clippers\n\nFollow on MiLB First Pitch: https://stza.co/+vK0b-h\n\nShop: https://stza.co/+vK0b-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Knights
<2018-06-01 Fri 18:05-21:05>
:PROPERTIES:
:ID:       2CEW-r-sVgvHm4gordLWmZ0A@stanza.co
:LOCATION: Meet up with some friends at today's Happy Hour game
:STATUS:   CONFIRMED
:END:

Bisons vs. Knights Our friday night Happy Hour returns featuring $3 beer from Resurgence Brewery!  

Make sure your phones are charged before you head to the ballpark!  We'll give away prizes, let you vote for the opposing team's at-bat music, and more on all of our social media accounts!

Follow on MiLB First Pitch  https //stza.co/+vK0c-2_

Shop  https //stza.co/+vK0c-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Knights
END:VALARM
DTSTART:20180601T230500Z
DTEND:20180602T020500Z
UID:2CEW-r-sVgvHm4gordLWmZ0A@stanza.co
SUMMARY:Bisons vs. Knights
DESCRIPTION:Our friday night Happy Hour returns featuring $3 beer from Resurgence Brewery!  \n\nMake sure your phones are charged before you head to the ballpark!  We'll give away prizes, let you vote for the opposing team's at-bat music, and more on all of our social media accounts!\n\nFollow on MiLB First Pitch: https://stza.co/+vK0c-2_\n\nShop: https://stza.co/+vK0c-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Meet up with some friends at today's Happy Hour game
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Knights
<2018-06-02 Sat 17:05-20:05>
:PROPERTIES:
:ID:       CONXt29cLf5BdwOG95GVG9Ay@stanza.co
:LOCATION: May the force be with you! Come check out Stars Wars Night at the park
:STATUS:   CONFIRMED
:END:

Bisons vs. Knights May the Force be with you on one of the most exciting nights of the season!  You'll have the opportunity to meet your favorite characters and follow along with our story line on the Video Board.  After the game we'll cap the evening off with an epic on-field battle accompanied by an awesome fireworks show!

Follow on MiLB First Pitch  https //stza.co/+vK0f-y

Shop  https //stza.co/+vK0f-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Knights
END:VALARM
DTSTART:20180602T220500Z
DTEND:20180603T010500Z
UID:CONXt29cLf5BdwOG95GVG9Ay@stanza.co
SUMMARY:Bisons vs. Knights
DESCRIPTION:May the Force be with you on one of the most exciting nights of the season!  You'll have the opportunity to meet your favorite characters and follow along with our story line on the Video Board.  After the game we'll cap the evening off with an epic on-field battle accompanied by an awesome fireworks show!\n\nFollow on MiLB First Pitch: https://stza.co/+vK0f-y\n\nShop: https://stza.co/+vK0f-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:May the force be with you! Come check out Stars Wars Night at the park
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Knights
<2018-06-03 Sun 12:05-15:05>
:PROPERTIES:
:ID:       xt0ByJ7yWPM0qJ1eO4Pq-IWN@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Bisons vs. Knights Your little league team can buy tickets at a group rate and have the opportunity to participate in a Q&A with one of the Bisons players before the game!

The first 1,000 fans through the gates will receive a Bisons Activity Book featuring puzzles, coloring sheets, and more!

Stick around after every Sunday game and watch your child run the bases, just like the Bisons do!

Follow on MiLB First Pitch  https //stza.co/+vK0h-3H

Shop  https //stza.co/+vK0h-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Knights
END:VALARM
DTSTART:20180603T170500Z
DTEND:20180603T200500Z
UID:xt0ByJ7yWPM0qJ1eO4Pq-IWN@stanza.co
SUMMARY:Bisons vs. Knights
DESCRIPTION:Your little league team can buy tickets at a group rate and have the opportunity to participate in a Q&A with one of the Bisons players before the game!\n\nThe first 1,000 fans through the gates will receive a Bisons Activity Book featuring puzzles, coloring sheets, and more!\n\nStick around after every Sunday game and watch your child run the bases, just like the Bisons do!\n\nFollow on MiLB First Pitch: https://stza.co/+vK0h-3H\n\nShop: https://stza.co/+vK0h-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Mud Hens
<2018-06-05 Tue 18:05-21:05>
:PROPERTIES:
:ID:       g9T8suSZnowUWcika_kkIbjp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Mud Hens Bisons @ Mud Hens

Follow on MiLB First Pitch  https //stza.co/+vK2B-25

Shop  https //stza.co/+vK2B-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Mud Hens
END:VALARM
DTSTART:20180605T230500Z
DTEND:20180606T020500Z
UID:g9T8suSZnowUWcika_kkIbjp@stanza.co
SUMMARY:Bisons @ Mud Hens
DESCRIPTION:Bisons @ Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+vK2B-25\n\nShop: https://stza.co/+vK2B-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Mud Hens
<2018-06-06 Wed 18:05-21:05>
:PROPERTIES:
:ID:       EUuFEPxys7hPhxMQ67Ri2hB1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bisons @ Mud Hens Bisons @ Mud Hens

Follow on MiLB First Pitch  https //stza.co/+vK2C-3a

Shop  https //stza.co/+vK2C-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Mud Hens
END:VALARM
DTSTART:20180606T230500Z
DTEND:20180607T020500Z
UID:EUuFEPxys7hPhxMQ67Ri2hB1@stanza.co
SUMMARY:Bisons @ Mud Hens
DESCRIPTION:Bisons @ Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+vK2C-3a\n\nShop: https://stza.co/+vK2C-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Mud Hens
<2018-06-07 Thu 18:05-21:05>
:PROPERTIES:
:ID:       8bEBk0eL6dIo3sKmp69uevBU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Mud Hens Bisons @ Mud Hens

Follow on MiLB First Pitch  https //stza.co/+uWU_-29

Shop  https //stza.co/+uWU_-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Mud Hens
END:VALARM
DTSTART:20180607T230500Z
DTEND:20180608T020500Z
UID:8bEBk0eL6dIo3sKmp69uevBU@stanza.co
SUMMARY:Bisons @ Mud Hens
DESCRIPTION:Bisons @ Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+uWU_-29\n\nShop: https://stza.co/+uWU_-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Clippers
<2018-06-08 Fri 18:15-21:15>
:PROPERTIES:
:ID:       NNV6TwpTy3alB9DuO7hjTMuB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Clippers Bisons @ Clippers

Buy tickets here  https //stza.co/~vK1B

Follow on MiLB First Pitch  https //stza.co/+vK1B-3a

Shop  https //stza.co/+vK1B-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Clippers
END:VALARM
DTSTART:20180608T231500Z
DTEND:20180609T021500Z
UID:NNV6TwpTy3alB9DuO7hjTMuB@stanza.co
SUMMARY:Bisons @ Clippers
DESCRIPTION:Bisons @ Clippers\n\nBuy tickets here: https://stza.co/~vK1B\n\nFollow on MiLB First Pitch: https://stza.co/+vK1B-3a\n\nShop: https://stza.co/+vK1B-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Clippers
<2018-06-09 Sat 18:15-21:15>
:PROPERTIES:
:ID:       u6WbspgYGaubYbUEmlhhlmo3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bisons @ Clippers Bisons @ Clippers

Buy tickets here  https //stza.co/~vK1C

Follow on MiLB First Pitch  https //stza.co/+vK1C-3B

Shop  https //stza.co/+vK1C-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Clippers
END:VALARM
DTSTART:20180609T231500Z
DTEND:20180610T021500Z
UID:u6WbspgYGaubYbUEmlhhlmo3@stanza.co
SUMMARY:Bisons @ Clippers
DESCRIPTION:Bisons @ Clippers\n\nBuy tickets here: https://stza.co/~vK1C\n\nFollow on MiLB First Pitch: https://stza.co/+vK1C-3B\n\nShop: https://stza.co/+vK1C-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Clippers
<2018-06-10 Sun 13:05-16:05>
:PROPERTIES:
:ID:       1y3-xBASwwDjhQ9Wx-utVykX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Clippers Bisons @ Clippers

Buy tickets here  https //stza.co/~vK1D

Follow on MiLB First Pitch  https //stza.co/+vK1D-18

Shop  https //stza.co/+vK1D-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Clippers
END:VALARM
DTSTART:20180610T180500Z
DTEND:20180610T210500Z
UID:1y3-xBASwwDjhQ9Wx-utVykX@stanza.co
SUMMARY:Bisons @ Clippers
DESCRIPTION:Bisons @ Clippers\n\nBuy tickets here: https://stza.co/~vK1D\n\nFollow on MiLB First Pitch: https://stza.co/+vK1D-18\n\nShop: https://stza.co/+vK1D-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ IronPigs
<2018-06-11 Mon 18:05-21:05>
:PROPERTIES:
:ID:       gUv7kuqXg_GKiK8llbMus-22@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ IronPigs Bisons @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+vK1S-1w

Shop  https //stza.co/+vK1S-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ IronPigs
END:VALARM
DTSTART:20180611T230500Z
DTEND:20180612T020500Z
UID:gUv7kuqXg_GKiK8llbMus-22@stanza.co
SUMMARY:Bisons @ IronPigs
DESCRIPTION:Bisons @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vK1S-1w\n\nShop: https://stza.co/+vK1S-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ IronPigs
<2018-06-12 Tue 18:05-21:05>
:PROPERTIES:
:ID:       dVegwuZr_q0lJTk59mGzd5vf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bisons @ IronPigs Bisons @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+vK1T-1f

Shop  https //stza.co/+vK1T-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ IronPigs
END:VALARM
DTSTART:20180612T230500Z
DTEND:20180613T020500Z
UID:dVegwuZr_q0lJTk59mGzd5vf@stanza.co
SUMMARY:Bisons @ IronPigs
DESCRIPTION:Bisons @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vK1T-1f\n\nShop: https://stza.co/+vK1T-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ IronPigs
<2018-06-13 Wed 18:05-21:05>
:PROPERTIES:
:ID:       Fe00qnV8s-fAKAANtzC-PzCi@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ IronPigs Bisons @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+vK1U-i

Shop  https //stza.co/+vK1U-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ IronPigs
END:VALARM
DTSTART:20180613T230500Z
DTEND:20180614T020500Z
UID:Fe00qnV8s-fAKAANtzC-PzCi@stanza.co
SUMMARY:Bisons @ IronPigs
DESCRIPTION:Bisons @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vK1U-i\n\nShop: https://stza.co/+vK1U-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Red Wings
<2018-06-14 Thu 18:05-21:05>
:PROPERTIES:
:ID:       0WfdhNfDQtN4ID3gQhKK8Pkn@stanza.co
:LOCATION: Dog Day
:STATUS:   CONFIRMED
:END:

Bisons vs. Red Wings Come and enjoy the game with man's best friend!

Follow on MiLB First Pitch  https //stza.co/+vK0i-1E

Shop  https //stza.co/+vK0i-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Red Wings
END:VALARM
DTSTART:20180614T230500Z
DTEND:20180615T020500Z
UID:0WfdhNfDQtN4ID3gQhKK8Pkn@stanza.co
SUMMARY:Bisons vs. Red Wings
DESCRIPTION:Come and enjoy the game with man's best friend!\n\nFollow on MiLB First Pitch: https://stza.co/+vK0i-1E\n\nShop: https://stza.co/+vK0i-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dog Day
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Red Wings
<2018-06-15 Fri 18:05-21:05>
:PROPERTIES:
:ID:       kw9bJfwvnOLrxNkWiOsJY44Y@stanza.co
:LOCATION: Come to the park for our Friday Night Bash!
:STATUS:   CONFIRMED
:END:

Bisons vs. Red Wings More details to be announced.

Follow on MiLB First Pitch  https //stza.co/+vK0k-3o

Shop  https //stza.co/+vK0k-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Red Wings
END:VALARM
DTSTART:20180615T230500Z
DTEND:20180616T020500Z
UID:kw9bJfwvnOLrxNkWiOsJY44Y@stanza.co
SUMMARY:Bisons vs. Red Wings
DESCRIPTION:More details to be announced.\n\nFollow on MiLB First Pitch: https://stza.co/+vK0k-3o\n\nShop: https://stza.co/+vK0k-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Come to the park for our Friday Night Bash!
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Red Wings
<2018-06-16 Sat 17:05-20:05>
:PROPERTIES:
:ID:       KlEyX24yR-YSgjHrmvBZwsQI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons vs. Red Wings Bisons vs. Red Wings

Follow on MiLB First Pitch  https //stza.co/+vK0m-$

Shop  https //stza.co/+vK0m-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Red Wings
END:VALARM
DTSTART:20180616T220500Z
DTEND:20180617T010500Z
UID:KlEyX24yR-YSgjHrmvBZwsQI@stanza.co
SUMMARY:Bisons vs. Red Wings
DESCRIPTION:Bisons vs. Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vK0m-$\n\nShop: https://stza.co/+vK0m-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Red Wings
<2018-06-17 Sun 12:05-15:05>
:PROPERTIES:
:ID:       ztHW_vmdA_5A2iVlr8JXS61Y@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Bisons vs. Red Wings Bring your dad out to the old ballgame, and make sure you get here early because the first 2,000 fans through the gate will receive a logo baseball!

Stick around after every Sunday game and watch your child run the bases, just like the Bisons do!

Stick around after the game and play catch with dad on the field!

Follow on MiLB First Pitch  https //stza.co/+vK0p-3

Shop  https //stza.co/+vK0p-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Red Wings
END:VALARM
DTSTART:20180617T170500Z
DTEND:20180617T200500Z
UID:ztHW_vmdA_5A2iVlr8JXS61Y@stanza.co
SUMMARY:Bisons vs. Red Wings
DESCRIPTION:Bring your dad out to the old ballgame, and make sure you get here early because the first 2,000 fans through the gate will receive a logo baseball!\n\nStick around after every Sunday game and watch your child run the bases, just like the Bisons do!\n\nStick around after the game and play catch with dad on the field!\n\nFollow on MiLB First Pitch: https://stza.co/+vK0p-3\n\nShop: https://stza.co/+vK0p-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Red Sox
<2018-06-19 Tue 17:15-20:15>
:PROPERTIES:
:ID:       rEyeulJcuvdzh08h6uipLbJx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bisons @ Red Sox Bisons @ Red Sox

Buy tickets here  https //stza.co/~vK29

Follow on MiLB First Pitch  https //stza.co/+vK29-

Shop  https //stza.co/+vK29-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Red Sox
END:VALARM
DTSTART:20180619T221500Z
DTEND:20180620T011500Z
UID:rEyeulJcuvdzh08h6uipLbJx@stanza.co
SUMMARY:Bisons @ Red Sox
DESCRIPTION:Bisons @ Red Sox\n\nBuy tickets here: https://stza.co/~vK29\n\nFollow on MiLB First Pitch: https://stza.co/+vK29-\n\nShop: https://stza.co/+vK29-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Red Sox
<2018-06-20 Wed 17:15-20:15>
:PROPERTIES:
:ID:       1TBdQrONspVPJJCU1KwkPKFV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Red Sox Bisons @ Red Sox

Buy tickets here  https //stza.co/~vK2a

Follow on MiLB First Pitch  https //stza.co/+vK2a-2F

Shop  https //stza.co/+vK2a-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Red Sox
END:VALARM
DTSTART:20180620T221500Z
DTEND:20180621T011500Z
UID:1TBdQrONspVPJJCU1KwkPKFV@stanza.co
SUMMARY:Bisons @ Red Sox
DESCRIPTION:Bisons @ Red Sox\n\nBuy tickets here: https://stza.co/~vK2a\n\nFollow on MiLB First Pitch: https://stza.co/+vK2a-2F\n\nShop: https://stza.co/+vK2a-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Red Sox
<2018-06-21 Thu 17:15-20:15>
:PROPERTIES:
:ID:       hJ_iRTUrJLTK4hMOqBC7rQ0E@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Red Sox Bisons @ Red Sox

Buy tickets here  https //stza.co/~vK2b

Follow on MiLB First Pitch  https //stza.co/+vK2b-3I

Shop  https //stza.co/+vK2b-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Red Sox
END:VALARM
DTSTART:20180621T221500Z
DTEND:20180622T011500Z
UID:hJ_iRTUrJLTK4hMOqBC7rQ0E@stanza.co
SUMMARY:Bisons @ Red Sox
DESCRIPTION:Bisons @ Red Sox\n\nBuy tickets here: https://stza.co/~vK2b\n\nFollow on MiLB First Pitch: https://stza.co/+vK2b-3I\n\nShop: https://stza.co/+vK2b-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. IronPigs
<2018-06-22 Fri 18:05-21:05>
:PROPERTIES:
:ID:       ETaMZNd5hfMwo8S5a-pbGkzX@stanza.co
:LOCATION: Meet up with some friends at today's Happy Hour game
:STATUS:   CONFIRMED
:END:

Bisons vs. IronPigs Our friday night Happy Hour returns featuring $3 beer from Resurgence Brewery!  

We'll celebrate the 25th anniversary of this classic baseball film with trivia, games, and more!

Follow on MiLB First Pitch  https //stza.co/+vK0q-1z

Shop  https //stza.co/+vK0q-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. IronPigs
END:VALARM
DTSTART:20180622T230500Z
DTEND:20180623T020500Z
UID:ETaMZNd5hfMwo8S5a-pbGkzX@stanza.co
SUMMARY:Bisons vs. IronPigs
DESCRIPTION:Our friday night Happy Hour returns featuring $3 beer from Resurgence Brewery!  \n\nWe'll celebrate the 25th anniversary of this classic baseball film with trivia, games, and more!\n\nFollow on MiLB First Pitch: https://stza.co/+vK0q-1z\n\nShop: https://stza.co/+vK0q-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Meet up with some friends at today's Happy Hour game
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. IronPigs
<2018-06-23 Sat 17:05-20:05>
:PROPERTIES:
:ID:       _iV2QlvoKCTWJHjhZwM48REQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bisons vs. IronPigs Bisons vs. IronPigs

Follow on MiLB First Pitch  https //stza.co/+vK0s-2q

Shop  https //stza.co/+vK0s-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. IronPigs
END:VALARM
DTSTART:20180623T220500Z
DTEND:20180624T010500Z
UID:_iV2QlvoKCTWJHjhZwM48REQ@stanza.co
SUMMARY:Bisons vs. IronPigs
DESCRIPTION:Bisons vs. IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vK0s-2q\n\nShop: https://stza.co/+vK0s-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. IronPigs
<2018-06-24 Sun 12:05-15:05>
:PROPERTIES:
:ID:       P_iZBLneXh7sHmB91SFZANGA@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Bisons vs. IronPigs Bring your little princess to meet some of her favorite princesses!

Stick around after every Sunday game and watch your child run the bases, just like the Bisons do!

Follow on MiLB First Pitch  https //stza.co/+vK0v-1I

Shop  https //stza.co/+vK0v-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. IronPigs
END:VALARM
DTSTART:20180624T170500Z
DTEND:20180624T200500Z
UID:P_iZBLneXh7sHmB91SFZANGA@stanza.co
SUMMARY:Bisons vs. IronPigs
DESCRIPTION:Bring your little princess to meet some of her favorite princesses!\n\nStick around after every Sunday game and watch your child run the bases, just like the Bisons do!\n\nFollow on MiLB First Pitch: https://stza.co/+vK0v-1I\n\nShop: https://stza.co/+vK0v-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Red Sox
<2018-06-25 Mon 18:05-21:05>
:PROPERTIES:
:ID:       3xZjVE5FMgsNXRZ0n1aSCYNu@stanza.co
:LOCATION: Come out for our Mardown Monday game!
:STATUS:   CONFIRMED
:END:

Bisons vs. Red Sox Discounted tickets along with $1 ice-cream and $1 popcorn at the concession stands!

Follow on MiLB First Pitch  https //stza.co/+vK0x-3b

Shop  https //stza.co/+vK0x-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Red Sox
END:VALARM
DTSTART:20180625T230500Z
DTEND:20180626T020500Z
UID:3xZjVE5FMgsNXRZ0n1aSCYNu@stanza.co
SUMMARY:Bisons vs. Red Sox
DESCRIPTION:Discounted tickets along with $1 ice-cream and $1 popcorn at the concession stands!\n\nFollow on MiLB First Pitch: https://stza.co/+vK0x-3b\n\nShop: https://stza.co/+vK0x-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Come out for our Mardown Monday game!
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Red Sox
<2018-06-26 Tue 18:05-21:05>
:PROPERTIES:
:ID:       XlbgDgqqYZ3LiHpX33llAN3x@stanza.co
:LOCATION: Irish Festival Night
:STATUS:   CONFIRMED
:END:

Bisons vs. Red Sox We'll celebrate the Irish Heritage with music, dancers and more!  Stick around after the game for some weeknight fireworks!

Follow on MiLB First Pitch  https //stza.co/+vK0z-C

Shop  https //stza.co/+vK0z-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Red Sox
END:VALARM
DTSTART:20180626T230500Z
DTEND:20180627T020500Z
UID:XlbgDgqqYZ3LiHpX33llAN3x@stanza.co
SUMMARY:Bisons vs. Red Sox
DESCRIPTION:We'll celebrate the Irish Heritage with music, dancers and more!  Stick around after the game for some weeknight fireworks!\n\nFollow on MiLB First Pitch: https://stza.co/+vK0z-C\n\nShop: https://stza.co/+vK0z-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Irish Festival Night
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Red Sox
<2018-06-27 Wed 18:05-21:05>
:PROPERTIES:
:ID:       ADcq0Na68EuKkAVqlbaEahxT@stanza.co
:LOCATION: Fidget Spinner Giveaway
:STATUS:   CONFIRMED
:END:

Bisons vs. Red Sox The first 2,000 fans through the Inspire Dental Gate at Swan will receive a Bisons themed fidget spinner.  Gates open at 6 00pm.

Follow on MiLB First Pitch  https //stza.co/+vK0A-14

Shop  https //stza.co/+vK0A-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Red Sox
END:VALARM
DTSTART:20180627T230500Z
DTEND:20180628T020500Z
UID:ADcq0Na68EuKkAVqlbaEahxT@stanza.co
SUMMARY:Bisons vs. Red Sox
DESCRIPTION:The first 2,000 fans through the Inspire Dental Gate at Swan will receive a Bisons themed fidget spinner.  Gates open at 6:00pm.\n\nFollow on MiLB First Pitch: https://stza.co/+vK0A-14\n\nShop: https://stza.co/+vK0A-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fidget Spinner Giveaway
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Red Sox
<2018-06-28 Thu 12:05-15:05>
:PROPERTIES:
:ID:       wvIrRoZnx30hsVhm_bF7Z1Kc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons vs. Red Sox Bisons vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+vK0D-2x

Shop  https //stza.co/+vK0D-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Red Sox
END:VALARM
DTSTART:20180628T170500Z
DTEND:20180628T200500Z
UID:wvIrRoZnx30hsVhm_bF7Z1Kc@stanza.co
SUMMARY:Bisons vs. Red Sox
DESCRIPTION:Bisons vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+vK0D-2x\n\nShop: https://stza.co/+vK0D-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Chiefs
<2018-06-29 Fri 18:05-21:05>
:PROPERTIES:
:ID:       AoB9gDrmoHeGpSqujDkVBQqc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Chiefs Bisons @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+vK2u-1M

Shop  https //stza.co/+vK2u-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Chiefs
END:VALARM
DTSTART:20180629T230500Z
DTEND:20180630T020500Z
UID:AoB9gDrmoHeGpSqujDkVBQqc@stanza.co
SUMMARY:Bisons @ Chiefs
DESCRIPTION:Bisons @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+vK2u-1M\n\nShop: https://stza.co/+vK2u-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Chiefs
<2018-06-30 Sat 18:05-21:05>
:PROPERTIES:
:ID:       NGPqf8B4qXt2zi6WLLuEH7W1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bisons @ Chiefs Bisons @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+vK2v-2i

Shop  https //stza.co/+vK2v-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Chiefs
END:VALARM
DTSTART:20180630T230500Z
DTEND:20180701T020500Z
UID:NGPqf8B4qXt2zi6WLLuEH7W1@stanza.co
SUMMARY:Bisons @ Chiefs
DESCRIPTION:Bisons @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+vK2v-2i\n\nShop: https://stza.co/+vK2v-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Chiefs
<2018-07-01 Sun 12:05-15:05>
:PROPERTIES:
:ID:       s0sBD6esaK1BBeTEDk31QpL6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Chiefs Bisons @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+vK2w-3E

Shop  https //stza.co/+vK2w-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Chiefs
END:VALARM
DTSTART:20180701T170500Z
DTEND:20180701T200500Z
UID:s0sBD6esaK1BBeTEDk31QpL6@stanza.co
SUMMARY:Bisons @ Chiefs
DESCRIPTION:Bisons @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+vK2w-3E\n\nShop: https://stza.co/+vK2w-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. RailRiders
<2018-07-02 Mon 18:05-21:05>
:PROPERTIES:
:ID:       X4wrIK3IZasiqn6LZ86O7La3@stanza.co
:LOCATION: Come out for our Mardown Monday game!
:STATUS:   CONFIRMED
:END:

Bisons vs. RailRiders Discounted tickets along with $1 ice-cream and $1 popcorn at the concession stands!

Follow on MiLB First Pitch  https //stza.co/+vK0F-2b

Shop  https //stza.co/+vK0F-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. RailRiders
END:VALARM
DTSTART:20180702T230500Z
DTEND:20180703T020500Z
UID:X4wrIK3IZasiqn6LZ86O7La3@stanza.co
SUMMARY:Bisons vs. RailRiders
DESCRIPTION:Discounted tickets along with $1 ice-cream and $1 popcorn at the concession stands!\n\nFollow on MiLB First Pitch: https://stza.co/+vK0F-2b\n\nShop: https://stza.co/+vK0F-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Come out for our Mardown Monday game!
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. RailRiders
<2018-07-03 Tue 17:05-20:05>
:PROPERTIES:
:ID:       Z-PBs2cYgg28ofI9-YSy58pK@stanza.co
:LOCATION: KeyBank Independence Eve Celebration
:STATUS:   CONFIRMED
:END:

Bisons vs. RailRiders The tradition continues as the Buffalo Philharmonic and Chorus will put on a harmonious post-game performance accompanied by one of the largest fireworks shows of the season!

Follow on MiLB First Pitch  https //stza.co/+vK0H-S

Shop  https //stza.co/+vK0H-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. RailRiders
END:VALARM
DTSTART:20180703T220500Z
DTEND:20180704T010500Z
UID:Z-PBs2cYgg28ofI9-YSy58pK@stanza.co
SUMMARY:Bisons vs. RailRiders
DESCRIPTION:The tradition continues as the Buffalo Philharmonic and Chorus will put on a harmonious post-game performance accompanied by one of the largest fireworks shows of the season!\n\nFollow on MiLB First Pitch: https://stza.co/+vK0H-S\n\nShop: https://stza.co/+vK0H-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:KeyBank Independence Eve Celebration
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ RailRiders
<2018-07-04 Wed 18:05-21:05>
:PROPERTIES:
:ID:       tStIAlBkvuZBqbamq96GHXqV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ RailRiders Bisons @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vK2p-2k

Shop  https //stza.co/+vK2p-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ RailRiders
END:VALARM
DTSTART:20180704T230500Z
DTEND:20180705T020500Z
UID:tStIAlBkvuZBqbamq96GHXqV@stanza.co
SUMMARY:Bisons @ RailRiders
DESCRIPTION:Bisons @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vK2p-2k\n\nShop: https://stza.co/+vK2p-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ RailRiders
<2018-07-05 Thu 11:05-14:05>
:PROPERTIES:
:ID:       wxHIuLuZXCKQxxT5VzGW1sv0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bisons @ RailRiders Bisons @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vK2q-u

Shop  https //stza.co/+vK2q-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ RailRiders
END:VALARM
DTSTART:20180705T160500Z
DTEND:20180705T190500Z
UID:wxHIuLuZXCKQxxT5VzGW1sv0@stanza.co
SUMMARY:Bisons @ RailRiders
DESCRIPTION:Bisons @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vK2q-u\n\nShop: https://stza.co/+vK2q-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Chiefs
<2018-07-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       Ffco-0CjECw8El3Zc2YouvEi@stanza.co
:LOCATION: Meet up with some friends at today's Happy Hour game
:STATUS:   CONFIRMED
:END:

Bisons vs. Chiefs We'll honor Conehead's 40th season with a special pre-game ceremony!

To commemorate Conehead Day, we'll giveaway 2,000 koozies to make sure your drinks stay cold!

Our friday night Happy Hour returns featuring $3 beer from Resurgence Brewery!  

Follow on MiLB First Pitch  https //stza.co/+vK0I-1p

Shop  https //stza.co/+vK0I-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Chiefs
END:VALARM
DTSTART:20180706T230500Z
DTEND:20180707T020500Z
UID:Ffco-0CjECw8El3Zc2YouvEi@stanza.co
SUMMARY:Bisons vs. Chiefs
DESCRIPTION:We'll honor Conehead's 40th season with a special pre-game ceremony!\n\nTo commemorate Conehead Day, we'll giveaway 2,000 koozies to make sure your drinks stay cold!\n\nOur friday night Happy Hour returns featuring $3 beer from Resurgence Brewery!  \n\nFollow on MiLB First Pitch: https://stza.co/+vK0I-1p\n\nShop: https://stza.co/+vK0I-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Meet up with some friends at today's Happy Hour game
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Chiefs
<2018-07-07 Sat 17:05-20:05>
:PROPERTIES:
:ID:       mzQ170i01imMlkihUUdig9K2@stanza.co
:LOCATION: Strikeout Cancer
:STATUS:   CONFIRMED
:END:

Bisons vs. Chiefs We'll honor cancer survivors before the game with a 1st pitch ceremony.  During the game will be a placard moment giving everyone an opportunity to show who they're standing up to strikeout cancer for.

Follow on MiLB First Pitch  https //stza.co/+vK0K-7

Shop  https //stza.co/+vK0K-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Chiefs
END:VALARM
DTSTART:20180707T220500Z
DTEND:20180708T010500Z
UID:mzQ170i01imMlkihUUdig9K2@stanza.co
SUMMARY:Bisons vs. Chiefs
DESCRIPTION:We'll honor cancer survivors before the game with a 1st pitch ceremony.  During the game will be a placard moment giving everyone an opportunity to show who they're standing up to strikeout cancer for.\n\nFollow on MiLB First Pitch: https://stza.co/+vK0K-7\n\nShop: https://stza.co/+vK0K-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Strikeout Cancer
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Chiefs
<2018-07-08 Sun 12:05-15:05>
:PROPERTIES:
:ID:       T-lZSN1YUgqoZ75uz02jLiJs@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Bisons vs. Chiefs The first 1,000 fans through the gates will receive a Bisons Activity Book featuring puzzles, coloring sheets, and more!

More details to be announced.

Stick around after every Sunday game and watch your child run the bases, just like the Bisons do!

Follow on MiLB First Pitch  https //stza.co/+vK0M-2O

Shop  https //stza.co/+vK0M-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Chiefs
END:VALARM
DTSTART:20180708T170500Z
DTEND:20180708T200500Z
UID:T-lZSN1YUgqoZ75uz02jLiJs@stanza.co
SUMMARY:Bisons vs. Chiefs
DESCRIPTION:The first 1,000 fans through the gates will receive a Bisons Activity Book featuring puzzles, coloring sheets, and more!\n\nMore details to be announced.\n\nStick around after every Sunday game and watch your child run the bases, just like the Bisons do!\n\nFollow on MiLB First Pitch: https://stza.co/+vK0M-2O\n\nShop: https://stza.co/+vK0M-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ IronPigs
<2018-07-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       L55ucYbYHgn7g_vE82WxPpZz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ IronPigs Bisons @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+vK1V-1a

Shop  https //stza.co/+vK1V-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ IronPigs
END:VALARM
DTSTART:20180712T230500Z
DTEND:20180713T020500Z
UID:L55ucYbYHgn7g_vE82WxPpZz@stanza.co
SUMMARY:Bisons @ IronPigs
DESCRIPTION:Bisons @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vK1V-1a\n\nShop: https://stza.co/+vK1V-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ IronPigs
<2018-07-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       bLExPtpbii0vCtDSYBT27viK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ IronPigs Bisons @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+vK1W-2w

Shop  https //stza.co/+vK1W-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ IronPigs
END:VALARM
DTSTART:20180713T230500Z
DTEND:20180714T020500Z
UID:bLExPtpbii0vCtDSYBT27viK@stanza.co
SUMMARY:Bisons @ IronPigs
DESCRIPTION:Bisons @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vK1W-2w\n\nShop: https://stza.co/+vK1W-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ IronPigs
<2018-07-14 Sat 17:35-20:35>
:PROPERTIES:
:ID:       s-bkLzK7K-pbufFKTw9llZgl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bisons @ IronPigs Bisons @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+vK1X-2I

Shop  https //stza.co/+vK1X-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ IronPigs
END:VALARM
DTSTART:20180714T223500Z
DTEND:20180715T013500Z
UID:s-bkLzK7K-pbufFKTw9llZgl@stanza.co
SUMMARY:Bisons @ IronPigs
DESCRIPTION:Bisons @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vK1X-2I\n\nShop: https://stza.co/+vK1X-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ IronPigs
<2018-07-15 Sun 12:35-15:35>
:PROPERTIES:
:ID:       A5rcPnxMtnL5bxV7uy3jxh8r@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ IronPigs Bisons @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+vK1Y-n

Shop  https //stza.co/+vK1Y-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ IronPigs
END:VALARM
DTSTART:20180715T173500Z
DTEND:20180715T203500Z
UID:A5rcPnxMtnL5bxV7uy3jxh8r@stanza.co
SUMMARY:Bisons @ IronPigs
DESCRIPTION:Bisons @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vK1Y-n\n\nShop: https://stza.co/+vK1Y-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Tides
<2018-07-16 Mon 18:05-21:05>
:PROPERTIES:
:ID:       hfIXn30NAD9FWo1Lhb1oCwrW@stanza.co
:LOCATION: Come out for our Mardown Monday game!
:STATUS:   CONFIRMED
:END:

Bisons vs. Tides Discounted tickets along with $1 ice-cream and $1 popcorn at the concession stands!

Follow on MiLB First Pitch  https //stza.co/+vK0O-v

Shop  https //stza.co/+vK0O-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Tides
END:VALARM
DTSTART:20180716T230500Z
DTEND:20180717T020500Z
UID:hfIXn30NAD9FWo1Lhb1oCwrW@stanza.co
SUMMARY:Bisons vs. Tides
DESCRIPTION:Discounted tickets along with $1 ice-cream and $1 popcorn at the concession stands!\n\nFollow on MiLB First Pitch: https://stza.co/+vK0O-v\n\nShop: https://stza.co/+vK0O-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Come out for our Mardown Monday game!
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Tides
<2018-07-17 Tue 18:05-21:05>
:PROPERTIES:
:ID:       K3d2xeFTYVZT0tRFPy6PiUIM@stanza.co
:LOCATION: Dog Day
:STATUS:   CONFIRMED
:END:

Bisons vs. Tides Come and enjoy the game with man's best friend!

Follow on MiLB First Pitch  https //stza.co/+vK0Q-2n

Shop  https //stza.co/+vK0Q-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Tides
END:VALARM
DTSTART:20180717T230500Z
DTEND:20180718T020500Z
UID:K3d2xeFTYVZT0tRFPy6PiUIM@stanza.co
SUMMARY:Bisons vs. Tides
DESCRIPTION:Come and enjoy the game with man's best friend!\n\nFollow on MiLB First Pitch: https://stza.co/+vK0Q-2n\n\nShop: https://stza.co/+vK0Q-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dog Day
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Tides
<2018-07-18 Wed 12:05-15:05>
:PROPERTIES:
:ID:       dnyUiAonZtkaNheCq_VibtgV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons vs. Tides Bisons vs. Tides

Follow on MiLB First Pitch  https //stza.co/+vK0S-2q

Shop  https //stza.co/+vK0S-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Tides
END:VALARM
DTSTART:20180718T170500Z
DTEND:20180718T200500Z
UID:dnyUiAonZtkaNheCq_VibtgV@stanza.co
SUMMARY:Bisons vs. Tides
DESCRIPTION:Bisons vs. Tides\n\nFollow on MiLB First Pitch: https://stza.co/+vK0S-2q\n\nShop: https://stza.co/+vK0S-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Bulls
<2018-07-19 Thu 18:05-21:05>
:PROPERTIES:
:ID:       WFPrVkjrD2ahPB8k97LihoLI@stanza.co
:LOCATION: Italian Festival Night
:STATUS:   CONFIRMED
:END:

Bisons vs. Bulls We'll celebrate Italian heritage with music, food, trivia and of course, bocce!  Stick around after the game for a great fireworks show!

Follow on MiLB First Pitch  https //stza.co/+vK0U-1G

Shop  https //stza.co/+vK0U-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Bulls
END:VALARM
DTSTART:20180719T230500Z
DTEND:20180720T020500Z
UID:WFPrVkjrD2ahPB8k97LihoLI@stanza.co
SUMMARY:Bisons vs. Bulls
DESCRIPTION:We'll celebrate Italian heritage with music, food, trivia and of course, bocce!  Stick around after the game for a great fireworks show!\n\nFollow on MiLB First Pitch: https://stza.co/+vK0U-1G\n\nShop: https://stza.co/+vK0U-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Italian Festival Night
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Bulls
<2018-07-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       VO-HskXI5iVFwqQxKzxqyc35@stanza.co
:LOCATION: Meet up with some friends at today's Happy Hour game
:STATUS:   CONFIRMED
:END:

Bisons vs. Bulls We'll celebrate the 40th anniversary of the movie Grease!  Come dressed as your favorite T-bird or Pink Lady and make sure you know the Hand Jive!

Our friday night Happy Hour returns featuring $3 beer from Resurgence Brewery!  

Follow on MiLB First Pitch  https //stza.co/+vK0X-2C

Shop  https //stza.co/+vK0X-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Bulls
END:VALARM
DTSTART:20180720T230500Z
DTEND:20180721T020500Z
UID:VO-HskXI5iVFwqQxKzxqyc35@stanza.co
SUMMARY:Bisons vs. Bulls
DESCRIPTION:We'll celebrate the 40th anniversary of the movie Grease!  Come dressed as your favorite T-bird or Pink Lady and make sure you know the Hand Jive!\n\nOur friday night Happy Hour returns featuring $3 beer from Resurgence Brewery!  \n\nFollow on MiLB First Pitch: https://stza.co/+vK0X-2C\n\nShop: https://stza.co/+vK0X-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Meet up with some friends at today's Happy Hour game
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Bulls
<2018-07-21 Sat 17:05-20:05>
:PROPERTIES:
:ID:       EAEP3w3IuOUHmMql0fbr06bJ@stanza.co
:LOCATION: Dino Day
:STATUS:   CONFIRMED
:END:

Bisons vs. Bulls Come and meet Teddy the T-rex and Vinny the Velociraptor from Ravage Productions!  During the game we'll have a fun storyline that picks up where last year's left off on the BisonsTV HD Video Board!

Follow on MiLB First Pitch  https //stza.co/+vK0Y-3n

Shop  https //stza.co/+vK0Y-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Bulls
END:VALARM
DTSTART:20180721T220500Z
DTEND:20180722T010500Z
UID:EAEP3w3IuOUHmMql0fbr06bJ@stanza.co
SUMMARY:Bisons vs. Bulls
DESCRIPTION:Come and meet Teddy the T-rex and Vinny the Velociraptor from Ravage Productions!  During the game we'll have a fun storyline that picks up where last year's left off on the BisonsTV HD Video Board!\n\nFollow on MiLB First Pitch: https://stza.co/+vK0Y-3n\n\nShop: https://stza.co/+vK0Y-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dino Day
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Bulls
<2018-07-22 Sun 12:05-15:05>
:PROPERTIES:
:ID:       ti_cT8p8Cu8PSsBHKhdK4DcE@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Bisons vs. Bulls Stick around after every Sunday game and watch your child run the bases, just like the Bisons do!

Follow on MiLB First Pitch  https //stza.co/+vK0$-2m

Shop  https //stza.co/+vK0$-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Bulls
END:VALARM
DTSTART:20180722T170500Z
DTEND:20180722T200500Z
UID:ti_cT8p8Cu8PSsBHKhdK4DcE@stanza.co
SUMMARY:Bisons vs. Bulls
DESCRIPTION:Stick around after every Sunday game and watch your child run the bases, just like the Bisons do!\n\nFollow on MiLB First Pitch: https://stza.co/+vK0$-2m\n\nShop: https://stza.co/+vK0$-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Bats
<2018-07-24 Tue 18:00-21:00>
:PROPERTIES:
:ID:       dMe2tfPo7HqQ6Tupl7TJkx86@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bisons @ Bats Bisons @ Bats

Buy tickets here  https //stza.co/~vK1Z

Follow on MiLB First Pitch  https //stza.co/+vK1Z-3T

Shop  https //stza.co/+vK1Z-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Bats
END:VALARM
DTSTART:20180724T230000Z
DTEND:20180725T020000Z
UID:dMe2tfPo7HqQ6Tupl7TJkx86@stanza.co
SUMMARY:Bisons @ Bats
DESCRIPTION:Bisons @ Bats\n\nBuy tickets here: https://stza.co/~vK1Z\n\nFollow on MiLB First Pitch: https://stza.co/+vK1Z-3T\n\nShop: https://stza.co/+vK1Z-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Bats
<2018-07-25 Wed 18:00-21:00>
:PROPERTIES:
:ID:       OrLuw5LcuZlq_oqNXQsAAtCG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Bats Bisons @ Bats

Buy tickets here  https //stza.co/~vK1_

Follow on MiLB First Pitch  https //stza.co/+vK1_-1P

Shop  https //stza.co/+vK1_-2S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Bats
END:VALARM
DTSTART:20180725T230000Z
DTEND:20180726T020000Z
UID:OrLuw5LcuZlq_oqNXQsAAtCG@stanza.co
SUMMARY:Bisons @ Bats
DESCRIPTION:Bisons @ Bats\n\nBuy tickets here: https://stza.co/~vK1_\n\nFollow on MiLB First Pitch: https://stza.co/+vK1_-1P\n\nShop: https://stza.co/+vK1_-2S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Bats
<2018-07-26 Thu 18:00-21:00>
:PROPERTIES:
:ID:       I5ndynGzpzEAOpC7Rfx3p2ut@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Bats Bisons @ Bats

Buy tickets here  https //stza.co/~vK1$

Follow on MiLB First Pitch  https //stza.co/+vK1$-3l

Shop  https //stza.co/+vK1$-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Bats
END:VALARM
DTSTART:20180726T230000Z
DTEND:20180727T020000Z
UID:I5ndynGzpzEAOpC7Rfx3p2ut@stanza.co
SUMMARY:Bisons @ Bats
DESCRIPTION:Bisons @ Bats\n\nBuy tickets here: https://stza.co/~vK1$\n\nFollow on MiLB First Pitch: https://stza.co/+vK1$-3l\n\nShop: https://stza.co/+vK1$-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Indians
<2018-07-27 Fri 18:15-21:15>
:PROPERTIES:
:ID:       j3URZdLXm-3b2spAocnJjayc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bisons @ Indians Bisons @ Indians

Follow on MiLB First Pitch  https //stza.co/+vK1L-3m

Shop  https //stza.co/+vK1L-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Indians
END:VALARM
DTSTART:20180727T231500Z
DTEND:20180728T021500Z
UID:j3URZdLXm-3b2spAocnJjayc@stanza.co
SUMMARY:Bisons @ Indians
DESCRIPTION:Bisons @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+vK1L-3m\n\nShop: https://stza.co/+vK1L-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Indians
<2018-07-28 Sat 18:05-21:05>
:PROPERTIES:
:ID:       GIePPTfimY-gZoIlF5Ax0jUp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Indians Bisons @ Indians

Follow on MiLB First Pitch  https //stza.co/+vK1M-26

Shop  https //stza.co/+vK1M-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Indians
END:VALARM
DTSTART:20180728T230500Z
DTEND:20180729T020500Z
UID:GIePPTfimY-gZoIlF5Ax0jUp@stanza.co
SUMMARY:Bisons @ Indians
DESCRIPTION:Bisons @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+vK1M-26\n\nShop: https://stza.co/+vK1M-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Indians
<2018-07-29 Sun 12:35-15:35>
:PROPERTIES:
:ID:       2O7RM2q5c6_sBEj-dkKQIsik@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Indians Bisons @ Indians

Follow on MiLB First Pitch  https //stza.co/+vK1N-O

Shop  https //stza.co/+vK1N-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Indians
END:VALARM
DTSTART:20180729T173500Z
DTEND:20180729T203500Z
UID:2O7RM2q5c6_sBEj-dkKQIsik@stanza.co
SUMMARY:Bisons @ Indians
DESCRIPTION:Bisons @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+vK1N-O\n\nShop: https://stza.co/+vK1N-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. IronPigs
<2018-07-30 Mon 18:05-21:05>
:PROPERTIES:
:ID:       F1KAehbhk4VemrFACCW5g6yW@stanza.co
:LOCATION: Come out for our Mardown Monday game!
:STATUS:   CONFIRMED
:END:

Bisons vs. IronPigs Discounted tickets along with $1 ice-cream and $1 popcorn at the concession stands!

Follow on MiLB First Pitch  https //stza.co/+vK10-p

Shop  https //stza.co/+vK10-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. IronPigs
END:VALARM
DTSTART:20180730T230500Z
DTEND:20180731T020500Z
UID:F1KAehbhk4VemrFACCW5g6yW@stanza.co
SUMMARY:Bisons vs. IronPigs
DESCRIPTION:Discounted tickets along with $1 ice-cream and $1 popcorn at the concession stands!\n\nFollow on MiLB First Pitch: https://stza.co/+vK10-p\n\nShop: https://stza.co/+vK10-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Come out for our Mardown Monday game!
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. IronPigs
<2018-07-31 Tue 18:05-21:05>
:PROPERTIES:
:ID:       J107yXWbG8warMApHWX8O25p@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bisons vs. IronPigs Bisons vs. IronPigs

Follow on MiLB First Pitch  https //stza.co/+vK12-16

Shop  https //stza.co/+vK12-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. IronPigs
END:VALARM
DTSTART:20180731T230500Z
DTEND:20180801T020500Z
UID:J107yXWbG8warMApHWX8O25p@stanza.co
SUMMARY:Bisons vs. IronPigs
DESCRIPTION:Bisons vs. IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vK12-16\n\nShop: https://stza.co/+vK12-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. IronPigs
<2018-08-01 Wed 18:05-21:05>
:PROPERTIES:
:ID:       7F6KgxJo2Hn109P95cBQD3f0@stanza.co
:LOCATION: Buster Wall Sticker Giveaway
:STATUS:   CONFIRMED
:END:

Bisons vs. IronPigs The first 2,000 fans through the Inspire Dental gate at Swan will receive a life sized Buster Bison Wall Sticker!  Gates open at 6pm.

Follow on MiLB First Pitch  https //stza.co/+vK14-g

Shop  https //stza.co/+vK14-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. IronPigs
END:VALARM
DTSTART:20180801T230500Z
DTEND:20180802T020500Z
UID:7F6KgxJo2Hn109P95cBQD3f0@stanza.co
SUMMARY:Bisons vs. IronPigs
DESCRIPTION:The first 2,000 fans through the Inspire Dental gate at Swan will receive a life sized Buster Bison Wall Sticker!  Gates open at 6pm.\n\nFollow on MiLB First Pitch: https://stza.co/+vK14-g\n\nShop: https://stza.co/+vK14-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Buster Wall Sticker Giveaway
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. IronPigs
<2018-08-02 Thu 12:05-15:05>
:PROPERTIES:
:ID:       CkhehRhi4NSydmAXBSrhJTfv@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons vs. IronPigs Bisons vs. IronPigs

Follow on MiLB First Pitch  https //stza.co/+vK16-Z

Shop  https //stza.co/+vK16-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. IronPigs
END:VALARM
DTSTART:20180802T170500Z
DTEND:20180802T200500Z
UID:CkhehRhi4NSydmAXBSrhJTfv@stanza.co
SUMMARY:Bisons vs. IronPigs
DESCRIPTION:Bisons vs. IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vK16-Z\n\nShop: https://stza.co/+vK16-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ RailRiders
<2018-08-03 Fri 18:05-21:05>
:PROPERTIES:
:ID:       cGP6YN3AUFC2EUld3H2YxF8x@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ RailRiders Bisons @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vK2r-3e

Shop  https //stza.co/+vK2r-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ RailRiders
END:VALARM
DTSTART:20180803T230500Z
DTEND:20180804T020500Z
UID:cGP6YN3AUFC2EUld3H2YxF8x@stanza.co
SUMMARY:Bisons @ RailRiders
DESCRIPTION:Bisons @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vK2r-3e\n\nShop: https://stza.co/+vK2r-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ RailRiders
<2018-08-04 Sat 17:35-20:35>
:PROPERTIES:
:ID:       Biaz30COi7Ew56UmcJcB0nE3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bisons @ RailRiders Bisons @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vK2s-2k

Shop  https //stza.co/+vK2s-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ RailRiders
END:VALARM
DTSTART:20180804T223500Z
DTEND:20180805T013500Z
UID:Biaz30COi7Ew56UmcJcB0nE3@stanza.co
SUMMARY:Bisons @ RailRiders
DESCRIPTION:Bisons @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vK2s-2k\n\nShop: https://stza.co/+vK2s-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ RailRiders
<2018-08-05 Sun 12:05-15:05>
:PROPERTIES:
:ID:       0xk-ZUCQhmcCNqXCttwl-ZAz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ RailRiders Bisons @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vK2t-2G

Shop  https //stza.co/+vK2t-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ RailRiders
END:VALARM
DTSTART:20180805T170500Z
DTEND:20180805T200500Z
UID:0xk-ZUCQhmcCNqXCttwl-ZAz@stanza.co
SUMMARY:Bisons @ RailRiders
DESCRIPTION:Bisons @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vK2t-2G\n\nShop: https://stza.co/+vK2t-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Stripers
<2018-08-07 Tue 18:05-21:05>
:PROPERTIES:
:ID:       _f-rv2PCtGWHz5I_OpNp-DVq@stanza.co
:LOCATION: Polish Festival Night
:STATUS:   CONFIRMED
:END:

Bisons vs. Stripers We'll celebrate Polish heritage with a pre-game tent party featuring Polish cuisine.  Prior to the game we'll also honor the Polish American of the year, and after the game will be an awesome fireworks show to cap off the evening.

Follow on MiLB First Pitch  https //stza.co/+vK18-3i

Shop  https //stza.co/+vK18-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Stripers
END:VALARM
DTSTART:20180807T230500Z
DTEND:20180808T020500Z
UID:_f-rv2PCtGWHz5I_OpNp-DVq@stanza.co
SUMMARY:Bisons vs. Stripers
DESCRIPTION:We'll celebrate Polish heritage with a pre-game tent party featuring Polish cuisine.  Prior to the game we'll also honor the Polish American of the year, and after the game will be an awesome fireworks show to cap off the evening.\n\nFollow on MiLB First Pitch: https://stza.co/+vK18-3i\n\nShop: https://stza.co/+vK18-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Polish Festival Night
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Stripers
<2018-08-08 Wed 18:05-21:05>
:PROPERTIES:
:ID:       RtjWXs92EwuvbWOkX0KP4v-d@stanza.co
:LOCATION: National Dollar Day
:STATUS:   CONFIRMED
:END:

Bisons vs. Stripers Details to be announced.

Follow on MiLB First Pitch  https //stza.co/+vK1b-3o

Shop  https //stza.co/+vK1b-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Stripers
END:VALARM
DTSTART:20180808T230500Z
DTEND:20180809T020500Z
UID:RtjWXs92EwuvbWOkX0KP4v-d@stanza.co
SUMMARY:Bisons vs. Stripers
DESCRIPTION:Details to be announced.\n\nFollow on MiLB First Pitch: https://stza.co/+vK1b-3o\n\nShop: https://stza.co/+vK1b-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:National Dollar Day
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Stripers
<2018-08-09 Thu 18:05-21:05>
:PROPERTIES:
:ID:       5hoiwzlSClx4EwTzD0H6ORWf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons vs. Stripers Bisons vs. Stripers

Follow on MiLB First Pitch  https //stza.co/+vK1d-3

Shop  https //stza.co/+vK1d-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Stripers
END:VALARM
DTSTART:20180809T230500Z
DTEND:20180810T020500Z
UID:5hoiwzlSClx4EwTzD0H6ORWf@stanza.co
SUMMARY:Bisons vs. Stripers
DESCRIPTION:Bisons vs. Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+vK1d-3\n\nShop: https://stza.co/+vK1d-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Mud Hens
<2018-08-10 Fri 18:05-21:05>
:PROPERTIES:
:ID:       rNs2dNgH5F3l3wIKEvPdWT25@stanza.co
:LOCATION: Meet up with some friends at today's Happy Hour game
:STATUS:   CONFIRMED
:END:

Bisons vs. Mud Hens After the game you can spend the night on the field under the stars with our annual Family Campout.  We'll have a movie on the Video Board with snacks available throughout, and breakfast the next morning.

Our friday night Happy Hour returns featuring $3 beer from Resurgence Brewery!  

Follow on MiLB First Pitch  https //stza.co/+vK1f-G

Shop  https //stza.co/+vK1f-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Mud Hens
END:VALARM
DTSTART:20180810T230500Z
DTEND:20180811T020500Z
UID:rNs2dNgH5F3l3wIKEvPdWT25@stanza.co
SUMMARY:Bisons vs. Mud Hens
DESCRIPTION:After the game you can spend the night on the field under the stars with our annual Family Campout.  We'll have a movie on the Video Board with snacks available throughout, and breakfast the next morning.\n\nOur friday night Happy Hour returns featuring $3 beer from Resurgence Brewery!  \n\nFollow on MiLB First Pitch: https://stza.co/+vK1f-G\n\nShop: https://stza.co/+vK1f-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Meet up with some friends at today's Happy Hour game
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Mud Hens
<2018-08-11 Sat 17:05-20:05>
:PROPERTIES:
:ID:       A1vzdzSoBvkJ4z0HyaiYS1Kb@stanza.co
:LOCATION: Superhero Night
:STATUS:   CONFIRMED
:END:

Bisons vs. Mud Hens Come dressed as your favorite Super Hero, and take advantage of the opportunity to meet your favorite characters!  During the game we'll have a great storyline on the Video Board that'll be capped off after the game in an on-field battle in your classic good guys vs bad guys matchup.  Of course, there will also be an awesome fireworks show!

Follow on MiLB First Pitch  https //stza.co/+vK1h-3u

Shop  https //stza.co/+vK1h-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Mud Hens
END:VALARM
DTSTART:20180811T220500Z
DTEND:20180812T010500Z
UID:A1vzdzSoBvkJ4z0HyaiYS1Kb@stanza.co
SUMMARY:Bisons vs. Mud Hens
DESCRIPTION:Come dressed as your favorite Super Hero, and take advantage of the opportunity to meet your favorite characters!  During the game we'll have a great storyline on the Video Board that'll be capped off after the game in an on-field battle in your classic good guys vs bad guys matchup.  Of course, there will also be an awesome fireworks show!\n\nFollow on MiLB First Pitch: https://stza.co/+vK1h-3u\n\nShop: https://stza.co/+vK1h-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Superhero Night
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Mud Hens
<2018-08-12 Sun 12:05-15:05>
:PROPERTIES:
:ID:       A-k5Nkdh1VwH53yZyqjRiPDW@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Bisons vs. Mud Hens Come see the hilarious ZOOperstars!, featuring characters such as Nolan Rhino, Roger Clamens, Harry Canary and many more for a show you will never forget!

The first 1,000 fans through the gates will receive a Bisons Activity Book featuring puzzles, coloring sheets, and more!

Stick around after every Sunday game and watch your child run the bases, just like the Bisons do!

Follow on MiLB First Pitch  https //stza.co/+vK1i-1e

Shop  https //stza.co/+vK1i-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Mud Hens
END:VALARM
DTSTART:20180812T170500Z
DTEND:20180812T200500Z
UID:A-k5Nkdh1VwH53yZyqjRiPDW@stanza.co
SUMMARY:Bisons vs. Mud Hens
DESCRIPTION:Come see the hilarious ZOOperstars!, featuring characters such as Nolan Rhino, Roger Clamens, Harry Canary and many more for a show you will never forget!\n\nThe first 1,000 fans through the gates will receive a Bisons Activity Book featuring puzzles, coloring sheets, and more!\n\nStick around after every Sunday game and watch your child run the bases, just like the Bisons do!\n\nFollow on MiLB First Pitch: https://stza.co/+vK1i-1e\n\nShop: https://stza.co/+vK1i-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Knights
<2018-08-13 Mon 18:04-21:04>
:PROPERTIES:
:ID:       fm3EMs_akyfwvrENqUXCqYWd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bisons @ Knights Bisons @ Knights

Follow on MiLB First Pitch  https //stza.co/+xOKF-1D

Shop  https //stza.co/+xOKF-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Knights
END:VALARM
DTSTART:20180813T230400Z
DTEND:20180814T020400Z
UID:fm3EMs_akyfwvrENqUXCqYWd@stanza.co
SUMMARY:Bisons @ Knights
DESCRIPTION:Bisons @ Knights\n\nFollow on MiLB First Pitch: https://stza.co/+xOKF-1D\n\nShop: https://stza.co/+xOKF-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Knights
<2018-08-14 Tue 18:04-21:04>
:PROPERTIES:
:ID:       dEFJ2CMdgZhlOQCxcKwgqZST@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Knights Bisons @ Knights

Follow on MiLB First Pitch  https //stza.co/+xOKG-2r

Shop  https //stza.co/+xOKG-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Knights
END:VALARM
DTSTART:20180814T230400Z
DTEND:20180815T020400Z
UID:dEFJ2CMdgZhlOQCxcKwgqZST@stanza.co
SUMMARY:Bisons @ Knights
DESCRIPTION:Bisons @ Knights\n\nFollow on MiLB First Pitch: https://stza.co/+xOKG-2r\n\nShop: https://stza.co/+xOKG-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Knights
<2018-08-15 Wed 18:04-21:04>
:PROPERTIES:
:ID:       YuThihwogIvSTb4kbAYyEehM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Knights Bisons @ Knights

Follow on MiLB First Pitch  https //stza.co/+xOKH-2m

Shop  https //stza.co/+xOKH-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Knights
END:VALARM
DTSTART:20180815T230400Z
DTEND:20180816T020400Z
UID:YuThihwogIvSTb4kbAYyEehM@stanza.co
SUMMARY:Bisons @ Knights
DESCRIPTION:Bisons @ Knights\n\nFollow on MiLB First Pitch: https://stza.co/+xOKH-2m\n\nShop: https://stza.co/+xOKH-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Stripers
<2018-08-16 Thu 18:05-21:05>
:PROPERTIES:
:ID:       1rqGDVRV9wvwtmMGxV4v5zUx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bisons @ Stripers Bisons @ Stripers

Follow on MiLB First Pitch  https //stza.co/+vK1H-3d

Shop  https //stza.co/+vK1H-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Stripers
END:VALARM
DTSTART:20180816T230500Z
DTEND:20180817T020500Z
UID:1rqGDVRV9wvwtmMGxV4v5zUx@stanza.co
SUMMARY:Bisons @ Stripers
DESCRIPTION:Bisons @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+vK1H-3d\n\nShop: https://stza.co/+vK1H-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Stripers
<2018-08-17 Fri 18:05-21:05>
:PROPERTIES:
:ID:       Umw352qIjppREiRe8KNwd0k-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Stripers Bisons @ Stripers

Follow on MiLB First Pitch  https //stza.co/+vK1I-3s

Shop  https //stza.co/+vK1I-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Stripers
END:VALARM
DTSTART:20180817T230500Z
DTEND:20180818T020500Z
UID:Umw352qIjppREiRe8KNwd0k-@stanza.co
SUMMARY:Bisons @ Stripers
DESCRIPTION:Bisons @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+vK1I-3s\n\nShop: https://stza.co/+vK1I-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Stripers
<2018-08-18 Sat 17:05-20:05>
:PROPERTIES:
:ID:       G1Wh1wXg8MdJNTcuiGHXgN-d@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Stripers Bisons @ Stripers

Follow on MiLB First Pitch  https //stza.co/+vK1J-3P

Shop  https //stza.co/+vK1J-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Stripers
END:VALARM
DTSTART:20180818T220500Z
DTEND:20180819T010500Z
UID:G1Wh1wXg8MdJNTcuiGHXgN-d@stanza.co
SUMMARY:Bisons @ Stripers
DESCRIPTION:Bisons @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+vK1J-3P\n\nShop: https://stza.co/+vK1J-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Stripers
<2018-08-19 Sun 12:05-15:05>
:PROPERTIES:
:ID:       IIMduyQTVgZ7ZgPcmID-ffQP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bisons @ Stripers Bisons @ Stripers

Follow on MiLB First Pitch  https //stza.co/+vK1K-1s

Shop  https //stza.co/+vK1K-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Stripers
END:VALARM
DTSTART:20180819T170500Z
DTEND:20180819T200500Z
UID:IIMduyQTVgZ7ZgPcmID-ffQP@stanza.co
SUMMARY:Bisons @ Stripers
DESCRIPTION:Bisons @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+vK1K-1s\n\nShop: https://stza.co/+vK1K-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. RailRiders
<2018-08-21 Tue 18:05-21:05>
:PROPERTIES:
:ID:       kiySd4XsNaO-ZrsOO8dgSoDJ@stanza.co
:LOCATION: Dog Day
:STATUS:   CONFIRMED
:END:

Bisons vs. RailRiders Come and enjoy the game with man's best friend!

Follow on MiLB First Pitch  https //stza.co/+vK1l-2a

Shop  https //stza.co/+vK1l-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. RailRiders
END:VALARM
DTSTART:20180821T230500Z
DTEND:20180822T020500Z
UID:kiySd4XsNaO-ZrsOO8dgSoDJ@stanza.co
SUMMARY:Bisons vs. RailRiders
DESCRIPTION:Come and enjoy the game with man's best friend!\n\nFollow on MiLB First Pitch: https://stza.co/+vK1l-2a\n\nShop: https://stza.co/+vK1l-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dog Day
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. RailRiders
<2018-08-22 Wed 18:05-21:05>
:PROPERTIES:
:ID:       n6nHvA6RbwgCA6YaGV_sUOjO@stanza.co
:LOCATION: Mystery Ball Night
:STATUS:   CONFIRMED
:END:

Bisons vs. RailRiders It's the 11th year of this annual event as we'll collect 500 autographed baseballs from a variety of current and former players.  At 6pm fans with a game ticket can enter the Oak St. gate and have the opportunity to purchase one mystery ball ticket for $20 to benefit a local charity.

Follow on MiLB First Pitch  https //stza.co/+vK1n-1O

Shop  https //stza.co/+vK1n-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. RailRiders
END:VALARM
DTSTART:20180822T230500Z
DTEND:20180823T020500Z
UID:n6nHvA6RbwgCA6YaGV_sUOjO@stanza.co
SUMMARY:Bisons vs. RailRiders
DESCRIPTION:It's the 11th year of this annual event as we'll collect 500 autographed baseballs from a variety of current and former players.  At 6pm fans with a game ticket can enter the Oak St. gate and have the opportunity to purchase one mystery ball ticket for $20 to benefit a local charity.\n\nFollow on MiLB First Pitch: https://stza.co/+vK1n-1O\n\nShop: https://stza.co/+vK1n-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Mystery Ball Night
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. RailRiders
<2018-08-23 Thu 12:05-15:05>
:PROPERTIES:
:ID:       RfoL6_cZ8YzjqBcdZYkh9mkr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons vs. RailRiders Bisons vs. RailRiders

Follow on MiLB First Pitch  https //stza.co/+vK1o-12

Shop  https //stza.co/+vK1o-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. RailRiders
END:VALARM
DTSTART:20180823T170500Z
DTEND:20180823T200500Z
UID:RfoL6_cZ8YzjqBcdZYkh9mkr@stanza.co
SUMMARY:Bisons vs. RailRiders
DESCRIPTION:Bisons vs. RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vK1o-12\n\nShop: https://stza.co/+vK1o-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Red Sox
<2018-08-24 Fri 18:05-21:05>
:PROPERTIES:
:ID:       -OX0UpCGX_Mbzj8DfP5p8n_B@stanza.co
:LOCATION: Meet up with some friends at today's Happy Hour game
:STATUS:   CONFIRMED
:END:

Bisons vs. Red Sox Our friday night Happy Hour returns featuring $3 beer from Resurgence Brewery!  



Follow on MiLB First Pitch  https //stza.co/+vK1q-i

Shop  https //stza.co/+vK1q-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Red Sox
END:VALARM
DTSTART:20180824T230500Z
DTEND:20180825T020500Z
UID:-OX0UpCGX_Mbzj8DfP5p8n_B@stanza.co
SUMMARY:Bisons vs. Red Sox
DESCRIPTION:Our friday night Happy Hour returns featuring $3 beer from Resurgence Brewery!  \n\n\n\nFollow on MiLB First Pitch: https://stza.co/+vK1q-i\n\nShop: https://stza.co/+vK1q-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Meet up with some friends at today's Happy Hour game
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Red Sox
<2018-08-25 Sat 17:05-20:05>
:PROPERTIES:
:ID:       N1GBMgdNnolnEkcWsYCb_9fq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons vs. Red Sox Bisons vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+vK1s-3b

Shop  https //stza.co/+vK1s-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Red Sox
END:VALARM
DTSTART:20180825T220500Z
DTEND:20180826T010500Z
UID:N1GBMgdNnolnEkcWsYCb_9fq@stanza.co
SUMMARY:Bisons vs. Red Sox
DESCRIPTION:Bisons vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+vK1s-3b\n\nShop: https://stza.co/+vK1s-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Red Sox
<2018-08-26 Sun 12:05-15:05>
:PROPERTIES:
:ID:       SGg940KJ24ic1wDAdkRfljoO@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Bisons vs. Red Sox Details to be announced.

Stick around after every Sunday game and watch your child run the bases, just like the Bisons do!

Follow on MiLB First Pitch  https //stza.co/+vK1v-10

Shop  https //stza.co/+vK1v-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Red Sox
END:VALARM
DTSTART:20180826T170500Z
DTEND:20180826T200500Z
UID:SGg940KJ24ic1wDAdkRfljoO@stanza.co
SUMMARY:Bisons vs. Red Sox
DESCRIPTION:Details to be announced.\n\nStick around after every Sunday game and watch your child run the bases, just like the Bisons do!\n\nFollow on MiLB First Pitch: https://stza.co/+vK1v-10\n\nShop: https://stza.co/+vK1v-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons vs. Red Sox
<2018-08-27 Mon 18:05-21:05>
:PROPERTIES:
:ID:       BXhYJjq2_pKldgqjkAu4cXcL@stanza.co
:LOCATION: Come out for our Mardown Monday game!
:STATUS:   CONFIRMED
:END:

Bisons vs. Red Sox Discounted tickets along with $1 ice-cream and $1 popcorn at the concession stands!

Giveaways throughout the game and one of the largest fireworks shows of the season!  More details to be announced.

Follow on MiLB First Pitch  https //stza.co/+vK1x-A

Shop  https //stza.co/+vK1x-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bisons vs. Red Sox
END:VALARM
DTSTART:20180827T230500Z
DTEND:20180828T020500Z
UID:BXhYJjq2_pKldgqjkAu4cXcL@stanza.co
SUMMARY:Bisons vs. Red Sox
DESCRIPTION:Discounted tickets along with $1 ice-cream and $1 popcorn at the concession stands!\n\nGiveaways throughout the game and one of the largest fireworks shows of the season!  More details to be announced.\n\nFollow on MiLB First Pitch: https://stza.co/+vK1x-A\n\nShop: https://stza.co/+vK1x-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Come out for our Mardown Monday game!
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Red Wings
<2018-08-28 Tue 18:05-21:05>
:PROPERTIES:
:ID:       pFNxEVQZjG6N78A66FEm96LM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bisons @ Red Wings Bisons @ Red Wings

Follow on MiLB First Pitch  https //stza.co/+vK2j-24

Shop  https //stza.co/+vK2j-1w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Red Wings
END:VALARM
DTSTART:20180828T230500Z
DTEND:20180829T020500Z
UID:pFNxEVQZjG6N78A66FEm96LM@stanza.co
SUMMARY:Bisons @ Red Wings
DESCRIPTION:Bisons @ Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vK2j-24\n\nShop: https://stza.co/+vK2j-1w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Red Wings
<2018-08-29 Wed 18:05-21:05>
:PROPERTIES:
:ID:       I4tk56-Yi92Y2TwHuCuwq8Yl@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Red Wings Bisons @ Red Wings

Follow on MiLB First Pitch  https //stza.co/+vK2k-2j

Shop  https //stza.co/+vK2k-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Red Wings
END:VALARM
DTSTART:20180829T230500Z
DTEND:20180830T020500Z
UID:I4tk56-Yi92Y2TwHuCuwq8Yl@stanza.co
SUMMARY:Bisons @ Red Wings
DESCRIPTION:Bisons @ Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vK2k-2j\n\nShop: https://stza.co/+vK2k-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Red Wings
<2018-08-30 Thu 18:05-21:05>
:PROPERTIES:
:ID:       HMebjlllLxfWfuCYUmgV3IL-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Red Wings Bisons @ Red Wings

Follow on MiLB First Pitch  https //stza.co/+vK2l-2S

Shop  https //stza.co/+vK2l-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Red Wings
END:VALARM
DTSTART:20180830T230500Z
DTEND:20180831T020500Z
UID:HMebjlllLxfWfuCYUmgV3IL-@stanza.co
SUMMARY:Bisons @ Red Wings
DESCRIPTION:Bisons @ Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vK2l-2S\n\nShop: https://stza.co/+vK2l-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Chiefs
<2018-08-31 Fri 18:05-21:05>
:PROPERTIES:
:ID:       lW1gD2vKyL-5z9DXP0awJgrb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bisons @ Chiefs Bisons @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+vK2x-16

Shop  https //stza.co/+vK2x-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Chiefs
END:VALARM
DTSTART:20180831T230500Z
DTEND:20180901T020500Z
UID:lW1gD2vKyL-5z9DXP0awJgrb@stanza.co
SUMMARY:Bisons @ Chiefs
DESCRIPTION:Bisons @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+vK2x-16\n\nShop: https://stza.co/+vK2x-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Chiefs
<2018-09-01 Sat 18:05-21:05>
:PROPERTIES:
:ID:       6jyWlCboC_oji5EHjYrQWrq7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Chiefs Bisons @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+vK2y-1N

Shop  https //stza.co/+vK2y-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Chiefs
END:VALARM
DTSTART:20180901T230500Z
DTEND:20180902T020500Z
UID:6jyWlCboC_oji5EHjYrQWrq7@stanza.co
SUMMARY:Bisons @ Chiefs
DESCRIPTION:Bisons @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+vK2y-1N\n\nShop: https://stza.co/+vK2y-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Chiefs
<2018-09-02 Sun 18:05-21:05>
:PROPERTIES:
:ID:       cgKxmGA9fQtO2EorkPl6rziv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bisons @ Chiefs Bisons @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+vK2z-1k

Shop  https //stza.co/+vK2z-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Chiefs
END:VALARM
DTSTART:20180902T230500Z
DTEND:20180903T020500Z
UID:cgKxmGA9fQtO2EorkPl6rziv@stanza.co
SUMMARY:Bisons @ Chiefs
DESCRIPTION:Bisons @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+vK2z-1k\n\nShop: https://stza.co/+vK2z-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Bisons @ Chiefs
<2018-09-03 Mon 12:05-15:05>
:PROPERTIES:
:ID:       xhZuiuM2XtoYv5sgMDNCQgPm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bisons @ Chiefs Bisons @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+vK2A-2o

Shop  https //stza.co/+vK2A-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bisons @ Chiefs
END:VALARM
DTSTART:20180903T170500Z
DTEND:20180903T200500Z
UID:xhZuiuM2XtoYv5sgMDNCQgPm@stanza.co
SUMMARY:Bisons @ Chiefs
DESCRIPTION:Bisons @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+vK2A-2o\n\nShop: https://stza.co/+vK2A-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
