#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Blue Rocks @ Nationals
<2018-04-05 Thu 18:05-21:05>
:PROPERTIES:
:ID:       2jPX9Fitf-kVXCysafSq0sr3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Nationals Blue Rocks @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xA8k-1N

Shop  https //stza.co/+xA8k-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Nationals
END:VALARM
DTSTART:20180405T230500Z
DTEND:20180406T020500Z
UID:2jPX9Fitf-kVXCysafSq0sr3@stanza.co
SUMMARY:Blue Rocks @ Nationals
DESCRIPTION:Blue Rocks @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xA8k-1N\n\nShop: https://stza.co/+xA8k-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Nationals
<2018-04-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       1zThzbwlLVpKARKSGXjAfaEg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Nationals Blue Rocks @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xA8l-H

Shop  https //stza.co/+xA8l-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Nationals
END:VALARM
DTSTART:20180406T230500Z
DTEND:20180407T020500Z
UID:1zThzbwlLVpKARKSGXjAfaEg@stanza.co
SUMMARY:Blue Rocks @ Nationals
DESCRIPTION:Blue Rocks @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xA8l-H\n\nShop: https://stza.co/+xA8l-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Nationals
<2018-04-07 Sat 17:35-20:35>
:PROPERTIES:
:ID:       WY037PFCPp_IgcJpu2yEg-Rr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Nationals Blue Rocks @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xA8m-i

Shop  https //stza.co/+xA8m-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Nationals
END:VALARM
DTSTART:20180407T223500Z
DTEND:20180408T013500Z
UID:WY037PFCPp_IgcJpu2yEg-Rr@stanza.co
SUMMARY:Blue Rocks @ Nationals
DESCRIPTION:Blue Rocks @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xA8m-i\n\nShop: https://stza.co/+xA8m-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Nationals
<2018-04-08 Sun 12:05-15:05>
:PROPERTIES:
:ID:       mFYChqavpeScKjO1NR1TGl8C@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Nationals Blue Rocks @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xA8n-3D

Shop  https //stza.co/+xA8n-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Nationals
END:VALARM
DTSTART:20180408T170500Z
DTEND:20180408T200500Z
UID:mFYChqavpeScKjO1NR1TGl8C@stanza.co
SUMMARY:Blue Rocks @ Nationals
DESCRIPTION:Blue Rocks @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xA8n-3D\n\nShop: https://stza.co/+xA8n-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Red Sox
<2018-04-09 Mon>--<2018-04-08 Sun>
:PROPERTIES:
:ID:       axrjku5xomk_OJPDkQw-8FGP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Red Sox Blue Rocks @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0H_-M

Shop  https //stza.co/+w0H_-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180409
DTEND;VALUE=DATE:20180409
UID:axrjku5xomk_OJPDkQw-8FGP@stanza.co
SUMMARY:Blue Rocks @ Red Sox
DESCRIPTION:Blue Rocks @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0H_-M\n\nShop: https://stza.co/+w0H_-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Red Sox
<2018-04-10 Tue>--<2018-04-09 Mon>
:PROPERTIES:
:ID:       QQjITE6QnHdk4DVQrASA4_3x@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Red Sox Blue Rocks @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0H$-3P

Shop  https //stza.co/+w0H$-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180410
DTEND;VALUE=DATE:20180410
UID:QQjITE6QnHdk4DVQrASA4_3x@stanza.co
SUMMARY:Blue Rocks @ Red Sox
DESCRIPTION:Blue Rocks @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0H$-3P\n\nShop: https://stza.co/+w0H$-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Red Sox
<2018-04-11 Wed>--<2018-04-10 Tue>
:PROPERTIES:
:ID:       uIuTusdX1rg9Ri7XA28SubM7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Red Sox Blue Rocks @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0I0-3Z

Shop  https //stza.co/+w0I0-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180411
DTEND;VALUE=DATE:20180411
UID:uIuTusdX1rg9Ri7XA28SubM7@stanza.co
SUMMARY:Blue Rocks @ Red Sox
DESCRIPTION:Blue Rocks @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0I0-3Z\n\nShop: https://stza.co/+w0I0-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Hillcats
<2018-04-12 Thu 17:35-20:35>
:PROPERTIES:
:ID:       GzPUqKTl3jINuG0iVfAdw7Qe@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Hillcats Blue Rocks vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+wXab-3Y

Shop  https //stza.co/+wXab-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Hillcats
END:VALARM
DTSTART:20180412T223500Z
DTEND:20180413T013500Z
UID:GzPUqKTl3jINuG0iVfAdw7Qe@stanza.co
SUMMARY:Blue Rocks vs. Hillcats
DESCRIPTION:Blue Rocks vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+wXab-3Y\n\nShop: https://stza.co/+wXab-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Hillcats
<2018-04-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       HfXZbroEPnwsmisk7hT6nMXJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Hillcats Blue Rocks vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+wXad-1a

Shop  https //stza.co/+wXad-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Hillcats
END:VALARM
DTSTART:20180413T230500Z
DTEND:20180414T020500Z
UID:HfXZbroEPnwsmisk7hT6nMXJ@stanza.co
SUMMARY:Blue Rocks vs. Hillcats
DESCRIPTION:Blue Rocks vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+wXad-1a\n\nShop: https://stza.co/+wXad-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Hillcats
<2018-04-14 Sat 17:05-20:05>
:PROPERTIES:
:ID:       Ck1pvzhDiyDjt8Hunw54gp6-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Hillcats Blue Rocks vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+wXag-3K

Shop  https //stza.co/+wXag-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Hillcats
END:VALARM
DTSTART:20180414T220500Z
DTEND:20180415T010500Z
UID:Ck1pvzhDiyDjt8Hunw54gp6-@stanza.co
SUMMARY:Blue Rocks vs. Hillcats
DESCRIPTION:Blue Rocks vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+wXag-3K\n\nShop: https://stza.co/+wXag-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Hillcats
<2018-04-15 Sun 12:35-15:35>
:PROPERTIES:
:ID:       x0l4X7mOE74ddkyc4d6yBqol@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Hillcats Blue Rocks vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+wXak-2y

Shop  https //stza.co/+wXak-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Hillcats
END:VALARM
DTSTART:20180415T173500Z
DTEND:20180415T203500Z
UID:x0l4X7mOE74ddkyc4d6yBqol@stanza.co
SUMMARY:Blue Rocks vs. Hillcats
DESCRIPTION:Blue Rocks vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+wXak-2y\n\nShop: https://stza.co/+wXak-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Mudcats
<2018-04-16 Mon 17:35-20:35>
:PROPERTIES:
:ID:       kQTx8-IbpzXJ8S2lTi3gWh8U@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Mudcats Blue Rocks vs. Mudcats

Follow on MiLB First Pitch  https //stza.co/+wXan-23

Shop  https //stza.co/+wXan-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Mudcats
END:VALARM
DTSTART:20180416T223500Z
DTEND:20180417T013500Z
UID:kQTx8-IbpzXJ8S2lTi3gWh8U@stanza.co
SUMMARY:Blue Rocks vs. Mudcats
DESCRIPTION:Blue Rocks vs. Mudcats\n\nFollow on MiLB First Pitch: https://stza.co/+wXan-23\n\nShop: https://stza.co/+wXan-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Mudcats
<2018-04-17 Tue 17:35-20:35>
:PROPERTIES:
:ID:       TK0v6b43Rx91sp19aoeh8nJl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Mudcats Blue Rocks vs. Mudcats

Follow on MiLB First Pitch  https //stza.co/+wXap-3S

Shop  https //stza.co/+wXap-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Mudcats
END:VALARM
DTSTART:20180417T223500Z
DTEND:20180418T013500Z
UID:TK0v6b43Rx91sp19aoeh8nJl@stanza.co
SUMMARY:Blue Rocks vs. Mudcats
DESCRIPTION:Blue Rocks vs. Mudcats\n\nFollow on MiLB First Pitch: https://stza.co/+wXap-3S\n\nShop: https://stza.co/+wXap-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Mudcats
<2018-04-18 Wed 09:35-12:35>
:PROPERTIES:
:ID:       jLlOhA-3hwbCskvE9cUpytCS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Mudcats Blue Rocks vs. Mudcats

Follow on MiLB First Pitch  https //stza.co/+wXar-1R

Shop  https //stza.co/+wXar-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Mudcats
END:VALARM
DTSTART:20180418T143500Z
DTEND:20180418T173500Z
UID:jLlOhA-3hwbCskvE9cUpytCS@stanza.co
SUMMARY:Blue Rocks vs. Mudcats
DESCRIPTION:Blue Rocks vs. Mudcats\n\nFollow on MiLB First Pitch: https://stza.co/+wXar-1R\n\nShop: https://stza.co/+wXar-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Keys
<2018-04-19 Thu 18:00-21:00>
:PROPERTIES:
:ID:       fr4j_JlOm7r0S7HERgB9uv7r@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Keys Blue Rocks @ Keys

Follow on MiLB First Pitch  https //stza.co/+wibt-F

Shop  https //stza.co/+wibt-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Keys
END:VALARM
DTSTART:20180419T230000Z
DTEND:20180420T020000Z
UID:fr4j_JlOm7r0S7HERgB9uv7r@stanza.co
SUMMARY:Blue Rocks @ Keys
DESCRIPTION:Blue Rocks @ Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wibt-F\n\nShop: https://stza.co/+wibt-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Keys
<2018-04-20 Fri 18:00-21:00>
:PROPERTIES:
:ID:       2jo7sadV69kE3pwY3mOfLS3w@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Keys Blue Rocks @ Keys

Follow on MiLB First Pitch  https //stza.co/+wibu-3j

Shop  https //stza.co/+wibu-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Keys
END:VALARM
DTSTART:20180420T230000Z
DTEND:20180421T020000Z
UID:2jo7sadV69kE3pwY3mOfLS3w@stanza.co
SUMMARY:Blue Rocks @ Keys
DESCRIPTION:Blue Rocks @ Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wibu-3j\n\nShop: https://stza.co/+wibu-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Keys
<2018-04-21 Sat 13:00-16:00>
:PROPERTIES:
:ID:       ZnrpdKBPigq8eoFPXgeYZvOY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Keys Blue Rocks @ Keys

Follow on MiLB First Pitch  https //stza.co/+wibv-U

Shop  https //stza.co/+wibv-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Keys
END:VALARM
DTSTART:20180421T180000Z
DTEND:20180421T210000Z
UID:ZnrpdKBPigq8eoFPXgeYZvOY@stanza.co
SUMMARY:Blue Rocks @ Keys
DESCRIPTION:Blue Rocks @ Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wibv-U\n\nShop: https://stza.co/+wibv-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Keys
<2018-04-22 Sun 13:00-16:00>
:PROPERTIES:
:ID:       FtHv4ARPbKPA7PuxMhPwIX3c@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Keys Blue Rocks @ Keys

Follow on MiLB First Pitch  https //stza.co/+wibw-1a

Shop  https //stza.co/+wibw-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Keys
END:VALARM
DTSTART:20180422T180000Z
DTEND:20180422T210000Z
UID:FtHv4ARPbKPA7PuxMhPwIX3c@stanza.co
SUMMARY:Blue Rocks @ Keys
DESCRIPTION:Blue Rocks @ Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wibw-1a\n\nShop: https://stza.co/+wibw-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Nationals
<2018-04-24 Tue 17:35-20:35>
:PROPERTIES:
:ID:       EkA6_vubK8aWmhnc0SI6E5lK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Nationals Blue Rocks vs. Nationals

Follow on MiLB First Pitch  https //stza.co/+wXat-E

Shop  https //stza.co/+wXat-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Nationals
END:VALARM
DTSTART:20180424T223500Z
DTEND:20180425T013500Z
UID:EkA6_vubK8aWmhnc0SI6E5lK@stanza.co
SUMMARY:Blue Rocks vs. Nationals
DESCRIPTION:Blue Rocks vs. Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+wXat-E\n\nShop: https://stza.co/+wXat-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Nationals
<2018-04-25 Wed 17:35-20:35>
:PROPERTIES:
:ID:       eS7KKfCFJhOq89gH5iCLHCHV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Nationals Blue Rocks vs. Nationals

Follow on MiLB First Pitch  https //stza.co/+wXav-3K

Shop  https //stza.co/+wXav-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Nationals
END:VALARM
DTSTART:20180425T223500Z
DTEND:20180426T013500Z
UID:eS7KKfCFJhOq89gH5iCLHCHV@stanza.co
SUMMARY:Blue Rocks vs. Nationals
DESCRIPTION:Blue Rocks vs. Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+wXav-3K\n\nShop: https://stza.co/+wXav-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Nationals
<2018-04-26 Thu 17:35-20:35>
:PROPERTIES:
:ID:       hNSFeJH34EukQSlp044oSh2E@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Nationals Blue Rocks vs. Nationals

Follow on MiLB First Pitch  https //stza.co/+wXax-3m

Shop  https //stza.co/+wXax-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Nationals
END:VALARM
DTSTART:20180426T223500Z
DTEND:20180427T013500Z
UID:hNSFeJH34EukQSlp044oSh2E@stanza.co
SUMMARY:Blue Rocks vs. Nationals
DESCRIPTION:Blue Rocks vs. Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+wXax-3m\n\nShop: https://stza.co/+wXax-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Dash
<2018-04-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       5fd-g0Z9guqkwweQFnbGTggl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Dash Blue Rocks vs. Dash

Follow on MiLB First Pitch  https //stza.co/+wXaz-3J

Shop  https //stza.co/+wXaz-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Dash
END:VALARM
DTSTART:20180427T230500Z
DTEND:20180428T020500Z
UID:5fd-g0Z9guqkwweQFnbGTggl@stanza.co
SUMMARY:Blue Rocks vs. Dash
DESCRIPTION:Blue Rocks vs. Dash\n\nFollow on MiLB First Pitch: https://stza.co/+wXaz-3J\n\nShop: https://stza.co/+wXaz-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Dash
<2018-04-28 Sat 17:05-20:05>
:PROPERTIES:
:ID:       8bb92Ze5ld3c9tlHOQL98djG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Dash Blue Rocks vs. Dash

Follow on MiLB First Pitch  https //stza.co/+wXaA-E

Shop  https //stza.co/+wXaA-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Dash
END:VALARM
DTSTART:20180428T220500Z
DTEND:20180429T010500Z
UID:8bb92Ze5ld3c9tlHOQL98djG@stanza.co
SUMMARY:Blue Rocks vs. Dash
DESCRIPTION:Blue Rocks vs. Dash\n\nFollow on MiLB First Pitch: https://stza.co/+wXaA-E\n\nShop: https://stza.co/+wXaA-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Dash
<2018-04-29 Sun 12:35-15:35>
:PROPERTIES:
:ID:       teJrvB_suV38kO381Igu3u4D@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Dash Blue Rocks vs. Dash

Follow on MiLB First Pitch  https //stza.co/+wXaD-2$

Shop  https //stza.co/+wXaD-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Dash
END:VALARM
DTSTART:20180429T173500Z
DTEND:20180429T203500Z
UID:teJrvB_suV38kO381Igu3u4D@stanza.co
SUMMARY:Blue Rocks vs. Dash
DESCRIPTION:Blue Rocks vs. Dash\n\nFollow on MiLB First Pitch: https://stza.co/+wXaD-2$\n\nShop: https://stza.co/+wXaD-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Nationals
<2018-05-01 Tue 18:05-21:05>
:PROPERTIES:
:ID:       mwmw59lAsBdK8BKP8qybFjGy@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Nationals Blue Rocks @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xB73-3Z

Shop  https //stza.co/+xB73-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Nationals
END:VALARM
DTSTART:20180501T230500Z
DTEND:20180502T020500Z
UID:mwmw59lAsBdK8BKP8qybFjGy@stanza.co
SUMMARY:Blue Rocks @ Nationals
DESCRIPTION:Blue Rocks @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xB73-3Z\n\nShop: https://stza.co/+xB73-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Nationals
<2018-05-02 Wed 18:05-21:05>
:PROPERTIES:
:ID:       ParXw7jcNeSmPlbcd4J2o6Yb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Nationals Blue Rocks @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xB74-X

Shop  https //stza.co/+xB74-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Nationals
END:VALARM
DTSTART:20180502T230500Z
DTEND:20180503T020500Z
UID:ParXw7jcNeSmPlbcd4J2o6Yb@stanza.co
SUMMARY:Blue Rocks @ Nationals
DESCRIPTION:Blue Rocks @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xB74-X\n\nShop: https://stza.co/+xB74-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Nationals
<2018-05-03 Thu 18:05-21:05>
:PROPERTIES:
:ID:       7cVm6mCPdWQQQDAW1eKcdUES@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Nationals Blue Rocks @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xB75-N

Shop  https //stza.co/+xB75-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Nationals
END:VALARM
DTSTART:20180503T230500Z
DTEND:20180504T020500Z
UID:7cVm6mCPdWQQQDAW1eKcdUES@stanza.co
SUMMARY:Blue Rocks @ Nationals
DESCRIPTION:Blue Rocks @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xB75-N\n\nShop: https://stza.co/+xB75-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Keys
<2018-05-04 Fri 18:05-21:05>
:PROPERTIES:
:ID:       bc8XPEDq1UfAXktJuHgcuowH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Keys Blue Rocks vs. Keys

Follow on MiLB First Pitch  https //stza.co/+wXaF-1l

Shop  https //stza.co/+wXaF-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Keys
END:VALARM
DTSTART:20180504T230500Z
DTEND:20180505T020500Z
UID:bc8XPEDq1UfAXktJuHgcuowH@stanza.co
SUMMARY:Blue Rocks vs. Keys
DESCRIPTION:Blue Rocks vs. Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wXaF-1l\n\nShop: https://stza.co/+wXaF-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Keys
<2018-05-05 Sat 17:05-20:05>
:PROPERTIES:
:ID:       X3EKrY9sDQzST6LVE1CiS9cV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Keys Blue Rocks vs. Keys

Follow on MiLB First Pitch  https //stza.co/+wXaG-y

Shop  https //stza.co/+wXaG-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Keys
END:VALARM
DTSTART:20180505T220500Z
DTEND:20180506T010500Z
UID:X3EKrY9sDQzST6LVE1CiS9cV@stanza.co
SUMMARY:Blue Rocks vs. Keys
DESCRIPTION:Blue Rocks vs. Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wXaG-y\n\nShop: https://stza.co/+wXaG-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Keys
<2018-05-06 Sun 12:35-15:35>
:PROPERTIES:
:ID:       cTz7WLDDAprRY3sUgywiby1l@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Keys Blue Rocks vs. Keys

Follow on MiLB First Pitch  https //stza.co/+wXaI-2l

Shop  https //stza.co/+wXaI-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Keys
END:VALARM
DTSTART:20180506T173500Z
DTEND:20180506T203500Z
UID:cTz7WLDDAprRY3sUgywiby1l@stanza.co
SUMMARY:Blue Rocks vs. Keys
DESCRIPTION:Blue Rocks vs. Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wXaI-2l\n\nShop: https://stza.co/+wXaI-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Nationals
<2018-05-07 Mon 17:35-20:35>
:PROPERTIES:
:ID:       YZEoKfBBA-do4o5Ih-fArnlL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Nationals Blue Rocks vs. Nationals

Follow on MiLB First Pitch  https //stza.co/+wXaL-18

Shop  https //stza.co/+wXaL-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Nationals
END:VALARM
DTSTART:20180507T223500Z
DTEND:20180508T013500Z
UID:YZEoKfBBA-do4o5Ih-fArnlL@stanza.co
SUMMARY:Blue Rocks vs. Nationals
DESCRIPTION:Blue Rocks vs. Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+wXaL-18\n\nShop: https://stza.co/+wXaL-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Nationals
<2018-05-08 Tue 17:35-20:35>
:PROPERTIES:
:ID:       lvNMvwsHEb70MSrn3H1SDR_X@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Nationals Blue Rocks vs. Nationals

Follow on MiLB First Pitch  https //stza.co/+wXaN-2i

Shop  https //stza.co/+wXaN-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Nationals
END:VALARM
DTSTART:20180508T223500Z
DTEND:20180509T013500Z
UID:lvNMvwsHEb70MSrn3H1SDR_X@stanza.co
SUMMARY:Blue Rocks vs. Nationals
DESCRIPTION:Blue Rocks vs. Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+wXaN-2i\n\nShop: https://stza.co/+wXaN-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Nationals
<2018-05-09 Wed 17:35-20:35>
:PROPERTIES:
:ID:       AXOkG_rFiYBKAChAHKDYZPY-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Nationals Blue Rocks vs. Nationals

Follow on MiLB First Pitch  https //stza.co/+wXaP-q

Shop  https //stza.co/+wXaP-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Nationals
END:VALARM
DTSTART:20180509T223500Z
DTEND:20180510T013500Z
UID:AXOkG_rFiYBKAChAHKDYZPY-@stanza.co
SUMMARY:Blue Rocks vs. Nationals
DESCRIPTION:Blue Rocks vs. Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+wXaP-q\n\nShop: https://stza.co/+wXaP-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Mudcats
<2018-05-10 Thu 18:00-21:00>
:PROPERTIES:
:ID:       aOhvaQMmAaXwwhaPXJwAjTMr@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Mudcats Blue Rocks @ Mudcats

Buy tickets here  https //stza.co/~w0He

Follow on MiLB First Pitch  https //stza.co/+w0He-2W

Shop  https //stza.co/+w0He-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Mudcats
END:VALARM
DTSTART:20180510T230000Z
DTEND:20180511T020000Z
UID:aOhvaQMmAaXwwhaPXJwAjTMr@stanza.co
SUMMARY:Blue Rocks @ Mudcats
DESCRIPTION:Blue Rocks @ Mudcats\n\nBuy tickets here: https://stza.co/~w0He\n\nFollow on MiLB First Pitch: https://stza.co/+w0He-2W\n\nShop: https://stza.co/+w0He-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Mudcats
<2018-05-11 Fri 18:00-21:00>
:PROPERTIES:
:ID:       DQOTb2DP2-8kRZ6ljM-NZLdn@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Mudcats Blue Rocks @ Mudcats

Buy tickets here  https //stza.co/~w0Hf

Follow on MiLB First Pitch  https //stza.co/+w0Hf-1D

Shop  https //stza.co/+w0Hf-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Mudcats
END:VALARM
DTSTART:20180511T230000Z
DTEND:20180512T020000Z
UID:DQOTb2DP2-8kRZ6ljM-NZLdn@stanza.co
SUMMARY:Blue Rocks @ Mudcats
DESCRIPTION:Blue Rocks @ Mudcats\n\nBuy tickets here: https://stza.co/~w0Hf\n\nFollow on MiLB First Pitch: https://stza.co/+w0Hf-1D\n\nShop: https://stza.co/+w0Hf-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Mudcats
<2018-05-12 Sat 16:00-19:00>
:PROPERTIES:
:ID:       naXiUfkaIPW8rRBqwWTgezBP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Mudcats Blue Rocks @ Mudcats

Buy tickets here  https //stza.co/~w0Hg

Follow on MiLB First Pitch  https //stza.co/+w0Hg-3t

Shop  https //stza.co/+w0Hg-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Mudcats
END:VALARM
DTSTART:20180512T210000Z
DTEND:20180513T000000Z
UID:naXiUfkaIPW8rRBqwWTgezBP@stanza.co
SUMMARY:Blue Rocks @ Mudcats
DESCRIPTION:Blue Rocks @ Mudcats\n\nBuy tickets here: https://stza.co/~w0Hg\n\nFollow on MiLB First Pitch: https://stza.co/+w0Hg-3t\n\nShop: https://stza.co/+w0Hg-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Mudcats
<2018-05-13 Sun 13:00-16:00>
:PROPERTIES:
:ID:       yJVkQBL3oAQ5u6TQdi5YCKj-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Mudcats Blue Rocks @ Mudcats

Buy tickets here  https //stza.co/~w0Hh

Follow on MiLB First Pitch  https //stza.co/+w0Hh-1Y

Shop  https //stza.co/+w0Hh-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Mudcats
END:VALARM
DTSTART:20180513T180000Z
DTEND:20180513T210000Z
UID:yJVkQBL3oAQ5u6TQdi5YCKj-@stanza.co
SUMMARY:Blue Rocks @ Mudcats
DESCRIPTION:Blue Rocks @ Mudcats\n\nBuy tickets here: https://stza.co/~w0Hh\n\nFollow on MiLB First Pitch: https://stza.co/+w0Hh-1Y\n\nShop: https://stza.co/+w0Hh-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Pelicans
<2018-05-15 Tue 17:35-20:35>
:PROPERTIES:
:ID:       3aBlpRZLcwUpQmMC34ad54a6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Pelicans Blue Rocks vs. Pelicans

Follow on MiLB First Pitch  https //stza.co/+wXaR-1w

Shop  https //stza.co/+wXaR-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Pelicans
END:VALARM
DTSTART:20180515T223500Z
DTEND:20180516T013500Z
UID:3aBlpRZLcwUpQmMC34ad54a6@stanza.co
SUMMARY:Blue Rocks vs. Pelicans
DESCRIPTION:Blue Rocks vs. Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+wXaR-1w\n\nShop: https://stza.co/+wXaR-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Pelicans
<2018-05-16 Wed 09:35-12:35>
:PROPERTIES:
:ID:       AJaNVK9Bk4qz2gH15Bc4EYLV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Pelicans Blue Rocks vs. Pelicans

Follow on MiLB First Pitch  https //stza.co/+wXaT-1r

Shop  https //stza.co/+wXaT-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Pelicans
END:VALARM
DTSTART:20180516T143500Z
DTEND:20180516T173500Z
UID:AJaNVK9Bk4qz2gH15Bc4EYLV@stanza.co
SUMMARY:Blue Rocks vs. Pelicans
DESCRIPTION:Blue Rocks vs. Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+wXaT-1r\n\nShop: https://stza.co/+wXaT-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Pelicans
<2018-05-17 Thu 17:35-20:35>
:PROPERTIES:
:ID:       98XyZO4bEg7tyynUMEBW4Dee@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Pelicans Blue Rocks vs. Pelicans

Follow on MiLB First Pitch  https //stza.co/+wXaV-3H

Shop  https //stza.co/+wXaV-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Pelicans
END:VALARM
DTSTART:20180517T223500Z
DTEND:20180518T013500Z
UID:98XyZO4bEg7tyynUMEBW4Dee@stanza.co
SUMMARY:Blue Rocks vs. Pelicans
DESCRIPTION:Blue Rocks vs. Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+wXaV-3H\n\nShop: https://stza.co/+wXaV-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Red Sox
<2018-05-18 Fri>--<2018-05-17 Thu>
:PROPERTIES:
:ID:       RXlYn7-g-K0R4GTrASJT_pBi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Red Sox Blue Rocks @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0I1-i

Shop  https //stza.co/+w0I1-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180518
DTEND;VALUE=DATE:20180518
UID:RXlYn7-g-K0R4GTrASJT_pBi@stanza.co
SUMMARY:Blue Rocks @ Red Sox
DESCRIPTION:Blue Rocks @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0I1-i\n\nShop: https://stza.co/+w0I1-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Red Sox
<2018-05-19 Sat>--<2018-05-18 Fri>
:PROPERTIES:
:ID:       hhIl7QfAHP2mAUA0WQoO1ixk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Red Sox Blue Rocks @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0I2-3s

Shop  https //stza.co/+w0I2-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180519
DTEND;VALUE=DATE:20180519
UID:hhIl7QfAHP2mAUA0WQoO1ixk@stanza.co
SUMMARY:Blue Rocks @ Red Sox
DESCRIPTION:Blue Rocks @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0I2-3s\n\nShop: https://stza.co/+w0I2-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Red Sox
<2018-05-20 Sun>--<2018-05-19 Sat>
:PROPERTIES:
:ID:       AWrWCjHeGafG2mYmsilt_rw7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Red Sox Blue Rocks @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0I3-3e

Shop  https //stza.co/+w0I3-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180520
DTEND;VALUE=DATE:20180520
UID:AWrWCjHeGafG2mYmsilt_rw7@stanza.co
SUMMARY:Blue Rocks @ Red Sox
DESCRIPTION:Blue Rocks @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0I3-3e\n\nShop: https://stza.co/+w0I3-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Nationals
<2018-05-21 Mon 18:05-21:05>
:PROPERTIES:
:ID:       fKkgU-YSVCAckV68Lg-K06jK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Nationals Blue Rocks @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xB76-1a

Shop  https //stza.co/+xB76-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Nationals
END:VALARM
DTSTART:20180521T230500Z
DTEND:20180522T020500Z
UID:fKkgU-YSVCAckV68Lg-K06jK@stanza.co
SUMMARY:Blue Rocks @ Nationals
DESCRIPTION:Blue Rocks @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xB76-1a\n\nShop: https://stza.co/+xB76-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Nationals
<2018-05-22 Tue 18:05-21:05>
:PROPERTIES:
:ID:       Ck7SSyL11pzPyMe1c8s8QUCx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Nationals Blue Rocks @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xB77-S

Shop  https //stza.co/+xB77-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Nationals
END:VALARM
DTSTART:20180522T230500Z
DTEND:20180523T020500Z
UID:Ck7SSyL11pzPyMe1c8s8QUCx@stanza.co
SUMMARY:Blue Rocks @ Nationals
DESCRIPTION:Blue Rocks @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xB77-S\n\nShop: https://stza.co/+xB77-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Nationals
<2018-05-23 Wed 18:05-21:05>
:PROPERTIES:
:ID:       p-UjxGpk1g8FT-EfskeGiMRx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Nationals Blue Rocks @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xB78-2k

Shop  https //stza.co/+xB78-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Nationals
END:VALARM
DTSTART:20180523T230500Z
DTEND:20180524T020500Z
UID:p-UjxGpk1g8FT-EfskeGiMRx@stanza.co
SUMMARY:Blue Rocks @ Nationals
DESCRIPTION:Blue Rocks @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xB78-2k\n\nShop: https://stza.co/+xB78-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Nationals
<2018-05-24 Thu 18:05-21:05>
:PROPERTIES:
:ID:       kXKmsDsL45CVKSwI4bfS9frY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Nationals Blue Rocks @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xB79-38

Shop  https //stza.co/+xB79-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Nationals
END:VALARM
DTSTART:20180524T230500Z
DTEND:20180525T020500Z
UID:kXKmsDsL45CVKSwI4bfS9frY@stanza.co
SUMMARY:Blue Rocks @ Nationals
DESCRIPTION:Blue Rocks @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xB79-38\n\nShop: https://stza.co/+xB79-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Red Sox
<2018-05-25 Fri 18:05-21:05>
:PROPERTIES:
:ID:       IhS98FefmBcg3Zw9Ze6_KHcV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Red Sox Blue Rocks vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+wXaY-S

Shop  https //stza.co/+wXaY-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Red Sox
END:VALARM
DTSTART:20180525T230500Z
DTEND:20180526T020500Z
UID:IhS98FefmBcg3Zw9Ze6_KHcV@stanza.co
SUMMARY:Blue Rocks vs. Red Sox
DESCRIPTION:Blue Rocks vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wXaY-S\n\nShop: https://stza.co/+wXaY-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Red Sox
<2018-05-26 Sat 17:05-20:05>
:PROPERTIES:
:ID:       H11BUv9verpYrgGsNOmUDqjW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Red Sox Blue Rocks vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+wXa_-u

Shop  https //stza.co/+wXa_-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Red Sox
END:VALARM
DTSTART:20180526T220500Z
DTEND:20180527T010500Z
UID:H11BUv9verpYrgGsNOmUDqjW@stanza.co
SUMMARY:Blue Rocks vs. Red Sox
DESCRIPTION:Blue Rocks vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wXa_-u\n\nShop: https://stza.co/+wXa_-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Red Sox
<2018-05-27 Sun 12:35-15:35>
:PROPERTIES:
:ID:       MDju6rq2Wk2sW4vHWKJ0bpxa@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Red Sox Blue Rocks vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+wXb1-1q

Shop  https //stza.co/+wXb1-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Red Sox
END:VALARM
DTSTART:20180527T173500Z
DTEND:20180527T203500Z
UID:MDju6rq2Wk2sW4vHWKJ0bpxa@stanza.co
SUMMARY:Blue Rocks vs. Red Sox
DESCRIPTION:Blue Rocks vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wXb1-1q\n\nShop: https://stza.co/+wXb1-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Red Sox
<2018-05-28 Mon 11:05-14:05>
:PROPERTIES:
:ID:       _CRjGJ2mG7419BurklrcbCLJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Red Sox Blue Rocks vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+wXb2-3L

Shop  https //stza.co/+wXb2-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Red Sox
END:VALARM
DTSTART:20180528T160500Z
DTEND:20180528T190500Z
UID:_CRjGJ2mG7419BurklrcbCLJ@stanza.co
SUMMARY:Blue Rocks vs. Red Sox
DESCRIPTION:Blue Rocks vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wXb2-3L\n\nShop: https://stza.co/+wXb2-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Keys
<2018-05-29 Tue 17:35-20:35>
:PROPERTIES:
:ID:       Ieqba7tyJBBm3R01GqURl66n@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Keys Blue Rocks vs. Keys

Follow on MiLB First Pitch  https //stza.co/+wXb4-2t

Shop  https //stza.co/+wXb4-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Keys
END:VALARM
DTSTART:20180529T223500Z
DTEND:20180530T013500Z
UID:Ieqba7tyJBBm3R01GqURl66n@stanza.co
SUMMARY:Blue Rocks vs. Keys
DESCRIPTION:Blue Rocks vs. Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wXb4-2t\n\nShop: https://stza.co/+wXb4-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Keys
<2018-05-30 Wed 17:35-20:35>
:PROPERTIES:
:ID:       2t9AptkU87GM0IdgG7kqm7aT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Keys Blue Rocks vs. Keys

Follow on MiLB First Pitch  https //stza.co/+wXb7-2_

Shop  https //stza.co/+wXb7-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Keys
END:VALARM
DTSTART:20180530T223500Z
DTEND:20180531T013500Z
UID:2t9AptkU87GM0IdgG7kqm7aT@stanza.co
SUMMARY:Blue Rocks vs. Keys
DESCRIPTION:Blue Rocks vs. Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wXb7-2_\n\nShop: https://stza.co/+wXb7-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Keys
<2018-05-31 Thu 17:35-20:35>
:PROPERTIES:
:ID:       1dpQqMWuKVXKQSLoqhCmzhzF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Keys Blue Rocks vs. Keys

Follow on MiLB First Pitch  https //stza.co/+wXba-33

Shop  https //stza.co/+wXba-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Keys
END:VALARM
DTSTART:20180531T223500Z
DTEND:20180601T013500Z
UID:1dpQqMWuKVXKQSLoqhCmzhzF@stanza.co
SUMMARY:Blue Rocks vs. Keys
DESCRIPTION:Blue Rocks vs. Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wXba-33\n\nShop: https://stza.co/+wXba-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Red Sox
<2018-06-01 Fri>--<2018-05-31 Thu>
:PROPERTIES:
:ID:       ardkTMHblDDq4VVencJ32w03@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Red Sox Blue Rocks @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0I4-R

Shop  https //stza.co/+w0I4-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180601
DTEND;VALUE=DATE:20180601
UID:ardkTMHblDDq4VVencJ32w03@stanza.co
SUMMARY:Blue Rocks @ Red Sox
DESCRIPTION:Blue Rocks @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0I4-R\n\nShop: https://stza.co/+w0I4-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Red Sox
<2018-06-02 Sat>--<2018-06-01 Fri>
:PROPERTIES:
:ID:       goqVKroRV9lFo_LPT0XHrpvC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Red Sox Blue Rocks @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0I5-s

Shop  https //stza.co/+w0I5-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180602
DTEND;VALUE=DATE:20180602
UID:goqVKroRV9lFo_LPT0XHrpvC@stanza.co
SUMMARY:Blue Rocks @ Red Sox
DESCRIPTION:Blue Rocks @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0I5-s\n\nShop: https://stza.co/+w0I5-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Red Sox
<2018-06-03 Sun>--<2018-06-02 Sat>
:PROPERTIES:
:ID:       8UXvkniK0iQNy7D9EntE1UHx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Red Sox Blue Rocks @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0I6-3O

Shop  https //stza.co/+w0I6-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180603
DTEND;VALUE=DATE:20180603
UID:8UXvkniK0iQNy7D9EntE1UHx@stanza.co
SUMMARY:Blue Rocks @ Red Sox
DESCRIPTION:Blue Rocks @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0I6-3O\n\nShop: https://stza.co/+w0I6-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Hillcats
<2018-06-05 Tue 17:35-20:35>
:PROPERTIES:
:ID:       uUNUcU-gjZs2OWwgQS1URpMh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Hillcats Blue Rocks vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+wXbb-1h

Shop  https //stza.co/+wXbb-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Hillcats
END:VALARM
DTSTART:20180605T223500Z
DTEND:20180606T013500Z
UID:uUNUcU-gjZs2OWwgQS1URpMh@stanza.co
SUMMARY:Blue Rocks vs. Hillcats
DESCRIPTION:Blue Rocks vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+wXbb-1h\n\nShop: https://stza.co/+wXbb-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Hillcats
<2018-06-06 Wed 17:35-20:35>
:PROPERTIES:
:ID:       xJDbV_3nZAdFWvhxa24ca0Wx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Hillcats Blue Rocks vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+wXbe-17

Shop  https //stza.co/+wXbe-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Hillcats
END:VALARM
DTSTART:20180606T223500Z
DTEND:20180607T013500Z
UID:xJDbV_3nZAdFWvhxa24ca0Wx@stanza.co
SUMMARY:Blue Rocks vs. Hillcats
DESCRIPTION:Blue Rocks vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+wXbe-17\n\nShop: https://stza.co/+wXbe-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Hillcats
<2018-06-07 Thu 17:35-20:35>
:PROPERTIES:
:ID:       aOpkvjWwWLFC6TAK2ztOJh0p@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Hillcats Blue Rocks vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+wXbg-2F

Shop  https //stza.co/+wXbg-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Hillcats
END:VALARM
DTSTART:20180607T223500Z
DTEND:20180608T013500Z
UID:aOpkvjWwWLFC6TAK2ztOJh0p@stanza.co
SUMMARY:Blue Rocks vs. Hillcats
DESCRIPTION:Blue Rocks vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+wXbg-2F\n\nShop: https://stza.co/+wXbg-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Keys
<2018-06-08 Fri 18:05-21:05>
:PROPERTIES:
:ID:       Y6lFOm7lM65-E8ghGkOYEmEK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Keys Blue Rocks vs. Keys

Follow on MiLB First Pitch  https //stza.co/+wXbi-20

Shop  https //stza.co/+wXbi-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Keys
END:VALARM
DTSTART:20180608T230500Z
DTEND:20180609T020500Z
UID:Y6lFOm7lM65-E8ghGkOYEmEK@stanza.co
SUMMARY:Blue Rocks vs. Keys
DESCRIPTION:Blue Rocks vs. Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wXbi-20\n\nShop: https://stza.co/+wXbi-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Keys
<2018-06-09 Sat 17:05-20:05>
:PROPERTIES:
:ID:       cNAI7Pk-0I-lklN8gMQ6Nyft@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Keys Blue Rocks vs. Keys

Follow on MiLB First Pitch  https //stza.co/+wXbj-2J

Shop  https //stza.co/+wXbj-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Keys
END:VALARM
DTSTART:20180609T220500Z
DTEND:20180610T010500Z
UID:cNAI7Pk-0I-lklN8gMQ6Nyft@stanza.co
SUMMARY:Blue Rocks vs. Keys
DESCRIPTION:Blue Rocks vs. Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wXbj-2J\n\nShop: https://stza.co/+wXbj-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Keys
<2018-06-10 Sun 12:35-15:35>
:PROPERTIES:
:ID:       3WVulE-XFjPWlavoOWuzVMvr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Keys Blue Rocks vs. Keys

Follow on MiLB First Pitch  https //stza.co/+wXbm-38

Shop  https //stza.co/+wXbm-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Keys
END:VALARM
DTSTART:20180610T173500Z
DTEND:20180610T203500Z
UID:3WVulE-XFjPWlavoOWuzVMvr@stanza.co
SUMMARY:Blue Rocks vs. Keys
DESCRIPTION:Blue Rocks vs. Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wXbm-38\n\nShop: https://stza.co/+wXbm-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Wood Ducks
<2018-06-11 Mon 18:00-21:00>
:PROPERTIES:
:ID:       JvmmSjOte3Pc43BuyaC0KaQt@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Wood Ducks Blue Rocks @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0Hi-D

Shop  https //stza.co/+w0Hi-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Wood Ducks
END:VALARM
DTSTART:20180611T230000Z
DTEND:20180612T020000Z
UID:JvmmSjOte3Pc43BuyaC0KaQt@stanza.co
SUMMARY:Blue Rocks @ Wood Ducks
DESCRIPTION:Blue Rocks @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0Hi-D\n\nShop: https://stza.co/+w0Hi-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Wood Ducks
<2018-06-12 Tue 18:00-21:00>
:PROPERTIES:
:ID:       -2IFxqKFajqO2UxvdEvg5w4o@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Wood Ducks Blue Rocks @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0Hj-3U

Shop  https //stza.co/+w0Hj-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Wood Ducks
END:VALARM
DTSTART:20180612T230000Z
DTEND:20180613T020000Z
UID:-2IFxqKFajqO2UxvdEvg5w4o@stanza.co
SUMMARY:Blue Rocks @ Wood Ducks
DESCRIPTION:Blue Rocks @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0Hj-3U\n\nShop: https://stza.co/+w0Hj-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Wood Ducks
<2018-06-13 Wed 11:05-14:05>
:PROPERTIES:
:ID:       QVtirDo62CS1T7QNX_Ejilfd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Wood Ducks Blue Rocks @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0Hk-32

Shop  https //stza.co/+w0Hk-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Wood Ducks
END:VALARM
DTSTART:20180613T160500Z
DTEND:20180613T190500Z
UID:QVtirDo62CS1T7QNX_Ejilfd@stanza.co
SUMMARY:Blue Rocks @ Wood Ducks
DESCRIPTION:Blue Rocks @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0Hk-32\n\nShop: https://stza.co/+w0Hk-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Dash
<2018-06-14 Thu 18:00-21:00>
:PROPERTIES:
:ID:       yj31IUD4tn0y6M68qfHhxGbU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Dash Blue Rocks @ Dash

Buy tickets here  https //stza.co/~w0Km

Follow on MiLB First Pitch  https //stza.co/+w0Km-12

Shop  https //stza.co/+w0Km-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Dash
END:VALARM
DTSTART:20180614T230000Z
DTEND:20180615T020000Z
UID:yj31IUD4tn0y6M68qfHhxGbU@stanza.co
SUMMARY:Blue Rocks @ Dash
DESCRIPTION:Blue Rocks @ Dash\n\nBuy tickets here: https://stza.co/~w0Km\n\nFollow on MiLB First Pitch: https://stza.co/+w0Km-12\n\nShop: https://stza.co/+w0Km-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Dash
<2018-06-15 Fri 18:00-21:00>
:PROPERTIES:
:ID:       GxffCKn0B9HuxqnDs6WULxc5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Dash Blue Rocks @ Dash

Buy tickets here  https //stza.co/~w0Kn

Follow on MiLB First Pitch  https //stza.co/+w0Kn-m

Shop  https //stza.co/+w0Kn-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Dash
END:VALARM
DTSTART:20180615T230000Z
DTEND:20180616T020000Z
UID:GxffCKn0B9HuxqnDs6WULxc5@stanza.co
SUMMARY:Blue Rocks @ Dash
DESCRIPTION:Blue Rocks @ Dash\n\nBuy tickets here: https://stza.co/~w0Kn\n\nFollow on MiLB First Pitch: https://stza.co/+w0Kn-m\n\nShop: https://stza.co/+w0Kn-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Dash
<2018-06-16 Sat 17:00-20:00>
:PROPERTIES:
:ID:       gC9nn44mn-evq6GC7wgNATMd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Dash Blue Rocks @ Dash

Buy tickets here  https //stza.co/~w0Ko

Follow on MiLB First Pitch  https //stza.co/+w0Ko-38

Shop  https //stza.co/+w0Ko-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Dash
END:VALARM
DTSTART:20180616T220000Z
DTEND:20180617T010000Z
UID:gC9nn44mn-evq6GC7wgNATMd@stanza.co
SUMMARY:Blue Rocks @ Dash
DESCRIPTION:Blue Rocks @ Dash\n\nBuy tickets here: https://stza.co/~w0Ko\n\nFollow on MiLB First Pitch: https://stza.co/+w0Ko-38\n\nShop: https://stza.co/+w0Ko-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Dash
<2018-06-17 Sun 13:00-16:00>
:PROPERTIES:
:ID:       Q-7riVXr3h1fTS7rvKBJZK-Q@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Dash Blue Rocks @ Dash

Buy tickets here  https //stza.co/~w0Kp

Follow on MiLB First Pitch  https //stza.co/+w0Kp-2M

Shop  https //stza.co/+w0Kp-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Dash
END:VALARM
DTSTART:20180617T180000Z
DTEND:20180617T210000Z
UID:Q-7riVXr3h1fTS7rvKBJZK-Q@stanza.co
SUMMARY:Blue Rocks @ Dash
DESCRIPTION:Blue Rocks @ Dash\n\nBuy tickets here: https://stza.co/~w0Kp\n\nFollow on MiLB First Pitch: https://stza.co/+w0Kp-2M\n\nShop: https://stza.co/+w0Kp-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Nationals
<2018-06-21 Thu 18:05-21:05>
:PROPERTIES:
:ID:       -Z_aPkVZp2pnM4-Op3tt89Us@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Nationals Blue Rocks @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xB7a-1s

Shop  https //stza.co/+xB7a-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Nationals
END:VALARM
DTSTART:20180621T230500Z
DTEND:20180622T020500Z
UID:-Z_aPkVZp2pnM4-Op3tt89Us@stanza.co
SUMMARY:Blue Rocks @ Nationals
DESCRIPTION:Blue Rocks @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xB7a-1s\n\nShop: https://stza.co/+xB7a-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Nationals
<2018-06-22 Fri 18:05-21:05>
:PROPERTIES:
:ID:       C7zvP_vEU1EdWP42vVZPxvmL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Nationals Blue Rocks @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xB7b-2D

Shop  https //stza.co/+xB7b-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Nationals
END:VALARM
DTSTART:20180622T230500Z
DTEND:20180623T020500Z
UID:C7zvP_vEU1EdWP42vVZPxvmL@stanza.co
SUMMARY:Blue Rocks @ Nationals
DESCRIPTION:Blue Rocks @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xB7b-2D\n\nShop: https://stza.co/+xB7b-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Nationals
<2018-06-23 Sat 17:35-20:35>
:PROPERTIES:
:ID:       SDpM_BWdA9PiGWZls9LJDGID@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Nationals Blue Rocks @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xB7c-1u

Shop  https //stza.co/+xB7c-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Nationals
END:VALARM
DTSTART:20180623T223500Z
DTEND:20180624T013500Z
UID:SDpM_BWdA9PiGWZls9LJDGID@stanza.co
SUMMARY:Blue Rocks @ Nationals
DESCRIPTION:Blue Rocks @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xB7c-1u\n\nShop: https://stza.co/+xB7c-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Nationals
<2018-06-24 Sun 12:05-15:05>
:PROPERTIES:
:ID:       tw6LY2PXKGPe3sGozudd502L@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Nationals Blue Rocks @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xA8K-1v

Shop  https //stza.co/+xA8K-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Nationals
END:VALARM
DTSTART:20180624T170500Z
DTEND:20180624T200500Z
UID:tw6LY2PXKGPe3sGozudd502L@stanza.co
SUMMARY:Blue Rocks @ Nationals
DESCRIPTION:Blue Rocks @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xA8K-1v\n\nShop: https://stza.co/+xA8K-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Hillcats
<2018-06-25 Mon 17:35-20:35>
:PROPERTIES:
:ID:       Qz12DTvNXBL-Qg5PcFEB3Kpa@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Hillcats Blue Rocks vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+wXbn-_

Shop  https //stza.co/+wXbn-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Hillcats
END:VALARM
DTSTART:20180625T223500Z
DTEND:20180626T013500Z
UID:Qz12DTvNXBL-Qg5PcFEB3Kpa@stanza.co
SUMMARY:Blue Rocks vs. Hillcats
DESCRIPTION:Blue Rocks vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+wXbn-_\n\nShop: https://stza.co/+wXbn-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Hillcats
<2018-06-26 Tue 17:35-20:35>
:PROPERTIES:
:ID:       knG7bF02HGcWXYNrjTPK1abp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Hillcats Blue Rocks vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+wXbq-i

Shop  https //stza.co/+wXbq-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Hillcats
END:VALARM
DTSTART:20180626T223500Z
DTEND:20180627T013500Z
UID:knG7bF02HGcWXYNrjTPK1abp@stanza.co
SUMMARY:Blue Rocks vs. Hillcats
DESCRIPTION:Blue Rocks vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+wXbq-i\n\nShop: https://stza.co/+wXbq-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Hillcats
<2018-06-27 Wed 17:35-20:35>
:PROPERTIES:
:ID:       ypjS-wG7649Z_vus22uEEfCO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Hillcats Blue Rocks vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+wXbr-z

Shop  https //stza.co/+wXbr-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Hillcats
END:VALARM
DTSTART:20180627T223500Z
DTEND:20180628T013500Z
UID:ypjS-wG7649Z_vus22uEEfCO@stanza.co
SUMMARY:Blue Rocks vs. Hillcats
DESCRIPTION:Blue Rocks vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+wXbr-z\n\nShop: https://stza.co/+wXbr-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Hillcats
<2018-06-28 Thu 17:35-20:35>
:PROPERTIES:
:ID:       w9JuT7pDwXu-2STkEvuXlDLQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Hillcats Blue Rocks vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+wXbu-2y

Shop  https //stza.co/+wXbu-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Hillcats
END:VALARM
DTSTART:20180628T223500Z
DTEND:20180629T013500Z
UID:w9JuT7pDwXu-2STkEvuXlDLQ@stanza.co
SUMMARY:Blue Rocks vs. Hillcats
DESCRIPTION:Blue Rocks vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+wXbu-2y\n\nShop: https://stza.co/+wXbu-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Hillcats
<2018-06-29 Fri 18:05-21:05>
:PROPERTIES:
:ID:       5GMdEzI9nqDzMXou6AWLuGAz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Hillcats Blue Rocks vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+wXbv-k

Shop  https //stza.co/+wXbv-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Hillcats
END:VALARM
DTSTART:20180629T230500Z
DTEND:20180630T020500Z
UID:5GMdEzI9nqDzMXou6AWLuGAz@stanza.co
SUMMARY:Blue Rocks vs. Hillcats
DESCRIPTION:Blue Rocks vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+wXbv-k\n\nShop: https://stza.co/+wXbv-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Dash
<2018-06-30 Sat 17:05-20:05>
:PROPERTIES:
:ID:       grlM85CisvIv8c1ch7ue8_95@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Dash Blue Rocks vs. Dash

Follow on MiLB First Pitch  https //stza.co/+wXbx-20

Shop  https //stza.co/+wXbx-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Dash
END:VALARM
DTSTART:20180630T220500Z
DTEND:20180701T010500Z
UID:grlM85CisvIv8c1ch7ue8_95@stanza.co
SUMMARY:Blue Rocks vs. Dash
DESCRIPTION:Blue Rocks vs. Dash\n\nFollow on MiLB First Pitch: https://stza.co/+wXbx-20\n\nShop: https://stza.co/+wXbx-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Dash
<2018-07-01 Sun 12:35-15:35>
:PROPERTIES:
:ID:       LNbakQ65JWqkL-F78IEe6WXR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Dash Blue Rocks vs. Dash

Follow on MiLB First Pitch  https //stza.co/+wXbA-3o

Shop  https //stza.co/+wXbA-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Dash
END:VALARM
DTSTART:20180701T173500Z
DTEND:20180701T203500Z
UID:LNbakQ65JWqkL-F78IEe6WXR@stanza.co
SUMMARY:Blue Rocks vs. Dash
DESCRIPTION:Blue Rocks vs. Dash\n\nFollow on MiLB First Pitch: https://stza.co/+wXbA-3o\n\nShop: https://stza.co/+wXbA-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Dash
<2018-07-02 Mon 17:35-20:35>
:PROPERTIES:
:ID:       uiG_VYHwjxAdXgq5ww0REKJL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Dash Blue Rocks vs. Dash

Follow on MiLB First Pitch  https //stza.co/+wXbB-9

Shop  https //stza.co/+wXbB-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Dash
END:VALARM
DTSTART:20180702T223500Z
DTEND:20180703T013500Z
UID:uiG_VYHwjxAdXgq5ww0REKJL@stanza.co
SUMMARY:Blue Rocks vs. Dash
DESCRIPTION:Blue Rocks vs. Dash\n\nFollow on MiLB First Pitch: https://stza.co/+wXbB-9\n\nShop: https://stza.co/+wXbB-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Dash
<2018-07-03 Tue 17:35-20:35>
:PROPERTIES:
:ID:       PgWNf6J9-ST4n5j1zjQ6QfxC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Dash Blue Rocks vs. Dash

Follow on MiLB First Pitch  https //stza.co/+wXbE-1J

Shop  https //stza.co/+wXbE-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Dash
END:VALARM
DTSTART:20180703T223500Z
DTEND:20180704T013500Z
UID:PgWNf6J9-ST4n5j1zjQ6QfxC@stanza.co
SUMMARY:Blue Rocks vs. Dash
DESCRIPTION:Blue Rocks vs. Dash\n\nFollow on MiLB First Pitch: https://stza.co/+wXbE-1J\n\nShop: https://stza.co/+wXbE-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Hillcats
<2018-07-04 Wed 17:30-20:30>
:PROPERTIES:
:ID:       cr8CNkA0bA-lLw4N8tTLTpCL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Hillcats Blue Rocks @ Hillcats

Buy tickets here  https //stza.co/~y3Wh

Follow on MiLB First Pitch  https //stza.co/+y3Wh-3W

Shop  https //stza.co/+y3Wh-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Hillcats
END:VALARM
DTSTART:20180704T223000Z
DTEND:20180705T013000Z
UID:cr8CNkA0bA-lLw4N8tTLTpCL@stanza.co
SUMMARY:Blue Rocks @ Hillcats
DESCRIPTION:Blue Rocks @ Hillcats\n\nBuy tickets here: https://stza.co/~y3Wh\n\nFollow on MiLB First Pitch: https://stza.co/+y3Wh-3W\n\nShop: https://stza.co/+y3Wh-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Hillcats
<2018-07-05 Thu 17:30-20:30>
:PROPERTIES:
:ID:       37pKLqMyS0ibkaVh-ZULKSw1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Hillcats Blue Rocks @ Hillcats

Buy tickets here  https //stza.co/~y3Wi

Follow on MiLB First Pitch  https //stza.co/+y3Wi-1d

Shop  https //stza.co/+y3Wi-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Hillcats
END:VALARM
DTSTART:20180705T223000Z
DTEND:20180706T013000Z
UID:37pKLqMyS0ibkaVh-ZULKSw1@stanza.co
SUMMARY:Blue Rocks @ Hillcats
DESCRIPTION:Blue Rocks @ Hillcats\n\nBuy tickets here: https://stza.co/~y3Wi\n\nFollow on MiLB First Pitch: https://stza.co/+y3Wi-1d\n\nShop: https://stza.co/+y3Wi-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Hillcats
<2018-07-06 Fri 17:30-20:30>
:PROPERTIES:
:ID:       yV0k_F5qRiwqNx3z054HJqa8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Hillcats Blue Rocks @ Hillcats

Buy tickets here  https //stza.co/~y3Wj

Follow on MiLB First Pitch  https //stza.co/+y3Wj-k

Shop  https //stza.co/+y3Wj-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Hillcats
END:VALARM
DTSTART:20180706T223000Z
DTEND:20180707T013000Z
UID:yV0k_F5qRiwqNx3z054HJqa8@stanza.co
SUMMARY:Blue Rocks @ Hillcats
DESCRIPTION:Blue Rocks @ Hillcats\n\nBuy tickets here: https://stza.co/~y3Wj\n\nFollow on MiLB First Pitch: https://stza.co/+y3Wj-k\n\nShop: https://stza.co/+y3Wj-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Hillcats
<2018-07-07 Sat 17:00-20:00>
:PROPERTIES:
:ID:       3GgrbwcbiZQQncuVvGlC8UdQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Hillcats Blue Rocks @ Hillcats

Buy tickets here  https //stza.co/~y3Wk

Follow on MiLB First Pitch  https //stza.co/+y3Wk-1V

Shop  https //stza.co/+y3Wk-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Hillcats
END:VALARM
DTSTART:20180707T220000Z
DTEND:20180708T010000Z
UID:3GgrbwcbiZQQncuVvGlC8UdQ@stanza.co
SUMMARY:Blue Rocks @ Hillcats
DESCRIPTION:Blue Rocks @ Hillcats\n\nBuy tickets here: https://stza.co/~y3Wk\n\nFollow on MiLB First Pitch: https://stza.co/+y3Wk-1V\n\nShop: https://stza.co/+y3Wk-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Hillcats
<2018-07-08 Sun 16:00-19:00>
:PROPERTIES:
:ID:       veFJZuWU6B2xwlNK-GNndHJH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Hillcats Blue Rocks @ Hillcats

Buy tickets here  https //stza.co/~y3Wl

Follow on MiLB First Pitch  https //stza.co/+y3Wl-1_

Shop  https //stza.co/+y3Wl-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Hillcats
END:VALARM
DTSTART:20180708T210000Z
DTEND:20180709T000000Z
UID:veFJZuWU6B2xwlNK-GNndHJH@stanza.co
SUMMARY:Blue Rocks @ Hillcats
DESCRIPTION:Blue Rocks @ Hillcats\n\nBuy tickets here: https://stza.co/~y3Wl\n\nFollow on MiLB First Pitch: https://stza.co/+y3Wl-1_\n\nShop: https://stza.co/+y3Wl-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Keys
<2018-07-09 Mon 18:00-21:00>
:PROPERTIES:
:ID:       Vmx3kMKZDAKmfg34AZi4Cc9H@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Keys Blue Rocks @ Keys

Follow on MiLB First Pitch  https //stza.co/+wibx-1a

Shop  https //stza.co/+wibx-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Keys
END:VALARM
DTSTART:20180709T230000Z
DTEND:20180710T020000Z
UID:Vmx3kMKZDAKmfg34AZi4Cc9H@stanza.co
SUMMARY:Blue Rocks @ Keys
DESCRIPTION:Blue Rocks @ Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wibx-1a\n\nShop: https://stza.co/+wibx-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Keys
<2018-07-10 Tue 18:00-21:00>
:PROPERTIES:
:ID:       bIz4F3x_aU3K6J3K2VKFlGiJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Keys Blue Rocks @ Keys

Follow on MiLB First Pitch  https //stza.co/+wiby-1n

Shop  https //stza.co/+wiby-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Keys
END:VALARM
DTSTART:20180710T230000Z
DTEND:20180711T020000Z
UID:bIz4F3x_aU3K6J3K2VKFlGiJ@stanza.co
SUMMARY:Blue Rocks @ Keys
DESCRIPTION:Blue Rocks @ Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wiby-1n\n\nShop: https://stza.co/+wiby-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Keys
<2018-07-11 Wed 18:00-21:00>
:PROPERTIES:
:ID:       5OSJ911Qtlu1FbJQ8o1bSCOx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Keys Blue Rocks @ Keys

Follow on MiLB First Pitch  https //stza.co/+wibz-3

Shop  https //stza.co/+wibz-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Keys
END:VALARM
DTSTART:20180711T230000Z
DTEND:20180712T020000Z
UID:5OSJ911Qtlu1FbJQ8o1bSCOx@stanza.co
SUMMARY:Blue Rocks @ Keys
DESCRIPTION:Blue Rocks @ Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wibz-3\n\nShop: https://stza.co/+wibz-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Keys
<2018-07-12 Thu 18:00-21:00>
:PROPERTIES:
:ID:       tmkw2YBso426PDFviWCQRf1i@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Keys Blue Rocks @ Keys

Follow on MiLB First Pitch  https //stza.co/+wibA-w

Shop  https //stza.co/+wibA-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Keys
END:VALARM
DTSTART:20180712T230000Z
DTEND:20180713T020000Z
UID:tmkw2YBso426PDFviWCQRf1i@stanza.co
SUMMARY:Blue Rocks @ Keys
DESCRIPTION:Blue Rocks @ Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wibA-w\n\nShop: https://stza.co/+wibA-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Red Sox
<2018-07-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       O-SqDs5NQWL5Bspn_9FH6Lm2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Red Sox Blue Rocks vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+wXbG-N

Shop  https //stza.co/+wXbG-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Red Sox
END:VALARM
DTSTART:20180713T230500Z
DTEND:20180714T020500Z
UID:O-SqDs5NQWL5Bspn_9FH6Lm2@stanza.co
SUMMARY:Blue Rocks vs. Red Sox
DESCRIPTION:Blue Rocks vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wXbG-N\n\nShop: https://stza.co/+wXbG-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Red Sox
<2018-07-14 Sat 17:05-20:05>
:PROPERTIES:
:ID:       T3jDFU_2fNsYV786icsHuUzg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Red Sox Blue Rocks vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+wXbI-b

Shop  https //stza.co/+wXbI-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Red Sox
END:VALARM
DTSTART:20180714T220500Z
DTEND:20180715T010500Z
UID:T3jDFU_2fNsYV786icsHuUzg@stanza.co
SUMMARY:Blue Rocks vs. Red Sox
DESCRIPTION:Blue Rocks vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wXbI-b\n\nShop: https://stza.co/+wXbI-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Red Sox
<2018-07-15 Sun 12:35-15:35>
:PROPERTIES:
:ID:       1tMz09rDp30jESfSK6BkpOiw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Red Sox Blue Rocks vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+wXbJ-1R

Shop  https //stza.co/+wXbJ-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Red Sox
END:VALARM
DTSTART:20180715T173500Z
DTEND:20180715T203500Z
UID:1tMz09rDp30jESfSK6BkpOiw@stanza.co
SUMMARY:Blue Rocks vs. Red Sox
DESCRIPTION:Blue Rocks vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wXbJ-1R\n\nShop: https://stza.co/+wXbJ-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Red Sox
<2018-07-16 Mon 17:35-20:35>
:PROPERTIES:
:ID:       IbUjaNAkvCc0Uc0u-EpM9gh3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Red Sox Blue Rocks vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+wXbM-1y

Shop  https //stza.co/+wXbM-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Red Sox
END:VALARM
DTSTART:20180716T223500Z
DTEND:20180717T013500Z
UID:IbUjaNAkvCc0Uc0u-EpM9gh3@stanza.co
SUMMARY:Blue Rocks vs. Red Sox
DESCRIPTION:Blue Rocks vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wXbM-1y\n\nShop: https://stza.co/+wXbM-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Hillcats
<2018-07-18 Wed 17:30-20:30>
:PROPERTIES:
:ID:       lOYiIcXoQsxI9vg41wSVVAqg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Hillcats Blue Rocks @ Hillcats

Buy tickets here  https //stza.co/~y3Wm

Follow on MiLB First Pitch  https //stza.co/+y3Wm-R

Shop  https //stza.co/+y3Wm-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Hillcats
END:VALARM
DTSTART:20180718T223000Z
DTEND:20180719T013000Z
UID:lOYiIcXoQsxI9vg41wSVVAqg@stanza.co
SUMMARY:Blue Rocks @ Hillcats
DESCRIPTION:Blue Rocks @ Hillcats\n\nBuy tickets here: https://stza.co/~y3Wm\n\nFollow on MiLB First Pitch: https://stza.co/+y3Wm-R\n\nShop: https://stza.co/+y3Wm-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Hillcats
<2018-07-19 Thu 17:30-20:30>
:PROPERTIES:
:ID:       bJURwynouFIjYh37vrzXgVcW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Hillcats Blue Rocks @ Hillcats

Buy tickets here  https //stza.co/~y3Wn

Follow on MiLB First Pitch  https //stza.co/+y3Wn-9

Shop  https //stza.co/+y3Wn-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Hillcats
END:VALARM
DTSTART:20180719T223000Z
DTEND:20180720T013000Z
UID:bJURwynouFIjYh37vrzXgVcW@stanza.co
SUMMARY:Blue Rocks @ Hillcats
DESCRIPTION:Blue Rocks @ Hillcats\n\nBuy tickets here: https://stza.co/~y3Wn\n\nFollow on MiLB First Pitch: https://stza.co/+y3Wn-9\n\nShop: https://stza.co/+y3Wn-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Hillcats
<2018-07-20 Fri 17:30-20:30>
:PROPERTIES:
:ID:       QrTXwtx981QoW2bNhu7orX_m@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Hillcats Blue Rocks @ Hillcats

Buy tickets here  https //stza.co/~y3Wo

Follow on MiLB First Pitch  https //stza.co/+y3Wo-3I

Shop  https //stza.co/+y3Wo-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Hillcats
END:VALARM
DTSTART:20180720T223000Z
DTEND:20180721T013000Z
UID:QrTXwtx981QoW2bNhu7orX_m@stanza.co
SUMMARY:Blue Rocks @ Hillcats
DESCRIPTION:Blue Rocks @ Hillcats\n\nBuy tickets here: https://stza.co/~y3Wo\n\nFollow on MiLB First Pitch: https://stza.co/+y3Wo-3I\n\nShop: https://stza.co/+y3Wo-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Keys
<2018-07-21 Sat 17:00-20:00>
:PROPERTIES:
:ID:       PR4VuqUdn_wKz4szNieRstRH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Keys Blue Rocks @ Keys

Follow on MiLB First Pitch  https //stza.co/+wibB-2Z

Shop  https //stza.co/+wibB-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Keys
END:VALARM
DTSTART:20180721T220000Z
DTEND:20180722T010000Z
UID:PR4VuqUdn_wKz4szNieRstRH@stanza.co
SUMMARY:Blue Rocks @ Keys
DESCRIPTION:Blue Rocks @ Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wibB-2Z\n\nShop: https://stza.co/+wibB-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Keys
<2018-07-22 Sun 13:00-16:00>
:PROPERTIES:
:ID:       x7c1gs61b_odDl1WOHDq-2vk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Keys Blue Rocks @ Keys

Follow on MiLB First Pitch  https //stza.co/+wibC-1B

Shop  https //stza.co/+wibC-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Keys
END:VALARM
DTSTART:20180722T180000Z
DTEND:20180722T210000Z
UID:x7c1gs61b_odDl1WOHDq-2vk@stanza.co
SUMMARY:Blue Rocks @ Keys
DESCRIPTION:Blue Rocks @ Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wibC-1B\n\nShop: https://stza.co/+wibC-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Keys
<2018-07-23 Mon 13:00-16:00>
:PROPERTIES:
:ID:       snUS3nu3_wP1C4GbXLEj4JEW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Keys Blue Rocks @ Keys

Follow on MiLB First Pitch  https //stza.co/+wibD-37

Shop  https //stza.co/+wibD-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Keys
END:VALARM
DTSTART:20180723T180000Z
DTEND:20180723T210000Z
UID:snUS3nu3_wP1C4GbXLEj4JEW@stanza.co
SUMMARY:Blue Rocks @ Keys
DESCRIPTION:Blue Rocks @ Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wibD-37\n\nShop: https://stza.co/+wibD-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Red Sox
<2018-07-24 Tue 17:35-20:35>
:PROPERTIES:
:ID:       _tt_yUQ8K-usdX3hTaRN9fmH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Red Sox Blue Rocks vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+wXbO-1D

Shop  https //stza.co/+wXbO-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Red Sox
END:VALARM
DTSTART:20180724T223500Z
DTEND:20180725T013500Z
UID:_tt_yUQ8K-usdX3hTaRN9fmH@stanza.co
SUMMARY:Blue Rocks vs. Red Sox
DESCRIPTION:Blue Rocks vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wXbO-1D\n\nShop: https://stza.co/+wXbO-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Red Sox
<2018-07-25 Wed 10:05-13:05>
:PROPERTIES:
:ID:       YyqZoPk8uIqJgIVCr6wDhyUO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Red Sox Blue Rocks vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+wXbP-10

Shop  https //stza.co/+wXbP-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Red Sox
END:VALARM
DTSTART:20180725T150500Z
DTEND:20180725T180500Z
UID:YyqZoPk8uIqJgIVCr6wDhyUO@stanza.co
SUMMARY:Blue Rocks vs. Red Sox
DESCRIPTION:Blue Rocks vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wXbP-10\n\nShop: https://stza.co/+wXbP-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Red Sox
<2018-07-26 Thu 17:35-20:35>
:PROPERTIES:
:ID:       VHYOIRa62Z9F89wG6jfek72a@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Red Sox Blue Rocks vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+wXbS-32

Shop  https //stza.co/+wXbS-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Red Sox
END:VALARM
DTSTART:20180726T223500Z
DTEND:20180727T013500Z
UID:VHYOIRa62Z9F89wG6jfek72a@stanza.co
SUMMARY:Blue Rocks vs. Red Sox
DESCRIPTION:Blue Rocks vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wXbS-32\n\nShop: https://stza.co/+wXbS-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Astros
<2018-07-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       qyD-CQ_6B0fQCyy4_k2vMydc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Astros Blue Rocks vs. Astros

Follow on MiLB First Pitch  https //stza.co/+wXbV-c

Shop  https //stza.co/+wXbV-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Astros
END:VALARM
DTSTART:20180727T230500Z
DTEND:20180728T020500Z
UID:qyD-CQ_6B0fQCyy4_k2vMydc@stanza.co
SUMMARY:Blue Rocks vs. Astros
DESCRIPTION:Blue Rocks vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+wXbV-c\n\nShop: https://stza.co/+wXbV-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Astros
<2018-07-28 Sat 17:05-20:05>
:PROPERTIES:
:ID:       ltnR_MgO5gaQgnGezkUbbdLZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Astros Blue Rocks vs. Astros

Follow on MiLB First Pitch  https //stza.co/+wXbX-2z

Shop  https //stza.co/+wXbX-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Astros
END:VALARM
DTSTART:20180728T220500Z
DTEND:20180729T010500Z
UID:ltnR_MgO5gaQgnGezkUbbdLZ@stanza.co
SUMMARY:Blue Rocks vs. Astros
DESCRIPTION:Blue Rocks vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+wXbX-2z\n\nShop: https://stza.co/+wXbX-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Astros
<2018-07-29 Sun 12:35-15:35>
:PROPERTIES:
:ID:       Fuj8PfkgyDQpY_WpJxdiVf6d@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Astros Blue Rocks vs. Astros

Follow on MiLB First Pitch  https //stza.co/+wXbZ-2u

Shop  https //stza.co/+wXbZ-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Astros
END:VALARM
DTSTART:20180729T173500Z
DTEND:20180729T203500Z
UID:Fuj8PfkgyDQpY_WpJxdiVf6d@stanza.co
SUMMARY:Blue Rocks vs. Astros
DESCRIPTION:Blue Rocks vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+wXbZ-2u\n\nShop: https://stza.co/+wXbZ-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Astros
<2018-07-31 Tue 18:00-21:00>
:PROPERTIES:
:ID:       T_-K-A6Y3GPSSmm3FeV6Rklq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Astros Blue Rocks @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM9J-1z

Shop  https //stza.co/+xM9J-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Astros
END:VALARM
DTSTART:20180731T230000Z
DTEND:20180801T020000Z
UID:T_-K-A6Y3GPSSmm3FeV6Rklq@stanza.co
SUMMARY:Blue Rocks @ Astros
DESCRIPTION:Blue Rocks @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM9J-1z\n\nShop: https://stza.co/+xM9J-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Astros
<2018-08-01 Wed 18:00-21:00>
:PROPERTIES:
:ID:       pAXGeNl6GCR1RgJwbDTaeltW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Astros Blue Rocks @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM9K-1c

Shop  https //stza.co/+xM9K-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Astros
END:VALARM
DTSTART:20180801T230000Z
DTEND:20180802T020000Z
UID:pAXGeNl6GCR1RgJwbDTaeltW@stanza.co
SUMMARY:Blue Rocks @ Astros
DESCRIPTION:Blue Rocks @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM9K-1c\n\nShop: https://stza.co/+xM9K-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Astros
<2018-08-02 Thu 18:00-21:00>
:PROPERTIES:
:ID:       Fubb0Dh-m9JpWU-rYB8-gETp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Astros Blue Rocks @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM9L-3u

Shop  https //stza.co/+xM9L-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Astros
END:VALARM
DTSTART:20180802T230000Z
DTEND:20180803T020000Z
UID:Fubb0Dh-m9JpWU-rYB8-gETp@stanza.co
SUMMARY:Blue Rocks @ Astros
DESCRIPTION:Blue Rocks @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM9L-3u\n\nShop: https://stza.co/+xM9L-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Keys
<2018-08-03 Fri 18:05-21:05>
:PROPERTIES:
:ID:       qgq5OGpiekpZ2DRTG9aij4XD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Keys Blue Rocks vs. Keys

Follow on MiLB First Pitch  https //stza.co/+wXb$-1k

Shop  https //stza.co/+wXb$-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Keys
END:VALARM
DTSTART:20180803T230500Z
DTEND:20180804T020500Z
UID:qgq5OGpiekpZ2DRTG9aij4XD@stanza.co
SUMMARY:Blue Rocks vs. Keys
DESCRIPTION:Blue Rocks vs. Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wXb$-1k\n\nShop: https://stza.co/+wXb$-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Keys
<2018-08-04 Sat 17:05-20:05>
:PROPERTIES:
:ID:       SnFsZBqO_eWOqCYu4bGR0l1_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Keys Blue Rocks vs. Keys

Follow on MiLB First Pitch  https //stza.co/+wXc2-w

Shop  https //stza.co/+wXc2-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Keys
END:VALARM
DTSTART:20180804T220500Z
DTEND:20180805T010500Z
UID:SnFsZBqO_eWOqCYu4bGR0l1_@stanza.co
SUMMARY:Blue Rocks vs. Keys
DESCRIPTION:Blue Rocks vs. Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wXc2-w\n\nShop: https://stza.co/+wXc2-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Keys
<2018-08-05 Sun 12:35-15:35>
:PROPERTIES:
:ID:       3bYKfFwwYqdOGPa96y2HZH4h@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Keys Blue Rocks vs. Keys

Follow on MiLB First Pitch  https //stza.co/+wXc5-3s

Shop  https //stza.co/+wXc5-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Keys
END:VALARM
DTSTART:20180805T173500Z
DTEND:20180805T203500Z
UID:3bYKfFwwYqdOGPa96y2HZH4h@stanza.co
SUMMARY:Blue Rocks vs. Keys
DESCRIPTION:Blue Rocks vs. Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wXc5-3s\n\nShop: https://stza.co/+wXc5-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Red Sox
<2018-08-07 Tue>--<2018-08-06 Mon>
:PROPERTIES:
:ID:       VTmlW0lw8WTedEjdbuB2ejYV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Red Sox Blue Rocks @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0I7-2K

Shop  https //stza.co/+w0I7-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180807
DTEND;VALUE=DATE:20180807
UID:VTmlW0lw8WTedEjdbuB2ejYV@stanza.co
SUMMARY:Blue Rocks @ Red Sox
DESCRIPTION:Blue Rocks @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0I7-2K\n\nShop: https://stza.co/+w0I7-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Red Sox
<2018-08-08 Wed>--<2018-08-07 Tue>
:PROPERTIES:
:ID:       arK4XQM14MbmUfZBNGzIDBF-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Red Sox Blue Rocks @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0I8-36

Shop  https //stza.co/+w0I8-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180808
DTEND;VALUE=DATE:20180808
UID:arK4XQM14MbmUfZBNGzIDBF-@stanza.co
SUMMARY:Blue Rocks @ Red Sox
DESCRIPTION:Blue Rocks @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0I8-36\n\nShop: https://stza.co/+w0I8-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Red Sox
<2018-08-09 Thu>--<2018-08-08 Wed>
:PROPERTIES:
:ID:       DdDg3AKEWoV6ral7coah5CoN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Red Sox Blue Rocks @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0I9-2p

Shop  https //stza.co/+w0I9-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180809
DTEND;VALUE=DATE:20180809
UID:DdDg3AKEWoV6ral7coah5CoN@stanza.co
SUMMARY:Blue Rocks @ Red Sox
DESCRIPTION:Blue Rocks @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0I9-2p\n\nShop: https://stza.co/+w0I9-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Pelicans
<2018-08-10 Fri>--<2018-08-09 Thu>
:PROPERTIES:
:ID:       WrrXSIwfFMMnNXtM4LPgt-C1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Pelicans Blue Rocks @ Pelicans

Follow on MiLB First Pitch  https //stza.co/+w0HI-3T

Shop  https //stza.co/+w0HI-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Pelicans
END:VALARM
DTSTART;VALUE=DATE:20180810
DTEND;VALUE=DATE:20180810
UID:WrrXSIwfFMMnNXtM4LPgt-C1@stanza.co
SUMMARY:Blue Rocks @ Pelicans
DESCRIPTION:Blue Rocks @ Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+w0HI-3T\n\nShop: https://stza.co/+w0HI-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Pelicans
<2018-08-11 Sat>--<2018-08-10 Fri>
:PROPERTIES:
:ID:       psFL8AN9eeIpSc8BHdm0nB_Y@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Pelicans Blue Rocks @ Pelicans

Follow on MiLB First Pitch  https //stza.co/+w0HJ-15

Shop  https //stza.co/+w0HJ-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Pelicans
END:VALARM
DTSTART;VALUE=DATE:20180811
DTEND;VALUE=DATE:20180811
UID:psFL8AN9eeIpSc8BHdm0nB_Y@stanza.co
SUMMARY:Blue Rocks @ Pelicans
DESCRIPTION:Blue Rocks @ Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+w0HJ-15\n\nShop: https://stza.co/+w0HJ-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Pelicans
<2018-08-12 Sun>--<2018-08-11 Sat>
:PROPERTIES:
:ID:       P1ER3LoP3EGVGlg3Wp76CVpe@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Pelicans Blue Rocks @ Pelicans

Follow on MiLB First Pitch  https //stza.co/+w0HK-2V

Shop  https //stza.co/+w0HK-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Pelicans
END:VALARM
DTSTART;VALUE=DATE:20180812
DTEND;VALUE=DATE:20180812
UID:P1ER3LoP3EGVGlg3Wp76CVpe@stanza.co
SUMMARY:Blue Rocks @ Pelicans
DESCRIPTION:Blue Rocks @ Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+w0HK-2V\n\nShop: https://stza.co/+w0HK-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Hillcats
<2018-08-14 Tue 17:35-20:35>
:PROPERTIES:
:ID:       JqZwm0A1GRm8Bhee0dFUZrIF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Hillcats Blue Rocks vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+wXc6-3G

Shop  https //stza.co/+wXc6-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Hillcats
END:VALARM
DTSTART:20180814T223500Z
DTEND:20180815T013500Z
UID:JqZwm0A1GRm8Bhee0dFUZrIF@stanza.co
SUMMARY:Blue Rocks vs. Hillcats
DESCRIPTION:Blue Rocks vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+wXc6-3G\n\nShop: https://stza.co/+wXc6-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Hillcats
<2018-08-15 Wed 17:35-20:35>
:PROPERTIES:
:ID:       Ux_87J82qKFfZEXpSWh_eVeS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Hillcats Blue Rocks vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+wXc9-3J

Shop  https //stza.co/+wXc9-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Hillcats
END:VALARM
DTSTART:20180815T223500Z
DTEND:20180816T013500Z
UID:Ux_87J82qKFfZEXpSWh_eVeS@stanza.co
SUMMARY:Blue Rocks vs. Hillcats
DESCRIPTION:Blue Rocks vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+wXc9-3J\n\nShop: https://stza.co/+wXc9-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Hillcats
<2018-08-16 Thu 17:35-20:35>
:PROPERTIES:
:ID:       DVXCm0h9_9w7u44Aay5IrP5k@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Hillcats Blue Rocks vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+wXca-3z

Shop  https //stza.co/+wXca-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Hillcats
END:VALARM
DTSTART:20180816T223500Z
DTEND:20180817T013500Z
UID:DVXCm0h9_9w7u44Aay5IrP5k@stanza.co
SUMMARY:Blue Rocks vs. Hillcats
DESCRIPTION:Blue Rocks vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+wXca-3z\n\nShop: https://stza.co/+wXca-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Dash
<2018-08-17 Fri 18:00-21:00>
:PROPERTIES:
:ID:       0NDW9G3_EiJdIybAfhU0MMv3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Dash Blue Rocks @ Dash

Buy tickets here  https //stza.co/~w0Kq

Follow on MiLB First Pitch  https //stza.co/+w0Kq-12

Shop  https //stza.co/+w0Kq-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Dash
END:VALARM
DTSTART:20180817T230000Z
DTEND:20180818T020000Z
UID:0NDW9G3_EiJdIybAfhU0MMv3@stanza.co
SUMMARY:Blue Rocks @ Dash
DESCRIPTION:Blue Rocks @ Dash\n\nBuy tickets here: https://stza.co/~w0Kq\n\nFollow on MiLB First Pitch: https://stza.co/+w0Kq-12\n\nShop: https://stza.co/+w0Kq-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Dash
<2018-08-18 Sat 17:00-20:00>
:PROPERTIES:
:ID:       cCGElsMMUlHZqk-zlu4IKsaS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Dash Blue Rocks @ Dash

Buy tickets here  https //stza.co/~w0Kr

Follow on MiLB First Pitch  https //stza.co/+w0Kr-2y

Shop  https //stza.co/+w0Kr-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Dash
END:VALARM
DTSTART:20180818T220000Z
DTEND:20180819T010000Z
UID:cCGElsMMUlHZqk-zlu4IKsaS@stanza.co
SUMMARY:Blue Rocks @ Dash
DESCRIPTION:Blue Rocks @ Dash\n\nBuy tickets here: https://stza.co/~w0Kr\n\nFollow on MiLB First Pitch: https://stza.co/+w0Kr-2y\n\nShop: https://stza.co/+w0Kr-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Dash
<2018-08-19 Sun 13:00-16:00>
:PROPERTIES:
:ID:       zldzlgEJW7IyVPqACNWPosfH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Dash Blue Rocks @ Dash

Buy tickets here  https //stza.co/~w0Ks

Follow on MiLB First Pitch  https //stza.co/+w0Ks-i

Shop  https //stza.co/+w0Ks-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Dash
END:VALARM
DTSTART:20180819T180000Z
DTEND:20180819T210000Z
UID:zldzlgEJW7IyVPqACNWPosfH@stanza.co
SUMMARY:Blue Rocks @ Dash
DESCRIPTION:Blue Rocks @ Dash\n\nBuy tickets here: https://stza.co/~w0Ks\n\nFollow on MiLB First Pitch: https://stza.co/+w0Ks-i\n\nShop: https://stza.co/+w0Ks-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Wood Ducks
<2018-08-20 Mon 17:35-20:35>
:PROPERTIES:
:ID:       hT0gAvVLawg5rwLxeSrYXIcY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Wood Ducks Blue Rocks vs. Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+wXce-2_

Shop  https //stza.co/+wXce-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Wood Ducks
END:VALARM
DTSTART:20180820T223500Z
DTEND:20180821T013500Z
UID:hT0gAvVLawg5rwLxeSrYXIcY@stanza.co
SUMMARY:Blue Rocks vs. Wood Ducks
DESCRIPTION:Blue Rocks vs. Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+wXce-2_\n\nShop: https://stza.co/+wXce-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Wood Ducks
<2018-08-21 Tue 17:35-20:35>
:PROPERTIES:
:ID:       PeWOJyWnp7yXoO6FHEgDjjGY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Wood Ducks Blue Rocks vs. Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+wXcg-2h

Shop  https //stza.co/+wXcg-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Wood Ducks
END:VALARM
DTSTART:20180821T223500Z
DTEND:20180822T013500Z
UID:PeWOJyWnp7yXoO6FHEgDjjGY@stanza.co
SUMMARY:Blue Rocks vs. Wood Ducks
DESCRIPTION:Blue Rocks vs. Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+wXcg-2h\n\nShop: https://stza.co/+wXcg-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Wood Ducks
<2018-08-22 Wed 17:35-20:35>
:PROPERTIES:
:ID:       o89rXC2IiMADmyFMSRPYtyup@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Wood Ducks Blue Rocks vs. Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+wXcj-l

Shop  https //stza.co/+wXcj-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Wood Ducks
END:VALARM
DTSTART:20180822T223500Z
DTEND:20180823T013500Z
UID:o89rXC2IiMADmyFMSRPYtyup@stanza.co
SUMMARY:Blue Rocks vs. Wood Ducks
DESCRIPTION:Blue Rocks vs. Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+wXcj-l\n\nShop: https://stza.co/+wXcj-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Red Sox
<2018-08-24 Fri 18:05-21:05>
:PROPERTIES:
:ID:       THm-Nv6KGRGsFiKDb5M4Oled@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Red Sox Blue Rocks vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+wXcl-1J

Shop  https //stza.co/+wXcl-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Red Sox
END:VALARM
DTSTART:20180824T230500Z
DTEND:20180825T020500Z
UID:THm-Nv6KGRGsFiKDb5M4Oled@stanza.co
SUMMARY:Blue Rocks vs. Red Sox
DESCRIPTION:Blue Rocks vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wXcl-1J\n\nShop: https://stza.co/+wXcl-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Red Sox
<2018-08-25 Sat 17:05-20:05>
:PROPERTIES:
:ID:       I7bGbYdb08ydLbofimecvlSo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Red Sox Blue Rocks vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+wXcn-18

Shop  https //stza.co/+wXcn-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Red Sox
END:VALARM
DTSTART:20180825T220500Z
DTEND:20180826T010500Z
UID:I7bGbYdb08ydLbofimecvlSo@stanza.co
SUMMARY:Blue Rocks vs. Red Sox
DESCRIPTION:Blue Rocks vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wXcn-18\n\nShop: https://stza.co/+wXcn-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Red Sox
<2018-08-26 Sun 12:35-15:35>
:PROPERTIES:
:ID:       0FPJEOxWWozzrZnHFPeW7-jW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Red Sox Blue Rocks vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+wXco-25

Shop  https //stza.co/+wXco-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Red Sox
END:VALARM
DTSTART:20180826T173500Z
DTEND:20180826T203500Z
UID:0FPJEOxWWozzrZnHFPeW7-jW@stanza.co
SUMMARY:Blue Rocks vs. Red Sox
DESCRIPTION:Blue Rocks vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wXco-25\n\nShop: https://stza.co/+wXco-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Hillcats
<2018-08-27 Mon 17:30-20:30>
:PROPERTIES:
:ID:       XgwSxYCfg7fxJdbvCTmINLr0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Hillcats Blue Rocks @ Hillcats

Buy tickets here  https //stza.co/~y3Wp

Follow on MiLB First Pitch  https //stza.co/+y3Wp-2

Shop  https //stza.co/+y3Wp-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Hillcats
END:VALARM
DTSTART:20180827T223000Z
DTEND:20180828T013000Z
UID:XgwSxYCfg7fxJdbvCTmINLr0@stanza.co
SUMMARY:Blue Rocks @ Hillcats
DESCRIPTION:Blue Rocks @ Hillcats\n\nBuy tickets here: https://stza.co/~y3Wp\n\nFollow on MiLB First Pitch: https://stza.co/+y3Wp-2\n\nShop: https://stza.co/+y3Wp-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Hillcats
<2018-08-28 Tue 17:30-20:30>
:PROPERTIES:
:ID:       9mp5FERiS7vMAxKtfdDffgv-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Hillcats Blue Rocks @ Hillcats

Buy tickets here  https //stza.co/~y3Wq

Follow on MiLB First Pitch  https //stza.co/+y3Wq-38

Shop  https //stza.co/+y3Wq-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Hillcats
END:VALARM
DTSTART:20180828T223000Z
DTEND:20180829T013000Z
UID:9mp5FERiS7vMAxKtfdDffgv-@stanza.co
SUMMARY:Blue Rocks @ Hillcats
DESCRIPTION:Blue Rocks @ Hillcats\n\nBuy tickets here: https://stza.co/~y3Wq\n\nFollow on MiLB First Pitch: https://stza.co/+y3Wq-38\n\nShop: https://stza.co/+y3Wq-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Hillcats
<2018-08-29 Wed 17:30-20:30>
:PROPERTIES:
:ID:       htio3uFmmmzLGsELWizWn3bo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Hillcats Blue Rocks @ Hillcats

Buy tickets here  https //stza.co/~y3Wr

Follow on MiLB First Pitch  https //stza.co/+y3Wr-2e

Shop  https //stza.co/+y3Wr-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Hillcats
END:VALARM
DTSTART:20180829T223000Z
DTEND:20180830T013000Z
UID:htio3uFmmmzLGsELWizWn3bo@stanza.co
SUMMARY:Blue Rocks @ Hillcats
DESCRIPTION:Blue Rocks @ Hillcats\n\nBuy tickets here: https://stza.co/~y3Wr\n\nFollow on MiLB First Pitch: https://stza.co/+y3Wr-2e\n\nShop: https://stza.co/+y3Wr-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks @ Hillcats
<2018-08-30 Thu 17:30-20:30>
:PROPERTIES:
:ID:       Meyl3P5cSftYBFaQ-hX0cTyy@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks @ Hillcats Blue Rocks @ Hillcats

Buy tickets here  https //stza.co/~y3Ws

Follow on MiLB First Pitch  https //stza.co/+y3Ws-2_

Shop  https //stza.co/+y3Ws-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks @ Hillcats
END:VALARM
DTSTART:20180830T223000Z
DTEND:20180831T013000Z
UID:Meyl3P5cSftYBFaQ-hX0cTyy@stanza.co
SUMMARY:Blue Rocks @ Hillcats
DESCRIPTION:Blue Rocks @ Hillcats\n\nBuy tickets here: https://stza.co/~y3Ws\n\nFollow on MiLB First Pitch: https://stza.co/+y3Ws-2_\n\nShop: https://stza.co/+y3Ws-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Nationals
<2018-08-31 Fri 18:05-21:05>
:PROPERTIES:
:ID:       xZNKcE8P_S2ZW-7iDqEuyc-V@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Nationals Blue Rocks vs. Nationals

Follow on MiLB First Pitch  https //stza.co/+wXcq-2m

Shop  https //stza.co/+wXcq-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Nationals
END:VALARM
DTSTART:20180831T230500Z
DTEND:20180901T020500Z
UID:xZNKcE8P_S2ZW-7iDqEuyc-V@stanza.co
SUMMARY:Blue Rocks vs. Nationals
DESCRIPTION:Blue Rocks vs. Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+wXcq-2m\n\nShop: https://stza.co/+wXcq-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Nationals
<2018-09-01 Sat 17:05-20:05>
:PROPERTIES:
:ID:       1XLqtj85YU8aNY1qGuGB0sCb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Nationals Blue Rocks vs. Nationals

Follow on MiLB First Pitch  https //stza.co/+wXct-3w

Shop  https //stza.co/+wXct-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Nationals
END:VALARM
DTSTART:20180901T220500Z
DTEND:20180902T010500Z
UID:1XLqtj85YU8aNY1qGuGB0sCb@stanza.co
SUMMARY:Blue Rocks vs. Nationals
DESCRIPTION:Blue Rocks vs. Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+wXct-3w\n\nShop: https://stza.co/+wXct-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Nationals
<2018-09-02 Sun 12:35-15:35>
:PROPERTIES:
:ID:       h9jOtViNmztZ-4j1Nz30sjeK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Nationals Blue Rocks vs. Nationals

Follow on MiLB First Pitch  https //stza.co/+wXcw-2V

Shop  https //stza.co/+wXcw-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Nationals
END:VALARM
DTSTART:20180902T173500Z
DTEND:20180902T203500Z
UID:h9jOtViNmztZ-4j1Nz30sjeK@stanza.co
SUMMARY:Blue Rocks vs. Nationals
DESCRIPTION:Blue Rocks vs. Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+wXcw-2V\n\nShop: https://stza.co/+wXcw-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Blue Rocks vs. Nationals
<2018-09-03 Mon 11:05-14:05>
:PROPERTIES:
:ID:       034qRY16FUEdLi9wQPPpcbSA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Rocks vs. Nationals Blue Rocks vs. Nationals

Follow on MiLB First Pitch  https //stza.co/+wXcy-1o

Shop  https //stza.co/+wXcy-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Rocks vs. Nationals
END:VALARM
DTSTART:20180903T160500Z
DTEND:20180903T190500Z
UID:034qRY16FUEdLi9wQPPpcbSA@stanza.co
SUMMARY:Blue Rocks vs. Nationals
DESCRIPTION:Blue Rocks vs. Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+wXcy-1o\n\nShop: https://stza.co/+wXcy-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
