#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Twins vs. Royals
<2018-06-19 Tue>--<2018-06-18 Mon>
:PROPERTIES:
:ID:       zxCoNffmLV75eaCRD1yN8viA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins vs. Royals Twins vs. Royals

Follow on MiLB First Pitch  https //stza.co/+xCdy-3V

Shop  https //stza.co/+xCdy-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Royals
END:VALARM
DTSTART;VALUE=DATE:20180619
DTEND;VALUE=DATE:20180619
UID:zxCoNffmLV75eaCRD1yN8viA@stanza.co
SUMMARY:Twins vs. Royals
DESCRIPTION:Twins vs. Royals\n\nFollow on MiLB First Pitch: https://stza.co/+xCdy-3V\n\nShop: https://stza.co/+xCdy-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Royals
<2018-06-20 Wed>--<2018-06-19 Tue>
:PROPERTIES:
:ID:       K1CasTU4Act7krNvKdiEbWlL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Twins vs. Royals Twins vs. Royals

Follow on MiLB First Pitch  https //stza.co/+xCdD-6

Shop  https //stza.co/+xCdD-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Royals
END:VALARM
DTSTART;VALUE=DATE:20180620
DTEND;VALUE=DATE:20180620
UID:K1CasTU4Act7krNvKdiEbWlL@stanza.co
SUMMARY:Twins vs. Royals
DESCRIPTION:Twins vs. Royals\n\nFollow on MiLB First Pitch: https://stza.co/+xCdD-6\n\nShop: https://stza.co/+xCdD-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Royals
<2018-06-21 Thu>--<2018-06-20 Wed>
:PROPERTIES:
:ID:       -tN2XfjAh2Xt907F0ugHtHTv@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins vs. Royals Twins vs. Royals

Follow on MiLB First Pitch  https //stza.co/+xCdE-3L

Shop  https //stza.co/+xCdE-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Royals
END:VALARM
DTSTART;VALUE=DATE:20180621
DTEND;VALUE=DATE:20180621
UID:-tN2XfjAh2Xt907F0ugHtHTv@stanza.co
SUMMARY:Twins vs. Royals
DESCRIPTION:Twins vs. Royals\n\nFollow on MiLB First Pitch: https://stza.co/+xCdE-3L\n\nShop: https://stza.co/+xCdE-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Pirates
<2018-06-22 Fri>--<2018-06-21 Thu>
:PROPERTIES:
:ID:       kBZlFNlSJgnGenJWpwg168cL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins @ Pirates Twins @ Pirates

Follow on MiLB First Pitch  https //stza.co/+xCdJ-1X

Shop  https //stza.co/+xCdJ-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Pirates
END:VALARM
DTSTART;VALUE=DATE:20180622
DTEND;VALUE=DATE:20180622
UID:kBZlFNlSJgnGenJWpwg168cL@stanza.co
SUMMARY:Twins @ Pirates
DESCRIPTION:Twins @ Pirates\n\nFollow on MiLB First Pitch: https://stza.co/+xCdJ-1X\n\nShop: https://stza.co/+xCdJ-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Pirates
<2018-06-23 Sat>--<2018-06-22 Fri>
:PROPERTIES:
:ID:       rNocaHnMEkOItwmXAekvYjJE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Twins @ Pirates Twins @ Pirates

Follow on MiLB First Pitch  https //stza.co/+xCdK-15

Shop  https //stza.co/+xCdK-3_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Pirates
END:VALARM
DTSTART;VALUE=DATE:20180623
DTEND;VALUE=DATE:20180623
UID:rNocaHnMEkOItwmXAekvYjJE@stanza.co
SUMMARY:Twins @ Pirates
DESCRIPTION:Twins @ Pirates\n\nFollow on MiLB First Pitch: https://stza.co/+xCdK-15\n\nShop: https://stza.co/+xCdK-3_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Pirates
<2018-06-24 Sun>--<2018-06-23 Sat>
:PROPERTIES:
:ID:       uJ-fqPah98h6ikQWKIf0yJdS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins @ Pirates Twins @ Pirates

Follow on MiLB First Pitch  https //stza.co/+xCdL-2e

Shop  https //stza.co/+xCdL-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Pirates
END:VALARM
DTSTART;VALUE=DATE:20180624
DTEND;VALUE=DATE:20180624
UID:uJ-fqPah98h6ikQWKIf0yJdS@stanza.co
SUMMARY:Twins @ Pirates
DESCRIPTION:Twins @ Pirates\n\nFollow on MiLB First Pitch: https://stza.co/+xCdL-2e\n\nShop: https://stza.co/+xCdL-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Cardinals
<2018-06-25 Mon>--<2018-06-24 Sun>
:PROPERTIES:
:ID:       GSxkNKG9vfZqQRsomG7xdl7r@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins vs. Cardinals Twins vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xCdN-3J

Shop  https //stza.co/+xCdN-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180625
DTEND;VALUE=DATE:20180625
UID:GSxkNKG9vfZqQRsomG7xdl7r@stanza.co
SUMMARY:Twins vs. Cardinals
DESCRIPTION:Twins vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xCdN-3J\n\nShop: https://stza.co/+xCdN-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Cardinals
<2018-06-26 Tue>--<2018-06-25 Mon>
:PROPERTIES:
:ID:       20T4NVN-U1v-kWECb3LQ5gzB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Twins vs. Cardinals Twins vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xCdQ-3Q

Shop  https //stza.co/+xCdQ-1J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180626
DTEND;VALUE=DATE:20180626
UID:20T4NVN-U1v-kWECb3LQ5gzB@stanza.co
SUMMARY:Twins vs. Cardinals
DESCRIPTION:Twins vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xCdQ-3Q\n\nShop: https://stza.co/+xCdQ-1J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Braves
<2018-06-28 Thu 18:00-21:00>
:PROPERTIES:
:ID:       _HlfDAA5Y0y06N_JY9kUZQoa@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins @ Braves Twins @ Braves

Follow on MiLB First Pitch  https //stza.co/+xDTE-1z

Shop  https //stza.co/+xDTE-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Braves
END:VALARM
DTSTART:20180628T230000Z
DTEND:20180629T020000Z
UID:_HlfDAA5Y0y06N_JY9kUZQoa@stanza.co
SUMMARY:Twins @ Braves
DESCRIPTION:Twins @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xDTE-1z\n\nShop: https://stza.co/+xDTE-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Braves
<2018-06-29 Fri 18:00-21:00>
:PROPERTIES:
:ID:       RLL4gwzbt58mbGAjH0lmZt1F@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins @ Braves Twins @ Braves

Follow on MiLB First Pitch  https //stza.co/+xDTF-2X

Shop  https //stza.co/+xDTF-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Braves
END:VALARM
DTSTART:20180629T230000Z
DTEND:20180630T020000Z
UID:RLL4gwzbt58mbGAjH0lmZt1F@stanza.co
SUMMARY:Twins @ Braves
DESCRIPTION:Twins @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xDTF-2X\n\nShop: https://stza.co/+xDTF-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Braves
<2018-06-30 Sat 18:00-21:00>
:PROPERTIES:
:ID:       _TQk8Jp7xBk4hrdrG0szgKfh@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Twins @ Braves Twins @ Braves

Follow on MiLB First Pitch  https //stza.co/+xDTH-2Z

Shop  https //stza.co/+xDTH-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Braves
END:VALARM
DTSTART:20180630T230000Z
DTEND:20180701T020000Z
UID:_TQk8Jp7xBk4hrdrG0szgKfh@stanza.co
SUMMARY:Twins @ Braves
DESCRIPTION:Twins @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xDTH-2Z\n\nShop: https://stza.co/+xDTH-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Rays
<2018-07-01 Sun>--<2018-06-30 Sat>
:PROPERTIES:
:ID:       ItH5C-1g7SrJsARyDOwoP9yA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins @ Rays Twins @ Rays

Follow on MiLB First Pitch  https //stza.co/+xCd_-32

Shop  https //stza.co/+xCd_-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Rays
END:VALARM
DTSTART;VALUE=DATE:20180701
DTEND;VALUE=DATE:20180701
UID:ItH5C-1g7SrJsARyDOwoP9yA@stanza.co
SUMMARY:Twins @ Rays
DESCRIPTION:Twins @ Rays\n\nFollow on MiLB First Pitch: https://stza.co/+xCd_-32\n\nShop: https://stza.co/+xCd_-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Rays
<2018-07-02 Mon>--<2018-07-01 Sun>
:PROPERTIES:
:ID:       DibQ9nhz48_LwOJF7Uz31xnG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins @ Rays Twins @ Rays

Follow on MiLB First Pitch  https //stza.co/+xCd$-2A

Shop  https //stza.co/+xCd$-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Rays
END:VALARM
DTSTART;VALUE=DATE:20180702
DTEND;VALUE=DATE:20180702
UID:DibQ9nhz48_LwOJF7Uz31xnG@stanza.co
SUMMARY:Twins @ Rays
DESCRIPTION:Twins @ Rays\n\nFollow on MiLB First Pitch: https://stza.co/+xCd$-2A\n\nShop: https://stza.co/+xCd$-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Rays
<2018-07-03 Tue>--<2018-07-02 Mon>
:PROPERTIES:
:ID:       i4eNPHwVuQ0-loX0cCyRJx8t@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Twins @ Rays Twins @ Rays

Follow on MiLB First Pitch  https //stza.co/+xCe0-M

Shop  https //stza.co/+xCe0-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Rays
END:VALARM
DTSTART;VALUE=DATE:20180703
DTEND;VALUE=DATE:20180703
UID:i4eNPHwVuQ0-loX0cCyRJx8t@stanza.co
SUMMARY:Twins @ Rays
DESCRIPTION:Twins @ Rays\n\nFollow on MiLB First Pitch: https://stza.co/+xCe0-M\n\nShop: https://stza.co/+xCe0-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Mets
<2018-07-04 Wed>--<2018-07-03 Tue>
:PROPERTIES:
:ID:       2zPLGS6XGS08Kczj2CsLijdq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins vs. Mets Twins vs. Mets

Follow on MiLB First Pitch  https //stza.co/+xCe1-O

Shop  https //stza.co/+xCe1-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Mets
END:VALARM
DTSTART;VALUE=DATE:20180704
DTEND;VALUE=DATE:20180704
UID:2zPLGS6XGS08Kczj2CsLijdq@stanza.co
SUMMARY:Twins vs. Mets
DESCRIPTION:Twins vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xCe1-O\n\nShop: https://stza.co/+xCe1-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Mets
<2018-07-05 Thu>--<2018-07-04 Wed>
:PROPERTIES:
:ID:       An4C4_oHga-wudd57lR9Q-rC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins vs. Mets Twins vs. Mets

Follow on MiLB First Pitch  https //stza.co/+xCe3-L

Shop  https //stza.co/+xCe3-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Mets
END:VALARM
DTSTART;VALUE=DATE:20180705
DTEND;VALUE=DATE:20180705
UID:An4C4_oHga-wudd57lR9Q-rC@stanza.co
SUMMARY:Twins vs. Mets
DESCRIPTION:Twins vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xCe3-L\n\nShop: https://stza.co/+xCe3-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Mets
<2018-07-06 Fri>--<2018-07-05 Thu>
:PROPERTIES:
:ID:       exZY5_5wIhVA6FQ1Jw29a4o4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Twins vs. Mets Twins vs. Mets

Follow on MiLB First Pitch  https //stza.co/+xCe6-2M

Shop  https //stza.co/+xCe6-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Mets
END:VALARM
DTSTART;VALUE=DATE:20180706
DTEND;VALUE=DATE:20180706
UID:exZY5_5wIhVA6FQ1Jw29a4o4@stanza.co
SUMMARY:Twins vs. Mets
DESCRIPTION:Twins vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xCe6-2M\n\nShop: https://stza.co/+xCe6-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Braves
<2018-07-07 Sat>--<2018-07-06 Fri>
:PROPERTIES:
:ID:       rl2KJgMa3U8UEVAqoiyoftJX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins vs. Braves Twins vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xCe8-3w

Shop  https //stza.co/+xCe8-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Braves
END:VALARM
DTSTART;VALUE=DATE:20180707
DTEND;VALUE=DATE:20180707
UID:rl2KJgMa3U8UEVAqoiyoftJX@stanza.co
SUMMARY:Twins vs. Braves
DESCRIPTION:Twins vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xCe8-3w\n\nShop: https://stza.co/+xCe8-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Braves
<2018-07-08 Sun>--<2018-07-07 Sat>
:PROPERTIES:
:ID:       6YI7MPbUDMBjpzJDS05q2KGw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins vs. Braves Twins vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xCeb-1M

Shop  https //stza.co/+xCeb-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Braves
END:VALARM
DTSTART;VALUE=DATE:20180708
DTEND;VALUE=DATE:20180708
UID:6YI7MPbUDMBjpzJDS05q2KGw@stanza.co
SUMMARY:Twins vs. Braves
DESCRIPTION:Twins vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xCeb-1M\n\nShop: https://stza.co/+xCeb-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Braves
<2018-07-09 Mon>--<2018-07-08 Sun>
:PROPERTIES:
:ID:       gQqGmaKcBikHSNwBl80Y1DQk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Twins vs. Braves Twins vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xCee-35

Shop  https //stza.co/+xCee-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Braves
END:VALARM
DTSTART;VALUE=DATE:20180709
DTEND;VALUE=DATE:20180709
UID:gQqGmaKcBikHSNwBl80Y1DQk@stanza.co
SUMMARY:Twins vs. Braves
DESCRIPTION:Twins vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xCee-35\n\nShop: https://stza.co/+xCee-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Cardinals
<2018-07-10 Tue>--<2018-07-09 Mon>
:PROPERTIES:
:ID:       HT71yvNNy79g6enzDbM-6ulT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins @ Cardinals Twins @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+xCef-2o

Shop  https //stza.co/+xCef-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180710
DTEND;VALUE=DATE:20180710
UID:HT71yvNNy79g6enzDbM-6ulT@stanza.co
SUMMARY:Twins @ Cardinals
DESCRIPTION:Twins @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xCef-2o\n\nShop: https://stza.co/+xCef-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Cardinals
<2018-07-11 Wed>--<2018-07-10 Tue>
:PROPERTIES:
:ID:       6-dX4Kaj2_m-wwrZAKTxpayP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins @ Cardinals Twins @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+xCeh-3C

Shop  https //stza.co/+xCeh-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180711
DTEND;VALUE=DATE:20180711
UID:6-dX4Kaj2_m-wwrZAKTxpayP@stanza.co
SUMMARY:Twins @ Cardinals
DESCRIPTION:Twins @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xCeh-3C\n\nShop: https://stza.co/+xCeh-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Cardinals
<2018-07-12 Thu>--<2018-07-11 Wed>
:PROPERTIES:
:ID:       g9OvhlGbMhPys0UdcN-KGqka@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Twins @ Cardinals Twins @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+xCej-37

Shop  https //stza.co/+xCej-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180712
DTEND;VALUE=DATE:20180712
UID:g9OvhlGbMhPys0UdcN-KGqka@stanza.co
SUMMARY:Twins @ Cardinals
DESCRIPTION:Twins @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xCej-37\n\nShop: https://stza.co/+xCej-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Cardinals
<2018-07-13 Fri>--<2018-07-12 Thu>
:PROPERTIES:
:ID:       oZsCI-VMthRTrBuQnZQl6DMP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins @ Cardinals Twins @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+xCem-c

Shop  https //stza.co/+xCem-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180713
DTEND;VALUE=DATE:20180713
UID:oZsCI-VMthRTrBuQnZQl6DMP@stanza.co
SUMMARY:Twins @ Cardinals
DESCRIPTION:Twins @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xCem-c\n\nShop: https://stza.co/+xCem-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Mets
<2018-07-14 Sat>--<2018-07-13 Fri>
:PROPERTIES:
:ID:       kxQk7hy3I3up9jHhiyhlr7y6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins @ Mets Twins @ Mets

Follow on MiLB First Pitch  https //stza.co/+xCeo-Y

Shop  https //stza.co/+xCeo-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Mets
END:VALARM
DTSTART;VALUE=DATE:20180714
DTEND;VALUE=DATE:20180714
UID:kxQk7hy3I3up9jHhiyhlr7y6@stanza.co
SUMMARY:Twins @ Mets
DESCRIPTION:Twins @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xCeo-Y\n\nShop: https://stza.co/+xCeo-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Mets
<2018-07-15 Sun>--<2018-07-14 Sat>
:PROPERTIES:
:ID:       p4EgudjwI6E9EQXaHwxbiO-s@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Twins @ Mets Twins @ Mets

Follow on MiLB First Pitch  https //stza.co/+xCeq-2K

Shop  https //stza.co/+xCeq-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Mets
END:VALARM
DTSTART;VALUE=DATE:20180715
DTEND;VALUE=DATE:20180715
UID:p4EgudjwI6E9EQXaHwxbiO-s@stanza.co
SUMMARY:Twins @ Mets
DESCRIPTION:Twins @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xCeq-2K\n\nShop: https://stza.co/+xCeq-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Mets
<2018-07-16 Mon>--<2018-07-15 Sun>
:PROPERTIES:
:ID:       L0Z0Y9BsrPrEtvAWtTQd1VG7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins @ Mets Twins @ Mets

Follow on MiLB First Pitch  https //stza.co/+xCes-1S

Shop  https //stza.co/+xCes-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Mets
END:VALARM
DTSTART;VALUE=DATE:20180716
DTEND;VALUE=DATE:20180716
UID:L0Z0Y9BsrPrEtvAWtTQd1VG7@stanza.co
SUMMARY:Twins @ Mets
DESCRIPTION:Twins @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xCes-1S\n\nShop: https://stza.co/+xCes-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Astros
<2018-07-18 Wed>--<2018-07-17 Tue>
:PROPERTIES:
:ID:       rTCkVTx9caYJiA3-HxHUrXh6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins vs. Astros Twins vs. Astros

Follow on MiLB First Pitch  https //stza.co/+xCev-2

Shop  https //stza.co/+xCev-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Astros
END:VALARM
DTSTART;VALUE=DATE:20180718
DTEND;VALUE=DATE:20180718
UID:rTCkVTx9caYJiA3-HxHUrXh6@stanza.co
SUMMARY:Twins vs. Astros
DESCRIPTION:Twins vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xCev-2\n\nShop: https://stza.co/+xCev-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Astros
<2018-07-19 Thu>--<2018-07-18 Wed>
:PROPERTIES:
:ID:       2tPyjX7hpnKvOROMKP0LswiT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Twins vs. Astros Twins vs. Astros

Follow on MiLB First Pitch  https //stza.co/+xCez-3i

Shop  https //stza.co/+xCez-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Astros
END:VALARM
DTSTART;VALUE=DATE:20180719
DTEND;VALUE=DATE:20180719
UID:2tPyjX7hpnKvOROMKP0LswiT@stanza.co
SUMMARY:Twins vs. Astros
DESCRIPTION:Twins vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xCez-3i\n\nShop: https://stza.co/+xCez-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Astros
<2018-07-20 Fri>--<2018-07-19 Thu>
:PROPERTIES:
:ID:       j6W1j4DyCZqRrtshAEBMbT0Y@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins vs. Astros Twins vs. Astros

Follow on MiLB First Pitch  https //stza.co/+xCeD-1L

Shop  https //stza.co/+xCeD-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Astros
END:VALARM
DTSTART;VALUE=DATE:20180720
DTEND;VALUE=DATE:20180720
UID:j6W1j4DyCZqRrtshAEBMbT0Y@stanza.co
SUMMARY:Twins vs. Astros
DESCRIPTION:Twins vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xCeD-1L\n\nShop: https://stza.co/+xCeD-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Rays
<2018-07-21 Sat>--<2018-07-20 Fri>
:PROPERTIES:
:ID:       4bt5MaBPr8wzJRf6B6vuS2wM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins vs. Rays Twins vs. Rays

Follow on MiLB First Pitch  https //stza.co/+xCeG-1I

Shop  https //stza.co/+xCeG-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Rays
END:VALARM
DTSTART;VALUE=DATE:20180721
DTEND;VALUE=DATE:20180721
UID:4bt5MaBPr8wzJRf6B6vuS2wM@stanza.co
SUMMARY:Twins vs. Rays
DESCRIPTION:Twins vs. Rays\n\nFollow on MiLB First Pitch: https://stza.co/+xCeG-1I\n\nShop: https://stza.co/+xCeG-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Rays
<2018-07-22 Sun>--<2018-07-21 Sat>
:PROPERTIES:
:ID:       CAsTSuT1hWt_fHDmlw6Ko4Rx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Twins vs. Rays Twins vs. Rays

Follow on MiLB First Pitch  https //stza.co/+xCeI-3

Shop  https //stza.co/+xCeI-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Rays
END:VALARM
DTSTART;VALUE=DATE:20180722
DTEND;VALUE=DATE:20180722
UID:CAsTSuT1hWt_fHDmlw6Ko4Rx@stanza.co
SUMMARY:Twins vs. Rays
DESCRIPTION:Twins vs. Rays\n\nFollow on MiLB First Pitch: https://stza.co/+xCeI-3\n\nShop: https://stza.co/+xCeI-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Rays
<2018-07-23 Mon>--<2018-07-22 Sun>
:PROPERTIES:
:ID:       zRNSSi0N7Q2FFb8_zPCWG4vO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins vs. Rays Twins vs. Rays

Follow on MiLB First Pitch  https //stza.co/+xCeQ-2E

Shop  https //stza.co/+xCeQ-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Rays
END:VALARM
DTSTART;VALUE=DATE:20180723
DTEND;VALUE=DATE:20180723
UID:zRNSSi0N7Q2FFb8_zPCWG4vO@stanza.co
SUMMARY:Twins vs. Rays
DESCRIPTION:Twins vs. Rays\n\nFollow on MiLB First Pitch: https://stza.co/+xCeQ-2E\n\nShop: https://stza.co/+xCeQ-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Royals
<2018-07-24 Tue>--<2018-07-23 Mon>
:PROPERTIES:
:ID:       dYpGtZSyenKem72SFdIp4vsM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins @ Royals Twins @ Royals

Follow on MiLB First Pitch  https //stza.co/+xCeR-n

Shop  https //stza.co/+xCeR-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Royals
END:VALARM
DTSTART;VALUE=DATE:20180724
DTEND;VALUE=DATE:20180724
UID:dYpGtZSyenKem72SFdIp4vsM@stanza.co
SUMMARY:Twins @ Royals
DESCRIPTION:Twins @ Royals\n\nFollow on MiLB First Pitch: https://stza.co/+xCeR-n\n\nShop: https://stza.co/+xCeR-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Royals
<2018-07-25 Wed>--<2018-07-24 Tue>
:PROPERTIES:
:ID:       W9aPrHlwtb6mgAt6P4PUfEcD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Twins @ Royals Twins @ Royals

Follow on MiLB First Pitch  https //stza.co/+xCeS-2y

Shop  https //stza.co/+xCeS-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Royals
END:VALARM
DTSTART;VALUE=DATE:20180725
DTEND;VALUE=DATE:20180725
UID:W9aPrHlwtb6mgAt6P4PUfEcD@stanza.co
SUMMARY:Twins @ Royals
DESCRIPTION:Twins @ Royals\n\nFollow on MiLB First Pitch: https://stza.co/+xCeS-2y\n\nShop: https://stza.co/+xCeS-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Royals
<2018-07-26 Thu>--<2018-07-25 Wed>
:PROPERTIES:
:ID:       MMs0J1mZrIb-95AItGAwFdQy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins @ Royals Twins @ Royals

Follow on MiLB First Pitch  https //stza.co/+xCeT-_

Shop  https //stza.co/+xCeT-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Royals
END:VALARM
DTSTART;VALUE=DATE:20180726
DTEND;VALUE=DATE:20180726
UID:MMs0J1mZrIb-95AItGAwFdQy@stanza.co
SUMMARY:Twins @ Royals
DESCRIPTION:Twins @ Royals\n\nFollow on MiLB First Pitch: https://stza.co/+xCeT-_\n\nShop: https://stza.co/+xCeT-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Pirates
<2018-07-27 Fri>--<2018-07-26 Thu>
:PROPERTIES:
:ID:       ObzTOukXLuWJLBmI5DwGgAjM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins vs. Pirates Twins vs. Pirates

Follow on MiLB First Pitch  https //stza.co/+xCeW-2K

Shop  https //stza.co/+xCeW-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Pirates
END:VALARM
DTSTART;VALUE=DATE:20180727
DTEND;VALUE=DATE:20180727
UID:ObzTOukXLuWJLBmI5DwGgAjM@stanza.co
SUMMARY:Twins vs. Pirates
DESCRIPTION:Twins vs. Pirates\n\nFollow on MiLB First Pitch: https://stza.co/+xCeW-2K\n\nShop: https://stza.co/+xCeW-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Pirates
<2018-07-28 Sat>--<2018-07-27 Fri>
:PROPERTIES:
:ID:       TAaSCIEE2xuh5Rgoflejsn9x@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Twins vs. Pirates Twins vs. Pirates

Follow on MiLB First Pitch  https //stza.co/+xCeZ-13

Shop  https //stza.co/+xCeZ-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Pirates
END:VALARM
DTSTART;VALUE=DATE:20180728
DTEND;VALUE=DATE:20180728
UID:TAaSCIEE2xuh5Rgoflejsn9x@stanza.co
SUMMARY:Twins vs. Pirates
DESCRIPTION:Twins vs. Pirates\n\nFollow on MiLB First Pitch: https://stza.co/+xCeZ-13\n\nShop: https://stza.co/+xCeZ-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Pirates
<2018-07-29 Sun>--<2018-07-28 Sat>
:PROPERTIES:
:ID:       9_HWr9QBPNkupXqZ8VEeKE1d@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins vs. Pirates Twins vs. Pirates

Follow on MiLB First Pitch  https //stza.co/+xCe$-3i

Shop  https //stza.co/+xCe$-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Pirates
END:VALARM
DTSTART;VALUE=DATE:20180729
DTEND;VALUE=DATE:20180729
UID:9_HWr9QBPNkupXqZ8VEeKE1d@stanza.co
SUMMARY:Twins vs. Pirates
DESCRIPTION:Twins vs. Pirates\n\nFollow on MiLB First Pitch: https://stza.co/+xCe$-3i\n\nShop: https://stza.co/+xCe$-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Cardinals
<2018-07-31 Tue>--<2018-07-30 Mon>
:PROPERTIES:
:ID:       IrD-slB1_d8Yt9w0Ar_a8Yh6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins @ Cardinals Twins @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+xCf2-1N

Shop  https //stza.co/+xCf2-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180731
DTEND;VALUE=DATE:20180731
UID:IrD-slB1_d8Yt9w0Ar_a8Yh6@stanza.co
SUMMARY:Twins @ Cardinals
DESCRIPTION:Twins @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xCf2-1N\n\nShop: https://stza.co/+xCf2-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Cardinals
<2018-08-01 Wed>--<2018-07-31 Tue>
:PROPERTIES:
:ID:       vvpZunSJcCFtsc3_9B4gAXCw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Twins @ Cardinals Twins @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+xCf3-H

Shop  https //stza.co/+xCf3-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180801
DTEND;VALUE=DATE:20180801
UID:vvpZunSJcCFtsc3_9B4gAXCw@stanza.co
SUMMARY:Twins @ Cardinals
DESCRIPTION:Twins @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xCf3-H\n\nShop: https://stza.co/+xCf3-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Cardinals
<2018-08-02 Thu>--<2018-08-01 Wed>
:PROPERTIES:
:ID:       v1x01lnUV0bDL9iglwcTAMOB@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins @ Cardinals Twins @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+xCf5-3L

Shop  https //stza.co/+xCf5-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180802
DTEND;VALUE=DATE:20180802
UID:v1x01lnUV0bDL9iglwcTAMOB@stanza.co
SUMMARY:Twins @ Cardinals
DESCRIPTION:Twins @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xCf5-3L\n\nShop: https://stza.co/+xCf5-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Yankees
<2018-08-03 Fri>--<2018-08-02 Thu>
:PROPERTIES:
:ID:       HxMK1bOXImi09P69t-zG2Kr-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins @ Yankees Twins @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xCf7-1$

Shop  https //stza.co/+xCf7-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180803
DTEND;VALUE=DATE:20180803
UID:HxMK1bOXImi09P69t-zG2Kr-@stanza.co
SUMMARY:Twins @ Yankees
DESCRIPTION:Twins @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xCf7-1$\n\nShop: https://stza.co/+xCf7-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Yankees
<2018-08-04 Sat>--<2018-08-03 Fri>
:PROPERTIES:
:ID:       Lt9BjHmJKA1QbYr8waYQQwWE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Twins @ Yankees Twins @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xCf8-36

Shop  https //stza.co/+xCf8-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180804
DTEND;VALUE=DATE:20180804
UID:Lt9BjHmJKA1QbYr8waYQQwWE@stanza.co
SUMMARY:Twins @ Yankees
DESCRIPTION:Twins @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xCf8-36\n\nShop: https://stza.co/+xCf8-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Yankees
<2018-08-05 Sun>--<2018-08-04 Sat>
:PROPERTIES:
:ID:       2_E4Lc50k6lpDjMmgNSYXfow@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins @ Yankees Twins @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xCf9-27

Shop  https //stza.co/+xCf9-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180805
DTEND;VALUE=DATE:20180805
UID:2_E4Lc50k6lpDjMmgNSYXfow@stanza.co
SUMMARY:Twins @ Yankees
DESCRIPTION:Twins @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xCf9-27\n\nShop: https://stza.co/+xCf9-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Mets
<2018-08-06 Mon>--<2018-08-05 Sun>
:PROPERTIES:
:ID:       dcRUM8bJoH5HIuu0qnYFYtF7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins vs. Mets Twins vs. Mets

Follow on MiLB First Pitch  https //stza.co/+xCfd-2_

Shop  https //stza.co/+xCfd-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Mets
END:VALARM
DTSTART;VALUE=DATE:20180806
DTEND;VALUE=DATE:20180806
UID:dcRUM8bJoH5HIuu0qnYFYtF7@stanza.co
SUMMARY:Twins vs. Mets
DESCRIPTION:Twins vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xCfd-2_\n\nShop: https://stza.co/+xCfd-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Mets
<2018-08-07 Tue>--<2018-08-06 Mon>
:PROPERTIES:
:ID:       43lTWyB3Qpx_4i6UUXJ_6m2P@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Twins vs. Mets Twins vs. Mets

Follow on MiLB First Pitch  https //stza.co/+xCff-y

Shop  https //stza.co/+xCff-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Mets
END:VALARM
DTSTART;VALUE=DATE:20180807
DTEND;VALUE=DATE:20180807
UID:43lTWyB3Qpx_4i6UUXJ_6m2P@stanza.co
SUMMARY:Twins vs. Mets
DESCRIPTION:Twins vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xCff-y\n\nShop: https://stza.co/+xCff-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Mets
<2018-08-08 Wed>--<2018-08-07 Tue>
:PROPERTIES:
:ID:       Cz5drl2SVx_ffwC8w72fEjFj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins vs. Mets Twins vs. Mets

Follow on MiLB First Pitch  https //stza.co/+xCfh-1N

Shop  https //stza.co/+xCfh-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Mets
END:VALARM
DTSTART;VALUE=DATE:20180808
DTEND;VALUE=DATE:20180808
UID:Cz5drl2SVx_ffwC8w72fEjFj@stanza.co
SUMMARY:Twins vs. Mets
DESCRIPTION:Twins vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xCfh-1N\n\nShop: https://stza.co/+xCfh-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Blue Jays
<2018-08-09 Thu>--<2018-08-08 Wed>
:PROPERTIES:
:ID:       jQ_9Xbnf9v42FjBtMjelTpbA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins vs. Blue Jays Twins vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xCfk-

Shop  https //stza.co/+xCfk-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Blue Jays
END:VALARM
DTSTART;VALUE=DATE:20180809
DTEND;VALUE=DATE:20180809
UID:jQ_9Xbnf9v42FjBtMjelTpbA@stanza.co
SUMMARY:Twins vs. Blue Jays
DESCRIPTION:Twins vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xCfk-\n\nShop: https://stza.co/+xCfk-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Blue Jays
<2018-08-10 Fri>--<2018-08-09 Thu>
:PROPERTIES:
:ID:       2DTOu3PrcrBvmgdbzpcBuCQP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Twins vs. Blue Jays Twins vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xCfm-

Shop  https //stza.co/+xCfm-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Blue Jays
END:VALARM
DTSTART;VALUE=DATE:20180810
DTEND;VALUE=DATE:20180810
UID:2DTOu3PrcrBvmgdbzpcBuCQP@stanza.co
SUMMARY:Twins vs. Blue Jays
DESCRIPTION:Twins vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xCfm-\n\nShop: https://stza.co/+xCfm-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Blue Jays
<2018-08-11 Sat>--<2018-08-10 Fri>
:PROPERTIES:
:ID:       NaJwAPsLSN_fqHl_K1qUiv29@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins vs. Blue Jays Twins vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xCfr-1l

Shop  https //stza.co/+xCfr-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Blue Jays
END:VALARM
DTSTART;VALUE=DATE:20180811
DTEND;VALUE=DATE:20180811
UID:NaJwAPsLSN_fqHl_K1qUiv29@stanza.co
SUMMARY:Twins vs. Blue Jays
DESCRIPTION:Twins vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xCfr-1l\n\nShop: https://stza.co/+xCfr-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Astros
<2018-08-12 Sun>--<2018-08-11 Sat>
:PROPERTIES:
:ID:       zthC2obz0jMwCupt8GHnA8L6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins @ Astros Twins @ Astros

Follow on MiLB First Pitch  https //stza.co/+xCft-37

Shop  https //stza.co/+xCft-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Astros
END:VALARM
DTSTART;VALUE=DATE:20180812
DTEND;VALUE=DATE:20180812
UID:zthC2obz0jMwCupt8GHnA8L6@stanza.co
SUMMARY:Twins @ Astros
DESCRIPTION:Twins @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xCft-37\n\nShop: https://stza.co/+xCft-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Astros
<2018-08-13 Mon>--<2018-08-12 Sun>
:PROPERTIES:
:ID:       Smf8Jj5cP4_Nh4Xvb3osYHCC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Twins @ Astros Twins @ Astros

Follow on MiLB First Pitch  https //stza.co/+xCfu-1a

Shop  https //stza.co/+xCfu-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Astros
END:VALARM
DTSTART;VALUE=DATE:20180813
DTEND;VALUE=DATE:20180813
UID:Smf8Jj5cP4_Nh4Xvb3osYHCC@stanza.co
SUMMARY:Twins @ Astros
DESCRIPTION:Twins @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xCfu-1a\n\nShop: https://stza.co/+xCfu-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Astros
<2018-08-14 Tue>--<2018-08-13 Mon>
:PROPERTIES:
:ID:       -GmtfafH1lsLHyEgiR0ZPfOv@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins @ Astros Twins @ Astros

Follow on MiLB First Pitch  https //stza.co/+xCfv-2

Shop  https //stza.co/+xCfv-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Astros
END:VALARM
DTSTART;VALUE=DATE:20180814
DTEND;VALUE=DATE:20180814
UID:-GmtfafH1lsLHyEgiR0ZPfOv@stanza.co
SUMMARY:Twins @ Astros
DESCRIPTION:Twins @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xCfv-2\n\nShop: https://stza.co/+xCfv-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Blue Jays
<2018-08-16 Thu>--<2018-08-15 Wed>
:PROPERTIES:
:ID:       wRUJINmh9yjygiTM3TOTIsBD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins @ Blue Jays Twins @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xCfw-18

Shop  https //stza.co/+xCfw-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Blue Jays
END:VALARM
DTSTART;VALUE=DATE:20180816
DTEND;VALUE=DATE:20180816
UID:wRUJINmh9yjygiTM3TOTIsBD@stanza.co
SUMMARY:Twins @ Blue Jays
DESCRIPTION:Twins @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xCfw-18\n\nShop: https://stza.co/+xCfw-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Blue Jays
<2018-08-17 Fri>--<2018-08-16 Thu>
:PROPERTIES:
:ID:       XQ4BcjJMW_wXPOBJkc5h_V-r@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Twins @ Blue Jays Twins @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xCfy-1d

Shop  https //stza.co/+xCfy-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Blue Jays
END:VALARM
DTSTART;VALUE=DATE:20180817
DTEND;VALUE=DATE:20180817
UID:XQ4BcjJMW_wXPOBJkc5h_V-r@stanza.co
SUMMARY:Twins @ Blue Jays
DESCRIPTION:Twins @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xCfy-1d\n\nShop: https://stza.co/+xCfy-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Blue Jays
<2018-08-18 Sat>--<2018-08-17 Fri>
:PROPERTIES:
:ID:       L8myj9LKZeyFfVGF8BO8fXuY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins @ Blue Jays Twins @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xCfB-2$

Shop  https //stza.co/+xCfB-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Blue Jays
END:VALARM
DTSTART;VALUE=DATE:20180818
DTEND;VALUE=DATE:20180818
UID:L8myj9LKZeyFfVGF8BO8fXuY@stanza.co
SUMMARY:Twins @ Blue Jays
DESCRIPTION:Twins @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xCfB-2$\n\nShop: https://stza.co/+xCfB-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Cardinals
<2018-08-19 Sun>--<2018-08-18 Sat>
:PROPERTIES:
:ID:       Sec36dcKyGzuF11bk_-gNaAu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins vs. Cardinals Twins vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xCfD-s

Shop  https //stza.co/+xCfD-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180819
DTEND;VALUE=DATE:20180819
UID:Sec36dcKyGzuF11bk_-gNaAu@stanza.co
SUMMARY:Twins vs. Cardinals
DESCRIPTION:Twins vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xCfD-s\n\nShop: https://stza.co/+xCfD-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Cardinals
<2018-08-20 Mon>--<2018-08-19 Sun>
:PROPERTIES:
:ID:       Z5TWz55eyzky9AGk9s2xrGov@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Twins vs. Cardinals Twins vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xCfF-2a

Shop  https //stza.co/+xCfF-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180820
DTEND;VALUE=DATE:20180820
UID:Z5TWz55eyzky9AGk9s2xrGov@stanza.co
SUMMARY:Twins vs. Cardinals
DESCRIPTION:Twins vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xCfF-2a\n\nShop: https://stza.co/+xCfF-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Astros
<2018-08-21 Tue>--<2018-08-20 Mon>
:PROPERTIES:
:ID:       WlLlITP5_HF9aTla-PmNtjU8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins vs. Astros Twins vs. Astros

Follow on MiLB First Pitch  https //stza.co/+xCfJ-S

Shop  https //stza.co/+xCfJ-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Astros
END:VALARM
DTSTART;VALUE=DATE:20180821
DTEND;VALUE=DATE:20180821
UID:WlLlITP5_HF9aTla-PmNtjU8@stanza.co
SUMMARY:Twins vs. Astros
DESCRIPTION:Twins vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xCfJ-S\n\nShop: https://stza.co/+xCfJ-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Astros
<2018-08-22 Wed>--<2018-08-21 Tue>
:PROPERTIES:
:ID:       FdWT7-KGnANRLZfTwVt0X00I@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins vs. Astros Twins vs. Astros

Follow on MiLB First Pitch  https //stza.co/+xCfL-10

Shop  https //stza.co/+xCfL-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Astros
END:VALARM
DTSTART;VALUE=DATE:20180822
DTEND;VALUE=DATE:20180822
UID:FdWT7-KGnANRLZfTwVt0X00I@stanza.co
SUMMARY:Twins vs. Astros
DESCRIPTION:Twins vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xCfL-10\n\nShop: https://stza.co/+xCfL-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Astros
<2018-08-23 Thu>--<2018-08-22 Wed>
:PROPERTIES:
:ID:       RRSxk63QzQqbDL0NDyzAaO-V@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Twins vs. Astros Twins vs. Astros

Follow on MiLB First Pitch  https //stza.co/+xCfO-1s

Shop  https //stza.co/+xCfO-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Astros
END:VALARM
DTSTART;VALUE=DATE:20180823
DTEND;VALUE=DATE:20180823
UID:RRSxk63QzQqbDL0NDyzAaO-V@stanza.co
SUMMARY:Twins vs. Astros
DESCRIPTION:Twins vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xCfO-1s\n\nShop: https://stza.co/+xCfO-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Pirates
<2018-08-24 Fri>--<2018-08-23 Thu>
:PROPERTIES:
:ID:       GKml6Rah2tK-0eHFPPth_oMZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins @ Pirates Twins @ Pirates

Follow on MiLB First Pitch  https //stza.co/+xCfQ-2W

Shop  https //stza.co/+xCfQ-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Pirates
END:VALARM
DTSTART;VALUE=DATE:20180824
DTEND;VALUE=DATE:20180824
UID:GKml6Rah2tK-0eHFPPth_oMZ@stanza.co
SUMMARY:Twins @ Pirates
DESCRIPTION:Twins @ Pirates\n\nFollow on MiLB First Pitch: https://stza.co/+xCfQ-2W\n\nShop: https://stza.co/+xCfQ-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Pirates
<2018-08-25 Sat>--<2018-08-24 Fri>
:PROPERTIES:
:ID:       faZfSJtCsPESXnIM2Rphi3on@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins @ Pirates Twins @ Pirates

Follow on MiLB First Pitch  https //stza.co/+xCfS-x

Shop  https //stza.co/+xCfS-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Pirates
END:VALARM
DTSTART;VALUE=DATE:20180825
DTEND;VALUE=DATE:20180825
UID:faZfSJtCsPESXnIM2Rphi3on@stanza.co
SUMMARY:Twins @ Pirates
DESCRIPTION:Twins @ Pirates\n\nFollow on MiLB First Pitch: https://stza.co/+xCfS-x\n\nShop: https://stza.co/+xCfS-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins @ Pirates
<2018-08-26 Sun>--<2018-08-25 Sat>
:PROPERTIES:
:ID:       ZPiMvjakP3ik4IiKA-elDpIX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Twins @ Pirates Twins @ Pirates

Follow on MiLB First Pitch  https //stza.co/+xCfU-3Q

Shop  https //stza.co/+xCfU-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Twins @ Pirates
END:VALARM
DTSTART;VALUE=DATE:20180826
DTEND;VALUE=DATE:20180826
UID:ZPiMvjakP3ik4IiKA-elDpIX@stanza.co
SUMMARY:Twins @ Pirates
DESCRIPTION:Twins @ Pirates\n\nFollow on MiLB First Pitch: https://stza.co/+xCfU-3Q\n\nShop: https://stza.co/+xCfU-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Yankees
<2018-08-27 Mon>--<2018-08-26 Sun>
:PROPERTIES:
:ID:       WveEaAZjeOjYtYfN0zkZPKVU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins vs. Yankees Twins vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xCfW-2f

Shop  https //stza.co/+xCfW-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Yankees
END:VALARM
DTSTART;VALUE=DATE:20180827
DTEND;VALUE=DATE:20180827
UID:WveEaAZjeOjYtYfN0zkZPKVU@stanza.co
SUMMARY:Twins vs. Yankees
DESCRIPTION:Twins vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xCfW-2f\n\nShop: https://stza.co/+xCfW-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Yankees
<2018-08-28 Tue>--<2018-08-27 Mon>
:PROPERTIES:
:ID:       _7WU-H8_FNkNVXQ4l6BYT6B7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Twins vs. Yankees Twins vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xCfX-3K

Shop  https //stza.co/+xCfX-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Yankees
END:VALARM
DTSTART;VALUE=DATE:20180828
DTEND;VALUE=DATE:20180828
UID:_7WU-H8_FNkNVXQ4l6BYT6B7@stanza.co
SUMMARY:Twins vs. Yankees
DESCRIPTION:Twins vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xCfX-3K\n\nShop: https://stza.co/+xCfX-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Twins vs. Yankees
<2018-08-29 Wed>--<2018-08-28 Tue>
:PROPERTIES:
:ID:       yL0YOwSPpxDHFSVKJs3Hwnfb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Twins vs. Yankees Twins vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xCf$-3A

Shop  https //stza.co/+xCf$-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Twins vs. Yankees
END:VALARM
DTSTART;VALUE=DATE:20180829
DTEND;VALUE=DATE:20180829
UID:yL0YOwSPpxDHFSVKJs3Hwnfb@stanza.co
SUMMARY:Twins vs. Yankees
DESCRIPTION:Twins vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xCf$-3A\n\nShop: https://stza.co/+xCf$-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
