#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Flying Squirrels @ Thunder
<2018-04-05 Thu 18:00-21:00>
:PROPERTIES:
:ID:       Smb6pbmTj75eN1W3YiSMmxXs@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Thunder Flying Squirrels @ Thunder

Follow on MiLB First Pitch  https //stza.co/+vbly-2i

Shop  https //stza.co/+vbly-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Thunder
END:VALARM
DTSTART:20180405T230000Z
DTEND:20180406T020000Z
UID:Smb6pbmTj75eN1W3YiSMmxXs@stanza.co
SUMMARY:Flying Squirrels @ Thunder
DESCRIPTION:Flying Squirrels @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vbly-2i\n\nShop: https://stza.co/+vbly-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Thunder
<2018-04-06 Fri 18:00-21:00>
:PROPERTIES:
:ID:       G0s_ZT59Y6AWqFqOD59gnttt@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Thunder Flying Squirrels @ Thunder

Follow on MiLB First Pitch  https //stza.co/+vblR-13

Shop  https //stza.co/+vblR-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Thunder
END:VALARM
DTSTART:20180406T230000Z
DTEND:20180407T020000Z
UID:G0s_ZT59Y6AWqFqOD59gnttt@stanza.co
SUMMARY:Flying Squirrels @ Thunder
DESCRIPTION:Flying Squirrels @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vblR-13\n\nShop: https://stza.co/+vblR-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Thunder
<2018-04-07 Sat 12:00-15:00>
:PROPERTIES:
:ID:       XVHZTNoZ0zdQytg0TgvfipRD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Thunder Flying Squirrels @ Thunder

Follow on MiLB First Pitch  https //stza.co/+vbm6-3j

Shop  https //stza.co/+vbm6-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Thunder
END:VALARM
DTSTART:20180407T170000Z
DTEND:20180407T200000Z
UID:XVHZTNoZ0zdQytg0TgvfipRD@stanza.co
SUMMARY:Flying Squirrels @ Thunder
DESCRIPTION:Flying Squirrels @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vbm6-3j\n\nShop: https://stza.co/+vbm6-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Thunder
<2018-04-08 Sun 12:00-15:00>
:PROPERTIES:
:ID:       pUID660dMw1nnPf267HrTJbz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Thunder Flying Squirrels @ Thunder

Follow on MiLB First Pitch  https //stza.co/+vbmq-3n

Shop  https //stza.co/+vbmq-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Thunder
END:VALARM
DTSTART:20180408T170000Z
DTEND:20180408T200000Z
UID:pUID660dMw1nnPf267HrTJbz@stanza.co
SUMMARY:Flying Squirrels @ Thunder
DESCRIPTION:Flying Squirrels @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vbmq-3n\n\nShop: https://stza.co/+vbmq-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Yard Goats
<2018-04-09 Mon 18:05-21:05>
:PROPERTIES:
:ID:       MlkEQynMdRCR7JfHwNJ4TWso@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Yard Goats Flying Squirrels @ Yard Goats

Buy tickets here  https //stza.co/~va_G

Follow on MiLB First Pitch  https //stza.co/+va_G-2O

Shop  https //stza.co/+va_G-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Yard Goats
END:VALARM
DTSTART:20180409T230500Z
DTEND:20180410T020500Z
UID:MlkEQynMdRCR7JfHwNJ4TWso@stanza.co
SUMMARY:Flying Squirrels @ Yard Goats
DESCRIPTION:Flying Squirrels @ Yard Goats\n\nBuy tickets here: https://stza.co/~va_G\n\nFollow on MiLB First Pitch: https://stza.co/+va_G-2O\n\nShop: https://stza.co/+va_G-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Yard Goats
<2018-04-10 Tue 18:05-21:05>
:PROPERTIES:
:ID:       Y6ORuN_ObeJoVwiME9oX9AWs@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Yard Goats Flying Squirrels @ Yard Goats

Buy tickets here  https //stza.co/~va_O

Follow on MiLB First Pitch  https //stza.co/+va_O-3i

Shop  https //stza.co/+va_O-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Yard Goats
END:VALARM
DTSTART:20180410T230500Z
DTEND:20180411T020500Z
UID:Y6ORuN_ObeJoVwiME9oX9AWs@stanza.co
SUMMARY:Flying Squirrels @ Yard Goats
DESCRIPTION:Flying Squirrels @ Yard Goats\n\nBuy tickets here: https://stza.co/~va_O\n\nFollow on MiLB First Pitch: https://stza.co/+va_O-3i\n\nShop: https://stza.co/+va_O-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Yard Goats
<2018-04-11 Wed 18:05-21:05>
:PROPERTIES:
:ID:       tRYiATsYghj88PQBf2ZCL-TE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Yard Goats Flying Squirrels @ Yard Goats

Buy tickets here  https //stza.co/~va_X

Follow on MiLB First Pitch  https //stza.co/+va_X-3X

Shop  https //stza.co/+va_X-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Yard Goats
END:VALARM
DTSTART:20180411T230500Z
DTEND:20180412T020500Z
UID:tRYiATsYghj88PQBf2ZCL-TE@stanza.co
SUMMARY:Flying Squirrels @ Yard Goats
DESCRIPTION:Flying Squirrels @ Yard Goats\n\nBuy tickets here: https://stza.co/~va_X\n\nFollow on MiLB First Pitch: https://stza.co/+va_X-3X\n\nShop: https://stza.co/+va_X-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Fightin Phils
<2018-04-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       aEbyVUUWldqRvCJll7AQuSHl@stanza.co
:LOCATION: Promo Schedule Coming Soon! 
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Fightin Phils The 2018 Flying Squirrels promotional schedule will be released in the near future. Check back soon! 

Follow on MiLB First Pitch  https //stza.co/+vb1y-t

Shop  https //stza.co/+vb1y-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Fightin Phils
END:VALARM
DTSTART:20180413T230500Z
DTEND:20180414T020500Z
UID:aEbyVUUWldqRvCJll7AQuSHl@stanza.co
SUMMARY:Flying Squirrels vs. Fightin Phils
DESCRIPTION:The 2018 Flying Squirrels promotional schedule will be released in the near future. Check back soon! \n\nFollow on MiLB First Pitch: https://stza.co/+vb1y-t\n\nShop: https://stza.co/+vb1y-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Promo Schedule Coming Soon! 
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Fightin Phils
<2018-04-14 Sat 17:05-20:05>
:PROPERTIES:
:ID:       WxVWEcZdZiHh5fObKsjDSWGV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Fightin Phils Flying Squirrels vs. Fightin Phils

Follow on MiLB First Pitch  https //stza.co/+vb1I-37

Shop  https //stza.co/+vb1I-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Fightin Phils
END:VALARM
DTSTART:20180414T220500Z
DTEND:20180415T010500Z
UID:WxVWEcZdZiHh5fObKsjDSWGV@stanza.co
SUMMARY:Flying Squirrels vs. Fightin Phils
DESCRIPTION:Flying Squirrels vs. Fightin Phils\n\nFollow on MiLB First Pitch: https://stza.co/+vb1I-37\n\nShop: https://stza.co/+vb1I-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Fightin Phils
<2018-04-15 Sun 12:05-15:05>
:PROPERTIES:
:ID:       -HUp-7lOrfdiDuOy3uK1IkHx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Fightin Phils Flying Squirrels vs. Fightin Phils

Follow on MiLB First Pitch  https //stza.co/+vb1S-3x

Shop  https //stza.co/+vb1S-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Fightin Phils
END:VALARM
DTSTART:20180415T170500Z
DTEND:20180415T200500Z
UID:-HUp-7lOrfdiDuOy3uK1IkHx@stanza.co
SUMMARY:Flying Squirrels vs. Fightin Phils
DESCRIPTION:Flying Squirrels vs. Fightin Phils\n\nFollow on MiLB First Pitch: https://stza.co/+vb1S-3x\n\nShop: https://stza.co/+vb1S-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Baysox
<2018-04-16 Mon 17:35-20:35>
:PROPERTIES:
:ID:       IKywzp2VDlKDpRs4uMYtXAvo@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Baysox Flying Squirrels vs. Baysox

Follow on MiLB First Pitch  https //stza.co/+vb1$-5

Shop  https //stza.co/+vb1$-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Baysox
END:VALARM
DTSTART:20180416T223500Z
DTEND:20180417T013500Z
UID:IKywzp2VDlKDpRs4uMYtXAvo@stanza.co
SUMMARY:Flying Squirrels vs. Baysox
DESCRIPTION:Flying Squirrels vs. Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vb1$-5\n\nShop: https://stza.co/+vb1$-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Baysox
<2018-04-17 Tue 17:35-20:35>
:PROPERTIES:
:ID:       eb8sKVmfDgki8bAxPRcdKkHB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Baysox Flying Squirrels vs. Baysox

Follow on MiLB First Pitch  https //stza.co/+vb2c-1M

Shop  https //stza.co/+vb2c-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Baysox
END:VALARM
DTSTART:20180417T223500Z
DTEND:20180418T013500Z
UID:eb8sKVmfDgki8bAxPRcdKkHB@stanza.co
SUMMARY:Flying Squirrels vs. Baysox
DESCRIPTION:Flying Squirrels vs. Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vb2c-1M\n\nShop: https://stza.co/+vb2c-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Baysox
<2018-04-18 Wed 17:35-20:35>
:PROPERTIES:
:ID:       lQeuse55iqAaZ2W3FpwNtU8S@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Baysox Flying Squirrels vs. Baysox

Follow on MiLB First Pitch  https //stza.co/+vb2g-24

Shop  https //stza.co/+vb2g-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Baysox
END:VALARM
DTSTART:20180418T223500Z
DTEND:20180419T013500Z
UID:lQeuse55iqAaZ2W3FpwNtU8S@stanza.co
SUMMARY:Flying Squirrels vs. Baysox
DESCRIPTION:Flying Squirrels vs. Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vb2g-24\n\nShop: https://stza.co/+vb2g-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Baysox
<2018-04-19 Thu 09:35-12:35>
:PROPERTIES:
:ID:       nCew8ms8KYrNQUCjUq-VSWa9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Baysox Flying Squirrels vs. Baysox

Follow on MiLB First Pitch  https //stza.co/+vb2s-3E

Shop  https //stza.co/+vb2s-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Baysox
END:VALARM
DTSTART:20180419T143500Z
DTEND:20180419T173500Z
UID:nCew8ms8KYrNQUCjUq-VSWa9@stanza.co
SUMMARY:Flying Squirrels vs. Baysox
DESCRIPTION:Flying Squirrels vs. Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vb2s-3E\n\nShop: https://stza.co/+vb2s-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Curve
<2018-04-20 Fri 17:00-20:00>
:PROPERTIES:
:ID:       5X_Axk_jYsRne417hCXO5Vlj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Curve Flying Squirrels @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLw9-R

Shop  https //stza.co/+vLw9-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Curve
END:VALARM
DTSTART:20180420T220000Z
DTEND:20180421T010000Z
UID:5X_Axk_jYsRne417hCXO5Vlj@stanza.co
SUMMARY:Flying Squirrels @ Curve
DESCRIPTION:Flying Squirrels @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLw9-R\n\nShop: https://stza.co/+vLw9-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Curve
<2018-04-21 Sat 15:00-18:00>
:PROPERTIES:
:ID:       Sgb-aiK-YSn_-XeU0Mj4sP7k@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Curve Flying Squirrels @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLwa-10

Shop  https //stza.co/+vLwa-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Curve
END:VALARM
DTSTART:20180421T200000Z
DTEND:20180421T230000Z
UID:Sgb-aiK-YSn_-XeU0Mj4sP7k@stanza.co
SUMMARY:Flying Squirrels @ Curve
DESCRIPTION:Flying Squirrels @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLwa-10\n\nShop: https://stza.co/+vLwa-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Curve
<2018-04-22 Sun 13:00-16:00>
:PROPERTIES:
:ID:       aHBwQotb32A-I9w3mx2ppYT1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Curve Flying Squirrels @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLwb-3s

Shop  https //stza.co/+vLwb-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Curve
END:VALARM
DTSTART:20180422T180000Z
DTEND:20180422T210000Z
UID:aHBwQotb32A-I9w3mx2ppYT1@stanza.co
SUMMARY:Flying Squirrels @ Curve
DESCRIPTION:Flying Squirrels @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLwb-3s\n\nShop: https://stza.co/+vLwb-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Baysox
<2018-04-23 Mon 17:35-20:35>
:PROPERTIES:
:ID:       njexoenjw1JhasAijDcV8m2z@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Baysox Flying Squirrels @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vLwl-3L

Shop  https //stza.co/+vLwl-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Baysox
END:VALARM
DTSTART:20180423T223500Z
DTEND:20180424T013500Z
UID:njexoenjw1JhasAijDcV8m2z@stanza.co
SUMMARY:Flying Squirrels @ Baysox
DESCRIPTION:Flying Squirrels @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLwl-3L\n\nShop: https://stza.co/+vLwl-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Baysox
<2018-04-24 Tue 17:35-20:35>
:PROPERTIES:
:ID:       0OLlY39fasnoDHQ6HMl9hrjj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Baysox Flying Squirrels @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vLwm-I

Shop  https //stza.co/+vLwm-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Baysox
END:VALARM
DTSTART:20180424T223500Z
DTEND:20180425T013500Z
UID:0OLlY39fasnoDHQ6HMl9hrjj@stanza.co
SUMMARY:Flying Squirrels @ Baysox
DESCRIPTION:Flying Squirrels @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLwm-I\n\nShop: https://stza.co/+vLwm-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Baysox
<2018-04-25 Wed 10:05-13:05>
:PROPERTIES:
:ID:       _lEL1I5y6U8cyRn80DptnUE1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Baysox Flying Squirrels @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vLwn-2C

Shop  https //stza.co/+vLwn-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Baysox
END:VALARM
DTSTART:20180425T150500Z
DTEND:20180425T180500Z
UID:_lEL1I5y6U8cyRn80DptnUE1@stanza.co
SUMMARY:Flying Squirrels @ Baysox
DESCRIPTION:Flying Squirrels @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLwn-2C\n\nShop: https://stza.co/+vLwn-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Yard Goats
<2018-04-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       ck0cTtDHx-zpKc5DnQplKjau@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Yard Goats Flying Squirrels vs. Yard Goats

Follow on MiLB First Pitch  https //stza.co/+vb2G-M

Shop  https //stza.co/+vb2G-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Yard Goats
END:VALARM
DTSTART:20180427T230500Z
DTEND:20180428T020500Z
UID:ck0cTtDHx-zpKc5DnQplKjau@stanza.co
SUMMARY:Flying Squirrels vs. Yard Goats
DESCRIPTION:Flying Squirrels vs. Yard Goats\n\nFollow on MiLB First Pitch: https://stza.co/+vb2G-M\n\nShop: https://stza.co/+vb2G-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Yard Goats
<2018-04-28 Sat 17:05-20:05>
:PROPERTIES:
:ID:       yX5eslcLGA8QG2cUKREqxuHa@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Yard Goats Flying Squirrels vs. Yard Goats

Follow on MiLB First Pitch  https //stza.co/+vb2N-A

Shop  https //stza.co/+vb2N-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Yard Goats
END:VALARM
DTSTART:20180428T220500Z
DTEND:20180429T010500Z
UID:yX5eslcLGA8QG2cUKREqxuHa@stanza.co
SUMMARY:Flying Squirrels vs. Yard Goats
DESCRIPTION:Flying Squirrels vs. Yard Goats\n\nFollow on MiLB First Pitch: https://stza.co/+vb2N-A\n\nShop: https://stza.co/+vb2N-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Yard Goats
<2018-04-29 Sun 12:05-15:05>
:PROPERTIES:
:ID:       avazcZZjBFqNnet5cUKs-lx9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Yard Goats Flying Squirrels vs. Yard Goats

Follow on MiLB First Pitch  https //stza.co/+vb2_-2f

Shop  https //stza.co/+vb2_-1w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Yard Goats
END:VALARM
DTSTART:20180429T170500Z
DTEND:20180429T200500Z
UID:avazcZZjBFqNnet5cUKs-lx9@stanza.co
SUMMARY:Flying Squirrels vs. Yard Goats
DESCRIPTION:Flying Squirrels vs. Yard Goats\n\nFollow on MiLB First Pitch: https://stza.co/+vb2_-2f\n\nShop: https://stza.co/+vb2_-1w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Curve
<2018-04-30 Mon 17:35-20:35>
:PROPERTIES:
:ID:       WoY0FAmo7lGwJ0SSSnEt0gv1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Curve Flying Squirrels vs. Curve

Follow on MiLB First Pitch  https //stza.co/+vb3f-3T

Shop  https //stza.co/+vb3f-1J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Curve
END:VALARM
DTSTART:20180430T223500Z
DTEND:20180501T013500Z
UID:WoY0FAmo7lGwJ0SSSnEt0gv1@stanza.co
SUMMARY:Flying Squirrels vs. Curve
DESCRIPTION:Flying Squirrels vs. Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vb3f-3T\n\nShop: https://stza.co/+vb3f-1J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Curve
<2018-05-01 Tue 17:35-20:35>
:PROPERTIES:
:ID:       AN1aq_g9obkleVXFYYWhG2qo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Curve Flying Squirrels vs. Curve

Follow on MiLB First Pitch  https //stza.co/+vb3x-38

Shop  https //stza.co/+vb3x-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Curve
END:VALARM
DTSTART:20180501T223500Z
DTEND:20180502T013500Z
UID:AN1aq_g9obkleVXFYYWhG2qo@stanza.co
SUMMARY:Flying Squirrels vs. Curve
DESCRIPTION:Flying Squirrels vs. Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vb3x-38\n\nShop: https://stza.co/+vb3x-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Curve
<2018-05-02 Wed 09:35-12:35>
:PROPERTIES:
:ID:       XLxqLogc0Q_T9wnLb4jrJTKA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Curve Flying Squirrels vs. Curve

Follow on MiLB First Pitch  https //stza.co/+vb3R-2t

Shop  https //stza.co/+vb3R-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Curve
END:VALARM
DTSTART:20180502T143500Z
DTEND:20180502T173500Z
UID:XLxqLogc0Q_T9wnLb4jrJTKA@stanza.co
SUMMARY:Flying Squirrels vs. Curve
DESCRIPTION:Flying Squirrels vs. Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vb3R-2t\n\nShop: https://stza.co/+vb3R-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Fightin Phils
<2018-05-04 Fri 18:05-21:05>
:PROPERTIES:
:ID:       fnWd1D6uLVjunl4kafGKB25f@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Fightin Phils Flying Squirrels @ Fightin Phils

Buy tickets here  https //stza.co/~vb0y

Follow on MiLB First Pitch  https //stza.co/+vb0y-3v

Shop  https //stza.co/+vb0y-1J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Fightin Phils
END:VALARM
DTSTART:20180504T230500Z
DTEND:20180505T020500Z
UID:fnWd1D6uLVjunl4kafGKB25f@stanza.co
SUMMARY:Flying Squirrels @ Fightin Phils
DESCRIPTION:Flying Squirrels @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vb0y\n\nFollow on MiLB First Pitch: https://stza.co/+vb0y-3v\n\nShop: https://stza.co/+vb0y-1J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Fightin Phils
<2018-05-05 Sat 17:05-20:05>
:PROPERTIES:
:ID:       25SQCl0_GRb-0S-69pJ13kvw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Fightin Phils Flying Squirrels @ Fightin Phils

Buy tickets here  https //stza.co/~vb0G

Follow on MiLB First Pitch  https //stza.co/+vb0G-E

Shop  https //stza.co/+vb0G-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Fightin Phils
END:VALARM
DTSTART:20180505T220500Z
DTEND:20180506T010500Z
UID:25SQCl0_GRb-0S-69pJ13kvw@stanza.co
SUMMARY:Flying Squirrels @ Fightin Phils
DESCRIPTION:Flying Squirrels @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vb0G\n\nFollow on MiLB First Pitch: https://stza.co/+vb0G-E\n\nShop: https://stza.co/+vb0G-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Fightin Phils
<2018-05-06 Sun 13:05-16:05>
:PROPERTIES:
:ID:       eK3JcjLPZSHITB6jGCl0X5g9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Fightin Phils Flying Squirrels @ Fightin Phils

Buy tickets here  https //stza.co/~vb0Q

Follow on MiLB First Pitch  https //stza.co/+vb0Q-2x

Shop  https //stza.co/+vb0Q-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Fightin Phils
END:VALARM
DTSTART:20180506T180500Z
DTEND:20180506T210500Z
UID:eK3JcjLPZSHITB6jGCl0X5g9@stanza.co
SUMMARY:Flying Squirrels @ Fightin Phils
DESCRIPTION:Flying Squirrels @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vb0Q\n\nFollow on MiLB First Pitch: https://stza.co/+vb0Q-2x\n\nShop: https://stza.co/+vb0Q-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. RubberDucks
<2018-05-07 Mon 17:35-20:35>
:PROPERTIES:
:ID:       EUQFKCD79hEAzRVQ4li5yKgG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. RubberDucks Flying Squirrels vs. RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vb45-1z

Shop  https //stza.co/+vb45-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. RubberDucks
END:VALARM
DTSTART:20180507T223500Z
DTEND:20180508T013500Z
UID:EUQFKCD79hEAzRVQ4li5yKgG@stanza.co
SUMMARY:Flying Squirrels vs. RubberDucks
DESCRIPTION:Flying Squirrels vs. RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vb45-1z\n\nShop: https://stza.co/+vb45-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. RubberDucks
<2018-05-08 Tue 17:35-20:35>
:PROPERTIES:
:ID:       BQCBZrVhD_h4cWO3CbPF5Rj9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. RubberDucks Flying Squirrels vs. RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vb4n-2v

Shop  https //stza.co/+vb4n-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. RubberDucks
END:VALARM
DTSTART:20180508T223500Z
DTEND:20180509T013500Z
UID:BQCBZrVhD_h4cWO3CbPF5Rj9@stanza.co
SUMMARY:Flying Squirrels vs. RubberDucks
DESCRIPTION:Flying Squirrels vs. RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vb4n-2v\n\nShop: https://stza.co/+vb4n-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. RubberDucks
<2018-05-09 Wed 11:05-14:05>
:PROPERTIES:
:ID:       dQIO877PpjX27aDOr95ihOwk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. RubberDucks Flying Squirrels vs. RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vb4J-w

Shop  https //stza.co/+vb4J-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. RubberDucks
END:VALARM
DTSTART:20180509T160500Z
DTEND:20180509T190500Z
UID:dQIO877PpjX27aDOr95ihOwk@stanza.co
SUMMARY:Flying Squirrels vs. RubberDucks
DESCRIPTION:Flying Squirrels vs. RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vb4J-w\n\nShop: https://stza.co/+vb4J-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Thunder
<2018-05-10 Thu 17:35-20:35>
:PROPERTIES:
:ID:       Jv2M40ckZyd3scYm8bnlmPRO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Thunder Flying Squirrels vs. Thunder

Follow on MiLB First Pitch  https //stza.co/+vb4$-3l

Shop  https //stza.co/+vb4$-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Thunder
END:VALARM
DTSTART:20180510T223500Z
DTEND:20180511T013500Z
UID:Jv2M40ckZyd3scYm8bnlmPRO@stanza.co
SUMMARY:Flying Squirrels vs. Thunder
DESCRIPTION:Flying Squirrels vs. Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vb4$-3l\n\nShop: https://stza.co/+vb4$-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Thunder
<2018-05-11 Fri 18:05-21:05>
:PROPERTIES:
:ID:       z1s5VqBqccxQTHr9ZkVyUECv@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Thunder Flying Squirrels vs. Thunder

Follow on MiLB First Pitch  https //stza.co/+vb5i-Z

Shop  https //stza.co/+vb5i-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Thunder
END:VALARM
DTSTART:20180511T230500Z
DTEND:20180512T020500Z
UID:z1s5VqBqccxQTHr9ZkVyUECv@stanza.co
SUMMARY:Flying Squirrels vs. Thunder
DESCRIPTION:Flying Squirrels vs. Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vb5i-Z\n\nShop: https://stza.co/+vb5i-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Thunder
<2018-05-12 Sat 17:05-20:05>
:PROPERTIES:
:ID:       1FMwBYNvqlyAfQjTWr1CCkVw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Thunder Flying Squirrels vs. Thunder

Follow on MiLB First Pitch  https //stza.co/+vb5B-V

Shop  https //stza.co/+vb5B-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Thunder
END:VALARM
DTSTART:20180512T220500Z
DTEND:20180513T010500Z
UID:1FMwBYNvqlyAfQjTWr1CCkVw@stanza.co
SUMMARY:Flying Squirrels vs. Thunder
DESCRIPTION:Flying Squirrels vs. Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vb5B-V\n\nShop: https://stza.co/+vb5B-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Thunder
<2018-05-13 Sun 12:05-15:05>
:PROPERTIES:
:ID:       hureT0xO5mQTU5EYmju8zBvo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Thunder Flying Squirrels vs. Thunder

Follow on MiLB First Pitch  https //stza.co/+vb5T-z

Shop  https //stza.co/+vb5T-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Thunder
END:VALARM
DTSTART:20180513T170500Z
DTEND:20180513T200500Z
UID:hureT0xO5mQTU5EYmju8zBvo@stanza.co
SUMMARY:Flying Squirrels vs. Thunder
DESCRIPTION:Flying Squirrels vs. Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vb5T-z\n\nShop: https://stza.co/+vb5T-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Curve
<2018-05-14 Mon 17:00-20:00>
:PROPERTIES:
:ID:       1NAhR-5Fp8Jze7hUglPjbTpF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Curve Flying Squirrels @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLwc-O

Shop  https //stza.co/+vLwc-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Curve
END:VALARM
DTSTART:20180514T220000Z
DTEND:20180515T010000Z
UID:1NAhR-5Fp8Jze7hUglPjbTpF@stanza.co
SUMMARY:Flying Squirrels @ Curve
DESCRIPTION:Flying Squirrels @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLwc-O\n\nShop: https://stza.co/+vLwc-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Curve
<2018-05-15 Tue 17:00-20:00>
:PROPERTIES:
:ID:       0vSmetcvvyD-J-m2mb2440zr@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Curve Flying Squirrels @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLwd-1R

Shop  https //stza.co/+vLwd-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Curve
END:VALARM
DTSTART:20180515T220000Z
DTEND:20180516T010000Z
UID:0vSmetcvvyD-J-m2mb2440zr@stanza.co
SUMMARY:Flying Squirrels @ Curve
DESCRIPTION:Flying Squirrels @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLwd-1R\n\nShop: https://stza.co/+vLwd-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Curve
<2018-05-16 Wed 17:00-20:00>
:PROPERTIES:
:ID:       3eJMiHoEeqqYlfAr8wl4cyGS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Curve Flying Squirrels @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLwe-1O

Shop  https //stza.co/+vLwe-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Curve
END:VALARM
DTSTART:20180516T220000Z
DTEND:20180517T010000Z
UID:3eJMiHoEeqqYlfAr8wl4cyGS@stanza.co
SUMMARY:Flying Squirrels @ Curve
DESCRIPTION:Flying Squirrels @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLwe-1O\n\nShop: https://stza.co/+vLwe-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Senators
<2018-05-17 Thu 17:35-20:35>
:PROPERTIES:
:ID:       ldDTBNeOuZp63br7DWDldkFh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Senators Flying Squirrels vs. Senators

Follow on MiLB First Pitch  https //stza.co/+vb6a-2a

Shop  https //stza.co/+vb6a-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Senators
END:VALARM
DTSTART:20180517T223500Z
DTEND:20180518T013500Z
UID:ldDTBNeOuZp63br7DWDldkFh@stanza.co
SUMMARY:Flying Squirrels vs. Senators
DESCRIPTION:Flying Squirrels vs. Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vb6a-2a\n\nShop: https://stza.co/+vb6a-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Senators
<2018-05-18 Fri 18:05-21:05>
:PROPERTIES:
:ID:       wW9EOeOEh3mazH40-kG27WiX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Senators Flying Squirrels vs. Senators

Follow on MiLB First Pitch  https //stza.co/+vb6t-2Q

Shop  https //stza.co/+vb6t-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Senators
END:VALARM
DTSTART:20180518T230500Z
DTEND:20180519T020500Z
UID:wW9EOeOEh3mazH40-kG27WiX@stanza.co
SUMMARY:Flying Squirrels vs. Senators
DESCRIPTION:Flying Squirrels vs. Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vb6t-2Q\n\nShop: https://stza.co/+vb6t-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Senators
<2018-05-19 Sat 17:05-20:05>
:PROPERTIES:
:ID:       hbp3TShF8e6UzsA9vZFiQjnC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Senators Flying Squirrels vs. Senators

Follow on MiLB First Pitch  https //stza.co/+vb6N-2D

Shop  https //stza.co/+vb6N-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Senators
END:VALARM
DTSTART:20180519T220500Z
DTEND:20180520T010500Z
UID:hbp3TShF8e6UzsA9vZFiQjnC@stanza.co
SUMMARY:Flying Squirrels vs. Senators
DESCRIPTION:Flying Squirrels vs. Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vb6N-2D\n\nShop: https://stza.co/+vb6N-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Senators
<2018-05-20 Sun 12:05-15:05>
:PROPERTIES:
:ID:       hMPG-XCn3f97XHEOgbqnJMX2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Senators Flying Squirrels vs. Senators

Follow on MiLB First Pitch  https //stza.co/+vb78-2m

Shop  https //stza.co/+vb78-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Senators
END:VALARM
DTSTART:20180520T170500Z
DTEND:20180520T200500Z
UID:hMPG-XCn3f97XHEOgbqnJMX2@stanza.co
SUMMARY:Flying Squirrels vs. Senators
DESCRIPTION:Flying Squirrels vs. Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vb78-2m\n\nShop: https://stza.co/+vb78-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Rumble Ponies
<2018-05-22 Tue 17:35-20:35>
:PROPERTIES:
:ID:       Wsyhdp7Nez7R7oALjM501D-M@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Rumble Ponies Flying Squirrels @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLwi-m

Shop  https //stza.co/+vLwi-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Rumble Ponies
END:VALARM
DTSTART:20180522T223500Z
DTEND:20180523T013500Z
UID:Wsyhdp7Nez7R7oALjM501D-M@stanza.co
SUMMARY:Flying Squirrels @ Rumble Ponies
DESCRIPTION:Flying Squirrels @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLwi-m\n\nShop: https://stza.co/+vLwi-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Rumble Ponies
<2018-05-23 Wed 17:35-20:35>
:PROPERTIES:
:ID:       zBIn3kzTbm8B3JHgXyCJQVYB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Rumble Ponies Flying Squirrels @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLwj-1s

Shop  https //stza.co/+vLwj-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Rumble Ponies
END:VALARM
DTSTART:20180523T223500Z
DTEND:20180524T013500Z
UID:zBIn3kzTbm8B3JHgXyCJQVYB@stanza.co
SUMMARY:Flying Squirrels @ Rumble Ponies
DESCRIPTION:Flying Squirrels @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLwj-1s\n\nShop: https://stza.co/+vLwj-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Rumble Ponies
<2018-05-24 Thu 09:35-12:35>
:PROPERTIES:
:ID:       NqNI8i71eIW0AuJ1FdXV0ij5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Rumble Ponies Flying Squirrels @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLwk-3U

Shop  https //stza.co/+vLwk-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Rumble Ponies
END:VALARM
DTSTART:20180524T143500Z
DTEND:20180524T173500Z
UID:NqNI8i71eIW0AuJ1FdXV0ij5@stanza.co
SUMMARY:Flying Squirrels @ Rumble Ponies
DESCRIPTION:Flying Squirrels @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLwk-3U\n\nShop: https://stza.co/+vLwk-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ RubberDucks
<2018-05-25 Fri 17:35-20:35>
:PROPERTIES:
:ID:       FyRr--3mGpbd3n-nQ0Z1Onmj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ RubberDucks Flying Squirrels @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLw1-3C

Shop  https //stza.co/+vLw1-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ RubberDucks
END:VALARM
DTSTART:20180525T223500Z
DTEND:20180526T013500Z
UID:FyRr--3mGpbd3n-nQ0Z1Onmj@stanza.co
SUMMARY:Flying Squirrels @ RubberDucks
DESCRIPTION:Flying Squirrels @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLw1-3C\n\nShop: https://stza.co/+vLw1-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ RubberDucks
<2018-05-26 Sat 17:35-20:35>
:PROPERTIES:
:ID:       DcnSU4Iwfq2a_G4gvl68UE5_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ RubberDucks Flying Squirrels @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLw2-E

Shop  https //stza.co/+vLw2-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ RubberDucks
END:VALARM
DTSTART:20180526T223500Z
DTEND:20180527T013500Z
UID:DcnSU4Iwfq2a_G4gvl68UE5_@stanza.co
SUMMARY:Flying Squirrels @ RubberDucks
DESCRIPTION:Flying Squirrels @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLw2-E\n\nShop: https://stza.co/+vLw2-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ RubberDucks
<2018-05-27 Sun 17:35-20:35>
:PROPERTIES:
:ID:       MgqQjz6I3ES5tXhu6s6AaCCh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ RubberDucks Flying Squirrels @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLw3-2R

Shop  https //stza.co/+vLw3-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ RubberDucks
END:VALARM
DTSTART:20180527T223500Z
DTEND:20180528T013500Z
UID:MgqQjz6I3ES5tXhu6s6AaCCh@stanza.co
SUMMARY:Flying Squirrels @ RubberDucks
DESCRIPTION:Flying Squirrels @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLw3-2R\n\nShop: https://stza.co/+vLw3-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ RubberDucks
<2018-05-28 Mon 12:05-15:05>
:PROPERTIES:
:ID:       XC91e-sA3__1WRSlYfp3u94o@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ RubberDucks Flying Squirrels @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLw4-2Z

Shop  https //stza.co/+vLw4-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ RubberDucks
END:VALARM
DTSTART:20180528T170500Z
DTEND:20180528T200500Z
UID:XC91e-sA3__1WRSlYfp3u94o@stanza.co
SUMMARY:Flying Squirrels @ RubberDucks
DESCRIPTION:Flying Squirrels @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLw4-2Z\n\nShop: https://stza.co/+vLw4-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Baysox
<2018-05-29 Tue 17:35-20:35>
:PROPERTIES:
:ID:       nHcPZI-kSvzi7LniGL2sREZn@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Baysox Flying Squirrels vs. Baysox

Follow on MiLB First Pitch  https //stza.co/+vb7q-3l

Shop  https //stza.co/+vb7q-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Baysox
END:VALARM
DTSTART:20180529T223500Z
DTEND:20180530T013500Z
UID:nHcPZI-kSvzi7LniGL2sREZn@stanza.co
SUMMARY:Flying Squirrels vs. Baysox
DESCRIPTION:Flying Squirrels vs. Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vb7q-3l\n\nShop: https://stza.co/+vb7q-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Baysox
<2018-05-30 Wed 17:35-20:35>
:PROPERTIES:
:ID:       Ayeb5wia3g4suWYYW1dudk-w@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Baysox Flying Squirrels vs. Baysox

Follow on MiLB First Pitch  https //stza.co/+vb7N-w

Shop  https //stza.co/+vb7N-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Baysox
END:VALARM
DTSTART:20180530T223500Z
DTEND:20180531T013500Z
UID:Ayeb5wia3g4suWYYW1dudk-w@stanza.co
SUMMARY:Flying Squirrels vs. Baysox
DESCRIPTION:Flying Squirrels vs. Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vb7N-w\n\nShop: https://stza.co/+vb7N-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Baysox
<2018-05-31 Thu 17:35-20:35>
:PROPERTIES:
:ID:       4tJlxfJ9CBDJEhrPKBHoRal6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Baysox Flying Squirrels vs. Baysox

Follow on MiLB First Pitch  https //stza.co/+vb84-2V

Shop  https //stza.co/+vb84-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Baysox
END:VALARM
DTSTART:20180531T223500Z
DTEND:20180601T013500Z
UID:4tJlxfJ9CBDJEhrPKBHoRal6@stanza.co
SUMMARY:Flying Squirrels vs. Baysox
DESCRIPTION:Flying Squirrels vs. Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vb84-2V\n\nShop: https://stza.co/+vb84-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Fightin Phils
<2018-06-01 Fri 18:05-21:05>
:PROPERTIES:
:ID:       Oz67-UIHT7qQgQKv6on-NSGM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Fightin Phils Flying Squirrels @ Fightin Phils

Buy tickets here  https //stza.co/~vb0W

Follow on MiLB First Pitch  https //stza.co/+vb0W-F

Shop  https //stza.co/+vb0W-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Fightin Phils
END:VALARM
DTSTART:20180601T230500Z
DTEND:20180602T020500Z
UID:Oz67-UIHT7qQgQKv6on-NSGM@stanza.co
SUMMARY:Flying Squirrels @ Fightin Phils
DESCRIPTION:Flying Squirrels @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vb0W\n\nFollow on MiLB First Pitch: https://stza.co/+vb0W-F\n\nShop: https://stza.co/+vb0W-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Fightin Phils
<2018-06-02 Sat 17:35-20:35>
:PROPERTIES:
:ID:       FJQFNMmS88AtCh1Zn3GLO7TV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Fightin Phils Flying Squirrels @ Fightin Phils

Buy tickets here  https //stza.co/~vb17

Follow on MiLB First Pitch  https //stza.co/+vb17-Z

Shop  https //stza.co/+vb17-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Fightin Phils
END:VALARM
DTSTART:20180602T223500Z
DTEND:20180603T013500Z
UID:FJQFNMmS88AtCh1Zn3GLO7TV@stanza.co
SUMMARY:Flying Squirrels @ Fightin Phils
DESCRIPTION:Flying Squirrels @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vb17\n\nFollow on MiLB First Pitch: https://stza.co/+vb17-Z\n\nShop: https://stza.co/+vb17-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Fightin Phils
<2018-06-03 Sun 13:05-16:05>
:PROPERTIES:
:ID:       Yfc9dNC2gwtj8wammb3RM89p@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Fightin Phils Flying Squirrels @ Fightin Phils

Buy tickets here  https //stza.co/~vb1c

Follow on MiLB First Pitch  https //stza.co/+vb1c-2p

Shop  https //stza.co/+vb1c-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Fightin Phils
END:VALARM
DTSTART:20180603T180500Z
DTEND:20180603T210500Z
UID:Yfc9dNC2gwtj8wammb3RM89p@stanza.co
SUMMARY:Flying Squirrels @ Fightin Phils
DESCRIPTION:Flying Squirrels @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vb1c\n\nFollow on MiLB First Pitch: https://stza.co/+vb1c-2p\n\nShop: https://stza.co/+vb1c-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Fightin Phils
<2018-06-04 Mon 08:35-11:35>
:PROPERTIES:
:ID:       poTxfYjkF5_3QoEq19WkMUrk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Fightin Phils Flying Squirrels @ Fightin Phils

Buy tickets here  https //stza.co/~vb1l

Follow on MiLB First Pitch  https //stza.co/+vb1l-n

Shop  https //stza.co/+vb1l-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Fightin Phils
END:VALARM
DTSTART:20180604T133500Z
DTEND:20180604T163500Z
UID:poTxfYjkF5_3QoEq19WkMUrk@stanza.co
SUMMARY:Flying Squirrels @ Fightin Phils
DESCRIPTION:Flying Squirrels @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vb1l\n\nFollow on MiLB First Pitch: https://stza.co/+vb1l-n\n\nShop: https://stza.co/+vb1l-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Thunder
<2018-06-05 Tue 18:00-21:00>
:PROPERTIES:
:ID:       wBbHEwQNV0OyTcQcH972LTeT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Thunder Flying Squirrels @ Thunder

Follow on MiLB First Pitch  https //stza.co/+vbmM-33

Shop  https //stza.co/+vbmM-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Thunder
END:VALARM
DTSTART:20180605T230000Z
DTEND:20180606T020000Z
UID:wBbHEwQNV0OyTcQcH972LTeT@stanza.co
SUMMARY:Flying Squirrels @ Thunder
DESCRIPTION:Flying Squirrels @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vbmM-33\n\nShop: https://stza.co/+vbmM-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Thunder
<2018-06-06 Wed 18:00-21:00>
:PROPERTIES:
:ID:       sHsd1S5R2tktfpLZOjEWUAbU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Thunder Flying Squirrels @ Thunder

Follow on MiLB First Pitch  https //stza.co/+vbmZ-21

Shop  https //stza.co/+vbmZ-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Thunder
END:VALARM
DTSTART:20180606T230000Z
DTEND:20180607T020000Z
UID:sHsd1S5R2tktfpLZOjEWUAbU@stanza.co
SUMMARY:Flying Squirrels @ Thunder
DESCRIPTION:Flying Squirrels @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vbmZ-21\n\nShop: https://stza.co/+vbmZ-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Thunder
<2018-06-07 Thu 18:00-21:00>
:PROPERTIES:
:ID:       2fS-FhK1pgGPOL1esEoUkimL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Thunder Flying Squirrels @ Thunder

Follow on MiLB First Pitch  https //stza.co/+vbnk-a

Shop  https //stza.co/+vbnk-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Thunder
END:VALARM
DTSTART:20180607T230000Z
DTEND:20180608T020000Z
UID:2fS-FhK1pgGPOL1esEoUkimL@stanza.co
SUMMARY:Flying Squirrels @ Thunder
DESCRIPTION:Flying Squirrels @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vbnk-a\n\nShop: https://stza.co/+vbnk-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Senators
<2018-06-08 Fri 18:05-21:05>
:PROPERTIES:
:ID:       4Y467vbYSATnZuwvYglVj701@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Senators Flying Squirrels vs. Senators

Follow on MiLB First Pitch  https //stza.co/+vb8o-3C

Shop  https //stza.co/+vb8o-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Senators
END:VALARM
DTSTART:20180608T230500Z
DTEND:20180609T020500Z
UID:4Y467vbYSATnZuwvYglVj701@stanza.co
SUMMARY:Flying Squirrels vs. Senators
DESCRIPTION:Flying Squirrels vs. Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vb8o-3C\n\nShop: https://stza.co/+vb8o-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Senators
<2018-06-09 Sat 17:05-20:05>
:PROPERTIES:
:ID:       A1vul1oQz2pUqZ0Hltk_MB2b@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Senators Flying Squirrels vs. Senators

Follow on MiLB First Pitch  https //stza.co/+vb8H-2H

Shop  https //stza.co/+vb8H-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Senators
END:VALARM
DTSTART:20180609T220500Z
DTEND:20180610T010500Z
UID:A1vul1oQz2pUqZ0Hltk_MB2b@stanza.co
SUMMARY:Flying Squirrels vs. Senators
DESCRIPTION:Flying Squirrels vs. Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vb8H-2H\n\nShop: https://stza.co/+vb8H-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Senators
<2018-06-10 Sun 12:05-15:05>
:PROPERTIES:
:ID:       xKCXTJSy3KlqPpHcBCgn9uzZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Senators Flying Squirrels vs. Senators

Follow on MiLB First Pitch  https //stza.co/+vb93-28

Shop  https //stza.co/+vb93-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Senators
END:VALARM
DTSTART:20180610T170500Z
DTEND:20180610T200500Z
UID:xKCXTJSy3KlqPpHcBCgn9uzZ@stanza.co
SUMMARY:Flying Squirrels vs. Senators
DESCRIPTION:Flying Squirrels vs. Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vb93-28\n\nShop: https://stza.co/+vb93-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Sea Dogs
<2018-06-12 Tue 17:35-20:35>
:PROPERTIES:
:ID:       FZrFx-__WZhWMHsdrE3l2jJW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Sea Dogs Flying Squirrels vs. Sea Dogs

Follow on MiLB First Pitch  https //stza.co/+vb9k-M

Shop  https //stza.co/+vb9k-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Sea Dogs
END:VALARM
DTSTART:20180612T223500Z
DTEND:20180613T013500Z
UID:FZrFx-__WZhWMHsdrE3l2jJW@stanza.co
SUMMARY:Flying Squirrels vs. Sea Dogs
DESCRIPTION:Flying Squirrels vs. Sea Dogs\n\nFollow on MiLB First Pitch: https://stza.co/+vb9k-M\n\nShop: https://stza.co/+vb9k-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Sea Dogs
<2018-06-13 Wed 17:35-20:35>
:PROPERTIES:
:ID:       -CiVOhR-TDG3eFHqabvliDjK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Sea Dogs Flying Squirrels vs. Sea Dogs

Follow on MiLB First Pitch  https //stza.co/+vb9D-1X

Shop  https //stza.co/+vb9D-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Sea Dogs
END:VALARM
DTSTART:20180613T223500Z
DTEND:20180614T013500Z
UID:-CiVOhR-TDG3eFHqabvliDjK@stanza.co
SUMMARY:Flying Squirrels vs. Sea Dogs
DESCRIPTION:Flying Squirrels vs. Sea Dogs\n\nFollow on MiLB First Pitch: https://stza.co/+vb9D-1X\n\nShop: https://stza.co/+vb9D-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Sea Dogs
<2018-06-14 Thu 17:35-20:35>
:PROPERTIES:
:ID:       qAtrMkPOnrn1ys813VED5pOy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Sea Dogs Flying Squirrels vs. Sea Dogs

Follow on MiLB First Pitch  https //stza.co/+vb9W-q

Shop  https //stza.co/+vb9W-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Sea Dogs
END:VALARM
DTSTART:20180614T223500Z
DTEND:20180615T013500Z
UID:qAtrMkPOnrn1ys813VED5pOy@stanza.co
SUMMARY:Flying Squirrels vs. Sea Dogs
DESCRIPTION:Flying Squirrels vs. Sea Dogs\n\nFollow on MiLB First Pitch: https://stza.co/+vb9W-q\n\nShop: https://stza.co/+vb9W-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Senators
<2018-06-15 Fri 18:00-21:00>
:PROPERTIES:
:ID:       TRViju2J8uZ6cC1KrLnnGAeg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Senators Flying Squirrels @ Senators

Follow on MiLB First Pitch  https //stza.co/+vaZw-2Z

Shop  https //stza.co/+vaZw-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Senators
END:VALARM
DTSTART:20180615T230000Z
DTEND:20180616T020000Z
UID:TRViju2J8uZ6cC1KrLnnGAeg@stanza.co
SUMMARY:Flying Squirrels @ Senators
DESCRIPTION:Flying Squirrels @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vaZw-2Z\n\nShop: https://stza.co/+vaZw-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Senators
<2018-06-16 Sat 17:00-20:00>
:PROPERTIES:
:ID:       rjh1-AG3surrKhkR11D8-uIX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Senators Flying Squirrels @ Senators

Follow on MiLB First Pitch  https //stza.co/+vaZH-37

Shop  https //stza.co/+vaZH-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Senators
END:VALARM
DTSTART:20180616T220000Z
DTEND:20180617T010000Z
UID:rjh1-AG3surrKhkR11D8-uIX@stanza.co
SUMMARY:Flying Squirrels @ Senators
DESCRIPTION:Flying Squirrels @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vaZH-37\n\nShop: https://stza.co/+vaZH-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Senators
<2018-06-17 Sun 12:30-15:30>
:PROPERTIES:
:ID:       qqDordRzS7M9N8rXypS1QOIa@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Senators Flying Squirrels @ Senators

Follow on MiLB First Pitch  https //stza.co/+vaZP-3x

Shop  https //stza.co/+vaZP-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Senators
END:VALARM
DTSTART:20180617T173000Z
DTEND:20180617T203000Z
UID:qqDordRzS7M9N8rXypS1QOIa@stanza.co
SUMMARY:Flying Squirrels @ Senators
DESCRIPTION:Flying Squirrels @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vaZP-3x\n\nShop: https://stza.co/+vaZP-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Curve
<2018-06-19 Tue 17:35-20:35>
:PROPERTIES:
:ID:       0WQSgerELfBhlry0V8ONr498@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Curve Flying Squirrels vs. Curve

Follow on MiLB First Pitch  https //stza.co/+vbad-1I

Shop  https //stza.co/+vbad-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Curve
END:VALARM
DTSTART:20180619T223500Z
DTEND:20180620T013500Z
UID:0WQSgerELfBhlry0V8ONr498@stanza.co
SUMMARY:Flying Squirrels vs. Curve
DESCRIPTION:Flying Squirrels vs. Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vbad-1I\n\nShop: https://stza.co/+vbad-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Curve
<2018-06-20 Wed 17:35-20:35>
:PROPERTIES:
:ID:       hHcagydeGiJvTup4UNe7FpOt@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Curve Flying Squirrels vs. Curve

Follow on MiLB First Pitch  https //stza.co/+vbav-22

Shop  https //stza.co/+vbav-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Curve
END:VALARM
DTSTART:20180620T223500Z
DTEND:20180621T013500Z
UID:hHcagydeGiJvTup4UNe7FpOt@stanza.co
SUMMARY:Flying Squirrels vs. Curve
DESCRIPTION:Flying Squirrels vs. Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vbav-22\n\nShop: https://stza.co/+vbav-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Curve
<2018-06-21 Thu 17:35-20:35>
:PROPERTIES:
:ID:       f_Vu-bollh3xY3MCs7Pxa2Q7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Curve Flying Squirrels vs. Curve

Follow on MiLB First Pitch  https //stza.co/+vbaQ-b

Shop  https //stza.co/+vbaQ-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Curve
END:VALARM
DTSTART:20180621T223500Z
DTEND:20180622T013500Z
UID:f_Vu-bollh3xY3MCs7Pxa2Q7@stanza.co
SUMMARY:Flying Squirrels vs. Curve
DESCRIPTION:Flying Squirrels vs. Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vbaQ-b\n\nShop: https://stza.co/+vbaQ-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Baysox
<2018-06-22 Fri 18:05-21:05>
:PROPERTIES:
:ID:       PdO6lVJH72bAlwIArwlVCBEA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Baysox Flying Squirrels vs. Baysox

Follow on MiLB First Pitch  https //stza.co/+vbba-2m

Shop  https //stza.co/+vbba-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Baysox
END:VALARM
DTSTART:20180622T230500Z
DTEND:20180623T020500Z
UID:PdO6lVJH72bAlwIArwlVCBEA@stanza.co
SUMMARY:Flying Squirrels vs. Baysox
DESCRIPTION:Flying Squirrels vs. Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vbba-2m\n\nShop: https://stza.co/+vbba-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Baysox
<2018-06-23 Sat 17:05-20:05>
:PROPERTIES:
:ID:       pj7nnReNLKHNQKomaRXiJG4c@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Baysox Flying Squirrels vs. Baysox

Follow on MiLB First Pitch  https //stza.co/+vbbt-1E

Shop  https //stza.co/+vbbt-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Baysox
END:VALARM
DTSTART:20180623T220500Z
DTEND:20180624T010500Z
UID:pj7nnReNLKHNQKomaRXiJG4c@stanza.co
SUMMARY:Flying Squirrels vs. Baysox
DESCRIPTION:Flying Squirrels vs. Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vbbt-1E\n\nShop: https://stza.co/+vbbt-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Baysox
<2018-06-24 Sun 12:05-15:05>
:PROPERTIES:
:ID:       qGbGcJPO7VlroTE-gwgWmK-O@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Baysox Flying Squirrels vs. Baysox

Follow on MiLB First Pitch  https //stza.co/+vbbH-J

Shop  https //stza.co/+vbbH-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Baysox
END:VALARM
DTSTART:20180624T170500Z
DTEND:20180624T200500Z
UID:qGbGcJPO7VlroTE-gwgWmK-O@stanza.co
SUMMARY:Flying Squirrels vs. Baysox
DESCRIPTION:Flying Squirrels vs. Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vbbH-J\n\nShop: https://stza.co/+vbbH-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Yard Goats
<2018-06-25 Mon 18:05-21:05>
:PROPERTIES:
:ID:       -e1JxDK4rpkIiKYIgH0eC-Vt@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Yard Goats Flying Squirrels @ Yard Goats

Buy tickets here  https //stza.co/~va$4

Follow on MiLB First Pitch  https //stza.co/+va$4-3g

Shop  https //stza.co/+va$4-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Yard Goats
END:VALARM
DTSTART:20180625T230500Z
DTEND:20180626T020500Z
UID:-e1JxDK4rpkIiKYIgH0eC-Vt@stanza.co
SUMMARY:Flying Squirrels @ Yard Goats
DESCRIPTION:Flying Squirrels @ Yard Goats\n\nBuy tickets here: https://stza.co/~va$4\n\nFollow on MiLB First Pitch: https://stza.co/+va$4-3g\n\nShop: https://stza.co/+va$4-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Yard Goats
<2018-06-26 Tue 18:05-21:05>
:PROPERTIES:
:ID:       wZ8A1aDVfU8W_YY5YDRE6Kv0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Yard Goats Flying Squirrels @ Yard Goats

Buy tickets here  https //stza.co/~va$a

Follow on MiLB First Pitch  https //stza.co/+va$a-2g

Shop  https //stza.co/+va$a-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Yard Goats
END:VALARM
DTSTART:20180626T230500Z
DTEND:20180627T020500Z
UID:wZ8A1aDVfU8W_YY5YDRE6Kv0@stanza.co
SUMMARY:Flying Squirrels @ Yard Goats
DESCRIPTION:Flying Squirrels @ Yard Goats\n\nBuy tickets here: https://stza.co/~va$a\n\nFollow on MiLB First Pitch: https://stza.co/+va$a-2g\n\nShop: https://stza.co/+va$a-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Yard Goats
<2018-06-27 Wed 18:05-21:05>
:PROPERTIES:
:ID:       jkcBbxjVwB7ws2Tahj3c2nKF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Yard Goats Flying Squirrels @ Yard Goats

Buy tickets here  https //stza.co/~va$k

Follow on MiLB First Pitch  https //stza.co/+va$k-Y

Shop  https //stza.co/+va$k-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Yard Goats
END:VALARM
DTSTART:20180627T230500Z
DTEND:20180628T020500Z
UID:jkcBbxjVwB7ws2Tahj3c2nKF@stanza.co
SUMMARY:Flying Squirrels @ Yard Goats
DESCRIPTION:Flying Squirrels @ Yard Goats\n\nBuy tickets here: https://stza.co/~va$k\n\nFollow on MiLB First Pitch: https://stza.co/+va$k-Y\n\nShop: https://stza.co/+va$k-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Yard Goats
<2018-06-28 Thu 18:05-21:05>
:PROPERTIES:
:ID:       7QDi11aqBdDpli4JhjHoLQhZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Yard Goats Flying Squirrels @ Yard Goats

Buy tickets here  https //stza.co/~va$t

Follow on MiLB First Pitch  https //stza.co/+va$t-32

Shop  https //stza.co/+va$t-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Yard Goats
END:VALARM
DTSTART:20180628T230500Z
DTEND:20180629T020500Z
UID:7QDi11aqBdDpli4JhjHoLQhZ@stanza.co
SUMMARY:Flying Squirrels @ Yard Goats
DESCRIPTION:Flying Squirrels @ Yard Goats\n\nBuy tickets here: https://stza.co/~va$t\n\nFollow on MiLB First Pitch: https://stza.co/+va$t-32\n\nShop: https://stza.co/+va$t-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Senators
<2018-06-29 Fri 18:00-21:00>
:PROPERTIES:
:ID:       7ZzyZPNsKUk2cKWLwLU-ozml@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Senators Flying Squirrels @ Senators

Follow on MiLB First Pitch  https //stza.co/+vaZZ-27

Shop  https //stza.co/+vaZZ-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Senators
END:VALARM
DTSTART:20180629T230000Z
DTEND:20180630T020000Z
UID:7ZzyZPNsKUk2cKWLwLU-ozml@stanza.co
SUMMARY:Flying Squirrels @ Senators
DESCRIPTION:Flying Squirrels @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vaZZ-27\n\nShop: https://stza.co/+vaZZ-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Senators
<2018-06-30 Sat 17:00-20:00>
:PROPERTIES:
:ID:       BHqEps0Ksdp5E3AgXfXm0GJc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Senators Flying Squirrels @ Senators

Follow on MiLB First Pitch  https //stza.co/+va_4-2H

Shop  https //stza.co/+va_4-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Senators
END:VALARM
DTSTART:20180630T220000Z
DTEND:20180701T010000Z
UID:BHqEps0Ksdp5E3AgXfXm0GJc@stanza.co
SUMMARY:Flying Squirrels @ Senators
DESCRIPTION:Flying Squirrels @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+va_4-2H\n\nShop: https://stza.co/+va_4-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Senators
<2018-07-01 Sun 17:00-20:00>
:PROPERTIES:
:ID:       210A6ChwLNXUZNfE1rKHcagP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Senators Flying Squirrels @ Senators

Follow on MiLB First Pitch  https //stza.co/+va_e-2b

Shop  https //stza.co/+va_e-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Senators
END:VALARM
DTSTART:20180701T220000Z
DTEND:20180702T010000Z
UID:210A6ChwLNXUZNfE1rKHcagP@stanza.co
SUMMARY:Flying Squirrels @ Senators
DESCRIPTION:Flying Squirrels @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+va_e-2b\n\nShop: https://stza.co/+va_e-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Senators
<2018-07-02 Mon 17:30-20:30>
:PROPERTIES:
:ID:       CLhsJZ_fBlneVF2hzjCSEbGA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Senators Flying Squirrels @ Senators

Follow on MiLB First Pitch  https //stza.co/+va_n-2C

Shop  https //stza.co/+va_n-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Senators
END:VALARM
DTSTART:20180702T223000Z
DTEND:20180703T013000Z
UID:CLhsJZ_fBlneVF2hzjCSEbGA@stanza.co
SUMMARY:Flying Squirrels @ Senators
DESCRIPTION:Flying Squirrels @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+va_n-2C\n\nShop: https://stza.co/+va_n-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Senators
<2018-07-03 Tue 17:30-20:30>
:PROPERTIES:
:ID:       pAIBYOGalBvnvmcu8eWgXE1F@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Senators Flying Squirrels @ Senators

Follow on MiLB First Pitch  https //stza.co/+va_x-26

Shop  https //stza.co/+va_x-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Senators
END:VALARM
DTSTART:20180703T223000Z
DTEND:20180704T013000Z
UID:pAIBYOGalBvnvmcu8eWgXE1F@stanza.co
SUMMARY:Flying Squirrels @ Senators
DESCRIPTION:Flying Squirrels @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+va_x-26\n\nShop: https://stza.co/+va_x-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. RubberDucks
<2018-07-04 Wed 17:35-20:35>
:PROPERTIES:
:ID:       _NvjGSazBf1OAZqbIErcj8jM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. RubberDucks Flying Squirrels vs. RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vbc4-f

Shop  https //stza.co/+vbc4-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. RubberDucks
END:VALARM
DTSTART:20180704T223500Z
DTEND:20180705T013500Z
UID:_NvjGSazBf1OAZqbIErcj8jM@stanza.co
SUMMARY:Flying Squirrels vs. RubberDucks
DESCRIPTION:Flying Squirrels vs. RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vbc4-f\n\nShop: https://stza.co/+vbc4-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. RubberDucks
<2018-07-05 Thu 17:35-20:35>
:PROPERTIES:
:ID:       f504ozdebT8HBtnj6KigR0_F@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. RubberDucks Flying Squirrels vs. RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vbco-2Z

Shop  https //stza.co/+vbco-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. RubberDucks
END:VALARM
DTSTART:20180705T223500Z
DTEND:20180706T013500Z
UID:f504ozdebT8HBtnj6KigR0_F@stanza.co
SUMMARY:Flying Squirrels vs. RubberDucks
DESCRIPTION:Flying Squirrels vs. RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vbco-2Z\n\nShop: https://stza.co/+vbco-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. RubberDucks
<2018-07-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       PHLdYr5JurUkJ2YkVdozi_Sh@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. RubberDucks Flying Squirrels vs. RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vbcO-v

Shop  https //stza.co/+vbcO-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. RubberDucks
END:VALARM
DTSTART:20180706T230500Z
DTEND:20180707T020500Z
UID:PHLdYr5JurUkJ2YkVdozi_Sh@stanza.co
SUMMARY:Flying Squirrels vs. RubberDucks
DESCRIPTION:Flying Squirrels vs. RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vbcO-v\n\nShop: https://stza.co/+vbcO-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. RubberDucks
<2018-07-07 Sat 17:05-20:05>
:PROPERTIES:
:ID:       CIGDNkrMnXffwGUi01bUMkSw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. RubberDucks Flying Squirrels vs. RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vbd2-1v

Shop  https //stza.co/+vbd2-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. RubberDucks
END:VALARM
DTSTART:20180707T220500Z
DTEND:20180708T010500Z
UID:CIGDNkrMnXffwGUi01bUMkSw@stanza.co
SUMMARY:Flying Squirrels vs. RubberDucks
DESCRIPTION:Flying Squirrels vs. RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vbd2-1v\n\nShop: https://stza.co/+vbd2-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. RubberDucks
<2018-07-08 Sun 12:05-15:05>
:PROPERTIES:
:ID:       RshIPkarbdmQWPLdSk2UAqQM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. RubberDucks Flying Squirrels vs. RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vbdg-1x

Shop  https //stza.co/+vbdg-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. RubberDucks
END:VALARM
DTSTART:20180708T170500Z
DTEND:20180708T200500Z
UID:RshIPkarbdmQWPLdSk2UAqQM@stanza.co
SUMMARY:Flying Squirrels vs. RubberDucks
DESCRIPTION:Flying Squirrels vs. RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vbdg-1x\n\nShop: https://stza.co/+vbdg-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Thunder
<2018-07-12 Thu 18:00-21:00>
:PROPERTIES:
:ID:       IDE2vujby-uakP5MkLQyOg7l@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Thunder Flying Squirrels @ Thunder

Follow on MiLB First Pitch  https //stza.co/+vbnx-3f

Shop  https //stza.co/+vbnx-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Thunder
END:VALARM
DTSTART:20180712T230000Z
DTEND:20180713T020000Z
UID:IDE2vujby-uakP5MkLQyOg7l@stanza.co
SUMMARY:Flying Squirrels @ Thunder
DESCRIPTION:Flying Squirrels @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vbnx-3f\n\nShop: https://stza.co/+vbnx-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Thunder
<2018-07-13 Fri 18:00-21:00>
:PROPERTIES:
:ID:       QL8eutZY4MkVd4qtpMqB5ZNG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Thunder Flying Squirrels @ Thunder

Follow on MiLB First Pitch  https //stza.co/+vbnK-3m

Shop  https //stza.co/+vbnK-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Thunder
END:VALARM
DTSTART:20180713T230000Z
DTEND:20180714T020000Z
UID:QL8eutZY4MkVd4qtpMqB5ZNG@stanza.co
SUMMARY:Flying Squirrels @ Thunder
DESCRIPTION:Flying Squirrels @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vbnK-3m\n\nShop: https://stza.co/+vbnK-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Thunder
<2018-07-14 Sat 18:00-21:00>
:PROPERTIES:
:ID:       33_ApXffp_MjpflLrZwqu8l7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Thunder Flying Squirrels @ Thunder

Follow on MiLB First Pitch  https //stza.co/+vbnR-2z

Shop  https //stza.co/+vbnR-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Thunder
END:VALARM
DTSTART:20180714T230000Z
DTEND:20180715T020000Z
UID:33_ApXffp_MjpflLrZwqu8l7@stanza.co
SUMMARY:Flying Squirrels @ Thunder
DESCRIPTION:Flying Squirrels @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vbnR-2z\n\nShop: https://stza.co/+vbnR-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Thunder
<2018-07-15 Sun 12:00-15:00>
:PROPERTIES:
:ID:       JSc6uGdrP-dJgTA9wr1ugxVt@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Thunder Flying Squirrels @ Thunder

Follow on MiLB First Pitch  https //stza.co/+vLws-3b

Shop  https //stza.co/+vLws-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Thunder
END:VALARM
DTSTART:20180715T170000Z
DTEND:20180715T200000Z
UID:JSc6uGdrP-dJgTA9wr1ugxVt@stanza.co
SUMMARY:Flying Squirrels @ Thunder
DESCRIPTION:Flying Squirrels @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vLws-3b\n\nShop: https://stza.co/+vLws-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. SeaWolves
<2018-07-16 Mon 17:35-20:35>
:PROPERTIES:
:ID:       2Iv-TNF7xPD0qIvQ_IDTX-fU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. SeaWolves Flying Squirrels vs. SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vbdA-3t

Shop  https //stza.co/+vbdA-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. SeaWolves
END:VALARM
DTSTART:20180716T223500Z
DTEND:20180717T013500Z
UID:2Iv-TNF7xPD0qIvQ_IDTX-fU@stanza.co
SUMMARY:Flying Squirrels vs. SeaWolves
DESCRIPTION:Flying Squirrels vs. SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vbdA-3t\n\nShop: https://stza.co/+vbdA-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. SeaWolves
<2018-07-17 Tue 17:35-20:35>
:PROPERTIES:
:ID:       YBZNE7RK5AiLKDo6yFEjbJuI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. SeaWolves Flying Squirrels vs. SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vbdT-9

Shop  https //stza.co/+vbdT-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. SeaWolves
END:VALARM
DTSTART:20180717T223500Z
DTEND:20180718T013500Z
UID:YBZNE7RK5AiLKDo6yFEjbJuI@stanza.co
SUMMARY:Flying Squirrels vs. SeaWolves
DESCRIPTION:Flying Squirrels vs. SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vbdT-9\n\nShop: https://stza.co/+vbdT-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. SeaWolves
<2018-07-18 Wed 11:05-14:05>
:PROPERTIES:
:ID:       Sh-rkRhXTj8nkk8ciWAIuVvc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. SeaWolves Flying Squirrels vs. SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vbed-3M

Shop  https //stza.co/+vbed-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. SeaWolves
END:VALARM
DTSTART:20180718T160500Z
DTEND:20180718T190500Z
UID:Sh-rkRhXTj8nkk8ciWAIuVvc@stanza.co
SUMMARY:Flying Squirrels vs. SeaWolves
DESCRIPTION:Flying Squirrels vs. SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vbed-3M\n\nShop: https://stza.co/+vbed-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ RubberDucks
<2018-07-19 Thu 18:05-21:05>
:PROPERTIES:
:ID:       pUZ71AgqmxZHpfpDWJIgMWmu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ RubberDucks Flying Squirrels @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLw5-3S

Shop  https //stza.co/+vLw5-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ RubberDucks
END:VALARM
DTSTART:20180719T230500Z
DTEND:20180720T020500Z
UID:pUZ71AgqmxZHpfpDWJIgMWmu@stanza.co
SUMMARY:Flying Squirrels @ RubberDucks
DESCRIPTION:Flying Squirrels @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLw5-3S\n\nShop: https://stza.co/+vLw5-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ RubberDucks
<2018-07-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       -PPnT8m7p70i34UiWWdndXZJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ RubberDucks Flying Squirrels @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLw6-1h

Shop  https //stza.co/+vLw6-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ RubberDucks
END:VALARM
DTSTART:20180720T230500Z
DTEND:20180721T020500Z
UID:-PPnT8m7p70i34UiWWdndXZJ@stanza.co
SUMMARY:Flying Squirrels @ RubberDucks
DESCRIPTION:Flying Squirrels @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLw6-1h\n\nShop: https://stza.co/+vLw6-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ RubberDucks
<2018-07-21 Sat 18:05-21:05>
:PROPERTIES:
:ID:       ijXcG8Q3pThMyuQEo47e_4WN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ RubberDucks Flying Squirrels @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLw7-21

Shop  https //stza.co/+vLw7-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ RubberDucks
END:VALARM
DTSTART:20180721T230500Z
DTEND:20180722T020500Z
UID:ijXcG8Q3pThMyuQEo47e_4WN@stanza.co
SUMMARY:Flying Squirrels @ RubberDucks
DESCRIPTION:Flying Squirrels @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLw7-21\n\nShop: https://stza.co/+vLw7-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ RubberDucks
<2018-07-22 Sun 13:05-16:05>
:PROPERTIES:
:ID:       HiYK2cQibWa8jtWFb8sdB3aM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ RubberDucks Flying Squirrels @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLw8-P

Shop  https //stza.co/+vLw8-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ RubberDucks
END:VALARM
DTSTART:20180722T180500Z
DTEND:20180722T210500Z
UID:HiYK2cQibWa8jtWFb8sdB3aM@stanza.co
SUMMARY:Flying Squirrels @ RubberDucks
DESCRIPTION:Flying Squirrels @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLw8-P\n\nShop: https://stza.co/+vLw8-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ SeaWolves
<2018-07-23 Mon 18:05-21:05>
:PROPERTIES:
:ID:       Prkn3-r9n15AiDZZuubGT9kc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ SeaWolves Flying Squirrels @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vaZ5-T

Shop  https //stza.co/+vaZ5-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ SeaWolves
END:VALARM
DTSTART:20180723T230500Z
DTEND:20180724T020500Z
UID:Prkn3-r9n15AiDZZuubGT9kc@stanza.co
SUMMARY:Flying Squirrels @ SeaWolves
DESCRIPTION:Flying Squirrels @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vaZ5-T\n\nShop: https://stza.co/+vaZ5-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ SeaWolves
<2018-07-24 Tue 18:05-21:05>
:PROPERTIES:
:ID:       gKVi_w4tpt3S2_oqoaYIaTCB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ SeaWolves Flying Squirrels @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vaZe-X

Shop  https //stza.co/+vaZe-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ SeaWolves
END:VALARM
DTSTART:20180724T230500Z
DTEND:20180725T020500Z
UID:gKVi_w4tpt3S2_oqoaYIaTCB@stanza.co
SUMMARY:Flying Squirrels @ SeaWolves
DESCRIPTION:Flying Squirrels @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vaZe-X\n\nShop: https://stza.co/+vaZe-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ SeaWolves
<2018-07-25 Wed 11:05-14:05>
:PROPERTIES:
:ID:       JAOOiPN4iZmXqVHwtXgFwnOO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ SeaWolves Flying Squirrels @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vaZn-x

Shop  https //stza.co/+vaZn-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ SeaWolves
END:VALARM
DTSTART:20180725T160500Z
DTEND:20180725T190500Z
UID:JAOOiPN4iZmXqVHwtXgFwnOO@stanza.co
SUMMARY:Flying Squirrels @ SeaWolves
DESCRIPTION:Flying Squirrels @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vaZn-x\n\nShop: https://stza.co/+vaZn-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Fightin Phils
<2018-07-26 Thu 17:35-20:35>
:PROPERTIES:
:ID:       7FfZigCb04NNo3TcneCw3bZv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Fightin Phils Flying Squirrels vs. Fightin Phils

Follow on MiLB First Pitch  https //stza.co/+vbev-1

Shop  https //stza.co/+vbev-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Fightin Phils
END:VALARM
DTSTART:20180726T223500Z
DTEND:20180727T013500Z
UID:7FfZigCb04NNo3TcneCw3bZv@stanza.co
SUMMARY:Flying Squirrels vs. Fightin Phils
DESCRIPTION:Flying Squirrels vs. Fightin Phils\n\nFollow on MiLB First Pitch: https://stza.co/+vbev-1\n\nShop: https://stza.co/+vbev-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Fightin Phils
<2018-07-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       yY1kUgW7XIeiIFqSx8uj325G@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Fightin Phils Flying Squirrels vs. Fightin Phils

Follow on MiLB First Pitch  https //stza.co/+vbeS-2c

Shop  https //stza.co/+vbeS-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Fightin Phils
END:VALARM
DTSTART:20180727T230500Z
DTEND:20180728T020500Z
UID:yY1kUgW7XIeiIFqSx8uj325G@stanza.co
SUMMARY:Flying Squirrels vs. Fightin Phils
DESCRIPTION:Flying Squirrels vs. Fightin Phils\n\nFollow on MiLB First Pitch: https://stza.co/+vbeS-2c\n\nShop: https://stza.co/+vbeS-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Fightin Phils
<2018-07-28 Sat 17:05-20:05>
:PROPERTIES:
:ID:       cdsBQGo7XAAnHCXRRclSWOeJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Fightin Phils Flying Squirrels vs. Fightin Phils

Follow on MiLB First Pitch  https //stza.co/+vbf9-1z

Shop  https //stza.co/+vbf9-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Fightin Phils
END:VALARM
DTSTART:20180728T220500Z
DTEND:20180729T010500Z
UID:cdsBQGo7XAAnHCXRRclSWOeJ@stanza.co
SUMMARY:Flying Squirrels vs. Fightin Phils
DESCRIPTION:Flying Squirrels vs. Fightin Phils\n\nFollow on MiLB First Pitch: https://stza.co/+vbf9-1z\n\nShop: https://stza.co/+vbf9-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Fightin Phils
<2018-07-29 Sun 12:05-15:05>
:PROPERTIES:
:ID:       hsGt3zRLuJiD7IJv9yn4LcEU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Fightin Phils Flying Squirrels vs. Fightin Phils

Follow on MiLB First Pitch  https //stza.co/+vbfv-2U

Shop  https //stza.co/+vbfv-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Fightin Phils
END:VALARM
DTSTART:20180729T170500Z
DTEND:20180729T200500Z
UID:hsGt3zRLuJiD7IJv9yn4LcEU@stanza.co
SUMMARY:Flying Squirrels vs. Fightin Phils
DESCRIPTION:Flying Squirrels vs. Fightin Phils\n\nFollow on MiLB First Pitch: https://stza.co/+vbfv-2U\n\nShop: https://stza.co/+vbfv-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Fisher Cats
<2018-07-31 Tue 18:05-21:05>
:PROPERTIES:
:ID:       pg6KB0wfizXaVbcBcU13laIP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Fisher Cats Flying Squirrels @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+va$A-r

Shop  https //stza.co/+va$A-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Fisher Cats
END:VALARM
DTSTART:20180731T230500Z
DTEND:20180801T020500Z
UID:pg6KB0wfizXaVbcBcU13laIP@stanza.co
SUMMARY:Flying Squirrels @ Fisher Cats
DESCRIPTION:Flying Squirrels @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+va$A-r\n\nShop: https://stza.co/+va$A-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Fisher Cats
<2018-08-01 Wed 11:05-14:05>
:PROPERTIES:
:ID:       H14VdAF901fbaIz9_6N2OIvN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Fisher Cats Flying Squirrels @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+va$K-19

Shop  https //stza.co/+va$K-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Fisher Cats
END:VALARM
DTSTART:20180801T160500Z
DTEND:20180801T190500Z
UID:H14VdAF901fbaIz9_6N2OIvN@stanza.co
SUMMARY:Flying Squirrels @ Fisher Cats
DESCRIPTION:Flying Squirrels @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+va$K-19\n\nShop: https://stza.co/+va$K-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Fisher Cats
<2018-08-02 Thu 18:05-21:05>
:PROPERTIES:
:ID:       myZ4YFNL5w6BnPMC5uG4AR60@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Fisher Cats Flying Squirrels @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+va$T-1d

Shop  https //stza.co/+va$T-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Fisher Cats
END:VALARM
DTSTART:20180802T230500Z
DTEND:20180803T020500Z
UID:myZ4YFNL5w6BnPMC5uG4AR60@stanza.co
SUMMARY:Flying Squirrels @ Fisher Cats
DESCRIPTION:Flying Squirrels @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+va$T-1d\n\nShop: https://stza.co/+va$T-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Sea Dogs
<2018-08-03 Fri 18:00-21:00>
:PROPERTIES:
:ID:       oK978V-iDTgTryGKLcAddAyO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Sea Dogs Flying Squirrels @ Sea Dogs

Buy tickets here  https //stza.co/~vb00

Follow on MiLB First Pitch  https //stza.co/+vb00-1w

Shop  https //stza.co/+vb00-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Sea Dogs
END:VALARM
DTSTART:20180803T230000Z
DTEND:20180804T020000Z
UID:oK978V-iDTgTryGKLcAddAyO@stanza.co
SUMMARY:Flying Squirrels @ Sea Dogs
DESCRIPTION:Flying Squirrels @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vb00\n\nFollow on MiLB First Pitch: https://stza.co/+vb00-1w\n\nShop: https://stza.co/+vb00-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Sea Dogs
<2018-08-04 Sat 17:00-20:00>
:PROPERTIES:
:ID:       NOu3bEMM29C0nYGdIjIRsXfu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Sea Dogs Flying Squirrels @ Sea Dogs

Buy tickets here  https //stza.co/~vb09

Follow on MiLB First Pitch  https //stza.co/+vb09-A

Shop  https //stza.co/+vb09-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Sea Dogs
END:VALARM
DTSTART:20180804T220000Z
DTEND:20180805T010000Z
UID:NOu3bEMM29C0nYGdIjIRsXfu@stanza.co
SUMMARY:Flying Squirrels @ Sea Dogs
DESCRIPTION:Flying Squirrels @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vb09\n\nFollow on MiLB First Pitch: https://stza.co/+vb09-A\n\nShop: https://stza.co/+vb09-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Sea Dogs
<2018-08-05 Sun 12:00-15:00>
:PROPERTIES:
:ID:       oxFSNm-pvQT1dRAYhw06iD61@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Sea Dogs Flying Squirrels @ Sea Dogs

Buy tickets here  https //stza.co/~vb0i

Follow on MiLB First Pitch  https //stza.co/+vb0i-1A

Shop  https //stza.co/+vb0i-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Sea Dogs
END:VALARM
DTSTART:20180805T170000Z
DTEND:20180805T200000Z
UID:oxFSNm-pvQT1dRAYhw06iD61@stanza.co
SUMMARY:Flying Squirrels @ Sea Dogs
DESCRIPTION:Flying Squirrels @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vb0i\n\nFollow on MiLB First Pitch: https://stza.co/+vb0i-1A\n\nShop: https://stza.co/+vb0i-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Rumble Ponies
<2018-08-07 Tue 17:35-20:35>
:PROPERTIES:
:ID:       NV5xgnIy65C0KTOd7fm62j9e@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Rumble Ponies Flying Squirrels vs. Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vbfL-1N

Shop  https //stza.co/+vbfL-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Rumble Ponies
END:VALARM
DTSTART:20180807T223500Z
DTEND:20180808T013500Z
UID:NV5xgnIy65C0KTOd7fm62j9e@stanza.co
SUMMARY:Flying Squirrels vs. Rumble Ponies
DESCRIPTION:Flying Squirrels vs. Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vbfL-1N\n\nShop: https://stza.co/+vbfL-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Rumble Ponies
<2018-08-08 Wed 17:35-20:35>
:PROPERTIES:
:ID:       C1BvltShoUt_6sOx9lDjJR1W@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Rumble Ponies Flying Squirrels vs. Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vbf$-3P

Shop  https //stza.co/+vbf$-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Rumble Ponies
END:VALARM
DTSTART:20180808T223500Z
DTEND:20180809T013500Z
UID:C1BvltShoUt_6sOx9lDjJR1W@stanza.co
SUMMARY:Flying Squirrels vs. Rumble Ponies
DESCRIPTION:Flying Squirrels vs. Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vbf$-3P\n\nShop: https://stza.co/+vbf$-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Rumble Ponies
<2018-08-09 Thu 17:35-20:35>
:PROPERTIES:
:ID:       1M8byTEBGhT314D-ZYwqYYuO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Rumble Ponies Flying Squirrels vs. Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vbgg-1s

Shop  https //stza.co/+vbgg-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Rumble Ponies
END:VALARM
DTSTART:20180809T223500Z
DTEND:20180810T013500Z
UID:1M8byTEBGhT314D-ZYwqYYuO@stanza.co
SUMMARY:Flying Squirrels vs. Rumble Ponies
DESCRIPTION:Flying Squirrels vs. Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vbgg-1s\n\nShop: https://stza.co/+vbgg-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Fisher Cats
<2018-08-10 Fri 18:05-21:05>
:PROPERTIES:
:ID:       IMGex8r7fDCGwtVbzwgf5WpX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Fisher Cats Flying Squirrels vs. Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vbgE-34

Shop  https //stza.co/+vbgE-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Fisher Cats
END:VALARM
DTSTART:20180810T230500Z
DTEND:20180811T020500Z
UID:IMGex8r7fDCGwtVbzwgf5WpX@stanza.co
SUMMARY:Flying Squirrels vs. Fisher Cats
DESCRIPTION:Flying Squirrels vs. Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vbgE-34\n\nShop: https://stza.co/+vbgE-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Fisher Cats
<2018-08-11 Sat 17:05-20:05>
:PROPERTIES:
:ID:       m8OWqgZoI51gwrT2ijN_y4xy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Fisher Cats Flying Squirrels vs. Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vbgZ-1_

Shop  https //stza.co/+vbgZ-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Fisher Cats
END:VALARM
DTSTART:20180811T220500Z
DTEND:20180812T010500Z
UID:m8OWqgZoI51gwrT2ijN_y4xy@stanza.co
SUMMARY:Flying Squirrels vs. Fisher Cats
DESCRIPTION:Flying Squirrels vs. Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vbgZ-1_\n\nShop: https://stza.co/+vbgZ-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Fisher Cats
<2018-08-12 Sun 12:05-15:05>
:PROPERTIES:
:ID:       ycl3ubHIorCYmlNynHDyFI-e@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Fisher Cats Flying Squirrels vs. Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vbhl-3L

Shop  https //stza.co/+vbhl-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Fisher Cats
END:VALARM
DTSTART:20180812T170500Z
DTEND:20180812T200500Z
UID:ycl3ubHIorCYmlNynHDyFI-e@stanza.co
SUMMARY:Flying Squirrels vs. Fisher Cats
DESCRIPTION:Flying Squirrels vs. Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vbhl-3L\n\nShop: https://stza.co/+vbhl-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Baysox
<2018-08-14 Tue 18:05-21:05>
:PROPERTIES:
:ID:       S1sZABBFdb0tJjk04A-sQHHF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Baysox Flying Squirrels @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vLwo-2l

Shop  https //stza.co/+vLwo-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Baysox
END:VALARM
DTSTART:20180814T230500Z
DTEND:20180815T020500Z
UID:S1sZABBFdb0tJjk04A-sQHHF@stanza.co
SUMMARY:Flying Squirrels @ Baysox
DESCRIPTION:Flying Squirrels @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLwo-2l\n\nShop: https://stza.co/+vLwo-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Baysox
<2018-08-15 Wed 18:05-21:05>
:PROPERTIES:
:ID:       6Zu-FTNT9Iw2UO4avpWV95Db@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Baysox Flying Squirrels @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vLwp-2P

Shop  https //stza.co/+vLwp-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Baysox
END:VALARM
DTSTART:20180815T230500Z
DTEND:20180816T020500Z
UID:6Zu-FTNT9Iw2UO4avpWV95Db@stanza.co
SUMMARY:Flying Squirrels @ Baysox
DESCRIPTION:Flying Squirrels @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLwp-2P\n\nShop: https://stza.co/+vLwp-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Baysox
<2018-08-16 Thu 18:05-21:05>
:PROPERTIES:
:ID:       3Bezozv3ulEU061RBTNVa-12@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Baysox Flying Squirrels @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vLwq-19

Shop  https //stza.co/+vLwq-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Baysox
END:VALARM
DTSTART:20180816T230500Z
DTEND:20180817T020500Z
UID:3Bezozv3ulEU061RBTNVa-12@stanza.co
SUMMARY:Flying Squirrels @ Baysox
DESCRIPTION:Flying Squirrels @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLwq-19\n\nShop: https://stza.co/+vLwq-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Yard Goats
<2018-08-17 Fri 18:05-21:05>
:PROPERTIES:
:ID:       Pv08haIsKZfuhRdhjd7BP6g9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Yard Goats Flying Squirrels vs. Yard Goats

Follow on MiLB First Pitch  https //stza.co/+vbhz-1S

Shop  https //stza.co/+vbhz-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Yard Goats
END:VALARM
DTSTART:20180817T230500Z
DTEND:20180818T020500Z
UID:Pv08haIsKZfuhRdhjd7BP6g9@stanza.co
SUMMARY:Flying Squirrels vs. Yard Goats
DESCRIPTION:Flying Squirrels vs. Yard Goats\n\nFollow on MiLB First Pitch: https://stza.co/+vbhz-1S\n\nShop: https://stza.co/+vbhz-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Yard Goats
<2018-08-18 Sat 17:05-20:05>
:PROPERTIES:
:ID:       AVfnzHP1-QUjFINynk3TIPU0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Yard Goats Flying Squirrels vs. Yard Goats

Follow on MiLB First Pitch  https //stza.co/+vbhT-2d

Shop  https //stza.co/+vbhT-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Yard Goats
END:VALARM
DTSTART:20180818T220500Z
DTEND:20180819T010500Z
UID:AVfnzHP1-QUjFINynk3TIPU0@stanza.co
SUMMARY:Flying Squirrels vs. Yard Goats
DESCRIPTION:Flying Squirrels vs. Yard Goats\n\nFollow on MiLB First Pitch: https://stza.co/+vbhT-2d\n\nShop: https://stza.co/+vbhT-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Yard Goats
<2018-08-19 Sun 12:05-15:05>
:PROPERTIES:
:ID:       HiwAvjxZNUXgY_sFfRYrfLPv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Yard Goats Flying Squirrels vs. Yard Goats

Follow on MiLB First Pitch  https //stza.co/+vbi0-3j

Shop  https //stza.co/+vbi0-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Yard Goats
END:VALARM
DTSTART:20180819T170500Z
DTEND:20180819T200500Z
UID:HiwAvjxZNUXgY_sFfRYrfLPv@stanza.co
SUMMARY:Flying Squirrels vs. Yard Goats
DESCRIPTION:Flying Squirrels vs. Yard Goats\n\nFollow on MiLB First Pitch: https://stza.co/+vbi0-3j\n\nShop: https://stza.co/+vbi0-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Baysox
<2018-08-20 Mon 17:35-20:35>
:PROPERTIES:
:ID:       CqAkddAaCpYPeRka2C1c181S@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Baysox Flying Squirrels vs. Baysox

Follow on MiLB First Pitch  https //stza.co/+vbiq-18

Shop  https //stza.co/+vbiq-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Baysox
END:VALARM
DTSTART:20180820T223500Z
DTEND:20180821T013500Z
UID:CqAkddAaCpYPeRka2C1c181S@stanza.co
SUMMARY:Flying Squirrels vs. Baysox
DESCRIPTION:Flying Squirrels vs. Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vbiq-18\n\nShop: https://stza.co/+vbiq-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Baysox
<2018-08-21 Tue 17:35-20:35>
:PROPERTIES:
:ID:       5fqUoTa2Xtpci_pYVoXN-wtL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Baysox Flying Squirrels vs. Baysox

Follow on MiLB First Pitch  https //stza.co/+vbiG-1w

Shop  https //stza.co/+vbiG-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Baysox
END:VALARM
DTSTART:20180821T223500Z
DTEND:20180822T013500Z
UID:5fqUoTa2Xtpci_pYVoXN-wtL@stanza.co
SUMMARY:Flying Squirrels vs. Baysox
DESCRIPTION:Flying Squirrels vs. Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vbiG-1w\n\nShop: https://stza.co/+vbiG-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Baysox
<2018-08-22 Wed 18:05-21:05>
:PROPERTIES:
:ID:       r0FvSxI_M4MGVCjW8VOE8_Sv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Baysox Flying Squirrels @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vLwr-7

Shop  https //stza.co/+vLwr-1J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Baysox
END:VALARM
DTSTART:20180822T230500Z
DTEND:20180823T020500Z
UID:r0FvSxI_M4MGVCjW8VOE8_Sv@stanza.co
SUMMARY:Flying Squirrels @ Baysox
DESCRIPTION:Flying Squirrels @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLwr-7\n\nShop: https://stza.co/+vLwr-1J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Baysox
<2018-08-23 Thu 18:05-21:05>
:PROPERTIES:
:ID:       N_KxWhdOY4e72-w8QRlcSYCB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Baysox Flying Squirrels @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vaYY-2x

Shop  https //stza.co/+vaYY-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Baysox
END:VALARM
DTSTART:20180823T230500Z
DTEND:20180824T020500Z
UID:N_KxWhdOY4e72-w8QRlcSYCB@stanza.co
SUMMARY:Flying Squirrels @ Baysox
DESCRIPTION:Flying Squirrels @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vaYY-2x\n\nShop: https://stza.co/+vaYY-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Curve
<2018-08-24 Fri 17:00-20:00>
:PROPERTIES:
:ID:       OFg3uGVMVi0advnAoMI2rrSQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Curve Flying Squirrels @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLwf-3g

Shop  https //stza.co/+vLwf-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Curve
END:VALARM
DTSTART:20180824T220000Z
DTEND:20180825T010000Z
UID:OFg3uGVMVi0advnAoMI2rrSQ@stanza.co
SUMMARY:Flying Squirrels @ Curve
DESCRIPTION:Flying Squirrels @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLwf-3g\n\nShop: https://stza.co/+vLwf-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Curve
<2018-08-25 Sat 17:00-20:00>
:PROPERTIES:
:ID:       ZlW6-QQcvjvIjy0-fbDYIyyS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Curve Flying Squirrels @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLwg-1_

Shop  https //stza.co/+vLwg-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Curve
END:VALARM
DTSTART:20180825T220000Z
DTEND:20180826T010000Z
UID:ZlW6-QQcvjvIjy0-fbDYIyyS@stanza.co
SUMMARY:Flying Squirrels @ Curve
DESCRIPTION:Flying Squirrels @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLwg-1_\n\nShop: https://stza.co/+vLwg-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels @ Curve
<2018-08-26 Sun 17:00-20:00>
:PROPERTIES:
:ID:       VZd5jGpWP3C8gHbcaJ3T3Y1-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels @ Curve Flying Squirrels @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLwh-2z

Shop  https //stza.co/+vLwh-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels @ Curve
END:VALARM
DTSTART:20180826T220000Z
DTEND:20180827T010000Z
UID:VZd5jGpWP3C8gHbcaJ3T3Y1-@stanza.co
SUMMARY:Flying Squirrels @ Curve
DESCRIPTION:Flying Squirrels @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLwh-2z\n\nShop: https://stza.co/+vLwh-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Fightin Phils
<2018-08-27 Mon 17:35-20:35>
:PROPERTIES:
:ID:       f4yNAtgPaVcfKj93I1hHc0WO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Fightin Phils Flying Squirrels vs. Fightin Phils

Follow on MiLB First Pitch  https //stza.co/+vbi_-1r

Shop  https //stza.co/+vbi_-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Fightin Phils
END:VALARM
DTSTART:20180827T223500Z
DTEND:20180828T013500Z
UID:f4yNAtgPaVcfKj93I1hHc0WO@stanza.co
SUMMARY:Flying Squirrels vs. Fightin Phils
DESCRIPTION:Flying Squirrels vs. Fightin Phils\n\nFollow on MiLB First Pitch: https://stza.co/+vbi_-1r\n\nShop: https://stza.co/+vbi_-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Fightin Phils
<2018-08-28 Tue 17:35-20:35>
:PROPERTIES:
:ID:       SJsk--WAzRioXdxwZmTQVtFD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Fightin Phils Flying Squirrels vs. Fightin Phils

Follow on MiLB First Pitch  https //stza.co/+vbjh-29

Shop  https //stza.co/+vbjh-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Fightin Phils
END:VALARM
DTSTART:20180828T223500Z
DTEND:20180829T013500Z
UID:SJsk--WAzRioXdxwZmTQVtFD@stanza.co
SUMMARY:Flying Squirrels vs. Fightin Phils
DESCRIPTION:Flying Squirrels vs. Fightin Phils\n\nFollow on MiLB First Pitch: https://stza.co/+vbjh-29\n\nShop: https://stza.co/+vbjh-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Fightin Phils
<2018-08-29 Wed 17:35-20:35>
:PROPERTIES:
:ID:       LGserUwluYd27oTAlDeT8j3U@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Fightin Phils Flying Squirrels vs. Fightin Phils

Follow on MiLB First Pitch  https //stza.co/+vbjC-3C

Shop  https //stza.co/+vbjC-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Fightin Phils
END:VALARM
DTSTART:20180829T223500Z
DTEND:20180830T013500Z
UID:LGserUwluYd27oTAlDeT8j3U@stanza.co
SUMMARY:Flying Squirrels vs. Fightin Phils
DESCRIPTION:Flying Squirrels vs. Fightin Phils\n\nFollow on MiLB First Pitch: https://stza.co/+vbjC-3C\n\nShop: https://stza.co/+vbjC-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Fightin Phils
<2018-08-30 Thu 17:35-20:35>
:PROPERTIES:
:ID:       tAhjim3UbAEHb0ATrNk3mlfA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Fightin Phils Flying Squirrels vs. Fightin Phils

Follow on MiLB First Pitch  https //stza.co/+vbjV-1O

Shop  https //stza.co/+vbjV-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Fightin Phils
END:VALARM
DTSTART:20180830T223500Z
DTEND:20180831T013500Z
UID:tAhjim3UbAEHb0ATrNk3mlfA@stanza.co
SUMMARY:Flying Squirrels vs. Fightin Phils
DESCRIPTION:Flying Squirrels vs. Fightin Phils\n\nFollow on MiLB First Pitch: https://stza.co/+vbjV-1O\n\nShop: https://stza.co/+vbjV-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Senators
<2018-08-31 Fri 18:05-21:05>
:PROPERTIES:
:ID:       wHCj3g0pcxuuKyL-f6p34pAs@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Senators Flying Squirrels vs. Senators

Follow on MiLB First Pitch  https //stza.co/+vbki-1Z

Shop  https //stza.co/+vbki-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Senators
END:VALARM
DTSTART:20180831T230500Z
DTEND:20180901T020500Z
UID:wHCj3g0pcxuuKyL-f6p34pAs@stanza.co
SUMMARY:Flying Squirrels vs. Senators
DESCRIPTION:Flying Squirrels vs. Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vbki-1Z\n\nShop: https://stza.co/+vbki-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Senators
<2018-09-01 Sat 17:05-20:05>
:PROPERTIES:
:ID:       GoEbfPPC4OByveGelkqrICy4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Senators Flying Squirrels vs. Senators

Follow on MiLB First Pitch  https //stza.co/+vbkA-1X

Shop  https //stza.co/+vbkA-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Senators
END:VALARM
DTSTART:20180901T220500Z
DTEND:20180902T010500Z
UID:GoEbfPPC4OByveGelkqrICy4@stanza.co
SUMMARY:Flying Squirrels vs. Senators
DESCRIPTION:Flying Squirrels vs. Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vbkA-1X\n\nShop: https://stza.co/+vbkA-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Senators
<2018-09-02 Sun 17:05-20:05>
:PROPERTIES:
:ID:       0txfYwrynOZkglRsUuna7fYF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Senators Flying Squirrels vs. Senators

Follow on MiLB First Pitch  https //stza.co/+vbkW-26

Shop  https //stza.co/+vbkW-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Senators
END:VALARM
DTSTART:20180902T220500Z
DTEND:20180903T010500Z
UID:0txfYwrynOZkglRsUuna7fYF@stanza.co
SUMMARY:Flying Squirrels vs. Senators
DESCRIPTION:Flying Squirrels vs. Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vbkW-26\n\nShop: https://stza.co/+vbkW-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Flying Squirrels vs. Senators
<2018-09-03 Mon 12:05-15:05>
:PROPERTIES:
:ID:       Kv9o4qt6p95x7WRchxukai4F@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Flying Squirrels vs. Senators Flying Squirrels vs. Senators

Follow on MiLB First Pitch  https //stza.co/+vble-2K

Shop  https //stza.co/+vble-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Flying Squirrels vs. Senators
END:VALARM
DTSTART:20180903T170500Z
DTEND:20180903T200500Z
UID:Kv9o4qt6p95x7WRchxukai4F@stanza.co
SUMMARY:Flying Squirrels vs. Senators
DESCRIPTION:Flying Squirrels vs. Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vble-2K\n\nShop: https://stza.co/+vble-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
