#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Spinners @ Tigers
<2018-06-15 Fri>--<2018-06-14 Thu>
:PROPERTIES:
:ID:       4hhJALC31BVAmMoy9YH4yVKr@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners @ Tigers Spinners @ Tigers

Follow on MiLB First Pitch  https //stza.co/+xMoE-1W

Shop  https //stza.co/+xMoE-3_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ Tigers
END:VALARM
DTSTART;VALUE=DATE:20180615
DTEND;VALUE=DATE:20180615
UID:4hhJALC31BVAmMoy9YH4yVKr@stanza.co
SUMMARY:Spinners @ Tigers
DESCRIPTION:Spinners @ Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMoE-1W\n\nShop: https://stza.co/+xMoE-3_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ Tigers
<2018-06-16 Sat>--<2018-06-15 Fri>
:PROPERTIES:
:ID:       3zqpHepeRTnX8Q0wyw-Idgt8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Spinners @ Tigers Spinners @ Tigers

Follow on MiLB First Pitch  https //stza.co/+xMoF-3N

Shop  https //stza.co/+xMoF-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ Tigers
END:VALARM
DTSTART;VALUE=DATE:20180616
DTEND;VALUE=DATE:20180616
UID:3zqpHepeRTnX8Q0wyw-Idgt8@stanza.co
SUMMARY:Spinners @ Tigers
DESCRIPTION:Spinners @ Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMoF-3N\n\nShop: https://stza.co/+xMoF-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ Tigers
<2018-06-17 Sun>--<2018-06-16 Sat>
:PROPERTIES:
:ID:       kWea_MU3eMJqwJuQaK5hCOco@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners @ Tigers Spinners @ Tigers

Follow on MiLB First Pitch  https //stza.co/+xMoG-O

Shop  https //stza.co/+xMoG-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ Tigers
END:VALARM
DTSTART;VALUE=DATE:20180617
DTEND;VALUE=DATE:20180617
UID:kWea_MU3eMJqwJuQaK5hCOco@stanza.co
SUMMARY:Spinners @ Tigers
DESCRIPTION:Spinners @ Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMoG-O\n\nShop: https://stza.co/+xMoG-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. Yankees
<2018-06-18 Mon>--<2018-06-17 Sun>
:PROPERTIES:
:ID:       m2SaFbyQusD1XxStTIoPSzhs@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners vs. Yankees Spinners vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xMoQ-2d

Shop  https //stza.co/+xMoQ-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. Yankees
END:VALARM
DTSTART;VALUE=DATE:20180618
DTEND;VALUE=DATE:20180618
UID:m2SaFbyQusD1XxStTIoPSzhs@stanza.co
SUMMARY:Spinners vs. Yankees
DESCRIPTION:Spinners vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMoQ-2d\n\nShop: https://stza.co/+xMoQ-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. Yankees
<2018-06-19 Tue>--<2018-06-18 Mon>
:PROPERTIES:
:ID:       A2R2YeCyy_JsqE0Uap4o7Vhy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Spinners vs. Yankees Spinners vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xMoT-3r

Shop  https //stza.co/+xMoT-2S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. Yankees
END:VALARM
DTSTART;VALUE=DATE:20180619
DTEND;VALUE=DATE:20180619
UID:A2R2YeCyy_JsqE0Uap4o7Vhy@stanza.co
SUMMARY:Spinners vs. Yankees
DESCRIPTION:Spinners vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMoT-3r\n\nShop: https://stza.co/+xMoT-2S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. Yankees
<2018-06-20 Wed>--<2018-06-19 Tue>
:PROPERTIES:
:ID:       TRaYn2OE4Pb17Fh4t2D8ouRP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners vs. Yankees Spinners vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xMoU-1f

Shop  https //stza.co/+xMoU-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. Yankees
END:VALARM
DTSTART;VALUE=DATE:20180620
DTEND;VALUE=DATE:20180620
UID:TRaYn2OE4Pb17Fh4t2D8ouRP@stanza.co
SUMMARY:Spinners vs. Yankees
DESCRIPTION:Spinners vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMoU-1f\n\nShop: https://stza.co/+xMoU-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ ValleyCats
<2018-06-21 Thu>--<2018-06-20 Wed>
:PROPERTIES:
:ID:       askKq8189KHYE_fBisjn0yg7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners @ ValleyCats Spinners @ ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMq6-2z

Shop  https //stza.co/+xMq6-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180621
DTEND;VALUE=DATE:20180621
UID:askKq8189KHYE_fBisjn0yg7@stanza.co
SUMMARY:Spinners @ ValleyCats
DESCRIPTION:Spinners @ ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMq6-2z\n\nShop: https://stza.co/+xMq6-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ ValleyCats
<2018-06-22 Fri>--<2018-06-21 Thu>
:PROPERTIES:
:ID:       2dMhB_I4a3wgZX1O-YhowjtC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Spinners @ ValleyCats Spinners @ ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMq7-I

Shop  https //stza.co/+xMq7-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180622
DTEND;VALUE=DATE:20180622
UID:2dMhB_I4a3wgZX1O-YhowjtC@stanza.co
SUMMARY:Spinners @ ValleyCats
DESCRIPTION:Spinners @ ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMq7-I\n\nShop: https://stza.co/+xMq7-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ ValleyCats
<2018-06-23 Sat>--<2018-06-22 Fri>
:PROPERTIES:
:ID:       XwFdU23CwQW2FlM7frxM180Q@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners @ ValleyCats Spinners @ ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMq8-Z

Shop  https //stza.co/+xMq8-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180623
DTEND;VALUE=DATE:20180623
UID:XwFdU23CwQW2FlM7frxM180Q@stanza.co
SUMMARY:Spinners @ ValleyCats
DESCRIPTION:Spinners @ ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMq8-Z\n\nShop: https://stza.co/+xMq8-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ Cyclones
<2018-06-24 Sun>--<2018-06-23 Sat>
:PROPERTIES:
:ID:       9VIMGoSKxqqQS6yTbxcv_f8Z@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners @ Cyclones Spinners @ Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMoy-1I

Shop  https //stza.co/+xMoy-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180624
DTEND;VALUE=DATE:20180624
UID:9VIMGoSKxqqQS6yTbxcv_f8Z@stanza.co
SUMMARY:Spinners @ Cyclones
DESCRIPTION:Spinners @ Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMoy-1I\n\nShop: https://stza.co/+xMoy-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ Cyclones
<2018-06-25 Mon>--<2018-06-24 Sun>
:PROPERTIES:
:ID:       G_pxbfumGQP5Ro1oyFygVz0A@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Spinners @ Cyclones Spinners @ Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMoz-2$

Shop  https //stza.co/+xMoz-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180625
DTEND;VALUE=DATE:20180625
UID:G_pxbfumGQP5Ro1oyFygVz0A@stanza.co
SUMMARY:Spinners @ Cyclones
DESCRIPTION:Spinners @ Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMoz-2$\n\nShop: https://stza.co/+xMoz-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ Cyclones
<2018-06-26 Tue>--<2018-06-25 Mon>
:PROPERTIES:
:ID:       siqoVlFiky4t4Yem2UbdfngF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners @ Cyclones Spinners @ Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMoA-3j

Shop  https //stza.co/+xMoA-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180626
DTEND;VALUE=DATE:20180626
UID:siqoVlFiky4t4Yem2UbdfngF@stanza.co
SUMMARY:Spinners @ Cyclones
DESCRIPTION:Spinners @ Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMoA-3j\n\nShop: https://stza.co/+xMoA-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. IronBirds
<2018-06-28 Thu>--<2018-06-27 Wed>
:PROPERTIES:
:ID:       4oXC_-qPrEfYl1vXh4nMlcWD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners vs. IronBirds Spinners vs. IronBirds

Follow on MiLB First Pitch  https //stza.co/+xMoW-U

Shop  https //stza.co/+xMoW-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. IronBirds
END:VALARM
DTSTART;VALUE=DATE:20180628
DTEND;VALUE=DATE:20180628
UID:4oXC_-qPrEfYl1vXh4nMlcWD@stanza.co
SUMMARY:Spinners vs. IronBirds
DESCRIPTION:Spinners vs. IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xMoW-U\n\nShop: https://stza.co/+xMoW-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. IronBirds
<2018-06-29 Fri>--<2018-06-28 Thu>
:PROPERTIES:
:ID:       FWc5y965gL-iKH3NprG1JXF8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Spinners vs. IronBirds Spinners vs. IronBirds

Follow on MiLB First Pitch  https //stza.co/+xMoY-25

Shop  https //stza.co/+xMoY-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. IronBirds
END:VALARM
DTSTART;VALUE=DATE:20180629
DTEND;VALUE=DATE:20180629
UID:FWc5y965gL-iKH3NprG1JXF8@stanza.co
SUMMARY:Spinners vs. IronBirds
DESCRIPTION:Spinners vs. IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xMoY-25\n\nShop: https://stza.co/+xMoY-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. IronBirds
<2018-06-30 Sat>--<2018-06-29 Fri>
:PROPERTIES:
:ID:       XUKMIis7km6Z9SlKxs2bp_gy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners vs. IronBirds Spinners vs. IronBirds

Follow on MiLB First Pitch  https //stza.co/+xMo$-3f

Shop  https //stza.co/+xMo$-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. IronBirds
END:VALARM
DTSTART;VALUE=DATE:20180630
DTEND;VALUE=DATE:20180630
UID:XUKMIis7km6Z9SlKxs2bp_gy@stanza.co
SUMMARY:Spinners vs. IronBirds
DESCRIPTION:Spinners vs. IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xMo$-3f\n\nShop: https://stza.co/+xMo$-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. Tigers
<2018-07-01 Sun>--<2018-06-30 Sat>
:PROPERTIES:
:ID:       7ToVNxiEZBOuechyZD6tvoRE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners vs. Tigers Spinners vs. Tigers

Follow on MiLB First Pitch  https //stza.co/+xMp0-3W

Shop  https //stza.co/+xMp0-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. Tigers
END:VALARM
DTSTART;VALUE=DATE:20180701
DTEND;VALUE=DATE:20180701
UID:7ToVNxiEZBOuechyZD6tvoRE@stanza.co
SUMMARY:Spinners vs. Tigers
DESCRIPTION:Spinners vs. Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMp0-3W\n\nShop: https://stza.co/+xMp0-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. Tigers
<2018-07-02 Mon>--<2018-07-01 Sun>
:PROPERTIES:
:ID:       l-H7sVgCUF3rh5Q6xAzkXOFQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Spinners vs. Tigers Spinners vs. Tigers

Follow on MiLB First Pitch  https //stza.co/+xMp2-3X

Shop  https //stza.co/+xMp2-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. Tigers
END:VALARM
DTSTART;VALUE=DATE:20180702
DTEND;VALUE=DATE:20180702
UID:l-H7sVgCUF3rh5Q6xAzkXOFQ@stanza.co
SUMMARY:Spinners vs. Tigers
DESCRIPTION:Spinners vs. Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMp2-3X\n\nShop: https://stza.co/+xMp2-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. Tigers
<2018-07-03 Tue>--<2018-07-02 Mon>
:PROPERTIES:
:ID:       -YTC5BrmfhVXBzRsxVlk6ksh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners vs. Tigers Spinners vs. Tigers

Follow on MiLB First Pitch  https //stza.co/+xMp5-k

Shop  https //stza.co/+xMp5-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. Tigers
END:VALARM
DTSTART;VALUE=DATE:20180703
DTEND;VALUE=DATE:20180703
UID:-YTC5BrmfhVXBzRsxVlk6ksh@stanza.co
SUMMARY:Spinners vs. Tigers
DESCRIPTION:Spinners vs. Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMp5-k\n\nShop: https://stza.co/+xMp5-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ Tigers
<2018-07-04 Wed>--<2018-07-03 Tue>
:PROPERTIES:
:ID:       WXl0AYYTKxKax9Dg4tYSL4Re@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners @ Tigers Spinners @ Tigers

Follow on MiLB First Pitch  https //stza.co/+xMoH-2e

Shop  https //stza.co/+xMoH-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ Tigers
END:VALARM
DTSTART;VALUE=DATE:20180704
DTEND;VALUE=DATE:20180704
UID:WXl0AYYTKxKax9Dg4tYSL4Re@stanza.co
SUMMARY:Spinners @ Tigers
DESCRIPTION:Spinners @ Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMoH-2e\n\nShop: https://stza.co/+xMoH-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ Tigers
<2018-07-05 Thu>--<2018-07-04 Wed>
:PROPERTIES:
:ID:       4Wz3QdBHr_mHcr3oPLQSFQm9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Spinners @ Tigers Spinners @ Tigers

Follow on MiLB First Pitch  https //stza.co/+xMoI-U

Shop  https //stza.co/+xMoI-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ Tigers
END:VALARM
DTSTART;VALUE=DATE:20180705
DTEND;VALUE=DATE:20180705
UID:4Wz3QdBHr_mHcr3oPLQSFQm9@stanza.co
SUMMARY:Spinners @ Tigers
DESCRIPTION:Spinners @ Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMoI-U\n\nShop: https://stza.co/+xMoI-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ Tigers
<2018-07-06 Fri>--<2018-07-05 Thu>
:PROPERTIES:
:ID:       eqoe53Dpljs2SG4At1CSekqB@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners @ Tigers Spinners @ Tigers

Follow on MiLB First Pitch  https //stza.co/+xMoJ-3K

Shop  https //stza.co/+xMoJ-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ Tigers
END:VALARM
DTSTART;VALUE=DATE:20180706
DTEND;VALUE=DATE:20180706
UID:eqoe53Dpljs2SG4At1CSekqB@stanza.co
SUMMARY:Spinners @ Tigers
DESCRIPTION:Spinners @ Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMoJ-3K\n\nShop: https://stza.co/+xMoJ-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. Renegades
<2018-07-07 Sat>--<2018-07-06 Fri>
:PROPERTIES:
:ID:       4FbPZRQUn5E4-5qlIryEnOW-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners vs. Renegades Spinners vs. Renegades

Follow on MiLB First Pitch  https //stza.co/+xMp6-3C

Shop  https //stza.co/+xMp6-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. Renegades
END:VALARM
DTSTART;VALUE=DATE:20180707
DTEND;VALUE=DATE:20180707
UID:4FbPZRQUn5E4-5qlIryEnOW-@stanza.co
SUMMARY:Spinners vs. Renegades
DESCRIPTION:Spinners vs. Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xMp6-3C\n\nShop: https://stza.co/+xMp6-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. Renegades
<2018-07-08 Sun>--<2018-07-07 Sat>
:PROPERTIES:
:ID:       iW21o79ijVTgONZemZ6VNO2X@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Spinners vs. Renegades Spinners vs. Renegades

Follow on MiLB First Pitch  https //stza.co/+xMp8-3J

Shop  https //stza.co/+xMp8-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. Renegades
END:VALARM
DTSTART;VALUE=DATE:20180708
DTEND;VALUE=DATE:20180708
UID:iW21o79ijVTgONZemZ6VNO2X@stanza.co
SUMMARY:Spinners vs. Renegades
DESCRIPTION:Spinners vs. Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xMp8-3J\n\nShop: https://stza.co/+xMp8-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. Renegades
<2018-07-09 Mon>--<2018-07-08 Sun>
:PROPERTIES:
:ID:       97YcZutOV8JG2KHftFEYWfHj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners vs. Renegades Spinners vs. Renegades

Follow on MiLB First Pitch  https //stza.co/+xMpa-2U

Shop  https //stza.co/+xMpa-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. Renegades
END:VALARM
DTSTART;VALUE=DATE:20180709
DTEND;VALUE=DATE:20180709
UID:97YcZutOV8JG2KHftFEYWfHj@stanza.co
SUMMARY:Spinners vs. Renegades
DESCRIPTION:Spinners vs. Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xMpa-2U\n\nShop: https://stza.co/+xMpa-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ Doubledays
<2018-07-11 Wed 17:30-20:30>
:PROPERTIES:
:ID:       zj38Yy2mDx9dRhg6ueDB9hga@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners @ Doubledays Spinners @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xV$S-3p

Shop  https //stza.co/+xV$S-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ Doubledays
END:VALARM
DTSTART:20180711T223000Z
DTEND:20180712T013000Z
UID:zj38Yy2mDx9dRhg6ueDB9hga@stanza.co
SUMMARY:Spinners @ Doubledays
DESCRIPTION:Spinners @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xV$S-3p\n\nShop: https://stza.co/+xV$S-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ Doubledays
<2018-07-12 Thu 17:30-20:30>
:PROPERTIES:
:ID:       ZiZzPHuHiHu4y6HxBKdnQSVy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Spinners @ Doubledays Spinners @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xV$T-1T

Shop  https //stza.co/+xV$T-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ Doubledays
END:VALARM
DTSTART:20180712T223000Z
DTEND:20180713T013000Z
UID:ZiZzPHuHiHu4y6HxBKdnQSVy@stanza.co
SUMMARY:Spinners @ Doubledays
DESCRIPTION:Spinners @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xV$T-1T\n\nShop: https://stza.co/+xV$T-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ Doubledays
<2018-07-13 Fri 17:30-20:30>
:PROPERTIES:
:ID:       U8LhQsCwPjE7wq_-KWFHcpHv@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners @ Doubledays Spinners @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xV$U-3k

Shop  https //stza.co/+xV$U-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ Doubledays
END:VALARM
DTSTART:20180713T223000Z
DTEND:20180714T013000Z
UID:U8LhQsCwPjE7wq_-KWFHcpHv@stanza.co
SUMMARY:Spinners @ Doubledays
DESCRIPTION:Spinners @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xV$U-3k\n\nShop: https://stza.co/+xV$U-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ Muckdogs
<2018-07-14 Sat>--<2018-07-13 Fri>
:PROPERTIES:
:ID:       qVgL4jQI1eo1c7-12xlhwFm3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners @ Muckdogs Spinners @ Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMov-13

Shop  https //stza.co/+xMov-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180714
DTEND;VALUE=DATE:20180714
UID:qVgL4jQI1eo1c7-12xlhwFm3@stanza.co
SUMMARY:Spinners @ Muckdogs
DESCRIPTION:Spinners @ Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMov-13\n\nShop: https://stza.co/+xMov-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ Muckdogs
<2018-07-15 Sun>--<2018-07-14 Sat>
:PROPERTIES:
:ID:       hNACzleD1pWlgmu6WKvNJGXh@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Spinners @ Muckdogs Spinners @ Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMow-1M

Shop  https //stza.co/+xMow-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180715
DTEND;VALUE=DATE:20180715
UID:hNACzleD1pWlgmu6WKvNJGXh@stanza.co
SUMMARY:Spinners @ Muckdogs
DESCRIPTION:Spinners @ Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMow-1M\n\nShop: https://stza.co/+xMow-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ Muckdogs
<2018-07-16 Mon>--<2018-07-15 Sun>
:PROPERTIES:
:ID:       xD_IwzD0ruHOPaD_jg1GMCFC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners @ Muckdogs Spinners @ Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMox-X

Shop  https //stza.co/+xMox-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180716
DTEND;VALUE=DATE:20180716
UID:xD_IwzD0ruHOPaD_jg1GMCFC@stanza.co
SUMMARY:Spinners @ Muckdogs
DESCRIPTION:Spinners @ Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMox-X\n\nShop: https://stza.co/+xMox-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. IronBirds
<2018-07-17 Tue>--<2018-07-16 Mon>
:PROPERTIES:
:ID:       7NjDSakkxUpp2oYf62r4NQQD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners vs. IronBirds Spinners vs. IronBirds

Follow on MiLB First Pitch  https //stza.co/+xMpd-3R

Shop  https //stza.co/+xMpd-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. IronBirds
END:VALARM
DTSTART;VALUE=DATE:20180717
DTEND;VALUE=DATE:20180717
UID:7NjDSakkxUpp2oYf62r4NQQD@stanza.co
SUMMARY:Spinners vs. IronBirds
DESCRIPTION:Spinners vs. IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xMpd-3R\n\nShop: https://stza.co/+xMpd-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. IronBirds
<2018-07-18 Wed>--<2018-07-17 Tue>
:PROPERTIES:
:ID:       EuvB3jewJQMRnsqFVWTsZSCe@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Spinners vs. IronBirds Spinners vs. IronBirds

Follow on MiLB First Pitch  https //stza.co/+xMpe-3G

Shop  https //stza.co/+xMpe-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. IronBirds
END:VALARM
DTSTART;VALUE=DATE:20180718
DTEND;VALUE=DATE:20180718
UID:EuvB3jewJQMRnsqFVWTsZSCe@stanza.co
SUMMARY:Spinners vs. IronBirds
DESCRIPTION:Spinners vs. IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xMpe-3G\n\nShop: https://stza.co/+xMpe-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. IronBirds
<2018-07-19 Thu>--<2018-07-18 Wed>
:PROPERTIES:
:ID:       k7hPHTyC_aP7hmm75ZJqP2tE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners vs. IronBirds Spinners vs. IronBirds

Follow on MiLB First Pitch  https //stza.co/+xMpg-2a

Shop  https //stza.co/+xMpg-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. IronBirds
END:VALARM
DTSTART;VALUE=DATE:20180719
DTEND;VALUE=DATE:20180719
UID:k7hPHTyC_aP7hmm75ZJqP2tE@stanza.co
SUMMARY:Spinners vs. IronBirds
DESCRIPTION:Spinners vs. IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xMpg-2a\n\nShop: https://stza.co/+xMpg-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ Cyclones
<2018-07-20 Fri>--<2018-07-19 Thu>
:PROPERTIES:
:ID:       ZXZ2wmKzgJW11o9DwQRNhLj6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners @ Cyclones Spinners @ Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMoB-3L

Shop  https //stza.co/+xMoB-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180720
DTEND;VALUE=DATE:20180720
UID:ZXZ2wmKzgJW11o9DwQRNhLj6@stanza.co
SUMMARY:Spinners @ Cyclones
DESCRIPTION:Spinners @ Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMoB-3L\n\nShop: https://stza.co/+xMoB-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ Cyclones
<2018-07-21 Sat>--<2018-07-20 Fri>
:PROPERTIES:
:ID:       qwLp7xgzu1VFHvUbbg5899yT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Spinners @ Cyclones Spinners @ Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMoC-36

Shop  https //stza.co/+xMoC-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180721
DTEND;VALUE=DATE:20180721
UID:qwLp7xgzu1VFHvUbbg5899yT@stanza.co
SUMMARY:Spinners @ Cyclones
DESCRIPTION:Spinners @ Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMoC-36\n\nShop: https://stza.co/+xMoC-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ Cyclones
<2018-07-22 Sun>--<2018-07-21 Sat>
:PROPERTIES:
:ID:       NEUNrlz12mctwHyDNIQFCeDr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners @ Cyclones Spinners @ Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMoD-1O

Shop  https //stza.co/+xMoD-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180722
DTEND;VALUE=DATE:20180722
UID:NEUNrlz12mctwHyDNIQFCeDr@stanza.co
SUMMARY:Spinners @ Cyclones
DESCRIPTION:Spinners @ Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMoD-1O\n\nShop: https://stza.co/+xMoD-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. Renegades
<2018-07-24 Tue>--<2018-07-23 Mon>
:PROPERTIES:
:ID:       05fOxN1egiVnMXyv7ebzb6gJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners vs. Renegades Spinners vs. Renegades

Follow on MiLB First Pitch  https //stza.co/+xMpi-17

Shop  https //stza.co/+xMpi-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. Renegades
END:VALARM
DTSTART;VALUE=DATE:20180724
DTEND;VALUE=DATE:20180724
UID:05fOxN1egiVnMXyv7ebzb6gJ@stanza.co
SUMMARY:Spinners vs. Renegades
DESCRIPTION:Spinners vs. Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xMpi-17\n\nShop: https://stza.co/+xMpi-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. Renegades
<2018-07-25 Wed>--<2018-07-24 Tue>
:PROPERTIES:
:ID:       XLMHaIPUE5H5tx1tILxlcFkm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Spinners vs. Renegades Spinners vs. Renegades

Follow on MiLB First Pitch  https //stza.co/+xMpk-3j

Shop  https //stza.co/+xMpk-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. Renegades
END:VALARM
DTSTART;VALUE=DATE:20180725
DTEND;VALUE=DATE:20180725
UID:XLMHaIPUE5H5tx1tILxlcFkm@stanza.co
SUMMARY:Spinners vs. Renegades
DESCRIPTION:Spinners vs. Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xMpk-3j\n\nShop: https://stza.co/+xMpk-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. Renegades
<2018-07-26 Thu>--<2018-07-25 Wed>
:PROPERTIES:
:ID:       Sl1XMJmKVU39Rt-jn3MtSwK_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners vs. Renegades Spinners vs. Renegades

Follow on MiLB First Pitch  https //stza.co/+xMpn-2n

Shop  https //stza.co/+xMpn-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. Renegades
END:VALARM
DTSTART;VALUE=DATE:20180726
DTEND;VALUE=DATE:20180726
UID:Sl1XMJmKVU39Rt-jn3MtSwK_@stanza.co
SUMMARY:Spinners vs. Renegades
DESCRIPTION:Spinners vs. Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xMpn-2n\n\nShop: https://stza.co/+xMpn-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. Spikes
<2018-07-27 Fri>--<2018-07-26 Thu>
:PROPERTIES:
:ID:       SYzZMj8scCbgjK49fXZaNxxV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners vs. Spikes Spinners vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+xMpo-1A

Shop  https //stza.co/+xMpo-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. Spikes
END:VALARM
DTSTART;VALUE=DATE:20180727
DTEND;VALUE=DATE:20180727
UID:SYzZMj8scCbgjK49fXZaNxxV@stanza.co
SUMMARY:Spinners vs. Spikes
DESCRIPTION:Spinners vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMpo-1A\n\nShop: https://stza.co/+xMpo-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. Spikes
<2018-07-28 Sat>--<2018-07-27 Fri>
:PROPERTIES:
:ID:       1UZcsw9eRGk32E81IxprEMzn@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Spinners vs. Spikes Spinners vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+xMpr-z

Shop  https //stza.co/+xMpr-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. Spikes
END:VALARM
DTSTART;VALUE=DATE:20180728
DTEND;VALUE=DATE:20180728
UID:1UZcsw9eRGk32E81IxprEMzn@stanza.co
SUMMARY:Spinners vs. Spikes
DESCRIPTION:Spinners vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMpr-z\n\nShop: https://stza.co/+xMpr-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. Spikes
<2018-07-29 Sun>--<2018-07-28 Sat>
:PROPERTIES:
:ID:       kEfuSkxae6JNaA0MNI3L2bUQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners vs. Spikes Spinners vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+xMps-2q

Shop  https //stza.co/+xMps-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. Spikes
END:VALARM
DTSTART;VALUE=DATE:20180729
DTEND;VALUE=DATE:20180729
UID:kEfuSkxae6JNaA0MNI3L2bUQ@stanza.co
SUMMARY:Spinners vs. Spikes
DESCRIPTION:Spinners vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMps-2q\n\nShop: https://stza.co/+xMps-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ Renegades
<2018-07-30 Mon 18:05-21:05>
:PROPERTIES:
:ID:       uI3pndWbsyGf9E8nIhdwvdID@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners @ Renegades Spinners @ Renegades

Follow on MiLB First Pitch  https //stza.co/+xV$V-x

Shop  https //stza.co/+xV$V-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ Renegades
END:VALARM
DTSTART:20180730T230500Z
DTEND:20180731T020500Z
UID:uI3pndWbsyGf9E8nIhdwvdID@stanza.co
SUMMARY:Spinners @ Renegades
DESCRIPTION:Spinners @ Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xV$V-x\n\nShop: https://stza.co/+xV$V-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ Renegades
<2018-07-31 Tue 10:05-13:05>
:PROPERTIES:
:ID:       Vx9lg0Fz_ECwMqbbWRdVBq9E@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Spinners @ Renegades Spinners @ Renegades

Follow on MiLB First Pitch  https //stza.co/+xV$W-1N

Shop  https //stza.co/+xV$W-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ Renegades
END:VALARM
DTSTART:20180731T150500Z
DTEND:20180731T180500Z
UID:Vx9lg0Fz_ECwMqbbWRdVBq9E@stanza.co
SUMMARY:Spinners @ Renegades
DESCRIPTION:Spinners @ Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xV$W-1N\n\nShop: https://stza.co/+xV$W-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ Renegades
<2018-08-01 Wed 18:05-21:05>
:PROPERTIES:
:ID:       NO4_xXNSlDC7q4_xG2Os6l9t@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners @ Renegades Spinners @ Renegades

Follow on MiLB First Pitch  https //stza.co/+xV$X-3q

Shop  https //stza.co/+xV$X-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ Renegades
END:VALARM
DTSTART:20180801T230500Z
DTEND:20180802T020500Z
UID:NO4_xXNSlDC7q4_xG2Os6l9t@stanza.co
SUMMARY:Spinners @ Renegades
DESCRIPTION:Spinners @ Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xV$X-3q\n\nShop: https://stza.co/+xV$X-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ ValleyCats
<2018-08-02 Thu>--<2018-08-01 Wed>
:PROPERTIES:
:ID:       W623tiBCojffAnrFpx48-3Ma@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners @ ValleyCats Spinners @ ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMq9-22

Shop  https //stza.co/+xMq9-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180802
DTEND;VALUE=DATE:20180802
UID:W623tiBCojffAnrFpx48-3Ma@stanza.co
SUMMARY:Spinners @ ValleyCats
DESCRIPTION:Spinners @ ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMq9-22\n\nShop: https://stza.co/+xMq9-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ ValleyCats
<2018-08-03 Fri>--<2018-08-02 Thu>
:PROPERTIES:
:ID:       umhbF653naHfmviKRIytBXJK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Spinners @ ValleyCats Spinners @ ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMqa-n

Shop  https //stza.co/+xMqa-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180803
DTEND;VALUE=DATE:20180803
UID:umhbF653naHfmviKRIytBXJK@stanza.co
SUMMARY:Spinners @ ValleyCats
DESCRIPTION:Spinners @ ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMqa-n\n\nShop: https://stza.co/+xMqa-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ ValleyCats
<2018-08-04 Sat>--<2018-08-03 Fri>
:PROPERTIES:
:ID:       _fzFfBn0RlI3UfnnoyvSpVrq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners @ ValleyCats Spinners @ ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMqb-3a

Shop  https //stza.co/+xMqb-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180804
DTEND;VALUE=DATE:20180804
UID:_fzFfBn0RlI3UfnnoyvSpVrq@stanza.co
SUMMARY:Spinners @ ValleyCats
DESCRIPTION:Spinners @ ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMqb-3a\n\nShop: https://stza.co/+xMqb-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. Lake Monsters
<2018-08-05 Sun>--<2018-08-04 Sat>
:PROPERTIES:
:ID:       ArEifgoaHmyME1KkQQLJ-kJA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners vs. Lake Monsters Spinners vs. Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMpv-3T

Shop  https //stza.co/+xMpv-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180805
DTEND;VALUE=DATE:20180805
UID:ArEifgoaHmyME1KkQQLJ-kJA@stanza.co
SUMMARY:Spinners vs. Lake Monsters
DESCRIPTION:Spinners vs. Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMpv-3T\n\nShop: https://stza.co/+xMpv-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. Lake Monsters
<2018-08-06 Mon>--<2018-08-05 Sun>
:PROPERTIES:
:ID:       gDoyXNk9P6X05Yp9MdntAR7e@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Spinners vs. Lake Monsters Spinners vs. Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMpx-t

Shop  https //stza.co/+xMpx-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180806
DTEND;VALUE=DATE:20180806
UID:gDoyXNk9P6X05Yp9MdntAR7e@stanza.co
SUMMARY:Spinners vs. Lake Monsters
DESCRIPTION:Spinners vs. Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMpx-t\n\nShop: https://stza.co/+xMpx-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. Lake Monsters
<2018-08-07 Tue>--<2018-08-06 Mon>
:PROPERTIES:
:ID:       3czbW54JOu0OjeD5q9Dg5fyK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners vs. Lake Monsters Spinners vs. Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMpy-1O

Shop  https //stza.co/+xMpy-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180807
DTEND;VALUE=DATE:20180807
UID:3czbW54JOu0OjeD5q9Dg5fyK@stanza.co
SUMMARY:Spinners vs. Lake Monsters
DESCRIPTION:Spinners vs. Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMpy-1O\n\nShop: https://stza.co/+xMpy-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ Yankees
<2018-08-08 Wed>--<2018-08-07 Tue>
:PROPERTIES:
:ID:       4ui3XzGyLrhuMJf8GFVRJGb9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners @ Yankees Spinners @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xMq0-3d

Shop  https //stza.co/+xMq0-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180808
DTEND;VALUE=DATE:20180808
UID:4ui3XzGyLrhuMJf8GFVRJGb9@stanza.co
SUMMARY:Spinners @ Yankees
DESCRIPTION:Spinners @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMq0-3d\n\nShop: https://stza.co/+xMq0-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ Yankees
<2018-08-09 Thu>--<2018-08-08 Wed>
:PROPERTIES:
:ID:       mqjL96BK_Y9cSk_vKAttpBav@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Spinners @ Yankees Spinners @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xMq1-3L

Shop  https //stza.co/+xMq1-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180809
DTEND;VALUE=DATE:20180809
UID:mqjL96BK_Y9cSk_vKAttpBav@stanza.co
SUMMARY:Spinners @ Yankees
DESCRIPTION:Spinners @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMq1-3L\n\nShop: https://stza.co/+xMq1-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ Yankees
<2018-08-10 Fri>--<2018-08-09 Thu>
:PROPERTIES:
:ID:       hL70HFy6qr_uwSu2n2bD5Jrb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners @ Yankees Spinners @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xMq2-d

Shop  https //stza.co/+xMq2-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180810
DTEND;VALUE=DATE:20180810
UID:hL70HFy6qr_uwSu2n2bD5Jrb@stanza.co
SUMMARY:Spinners @ Yankees
DESCRIPTION:Spinners @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMq2-d\n\nShop: https://stza.co/+xMq2-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. Cyclones
<2018-08-11 Sat>--<2018-08-10 Fri>
:PROPERTIES:
:ID:       rhkSP9ZKf5NXU8qKb_1dJfTO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners vs. Cyclones Spinners vs. Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMpB-2V

Shop  https //stza.co/+xMpB-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180811
DTEND;VALUE=DATE:20180811
UID:rhkSP9ZKf5NXU8qKb_1dJfTO@stanza.co
SUMMARY:Spinners vs. Cyclones
DESCRIPTION:Spinners vs. Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMpB-2V\n\nShop: https://stza.co/+xMpB-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. Cyclones
<2018-08-12 Sun>--<2018-08-11 Sat>
:PROPERTIES:
:ID:       nu_m03vhXL1QVSLSzb-17hls@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Spinners vs. Cyclones Spinners vs. Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMpC-35

Shop  https //stza.co/+xMpC-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180812
DTEND;VALUE=DATE:20180812
UID:nu_m03vhXL1QVSLSzb-17hls@stanza.co
SUMMARY:Spinners vs. Cyclones
DESCRIPTION:Spinners vs. Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMpC-35\n\nShop: https://stza.co/+xMpC-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ IronBirds
<2018-08-15 Wed 18:05-21:05>
:PROPERTIES:
:ID:       ZC2aSxB-Cn80t6GEIziXHFl_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners @ IronBirds Spinners @ IronBirds

Follow on MiLB First Pitch  https //stza.co/+xXU5-27

Shop  https //stza.co/+xXU5-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ IronBirds
END:VALARM
DTSTART:20180815T230500Z
DTEND:20180816T020500Z
UID:ZC2aSxB-Cn80t6GEIziXHFl_@stanza.co
SUMMARY:Spinners @ IronBirds
DESCRIPTION:Spinners @ IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xXU5-27\n\nShop: https://stza.co/+xXU5-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ IronBirds
<2018-08-16 Thu 18:05-21:05>
:PROPERTIES:
:ID:       47h3FkX2fcqYyxdgwpIsUiqS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners @ IronBirds Spinners @ IronBirds

Follow on MiLB First Pitch  https //stza.co/+xXU6-3H

Shop  https //stza.co/+xXU6-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ IronBirds
END:VALARM
DTSTART:20180816T230500Z
DTEND:20180817T020500Z
UID:47h3FkX2fcqYyxdgwpIsUiqS@stanza.co
SUMMARY:Spinners @ IronBirds
DESCRIPTION:Spinners @ IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xXU6-3H\n\nShop: https://stza.co/+xXU6-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. ValleyCats
<2018-08-17 Fri>--<2018-08-16 Thu>
:PROPERTIES:
:ID:       QtoVOoxajdYMCMRMovvKMFDI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Spinners vs. ValleyCats Spinners vs. ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMpF-34

Shop  https //stza.co/+xMpF-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180817
DTEND;VALUE=DATE:20180817
UID:QtoVOoxajdYMCMRMovvKMFDI@stanza.co
SUMMARY:Spinners vs. ValleyCats
DESCRIPTION:Spinners vs. ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMpF-34\n\nShop: https://stza.co/+xMpF-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. ValleyCats
<2018-08-18 Sat>--<2018-08-17 Fri>
:PROPERTIES:
:ID:       CYmKnHl5sfq2iJEKqPyGQNXC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners vs. ValleyCats Spinners vs. ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMpH-2v

Shop  https //stza.co/+xMpH-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180818
DTEND;VALUE=DATE:20180818
UID:CYmKnHl5sfq2iJEKqPyGQNXC@stanza.co
SUMMARY:Spinners vs. ValleyCats
DESCRIPTION:Spinners vs. ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMpH-2v\n\nShop: https://stza.co/+xMpH-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. ValleyCats
<2018-08-19 Sun>--<2018-08-18 Sat>
:PROPERTIES:
:ID:       TKitGHv-EOVTd2uWe-ZKMIbR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners vs. ValleyCats Spinners vs. ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMpJ-2N

Shop  https //stza.co/+xMpJ-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180819
DTEND;VALUE=DATE:20180819
UID:TKitGHv-EOVTd2uWe-ZKMIbR@stanza.co
SUMMARY:Spinners vs. ValleyCats
DESCRIPTION:Spinners vs. ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMpJ-2N\n\nShop: https://stza.co/+xMpJ-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ Yankees
<2018-08-20 Mon>--<2018-08-19 Sun>
:PROPERTIES:
:ID:       mrAEZHqVFjC31kzjMI7MCSxW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Spinners @ Yankees Spinners @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xMq3-S

Shop  https //stza.co/+xMq3-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180820
DTEND;VALUE=DATE:20180820
UID:mrAEZHqVFjC31kzjMI7MCSxW@stanza.co
SUMMARY:Spinners @ Yankees
DESCRIPTION:Spinners @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMq3-S\n\nShop: https://stza.co/+xMq3-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ Yankees
<2018-08-21 Tue>--<2018-08-20 Mon>
:PROPERTIES:
:ID:       PQJ43WCPgBkkOAo0VxcbY_6O@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners @ Yankees Spinners @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xMq4-1C

Shop  https //stza.co/+xMq4-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180821
DTEND;VALUE=DATE:20180821
UID:PQJ43WCPgBkkOAo0VxcbY_6O@stanza.co
SUMMARY:Spinners @ Yankees
DESCRIPTION:Spinners @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMq4-1C\n\nShop: https://stza.co/+xMq4-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ Yankees
<2018-08-22 Wed>--<2018-08-21 Tue>
:PROPERTIES:
:ID:       EbYVMTYUY-wVIWcL71EeQvHm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners @ Yankees Spinners @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xMq5-q

Shop  https //stza.co/+xMq5-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180822
DTEND;VALUE=DATE:20180822
UID:EbYVMTYUY-wVIWcL71EeQvHm@stanza.co
SUMMARY:Spinners @ Yankees
DESCRIPTION:Spinners @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMq5-q\n\nShop: https://stza.co/+xMq5-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. Lake Monsters
<2018-08-23 Thu>--<2018-08-22 Wed>
:PROPERTIES:
:ID:       epxg7NLtPIVtwZuB9bjqeLRb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Spinners vs. Lake Monsters Spinners vs. Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMpK-27

Shop  https //stza.co/+xMpK-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180823
DTEND;VALUE=DATE:20180823
UID:epxg7NLtPIVtwZuB9bjqeLRb@stanza.co
SUMMARY:Spinners vs. Lake Monsters
DESCRIPTION:Spinners vs. Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMpK-27\n\nShop: https://stza.co/+xMpK-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. Lake Monsters
<2018-08-24 Fri>--<2018-08-23 Thu>
:PROPERTIES:
:ID:       iA_InuvbhyRFEURmJtoi_Zsc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners vs. Lake Monsters Spinners vs. Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMpM-1p

Shop  https //stza.co/+xMpM-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180824
DTEND;VALUE=DATE:20180824
UID:iA_InuvbhyRFEURmJtoi_Zsc@stanza.co
SUMMARY:Spinners vs. Lake Monsters
DESCRIPTION:Spinners vs. Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMpM-1p\n\nShop: https://stza.co/+xMpM-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. Lake Monsters
<2018-08-25 Sat>--<2018-08-24 Fri>
:PROPERTIES:
:ID:       s20vegRnMkqxMv_AWpNIjWjR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners vs. Lake Monsters Spinners vs. Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMpP-2N

Shop  https //stza.co/+xMpP-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180825
DTEND;VALUE=DATE:20180825
UID:s20vegRnMkqxMv_AWpNIjWjR@stanza.co
SUMMARY:Spinners vs. Lake Monsters
DESCRIPTION:Spinners vs. Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMpP-2N\n\nShop: https://stza.co/+xMpP-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ Tigers
<2018-08-26 Sun>--<2018-08-25 Sat>
:PROPERTIES:
:ID:       wJitd-dbYEhmA1ze-MrE1F5B@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Spinners @ Tigers Spinners @ Tigers

Follow on MiLB First Pitch  https //stza.co/+xMoK-2$

Shop  https //stza.co/+xMoK-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ Tigers
END:VALARM
DTSTART;VALUE=DATE:20180826
DTEND;VALUE=DATE:20180826
UID:wJitd-dbYEhmA1ze-MrE1F5B@stanza.co
SUMMARY:Spinners @ Tigers
DESCRIPTION:Spinners @ Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMoK-2$\n\nShop: https://stza.co/+xMoK-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ Tigers
<2018-08-27 Mon>--<2018-08-26 Sun>
:PROPERTIES:
:ID:       A6UN78h4mG_U29WHojkdx-z3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners @ Tigers Spinners @ Tigers

Follow on MiLB First Pitch  https //stza.co/+xMoL-3I

Shop  https //stza.co/+xMoL-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ Tigers
END:VALARM
DTSTART;VALUE=DATE:20180827
DTEND;VALUE=DATE:20180827
UID:A6UN78h4mG_U29WHojkdx-z3@stanza.co
SUMMARY:Spinners @ Tigers
DESCRIPTION:Spinners @ Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMoL-3I\n\nShop: https://stza.co/+xMoL-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners @ Tigers
<2018-08-28 Tue>--<2018-08-27 Mon>
:PROPERTIES:
:ID:       YOq3sshDrn5JZEycdn5o5pbC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners @ Tigers Spinners @ Tigers

Follow on MiLB First Pitch  https //stza.co/+xMoM-1n

Shop  https //stza.co/+xMoM-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Spinners @ Tigers
END:VALARM
DTSTART;VALUE=DATE:20180828
DTEND;VALUE=DATE:20180828
UID:YOq3sshDrn5JZEycdn5o5pbC@stanza.co
SUMMARY:Spinners @ Tigers
DESCRIPTION:Spinners @ Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMoM-1n\n\nShop: https://stza.co/+xMoM-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. ValleyCats
<2018-08-29 Wed>--<2018-08-28 Tue>
:PROPERTIES:
:ID:       haGgKXS0Gt5Nw8xdRoOnDKoV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Spinners vs. ValleyCats Spinners vs. ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMpR-Q

Shop  https //stza.co/+xMpR-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180829
DTEND;VALUE=DATE:20180829
UID:haGgKXS0Gt5Nw8xdRoOnDKoV@stanza.co
SUMMARY:Spinners vs. ValleyCats
DESCRIPTION:Spinners vs. ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMpR-Q\n\nShop: https://stza.co/+xMpR-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. ValleyCats
<2018-08-30 Thu>--<2018-08-29 Wed>
:PROPERTIES:
:ID:       L70T3-390-Efe2x_LzYvEH6z@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners vs. ValleyCats Spinners vs. ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMpS-1k

Shop  https //stza.co/+xMpS-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180830
DTEND;VALUE=DATE:20180830
UID:L70T3-390-Efe2x_LzYvEH6z@stanza.co
SUMMARY:Spinners vs. ValleyCats
DESCRIPTION:Spinners vs. ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMpS-1k\n\nShop: https://stza.co/+xMpS-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. ValleyCats
<2018-08-31 Fri>--<2018-08-30 Thu>
:PROPERTIES:
:ID:       gdtDQU3pC6sp5-wn-lXoFuT6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners vs. ValleyCats Spinners vs. ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMpU-3U

Shop  https //stza.co/+xMpU-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180831
DTEND;VALUE=DATE:20180831
UID:gdtDQU3pC6sp5-wn-lXoFuT6@stanza.co
SUMMARY:Spinners vs. ValleyCats
DESCRIPTION:Spinners vs. ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMpU-3U\n\nShop: https://stza.co/+xMpU-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. Tigers
<2018-09-01 Sat>--<2018-08-31 Fri>
:PROPERTIES:
:ID:       DMj5_0RJQt_Ojsw_t9iP5CVJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Spinners vs. Tigers Spinners vs. Tigers

Follow on MiLB First Pitch  https //stza.co/+xMpX-2D

Shop  https //stza.co/+xMpX-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. Tigers
END:VALARM
DTSTART;VALUE=DATE:20180901
DTEND;VALUE=DATE:20180901
UID:DMj5_0RJQt_Ojsw_t9iP5CVJ@stanza.co
SUMMARY:Spinners vs. Tigers
DESCRIPTION:Spinners vs. Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMpX-2D\n\nShop: https://stza.co/+xMpX-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. Tigers
<2018-09-02 Sun>--<2018-09-01 Sat>
:PROPERTIES:
:ID:       frISWQjjrH-OAvLrg8ma_SDJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners vs. Tigers Spinners vs. Tigers

Follow on MiLB First Pitch  https //stza.co/+xMpY-33

Shop  https //stza.co/+xMpY-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. Tigers
END:VALARM
DTSTART;VALUE=DATE:20180902
DTEND;VALUE=DATE:20180902
UID:frISWQjjrH-OAvLrg8ma_SDJ@stanza.co
SUMMARY:Spinners vs. Tigers
DESCRIPTION:Spinners vs. Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMpY-33\n\nShop: https://stza.co/+xMpY-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
* Spinners vs. Tigers
<2018-09-03 Mon>--<2018-09-02 Sun>
:PROPERTIES:
:ID:       MPy6uCSsQRC9j2S24aeumwdx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Spinners vs. Tigers Spinners vs. Tigers

Follow on MiLB First Pitch  https //stza.co/+xMp$-q

Shop  https //stza.co/+xMp$-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Spinners vs. Tigers
END:VALARM
DTSTART;VALUE=DATE:20180903
DTEND;VALUE=DATE:20180903
UID:MPy6uCSsQRC9j2S24aeumwdx@stanza.co
SUMMARY:Spinners vs. Tigers
DESCRIPTION:Spinners vs. Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMp$-q\n\nShop: https://stza.co/+xMp$-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144542Z
LAST-MODIFIED:20180213T144542Z
TRANSP:OPAQUE
END:VEVENT
