#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Tigers vs. Spinners
<2018-06-15 Fri>--<2018-06-14 Thu>
:PROPERTIES:
:ID:       zGD4x1EHbDt8uxjsjHYvz4zt@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers vs. Spinners Tigers vs. Spinners

Follow on MiLB First Pitch  https //stza.co/+xMl5-2J

Shop  https //stza.co/+xMl5-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. Spinners
END:VALARM
DTSTART;VALUE=DATE:20180615
DTEND;VALUE=DATE:20180615
UID:zGD4x1EHbDt8uxjsjHYvz4zt@stanza.co
SUMMARY:Tigers vs. Spinners
DESCRIPTION:Tigers vs. Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMl5-2J\n\nShop: https://stza.co/+xMl5-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. Spinners
<2018-06-16 Sat>--<2018-06-15 Fri>
:PROPERTIES:
:ID:       Yt6scHpCY6mlkYs55GocXyFY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tigers vs. Spinners Tigers vs. Spinners

Follow on MiLB First Pitch  https //stza.co/+xMl7-3H

Shop  https //stza.co/+xMl7-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. Spinners
END:VALARM
DTSTART;VALUE=DATE:20180616
DTEND;VALUE=DATE:20180616
UID:Yt6scHpCY6mlkYs55GocXyFY@stanza.co
SUMMARY:Tigers vs. Spinners
DESCRIPTION:Tigers vs. Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMl7-3H\n\nShop: https://stza.co/+xMl7-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. Spinners
<2018-06-17 Sun>--<2018-06-16 Sat>
:PROPERTIES:
:ID:       fR9DRqmf5LpPPFFSzJXBdrio@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers vs. Spinners Tigers vs. Spinners

Follow on MiLB First Pitch  https //stza.co/+xMl9-2t

Shop  https //stza.co/+xMl9-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. Spinners
END:VALARM
DTSTART;VALUE=DATE:20180617
DTEND;VALUE=DATE:20180617
UID:fR9DRqmf5LpPPFFSzJXBdrio@stanza.co
SUMMARY:Tigers vs. Spinners
DESCRIPTION:Tigers vs. Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMl9-2t\n\nShop: https://stza.co/+xMl9-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ Lake Monsters
<2018-06-18 Mon>--<2018-06-17 Sun>
:PROPERTIES:
:ID:       n3ixzalwBXogXKbdQrVUJWV_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers @ Lake Monsters Tigers @ Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMmy-e

Shop  https //stza.co/+xMmy-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180618
DTEND;VALUE=DATE:20180618
UID:n3ixzalwBXogXKbdQrVUJWV_@stanza.co
SUMMARY:Tigers @ Lake Monsters
DESCRIPTION:Tigers @ Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMmy-e\n\nShop: https://stza.co/+xMmy-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ Lake Monsters
<2018-06-19 Tue>--<2018-06-18 Mon>
:PROPERTIES:
:ID:       pWB0PXXTVh6WfTAKcs_H5kZP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tigers @ Lake Monsters Tigers @ Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMmz-2e

Shop  https //stza.co/+xMmz-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180619
DTEND;VALUE=DATE:20180619
UID:pWB0PXXTVh6WfTAKcs_H5kZP@stanza.co
SUMMARY:Tigers @ Lake Monsters
DESCRIPTION:Tigers @ Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMmz-2e\n\nShop: https://stza.co/+xMmz-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ Lake Monsters
<2018-06-20 Wed>--<2018-06-19 Tue>
:PROPERTIES:
:ID:       I8_Xlbo8NJ6pLXOZccpZwu_U@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers @ Lake Monsters Tigers @ Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMmA-2$

Shop  https //stza.co/+xMmA-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180620
DTEND;VALUE=DATE:20180620
UID:I8_Xlbo8NJ6pLXOZccpZwu_U@stanza.co
SUMMARY:Tigers @ Lake Monsters
DESCRIPTION:Tigers @ Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMmA-2$\n\nShop: https://stza.co/+xMmA-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. Cyclones
<2018-06-21 Thu>--<2018-06-20 Wed>
:PROPERTIES:
:ID:       18MX_zvsV6l4fWwipoufEXHH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers vs. Cyclones Tigers vs. Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMlc-1z

Shop  https //stza.co/+xMlc-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180621
DTEND;VALUE=DATE:20180621
UID:18MX_zvsV6l4fWwipoufEXHH@stanza.co
SUMMARY:Tigers vs. Cyclones
DESCRIPTION:Tigers vs. Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMlc-1z\n\nShop: https://stza.co/+xMlc-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. Cyclones
<2018-06-22 Fri>--<2018-06-21 Thu>
:PROPERTIES:
:ID:       w0TEPq5QdLiBhGobuBvr8wEX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tigers vs. Cyclones Tigers vs. Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMle-3E

Shop  https //stza.co/+xMle-3_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180622
DTEND;VALUE=DATE:20180622
UID:w0TEPq5QdLiBhGobuBvr8wEX@stanza.co
SUMMARY:Tigers vs. Cyclones
DESCRIPTION:Tigers vs. Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMle-3E\n\nShop: https://stza.co/+xMle-3_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. Cyclones
<2018-06-23 Sat>--<2018-06-22 Fri>
:PROPERTIES:
:ID:       5awdXH1aZUErd6UpdyLYYTeT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers vs. Cyclones Tigers vs. Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMlf-3c

Shop  https //stza.co/+xMlf-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180623
DTEND;VALUE=DATE:20180623
UID:5awdXH1aZUErd6UpdyLYYTeT@stanza.co
SUMMARY:Tigers vs. Cyclones
DESCRIPTION:Tigers vs. Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMlf-3c\n\nShop: https://stza.co/+xMlf-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ Renegades
<2018-06-24 Sun 16:05-19:05>
:PROPERTIES:
:ID:       K4wTjCA6nC04aQ7ySTn1gDVy@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers @ Renegades Tigers @ Renegades

Follow on MiLB First Pitch  https //stza.co/+xV_A-3f

Shop  https //stza.co/+xV_A-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ Renegades
END:VALARM
DTSTART:20180624T210500Z
DTEND:20180625T000500Z
UID:K4wTjCA6nC04aQ7ySTn1gDVy@stanza.co
SUMMARY:Tigers @ Renegades
DESCRIPTION:Tigers @ Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xV_A-3f\n\nShop: https://stza.co/+xV_A-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ Renegades
<2018-06-25 Mon 18:05-21:05>
:PROPERTIES:
:ID:       inH0EUvPfdZEOo5qtYjmONux@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tigers @ Renegades Tigers @ Renegades

Follow on MiLB First Pitch  https //stza.co/+xV_B-2g

Shop  https //stza.co/+xV_B-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ Renegades
END:VALARM
DTSTART:20180625T230500Z
DTEND:20180626T020500Z
UID:inH0EUvPfdZEOo5qtYjmONux@stanza.co
SUMMARY:Tigers @ Renegades
DESCRIPTION:Tigers @ Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xV_B-2g\n\nShop: https://stza.co/+xV_B-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ Renegades
<2018-06-26 Tue 18:05-21:05>
:PROPERTIES:
:ID:       5PfAyKKKKaXKwEUgIj6_Zbsr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers @ Renegades Tigers @ Renegades

Follow on MiLB First Pitch  https //stza.co/+xV_C-1A

Shop  https //stza.co/+xV_C-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ Renegades
END:VALARM
DTSTART:20180626T230500Z
DTEND:20180627T020500Z
UID:5PfAyKKKKaXKwEUgIj6_Zbsr@stanza.co
SUMMARY:Tigers @ Renegades
DESCRIPTION:Tigers @ Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xV_C-1A\n\nShop: https://stza.co/+xV_C-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. Yankees
<2018-06-28 Thu>--<2018-06-27 Wed>
:PROPERTIES:
:ID:       Y9th5JD3IpcdYAB4P3h8wpcS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers vs. Yankees Tigers vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xMli-2v

Shop  https //stza.co/+xMli-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. Yankees
END:VALARM
DTSTART;VALUE=DATE:20180628
DTEND;VALUE=DATE:20180628
UID:Y9th5JD3IpcdYAB4P3h8wpcS@stanza.co
SUMMARY:Tigers vs. Yankees
DESCRIPTION:Tigers vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMli-2v\n\nShop: https://stza.co/+xMli-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. Yankees
<2018-06-29 Fri>--<2018-06-28 Thu>
:PROPERTIES:
:ID:       wsOBw9J_zhAxrab3V2AGlTZh@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tigers vs. Yankees Tigers vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xMlj-3i

Shop  https //stza.co/+xMlj-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. Yankees
END:VALARM
DTSTART;VALUE=DATE:20180629
DTEND;VALUE=DATE:20180629
UID:wsOBw9J_zhAxrab3V2AGlTZh@stanza.co
SUMMARY:Tigers vs. Yankees
DESCRIPTION:Tigers vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMlj-3i\n\nShop: https://stza.co/+xMlj-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. Yankees
<2018-06-30 Sat>--<2018-06-29 Fri>
:PROPERTIES:
:ID:       0t6NgeDvsRsVn-I6tbykpLy5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers vs. Yankees Tigers vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xMll-2g

Shop  https //stza.co/+xMll-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. Yankees
END:VALARM
DTSTART;VALUE=DATE:20180630
DTEND;VALUE=DATE:20180630
UID:0t6NgeDvsRsVn-I6tbykpLy5@stanza.co
SUMMARY:Tigers vs. Yankees
DESCRIPTION:Tigers vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMll-2g\n\nShop: https://stza.co/+xMll-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ Spinners
<2018-07-01 Sun>--<2018-06-30 Sat>
:PROPERTIES:
:ID:       4xX-pvc8Jff1m3YMnOJXnOr2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers @ Spinners Tigers @ Spinners

Follow on MiLB First Pitch  https //stza.co/+xMmn-3h

Shop  https //stza.co/+xMmn-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ Spinners
END:VALARM
DTSTART;VALUE=DATE:20180701
DTEND;VALUE=DATE:20180701
UID:4xX-pvc8Jff1m3YMnOJXnOr2@stanza.co
SUMMARY:Tigers @ Spinners
DESCRIPTION:Tigers @ Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMmn-3h\n\nShop: https://stza.co/+xMmn-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ Spinners
<2018-07-02 Mon>--<2018-07-01 Sun>
:PROPERTIES:
:ID:       5tz4vh-U53UoGAGalFIW_4BV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tigers @ Spinners Tigers @ Spinners

Follow on MiLB First Pitch  https //stza.co/+xMmo-3i

Shop  https //stza.co/+xMmo-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ Spinners
END:VALARM
DTSTART;VALUE=DATE:20180702
DTEND;VALUE=DATE:20180702
UID:5tz4vh-U53UoGAGalFIW_4BV@stanza.co
SUMMARY:Tigers @ Spinners
DESCRIPTION:Tigers @ Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMmo-3i\n\nShop: https://stza.co/+xMmo-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ Spinners
<2018-07-03 Tue>--<2018-07-02 Mon>
:PROPERTIES:
:ID:       VfzwbyxQTi-aujGvbBLp8_p6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers @ Spinners Tigers @ Spinners

Follow on MiLB First Pitch  https //stza.co/+xMmp-c

Shop  https //stza.co/+xMmp-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ Spinners
END:VALARM
DTSTART;VALUE=DATE:20180703
DTEND;VALUE=DATE:20180703
UID:VfzwbyxQTi-aujGvbBLp8_p6@stanza.co
SUMMARY:Tigers @ Spinners
DESCRIPTION:Tigers @ Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMmp-c\n\nShop: https://stza.co/+xMmp-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. Spinners
<2018-07-04 Wed>--<2018-07-03 Tue>
:PROPERTIES:
:ID:       84PJ9sba35nleOdiv0qbilPt@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers vs. Spinners Tigers vs. Spinners

Follow on MiLB First Pitch  https //stza.co/+xMlo-Y

Shop  https //stza.co/+xMlo-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. Spinners
END:VALARM
DTSTART;VALUE=DATE:20180704
DTEND;VALUE=DATE:20180704
UID:84PJ9sba35nleOdiv0qbilPt@stanza.co
SUMMARY:Tigers vs. Spinners
DESCRIPTION:Tigers vs. Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMlo-Y\n\nShop: https://stza.co/+xMlo-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. Spinners
<2018-07-05 Thu>--<2018-07-04 Wed>
:PROPERTIES:
:ID:       3mtsQAwTOKWgxlkev4uyLB9K@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tigers vs. Spinners Tigers vs. Spinners

Follow on MiLB First Pitch  https //stza.co/+xMlp-3f

Shop  https //stza.co/+xMlp-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. Spinners
END:VALARM
DTSTART;VALUE=DATE:20180705
DTEND;VALUE=DATE:20180705
UID:3mtsQAwTOKWgxlkev4uyLB9K@stanza.co
SUMMARY:Tigers vs. Spinners
DESCRIPTION:Tigers vs. Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMlp-3f\n\nShop: https://stza.co/+xMlp-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. Spinners
<2018-07-06 Fri>--<2018-07-05 Thu>
:PROPERTIES:
:ID:       AOGs1QXyhCDOBRnx7z7ZxpGP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers vs. Spinners Tigers vs. Spinners

Follow on MiLB First Pitch  https //stza.co/+xMls-q

Shop  https //stza.co/+xMls-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. Spinners
END:VALARM
DTSTART;VALUE=DATE:20180706
DTEND;VALUE=DATE:20180706
UID:AOGs1QXyhCDOBRnx7z7ZxpGP@stanza.co
SUMMARY:Tigers vs. Spinners
DESCRIPTION:Tigers vs. Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMls-q\n\nShop: https://stza.co/+xMls-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ Lake Monsters
<2018-07-07 Sat>--<2018-07-06 Fri>
:PROPERTIES:
:ID:       CsBbMXBiiKl7u3Nm1SKIMGJd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers @ Lake Monsters Tigers @ Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMmB-2q

Shop  https //stza.co/+xMmB-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180707
DTEND;VALUE=DATE:20180707
UID:CsBbMXBiiKl7u3Nm1SKIMGJd@stanza.co
SUMMARY:Tigers @ Lake Monsters
DESCRIPTION:Tigers @ Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMmB-2q\n\nShop: https://stza.co/+xMmB-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ Lake Monsters
<2018-07-08 Sun>--<2018-07-07 Sat>
:PROPERTIES:
:ID:       Mdoho0KEaLXKx_k7PT1dOhOV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tigers @ Lake Monsters Tigers @ Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMmC-3X

Shop  https //stza.co/+xMmC-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180708
DTEND;VALUE=DATE:20180708
UID:Mdoho0KEaLXKx_k7PT1dOhOV@stanza.co
SUMMARY:Tigers @ Lake Monsters
DESCRIPTION:Tigers @ Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMmC-3X\n\nShop: https://stza.co/+xMmC-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ Lake Monsters
<2018-07-09 Mon>--<2018-07-08 Sun>
:PROPERTIES:
:ID:       vhJ0rqVQLpLby4VBJi232_Ip@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers @ Lake Monsters Tigers @ Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMmD-2Q

Shop  https //stza.co/+xMmD-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180709
DTEND;VALUE=DATE:20180709
UID:vhJ0rqVQLpLby4VBJi232_Ip@stanza.co
SUMMARY:Tigers @ Lake Monsters
DESCRIPTION:Tigers @ Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMmD-2Q\n\nShop: https://stza.co/+xMmD-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. Muckdogs
<2018-07-11 Wed>--<2018-07-10 Tue>
:PROPERTIES:
:ID:       Zz9lIEeCEwUcXm7aAcmkkm-y@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers vs. Muckdogs Tigers vs. Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMlt-3_

Shop  https //stza.co/+xMlt-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180711
DTEND;VALUE=DATE:20180711
UID:Zz9lIEeCEwUcXm7aAcmkkm-y@stanza.co
SUMMARY:Tigers vs. Muckdogs
DESCRIPTION:Tigers vs. Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMlt-3_\n\nShop: https://stza.co/+xMlt-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. Muckdogs
<2018-07-12 Thu>--<2018-07-11 Wed>
:PROPERTIES:
:ID:       aPx2Y9Y1EvEzvv5dzbOKHj5p@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tigers vs. Muckdogs Tigers vs. Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMlw-f

Shop  https //stza.co/+xMlw-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180712
DTEND;VALUE=DATE:20180712
UID:aPx2Y9Y1EvEzvv5dzbOKHj5p@stanza.co
SUMMARY:Tigers vs. Muckdogs
DESCRIPTION:Tigers vs. Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMlw-f\n\nShop: https://stza.co/+xMlw-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. Muckdogs
<2018-07-13 Fri>--<2018-07-12 Thu>
:PROPERTIES:
:ID:       d-8dHwZXASAjlvDC28Nvl8jC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers vs. Muckdogs Tigers vs. Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMly-2_

Shop  https //stza.co/+xMly-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180713
DTEND;VALUE=DATE:20180713
UID:d-8dHwZXASAjlvDC28Nvl8jC@stanza.co
SUMMARY:Tigers vs. Muckdogs
DESCRIPTION:Tigers vs. Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMly-2_\n\nShop: https://stza.co/+xMly-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. Lake Monsters
<2018-07-14 Sat>--<2018-07-13 Fri>
:PROPERTIES:
:ID:       l4RGXlRfrP9O7s2_fOk6hXpm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers vs. Lake Monsters Tigers vs. Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMlz-v

Shop  https //stza.co/+xMlz-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180714
DTEND;VALUE=DATE:20180714
UID:l4RGXlRfrP9O7s2_fOk6hXpm@stanza.co
SUMMARY:Tigers vs. Lake Monsters
DESCRIPTION:Tigers vs. Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMlz-v\n\nShop: https://stza.co/+xMlz-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. Lake Monsters
<2018-07-15 Sun>--<2018-07-14 Sat>
:PROPERTIES:
:ID:       AuPQgrihfB1akLnf-fTwKZ5T@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tigers vs. Lake Monsters Tigers vs. Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMlC-2$

Shop  https //stza.co/+xMlC-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180715
DTEND;VALUE=DATE:20180715
UID:AuPQgrihfB1akLnf-fTwKZ5T@stanza.co
SUMMARY:Tigers vs. Lake Monsters
DESCRIPTION:Tigers vs. Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMlC-2$\n\nShop: https://stza.co/+xMlC-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. Lake Monsters
<2018-07-16 Mon>--<2018-07-15 Sun>
:PROPERTIES:
:ID:       8ZRjG_GyvFpKEADsPzflgseW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers vs. Lake Monsters Tigers vs. Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMlE-1b

Shop  https //stza.co/+xMlE-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180716
DTEND;VALUE=DATE:20180716
UID:8ZRjG_GyvFpKEADsPzflgseW@stanza.co
SUMMARY:Tigers vs. Lake Monsters
DESCRIPTION:Tigers vs. Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMlE-1b\n\nShop: https://stza.co/+xMlE-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ Renegades
<2018-07-17 Tue 18:05-21:05>
:PROPERTIES:
:ID:       sVmbElu5EKXKtaP0nyoh_y--@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers @ Renegades Tigers @ Renegades

Follow on MiLB First Pitch  https //stza.co/+xV_D-2A

Shop  https //stza.co/+xV_D-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ Renegades
END:VALARM
DTSTART:20180717T230500Z
DTEND:20180718T020500Z
UID:sVmbElu5EKXKtaP0nyoh_y--@stanza.co
SUMMARY:Tigers @ Renegades
DESCRIPTION:Tigers @ Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xV_D-2A\n\nShop: https://stza.co/+xV_D-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ Renegades
<2018-07-18 Wed 18:05-21:05>
:PROPERTIES:
:ID:       QJxbGrRybbXZog-4f2qxoBgL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tigers @ Renegades Tigers @ Renegades

Follow on MiLB First Pitch  https //stza.co/+xV_E-1a

Shop  https //stza.co/+xV_E-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ Renegades
END:VALARM
DTSTART:20180718T230500Z
DTEND:20180719T020500Z
UID:QJxbGrRybbXZog-4f2qxoBgL@stanza.co
SUMMARY:Tigers @ Renegades
DESCRIPTION:Tigers @ Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xV_E-1a\n\nShop: https://stza.co/+xV_E-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ Renegades
<2018-07-19 Thu 18:05-21:05>
:PROPERTIES:
:ID:       0qE2EJlYHM0gflyN5FW7ADwC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers @ Renegades Tigers @ Renegades

Follow on MiLB First Pitch  https //stza.co/+xV_F-3k

Shop  https //stza.co/+xV_F-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ Renegades
END:VALARM
DTSTART:20180719T230500Z
DTEND:20180720T020500Z
UID:0qE2EJlYHM0gflyN5FW7ADwC@stanza.co
SUMMARY:Tigers @ Renegades
DESCRIPTION:Tigers @ Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xV_F-3k\n\nShop: https://stza.co/+xV_F-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ IronBirds
<2018-07-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       ed7kHsiuvEBppUd_lT1tGnNJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers @ IronBirds Tigers @ IronBirds

Follow on MiLB First Pitch  https //stza.co/+xXTU-2n

Shop  https //stza.co/+xXTU-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ IronBirds
END:VALARM
DTSTART:20180720T230500Z
DTEND:20180721T020500Z
UID:ed7kHsiuvEBppUd_lT1tGnNJ@stanza.co
SUMMARY:Tigers @ IronBirds
DESCRIPTION:Tigers @ IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xXTU-2n\n\nShop: https://stza.co/+xXTU-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ IronBirds
<2018-07-21 Sat 17:05-20:05>
:PROPERTIES:
:ID:       JVjScLEjhKL6-z4IAwZMjl0U@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tigers @ IronBirds Tigers @ IronBirds

Follow on MiLB First Pitch  https //stza.co/+xXTV-O

Shop  https //stza.co/+xXTV-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ IronBirds
END:VALARM
DTSTART:20180721T220500Z
DTEND:20180722T010500Z
UID:JVjScLEjhKL6-z4IAwZMjl0U@stanza.co
SUMMARY:Tigers @ IronBirds
DESCRIPTION:Tigers @ IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xXTV-O\n\nShop: https://stza.co/+xXTV-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ IronBirds
<2018-07-22 Sun 15:05-18:05>
:PROPERTIES:
:ID:       AQT6YFH4cD9b94VF6P7Nbh-n@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers @ IronBirds Tigers @ IronBirds

Follow on MiLB First Pitch  https //stza.co/+xXTW-B

Shop  https //stza.co/+xXTW-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ IronBirds
END:VALARM
DTSTART:20180722T200500Z
DTEND:20180722T230500Z
UID:AQT6YFH4cD9b94VF6P7Nbh-n@stanza.co
SUMMARY:Tigers @ IronBirds
DESCRIPTION:Tigers @ IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xXTW-B\n\nShop: https://stza.co/+xXTW-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. Spikes
<2018-07-24 Tue>--<2018-07-23 Mon>
:PROPERTIES:
:ID:       rWySFtPO-1iwO7pMJJ0cULYm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers vs. Spikes Tigers vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+xMlF-3g

Shop  https //stza.co/+xMlF-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. Spikes
END:VALARM
DTSTART;VALUE=DATE:20180724
DTEND;VALUE=DATE:20180724
UID:rWySFtPO-1iwO7pMJJ0cULYm@stanza.co
SUMMARY:Tigers vs. Spikes
DESCRIPTION:Tigers vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMlF-3g\n\nShop: https://stza.co/+xMlF-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. Spikes
<2018-07-25 Wed>--<2018-07-24 Tue>
:PROPERTIES:
:ID:       LvoJMcLlLT776ygvpHnBHFUl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tigers vs. Spikes Tigers vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+xMlI-Q

Shop  https //stza.co/+xMlI-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. Spikes
END:VALARM
DTSTART;VALUE=DATE:20180725
DTEND;VALUE=DATE:20180725
UID:LvoJMcLlLT776ygvpHnBHFUl@stanza.co
SUMMARY:Tigers vs. Spikes
DESCRIPTION:Tigers vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMlI-Q\n\nShop: https://stza.co/+xMlI-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. Spikes
<2018-07-26 Thu>--<2018-07-25 Wed>
:PROPERTIES:
:ID:       0yQ7PqSqzfkvMl3-a1zpmMjV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers vs. Spikes Tigers vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+xMlJ-j

Shop  https //stza.co/+xMlJ-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. Spikes
END:VALARM
DTSTART;VALUE=DATE:20180726
DTEND;VALUE=DATE:20180726
UID:0yQ7PqSqzfkvMl3-a1zpmMjV@stanza.co
SUMMARY:Tigers vs. Spikes
DESCRIPTION:Tigers vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMlJ-j\n\nShop: https://stza.co/+xMlJ-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ Doubledays
<2018-07-27 Fri 17:30-20:30>
:PROPERTIES:
:ID:       oZXpTno3jS9pmTkivl96hd1i@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers @ Doubledays Tigers @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xV_x-x

Shop  https //stza.co/+xV_x-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ Doubledays
END:VALARM
DTSTART:20180727T223000Z
DTEND:20180728T013000Z
UID:oZXpTno3jS9pmTkivl96hd1i@stanza.co
SUMMARY:Tigers @ Doubledays
DESCRIPTION:Tigers @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xV_x-x\n\nShop: https://stza.co/+xV_x-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ Doubledays
<2018-07-28 Sat 17:30-20:30>
:PROPERTIES:
:ID:       ym4VqKVbuLJiHHwegQBsTRRH@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tigers @ Doubledays Tigers @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xV_y-19

Shop  https //stza.co/+xV_y-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ Doubledays
END:VALARM
DTSTART:20180728T223000Z
DTEND:20180729T013000Z
UID:ym4VqKVbuLJiHHwegQBsTRRH@stanza.co
SUMMARY:Tigers @ Doubledays
DESCRIPTION:Tigers @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xV_y-19\n\nShop: https://stza.co/+xV_y-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ Doubledays
<2018-07-29 Sun 13:00-16:00>
:PROPERTIES:
:ID:       n8AklgiMikmoOeE00fHpxTTO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers @ Doubledays Tigers @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xV_z-2S

Shop  https //stza.co/+xV_z-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ Doubledays
END:VALARM
DTSTART:20180729T180000Z
DTEND:20180729T210000Z
UID:n8AklgiMikmoOeE00fHpxTTO@stanza.co
SUMMARY:Tigers @ Doubledays
DESCRIPTION:Tigers @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xV_z-2S\n\nShop: https://stza.co/+xV_z-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. Lake Monsters
<2018-07-30 Mon>--<2018-07-29 Sun>
:PROPERTIES:
:ID:       FIrImKzcpteCdSBK0uToaMYh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers vs. Lake Monsters Tigers vs. Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMlL-

Shop  https //stza.co/+xMlL-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180730
DTEND;VALUE=DATE:20180730
UID:FIrImKzcpteCdSBK0uToaMYh@stanza.co
SUMMARY:Tigers vs. Lake Monsters
DESCRIPTION:Tigers vs. Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMlL-\n\nShop: https://stza.co/+xMlL-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. Lake Monsters
<2018-07-31 Tue>--<2018-07-30 Mon>
:PROPERTIES:
:ID:       AXD-2cdPtx_eaREM5QFinW6R@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tigers vs. Lake Monsters Tigers vs. Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMlO-1o

Shop  https //stza.co/+xMlO-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180731
DTEND;VALUE=DATE:20180731
UID:AXD-2cdPtx_eaREM5QFinW6R@stanza.co
SUMMARY:Tigers vs. Lake Monsters
DESCRIPTION:Tigers vs. Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMlO-1o\n\nShop: https://stza.co/+xMlO-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. Lake Monsters
<2018-08-01 Wed>--<2018-07-31 Tue>
:PROPERTIES:
:ID:       XRQOxkBi5V0PlRhpb_yAPEN5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers vs. Lake Monsters Tigers vs. Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMlQ-2s

Shop  https //stza.co/+xMlQ-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180801
DTEND;VALUE=DATE:20180801
UID:XRQOxkBi5V0PlRhpb_yAPEN5@stanza.co
SUMMARY:Tigers vs. Lake Monsters
DESCRIPTION:Tigers vs. Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMlQ-2s\n\nShop: https://stza.co/+xMlQ-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ Yankees
<2018-08-02 Thu>--<2018-08-01 Wed>
:PROPERTIES:
:ID:       H1eP0SaI6Y4UtdbzHThgEpqR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers @ Yankees Tigers @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xMmt-1O

Shop  https //stza.co/+xMmt-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180802
DTEND;VALUE=DATE:20180802
UID:H1eP0SaI6Y4UtdbzHThgEpqR@stanza.co
SUMMARY:Tigers @ Yankees
DESCRIPTION:Tigers @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMmt-1O\n\nShop: https://stza.co/+xMmt-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ Yankees
<2018-08-03 Fri>--<2018-08-02 Thu>
:PROPERTIES:
:ID:       R8-TGEMim0pwNotlH2qq7JJO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tigers @ Yankees Tigers @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xMmu-1I

Shop  https //stza.co/+xMmu-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180803
DTEND;VALUE=DATE:20180803
UID:R8-TGEMim0pwNotlH2qq7JJO@stanza.co
SUMMARY:Tigers @ Yankees
DESCRIPTION:Tigers @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMmu-1I\n\nShop: https://stza.co/+xMmu-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ Yankees
<2018-08-04 Sat>--<2018-08-03 Fri>
:PROPERTIES:
:ID:       HgnHW35UNzudPgfcO5bPTA8D@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers @ Yankees Tigers @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xMmv-1h

Shop  https //stza.co/+xMmv-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180804
DTEND;VALUE=DATE:20180804
UID:HgnHW35UNzudPgfcO5bPTA8D@stanza.co
SUMMARY:Tigers @ Yankees
DESCRIPTION:Tigers @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMmv-1h\n\nShop: https://stza.co/+xMmv-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. ValleyCats
<2018-08-05 Sun>--<2018-08-04 Sat>
:PROPERTIES:
:ID:       H-zOS9yfWzHW3Kyu8JQpf9o8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers vs. ValleyCats Tigers vs. ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMlS-3R

Shop  https //stza.co/+xMlS-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180805
DTEND;VALUE=DATE:20180805
UID:H-zOS9yfWzHW3Kyu8JQpf9o8@stanza.co
SUMMARY:Tigers vs. ValleyCats
DESCRIPTION:Tigers vs. ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMlS-3R\n\nShop: https://stza.co/+xMlS-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. ValleyCats
<2018-08-06 Mon>--<2018-08-05 Sun>
:PROPERTIES:
:ID:       99bZ4xIaFux4GLj_VGg9Hn30@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tigers vs. ValleyCats Tigers vs. ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMlU-3n

Shop  https //stza.co/+xMlU-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180806
DTEND;VALUE=DATE:20180806
UID:99bZ4xIaFux4GLj_VGg9Hn30@stanza.co
SUMMARY:Tigers vs. ValleyCats
DESCRIPTION:Tigers vs. ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMlU-3n\n\nShop: https://stza.co/+xMlU-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. ValleyCats
<2018-08-07 Tue>--<2018-08-06 Mon>
:PROPERTIES:
:ID:       lT2MiNLO-pYyyCuufsFBVEMb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers vs. ValleyCats Tigers vs. ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMlW-1G

Shop  https //stza.co/+xMlW-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180807
DTEND;VALUE=DATE:20180807
UID:lT2MiNLO-pYyyCuufsFBVEMb@stanza.co
SUMMARY:Tigers vs. ValleyCats
DESCRIPTION:Tigers vs. ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMlW-1G\n\nShop: https://stza.co/+xMlW-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ Cyclones
<2018-08-08 Wed>--<2018-08-07 Tue>
:PROPERTIES:
:ID:       49lLhTkgMAXBYYax8pWyrIvX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers @ Cyclones Tigers @ Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMk$-14

Shop  https //stza.co/+xMk$-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180808
DTEND;VALUE=DATE:20180808
UID:49lLhTkgMAXBYYax8pWyrIvX@stanza.co
SUMMARY:Tigers @ Cyclones
DESCRIPTION:Tigers @ Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMk$-14\n\nShop: https://stza.co/+xMk$-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ Cyclones
<2018-08-09 Thu>--<2018-08-08 Wed>
:PROPERTIES:
:ID:       Dnnvs2coTFRmryu789mp0pWm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tigers @ Cyclones Tigers @ Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMl0-2u

Shop  https //stza.co/+xMl0-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180809
DTEND;VALUE=DATE:20180809
UID:Dnnvs2coTFRmryu789mp0pWm@stanza.co
SUMMARY:Tigers @ Cyclones
DESCRIPTION:Tigers @ Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMl0-2u\n\nShop: https://stza.co/+xMl0-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ Cyclones
<2018-08-10 Fri>--<2018-08-09 Thu>
:PROPERTIES:
:ID:       s0L31C_067xusIn0pcBxdtPL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers @ Cyclones Tigers @ Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMl1-2q

Shop  https //stza.co/+xMl1-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180810
DTEND;VALUE=DATE:20180810
UID:s0L31C_067xusIn0pcBxdtPL@stanza.co
SUMMARY:Tigers @ Cyclones
DESCRIPTION:Tigers @ Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMl1-2q\n\nShop: https://stza.co/+xMl1-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. Yankees
<2018-08-11 Sat>--<2018-08-10 Fri>
:PROPERTIES:
:ID:       nuBc1Z3JyjI4AQ0woIMwh_LG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers vs. Yankees Tigers vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xMlX-22

Shop  https //stza.co/+xMlX-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. Yankees
END:VALARM
DTSTART;VALUE=DATE:20180811
DTEND;VALUE=DATE:20180811
UID:nuBc1Z3JyjI4AQ0woIMwh_LG@stanza.co
SUMMARY:Tigers vs. Yankees
DESCRIPTION:Tigers vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMlX-22\n\nShop: https://stza.co/+xMlX-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. Yankees
<2018-08-12 Sun>--<2018-08-11 Sat>
:PROPERTIES:
:ID:       AThFnXt7GxSqi4NvRlZKVIZW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tigers vs. Yankees Tigers vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xMlZ-1E

Shop  https //stza.co/+xMlZ-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. Yankees
END:VALARM
DTSTART;VALUE=DATE:20180812
DTEND;VALUE=DATE:20180812
UID:AThFnXt7GxSqi4NvRlZKVIZW@stanza.co
SUMMARY:Tigers vs. Yankees
DESCRIPTION:Tigers vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMlZ-1E\n\nShop: https://stza.co/+xMlZ-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ ValleyCats
<2018-08-15 Wed>--<2018-08-14 Tue>
:PROPERTIES:
:ID:       yKU1ptiQgNrAJ3IBRUgGnx_E@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers @ ValleyCats Tigers @ ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMmw-1Q

Shop  https //stza.co/+xMmw-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180815
DTEND;VALUE=DATE:20180815
UID:yKU1ptiQgNrAJ3IBRUgGnx_E@stanza.co
SUMMARY:Tigers @ ValleyCats
DESCRIPTION:Tigers @ ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMmw-1Q\n\nShop: https://stza.co/+xMmw-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ ValleyCats
<2018-08-16 Thu>--<2018-08-15 Wed>
:PROPERTIES:
:ID:       G2KDQFpQaydtpU5MJK4Tb-K6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers @ ValleyCats Tigers @ ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMmx-1z

Shop  https //stza.co/+xMmx-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180816
DTEND;VALUE=DATE:20180816
UID:G2KDQFpQaydtpU5MJK4Tb-K6@stanza.co
SUMMARY:Tigers @ ValleyCats
DESCRIPTION:Tigers @ ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMmx-1z\n\nShop: https://stza.co/+xMmx-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. IronBirds
<2018-08-17 Fri>--<2018-08-16 Thu>
:PROPERTIES:
:ID:       IkN3f6tyY_aQlOmTEMd9AsBv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tigers vs. IronBirds Tigers vs. IronBirds

Follow on MiLB First Pitch  https //stza.co/+xMl$-3W

Shop  https //stza.co/+xMl$-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. IronBirds
END:VALARM
DTSTART;VALUE=DATE:20180817
DTEND;VALUE=DATE:20180817
UID:IkN3f6tyY_aQlOmTEMd9AsBv@stanza.co
SUMMARY:Tigers vs. IronBirds
DESCRIPTION:Tigers vs. IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xMl$-3W\n\nShop: https://stza.co/+xMl$-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. IronBirds
<2018-08-18 Sat>--<2018-08-17 Fri>
:PROPERTIES:
:ID:       Iax7AAIHlv2DJ-Qc2SAdMloy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers vs. IronBirds Tigers vs. IronBirds

Follow on MiLB First Pitch  https //stza.co/+xMm2-1G

Shop  https //stza.co/+xMm2-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. IronBirds
END:VALARM
DTSTART;VALUE=DATE:20180818
DTEND;VALUE=DATE:20180818
UID:Iax7AAIHlv2DJ-Qc2SAdMloy@stanza.co
SUMMARY:Tigers vs. IronBirds
DESCRIPTION:Tigers vs. IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xMm2-1G\n\nShop: https://stza.co/+xMm2-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. IronBirds
<2018-08-19 Sun>--<2018-08-18 Sat>
:PROPERTIES:
:ID:       3DYKiX_IfFrUt0XqQ8SMR6Cu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers vs. IronBirds Tigers vs. IronBirds

Follow on MiLB First Pitch  https //stza.co/+xMm4-3S

Shop  https //stza.co/+xMm4-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. IronBirds
END:VALARM
DTSTART;VALUE=DATE:20180819
DTEND;VALUE=DATE:20180819
UID:3DYKiX_IfFrUt0XqQ8SMR6Cu@stanza.co
SUMMARY:Tigers vs. IronBirds
DESCRIPTION:Tigers vs. IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xMm4-3S\n\nShop: https://stza.co/+xMm4-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. Renegades
<2018-08-20 Mon>--<2018-08-19 Sun>
:PROPERTIES:
:ID:       qV_B0VQYaYlVCKsYo0Mm1q2b@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tigers vs. Renegades Tigers vs. Renegades

Follow on MiLB First Pitch  https //stza.co/+xMm6-y

Shop  https //stza.co/+xMm6-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. Renegades
END:VALARM
DTSTART;VALUE=DATE:20180820
DTEND;VALUE=DATE:20180820
UID:qV_B0VQYaYlVCKsYo0Mm1q2b@stanza.co
SUMMARY:Tigers vs. Renegades
DESCRIPTION:Tigers vs. Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xMm6-y\n\nShop: https://stza.co/+xMm6-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. Renegades
<2018-08-21 Tue>--<2018-08-20 Mon>
:PROPERTIES:
:ID:       wumy8MVYvuB8jXhp_Fx3KBn0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers vs. Renegades Tigers vs. Renegades

Follow on MiLB First Pitch  https //stza.co/+xMm7-3e

Shop  https //stza.co/+xMm7-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. Renegades
END:VALARM
DTSTART;VALUE=DATE:20180821
DTEND;VALUE=DATE:20180821
UID:wumy8MVYvuB8jXhp_Fx3KBn0@stanza.co
SUMMARY:Tigers vs. Renegades
DESCRIPTION:Tigers vs. Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xMm7-3e\n\nShop: https://stza.co/+xMm7-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. Renegades
<2018-08-22 Wed>--<2018-08-21 Tue>
:PROPERTIES:
:ID:       Ey20pBNtz846X10Tqs9YNSBA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers vs. Renegades Tigers vs. Renegades

Follow on MiLB First Pitch  https //stza.co/+xMm9-3B

Shop  https //stza.co/+xMm9-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. Renegades
END:VALARM
DTSTART;VALUE=DATE:20180822
DTEND;VALUE=DATE:20180822
UID:Ey20pBNtz846X10Tqs9YNSBA@stanza.co
SUMMARY:Tigers vs. Renegades
DESCRIPTION:Tigers vs. Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xMm9-3B\n\nShop: https://stza.co/+xMm9-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ Cyclones
<2018-08-23 Thu>--<2018-08-22 Wed>
:PROPERTIES:
:ID:       _uCHmG-wRFmiiqGOWrP3AcMv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tigers @ Cyclones Tigers @ Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMl2-G

Shop  https //stza.co/+xMl2-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180823
DTEND;VALUE=DATE:20180823
UID:_uCHmG-wRFmiiqGOWrP3AcMv@stanza.co
SUMMARY:Tigers @ Cyclones
DESCRIPTION:Tigers @ Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMl2-G\n\nShop: https://stza.co/+xMl2-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ Cyclones
<2018-08-24 Fri>--<2018-08-23 Thu>
:PROPERTIES:
:ID:       rQxxGvfM0EDeWdfnuWsABg2V@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers @ Cyclones Tigers @ Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMl3-14

Shop  https //stza.co/+xMl3-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180824
DTEND;VALUE=DATE:20180824
UID:rQxxGvfM0EDeWdfnuWsABg2V@stanza.co
SUMMARY:Tigers @ Cyclones
DESCRIPTION:Tigers @ Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMl3-14\n\nShop: https://stza.co/+xMl3-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ Cyclones
<2018-08-25 Sat>--<2018-08-24 Fri>
:PROPERTIES:
:ID:       mSVt4nu8OP0ko7VT4mMaRCuo@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers @ Cyclones Tigers @ Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMl4-P

Shop  https //stza.co/+xMl4-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180825
DTEND;VALUE=DATE:20180825
UID:mSVt4nu8OP0ko7VT4mMaRCuo@stanza.co
SUMMARY:Tigers @ Cyclones
DESCRIPTION:Tigers @ Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMl4-P\n\nShop: https://stza.co/+xMl4-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. Spinners
<2018-08-26 Sun>--<2018-08-25 Sat>
:PROPERTIES:
:ID:       uQEwy-Hc7g4qSFFgnuPPftM4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tigers vs. Spinners Tigers vs. Spinners

Follow on MiLB First Pitch  https //stza.co/+xMmc-1J

Shop  https //stza.co/+xMmc-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. Spinners
END:VALARM
DTSTART;VALUE=DATE:20180826
DTEND;VALUE=DATE:20180826
UID:uQEwy-Hc7g4qSFFgnuPPftM4@stanza.co
SUMMARY:Tigers vs. Spinners
DESCRIPTION:Tigers vs. Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMmc-1J\n\nShop: https://stza.co/+xMmc-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. Spinners
<2018-08-27 Mon>--<2018-08-26 Sun>
:PROPERTIES:
:ID:       FKlPE4e5i2DzQbdGGWGNfguY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers vs. Spinners Tigers vs. Spinners

Follow on MiLB First Pitch  https //stza.co/+xMme-2Z

Shop  https //stza.co/+xMme-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. Spinners
END:VALARM
DTSTART;VALUE=DATE:20180827
DTEND;VALUE=DATE:20180827
UID:FKlPE4e5i2DzQbdGGWGNfguY@stanza.co
SUMMARY:Tigers vs. Spinners
DESCRIPTION:Tigers vs. Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMme-2Z\n\nShop: https://stza.co/+xMme-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers vs. Spinners
<2018-08-28 Tue>--<2018-08-27 Mon>
:PROPERTIES:
:ID:       46FUIpXlpdBIHYcGlX0-eRbX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers vs. Spinners Tigers vs. Spinners

Follow on MiLB First Pitch  https //stza.co/+xMmf-3M

Shop  https //stza.co/+xMmf-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tigers vs. Spinners
END:VALARM
DTSTART;VALUE=DATE:20180828
DTEND;VALUE=DATE:20180828
UID:46FUIpXlpdBIHYcGlX0-eRbX@stanza.co
SUMMARY:Tigers vs. Spinners
DESCRIPTION:Tigers vs. Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMmf-3M\n\nShop: https://stza.co/+xMmf-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ IronBirds
<2018-08-29 Wed 18:05-21:05>
:PROPERTIES:
:ID:       znVxsPT0qpk80FXVQcss1pRB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tigers @ IronBirds Tigers @ IronBirds

Follow on MiLB First Pitch  https //stza.co/+xXTX-29

Shop  https //stza.co/+xXTX-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ IronBirds
END:VALARM
DTSTART:20180829T230500Z
DTEND:20180830T020500Z
UID:znVxsPT0qpk80FXVQcss1pRB@stanza.co
SUMMARY:Tigers @ IronBirds
DESCRIPTION:Tigers @ IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xXTX-29\n\nShop: https://stza.co/+xXTX-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ IronBirds
<2018-08-30 Thu 18:05-21:05>
:PROPERTIES:
:ID:       Sq3bb8Xgmw54IwwD90ouFWOV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers @ IronBirds Tigers @ IronBirds

Follow on MiLB First Pitch  https //stza.co/+xXTY-W

Shop  https //stza.co/+xXTY-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ IronBirds
END:VALARM
DTSTART:20180830T230500Z
DTEND:20180831T020500Z
UID:Sq3bb8Xgmw54IwwD90ouFWOV@stanza.co
SUMMARY:Tigers @ IronBirds
DESCRIPTION:Tigers @ IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xXTY-W\n\nShop: https://stza.co/+xXTY-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ IronBirds
<2018-08-31 Fri 18:05-21:05>
:PROPERTIES:
:ID:       7C8_3cYD00-_Iz2gcWrETLe4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers @ IronBirds Tigers @ IronBirds

Follow on MiLB First Pitch  https //stza.co/+xXTZ-2j

Shop  https //stza.co/+xXTZ-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ IronBirds
END:VALARM
DTSTART:20180831T230500Z
DTEND:20180901T020500Z
UID:7C8_3cYD00-_Iz2gcWrETLe4@stanza.co
SUMMARY:Tigers @ IronBirds
DESCRIPTION:Tigers @ IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xXTZ-2j\n\nShop: https://stza.co/+xXTZ-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ Spinners
<2018-09-01 Sat>--<2018-08-31 Fri>
:PROPERTIES:
:ID:       VBeUOeyHsBjTQyW0OvnWOvku@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tigers @ Spinners Tigers @ Spinners

Follow on MiLB First Pitch  https //stza.co/+xMmq-2b

Shop  https //stza.co/+xMmq-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ Spinners
END:VALARM
DTSTART;VALUE=DATE:20180901
DTEND;VALUE=DATE:20180901
UID:VBeUOeyHsBjTQyW0OvnWOvku@stanza.co
SUMMARY:Tigers @ Spinners
DESCRIPTION:Tigers @ Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMmq-2b\n\nShop: https://stza.co/+xMmq-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ Spinners
<2018-09-02 Sun>--<2018-09-01 Sat>
:PROPERTIES:
:ID:       snodcHPCQSVrESRew6SPcbqm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers @ Spinners Tigers @ Spinners

Follow on MiLB First Pitch  https //stza.co/+xMmr-3c

Shop  https //stza.co/+xMmr-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ Spinners
END:VALARM
DTSTART;VALUE=DATE:20180902
DTEND;VALUE=DATE:20180902
UID:snodcHPCQSVrESRew6SPcbqm@stanza.co
SUMMARY:Tigers @ Spinners
DESCRIPTION:Tigers @ Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMmr-3c\n\nShop: https://stza.co/+xMmr-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Tigers @ Spinners
<2018-09-03 Mon>--<2018-09-02 Sun>
:PROPERTIES:
:ID:       cL7ezIM3eesZ5tS4Oc_TdWOH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tigers @ Spinners Tigers @ Spinners

Follow on MiLB First Pitch  https //stza.co/+xMms-8

Shop  https //stza.co/+xMms-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tigers @ Spinners
END:VALARM
DTSTART;VALUE=DATE:20180903
DTEND;VALUE=DATE:20180903
UID:cL7ezIM3eesZ5tS4Oc_TdWOH@stanza.co
SUMMARY:Tigers @ Spinners
DESCRIPTION:Tigers @ Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMms-8\n\nShop: https://stza.co/+xMms-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
