#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Doubledays vs. Muckdogs
<2018-06-15 Fri 17:30-20:30>
:PROPERTIES:
:ID:       fWeFgP5J499qsP1ltX3k8P_j@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Muckdogs Doubledays vs. Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xVYT-Q

Shop  https //stza.co/+xVYT-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Muckdogs
END:VALARM
DTSTART:20180615T223000Z
DTEND:20180616T013000Z
UID:fWeFgP5J499qsP1ltX3k8P_j@stanza.co
SUMMARY:Doubledays vs. Muckdogs
DESCRIPTION:Doubledays vs. Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xVYT-Q\n\nShop: https://stza.co/+xVYT-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Muckdogs
<2018-06-16 Sat 17:30-20:30>
:PROPERTIES:
:ID:       OrekWlpfNNiYNJHGrurktizE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Muckdogs Doubledays vs. Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xVYW-b

Shop  https //stza.co/+xVYW-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Muckdogs
END:VALARM
DTSTART:20180616T223000Z
DTEND:20180617T013000Z
UID:OrekWlpfNNiYNJHGrurktizE@stanza.co
SUMMARY:Doubledays vs. Muckdogs
DESCRIPTION:Doubledays vs. Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xVYW-b\n\nShop: https://stza.co/+xVYW-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Muckdogs
<2018-06-17 Sun 13:00-16:00>
:PROPERTIES:
:ID:       c6mMEZSff_QMV1nYM63TPxbB@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Muckdogs Doubledays vs. Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xVYY-v

Shop  https //stza.co/+xVYY-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Muckdogs
END:VALARM
DTSTART:20180617T180000Z
DTEND:20180617T210000Z
UID:c6mMEZSff_QMV1nYM63TPxbB@stanza.co
SUMMARY:Doubledays vs. Muckdogs
DESCRIPTION:Doubledays vs. Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xVYY-v\n\nShop: https://stza.co/+xVYY-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ Crosscutters
<2018-06-18 Mon 18:05-21:05>
:PROPERTIES:
:ID:       -VTDP-rN7f0CZEFIBHNMn7rM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays @ Crosscutters Doubledays @ Crosscutters

Follow on MiLB First Pitch  https //stza.co/+x$5Z-1W

Shop  https //stza.co/+x$5Z-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ Crosscutters
END:VALARM
DTSTART:20180618T230500Z
DTEND:20180619T020500Z
UID:-VTDP-rN7f0CZEFIBHNMn7rM@stanza.co
SUMMARY:Doubledays @ Crosscutters
DESCRIPTION:Doubledays @ Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+x$5Z-1W\n\nShop: https://stza.co/+x$5Z-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ Crosscutters
<2018-06-19 Tue 18:05-21:05>
:PROPERTIES:
:ID:       THeCxNv1_pue-KV3sHtCUk7I@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Doubledays @ Crosscutters Doubledays @ Crosscutters

Follow on MiLB First Pitch  https //stza.co/+x$5_-3B

Shop  https //stza.co/+x$5_-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ Crosscutters
END:VALARM
DTSTART:20180619T230500Z
DTEND:20180620T020500Z
UID:THeCxNv1_pue-KV3sHtCUk7I@stanza.co
SUMMARY:Doubledays @ Crosscutters
DESCRIPTION:Doubledays @ Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+x$5_-3B\n\nShop: https://stza.co/+x$5_-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ Crosscutters
<2018-06-20 Wed 18:05-21:05>
:PROPERTIES:
:ID:       wOZTIKmwEdzskByivnGf9Ena@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays @ Crosscutters Doubledays @ Crosscutters

Follow on MiLB First Pitch  https //stza.co/+x$5$-t

Shop  https //stza.co/+x$5$-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ Crosscutters
END:VALARM
DTSTART:20180620T230500Z
DTEND:20180621T020500Z
UID:wOZTIKmwEdzskByivnGf9Ena@stanza.co
SUMMARY:Doubledays @ Crosscutters
DESCRIPTION:Doubledays @ Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+x$5$-t\n\nShop: https://stza.co/+x$5$-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ Scrappers
<2018-06-21 Thu>--<2018-06-20 Wed>
:PROPERTIES:
:ID:       _Goz2T_BTjliYkZhuUno4bj-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays @ Scrappers Doubledays @ Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMgR-3M

Shop  https //stza.co/+xMgR-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180621
DTEND;VALUE=DATE:20180621
UID:_Goz2T_BTjliYkZhuUno4bj-@stanza.co
SUMMARY:Doubledays @ Scrappers
DESCRIPTION:Doubledays @ Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMgR-3M\n\nShop: https://stza.co/+xMgR-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ Scrappers
<2018-06-22 Fri>--<2018-06-21 Thu>
:PROPERTIES:
:ID:       NUXndv8r_YR6e17_yhFwpV8t@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Doubledays @ Scrappers Doubledays @ Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMgS-1k

Shop  https //stza.co/+xMgS-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180622
DTEND;VALUE=DATE:20180622
UID:NUXndv8r_YR6e17_yhFwpV8t@stanza.co
SUMMARY:Doubledays @ Scrappers
DESCRIPTION:Doubledays @ Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMgS-1k\n\nShop: https://stza.co/+xMgS-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ Scrappers
<2018-06-23 Sat>--<2018-06-22 Fri>
:PROPERTIES:
:ID:       lKS-xmBCBQ434poqP9Z0DuTP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays @ Scrappers Doubledays @ Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMgT-2B

Shop  https //stza.co/+xMgT-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180623
DTEND;VALUE=DATE:20180623
UID:lKS-xmBCBQ434poqP9Z0DuTP@stanza.co
SUMMARY:Doubledays @ Scrappers
DESCRIPTION:Doubledays @ Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMgT-2B\n\nShop: https://stza.co/+xMgT-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Black Bears
<2018-06-24 Sun 13:00-16:00>
:PROPERTIES:
:ID:       neWkxM7wJsgEfymFr9PFuGN0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Black Bears Doubledays vs. Black Bears

Follow on MiLB First Pitch  https //stza.co/+xVY_-E

Shop  https //stza.co/+xVY_-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Black Bears
END:VALARM
DTSTART:20180624T180000Z
DTEND:20180624T210000Z
UID:neWkxM7wJsgEfymFr9PFuGN0@stanza.co
SUMMARY:Doubledays vs. Black Bears
DESCRIPTION:Doubledays vs. Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xVY_-E\n\nShop: https://stza.co/+xVY_-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Black Bears
<2018-06-25 Mon 17:30-20:30>
:PROPERTIES:
:ID:       7sT6qGyZY-5pyJnLZwIyavPt@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Black Bears Doubledays vs. Black Bears

Follow on MiLB First Pitch  https //stza.co/+xVZ0-2o

Shop  https //stza.co/+xVZ0-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Black Bears
END:VALARM
DTSTART:20180625T223000Z
DTEND:20180626T013000Z
UID:7sT6qGyZY-5pyJnLZwIyavPt@stanza.co
SUMMARY:Doubledays vs. Black Bears
DESCRIPTION:Doubledays vs. Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xVZ0-2o\n\nShop: https://stza.co/+xVZ0-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Black Bears
<2018-06-26 Tue 17:30-20:30>
:PROPERTIES:
:ID:       FHmycNgWObu4w_B2LF8WMYWk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Black Bears Doubledays vs. Black Bears

Follow on MiLB First Pitch  https //stza.co/+xVZ2-1_

Shop  https //stza.co/+xVZ2-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Black Bears
END:VALARM
DTSTART:20180626T223000Z
DTEND:20180627T013000Z
UID:FHmycNgWObu4w_B2LF8WMYWk@stanza.co
SUMMARY:Doubledays vs. Black Bears
DESCRIPTION:Doubledays vs. Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xVZ2-1_\n\nShop: https://stza.co/+xVZ2-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ Muckdogs
<2018-06-28 Thu>--<2018-06-27 Wed>
:PROPERTIES:
:ID:       5raqzebypCk4qtDaajC5t527@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays @ Muckdogs Doubledays @ Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMgL-2T

Shop  https //stza.co/+xMgL-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180628
DTEND;VALUE=DATE:20180628
UID:5raqzebypCk4qtDaajC5t527@stanza.co
SUMMARY:Doubledays @ Muckdogs
DESCRIPTION:Doubledays @ Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMgL-2T\n\nShop: https://stza.co/+xMgL-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Muckdogs
<2018-06-29 Fri 17:30-20:30>
:PROPERTIES:
:ID:       HACRNdEmQQztxzV7-gS3ldE_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Muckdogs Doubledays vs. Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xVZ4-1K

Shop  https //stza.co/+xVZ4-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Muckdogs
END:VALARM
DTSTART:20180629T223000Z
DTEND:20180630T013000Z
UID:HACRNdEmQQztxzV7-gS3ldE_@stanza.co
SUMMARY:Doubledays vs. Muckdogs
DESCRIPTION:Doubledays vs. Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xVZ4-1K\n\nShop: https://stza.co/+xVZ4-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Muckdogs
<2018-06-30 Sat 17:30-20:30>
:PROPERTIES:
:ID:       ts7g2DuqYeS9MSAEhvmTpuCS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Muckdogs Doubledays vs. Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xVZ6-G

Shop  https //stza.co/+xVZ6-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Muckdogs
END:VALARM
DTSTART:20180630T223000Z
DTEND:20180701T013000Z
UID:ts7g2DuqYeS9MSAEhvmTpuCS@stanza.co
SUMMARY:Doubledays vs. Muckdogs
DESCRIPTION:Doubledays vs. Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xVZ6-G\n\nShop: https://stza.co/+xVZ6-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ Crosscutters
<2018-07-01 Sun 16:05-19:05>
:PROPERTIES:
:ID:       lACXXgsEz4C2zLsWiH5MTre4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays @ Crosscutters Doubledays @ Crosscutters

Follow on MiLB First Pitch  https //stza.co/+x$60-1H

Shop  https //stza.co/+x$60-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ Crosscutters
END:VALARM
DTSTART:20180701T210500Z
DTEND:20180702T000500Z
UID:lACXXgsEz4C2zLsWiH5MTre4@stanza.co
SUMMARY:Doubledays @ Crosscutters
DESCRIPTION:Doubledays @ Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+x$60-1H\n\nShop: https://stza.co/+x$60-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ Crosscutters
<2018-07-02 Mon 18:05-21:05>
:PROPERTIES:
:ID:       KRfpMqDvZMedRX91sUGk-N6Q@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Doubledays @ Crosscutters Doubledays @ Crosscutters

Follow on MiLB First Pitch  https //stza.co/+x$61-a

Shop  https //stza.co/+x$61-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ Crosscutters
END:VALARM
DTSTART:20180702T230500Z
DTEND:20180703T020500Z
UID:KRfpMqDvZMedRX91sUGk-N6Q@stanza.co
SUMMARY:Doubledays @ Crosscutters
DESCRIPTION:Doubledays @ Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+x$61-a\n\nShop: https://stza.co/+x$61-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ Crosscutters
<2018-07-03 Tue 18:05-21:05>
:PROPERTIES:
:ID:       qUy9JPf-c_MIpWA8CYQhFChN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays @ Crosscutters Doubledays @ Crosscutters

Follow on MiLB First Pitch  https //stza.co/+x$62-1

Shop  https //stza.co/+x$62-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ Crosscutters
END:VALARM
DTSTART:20180703T230500Z
DTEND:20180704T020500Z
UID:qUy9JPf-c_MIpWA8CYQhFChN@stanza.co
SUMMARY:Doubledays @ Crosscutters
DESCRIPTION:Doubledays @ Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+x$62-1\n\nShop: https://stza.co/+x$62-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Spikes
<2018-07-04 Wed 17:30-20:30>
:PROPERTIES:
:ID:       Fln33PZd5mUZvlScPRVDvTVE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Spikes Doubledays vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+xVZ8-3_

Shop  https //stza.co/+xVZ8-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Spikes
END:VALARM
DTSTART:20180704T223000Z
DTEND:20180705T013000Z
UID:Fln33PZd5mUZvlScPRVDvTVE@stanza.co
SUMMARY:Doubledays vs. Spikes
DESCRIPTION:Doubledays vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xVZ8-3_\n\nShop: https://stza.co/+xVZ8-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Spikes
<2018-07-05 Thu 17:30-20:30>
:PROPERTIES:
:ID:       kDxNZbQNxRmgEWk30wZeXa8_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Spikes Doubledays vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+xVZ9-

Shop  https //stza.co/+xVZ9-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Spikes
END:VALARM
DTSTART:20180705T223000Z
DTEND:20180706T013000Z
UID:kDxNZbQNxRmgEWk30wZeXa8_@stanza.co
SUMMARY:Doubledays vs. Spikes
DESCRIPTION:Doubledays vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xVZ9-\n\nShop: https://stza.co/+xVZ9-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Spikes
<2018-07-06 Fri 17:30-20:30>
:PROPERTIES:
:ID:       5q-hYIxgz1HmFOGSHxazgggd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Spikes Doubledays vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+xVZc-8

Shop  https //stza.co/+xVZc-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Spikes
END:VALARM
DTSTART:20180706T223000Z
DTEND:20180707T013000Z
UID:5q-hYIxgz1HmFOGSHxazgggd@stanza.co
SUMMARY:Doubledays vs. Spikes
DESCRIPTION:Doubledays vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xVZc-8\n\nShop: https://stza.co/+xVZc-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ Black Bears
<2018-07-07 Sat 18:05-21:05>
:PROPERTIES:
:ID:       IAjUiPTvBb9Dr9djYBSphH-w@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays @ Black Bears Doubledays @ Black Bears

Follow on MiLB First Pitch  https //stza.co/+xV_3-2u

Shop  https //stza.co/+xV_3-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ Black Bears
END:VALARM
DTSTART:20180707T230500Z
DTEND:20180708T020500Z
UID:IAjUiPTvBb9Dr9djYBSphH-w@stanza.co
SUMMARY:Doubledays @ Black Bears
DESCRIPTION:Doubledays @ Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xV_3-2u\n\nShop: https://stza.co/+xV_3-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ Black Bears
<2018-07-08 Sun 15:05-18:05>
:PROPERTIES:
:ID:       jJ3iobPIkpesAad8-_HsKyU1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Doubledays @ Black Bears Doubledays @ Black Bears

Follow on MiLB First Pitch  https //stza.co/+xV_4-1B

Shop  https //stza.co/+xV_4-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ Black Bears
END:VALARM
DTSTART:20180708T200500Z
DTEND:20180708T230500Z
UID:jJ3iobPIkpesAad8-_HsKyU1@stanza.co
SUMMARY:Doubledays @ Black Bears
DESCRIPTION:Doubledays @ Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xV_4-1B\n\nShop: https://stza.co/+xV_4-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ Black Bears
<2018-07-09 Mon 18:05-21:05>
:PROPERTIES:
:ID:       JUSh13rhtGTKDv3RdNYJctSY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays @ Black Bears Doubledays @ Black Bears

Follow on MiLB First Pitch  https //stza.co/+xV_5-3T

Shop  https //stza.co/+xV_5-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ Black Bears
END:VALARM
DTSTART:20180709T230500Z
DTEND:20180710T020500Z
UID:JUSh13rhtGTKDv3RdNYJctSY@stanza.co
SUMMARY:Doubledays @ Black Bears
DESCRIPTION:Doubledays @ Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xV_5-3T\n\nShop: https://stza.co/+xV_5-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Spinners
<2018-07-11 Wed 17:30-20:30>
:PROPERTIES:
:ID:       SJV8TL_q0B2ZZ1HU0xt9sUN3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Spinners Doubledays vs. Spinners

Follow on MiLB First Pitch  https //stza.co/+xVZe-2G

Shop  https //stza.co/+xVZe-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Spinners
END:VALARM
DTSTART:20180711T223000Z
DTEND:20180712T013000Z
UID:SJV8TL_q0B2ZZ1HU0xt9sUN3@stanza.co
SUMMARY:Doubledays vs. Spinners
DESCRIPTION:Doubledays vs. Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xVZe-2G\n\nShop: https://stza.co/+xVZe-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Spinners
<2018-07-12 Thu 17:30-20:30>
:PROPERTIES:
:ID:       2Wrr7Hx4QLICR2wLArWPONqm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Spinners Doubledays vs. Spinners

Follow on MiLB First Pitch  https //stza.co/+xVZf-1o

Shop  https //stza.co/+xVZf-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Spinners
END:VALARM
DTSTART:20180712T223000Z
DTEND:20180713T013000Z
UID:2Wrr7Hx4QLICR2wLArWPONqm@stanza.co
SUMMARY:Doubledays vs. Spinners
DESCRIPTION:Doubledays vs. Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xVZf-1o\n\nShop: https://stza.co/+xVZf-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Spinners
<2018-07-13 Fri 17:30-20:30>
:PROPERTIES:
:ID:       47mEaLhkibu5JAQKhkcGWDln@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Spinners Doubledays vs. Spinners

Follow on MiLB First Pitch  https //stza.co/+xVZh-17

Shop  https //stza.co/+xVZh-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Spinners
END:VALARM
DTSTART:20180713T223000Z
DTEND:20180714T013000Z
UID:47mEaLhkibu5JAQKhkcGWDln@stanza.co
SUMMARY:Doubledays vs. Spinners
DESCRIPTION:Doubledays vs. Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xVZh-17\n\nShop: https://stza.co/+xVZh-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ IronBirds
<2018-07-14 Sat 17:05-20:05>
:PROPERTIES:
:ID:       TWoQ35t6g-pirzZaKPOfZAep@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays @ IronBirds Doubledays @ IronBirds

Follow on MiLB First Pitch  https //stza.co/+xXTM-t

Shop  https //stza.co/+xXTM-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ IronBirds
END:VALARM
DTSTART:20180714T220500Z
DTEND:20180715T010500Z
UID:TWoQ35t6g-pirzZaKPOfZAep@stanza.co
SUMMARY:Doubledays @ IronBirds
DESCRIPTION:Doubledays @ IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xXTM-t\n\nShop: https://stza.co/+xXTM-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ IronBirds
<2018-07-15 Sun 15:05-18:05>
:PROPERTIES:
:ID:       qhUdxNDi4ssIipJUtv-_bEdv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Doubledays @ IronBirds Doubledays @ IronBirds

Follow on MiLB First Pitch  https //stza.co/+xXTN-38

Shop  https //stza.co/+xXTN-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ IronBirds
END:VALARM
DTSTART:20180715T200500Z
DTEND:20180715T230500Z
UID:qhUdxNDi4ssIipJUtv-_bEdv@stanza.co
SUMMARY:Doubledays @ IronBirds
DESCRIPTION:Doubledays @ IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xXTN-38\n\nShop: https://stza.co/+xXTN-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ IronBirds
<2018-07-16 Mon 10:05-13:05>
:PROPERTIES:
:ID:       XonGUWl3TBQya2lR5DmKeute@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays @ IronBirds Doubledays @ IronBirds

Follow on MiLB First Pitch  https //stza.co/+xXTO-3Z

Shop  https //stza.co/+xXTO-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ IronBirds
END:VALARM
DTSTART:20180716T150500Z
DTEND:20180716T180500Z
UID:XonGUWl3TBQya2lR5DmKeute@stanza.co
SUMMARY:Doubledays @ IronBirds
DESCRIPTION:Doubledays @ IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xXTO-3Z\n\nShop: https://stza.co/+xXTO-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Scrappers
<2018-07-17 Tue 17:30-20:30>
:PROPERTIES:
:ID:       x5YXJ12f53ud88KqcDseXTQK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Scrappers Doubledays vs. Scrappers

Follow on MiLB First Pitch  https //stza.co/+xVZk-1G

Shop  https //stza.co/+xVZk-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Scrappers
END:VALARM
DTSTART:20180717T223000Z
DTEND:20180718T013000Z
UID:x5YXJ12f53ud88KqcDseXTQK@stanza.co
SUMMARY:Doubledays vs. Scrappers
DESCRIPTION:Doubledays vs. Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xVZk-1G\n\nShop: https://stza.co/+xVZk-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Scrappers
<2018-07-18 Wed 17:30-20:30>
:PROPERTIES:
:ID:       RiKz_bxTwJ-9YFE8DDpNxXJu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Scrappers Doubledays vs. Scrappers

Follow on MiLB First Pitch  https //stza.co/+xVZm-1D

Shop  https //stza.co/+xVZm-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Scrappers
END:VALARM
DTSTART:20180718T223000Z
DTEND:20180719T013000Z
UID:RiKz_bxTwJ-9YFE8DDpNxXJu@stanza.co
SUMMARY:Doubledays vs. Scrappers
DESCRIPTION:Doubledays vs. Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xVZm-1D\n\nShop: https://stza.co/+xVZm-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Scrappers
<2018-07-19 Thu 17:30-20:30>
:PROPERTIES:
:ID:       qjwHpDGAzO4r2-FyY7dQYk2D@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Scrappers Doubledays vs. Scrappers

Follow on MiLB First Pitch  https //stza.co/+xVZn-35

Shop  https //stza.co/+xVZn-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Scrappers
END:VALARM
DTSTART:20180719T223000Z
DTEND:20180720T013000Z
UID:qjwHpDGAzO4r2-FyY7dQYk2D@stanza.co
SUMMARY:Doubledays vs. Scrappers
DESCRIPTION:Doubledays vs. Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xVZn-35\n\nShop: https://stza.co/+xVZn-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ Spikes
<2018-07-20 Fri>--<2018-07-19 Thu>
:PROPERTIES:
:ID:       h5E6-ch4jfX-5rkL7vUxkXGB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays @ Spikes Doubledays @ Spikes

Follow on MiLB First Pitch  https //stza.co/+xMgW-2c

Shop  https //stza.co/+xMgW-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ Spikes
END:VALARM
DTSTART;VALUE=DATE:20180720
DTEND;VALUE=DATE:20180720
UID:h5E6-ch4jfX-5rkL7vUxkXGB@stanza.co
SUMMARY:Doubledays @ Spikes
DESCRIPTION:Doubledays @ Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMgW-2c\n\nShop: https://stza.co/+xMgW-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ Spikes
<2018-07-21 Sat>--<2018-07-20 Fri>
:PROPERTIES:
:ID:       r5F-aFY_CP4B1iFmWmscFTXX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Doubledays @ Spikes Doubledays @ Spikes

Follow on MiLB First Pitch  https //stza.co/+xMgX-1D

Shop  https //stza.co/+xMgX-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ Spikes
END:VALARM
DTSTART;VALUE=DATE:20180721
DTEND;VALUE=DATE:20180721
UID:r5F-aFY_CP4B1iFmWmscFTXX@stanza.co
SUMMARY:Doubledays @ Spikes
DESCRIPTION:Doubledays @ Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMgX-1D\n\nShop: https://stza.co/+xMgX-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ Spikes
<2018-07-22 Sun>--<2018-07-21 Sat>
:PROPERTIES:
:ID:       DrJKi4US4r1W82mowEnxKVAM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays @ Spikes Doubledays @ Spikes

Follow on MiLB First Pitch  https //stza.co/+xMgY-24

Shop  https //stza.co/+xMgY-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ Spikes
END:VALARM
DTSTART;VALUE=DATE:20180722
DTEND;VALUE=DATE:20180722
UID:DrJKi4US4r1W82mowEnxKVAM@stanza.co
SUMMARY:Doubledays @ Spikes
DESCRIPTION:Doubledays @ Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMgY-24\n\nShop: https://stza.co/+xMgY-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ ValleyCats
<2018-07-24 Tue>--<2018-07-23 Mon>
:PROPERTIES:
:ID:       _Wz2xQmOoI9Uq3JeOgIsp3Il@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays @ ValleyCats Doubledays @ ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMh3-v

Shop  https //stza.co/+xMh3-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180724
DTEND;VALUE=DATE:20180724
UID:_Wz2xQmOoI9Uq3JeOgIsp3Il@stanza.co
SUMMARY:Doubledays @ ValleyCats
DESCRIPTION:Doubledays @ ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMh3-v\n\nShop: https://stza.co/+xMh3-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ ValleyCats
<2018-07-25 Wed>--<2018-07-24 Tue>
:PROPERTIES:
:ID:       KzJ2_IwEJk6zUjbJOKVxneng@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Doubledays @ ValleyCats Doubledays @ ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMh4-2e

Shop  https //stza.co/+xMh4-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180725
DTEND;VALUE=DATE:20180725
UID:KzJ2_IwEJk6zUjbJOKVxneng@stanza.co
SUMMARY:Doubledays @ ValleyCats
DESCRIPTION:Doubledays @ ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMh4-2e\n\nShop: https://stza.co/+xMh4-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ ValleyCats
<2018-07-26 Thu>--<2018-07-25 Wed>
:PROPERTIES:
:ID:       sPr9sXx1RdUra-iOCcQM4cvC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays @ ValleyCats Doubledays @ ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMh5-2z

Shop  https //stza.co/+xMh5-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180726
DTEND;VALUE=DATE:20180726
UID:sPr9sXx1RdUra-iOCcQM4cvC@stanza.co
SUMMARY:Doubledays @ ValleyCats
DESCRIPTION:Doubledays @ ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMh5-2z\n\nShop: https://stza.co/+xMh5-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Tigers
<2018-07-27 Fri 17:30-20:30>
:PROPERTIES:
:ID:       xwOGzxBn06pTdUCas_wHgmlQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Tigers Doubledays vs. Tigers

Follow on MiLB First Pitch  https //stza.co/+xVZp-j

Shop  https //stza.co/+xVZp-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Tigers
END:VALARM
DTSTART:20180727T223000Z
DTEND:20180728T013000Z
UID:xwOGzxBn06pTdUCas_wHgmlQ@stanza.co
SUMMARY:Doubledays vs. Tigers
DESCRIPTION:Doubledays vs. Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xVZp-j\n\nShop: https://stza.co/+xVZp-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Tigers
<2018-07-28 Sat 17:30-20:30>
:PROPERTIES:
:ID:       oFngKjhLtwC9tIlQve8dpOD7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Tigers Doubledays vs. Tigers

Follow on MiLB First Pitch  https //stza.co/+xVZr-21

Shop  https //stza.co/+xVZr-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Tigers
END:VALARM
DTSTART:20180728T223000Z
DTEND:20180729T013000Z
UID:oFngKjhLtwC9tIlQve8dpOD7@stanza.co
SUMMARY:Doubledays vs. Tigers
DESCRIPTION:Doubledays vs. Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xVZr-21\n\nShop: https://stza.co/+xVZr-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Tigers
<2018-07-29 Sun 13:00-16:00>
:PROPERTIES:
:ID:       fF2X-LTqpU6vDlH0IUiEDydL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Tigers Doubledays vs. Tigers

Follow on MiLB First Pitch  https //stza.co/+xVZu-a

Shop  https //stza.co/+xVZu-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Tigers
END:VALARM
DTSTART:20180729T180000Z
DTEND:20180729T210000Z
UID:fF2X-LTqpU6vDlH0IUiEDydL@stanza.co
SUMMARY:Doubledays vs. Tigers
DESCRIPTION:Doubledays vs. Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xVZu-a\n\nShop: https://stza.co/+xVZu-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Black Bears
<2018-07-30 Mon 17:30-20:30>
:PROPERTIES:
:ID:       dI91bCts7fhBuJpuf151D8Y_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Black Bears Doubledays vs. Black Bears

Follow on MiLB First Pitch  https //stza.co/+xVZw-2s

Shop  https //stza.co/+xVZw-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Black Bears
END:VALARM
DTSTART:20180730T223000Z
DTEND:20180731T013000Z
UID:dI91bCts7fhBuJpuf151D8Y_@stanza.co
SUMMARY:Doubledays vs. Black Bears
DESCRIPTION:Doubledays vs. Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xVZw-2s\n\nShop: https://stza.co/+xVZw-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Black Bears
<2018-07-31 Tue 17:30-20:30>
:PROPERTIES:
:ID:       Tjp5lWiYTxG8_MwOMYqWqbrd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Black Bears Doubledays vs. Black Bears

Follow on MiLB First Pitch  https //stza.co/+xVZy-T

Shop  https //stza.co/+xVZy-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Black Bears
END:VALARM
DTSTART:20180731T223000Z
DTEND:20180801T013000Z
UID:Tjp5lWiYTxG8_MwOMYqWqbrd@stanza.co
SUMMARY:Doubledays vs. Black Bears
DESCRIPTION:Doubledays vs. Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xVZy-T\n\nShop: https://stza.co/+xVZy-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Black Bears
<2018-08-01 Wed 17:30-20:30>
:PROPERTIES:
:ID:       1yJGtkGhZmELVtqCP9Ui5oyj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Black Bears Doubledays vs. Black Bears

Follow on MiLB First Pitch  https //stza.co/+xVZz-2V

Shop  https //stza.co/+xVZz-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Black Bears
END:VALARM
DTSTART:20180801T223000Z
DTEND:20180802T013000Z
UID:1yJGtkGhZmELVtqCP9Ui5oyj@stanza.co
SUMMARY:Doubledays vs. Black Bears
DESCRIPTION:Doubledays vs. Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xVZz-2V\n\nShop: https://stza.co/+xVZz-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ Spikes
<2018-08-02 Thu>--<2018-08-01 Wed>
:PROPERTIES:
:ID:       ra686IlPyNMBtGORjaegDbH8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays @ Spikes Doubledays @ Spikes

Follow on MiLB First Pitch  https //stza.co/+xMgZ-2N

Shop  https //stza.co/+xMgZ-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ Spikes
END:VALARM
DTSTART;VALUE=DATE:20180802
DTEND;VALUE=DATE:20180802
UID:ra686IlPyNMBtGORjaegDbH8@stanza.co
SUMMARY:Doubledays @ Spikes
DESCRIPTION:Doubledays @ Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMgZ-2N\n\nShop: https://stza.co/+xMgZ-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ Spikes
<2018-08-03 Fri>--<2018-08-02 Thu>
:PROPERTIES:
:ID:       CSzQc6A6dBbsWXspUYZOk6QU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Doubledays @ Spikes Doubledays @ Spikes

Follow on MiLB First Pitch  https //stza.co/+xMg_-3L

Shop  https //stza.co/+xMg_-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ Spikes
END:VALARM
DTSTART;VALUE=DATE:20180803
DTEND;VALUE=DATE:20180803
UID:CSzQc6A6dBbsWXspUYZOk6QU@stanza.co
SUMMARY:Doubledays @ Spikes
DESCRIPTION:Doubledays @ Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMg_-3L\n\nShop: https://stza.co/+xMg_-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ Spikes
<2018-08-04 Sat>--<2018-08-03 Fri>
:PROPERTIES:
:ID:       4zZUfLu5U8X0Kc3FeCQw96oW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays @ Spikes Doubledays @ Spikes

Follow on MiLB First Pitch  https //stza.co/+xMg$-O

Shop  https //stza.co/+xMg$-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ Spikes
END:VALARM
DTSTART;VALUE=DATE:20180804
DTEND;VALUE=DATE:20180804
UID:4zZUfLu5U8X0Kc3FeCQw96oW@stanza.co
SUMMARY:Doubledays @ Spikes
DESCRIPTION:Doubledays @ Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMg$-O\n\nShop: https://stza.co/+xMg$-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Crosscutters
<2018-08-05 Sun 13:00-16:00>
:PROPERTIES:
:ID:       V7X0pYQXiQ6skqyBbjX4YRdx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Crosscutters Doubledays vs. Crosscutters

Follow on MiLB First Pitch  https //stza.co/+xVZB-3X

Shop  https //stza.co/+xVZB-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Crosscutters
END:VALARM
DTSTART:20180805T180000Z
DTEND:20180805T210000Z
UID:V7X0pYQXiQ6skqyBbjX4YRdx@stanza.co
SUMMARY:Doubledays vs. Crosscutters
DESCRIPTION:Doubledays vs. Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+xVZB-3X\n\nShop: https://stza.co/+xVZB-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Crosscutters
<2018-08-06 Mon 17:30-20:30>
:PROPERTIES:
:ID:       AGPu0uxYKymEersCiUvnkNG2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Crosscutters Doubledays vs. Crosscutters

Follow on MiLB First Pitch  https //stza.co/+xVZD-3s

Shop  https //stza.co/+xVZD-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Crosscutters
END:VALARM
DTSTART:20180806T223000Z
DTEND:20180807T013000Z
UID:AGPu0uxYKymEersCiUvnkNG2@stanza.co
SUMMARY:Doubledays vs. Crosscutters
DESCRIPTION:Doubledays vs. Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+xVZD-3s\n\nShop: https://stza.co/+xVZD-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Crosscutters
<2018-08-07 Tue 17:30-20:30>
:PROPERTIES:
:ID:       YejrvCiNVyxyksLEO6XyV-aJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Crosscutters Doubledays vs. Crosscutters

Follow on MiLB First Pitch  https //stza.co/+xVZG-1I

Shop  https //stza.co/+xVZG-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Crosscutters
END:VALARM
DTSTART:20180807T223000Z
DTEND:20180808T013000Z
UID:YejrvCiNVyxyksLEO6XyV-aJ@stanza.co
SUMMARY:Doubledays vs. Crosscutters
DESCRIPTION:Doubledays vs. Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+xVZG-1I\n\nShop: https://stza.co/+xVZG-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Muckdogs
<2018-08-08 Wed 17:30-20:30>
:PROPERTIES:
:ID:       e1O1clGhGswpqZli-aoKZ_cz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Muckdogs Doubledays vs. Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xVZI-r

Shop  https //stza.co/+xVZI-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Muckdogs
END:VALARM
DTSTART:20180808T223000Z
DTEND:20180809T013000Z
UID:e1O1clGhGswpqZli-aoKZ_cz@stanza.co
SUMMARY:Doubledays vs. Muckdogs
DESCRIPTION:Doubledays vs. Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xVZI-r\n\nShop: https://stza.co/+xVZI-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ Muckdogs
<2018-08-09 Thu>--<2018-08-08 Wed>
:PROPERTIES:
:ID:       sMzJ---KEwswYYCPgTMZMO58@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Doubledays @ Muckdogs Doubledays @ Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMgM-Y

Shop  https //stza.co/+xMgM-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180809
DTEND;VALUE=DATE:20180809
UID:sMzJ---KEwswYYCPgTMZMO58@stanza.co
SUMMARY:Doubledays @ Muckdogs
DESCRIPTION:Doubledays @ Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMgM-Y\n\nShop: https://stza.co/+xMgM-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ Muckdogs
<2018-08-10 Fri>--<2018-08-09 Thu>
:PROPERTIES:
:ID:       JwYz-zICZFkqK3OR6cqIY1aj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays @ Muckdogs Doubledays @ Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMgN-39

Shop  https //stza.co/+xMgN-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180810
DTEND;VALUE=DATE:20180810
UID:JwYz-zICZFkqK3OR6cqIY1aj@stanza.co
SUMMARY:Doubledays @ Muckdogs
DESCRIPTION:Doubledays @ Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMgN-39\n\nShop: https://stza.co/+xMgN-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Spikes
<2018-08-11 Sat 17:30-20:30>
:PROPERTIES:
:ID:       nI-txKYL18uwSJQ6sJnfn36N@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Spikes Doubledays vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+xVZJ-30

Shop  https //stza.co/+xVZJ-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Spikes
END:VALARM
DTSTART:20180811T223000Z
DTEND:20180812T013000Z
UID:nI-txKYL18uwSJQ6sJnfn36N@stanza.co
SUMMARY:Doubledays vs. Spikes
DESCRIPTION:Doubledays vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xVZJ-30\n\nShop: https://stza.co/+xVZJ-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Spikes
<2018-08-12 Sun 15:00-18:00>
:PROPERTIES:
:ID:       Uuzj6Xc9iBU5FMvU0lM1bvIR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Spikes Doubledays vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+xVZM-1f

Shop  https //stza.co/+xVZM-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Spikes
END:VALARM
DTSTART:20180812T200000Z
DTEND:20180812T230000Z
UID:Uuzj6Xc9iBU5FMvU0lM1bvIR@stanza.co
SUMMARY:Doubledays vs. Spikes
DESCRIPTION:Doubledays vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xVZM-1f\n\nShop: https://stza.co/+xVZM-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ Scrappers
<2018-08-15 Wed>--<2018-08-14 Tue>
:PROPERTIES:
:ID:       9AiehpjChxCssWuBMO8YtCdC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays @ Scrappers Doubledays @ Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMgU-31

Shop  https //stza.co/+xMgU-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180815
DTEND;VALUE=DATE:20180815
UID:9AiehpjChxCssWuBMO8YtCdC@stanza.co
SUMMARY:Doubledays @ Scrappers
DESCRIPTION:Doubledays @ Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMgU-31\n\nShop: https://stza.co/+xMgU-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ Scrappers
<2018-08-16 Thu>--<2018-08-15 Wed>
:PROPERTIES:
:ID:       lMZ10yH3gCGw1mqqQ-plWSd8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays @ Scrappers Doubledays @ Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMgV-29

Shop  https //stza.co/+xMgV-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180816
DTEND;VALUE=DATE:20180816
UID:lMZ10yH3gCGw1mqqQ-plWSd8@stanza.co
SUMMARY:Doubledays @ Scrappers
DESCRIPTION:Doubledays @ Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMgV-29\n\nShop: https://stza.co/+xMgV-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Muckdogs
<2018-08-17 Fri 17:30-20:30>
:PROPERTIES:
:ID:       afmEQx_5MoLx1VN1xm21uezc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Muckdogs Doubledays vs. Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xVZN-3S

Shop  https //stza.co/+xVZN-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Muckdogs
END:VALARM
DTSTART:20180817T223000Z
DTEND:20180818T013000Z
UID:afmEQx_5MoLx1VN1xm21uezc@stanza.co
SUMMARY:Doubledays vs. Muckdogs
DESCRIPTION:Doubledays vs. Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xVZN-3S\n\nShop: https://stza.co/+xVZN-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Muckdogs
<2018-08-18 Sat 17:30-20:30>
:PROPERTIES:
:ID:       AJ3YvG62qBxYjxKHuKdzEF-N@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Muckdogs Doubledays vs. Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xVZQ-3I

Shop  https //stza.co/+xVZQ-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Muckdogs
END:VALARM
DTSTART:20180818T223000Z
DTEND:20180819T013000Z
UID:AJ3YvG62qBxYjxKHuKdzEF-N@stanza.co
SUMMARY:Doubledays vs. Muckdogs
DESCRIPTION:Doubledays vs. Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xVZQ-3I\n\nShop: https://stza.co/+xVZQ-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Muckdogs
<2018-08-19 Sun 13:00-16:00>
:PROPERTIES:
:ID:       siTMQ8l-igG83qOzCsc-fnEW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Muckdogs Doubledays vs. Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xVZR-l

Shop  https //stza.co/+xVZR-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Muckdogs
END:VALARM
DTSTART:20180819T180000Z
DTEND:20180819T210000Z
UID:siTMQ8l-igG83qOzCsc-fnEW@stanza.co
SUMMARY:Doubledays vs. Muckdogs
DESCRIPTION:Doubledays vs. Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xVZR-l\n\nShop: https://stza.co/+xVZR-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Scrappers
<2018-08-20 Mon 17:30-20:30>
:PROPERTIES:
:ID:       O8ipOObDjdDnRa4HrWbtyLWF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Scrappers Doubledays vs. Scrappers

Follow on MiLB First Pitch  https //stza.co/+xVZT-o

Shop  https //stza.co/+xVZT-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Scrappers
END:VALARM
DTSTART:20180820T223000Z
DTEND:20180821T013000Z
UID:O8ipOObDjdDnRa4HrWbtyLWF@stanza.co
SUMMARY:Doubledays vs. Scrappers
DESCRIPTION:Doubledays vs. Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xVZT-o\n\nShop: https://stza.co/+xVZT-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Scrappers
<2018-08-21 Tue 17:30-20:30>
:PROPERTIES:
:ID:       T0bQ-Re7gu-Nhg6F9Yh-YlOF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Scrappers Doubledays vs. Scrappers

Follow on MiLB First Pitch  https //stza.co/+xVZV-N

Shop  https //stza.co/+xVZV-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Scrappers
END:VALARM
DTSTART:20180821T223000Z
DTEND:20180822T013000Z
UID:T0bQ-Re7gu-Nhg6F9Yh-YlOF@stanza.co
SUMMARY:Doubledays vs. Scrappers
DESCRIPTION:Doubledays vs. Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xVZV-N\n\nShop: https://stza.co/+xVZV-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Scrappers
<2018-08-22 Wed 17:30-20:30>
:PROPERTIES:
:ID:       t7p61ojvBtZ7Bp4dRpMdab0A@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Scrappers Doubledays vs. Scrappers

Follow on MiLB First Pitch  https //stza.co/+xVZY-20

Shop  https //stza.co/+xVZY-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Scrappers
END:VALARM
DTSTART:20180822T223000Z
DTEND:20180823T013000Z
UID:t7p61ojvBtZ7Bp4dRpMdab0A@stanza.co
SUMMARY:Doubledays vs. Scrappers
DESCRIPTION:Doubledays vs. Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xVZY-20\n\nShop: https://stza.co/+xVZY-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ Spikes
<2018-08-23 Thu>--<2018-08-22 Wed>
:PROPERTIES:
:ID:       T5xWbOP_CiRPVA6fOL9lXIKb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Doubledays @ Spikes Doubledays @ Spikes

Follow on MiLB First Pitch  https //stza.co/+xMh0-1f

Shop  https //stza.co/+xMh0-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ Spikes
END:VALARM
DTSTART;VALUE=DATE:20180823
DTEND;VALUE=DATE:20180823
UID:T5xWbOP_CiRPVA6fOL9lXIKb@stanza.co
SUMMARY:Doubledays @ Spikes
DESCRIPTION:Doubledays @ Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMh0-1f\n\nShop: https://stza.co/+xMh0-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ Spikes
<2018-08-24 Fri>--<2018-08-23 Thu>
:PROPERTIES:
:ID:       kX5B4AGGHJu9olxmNnYDF4sr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays @ Spikes Doubledays @ Spikes

Follow on MiLB First Pitch  https //stza.co/+xMh1-28

Shop  https //stza.co/+xMh1-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ Spikes
END:VALARM
DTSTART;VALUE=DATE:20180824
DTEND;VALUE=DATE:20180824
UID:kX5B4AGGHJu9olxmNnYDF4sr@stanza.co
SUMMARY:Doubledays @ Spikes
DESCRIPTION:Doubledays @ Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMh1-28\n\nShop: https://stza.co/+xMh1-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ Spikes
<2018-08-25 Sat>--<2018-08-24 Fri>
:PROPERTIES:
:ID:       YLRoc0B48S_x9x85jZc2aAOF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays @ Spikes Doubledays @ Spikes

Follow on MiLB First Pitch  https //stza.co/+xMh2-2I

Shop  https //stza.co/+xMh2-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ Spikes
END:VALARM
DTSTART;VALUE=DATE:20180825
DTEND;VALUE=DATE:20180825
UID:YLRoc0B48S_x9x85jZc2aAOF@stanza.co
SUMMARY:Doubledays @ Spikes
DESCRIPTION:Doubledays @ Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMh2-2I\n\nShop: https://stza.co/+xMh2-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ Black Bears
<2018-08-26 Sun 15:05-18:05>
:PROPERTIES:
:ID:       FpklatvdVJInbJLSJBJqHOUk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Doubledays @ Black Bears Doubledays @ Black Bears

Follow on MiLB First Pitch  https //stza.co/+xV_6-1o

Shop  https //stza.co/+xV_6-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ Black Bears
END:VALARM
DTSTART:20180826T200500Z
DTEND:20180826T230500Z
UID:FpklatvdVJInbJLSJBJqHOUk@stanza.co
SUMMARY:Doubledays @ Black Bears
DESCRIPTION:Doubledays @ Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xV_6-1o\n\nShop: https://stza.co/+xV_6-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ Black Bears
<2018-08-27 Mon 18:05-21:05>
:PROPERTIES:
:ID:       CY18mmVze2PtW4QvQIOOi5Z9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays @ Black Bears Doubledays @ Black Bears

Follow on MiLB First Pitch  https //stza.co/+xV_7-t

Shop  https //stza.co/+xV_7-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ Black Bears
END:VALARM
DTSTART:20180827T230500Z
DTEND:20180828T020500Z
UID:CY18mmVze2PtW4QvQIOOi5Z9@stanza.co
SUMMARY:Doubledays @ Black Bears
DESCRIPTION:Doubledays @ Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xV_7-t\n\nShop: https://stza.co/+xV_7-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ Black Bears
<2018-08-28 Tue 18:05-21:05>
:PROPERTIES:
:ID:       8GkOQMxvImJ69cIZ3iXrEMt-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays @ Black Bears Doubledays @ Black Bears

Follow on MiLB First Pitch  https //stza.co/+xV_8-2i

Shop  https //stza.co/+xV_8-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ Black Bears
END:VALARM
DTSTART:20180828T230500Z
DTEND:20180829T020500Z
UID:8GkOQMxvImJ69cIZ3iXrEMt-@stanza.co
SUMMARY:Doubledays @ Black Bears
DESCRIPTION:Doubledays @ Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xV_8-2i\n\nShop: https://stza.co/+xV_8-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Crosscutters
<2018-08-29 Wed 17:30-20:30>
:PROPERTIES:
:ID:       XQ9SIdaGcAI0hHniRXc9kluP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Crosscutters Doubledays vs. Crosscutters

Follow on MiLB First Pitch  https //stza.co/+xVZ_-2i

Shop  https //stza.co/+xVZ_-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Crosscutters
END:VALARM
DTSTART:20180829T223000Z
DTEND:20180830T013000Z
UID:XQ9SIdaGcAI0hHniRXc9kluP@stanza.co
SUMMARY:Doubledays vs. Crosscutters
DESCRIPTION:Doubledays vs. Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+xVZ_-2i\n\nShop: https://stza.co/+xVZ_-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Crosscutters
<2018-08-30 Thu 17:30-20:30>
:PROPERTIES:
:ID:       FUbk6ZPPqOKu3OFuGbhVZw1Y@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Crosscutters Doubledays vs. Crosscutters

Follow on MiLB First Pitch  https //stza.co/+xV_0-1l

Shop  https //stza.co/+xV_0-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Crosscutters
END:VALARM
DTSTART:20180830T223000Z
DTEND:20180831T013000Z
UID:FUbk6ZPPqOKu3OFuGbhVZw1Y@stanza.co
SUMMARY:Doubledays vs. Crosscutters
DESCRIPTION:Doubledays vs. Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+xV_0-1l\n\nShop: https://stza.co/+xV_0-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays vs. Crosscutters
<2018-08-31 Fri 17:30-20:30>
:PROPERTIES:
:ID:       Id9YOAKhLxCEAq1yvX-3g_3g@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays vs. Crosscutters Doubledays vs. Crosscutters

Follow on MiLB First Pitch  https //stza.co/+xV_1-2P

Shop  https //stza.co/+xV_1-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Doubledays vs. Crosscutters
END:VALARM
DTSTART:20180831T223000Z
DTEND:20180901T013000Z
UID:Id9YOAKhLxCEAq1yvX-3g_3g@stanza.co
SUMMARY:Doubledays vs. Crosscutters
DESCRIPTION:Doubledays vs. Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+xV_1-2P\n\nShop: https://stza.co/+xV_1-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ Muckdogs
<2018-09-01 Sat>--<2018-08-31 Fri>
:PROPERTIES:
:ID:       Yjq5LY6X0ZnrvseNxHrR27Wz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Doubledays @ Muckdogs Doubledays @ Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMgO-t

Shop  https //stza.co/+xMgO-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180901
DTEND;VALUE=DATE:20180901
UID:Yjq5LY6X0ZnrvseNxHrR27Wz@stanza.co
SUMMARY:Doubledays @ Muckdogs
DESCRIPTION:Doubledays @ Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMgO-t\n\nShop: https://stza.co/+xMgO-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ Muckdogs
<2018-09-02 Sun>--<2018-09-01 Sat>
:PROPERTIES:
:ID:       68oop1xX_7Gf97bBfxZgy0i_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays @ Muckdogs Doubledays @ Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMgP-1x

Shop  https //stza.co/+xMgP-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180902
DTEND;VALUE=DATE:20180902
UID:68oop1xX_7Gf97bBfxZgy0i_@stanza.co
SUMMARY:Doubledays @ Muckdogs
DESCRIPTION:Doubledays @ Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMgP-1x\n\nShop: https://stza.co/+xMgP-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Doubledays @ Muckdogs
<2018-09-03 Mon>--<2018-09-02 Sun>
:PROPERTIES:
:ID:       B03hKWFXdJtHvtv75VZjVhij@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Doubledays @ Muckdogs Doubledays @ Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMgQ-3_

Shop  https //stza.co/+xMgQ-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Doubledays @ Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180903
DTEND;VALUE=DATE:20180903
UID:B03hKWFXdJtHvtv75VZjVhij@stanza.co
SUMMARY:Doubledays @ Muckdogs
DESCRIPTION:Doubledays @ Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMgQ-3_\n\nShop: https://stza.co/+xMgQ-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
