#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Senators @ Baysox
<2018-04-05 Thu 17:35-20:35>
:PROPERTIES:
:ID:       f59W7rhaIx4J6u4yk0woSP6j@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Baysox Senators @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vLhf-2b

Shop  https //stza.co/+vLhf-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Baysox
END:VALARM
DTSTART:20180405T223500Z
DTEND:20180406T013500Z
UID:f59W7rhaIx4J6u4yk0woSP6j@stanza.co
SUMMARY:Senators @ Baysox
DESCRIPTION:Senators @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLhf-2b\n\nShop: https://stza.co/+vLhf-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Baysox
<2018-04-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       JrLvgg1Y_v3JQ2kI1DzPwDBP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators @ Baysox Senators @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vLhg-1g

Shop  https //stza.co/+vLhg-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Baysox
END:VALARM
DTSTART:20180406T230500Z
DTEND:20180407T020500Z
UID:JrLvgg1Y_v3JQ2kI1DzPwDBP@stanza.co
SUMMARY:Senators @ Baysox
DESCRIPTION:Senators @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLhg-1g\n\nShop: https://stza.co/+vLhg-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Baysox
<2018-04-07 Sat 12:35-15:35>
:PROPERTIES:
:ID:       aIMO2Q0K82hdhdVuIyls3pq-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Baysox Senators @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vLhh-3d

Shop  https //stza.co/+vLhh-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Baysox
END:VALARM
DTSTART:20180407T173500Z
DTEND:20180407T203500Z
UID:aIMO2Q0K82hdhdVuIyls3pq-@stanza.co
SUMMARY:Senators @ Baysox
DESCRIPTION:Senators @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLhh-3d\n\nShop: https://stza.co/+vLhh-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Baysox
<2018-04-08 Sun 12:35-15:35>
:PROPERTIES:
:ID:       uUwf8dUhmWOCW5TB-VGDZVDl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Baysox Senators @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vLhi-1c

Shop  https //stza.co/+vLhi-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Baysox
END:VALARM
DTSTART:20180408T173500Z
DTEND:20180408T203500Z
UID:uUwf8dUhmWOCW5TB-VGDZVDl@stanza.co
SUMMARY:Senators @ Baysox
DESCRIPTION:Senators @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLhi-1c\n\nShop: https://stza.co/+vLhi-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Curve
<2018-04-09 Mon 17:00-20:00>
:PROPERTIES:
:ID:       Ji3WQvFjG7mw0RF2OkHA2ukv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators @ Curve Senators @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLh3-27

Shop  https //stza.co/+vLh3-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Curve
END:VALARM
DTSTART:20180409T220000Z
DTEND:20180410T010000Z
UID:Ji3WQvFjG7mw0RF2OkHA2ukv@stanza.co
SUMMARY:Senators @ Curve
DESCRIPTION:Senators @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLh3-27\n\nShop: https://stza.co/+vLh3-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Curve
<2018-04-10 Tue 17:00-20:00>
:PROPERTIES:
:ID:       LVqC9DEJOO8rWlqkJd3zKYoT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Curve Senators @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLh4-2W

Shop  https //stza.co/+vLh4-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Curve
END:VALARM
DTSTART:20180410T220000Z
DTEND:20180411T010000Z
UID:LVqC9DEJOO8rWlqkJd3zKYoT@stanza.co
SUMMARY:Senators @ Curve
DESCRIPTION:Senators @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLh4-2W\n\nShop: https://stza.co/+vLh4-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Curve
<2018-04-11 Wed 17:00-20:00>
:PROPERTIES:
:ID:       v5C8dXDZ9vcypcb7vPlcBWBt@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Curve Senators @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLh5-2F

Shop  https //stza.co/+vLh5-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Curve
END:VALARM
DTSTART:20180411T220000Z
DTEND:20180412T010000Z
UID:v5C8dXDZ9vcypcb7vPlcBWBt@stanza.co
SUMMARY:Senators @ Curve
DESCRIPTION:Senators @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLh5-2F\n\nShop: https://stza.co/+vLh5-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Baysox
<2018-04-13 Fri 18:00-21:00>
:PROPERTIES:
:ID:       071qFWPOCW8DjDcWsqgG_t3R@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Senators vs. Baysox Make sure to stick around post-game for the best fireworks in Central PA courtesy of First National Bank! 

Follow on MiLB First Pitch  https //stza.co/+vLhy-1s

Shop  https //stza.co/+vLhy-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Baysox
END:VALARM
DTSTART:20180413T230000Z
DTEND:20180414T020000Z
UID:071qFWPOCW8DjDcWsqgG_t3R@stanza.co
SUMMARY:Senators vs. Baysox
DESCRIPTION:Make sure to stick around post-game for the best fireworks in Central PA courtesy of First National Bank! \n\nFollow on MiLB First Pitch: https://stza.co/+vLhy-1s\n\nShop: https://stza.co/+vLhy-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Baysox
<2018-04-14 Sat 17:00-20:00>
:PROPERTIES:
:ID:       epnkFU87u4w8jsmyfI5C-yQD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators vs. Baysox Senators vs. Baysox

Follow on MiLB First Pitch  https //stza.co/+vLhz-2m

Shop  https //stza.co/+vLhz-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Baysox
END:VALARM
DTSTART:20180414T220000Z
DTEND:20180415T010000Z
UID:epnkFU87u4w8jsmyfI5C-yQD@stanza.co
SUMMARY:Senators vs. Baysox
DESCRIPTION:Senators vs. Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLhz-2m\n\nShop: https://stza.co/+vLhz-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Baysox
<2018-04-15 Sun 12:30-15:30>
:PROPERTIES:
:ID:       pSmM0lvoBSl3B9A_o4Sj_GL_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators vs. Baysox Senators vs. Baysox

Follow on MiLB First Pitch  https //stza.co/+vLhB-2y

Shop  https //stza.co/+vLhB-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Baysox
END:VALARM
DTSTART:20180415T173000Z
DTEND:20180415T203000Z
UID:pSmM0lvoBSl3B9A_o4Sj_GL_@stanza.co
SUMMARY:Senators vs. Baysox
DESCRIPTION:Senators vs. Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLhB-2y\n\nShop: https://stza.co/+vLhB-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Fightin Phils
<2018-04-16 Mon 17:30-20:30>
:PROPERTIES:
:ID:       7OAkYs5cJzaZgVQ9-voD6cjJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators vs. Fightin Phils Senators vs. Fightin Phils

Follow on MiLB First Pitch  https //stza.co/+vLhD-2A

Shop  https //stza.co/+vLhD-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Fightin Phils
END:VALARM
DTSTART:20180416T223000Z
DTEND:20180417T013000Z
UID:7OAkYs5cJzaZgVQ9-voD6cjJ@stanza.co
SUMMARY:Senators vs. Fightin Phils
DESCRIPTION:Senators vs. Fightin Phils\n\nFollow on MiLB First Pitch: https://stza.co/+vLhD-2A\n\nShop: https://stza.co/+vLhD-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Fightin Phils
<2018-04-17 Tue 17:30-20:30>
:PROPERTIES:
:ID:       z5Iy-BepTmdRI6KExX6jgNO2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators vs. Fightin Phils Senators vs. Fightin Phils

Follow on MiLB First Pitch  https //stza.co/+vLhF-2b

Shop  https //stza.co/+vLhF-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Fightin Phils
END:VALARM
DTSTART:20180417T223000Z
DTEND:20180418T013000Z
UID:z5Iy-BepTmdRI6KExX6jgNO2@stanza.co
SUMMARY:Senators vs. Fightin Phils
DESCRIPTION:Senators vs. Fightin Phils\n\nFollow on MiLB First Pitch: https://stza.co/+vLhF-2b\n\nShop: https://stza.co/+vLhF-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Fightin Phils
<2018-04-18 Wed 17:30-20:30>
:PROPERTIES:
:ID:       e1JpReVEc8U-qQ2T7x6DLl7r@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators vs. Fightin Phils Senators vs. Fightin Phils

Follow on MiLB First Pitch  https //stza.co/+vLhH-w

Shop  https //stza.co/+vLhH-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Fightin Phils
END:VALARM
DTSTART:20180418T223000Z
DTEND:20180419T013000Z
UID:e1JpReVEc8U-qQ2T7x6DLl7r@stanza.co
SUMMARY:Senators vs. Fightin Phils
DESCRIPTION:Senators vs. Fightin Phils\n\nFollow on MiLB First Pitch: https://stza.co/+vLhH-w\n\nShop: https://stza.co/+vLhH-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Fightin Phils
<2018-04-19 Thu 11:00-14:00>
:PROPERTIES:
:ID:       e8Z8AqDqzpK0tZ_ZpqbhM4QU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators vs. Fightin Phils Senators vs. Fightin Phils

Follow on MiLB First Pitch  https //stza.co/+vLhJ-i

Shop  https //stza.co/+vLhJ-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Fightin Phils
END:VALARM
DTSTART:20180419T160000Z
DTEND:20180419T190000Z
UID:e8Z8AqDqzpK0tZ_ZpqbhM4QU@stanza.co
SUMMARY:Senators vs. Fightin Phils
DESCRIPTION:Senators vs. Fightin Phils\n\nFollow on MiLB First Pitch: https://stza.co/+vLhJ-i\n\nShop: https://stza.co/+vLhJ-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Yard Goats
<2018-04-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       9ewq1YYwod0MN0vOJTgiye1V@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators @ Yard Goats Senators @ Yard Goats

Buy tickets here  https //stza.co/~vLjJ

Follow on MiLB First Pitch  https //stza.co/+vLjJ-1c

Shop  https //stza.co/+vLjJ-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Yard Goats
END:VALARM
DTSTART:20180420T230500Z
DTEND:20180421T020500Z
UID:9ewq1YYwod0MN0vOJTgiye1V@stanza.co
SUMMARY:Senators @ Yard Goats
DESCRIPTION:Senators @ Yard Goats\n\nBuy tickets here: https://stza.co/~vLjJ\n\nFollow on MiLB First Pitch: https://stza.co/+vLjJ-1c\n\nShop: https://stza.co/+vLjJ-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Yard Goats
<2018-04-21 Sat 17:05-20:05>
:PROPERTIES:
:ID:       H2JVlr_kJ7pWiVRaAanvs-Ie@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Yard Goats Senators @ Yard Goats

Buy tickets here  https //stza.co/~vLjK

Follow on MiLB First Pitch  https //stza.co/+vLjK-1E

Shop  https //stza.co/+vLjK-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Yard Goats
END:VALARM
DTSTART:20180421T220500Z
DTEND:20180422T010500Z
UID:H2JVlr_kJ7pWiVRaAanvs-Ie@stanza.co
SUMMARY:Senators @ Yard Goats
DESCRIPTION:Senators @ Yard Goats\n\nBuy tickets here: https://stza.co/~vLjK\n\nFollow on MiLB First Pitch: https://stza.co/+vLjK-1E\n\nShop: https://stza.co/+vLjK-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Yard Goats
<2018-04-22 Sun 12:05-15:05>
:PROPERTIES:
:ID:       FEhIHnN_IOjQh-HNnqUuXP7c@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Yard Goats Senators @ Yard Goats

Buy tickets here  https //stza.co/~vLjL

Follow on MiLB First Pitch  https //stza.co/+vLjL-3v

Shop  https //stza.co/+vLjL-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Yard Goats
END:VALARM
DTSTART:20180422T170500Z
DTEND:20180422T200500Z
UID:FEhIHnN_IOjQh-HNnqUuXP7c@stanza.co
SUMMARY:Senators @ Yard Goats
DESCRIPTION:Senators @ Yard Goats\n\nBuy tickets here: https://stza.co/~vLjL\n\nFollow on MiLB First Pitch: https://stza.co/+vLjL-3v\n\nShop: https://stza.co/+vLjL-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Thunder
<2018-04-23 Mon 18:00-21:00>
:PROPERTIES:
:ID:       tmGm-7pK3Ma1fgNJyd6lXki3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators @ Thunder Senators @ Thunder

Follow on MiLB First Pitch  https //stza.co/+v8Rq-2r

Shop  https //stza.co/+v8Rq-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Thunder
END:VALARM
DTSTART:20180423T230000Z
DTEND:20180424T020000Z
UID:tmGm-7pK3Ma1fgNJyd6lXki3@stanza.co
SUMMARY:Senators @ Thunder
DESCRIPTION:Senators @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+v8Rq-2r\n\nShop: https://stza.co/+v8Rq-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Thunder
<2018-04-24 Tue 18:00-21:00>
:PROPERTIES:
:ID:       XH6UiCKg1bbrTxERYvpYjfC3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Thunder Senators @ Thunder

Follow on MiLB First Pitch  https //stza.co/+v8Rr-1F

Shop  https //stza.co/+v8Rr-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Thunder
END:VALARM
DTSTART:20180424T230000Z
DTEND:20180425T020000Z
UID:XH6UiCKg1bbrTxERYvpYjfC3@stanza.co
SUMMARY:Senators @ Thunder
DESCRIPTION:Senators @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+v8Rr-1F\n\nShop: https://stza.co/+v8Rr-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Thunder
<2018-04-25 Wed 09:30-12:30>
:PROPERTIES:
:ID:       JzSKfqYsBwElVB85vpOdsGU0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Thunder Senators @ Thunder

Follow on MiLB First Pitch  https //stza.co/+v8Rs-1B

Shop  https //stza.co/+v8Rs-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Thunder
END:VALARM
DTSTART:20180425T143000Z
DTEND:20180425T173000Z
UID:JzSKfqYsBwElVB85vpOdsGU0@stanza.co
SUMMARY:Senators @ Thunder
DESCRIPTION:Senators @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+v8Rs-1B\n\nShop: https://stza.co/+v8Rs-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Curve
<2018-04-27 Fri 18:00-21:00>
:PROPERTIES:
:ID:       kcxshuTe5RYQ_fZNk_rM1w34@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Senators vs. Curve Make sure to stick around post-game for the best fireworks in Central PA courtesy of Harrisburg Mall! 

Follow on MiLB First Pitch  https //stza.co/+vLhL-E

Shop  https //stza.co/+vLhL-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Curve
END:VALARM
DTSTART:20180427T230000Z
DTEND:20180428T020000Z
UID:kcxshuTe5RYQ_fZNk_rM1w34@stanza.co
SUMMARY:Senators vs. Curve
DESCRIPTION:Make sure to stick around post-game for the best fireworks in Central PA courtesy of Harrisburg Mall! \n\nFollow on MiLB First Pitch: https://stza.co/+vLhL-E\n\nShop: https://stza.co/+vLhL-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Curve
<2018-04-28 Sat 17:00-20:00>
:PROPERTIES:
:ID:       Qq_ADglciDwwOf1leEZ6xlRd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators vs. Curve Senators vs. Curve

Follow on MiLB First Pitch  https //stza.co/+vLhO-23

Shop  https //stza.co/+vLhO-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Curve
END:VALARM
DTSTART:20180428T220000Z
DTEND:20180429T010000Z
UID:Qq_ADglciDwwOf1leEZ6xlRd@stanza.co
SUMMARY:Senators vs. Curve
DESCRIPTION:Senators vs. Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLhO-23\n\nShop: https://stza.co/+vLhO-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Curve
<2018-04-29 Sun 12:30-15:30>
:PROPERTIES:
:ID:       S0Gce5v9X1dxeS57_yR5-Om1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators vs. Curve Senators vs. Curve

Follow on MiLB First Pitch  https //stza.co/+vLhQ-3R

Shop  https //stza.co/+vLhQ-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Curve
END:VALARM
DTSTART:20180429T173000Z
DTEND:20180429T203000Z
UID:S0Gce5v9X1dxeS57_yR5-Om1@stanza.co
SUMMARY:Senators vs. Curve
DESCRIPTION:Senators vs. Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLhQ-3R\n\nShop: https://stza.co/+vLhQ-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Yard Goats
<2018-04-30 Mon 17:30-20:30>
:PROPERTIES:
:ID:       xEd2pV9yluhzRG2pfIz6409T@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators vs. Yard Goats Senators vs. Yard Goats

Follow on MiLB First Pitch  https //stza.co/+vLhR-3R

Shop  https //stza.co/+vLhR-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Yard Goats
END:VALARM
DTSTART:20180430T223000Z
DTEND:20180501T013000Z
UID:xEd2pV9yluhzRG2pfIz6409T@stanza.co
SUMMARY:Senators vs. Yard Goats
DESCRIPTION:Senators vs. Yard Goats\n\nFollow on MiLB First Pitch: https://stza.co/+vLhR-3R\n\nShop: https://stza.co/+vLhR-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Yard Goats
<2018-05-01 Tue 17:30-20:30>
:PROPERTIES:
:ID:       0Ryy6iLffRHZmeY5pNPuNaqC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators vs. Yard Goats Senators vs. Yard Goats

Follow on MiLB First Pitch  https //stza.co/+vLhU-1t

Shop  https //stza.co/+vLhU-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Yard Goats
END:VALARM
DTSTART:20180501T223000Z
DTEND:20180502T013000Z
UID:0Ryy6iLffRHZmeY5pNPuNaqC@stanza.co
SUMMARY:Senators vs. Yard Goats
DESCRIPTION:Senators vs. Yard Goats\n\nFollow on MiLB First Pitch: https://stza.co/+vLhU-1t\n\nShop: https://stza.co/+vLhU-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Yard Goats
<2018-05-02 Wed 09:30-12:30>
:PROPERTIES:
:ID:       o91UeEEl2o2gQvKxEWIiDQDN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators vs. Yard Goats Senators vs. Yard Goats

Follow on MiLB First Pitch  https //stza.co/+vLhV-1p

Shop  https //stza.co/+vLhV-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Yard Goats
END:VALARM
DTSTART:20180502T143000Z
DTEND:20180502T173000Z
UID:o91UeEEl2o2gQvKxEWIiDQDN@stanza.co
SUMMARY:Senators vs. Yard Goats
DESCRIPTION:Senators vs. Yard Goats\n\nFollow on MiLB First Pitch: https://stza.co/+vLhV-1p\n\nShop: https://stza.co/+vLhV-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Thunder
<2018-05-03 Thu 18:00-21:00>
:PROPERTIES:
:ID:       WRjeBemzogU6Jq6XGoE7jWfY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Thunder Senators @ Thunder

Follow on MiLB First Pitch  https //stza.co/+v8Rt-20

Shop  https //stza.co/+v8Rt-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Thunder
END:VALARM
DTSTART:20180503T230000Z
DTEND:20180504T020000Z
UID:WRjeBemzogU6Jq6XGoE7jWfY@stanza.co
SUMMARY:Senators @ Thunder
DESCRIPTION:Senators @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+v8Rt-20\n\nShop: https://stza.co/+v8Rt-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Thunder
<2018-05-04 Fri 18:00-21:00>
:PROPERTIES:
:ID:       fdb05s8tJG0v_szGKdjkJJ-q@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators @ Thunder Senators @ Thunder

Follow on MiLB First Pitch  https //stza.co/+v8Ru-R

Shop  https //stza.co/+v8Ru-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Thunder
END:VALARM
DTSTART:20180504T230000Z
DTEND:20180505T020000Z
UID:fdb05s8tJG0v_szGKdjkJJ-q@stanza.co
SUMMARY:Senators @ Thunder
DESCRIPTION:Senators @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+v8Ru-R\n\nShop: https://stza.co/+v8Ru-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Thunder
<2018-05-05 Sat 18:00-21:00>
:PROPERTIES:
:ID:       TcUSTq81OwTJRtXxBTLbpRux@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Thunder Senators @ Thunder

Follow on MiLB First Pitch  https //stza.co/+v8Rv-2b

Shop  https //stza.co/+v8Rv-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Thunder
END:VALARM
DTSTART:20180505T230000Z
DTEND:20180506T020000Z
UID:TcUSTq81OwTJRtXxBTLbpRux@stanza.co
SUMMARY:Senators @ Thunder
DESCRIPTION:Senators @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+v8Rv-2b\n\nShop: https://stza.co/+v8Rv-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Thunder
<2018-05-06 Sun 12:00-15:00>
:PROPERTIES:
:ID:       TfNFETqz0UKku_e2gCa7PdyG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Thunder Senators @ Thunder

Follow on MiLB First Pitch  https //stza.co/+v8Rw-2S

Shop  https //stza.co/+v8Rw-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Thunder
END:VALARM
DTSTART:20180506T170000Z
DTEND:20180506T200000Z
UID:TfNFETqz0UKku_e2gCa7PdyG@stanza.co
SUMMARY:Senators @ Thunder
DESCRIPTION:Senators @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+v8Rw-2S\n\nShop: https://stza.co/+v8Rw-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ SeaWolves
<2018-05-07 Mon 17:05-20:05>
:PROPERTIES:
:ID:       FNvNGlWoBlNKv25SkQS1gO2k@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators @ SeaWolves Senators @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLhr-2f

Shop  https //stza.co/+vLhr-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ SeaWolves
END:VALARM
DTSTART:20180507T220500Z
DTEND:20180508T010500Z
UID:FNvNGlWoBlNKv25SkQS1gO2k@stanza.co
SUMMARY:Senators @ SeaWolves
DESCRIPTION:Senators @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLhr-2f\n\nShop: https://stza.co/+vLhr-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ SeaWolves
<2018-05-08 Tue 17:05-20:05>
:PROPERTIES:
:ID:       xYnkZw3O6FQNeugGV9L7FqTc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ SeaWolves Senators @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLhs-S

Shop  https //stza.co/+vLhs-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ SeaWolves
END:VALARM
DTSTART:20180508T220500Z
DTEND:20180509T010500Z
UID:xYnkZw3O6FQNeugGV9L7FqTc@stanza.co
SUMMARY:Senators @ SeaWolves
DESCRIPTION:Senators @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLhs-S\n\nShop: https://stza.co/+vLhs-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ SeaWolves
<2018-05-09 Wed 10:05-13:05>
:PROPERTIES:
:ID:       nelt6kyWuJZ1L2dtOmSQhZt-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ SeaWolves Senators @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLht-n

Shop  https //stza.co/+vLht-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ SeaWolves
END:VALARM
DTSTART:20180509T150500Z
DTEND:20180509T180500Z
UID:nelt6kyWuJZ1L2dtOmSQhZt-@stanza.co
SUMMARY:Senators @ SeaWolves
DESCRIPTION:Senators @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLht-n\n\nShop: https://stza.co/+vLht-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Fisher Cats
<2018-05-10 Thu 18:00-21:00>
:PROPERTIES:
:ID:       4xVHNky-NBFnpFbDHhBQ8Uxt@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Senators vs. Fisher Cats Make sure to stick around post-game for the best fireworks in Central PA!

Follow on MiLB First Pitch  https //stza.co/+vLhX-3H

Shop  https //stza.co/+vLhX-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Fisher Cats
END:VALARM
DTSTART:20180510T230000Z
DTEND:20180511T020000Z
UID:4xVHNky-NBFnpFbDHhBQ8Uxt@stanza.co
SUMMARY:Senators vs. Fisher Cats
DESCRIPTION:Make sure to stick around post-game for the best fireworks in Central PA!\n\nFollow on MiLB First Pitch: https://stza.co/+vLhX-3H\n\nShop: https://stza.co/+vLhX-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Fisher Cats
<2018-05-11 Fri 18:00-21:00>
:PROPERTIES:
:ID:       A7ojANYCP-FVBlMyPa3S3ucd@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Senators vs. Fisher Cats Make sure to stick around post-game for the best fireworks in Central PA courtesy of PreventSuicide PA!

Follow on MiLB First Pitch  https //stza.co/+vLhZ-2f

Shop  https //stza.co/+vLhZ-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Fisher Cats
END:VALARM
DTSTART:20180511T230000Z
DTEND:20180512T020000Z
UID:A7ojANYCP-FVBlMyPa3S3ucd@stanza.co
SUMMARY:Senators vs. Fisher Cats
DESCRIPTION:Make sure to stick around post-game for the best fireworks in Central PA courtesy of PreventSuicide PA!\n\nFollow on MiLB First Pitch: https://stza.co/+vLhZ-2f\n\nShop: https://stza.co/+vLhZ-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Fisher Cats
<2018-05-12 Sat 17:00-20:00>
:PROPERTIES:
:ID:       1Wux9T-bns8S-rm539GgZP7i@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators vs. Fisher Cats Senators vs. Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLi0-e

Shop  https //stza.co/+vLi0-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Fisher Cats
END:VALARM
DTSTART:20180512T220000Z
DTEND:20180513T010000Z
UID:1Wux9T-bns8S-rm539GgZP7i@stanza.co
SUMMARY:Senators vs. Fisher Cats
DESCRIPTION:Senators vs. Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLi0-e\n\nShop: https://stza.co/+vLi0-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Fisher Cats
<2018-05-13 Sun 12:30-15:30>
:PROPERTIES:
:ID:       AfsCo5g5Hu_8dRBMzDWndfNl@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators vs. Fisher Cats Senators vs. Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLi2-

Shop  https //stza.co/+vLi2-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Fisher Cats
END:VALARM
DTSTART:20180513T173000Z
DTEND:20180513T203000Z
UID:AfsCo5g5Hu_8dRBMzDWndfNl@stanza.co
SUMMARY:Senators vs. Fisher Cats
DESCRIPTION:Senators vs. Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLi2-\n\nShop: https://stza.co/+vLi2-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Baysox
<2018-05-14 Mon 17:35-20:35>
:PROPERTIES:
:ID:       F0VyRfz26MLK3Rfmny6kFuxB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Baysox Senators @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vLhj-32

Shop  https //stza.co/+vLhj-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Baysox
END:VALARM
DTSTART:20180514T223500Z
DTEND:20180515T013500Z
UID:F0VyRfz26MLK3Rfmny6kFuxB@stanza.co
SUMMARY:Senators @ Baysox
DESCRIPTION:Senators @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLhj-32\n\nShop: https://stza.co/+vLhj-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Baysox
<2018-05-15 Tue 17:35-20:35>
:PROPERTIES:
:ID:       nz3ukjZDbH4mvWX0KefKlO27@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators @ Baysox Senators @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vLhk-2Y

Shop  https //stza.co/+vLhk-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Baysox
END:VALARM
DTSTART:20180515T223500Z
DTEND:20180516T013500Z
UID:nz3ukjZDbH4mvWX0KefKlO27@stanza.co
SUMMARY:Senators @ Baysox
DESCRIPTION:Senators @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLhk-2Y\n\nShop: https://stza.co/+vLhk-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Baysox
<2018-05-16 Wed 10:05-13:05>
:PROPERTIES:
:ID:       27uPat8PgZTlZgwUAviBzSrP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Baysox Senators @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vLhl-3U

Shop  https //stza.co/+vLhl-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Baysox
END:VALARM
DTSTART:20180516T150500Z
DTEND:20180516T180500Z
UID:27uPat8PgZTlZgwUAviBzSrP@stanza.co
SUMMARY:Senators @ Baysox
DESCRIPTION:Senators @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLhl-3U\n\nShop: https://stza.co/+vLhl-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Flying Squirrels
<2018-05-17 Thu 17:35-20:35>
:PROPERTIES:
:ID:       8D6Pzgo4nwfVOKhshljYpe0z@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Flying Squirrels Senators @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vLjZ-I

Shop  https //stza.co/+vLjZ-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Flying Squirrels
END:VALARM
DTSTART:20180517T223500Z
DTEND:20180518T013500Z
UID:8D6Pzgo4nwfVOKhshljYpe0z@stanza.co
SUMMARY:Senators @ Flying Squirrels
DESCRIPTION:Senators @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vLjZ-I\n\nShop: https://stza.co/+vLjZ-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Flying Squirrels
<2018-05-18 Fri 18:05-21:05>
:PROPERTIES:
:ID:       2yvdVzZWnR574MrDEMcTKqRQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators @ Flying Squirrels Senators @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+v8Rg-1b

Shop  https //stza.co/+v8Rg-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Flying Squirrels
END:VALARM
DTSTART:20180518T230500Z
DTEND:20180519T020500Z
UID:2yvdVzZWnR574MrDEMcTKqRQ@stanza.co
SUMMARY:Senators @ Flying Squirrels
DESCRIPTION:Senators @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+v8Rg-1b\n\nShop: https://stza.co/+v8Rg-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Flying Squirrels
<2018-05-19 Sat 17:05-20:05>
:PROPERTIES:
:ID:       AuWMlMllu2oWSitB7Udk8Hh9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Flying Squirrels Senators @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+v8Rh-1O

Shop  https //stza.co/+v8Rh-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Flying Squirrels
END:VALARM
DTSTART:20180519T220500Z
DTEND:20180520T010500Z
UID:AuWMlMllu2oWSitB7Udk8Hh9@stanza.co
SUMMARY:Senators @ Flying Squirrels
DESCRIPTION:Senators @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+v8Rh-1O\n\nShop: https://stza.co/+v8Rh-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Flying Squirrels
<2018-05-20 Sun 12:05-15:05>
:PROPERTIES:
:ID:       PxNIPTnnCcCrHMKBEwHC3Nez@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Flying Squirrels Senators @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+v8Ri-T

Shop  https //stza.co/+v8Ri-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Flying Squirrels
END:VALARM
DTSTART:20180520T170500Z
DTEND:20180520T200500Z
UID:PxNIPTnnCcCrHMKBEwHC3Nez@stanza.co
SUMMARY:Senators @ Flying Squirrels
DESCRIPTION:Senators @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+v8Ri-T\n\nShop: https://stza.co/+v8Ri-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. SeaWolves
<2018-05-22 Tue 17:30-20:30>
:PROPERTIES:
:ID:       22-_P63t43I-aW0jkMGcjrre@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators vs. SeaWolves Senators vs. SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLi4-2f

Shop  https //stza.co/+vLi4-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. SeaWolves
END:VALARM
DTSTART:20180522T223000Z
DTEND:20180523T013000Z
UID:22-_P63t43I-aW0jkMGcjrre@stanza.co
SUMMARY:Senators vs. SeaWolves
DESCRIPTION:Senators vs. SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLi4-2f\n\nShop: https://stza.co/+vLi4-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. SeaWolves
<2018-05-23 Wed 17:30-20:30>
:PROPERTIES:
:ID:       s6aIlcMmnMbMMBHXYmu_sHwJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators vs. SeaWolves Senators vs. SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLi5-3Z

Shop  https //stza.co/+vLi5-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. SeaWolves
END:VALARM
DTSTART:20180523T223000Z
DTEND:20180524T013000Z
UID:s6aIlcMmnMbMMBHXYmu_sHwJ@stanza.co
SUMMARY:Senators vs. SeaWolves
DESCRIPTION:Senators vs. SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLi5-3Z\n\nShop: https://stza.co/+vLi5-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. SeaWolves
<2018-05-24 Thu 09:30-12:30>
:PROPERTIES:
:ID:       nFAvzTEMTNB6jlEA1BzR0B2E@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators vs. SeaWolves Senators vs. SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLi7-1i

Shop  https //stza.co/+vLi7-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. SeaWolves
END:VALARM
DTSTART:20180524T143000Z
DTEND:20180524T173000Z
UID:nFAvzTEMTNB6jlEA1BzR0B2E@stanza.co
SUMMARY:Senators vs. SeaWolves
DESCRIPTION:Senators vs. SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLi7-1i\n\nShop: https://stza.co/+vLi7-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Curve
<2018-05-25 Fri 18:00-21:00>
:PROPERTIES:
:ID:       MH-D_9SRb_chUTONGamJC88S@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Senators vs. Curve Make sure to stick around post-game for the best fireworks in Central PA!

Follow on MiLB First Pitch  https //stza.co/+vLia-1G

Shop  https //stza.co/+vLia-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Curve
END:VALARM
DTSTART:20180525T230000Z
DTEND:20180526T020000Z
UID:MH-D_9SRb_chUTONGamJC88S@stanza.co
SUMMARY:Senators vs. Curve
DESCRIPTION:Make sure to stick around post-game for the best fireworks in Central PA!\n\nFollow on MiLB First Pitch: https://stza.co/+vLia-1G\n\nShop: https://stza.co/+vLia-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Curve
<2018-05-26 Sat 17:00-20:00>
:PROPERTIES:
:ID:       W7c7V0Ef8OevX0gNtl36xP4-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators vs. Curve Senators vs. Curve

Follow on MiLB First Pitch  https //stza.co/+vLic-21

Shop  https //stza.co/+vLic-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Curve
END:VALARM
DTSTART:20180526T220000Z
DTEND:20180527T010000Z
UID:W7c7V0Ef8OevX0gNtl36xP4-@stanza.co
SUMMARY:Senators vs. Curve
DESCRIPTION:Senators vs. Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLic-21\n\nShop: https://stza.co/+vLic-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Curve
<2018-05-27 Sun 17:30-20:30>
:PROPERTIES:
:ID:       zESXovhUyOVCQtyF9fCxFlH7@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Senators vs. Curve Make sure to stick around post-game for the best fireworks in Central PA!

Follow on MiLB First Pitch  https //stza.co/+vLid-3h

Shop  https //stza.co/+vLid-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Curve
END:VALARM
DTSTART:20180527T223000Z
DTEND:20180528T013000Z
UID:zESXovhUyOVCQtyF9fCxFlH7@stanza.co
SUMMARY:Senators vs. Curve
DESCRIPTION:Make sure to stick around post-game for the best fireworks in Central PA!\n\nFollow on MiLB First Pitch: https://stza.co/+vLid-3h\n\nShop: https://stza.co/+vLid-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Curve
<2018-05-28 Mon 11:00-14:00>
:PROPERTIES:
:ID:       cZbkjx4vcG4QQpfyE5XnEbV_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators vs. Curve Senators vs. Curve

Follow on MiLB First Pitch  https //stza.co/+vLig-1K

Shop  https //stza.co/+vLig-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Curve
END:VALARM
DTSTART:20180528T160000Z
DTEND:20180528T190000Z
UID:cZbkjx4vcG4QQpfyE5XnEbV_@stanza.co
SUMMARY:Senators vs. Curve
DESCRIPTION:Senators vs. Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLig-1K\n\nShop: https://stza.co/+vLig-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Yard Goats
<2018-05-29 Tue 18:05-21:05>
:PROPERTIES:
:ID:       UkVXE4aZAJlt_MDcMebiClcK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Yard Goats Senators @ Yard Goats

Buy tickets here  https //stza.co/~vLjM

Follow on MiLB First Pitch  https //stza.co/+vLjM-2Z

Shop  https //stza.co/+vLjM-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Yard Goats
END:VALARM
DTSTART:20180529T230500Z
DTEND:20180530T020500Z
UID:UkVXE4aZAJlt_MDcMebiClcK@stanza.co
SUMMARY:Senators @ Yard Goats
DESCRIPTION:Senators @ Yard Goats\n\nBuy tickets here: https://stza.co/~vLjM\n\nFollow on MiLB First Pitch: https://stza.co/+vLjM-2Z\n\nShop: https://stza.co/+vLjM-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Yard Goats
<2018-05-30 Wed 18:05-21:05>
:PROPERTIES:
:ID:       SGTThXJ6yD9yR7LBzVlbU4MS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators @ Yard Goats Senators @ Yard Goats

Buy tickets here  https //stza.co/~vLjN

Follow on MiLB First Pitch  https //stza.co/+vLjN-2L

Shop  https //stza.co/+vLjN-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Yard Goats
END:VALARM
DTSTART:20180530T230500Z
DTEND:20180531T020500Z
UID:SGTThXJ6yD9yR7LBzVlbU4MS@stanza.co
SUMMARY:Senators @ Yard Goats
DESCRIPTION:Senators @ Yard Goats\n\nBuy tickets here: https://stza.co/~vLjN\n\nFollow on MiLB First Pitch: https://stza.co/+vLjN-2L\n\nShop: https://stza.co/+vLjN-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Yard Goats
<2018-05-31 Thu 09:35-12:35>
:PROPERTIES:
:ID:       RdBasJyXebJ8nfnkiyMPIPmH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Yard Goats Senators @ Yard Goats

Buy tickets here  https //stza.co/~vLjO

Follow on MiLB First Pitch  https //stza.co/+vLjO-3o

Shop  https //stza.co/+vLjO-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Yard Goats
END:VALARM
DTSTART:20180531T143500Z
DTEND:20180531T173500Z
UID:RdBasJyXebJ8nfnkiyMPIPmH@stanza.co
SUMMARY:Senators @ Yard Goats
DESCRIPTION:Senators @ Yard Goats\n\nBuy tickets here: https://stza.co/~vLjO\n\nFollow on MiLB First Pitch: https://stza.co/+vLjO-3o\n\nShop: https://stza.co/+vLjO-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Sea Dogs
<2018-06-01 Fri 18:00-21:00>
:PROPERTIES:
:ID:       V7gI0gjxstU9yBCPetJKHsa0@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Senators vs. Sea Dogs Make sure to stick around post-game for the best fireworks in Central PA courtesy of Geisinger Stroke!

Follow on MiLB First Pitch  https //stza.co/+vLii-o

Shop  https //stza.co/+vLii-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Sea Dogs
END:VALARM
DTSTART:20180601T230000Z
DTEND:20180602T020000Z
UID:V7gI0gjxstU9yBCPetJKHsa0@stanza.co
SUMMARY:Senators vs. Sea Dogs
DESCRIPTION:Make sure to stick around post-game for the best fireworks in Central PA courtesy of Geisinger Stroke!\n\nFollow on MiLB First Pitch: https://stza.co/+vLii-o\n\nShop: https://stza.co/+vLii-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Sea Dogs
<2018-06-02 Sat 17:00-20:00>
:PROPERTIES:
:ID:       BXTAFyBCxunn2ITQKB6Bo1-_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators vs. Sea Dogs Senators vs. Sea Dogs

Follow on MiLB First Pitch  https //stza.co/+vLik-3I

Shop  https //stza.co/+vLik-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Sea Dogs
END:VALARM
DTSTART:20180602T220000Z
DTEND:20180603T010000Z
UID:BXTAFyBCxunn2ITQKB6Bo1-_@stanza.co
SUMMARY:Senators vs. Sea Dogs
DESCRIPTION:Senators vs. Sea Dogs\n\nFollow on MiLB First Pitch: https://stza.co/+vLik-3I\n\nShop: https://stza.co/+vLik-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Sea Dogs
<2018-06-03 Sun 14:30-17:30>
:PROPERTIES:
:ID:       V2ODSUpsnexADXA_noeponDQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators vs. Sea Dogs Senators vs. Sea Dogs

Follow on MiLB First Pitch  https //stza.co/+vLim-f

Shop  https //stza.co/+vLim-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Sea Dogs
END:VALARM
DTSTART:20180603T193000Z
DTEND:20180603T223000Z
UID:V2ODSUpsnexADXA_noeponDQ@stanza.co
SUMMARY:Senators vs. Sea Dogs
DESCRIPTION:Senators vs. Sea Dogs\n\nFollow on MiLB First Pitch: https://stza.co/+vLim-f\n\nShop: https://stza.co/+vLim-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Rumble Ponies
<2018-06-05 Tue 17:30-20:30>
:PROPERTIES:
:ID:       DSGx8eF-CRmD2A9mos7gUPOH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators vs. Rumble Ponies Senators vs. Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLio-w

Shop  https //stza.co/+vLio-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Rumble Ponies
END:VALARM
DTSTART:20180605T223000Z
DTEND:20180606T013000Z
UID:DSGx8eF-CRmD2A9mos7gUPOH@stanza.co
SUMMARY:Senators vs. Rumble Ponies
DESCRIPTION:Senators vs. Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLio-w\n\nShop: https://stza.co/+vLio-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Rumble Ponies
<2018-06-06 Wed 17:30-20:30>
:PROPERTIES:
:ID:       uJKw-32BFG8wsEVMgcnmXlIg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators vs. Rumble Ponies Senators vs. Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLip-1F

Shop  https //stza.co/+vLip-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Rumble Ponies
END:VALARM
DTSTART:20180606T223000Z
DTEND:20180607T013000Z
UID:uJKw-32BFG8wsEVMgcnmXlIg@stanza.co
SUMMARY:Senators vs. Rumble Ponies
DESCRIPTION:Senators vs. Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLip-1F\n\nShop: https://stza.co/+vLip-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Rumble Ponies
<2018-06-07 Thu 11:00-14:00>
:PROPERTIES:
:ID:       dEuDl2bMSfK0wcgb1Tu0sLyB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators vs. Rumble Ponies Senators vs. Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLis-J

Shop  https //stza.co/+vLis-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Rumble Ponies
END:VALARM
DTSTART:20180607T160000Z
DTEND:20180607T190000Z
UID:dEuDl2bMSfK0wcgb1Tu0sLyB@stanza.co
SUMMARY:Senators vs. Rumble Ponies
DESCRIPTION:Senators vs. Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLis-J\n\nShop: https://stza.co/+vLis-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Flying Squirrels
<2018-06-08 Fri 18:05-21:05>
:PROPERTIES:
:ID:       YsAU3QM7p1ggPXnQ4IIwrZUj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Flying Squirrels Senators @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+v8Rj-y

Shop  https //stza.co/+v8Rj-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Flying Squirrels
END:VALARM
DTSTART:20180608T230500Z
DTEND:20180609T020500Z
UID:YsAU3QM7p1ggPXnQ4IIwrZUj@stanza.co
SUMMARY:Senators @ Flying Squirrels
DESCRIPTION:Senators @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+v8Rj-y\n\nShop: https://stza.co/+v8Rj-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Flying Squirrels
<2018-06-09 Sat 17:05-20:05>
:PROPERTIES:
:ID:       jkP2JmA6j8CYlhICt-Lbyl37@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Flying Squirrels Senators @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+v8Rk-b

Shop  https //stza.co/+v8Rk-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Flying Squirrels
END:VALARM
DTSTART:20180609T220500Z
DTEND:20180610T010500Z
UID:jkP2JmA6j8CYlhICt-Lbyl37@stanza.co
SUMMARY:Senators @ Flying Squirrels
DESCRIPTION:Senators @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+v8Rk-b\n\nShop: https://stza.co/+v8Rk-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Flying Squirrels
<2018-06-10 Sun 12:05-15:05>
:PROPERTIES:
:ID:       x2B0JRxf1NzjSfcYlCD74B6x@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators @ Flying Squirrels Senators @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+v8Rl-2C

Shop  https //stza.co/+v8Rl-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Flying Squirrels
END:VALARM
DTSTART:20180610T170500Z
DTEND:20180610T200500Z
UID:x2B0JRxf1NzjSfcYlCD74B6x@stanza.co
SUMMARY:Senators @ Flying Squirrels
DESCRIPTION:Senators @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+v8Rl-2C\n\nShop: https://stza.co/+v8Rl-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Fightin Phils
<2018-06-12 Tue 18:05-21:05>
:PROPERTIES:
:ID:       ZZu49JVSpSZg5x7uBliNj82w@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Fightin Phils Senators @ Fightin Phils

Buy tickets here  https //stza.co/~vLjW

Follow on MiLB First Pitch  https //stza.co/+vLjW-Z

Shop  https //stza.co/+vLjW-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Fightin Phils
END:VALARM
DTSTART:20180612T230500Z
DTEND:20180613T020500Z
UID:ZZu49JVSpSZg5x7uBliNj82w@stanza.co
SUMMARY:Senators @ Fightin Phils
DESCRIPTION:Senators @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vLjW\n\nFollow on MiLB First Pitch: https://stza.co/+vLjW-Z\n\nShop: https://stza.co/+vLjW-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Fightin Phils
<2018-06-13 Wed 18:05-21:05>
:PROPERTIES:
:ID:       fXKUv1M7eo5hfTggHWyTTkP-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Fightin Phils Senators @ Fightin Phils

Buy tickets here  https //stza.co/~vLjX

Follow on MiLB First Pitch  https //stza.co/+vLjX-1v

Shop  https //stza.co/+vLjX-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Fightin Phils
END:VALARM
DTSTART:20180613T230500Z
DTEND:20180614T020500Z
UID:fXKUv1M7eo5hfTggHWyTTkP-@stanza.co
SUMMARY:Senators @ Fightin Phils
DESCRIPTION:Senators @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vLjX\n\nFollow on MiLB First Pitch: https://stza.co/+vLjX-1v\n\nShop: https://stza.co/+vLjX-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Fightin Phils
<2018-06-14 Thu 18:05-21:05>
:PROPERTIES:
:ID:       7ZTY4kE7H7gZU_imZue9Hk-P@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators @ Fightin Phils Senators @ Fightin Phils

Buy tickets here  https //stza.co/~vLjY

Follow on MiLB First Pitch  https //stza.co/+vLjY-S

Shop  https //stza.co/+vLjY-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Fightin Phils
END:VALARM
DTSTART:20180614T230500Z
DTEND:20180615T020500Z
UID:7ZTY4kE7H7gZU_imZue9Hk-P@stanza.co
SUMMARY:Senators @ Fightin Phils
DESCRIPTION:Senators @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vLjY\n\nFollow on MiLB First Pitch: https://stza.co/+vLjY-S\n\nShop: https://stza.co/+vLjY-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Flying Squirrels
<2018-06-15 Fri 18:00-21:00>
:PROPERTIES:
:ID:       Be0zRft6VhysW-Nq_6XbC52V@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Senators vs. Flying Squirrels Make sure to stick around post-game for the best fireworks in Central PA courtesy of the PA Prostate Cancer Coalition! 

Follow on MiLB First Pitch  https //stza.co/+vLiu-3G

Shop  https //stza.co/+vLiu-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Flying Squirrels
END:VALARM
DTSTART:20180615T230000Z
DTEND:20180616T020000Z
UID:Be0zRft6VhysW-Nq_6XbC52V@stanza.co
SUMMARY:Senators vs. Flying Squirrels
DESCRIPTION:Make sure to stick around post-game for the best fireworks in Central PA courtesy of the PA Prostate Cancer Coalition! \n\nFollow on MiLB First Pitch: https://stza.co/+vLiu-3G\n\nShop: https://stza.co/+vLiu-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Flying Squirrels
<2018-06-16 Sat 17:00-20:00>
:PROPERTIES:
:ID:       oGh5tesZZZ6XMn7WVuyMSR4z@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators vs. Flying Squirrels Senators vs. Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vLiv-2D

Shop  https //stza.co/+vLiv-2S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Flying Squirrels
END:VALARM
DTSTART:20180616T220000Z
DTEND:20180617T010000Z
UID:oGh5tesZZZ6XMn7WVuyMSR4z@stanza.co
SUMMARY:Senators vs. Flying Squirrels
DESCRIPTION:Senators vs. Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vLiv-2D\n\nShop: https://stza.co/+vLiv-2S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Flying Squirrels
<2018-06-17 Sun 12:30-15:30>
:PROPERTIES:
:ID:       JDB5Dlvh1S5xeZpC6vre4zHd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators vs. Flying Squirrels Senators vs. Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vLix-r

Shop  https //stza.co/+vLix-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Flying Squirrels
END:VALARM
DTSTART:20180617T173000Z
DTEND:20180617T203000Z
UID:JDB5Dlvh1S5xeZpC6vre4zHd@stanza.co
SUMMARY:Senators vs. Flying Squirrels
DESCRIPTION:Senators vs. Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vLix-r\n\nShop: https://stza.co/+vLix-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Baysox
<2018-06-19 Tue 17:30-20:30>
:PROPERTIES:
:ID:       VGekX-ax3-D-VTtFdckjaUJE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators vs. Baysox Senators vs. Baysox

Follow on MiLB First Pitch  https //stza.co/+vLiz-3s

Shop  https //stza.co/+vLiz-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Baysox
END:VALARM
DTSTART:20180619T223000Z
DTEND:20180620T013000Z
UID:VGekX-ax3-D-VTtFdckjaUJE@stanza.co
SUMMARY:Senators vs. Baysox
DESCRIPTION:Senators vs. Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLiz-3s\n\nShop: https://stza.co/+vLiz-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Baysox
<2018-06-20 Wed 11:00-14:00>
:PROPERTIES:
:ID:       u2poOq2jp9itbk1PTs-Nj383@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators vs. Baysox Senators vs. Baysox

Follow on MiLB First Pitch  https //stza.co/+vLiB-2u

Shop  https //stza.co/+vLiB-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Baysox
END:VALARM
DTSTART:20180620T160000Z
DTEND:20180620T190000Z
UID:u2poOq2jp9itbk1PTs-Nj383@stanza.co
SUMMARY:Senators vs. Baysox
DESCRIPTION:Senators vs. Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLiB-2u\n\nShop: https://stza.co/+vLiB-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Baysox
<2018-06-21 Thu 18:00-21:00>
:PROPERTIES:
:ID:       ULF6V6WeqBvFTAvEDBJyEqCZ@stanza.co
:LOCATION: Post-Game Fireworks!
:STATUS:   CONFIRMED
:END:

Senators vs. Baysox Make sure to stick around post-game for the best fireworks in Central PA! 

Follow on MiLB First Pitch  https //stza.co/+vLiE-1b

Shop  https //stza.co/+vLiE-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Baysox
END:VALARM
DTSTART:20180621T230000Z
DTEND:20180622T020000Z
UID:ULF6V6WeqBvFTAvEDBJyEqCZ@stanza.co
SUMMARY:Senators vs. Baysox
DESCRIPTION:Make sure to stick around post-game for the best fireworks in Central PA! \n\nFollow on MiLB First Pitch: https://stza.co/+vLiE-1b\n\nShop: https://stza.co/+vLiE-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Post-Game Fireworks!
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ RubberDucks
<2018-06-22 Fri 18:05-21:05>
:PROPERTIES:
:ID:       HOuRCB2yhXHJfxzljVP-eFtx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ RubberDucks Senators @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLgZ-H

Shop  https //stza.co/+vLgZ-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ RubberDucks
END:VALARM
DTSTART:20180622T230500Z
DTEND:20180623T020500Z
UID:HOuRCB2yhXHJfxzljVP-eFtx@stanza.co
SUMMARY:Senators @ RubberDucks
DESCRIPTION:Senators @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLgZ-H\n\nShop: https://stza.co/+vLgZ-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ RubberDucks
<2018-06-23 Sat 18:05-21:05>
:PROPERTIES:
:ID:       KhFrILJUCrvcivCPx6WTgqIw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators @ RubberDucks Senators @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLg_-c

Shop  https //stza.co/+vLg_-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ RubberDucks
END:VALARM
DTSTART:20180623T230500Z
DTEND:20180624T020500Z
UID:KhFrILJUCrvcivCPx6WTgqIw@stanza.co
SUMMARY:Senators @ RubberDucks
DESCRIPTION:Senators @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLg_-c\n\nShop: https://stza.co/+vLg_-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ RubberDucks
<2018-06-24 Sun 13:05-16:05>
:PROPERTIES:
:ID:       hmTBtpTXM7eKQ11bBHD7W_rm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ RubberDucks Senators @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLg$-1o

Shop  https //stza.co/+vLg$-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ RubberDucks
END:VALARM
DTSTART:20180624T180500Z
DTEND:20180624T210500Z
UID:hmTBtpTXM7eKQ11bBHD7W_rm@stanza.co
SUMMARY:Senators @ RubberDucks
DESCRIPTION:Senators @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLg$-1o\n\nShop: https://stza.co/+vLg$-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Curve
<2018-06-25 Mon 18:00-21:00>
:PROPERTIES:
:ID:       WorVOVE0paKi0L6yThe_-kys@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Curve Senators @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLh6-y

Shop  https //stza.co/+vLh6-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Curve
END:VALARM
DTSTART:20180625T230000Z
DTEND:20180626T020000Z
UID:WorVOVE0paKi0L6yThe_-kys@stanza.co
SUMMARY:Senators @ Curve
DESCRIPTION:Senators @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLh6-y\n\nShop: https://stza.co/+vLh6-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Curve
<2018-06-26 Tue 18:00-21:00>
:PROPERTIES:
:ID:       vj3djcI4F2Mibcxqpu4lRKch@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators @ Curve Senators @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLh7-2g

Shop  https //stza.co/+vLh7-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Curve
END:VALARM
DTSTART:20180626T230000Z
DTEND:20180627T020000Z
UID:vj3djcI4F2Mibcxqpu4lRKch@stanza.co
SUMMARY:Senators @ Curve
DESCRIPTION:Senators @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLh7-2g\n\nShop: https://stza.co/+vLh7-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Curve
<2018-06-27 Wed 18:00-21:00>
:PROPERTIES:
:ID:       _LAsy7MuwEyStZWUlcyzZDz5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Curve Senators @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLh8-3P

Shop  https //stza.co/+vLh8-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Curve
END:VALARM
DTSTART:20180627T230000Z
DTEND:20180628T020000Z
UID:_LAsy7MuwEyStZWUlcyzZDz5@stanza.co
SUMMARY:Senators @ Curve
DESCRIPTION:Senators @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLh8-3P\n\nShop: https://stza.co/+vLh8-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Curve
<2018-06-28 Thu 18:00-21:00>
:PROPERTIES:
:ID:       p7Tc7upYX95wDCCPqRXJDYhE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Curve Senators @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLh9-33

Shop  https //stza.co/+vLh9-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Curve
END:VALARM
DTSTART:20180628T230000Z
DTEND:20180629T020000Z
UID:p7Tc7upYX95wDCCPqRXJDYhE@stanza.co
SUMMARY:Senators @ Curve
DESCRIPTION:Senators @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLh9-33\n\nShop: https://stza.co/+vLh9-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Flying Squirrels
<2018-06-29 Fri 18:00-21:00>
:PROPERTIES:
:ID:       h9mxxKZ_u4lTAfEYDVpcM4En@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Senators vs. Flying Squirrels Make sure to stick around post-game for the best fireworks in Central PA courtesy of PSECU!

Follow on MiLB First Pitch  https //stza.co/+vLiF-2J

Shop  https //stza.co/+vLiF-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Flying Squirrels
END:VALARM
DTSTART:20180629T230000Z
DTEND:20180630T020000Z
UID:h9mxxKZ_u4lTAfEYDVpcM4En@stanza.co
SUMMARY:Senators vs. Flying Squirrels
DESCRIPTION:Make sure to stick around post-game for the best fireworks in Central PA courtesy of PSECU!\n\nFollow on MiLB First Pitch: https://stza.co/+vLiF-2J\n\nShop: https://stza.co/+vLiF-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Flying Squirrels
<2018-06-30 Sat 17:00-20:00>
:PROPERTIES:
:ID:       R7YTmAwBwGOXQDP2j0g6h_0R@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators vs. Flying Squirrels Senators vs. Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vLiI-L

Shop  https //stza.co/+vLiI-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Flying Squirrels
END:VALARM
DTSTART:20180630T220000Z
DTEND:20180701T010000Z
UID:R7YTmAwBwGOXQDP2j0g6h_0R@stanza.co
SUMMARY:Senators vs. Flying Squirrels
DESCRIPTION:Senators vs. Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vLiI-L\n\nShop: https://stza.co/+vLiI-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Flying Squirrels
<2018-07-01 Sun 17:00-20:00>
:PROPERTIES:
:ID:       Q0_knN-UVSqSytksNx2c1QaD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators vs. Flying Squirrels Senators vs. Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vLiK-1p

Shop  https //stza.co/+vLiK-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Flying Squirrels
END:VALARM
DTSTART:20180701T220000Z
DTEND:20180702T010000Z
UID:Q0_knN-UVSqSytksNx2c1QaD@stanza.co
SUMMARY:Senators vs. Flying Squirrels
DESCRIPTION:Senators vs. Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vLiK-1p\n\nShop: https://stza.co/+vLiK-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Flying Squirrels
<2018-07-02 Mon 17:30-20:30>
:PROPERTIES:
:ID:       ZAC-4K9mYBrcVLEelzT9u0zg@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Senators vs. Flying Squirrels Make sure to stick around post-game for the best fireworks in Central PA!

Follow on MiLB First Pitch  https //stza.co/+vLiL-2P

Shop  https //stza.co/+vLiL-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Flying Squirrels
END:VALARM
DTSTART:20180702T223000Z
DTEND:20180703T013000Z
UID:ZAC-4K9mYBrcVLEelzT9u0zg@stanza.co
SUMMARY:Senators vs. Flying Squirrels
DESCRIPTION:Make sure to stick around post-game for the best fireworks in Central PA!\n\nFollow on MiLB First Pitch: https://stza.co/+vLiL-2P\n\nShop: https://stza.co/+vLiL-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Flying Squirrels
<2018-07-03 Tue 17:30-20:30>
:PROPERTIES:
:ID:       IQ0Fk9XFBfVORYQc2a3MZAYB@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Senators vs. Flying Squirrels Make sure to stick around post-game for the best fireworks in Central PA courtesy of PA Lottery!

Follow on MiLB First Pitch  https //stza.co/+vLiO-2T

Shop  https //stza.co/+vLiO-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Flying Squirrels
END:VALARM
DTSTART:20180703T223000Z
DTEND:20180704T013000Z
UID:IQ0Fk9XFBfVORYQc2a3MZAYB@stanza.co
SUMMARY:Senators vs. Flying Squirrels
DESCRIPTION:Make sure to stick around post-game for the best fireworks in Central PA courtesy of PA Lottery!\n\nFollow on MiLB First Pitch: https://stza.co/+vLiO-2T\n\nShop: https://stza.co/+vLiO-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Baysox
<2018-07-04 Wed 17:35-20:35>
:PROPERTIES:
:ID:       KMWy03HCvELVP96xCgr7S35E@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Baysox Senators @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vLhm-10

Shop  https //stza.co/+vLhm-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Baysox
END:VALARM
DTSTART:20180704T223500Z
DTEND:20180705T013500Z
UID:KMWy03HCvELVP96xCgr7S35E@stanza.co
SUMMARY:Senators @ Baysox
DESCRIPTION:Senators @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLhm-10\n\nShop: https://stza.co/+vLhm-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Baysox
<2018-07-05 Thu 18:05-21:05>
:PROPERTIES:
:ID:       DGFBWQltmNXTyEeNse6hh0Rb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators @ Baysox Senators @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vLhn-15

Shop  https //stza.co/+vLhn-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Baysox
END:VALARM
DTSTART:20180705T230500Z
DTEND:20180706T020500Z
UID:DGFBWQltmNXTyEeNse6hh0Rb@stanza.co
SUMMARY:Senators @ Baysox
DESCRIPTION:Senators @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLhn-15\n\nShop: https://stza.co/+vLhn-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Baysox
<2018-07-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       IS8PJrtzSDwXaQmnTYtFPAP4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Baysox Senators @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vLho-2s

Shop  https //stza.co/+vLho-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Baysox
END:VALARM
DTSTART:20180706T230500Z
DTEND:20180707T020500Z
UID:IS8PJrtzSDwXaQmnTYtFPAP4@stanza.co
SUMMARY:Senators @ Baysox
DESCRIPTION:Senators @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLho-2s\n\nShop: https://stza.co/+vLho-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Baysox
<2018-07-07 Sat 17:35-20:35>
:PROPERTIES:
:ID:       oAivZ5INhE4sD7JnKBlXIW6k@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Baysox Senators @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vLhp-2Q

Shop  https //stza.co/+vLhp-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Baysox
END:VALARM
DTSTART:20180707T223500Z
DTEND:20180708T013500Z
UID:oAivZ5INhE4sD7JnKBlXIW6k@stanza.co
SUMMARY:Senators @ Baysox
DESCRIPTION:Senators @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLhp-2Q\n\nShop: https://stza.co/+vLhp-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Baysox
<2018-07-08 Sun 12:35-15:35>
:PROPERTIES:
:ID:       BZo36ccUrNvWecL7CcYx2hEz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators @ Baysox Senators @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vLhq-2t

Shop  https //stza.co/+vLhq-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Baysox
END:VALARM
DTSTART:20180708T173500Z
DTEND:20180708T203500Z
UID:BZo36ccUrNvWecL7CcYx2hEz@stanza.co
SUMMARY:Senators @ Baysox
DESCRIPTION:Senators @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLhq-2t\n\nShop: https://stza.co/+vLhq-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Yard Goats
<2018-07-12 Thu 18:00-21:00>
:PROPERTIES:
:ID:       3BF-Y7nnuN-dK5kmDK_RRmHm@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Senators vs. Yard Goats Make sure to stick around post-game for the best fireworks in Central PA!

Follow on MiLB First Pitch  https //stza.co/+vLiQ-2N

Shop  https //stza.co/+vLiQ-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Yard Goats
END:VALARM
DTSTART:20180712T230000Z
DTEND:20180713T020000Z
UID:3BF-Y7nnuN-dK5kmDK_RRmHm@stanza.co
SUMMARY:Senators vs. Yard Goats
DESCRIPTION:Make sure to stick around post-game for the best fireworks in Central PA!\n\nFollow on MiLB First Pitch: https://stza.co/+vLiQ-2N\n\nShop: https://stza.co/+vLiQ-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Yard Goats
<2018-07-13 Fri 18:00-21:00>
:PROPERTIES:
:ID:       rNTUoW49UDHqdg3pO1rPuf8q@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Senators vs. Yard Goats Make sure to stick around post-game for the best fireworks in Central PA!

Follow on MiLB First Pitch  https //stza.co/+vLiS-2e

Shop  https //stza.co/+vLiS-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Yard Goats
END:VALARM
DTSTART:20180713T230000Z
DTEND:20180714T020000Z
UID:rNTUoW49UDHqdg3pO1rPuf8q@stanza.co
SUMMARY:Senators vs. Yard Goats
DESCRIPTION:Make sure to stick around post-game for the best fireworks in Central PA!\n\nFollow on MiLB First Pitch: https://stza.co/+vLiS-2e\n\nShop: https://stza.co/+vLiS-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Yard Goats
<2018-07-14 Sat 17:00-20:00>
:PROPERTIES:
:ID:       ApyjkDmjYFPRV0hVHZk0l1dM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators vs. Yard Goats Senators vs. Yard Goats

Follow on MiLB First Pitch  https //stza.co/+vLiT-2B

Shop  https //stza.co/+vLiT-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Yard Goats
END:VALARM
DTSTART:20180714T220000Z
DTEND:20180715T010000Z
UID:ApyjkDmjYFPRV0hVHZk0l1dM@stanza.co
SUMMARY:Senators vs. Yard Goats
DESCRIPTION:Senators vs. Yard Goats\n\nFollow on MiLB First Pitch: https://stza.co/+vLiT-2B\n\nShop: https://stza.co/+vLiT-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Yard Goats
<2018-07-15 Sun 12:30-15:30>
:PROPERTIES:
:ID:       p81_xXWcp5oaEswzdqIsJ2KL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators vs. Yard Goats Senators vs. Yard Goats

Follow on MiLB First Pitch  https //stza.co/+vLiV-28

Shop  https //stza.co/+vLiV-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Yard Goats
END:VALARM
DTSTART:20180715T173000Z
DTEND:20180715T203000Z
UID:p81_xXWcp5oaEswzdqIsJ2KL@stanza.co
SUMMARY:Senators vs. Yard Goats
DESCRIPTION:Senators vs. Yard Goats\n\nFollow on MiLB First Pitch: https://stza.co/+vLiV-28\n\nShop: https://stza.co/+vLiV-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. RubberDucks
<2018-07-16 Mon 17:30-20:30>
:PROPERTIES:
:ID:       7F78sPvoKCDO_5c6jV1nrTWp@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators vs. RubberDucks Senators vs. RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLiX-2e

Shop  https //stza.co/+vLiX-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. RubberDucks
END:VALARM
DTSTART:20180716T223000Z
DTEND:20180717T013000Z
UID:7F78sPvoKCDO_5c6jV1nrTWp@stanza.co
SUMMARY:Senators vs. RubberDucks
DESCRIPTION:Senators vs. RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLiX-2e\n\nShop: https://stza.co/+vLiX-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. RubberDucks
<2018-07-17 Tue 17:30-20:30>
:PROPERTIES:
:ID:       pCVFMkTyWPXReavWSs91hp-M@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators vs. RubberDucks Senators vs. RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLiZ-2Z

Shop  https //stza.co/+vLiZ-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. RubberDucks
END:VALARM
DTSTART:20180717T223000Z
DTEND:20180718T013000Z
UID:pCVFMkTyWPXReavWSs91hp-M@stanza.co
SUMMARY:Senators vs. RubberDucks
DESCRIPTION:Senators vs. RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLiZ-2Z\n\nShop: https://stza.co/+vLiZ-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. RubberDucks
<2018-07-18 Wed 11:00-14:00>
:PROPERTIES:
:ID:       gVDf-Yk1LdD9GeNXE9mzCNG7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators vs. RubberDucks Senators vs. RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLj0-d

Shop  https //stza.co/+vLj0-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. RubberDucks
END:VALARM
DTSTART:20180718T160000Z
DTEND:20180718T190000Z
UID:gVDf-Yk1LdD9GeNXE9mzCNG7@stanza.co
SUMMARY:Senators vs. RubberDucks
DESCRIPTION:Senators vs. RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLj0-d\n\nShop: https://stza.co/+vLj0-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Fisher Cats
<2018-07-19 Thu 18:05-21:05>
:PROPERTIES:
:ID:       ksSaRJS_c3409V_Ba0stvDvr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators @ Fisher Cats Senators @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLjP-2U

Shop  https //stza.co/+vLjP-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Fisher Cats
END:VALARM
DTSTART:20180719T230500Z
DTEND:20180720T020500Z
UID:ksSaRJS_c3409V_Ba0stvDvr@stanza.co
SUMMARY:Senators @ Fisher Cats
DESCRIPTION:Senators @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLjP-2U\n\nShop: https://stza.co/+vLjP-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Fisher Cats
<2018-07-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       Jz_8cs5FS2rPX6sL21e-Dbqe@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Fisher Cats Senators @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLjQ-k

Shop  https //stza.co/+vLjQ-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Fisher Cats
END:VALARM
DTSTART:20180720T230500Z
DTEND:20180721T020500Z
UID:Jz_8cs5FS2rPX6sL21e-Dbqe@stanza.co
SUMMARY:Senators @ Fisher Cats
DESCRIPTION:Senators @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLjQ-k\n\nShop: https://stza.co/+vLjQ-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Fisher Cats
<2018-07-21 Sat 18:05-21:05>
:PROPERTIES:
:ID:       h2UcRCqAlG-cHHWsqOw90wNA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Fisher Cats Senators @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLjR-3L

Shop  https //stza.co/+vLjR-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Fisher Cats
END:VALARM
DTSTART:20180721T230500Z
DTEND:20180722T020500Z
UID:h2UcRCqAlG-cHHWsqOw90wNA@stanza.co
SUMMARY:Senators @ Fisher Cats
DESCRIPTION:Senators @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLjR-3L\n\nShop: https://stza.co/+vLjR-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Fisher Cats
<2018-07-22 Sun 12:35-15:35>
:PROPERTIES:
:ID:       JPdAZqL1xPsYq41Rx-TBiQ1W@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators @ Fisher Cats Senators @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLjS-2V

Shop  https //stza.co/+vLjS-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Fisher Cats
END:VALARM
DTSTART:20180722T173500Z
DTEND:20180722T203500Z
UID:JPdAZqL1xPsYq41Rx-TBiQ1W@stanza.co
SUMMARY:Senators @ Fisher Cats
DESCRIPTION:Senators @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLjS-2V\n\nShop: https://stza.co/+vLjS-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Sea Dogs
<2018-07-23 Mon 18:00-21:00>
:PROPERTIES:
:ID:       k5jCUG5e0kHoMapSkXxoJh9w@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Sea Dogs Senators @ Sea Dogs

Buy tickets here  https //stza.co/~vLjT

Follow on MiLB First Pitch  https //stza.co/+vLjT-2F

Shop  https //stza.co/+vLjT-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Sea Dogs
END:VALARM
DTSTART:20180723T230000Z
DTEND:20180724T020000Z
UID:k5jCUG5e0kHoMapSkXxoJh9w@stanza.co
SUMMARY:Senators @ Sea Dogs
DESCRIPTION:Senators @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vLjT\n\nFollow on MiLB First Pitch: https://stza.co/+vLjT-2F\n\nShop: https://stza.co/+vLjT-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Sea Dogs
<2018-07-24 Tue 18:00-21:00>
:PROPERTIES:
:ID:       2103b403KrSiPnh5UkI5P94-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Sea Dogs Senators @ Sea Dogs

Buy tickets here  https //stza.co/~vLjU

Follow on MiLB First Pitch  https //stza.co/+vLjU-2H

Shop  https //stza.co/+vLjU-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Sea Dogs
END:VALARM
DTSTART:20180724T230000Z
DTEND:20180725T020000Z
UID:2103b403KrSiPnh5UkI5P94-@stanza.co
SUMMARY:Senators @ Sea Dogs
DESCRIPTION:Senators @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vLjU\n\nFollow on MiLB First Pitch: https://stza.co/+vLjU-2H\n\nShop: https://stza.co/+vLjU-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Sea Dogs
<2018-07-25 Wed 11:00-14:00>
:PROPERTIES:
:ID:       9vSQiIjo4eQzSlsOvv60iAOc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators @ Sea Dogs Senators @ Sea Dogs

Buy tickets here  https //stza.co/~vLjV

Follow on MiLB First Pitch  https //stza.co/+vLjV-1X

Shop  https //stza.co/+vLjV-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Sea Dogs
END:VALARM
DTSTART:20180725T160000Z
DTEND:20180725T190000Z
UID:9vSQiIjo4eQzSlsOvv60iAOc@stanza.co
SUMMARY:Senators @ Sea Dogs
DESCRIPTION:Senators @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vLjV\n\nFollow on MiLB First Pitch: https://stza.co/+vLjV-1X\n\nShop: https://stza.co/+vLjV-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Baysox
<2018-07-26 Thu 18:00-21:00>
:PROPERTIES:
:ID:       Wxoa1StlRRP5Wrg01KBk2Qxs@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Senators vs. Baysox Make sure to stick around post-game for the best fireworks in Central PA!

Follow on MiLB First Pitch  https //stza.co/+vLj2-2o

Shop  https //stza.co/+vLj2-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Baysox
END:VALARM
DTSTART:20180726T230000Z
DTEND:20180727T020000Z
UID:Wxoa1StlRRP5Wrg01KBk2Qxs@stanza.co
SUMMARY:Senators vs. Baysox
DESCRIPTION:Make sure to stick around post-game for the best fireworks in Central PA!\n\nFollow on MiLB First Pitch: https://stza.co/+vLj2-2o\n\nShop: https://stza.co/+vLj2-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Baysox
<2018-07-27 Fri 18:00-21:00>
:PROPERTIES:
:ID:       82B-txddbhfBP2XsuqyZ9OrN@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Senators vs. Baysox Make sure to stick around post-game for the best fireworks in Central PA!

Follow on MiLB First Pitch  https //stza.co/+vLj3-w

Shop  https //stza.co/+vLj3-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Baysox
END:VALARM
DTSTART:20180727T230000Z
DTEND:20180728T020000Z
UID:82B-txddbhfBP2XsuqyZ9OrN@stanza.co
SUMMARY:Senators vs. Baysox
DESCRIPTION:Make sure to stick around post-game for the best fireworks in Central PA!\n\nFollow on MiLB First Pitch: https://stza.co/+vLj3-w\n\nShop: https://stza.co/+vLj3-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Baysox
<2018-07-28 Sat 17:00-20:00>
:PROPERTIES:
:ID:       CQztmpyUqDVRZXwuYUTNvuZe@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Senators vs. Baysox Make sure to stick around post-game for the best fireworks in Central PA!

Follow on MiLB First Pitch  https //stza.co/+vLj6-2$

Shop  https //stza.co/+vLj6-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Baysox
END:VALARM
DTSTART:20180728T220000Z
DTEND:20180729T010000Z
UID:CQztmpyUqDVRZXwuYUTNvuZe@stanza.co
SUMMARY:Senators vs. Baysox
DESCRIPTION:Make sure to stick around post-game for the best fireworks in Central PA!\n\nFollow on MiLB First Pitch: https://stza.co/+vLj6-2$\n\nShop: https://stza.co/+vLj6-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Baysox
<2018-07-29 Sun 17:00-20:00>
:PROPERTIES:
:ID:       Dwcwp8SKCPayq06qBXmVEWFo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators vs. Baysox Senators vs. Baysox

Follow on MiLB First Pitch  https //stza.co/+vLj8-2N

Shop  https //stza.co/+vLj8-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Baysox
END:VALARM
DTSTART:20180729T220000Z
DTEND:20180730T010000Z
UID:Dwcwp8SKCPayq06qBXmVEWFo@stanza.co
SUMMARY:Senators vs. Baysox
DESCRIPTION:Senators vs. Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLj8-2N\n\nShop: https://stza.co/+vLj8-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Curve
<2018-07-31 Tue 17:30-20:30>
:PROPERTIES:
:ID:       S59ibT3NqqjxyWJOmjJDxNSq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators vs. Curve Senators vs. Curve

Follow on MiLB First Pitch  https //stza.co/+vLja-14

Shop  https //stza.co/+vLja-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Curve
END:VALARM
DTSTART:20180731T223000Z
DTEND:20180801T013000Z
UID:S59ibT3NqqjxyWJOmjJDxNSq@stanza.co
SUMMARY:Senators vs. Curve
DESCRIPTION:Senators vs. Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLja-14\n\nShop: https://stza.co/+vLja-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Curve
<2018-08-01 Wed 17:30-20:30>
:PROPERTIES:
:ID:       GMwdaYHsRXAPo0csSbHPIjm9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators vs. Curve Senators vs. Curve

Follow on MiLB First Pitch  https //stza.co/+vLjc-q

Shop  https //stza.co/+vLjc-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Curve
END:VALARM
DTSTART:20180801T223000Z
DTEND:20180802T013000Z
UID:GMwdaYHsRXAPo0csSbHPIjm9@stanza.co
SUMMARY:Senators vs. Curve
DESCRIPTION:Senators vs. Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLjc-q\n\nShop: https://stza.co/+vLjc-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Curve
<2018-08-02 Thu 18:00-21:00>
:PROPERTIES:
:ID:       Z5Tl_Y0N_O6g979okOSSFiU_@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Senators vs. Curve Make sure to stick around post-game for the best fireworks in Central PA!

Follow on MiLB First Pitch  https //stza.co/+vLje-f

Shop  https //stza.co/+vLje-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Curve
END:VALARM
DTSTART:20180802T230000Z
DTEND:20180803T020000Z
UID:Z5Tl_Y0N_O6g979okOSSFiU_@stanza.co
SUMMARY:Senators vs. Curve
DESCRIPTION:Make sure to stick around post-game for the best fireworks in Central PA!\n\nFollow on MiLB First Pitch: https://stza.co/+vLje-f\n\nShop: https://stza.co/+vLje-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Rumble Ponies
<2018-08-03 Fri 18:05-21:05>
:PROPERTIES:
:ID:       Xnr-Hh3e5WP0N-Ep4_bp8SNn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Rumble Ponies Senators @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLhc-1Z

Shop  https //stza.co/+vLhc-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Rumble Ponies
END:VALARM
DTSTART:20180803T230500Z
DTEND:20180804T020500Z
UID:Xnr-Hh3e5WP0N-Ep4_bp8SNn@stanza.co
SUMMARY:Senators @ Rumble Ponies
DESCRIPTION:Senators @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLhc-1Z\n\nShop: https://stza.co/+vLhc-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Rumble Ponies
<2018-08-04 Sat 17:05-20:05>
:PROPERTIES:
:ID:       2mUZO4HuSLxTSNc95l54REmK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Rumble Ponies Senators @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLhd-2l

Shop  https //stza.co/+vLhd-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Rumble Ponies
END:VALARM
DTSTART:20180804T220500Z
DTEND:20180805T010500Z
UID:2mUZO4HuSLxTSNc95l54REmK@stanza.co
SUMMARY:Senators @ Rumble Ponies
DESCRIPTION:Senators @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLhd-2l\n\nShop: https://stza.co/+vLhd-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Rumble Ponies
<2018-08-05 Sun 13:05-16:05>
:PROPERTIES:
:ID:       eWUu_2j0rKJH4QlbWQub_KtE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators @ Rumble Ponies Senators @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLhe-35

Shop  https //stza.co/+vLhe-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Rumble Ponies
END:VALARM
DTSTART:20180805T180500Z
DTEND:20180805T210500Z
UID:eWUu_2j0rKJH4QlbWQub_KtE@stanza.co
SUMMARY:Senators @ Rumble Ponies
DESCRIPTION:Senators @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLhe-35\n\nShop: https://stza.co/+vLhe-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Yard Goats
<2018-08-07 Tue 17:30-20:30>
:PROPERTIES:
:ID:       g-j1hX0Qc2tgL8C53U05JE-0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators vs. Yard Goats Senators vs. Yard Goats

Follow on MiLB First Pitch  https //stza.co/+vLjf-3P

Shop  https //stza.co/+vLjf-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Yard Goats
END:VALARM
DTSTART:20180807T223000Z
DTEND:20180808T013000Z
UID:g-j1hX0Qc2tgL8C53U05JE-0@stanza.co
SUMMARY:Senators vs. Yard Goats
DESCRIPTION:Senators vs. Yard Goats\n\nFollow on MiLB First Pitch: https://stza.co/+vLjf-3P\n\nShop: https://stza.co/+vLjf-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Yard Goats
<2018-08-08 Wed 17:30-20:30>
:PROPERTIES:
:ID:       cpYHvIfCOYH4PcyXZbu0e0VA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators vs. Yard Goats Senators vs. Yard Goats

Follow on MiLB First Pitch  https //stza.co/+vLji-2t

Shop  https //stza.co/+vLji-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Yard Goats
END:VALARM
DTSTART:20180808T223000Z
DTEND:20180809T013000Z
UID:cpYHvIfCOYH4PcyXZbu0e0VA@stanza.co
SUMMARY:Senators vs. Yard Goats
DESCRIPTION:Senators vs. Yard Goats\n\nFollow on MiLB First Pitch: https://stza.co/+vLji-2t\n\nShop: https://stza.co/+vLji-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Yard Goats
<2018-08-09 Thu 18:00-21:00>
:PROPERTIES:
:ID:       Jyvtb3XJ-OpI_AOQx-_fM8Hl@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Senators vs. Yard Goats Make sure to stick around post-game for the best fireworks in Central PA!

Follow on MiLB First Pitch  https //stza.co/+vLjj-1B

Shop  https //stza.co/+vLjj-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Yard Goats
END:VALARM
DTSTART:20180809T230000Z
DTEND:20180810T020000Z
UID:Jyvtb3XJ-OpI_AOQx-_fM8Hl@stanza.co
SUMMARY:Senators vs. Yard Goats
DESCRIPTION:Make sure to stick around post-game for the best fireworks in Central PA!\n\nFollow on MiLB First Pitch: https://stza.co/+vLjj-1B\n\nShop: https://stza.co/+vLjj-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Thunder
<2018-08-10 Fri 18:00-21:00>
:PROPERTIES:
:ID:       GrlCbk03aR7nBR7iSxH6Pb73@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Senators vs. Thunder Make sure to stick around post-game for the best fireworks in Central PA!

Follow on MiLB First Pitch  https //stza.co/+vLjm-z

Shop  https //stza.co/+vLjm-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Thunder
END:VALARM
DTSTART:20180810T230000Z
DTEND:20180811T020000Z
UID:GrlCbk03aR7nBR7iSxH6Pb73@stanza.co
SUMMARY:Senators vs. Thunder
DESCRIPTION:Make sure to stick around post-game for the best fireworks in Central PA!\n\nFollow on MiLB First Pitch: https://stza.co/+vLjm-z\n\nShop: https://stza.co/+vLjm-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Thunder
<2018-08-11 Sat 17:00-20:00>
:PROPERTIES:
:ID:       td6jPkRgAMb8peMrGiY134Gs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators vs. Thunder Senators vs. Thunder

Follow on MiLB First Pitch  https //stza.co/+vLjn-1Y

Shop  https //stza.co/+vLjn-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Thunder
END:VALARM
DTSTART:20180811T220000Z
DTEND:20180812T010000Z
UID:td6jPkRgAMb8peMrGiY134Gs@stanza.co
SUMMARY:Senators vs. Thunder
DESCRIPTION:Senators vs. Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vLjn-1Y\n\nShop: https://stza.co/+vLjn-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Thunder
<2018-08-12 Sun 12:30-15:30>
:PROPERTIES:
:ID:       c7AHUC07ebWRHkj8_BHEwYL4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators vs. Thunder Senators vs. Thunder

Follow on MiLB First Pitch  https //stza.co/+vLjp-v

Shop  https //stza.co/+vLjp-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Thunder
END:VALARM
DTSTART:20180812T173000Z
DTEND:20180812T203000Z
UID:c7AHUC07ebWRHkj8_BHEwYL4@stanza.co
SUMMARY:Senators vs. Thunder
DESCRIPTION:Senators vs. Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vLjp-v\n\nShop: https://stza.co/+vLjp-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ SeaWolves
<2018-08-13 Mon 18:05-21:05>
:PROPERTIES:
:ID:       NmDf9osWtbBuCzpAZKXQ5Er6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ SeaWolves Senators @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLhu-s

Shop  https //stza.co/+vLhu-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ SeaWolves
END:VALARM
DTSTART:20180813T230500Z
DTEND:20180814T020500Z
UID:NmDf9osWtbBuCzpAZKXQ5Er6@stanza.co
SUMMARY:Senators @ SeaWolves
DESCRIPTION:Senators @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLhu-s\n\nShop: https://stza.co/+vLhu-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ SeaWolves
<2018-08-14 Tue 18:05-21:05>
:PROPERTIES:
:ID:       y6TYsPtZn7hjgAcGm5hLtWme@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators @ SeaWolves Senators @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLhv-2Q

Shop  https //stza.co/+vLhv-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ SeaWolves
END:VALARM
DTSTART:20180814T230500Z
DTEND:20180815T020500Z
UID:y6TYsPtZn7hjgAcGm5hLtWme@stanza.co
SUMMARY:Senators @ SeaWolves
DESCRIPTION:Senators @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLhv-2Q\n\nShop: https://stza.co/+vLhv-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ SeaWolves
<2018-08-15 Wed 18:05-21:05>
:PROPERTIES:
:ID:       GevWecxC6wghhv0gGUfzhN_-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ SeaWolves Senators @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLhw-e

Shop  https //stza.co/+vLhw-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ SeaWolves
END:VALARM
DTSTART:20180815T230500Z
DTEND:20180816T020500Z
UID:GevWecxC6wghhv0gGUfzhN_-@stanza.co
SUMMARY:Senators @ SeaWolves
DESCRIPTION:Senators @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLhw-e\n\nShop: https://stza.co/+vLhw-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. RubberDucks
<2018-08-17 Fri 18:00-21:00>
:PROPERTIES:
:ID:       HMhzquQxMAngSsPwqRPYY3zN@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Senators vs. RubberDucks Make sure to stick around post-game for the best fireworks in Central PA courtesy of PSECU!

Follow on MiLB First Pitch  https //stza.co/+vLjs-3x

Shop  https //stza.co/+vLjs-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. RubberDucks
END:VALARM
DTSTART:20180817T230000Z
DTEND:20180818T020000Z
UID:HMhzquQxMAngSsPwqRPYY3zN@stanza.co
SUMMARY:Senators vs. RubberDucks
DESCRIPTION:Make sure to stick around post-game for the best fireworks in Central PA courtesy of PSECU!\n\nFollow on MiLB First Pitch: https://stza.co/+vLjs-3x\n\nShop: https://stza.co/+vLjs-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. RubberDucks
<2018-08-18 Sat 17:00-20:00>
:PROPERTIES:
:ID:       7rDk3BQP6yhVs9wqaFdyHBF5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators vs. RubberDucks Senators vs. RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLju-28

Shop  https //stza.co/+vLju-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. RubberDucks
END:VALARM
DTSTART:20180818T220000Z
DTEND:20180819T010000Z
UID:7rDk3BQP6yhVs9wqaFdyHBF5@stanza.co
SUMMARY:Senators vs. RubberDucks
DESCRIPTION:Senators vs. RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLju-28\n\nShop: https://stza.co/+vLju-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. RubberDucks
<2018-08-19 Sun 12:30-15:30>
:PROPERTIES:
:ID:       mxIbiq1MxYShYsSMxtpF6OI_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators vs. RubberDucks Senators vs. RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLjv-3C

Shop  https //stza.co/+vLjv-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. RubberDucks
END:VALARM
DTSTART:20180819T173000Z
DTEND:20180819T203000Z
UID:mxIbiq1MxYShYsSMxtpF6OI_@stanza.co
SUMMARY:Senators vs. RubberDucks
DESCRIPTION:Senators vs. RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLjv-3C\n\nShop: https://stza.co/+vLjv-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Fightin Phils
<2018-08-20 Mon 17:30-20:30>
:PROPERTIES:
:ID:       fuSgqYpEokp2d5TPhavMI8GU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators vs. Fightin Phils Senators vs. Fightin Phils

Follow on MiLB First Pitch  https //stza.co/+vLjy-Q

Shop  https //stza.co/+vLjy-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Fightin Phils
END:VALARM
DTSTART:20180820T223000Z
DTEND:20180821T013000Z
UID:fuSgqYpEokp2d5TPhavMI8GU@stanza.co
SUMMARY:Senators vs. Fightin Phils
DESCRIPTION:Senators vs. Fightin Phils\n\nFollow on MiLB First Pitch: https://stza.co/+vLjy-Q\n\nShop: https://stza.co/+vLjy-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. Fightin Phils
<2018-08-21 Tue 17:30-20:30>
:PROPERTIES:
:ID:       P9vCClr5CNInT_XqCnxJI-ys@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators vs. Fightin Phils Senators vs. Fightin Phils

Follow on MiLB First Pitch  https //stza.co/+vLjz-1m

Shop  https //stza.co/+vLjz-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. Fightin Phils
END:VALARM
DTSTART:20180821T223000Z
DTEND:20180822T013000Z
UID:P9vCClr5CNInT_XqCnxJI-ys@stanza.co
SUMMARY:Senators vs. Fightin Phils
DESCRIPTION:Senators vs. Fightin Phils\n\nFollow on MiLB First Pitch: https://stza.co/+vLjz-1m\n\nShop: https://stza.co/+vLjz-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Curve
<2018-08-22 Wed 17:00-20:00>
:PROPERTIES:
:ID:       HjpM3czgTOawvlwPfykI6CIf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators @ Curve Senators @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLha-3E

Shop  https //stza.co/+vLha-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Curve
END:VALARM
DTSTART:20180822T220000Z
DTEND:20180823T010000Z
UID:HjpM3czgTOawvlwPfykI6CIf@stanza.co
SUMMARY:Senators @ Curve
DESCRIPTION:Senators @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLha-3E\n\nShop: https://stza.co/+vLha-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Curve
<2018-08-23 Thu 17:00-20:00>
:PROPERTIES:
:ID:       hAG8FfhW6esR8tycz5mJa4GE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Curve Senators @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLhb-2V

Shop  https //stza.co/+vLhb-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Curve
END:VALARM
DTSTART:20180823T220000Z
DTEND:20180824T010000Z
UID:hAG8FfhW6esR8tycz5mJa4GE@stanza.co
SUMMARY:Senators @ Curve
DESCRIPTION:Senators @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLhb-2V\n\nShop: https://stza.co/+vLhb-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ RubberDucks
<2018-08-24 Fri 18:05-21:05>
:PROPERTIES:
:ID:       g6lY1kgMH-euOgfG6nEsRco2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ RubberDucks Senators @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLh0-A

Shop  https //stza.co/+vLh0-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ RubberDucks
END:VALARM
DTSTART:20180824T230500Z
DTEND:20180825T020500Z
UID:g6lY1kgMH-euOgfG6nEsRco2@stanza.co
SUMMARY:Senators @ RubberDucks
DESCRIPTION:Senators @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLh0-A\n\nShop: https://stza.co/+vLh0-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ RubberDucks
<2018-08-25 Sat 18:05-21:05>
:PROPERTIES:
:ID:       F91ozPbP6jxckur5kQNOgITM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators @ RubberDucks Senators @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLh1-2D

Shop  https //stza.co/+vLh1-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ RubberDucks
END:VALARM
DTSTART:20180825T230500Z
DTEND:20180826T020500Z
UID:F91ozPbP6jxckur5kQNOgITM@stanza.co
SUMMARY:Senators @ RubberDucks
DESCRIPTION:Senators @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLh1-2D\n\nShop: https://stza.co/+vLh1-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ RubberDucks
<2018-08-26 Sun 13:05-16:05>
:PROPERTIES:
:ID:       jA4lvZY8hdH4T3IBAOk_7vMc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ RubberDucks Senators @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLh2-3x

Shop  https //stza.co/+vLh2-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ RubberDucks
END:VALARM
DTSTART:20180826T180500Z
DTEND:20180826T210500Z
UID:jA4lvZY8hdH4T3IBAOk_7vMc@stanza.co
SUMMARY:Senators @ RubberDucks
DESCRIPTION:Senators @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLh2-3x\n\nShop: https://stza.co/+vLh2-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. SeaWolves
<2018-08-27 Mon 17:30-20:30>
:PROPERTIES:
:ID:       -8EgOS74kFxwRfyxv-_-jaga@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators vs. SeaWolves Senators vs. SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLjC-1g

Shop  https //stza.co/+vLjC-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. SeaWolves
END:VALARM
DTSTART:20180827T223000Z
DTEND:20180828T013000Z
UID:-8EgOS74kFxwRfyxv-_-jaga@stanza.co
SUMMARY:Senators vs. SeaWolves
DESCRIPTION:Senators vs. SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLjC-1g\n\nShop: https://stza.co/+vLjC-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. SeaWolves
<2018-08-28 Tue 17:30-20:30>
:PROPERTIES:
:ID:       jkWWyJwbP2IJ_otpOeICA3hf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators vs. SeaWolves Senators vs. SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLjE-5

Shop  https //stza.co/+vLjE-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. SeaWolves
END:VALARM
DTSTART:20180828T223000Z
DTEND:20180829T013000Z
UID:jkWWyJwbP2IJ_otpOeICA3hf@stanza.co
SUMMARY:Senators vs. SeaWolves
DESCRIPTION:Senators vs. SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLjE-5\n\nShop: https://stza.co/+vLjE-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. SeaWolves
<2018-08-29 Wed 17:30-20:30>
:PROPERTIES:
:ID:       _i5ymTR1r090A7HpUu8ShwL0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators vs. SeaWolves Senators vs. SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLjF-x

Shop  https //stza.co/+vLjF-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. SeaWolves
END:VALARM
DTSTART:20180829T223000Z
DTEND:20180830T013000Z
UID:_i5ymTR1r090A7HpUu8ShwL0@stanza.co
SUMMARY:Senators vs. SeaWolves
DESCRIPTION:Senators vs. SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLjF-x\n\nShop: https://stza.co/+vLjF-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators vs. SeaWolves
<2018-08-30 Thu 18:00-21:00>
:PROPERTIES:
:ID:       pOC61wFyCP6aZhm5sZ21GDHV@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Senators vs. SeaWolves Make sure to stick around post-game for the best fireworks in Central PA!

Follow on MiLB First Pitch  https //stza.co/+vLjI-2n

Shop  https //stza.co/+vLjI-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Senators vs. SeaWolves
END:VALARM
DTSTART:20180830T230000Z
DTEND:20180831T020000Z
UID:pOC61wFyCP6aZhm5sZ21GDHV@stanza.co
SUMMARY:Senators vs. SeaWolves
DESCRIPTION:Make sure to stick around post-game for the best fireworks in Central PA!\n\nFollow on MiLB First Pitch: https://stza.co/+vLjI-2n\n\nShop: https://stza.co/+vLjI-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Flying Squirrels
<2018-08-31 Fri 18:05-21:05>
:PROPERTIES:
:ID:       Xv5hnqhoG-OeyO_0-uVCjvQE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Flying Squirrels Senators @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+v8Rm-3F

Shop  https //stza.co/+v8Rm-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Flying Squirrels
END:VALARM
DTSTART:20180831T230500Z
DTEND:20180901T020500Z
UID:Xv5hnqhoG-OeyO_0-uVCjvQE@stanza.co
SUMMARY:Senators @ Flying Squirrels
DESCRIPTION:Senators @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+v8Rm-3F\n\nShop: https://stza.co/+v8Rm-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Flying Squirrels
<2018-09-01 Sat 17:05-20:05>
:PROPERTIES:
:ID:       C_WXw54P81E_aWYeGFjJhA8y@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Senators @ Flying Squirrels Senators @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+v8Rn-2z

Shop  https //stza.co/+v8Rn-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Flying Squirrels
END:VALARM
DTSTART:20180901T220500Z
DTEND:20180902T010500Z
UID:C_WXw54P81E_aWYeGFjJhA8y@stanza.co
SUMMARY:Senators @ Flying Squirrels
DESCRIPTION:Senators @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+v8Rn-2z\n\nShop: https://stza.co/+v8Rn-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Flying Squirrels
<2018-09-02 Sun 17:05-20:05>
:PROPERTIES:
:ID:       R8sL1-UMh7ohLtPrqz2Va2q1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Flying Squirrels Senators @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+v8Ro-1l

Shop  https //stza.co/+v8Ro-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Flying Squirrels
END:VALARM
DTSTART:20180902T220500Z
DTEND:20180903T010500Z
UID:R8sL1-UMh7ohLtPrqz2Va2q1@stanza.co
SUMMARY:Senators @ Flying Squirrels
DESCRIPTION:Senators @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+v8Ro-1l\n\nShop: https://stza.co/+v8Ro-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Senators @ Flying Squirrels
<2018-09-03 Mon 12:05-15:05>
:PROPERTIES:
:ID:       OrXxBbI-jyAzThMUKVMj4JEx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Senators @ Flying Squirrels Senators @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+v8Rp-32

Shop  https //stza.co/+v8Rp-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Senators @ Flying Squirrels
END:VALARM
DTSTART:20180903T170500Z
DTEND:20180903T200500Z
UID:OrXxBbI-jyAzThMUKVMj4JEx@stanza.co
SUMMARY:Senators @ Flying Squirrels
DESCRIPTION:Senators @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+v8Rp-32\n\nShop: https://stza.co/+v8Rp-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
