#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Tides vs. Orioles
<2018-03-26 Mon 14:05-17:05>
:PROPERTIES:
:ID:       BGKrsjTuIshTmLkY0GpD41E5@stanza.co
:LOCATION: Orioles vs Tides Exhibition Game
:STATUS:   CONFIRMED
:END:

Tides vs. Orioles The Tides and Baltimore Orioles will play an exhibition game at Harbor Park on Monday, March 26th at 3 05 pm. Tickets will go on sale to the general public on March 3rd at 10 00 am, with box seats $25 and reserved seats $22. Season ticket holders and advertisers may contact the Tides front office to purchase tickets in advance of the March 3rd on-sale date.

Follow on MiLB First Pitch  https //stza.co/+xONE-3G

Shop  https //stza.co/+xONE-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Orioles
END:VALARM
DTSTART:20180326T190500Z
DTEND:20180326T220500Z
UID:BGKrsjTuIshTmLkY0GpD41E5@stanza.co
SUMMARY:Tides vs. Orioles
DESCRIPTION:The Tides and Baltimore Orioles will play an exhibition game at Harbor Park on Monday, March 26th at 3:05 pm. Tickets will go on sale to the general public on March 3rd at 10:00 am, with box seats $25 and reserved seats $22. Season ticket holders and advertisers may contact the Tides front office to purchase tickets in advance of the March 3rd on-sale date.\n\nFollow on MiLB First Pitch: https://stza.co/+xONE-3G\n\nShop: https://stza.co/+xONE-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Orioles vs Tides Exhibition Game
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Stripers
<2018-04-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       -mEwJMD8FePklBXAQSOk0sIQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Stripers Tides vs. Stripers

Follow on MiLB First Pitch  https //stza.co/+uYuV-1h

Shop  https //stza.co/+uYuV-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Stripers
END:VALARM
DTSTART:20180406T230500Z
DTEND:20180407T020500Z
UID:-mEwJMD8FePklBXAQSOk0sIQ@stanza.co
SUMMARY:Tides vs. Stripers
DESCRIPTION:Tides vs. Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+uYuV-1h\n\nShop: https://stza.co/+uYuV-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Stripers
<2018-04-07 Sat 18:05-21:05>
:PROPERTIES:
:ID:       L0qLqE0Z-zjBDmH968tkLiTY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides vs. Stripers Tides vs. Stripers

Follow on MiLB First Pitch  https //stza.co/+uYvk-1E

Shop  https //stza.co/+uYvk-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Stripers
END:VALARM
DTSTART:20180407T230500Z
DTEND:20180408T020500Z
UID:L0qLqE0Z-zjBDmH968tkLiTY@stanza.co
SUMMARY:Tides vs. Stripers
DESCRIPTION:Tides vs. Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+uYvk-1E\n\nShop: https://stza.co/+uYvk-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Stripers
<2018-04-08 Sun 12:05-15:05>
:PROPERTIES:
:ID:       ZECgQ8_o6SaO72rIx8fJaViI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Stripers Tides vs. Stripers

Follow on MiLB First Pitch  https //stza.co/+uYvD-r

Shop  https //stza.co/+uYvD-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Stripers
END:VALARM
DTSTART:20180408T170500Z
DTEND:20180408T200500Z
UID:ZECgQ8_o6SaO72rIx8fJaViI@stanza.co
SUMMARY:Tides vs. Stripers
DESCRIPTION:Tides vs. Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+uYvD-r\n\nShop: https://stza.co/+uYvD-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Knights
<2018-04-09 Mon 17:35-20:35>
:PROPERTIES:
:ID:       H0xy5ylk37qCDQ9EBnAnOIhn@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Knights Tides vs. Knights

Follow on MiLB First Pitch  https //stza.co/+uYw0-1q

Shop  https //stza.co/+uYw0-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Knights
END:VALARM
DTSTART:20180409T223500Z
DTEND:20180410T013500Z
UID:H0xy5ylk37qCDQ9EBnAnOIhn@stanza.co
SUMMARY:Tides vs. Knights
DESCRIPTION:Tides vs. Knights\n\nFollow on MiLB First Pitch: https://stza.co/+uYw0-1q\n\nShop: https://stza.co/+uYw0-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Knights
<2018-04-10 Tue 17:35-20:35>
:PROPERTIES:
:ID:       YxtlZid7CXF-tXfWjIcy5b1L@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides vs. Knights Tides vs. Knights

Follow on MiLB First Pitch  https //stza.co/+uYwn-g

Shop  https //stza.co/+uYwn-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Knights
END:VALARM
DTSTART:20180410T223500Z
DTEND:20180411T013500Z
UID:YxtlZid7CXF-tXfWjIcy5b1L@stanza.co
SUMMARY:Tides vs. Knights
DESCRIPTION:Tides vs. Knights\n\nFollow on MiLB First Pitch: https://stza.co/+uYwn-g\n\nShop: https://stza.co/+uYwn-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Knights
<2018-04-11 Wed 11:05-14:05>
:PROPERTIES:
:ID:       yMLVIcUVM_HSk7l86OYsKgor@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Knights Tides vs. Knights

Follow on MiLB First Pitch  https //stza.co/+uYwF-l

Shop  https //stza.co/+uYwF-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Knights
END:VALARM
DTSTART:20180411T160500Z
DTEND:20180411T190500Z
UID:yMLVIcUVM_HSk7l86OYsKgor@stanza.co
SUMMARY:Tides vs. Knights
DESCRIPTION:Tides vs. Knights\n\nFollow on MiLB First Pitch: https://stza.co/+uYwF-l\n\nShop: https://stza.co/+uYwF-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Chiefs
<2018-04-12 Thu 13:05-16:05>
:PROPERTIES:
:ID:       IXzPm8odlNfMkPeF0MY0lBIr@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Chiefs Tides @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+vKhP-2p

Shop  https //stza.co/+vKhP-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Chiefs
END:VALARM
DTSTART:20180412T180500Z
DTEND:20180412T210500Z
UID:IXzPm8odlNfMkPeF0MY0lBIr@stanza.co
SUMMARY:Tides @ Chiefs
DESCRIPTION:Tides @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+vKhP-2p\n\nShop: https://stza.co/+vKhP-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Chiefs
<2018-04-13 Fri 12:05-15:05>
:PROPERTIES:
:ID:       iQbIV__Ac8geouzbuQOUgB15@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides @ Chiefs Tides @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+y4zN-2B

Shop  https //stza.co/+y4zN-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Chiefs
END:VALARM
DTSTART:20180413T170500Z
DTEND:20180413T200500Z
UID:iQbIV__Ac8geouzbuQOUgB15@stanza.co
SUMMARY:Tides @ Chiefs
DESCRIPTION:Tides @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+y4zN-2B\n\nShop: https://stza.co/+y4zN-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Chiefs
<2018-04-14 Sat 12:05-15:05>
:PROPERTIES:
:ID:       nEZRLkYvT33PEX8wwPCK6OSf@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Chiefs Tides @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+vKhR-12

Shop  https //stza.co/+vKhR-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Chiefs
END:VALARM
DTSTART:20180414T170500Z
DTEND:20180414T200500Z
UID:nEZRLkYvT33PEX8wwPCK6OSf@stanza.co
SUMMARY:Tides @ Chiefs
DESCRIPTION:Tides @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+vKhR-12\n\nShop: https://stza.co/+vKhR-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Chiefs
<2018-04-15 Sun 12:05-15:05>
:PROPERTIES:
:ID:       qgR8A-m7D94vDT4DeSmIYt4Q@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Chiefs Tides @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+vKhS-12

Shop  https //stza.co/+vKhS-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Chiefs
END:VALARM
DTSTART:20180415T170500Z
DTEND:20180415T200500Z
UID:qgR8A-m7D94vDT4DeSmIYt4Q@stanza.co
SUMMARY:Tides @ Chiefs
DESCRIPTION:Tides @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+vKhS-12\n\nShop: https://stza.co/+vKhS-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ IronPigs
<2018-04-16 Mon 18:05-21:05>
:PROPERTIES:
:ID:       -70_7Kxd_BsrOvkPOVqf3G7P@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides @ IronPigs Tides @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+uYt5-1Y

Shop  https //stza.co/+uYt5-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ IronPigs
END:VALARM
DTSTART:20180416T230500Z
DTEND:20180417T020500Z
UID:-70_7Kxd_BsrOvkPOVqf3G7P@stanza.co
SUMMARY:Tides @ IronPigs
DESCRIPTION:Tides @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+uYt5-1Y\n\nShop: https://stza.co/+uYt5-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ IronPigs
<2018-04-17 Tue 18:05-21:05>
:PROPERTIES:
:ID:       eVm98MuTECIAALejx_gq7OPM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ IronPigs Tides @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+uYtr-31

Shop  https //stza.co/+uYtr-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ IronPigs
END:VALARM
DTSTART:20180417T230500Z
DTEND:20180418T020500Z
UID:eVm98MuTECIAALejx_gq7OPM@stanza.co
SUMMARY:Tides @ IronPigs
DESCRIPTION:Tides @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+uYtr-31\n\nShop: https://stza.co/+uYtr-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ IronPigs
<2018-04-18 Wed 18:05-21:05>
:PROPERTIES:
:ID:       _3TJd6xS1LVlJY0C-4Y44gga@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ IronPigs Tides @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+uYtM-3O

Shop  https //stza.co/+uYtM-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ IronPigs
END:VALARM
DTSTART:20180418T230500Z
DTEND:20180419T020500Z
UID:_3TJd6xS1LVlJY0C-4Y44gga@stanza.co
SUMMARY:Tides @ IronPigs
DESCRIPTION:Tides @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+uYtM-3O\n\nShop: https://stza.co/+uYtM-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Bisons
<2018-04-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       mtNvKW05ODkPaAHbVUwuWQWJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides vs. Bisons Tides vs. Bisons

Follow on MiLB First Pitch  https //stza.co/+uYx0-1T

Shop  https //stza.co/+uYx0-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Bisons
END:VALARM
DTSTART:20180420T230500Z
DTEND:20180421T020500Z
UID:mtNvKW05ODkPaAHbVUwuWQWJ@stanza.co
SUMMARY:Tides vs. Bisons
DESCRIPTION:Tides vs. Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+uYx0-1T\n\nShop: https://stza.co/+uYx0-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Bisons
<2018-04-21 Sat 18:05-21:05>
:PROPERTIES:
:ID:       koBiITzhUALucYFy-lmk_KaL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Bisons Tides vs. Bisons

Follow on MiLB First Pitch  https //stza.co/+uYxg-2l

Shop  https //stza.co/+uYxg-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Bisons
END:VALARM
DTSTART:20180421T230500Z
DTEND:20180422T020500Z
UID:koBiITzhUALucYFy-lmk_KaL@stanza.co
SUMMARY:Tides vs. Bisons
DESCRIPTION:Tides vs. Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+uYxg-2l\n\nShop: https://stza.co/+uYxg-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Bisons
<2018-04-22 Sun 12:05-15:05>
:PROPERTIES:
:ID:       h0llMmbMC5JKMK_DEqIwt8E3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Bisons Tides vs. Bisons

Follow on MiLB First Pitch  https //stza.co/+uYxD-K

Shop  https //stza.co/+uYxD-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Bisons
END:VALARM
DTSTART:20180422T170500Z
DTEND:20180422T200500Z
UID:h0llMmbMC5JKMK_DEqIwt8E3@stanza.co
SUMMARY:Tides vs. Bisons
DESCRIPTION:Tides vs. Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+uYxD-K\n\nShop: https://stza.co/+uYxD-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. IronPigs
<2018-04-23 Mon 17:35-20:35>
:PROPERTIES:
:ID:       eMeA7tTI2E_KdjHlaXT-hTEX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides vs. IronPigs Tides vs. IronPigs

Follow on MiLB First Pitch  https //stza.co/+uYxY-3n

Shop  https //stza.co/+uYxY-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. IronPigs
END:VALARM
DTSTART:20180423T223500Z
DTEND:20180424T013500Z
UID:eMeA7tTI2E_KdjHlaXT-hTEX@stanza.co
SUMMARY:Tides vs. IronPigs
DESCRIPTION:Tides vs. IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+uYxY-3n\n\nShop: https://stza.co/+uYxY-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. IronPigs
<2018-04-24 Tue 17:35-20:35>
:PROPERTIES:
:ID:       LZxSVYgwigg6dcCvBc-74mRL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. IronPigs Tides vs. IronPigs

Follow on MiLB First Pitch  https //stza.co/+uYyf-1

Shop  https //stza.co/+uYyf-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. IronPigs
END:VALARM
DTSTART:20180424T223500Z
DTEND:20180425T013500Z
UID:LZxSVYgwigg6dcCvBc-74mRL@stanza.co
SUMMARY:Tides vs. IronPigs
DESCRIPTION:Tides vs. IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+uYyf-1\n\nShop: https://stza.co/+uYyf-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. IronPigs
<2018-04-25 Wed 11:05-14:05>
:PROPERTIES:
:ID:       4hDGO6Tuwyt60ybx5_G3NP4L@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. IronPigs Tides vs. IronPigs

Follow on MiLB First Pitch  https //stza.co/+uYyG-v

Shop  https //stza.co/+uYyG-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. IronPigs
END:VALARM
DTSTART:20180425T160500Z
DTEND:20180425T190500Z
UID:4hDGO6Tuwyt60ybx5_G3NP4L@stanza.co
SUMMARY:Tides vs. IronPigs
DESCRIPTION:Tides vs. IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+uYyG-v\n\nShop: https://stza.co/+uYyG-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Knights
<2018-04-27 Fri 18:04-21:04>
:PROPERTIES:
:ID:       n-QXbbz3-NDvc5oSlslbq9em@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides @ Knights Tides @ Knights

Follow on MiLB First Pitch  https //stza.co/+xONt-1t

Shop  https //stza.co/+xONt-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Knights
END:VALARM
DTSTART:20180427T230400Z
DTEND:20180428T020400Z
UID:n-QXbbz3-NDvc5oSlslbq9em@stanza.co
SUMMARY:Tides @ Knights
DESCRIPTION:Tides @ Knights\n\nFollow on MiLB First Pitch: https://stza.co/+xONt-1t\n\nShop: https://stza.co/+xONt-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Knights
<2018-04-28 Sat 18:04-21:04>
:PROPERTIES:
:ID:       PLkg0e0EiDoi_ZTXrADbTzaQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Knights Tides @ Knights

Follow on MiLB First Pitch  https //stza.co/+xONu-3I

Shop  https //stza.co/+xONu-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Knights
END:VALARM
DTSTART:20180428T230400Z
DTEND:20180429T020400Z
UID:PLkg0e0EiDoi_ZTXrADbTzaQ@stanza.co
SUMMARY:Tides @ Knights
DESCRIPTION:Tides @ Knights\n\nFollow on MiLB First Pitch: https://stza.co/+xONu-3I\n\nShop: https://stza.co/+xONu-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Knights
<2018-04-29 Sun 13:05-16:05>
:PROPERTIES:
:ID:       kx2bZ4gip5EaspFpXR8o7jrh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Knights Tides @ Knights

Follow on MiLB First Pitch  https //stza.co/+uYin-1k

Shop  https //stza.co/+uYin-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Knights
END:VALARM
DTSTART:20180429T180500Z
DTEND:20180429T210500Z
UID:kx2bZ4gip5EaspFpXR8o7jrh@stanza.co
SUMMARY:Tides @ Knights
DESCRIPTION:Tides @ Knights\n\nFollow on MiLB First Pitch: https://stza.co/+uYin-1k\n\nShop: https://stza.co/+uYin-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Bulls
<2018-04-30 Mon 17:35-20:35>
:PROPERTIES:
:ID:       HKTr5wmSsX6UzJkRYw1IALM7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides vs. Bulls Tides vs. Bulls

Follow on MiLB First Pitch  https //stza.co/+uYyV-3b

Shop  https //stza.co/+uYyV-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Bulls
END:VALARM
DTSTART:20180430T223500Z
DTEND:20180501T013500Z
UID:HKTr5wmSsX6UzJkRYw1IALM7@stanza.co
SUMMARY:Tides vs. Bulls
DESCRIPTION:Tides vs. Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+uYyV-3b\n\nShop: https://stza.co/+uYyV-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Bulls
<2018-05-01 Tue 17:35-20:35>
:PROPERTIES:
:ID:       WqQBlQp27XFYKqPPQRdhMMSP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Bulls Tides vs. Bulls

Follow on MiLB First Pitch  https //stza.co/+uYzr-B

Shop  https //stza.co/+uYzr-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Bulls
END:VALARM
DTSTART:20180501T223500Z
DTEND:20180502T013500Z
UID:WqQBlQp27XFYKqPPQRdhMMSP@stanza.co
SUMMARY:Tides vs. Bulls
DESCRIPTION:Tides vs. Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+uYzr-B\n\nShop: https://stza.co/+uYzr-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Bulls
<2018-05-02 Wed 17:35-20:35>
:PROPERTIES:
:ID:       DXC139-ykZt03hWa6lkE7f2m@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Bulls Tides vs. Bulls

Follow on MiLB First Pitch  https //stza.co/+uYzH-37

Shop  https //stza.co/+uYzH-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Bulls
END:VALARM
DTSTART:20180502T223500Z
DTEND:20180503T013500Z
UID:DXC139-ykZt03hWa6lkE7f2m@stanza.co
SUMMARY:Tides vs. Bulls
DESCRIPTION:Tides vs. Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+uYzH-37\n\nShop: https://stza.co/+uYzH-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Bats
<2018-05-03 Thu 17:35-20:35>
:PROPERTIES:
:ID:       9AUJCHwgt0vRfTt-yZJnYIiG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides vs. Bats Tides vs. Bats

Follow on MiLB First Pitch  https //stza.co/+uYA8-3q

Shop  https //stza.co/+uYA8-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Bats
END:VALARM
DTSTART:20180503T223500Z
DTEND:20180504T013500Z
UID:9AUJCHwgt0vRfTt-yZJnYIiG@stanza.co
SUMMARY:Tides vs. Bats
DESCRIPTION:Tides vs. Bats\n\nFollow on MiLB First Pitch: https://stza.co/+uYA8-3q\n\nShop: https://stza.co/+uYA8-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Bats
<2018-05-04 Fri 18:05-21:05>
:PROPERTIES:
:ID:       oOYXlG0lrAi5i57WGq01Inh0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Bats Tides vs. Bats

Follow on MiLB First Pitch  https //stza.co/+uYAx-2r

Shop  https //stza.co/+uYAx-3_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Bats
END:VALARM
DTSTART:20180504T230500Z
DTEND:20180505T020500Z
UID:oOYXlG0lrAi5i57WGq01Inh0@stanza.co
SUMMARY:Tides vs. Bats
DESCRIPTION:Tides vs. Bats\n\nFollow on MiLB First Pitch: https://stza.co/+uYAx-2r\n\nShop: https://stza.co/+uYAx-3_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Bats
<2018-05-05 Sat 18:05-21:05>
:PROPERTIES:
:ID:       fNLZNaN0KoM8o-7QH-PuKPqa@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Bats Tides vs. Bats

Follow on MiLB First Pitch  https //stza.co/+uYAV-3I

Shop  https //stza.co/+uYAV-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Bats
END:VALARM
DTSTART:20180505T230500Z
DTEND:20180506T020500Z
UID:fNLZNaN0KoM8o-7QH-PuKPqa@stanza.co
SUMMARY:Tides vs. Bats
DESCRIPTION:Tides vs. Bats\n\nFollow on MiLB First Pitch: https://stza.co/+uYAV-3I\n\nShop: https://stza.co/+uYAV-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Bats
<2018-05-06 Sun 12:05-15:05>
:PROPERTIES:
:ID:       _h98jv-HPxqyACp07HLbws3M@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides vs. Bats Tides vs. Bats

Follow on MiLB First Pitch  https //stza.co/+uYB5-1t

Shop  https //stza.co/+uYB5-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Bats
END:VALARM
DTSTART:20180506T170500Z
DTEND:20180506T200500Z
UID:_h98jv-HPxqyACp07HLbws3M@stanza.co
SUMMARY:Tides vs. Bats
DESCRIPTION:Tides vs. Bats\n\nFollow on MiLB First Pitch: https://stza.co/+uYB5-1t\n\nShop: https://stza.co/+uYB5-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Bulls
<2018-05-07 Mon 18:05-21:05>
:PROPERTIES:
:ID:       ciYOeuAY3yw8xCfX53u0JdE4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Bulls Tides @ Bulls

Follow on MiLB First Pitch  https //stza.co/+uYlF-3a

Shop  https //stza.co/+uYlF-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Bulls
END:VALARM
DTSTART:20180507T230500Z
DTEND:20180508T020500Z
UID:ciYOeuAY3yw8xCfX53u0JdE4@stanza.co
SUMMARY:Tides @ Bulls
DESCRIPTION:Tides @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+uYlF-3a\n\nShop: https://stza.co/+uYlF-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Bulls
<2018-05-08 Tue 09:35-12:35>
:PROPERTIES:
:ID:       YxHk8JHSyO0rWwedaq8lbc5A@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Bulls Tides @ Bulls

Follow on MiLB First Pitch  https //stza.co/+uYl_-P

Shop  https //stza.co/+uYl_-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Bulls
END:VALARM
DTSTART:20180508T143500Z
DTEND:20180508T173500Z
UID:YxHk8JHSyO0rWwedaq8lbc5A@stanza.co
SUMMARY:Tides @ Bulls
DESCRIPTION:Tides @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+uYl_-P\n\nShop: https://stza.co/+uYl_-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Bulls
<2018-05-09 Wed 18:05-21:05>
:PROPERTIES:
:ID:       Ff5_5Hjs-T9M3SatwyW6NB89@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides @ Bulls Tides @ Bulls

Follow on MiLB First Pitch  https //stza.co/+uYmf-a

Shop  https //stza.co/+uYmf-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Bulls
END:VALARM
DTSTART:20180509T230500Z
DTEND:20180510T020500Z
UID:Ff5_5Hjs-T9M3SatwyW6NB89@stanza.co
SUMMARY:Tides @ Bulls
DESCRIPTION:Tides @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+uYmf-a\n\nShop: https://stza.co/+uYmf-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Bulls
<2018-05-10 Thu 18:05-21:05>
:PROPERTIES:
:ID:       EeUXKBRDjfPzFgkqyM5d7plj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Bulls Tides @ Bulls

Follow on MiLB First Pitch  https //stza.co/+uYmE-k

Shop  https //stza.co/+uYmE-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Bulls
END:VALARM
DTSTART:20180510T230500Z
DTEND:20180511T020500Z
UID:EeUXKBRDjfPzFgkqyM5d7plj@stanza.co
SUMMARY:Tides @ Bulls
DESCRIPTION:Tides @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+uYmE-k\n\nShop: https://stza.co/+uYmE-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Stripers
<2018-05-11 Fri 18:05-21:05>
:PROPERTIES:
:ID:       o-SziNfbs2aV1v-M10ttoTXi@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Stripers Tides @ Stripers

Follow on MiLB First Pitch  https //stza.co/+uYoZ-1I

Shop  https //stza.co/+uYoZ-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Stripers
END:VALARM
DTSTART:20180511T230500Z
DTEND:20180512T020500Z
UID:o-SziNfbs2aV1v-M10ttoTXi@stanza.co
SUMMARY:Tides @ Stripers
DESCRIPTION:Tides @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+uYoZ-1I\n\nShop: https://stza.co/+uYoZ-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Stripers
<2018-05-12 Sat 17:05-20:05>
:PROPERTIES:
:ID:       LJXOPaorYbmfMi3iCfqTqL3H@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides @ Stripers Tides @ Stripers

Follow on MiLB First Pitch  https //stza.co/+uYpd-1$

Shop  https //stza.co/+uYpd-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Stripers
END:VALARM
DTSTART:20180512T220500Z
DTEND:20180513T010500Z
UID:LJXOPaorYbmfMi3iCfqTqL3H@stanza.co
SUMMARY:Tides @ Stripers
DESCRIPTION:Tides @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+uYpd-1$\n\nShop: https://stza.co/+uYpd-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Stripers
<2018-05-13 Sun 12:05-15:05>
:PROPERTIES:
:ID:       jt5DcryyS4q32LZ67yc9Pn6n@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Stripers Tides @ Stripers

Follow on MiLB First Pitch  https //stza.co/+uYpw-1n

Shop  https //stza.co/+uYpw-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Stripers
END:VALARM
DTSTART:20180513T170500Z
DTEND:20180513T200500Z
UID:jt5DcryyS4q32LZ67yc9Pn6n@stanza.co
SUMMARY:Tides @ Stripers
DESCRIPTION:Tides @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+uYpw-1n\n\nShop: https://stza.co/+uYpw-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Indians
<2018-05-15 Tue 17:35-20:35>
:PROPERTIES:
:ID:       fxYiVkPQZCQdo6EySe3c2ENb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Indians Tides vs. Indians

Follow on MiLB First Pitch  https //stza.co/+uYBx-3I

Shop  https //stza.co/+uYBx-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Indians
END:VALARM
DTSTART:20180515T223500Z
DTEND:20180516T013500Z
UID:fxYiVkPQZCQdo6EySe3c2ENb@stanza.co
SUMMARY:Tides vs. Indians
DESCRIPTION:Tides vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+uYBx-3I\n\nShop: https://stza.co/+uYBx-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Indians
<2018-05-16 Wed 17:35-20:35>
:PROPERTIES:
:ID:       QJXJ9apWA4q7ymACApRxGWx6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides vs. Indians Tides vs. Indians

Follow on MiLB First Pitch  https //stza.co/+uYBQ-2p

Shop  https //stza.co/+uYBQ-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Indians
END:VALARM
DTSTART:20180516T223500Z
DTEND:20180517T013500Z
UID:QJXJ9apWA4q7ymACApRxGWx6@stanza.co
SUMMARY:Tides vs. Indians
DESCRIPTION:Tides vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+uYBQ-2p\n\nShop: https://stza.co/+uYBQ-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Indians
<2018-05-17 Thu 11:05-14:05>
:PROPERTIES:
:ID:       c2KbP4RpV-pd91FY8R-Q_ybt@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Indians Tides vs. Indians

Follow on MiLB First Pitch  https //stza.co/+uYCj-P

Shop  https //stza.co/+uYCj-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Indians
END:VALARM
DTSTART:20180517T160500Z
DTEND:20180517T190500Z
UID:c2KbP4RpV-pd91FY8R-Q_ybt@stanza.co
SUMMARY:Tides vs. Indians
DESCRIPTION:Tides vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+uYCj-P\n\nShop: https://stza.co/+uYCj-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Bats
<2018-05-18 Fri 18:05-21:05>
:PROPERTIES:
:ID:       fbokOv10uRLwYAB1pCV_9FK1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Bats Tides vs. Bats

Follow on MiLB First Pitch  https //stza.co/+uYCy-3V

Shop  https //stza.co/+uYCy-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Bats
END:VALARM
DTSTART:20180518T230500Z
DTEND:20180519T020500Z
UID:fbokOv10uRLwYAB1pCV_9FK1@stanza.co
SUMMARY:Tides vs. Bats
DESCRIPTION:Tides vs. Bats\n\nFollow on MiLB First Pitch: https://stza.co/+uYCy-3V\n\nShop: https://stza.co/+uYCy-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Bats
<2018-05-19 Sat 18:05-21:05>
:PROPERTIES:
:ID:       178ZE1sF340wNQ11rZen26WF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides vs. Bats Tides vs. Bats

Follow on MiLB First Pitch  https //stza.co/+uYCT-1U

Shop  https //stza.co/+uYCT-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Bats
END:VALARM
DTSTART:20180519T230500Z
DTEND:20180520T020500Z
UID:178ZE1sF340wNQ11rZen26WF@stanza.co
SUMMARY:Tides vs. Bats
DESCRIPTION:Tides vs. Bats\n\nFollow on MiLB First Pitch: https://stza.co/+uYCT-1U\n\nShop: https://stza.co/+uYCT-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Bats
<2018-05-20 Sun 12:05-15:05>
:PROPERTIES:
:ID:       l8eHmi9TDKatGVydjwwHcbXN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Bats Tides vs. Bats

Follow on MiLB First Pitch  https //stza.co/+uYDc-2t

Shop  https //stza.co/+uYDc-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Bats
END:VALARM
DTSTART:20180520T170500Z
DTEND:20180520T200500Z
UID:l8eHmi9TDKatGVydjwwHcbXN@stanza.co
SUMMARY:Tides vs. Bats
DESCRIPTION:Tides vs. Bats\n\nFollow on MiLB First Pitch: https://stza.co/+uYDc-2t\n\nShop: https://stza.co/+uYDc-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Knights
<2018-05-21 Mon 18:04-21:04>
:PROPERTIES:
:ID:       GpXVJ2DWyIHBZjhITAd7cMUU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Knights Tides @ Knights

Follow on MiLB First Pitch  https //stza.co/+xONv-

Shop  https //stza.co/+xONv-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Knights
END:VALARM
DTSTART:20180521T230400Z
DTEND:20180522T020400Z
UID:GpXVJ2DWyIHBZjhITAd7cMUU@stanza.co
SUMMARY:Tides @ Knights
DESCRIPTION:Tides @ Knights\n\nFollow on MiLB First Pitch: https://stza.co/+xONv-\n\nShop: https://stza.co/+xONv-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Knights
<2018-05-22 Tue 18:04-21:04>
:PROPERTIES:
:ID:       WzRPvTWNShLE_jFgmKfihcfN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides @ Knights Tides @ Knights

Follow on MiLB First Pitch  https //stza.co/+xONw-V

Shop  https //stza.co/+xONw-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Knights
END:VALARM
DTSTART:20180522T230400Z
DTEND:20180523T020400Z
UID:WzRPvTWNShLE_jFgmKfihcfN@stanza.co
SUMMARY:Tides @ Knights
DESCRIPTION:Tides @ Knights\n\nFollow on MiLB First Pitch: https://stza.co/+xONw-V\n\nShop: https://stza.co/+xONw-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Knights
<2018-05-23 Wed 18:04-21:04>
:PROPERTIES:
:ID:       2b0fZLoPklGy6UEVPFQwMkFP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Knights Tides @ Knights

Follow on MiLB First Pitch  https //stza.co/+xONx-1h

Shop  https //stza.co/+xONx-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Knights
END:VALARM
DTSTART:20180523T230400Z
DTEND:20180524T020400Z
UID:2b0fZLoPklGy6UEVPFQwMkFP@stanza.co
SUMMARY:Tides @ Knights
DESCRIPTION:Tides @ Knights\n\nFollow on MiLB First Pitch: https://stza.co/+xONx-1h\n\nShop: https://stza.co/+xONx-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Knights
<2018-05-24 Thu 18:04-21:04>
:PROPERTIES:
:ID:       mzhEn7iP0Np34mSi9qlj-hAG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Knights Tides @ Knights

Follow on MiLB First Pitch  https //stza.co/+xONy-2t

Shop  https //stza.co/+xONy-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Knights
END:VALARM
DTSTART:20180524T230400Z
DTEND:20180525T020400Z
UID:mzhEn7iP0Np34mSi9qlj-hAG@stanza.co
SUMMARY:Tides @ Knights
DESCRIPTION:Tides @ Knights\n\nFollow on MiLB First Pitch: https://stza.co/+xONy-2t\n\nShop: https://stza.co/+xONy-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Mud Hens
<2018-05-25 Fri 18:05-21:05>
:PROPERTIES:
:ID:       UC7osG-9UhI74LCIrkJ68WIM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides @ Mud Hens Tides @ Mud Hens

Follow on MiLB First Pitch  https //stza.co/+vKhT-

Shop  https //stza.co/+vKhT-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Mud Hens
END:VALARM
DTSTART:20180525T230500Z
DTEND:20180526T020500Z
UID:UC7osG-9UhI74LCIrkJ68WIM@stanza.co
SUMMARY:Tides @ Mud Hens
DESCRIPTION:Tides @ Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+vKhT-\n\nShop: https://stza.co/+vKhT-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Mud Hens
<2018-05-26 Sat 18:05-21:05>
:PROPERTIES:
:ID:       F0-nnqm6uJKRkFUgLjHSVdL8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Mud Hens Tides @ Mud Hens

Follow on MiLB First Pitch  https //stza.co/+vKhU-1s

Shop  https //stza.co/+vKhU-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Mud Hens
END:VALARM
DTSTART:20180526T230500Z
DTEND:20180527T020500Z
UID:F0-nnqm6uJKRkFUgLjHSVdL8@stanza.co
SUMMARY:Tides @ Mud Hens
DESCRIPTION:Tides @ Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+vKhU-1s\n\nShop: https://stza.co/+vKhU-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Mud Hens
<2018-05-27 Sun 17:05-20:05>
:PROPERTIES:
:ID:       0TQ5WKeBd81qOmaOwrSwsIdG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Mud Hens Tides @ Mud Hens

Follow on MiLB First Pitch  https //stza.co/+vKhV-2Y

Shop  https //stza.co/+vKhV-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Mud Hens
END:VALARM
DTSTART:20180527T220500Z
DTEND:20180528T010500Z
UID:0TQ5WKeBd81qOmaOwrSwsIdG@stanza.co
SUMMARY:Tides @ Mud Hens
DESCRIPTION:Tides @ Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+vKhV-2Y\n\nShop: https://stza.co/+vKhV-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Mud Hens
<2018-05-28 Mon 16:05-19:05>
:PROPERTIES:
:ID:       PSNegPCuGm5EWbEvFCScLJhG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides @ Mud Hens Tides @ Mud Hens

Follow on MiLB First Pitch  https //stza.co/+vKhW-K

Shop  https //stza.co/+vKhW-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Mud Hens
END:VALARM
DTSTART:20180528T210500Z
DTEND:20180529T000500Z
UID:PSNegPCuGm5EWbEvFCScLJhG@stanza.co
SUMMARY:Tides @ Mud Hens
DESCRIPTION:Tides @ Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+vKhW-K\n\nShop: https://stza.co/+vKhW-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Red Sox
<2018-05-29 Tue 17:35-20:35>
:PROPERTIES:
:ID:       QY0fkCwbuy8bLWaC-U89AHk2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Red Sox Tides vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+uYDF-$

Shop  https //stza.co/+uYDF-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Red Sox
END:VALARM
DTSTART:20180529T223500Z
DTEND:20180530T013500Z
UID:QY0fkCwbuy8bLWaC-U89AHk2@stanza.co
SUMMARY:Tides vs. Red Sox
DESCRIPTION:Tides vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+uYDF-$\n\nShop: https://stza.co/+uYDF-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Red Sox
<2018-05-30 Wed 17:35-20:35>
:PROPERTIES:
:ID:       HEXrbHuHDrGIuMkjcTzNzO9K@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Red Sox Tides vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+uYDT-3T

Shop  https //stza.co/+uYDT-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Red Sox
END:VALARM
DTSTART:20180530T223500Z
DTEND:20180531T013500Z
UID:HEXrbHuHDrGIuMkjcTzNzO9K@stanza.co
SUMMARY:Tides vs. Red Sox
DESCRIPTION:Tides vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+uYDT-3T\n\nShop: https://stza.co/+uYDT-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Red Sox
<2018-05-31 Thu 17:35-20:35>
:PROPERTIES:
:ID:       tpIKDrXu0mf2YB8GeO5EOyFG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides vs. Red Sox Tides vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+uYE7-3a

Shop  https //stza.co/+uYE7-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Red Sox
END:VALARM
DTSTART:20180531T223500Z
DTEND:20180601T013500Z
UID:tpIKDrXu0mf2YB8GeO5EOyFG@stanza.co
SUMMARY:Tides vs. Red Sox
DESCRIPTION:Tides vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+uYE7-3a\n\nShop: https://stza.co/+uYE7-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Red Wings
<2018-06-01 Fri 18:05-21:05>
:PROPERTIES:
:ID:       pRvTzsXEuF80smYHByA-ABtT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Red Wings Tides vs. Red Wings

Follow on MiLB First Pitch  https //stza.co/+uYEm-$

Shop  https //stza.co/+uYEm-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Red Wings
END:VALARM
DTSTART:20180601T230500Z
DTEND:20180602T020500Z
UID:pRvTzsXEuF80smYHByA-ABtT@stanza.co
SUMMARY:Tides vs. Red Wings
DESCRIPTION:Tides vs. Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+uYEm-$\n\nShop: https://stza.co/+uYEm-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Red Wings
<2018-06-02 Sat 18:05-21:05>
:PROPERTIES:
:ID:       yEXRb5zbW2W5h1BcqCHux74W@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Red Wings Tides vs. Red Wings

Follow on MiLB First Pitch  https //stza.co/+uYEG-2Q

Shop  https //stza.co/+uYEG-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Red Wings
END:VALARM
DTSTART:20180602T230500Z
DTEND:20180603T020500Z
UID:yEXRb5zbW2W5h1BcqCHux74W@stanza.co
SUMMARY:Tides vs. Red Wings
DESCRIPTION:Tides vs. Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+uYEG-2Q\n\nShop: https://stza.co/+uYEG-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Red Wings
<2018-06-03 Sun 12:05-15:05>
:PROPERTIES:
:ID:       FfcNlFFv1ikBckrRIJMoCsLX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides vs. Red Wings Tides vs. Red Wings

Follow on MiLB First Pitch  https //stza.co/+uYEW-36

Shop  https //stza.co/+uYEW-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Red Wings
END:VALARM
DTSTART:20180603T170500Z
DTEND:20180603T200500Z
UID:FfcNlFFv1ikBckrRIJMoCsLX@stanza.co
SUMMARY:Tides vs. Red Wings
DESCRIPTION:Tides vs. Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+uYEW-36\n\nShop: https://stza.co/+uYEW-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Clippers
<2018-06-05 Tue 18:05-21:05>
:PROPERTIES:
:ID:       Kbft7EzoUZI8DP16hAXVWsiy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Clippers Tides @ Clippers

Buy tickets here  https //stza.co/~uYkP

Follow on MiLB First Pitch  https //stza.co/+uYkP-3b

Shop  https //stza.co/+uYkP-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Clippers
END:VALARM
DTSTART:20180605T230500Z
DTEND:20180606T020500Z
UID:Kbft7EzoUZI8DP16hAXVWsiy@stanza.co
SUMMARY:Tides @ Clippers
DESCRIPTION:Tides @ Clippers\n\nBuy tickets here: https://stza.co/~uYkP\n\nFollow on MiLB First Pitch: https://stza.co/+uYkP-3b\n\nShop: https://stza.co/+uYkP-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Clippers
<2018-06-06 Wed 18:05-21:05>
:PROPERTIES:
:ID:       UkuTF52e8cf7fZdB__BtXvt9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Clippers Tides @ Clippers

Buy tickets here  https //stza.co/~uYl9

Follow on MiLB First Pitch  https //stza.co/+uYl9-1b

Shop  https //stza.co/+uYl9-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Clippers
END:VALARM
DTSTART:20180606T230500Z
DTEND:20180607T020500Z
UID:UkuTF52e8cf7fZdB__BtXvt9@stanza.co
SUMMARY:Tides @ Clippers
DESCRIPTION:Tides @ Clippers\n\nBuy tickets here: https://stza.co/~uYl9\n\nFollow on MiLB First Pitch: https://stza.co/+uYl9-1b\n\nShop: https://stza.co/+uYl9-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Clippers
<2018-06-07 Thu 11:05-14:05>
:PROPERTIES:
:ID:       dchdhBMHAjUGePtziDEB7zNt@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides @ Clippers Tides @ Clippers

Buy tickets here  https //stza.co/~uYlq

Follow on MiLB First Pitch  https //stza.co/+uYlq-3V

Shop  https //stza.co/+uYlq-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Clippers
END:VALARM
DTSTART:20180607T160500Z
DTEND:20180607T190500Z
UID:dchdhBMHAjUGePtziDEB7zNt@stanza.co
SUMMARY:Tides @ Clippers
DESCRIPTION:Tides @ Clippers\n\nBuy tickets here: https://stza.co/~uYlq\n\nFollow on MiLB First Pitch: https://stza.co/+uYlq-3V\n\nShop: https://stza.co/+uYlq-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Mud Hens
<2018-06-08 Fri 18:05-21:05>
:PROPERTIES:
:ID:       PG7ayAp1fB4p_a4hdMbmSpPe@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Mud Hens Tides @ Mud Hens

Follow on MiLB First Pitch  https //stza.co/+vKhX-T

Shop  https //stza.co/+vKhX-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Mud Hens
END:VALARM
DTSTART:20180608T230500Z
DTEND:20180609T020500Z
UID:PG7ayAp1fB4p_a4hdMbmSpPe@stanza.co
SUMMARY:Tides @ Mud Hens
DESCRIPTION:Tides @ Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+vKhX-T\n\nShop: https://stza.co/+vKhX-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Mud Hens
<2018-06-09 Sat 18:05-21:05>
:PROPERTIES:
:ID:       HvFQRFI9b4Oskn96-OTtQv6U@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Mud Hens Tides @ Mud Hens

Follow on MiLB First Pitch  https //stza.co/+vKhY-1S

Shop  https //stza.co/+vKhY-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Mud Hens
END:VALARM
DTSTART:20180609T230500Z
DTEND:20180610T020500Z
UID:HvFQRFI9b4Oskn96-OTtQv6U@stanza.co
SUMMARY:Tides @ Mud Hens
DESCRIPTION:Tides @ Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+vKhY-1S\n\nShop: https://stza.co/+vKhY-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Mud Hens
<2018-06-10 Sun 15:05-18:05>
:PROPERTIES:
:ID:       BEgl-YfX-QFfOnd86W9wigC9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides @ Mud Hens Tides @ Mud Hens

Follow on MiLB First Pitch  https //stza.co/+vKhZ-q

Shop  https //stza.co/+vKhZ-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Mud Hens
END:VALARM
DTSTART:20180610T200500Z
DTEND:20180610T230500Z
UID:BEgl-YfX-QFfOnd86W9wigC9@stanza.co
SUMMARY:Tides @ Mud Hens
DESCRIPTION:Tides @ Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+vKhZ-q\n\nShop: https://stza.co/+vKhZ-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Stripers
<2018-06-11 Mon 18:05-21:05>
:PROPERTIES:
:ID:       tgtpfQhxlptozLtJLJoccWmK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Stripers Tides vs. Stripers

Follow on MiLB First Pitch  https //stza.co/+uYFc-1

Shop  https //stza.co/+uYFc-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Stripers
END:VALARM
DTSTART:20180611T230500Z
DTEND:20180612T020500Z
UID:tgtpfQhxlptozLtJLJoccWmK@stanza.co
SUMMARY:Tides vs. Stripers
DESCRIPTION:Tides vs. Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+uYFc-1\n\nShop: https://stza.co/+uYFc-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Stripers
<2018-06-12 Tue 18:05-21:05>
:PROPERTIES:
:ID:       bd3MWAf0r_ufGnOFUJkfmTIK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Stripers Tides vs. Stripers

Follow on MiLB First Pitch  https //stza.co/+uYFp-2g

Shop  https //stza.co/+uYFp-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Stripers
END:VALARM
DTSTART:20180612T230500Z
DTEND:20180613T020500Z
UID:bd3MWAf0r_ufGnOFUJkfmTIK@stanza.co
SUMMARY:Tides vs. Stripers
DESCRIPTION:Tides vs. Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+uYFp-2g\n\nShop: https://stza.co/+uYFp-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Stripers
<2018-06-13 Wed 11:05-14:05>
:PROPERTIES:
:ID:       -PUOWDAjm2ESkAbYIAKUQKtT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides vs. Stripers Tides vs. Stripers

Follow on MiLB First Pitch  https //stza.co/+uYFE-1N

Shop  https //stza.co/+uYFE-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Stripers
END:VALARM
DTSTART:20180613T160500Z
DTEND:20180613T190500Z
UID:-PUOWDAjm2ESkAbYIAKUQKtT@stanza.co
SUMMARY:Tides vs. Stripers
DESCRIPTION:Tides vs. Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+uYFE-1N\n\nShop: https://stza.co/+uYFE-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Knights
<2018-06-14 Thu 18:05-21:05>
:PROPERTIES:
:ID:       CwpCzaHdNAuwBI_2ribRzUqO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Knights Tides vs. Knights

Follow on MiLB First Pitch  https //stza.co/+uYFV-1v

Shop  https //stza.co/+uYFV-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Knights
END:VALARM
DTSTART:20180614T230500Z
DTEND:20180615T020500Z
UID:CwpCzaHdNAuwBI_2ribRzUqO@stanza.co
SUMMARY:Tides vs. Knights
DESCRIPTION:Tides vs. Knights\n\nFollow on MiLB First Pitch: https://stza.co/+uYFV-1v\n\nShop: https://stza.co/+uYFV-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Knights
<2018-06-15 Fri 18:05-21:05>
:PROPERTIES:
:ID:       QW2nH9ceEfxOJ0_66xevBSed@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Knights Tides vs. Knights

Follow on MiLB First Pitch  https //stza.co/+uYG4-Z

Shop  https //stza.co/+uYG4-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Knights
END:VALARM
DTSTART:20180615T230500Z
DTEND:20180616T020500Z
UID:QW2nH9ceEfxOJ0_66xevBSed@stanza.co
SUMMARY:Tides vs. Knights
DESCRIPTION:Tides vs. Knights\n\nFollow on MiLB First Pitch: https://stza.co/+uYG4-Z\n\nShop: https://stza.co/+uYG4-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Knights
<2018-06-16 Sat 18:05-21:05>
:PROPERTIES:
:ID:       obOYEaME7EtT4ZjwaLLFErt6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides vs. Knights Tides vs. Knights

Follow on MiLB First Pitch  https //stza.co/+uYGn-2d

Shop  https //stza.co/+uYGn-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Knights
END:VALARM
DTSTART:20180616T230500Z
DTEND:20180617T020500Z
UID:obOYEaME7EtT4ZjwaLLFErt6@stanza.co
SUMMARY:Tides vs. Knights
DESCRIPTION:Tides vs. Knights\n\nFollow on MiLB First Pitch: https://stza.co/+uYGn-2d\n\nShop: https://stza.co/+uYGn-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Knights
<2018-06-17 Sun 12:05-15:05>
:PROPERTIES:
:ID:       js23ALNKa03Tb_VA5Q7T_o3C@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Knights Tides vs. Knights

Follow on MiLB First Pitch  https //stza.co/+uYGI-9

Shop  https //stza.co/+uYGI-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Knights
END:VALARM
DTSTART:20180617T170500Z
DTEND:20180617T200500Z
UID:js23ALNKa03Tb_VA5Q7T_o3C@stanza.co
SUMMARY:Tides vs. Knights
DESCRIPTION:Tides vs. Knights\n\nFollow on MiLB First Pitch: https://stza.co/+uYGI-9\n\nShop: https://stza.co/+uYGI-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Indians
<2018-06-19 Tue 18:05-21:05>
:PROPERTIES:
:ID:       4s2_IRb75nfTXO-RxcybtYg7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Indians Tides @ Indians

Follow on MiLB First Pitch  https //stza.co/+uYs9-1X

Shop  https //stza.co/+uYs9-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Indians
END:VALARM
DTSTART:20180619T230500Z
DTEND:20180620T020500Z
UID:4s2_IRb75nfTXO-RxcybtYg7@stanza.co
SUMMARY:Tides @ Indians
DESCRIPTION:Tides @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+uYs9-1X\n\nShop: https://stza.co/+uYs9-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Indians
<2018-06-20 Wed 12:35-15:35>
:PROPERTIES:
:ID:       c5Xo1QDPEcL90RLaVvADcwV9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides @ Indians Tides @ Indians

Follow on MiLB First Pitch  https //stza.co/+uYsA-t

Shop  https //stza.co/+uYsA-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Indians
END:VALARM
DTSTART:20180620T173500Z
DTEND:20180620T203500Z
UID:c5Xo1QDPEcL90RLaVvADcwV9@stanza.co
SUMMARY:Tides @ Indians
DESCRIPTION:Tides @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+uYsA-t\n\nShop: https://stza.co/+uYsA-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Indians
<2018-06-21 Thu 18:05-21:05>
:PROPERTIES:
:ID:       b4jxrO1UGP6WZvNM3wzfgsMG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Indians Tides @ Indians

Follow on MiLB First Pitch  https //stza.co/+uYsR-p

Shop  https //stza.co/+uYsR-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Indians
END:VALARM
DTSTART:20180621T230500Z
DTEND:20180622T020500Z
UID:b4jxrO1UGP6WZvNM3wzfgsMG@stanza.co
SUMMARY:Tides @ Indians
DESCRIPTION:Tides @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+uYsR-p\n\nShop: https://stza.co/+uYsR-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Bats
<2018-06-22 Fri 18:00-21:00>
:PROPERTIES:
:ID:       T5PlThg4oYT-cYE2nPMObI9B@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Bats Tides @ Bats

Buy tickets here  https //stza.co/~uYu1

Follow on MiLB First Pitch  https //stza.co/+uYu1-1a

Shop  https //stza.co/+uYu1-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Bats
END:VALARM
DTSTART:20180622T230000Z
DTEND:20180623T020000Z
UID:T5PlThg4oYT-cYE2nPMObI9B@stanza.co
SUMMARY:Tides @ Bats
DESCRIPTION:Tides @ Bats\n\nBuy tickets here: https://stza.co/~uYu1\n\nFollow on MiLB First Pitch: https://stza.co/+uYu1-1a\n\nShop: https://stza.co/+uYu1-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Bats
<2018-06-23 Sat 17:30-20:30>
:PROPERTIES:
:ID:       PkNho4rhomBv51AL65sCMcJg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides @ Bats Tides @ Bats

Buy tickets here  https //stza.co/~uYuo

Follow on MiLB First Pitch  https //stza.co/+uYuo-3Q

Shop  https //stza.co/+uYuo-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Bats
END:VALARM
DTSTART:20180623T223000Z
DTEND:20180624T013000Z
UID:PkNho4rhomBv51AL65sCMcJg@stanza.co
SUMMARY:Tides @ Bats
DESCRIPTION:Tides @ Bats\n\nBuy tickets here: https://stza.co/~uYuo\n\nFollow on MiLB First Pitch: https://stza.co/+uYuo-3Q\n\nShop: https://stza.co/+uYuo-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Bats
<2018-06-24 Sun 17:00-20:00>
:PROPERTIES:
:ID:       0JvDD0K7J8vPHeqiCpHLlave@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Bats Tides @ Bats

Buy tickets here  https //stza.co/~uYuF

Follow on MiLB First Pitch  https //stza.co/+uYuF-1$

Shop  https //stza.co/+uYuF-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Bats
END:VALARM
DTSTART:20180624T220000Z
DTEND:20180625T010000Z
UID:0JvDD0K7J8vPHeqiCpHLlave@stanza.co
SUMMARY:Tides @ Bats
DESCRIPTION:Tides @ Bats\n\nBuy tickets here: https://stza.co/~uYuF\n\nFollow on MiLB First Pitch: https://stza.co/+uYuF-1$\n\nShop: https://stza.co/+uYuF-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Stripers
<2018-06-25 Mon 18:05-21:05>
:PROPERTIES:
:ID:       B2lrrn6SCuYARMTus-fRmk2s@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Stripers Tides vs. Stripers

Follow on MiLB First Pitch  https //stza.co/+uYGT-$

Shop  https //stza.co/+uYGT-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Stripers
END:VALARM
DTSTART:20180625T230500Z
DTEND:20180626T020500Z
UID:B2lrrn6SCuYARMTus-fRmk2s@stanza.co
SUMMARY:Tides vs. Stripers
DESCRIPTION:Tides vs. Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+uYGT-$\n\nShop: https://stza.co/+uYGT-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Stripers
<2018-06-26 Tue 18:05-21:05>
:PROPERTIES:
:ID:       FNh-3we8cw2gLXQoU_BAQhj9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides vs. Stripers Tides vs. Stripers

Follow on MiLB First Pitch  https //stza.co/+uYHa-2V

Shop  https //stza.co/+uYHa-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Stripers
END:VALARM
DTSTART:20180626T230500Z
DTEND:20180627T020500Z
UID:FNh-3we8cw2gLXQoU_BAQhj9@stanza.co
SUMMARY:Tides vs. Stripers
DESCRIPTION:Tides vs. Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+uYHa-2V\n\nShop: https://stza.co/+uYHa-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Stripers
<2018-06-27 Wed 11:05-14:05>
:PROPERTIES:
:ID:       M72YgFjz5XjKhPIGvQ8DaJDo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Stripers Tides vs. Stripers

Follow on MiLB First Pitch  https //stza.co/+uYHp-G

Shop  https //stza.co/+uYHp-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Stripers
END:VALARM
DTSTART:20180627T160500Z
DTEND:20180627T190500Z
UID:M72YgFjz5XjKhPIGvQ8DaJDo@stanza.co
SUMMARY:Tides vs. Stripers
DESCRIPTION:Tides vs. Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+uYHp-G\n\nShop: https://stza.co/+uYHp-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Bulls
<2018-06-28 Thu 18:05-21:05>
:PROPERTIES:
:ID:       yNbSxdXtdu4VbhFQjTMNL_qW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Bulls Tides vs. Bulls

Follow on MiLB First Pitch  https //stza.co/+uYHB-7

Shop  https //stza.co/+uYHB-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Bulls
END:VALARM
DTSTART:20180628T230500Z
DTEND:20180629T020500Z
UID:yNbSxdXtdu4VbhFQjTMNL_qW@stanza.co
SUMMARY:Tides vs. Bulls
DESCRIPTION:Tides vs. Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+uYHB-7\n\nShop: https://stza.co/+uYHB-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Bulls
<2018-06-29 Fri 18:05-21:05>
:PROPERTIES:
:ID:       FMktjJ_2f8Wlyz_HPPR3FAaX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides vs. Bulls Tides vs. Bulls

Follow on MiLB First Pitch  https //stza.co/+uYHO-2X

Shop  https //stza.co/+uYHO-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Bulls
END:VALARM
DTSTART:20180629T230500Z
DTEND:20180630T020500Z
UID:FMktjJ_2f8Wlyz_HPPR3FAaX@stanza.co
SUMMARY:Tides vs. Bulls
DESCRIPTION:Tides vs. Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+uYHO-2X\n\nShop: https://stza.co/+uYHO-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Bulls
<2018-06-30 Sat 18:05-21:05>
:PROPERTIES:
:ID:       TnDEDG_HpSsFHnbu0x3Np6a5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Bulls Tides vs. Bulls

Follow on MiLB First Pitch  https //stza.co/+uYI0-2W

Shop  https //stza.co/+uYI0-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Bulls
END:VALARM
DTSTART:20180630T230500Z
DTEND:20180701T020500Z
UID:TnDEDG_HpSsFHnbu0x3Np6a5@stanza.co
SUMMARY:Tides vs. Bulls
DESCRIPTION:Tides vs. Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+uYI0-2W\n\nShop: https://stza.co/+uYI0-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Bulls
<2018-07-01 Sun 12:05-15:05>
:PROPERTIES:
:ID:       Ei0u-xARwM4DCoCInByZ5pqR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Bulls Tides vs. Bulls

Follow on MiLB First Pitch  https //stza.co/+uYIc-3L

Shop  https //stza.co/+uYIc-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Bulls
END:VALARM
DTSTART:20180701T170500Z
DTEND:20180701T200500Z
UID:Ei0u-xARwM4DCoCInByZ5pqR@stanza.co
SUMMARY:Tides vs. Bulls
DESCRIPTION:Tides vs. Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+uYIc-3L\n\nShop: https://stza.co/+uYIc-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Knights
<2018-07-02 Mon 18:05-21:05>
:PROPERTIES:
:ID:       mG-rlBrd7TvUDvuEIwmZVMko@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides vs. Knights Tides vs. Knights

Follow on MiLB First Pitch  https //stza.co/+uYIt-E

Shop  https //stza.co/+uYIt-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Knights
END:VALARM
DTSTART:20180702T230500Z
DTEND:20180703T020500Z
UID:mG-rlBrd7TvUDvuEIwmZVMko@stanza.co
SUMMARY:Tides vs. Knights
DESCRIPTION:Tides vs. Knights\n\nFollow on MiLB First Pitch: https://stza.co/+uYIt-E\n\nShop: https://stza.co/+uYIt-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Knights
<2018-07-03 Tue 18:05-21:05>
:PROPERTIES:
:ID:       MZ1xiN42ULdZW-ZTheqaVLKt@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Knights Tides vs. Knights

Follow on MiLB First Pitch  https //stza.co/+uYII-2N

Shop  https //stza.co/+uYII-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Knights
END:VALARM
DTSTART:20180703T230500Z
DTEND:20180704T020500Z
UID:MZ1xiN42ULdZW-ZTheqaVLKt@stanza.co
SUMMARY:Tides vs. Knights
DESCRIPTION:Tides vs. Knights\n\nFollow on MiLB First Pitch: https://stza.co/+uYII-2N\n\nShop: https://stza.co/+uYII-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Stripers
<2018-07-04 Wed 18:05-21:05>
:PROPERTIES:
:ID:       042tCos7q6rgZU7BlL3Wj7cV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Stripers Tides @ Stripers

Follow on MiLB First Pitch  https //stza.co/+uYpL-2g

Shop  https //stza.co/+uYpL-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Stripers
END:VALARM
DTSTART:20180704T230500Z
DTEND:20180705T020500Z
UID:042tCos7q6rgZU7BlL3Wj7cV@stanza.co
SUMMARY:Tides @ Stripers
DESCRIPTION:Tides @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+uYpL-2g\n\nShop: https://stza.co/+uYpL-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Stripers
<2018-07-05 Thu 18:05-21:05>
:PROPERTIES:
:ID:       10Ze4bibf3HJ6Ix312XAQkQX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides @ Stripers Tides @ Stripers

Follow on MiLB First Pitch  https //stza.co/+uYq9-o

Shop  https //stza.co/+uYq9-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Stripers
END:VALARM
DTSTART:20180705T230500Z
DTEND:20180706T020500Z
UID:10Ze4bibf3HJ6Ix312XAQkQX@stanza.co
SUMMARY:Tides @ Stripers
DESCRIPTION:Tides @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+uYq9-o\n\nShop: https://stza.co/+uYq9-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Bulls
<2018-07-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       g7ADhPv6RsevXMSpSuLdsDz-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Bulls Tides @ Bulls

Follow on MiLB First Pitch  https //stza.co/+uYmP-O

Shop  https //stza.co/+uYmP-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Bulls
END:VALARM
DTSTART:20180706T230500Z
DTEND:20180707T020500Z
UID:g7ADhPv6RsevXMSpSuLdsDz-@stanza.co
SUMMARY:Tides @ Bulls
DESCRIPTION:Tides @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+uYmP-O\n\nShop: https://stza.co/+uYmP-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Bulls
<2018-07-07 Sat 17:35-20:35>
:PROPERTIES:
:ID:       M1LuQOkxGJrleFHr0Enva2Ju@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Bulls Tides @ Bulls

Follow on MiLB First Pitch  https //stza.co/+uYna-1$

Shop  https //stza.co/+uYna-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Bulls
END:VALARM
DTSTART:20180707T223500Z
DTEND:20180708T013500Z
UID:M1LuQOkxGJrleFHr0Enva2Ju@stanza.co
SUMMARY:Tides @ Bulls
DESCRIPTION:Tides @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+uYna-1$\n\nShop: https://stza.co/+uYna-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Bulls
<2018-07-08 Sun 16:05-19:05>
:PROPERTIES:
:ID:       qvd5d5S_m4U4bniQLhF8Bwpi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides @ Bulls Tides @ Bulls

Follow on MiLB First Pitch  https //stza.co/+uYnv-V

Shop  https //stza.co/+uYnv-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Bulls
END:VALARM
DTSTART:20180708T210500Z
DTEND:20180709T000500Z
UID:qvd5d5S_m4U4bniQLhF8Bwpi@stanza.co
SUMMARY:Tides @ Bulls
DESCRIPTION:Tides @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+uYnv-V\n\nShop: https://stza.co/+uYnv-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Stripers
<2018-07-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       bvfM6Xy5Hy2BMIwXambauxj1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Stripers Tides vs. Stripers

Follow on MiLB First Pitch  https //stza.co/+uYIV-1m

Shop  https //stza.co/+uYIV-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Stripers
END:VALARM
DTSTART:20180712T230500Z
DTEND:20180713T020500Z
UID:bvfM6Xy5Hy2BMIwXambauxj1@stanza.co
SUMMARY:Tides vs. Stripers
DESCRIPTION:Tides vs. Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+uYIV-1m\n\nShop: https://stza.co/+uYIV-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Stripers
<2018-07-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       Swtxuu158hvT6Zr1mc_YTR0r@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Stripers Tides vs. Stripers

Follow on MiLB First Pitch  https //stza.co/+uYJb-1m

Shop  https //stza.co/+uYJb-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Stripers
END:VALARM
DTSTART:20180713T230500Z
DTEND:20180714T020500Z
UID:Swtxuu158hvT6Zr1mc_YTR0r@stanza.co
SUMMARY:Tides vs. Stripers
DESCRIPTION:Tides vs. Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+uYJb-1m\n\nShop: https://stza.co/+uYJb-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Stripers
<2018-07-14 Sat 18:05-21:05>
:PROPERTIES:
:ID:       Kb52RGtdSp9pqrhEESPI4m7G@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides vs. Stripers Tides vs. Stripers

Follow on MiLB First Pitch  https //stza.co/+uYJq-1N

Shop  https //stza.co/+uYJq-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Stripers
END:VALARM
DTSTART:20180714T230500Z
DTEND:20180715T020500Z
UID:Kb52RGtdSp9pqrhEESPI4m7G@stanza.co
SUMMARY:Tides vs. Stripers
DESCRIPTION:Tides vs. Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+uYJq-1N\n\nShop: https://stza.co/+uYJq-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Stripers
<2018-07-15 Sun 15:05-18:05>
:PROPERTIES:
:ID:       8_DQRiKwmkatbdqPZQQWYk5-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Stripers Tides vs. Stripers

Follow on MiLB First Pitch  https //stza.co/+uYJH-t

Shop  https //stza.co/+uYJH-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Stripers
END:VALARM
DTSTART:20180715T200500Z
DTEND:20180715T230500Z
UID:8_DQRiKwmkatbdqPZQQWYk5-@stanza.co
SUMMARY:Tides vs. Stripers
DESCRIPTION:Tides vs. Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+uYJH-t\n\nShop: https://stza.co/+uYJH-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Bisons
<2018-07-16 Mon 18:05-21:05>
:PROPERTIES:
:ID:       CmCjvJ9NNfDmt2WZOqzBfKR0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Bisons Tides @ Bisons

Follow on MiLB First Pitch  https //stza.co/+uYgS-3e

Shop  https //stza.co/+uYgS-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Bisons
END:VALARM
DTSTART:20180716T230500Z
DTEND:20180717T020500Z
UID:CmCjvJ9NNfDmt2WZOqzBfKR0@stanza.co
SUMMARY:Tides @ Bisons
DESCRIPTION:Tides @ Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+uYgS-3e\n\nShop: https://stza.co/+uYgS-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Bisons
<2018-07-17 Tue 18:05-21:05>
:PROPERTIES:
:ID:       th4KhVOfkipFBoujNAoigO2p@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides @ Bisons Tides @ Bisons

Follow on MiLB First Pitch  https //stza.co/+uYh9-h

Shop  https //stza.co/+uYh9-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Bisons
END:VALARM
DTSTART:20180717T230500Z
DTEND:20180718T020500Z
UID:th4KhVOfkipFBoujNAoigO2p@stanza.co
SUMMARY:Tides @ Bisons
DESCRIPTION:Tides @ Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+uYh9-h\n\nShop: https://stza.co/+uYh9-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Bisons
<2018-07-18 Wed 12:05-15:05>
:PROPERTIES:
:ID:       iZBL51f3i0yoplGLLaDGg0Zn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Bisons Tides @ Bisons

Follow on MiLB First Pitch  https //stza.co/+uYhj-2g

Shop  https //stza.co/+uYhj-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Bisons
END:VALARM
DTSTART:20180718T170500Z
DTEND:20180718T200500Z
UID:iZBL51f3i0yoplGLLaDGg0Zn@stanza.co
SUMMARY:Tides @ Bisons
DESCRIPTION:Tides @ Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+uYhj-2g\n\nShop: https://stza.co/+uYhj-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Red Wings
<2018-07-19 Thu 18:05-21:05>
:PROPERTIES:
:ID:       gVzmwdx57ERdzTDCsDkXjgDM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Red Wings Tides @ Red Wings

Follow on MiLB First Pitch  https //stza.co/+uYOr-2k

Shop  https //stza.co/+uYOr-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Red Wings
END:VALARM
DTSTART:20180719T230500Z
DTEND:20180720T020500Z
UID:gVzmwdx57ERdzTDCsDkXjgDM@stanza.co
SUMMARY:Tides @ Red Wings
DESCRIPTION:Tides @ Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+uYOr-2k\n\nShop: https://stza.co/+uYOr-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Red Wings
<2018-07-20 Fri 17:05-20:05>
:PROPERTIES:
:ID:       4xpz6d-YyiJTBCFxv6p-gPoL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides @ Red Wings Tides @ Red Wings

Follow on MiLB First Pitch  https //stza.co/+vKhI-3b

Shop  https //stza.co/+vKhI-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Red Wings
END:VALARM
DTSTART:20180720T220500Z
DTEND:20180721T010500Z
UID:4xpz6d-YyiJTBCFxv6p-gPoL@stanza.co
SUMMARY:Tides @ Red Wings
DESCRIPTION:Tides @ Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vKhI-3b\n\nShop: https://stza.co/+vKhI-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Red Wings
<2018-07-21 Sat 17:05-20:05>
:PROPERTIES:
:ID:       _fD6XbBGA11us5bmjj1X4xnL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Red Wings Tides @ Red Wings

Follow on MiLB First Pitch  https //stza.co/+vKhJ-1a

Shop  https //stza.co/+vKhJ-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Red Wings
END:VALARM
DTSTART:20180721T220500Z
DTEND:20180722T010500Z
UID:_fD6XbBGA11us5bmjj1X4xnL@stanza.co
SUMMARY:Tides @ Red Wings
DESCRIPTION:Tides @ Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vKhJ-1a\n\nShop: https://stza.co/+vKhJ-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Red Wings
<2018-07-22 Sun 12:05-15:05>
:PROPERTIES:
:ID:       ciucJt_FPY1LymHXZ_xvLvcg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Red Wings Tides @ Red Wings

Follow on MiLB First Pitch  https //stza.co/+vKhK-2R

Shop  https //stza.co/+vKhK-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Red Wings
END:VALARM
DTSTART:20180722T170500Z
DTEND:20180722T200500Z
UID:ciucJt_FPY1LymHXZ_xvLvcg@stanza.co
SUMMARY:Tides @ Red Wings
DESCRIPTION:Tides @ Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vKhK-2R\n\nShop: https://stza.co/+vKhK-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Chiefs
<2018-07-24 Tue 18:05-21:05>
:PROPERTIES:
:ID:       S9Jl2mSA9HkRqtaslptGmcAu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides vs. Chiefs Tides vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+uYJY-2P

Shop  https //stza.co/+uYJY-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Chiefs
END:VALARM
DTSTART:20180724T230500Z
DTEND:20180725T020500Z
UID:S9Jl2mSA9HkRqtaslptGmcAu@stanza.co
SUMMARY:Tides vs. Chiefs
DESCRIPTION:Tides vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+uYJY-2P\n\nShop: https://stza.co/+uYJY-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Chiefs
<2018-07-25 Wed 18:05-21:05>
:PROPERTIES:
:ID:       36sqjJAVqmsGR46OMb_jMV4O@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Chiefs Tides vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+uYKa-Y

Shop  https //stza.co/+uYKa-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Chiefs
END:VALARM
DTSTART:20180725T230500Z
DTEND:20180726T020500Z
UID:36sqjJAVqmsGR46OMb_jMV4O@stanza.co
SUMMARY:Tides vs. Chiefs
DESCRIPTION:Tides vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+uYKa-Y\n\nShop: https://stza.co/+uYKa-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Chiefs
<2018-07-26 Thu 11:05-14:05>
:PROPERTIES:
:ID:       nDw914Q_QO3LplX6Fpnwdu3I@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Chiefs Tides vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+uYKo-A

Shop  https //stza.co/+uYKo-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Chiefs
END:VALARM
DTSTART:20180726T160500Z
DTEND:20180726T190500Z
UID:nDw914Q_QO3LplX6Fpnwdu3I@stanza.co
SUMMARY:Tides vs. Chiefs
DESCRIPTION:Tides vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+uYKo-A\n\nShop: https://stza.co/+uYKo-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Mud Hens
<2018-07-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       7gWq8f1FaQj4K9nem6X7jDok@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides vs. Mud Hens Tides vs. Mud Hens

Follow on MiLB First Pitch  https //stza.co/+uYKF-3O

Shop  https //stza.co/+uYKF-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Mud Hens
END:VALARM
DTSTART:20180727T230500Z
DTEND:20180728T020500Z
UID:7gWq8f1FaQj4K9nem6X7jDok@stanza.co
SUMMARY:Tides vs. Mud Hens
DESCRIPTION:Tides vs. Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+uYKF-3O\n\nShop: https://stza.co/+uYKF-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Mud Hens
<2018-07-28 Sat 18:05-21:05>
:PROPERTIES:
:ID:       9lTKCH7GUhlQpXz7BOkvwqCg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Mud Hens Tides vs. Mud Hens

Follow on MiLB First Pitch  https //stza.co/+uYKS-U

Shop  https //stza.co/+uYKS-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Mud Hens
END:VALARM
DTSTART:20180728T230500Z
DTEND:20180729T020500Z
UID:9lTKCH7GUhlQpXz7BOkvwqCg@stanza.co
SUMMARY:Tides vs. Mud Hens
DESCRIPTION:Tides vs. Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+uYKS-U\n\nShop: https://stza.co/+uYKS-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Mud Hens
<2018-07-29 Sun 15:05-18:05>
:PROPERTIES:
:ID:       _bjOSeXrD-HG5ExWt7G6y2Tx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Mud Hens Tides vs. Mud Hens

Follow on MiLB First Pitch  https //stza.co/+uYL5-3P

Shop  https //stza.co/+uYL5-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Mud Hens
END:VALARM
DTSTART:20180729T200500Z
DTEND:20180729T230500Z
UID:_bjOSeXrD-HG5ExWt7G6y2Tx@stanza.co
SUMMARY:Tides vs. Mud Hens
DESCRIPTION:Tides vs. Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+uYL5-3P\n\nShop: https://stza.co/+uYL5-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Knights
<2018-07-30 Mon 18:04-21:04>
:PROPERTIES:
:ID:       viAwXm_lrDTVoE1pOc0stOgb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides @ Knights Tides @ Knights

Follow on MiLB First Pitch  https //stza.co/+xONz-K

Shop  https //stza.co/+xONz-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Knights
END:VALARM
DTSTART:20180730T230400Z
DTEND:20180731T020400Z
UID:viAwXm_lrDTVoE1pOc0stOgb@stanza.co
SUMMARY:Tides @ Knights
DESCRIPTION:Tides @ Knights\n\nFollow on MiLB First Pitch: https://stza.co/+xONz-K\n\nShop: https://stza.co/+xONz-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Knights
<2018-07-31 Tue 18:04-21:04>
:PROPERTIES:
:ID:       egd2iHrZqr_K0Kv7gkESo4fD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Knights Tides @ Knights

Follow on MiLB First Pitch  https //stza.co/+xONA-3F

Shop  https //stza.co/+xONA-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Knights
END:VALARM
DTSTART:20180731T230400Z
DTEND:20180801T020400Z
UID:egd2iHrZqr_K0Kv7gkESo4fD@stanza.co
SUMMARY:Tides @ Knights
DESCRIPTION:Tides @ Knights\n\nFollow on MiLB First Pitch: https://stza.co/+xONA-3F\n\nShop: https://stza.co/+xONA-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Knights
<2018-08-01 Wed 18:04-21:04>
:PROPERTIES:
:ID:       RsPblMUtJbxbPO1oX1f2b1Q3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Knights Tides @ Knights

Follow on MiLB First Pitch  https //stza.co/+xONB-1N

Shop  https //stza.co/+xONB-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Knights
END:VALARM
DTSTART:20180801T230400Z
DTEND:20180802T020400Z
UID:RsPblMUtJbxbPO1oX1f2b1Q3@stanza.co
SUMMARY:Tides @ Knights
DESCRIPTION:Tides @ Knights\n\nFollow on MiLB First Pitch: https://stza.co/+xONB-1N\n\nShop: https://stza.co/+xONB-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Knights
<2018-08-02 Thu 18:04-21:04>
:PROPERTIES:
:ID:       7RVEYerYUwaFFj8VV2nG-WXI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides @ Knights Tides @ Knights

Follow on MiLB First Pitch  https //stza.co/+xONC-U

Shop  https //stza.co/+xONC-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Knights
END:VALARM
DTSTART:20180802T230400Z
DTEND:20180803T020400Z
UID:7RVEYerYUwaFFj8VV2nG-WXI@stanza.co
SUMMARY:Tides @ Knights
DESCRIPTION:Tides @ Knights\n\nFollow on MiLB First Pitch: https://stza.co/+xONC-U\n\nShop: https://stza.co/+xONC-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Stripers
<2018-08-03 Fri 18:05-21:05>
:PROPERTIES:
:ID:       6ee4R_0P94kirPP0QF-lLkdm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Stripers Tides @ Stripers

Follow on MiLB First Pitch  https //stza.co/+uYqq-t

Shop  https //stza.co/+uYqq-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Stripers
END:VALARM
DTSTART:20180803T230500Z
DTEND:20180804T020500Z
UID:6ee4R_0P94kirPP0QF-lLkdm@stanza.co
SUMMARY:Tides @ Stripers
DESCRIPTION:Tides @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+uYqq-t\n\nShop: https://stza.co/+uYqq-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Stripers
<2018-08-04 Sat 17:05-20:05>
:PROPERTIES:
:ID:       Sd7Pp-GjsDPd0LP-SqKKET3a@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Stripers Tides @ Stripers

Follow on MiLB First Pitch  https //stza.co/+uYqM-y

Shop  https //stza.co/+uYqM-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Stripers
END:VALARM
DTSTART:20180804T220500Z
DTEND:20180805T010500Z
UID:Sd7Pp-GjsDPd0LP-SqKKET3a@stanza.co
SUMMARY:Tides @ Stripers
DESCRIPTION:Tides @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+uYqM-y\n\nShop: https://stza.co/+uYqM-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Stripers
<2018-08-05 Sun 12:05-15:05>
:PROPERTIES:
:ID:       32Vk9-gr8JcBM-Qr7MeeDCm8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides @ Stripers Tides @ Stripers

Follow on MiLB First Pitch  https //stza.co/+uYqX-2y

Shop  https //stza.co/+uYqX-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Stripers
END:VALARM
DTSTART:20180805T170500Z
DTEND:20180805T200500Z
UID:32Vk9-gr8JcBM-Qr7MeeDCm8@stanza.co
SUMMARY:Tides @ Stripers
DESCRIPTION:Tides @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+uYqX-2y\n\nShop: https://stza.co/+uYqX-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. RailRiders
<2018-08-07 Tue 18:05-21:05>
:PROPERTIES:
:ID:       7uIK0SuWhOGMuOhT3s4H72vK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. RailRiders Tides vs. RailRiders

Follow on MiLB First Pitch  https //stza.co/+uYLm-3j

Shop  https //stza.co/+uYLm-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. RailRiders
END:VALARM
DTSTART:20180807T230500Z
DTEND:20180808T020500Z
UID:7uIK0SuWhOGMuOhT3s4H72vK@stanza.co
SUMMARY:Tides vs. RailRiders
DESCRIPTION:Tides vs. RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+uYLm-3j\n\nShop: https://stza.co/+uYLm-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. RailRiders
<2018-08-08 Wed 18:05-21:05>
:PROPERTIES:
:ID:       nsQg8gYtTwoCubbDVMeE_E2D@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. RailRiders Tides vs. RailRiders

Follow on MiLB First Pitch  https //stza.co/+uYLz-O

Shop  https //stza.co/+uYLz-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. RailRiders
END:VALARM
DTSTART:20180808T230500Z
DTEND:20180809T020500Z
UID:nsQg8gYtTwoCubbDVMeE_E2D@stanza.co
SUMMARY:Tides vs. RailRiders
DESCRIPTION:Tides vs. RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+uYLz-O\n\nShop: https://stza.co/+uYLz-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. RailRiders
<2018-08-09 Thu 11:05-14:05>
:PROPERTIES:
:ID:       tfh31dylcEP8cMmZUWAcKlWl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides vs. RailRiders Tides vs. RailRiders

Follow on MiLB First Pitch  https //stza.co/+uYLN-J

Shop  https //stza.co/+uYLN-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. RailRiders
END:VALARM
DTSTART:20180809T160500Z
DTEND:20180809T190500Z
UID:tfh31dylcEP8cMmZUWAcKlWl@stanza.co
SUMMARY:Tides vs. RailRiders
DESCRIPTION:Tides vs. RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+uYLN-J\n\nShop: https://stza.co/+uYLN-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Clippers
<2018-08-10 Fri 18:05-21:05>
:PROPERTIES:
:ID:       5ZBe3aXgoFcDTbfTBQjg2UlR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Clippers Tides vs. Clippers

Follow on MiLB First Pitch  https //stza.co/+uYM3-z

Shop  https //stza.co/+uYM3-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Clippers
END:VALARM
DTSTART:20180810T230500Z
DTEND:20180811T020500Z
UID:5ZBe3aXgoFcDTbfTBQjg2UlR@stanza.co
SUMMARY:Tides vs. Clippers
DESCRIPTION:Tides vs. Clippers\n\nFollow on MiLB First Pitch: https://stza.co/+uYM3-z\n\nShop: https://stza.co/+uYM3-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Clippers
<2018-08-11 Sat 18:05-21:05>
:PROPERTIES:
:ID:       uKEjYNVHXIT6CShtoqK9icdW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Clippers Tides vs. Clippers

Follow on MiLB First Pitch  https //stza.co/+uYMi-39

Shop  https //stza.co/+uYMi-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Clippers
END:VALARM
DTSTART:20180811T230500Z
DTEND:20180812T020500Z
UID:uKEjYNVHXIT6CShtoqK9icdW@stanza.co
SUMMARY:Tides vs. Clippers
DESCRIPTION:Tides vs. Clippers\n\nFollow on MiLB First Pitch: https://stza.co/+uYMi-39\n\nShop: https://stza.co/+uYMi-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Clippers
<2018-08-12 Sun 15:05-18:05>
:PROPERTIES:
:ID:       wu_Ar4x5hUBQEFt67Qrs7ICd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides vs. Clippers Tides vs. Clippers

Follow on MiLB First Pitch  https //stza.co/+uYMy-j

Shop  https //stza.co/+uYMy-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Clippers
END:VALARM
DTSTART:20180812T200500Z
DTEND:20180812T230500Z
UID:wu_Ar4x5hUBQEFt67Qrs7ICd@stanza.co
SUMMARY:Tides vs. Clippers
DESCRIPTION:Tides vs. Clippers\n\nFollow on MiLB First Pitch: https://stza.co/+uYMy-j\n\nShop: https://stza.co/+uYMy-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Red Sox
<2018-08-13 Mon 18:05-21:05>
:PROPERTIES:
:ID:       4FsrWSMoZg3k2GBtAYzu3CgH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Red Sox Tides @ Red Sox

Buy tickets here  https //stza.co/~uYOa

Follow on MiLB First Pitch  https //stza.co/+uYOa-16

Shop  https //stza.co/+uYOa-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Red Sox
END:VALARM
DTSTART:20180813T230500Z
DTEND:20180814T020500Z
UID:4FsrWSMoZg3k2GBtAYzu3CgH@stanza.co
SUMMARY:Tides @ Red Sox
DESCRIPTION:Tides @ Red Sox\n\nBuy tickets here: https://stza.co/~uYOa\n\nFollow on MiLB First Pitch: https://stza.co/+uYOa-16\n\nShop: https://stza.co/+uYOa-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Red Sox
<2018-08-14 Tue 18:05-21:05>
:PROPERTIES:
:ID:       3NBzDM1B0UR5qKuR-p5uW4ir@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Red Sox Tides @ Red Sox

Buy tickets here  https //stza.co/~uYOf

Follow on MiLB First Pitch  https //stza.co/+uYOf-1B

Shop  https //stza.co/+uYOf-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Red Sox
END:VALARM
DTSTART:20180814T230500Z
DTEND:20180815T020500Z
UID:3NBzDM1B0UR5qKuR-p5uW4ir@stanza.co
SUMMARY:Tides @ Red Sox
DESCRIPTION:Tides @ Red Sox\n\nBuy tickets here: https://stza.co/~uYOf\n\nFollow on MiLB First Pitch: https://stza.co/+uYOf-1B\n\nShop: https://stza.co/+uYOf-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Red Sox
<2018-08-15 Wed 11:05-14:05>
:PROPERTIES:
:ID:       4itINmWBXYbgEtxaxja_hAT0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides @ Red Sox Tides @ Red Sox

Buy tickets here  https //stza.co/~uYOk

Follow on MiLB First Pitch  https //stza.co/+uYOk-3j

Shop  https //stza.co/+uYOk-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Red Sox
END:VALARM
DTSTART:20180815T160500Z
DTEND:20180815T190500Z
UID:4itINmWBXYbgEtxaxja_hAT0@stanza.co
SUMMARY:Tides @ Red Sox
DESCRIPTION:Tides @ Red Sox\n\nBuy tickets here: https://stza.co/~uYOk\n\nFollow on MiLB First Pitch: https://stza.co/+uYOk-3j\n\nShop: https://stza.co/+uYOk-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ RailRiders
<2018-08-16 Thu 18:05-21:05>
:PROPERTIES:
:ID:       0Q1QgxVO0wmRd1D3Nahe-6qD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ RailRiders Tides @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vKhL-z

Shop  https //stza.co/+vKhL-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ RailRiders
END:VALARM
DTSTART:20180816T230500Z
DTEND:20180817T020500Z
UID:0Q1QgxVO0wmRd1D3Nahe-6qD@stanza.co
SUMMARY:Tides @ RailRiders
DESCRIPTION:Tides @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vKhL-z\n\nShop: https://stza.co/+vKhL-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ RailRiders
<2018-08-17 Fri 18:05-21:05>
:PROPERTIES:
:ID:       qDpwQTQb8hTGsekcAfrJNYbI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ RailRiders Tides @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vKhM-G

Shop  https //stza.co/+vKhM-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ RailRiders
END:VALARM
DTSTART:20180817T230500Z
DTEND:20180818T020500Z
UID:qDpwQTQb8hTGsekcAfrJNYbI@stanza.co
SUMMARY:Tides @ RailRiders
DESCRIPTION:Tides @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vKhM-G\n\nShop: https://stza.co/+vKhM-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ RailRiders
<2018-08-18 Sat 17:35-20:35>
:PROPERTIES:
:ID:       rkFQCsqw5Pqc1_QN1iKtrxyf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides @ RailRiders Tides @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vKhN-2v

Shop  https //stza.co/+vKhN-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ RailRiders
END:VALARM
DTSTART:20180818T223500Z
DTEND:20180819T013500Z
UID:rkFQCsqw5Pqc1_QN1iKtrxyf@stanza.co
SUMMARY:Tides @ RailRiders
DESCRIPTION:Tides @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vKhN-2v\n\nShop: https://stza.co/+vKhN-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ RailRiders
<2018-08-19 Sun 12:05-15:05>
:PROPERTIES:
:ID:       eZEDGCdwpxM0kR9Dxrih9lev@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ RailRiders Tides @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vKhO-3w

Shop  https //stza.co/+vKhO-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ RailRiders
END:VALARM
DTSTART:20180819T170500Z
DTEND:20180819T200500Z
UID:eZEDGCdwpxM0kR9Dxrih9lev@stanza.co
SUMMARY:Tides @ RailRiders
DESCRIPTION:Tides @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vKhO-3w\n\nShop: https://stza.co/+vKhO-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Knights
<2018-08-21 Tue 18:05-21:05>
:PROPERTIES:
:ID:       MZfxrzxImTR6JtHB0QbkmOWm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Knights Tides vs. Knights

Follow on MiLB First Pitch  https //stza.co/+uYMN-14

Shop  https //stza.co/+uYMN-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Knights
END:VALARM
DTSTART:20180821T230500Z
DTEND:20180822T020500Z
UID:MZfxrzxImTR6JtHB0QbkmOWm@stanza.co
SUMMARY:Tides vs. Knights
DESCRIPTION:Tides vs. Knights\n\nFollow on MiLB First Pitch: https://stza.co/+uYMN-14\n\nShop: https://stza.co/+uYMN-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Knights
<2018-08-22 Wed 18:05-21:05>
:PROPERTIES:
:ID:       b6VwMF2rsDVROpXHOpLG2hB8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides vs. Knights Tides vs. Knights

Follow on MiLB First Pitch  https //stza.co/+uYM$-3d

Shop  https //stza.co/+uYM$-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Knights
END:VALARM
DTSTART:20180822T230500Z
DTEND:20180823T020500Z
UID:b6VwMF2rsDVROpXHOpLG2hB8@stanza.co
SUMMARY:Tides vs. Knights
DESCRIPTION:Tides vs. Knights\n\nFollow on MiLB First Pitch: https://stza.co/+uYM$-3d\n\nShop: https://stza.co/+uYM$-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Knights
<2018-08-23 Thu 11:05-14:05>
:PROPERTIES:
:ID:       XLohibCWj-_7OpOwNIiQepAC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Knights Tides vs. Knights

Follow on MiLB First Pitch  https //stza.co/+uYNa-2d

Shop  https //stza.co/+uYNa-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Knights
END:VALARM
DTSTART:20180823T160500Z
DTEND:20180823T190500Z
UID:XLohibCWj-_7OpOwNIiQepAC@stanza.co
SUMMARY:Tides vs. Knights
DESCRIPTION:Tides vs. Knights\n\nFollow on MiLB First Pitch: https://stza.co/+uYNa-2d\n\nShop: https://stza.co/+uYNa-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Bulls
<2018-08-24 Fri 18:05-21:05>
:PROPERTIES:
:ID:       lLZEbxnsaZ5BJf3fEyzBrRPL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Bulls Tides vs. Bulls

Follow on MiLB First Pitch  https //stza.co/+uYNv-2e

Shop  https //stza.co/+uYNv-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Bulls
END:VALARM
DTSTART:20180824T230500Z
DTEND:20180825T020500Z
UID:lLZEbxnsaZ5BJf3fEyzBrRPL@stanza.co
SUMMARY:Tides vs. Bulls
DESCRIPTION:Tides vs. Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+uYNv-2e\n\nShop: https://stza.co/+uYNv-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Bulls
<2018-08-25 Sat 18:05-21:05>
:PROPERTIES:
:ID:       eIke1Qk2NZVkVsDftT5MsEbl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides vs. Bulls Tides vs. Bulls

Follow on MiLB First Pitch  https //stza.co/+uYNH-1W

Shop  https //stza.co/+uYNH-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Bulls
END:VALARM
DTSTART:20180825T230500Z
DTEND:20180826T020500Z
UID:eIke1Qk2NZVkVsDftT5MsEbl@stanza.co
SUMMARY:Tides vs. Bulls
DESCRIPTION:Tides vs. Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+uYNH-1W\n\nShop: https://stza.co/+uYNH-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Bulls
<2018-08-26 Sun 15:05-18:05>
:PROPERTIES:
:ID:       TVV86WXe1kh_vAgZ5X-8vTPs@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Bulls Tides vs. Bulls

Follow on MiLB First Pitch  https //stza.co/+uYNX-3i

Shop  https //stza.co/+uYNX-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Bulls
END:VALARM
DTSTART:20180826T200500Z
DTEND:20180826T230500Z
UID:TVV86WXe1kh_vAgZ5X-8vTPs@stanza.co
SUMMARY:Tides vs. Bulls
DESCRIPTION:Tides vs. Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+uYNX-3i\n\nShop: https://stza.co/+uYNX-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides vs. Bulls
<2018-08-27 Mon 18:05-21:05>
:PROPERTIES:
:ID:       mKgzvJWXXWPVDRkuBfhdaUh2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides vs. Bulls Tides vs. Bulls

Follow on MiLB First Pitch  https //stza.co/+uYO5-w

Shop  https //stza.co/+uYO5-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tides vs. Bulls
END:VALARM
DTSTART:20180827T230500Z
DTEND:20180828T020500Z
UID:mKgzvJWXXWPVDRkuBfhdaUh2@stanza.co
SUMMARY:Tides vs. Bulls
DESCRIPTION:Tides vs. Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+uYO5-w\n\nShop: https://stza.co/+uYO5-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Stripers
<2018-08-28 Tue 18:05-21:05>
:PROPERTIES:
:ID:       Zk6Z2UDfPx3wSBinWsM5ptJQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides @ Stripers Tides @ Stripers

Follow on MiLB First Pitch  https //stza.co/+uYrl-2p

Shop  https //stza.co/+uYrl-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Stripers
END:VALARM
DTSTART:20180828T230500Z
DTEND:20180829T020500Z
UID:Zk6Z2UDfPx3wSBinWsM5ptJQ@stanza.co
SUMMARY:Tides @ Stripers
DESCRIPTION:Tides @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+uYrl-2p\n\nShop: https://stza.co/+uYrl-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Stripers
<2018-08-29 Wed 18:05-21:05>
:PROPERTIES:
:ID:       nzIcdkQLxX71bhd0bl414ftG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Stripers Tides @ Stripers

Follow on MiLB First Pitch  https //stza.co/+uYrD-2a

Shop  https //stza.co/+uYrD-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Stripers
END:VALARM
DTSTART:20180829T230500Z
DTEND:20180830T020500Z
UID:nzIcdkQLxX71bhd0bl414ftG@stanza.co
SUMMARY:Tides @ Stripers
DESCRIPTION:Tides @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+uYrD-2a\n\nShop: https://stza.co/+uYrD-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Stripers
<2018-08-30 Thu 09:35-12:35>
:PROPERTIES:
:ID:       xWEEaPCfjlnTf8CvhObRj1uU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Stripers Tides @ Stripers

Follow on MiLB First Pitch  https //stza.co/+uYs0-f

Shop  https //stza.co/+uYs0-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Stripers
END:VALARM
DTSTART:20180830T143500Z
DTEND:20180830T173500Z
UID:xWEEaPCfjlnTf8CvhObRj1uU@stanza.co
SUMMARY:Tides @ Stripers
DESCRIPTION:Tides @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+uYs0-f\n\nShop: https://stza.co/+uYs0-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Bulls
<2018-08-31 Fri 18:05-21:05>
:PROPERTIES:
:ID:       Z8wzGQR-N6vm6XnBUe2SYUO-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides @ Bulls Tides @ Bulls

Follow on MiLB First Pitch  https //stza.co/+uYnG-s

Shop  https //stza.co/+uYnG-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Bulls
END:VALARM
DTSTART:20180831T230500Z
DTEND:20180901T020500Z
UID:Z8wzGQR-N6vm6XnBUe2SYUO-@stanza.co
SUMMARY:Tides @ Bulls
DESCRIPTION:Tides @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+uYnG-s\n\nShop: https://stza.co/+uYnG-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Bulls
<2018-09-01 Sat 17:35-20:35>
:PROPERTIES:
:ID:       7AXoiJbQcG3t-w5HIX_JtDp2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Bulls Tides @ Bulls

Follow on MiLB First Pitch  https //stza.co/+uYo2-3R

Shop  https //stza.co/+uYo2-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Bulls
END:VALARM
DTSTART:20180901T223500Z
DTEND:20180902T013500Z
UID:7AXoiJbQcG3t-w5HIX_JtDp2@stanza.co
SUMMARY:Tides @ Bulls
DESCRIPTION:Tides @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+uYo2-3R\n\nShop: https://stza.co/+uYo2-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Bulls
<2018-09-02 Sun 16:05-19:05>
:PROPERTIES:
:ID:       BBDqWMxJOWvyl3ak2ogTO6tQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tides @ Bulls Tides @ Bulls

Follow on MiLB First Pitch  https //stza.co/+uYoo-1i

Shop  https //stza.co/+uYoo-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Bulls
END:VALARM
DTSTART:20180902T210500Z
DTEND:20180903T000500Z
UID:BBDqWMxJOWvyl3ak2ogTO6tQ@stanza.co
SUMMARY:Tides @ Bulls
DESCRIPTION:Tides @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+uYoo-1i\n\nShop: https://stza.co/+uYoo-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
* Tides @ Bulls
<2018-09-03 Mon 12:05-15:05>
:PROPERTIES:
:ID:       GLb1GHX29okX_fnZt8IWK5fQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tides @ Bulls Tides @ Bulls

Follow on MiLB First Pitch  https //stza.co/+uYoE-1J

Shop  https //stza.co/+uYoE-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tides @ Bulls
END:VALARM
DTSTART:20180903T170500Z
DTEND:20180903T200500Z
UID:GLb1GHX29okX_fnZt8IWK5fQ@stanza.co
SUMMARY:Tides @ Bulls
DESCRIPTION:Tides @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+uYoE-1J\n\nShop: https://stza.co/+uYoE-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144547Z
LAST-MODIFIED:20180213T144547Z
TRANSP:OPAQUE
END:VEVENT
