#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Bees vs. Isotopes
<2018-04-05 Thu 19:35-22:35>
:PROPERTIES:
:ID:       c0WeLi3DIqteP1Kg-uLMM8p7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Isotopes Bees vs. Isotopes

Follow on MiLB First Pitch  https //stza.co/+wmM$-2M

Shop  https //stza.co/+wmM$-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Isotopes
END:VALARM
DTSTART:20180406T003500Z
DTEND:20180406T033500Z
UID:c0WeLi3DIqteP1Kg-uLMM8p7@stanza.co
SUMMARY:Bees vs. Isotopes
DESCRIPTION:Bees vs. Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+wmM$-2M\n\nShop: https://stza.co/+wmM$-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Isotopes
<2018-04-06 Fri 19:35-22:35>
:PROPERTIES:
:ID:       iHbmyVCb1fW6upW0GKTJyynR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees vs. Isotopes Bees vs. Isotopes

Follow on MiLB First Pitch  https //stza.co/+wmN1-16

Shop  https //stza.co/+wmN1-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Isotopes
END:VALARM
DTSTART:20180407T003500Z
DTEND:20180407T033500Z
UID:iHbmyVCb1fW6upW0GKTJyynR@stanza.co
SUMMARY:Bees vs. Isotopes
DESCRIPTION:Bees vs. Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+wmN1-16\n\nShop: https://stza.co/+wmN1-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Isotopes
<2018-04-07 Sat 19:35-22:35>
:PROPERTIES:
:ID:       3bZ4HEVctLc5BAHs2VHcBjpN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Isotopes Bees vs. Isotopes

Follow on MiLB First Pitch  https //stza.co/+wmN3-2S

Shop  https //stza.co/+wmN3-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Isotopes
END:VALARM
DTSTART:20180408T003500Z
DTEND:20180408T033500Z
UID:3bZ4HEVctLc5BAHs2VHcBjpN@stanza.co
SUMMARY:Bees vs. Isotopes
DESCRIPTION:Bees vs. Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+wmN3-2S\n\nShop: https://stza.co/+wmN3-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Isotopes
<2018-04-08 Sun 14:05-17:05>
:PROPERTIES:
:ID:       jx08AVHwzDy4RlDmjiGCtbMm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Isotopes Bees vs. Isotopes

Follow on MiLB First Pitch  https //stza.co/+wmN5-p

Shop  https //stza.co/+wmN5-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Isotopes
END:VALARM
DTSTART:20180408T190500Z
DTEND:20180408T220500Z
UID:jx08AVHwzDy4RlDmjiGCtbMm@stanza.co
SUMMARY:Bees vs. Isotopes
DESCRIPTION:Bees vs. Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+wmN5-p\n\nShop: https://stza.co/+wmN5-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Isotopes
<2018-04-09 Mon 13:05-16:05>
:PROPERTIES:
:ID:       BlxE1L9lJV6ZH1aptacSTIG3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees vs. Isotopes Bees vs. Isotopes

Follow on MiLB First Pitch  https //stza.co/+wmN8-2A

Shop  https //stza.co/+wmN8-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Isotopes
END:VALARM
DTSTART:20180409T180500Z
DTEND:20180409T210500Z
UID:BlxE1L9lJV6ZH1aptacSTIG3@stanza.co
SUMMARY:Bees vs. Isotopes
DESCRIPTION:Bees vs. Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+wmN8-2A\n\nShop: https://stza.co/+wmN8-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Chihuahuas
<2018-04-10 Tue 20:05-23:05>
:PROPERTIES:
:ID:       2u7JOXXGp2S3tDfAHuiM2VQJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Chihuahuas Bees @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmMS-19

Shop  https //stza.co/+wmMS-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Chihuahuas
END:VALARM
DTSTART:20180411T010500Z
DTEND:20180411T040500Z
UID:2u7JOXXGp2S3tDfAHuiM2VQJ@stanza.co
SUMMARY:Bees @ Chihuahuas
DESCRIPTION:Bees @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmMS-19\n\nShop: https://stza.co/+wmMS-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Chihuahuas
<2018-04-11 Wed 12:05-15:05>
:PROPERTIES:
:ID:       jSVksJvt49OmfyseKgR_pCgA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Chihuahuas Bees @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmMT-y

Shop  https //stza.co/+wmMT-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Chihuahuas
END:VALARM
DTSTART:20180411T170500Z
DTEND:20180411T200500Z
UID:jSVksJvt49OmfyseKgR_pCgA@stanza.co
SUMMARY:Bees @ Chihuahuas
DESCRIPTION:Bees @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmMT-y\n\nShop: https://stza.co/+wmMT-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Chihuahuas
<2018-04-12 Thu 19:35-22:35>
:PROPERTIES:
:ID:       hwwptuLi8ygRxiBhYHvr5eJJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees @ Chihuahuas Bees @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmMU-1N

Shop  https //stza.co/+wmMU-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Chihuahuas
END:VALARM
DTSTART:20180413T003500Z
DTEND:20180413T033500Z
UID:hwwptuLi8ygRxiBhYHvr5eJJ@stanza.co
SUMMARY:Bees @ Chihuahuas
DESCRIPTION:Bees @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmMU-1N\n\nShop: https://stza.co/+wmMU-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Isotopes
<2018-04-13 Fri 19:35-22:35>
:PROPERTIES:
:ID:       c_fNI34zSXARQ4-o_mSnuuY9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Isotopes Bees @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whRC-2g

Shop  https //stza.co/+whRC-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Isotopes
END:VALARM
DTSTART:20180414T003500Z
DTEND:20180414T033500Z
UID:c_fNI34zSXARQ4-o_mSnuuY9@stanza.co
SUMMARY:Bees @ Isotopes
DESCRIPTION:Bees @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whRC-2g\n\nShop: https://stza.co/+whRC-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Isotopes
<2018-04-14 Sat 19:35-22:35>
:PROPERTIES:
:ID:       Z5sFlXVSalKir-1vv6e9_FZl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Isotopes Bees @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whRD-3b

Shop  https //stza.co/+whRD-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Isotopes
END:VALARM
DTSTART:20180415T003500Z
DTEND:20180415T033500Z
UID:Z5sFlXVSalKir-1vv6e9_FZl@stanza.co
SUMMARY:Bees @ Isotopes
DESCRIPTION:Bees @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whRD-3b\n\nShop: https://stza.co/+whRD-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Isotopes
<2018-04-15 Sun 14:35-17:35>
:PROPERTIES:
:ID:       95abLEJX2wiIu23oraFkoN6z@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees @ Isotopes Bees @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whRE-11

Shop  https //stza.co/+whRE-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Isotopes
END:VALARM
DTSTART:20180415T193500Z
DTEND:20180415T223500Z
UID:95abLEJX2wiIu23oraFkoN6z@stanza.co
SUMMARY:Bees @ Isotopes
DESCRIPTION:Bees @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whRE-11\n\nShop: https://stza.co/+whRE-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Isotopes
<2018-04-16 Mon 12:05-15:05>
:PROPERTIES:
:ID:       fLYe_YorsyHW7gF7qAGy_Y_-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Isotopes Bees @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whRG-1E

Shop  https //stza.co/+whRG-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Isotopes
END:VALARM
DTSTART:20180416T170500Z
DTEND:20180416T200500Z
UID:fLYe_YorsyHW7gF7qAGy_Y_-@stanza.co
SUMMARY:Bees @ Isotopes
DESCRIPTION:Bees @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whRG-1E\n\nShop: https://stza.co/+whRG-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. River Cats
<2018-04-17 Tue 19:35-22:35>
:PROPERTIES:
:ID:       gs7XxNNPkybd_xBnXgVu0FDv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. River Cats Bees vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+wmNb-3P

Shop  https //stza.co/+wmNb-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. River Cats
END:VALARM
DTSTART:20180418T003500Z
DTEND:20180418T033500Z
UID:gs7XxNNPkybd_xBnXgVu0FDv@stanza.co
SUMMARY:Bees vs. River Cats
DESCRIPTION:Bees vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wmNb-3P\n\nShop: https://stza.co/+wmNb-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. River Cats
<2018-04-18 Wed 13:05-16:05>
:PROPERTIES:
:ID:       smv3iTr-NdbqIjofEf-3DJej@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees vs. River Cats Bees vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+wmNc-O

Shop  https //stza.co/+wmNc-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. River Cats
END:VALARM
DTSTART:20180418T180500Z
DTEND:20180418T210500Z
UID:smv3iTr-NdbqIjofEf-3DJej@stanza.co
SUMMARY:Bees vs. River Cats
DESCRIPTION:Bees vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wmNc-O\n\nShop: https://stza.co/+wmNc-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. River Cats
<2018-04-19 Thu 19:35-22:35>
:PROPERTIES:
:ID:       ge-UJJ8lnJOGhBYb6moa4ISO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. River Cats Bees vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+wmNe-1L

Shop  https //stza.co/+wmNe-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. River Cats
END:VALARM
DTSTART:20180420T003500Z
DTEND:20180420T033500Z
UID:ge-UJJ8lnJOGhBYb6moa4ISO@stanza.co
SUMMARY:Bees vs. River Cats
DESCRIPTION:Bees vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wmNe-1L\n\nShop: https://stza.co/+wmNe-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. River Cats
<2018-04-20 Fri 19:35-22:35>
:PROPERTIES:
:ID:       qvQ8nGczZp_h7wkC1xlq_kBg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. River Cats Bees vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+wmNg-C

Shop  https //stza.co/+wmNg-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. River Cats
END:VALARM
DTSTART:20180421T003500Z
DTEND:20180421T033500Z
UID:qvQ8nGczZp_h7wkC1xlq_kBg@stanza.co
SUMMARY:Bees vs. River Cats
DESCRIPTION:Bees vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wmNg-C\n\nShop: https://stza.co/+wmNg-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Isotopes
<2018-04-21 Sat 19:35-22:35>
:PROPERTIES:
:ID:       S8T6u8kN0Bho_R1JRQxjeD2d@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees vs. Isotopes Bees vs. Isotopes

Follow on MiLB First Pitch  https //stza.co/+wmNj-2U

Shop  https //stza.co/+wmNj-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Isotopes
END:VALARM
DTSTART:20180422T003500Z
DTEND:20180422T033500Z
UID:S8T6u8kN0Bho_R1JRQxjeD2d@stanza.co
SUMMARY:Bees vs. Isotopes
DESCRIPTION:Bees vs. Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+wmNj-2U\n\nShop: https://stza.co/+wmNj-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Isotopes
<2018-04-22 Sun 14:05-17:05>
:PROPERTIES:
:ID:       8u9ksMyfsjgLX40dEW3uB6Bf@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Isotopes Bees vs. Isotopes

Follow on MiLB First Pitch  https //stza.co/+wmNl-2O

Shop  https //stza.co/+wmNl-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Isotopes
END:VALARM
DTSTART:20180422T190500Z
DTEND:20180422T220500Z
UID:8u9ksMyfsjgLX40dEW3uB6Bf@stanza.co
SUMMARY:Bees vs. Isotopes
DESCRIPTION:Bees vs. Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+wmNl-2O\n\nShop: https://stza.co/+wmNl-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Isotopes
<2018-04-23 Mon 19:35-22:35>
:PROPERTIES:
:ID:       irR_Vb-HW2BiDj5DmxB3qxUv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Isotopes Bees vs. Isotopes

Follow on MiLB First Pitch  https //stza.co/+wmNn-1T

Shop  https //stza.co/+wmNn-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Isotopes
END:VALARM
DTSTART:20180424T003500Z
DTEND:20180424T033500Z
UID:irR_Vb-HW2BiDj5DmxB3qxUv@stanza.co
SUMMARY:Bees vs. Isotopes
DESCRIPTION:Bees vs. Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+wmNn-1T\n\nShop: https://stza.co/+wmNn-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Chihuahuas
<2018-04-25 Wed 19:35-22:35>
:PROPERTIES:
:ID:       qn73QrqRUXhoLDHZKj4zt17q@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees @ Chihuahuas Bees @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmMW-3Z

Shop  https //stza.co/+wmMW-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Chihuahuas
END:VALARM
DTSTART:20180426T003500Z
DTEND:20180426T033500Z
UID:qn73QrqRUXhoLDHZKj4zt17q@stanza.co
SUMMARY:Bees @ Chihuahuas
DESCRIPTION:Bees @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmMW-3Z\n\nShop: https://stza.co/+wmMW-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Chihuahuas
<2018-04-26 Thu 19:35-22:35>
:PROPERTIES:
:ID:       xiaa_Nrtid0qcqEN9zuRfnFQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Chihuahuas Bees @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmMX-1T

Shop  https //stza.co/+wmMX-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Chihuahuas
END:VALARM
DTSTART:20180427T003500Z
DTEND:20180427T033500Z
UID:xiaa_Nrtid0qcqEN9zuRfnFQ@stanza.co
SUMMARY:Bees @ Chihuahuas
DESCRIPTION:Bees @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmMX-1T\n\nShop: https://stza.co/+wmMX-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Chihuahuas
<2018-04-27 Fri 20:05-23:05>
:PROPERTIES:
:ID:       MJnP52komsWStZGc3Apo1zwF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Chihuahuas Bees @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmMY-2_

Shop  https //stza.co/+wmMY-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Chihuahuas
END:VALARM
DTSTART:20180428T010500Z
DTEND:20180428T040500Z
UID:MJnP52komsWStZGc3Apo1zwF@stanza.co
SUMMARY:Bees @ Chihuahuas
DESCRIPTION:Bees @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmMY-2_\n\nShop: https://stza.co/+wmMY-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Chihuahuas
<2018-04-28 Sat 20:05-23:05>
:PROPERTIES:
:ID:       f5I11PjSmDYXubF6tbzR2RXI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees @ Chihuahuas Bees @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmMZ-1s

Shop  https //stza.co/+wmMZ-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Chihuahuas
END:VALARM
DTSTART:20180429T010500Z
DTEND:20180429T040500Z
UID:f5I11PjSmDYXubF6tbzR2RXI@stanza.co
SUMMARY:Bees @ Chihuahuas
DESCRIPTION:Bees @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmMZ-1s\n\nShop: https://stza.co/+wmMZ-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Chihuahuas
<2018-04-29 Sun 14:05-17:05>
:PROPERTIES:
:ID:       oM7uyPAlE3ymm-AUTERKOEqS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Chihuahuas Bees @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmM_-3g

Shop  https //stza.co/+wmM_-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Chihuahuas
END:VALARM
DTSTART:20180429T190500Z
DTEND:20180429T220500Z
UID:oM7uyPAlE3ymm-AUTERKOEqS@stanza.co
SUMMARY:Bees @ Chihuahuas
DESCRIPTION:Bees @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmM_-3g\n\nShop: https://stza.co/+wmM_-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Grizzlies
<2018-04-30 Mon 19:35-22:35>
:PROPERTIES:
:ID:       0OZC_xa5HHxczXZbRxpst_pE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Grizzlies Bees vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wmNp-2Q

Shop  https //stza.co/+wmNp-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Grizzlies
END:VALARM
DTSTART:20180501T003500Z
DTEND:20180501T033500Z
UID:0OZC_xa5HHxczXZbRxpst_pE@stanza.co
SUMMARY:Bees vs. Grizzlies
DESCRIPTION:Bees vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wmNp-2Q\n\nShop: https://stza.co/+wmNp-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Grizzlies
<2018-05-01 Tue 19:35-22:35>
:PROPERTIES:
:ID:       yp0Jn5KkAiL_cbC0wXyA7Frc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees vs. Grizzlies Bees vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wmNq-29

Shop  https //stza.co/+wmNq-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Grizzlies
END:VALARM
DTSTART:20180502T003500Z
DTEND:20180502T033500Z
UID:yp0Jn5KkAiL_cbC0wXyA7Frc@stanza.co
SUMMARY:Bees vs. Grizzlies
DESCRIPTION:Bees vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wmNq-29\n\nShop: https://stza.co/+wmNq-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Grizzlies
<2018-05-02 Wed 19:35-22:35>
:PROPERTIES:
:ID:       RumMDLzPqV2aOgjR8TJz8wdi@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Grizzlies Bees vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wmNt-1B

Shop  https //stza.co/+wmNt-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Grizzlies
END:VALARM
DTSTART:20180503T003500Z
DTEND:20180503T033500Z
UID:RumMDLzPqV2aOgjR8TJz8wdi@stanza.co
SUMMARY:Bees vs. Grizzlies
DESCRIPTION:Bees vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wmNt-1B\n\nShop: https://stza.co/+wmNt-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Grizzlies
<2018-05-03 Thu 11:35-14:35>
:PROPERTIES:
:ID:       WS6HgePnLOHGwSnbyz6666_g@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Grizzlies Bees vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wmNv-N

Shop  https //stza.co/+wmNv-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Grizzlies
END:VALARM
DTSTART:20180503T163500Z
DTEND:20180503T193500Z
UID:WS6HgePnLOHGwSnbyz6666_g@stanza.co
SUMMARY:Bees vs. Grizzlies
DESCRIPTION:Bees vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wmNv-N\n\nShop: https://stza.co/+wmNv-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. 51s
<2018-05-04 Fri 19:35-22:35>
:PROPERTIES:
:ID:       EMytz9fstyMDbVlxFSUt97oM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees vs. 51s Bees vs. 51s

Follow on MiLB First Pitch  https //stza.co/+wmNy-C

Shop  https //stza.co/+wmNy-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. 51s
END:VALARM
DTSTART:20180505T003500Z
DTEND:20180505T033500Z
UID:EMytz9fstyMDbVlxFSUt97oM@stanza.co
SUMMARY:Bees vs. 51s
DESCRIPTION:Bees vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+wmNy-C\n\nShop: https://stza.co/+wmNy-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. 51s
<2018-05-05 Sat 19:35-22:35>
:PROPERTIES:
:ID:       927kn16-UQFVnuZvtoP3J-l3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. 51s Bees vs. 51s

Follow on MiLB First Pitch  https //stza.co/+wmNA-2Q

Shop  https //stza.co/+wmNA-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. 51s
END:VALARM
DTSTART:20180506T003500Z
DTEND:20180506T033500Z
UID:927kn16-UQFVnuZvtoP3J-l3@stanza.co
SUMMARY:Bees vs. 51s
DESCRIPTION:Bees vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+wmNA-2Q\n\nShop: https://stza.co/+wmNA-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. 51s
<2018-05-06 Sun 19:35-22:35>
:PROPERTIES:
:ID:       pIlNMeFdYt6eikPu98a1MVnj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. 51s Bees vs. 51s

Follow on MiLB First Pitch  https //stza.co/+wmNE-3T

Shop  https //stza.co/+wmNE-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. 51s
END:VALARM
DTSTART:20180507T003500Z
DTEND:20180507T033500Z
UID:pIlNMeFdYt6eikPu98a1MVnj@stanza.co
SUMMARY:Bees vs. 51s
DESCRIPTION:Bees vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+wmNE-3T\n\nShop: https://stza.co/+wmNE-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. 51s
<2018-05-07 Mon 19:35-22:35>
:PROPERTIES:
:ID:       zDVuoPxXHPfrS61gx0Q5jck8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees vs. 51s Bees vs. 51s

Follow on MiLB First Pitch  https //stza.co/+wmNG-25

Shop  https //stza.co/+wmNG-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. 51s
END:VALARM
DTSTART:20180508T003500Z
DTEND:20180508T033500Z
UID:zDVuoPxXHPfrS61gx0Q5jck8@stanza.co
SUMMARY:Bees vs. 51s
DESCRIPTION:Bees vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+wmNG-25\n\nShop: https://stza.co/+wmNG-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ River Cats
<2018-05-08 Tue 21:05>--<2018-05-09 Wed 00:05>
:PROPERTIES:
:ID:       Ej0yQWtCR-lNN8pUh5tdweBg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ River Cats Bees @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjNJ-T

Shop  https //stza.co/+wjNJ-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ River Cats
END:VALARM
DTSTART:20180509T020500Z
DTEND:20180509T050500Z
UID:Ej0yQWtCR-lNN8pUh5tdweBg@stanza.co
SUMMARY:Bees @ River Cats
DESCRIPTION:Bees @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjNJ-T\n\nShop: https://stza.co/+wjNJ-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ River Cats
<2018-05-09 Wed 14:05-17:05>
:PROPERTIES:
:ID:       kriic2c5Iz6LpmHYUprYZiGM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ River Cats Bees @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjNK-3a

Shop  https //stza.co/+wjNK-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ River Cats
END:VALARM
DTSTART:20180509T190500Z
DTEND:20180509T220500Z
UID:kriic2c5Iz6LpmHYUprYZiGM@stanza.co
SUMMARY:Bees @ River Cats
DESCRIPTION:Bees @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjNK-3a\n\nShop: https://stza.co/+wjNK-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ River Cats
<2018-05-10 Thu 21:05>--<2018-05-11 Fri 00:05>
:PROPERTIES:
:ID:       Jfa468xgtgsyKVqSvPJIFooG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees @ River Cats Bees @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjNL-1U

Shop  https //stza.co/+wjNL-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ River Cats
END:VALARM
DTSTART:20180511T020500Z
DTEND:20180511T050500Z
UID:Jfa468xgtgsyKVqSvPJIFooG@stanza.co
SUMMARY:Bees @ River Cats
DESCRIPTION:Bees @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjNL-1U\n\nShop: https://stza.co/+wjNL-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ River Cats
<2018-05-11 Fri 21:05>--<2018-05-12 Sat 00:05>
:PROPERTIES:
:ID:       PkgYNV_6PEUb2__0_EiFF__2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ River Cats Bees @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjNM-h

Shop  https //stza.co/+wjNM-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ River Cats
END:VALARM
DTSTART:20180512T020500Z
DTEND:20180512T050500Z
UID:PkgYNV_6PEUb2__0_EiFF__2@stanza.co
SUMMARY:Bees @ River Cats
DESCRIPTION:Bees @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjNM-h\n\nShop: https://stza.co/+wjNM-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Grizzlies
<2018-05-12 Sat 21:05>--<2018-05-13 Sun 00:05>
:PROPERTIES:
:ID:       eoVEpEFvyA6muIvCqvq4paZB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Grizzlies Bees @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjNq-Z

Shop  https //stza.co/+wjNq-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Grizzlies
END:VALARM
DTSTART:20180513T020500Z
DTEND:20180513T050500Z
UID:eoVEpEFvyA6muIvCqvq4paZB@stanza.co
SUMMARY:Bees @ Grizzlies
DESCRIPTION:Bees @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjNq-Z\n\nShop: https://stza.co/+wjNq-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Grizzlies
<2018-05-13 Sun 15:05-18:05>
:PROPERTIES:
:ID:       PrkTQ3lmEK3_sSAh8gxZgo2q@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees @ Grizzlies Bees @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjNs-2O

Shop  https //stza.co/+wjNs-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Grizzlies
END:VALARM
DTSTART:20180513T200500Z
DTEND:20180513T230500Z
UID:PrkTQ3lmEK3_sSAh8gxZgo2q@stanza.co
SUMMARY:Bees @ Grizzlies
DESCRIPTION:Bees @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjNs-2O\n\nShop: https://stza.co/+wjNs-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Grizzlies
<2018-05-14 Mon 20:35-23:35>
:PROPERTIES:
:ID:       wQAaaH-DJfut2iEYprp6ZNGH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Grizzlies Bees @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjNt-1o

Shop  https //stza.co/+wjNt-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Grizzlies
END:VALARM
DTSTART:20180515T013500Z
DTEND:20180515T043500Z
UID:wQAaaH-DJfut2iEYprp6ZNGH@stanza.co
SUMMARY:Bees @ Grizzlies
DESCRIPTION:Bees @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjNt-1o\n\nShop: https://stza.co/+wjNt-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Grizzlies
<2018-05-15 Tue 13:05-16:05>
:PROPERTIES:
:ID:       3imnUWvaGREhblNmiNQm3Up7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Grizzlies Bees @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjNu-21

Shop  https //stza.co/+wjNu-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Grizzlies
END:VALARM
DTSTART:20180515T180500Z
DTEND:20180515T210500Z
UID:3imnUWvaGREhblNmiNQm3Up7@stanza.co
SUMMARY:Bees @ Grizzlies
DESCRIPTION:Bees @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjNu-21\n\nShop: https://stza.co/+wjNu-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. River Cats
<2018-05-17 Thu 19:35-22:35>
:PROPERTIES:
:ID:       WnLk2M9eocnKGJh1oZP6rVLy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees vs. River Cats Bees vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+wmNI-x

Shop  https //stza.co/+wmNI-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. River Cats
END:VALARM
DTSTART:20180518T003500Z
DTEND:20180518T033500Z
UID:WnLk2M9eocnKGJh1oZP6rVLy@stanza.co
SUMMARY:Bees vs. River Cats
DESCRIPTION:Bees vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wmNI-x\n\nShop: https://stza.co/+wmNI-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. River Cats
<2018-05-18 Fri 19:35-22:35>
:PROPERTIES:
:ID:       zsFnQEnh6rPDeKJF1GaxwH_j@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. River Cats Bees vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+wmNJ-h

Shop  https //stza.co/+wmNJ-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. River Cats
END:VALARM
DTSTART:20180519T003500Z
DTEND:20180519T033500Z
UID:zsFnQEnh6rPDeKJF1GaxwH_j@stanza.co
SUMMARY:Bees vs. River Cats
DESCRIPTION:Bees vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wmNJ-h\n\nShop: https://stza.co/+wmNJ-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. River Cats
<2018-05-19 Sat 19:35-22:35>
:PROPERTIES:
:ID:       5XIKZ7ZcF4jwXUG46o8e0_0n@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. River Cats Bees vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+wmNL-2n

Shop  https //stza.co/+wmNL-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. River Cats
END:VALARM
DTSTART:20180520T003500Z
DTEND:20180520T033500Z
UID:5XIKZ7ZcF4jwXUG46o8e0_0n@stanza.co
SUMMARY:Bees vs. River Cats
DESCRIPTION:Bees vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wmNL-2n\n\nShop: https://stza.co/+wmNL-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. River Cats
<2018-05-20 Sun 14:05-17:05>
:PROPERTIES:
:ID:       MVEA_TGRPz6_N0dgDPvBlK6B@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees vs. River Cats Bees vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+wmNO-W

Shop  https //stza.co/+wmNO-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. River Cats
END:VALARM
DTSTART:20180520T190500Z
DTEND:20180520T220500Z
UID:MVEA_TGRPz6_N0dgDPvBlK6B@stanza.co
SUMMARY:Bees vs. River Cats
DESCRIPTION:Bees vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wmNO-W\n\nShop: https://stza.co/+wmNO-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Isotopes
<2018-05-21 Mon 19:35-22:35>
:PROPERTIES:
:ID:       S7lMWa8f3fxSefNgABGUQpyY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Isotopes Bees @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whRI-27

Shop  https //stza.co/+whRI-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Isotopes
END:VALARM
DTSTART:20180522T003500Z
DTEND:20180522T033500Z
UID:S7lMWa8f3fxSefNgABGUQpyY@stanza.co
SUMMARY:Bees @ Isotopes
DESCRIPTION:Bees @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whRI-27\n\nShop: https://stza.co/+whRI-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Isotopes
<2018-05-22 Tue 19:35-22:35>
:PROPERTIES:
:ID:       YoId2lfY79dqF0dkHjKCWcfu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Isotopes Bees @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whRJ-2n

Shop  https //stza.co/+whRJ-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Isotopes
END:VALARM
DTSTART:20180523T003500Z
DTEND:20180523T033500Z
UID:YoId2lfY79dqF0dkHjKCWcfu@stanza.co
SUMMARY:Bees @ Isotopes
DESCRIPTION:Bees @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whRJ-2n\n\nShop: https://stza.co/+whRJ-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Isotopes
<2018-05-23 Wed 19:35-22:35>
:PROPERTIES:
:ID:       HQQWVfLEWiEAVb8j9EFQML0m@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees @ Isotopes Bees @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whRK-3E

Shop  https //stza.co/+whRK-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Isotopes
END:VALARM
DTSTART:20180524T003500Z
DTEND:20180524T033500Z
UID:HQQWVfLEWiEAVb8j9EFQML0m@stanza.co
SUMMARY:Bees @ Isotopes
DESCRIPTION:Bees @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whRK-3E\n\nShop: https://stza.co/+whRK-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Isotopes
<2018-05-24 Thu 13:05-16:05>
:PROPERTIES:
:ID:       1hKt2Il6IQeT-5SI2qwmzsVL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Isotopes Bees @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whRL-2i

Shop  https //stza.co/+whRL-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Isotopes
END:VALARM
DTSTART:20180524T180500Z
DTEND:20180524T210500Z
UID:1hKt2Il6IQeT-5SI2qwmzsVL@stanza.co
SUMMARY:Bees @ Isotopes
DESCRIPTION:Bees @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whRL-2i\n\nShop: https://stza.co/+whRL-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Aces
<2018-05-25 Fri 19:35-22:35>
:PROPERTIES:
:ID:       cN60fj_ZSz6W9oMckX3dfG7i@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Aces Bees vs. Aces

Follow on MiLB First Pitch  https //stza.co/+wmNQ-3b

Shop  https //stza.co/+wmNQ-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Aces
END:VALARM
DTSTART:20180526T003500Z
DTEND:20180526T033500Z
UID:cN60fj_ZSz6W9oMckX3dfG7i@stanza.co
SUMMARY:Bees vs. Aces
DESCRIPTION:Bees vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wmNQ-3b\n\nShop: https://stza.co/+wmNQ-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Aces
<2018-05-26 Sat 19:35-22:35>
:PROPERTIES:
:ID:       X2WHsT5_-Qu9x-Y5-SOZnDeC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees vs. Aces Bees vs. Aces

Follow on MiLB First Pitch  https //stza.co/+wmNS-3s

Shop  https //stza.co/+wmNS-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Aces
END:VALARM
DTSTART:20180527T003500Z
DTEND:20180527T033500Z
UID:X2WHsT5_-Qu9x-Y5-SOZnDeC@stanza.co
SUMMARY:Bees vs. Aces
DESCRIPTION:Bees vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wmNS-3s\n\nShop: https://stza.co/+wmNS-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Aces
<2018-05-27 Sun 19:35-22:35>
:PROPERTIES:
:ID:       OmGXK9HmZdpvO7BVvuknrtv4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Aces Bees vs. Aces

Follow on MiLB First Pitch  https //stza.co/+wmNU-2P

Shop  https //stza.co/+wmNU-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Aces
END:VALARM
DTSTART:20180528T003500Z
DTEND:20180528T033500Z
UID:OmGXK9HmZdpvO7BVvuknrtv4@stanza.co
SUMMARY:Bees vs. Aces
DESCRIPTION:Bees vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wmNU-2P\n\nShop: https://stza.co/+wmNU-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Aces
<2018-05-28 Mon 19:35-22:35>
:PROPERTIES:
:ID:       5zPo8-Fd8YTJBiy8yB3cshlY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Aces Bees vs. Aces

Follow on MiLB First Pitch  https //stza.co/+wmNW-29

Shop  https //stza.co/+wmNW-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Aces
END:VALARM
DTSTART:20180529T003500Z
DTEND:20180529T033500Z
UID:5zPo8-Fd8YTJBiy8yB3cshlY@stanza.co
SUMMARY:Bees vs. Aces
DESCRIPTION:Bees vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wmNW-29\n\nShop: https://stza.co/+wmNW-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Aces
<2018-05-29 Tue 13:05-16:05>
:PROPERTIES:
:ID:       i_XVDTehXCf1mrrrKPhGERJ4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees vs. Aces Bees vs. Aces

Follow on MiLB First Pitch  https //stza.co/+wmNX-2W

Shop  https //stza.co/+wmNX-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Aces
END:VALARM
DTSTART:20180529T180500Z
DTEND:20180529T210500Z
UID:i_XVDTehXCf1mrrrKPhGERJ4@stanza.co
SUMMARY:Bees vs. Aces
DESCRIPTION:Bees vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wmNX-2W\n\nShop: https://stza.co/+wmNX-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Rainiers
<2018-05-30 Wed 21:05>--<2018-05-31 Thu 00:05>
:PROPERTIES:
:ID:       UscQu0wy9FjcsJCspIgp-kh0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Rainiers Bees @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjNV-N

Shop  https //stza.co/+wjNV-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Rainiers
END:VALARM
DTSTART:20180531T020500Z
DTEND:20180531T050500Z
UID:UscQu0wy9FjcsJCspIgp-kh0@stanza.co
SUMMARY:Bees @ Rainiers
DESCRIPTION:Bees @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjNV-N\n\nShop: https://stza.co/+wjNV-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Rainiers
<2018-05-31 Thu 21:05>--<2018-06-01 Fri 00:05>
:PROPERTIES:
:ID:       h4-TkSgxB9sM86HZM780NphA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Rainiers Bees @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjNW-3W

Shop  https //stza.co/+wjNW-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Rainiers
END:VALARM
DTSTART:20180601T020500Z
DTEND:20180601T050500Z
UID:h4-TkSgxB9sM86HZM780NphA@stanza.co
SUMMARY:Bees @ Rainiers
DESCRIPTION:Bees @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjNW-3W\n\nShop: https://stza.co/+wjNW-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Rainiers
<2018-06-01 Fri 21:05>--<2018-06-02 Sat 00:05>
:PROPERTIES:
:ID:       ipN9dvqjhP4NemrN5ztdAxVB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees @ Rainiers Bees @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjNX-A

Shop  https //stza.co/+wjNX-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Rainiers
END:VALARM
DTSTART:20180602T020500Z
DTEND:20180602T050500Z
UID:ipN9dvqjhP4NemrN5ztdAxVB@stanza.co
SUMMARY:Bees @ Rainiers
DESCRIPTION:Bees @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjNX-A\n\nShop: https://stza.co/+wjNX-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Rainiers
<2018-06-02 Sat 19:05-22:05>
:PROPERTIES:
:ID:       1TnhbFMxEqKhNXpFVOccxnJJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Rainiers Bees @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjNY-1F

Shop  https //stza.co/+wjNY-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Rainiers
END:VALARM
DTSTART:20180603T000500Z
DTEND:20180603T030500Z
UID:1TnhbFMxEqKhNXpFVOccxnJJ@stanza.co
SUMMARY:Bees @ Rainiers
DESCRIPTION:Bees @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjNY-1F\n\nShop: https://stza.co/+wjNY-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Rainiers
<2018-06-03 Sun 15:35-18:35>
:PROPERTIES:
:ID:       SFz_Gv-8OmTEz7azwV3-ISZ_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Rainiers Bees @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjNZ-1K

Shop  https //stza.co/+wjNZ-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Rainiers
END:VALARM
DTSTART:20180603T203500Z
DTEND:20180603T233500Z
UID:SFz_Gv-8OmTEz7azwV3-ISZ_@stanza.co
SUMMARY:Bees @ Rainiers
DESCRIPTION:Bees @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjNZ-1K\n\nShop: https://stza.co/+wjNZ-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Express
<2018-06-05 Tue 20:05-23:05>
:PROPERTIES:
:ID:       2-8gl1RX40n3nlt962U5P0bl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees vs. Express Bees vs. Express

Follow on MiLB First Pitch  https //stza.co/+wmNZ-4

Shop  https //stza.co/+wmNZ-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Express
END:VALARM
DTSTART:20180606T010500Z
DTEND:20180606T040500Z
UID:2-8gl1RX40n3nlt962U5P0bl@stanza.co
SUMMARY:Bees vs. Express
DESCRIPTION:Bees vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+wmNZ-4\n\nShop: https://stza.co/+wmNZ-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Express
<2018-06-06 Wed 20:05-23:05>
:PROPERTIES:
:ID:       UBJNHq91q0iNUmWQiVpEU9A1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Express Bees vs. Express

Follow on MiLB First Pitch  https //stza.co/+wmO0-2X

Shop  https //stza.co/+wmO0-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Express
END:VALARM
DTSTART:20180607T010500Z
DTEND:20180607T040500Z
UID:UBJNHq91q0iNUmWQiVpEU9A1@stanza.co
SUMMARY:Bees vs. Express
DESCRIPTION:Bees vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+wmO0-2X\n\nShop: https://stza.co/+wmO0-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Express
<2018-06-07 Thu 13:05-16:05>
:PROPERTIES:
:ID:       CqrOIW6JFAi4rhaTtnhQHaUm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Express Bees vs. Express

Follow on MiLB First Pitch  https //stza.co/+wmO2-2s

Shop  https //stza.co/+wmO2-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Express
END:VALARM
DTSTART:20180607T180500Z
DTEND:20180607T210500Z
UID:CqrOIW6JFAi4rhaTtnhQHaUm@stanza.co
SUMMARY:Bees vs. Express
DESCRIPTION:Bees vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+wmO2-2s\n\nShop: https://stza.co/+wmO2-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Baby Cakes
<2018-06-08 Fri 20:05-23:05>
:PROPERTIES:
:ID:       fIuHYQIcPpxU-EOs5D-rGWTK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees vs. Baby Cakes Bees vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+wmO5-2V

Shop  https //stza.co/+wmO5-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Baby Cakes
END:VALARM
DTSTART:20180609T010500Z
DTEND:20180609T040500Z
UID:fIuHYQIcPpxU-EOs5D-rGWTK@stanza.co
SUMMARY:Bees vs. Baby Cakes
DESCRIPTION:Bees vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+wmO5-2V\n\nShop: https://stza.co/+wmO5-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Baby Cakes
<2018-06-09 Sat 19:35-22:35>
:PROPERTIES:
:ID:       5M36UFnpAKAfwk907YE5b2Fo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Baby Cakes Bees vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+wmO6-2e

Shop  https //stza.co/+wmO6-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Baby Cakes
END:VALARM
DTSTART:20180610T003500Z
DTEND:20180610T033500Z
UID:5M36UFnpAKAfwk907YE5b2Fo@stanza.co
SUMMARY:Bees vs. Baby Cakes
DESCRIPTION:Bees vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+wmO6-2e\n\nShop: https://stza.co/+wmO6-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Baby Cakes
<2018-06-10 Sun 14:05-17:05>
:PROPERTIES:
:ID:       Pjibfct5gduXIlgf0i8P1lKO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Baby Cakes Bees vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+wmO8-3B

Shop  https //stza.co/+wmO8-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Baby Cakes
END:VALARM
DTSTART:20180610T190500Z
DTEND:20180610T220500Z
UID:Pjibfct5gduXIlgf0i8P1lKO@stanza.co
SUMMARY:Bees vs. Baby Cakes
DESCRIPTION:Bees vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+wmO8-3B\n\nShop: https://stza.co/+wmO8-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Baby Cakes
<2018-06-11 Mon 20:05-23:05>
:PROPERTIES:
:ID:       aBuYEbl4KeETaIw85viMgdVJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees vs. Baby Cakes Bees vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+wmOb-2E

Shop  https //stza.co/+wmOb-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Baby Cakes
END:VALARM
DTSTART:20180612T010500Z
DTEND:20180612T040500Z
UID:aBuYEbl4KeETaIw85viMgdVJ@stanza.co
SUMMARY:Bees vs. Baby Cakes
DESCRIPTION:Bees vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+wmOb-2E\n\nShop: https://stza.co/+wmOb-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Dodgers
<2018-06-13 Wed 19:05-22:05>
:PROPERTIES:
:ID:       pkoilnR5RFm1mEZsngt9GCtO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Dodgers Bees @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$Ph-L

Shop  https //stza.co/+v$Ph-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Dodgers
END:VALARM
DTSTART:20180614T000500Z
DTEND:20180614T030500Z
UID:pkoilnR5RFm1mEZsngt9GCtO@stanza.co
SUMMARY:Bees @ Dodgers
DESCRIPTION:Bees @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Ph-L\n\nShop: https://stza.co/+v$Ph-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Dodgers
<2018-06-14 Thu 19:05-22:05>
:PROPERTIES:
:ID:       AxNxefelH0aifWKjBq1GxFlu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Dodgers Bees @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$Pi-3

Shop  https //stza.co/+v$Pi-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Dodgers
END:VALARM
DTSTART:20180615T000500Z
DTEND:20180615T030500Z
UID:AxNxefelH0aifWKjBq1GxFlu@stanza.co
SUMMARY:Bees @ Dodgers
DESCRIPTION:Bees @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Pi-3\n\nShop: https://stza.co/+v$Pi-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Dodgers
<2018-06-15 Fri 19:05-22:05>
:PROPERTIES:
:ID:       VCthOQwzD0USrLgsOlkp0CLm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees @ Dodgers Bees @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$Pj-r

Shop  https //stza.co/+v$Pj-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Dodgers
END:VALARM
DTSTART:20180616T000500Z
DTEND:20180616T030500Z
UID:VCthOQwzD0USrLgsOlkp0CLm@stanza.co
SUMMARY:Bees @ Dodgers
DESCRIPTION:Bees @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Pj-r\n\nShop: https://stza.co/+v$Pj-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Sky Sox
<2018-06-16 Sat 19:00-22:00>
:PROPERTIES:
:ID:       AIqxoADn5KxNgf5pEyXIL0Tv@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Sky Sox Bees @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmMO-3L

Shop  https //stza.co/+wmMO-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Sky Sox
END:VALARM
DTSTART:20180617T000000Z
DTEND:20180617T030000Z
UID:AIqxoADn5KxNgf5pEyXIL0Tv@stanza.co
SUMMARY:Bees @ Sky Sox
DESCRIPTION:Bees @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmMO-3L\n\nShop: https://stza.co/+wmMO-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Sky Sox
<2018-06-17 Sun 14:30-17:30>
:PROPERTIES:
:ID:       JgGMrm3OtS3o4h6gN8lep679@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Sky Sox Bees @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmMP-2b

Shop  https //stza.co/+wmMP-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Sky Sox
END:VALARM
DTSTART:20180617T193000Z
DTEND:20180617T223000Z
UID:JgGMrm3OtS3o4h6gN8lep679@stanza.co
SUMMARY:Bees @ Sky Sox
DESCRIPTION:Bees @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmMP-2b\n\nShop: https://stza.co/+wmMP-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Sky Sox
<2018-06-18 Mon 19:40-22:40>
:PROPERTIES:
:ID:       K7EgCCZPArwmR7FhXidR4obk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees @ Sky Sox Bees @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmMQ-3h

Shop  https //stza.co/+wmMQ-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Sky Sox
END:VALARM
DTSTART:20180619T004000Z
DTEND:20180619T034000Z
UID:K7EgCCZPArwmR7FhXidR4obk@stanza.co
SUMMARY:Bees @ Sky Sox
DESCRIPTION:Bees @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmMQ-3h\n\nShop: https://stza.co/+wmMQ-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Sky Sox
<2018-06-19 Tue 19:40-22:40>
:PROPERTIES:
:ID:       lLtw4q3DSC1vose_UOzHF_Fa@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Sky Sox Bees @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmMR-2V

Shop  https //stza.co/+wmMR-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Sky Sox
END:VALARM
DTSTART:20180620T004000Z
DTEND:20180620T034000Z
UID:lLtw4q3DSC1vose_UOzHF_Fa@stanza.co
SUMMARY:Bees @ Sky Sox
DESCRIPTION:Bees @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmMR-2V\n\nShop: https://stza.co/+wmMR-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Rainiers
<2018-06-21 Thu 20:05-23:05>
:PROPERTIES:
:ID:       7MILgITWp8Z2_Sw-3TbhN0KH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Rainiers Bees vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+wmOd-2C

Shop  https //stza.co/+wmOd-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Rainiers
END:VALARM
DTSTART:20180622T010500Z
DTEND:20180622T040500Z
UID:7MILgITWp8Z2_Sw-3TbhN0KH@stanza.co
SUMMARY:Bees vs. Rainiers
DESCRIPTION:Bees vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wmOd-2C\n\nShop: https://stza.co/+wmOd-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Rainiers
<2018-06-22 Fri 20:05-23:05>
:PROPERTIES:
:ID:       8GBAniKUsNzwncqN6ARDSgOr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees vs. Rainiers Bees vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+wmOf-3O

Shop  https //stza.co/+wmOf-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Rainiers
END:VALARM
DTSTART:20180623T010500Z
DTEND:20180623T040500Z
UID:8GBAniKUsNzwncqN6ARDSgOr@stanza.co
SUMMARY:Bees vs. Rainiers
DESCRIPTION:Bees vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wmOf-3O\n\nShop: https://stza.co/+wmOf-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Rainiers
<2018-06-23 Sat 20:05-23:05>
:PROPERTIES:
:ID:       dEeNYOI80mwTJcUG20JuaPAI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Rainiers Bees vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+wmOh-8

Shop  https //stza.co/+wmOh-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Rainiers
END:VALARM
DTSTART:20180624T010500Z
DTEND:20180624T040500Z
UID:dEeNYOI80mwTJcUG20JuaPAI@stanza.co
SUMMARY:Bees vs. Rainiers
DESCRIPTION:Bees vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wmOh-8\n\nShop: https://stza.co/+wmOh-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Rainiers
<2018-06-24 Sun 14:05-17:05>
:PROPERTIES:
:ID:       sbGubB1jslG5sJp0l_6cNJCZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Rainiers Bees vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+wmOi-27

Shop  https //stza.co/+wmOi-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Rainiers
END:VALARM
DTSTART:20180624T190500Z
DTEND:20180624T220500Z
UID:sbGubB1jslG5sJp0l_6cNJCZ@stanza.co
SUMMARY:Bees vs. Rainiers
DESCRIPTION:Bees vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wmOi-27\n\nShop: https://stza.co/+wmOi-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Aces
<2018-06-25 Mon 21:05>--<2018-06-26 Tue 00:05>
:PROPERTIES:
:ID:       Ux7giivxcGSGOLilxCmErTbx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees @ Aces Bees @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjNB-y

Shop  https //stza.co/+wjNB-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Aces
END:VALARM
DTSTART:20180626T020500Z
DTEND:20180626T050500Z
UID:Ux7giivxcGSGOLilxCmErTbx@stanza.co
SUMMARY:Bees @ Aces
DESCRIPTION:Bees @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjNB-y\n\nShop: https://stza.co/+wjNB-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Aces
<2018-06-26 Tue 21:05>--<2018-06-27 Wed 00:05>
:PROPERTIES:
:ID:       B0hpRUUVOZGpKjNqAhe2xTI5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Aces Bees @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjNC-2o

Shop  https //stza.co/+wjNC-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Aces
END:VALARM
DTSTART:20180627T020500Z
DTEND:20180627T050500Z
UID:B0hpRUUVOZGpKjNqAhe2xTI5@stanza.co
SUMMARY:Bees @ Aces
DESCRIPTION:Bees @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjNC-2o\n\nShop: https://stza.co/+wjNC-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Aces
<2018-06-27 Wed 21:05>--<2018-06-28 Thu 00:05>
:PROPERTIES:
:ID:       6zq2-hMF-FhWsWQf2kvgFMur@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Aces Bees @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjND-1a

Shop  https //stza.co/+wjND-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Aces
END:VALARM
DTSTART:20180628T020500Z
DTEND:20180628T050500Z
UID:6zq2-hMF-FhWsWQf2kvgFMur@stanza.co
SUMMARY:Bees @ Aces
DESCRIPTION:Bees @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjND-1a\n\nShop: https://stza.co/+wjND-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Aces
<2018-06-28 Thu 21:05>--<2018-06-29 Fri 00:05>
:PROPERTIES:
:ID:       BM8yjJ-BbeGhZ-eafFF-BDyg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees @ Aces Bees @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjNE-S

Shop  https //stza.co/+wjNE-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Aces
END:VALARM
DTSTART:20180629T020500Z
DTEND:20180629T050500Z
UID:BM8yjJ-BbeGhZ-eafFF-BDyg@stanza.co
SUMMARY:Bees @ Aces
DESCRIPTION:Bees @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjNE-S\n\nShop: https://stza.co/+wjNE-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ 51s
<2018-06-29 Fri 21:05>--<2018-06-30 Sat 00:05>
:PROPERTIES:
:ID:       -mlkIZAa9iOdqsGBMPt5E6IP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ 51s Bees @ 51s

Follow on MiLB First Pitch  https //stza.co/+vK$K-2u

Shop  https //stza.co/+vK$K-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ 51s
END:VALARM
DTSTART:20180630T020500Z
DTEND:20180630T050500Z
UID:-mlkIZAa9iOdqsGBMPt5E6IP@stanza.co
SUMMARY:Bees @ 51s
DESCRIPTION:Bees @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vK$K-2u\n\nShop: https://stza.co/+vK$K-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ 51s
<2018-06-30 Sat 21:05>--<2018-07-01 Sun 00:05>
:PROPERTIES:
:ID:       CRCbtSW-7jgxybegwb885YQy@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ 51s Bees @ 51s

Follow on MiLB First Pitch  https //stza.co/+vK$L-3E

Shop  https //stza.co/+vK$L-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ 51s
END:VALARM
DTSTART:20180701T020500Z
DTEND:20180701T050500Z
UID:CRCbtSW-7jgxybegwb885YQy@stanza.co
SUMMARY:Bees @ 51s
DESCRIPTION:Bees @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vK$L-3E\n\nShop: https://stza.co/+vK$L-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ 51s
<2018-07-01 Sun 21:05>--<2018-07-02 Mon 00:05>
:PROPERTIES:
:ID:       6orvpK_MRMVrzrXYnOuohBDL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees @ 51s Bees @ 51s

Follow on MiLB First Pitch  https //stza.co/+vK$M-30

Shop  https //stza.co/+vK$M-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ 51s
END:VALARM
DTSTART:20180702T020500Z
DTEND:20180702T050500Z
UID:6orvpK_MRMVrzrXYnOuohBDL@stanza.co
SUMMARY:Bees @ 51s
DESCRIPTION:Bees @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vK$M-30\n\nShop: https://stza.co/+vK$M-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ 51s
<2018-07-02 Mon 21:05>--<2018-07-03 Tue 00:05>
:PROPERTIES:
:ID:       w81AKLspgCBCWJ9Sh8XIMQEf@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ 51s Bees @ 51s

Follow on MiLB First Pitch  https //stza.co/+vK$N-2t

Shop  https //stza.co/+vK$N-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ 51s
END:VALARM
DTSTART:20180703T020500Z
DTEND:20180703T050500Z
UID:w81AKLspgCBCWJ9Sh8XIMQEf@stanza.co
SUMMARY:Bees @ 51s
DESCRIPTION:Bees @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vK$N-2t\n\nShop: https://stza.co/+vK$N-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ 51s
<2018-07-03 Tue 21:05>--<2018-07-04 Wed 00:05>
:PROPERTIES:
:ID:       zkHEZxAxASitR2VhmkrhdFAC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ 51s Bees @ 51s

Follow on MiLB First Pitch  https //stza.co/+vK$O-3C

Shop  https //stza.co/+vK$O-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ 51s
END:VALARM
DTSTART:20180704T020500Z
DTEND:20180704T050500Z
UID:zkHEZxAxASitR2VhmkrhdFAC@stanza.co
SUMMARY:Bees @ 51s
DESCRIPTION:Bees @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vK$O-3C\n\nShop: https://stza.co/+vK$O-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Chihuahuas
<2018-07-04 Wed 19:35-22:35>
:PROPERTIES:
:ID:       gAFC9Gyjj86myuVBb2pzGtd4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees vs. Chihuahuas Bees vs. Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmOk-1R

Shop  https //stza.co/+wmOk-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Chihuahuas
END:VALARM
DTSTART:20180705T003500Z
DTEND:20180705T033500Z
UID:gAFC9Gyjj86myuVBb2pzGtd4@stanza.co
SUMMARY:Bees vs. Chihuahuas
DESCRIPTION:Bees vs. Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmOk-1R\n\nShop: https://stza.co/+wmOk-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Chihuahuas
<2018-07-05 Thu 20:05-23:05>
:PROPERTIES:
:ID:       oHYqQyyheJLX-0kJrDzyqiE2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Chihuahuas Bees vs. Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmOn-b

Shop  https //stza.co/+wmOn-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Chihuahuas
END:VALARM
DTSTART:20180706T010500Z
DTEND:20180706T040500Z
UID:oHYqQyyheJLX-0kJrDzyqiE2@stanza.co
SUMMARY:Bees vs. Chihuahuas
DESCRIPTION:Bees vs. Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmOn-b\n\nShop: https://stza.co/+wmOn-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Chihuahuas
<2018-07-06 Fri 19:35-22:35>
:PROPERTIES:
:ID:       PjrjKlEDCQpabOnVZZrY8u2i@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Chihuahuas Bees vs. Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmOp-3s

Shop  https //stza.co/+wmOp-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Chihuahuas
END:VALARM
DTSTART:20180707T003500Z
DTEND:20180707T033500Z
UID:PjrjKlEDCQpabOnVZZrY8u2i@stanza.co
SUMMARY:Bees vs. Chihuahuas
DESCRIPTION:Bees vs. Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmOp-3s\n\nShop: https://stza.co/+wmOp-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Chihuahuas
<2018-07-07 Sat 19:35-22:35>
:PROPERTIES:
:ID:       ydaOmZEhHJWeUroGZGqaz6YC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees vs. Chihuahuas Bees vs. Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmOs-3O

Shop  https //stza.co/+wmOs-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Chihuahuas
END:VALARM
DTSTART:20180708T003500Z
DTEND:20180708T033500Z
UID:ydaOmZEhHJWeUroGZGqaz6YC@stanza.co
SUMMARY:Bees vs. Chihuahuas
DESCRIPTION:Bees vs. Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmOs-3O\n\nShop: https://stza.co/+wmOs-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Chihuahuas
<2018-07-08 Sun 14:05-17:05>
:PROPERTIES:
:ID:       Ao7l0vX_NN_WJpSdlNWLVCG8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Chihuahuas Bees vs. Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmOv-2w

Shop  https //stza.co/+wmOv-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Chihuahuas
END:VALARM
DTSTART:20180708T190500Z
DTEND:20180708T220500Z
UID:Ao7l0vX_NN_WJpSdlNWLVCG8@stanza.co
SUMMARY:Bees vs. Chihuahuas
DESCRIPTION:Bees vs. Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmOv-2w\n\nShop: https://stza.co/+wmOv-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ River Cats
<2018-07-12 Thu 21:05>--<2018-07-13 Fri 00:05>
:PROPERTIES:
:ID:       MzPc9aamD4Bpi2avZYn4SRxP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ River Cats Bees @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjNN-3T

Shop  https //stza.co/+wjNN-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ River Cats
END:VALARM
DTSTART:20180713T020500Z
DTEND:20180713T050500Z
UID:MzPc9aamD4Bpi2avZYn4SRxP@stanza.co
SUMMARY:Bees @ River Cats
DESCRIPTION:Bees @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjNN-3T\n\nShop: https://stza.co/+wjNN-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ River Cats
<2018-07-13 Fri 21:05>--<2018-07-14 Sat 00:05>
:PROPERTIES:
:ID:       xyUspo9N8vqGAzj4OWoUEO7c@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees @ River Cats Bees @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjNO-2B

Shop  https //stza.co/+wjNO-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ River Cats
END:VALARM
DTSTART:20180714T020500Z
DTEND:20180714T050500Z
UID:xyUspo9N8vqGAzj4OWoUEO7c@stanza.co
SUMMARY:Bees @ River Cats
DESCRIPTION:Bees @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjNO-2B\n\nShop: https://stza.co/+wjNO-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ River Cats
<2018-07-14 Sat 21:05>--<2018-07-15 Sun 00:05>
:PROPERTIES:
:ID:       8144S4ArbDTr38QC_u5nbc6e@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ River Cats Bees @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjNP-y

Shop  https //stza.co/+wjNP-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ River Cats
END:VALARM
DTSTART:20180715T020500Z
DTEND:20180715T050500Z
UID:8144S4ArbDTr38QC_u5nbc6e@stanza.co
SUMMARY:Bees @ River Cats
DESCRIPTION:Bees @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjNP-y\n\nShop: https://stza.co/+wjNP-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ River Cats
<2018-07-15 Sun 15:05-18:05>
:PROPERTIES:
:ID:       UHRnBXQRggLXghQYZdDDknl3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ River Cats Bees @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjNQ-y

Shop  https //stza.co/+wjNQ-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ River Cats
END:VALARM
DTSTART:20180715T200500Z
DTEND:20180715T230500Z
UID:UHRnBXQRggLXghQYZdDDknl3@stanza.co
SUMMARY:Bees @ River Cats
DESCRIPTION:Bees @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjNQ-y\n\nShop: https://stza.co/+wjNQ-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. 51s
<2018-07-16 Mon 20:05-23:05>
:PROPERTIES:
:ID:       i54b_PYu0FL7b5eHUkSX4fZP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees vs. 51s Bees vs. 51s

Follow on MiLB First Pitch  https //stza.co/+wmOw-2B

Shop  https //stza.co/+wmOw-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. 51s
END:VALARM
DTSTART:20180717T010500Z
DTEND:20180717T040500Z
UID:i54b_PYu0FL7b5eHUkSX4fZP@stanza.co
SUMMARY:Bees vs. 51s
DESCRIPTION:Bees vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+wmOw-2B\n\nShop: https://stza.co/+wmOw-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. 51s
<2018-07-17 Tue 20:05-23:05>
:PROPERTIES:
:ID:       tXLZpzvQDXI_rN832BY735JL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. 51s Bees vs. 51s

Follow on MiLB First Pitch  https //stza.co/+wmOz-2v

Shop  https //stza.co/+wmOz-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. 51s
END:VALARM
DTSTART:20180718T010500Z
DTEND:20180718T040500Z
UID:tXLZpzvQDXI_rN832BY735JL@stanza.co
SUMMARY:Bees vs. 51s
DESCRIPTION:Bees vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+wmOz-2v\n\nShop: https://stza.co/+wmOz-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. 51s
<2018-07-18 Wed 20:05-23:05>
:PROPERTIES:
:ID:       CWNskwTulvDdQHbsvPoZwES4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. 51s Bees vs. 51s

Follow on MiLB First Pitch  https //stza.co/+wmOA-34

Shop  https //stza.co/+wmOA-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. 51s
END:VALARM
DTSTART:20180719T010500Z
DTEND:20180719T040500Z
UID:CWNskwTulvDdQHbsvPoZwES4@stanza.co
SUMMARY:Bees vs. 51s
DESCRIPTION:Bees vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+wmOA-34\n\nShop: https://stza.co/+wmOA-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. 51s
<2018-07-19 Thu 20:05-23:05>
:PROPERTIES:
:ID:       IJbEJNy5Bw3dytaXDX-QKWQC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees vs. 51s Bees vs. 51s

Follow on MiLB First Pitch  https //stza.co/+wmOC-Q

Shop  https //stza.co/+wmOC-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. 51s
END:VALARM
DTSTART:20180720T010500Z
DTEND:20180720T040500Z
UID:IJbEJNy5Bw3dytaXDX-QKWQC@stanza.co
SUMMARY:Bees vs. 51s
DESCRIPTION:Bees vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+wmOC-Q\n\nShop: https://stza.co/+wmOC-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Rainiers
<2018-07-20 Fri 21:05>--<2018-07-21 Sat 00:05>
:PROPERTIES:
:ID:       mSiAncH-ibX7ntBhI4w7ZlKk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Rainiers Bees @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjN_-2Y

Shop  https //stza.co/+wjN_-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Rainiers
END:VALARM
DTSTART:20180721T020500Z
DTEND:20180721T050500Z
UID:mSiAncH-ibX7ntBhI4w7ZlKk@stanza.co
SUMMARY:Bees @ Rainiers
DESCRIPTION:Bees @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjN_-2Y\n\nShop: https://stza.co/+wjN_-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Rainiers
<2018-07-21 Sat 21:05>--<2018-07-22 Sun 00:05>
:PROPERTIES:
:ID:       xYh-XUf2ZEEJXpeALSp2hkxJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Rainiers Bees @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjN$-3S

Shop  https //stza.co/+wjN$-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Rainiers
END:VALARM
DTSTART:20180722T020500Z
DTEND:20180722T050500Z
UID:xYh-XUf2ZEEJXpeALSp2hkxJ@stanza.co
SUMMARY:Bees @ Rainiers
DESCRIPTION:Bees @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjN$-3S\n\nShop: https://stza.co/+wjN$-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Rainiers
<2018-07-22 Sun 15:35-18:35>
:PROPERTIES:
:ID:       GivZreNSwgR25DPd-73VMdvT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees @ Rainiers Bees @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjO1-2e

Shop  https //stza.co/+wjO1-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Rainiers
END:VALARM
DTSTART:20180722T203500Z
DTEND:20180722T233500Z
UID:GivZreNSwgR25DPd-73VMdvT@stanza.co
SUMMARY:Bees @ Rainiers
DESCRIPTION:Bees @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjO1-2e\n\nShop: https://stza.co/+wjO1-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Redbirds
<2018-07-24 Tue 19:35-22:35>
:PROPERTIES:
:ID:       fLdEsxaCo7s4h9w7chhV_Dty@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Redbirds Bees vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmOE-x

Shop  https //stza.co/+wmOE-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Redbirds
END:VALARM
DTSTART:20180725T003500Z
DTEND:20180725T033500Z
UID:fLdEsxaCo7s4h9w7chhV_Dty@stanza.co
SUMMARY:Bees vs. Redbirds
DESCRIPTION:Bees vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmOE-x\n\nShop: https://stza.co/+wmOE-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Redbirds
<2018-07-25 Wed 20:05-23:05>
:PROPERTIES:
:ID:       8ZQ8QtUPl45aL0FshvWvuEBy@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Redbirds Bees vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmOH-38

Shop  https //stza.co/+wmOH-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Redbirds
END:VALARM
DTSTART:20180726T010500Z
DTEND:20180726T040500Z
UID:8ZQ8QtUPl45aL0FshvWvuEBy@stanza.co
SUMMARY:Bees vs. Redbirds
DESCRIPTION:Bees vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmOH-38\n\nShop: https://stza.co/+wmOH-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Redbirds
<2018-07-26 Thu 20:05-23:05>
:PROPERTIES:
:ID:       TL7RtYxMVOqcdqPXVx-pdy8S@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees vs. Redbirds Bees vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmOI-3J

Shop  https //stza.co/+wmOI-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Redbirds
END:VALARM
DTSTART:20180727T010500Z
DTEND:20180727T040500Z
UID:TL7RtYxMVOqcdqPXVx-pdy8S@stanza.co
SUMMARY:Bees vs. Redbirds
DESCRIPTION:Bees vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmOI-3J\n\nShop: https://stza.co/+wmOI-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Sounds
<2018-07-27 Fri 19:35-22:35>
:PROPERTIES:
:ID:       as9r4hgIsL9D2AumlVSZOV_E@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Sounds Bees vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+wmOL-3e

Shop  https //stza.co/+wmOL-1J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Sounds
END:VALARM
DTSTART:20180728T003500Z
DTEND:20180728T033500Z
UID:as9r4hgIsL9D2AumlVSZOV_E@stanza.co
SUMMARY:Bees vs. Sounds
DESCRIPTION:Bees vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+wmOL-3e\n\nShop: https://stza.co/+wmOL-1J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Sounds
<2018-07-28 Sat 19:35-22:35>
:PROPERTIES:
:ID:       s-TzIS4rGvGAPlqaH6Zi0aLN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Sounds Bees vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+wmOM-m

Shop  https //stza.co/+wmOM-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Sounds
END:VALARM
DTSTART:20180729T003500Z
DTEND:20180729T033500Z
UID:s-TzIS4rGvGAPlqaH6Zi0aLN@stanza.co
SUMMARY:Bees vs. Sounds
DESCRIPTION:Bees vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+wmOM-m\n\nShop: https://stza.co/+wmOM-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Sounds
<2018-07-29 Sun 19:05-22:05>
:PROPERTIES:
:ID:       o0SgG5fMEqrXm_cPT0GzGpAn@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees vs. Sounds Bees vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+wmOO-1T

Shop  https //stza.co/+wmOO-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Sounds
END:VALARM
DTSTART:20180730T000500Z
DTEND:20180730T030500Z
UID:o0SgG5fMEqrXm_cPT0GzGpAn@stanza.co
SUMMARY:Bees vs. Sounds
DESCRIPTION:Bees vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+wmOO-1T\n\nShop: https://stza.co/+wmOO-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Sounds
<2018-07-30 Mon 20:05-23:05>
:PROPERTIES:
:ID:       QjaKq75GdMKT03T_bOLzro3F@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Sounds Bees vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+wmOQ-1q

Shop  https //stza.co/+wmOQ-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Sounds
END:VALARM
DTSTART:20180731T010500Z
DTEND:20180731T040500Z
UID:QjaKq75GdMKT03T_bOLzro3F@stanza.co
SUMMARY:Bees vs. Sounds
DESCRIPTION:Bees vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+wmOQ-1q\n\nShop: https://stza.co/+wmOQ-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Cubs
<2018-08-01 Wed 19:08-22:08>
:PROPERTIES:
:ID:       ksoEVUnq_si4esFahrFFzN3R@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Cubs Bees @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vK$H-c

Shop  https //stza.co/+vK$H-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Cubs
END:VALARM
DTSTART:20180802T000800Z
DTEND:20180802T030800Z
UID:ksoEVUnq_si4esFahrFFzN3R@stanza.co
SUMMARY:Bees @ Cubs
DESCRIPTION:Bees @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vK$H-c\n\nShop: https://stza.co/+vK$H-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Cubs
<2018-08-02 Thu 19:08-22:08>
:PROPERTIES:
:ID:       65zWDOTzIM7ZAo4AGVI2KM7R@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees @ Cubs Bees @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vK$I-3L

Shop  https //stza.co/+vK$I-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Cubs
END:VALARM
DTSTART:20180803T000800Z
DTEND:20180803T030800Z
UID:65zWDOTzIM7ZAo4AGVI2KM7R@stanza.co
SUMMARY:Bees @ Cubs
DESCRIPTION:Bees @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vK$I-3L\n\nShop: https://stza.co/+vK$I-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Cubs
<2018-08-03 Fri 19:08-22:08>
:PROPERTIES:
:ID:       Y6G0QrCow33bXRpKZxgPkP8P@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Cubs Bees @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vK$J-1v

Shop  https //stza.co/+vK$J-1w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Cubs
END:VALARM
DTSTART:20180804T000800Z
DTEND:20180804T030800Z
UID:Y6G0QrCow33bXRpKZxgPkP8P@stanza.co
SUMMARY:Bees @ Cubs
DESCRIPTION:Bees @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vK$J-1v\n\nShop: https://stza.co/+vK$J-1w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Storm Chasers
<2018-08-04 Sat 18:05-21:05>
:PROPERTIES:
:ID:       lETElntMOoJ8KxuPJfHjh04S@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Storm Chasers Bees @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+wPGZ-29

Shop  https //stza.co/+wPGZ-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Storm Chasers
END:VALARM
DTSTART:20180804T230500Z
DTEND:20180805T020500Z
UID:lETElntMOoJ8KxuPJfHjh04S@stanza.co
SUMMARY:Bees @ Storm Chasers
DESCRIPTION:Bees @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+wPGZ-29\n\nShop: https://stza.co/+wPGZ-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Storm Chasers
<2018-08-05 Sun 17:05-20:05>
:PROPERTIES:
:ID:       tEutxC5JITkFV8G6a9jQ2_Zx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees @ Storm Chasers Bees @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whRO-M

Shop  https //stza.co/+whRO-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Storm Chasers
END:VALARM
DTSTART:20180805T220500Z
DTEND:20180806T010500Z
UID:tEutxC5JITkFV8G6a9jQ2_Zx@stanza.co
SUMMARY:Bees @ Storm Chasers
DESCRIPTION:Bees @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whRO-M\n\nShop: https://stza.co/+whRO-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Storm Chasers
<2018-08-06 Mon 19:05-22:05>
:PROPERTIES:
:ID:       iveJJpVFoA8vjNM-i7ywrB6q@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Storm Chasers Bees @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whRP-L

Shop  https //stza.co/+whRP-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Storm Chasers
END:VALARM
DTSTART:20180807T000500Z
DTEND:20180807T030500Z
UID:iveJJpVFoA8vjNM-i7ywrB6q@stanza.co
SUMMARY:Bees @ Storm Chasers
DESCRIPTION:Bees @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whRP-L\n\nShop: https://stza.co/+whRP-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Storm Chasers
<2018-08-07 Tue 12:05-15:05>
:PROPERTIES:
:ID:       Oo0_yKlEcOI8ML6ajgDqbgUd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Storm Chasers Bees @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whRQ-1u

Shop  https //stza.co/+whRQ-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Storm Chasers
END:VALARM
DTSTART:20180807T170500Z
DTEND:20180807T200500Z
UID:Oo0_yKlEcOI8ML6ajgDqbgUd@stanza.co
SUMMARY:Bees @ Storm Chasers
DESCRIPTION:Bees @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whRQ-1u\n\nShop: https://stza.co/+whRQ-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Rainiers
<2018-08-09 Thu 20:05-23:05>
:PROPERTIES:
:ID:       Nepdjg-Iv6LAhv7FcwYwFqyR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees vs. Rainiers Bees vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+wmOU-3a

Shop  https //stza.co/+wmOU-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Rainiers
END:VALARM
DTSTART:20180810T010500Z
DTEND:20180810T040500Z
UID:Nepdjg-Iv6LAhv7FcwYwFqyR@stanza.co
SUMMARY:Bees vs. Rainiers
DESCRIPTION:Bees vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wmOU-3a\n\nShop: https://stza.co/+wmOU-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Rainiers
<2018-08-10 Fri 20:05-23:05>
:PROPERTIES:
:ID:       uGeaKDx7g_YnvKogVuumnFKy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Rainiers Bees vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+wmOW-3C

Shop  https //stza.co/+wmOW-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Rainiers
END:VALARM
DTSTART:20180811T010500Z
DTEND:20180811T040500Z
UID:uGeaKDx7g_YnvKogVuumnFKy@stanza.co
SUMMARY:Bees vs. Rainiers
DESCRIPTION:Bees vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wmOW-3C\n\nShop: https://stza.co/+wmOW-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Rainiers
<2018-08-11 Sat 19:35-22:35>
:PROPERTIES:
:ID:       VVqAJITrpydUIhEZUikwrd6W@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Rainiers Bees vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+wmOY-4

Shop  https //stza.co/+wmOY-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Rainiers
END:VALARM
DTSTART:20180812T003500Z
DTEND:20180812T033500Z
UID:VVqAJITrpydUIhEZUikwrd6W@stanza.co
SUMMARY:Bees vs. Rainiers
DESCRIPTION:Bees vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wmOY-4\n\nShop: https://stza.co/+wmOY-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Rainiers
<2018-08-12 Sun 19:05-22:05>
:PROPERTIES:
:ID:       rKb1a1IyMvo9o3oeXGRRenFs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees vs. Rainiers Bees vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+wmO$-

Shop  https //stza.co/+wmO$-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Rainiers
END:VALARM
DTSTART:20180813T000500Z
DTEND:20180813T030500Z
UID:rKb1a1IyMvo9o3oeXGRRenFs@stanza.co
SUMMARY:Bees vs. Rainiers
DESCRIPTION:Bees vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wmO$-\n\nShop: https://stza.co/+wmO$-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Chihuahuas
<2018-08-13 Mon 20:05-23:05>
:PROPERTIES:
:ID:       A8gkPLveGwDZ5q2LzedwO3va@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Chihuahuas Bees vs. Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmP1-2m

Shop  https //stza.co/+wmP1-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Chihuahuas
END:VALARM
DTSTART:20180814T010500Z
DTEND:20180814T040500Z
UID:A8gkPLveGwDZ5q2LzedwO3va@stanza.co
SUMMARY:Bees vs. Chihuahuas
DESCRIPTION:Bees vs. Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmP1-2m\n\nShop: https://stza.co/+wmP1-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Chihuahuas
<2018-08-14 Tue 20:05-23:05>
:PROPERTIES:
:ID:       PLDMfGgLFoWTHcgV62Bqbvo5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Chihuahuas Bees vs. Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmP3-16

Shop  https //stza.co/+wmP3-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Chihuahuas
END:VALARM
DTSTART:20180815T010500Z
DTEND:20180815T040500Z
UID:PLDMfGgLFoWTHcgV62Bqbvo5@stanza.co
SUMMARY:Bees vs. Chihuahuas
DESCRIPTION:Bees vs. Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmP3-16\n\nShop: https://stza.co/+wmP3-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Chihuahuas
<2018-08-15 Wed 20:05-23:05>
:PROPERTIES:
:ID:       TdtMwYBSuo4NYTF744_03AB8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees vs. Chihuahuas Bees vs. Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmP5-2d

Shop  https //stza.co/+wmP5-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Chihuahuas
END:VALARM
DTSTART:20180816T010500Z
DTEND:20180816T040500Z
UID:TdtMwYBSuo4NYTF744_03AB8@stanza.co
SUMMARY:Bees vs. Chihuahuas
DESCRIPTION:Bees vs. Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmP5-2d\n\nShop: https://stza.co/+wmP5-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Aces
<2018-08-16 Thu 21:05>--<2018-08-17 Fri 00:05>
:PROPERTIES:
:ID:       -cYpTeOHfuTuJR7EBMZc-W0T@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Aces Bees @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjNF-e

Shop  https //stza.co/+wjNF-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Aces
END:VALARM
DTSTART:20180817T020500Z
DTEND:20180817T050500Z
UID:-cYpTeOHfuTuJR7EBMZc-W0T@stanza.co
SUMMARY:Bees @ Aces
DESCRIPTION:Bees @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjNF-e\n\nShop: https://stza.co/+wjNF-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Aces
<2018-08-17 Fri 21:05>--<2018-08-18 Sat 00:05>
:PROPERTIES:
:ID:       jmQw41nNrGmOpMcGjL6ggzbf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Aces Bees @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjNG-3s

Shop  https //stza.co/+wjNG-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Aces
END:VALARM
DTSTART:20180818T020500Z
DTEND:20180818T050500Z
UID:jmQw41nNrGmOpMcGjL6ggzbf@stanza.co
SUMMARY:Bees @ Aces
DESCRIPTION:Bees @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjNG-3s\n\nShop: https://stza.co/+wjNG-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Aces
<2018-08-18 Sat 21:05>--<2018-08-19 Sun 00:05>
:PROPERTIES:
:ID:       C9MiAtBnOTylmWhX_xxzZ_P_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees @ Aces Bees @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjNH-2H

Shop  https //stza.co/+wjNH-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Aces
END:VALARM
DTSTART:20180819T020500Z
DTEND:20180819T050500Z
UID:C9MiAtBnOTylmWhX_xxzZ_P_@stanza.co
SUMMARY:Bees @ Aces
DESCRIPTION:Bees @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjNH-2H\n\nShop: https://stza.co/+wjNH-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Aces
<2018-08-19 Sun 15:05-18:05>
:PROPERTIES:
:ID:       JgnxVpFKs0LJLX-19ef5Vgss@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Aces Bees @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjNI-3f

Shop  https //stza.co/+wjNI-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Aces
END:VALARM
DTSTART:20180819T200500Z
DTEND:20180819T230500Z
UID:JgnxVpFKs0LJLX-19ef5Vgss@stanza.co
SUMMARY:Bees @ Aces
DESCRIPTION:Bees @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjNI-3f\n\nShop: https://stza.co/+wjNI-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ 51s
<2018-08-21 Tue 21:05>--<2018-08-22 Wed 00:05>
:PROPERTIES:
:ID:       b9CKsIB4EY5Dih0Fm-4uhJgj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ 51s Bees @ 51s

Follow on MiLB First Pitch  https //stza.co/+vK$P-5

Shop  https //stza.co/+vK$P-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ 51s
END:VALARM
DTSTART:20180822T020500Z
DTEND:20180822T050500Z
UID:b9CKsIB4EY5Dih0Fm-4uhJgj@stanza.co
SUMMARY:Bees @ 51s
DESCRIPTION:Bees @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vK$P-5\n\nShop: https://stza.co/+vK$P-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ 51s
<2018-08-22 Wed 21:05>--<2018-08-23 Thu 00:05>
:PROPERTIES:
:ID:       fN6bWQlSBjkELPl_NTLCHAsJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees @ 51s Bees @ 51s

Follow on MiLB First Pitch  https //stza.co/+vK$Q-w

Shop  https //stza.co/+vK$Q-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ 51s
END:VALARM
DTSTART:20180823T020500Z
DTEND:20180823T050500Z
UID:fN6bWQlSBjkELPl_NTLCHAsJ@stanza.co
SUMMARY:Bees @ 51s
DESCRIPTION:Bees @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vK$Q-w\n\nShop: https://stza.co/+vK$Q-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ 51s
<2018-08-23 Thu 21:05>--<2018-08-24 Fri 00:05>
:PROPERTIES:
:ID:       BGFe-2Q1QHn-WE4pNFk2XYPl@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ 51s Bees @ 51s

Follow on MiLB First Pitch  https //stza.co/+vK$R-39

Shop  https //stza.co/+vK$R-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ 51s
END:VALARM
DTSTART:20180824T020500Z
DTEND:20180824T050500Z
UID:BGFe-2Q1QHn-WE4pNFk2XYPl@stanza.co
SUMMARY:Bees @ 51s
DESCRIPTION:Bees @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vK$R-39\n\nShop: https://stza.co/+vK$R-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Grizzlies
<2018-08-24 Fri 21:05>--<2018-08-25 Sat 00:05>
:PROPERTIES:
:ID:       ywr4U4lNGCW7-AXBaWy4oAza@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Grizzlies Bees @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjNv-3G

Shop  https //stza.co/+wjNv-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Grizzlies
END:VALARM
DTSTART:20180825T020500Z
DTEND:20180825T050500Z
UID:ywr4U4lNGCW7-AXBaWy4oAza@stanza.co
SUMMARY:Bees @ Grizzlies
DESCRIPTION:Bees @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjNv-3G\n\nShop: https://stza.co/+wjNv-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Grizzlies
<2018-08-25 Sat 21:05>--<2018-08-26 Sun 00:05>
:PROPERTIES:
:ID:       Q6aYDU28QjDOVt8LsaBhhodn@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees @ Grizzlies Bees @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjNx-3l

Shop  https //stza.co/+wjNx-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Grizzlies
END:VALARM
DTSTART:20180826T020500Z
DTEND:20180826T050500Z
UID:Q6aYDU28QjDOVt8LsaBhhodn@stanza.co
SUMMARY:Bees @ Grizzlies
DESCRIPTION:Bees @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjNx-3l\n\nShop: https://stza.co/+wjNx-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Grizzlies
<2018-08-26 Sun 19:05-22:05>
:PROPERTIES:
:ID:       T6gg2J6FoWoVdzMaV2Z9GO9r@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Grizzlies Bees @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjNy-1_

Shop  https //stza.co/+wjNy-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Grizzlies
END:VALARM
DTSTART:20180827T000500Z
DTEND:20180827T030500Z
UID:T6gg2J6FoWoVdzMaV2Z9GO9r@stanza.co
SUMMARY:Bees @ Grizzlies
DESCRIPTION:Bees @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjNy-1_\n\nShop: https://stza.co/+wjNy-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees @ Grizzlies
<2018-08-27 Mon 21:05>--<2018-08-28 Tue 00:05>
:PROPERTIES:
:ID:       GEBPLv9x7qsoXq3WFTlS9OJF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees @ Grizzlies Bees @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjNz-2b

Shop  https //stza.co/+wjNz-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Bees @ Grizzlies
END:VALARM
DTSTART:20180828T020500Z
DTEND:20180828T050500Z
UID:GEBPLv9x7qsoXq3WFTlS9OJF@stanza.co
SUMMARY:Bees @ Grizzlies
DESCRIPTION:Bees @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjNz-2b\n\nShop: https://stza.co/+wjNz-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Aces
<2018-08-28 Tue 20:05-23:05>
:PROPERTIES:
:ID:       RbMj8N1ikTorywTKSQeSwAFL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees vs. Aces Bees vs. Aces

Follow on MiLB First Pitch  https //stza.co/+wmP7-3J

Shop  https //stza.co/+wmP7-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Aces
END:VALARM
DTSTART:20180829T010500Z
DTEND:20180829T040500Z
UID:RbMj8N1ikTorywTKSQeSwAFL@stanza.co
SUMMARY:Bees vs. Aces
DESCRIPTION:Bees vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wmP7-3J\n\nShop: https://stza.co/+wmP7-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Aces
<2018-08-29 Wed 20:05-23:05>
:PROPERTIES:
:ID:       G3gWyizLIcVevhEt7blbDyjl@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Aces Bees vs. Aces

Follow on MiLB First Pitch  https //stza.co/+wmP9-2R

Shop  https //stza.co/+wmP9-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Aces
END:VALARM
DTSTART:20180830T010500Z
DTEND:20180830T040500Z
UID:G3gWyizLIcVevhEt7blbDyjl@stanza.co
SUMMARY:Bees vs. Aces
DESCRIPTION:Bees vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wmP9-2R\n\nShop: https://stza.co/+wmP9-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Aces
<2018-08-30 Thu 20:05-23:05>
:PROPERTIES:
:ID:       rg7Avo9grIhYAKwskTgNxbwt@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Aces Bees vs. Aces

Follow on MiLB First Pitch  https //stza.co/+wmPb-3p

Shop  https //stza.co/+wmPb-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Aces
END:VALARM
DTSTART:20180831T010500Z
DTEND:20180831T040500Z
UID:rg7Avo9grIhYAKwskTgNxbwt@stanza.co
SUMMARY:Bees vs. Aces
DESCRIPTION:Bees vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wmPb-3p\n\nShop: https://stza.co/+wmPb-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Grizzlies
<2018-08-31 Fri 19:35-22:35>
:PROPERTIES:
:ID:       TIP3egI7RlYqKnkHmUOtRysf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees vs. Grizzlies Bees vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wmPd-3n

Shop  https //stza.co/+wmPd-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Grizzlies
END:VALARM
DTSTART:20180901T003500Z
DTEND:20180901T033500Z
UID:TIP3egI7RlYqKnkHmUOtRysf@stanza.co
SUMMARY:Bees vs. Grizzlies
DESCRIPTION:Bees vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wmPd-3n\n\nShop: https://stza.co/+wmPd-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Grizzlies
<2018-09-01 Sat 20:05-23:05>
:PROPERTIES:
:ID:       SOa3rwNzshCDyr-p1P--pJ9D@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Grizzlies Bees vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wmPf-1r

Shop  https //stza.co/+wmPf-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Grizzlies
END:VALARM
DTSTART:20180902T010500Z
DTEND:20180902T040500Z
UID:SOa3rwNzshCDyr-p1P--pJ9D@stanza.co
SUMMARY:Bees vs. Grizzlies
DESCRIPTION:Bees vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wmPf-1r\n\nShop: https://stza.co/+wmPf-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Grizzlies
<2018-09-02 Sun 19:05-22:05>
:PROPERTIES:
:ID:       WFq5iZJ7_vMBWw5BfBGF57iF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Bees vs. Grizzlies Bees vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wmPi-2x

Shop  https //stza.co/+wmPi-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Grizzlies
END:VALARM
DTSTART:20180903T000500Z
DTEND:20180903T030500Z
UID:WFq5iZJ7_vMBWw5BfBGF57iF@stanza.co
SUMMARY:Bees vs. Grizzlies
DESCRIPTION:Bees vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wmPi-2x\n\nShop: https://stza.co/+wmPi-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Bees vs. Grizzlies
<2018-09-03 Mon 13:05-16:05>
:PROPERTIES:
:ID:       TlChmWOJrskNqERumZ62mCwU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Bees vs. Grizzlies Bees vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wmPj-2n

Shop  https //stza.co/+wmPj-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Bees vs. Grizzlies
END:VALARM
DTSTART:20180903T180500Z
DTEND:20180903T210500Z
UID:TlChmWOJrskNqERumZ62mCwU@stanza.co
SUMMARY:Bees vs. Grizzlies
DESCRIPTION:Bees vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wmPj-2n\n\nShop: https://stza.co/+wmPj-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
