#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Baysox vs. Senators
<2018-04-05 Thu 17:35-20:35>
:PROPERTIES:
:ID:       zHu-dN19Pi76PG-MRAetL6yZ@stanza.co
:LOCATION: Opening Night & 2018 Baysox Magnet Schedule Giveaway
:STATUS:   CONFIRMED
:END:

Baysox vs. Senators Welcome to Opening Night of the 2018 season! All fans entering the stadium will receive a 2018 Baysox Magnet Schedule!

Follow on MiLB First Pitch  https //stza.co/+vLb8-a

Shop  https //stza.co/+vLb8-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Senators
END:VALARM
DTSTART:20180405T223500Z
DTEND:20180406T013500Z
UID:zHu-dN19Pi76PG-MRAetL6yZ@stanza.co
SUMMARY:Baysox vs. Senators
DESCRIPTION:Welcome to Opening Night of the 2018 season! All fans entering the stadium will receive a 2018 Baysox Magnet Schedule!\n\nFollow on MiLB First Pitch: https://stza.co/+vLb8-a\n\nShop: https://stza.co/+vLb8-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Opening Night & 2018 Baysox Magnet Schedule Giveaway
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Senators
<2018-04-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       DWDMULrP7LRUdtlErFCy5_zt@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox vs. Senators Baysox vs. Senators

Follow on MiLB First Pitch  https //stza.co/+vLba-

Shop  https //stza.co/+vLba-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Senators
END:VALARM
DTSTART:20180406T230500Z
DTEND:20180407T020500Z
UID:DWDMULrP7LRUdtlErFCy5_zt@stanza.co
SUMMARY:Baysox vs. Senators
DESCRIPTION:Baysox vs. Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLba-\n\nShop: https://stza.co/+vLba-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Senators
<2018-04-07 Sat 12:35-15:35>
:PROPERTIES:
:ID:       G82iHJgnN5tJlNVLHZho7VJQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox vs. Senators Baysox vs. Senators

Follow on MiLB First Pitch  https //stza.co/+vLbc-3X

Shop  https //stza.co/+vLbc-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Senators
END:VALARM
DTSTART:20180407T173500Z
DTEND:20180407T203500Z
UID:G82iHJgnN5tJlNVLHZho7VJQ@stanza.co
SUMMARY:Baysox vs. Senators
DESCRIPTION:Baysox vs. Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLbc-3X\n\nShop: https://stza.co/+vLbc-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Senators
<2018-04-08 Sun 12:35-15:35>
:PROPERTIES:
:ID:       N0fmSRfOLZMRaFZDUYfEz_sD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox vs. Senators Baysox vs. Senators

Follow on MiLB First Pitch  https //stza.co/+vLbf-2I

Shop  https //stza.co/+vLbf-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Senators
END:VALARM
DTSTART:20180408T173500Z
DTEND:20180408T203500Z
UID:N0fmSRfOLZMRaFZDUYfEz_sD@stanza.co
SUMMARY:Baysox vs. Senators
DESCRIPTION:Baysox vs. Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLbf-2I\n\nShop: https://stza.co/+vLbf-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. SeaWolves
<2018-04-09 Mon 17:35-20:35>
:PROPERTIES:
:ID:       GB3UDwzn2gedYniI_Zp3B4An@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox vs. SeaWolves Baysox vs. SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLbh-d

Shop  https //stza.co/+vLbh-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. SeaWolves
END:VALARM
DTSTART:20180409T223500Z
DTEND:20180410T013500Z
UID:GB3UDwzn2gedYniI_Zp3B4An@stanza.co
SUMMARY:Baysox vs. SeaWolves
DESCRIPTION:Baysox vs. SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLbh-d\n\nShop: https://stza.co/+vLbh-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. SeaWolves
<2018-04-10 Tue 17:35-20:35>
:PROPERTIES:
:ID:       eBf_as-ooJMLMEC7rb0QvHJE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox vs. SeaWolves Baysox vs. SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLbj-3U

Shop  https //stza.co/+vLbj-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. SeaWolves
END:VALARM
DTSTART:20180410T223500Z
DTEND:20180411T013500Z
UID:eBf_as-ooJMLMEC7rb0QvHJE@stanza.co
SUMMARY:Baysox vs. SeaWolves
DESCRIPTION:Baysox vs. SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLbj-3U\n\nShop: https://stza.co/+vLbj-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. SeaWolves
<2018-04-11 Wed 17:35-20:35>
:PROPERTIES:
:ID:       2u9HzFtqlHcFX_6lopO-hRFc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox vs. SeaWolves Baysox vs. SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLbk-3J

Shop  https //stza.co/+vLbk-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. SeaWolves
END:VALARM
DTSTART:20180411T223500Z
DTEND:20180412T013500Z
UID:2u9HzFtqlHcFX_6lopO-hRFc@stanza.co
SUMMARY:Baysox vs. SeaWolves
DESCRIPTION:Baysox vs. SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLbk-3J\n\nShop: https://stza.co/+vLbk-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Senators
<2018-04-13 Fri 18:00-21:00>
:PROPERTIES:
:ID:       VZJmUdyBWj_PQlc6Fblr9xXr@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Senators Baysox @ Senators

Follow on MiLB First Pitch  https //stza.co/+vLdv-1U

Shop  https //stza.co/+vLdv-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Senators
END:VALARM
DTSTART:20180413T230000Z
DTEND:20180414T020000Z
UID:VZJmUdyBWj_PQlc6Fblr9xXr@stanza.co
SUMMARY:Baysox @ Senators
DESCRIPTION:Baysox @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLdv-1U\n\nShop: https://stza.co/+vLdv-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Senators
<2018-04-14 Sat 17:00-20:00>
:PROPERTIES:
:ID:       Jb4bMZ158OS0aT3LAX2_UMnl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox @ Senators Baysox @ Senators

Follow on MiLB First Pitch  https //stza.co/+vLdw-3K

Shop  https //stza.co/+vLdw-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Senators
END:VALARM
DTSTART:20180414T220000Z
DTEND:20180415T010000Z
UID:Jb4bMZ158OS0aT3LAX2_UMnl@stanza.co
SUMMARY:Baysox @ Senators
DESCRIPTION:Baysox @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLdw-3K\n\nShop: https://stza.co/+vLdw-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Senators
<2018-04-15 Sun 12:30-15:30>
:PROPERTIES:
:ID:       RPBwKGftgerTgVJtZJpxSzqa@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Senators Baysox @ Senators

Follow on MiLB First Pitch  https //stza.co/+vLdx-3s

Shop  https //stza.co/+vLdx-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Senators
END:VALARM
DTSTART:20180415T173000Z
DTEND:20180415T203000Z
UID:RPBwKGftgerTgVJtZJpxSzqa@stanza.co
SUMMARY:Baysox @ Senators
DESCRIPTION:Baysox @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLdx-3s\n\nShop: https://stza.co/+vLdx-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Flying Squirrels
<2018-04-16 Mon 17:35-20:35>
:PROPERTIES:
:ID:       zRWIkWftaSlgQKuczhGX5el3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Flying Squirrels Baysox @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vLdS-2$

Shop  https //stza.co/+vLdS-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Flying Squirrels
END:VALARM
DTSTART:20180416T223500Z
DTEND:20180417T013500Z
UID:zRWIkWftaSlgQKuczhGX5el3@stanza.co
SUMMARY:Baysox @ Flying Squirrels
DESCRIPTION:Baysox @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vLdS-2$\n\nShop: https://stza.co/+vLdS-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Flying Squirrels
<2018-04-17 Tue 17:35-20:35>
:PROPERTIES:
:ID:       FxU6E9gjrWKg2hp4b0G082W_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox @ Flying Squirrels Baysox @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vLdT-P

Shop  https //stza.co/+vLdT-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Flying Squirrels
END:VALARM
DTSTART:20180417T223500Z
DTEND:20180418T013500Z
UID:FxU6E9gjrWKg2hp4b0G082W_@stanza.co
SUMMARY:Baysox @ Flying Squirrels
DESCRIPTION:Baysox @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vLdT-P\n\nShop: https://stza.co/+vLdT-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Flying Squirrels
<2018-04-18 Wed 17:35-20:35>
:PROPERTIES:
:ID:       c0c-26J0DQ_NO0tpZETG2QVI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Flying Squirrels Baysox @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vLdU-1m

Shop  https //stza.co/+vLdU-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Flying Squirrels
END:VALARM
DTSTART:20180418T223500Z
DTEND:20180419T013500Z
UID:c0c-26J0DQ_NO0tpZETG2QVI@stanza.co
SUMMARY:Baysox @ Flying Squirrels
DESCRIPTION:Baysox @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vLdU-1m\n\nShop: https://stza.co/+vLdU-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Flying Squirrels
<2018-04-19 Thu 09:35-12:35>
:PROPERTIES:
:ID:       8xRZy9Hcm1k_TQ5Jv4NGyw3S@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Flying Squirrels Baysox @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vLdV-3

Shop  https //stza.co/+vLdV-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Flying Squirrels
END:VALARM
DTSTART:20180419T143500Z
DTEND:20180419T173500Z
UID:8xRZy9Hcm1k_TQ5Jv4NGyw3S@stanza.co
SUMMARY:Baysox @ Flying Squirrels
DESCRIPTION:Baysox @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vLdV-3\n\nShop: https://stza.co/+vLdV-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. RubberDucks
<2018-04-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       Dx_mSALTztijEqVgm8pYOpBd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox vs. RubberDucks Baysox vs. RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLbn-25

Shop  https //stza.co/+vLbn-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. RubberDucks
END:VALARM
DTSTART:20180420T230500Z
DTEND:20180421T020500Z
UID:Dx_mSALTztijEqVgm8pYOpBd@stanza.co
SUMMARY:Baysox vs. RubberDucks
DESCRIPTION:Baysox vs. RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLbn-25\n\nShop: https://stza.co/+vLbn-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. RubberDucks
<2018-04-21 Sat 17:35-20:35>
:PROPERTIES:
:ID:       rC16JzgbuYJOLF5ThF4COy4M@stanza.co
:LOCATION: Stick around after tonight's game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Baysox vs. RubberDucks Enjoy the best Fireworks show in the region following the Baysox game!

Follow on MiLB First Pitch  https //stza.co/+vLbp-3f

Shop  https //stza.co/+vLbp-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. RubberDucks
END:VALARM
DTSTART:20180421T223500Z
DTEND:20180422T013500Z
UID:rC16JzgbuYJOLF5ThF4COy4M@stanza.co
SUMMARY:Baysox vs. RubberDucks
DESCRIPTION:Enjoy the best Fireworks show in the region following the Baysox game!\n\nFollow on MiLB First Pitch: https://stza.co/+vLbp-3f\n\nShop: https://stza.co/+vLbp-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after tonight's game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. RubberDucks
<2018-04-22 Sun 12:35-15:35>
:PROPERTIES:
:ID:       krycPaS5zGXj1aRb0Rjaq7Bc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox vs. RubberDucks Baysox vs. RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLbr-2r

Shop  https //stza.co/+vLbr-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. RubberDucks
END:VALARM
DTSTART:20180422T173500Z
DTEND:20180422T203500Z
UID:krycPaS5zGXj1aRb0Rjaq7Bc@stanza.co
SUMMARY:Baysox vs. RubberDucks
DESCRIPTION:Baysox vs. RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLbr-2r\n\nShop: https://stza.co/+vLbr-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Flying Squirrels
<2018-04-23 Mon 17:35-20:35>
:PROPERTIES:
:ID:       DinkbnTo2jG-cKjrxmS_E4bZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox vs. Flying Squirrels Baysox vs. Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vLbs-2v

Shop  https //stza.co/+vLbs-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Flying Squirrels
END:VALARM
DTSTART:20180423T223500Z
DTEND:20180424T013500Z
UID:DinkbnTo2jG-cKjrxmS_E4bZ@stanza.co
SUMMARY:Baysox vs. Flying Squirrels
DESCRIPTION:Baysox vs. Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vLbs-2v\n\nShop: https://stza.co/+vLbs-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Flying Squirrels
<2018-04-24 Tue 17:35-20:35>
:PROPERTIES:
:ID:       GAJFPF0A1753xHuKDpghosLn@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox vs. Flying Squirrels Baysox vs. Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vLbu-2h

Shop  https //stza.co/+vLbu-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Flying Squirrels
END:VALARM
DTSTART:20180424T223500Z
DTEND:20180425T013500Z
UID:GAJFPF0A1753xHuKDpghosLn@stanza.co
SUMMARY:Baysox vs. Flying Squirrels
DESCRIPTION:Baysox vs. Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vLbu-2h\n\nShop: https://stza.co/+vLbu-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Flying Squirrels
<2018-04-25 Wed 10:05-13:05>
:PROPERTIES:
:ID:       ZZNDF0MZt0ljapN54S3w_gBV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox vs. Flying Squirrels Baysox vs. Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vLbw-2R

Shop  https //stza.co/+vLbw-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Flying Squirrels
END:VALARM
DTSTART:20180425T150500Z
DTEND:20180425T180500Z
UID:ZZNDF0MZt0ljapN54S3w_gBV@stanza.co
SUMMARY:Baysox vs. Flying Squirrels
DESCRIPTION:Baysox vs. Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vLbw-2R\n\nShop: https://stza.co/+vLbw-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ RubberDucks
<2018-04-27 Fri 17:35-20:35>
:PROPERTIES:
:ID:       bwvmJnjiFOPI3I856aU4hxXV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ RubberDucks Baysox @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLaQ-c

Shop  https //stza.co/+vLaQ-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ RubberDucks
END:VALARM
DTSTART:20180427T223500Z
DTEND:20180428T013500Z
UID:bwvmJnjiFOPI3I856aU4hxXV@stanza.co
SUMMARY:Baysox @ RubberDucks
DESCRIPTION:Baysox @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLaQ-c\n\nShop: https://stza.co/+vLaQ-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ RubberDucks
<2018-04-28 Sat 13:05-16:05>
:PROPERTIES:
:ID:       DxDW0-6gaJv6NfF5DdpFNzaO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox @ RubberDucks Baysox @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLaR-29

Shop  https //stza.co/+vLaR-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ RubberDucks
END:VALARM
DTSTART:20180428T180500Z
DTEND:20180428T210500Z
UID:DxDW0-6gaJv6NfF5DdpFNzaO@stanza.co
SUMMARY:Baysox @ RubberDucks
DESCRIPTION:Baysox @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLaR-29\n\nShop: https://stza.co/+vLaR-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ RubberDucks
<2018-04-29 Sun 13:05-16:05>
:PROPERTIES:
:ID:       X3lVKgCTgK95oAAWHyhkvBmY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ RubberDucks Baysox @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLaS-1Z

Shop  https //stza.co/+vLaS-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ RubberDucks
END:VALARM
DTSTART:20180429T180500Z
DTEND:20180429T210500Z
UID:X3lVKgCTgK95oAAWHyhkvBmY@stanza.co
SUMMARY:Baysox @ RubberDucks
DESCRIPTION:Baysox @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLaS-1Z\n\nShop: https://stza.co/+vLaS-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ SeaWolves
<2018-04-30 Mon 17:05-20:05>
:PROPERTIES:
:ID:       vIGAH77C6LKm18aC5kNDY0xc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ SeaWolves Baysox @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLdk-1a

Shop  https //stza.co/+vLdk-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ SeaWolves
END:VALARM
DTSTART:20180430T220500Z
DTEND:20180501T010500Z
UID:vIGAH77C6LKm18aC5kNDY0xc@stanza.co
SUMMARY:Baysox @ SeaWolves
DESCRIPTION:Baysox @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLdk-1a\n\nShop: https://stza.co/+vLdk-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ SeaWolves
<2018-05-01 Tue 17:05-20:05>
:PROPERTIES:
:ID:       wPfle9yaolP4mZ_QqiaK4CW6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox @ SeaWolves Baysox @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLdl-y

Shop  https //stza.co/+vLdl-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ SeaWolves
END:VALARM
DTSTART:20180501T220500Z
DTEND:20180502T010500Z
UID:wPfle9yaolP4mZ_QqiaK4CW6@stanza.co
SUMMARY:Baysox @ SeaWolves
DESCRIPTION:Baysox @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLdl-y\n\nShop: https://stza.co/+vLdl-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ SeaWolves
<2018-05-02 Wed 10:05-13:05>
:PROPERTIES:
:ID:       fUKjB38mfxI5Pucuh21u-Ilq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ SeaWolves Baysox @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLdm-4

Shop  https //stza.co/+vLdm-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ SeaWolves
END:VALARM
DTSTART:20180502T150500Z
DTEND:20180502T180500Z
UID:fUKjB38mfxI5Pucuh21u-Ilq@stanza.co
SUMMARY:Baysox @ SeaWolves
DESCRIPTION:Baysox @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLdm-4\n\nShop: https://stza.co/+vLdm-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. RubberDucks
<2018-05-03 Thu 17:35-20:35>
:PROPERTIES:
:ID:       tlrBqCGTb0DSnLXhq8N9aDdP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox vs. RubberDucks Baysox vs. RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLbz-3V

Shop  https //stza.co/+vLbz-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. RubberDucks
END:VALARM
DTSTART:20180503T223500Z
DTEND:20180504T013500Z
UID:tlrBqCGTb0DSnLXhq8N9aDdP@stanza.co
SUMMARY:Baysox vs. RubberDucks
DESCRIPTION:Baysox vs. RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLbz-3V\n\nShop: https://stza.co/+vLbz-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. RubberDucks
<2018-05-04 Fri 18:05-21:05>
:PROPERTIES:
:ID:       IEWsrMfZVEUCQioVfPMWUTC0@stanza.co
:LOCATION: Stick around after tonight's game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Baysox vs. RubberDucks Enjoy the best Fireworks show in the region following the Baysox game!

We recognize the students from Prince George's & Montgomery counties for their success in completing the Baysox Reading Program

Follow on MiLB First Pitch  https //stza.co/+vLbB-G

Shop  https //stza.co/+vLbB-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. RubberDucks
END:VALARM
DTSTART:20180504T230500Z
DTEND:20180505T020500Z
UID:IEWsrMfZVEUCQioVfPMWUTC0@stanza.co
SUMMARY:Baysox vs. RubberDucks
DESCRIPTION:Enjoy the best Fireworks show in the region following the Baysox game!\n\nWe recognize the students from Prince George's & Montgomery counties for their success in completing the Baysox Reading Program\n\nFollow on MiLB First Pitch: https://stza.co/+vLbB-G\n\nShop: https://stza.co/+vLbB-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after tonight's game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. RubberDucks
<2018-05-05 Sat 17:35-20:35>
:PROPERTIES:
:ID:       Ss5_ziJ0sNo-o8ZVg8sIDYRf@stanza.co
:LOCATION: Stick around after tonight's game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Baysox vs. RubberDucks Enjoy the best Fireworks show in the region following the Baysox game!

We recognize the students from Prince George's & Montgomery counties for their success in completing the Baysox Reading Program

Follow on MiLB First Pitch  https //stza.co/+vLbC-1A

Shop  https //stza.co/+vLbC-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. RubberDucks
END:VALARM
DTSTART:20180505T223500Z
DTEND:20180506T013500Z
UID:Ss5_ziJ0sNo-o8ZVg8sIDYRf@stanza.co
SUMMARY:Baysox vs. RubberDucks
DESCRIPTION:Enjoy the best Fireworks show in the region following the Baysox game!\n\nWe recognize the students from Prince George's & Montgomery counties for their success in completing the Baysox Reading Program\n\nFollow on MiLB First Pitch: https://stza.co/+vLbC-1A\n\nShop: https://stza.co/+vLbC-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after tonight's game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. RubberDucks
<2018-05-06 Sun 12:35-15:35>
:PROPERTIES:
:ID:       W5j7-_RcSLV08a0MuMmh_jHW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox vs. RubberDucks Baysox vs. RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLbF-8

Shop  https //stza.co/+vLbF-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. RubberDucks
END:VALARM
DTSTART:20180506T173500Z
DTEND:20180506T203500Z
UID:W5j7-_RcSLV08a0MuMmh_jHW@stanza.co
SUMMARY:Baysox vs. RubberDucks
DESCRIPTION:Baysox vs. RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLbF-8\n\nShop: https://stza.co/+vLbF-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Curve
<2018-05-07 Mon 17:00-20:00>
:PROPERTIES:
:ID:       BVVkYMJz4PQEi2j8x8P15sru@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Curve Baysox @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLa_-2o

Shop  https //stza.co/+vLa_-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Curve
END:VALARM
DTSTART:20180507T220000Z
DTEND:20180508T010000Z
UID:BVVkYMJz4PQEi2j8x8P15sru@stanza.co
SUMMARY:Baysox @ Curve
DESCRIPTION:Baysox @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLa_-2o\n\nShop: https://stza.co/+vLa_-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Curve
<2018-05-08 Tue 17:00-20:00>
:PROPERTIES:
:ID:       tN7x9LWn4xEU0mk3yfb9wiMP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Curve Baysox @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLa$-15

Shop  https //stza.co/+vLa$-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Curve
END:VALARM
DTSTART:20180508T220000Z
DTEND:20180509T010000Z
UID:tN7x9LWn4xEU0mk3yfb9wiMP@stanza.co
SUMMARY:Baysox @ Curve
DESCRIPTION:Baysox @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLa$-15\n\nShop: https://stza.co/+vLa$-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Curve
<2018-05-09 Wed 09:30-12:30>
:PROPERTIES:
:ID:       OhT_cJAzMNmTr-FEV7PlaTe9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox @ Curve Baysox @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLb0-r

Shop  https //stza.co/+vLb0-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Curve
END:VALARM
DTSTART:20180509T143000Z
DTEND:20180509T173000Z
UID:OhT_cJAzMNmTr-FEV7PlaTe9@stanza.co
SUMMARY:Baysox @ Curve
DESCRIPTION:Baysox @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLb0-r\n\nShop: https://stza.co/+vLb0-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Yard Goats
<2018-05-10 Thu 17:35-20:35>
:PROPERTIES:
:ID:       QTVI2Wn6CGFo1mDSZOa3puUS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox vs. Yard Goats Baysox vs. Yard Goats

Follow on MiLB First Pitch  https //stza.co/+vLbG-K

Shop  https //stza.co/+vLbG-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Yard Goats
END:VALARM
DTSTART:20180510T223500Z
DTEND:20180511T013500Z
UID:QTVI2Wn6CGFo1mDSZOa3puUS@stanza.co
SUMMARY:Baysox vs. Yard Goats
DESCRIPTION:Baysox vs. Yard Goats\n\nFollow on MiLB First Pitch: https://stza.co/+vLbG-K\n\nShop: https://stza.co/+vLbG-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Yard Goats
<2018-05-11 Fri 18:05-21:05>
:PROPERTIES:
:ID:       l80rmh_lMzZM8v5bq9vQEpvI@stanza.co
:LOCATION: Stick around after tonight's game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Baysox vs. Yard Goats Enjoy the best Fireworks show in the region following the Baysox game!

We recognize the students from Anne Arundel, Howard, Baltimore & Queen Anne's counties for their success in completing the Baysox Reading Program

Follow on MiLB First Pitch  https //stza.co/+vLbI-P

Shop  https //stza.co/+vLbI-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Yard Goats
END:VALARM
DTSTART:20180511T230500Z
DTEND:20180512T020500Z
UID:l80rmh_lMzZM8v5bq9vQEpvI@stanza.co
SUMMARY:Baysox vs. Yard Goats
DESCRIPTION:Enjoy the best Fireworks show in the region following the Baysox game!\n\nWe recognize the students from Anne Arundel, Howard, Baltimore & Queen Anne's counties for their success in completing the Baysox Reading Program\n\nFollow on MiLB First Pitch: https://stza.co/+vLbI-P\n\nShop: https://stza.co/+vLbI-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after tonight's game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Yard Goats
<2018-05-12 Sat 17:35-20:35>
:PROPERTIES:
:ID:       PfmVDBuO_2ewFLaoM_RTMML6@stanza.co
:LOCATION: Stick around after tonight's game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Baysox vs. Yard Goats Enjoy the best Fireworks show in the region following the Baysox game!

We recognize the students from Anne Arundel, Howard, Baltimore & Queen Anne's counties for their success in completing the Baysox Reading Program

Follow on MiLB First Pitch  https //stza.co/+vLbL-Y

Shop  https //stza.co/+vLbL-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Yard Goats
END:VALARM
DTSTART:20180512T223500Z
DTEND:20180513T013500Z
UID:PfmVDBuO_2ewFLaoM_RTMML6@stanza.co
SUMMARY:Baysox vs. Yard Goats
DESCRIPTION:Enjoy the best Fireworks show in the region following the Baysox game!\n\nWe recognize the students from Anne Arundel, Howard, Baltimore & Queen Anne's counties for their success in completing the Baysox Reading Program\n\nFollow on MiLB First Pitch: https://stza.co/+vLbL-Y\n\nShop: https://stza.co/+vLbL-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after tonight's game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Yard Goats
<2018-05-13 Sun 12:35-15:35>
:PROPERTIES:
:ID:       Ny69lwbN780fGUt2POr88i6b@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox vs. Yard Goats Baysox vs. Yard Goats

Follow on MiLB First Pitch  https //stza.co/+vLbM-2_

Shop  https //stza.co/+vLbM-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Yard Goats
END:VALARM
DTSTART:20180513T173500Z
DTEND:20180513T203500Z
UID:Ny69lwbN780fGUt2POr88i6b@stanza.co
SUMMARY:Baysox vs. Yard Goats
DESCRIPTION:Baysox vs. Yard Goats\n\nFollow on MiLB First Pitch: https://stza.co/+vLbM-2_\n\nShop: https://stza.co/+vLbM-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Senators
<2018-05-14 Mon 17:35-20:35>
:PROPERTIES:
:ID:       eB224WodIgk1MHki-9fmD6NJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox vs. Senators Baysox vs. Senators

Follow on MiLB First Pitch  https //stza.co/+vLbO-i

Shop  https //stza.co/+vLbO-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Senators
END:VALARM
DTSTART:20180514T223500Z
DTEND:20180515T013500Z
UID:eB224WodIgk1MHki-9fmD6NJ@stanza.co
SUMMARY:Baysox vs. Senators
DESCRIPTION:Baysox vs. Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLbO-i\n\nShop: https://stza.co/+vLbO-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Senators
<2018-05-15 Tue 17:35-20:35>
:PROPERTIES:
:ID:       xL32loWse-PhEpYS3ovCJwTz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox vs. Senators Baysox vs. Senators

Follow on MiLB First Pitch  https //stza.co/+vLbQ-2Z

Shop  https //stza.co/+vLbQ-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Senators
END:VALARM
DTSTART:20180515T223500Z
DTEND:20180516T013500Z
UID:xL32loWse-PhEpYS3ovCJwTz@stanza.co
SUMMARY:Baysox vs. Senators
DESCRIPTION:Baysox vs. Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLbQ-2Z\n\nShop: https://stza.co/+vLbQ-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Senators
<2018-05-16 Wed 10:05-13:05>
:PROPERTIES:
:ID:       5IoK9nc6_ql2fjRaDX9SvclC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox vs. Senators Baysox vs. Senators

Follow on MiLB First Pitch  https //stza.co/+vLbT-3U

Shop  https //stza.co/+vLbT-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Senators
END:VALARM
DTSTART:20180516T150500Z
DTEND:20180516T180500Z
UID:5IoK9nc6_ql2fjRaDX9SvclC@stanza.co
SUMMARY:Baysox vs. Senators
DESCRIPTION:Baysox vs. Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLbT-3U\n\nShop: https://stza.co/+vLbT-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Thunder
<2018-05-17 Thu 18:00-21:00>
:PROPERTIES:
:ID:       xu8e2-WnLShSXSokbHYv8OL2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox @ Thunder Baysox @ Thunder

Follow on MiLB First Pitch  https //stza.co/+v7PR-o

Shop  https //stza.co/+v7PR-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Thunder
END:VALARM
DTSTART:20180517T230000Z
DTEND:20180518T020000Z
UID:xu8e2-WnLShSXSokbHYv8OL2@stanza.co
SUMMARY:Baysox @ Thunder
DESCRIPTION:Baysox @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+v7PR-o\n\nShop: https://stza.co/+v7PR-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Thunder
<2018-05-18 Fri 18:00-21:00>
:PROPERTIES:
:ID:       Jz3n-Gg6f6404he85ab7XU0w@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Thunder Baysox @ Thunder

Follow on MiLB First Pitch  https //stza.co/+v7PS-8

Shop  https //stza.co/+v7PS-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Thunder
END:VALARM
DTSTART:20180518T230000Z
DTEND:20180519T020000Z
UID:Jz3n-Gg6f6404he85ab7XU0w@stanza.co
SUMMARY:Baysox @ Thunder
DESCRIPTION:Baysox @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+v7PS-8\n\nShop: https://stza.co/+v7PS-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Thunder
<2018-05-19 Sat 18:00-21:00>
:PROPERTIES:
:ID:       Lkr-mfeOh9ywd5eGdBYKdfmK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Thunder Baysox @ Thunder

Follow on MiLB First Pitch  https //stza.co/+v7PT-1S

Shop  https //stza.co/+v7PT-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Thunder
END:VALARM
DTSTART:20180519T230000Z
DTEND:20180520T020000Z
UID:Lkr-mfeOh9ywd5eGdBYKdfmK@stanza.co
SUMMARY:Baysox @ Thunder
DESCRIPTION:Baysox @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+v7PT-1S\n\nShop: https://stza.co/+v7PT-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Thunder
<2018-05-20 Sun 12:00-15:00>
:PROPERTIES:
:ID:       gi5uGvY9t7wuscIDnK82VFWQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox @ Thunder Baysox @ Thunder

Follow on MiLB First Pitch  https //stza.co/+v7PU-f

Shop  https //stza.co/+v7PU-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Thunder
END:VALARM
DTSTART:20180520T170000Z
DTEND:20180520T200000Z
UID:gi5uGvY9t7wuscIDnK82VFWQ@stanza.co
SUMMARY:Baysox @ Thunder
DESCRIPTION:Baysox @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+v7PU-f\n\nShop: https://stza.co/+v7PU-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Curve
<2018-05-22 Tue 17:35-20:35>
:PROPERTIES:
:ID:       RHNBxoweYderSsdu5oGnzx2q@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox vs. Curve Baysox vs. Curve

Follow on MiLB First Pitch  https //stza.co/+vLbV-30

Shop  https //stza.co/+vLbV-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Curve
END:VALARM
DTSTART:20180522T223500Z
DTEND:20180523T013500Z
UID:RHNBxoweYderSsdu5oGnzx2q@stanza.co
SUMMARY:Baysox vs. Curve
DESCRIPTION:Baysox vs. Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLbV-30\n\nShop: https://stza.co/+vLbV-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Curve
<2018-05-23 Wed 17:35-20:35>
:PROPERTIES:
:ID:       LmJ-cmvlw-e3AAlpL__Ds83M@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox vs. Curve Baysox vs. Curve

Follow on MiLB First Pitch  https //stza.co/+vLbW-2E

Shop  https //stza.co/+vLbW-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Curve
END:VALARM
DTSTART:20180523T223500Z
DTEND:20180524T013500Z
UID:LmJ-cmvlw-e3AAlpL__Ds83M@stanza.co
SUMMARY:Baysox vs. Curve
DESCRIPTION:Baysox vs. Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLbW-2E\n\nShop: https://stza.co/+vLbW-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Curve
<2018-05-24 Thu 10:05-13:05>
:PROPERTIES:
:ID:       IfwHONjbKZYOpXQ2lRtiJ0Xc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox vs. Curve Baysox vs. Curve

Follow on MiLB First Pitch  https //stza.co/+vLbZ-2E

Shop  https //stza.co/+vLbZ-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Curve
END:VALARM
DTSTART:20180524T150500Z
DTEND:20180524T180500Z
UID:IfwHONjbKZYOpXQ2lRtiJ0Xc@stanza.co
SUMMARY:Baysox vs. Curve
DESCRIPTION:Baysox vs. Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLbZ-2E\n\nShop: https://stza.co/+vLbZ-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Rumble Ponies
<2018-05-25 Fri 18:05-21:05>
:PROPERTIES:
:ID:       HCnL8xq37qF68LBmBhEbNxAj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Rumble Ponies Baysox @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLb4-s

Shop  https //stza.co/+vLb4-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Rumble Ponies
END:VALARM
DTSTART:20180525T230500Z
DTEND:20180526T020500Z
UID:HCnL8xq37qF68LBmBhEbNxAj@stanza.co
SUMMARY:Baysox @ Rumble Ponies
DESCRIPTION:Baysox @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLb4-s\n\nShop: https://stza.co/+vLb4-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Rumble Ponies
<2018-05-26 Sat 17:05-20:05>
:PROPERTIES:
:ID:       ZO8CYQewivP3e3-cpi3HWdH6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Rumble Ponies Baysox @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLb5-3x

Shop  https //stza.co/+vLb5-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Rumble Ponies
END:VALARM
DTSTART:20180526T220500Z
DTEND:20180527T010500Z
UID:ZO8CYQewivP3e3-cpi3HWdH6@stanza.co
SUMMARY:Baysox @ Rumble Ponies
DESCRIPTION:Baysox @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLb5-3x\n\nShop: https://stza.co/+vLb5-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Rumble Ponies
<2018-05-27 Sun 17:35-20:35>
:PROPERTIES:
:ID:       UQq7oszhOFNZTnUIm-vO--Cj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox @ Rumble Ponies Baysox @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLb6-1w

Shop  https //stza.co/+vLb6-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Rumble Ponies
END:VALARM
DTSTART:20180527T223500Z
DTEND:20180528T013500Z
UID:UQq7oszhOFNZTnUIm-vO--Cj@stanza.co
SUMMARY:Baysox @ Rumble Ponies
DESCRIPTION:Baysox @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLb6-1w\n\nShop: https://stza.co/+vLb6-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Rumble Ponies
<2018-05-28 Mon 13:05-16:05>
:PROPERTIES:
:ID:       JFgwYc6lZPBeTENGcmkCG7-7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Rumble Ponies Baysox @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLb7-2E

Shop  https //stza.co/+vLb7-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Rumble Ponies
END:VALARM
DTSTART:20180528T180500Z
DTEND:20180528T210500Z
UID:JFgwYc6lZPBeTENGcmkCG7-7@stanza.co
SUMMARY:Baysox @ Rumble Ponies
DESCRIPTION:Baysox @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLb7-2E\n\nShop: https://stza.co/+vLb7-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Flying Squirrels
<2018-05-29 Tue 17:35-20:35>
:PROPERTIES:
:ID:       rcaHq_H5EsPKhBRhvI42YYS3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Flying Squirrels Baysox @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vLdW-21

Shop  https //stza.co/+vLdW-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Flying Squirrels
END:VALARM
DTSTART:20180529T223500Z
DTEND:20180530T013500Z
UID:rcaHq_H5EsPKhBRhvI42YYS3@stanza.co
SUMMARY:Baysox @ Flying Squirrels
DESCRIPTION:Baysox @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vLdW-21\n\nShop: https://stza.co/+vLdW-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Flying Squirrels
<2018-05-30 Wed 17:35-20:35>
:PROPERTIES:
:ID:       Y-gcPEqmAaVPg7qhyf54B4W8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox @ Flying Squirrels Baysox @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+v7PK-8

Shop  https //stza.co/+v7PK-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Flying Squirrels
END:VALARM
DTSTART:20180530T223500Z
DTEND:20180531T013500Z
UID:Y-gcPEqmAaVPg7qhyf54B4W8@stanza.co
SUMMARY:Baysox @ Flying Squirrels
DESCRIPTION:Baysox @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+v7PK-8\n\nShop: https://stza.co/+v7PK-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Flying Squirrels
<2018-05-31 Thu 17:35-20:35>
:PROPERTIES:
:ID:       kellT-c0rPOYfC9zLuOmTv4W@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Flying Squirrels Baysox @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+v7PL-2

Shop  https //stza.co/+v7PL-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Flying Squirrels
END:VALARM
DTSTART:20180531T223500Z
DTEND:20180601T013500Z
UID:kellT-c0rPOYfC9zLuOmTv4W@stanza.co
SUMMARY:Baysox @ Flying Squirrels
DESCRIPTION:Baysox @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+v7PL-2\n\nShop: https://stza.co/+v7PL-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Thunder
<2018-06-01 Fri 18:05-21:05>
:PROPERTIES:
:ID:       Rne96Ub4mr4dY6Lkmj5u64TP@stanza.co
:LOCATION: Boy & Cub Scout Camp Out
:STATUS:   CONFIRMED
:END:

Baysox vs. Thunder Join in all of the fun with the Baysox 20th annual Boy/Cub Scout Camp Out Event! Scouts will take part in a pre-game parade on the field beginning at 6 15 pm followed by a great baseball game featuring the Bowie Baysox as they take on the Trenton Thunder.  After the game, Scouts, Scout leaders and parents that have pre-registered, will get their camping gear and come onto the field and set up their tents for a night of fun under the stars to sleep on the field at Prince George's Stadium! Tent spaces are limited and you must pre-register for a tent space on the field at the time of your ticket order.  See below for additional tent/field rules and regulations. There will also be a family friendly movie shown on the Baysox Jumbotron once everyone has set up their tents! Event participation patches will also be available for Scouts attending this event. 

Follow on MiLB First Pitch  https //stza.co/+vLb_-h

Shop  https //stza.co/+vLb_-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Thunder
END:VALARM
DTSTART:20180601T230500Z
DTEND:20180602T020500Z
UID:Rne96Ub4mr4dY6Lkmj5u64TP@stanza.co
SUMMARY:Baysox vs. Thunder
DESCRIPTION:Join in all of the fun with the Baysox 20th annual Boy/Cub Scout Camp Out Event! Scouts will take part in a pre-game parade on the field beginning at 6:15 pm followed by a great baseball game featuring the Bowie Baysox as they take on the Trenton Thunder.  After the game, Scouts, Scout leaders and parents that have pre-registered, will get their camping gear and come onto the field and set up their tents for a night of fun under the stars to sleep on the field at Prince George's Stadium! Tent spaces are limited and you must pre-register for a tent space on the field at the time of your ticket order.  See below for additional tent/field rules and regulations. There will also be a family friendly movie shown on the Baysox Jumbotron once everyone has set up their tents! Event participation patches will also be available for Scouts attending this event. \n\nFollow on MiLB First Pitch: https://stza.co/+vLb_-h\n\nShop: https://stza.co/+vLb_-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Boy & Cub Scout Camp Out
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Thunder
<2018-06-02 Sat 17:35-20:35>
:PROPERTIES:
:ID:       bNFOo8iY1UaWb09VTGkaXI66@stanza.co
:LOCATION: Stick around after tonight's game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Baysox vs. Thunder Enjoy the best Fireworks show in the region following the Baysox game!

Follow on MiLB First Pitch  https //stza.co/+vLc1-2R

Shop  https //stza.co/+vLc1-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Thunder
END:VALARM
DTSTART:20180602T223500Z
DTEND:20180603T013500Z
UID:bNFOo8iY1UaWb09VTGkaXI66@stanza.co
SUMMARY:Baysox vs. Thunder
DESCRIPTION:Enjoy the best Fireworks show in the region following the Baysox game!\n\nFollow on MiLB First Pitch: https://stza.co/+vLc1-2R\n\nShop: https://stza.co/+vLc1-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after tonight's game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Thunder
<2018-06-03 Sun 12:35-15:35>
:PROPERTIES:
:ID:       GKbCnu4nXSt8kkdCHZEYtyJj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox vs. Thunder Baysox vs. Thunder

Follow on MiLB First Pitch  https //stza.co/+vLc2-25

Shop  https //stza.co/+vLc2-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Thunder
END:VALARM
DTSTART:20180603T173500Z
DTEND:20180603T203500Z
UID:GKbCnu4nXSt8kkdCHZEYtyJj@stanza.co
SUMMARY:Baysox vs. Thunder
DESCRIPTION:Baysox vs. Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vLc2-25\n\nShop: https://stza.co/+vLc2-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Sea Dogs
<2018-06-05 Tue 18:00-21:00>
:PROPERTIES:
:ID:       GBbFlTtBzLAR09SdkqhO2vGU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox @ Sea Dogs Baysox @ Sea Dogs

Buy tickets here  https //stza.co/~vLdL

Follow on MiLB First Pitch  https //stza.co/+vLdL-1K

Shop  https //stza.co/+vLdL-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Sea Dogs
END:VALARM
DTSTART:20180605T230000Z
DTEND:20180606T020000Z
UID:GBbFlTtBzLAR09SdkqhO2vGU@stanza.co
SUMMARY:Baysox @ Sea Dogs
DESCRIPTION:Baysox @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vLdL\n\nFollow on MiLB First Pitch: https://stza.co/+vLdL-1K\n\nShop: https://stza.co/+vLdL-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Sea Dogs
<2018-06-06 Wed 18:00-21:00>
:PROPERTIES:
:ID:       fLJobiIe2uEq4KUYCBB_hXsQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Sea Dogs Baysox @ Sea Dogs

Buy tickets here  https //stza.co/~vLdM

Follow on MiLB First Pitch  https //stza.co/+vLdM-2c

Shop  https //stza.co/+vLdM-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Sea Dogs
END:VALARM
DTSTART:20180606T230000Z
DTEND:20180607T020000Z
UID:fLJobiIe2uEq4KUYCBB_hXsQ@stanza.co
SUMMARY:Baysox @ Sea Dogs
DESCRIPTION:Baysox @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vLdM\n\nFollow on MiLB First Pitch: https://stza.co/+vLdM-2c\n\nShop: https://stza.co/+vLdM-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Sea Dogs
<2018-06-07 Thu 10:00-13:00>
:PROPERTIES:
:ID:       wRewXpzHtvR3WIWhHXXdNT2S@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Sea Dogs Baysox @ Sea Dogs

Buy tickets here  https //stza.co/~vLdN

Follow on MiLB First Pitch  https //stza.co/+vLdN-1g

Shop  https //stza.co/+vLdN-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Sea Dogs
END:VALARM
DTSTART:20180607T150000Z
DTEND:20180607T180000Z
UID:wRewXpzHtvR3WIWhHXXdNT2S@stanza.co
SUMMARY:Baysox @ Sea Dogs
DESCRIPTION:Baysox @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vLdN\n\nFollow on MiLB First Pitch: https://stza.co/+vLdN-1g\n\nShop: https://stza.co/+vLdN-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Fisher Cats
<2018-06-08 Fri 17:35-20:35>
:PROPERTIES:
:ID:       9-Me9OjgCpohgQXmtL1hhv36@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox @ Fisher Cats Baysox @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLdI-2z

Shop  https //stza.co/+vLdI-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Fisher Cats
END:VALARM
DTSTART:20180608T223500Z
DTEND:20180609T013500Z
UID:9-Me9OjgCpohgQXmtL1hhv36@stanza.co
SUMMARY:Baysox @ Fisher Cats
DESCRIPTION:Baysox @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLdI-2z\n\nShop: https://stza.co/+vLdI-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Fisher Cats
<2018-06-09 Sat 17:35-20:35>
:PROPERTIES:
:ID:       3B94IFbvY1uzgoNG8eof1gq4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Fisher Cats Baysox @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLdJ-3K

Shop  https //stza.co/+vLdJ-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Fisher Cats
END:VALARM
DTSTART:20180609T223500Z
DTEND:20180610T013500Z
UID:3B94IFbvY1uzgoNG8eof1gq4@stanza.co
SUMMARY:Baysox @ Fisher Cats
DESCRIPTION:Baysox @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLdJ-3K\n\nShop: https://stza.co/+vLdJ-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Fisher Cats
<2018-06-10 Sun 12:35-15:35>
:PROPERTIES:
:ID:       6pVFy1YCee1xMGDTHXQ5jsmm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Fisher Cats Baysox @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLdK-1O

Shop  https //stza.co/+vLdK-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Fisher Cats
END:VALARM
DTSTART:20180610T173500Z
DTEND:20180610T203500Z
UID:6pVFy1YCee1xMGDTHXQ5jsmm@stanza.co
SUMMARY:Baysox @ Fisher Cats
DESCRIPTION:Baysox @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLdK-1O\n\nShop: https://stza.co/+vLdK-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Thunder
<2018-06-12 Tue 17:35-20:35>
:PROPERTIES:
:ID:       nsmUUu_Z80_2teWVTC00m5iy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox vs. Thunder Baysox vs. Thunder

Follow on MiLB First Pitch  https //stza.co/+vLc4-A

Shop  https //stza.co/+vLc4-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Thunder
END:VALARM
DTSTART:20180612T223500Z
DTEND:20180613T013500Z
UID:nsmUUu_Z80_2teWVTC00m5iy@stanza.co
SUMMARY:Baysox vs. Thunder
DESCRIPTION:Baysox vs. Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vLc4-A\n\nShop: https://stza.co/+vLc4-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Thunder
<2018-06-13 Wed 17:35-20:35>
:PROPERTIES:
:ID:       3GPzAdbECf7CIvtM6eba1EPQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox vs. Thunder Baysox vs. Thunder

Follow on MiLB First Pitch  https //stza.co/+vLc7-2k

Shop  https //stza.co/+vLc7-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Thunder
END:VALARM
DTSTART:20180613T223500Z
DTEND:20180614T013500Z
UID:3GPzAdbECf7CIvtM6eba1EPQ@stanza.co
SUMMARY:Baysox vs. Thunder
DESCRIPTION:Baysox vs. Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vLc7-2k\n\nShop: https://stza.co/+vLc7-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Thunder
<2018-06-14 Thu 17:35-20:35>
:PROPERTIES:
:ID:       M2QAdWbDyazG6vD_zfu5gxzD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox vs. Thunder Baysox vs. Thunder

Follow on MiLB First Pitch  https //stza.co/+vLc8-2a

Shop  https //stza.co/+vLc8-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Thunder
END:VALARM
DTSTART:20180614T223500Z
DTEND:20180615T013500Z
UID:M2QAdWbDyazG6vD_zfu5gxzD@stanza.co
SUMMARY:Baysox vs. Thunder
DESCRIPTION:Baysox vs. Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vLc8-2a\n\nShop: https://stza.co/+vLc8-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Sea Dogs
<2018-06-15 Fri 18:05-21:05>
:PROPERTIES:
:ID:       6Fr8D0PYqKaobMP2DhW8dvp-@stanza.co
:LOCATION: Stick around after tonight's game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Baysox vs. Sea Dogs Enjoy the best Fireworks show in the region following the Baysox game!

Join in all of the fun with the Baysox 12th annual Girl Scout Sleepover Event! Girl Scouts will take part in a pre-game parade on the field, beginning at 6 15 pm, followed by a great baseball game featuring the Bowie Baysox as they take on the Portland Sea Dogs. After the game, Scouts, Scout leaders and parents that have pre-registered, will get their camping gear and come onto the field and set up their tents for a night of fun under the stars to sleep on the field here at Prince George's Stadium!  Tent spaces are limited and you must pre-register for a tent space on the field at the time of your ticket order. See below for additional tent/field rules and regulations. Event participation patches will also be available for Scouts attending this event. 

Follow on MiLB First Pitch  https //stza.co/+vLca-3K

Shop  https //stza.co/+vLca-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Sea Dogs
END:VALARM
DTSTART:20180615T230500Z
DTEND:20180616T020500Z
UID:6Fr8D0PYqKaobMP2DhW8dvp-@stanza.co
SUMMARY:Baysox vs. Sea Dogs
DESCRIPTION:Enjoy the best Fireworks show in the region following the Baysox game!\n\nJoin in all of the fun with the Baysox 12th annual Girl Scout Sleepover Event! Girl Scouts will take part in a pre-game parade on the field, beginning at 6:15 pm, followed by a great baseball game featuring the Bowie Baysox as they take on the Portland Sea Dogs. After the game, Scouts, Scout leaders and parents that have pre-registered, will get their camping gear and come onto the field and set up their tents for a night of fun under the stars to sleep on the field here at Prince George's Stadium!  Tent spaces are limited and you must pre-register for a tent space on the field at the time of your ticket order. See below for additional tent/field rules and regulations. Event participation patches will also be available for Scouts attending this event. \n\nFollow on MiLB First Pitch: https://stza.co/+vLca-3K\n\nShop: https://stza.co/+vLca-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after tonight's game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Sea Dogs
<2018-06-16 Sat 17:35-20:35>
:PROPERTIES:
:ID:       Ax0ojbKPUOzKVri1gWN8NkLt@stanza.co
:LOCATION: Stick around after tonight's game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Baysox vs. Sea Dogs Enjoy the best Fireworks show in the region following the Baysox game!

Follow on MiLB First Pitch  https //stza.co/+vLcc-d

Shop  https //stza.co/+vLcc-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Sea Dogs
END:VALARM
DTSTART:20180616T223500Z
DTEND:20180617T013500Z
UID:Ax0ojbKPUOzKVri1gWN8NkLt@stanza.co
SUMMARY:Baysox vs. Sea Dogs
DESCRIPTION:Enjoy the best Fireworks show in the region following the Baysox game!\n\nFollow on MiLB First Pitch: https://stza.co/+vLcc-d\n\nShop: https://stza.co/+vLcc-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after tonight's game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Sea Dogs
<2018-06-17 Sun 12:35-15:35>
:PROPERTIES:
:ID:       TQnShG04RSELp8kC1VRRLmOV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox vs. Sea Dogs Baysox vs. Sea Dogs

Follow on MiLB First Pitch  https //stza.co/+vLce-1h

Shop  https //stza.co/+vLce-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Sea Dogs
END:VALARM
DTSTART:20180617T173500Z
DTEND:20180617T203500Z
UID:TQnShG04RSELp8kC1VRRLmOV@stanza.co
SUMMARY:Baysox vs. Sea Dogs
DESCRIPTION:Baysox vs. Sea Dogs\n\nFollow on MiLB First Pitch: https://stza.co/+vLce-1h\n\nShop: https://stza.co/+vLce-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Senators
<2018-06-19 Tue 17:30-20:30>
:PROPERTIES:
:ID:       TxRigUzSNRK5KZpv9Thgcvng@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Senators Baysox @ Senators

Follow on MiLB First Pitch  https //stza.co/+vLdy-36

Shop  https //stza.co/+vLdy-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Senators
END:VALARM
DTSTART:20180619T223000Z
DTEND:20180620T013000Z
UID:TxRigUzSNRK5KZpv9Thgcvng@stanza.co
SUMMARY:Baysox @ Senators
DESCRIPTION:Baysox @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLdy-36\n\nShop: https://stza.co/+vLdy-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Senators
<2018-06-20 Wed 11:00-14:00>
:PROPERTIES:
:ID:       GnXg-cumw2LcacRLu6M1suU_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Senators Baysox @ Senators

Follow on MiLB First Pitch  https //stza.co/+vLdz-2$

Shop  https //stza.co/+vLdz-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Senators
END:VALARM
DTSTART:20180620T160000Z
DTEND:20180620T190000Z
UID:GnXg-cumw2LcacRLu6M1suU_@stanza.co
SUMMARY:Baysox @ Senators
DESCRIPTION:Baysox @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLdz-2$\n\nShop: https://stza.co/+vLdz-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Senators
<2018-06-21 Thu 18:00-21:00>
:PROPERTIES:
:ID:       jsKL5a4gBWPf0u9a3K3wZPVy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox @ Senators Baysox @ Senators

Follow on MiLB First Pitch  https //stza.co/+vLdA-11

Shop  https //stza.co/+vLdA-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Senators
END:VALARM
DTSTART:20180621T230000Z
DTEND:20180622T020000Z
UID:jsKL5a4gBWPf0u9a3K3wZPVy@stanza.co
SUMMARY:Baysox @ Senators
DESCRIPTION:Baysox @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLdA-11\n\nShop: https://stza.co/+vLdA-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Flying Squirrels
<2018-06-22 Fri 18:05-21:05>
:PROPERTIES:
:ID:       DaW1TcDu13ic2n02QhqDaOZ7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Flying Squirrels Baysox @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+v7PM-3g

Shop  https //stza.co/+v7PM-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Flying Squirrels
END:VALARM
DTSTART:20180622T230500Z
DTEND:20180623T020500Z
UID:DaW1TcDu13ic2n02QhqDaOZ7@stanza.co
SUMMARY:Baysox @ Flying Squirrels
DESCRIPTION:Baysox @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+v7PM-3g\n\nShop: https://stza.co/+v7PM-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Flying Squirrels
<2018-06-23 Sat 17:05-20:05>
:PROPERTIES:
:ID:       ELZJpXeda8D_PBu2L50LuuqS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Flying Squirrels Baysox @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+v7PN-3i

Shop  https //stza.co/+v7PN-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Flying Squirrels
END:VALARM
DTSTART:20180623T220500Z
DTEND:20180624T010500Z
UID:ELZJpXeda8D_PBu2L50LuuqS@stanza.co
SUMMARY:Baysox @ Flying Squirrels
DESCRIPTION:Baysox @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+v7PN-3i\n\nShop: https://stza.co/+v7PN-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Flying Squirrels
<2018-06-24 Sun 12:05-15:05>
:PROPERTIES:
:ID:       U-edzTD0VTgGS3EYzFmbnWpa@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox @ Flying Squirrels Baysox @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+v7PO-1d

Shop  https //stza.co/+v7PO-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Flying Squirrels
END:VALARM
DTSTART:20180624T170500Z
DTEND:20180624T200500Z
UID:U-edzTD0VTgGS3EYzFmbnWpa@stanza.co
SUMMARY:Baysox @ Flying Squirrels
DESCRIPTION:Baysox @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+v7PO-1d\n\nShop: https://stza.co/+v7PO-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. RubberDucks
<2018-06-25 Mon 18:05-21:05>
:PROPERTIES:
:ID:       z4gpaDiZHQte73KgHl3_v7Q5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox vs. RubberDucks Baysox vs. RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLcg-3r

Shop  https //stza.co/+vLcg-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. RubberDucks
END:VALARM
DTSTART:20180625T230500Z
DTEND:20180626T020500Z
UID:z4gpaDiZHQte73KgHl3_v7Q5@stanza.co
SUMMARY:Baysox vs. RubberDucks
DESCRIPTION:Baysox vs. RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLcg-3r\n\nShop: https://stza.co/+vLcg-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. RubberDucks
<2018-06-26 Tue 18:05-21:05>
:PROPERTIES:
:ID:       d6brECfikRIept7W-XYKA6kh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox vs. RubberDucks Baysox vs. RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLcj-3s

Shop  https //stza.co/+vLcj-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. RubberDucks
END:VALARM
DTSTART:20180626T230500Z
DTEND:20180627T020500Z
UID:d6brECfikRIept7W-XYKA6kh@stanza.co
SUMMARY:Baysox vs. RubberDucks
DESCRIPTION:Baysox vs. RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLcj-3s\n\nShop: https://stza.co/+vLcj-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. RubberDucks
<2018-06-27 Wed 18:05-21:05>
:PROPERTIES:
:ID:       T4vRxOzwmtVIg1RAHknvXsNI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox vs. RubberDucks Baysox vs. RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLck-D

Shop  https //stza.co/+vLck-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. RubberDucks
END:VALARM
DTSTART:20180627T230500Z
DTEND:20180628T020500Z
UID:T4vRxOzwmtVIg1RAHknvXsNI@stanza.co
SUMMARY:Baysox vs. RubberDucks
DESCRIPTION:Baysox vs. RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLck-D\n\nShop: https://stza.co/+vLck-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. RubberDucks
<2018-06-28 Thu 18:05-21:05>
:PROPERTIES:
:ID:       XiH-H6idaYT9aHIp50HitN-x@stanza.co
:LOCATION: Stick around after tonight's game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Baysox vs. RubberDucks Enjoy the best Fireworks show in the region following the Baysox game!

Follow on MiLB First Pitch  https //stza.co/+vLcn-33

Shop  https //stza.co/+vLcn-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. RubberDucks
END:VALARM
DTSTART:20180628T230500Z
DTEND:20180629T020500Z
UID:XiH-H6idaYT9aHIp50HitN-x@stanza.co
SUMMARY:Baysox vs. RubberDucks
DESCRIPTION:Enjoy the best Fireworks show in the region following the Baysox game!\n\nFollow on MiLB First Pitch: https://stza.co/+vLcn-33\n\nShop: https://stza.co/+vLcn-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after tonight's game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ SeaWolves
<2018-06-29 Fri 18:05-21:05>
:PROPERTIES:
:ID:       UYEfi436k1COjkccJ4Laf7Bq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ SeaWolves Baysox @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLdn-1A

Shop  https //stza.co/+vLdn-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ SeaWolves
END:VALARM
DTSTART:20180629T230500Z
DTEND:20180630T020500Z
UID:UYEfi436k1COjkccJ4Laf7Bq@stanza.co
SUMMARY:Baysox @ SeaWolves
DESCRIPTION:Baysox @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLdn-1A\n\nShop: https://stza.co/+vLdn-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ SeaWolves
<2018-06-30 Sat 18:05-21:05>
:PROPERTIES:
:ID:       mCRoz8jsgkdezoCOyao873aF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ SeaWolves Baysox @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLdo-3o

Shop  https //stza.co/+vLdo-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ SeaWolves
END:VALARM
DTSTART:20180630T230500Z
DTEND:20180701T020500Z
UID:mCRoz8jsgkdezoCOyao873aF@stanza.co
SUMMARY:Baysox @ SeaWolves
DESCRIPTION:Baysox @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLdo-3o\n\nShop: https://stza.co/+vLdo-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ SeaWolves
<2018-07-01 Sun 18:05-21:05>
:PROPERTIES:
:ID:       CijznjMvibYwOCPVDHH_gq6V@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox @ SeaWolves Baysox @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLdp-1K

Shop  https //stza.co/+vLdp-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ SeaWolves
END:VALARM
DTSTART:20180701T230500Z
DTEND:20180702T020500Z
UID:CijznjMvibYwOCPVDHH_gq6V@stanza.co
SUMMARY:Baysox @ SeaWolves
DESCRIPTION:Baysox @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLdp-1K\n\nShop: https://stza.co/+vLdp-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ SeaWolves
<2018-07-02 Mon 18:05-21:05>
:PROPERTIES:
:ID:       Qaib4nXwT118nkXnrys8lFVR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ SeaWolves Baysox @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLdq-M

Shop  https //stza.co/+vLdq-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ SeaWolves
END:VALARM
DTSTART:20180702T230500Z
DTEND:20180703T020500Z
UID:Qaib4nXwT118nkXnrys8lFVR@stanza.co
SUMMARY:Baysox @ SeaWolves
DESCRIPTION:Baysox @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLdq-M\n\nShop: https://stza.co/+vLdq-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ SeaWolves
<2018-07-03 Tue 18:05-21:05>
:PROPERTIES:
:ID:       wTSpO5medYkirVyrp2GHE1LI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ SeaWolves Baysox @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLdr-13

Shop  https //stza.co/+vLdr-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ SeaWolves
END:VALARM
DTSTART:20180703T230500Z
DTEND:20180704T020500Z
UID:wTSpO5medYkirVyrp2GHE1LI@stanza.co
SUMMARY:Baysox @ SeaWolves
DESCRIPTION:Baysox @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLdr-13\n\nShop: https://stza.co/+vLdr-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Senators
<2018-07-04 Wed 17:35-20:35>
:PROPERTIES:
:ID:       lAjJ44iI9dvDjHKVliGapMTN@stanza.co
:LOCATION: Independence Day Fireworks Spectacular
:STATUS:   CONFIRMED
:END:

Baysox vs. Senators There's no better way to celebrate the 4th of July than a Bowie Baysox Baseball Game and a huge post-game Fireworks Spectacular!

Spend the July 4th holiday in Luxury at the Bowie Baysox! Your Luxury Suite Seat Ticket will allow you to able to sit on the balcony seating level of the DIAMOND VIEW RESTAURANT located on the stadium's Luxury Suite level!  You will also have access to the indoor, climate controlled seating inside the DIAMOND VIEW RESTAURANT to enjoy the game and the post-game FIREWORKS show. There are only 100 tickets available for this special seating option for July 4th, so don't wait!  These tickets are only available until 5 00 pm on Friday, June 29, or until they are sold out. 

Follow on MiLB First Pitch  https //stza.co/+vLcp-m

Shop  https //stza.co/+vLcp-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Senators
END:VALARM
DTSTART:20180704T223500Z
DTEND:20180705T013500Z
UID:lAjJ44iI9dvDjHKVliGapMTN@stanza.co
SUMMARY:Baysox vs. Senators
DESCRIPTION:There's no better way to celebrate the 4th of July than a Bowie Baysox Baseball Game and a huge post-game Fireworks Spectacular!\n\nSpend the July 4th holiday in Luxury at the Bowie Baysox! Your Luxury Suite Seat Ticket will allow you to able to sit on the balcony seating level of the DIAMOND VIEW RESTAURANT located on the stadium's Luxury Suite level!  You will also have access to the indoor, climate controlled seating inside the DIAMOND VIEW RESTAURANT to enjoy the game and the post-game FIREWORKS show. There are only 100 tickets available for this special seating option for July 4th, so don't wait!  These tickets are only available until 5:00 pm on Friday, June 29, or until they are sold out. \n\nFollow on MiLB First Pitch: https://stza.co/+vLcp-m\n\nShop: https://stza.co/+vLcp-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Independence Day Fireworks Spectacular
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Senators
<2018-07-05 Thu 18:05-21:05>
:PROPERTIES:
:ID:       F1Oae9AjgRET7_d0kLKYqmNZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox vs. Senators Baysox vs. Senators

Follow on MiLB First Pitch  https //stza.co/+vLcr-2U

Shop  https //stza.co/+vLcr-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Senators
END:VALARM
DTSTART:20180705T230500Z
DTEND:20180706T020500Z
UID:F1Oae9AjgRET7_d0kLKYqmNZ@stanza.co
SUMMARY:Baysox vs. Senators
DESCRIPTION:Baysox vs. Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLcr-2U\n\nShop: https://stza.co/+vLcr-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Senators
<2018-07-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       u8iEVKbzFp19Po50cH-8jPec@stanza.co
:LOCATION: Stick around after tonight's game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Baysox vs. Senators Enjoy the best Fireworks show in the region following the Baysox game!

Follow on MiLB First Pitch  https //stza.co/+vLct-3I

Shop  https //stza.co/+vLct-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Senators
END:VALARM
DTSTART:20180706T230500Z
DTEND:20180707T020500Z
UID:u8iEVKbzFp19Po50cH-8jPec@stanza.co
SUMMARY:Baysox vs. Senators
DESCRIPTION:Enjoy the best Fireworks show in the region following the Baysox game!\n\nFollow on MiLB First Pitch: https://stza.co/+vLct-3I\n\nShop: https://stza.co/+vLct-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after tonight's game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Senators
<2018-07-07 Sat 17:35-20:35>
:PROPERTIES:
:ID:       uxdTBpE4esjk3BDQYCOoHFyo@stanza.co
:LOCATION: Fireworks & Island Luau Night
:STATUS:   CONFIRMED
:END:

Baysox vs. Senators Enjoy the best Fireworks show in the region following the Baysox game set to the sounds of the Islands!

Follow on MiLB First Pitch  https //stza.co/+vLcu-20

Shop  https //stza.co/+vLcu-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Senators
END:VALARM
DTSTART:20180707T223500Z
DTEND:20180708T013500Z
UID:uxdTBpE4esjk3BDQYCOoHFyo@stanza.co
SUMMARY:Baysox vs. Senators
DESCRIPTION:Enjoy the best Fireworks show in the region following the Baysox game set to the sounds of the Islands!\n\nFollow on MiLB First Pitch: https://stza.co/+vLcu-20\n\nShop: https://stza.co/+vLcu-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks & Island Luau Night
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Senators
<2018-07-08 Sun 12:35-15:35>
:PROPERTIES:
:ID:       7J5lfUk0dpX8_RY-ZFuqihJB@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox vs. Senators Baysox vs. Senators

Follow on MiLB First Pitch  https //stza.co/+vLcx-3p

Shop  https //stza.co/+vLcx-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Senators
END:VALARM
DTSTART:20180708T173500Z
DTEND:20180708T203500Z
UID:7J5lfUk0dpX8_RY-ZFuqihJB@stanza.co
SUMMARY:Baysox vs. Senators
DESCRIPTION:Baysox vs. Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLcx-3p\n\nShop: https://stza.co/+vLcx-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Fightin Phils
<2018-07-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       B3cpTZr9BYX3VPUjukmX1Txy@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Fightin Phils Baysox @ Fightin Phils

Buy tickets here  https //stza.co/~vLdO

Follow on MiLB First Pitch  https //stza.co/+vLdO-30

Shop  https //stza.co/+vLdO-3_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Fightin Phils
END:VALARM
DTSTART:20180712T230500Z
DTEND:20180713T020500Z
UID:B3cpTZr9BYX3VPUjukmX1Txy@stanza.co
SUMMARY:Baysox @ Fightin Phils
DESCRIPTION:Baysox @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vLdO\n\nFollow on MiLB First Pitch: https://stza.co/+vLdO-30\n\nShop: https://stza.co/+vLdO-3_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Fightin Phils
<2018-07-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       uHhoUth4gRTTwn876R1E9G8z@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox @ Fightin Phils Baysox @ Fightin Phils

Buy tickets here  https //stza.co/~vLdP

Follow on MiLB First Pitch  https //stza.co/+vLdP-d

Shop  https //stza.co/+vLdP-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Fightin Phils
END:VALARM
DTSTART:20180713T230500Z
DTEND:20180714T020500Z
UID:uHhoUth4gRTTwn876R1E9G8z@stanza.co
SUMMARY:Baysox @ Fightin Phils
DESCRIPTION:Baysox @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vLdP\n\nFollow on MiLB First Pitch: https://stza.co/+vLdP-d\n\nShop: https://stza.co/+vLdP-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Fightin Phils
<2018-07-14 Sat 17:35-20:35>
:PROPERTIES:
:ID:       4igFn47loijnvWiMBrRzy8Hd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Fightin Phils Baysox @ Fightin Phils

Buy tickets here  https //stza.co/~vLdQ

Follow on MiLB First Pitch  https //stza.co/+vLdQ-1q

Shop  https //stza.co/+vLdQ-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Fightin Phils
END:VALARM
DTSTART:20180714T223500Z
DTEND:20180715T013500Z
UID:4igFn47loijnvWiMBrRzy8Hd@stanza.co
SUMMARY:Baysox @ Fightin Phils
DESCRIPTION:Baysox @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vLdQ\n\nFollow on MiLB First Pitch: https://stza.co/+vLdQ-1q\n\nShop: https://stza.co/+vLdQ-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Fightin Phils
<2018-07-15 Sun 13:05-16:05>
:PROPERTIES:
:ID:       0tquNhJ3QZbuYprll80uf2K0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Fightin Phils Baysox @ Fightin Phils

Buy tickets here  https //stza.co/~vLdR

Follow on MiLB First Pitch  https //stza.co/+vLdR-1i

Shop  https //stza.co/+vLdR-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Fightin Phils
END:VALARM
DTSTART:20180715T180500Z
DTEND:20180715T210500Z
UID:0tquNhJ3QZbuYprll80uf2K0@stanza.co
SUMMARY:Baysox @ Fightin Phils
DESCRIPTION:Baysox @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vLdR\n\nFollow on MiLB First Pitch: https://stza.co/+vLdR-1i\n\nShop: https://stza.co/+vLdR-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Curve
<2018-07-16 Mon 18:00-21:00>
:PROPERTIES:
:ID:       FckFgePsWmAKcnnNYRLK3Q1w@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox @ Curve Baysox @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLb1-2a

Shop  https //stza.co/+vLb1-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Curve
END:VALARM
DTSTART:20180716T230000Z
DTEND:20180717T020000Z
UID:FckFgePsWmAKcnnNYRLK3Q1w@stanza.co
SUMMARY:Baysox @ Curve
DESCRIPTION:Baysox @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLb1-2a\n\nShop: https://stza.co/+vLb1-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Curve
<2018-07-17 Tue 18:00-21:00>
:PROPERTIES:
:ID:       DIOXtO2qUFrNBLqozVfEG9sW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Curve Baysox @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLb2-N

Shop  https //stza.co/+vLb2-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Curve
END:VALARM
DTSTART:20180717T230000Z
DTEND:20180718T020000Z
UID:DIOXtO2qUFrNBLqozVfEG9sW@stanza.co
SUMMARY:Baysox @ Curve
DESCRIPTION:Baysox @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLb2-N\n\nShop: https://stza.co/+vLb2-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Curve
<2018-07-18 Wed 11:00-14:00>
:PROPERTIES:
:ID:       39qNJhqidkge0MieoeSc2oni@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Curve Baysox @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLb3-3Q

Shop  https //stza.co/+vLb3-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Curve
END:VALARM
DTSTART:20180718T160000Z
DTEND:20180718T190000Z
UID:39qNJhqidkge0MieoeSc2oni@stanza.co
SUMMARY:Baysox @ Curve
DESCRIPTION:Baysox @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLb3-3Q\n\nShop: https://stza.co/+vLb3-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. SeaWolves
<2018-07-19 Thu 18:05-21:05>
:PROPERTIES:
:ID:       XYSL1cIWqkeCphzRkQp5VdeJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox vs. SeaWolves Baysox vs. SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLcz-2T

Shop  https //stza.co/+vLcz-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. SeaWolves
END:VALARM
DTSTART:20180719T230500Z
DTEND:20180720T020500Z
UID:XYSL1cIWqkeCphzRkQp5VdeJ@stanza.co
SUMMARY:Baysox vs. SeaWolves
DESCRIPTION:Baysox vs. SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLcz-2T\n\nShop: https://stza.co/+vLcz-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. SeaWolves
<2018-07-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       8yjAB5s__JJHruBl7PYg_8FO@stanza.co
:LOCATION: Stick around after tonight's game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Baysox vs. SeaWolves Enjoy the best Fireworks show in the region following the Baysox game!

Join in all of the family fun with the Baysox annual Family Camp Out! Families are encouraged to register early for this fun event for the whole family!  Enjoy a great baseball game featuring the Bowie Baysox as they take on Erie at 7 05 pm.  After the game, there will be a spectacular FIREWORKS show and all kids ages 12 & under can run the bases just like the Baysox do. Those pre-registering to stay overnight will then head out to their vehicles to get their camping gear and come onto the field and set up their tents for a night of fun under the stars, watch a family-friendly movie on the jumbotron and sleep on the field at Prince George's Stadium! Tent spaces are limited and you must pre-register for a tent space on the field at the time of your ticket order.  

Follow on MiLB First Pitch  https //stza.co/+vLcA-3

Shop  https //stza.co/+vLcA-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. SeaWolves
END:VALARM
DTSTART:20180720T230500Z
DTEND:20180721T020500Z
UID:8yjAB5s__JJHruBl7PYg_8FO@stanza.co
SUMMARY:Baysox vs. SeaWolves
DESCRIPTION:Enjoy the best Fireworks show in the region following the Baysox game!\n\nJoin in all of the family fun with the Baysox annual Family Camp Out! Families are encouraged to register early for this fun event for the whole family!  Enjoy a great baseball game featuring the Bowie Baysox as they take on Erie at 7:05 pm.  After the game, there will be a spectacular FIREWORKS show and all kids ages 12 & under can run the bases just like the Baysox do. Those pre-registering to stay overnight will then head out to their vehicles to get their camping gear and come onto the field and set up their tents for a night of fun under the stars, watch a family-friendly movie on the jumbotron and sleep on the field at Prince George's Stadium! Tent spaces are limited and you must pre-register for a tent space on the field at the time of your ticket order.  \n\nFollow on MiLB First Pitch: https://stza.co/+vLcA-3\n\nShop: https://stza.co/+vLcA-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after tonight's game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. SeaWolves
<2018-07-21 Sat 17:35-20:35>
:PROPERTIES:
:ID:       IIEiBmy_vBZ2jo09FdJoxmFB@stanza.co
:LOCATION: Stick around after tonight's game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Baysox vs. SeaWolves Enjoy the best Fireworks show in the region following the Baysox game!

Follow on MiLB First Pitch  https //stza.co/+vLcD-2h

Shop  https //stza.co/+vLcD-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. SeaWolves
END:VALARM
DTSTART:20180721T223500Z
DTEND:20180722T013500Z
UID:IIEiBmy_vBZ2jo09FdJoxmFB@stanza.co
SUMMARY:Baysox vs. SeaWolves
DESCRIPTION:Enjoy the best Fireworks show in the region following the Baysox game!\n\nFollow on MiLB First Pitch: https://stza.co/+vLcD-2h\n\nShop: https://stza.co/+vLcD-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after tonight's game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. SeaWolves
<2018-07-22 Sun 12:35-15:35>
:PROPERTIES:
:ID:       Yh5MafScA9tRvlIWfGNHNZTX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox vs. SeaWolves Baysox vs. SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLcF-1A

Shop  https //stza.co/+vLcF-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. SeaWolves
END:VALARM
DTSTART:20180722T173500Z
DTEND:20180722T203500Z
UID:Yh5MafScA9tRvlIWfGNHNZTX@stanza.co
SUMMARY:Baysox vs. SeaWolves
DESCRIPTION:Baysox vs. SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLcF-1A\n\nShop: https://stza.co/+vLcF-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Rumble Ponies
<2018-07-23 Mon 18:05-21:05>
:PROPERTIES:
:ID:       ZJNtOGKEP5sbX_1KahDt5ByQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox vs. Rumble Ponies Baysox vs. Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLcH-23

Shop  https //stza.co/+vLcH-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Rumble Ponies
END:VALARM
DTSTART:20180723T230500Z
DTEND:20180724T020500Z
UID:ZJNtOGKEP5sbX_1KahDt5ByQ@stanza.co
SUMMARY:Baysox vs. Rumble Ponies
DESCRIPTION:Baysox vs. Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLcH-23\n\nShop: https://stza.co/+vLcH-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Rumble Ponies
<2018-07-24 Tue 18:05-21:05>
:PROPERTIES:
:ID:       YnwvawJmxc-MkjC3-o-IJs85@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox vs. Rumble Ponies Baysox vs. Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLcJ-1S

Shop  https //stza.co/+vLcJ-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Rumble Ponies
END:VALARM
DTSTART:20180724T230500Z
DTEND:20180725T020500Z
UID:YnwvawJmxc-MkjC3-o-IJs85@stanza.co
SUMMARY:Baysox vs. Rumble Ponies
DESCRIPTION:Baysox vs. Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLcJ-1S\n\nShop: https://stza.co/+vLcJ-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Rumble Ponies
<2018-07-25 Wed 10:05-13:05>
:PROPERTIES:
:ID:       IZcuENjc0Hf2qf50E2ww9zIO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox vs. Rumble Ponies Baysox vs. Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLcL-3V

Shop  https //stza.co/+vLcL-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Rumble Ponies
END:VALARM
DTSTART:20180725T150500Z
DTEND:20180725T180500Z
UID:IZcuENjc0Hf2qf50E2ww9zIO@stanza.co
SUMMARY:Baysox vs. Rumble Ponies
DESCRIPTION:Baysox vs. Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLcL-3V\n\nShop: https://stza.co/+vLcL-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Senators
<2018-07-26 Thu 18:00-21:00>
:PROPERTIES:
:ID:       rXtPfiDKpQdiRIvhA2hoy41N@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Senators Baysox @ Senators

Follow on MiLB First Pitch  https //stza.co/+vLdB-2G

Shop  https //stza.co/+vLdB-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Senators
END:VALARM
DTSTART:20180726T230000Z
DTEND:20180727T020000Z
UID:rXtPfiDKpQdiRIvhA2hoy41N@stanza.co
SUMMARY:Baysox @ Senators
DESCRIPTION:Baysox @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLdB-2G\n\nShop: https://stza.co/+vLdB-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Senators
<2018-07-27 Fri 18:00-21:00>
:PROPERTIES:
:ID:       1_brNiirIKvJuc-kP3s9E45F@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox @ Senators Baysox @ Senators

Follow on MiLB First Pitch  https //stza.co/+vLdC-1W

Shop  https //stza.co/+vLdC-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Senators
END:VALARM
DTSTART:20180727T230000Z
DTEND:20180728T020000Z
UID:1_brNiirIKvJuc-kP3s9E45F@stanza.co
SUMMARY:Baysox @ Senators
DESCRIPTION:Baysox @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLdC-1W\n\nShop: https://stza.co/+vLdC-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Senators
<2018-07-28 Sat 17:00-20:00>
:PROPERTIES:
:ID:       gyGF-fFbD0YIwc13c7VHjZf_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Senators Baysox @ Senators

Follow on MiLB First Pitch  https //stza.co/+vLdD-G

Shop  https //stza.co/+vLdD-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Senators
END:VALARM
DTSTART:20180728T220000Z
DTEND:20180729T010000Z
UID:gyGF-fFbD0YIwc13c7VHjZf_@stanza.co
SUMMARY:Baysox @ Senators
DESCRIPTION:Baysox @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLdD-G\n\nShop: https://stza.co/+vLdD-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Senators
<2018-07-29 Sun 17:00-20:00>
:PROPERTIES:
:ID:       2GG88zf-f4TCB27ubddQ2R2q@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Senators Baysox @ Senators

Follow on MiLB First Pitch  https //stza.co/+vLdE-1A

Shop  https //stza.co/+vLdE-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Senators
END:VALARM
DTSTART:20180729T220000Z
DTEND:20180730T010000Z
UID:2GG88zf-f4TCB27ubddQ2R2q@stanza.co
SUMMARY:Baysox @ Senators
DESCRIPTION:Baysox @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLdE-1A\n\nShop: https://stza.co/+vLdE-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ RubberDucks
<2018-07-31 Tue 18:05-21:05>
:PROPERTIES:
:ID:       ca_-TKHF0KsWUHraWPVtZJxS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox @ RubberDucks Baysox @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLaT-k

Shop  https //stza.co/+vLaT-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ RubberDucks
END:VALARM
DTSTART:20180731T230500Z
DTEND:20180801T020500Z
UID:ca_-TKHF0KsWUHraWPVtZJxS@stanza.co
SUMMARY:Baysox @ RubberDucks
DESCRIPTION:Baysox @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLaT-k\n\nShop: https://stza.co/+vLaT-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ RubberDucks
<2018-08-01 Wed 18:05-21:05>
:PROPERTIES:
:ID:       wkZ_fXO9V9AerGqFZDROB8K1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ RubberDucks Baysox @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLaU-3G

Shop  https //stza.co/+vLaU-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ RubberDucks
END:VALARM
DTSTART:20180801T230500Z
DTEND:20180802T020500Z
UID:wkZ_fXO9V9AerGqFZDROB8K1@stanza.co
SUMMARY:Baysox @ RubberDucks
DESCRIPTION:Baysox @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLaU-3G\n\nShop: https://stza.co/+vLaU-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ RubberDucks
<2018-08-02 Thu 18:05-21:05>
:PROPERTIES:
:ID:       A02wkYA-abVZnzYyYch9jmtL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ RubberDucks Baysox @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLaV-17

Shop  https //stza.co/+vLaV-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ RubberDucks
END:VALARM
DTSTART:20180802T230500Z
DTEND:20180803T020500Z
UID:A02wkYA-abVZnzYyYch9jmtL@stanza.co
SUMMARY:Baysox @ RubberDucks
DESCRIPTION:Baysox @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLaV-17\n\nShop: https://stza.co/+vLaV-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Fightin Phils
<2018-08-03 Fri 18:05-21:05>
:PROPERTIES:
:ID:       CgjjSmh5D7fPXVhFXgLcfLzU@stanza.co
:LOCATION: Fireworks & Navy Night
:STATUS:   CONFIRMED
:END:

Baysox vs. Fightin Phils Join the Baysox for the annual Navy Night Event, where the Baysox celebrate the U.S. Navy and the U.S. Naval Academy!  Join the over 1,000 Plebes from the USNA's class of 2022 in this annual celebration. You'll also enjoy the best Fireworks show in the region following the Baysox game!

Follow on MiLB First Pitch  https //stza.co/+vLcM-S

Shop  https //stza.co/+vLcM-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Fightin Phils
END:VALARM
DTSTART:20180803T230500Z
DTEND:20180804T020500Z
UID:CgjjSmh5D7fPXVhFXgLcfLzU@stanza.co
SUMMARY:Baysox vs. Fightin Phils
DESCRIPTION:Join the Baysox for the annual Navy Night Event, where the Baysox celebrate the U.S. Navy and the U.S. Naval Academy!  Join the over 1,000 Plebes from the USNA's class of 2022 in this annual celebration. You'll also enjoy the best Fireworks show in the region following the Baysox game!\n\nFollow on MiLB First Pitch: https://stza.co/+vLcM-S\n\nShop: https://stza.co/+vLcM-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks & Navy Night
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Fightin Phils
<2018-08-04 Sat 17:35-20:35>
:PROPERTIES:
:ID:       0o4L564n0Kqk6IKsbMDknb8j@stanza.co
:LOCATION: Stick around after tonight's game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Baysox vs. Fightin Phils Enjoy the best Fireworks show in the region following the Baysox game!

Follow on MiLB First Pitch  https //stza.co/+vLcO-1K

Shop  https //stza.co/+vLcO-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Fightin Phils
END:VALARM
DTSTART:20180804T223500Z
DTEND:20180805T013500Z
UID:0o4L564n0Kqk6IKsbMDknb8j@stanza.co
SUMMARY:Baysox vs. Fightin Phils
DESCRIPTION:Enjoy the best Fireworks show in the region following the Baysox game!\n\nFollow on MiLB First Pitch: https://stza.co/+vLcO-1K\n\nShop: https://stza.co/+vLcO-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after tonight's game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Fightin Phils
<2018-08-05 Sun 12:35-15:35>
:PROPERTIES:
:ID:       WWy1jITpB8e-GZcSSnHE5mQF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox vs. Fightin Phils Baysox vs. Fightin Phils

Follow on MiLB First Pitch  https //stza.co/+vLcQ-1J

Shop  https //stza.co/+vLcQ-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Fightin Phils
END:VALARM
DTSTART:20180805T173500Z
DTEND:20180805T203500Z
UID:WWy1jITpB8e-GZcSSnHE5mQF@stanza.co
SUMMARY:Baysox vs. Fightin Phils
DESCRIPTION:Baysox vs. Fightin Phils\n\nFollow on MiLB First Pitch: https://stza.co/+vLcQ-1J\n\nShop: https://stza.co/+vLcQ-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Fisher Cats
<2018-08-07 Tue 18:05-21:05>
:PROPERTIES:
:ID:       jBKTVmMuhn-zNHd8yqXb2tMn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox vs. Fisher Cats Baysox vs. Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLcT-3o

Shop  https //stza.co/+vLcT-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Fisher Cats
END:VALARM
DTSTART:20180807T230500Z
DTEND:20180808T020500Z
UID:jBKTVmMuhn-zNHd8yqXb2tMn@stanza.co
SUMMARY:Baysox vs. Fisher Cats
DESCRIPTION:Baysox vs. Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLcT-3o\n\nShop: https://stza.co/+vLcT-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Fisher Cats
<2018-08-08 Wed 18:05-21:05>
:PROPERTIES:
:ID:       75U7bFkrhIPnRUVQGxvOLk9H@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox vs. Fisher Cats Baysox vs. Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLcU-D

Shop  https //stza.co/+vLcU-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Fisher Cats
END:VALARM
DTSTART:20180808T230500Z
DTEND:20180809T020500Z
UID:75U7bFkrhIPnRUVQGxvOLk9H@stanza.co
SUMMARY:Baysox vs. Fisher Cats
DESCRIPTION:Baysox vs. Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLcU-D\n\nShop: https://stza.co/+vLcU-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Fisher Cats
<2018-08-09 Thu 10:05-13:05>
:PROPERTIES:
:ID:       hiHEi35wWUAqTP8weTKZ9oG6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox vs. Fisher Cats Baysox vs. Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLcX-1N

Shop  https //stza.co/+vLcX-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Fisher Cats
END:VALARM
DTSTART:20180809T150500Z
DTEND:20180809T180500Z
UID:hiHEi35wWUAqTP8weTKZ9oG6@stanza.co
SUMMARY:Baysox vs. Fisher Cats
DESCRIPTION:Baysox vs. Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLcX-1N\n\nShop: https://stza.co/+vLcX-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Yard Goats
<2018-08-10 Fri 18:05-21:05>
:PROPERTIES:
:ID:       oVsWz_uOD1BCtRhkecZ47Nr1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Yard Goats Baysox @ Yard Goats

Buy tickets here  https //stza.co/~vLdF

Follow on MiLB First Pitch  https //stza.co/+vLdF-Q

Shop  https //stza.co/+vLdF-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Yard Goats
END:VALARM
DTSTART:20180810T230500Z
DTEND:20180811T020500Z
UID:oVsWz_uOD1BCtRhkecZ47Nr1@stanza.co
SUMMARY:Baysox @ Yard Goats
DESCRIPTION:Baysox @ Yard Goats\n\nBuy tickets here: https://stza.co/~vLdF\n\nFollow on MiLB First Pitch: https://stza.co/+vLdF-Q\n\nShop: https://stza.co/+vLdF-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Yard Goats
<2018-08-11 Sat 17:05-20:05>
:PROPERTIES:
:ID:       _PO-BRFI2rfokFmO71YRfawW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Yard Goats Baysox @ Yard Goats

Buy tickets here  https //stza.co/~vLdG

Follow on MiLB First Pitch  https //stza.co/+vLdG-1X

Shop  https //stza.co/+vLdG-1w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Yard Goats
END:VALARM
DTSTART:20180811T220500Z
DTEND:20180812T010500Z
UID:_PO-BRFI2rfokFmO71YRfawW@stanza.co
SUMMARY:Baysox @ Yard Goats
DESCRIPTION:Baysox @ Yard Goats\n\nBuy tickets here: https://stza.co/~vLdG\n\nFollow on MiLB First Pitch: https://stza.co/+vLdG-1X\n\nShop: https://stza.co/+vLdG-1w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Yard Goats
<2018-08-12 Sun 16:05-19:05>
:PROPERTIES:
:ID:       D-PRN-FjyMxHqF1VLyRR3KrQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox @ Yard Goats Baysox @ Yard Goats

Buy tickets here  https //stza.co/~vLdH

Follow on MiLB First Pitch  https //stza.co/+vLdH-3I

Shop  https //stza.co/+vLdH-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Yard Goats
END:VALARM
DTSTART:20180812T210500Z
DTEND:20180813T000500Z
UID:D-PRN-FjyMxHqF1VLyRR3KrQ@stanza.co
SUMMARY:Baysox @ Yard Goats
DESCRIPTION:Baysox @ Yard Goats\n\nBuy tickets here: https://stza.co/~vLdH\n\nFollow on MiLB First Pitch: https://stza.co/+vLdH-3I\n\nShop: https://stza.co/+vLdH-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Flying Squirrels
<2018-08-14 Tue 18:05-21:05>
:PROPERTIES:
:ID:       eAEkWoTTzu3CgYgBNhS4QRNC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox vs. Flying Squirrels Baysox vs. Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vLcY-2o

Shop  https //stza.co/+vLcY-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Flying Squirrels
END:VALARM
DTSTART:20180814T230500Z
DTEND:20180815T020500Z
UID:eAEkWoTTzu3CgYgBNhS4QRNC@stanza.co
SUMMARY:Baysox vs. Flying Squirrels
DESCRIPTION:Baysox vs. Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vLcY-2o\n\nShop: https://stza.co/+vLcY-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Flying Squirrels
<2018-08-15 Wed 18:05-21:05>
:PROPERTIES:
:ID:       KoTFJXZ2x4icdGiJHz2BgCh6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox vs. Flying Squirrels Baysox vs. Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vLc_-t

Shop  https //stza.co/+vLc_-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Flying Squirrels
END:VALARM
DTSTART:20180815T230500Z
DTEND:20180816T020500Z
UID:KoTFJXZ2x4icdGiJHz2BgCh6@stanza.co
SUMMARY:Baysox vs. Flying Squirrels
DESCRIPTION:Baysox vs. Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vLc_-t\n\nShop: https://stza.co/+vLc_-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Flying Squirrels
<2018-08-16 Thu 18:05-21:05>
:PROPERTIES:
:ID:       dl39thnxyeHQZ7GFPrBxndSM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox vs. Flying Squirrels Baysox vs. Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vLd0-24

Shop  https //stza.co/+vLd0-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Flying Squirrels
END:VALARM
DTSTART:20180816T230500Z
DTEND:20180817T020500Z
UID:dl39thnxyeHQZ7GFPrBxndSM@stanza.co
SUMMARY:Baysox vs. Flying Squirrels
DESCRIPTION:Baysox vs. Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vLd0-24\n\nShop: https://stza.co/+vLd0-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ SeaWolves
<2018-08-17 Fri 18:05-21:05>
:PROPERTIES:
:ID:       MMF-rnH0oi2HzzK5g6WzK3eb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ SeaWolves Baysox @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLds-2s

Shop  https //stza.co/+vLds-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ SeaWolves
END:VALARM
DTSTART:20180817T230500Z
DTEND:20180818T020500Z
UID:MMF-rnH0oi2HzzK5g6WzK3eb@stanza.co
SUMMARY:Baysox @ SeaWolves
DESCRIPTION:Baysox @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLds-2s\n\nShop: https://stza.co/+vLds-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ SeaWolves
<2018-08-18 Sat 18:05-21:05>
:PROPERTIES:
:ID:       ppE63UbCYprmeUuVOfAyAabK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ SeaWolves Baysox @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLdt-30

Shop  https //stza.co/+vLdt-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ SeaWolves
END:VALARM
DTSTART:20180818T230500Z
DTEND:20180819T020500Z
UID:ppE63UbCYprmeUuVOfAyAabK@stanza.co
SUMMARY:Baysox @ SeaWolves
DESCRIPTION:Baysox @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLdt-30\n\nShop: https://stza.co/+vLdt-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ SeaWolves
<2018-08-19 Sun 12:35-15:35>
:PROPERTIES:
:ID:       Ml_bVPYqPcoBHgMrTH1RjYlB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox @ SeaWolves Baysox @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLdu-2c

Shop  https //stza.co/+vLdu-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ SeaWolves
END:VALARM
DTSTART:20180819T173500Z
DTEND:20180819T203500Z
UID:Ml_bVPYqPcoBHgMrTH1RjYlB@stanza.co
SUMMARY:Baysox @ SeaWolves
DESCRIPTION:Baysox @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLdu-2c\n\nShop: https://stza.co/+vLdu-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Flying Squirrels
<2018-08-20 Mon 17:35-20:35>
:PROPERTIES:
:ID:       VT04JSNTkUn2LUJoDVC__UKg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Flying Squirrels Baysox @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+v7PP-7

Shop  https //stza.co/+v7PP-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Flying Squirrels
END:VALARM
DTSTART:20180820T223500Z
DTEND:20180821T013500Z
UID:VT04JSNTkUn2LUJoDVC__UKg@stanza.co
SUMMARY:Baysox @ Flying Squirrels
DESCRIPTION:Baysox @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+v7PP-7\n\nShop: https://stza.co/+v7PP-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ Flying Squirrels
<2018-08-21 Tue 17:35-20:35>
:PROPERTIES:
:ID:       Me_ubuFsojyfghqtVxuiAbhQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ Flying Squirrels Baysox @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+v7PQ-z

Shop  https //stza.co/+v7PQ-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ Flying Squirrels
END:VALARM
DTSTART:20180821T223500Z
DTEND:20180822T013500Z
UID:Me_ubuFsojyfghqtVxuiAbhQ@stanza.co
SUMMARY:Baysox @ Flying Squirrels
DESCRIPTION:Baysox @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+v7PQ-z\n\nShop: https://stza.co/+v7PQ-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Flying Squirrels
<2018-08-22 Wed 18:05-21:05>
:PROPERTIES:
:ID:       iNI0CJ6IYOMpx8_A1MPnNlPS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox vs. Flying Squirrels Baysox vs. Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vLd3-a

Shop  https //stza.co/+vLd3-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Flying Squirrels
END:VALARM
DTSTART:20180822T230500Z
DTEND:20180823T020500Z
UID:iNI0CJ6IYOMpx8_A1MPnNlPS@stanza.co
SUMMARY:Baysox vs. Flying Squirrels
DESCRIPTION:Baysox vs. Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vLd3-a\n\nShop: https://stza.co/+vLd3-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Flying Squirrels
<2018-08-23 Thu 18:05-21:05>
:PROPERTIES:
:ID:       g5Z7eNdZPu0kZtQg6s5iO7qo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox vs. Flying Squirrels Baysox vs. Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vLd5-10

Shop  https //stza.co/+vLd5-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Flying Squirrels
END:VALARM
DTSTART:20180823T230500Z
DTEND:20180824T020500Z
UID:g5Z7eNdZPu0kZtQg6s5iO7qo@stanza.co
SUMMARY:Baysox vs. Flying Squirrels
DESCRIPTION:Baysox vs. Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vLd5-10\n\nShop: https://stza.co/+vLd5-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. SeaWolves
<2018-08-24 Fri 18:05-21:05>
:PROPERTIES:
:ID:       NivFBoMmXwIPlUdfydi3xxvJ@stanza.co
:LOCATION: Stick around after tonight's game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Baysox vs. SeaWolves Enjoy the best Fireworks show in the region following the Baysox game!

Follow on MiLB First Pitch  https //stza.co/+vLd7-1A

Shop  https //stza.co/+vLd7-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. SeaWolves
END:VALARM
DTSTART:20180824T230500Z
DTEND:20180825T020500Z
UID:NivFBoMmXwIPlUdfydi3xxvJ@stanza.co
SUMMARY:Baysox vs. SeaWolves
DESCRIPTION:Enjoy the best Fireworks show in the region following the Baysox game!\n\nFollow on MiLB First Pitch: https://stza.co/+vLd7-1A\n\nShop: https://stza.co/+vLd7-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after tonight's game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. SeaWolves
<2018-08-25 Sat 17:35-20:35>
:PROPERTIES:
:ID:       GJn3j7natszUNLyzP8Hk4X0a@stanza.co
:LOCATION: Stick around after tonight's game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Baysox vs. SeaWolves Enjoy the best Fireworks show in the region following the Baysox game!

Follow on MiLB First Pitch  https //stza.co/+vLd9-3W

Shop  https //stza.co/+vLd9-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. SeaWolves
END:VALARM
DTSTART:20180825T223500Z
DTEND:20180826T013500Z
UID:GJn3j7natszUNLyzP8Hk4X0a@stanza.co
SUMMARY:Baysox vs. SeaWolves
DESCRIPTION:Enjoy the best Fireworks show in the region following the Baysox game!\n\nFollow on MiLB First Pitch: https://stza.co/+vLd9-3W\n\nShop: https://stza.co/+vLd9-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after tonight's game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. SeaWolves
<2018-08-26 Sun 12:35-15:35>
:PROPERTIES:
:ID:       jMs2rG2sr9oO_KX6IgXVAnSU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox vs. SeaWolves Baysox vs. SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLdb-1R

Shop  https //stza.co/+vLdb-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. SeaWolves
END:VALARM
DTSTART:20180826T173500Z
DTEND:20180826T203500Z
UID:jMs2rG2sr9oO_KX6IgXVAnSU@stanza.co
SUMMARY:Baysox vs. SeaWolves
DESCRIPTION:Baysox vs. SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLdb-1R\n\nShop: https://stza.co/+vLdb-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ RubberDucks
<2018-08-27 Mon 18:05-21:05>
:PROPERTIES:
:ID:       JJrEkIJEEZz9QfIb04I6-Sjh@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox @ RubberDucks Baysox @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLaW-1h

Shop  https //stza.co/+vLaW-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ RubberDucks
END:VALARM
DTSTART:20180827T230500Z
DTEND:20180828T020500Z
UID:JJrEkIJEEZz9QfIb04I6-Sjh@stanza.co
SUMMARY:Baysox @ RubberDucks
DESCRIPTION:Baysox @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLaW-1h\n\nShop: https://stza.co/+vLaW-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ RubberDucks
<2018-08-28 Tue 18:05-21:05>
:PROPERTIES:
:ID:       scmdVRgVBeEb0FVO1rbuD9rM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ RubberDucks Baysox @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLaX-1w

Shop  https //stza.co/+vLaX-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ RubberDucks
END:VALARM
DTSTART:20180828T230500Z
DTEND:20180829T020500Z
UID:scmdVRgVBeEb0FVO1rbuD9rM@stanza.co
SUMMARY:Baysox @ RubberDucks
DESCRIPTION:Baysox @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLaX-1w\n\nShop: https://stza.co/+vLaX-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ RubberDucks
<2018-08-29 Wed 18:05-21:05>
:PROPERTIES:
:ID:       HpsowaBmkFWLZAWZRqGnV1iv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox @ RubberDucks Baysox @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLaY-3F

Shop  https //stza.co/+vLaY-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ RubberDucks
END:VALARM
DTSTART:20180829T230500Z
DTEND:20180830T020500Z
UID:HpsowaBmkFWLZAWZRqGnV1iv@stanza.co
SUMMARY:Baysox @ RubberDucks
DESCRIPTION:Baysox @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLaY-3F\n\nShop: https://stza.co/+vLaY-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox @ RubberDucks
<2018-08-30 Thu 18:05-21:05>
:PROPERTIES:
:ID:       Enxo7zfvR5WHxEFHvDVoztTw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox @ RubberDucks Baysox @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLaZ-1h

Shop  https //stza.co/+vLaZ-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Baysox @ RubberDucks
END:VALARM
DTSTART:20180830T230500Z
DTEND:20180831T020500Z
UID:Enxo7zfvR5WHxEFHvDVoztTw@stanza.co
SUMMARY:Baysox @ RubberDucks
DESCRIPTION:Baysox @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLaZ-1h\n\nShop: https://stza.co/+vLaZ-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Curve
<2018-08-31 Fri 18:05-21:05>
:PROPERTIES:
:ID:       nwBSD5ipQsBI0199Xa5i2Rlm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox vs. Curve Baysox vs. Curve

Follow on MiLB First Pitch  https //stza.co/+vLdc-38

Shop  https //stza.co/+vLdc-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Curve
END:VALARM
DTSTART:20180831T230500Z
DTEND:20180901T020500Z
UID:nwBSD5ipQsBI0199Xa5i2Rlm@stanza.co
SUMMARY:Baysox vs. Curve
DESCRIPTION:Baysox vs. Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLdc-38\n\nShop: https://stza.co/+vLdc-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Curve
<2018-09-01 Sat 17:35-20:35>
:PROPERTIES:
:ID:       ahLlgfk54CLgZSuF6I-V_Inf@stanza.co
:LOCATION: Stick around after tonight's game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Baysox vs. Curve Come out to the ballpark to catch the final Fireworks show of the 2018 Baysox season!

Follow on MiLB First Pitch  https //stza.co/+vLde-1D

Shop  https //stza.co/+vLde-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Curve
END:VALARM
DTSTART:20180901T223500Z
DTEND:20180902T013500Z
UID:ahLlgfk54CLgZSuF6I-V_Inf@stanza.co
SUMMARY:Baysox vs. Curve
DESCRIPTION:Come out to the ballpark to catch the final Fireworks show of the 2018 Baysox season!\n\nFollow on MiLB First Pitch: https://stza.co/+vLde-1D\n\nShop: https://stza.co/+vLde-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after tonight's game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Curve
<2018-09-02 Sun 12:35-15:35>
:PROPERTIES:
:ID:       M8O4u607yeMuiQVYEjIIb72l@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Baysox vs. Curve Baysox vs. Curve

Follow on MiLB First Pitch  https //stza.co/+vLdg-1x

Shop  https //stza.co/+vLdg-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Curve
END:VALARM
DTSTART:20180902T173500Z
DTEND:20180902T203500Z
UID:M8O4u607yeMuiQVYEjIIb72l@stanza.co
SUMMARY:Baysox vs. Curve
DESCRIPTION:Baysox vs. Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLdg-1x\n\nShop: https://stza.co/+vLdg-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Baysox vs. Curve
<2018-09-03 Mon 12:35-15:35>
:PROPERTIES:
:ID:       fAqfQMKbmWWDFukzjQtEx1Z-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Baysox vs. Curve Baysox vs. Curve

Follow on MiLB First Pitch  https //stza.co/+vLdj-C

Shop  https //stza.co/+vLdj-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Baysox vs. Curve
END:VALARM
DTSTART:20180903T173500Z
DTEND:20180903T203500Z
UID:fAqfQMKbmWWDFukzjQtEx1Z-@stanza.co
SUMMARY:Baysox vs. Curve
DESCRIPTION:Baysox vs. Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLdj-C\n\nShop: https://stza.co/+vLdj-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
