#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Mustangs vs. Osprey
<2018-06-15 Fri 20:05-23:05>
:PROPERTIES:
:ID:       gtCOllIcL3L4C_UgzJ-3dsRQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Osprey Mustangs vs. Osprey

Follow on MiLB First Pitch  https //stza.co/+xSNd-1P

Shop  https //stza.co/+xSNd-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Osprey
END:VALARM
DTSTART:20180616T010500Z
DTEND:20180616T040500Z
UID:gtCOllIcL3L4C_UgzJ-3dsRQ@stanza.co
SUMMARY:Mustangs vs. Osprey
DESCRIPTION:Mustangs vs. Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xSNd-1P\n\nShop: https://stza.co/+xSNd-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Osprey
<2018-06-16 Sat 19:05-22:05>
:PROPERTIES:
:ID:       uJtNq1Jn5B6CUFkeQopBftmR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Osprey Mustangs vs. Osprey

Follow on MiLB First Pitch  https //stza.co/+xSNe-3_

Shop  https //stza.co/+xSNe-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Osprey
END:VALARM
DTSTART:20180617T000500Z
DTEND:20180617T030500Z
UID:uJtNq1Jn5B6CUFkeQopBftmR@stanza.co
SUMMARY:Mustangs vs. Osprey
DESCRIPTION:Mustangs vs. Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xSNe-3_\n\nShop: https://stza.co/+xSNe-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Osprey
<2018-06-17 Sun 14:05-17:05>
:PROPERTIES:
:ID:       fjyOZ0QbiOOo2SmaClL3bR6V@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Osprey Mustangs vs. Osprey

Follow on MiLB First Pitch  https //stza.co/+xSNh-1W

Shop  https //stza.co/+xSNh-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Osprey
END:VALARM
DTSTART:20180617T190500Z
DTEND:20180617T220500Z
UID:fjyOZ0QbiOOo2SmaClL3bR6V@stanza.co
SUMMARY:Mustangs vs. Osprey
DESCRIPTION:Mustangs vs. Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xSNh-1W\n\nShop: https://stza.co/+xSNh-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Osprey
<2018-06-18 Mon 20:05-23:05>
:PROPERTIES:
:ID:       kaKwojFODfDOGimSM8W1EFkA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Osprey Mustangs vs. Osprey

Follow on MiLB First Pitch  https //stza.co/+xSNi-x

Shop  https //stza.co/+xSNi-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Osprey
END:VALARM
DTSTART:20180619T010500Z
DTEND:20180619T040500Z
UID:kaKwojFODfDOGimSM8W1EFkA@stanza.co
SUMMARY:Mustangs vs. Osprey
DESCRIPTION:Mustangs vs. Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xSNi-x\n\nShop: https://stza.co/+xSNi-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Voyagers
<2018-06-19 Tue>--<2018-06-18 Mon>
:PROPERTIES:
:ID:       XVcykSO2aEMGFv4H3gU3jsDZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mustangs @ Voyagers Mustangs @ Voyagers

Follow on MiLB First Pitch  https //stza.co/+xClT-3C

Shop  https //stza.co/+xClT-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180619
DTEND;VALUE=DATE:20180619
UID:XVcykSO2aEMGFv4H3gU3jsDZ@stanza.co
SUMMARY:Mustangs @ Voyagers
DESCRIPTION:Mustangs @ Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xClT-3C\n\nShop: https://stza.co/+xClT-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Voyagers
<2018-06-20 Wed>--<2018-06-19 Tue>
:PROPERTIES:
:ID:       CwmcdWCHIq5H7JqBUSkwdnUx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs @ Voyagers Mustangs @ Voyagers

Follow on MiLB First Pitch  https //stza.co/+xClU-1N

Shop  https //stza.co/+xClU-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180620
DTEND;VALUE=DATE:20180620
UID:CwmcdWCHIq5H7JqBUSkwdnUx@stanza.co
SUMMARY:Mustangs @ Voyagers
DESCRIPTION:Mustangs @ Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xClU-1N\n\nShop: https://stza.co/+xClU-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Voyagers
<2018-06-21 Thu>--<2018-06-20 Wed>
:PROPERTIES:
:ID:       0iUoDgMxNo2JdVLIauZqvQu1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs @ Voyagers Mustangs @ Voyagers

Follow on MiLB First Pitch  https //stza.co/+xClX-1F

Shop  https //stza.co/+xClX-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180621
DTEND;VALUE=DATE:20180621
UID:0iUoDgMxNo2JdVLIauZqvQu1@stanza.co
SUMMARY:Mustangs @ Voyagers
DESCRIPTION:Mustangs @ Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xClX-1F\n\nShop: https://stza.co/+xClX-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Brewers
<2018-06-22 Fri>--<2018-06-21 Thu>
:PROPERTIES:
:ID:       WMft_9qT0nRngwmH139fO3o2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mustangs @ Brewers Mustangs @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCeg-2C

Shop  https //stza.co/+xCeg-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180622
DTEND;VALUE=DATE:20180622
UID:WMft_9qT0nRngwmH139fO3o2@stanza.co
SUMMARY:Mustangs @ Brewers
DESCRIPTION:Mustangs @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCeg-2C\n\nShop: https://stza.co/+xCeg-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Brewers
<2018-06-23 Sat>--<2018-06-22 Fri>
:PROPERTIES:
:ID:       RFDFqs5M74HPgIM-RTCCQGTT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs @ Brewers Mustangs @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCei-1g

Shop  https //stza.co/+xCei-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180623
DTEND;VALUE=DATE:20180623
UID:RFDFqs5M74HPgIM-RTCCQGTT@stanza.co
SUMMARY:Mustangs @ Brewers
DESCRIPTION:Mustangs @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCei-1g\n\nShop: https://stza.co/+xCei-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Brewers
<2018-06-24 Sun>--<2018-06-23 Sat>
:PROPERTIES:
:ID:       4zo22S6M5k4xa7vSfxsWXIop@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs @ Brewers Mustangs @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCel-1u

Shop  https //stza.co/+xCel-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180624
DTEND;VALUE=DATE:20180624
UID:4zo22S6M5k4xa7vSfxsWXIop@stanza.co
SUMMARY:Mustangs @ Brewers
DESCRIPTION:Mustangs @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCel-1u\n\nShop: https://stza.co/+xCel-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Voyagers
<2018-06-25 Mon 20:05-23:05>
:PROPERTIES:
:ID:       tNKwjUbO9bDfMxZ5SQzve_D8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Voyagers Mustangs vs. Voyagers

Follow on MiLB First Pitch  https //stza.co/+xSNl-1I

Shop  https //stza.co/+xSNl-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Voyagers
END:VALARM
DTSTART:20180626T010500Z
DTEND:20180626T040500Z
UID:tNKwjUbO9bDfMxZ5SQzve_D8@stanza.co
SUMMARY:Mustangs vs. Voyagers
DESCRIPTION:Mustangs vs. Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xSNl-1I\n\nShop: https://stza.co/+xSNl-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Voyagers
<2018-06-26 Tue 20:05-23:05>
:PROPERTIES:
:ID:       8Dd_ku9CUbR61csCVCJ6m_Go@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Voyagers Mustangs vs. Voyagers

Follow on MiLB First Pitch  https //stza.co/+xSNm-2_

Shop  https //stza.co/+xSNm-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Voyagers
END:VALARM
DTSTART:20180627T010500Z
DTEND:20180627T040500Z
UID:8Dd_ku9CUbR61csCVCJ6m_Go@stanza.co
SUMMARY:Mustangs vs. Voyagers
DESCRIPTION:Mustangs vs. Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xSNm-2_\n\nShop: https://stza.co/+xSNm-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Voyagers
<2018-06-27 Wed 20:05-23:05>
:PROPERTIES:
:ID:       hNd4etzXhHBFkQUosbF1O4sM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Voyagers Mustangs vs. Voyagers

Follow on MiLB First Pitch  https //stza.co/+xSNp-3d

Shop  https //stza.co/+xSNp-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Voyagers
END:VALARM
DTSTART:20180628T010500Z
DTEND:20180628T040500Z
UID:hNd4etzXhHBFkQUosbF1O4sM@stanza.co
SUMMARY:Mustangs vs. Voyagers
DESCRIPTION:Mustangs vs. Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xSNp-3d\n\nShop: https://stza.co/+xSNp-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Brewers
<2018-06-28 Thu 20:05-23:05>
:PROPERTIES:
:ID:       jJrof2QOp6BXt3GIVDgLq0xW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Brewers Mustangs vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xSNq-_

Shop  https //stza.co/+xSNq-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Brewers
END:VALARM
DTSTART:20180629T010500Z
DTEND:20180629T040500Z
UID:jJrof2QOp6BXt3GIVDgLq0xW@stanza.co
SUMMARY:Mustangs vs. Brewers
DESCRIPTION:Mustangs vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xSNq-_\n\nShop: https://stza.co/+xSNq-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Brewers
<2018-06-29 Fri 20:05-23:05>
:PROPERTIES:
:ID:       K9N-2-JXGBYnjIoB3sqq7RUx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Brewers Mustangs vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xSNt-20

Shop  https //stza.co/+xSNt-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Brewers
END:VALARM
DTSTART:20180630T010500Z
DTEND:20180630T040500Z
UID:K9N-2-JXGBYnjIoB3sqq7RUx@stanza.co
SUMMARY:Mustangs vs. Brewers
DESCRIPTION:Mustangs vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xSNt-20\n\nShop: https://stza.co/+xSNt-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Osprey
<2018-06-30 Sat>--<2018-06-29 Fri>
:PROPERTIES:
:ID:       p7HD-z356IYZr0V-aPEk2CaL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs @ Osprey Mustangs @ Osprey

Follow on MiLB First Pitch  https //stza.co/+xClk-37

Shop  https //stza.co/+xClk-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Osprey
END:VALARM
DTSTART;VALUE=DATE:20180630
DTEND;VALUE=DATE:20180630
UID:p7HD-z356IYZr0V-aPEk2CaL@stanza.co
SUMMARY:Mustangs @ Osprey
DESCRIPTION:Mustangs @ Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xClk-37\n\nShop: https://stza.co/+xClk-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Osprey
<2018-07-01 Sun>--<2018-06-30 Sat>
:PROPERTIES:
:ID:       Yp_R4JNOMMDOdQ-kldcEQOcX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mustangs @ Osprey Mustangs @ Osprey

Follow on MiLB First Pitch  https //stza.co/+xClm-2p

Shop  https //stza.co/+xClm-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Osprey
END:VALARM
DTSTART;VALUE=DATE:20180701
DTEND;VALUE=DATE:20180701
UID:Yp_R4JNOMMDOdQ-kldcEQOcX@stanza.co
SUMMARY:Mustangs @ Osprey
DESCRIPTION:Mustangs @ Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xClm-2p\n\nShop: https://stza.co/+xClm-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Osprey
<2018-07-02 Mon>--<2018-07-01 Sun>
:PROPERTIES:
:ID:       TwOfzmeDZZnmSlDS0VnnjT0m@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs @ Osprey Mustangs @ Osprey

Follow on MiLB First Pitch  https //stza.co/+xClo-2n

Shop  https //stza.co/+xClo-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Osprey
END:VALARM
DTSTART;VALUE=DATE:20180702
DTEND;VALUE=DATE:20180702
UID:TwOfzmeDZZnmSlDS0VnnjT0m@stanza.co
SUMMARY:Mustangs @ Osprey
DESCRIPTION:Mustangs @ Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xClo-2n\n\nShop: https://stza.co/+xClo-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Osprey
<2018-07-03 Tue>--<2018-07-02 Mon>
:PROPERTIES:
:ID:       _tShleJDrTKzU-Z7UN3hgLFJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs @ Osprey Mustangs @ Osprey

Follow on MiLB First Pitch  https //stza.co/+xClr-2_

Shop  https //stza.co/+xClr-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Osprey
END:VALARM
DTSTART;VALUE=DATE:20180703
DTEND;VALUE=DATE:20180703
UID:_tShleJDrTKzU-Z7UN3hgLFJ@stanza.co
SUMMARY:Mustangs @ Osprey
DESCRIPTION:Mustangs @ Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xClr-2_\n\nShop: https://stza.co/+xClr-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Brewers
<2018-07-04 Wed 17:05-20:05>
:PROPERTIES:
:ID:       zLlcO9sVqHCzZwOiZgTruyAS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Brewers Mustangs vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xSNv-Z

Shop  https //stza.co/+xSNv-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Brewers
END:VALARM
DTSTART:20180704T220500Z
DTEND:20180705T010500Z
UID:zLlcO9sVqHCzZwOiZgTruyAS@stanza.co
SUMMARY:Mustangs vs. Brewers
DESCRIPTION:Mustangs vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xSNv-Z\n\nShop: https://stza.co/+xSNv-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Brewers
<2018-07-05 Thu 20:05-23:05>
:PROPERTIES:
:ID:       JyEMpZp1hYNH9HZEn6c0Y8Y9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Brewers Mustangs vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xSNy-1k

Shop  https //stza.co/+xSNy-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Brewers
END:VALARM
DTSTART:20180706T010500Z
DTEND:20180706T040500Z
UID:JyEMpZp1hYNH9HZEn6c0Y8Y9@stanza.co
SUMMARY:Mustangs vs. Brewers
DESCRIPTION:Mustangs vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xSNy-1k\n\nShop: https://stza.co/+xSNy-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Brewers
<2018-07-06 Fri 20:05-23:05>
:PROPERTIES:
:ID:       apCMYKkbXNUgUr7zOWkJvXmY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Brewers Mustangs vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xSNA-y

Shop  https //stza.co/+xSNA-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Brewers
END:VALARM
DTSTART:20180707T010500Z
DTEND:20180707T040500Z
UID:apCMYKkbXNUgUr7zOWkJvXmY@stanza.co
SUMMARY:Mustangs vs. Brewers
DESCRIPTION:Mustangs vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xSNA-y\n\nShop: https://stza.co/+xSNA-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Brewers
<2018-07-07 Sat>--<2018-07-06 Fri>
:PROPERTIES:
:ID:       g0DW7ZN2ilgKMMrwCcgjZ7DV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mustangs @ Brewers Mustangs @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCen-v

Shop  https //stza.co/+xCen-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180707
DTEND;VALUE=DATE:20180707
UID:g0DW7ZN2ilgKMMrwCcgjZ7DV@stanza.co
SUMMARY:Mustangs @ Brewers
DESCRIPTION:Mustangs @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCen-v\n\nShop: https://stza.co/+xCen-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Brewers
<2018-07-08 Sun>--<2018-07-07 Sat>
:PROPERTIES:
:ID:       yXMOShMwQfsKNoxzJiBgNJwM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs @ Brewers Mustangs @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCep-1h

Shop  https //stza.co/+xCep-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180708
DTEND;VALUE=DATE:20180708
UID:yXMOShMwQfsKNoxzJiBgNJwM@stanza.co
SUMMARY:Mustangs @ Brewers
DESCRIPTION:Mustangs @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCep-1h\n\nShop: https://stza.co/+xCep-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Rockies
<2018-07-10 Tue 20:05-23:05>
:PROPERTIES:
:ID:       yAPf7M7phWPA4hWcRYuJEBUN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Rockies Mustangs vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+xSNC-2i

Shop  https //stza.co/+xSNC-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Rockies
END:VALARM
DTSTART:20180711T010500Z
DTEND:20180711T040500Z
UID:yAPf7M7phWPA4hWcRYuJEBUN@stanza.co
SUMMARY:Mustangs vs. Rockies
DESCRIPTION:Mustangs vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xSNC-2i\n\nShop: https://stza.co/+xSNC-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Rockies
<2018-07-11 Wed 20:05-23:05>
:PROPERTIES:
:ID:       2nic04hzyN1Z7Uaw7y_KOXlI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Rockies Mustangs vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+xSNE-1I

Shop  https //stza.co/+xSNE-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Rockies
END:VALARM
DTSTART:20180712T010500Z
DTEND:20180712T040500Z
UID:2nic04hzyN1Z7Uaw7y_KOXlI@stanza.co
SUMMARY:Mustangs vs. Rockies
DESCRIPTION:Mustangs vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xSNE-1I\n\nShop: https://stza.co/+xSNE-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Rockies
<2018-07-12 Thu 20:05-23:05>
:PROPERTIES:
:ID:       1YhzrG-y-xKNQNXVmLMXAmRA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Rockies Mustangs vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+xSNG-w

Shop  https //stza.co/+xSNG-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Rockies
END:VALARM
DTSTART:20180713T010500Z
DTEND:20180713T040500Z
UID:1YhzrG-y-xKNQNXVmLMXAmRA@stanza.co
SUMMARY:Mustangs vs. Rockies
DESCRIPTION:Mustangs vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xSNG-w\n\nShop: https://stza.co/+xSNG-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Rockies
<2018-07-13 Fri 20:05-23:05>
:PROPERTIES:
:ID:       YWRhl0Qki-V3sOYkVJ7yUx0u@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Rockies Mustangs vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+xSNI-n

Shop  https //stza.co/+xSNI-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Rockies
END:VALARM
DTSTART:20180714T010500Z
DTEND:20180714T040500Z
UID:YWRhl0Qki-V3sOYkVJ7yUx0u@stanza.co
SUMMARY:Mustangs vs. Rockies
DESCRIPTION:Mustangs vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xSNI-n\n\nShop: https://stza.co/+xSNI-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Owlz
<2018-07-14 Sat 19:05-22:05>
:PROPERTIES:
:ID:       z1GR_4rK86CiH0PGCw2VgDfT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Owlz Mustangs vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+xSNJ-1E

Shop  https //stza.co/+xSNJ-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Owlz
END:VALARM
DTSTART:20180715T000500Z
DTEND:20180715T030500Z
UID:z1GR_4rK86CiH0PGCw2VgDfT@stanza.co
SUMMARY:Mustangs vs. Owlz
DESCRIPTION:Mustangs vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xSNJ-1E\n\nShop: https://stza.co/+xSNJ-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Owlz
<2018-07-15 Sun 14:05-17:05>
:PROPERTIES:
:ID:       6YTt0uDjH2SopXbV0-zjjoA7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Owlz Mustangs vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+xSNM-3B

Shop  https //stza.co/+xSNM-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Owlz
END:VALARM
DTSTART:20180715T190500Z
DTEND:20180715T220500Z
UID:6YTt0uDjH2SopXbV0-zjjoA7@stanza.co
SUMMARY:Mustangs vs. Owlz
DESCRIPTION:Mustangs vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xSNM-3B\n\nShop: https://stza.co/+xSNM-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Owlz
<2018-07-16 Mon 20:05-23:05>
:PROPERTIES:
:ID:       GyAEWlM9GJDqMrJOycrDdnz6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Owlz Mustangs vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+xSNO-10

Shop  https //stza.co/+xSNO-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Owlz
END:VALARM
DTSTART:20180717T010500Z
DTEND:20180717T040500Z
UID:GyAEWlM9GJDqMrJOycrDdnz6@stanza.co
SUMMARY:Mustangs vs. Owlz
DESCRIPTION:Mustangs vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xSNO-10\n\nShop: https://stza.co/+xSNO-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Rockies
<2018-07-18 Wed 19:40-22:40>
:PROPERTIES:
:ID:       kZnky12VX0AHwQ0kjWF04u5M@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mustangs @ Rockies Mustangs @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ6R-3H

Shop  https //stza.co/+xJ6R-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Rockies
END:VALARM
DTSTART:20180719T004000Z
DTEND:20180719T034000Z
UID:kZnky12VX0AHwQ0kjWF04u5M@stanza.co
SUMMARY:Mustangs @ Rockies
DESCRIPTION:Mustangs @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ6R-3H\n\nShop: https://stza.co/+xJ6R-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Rockies
<2018-07-19 Thu 19:40-22:40>
:PROPERTIES:
:ID:       dP6Uo4IWHjal4d9NGrKC6P6R@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs @ Rockies Mustangs @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ6S-3v

Shop  https //stza.co/+xJ6S-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Rockies
END:VALARM
DTSTART:20180720T004000Z
DTEND:20180720T034000Z
UID:dP6Uo4IWHjal4d9NGrKC6P6R@stanza.co
SUMMARY:Mustangs @ Rockies
DESCRIPTION:Mustangs @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ6S-3v\n\nShop: https://stza.co/+xJ6S-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Rockies
<2018-07-20 Fri 19:40-22:40>
:PROPERTIES:
:ID:       1sz02gO3J8ZLL2nH6TYNaO7N@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs @ Rockies Mustangs @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ6T-2H

Shop  https //stza.co/+xJ6T-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Rockies
END:VALARM
DTSTART:20180721T004000Z
DTEND:20180721T034000Z
UID:1sz02gO3J8ZLL2nH6TYNaO7N@stanza.co
SUMMARY:Mustangs @ Rockies
DESCRIPTION:Mustangs @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ6T-2H\n\nShop: https://stza.co/+xJ6T-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Owlz
<2018-07-21 Sat 20:05-23:05>
:PROPERTIES:
:ID:       jBugAl-yprWkH8w6AyXbGUyd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mustangs @ Owlz Mustangs @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPB0-J

Shop  https //stza.co/+xPB0-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Owlz
END:VALARM
DTSTART:20180722T010500Z
DTEND:20180722T040500Z
UID:jBugAl-yprWkH8w6AyXbGUyd@stanza.co
SUMMARY:Mustangs @ Owlz
DESCRIPTION:Mustangs @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPB0-J\n\nShop: https://stza.co/+xPB0-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Owlz
<2018-07-22 Sun 17:05-20:05>
:PROPERTIES:
:ID:       1YOsL_zHAvuMvwRVvon1A_mQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs @ Owlz Mustangs @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPB1-2F

Shop  https //stza.co/+xPB1-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Owlz
END:VALARM
DTSTART:20180722T220500Z
DTEND:20180723T010500Z
UID:1YOsL_zHAvuMvwRVvon1A_mQ@stanza.co
SUMMARY:Mustangs @ Owlz
DESCRIPTION:Mustangs @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPB1-2F\n\nShop: https://stza.co/+xPB1-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Owlz
<2018-07-23 Mon 20:05-23:05>
:PROPERTIES:
:ID:       BWvErbn7Nv-yK3nB0Si08yEX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs @ Owlz Mustangs @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPB2-3p

Shop  https //stza.co/+xPB2-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Owlz
END:VALARM
DTSTART:20180724T010500Z
DTEND:20180724T040500Z
UID:BWvErbn7Nv-yK3nB0Si08yEX@stanza.co
SUMMARY:Mustangs @ Owlz
DESCRIPTION:Mustangs @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPB2-3p\n\nShop: https://stza.co/+xPB2-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Owlz
<2018-07-24 Tue 20:05-23:05>
:PROPERTIES:
:ID:       eIkhXbQDLmst2diunVNAGwUU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mustangs @ Owlz Mustangs @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPB3-a

Shop  https //stza.co/+xPB3-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Owlz
END:VALARM
DTSTART:20180725T010500Z
DTEND:20180725T040500Z
UID:eIkhXbQDLmst2diunVNAGwUU@stanza.co
SUMMARY:Mustangs @ Owlz
DESCRIPTION:Mustangs @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPB3-a\n\nShop: https://stza.co/+xPB3-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Osprey
<2018-07-26 Thu 20:05-23:05>
:PROPERTIES:
:ID:       AMNFUtToC9_P1q6UQM22XsiU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Osprey Mustangs vs. Osprey

Follow on MiLB First Pitch  https //stza.co/+xSNR-3O

Shop  https //stza.co/+xSNR-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Osprey
END:VALARM
DTSTART:20180727T010500Z
DTEND:20180727T040500Z
UID:AMNFUtToC9_P1q6UQM22XsiU@stanza.co
SUMMARY:Mustangs vs. Osprey
DESCRIPTION:Mustangs vs. Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xSNR-3O\n\nShop: https://stza.co/+xSNR-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Osprey
<2018-07-27 Fri 20:05-23:05>
:PROPERTIES:
:ID:       fcVizUFcplAXjkbCA50KUziu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Osprey Mustangs vs. Osprey

Follow on MiLB First Pitch  https //stza.co/+xSNS-1m

Shop  https //stza.co/+xSNS-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Osprey
END:VALARM
DTSTART:20180728T010500Z
DTEND:20180728T040500Z
UID:fcVizUFcplAXjkbCA50KUziu@stanza.co
SUMMARY:Mustangs vs. Osprey
DESCRIPTION:Mustangs vs. Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xSNS-1m\n\nShop: https://stza.co/+xSNS-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Osprey
<2018-07-28 Sat 19:05-22:05>
:PROPERTIES:
:ID:       SmTOFHeJbde2y1T2DstK0NBE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Osprey Mustangs vs. Osprey

Follow on MiLB First Pitch  https //stza.co/+xSNU-1D

Shop  https //stza.co/+xSNU-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Osprey
END:VALARM
DTSTART:20180729T000500Z
DTEND:20180729T030500Z
UID:SmTOFHeJbde2y1T2DstK0NBE@stanza.co
SUMMARY:Mustangs vs. Osprey
DESCRIPTION:Mustangs vs. Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xSNU-1D\n\nShop: https://stza.co/+xSNU-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Osprey
<2018-07-29 Sun 14:05-17:05>
:PROPERTIES:
:ID:       j9urpeOIYkRsdbl7ahSUiL3U@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Osprey Mustangs vs. Osprey

Follow on MiLB First Pitch  https //stza.co/+xSNX-R

Shop  https //stza.co/+xSNX-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Osprey
END:VALARM
DTSTART:20180729T190500Z
DTEND:20180729T220500Z
UID:j9urpeOIYkRsdbl7ahSUiL3U@stanza.co
SUMMARY:Mustangs vs. Osprey
DESCRIPTION:Mustangs vs. Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xSNX-R\n\nShop: https://stza.co/+xSNX-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Voyagers
<2018-07-30 Mon 20:05-23:05>
:PROPERTIES:
:ID:       zJ2Lb3B4V5sFffQ7ZhuKw-K0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Voyagers Mustangs vs. Voyagers

Follow on MiLB First Pitch  https //stza.co/+xSNY-2n

Shop  https //stza.co/+xSNY-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Voyagers
END:VALARM
DTSTART:20180731T010500Z
DTEND:20180731T040500Z
UID:zJ2Lb3B4V5sFffQ7ZhuKw-K0@stanza.co
SUMMARY:Mustangs vs. Voyagers
DESCRIPTION:Mustangs vs. Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xSNY-2n\n\nShop: https://stza.co/+xSNY-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Voyagers
<2018-07-31 Tue 20:05-23:05>
:PROPERTIES:
:ID:       a5X__Q5SZH-dtze8-qxyXYRF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Voyagers Mustangs vs. Voyagers

Follow on MiLB First Pitch  https //stza.co/+xSN_-3W

Shop  https //stza.co/+xSN_-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Voyagers
END:VALARM
DTSTART:20180801T010500Z
DTEND:20180801T040500Z
UID:a5X__Q5SZH-dtze8-qxyXYRF@stanza.co
SUMMARY:Mustangs vs. Voyagers
DESCRIPTION:Mustangs vs. Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xSN_-3W\n\nShop: https://stza.co/+xSN_-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Voyagers
<2018-08-01 Wed>--<2018-07-31 Tue>
:PROPERTIES:
:ID:       OW67HEYZOtxTK3cARtuPeEfP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs @ Voyagers Mustangs @ Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCl_-k

Shop  https //stza.co/+xCl_-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180801
DTEND;VALUE=DATE:20180801
UID:OW67HEYZOtxTK3cARtuPeEfP@stanza.co
SUMMARY:Mustangs @ Voyagers
DESCRIPTION:Mustangs @ Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCl_-k\n\nShop: https://stza.co/+xCl_-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Voyagers
<2018-08-02 Thu>--<2018-08-01 Wed>
:PROPERTIES:
:ID:       W-dXanscpeHAbPQtIW_0HQZZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs @ Voyagers Mustangs @ Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCm1-3r

Shop  https //stza.co/+xCm1-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180802
DTEND;VALUE=DATE:20180802
UID:W-dXanscpeHAbPQtIW_0HQZZ@stanza.co
SUMMARY:Mustangs @ Voyagers
DESCRIPTION:Mustangs @ Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCm1-3r\n\nShop: https://stza.co/+xCm1-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Brewers
<2018-08-03 Fri>--<2018-08-02 Thu>
:PROPERTIES:
:ID:       Vofaa9VsnaOwKvnhq8hJwzTz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mustangs @ Brewers Mustangs @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCer-4

Shop  https //stza.co/+xCer-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180803
DTEND;VALUE=DATE:20180803
UID:Vofaa9VsnaOwKvnhq8hJwzTz@stanza.co
SUMMARY:Mustangs @ Brewers
DESCRIPTION:Mustangs @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCer-4\n\nShop: https://stza.co/+xCer-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Brewers
<2018-08-04 Sat>--<2018-08-03 Fri>
:PROPERTIES:
:ID:       Ls9-EEmSbHlRqwDcw-cn8XHQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs @ Brewers Mustangs @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCet-2E

Shop  https //stza.co/+xCet-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180804
DTEND;VALUE=DATE:20180804
UID:Ls9-EEmSbHlRqwDcw-cn8XHQ@stanza.co
SUMMARY:Mustangs @ Brewers
DESCRIPTION:Mustangs @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCet-2E\n\nShop: https://stza.co/+xCet-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Brewers
<2018-08-05 Sun>--<2018-08-04 Sat>
:PROPERTIES:
:ID:       Nd9FPbpeSIDdAOKirHYj04oA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs @ Brewers Mustangs @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCey-1p

Shop  https //stza.co/+xCey-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180805
DTEND;VALUE=DATE:20180805
UID:Nd9FPbpeSIDdAOKirHYj04oA@stanza.co
SUMMARY:Mustangs @ Brewers
DESCRIPTION:Mustangs @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCey-1p\n\nShop: https://stza.co/+xCey-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Raptors
<2018-08-09 Thu 20:05-23:05>
:PROPERTIES:
:ID:       7gCfLGBI-chty_yKOjsWxMeo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Raptors Mustangs vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xSO0-2N

Shop  https //stza.co/+xSO0-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Raptors
END:VALARM
DTSTART:20180810T010500Z
DTEND:20180810T040500Z
UID:7gCfLGBI-chty_yKOjsWxMeo@stanza.co
SUMMARY:Mustangs vs. Raptors
DESCRIPTION:Mustangs vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xSO0-2N\n\nShop: https://stza.co/+xSO0-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Raptors
<2018-08-10 Fri 20:05-23:05>
:PROPERTIES:
:ID:       GIkZUDIjTgtcZLBGQ5L78Hv5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Raptors Mustangs vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xSO2-2I

Shop  https //stza.co/+xSO2-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Raptors
END:VALARM
DTSTART:20180811T010500Z
DTEND:20180811T040500Z
UID:GIkZUDIjTgtcZLBGQ5L78Hv5@stanza.co
SUMMARY:Mustangs vs. Raptors
DESCRIPTION:Mustangs vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xSO2-2I\n\nShop: https://stza.co/+xSO2-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Raptors
<2018-08-11 Sat 19:05-22:05>
:PROPERTIES:
:ID:       6zcP6fsno4IHjhKs2olUQ0_p@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Raptors Mustangs vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xSO5-26

Shop  https //stza.co/+xSO5-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Raptors
END:VALARM
DTSTART:20180812T000500Z
DTEND:20180812T030500Z
UID:6zcP6fsno4IHjhKs2olUQ0_p@stanza.co
SUMMARY:Mustangs vs. Raptors
DESCRIPTION:Mustangs vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xSO5-26\n\nShop: https://stza.co/+xSO5-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Raptors
<2018-08-12 Sun 14:05-17:05>
:PROPERTIES:
:ID:       L9okCDeMNN0tUz4nwIMeFli3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Raptors Mustangs vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xSO7-2x

Shop  https //stza.co/+xSO7-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Raptors
END:VALARM
DTSTART:20180812T190500Z
DTEND:20180812T220500Z
UID:L9okCDeMNN0tUz4nwIMeFli3@stanza.co
SUMMARY:Mustangs vs. Raptors
DESCRIPTION:Mustangs vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xSO7-2x\n\nShop: https://stza.co/+xSO7-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Chukars
<2018-08-13 Mon 20:05-23:05>
:PROPERTIES:
:ID:       Ax_IO09QDx-MarLNBsJSqfEG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Chukars Mustangs vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+xSO9-m

Shop  https //stza.co/+xSO9-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Chukars
END:VALARM
DTSTART:20180814T010500Z
DTEND:20180814T040500Z
UID:Ax_IO09QDx-MarLNBsJSqfEG@stanza.co
SUMMARY:Mustangs vs. Chukars
DESCRIPTION:Mustangs vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xSO9-m\n\nShop: https://stza.co/+xSO9-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Chukars
<2018-08-14 Tue 20:05-23:05>
:PROPERTIES:
:ID:       FcBO6Y6_xcjfd8yEHo7KVYK1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Chukars Mustangs vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+xSOa-R

Shop  https //stza.co/+xSOa-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Chukars
END:VALARM
DTSTART:20180815T010500Z
DTEND:20180815T040500Z
UID:FcBO6Y6_xcjfd8yEHo7KVYK1@stanza.co
SUMMARY:Mustangs vs. Chukars
DESCRIPTION:Mustangs vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xSOa-R\n\nShop: https://stza.co/+xSOa-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Chukars
<2018-08-15 Wed 20:05-23:05>
:PROPERTIES:
:ID:       ZEwrmAvhZHq8_VmtIA3RFlMV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Chukars Mustangs vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+xSOd-3g

Shop  https //stza.co/+xSOd-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Chukars
END:VALARM
DTSTART:20180816T010500Z
DTEND:20180816T040500Z
UID:ZEwrmAvhZHq8_VmtIA3RFlMV@stanza.co
SUMMARY:Mustangs vs. Chukars
DESCRIPTION:Mustangs vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xSOd-3g\n\nShop: https://stza.co/+xSOd-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Raptors
<2018-08-17 Fri 20:00-23:00>
:PROPERTIES:
:ID:       RL5XYqUkUZSv2qB_gI5PgGhm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs @ Raptors Mustangs @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$7L-g

Shop  https //stza.co/+x$7L-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Raptors
END:VALARM
DTSTART:20180818T010000Z
DTEND:20180818T040000Z
UID:RL5XYqUkUZSv2qB_gI5PgGhm@stanza.co
SUMMARY:Mustangs @ Raptors
DESCRIPTION:Mustangs @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$7L-g\n\nShop: https://stza.co/+x$7L-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Raptors
<2018-08-18 Sat 20:00-23:00>
:PROPERTIES:
:ID:       v_EaP5AokNkVbPtDKR6iDaZl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs @ Raptors Mustangs @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$7M-30

Shop  https //stza.co/+x$7M-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Raptors
END:VALARM
DTSTART:20180819T010000Z
DTEND:20180819T040000Z
UID:v_EaP5AokNkVbPtDKR6iDaZl@stanza.co
SUMMARY:Mustangs @ Raptors
DESCRIPTION:Mustangs @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$7M-30\n\nShop: https://stza.co/+x$7M-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Raptors
<2018-08-19 Sun 17:00-20:00>
:PROPERTIES:
:ID:       lvH0cbqVksNeOx13UngPgt9C@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mustangs @ Raptors Mustangs @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$7N-1C

Shop  https //stza.co/+x$7N-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Raptors
END:VALARM
DTSTART:20180819T220000Z
DTEND:20180820T010000Z
UID:lvH0cbqVksNeOx13UngPgt9C@stanza.co
SUMMARY:Mustangs @ Raptors
DESCRIPTION:Mustangs @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$7N-1C\n\nShop: https://stza.co/+x$7N-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Chukars
<2018-08-20 Mon 20:15-23:15>
:PROPERTIES:
:ID:       yPFRKna-oLBFBYmC_ZUnr3Bs@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs @ Chukars Mustangs @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZUw-2S

Shop  https //stza.co/+xZUw-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Chukars
END:VALARM
DTSTART:20180821T011500Z
DTEND:20180821T041500Z
UID:yPFRKna-oLBFBYmC_ZUnr3Bs@stanza.co
SUMMARY:Mustangs @ Chukars
DESCRIPTION:Mustangs @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZUw-2S\n\nShop: https://stza.co/+xZUw-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Chukars
<2018-08-21 Tue 20:15-23:15>
:PROPERTIES:
:ID:       3FVuIE86or-pULPQuwvT89mF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs @ Chukars Mustangs @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZUx-1D

Shop  https //stza.co/+xZUx-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Chukars
END:VALARM
DTSTART:20180822T011500Z
DTEND:20180822T041500Z
UID:3FVuIE86or-pULPQuwvT89mF@stanza.co
SUMMARY:Mustangs @ Chukars
DESCRIPTION:Mustangs @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZUx-1D\n\nShop: https://stza.co/+xZUx-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Chukars
<2018-08-22 Wed 20:15-23:15>
:PROPERTIES:
:ID:       w_bWodYpwzf2WPOaMVIT1rqW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mustangs @ Chukars Mustangs @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZUy-1S

Shop  https //stza.co/+xZUy-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Chukars
END:VALARM
DTSTART:20180823T011500Z
DTEND:20180823T041500Z
UID:w_bWodYpwzf2WPOaMVIT1rqW@stanza.co
SUMMARY:Mustangs @ Chukars
DESCRIPTION:Mustangs @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZUy-1S\n\nShop: https://stza.co/+xZUy-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Chukars
<2018-08-23 Thu 20:15-23:15>
:PROPERTIES:
:ID:       1_ZDgiLRz7tXmclrgPdPWxoy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs @ Chukars Mustangs @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZUz-1d

Shop  https //stza.co/+xZUz-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Chukars
END:VALARM
DTSTART:20180824T011500Z
DTEND:20180824T041500Z
UID:1_ZDgiLRz7tXmclrgPdPWxoy@stanza.co
SUMMARY:Mustangs @ Chukars
DESCRIPTION:Mustangs @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZUz-1d\n\nShop: https://stza.co/+xZUz-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Brewers
<2018-08-24 Fri 20:05-23:05>
:PROPERTIES:
:ID:       En_YpR5CgqbqOkG0eIqcLP11@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Brewers Mustangs vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xSOe-2p

Shop  https //stza.co/+xSOe-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Brewers
END:VALARM
DTSTART:20180825T010500Z
DTEND:20180825T040500Z
UID:En_YpR5CgqbqOkG0eIqcLP11@stanza.co
SUMMARY:Mustangs vs. Brewers
DESCRIPTION:Mustangs vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xSOe-2p\n\nShop: https://stza.co/+xSOe-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Brewers
<2018-08-25 Sat 19:05-22:05>
:PROPERTIES:
:ID:       Fg0f3hJmEUv2XzTjDA5k2Qs-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Brewers Mustangs vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xSOh-3l

Shop  https //stza.co/+xSOh-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Brewers
END:VALARM
DTSTART:20180826T000500Z
DTEND:20180826T030500Z
UID:Fg0f3hJmEUv2XzTjDA5k2Qs-@stanza.co
SUMMARY:Mustangs vs. Brewers
DESCRIPTION:Mustangs vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xSOh-3l\n\nShop: https://stza.co/+xSOh-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Brewers
<2018-08-26 Sun 14:05-17:05>
:PROPERTIES:
:ID:       Y-j9udm3zRmABXGvwJKcPK2E@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Brewers Mustangs vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xSOj-2g

Shop  https //stza.co/+xSOj-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Brewers
END:VALARM
DTSTART:20180826T190500Z
DTEND:20180826T220500Z
UID:Y-j9udm3zRmABXGvwJKcPK2E@stanza.co
SUMMARY:Mustangs vs. Brewers
DESCRIPTION:Mustangs vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xSOj-2g\n\nShop: https://stza.co/+xSOj-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Osprey
<2018-08-28 Tue>--<2018-08-27 Mon>
:PROPERTIES:
:ID:       QjX8vRJtYzJlRdEHNBcE_OqX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs @ Osprey Mustangs @ Osprey

Follow on MiLB First Pitch  https //stza.co/+xClu-2h

Shop  https //stza.co/+xClu-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Osprey
END:VALARM
DTSTART;VALUE=DATE:20180828
DTEND;VALUE=DATE:20180828
UID:QjX8vRJtYzJlRdEHNBcE_OqX@stanza.co
SUMMARY:Mustangs @ Osprey
DESCRIPTION:Mustangs @ Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xClu-2h\n\nShop: https://stza.co/+xClu-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Osprey
<2018-08-29 Wed>--<2018-08-28 Tue>
:PROPERTIES:
:ID:       LR1s4FXMZ6dSi5puH8g-JlhX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mustangs @ Osprey Mustangs @ Osprey

Follow on MiLB First Pitch  https //stza.co/+xClv-2Y

Shop  https //stza.co/+xClv-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Osprey
END:VALARM
DTSTART;VALUE=DATE:20180829
DTEND;VALUE=DATE:20180829
UID:LR1s4FXMZ6dSi5puH8g-JlhX@stanza.co
SUMMARY:Mustangs @ Osprey
DESCRIPTION:Mustangs @ Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xClv-2Y\n\nShop: https://stza.co/+xClv-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Osprey
<2018-08-30 Thu>--<2018-08-29 Wed>
:PROPERTIES:
:ID:       uROz6QNms1ixzrLKufwJLUk-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs @ Osprey Mustangs @ Osprey

Follow on MiLB First Pitch  https //stza.co/+xCly-3C

Shop  https //stza.co/+xCly-1w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Osprey
END:VALARM
DTSTART;VALUE=DATE:20180830
DTEND;VALUE=DATE:20180830
UID:uROz6QNms1ixzrLKufwJLUk-@stanza.co
SUMMARY:Mustangs @ Osprey
DESCRIPTION:Mustangs @ Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xCly-3C\n\nShop: https://stza.co/+xCly-1w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Osprey
<2018-08-31 Fri>--<2018-08-30 Thu>
:PROPERTIES:
:ID:       FN-wdT9jRSyxKhv6IDORGt-S@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs @ Osprey Mustangs @ Osprey

Follow on MiLB First Pitch  https //stza.co/+xClB-t

Shop  https //stza.co/+xClB-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Osprey
END:VALARM
DTSTART;VALUE=DATE:20180831
DTEND;VALUE=DATE:20180831
UID:FN-wdT9jRSyxKhv6IDORGt-S@stanza.co
SUMMARY:Mustangs @ Osprey
DESCRIPTION:Mustangs @ Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xClB-t\n\nShop: https://stza.co/+xClB-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Voyagers
<2018-09-01 Sat>--<2018-08-31 Fri>
:PROPERTIES:
:ID:       Zbl4Rr_lJozvCiRh-Dne28ns@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mustangs @ Voyagers Mustangs @ Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCm4-13

Shop  https //stza.co/+xCm4-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180901
DTEND;VALUE=DATE:20180901
UID:Zbl4Rr_lJozvCiRh-Dne28ns@stanza.co
SUMMARY:Mustangs @ Voyagers
DESCRIPTION:Mustangs @ Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCm4-13\n\nShop: https://stza.co/+xCm4-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Voyagers
<2018-09-02 Sun>--<2018-09-01 Sat>
:PROPERTIES:
:ID:       KWwXW9MsRmFUkDfexeCtfusl@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs @ Voyagers Mustangs @ Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCm7-1h

Shop  https //stza.co/+xCm7-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180902
DTEND;VALUE=DATE:20180902
UID:KWwXW9MsRmFUkDfexeCtfusl@stanza.co
SUMMARY:Mustangs @ Voyagers
DESCRIPTION:Mustangs @ Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCm7-1h\n\nShop: https://stza.co/+xCm7-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs @ Voyagers
<2018-09-03 Mon>--<2018-09-02 Sun>
:PROPERTIES:
:ID:       w_r2nFbma-Tg3A2q9FyXh795@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs @ Voyagers Mustangs @ Voyagers

Follow on MiLB First Pitch  https //stza.co/+xBum-3f

Shop  https //stza.co/+xBum-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mustangs @ Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180903
DTEND;VALUE=DATE:20180903
UID:w_r2nFbma-Tg3A2q9FyXh795@stanza.co
SUMMARY:Mustangs @ Voyagers
DESCRIPTION:Mustangs @ Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xBum-3f\n\nShop: https://stza.co/+xBum-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Voyagers
<2018-09-04 Tue 20:05-23:05>
:PROPERTIES:
:ID:       kyJPhkLwIezdVs4HFPDBL8qs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Voyagers Mustangs vs. Voyagers

Follow on MiLB First Pitch  https //stza.co/+xSOl-_

Shop  https //stza.co/+xSOl-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Voyagers
END:VALARM
DTSTART:20180905T010500Z
DTEND:20180905T040500Z
UID:kyJPhkLwIezdVs4HFPDBL8qs@stanza.co
SUMMARY:Mustangs vs. Voyagers
DESCRIPTION:Mustangs vs. Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xSOl-_\n\nShop: https://stza.co/+xSOl-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Voyagers
<2018-09-05 Wed 20:05-23:05>
:PROPERTIES:
:ID:       XCDrwEvCCnm_7joR8OaX-mZ3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Voyagers Mustangs vs. Voyagers

Follow on MiLB First Pitch  https //stza.co/+xSOm-2p

Shop  https //stza.co/+xSOm-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Voyagers
END:VALARM
DTSTART:20180906T010500Z
DTEND:20180906T040500Z
UID:XCDrwEvCCnm_7joR8OaX-mZ3@stanza.co
SUMMARY:Mustangs vs. Voyagers
DESCRIPTION:Mustangs vs. Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xSOm-2p\n\nShop: https://stza.co/+xSOm-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Mustangs vs. Voyagers
<2018-09-06 Thu 20:05-23:05>
:PROPERTIES:
:ID:       VMRnOrZQAFx4j-WxX_D4SNYs@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mustangs vs. Voyagers Mustangs vs. Voyagers

Follow on MiLB First Pitch  https //stza.co/+xSOp-1K

Shop  https //stza.co/+xSOp-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mustangs vs. Voyagers
END:VALARM
DTSTART:20180907T010500Z
DTEND:20180907T040500Z
UID:VMRnOrZQAFx4j-WxX_D4SNYs@stanza.co
SUMMARY:Mustangs vs. Voyagers
DESCRIPTION:Mustangs vs. Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xSOp-1K\n\nShop: https://stza.co/+xSOp-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
