#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Indians vs. Hawks
<2018-06-15 Fri 20:30-23:30>
:PROPERTIES:
:ID:       35R9znLNTJEKE4h9sExmnetT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians vs. Hawks Indians vs. Hawks

Follow on MiLB First Pitch  https //stza.co/+xCau-15

Shop  https //stza.co/+xCau-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. Hawks
END:VALARM
DTSTART:20180616T013000Z
DTEND:20180616T043000Z
UID:35R9znLNTJEKE4h9sExmnetT@stanza.co
SUMMARY:Indians vs. Hawks
DESCRIPTION:Indians vs. Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xCau-15\n\nShop: https://stza.co/+xCau-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. Hawks
<2018-06-16 Sat 20:30-23:30>
:PROPERTIES:
:ID:       C798BE1eUWvokGZYO55uQ3Qg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Indians vs. Hawks Indians vs. Hawks

Follow on MiLB First Pitch  https //stza.co/+xCaz-2k

Shop  https //stza.co/+xCaz-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. Hawks
END:VALARM
DTSTART:20180617T013000Z
DTEND:20180617T043000Z
UID:C798BE1eUWvokGZYO55uQ3Qg@stanza.co
SUMMARY:Indians vs. Hawks
DESCRIPTION:Indians vs. Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xCaz-2k\n\nShop: https://stza.co/+xCaz-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. Hawks
<2018-06-17 Sun 17:30-20:30>
:PROPERTIES:
:ID:       IlvwNqwjqVNWaGYbNE0HyJGP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians vs. Hawks Indians vs. Hawks

Follow on MiLB First Pitch  https //stza.co/+xCaE-2C

Shop  https //stza.co/+xCaE-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. Hawks
END:VALARM
DTSTART:20180617T223000Z
DTEND:20180618T013000Z
UID:IlvwNqwjqVNWaGYbNE0HyJGP@stanza.co
SUMMARY:Indians vs. Hawks
DESCRIPTION:Indians vs. Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xCaE-2C\n\nShop: https://stza.co/+xCaE-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. Hawks
<2018-06-18 Mon 20:30-23:30>
:PROPERTIES:
:ID:       2rmzoG5ZKTrgtofEYgHEJNf4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians vs. Hawks Indians vs. Hawks

Follow on MiLB First Pitch  https //stza.co/+xCaH-33

Shop  https //stza.co/+xCaH-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. Hawks
END:VALARM
DTSTART:20180619T013000Z
DTEND:20180619T043000Z
UID:2rmzoG5ZKTrgtofEYgHEJNf4@stanza.co
SUMMARY:Indians vs. Hawks
DESCRIPTION:Indians vs. Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xCaH-33\n\nShop: https://stza.co/+xCaH-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. Hawks
<2018-06-19 Tue 20:30-23:30>
:PROPERTIES:
:ID:       shw3FxiK72Cf0Qrx-CkJXdQs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Indians vs. Hawks Indians vs. Hawks

Follow on MiLB First Pitch  https //stza.co/+xCaM-1v

Shop  https //stza.co/+xCaM-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. Hawks
END:VALARM
DTSTART:20180620T013000Z
DTEND:20180620T043000Z
UID:shw3FxiK72Cf0Qrx-CkJXdQs@stanza.co
SUMMARY:Indians vs. Hawks
DESCRIPTION:Indians vs. Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xCaM-1v\n\nShop: https://stza.co/+xCaM-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ Dust Devils
<2018-06-20 Wed 21:15>--<2018-06-21 Thu 00:15>
:PROPERTIES:
:ID:       2wpKO1knF12gK5oE_VTuht_G@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians @ Dust Devils Indians @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vOeh-2X

Shop  https //stza.co/+vOeh-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ Dust Devils
END:VALARM
DTSTART:20180621T021500Z
DTEND:20180621T051500Z
UID:2wpKO1knF12gK5oE_VTuht_G@stanza.co
SUMMARY:Indians @ Dust Devils
DESCRIPTION:Indians @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vOeh-2X\n\nShop: https://stza.co/+vOeh-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ Dust Devils
<2018-06-21 Thu 21:15>--<2018-06-22 Fri 00:15>
:PROPERTIES:
:ID:       QjcTI7vlpba8s6Ynmz6W3R0H@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians @ Dust Devils Indians @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vOei-Q

Shop  https //stza.co/+vOei-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ Dust Devils
END:VALARM
DTSTART:20180622T021500Z
DTEND:20180622T051500Z
UID:QjcTI7vlpba8s6Ynmz6W3R0H@stanza.co
SUMMARY:Indians @ Dust Devils
DESCRIPTION:Indians @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vOei-Q\n\nShop: https://stza.co/+vOei-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ Dust Devils
<2018-06-22 Fri 21:15>--<2018-06-23 Sat 00:15>
:PROPERTIES:
:ID:       0gXtfzBSJoWXMIE3jpQxo8lb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Indians @ Dust Devils Indians @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vOej-1L

Shop  https //stza.co/+vOej-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ Dust Devils
END:VALARM
DTSTART:20180623T021500Z
DTEND:20180623T051500Z
UID:0gXtfzBSJoWXMIE3jpQxo8lb@stanza.co
SUMMARY:Indians @ Dust Devils
DESCRIPTION:Indians @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vOej-1L\n\nShop: https://stza.co/+vOej-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. Canadians
<2018-06-23 Sat 20:30-23:30>
:PROPERTIES:
:ID:       WGLoeXhoqpWY-VzqMKJnbzTA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians vs. Canadians Indians vs. Canadians

Follow on MiLB First Pitch  https //stza.co/+xCaP-2p

Shop  https //stza.co/+xCaP-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. Canadians
END:VALARM
DTSTART:20180624T013000Z
DTEND:20180624T043000Z
UID:WGLoeXhoqpWY-VzqMKJnbzTA@stanza.co
SUMMARY:Indians vs. Canadians
DESCRIPTION:Indians vs. Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xCaP-2p\n\nShop: https://stza.co/+xCaP-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. Canadians
<2018-06-24 Sun 17:30-20:30>
:PROPERTIES:
:ID:       pVNYPu-a9V8YACov9meIsdIT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians vs. Canadians Indians vs. Canadians

Follow on MiLB First Pitch  https //stza.co/+xCaU-1Q

Shop  https //stza.co/+xCaU-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. Canadians
END:VALARM
DTSTART:20180624T223000Z
DTEND:20180625T013000Z
UID:pVNYPu-a9V8YACov9meIsdIT@stanza.co
SUMMARY:Indians vs. Canadians
DESCRIPTION:Indians vs. Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xCaU-1Q\n\nShop: https://stza.co/+xCaU-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. Canadians
<2018-06-25 Mon 20:30-23:30>
:PROPERTIES:
:ID:       W1CQtMubtLXyGCkDVG_9Q7-i@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Indians vs. Canadians Indians vs. Canadians

Follow on MiLB First Pitch  https //stza.co/+xCaY-17

Shop  https //stza.co/+xCaY-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. Canadians
END:VALARM
DTSTART:20180626T013000Z
DTEND:20180626T043000Z
UID:W1CQtMubtLXyGCkDVG_9Q7-i@stanza.co
SUMMARY:Indians vs. Canadians
DESCRIPTION:Indians vs. Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xCaY-17\n\nShop: https://stza.co/+xCaY-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. AquaSox
<2018-06-26 Tue 20:30-23:30>
:PROPERTIES:
:ID:       TGBUIfJuRx3ac7wlDVKiIPiH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians vs. AquaSox Indians vs. AquaSox

Follow on MiLB First Pitch  https //stza.co/+xCa$-1D

Shop  https //stza.co/+xCa$-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. AquaSox
END:VALARM
DTSTART:20180627T013000Z
DTEND:20180627T043000Z
UID:TGBUIfJuRx3ac7wlDVKiIPiH@stanza.co
SUMMARY:Indians vs. AquaSox
DESCRIPTION:Indians vs. AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+xCa$-1D\n\nShop: https://stza.co/+xCa$-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. AquaSox
<2018-06-27 Wed 20:30-23:30>
:PROPERTIES:
:ID:       XWLvj47t7aRo9_aQAn-Izlnu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians vs. AquaSox Indians vs. AquaSox

Follow on MiLB First Pitch  https //stza.co/+xCb2-m

Shop  https //stza.co/+xCb2-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. AquaSox
END:VALARM
DTSTART:20180628T013000Z
DTEND:20180628T043000Z
UID:XWLvj47t7aRo9_aQAn-Izlnu@stanza.co
SUMMARY:Indians vs. AquaSox
DESCRIPTION:Indians vs. AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+xCb2-m\n\nShop: https://stza.co/+xCb2-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. AquaSox
<2018-06-28 Thu 20:30-23:30>
:PROPERTIES:
:ID:       L7Z8Fi1freWG1bPUmZa-0TKG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Indians vs. AquaSox Indians vs. AquaSox

Follow on MiLB First Pitch  https //stza.co/+xCb6-2r

Shop  https //stza.co/+xCb6-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. AquaSox
END:VALARM
DTSTART:20180629T013000Z
DTEND:20180629T043000Z
UID:L7Z8Fi1freWG1bPUmZa-0TKG@stanza.co
SUMMARY:Indians vs. AquaSox
DESCRIPTION:Indians vs. AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+xCb6-2r\n\nShop: https://stza.co/+xCb6-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ Hops
<2018-06-29 Fri 21:05>--<2018-06-30 Sat 00:05>
:PROPERTIES:
:ID:       vrah-NInZ7ab1XOlIoX2H4TM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians @ Hops Indians @ Hops

Follow on MiLB First Pitch  https //stza.co/+vOcX-T

Shop  https //stza.co/+vOcX-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ Hops
END:VALARM
DTSTART:20180630T020500Z
DTEND:20180630T050500Z
UID:vrah-NInZ7ab1XOlIoX2H4TM@stanza.co
SUMMARY:Indians @ Hops
DESCRIPTION:Indians @ Hops\n\nFollow on MiLB First Pitch: https://stza.co/+vOcX-T\n\nShop: https://stza.co/+vOcX-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ Hops
<2018-06-30 Sat 21:05>--<2018-07-01 Sun 00:05>
:PROPERTIES:
:ID:       -clBdUC3D8VR_J3jBbZxyqjF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians @ Hops Indians @ Hops

Follow on MiLB First Pitch  https //stza.co/+vOcY-Z

Shop  https //stza.co/+vOcY-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ Hops
END:VALARM
DTSTART:20180701T020500Z
DTEND:20180701T050500Z
UID:-clBdUC3D8VR_J3jBbZxyqjF@stanza.co
SUMMARY:Indians @ Hops
DESCRIPTION:Indians @ Hops\n\nFollow on MiLB First Pitch: https://stza.co/+vOcY-Z\n\nShop: https://stza.co/+vOcY-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ Hops
<2018-07-01 Sun 18:05-21:05>
:PROPERTIES:
:ID:       eJBjLpXDjUkzaVLuyq-0JghL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Indians @ Hops Indians @ Hops

Follow on MiLB First Pitch  https //stza.co/+vOcZ-3A

Shop  https //stza.co/+vOcZ-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ Hops
END:VALARM
DTSTART:20180701T230500Z
DTEND:20180702T020500Z
UID:eJBjLpXDjUkzaVLuyq-0JghL@stanza.co
SUMMARY:Indians @ Hops
DESCRIPTION:Indians @ Hops\n\nFollow on MiLB First Pitch: https://stza.co/+vOcZ-3A\n\nShop: https://stza.co/+vOcZ-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ Hops
<2018-07-02 Mon 21:05>--<2018-07-03 Tue 00:05>
:PROPERTIES:
:ID:       zc_bJN3ucURKtTma7Z_qjN_W@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians @ Hops Indians @ Hops

Follow on MiLB First Pitch  https //stza.co/+vOc_-2n

Shop  https //stza.co/+vOc_-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ Hops
END:VALARM
DTSTART:20180703T020500Z
DTEND:20180703T050500Z
UID:zc_bJN3ucURKtTma7Z_qjN_W@stanza.co
SUMMARY:Indians @ Hops
DESCRIPTION:Indians @ Hops\n\nFollow on MiLB First Pitch: https://stza.co/+vOc_-2n\n\nShop: https://stza.co/+vOc_-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ Hops
<2018-07-03 Tue 21:05>--<2018-07-04 Wed 00:05>
:PROPERTIES:
:ID:       yulGxJeVr-vq4dKlG64393tz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians @ Hops Indians @ Hops

Follow on MiLB First Pitch  https //stza.co/+vOc$-10

Shop  https //stza.co/+vOc$-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ Hops
END:VALARM
DTSTART:20180704T020500Z
DTEND:20180704T050500Z
UID:yulGxJeVr-vq4dKlG64393tz@stanza.co
SUMMARY:Indians @ Hops
DESCRIPTION:Indians @ Hops\n\nFollow on MiLB First Pitch: https://stza.co/+vOc$-10\n\nShop: https://stza.co/+vOc$-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. Dust Devils
<2018-07-04 Wed 20:30-23:30>
:PROPERTIES:
:ID:       dB0oNJmZ5EPuk4zDgS6MxLhq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Indians vs. Dust Devils Indians vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+xCb9-1S

Shop  https //stza.co/+xCb9-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. Dust Devils
END:VALARM
DTSTART:20180705T013000Z
DTEND:20180705T043000Z
UID:dB0oNJmZ5EPuk4zDgS6MxLhq@stanza.co
SUMMARY:Indians vs. Dust Devils
DESCRIPTION:Indians vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+xCb9-1S\n\nShop: https://stza.co/+xCb9-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. Dust Devils
<2018-07-05 Thu 20:30-23:30>
:PROPERTIES:
:ID:       LFcvlhharg1gVZh0JM4g3B9G@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians vs. Dust Devils Indians vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+xCbc-19

Shop  https //stza.co/+xCbc-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. Dust Devils
END:VALARM
DTSTART:20180706T013000Z
DTEND:20180706T043000Z
UID:LFcvlhharg1gVZh0JM4g3B9G@stanza.co
SUMMARY:Indians vs. Dust Devils
DESCRIPTION:Indians vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+xCbc-19\n\nShop: https://stza.co/+xCbc-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. Dust Devils
<2018-07-06 Fri 20:30-23:30>
:PROPERTIES:
:ID:       9L__RZJrlSaekXF411SyXfxd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians vs. Dust Devils Indians vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+xCbi-3w

Shop  https //stza.co/+xCbi-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. Dust Devils
END:VALARM
DTSTART:20180707T013000Z
DTEND:20180707T043000Z
UID:9L__RZJrlSaekXF411SyXfxd@stanza.co
SUMMARY:Indians vs. Dust Devils
DESCRIPTION:Indians vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+xCbi-3w\n\nShop: https://stza.co/+xCbi-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ Canadians
<2018-07-07 Sat 21:05>--<2018-07-08 Sun 00:05>
:PROPERTIES:
:ID:       0jLTt47vdLzUR9M6WePwX9wv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Indians @ Canadians Indians @ Canadians

Follow on MiLB First Pitch  https //stza.co/+xXVb-_

Shop  https //stza.co/+xXVb-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ Canadians
END:VALARM
DTSTART:20180708T020500Z
DTEND:20180708T050500Z
UID:0jLTt47vdLzUR9M6WePwX9wv@stanza.co
SUMMARY:Indians @ Canadians
DESCRIPTION:Indians @ Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xXVb-_\n\nShop: https://stza.co/+xXVb-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ Canadians
<2018-07-08 Sun 15:05-18:05>
:PROPERTIES:
:ID:       LHWhXtIMxAVTzZbj-CoUmlOK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians @ Canadians Indians @ Canadians

Follow on MiLB First Pitch  https //stza.co/+xXVc-Z

Shop  https //stza.co/+xXVc-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ Canadians
END:VALARM
DTSTART:20180708T200500Z
DTEND:20180708T230500Z
UID:LHWhXtIMxAVTzZbj-CoUmlOK@stanza.co
SUMMARY:Indians @ Canadians
DESCRIPTION:Indians @ Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xXVc-Z\n\nShop: https://stza.co/+xXVc-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ Canadians
<2018-07-09 Mon 21:05>--<2018-07-10 Tue 00:05>
:PROPERTIES:
:ID:       9WH2izaC-HtnnbHQrr6gmm1V@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians @ Canadians Indians @ Canadians

Follow on MiLB First Pitch  https //stza.co/+xXVd-1O

Shop  https //stza.co/+xXVd-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ Canadians
END:VALARM
DTSTART:20180710T020500Z
DTEND:20180710T050500Z
UID:9WH2izaC-HtnnbHQrr6gmm1V@stanza.co
SUMMARY:Indians @ Canadians
DESCRIPTION:Indians @ Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xXVd-1O\n\nShop: https://stza.co/+xXVd-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. Emeralds
<2018-07-11 Wed 20:30-23:30>
:PROPERTIES:
:ID:       VZ0w2l-V-RLOt70IvGPIyFc0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Indians vs. Emeralds Indians vs. Emeralds

Follow on MiLB First Pitch  https //stza.co/+xCbm-3B

Shop  https //stza.co/+xCbm-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. Emeralds
END:VALARM
DTSTART:20180712T013000Z
DTEND:20180712T043000Z
UID:VZ0w2l-V-RLOt70IvGPIyFc0@stanza.co
SUMMARY:Indians vs. Emeralds
DESCRIPTION:Indians vs. Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xCbm-3B\n\nShop: https://stza.co/+xCbm-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. Emeralds
<2018-07-12 Thu 20:30-23:30>
:PROPERTIES:
:ID:       LkHsjzCl4sfrpDH0-w3R5AUX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians vs. Emeralds Indians vs. Emeralds

Follow on MiLB First Pitch  https //stza.co/+xCbp-27

Shop  https //stza.co/+xCbp-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. Emeralds
END:VALARM
DTSTART:20180713T013000Z
DTEND:20180713T043000Z
UID:LkHsjzCl4sfrpDH0-w3R5AUX@stanza.co
SUMMARY:Indians vs. Emeralds
DESCRIPTION:Indians vs. Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xCbp-27\n\nShop: https://stza.co/+xCbp-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. Emeralds
<2018-07-13 Fri 20:30-23:30>
:PROPERTIES:
:ID:       pXjtSPuDCyZvzaNTiB3mryUE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians vs. Emeralds Indians vs. Emeralds

Follow on MiLB First Pitch  https //stza.co/+xCbw-1$

Shop  https //stza.co/+xCbw-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. Emeralds
END:VALARM
DTSTART:20180714T013000Z
DTEND:20180714T043000Z
UID:pXjtSPuDCyZvzaNTiB3mryUE@stanza.co
SUMMARY:Indians vs. Emeralds
DESCRIPTION:Indians vs. Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xCbw-1$\n\nShop: https://stza.co/+xCbw-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. Emeralds
<2018-07-14 Sat 20:30-23:30>
:PROPERTIES:
:ID:       pQ56S3xtzeNGNx-qxDm_hKNd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Indians vs. Emeralds Indians vs. Emeralds

Follow on MiLB First Pitch  https //stza.co/+xCbA-1W

Shop  https //stza.co/+xCbA-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. Emeralds
END:VALARM
DTSTART:20180715T013000Z
DTEND:20180715T043000Z
UID:pQ56S3xtzeNGNx-qxDm_hKNd@stanza.co
SUMMARY:Indians vs. Emeralds
DESCRIPTION:Indians vs. Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xCbA-1W\n\nShop: https://stza.co/+xCbA-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. Emeralds
<2018-07-15 Sun 17:30-20:30>
:PROPERTIES:
:ID:       mEVU1wcQdCjgXCxCZZdhRIOk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians vs. Emeralds Indians vs. Emeralds

Follow on MiLB First Pitch  https //stza.co/+xCbD-2W

Shop  https //stza.co/+xCbD-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. Emeralds
END:VALARM
DTSTART:20180715T223000Z
DTEND:20180716T013000Z
UID:mEVU1wcQdCjgXCxCZZdhRIOk@stanza.co
SUMMARY:Indians vs. Emeralds
DESCRIPTION:Indians vs. Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xCbD-2W\n\nShop: https://stza.co/+xCbD-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ AquaSox
<2018-07-16 Mon 21:05>--<2018-07-17 Tue 00:05>
:PROPERTIES:
:ID:       DfyHCFQ_kt860lbJaxR-x7Fn@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians @ AquaSox Indians @ AquaSox

Follow on MiLB First Pitch  https //stza.co/+vOcR-2A

Shop  https //stza.co/+vOcR-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ AquaSox
END:VALARM
DTSTART:20180717T020500Z
DTEND:20180717T050500Z
UID:DfyHCFQ_kt860lbJaxR-x7Fn@stanza.co
SUMMARY:Indians @ AquaSox
DESCRIPTION:Indians @ AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vOcR-2A\n\nShop: https://stza.co/+vOcR-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ AquaSox
<2018-07-17 Tue 21:05>--<2018-07-18 Wed 00:05>
:PROPERTIES:
:ID:       u_GaGP-ZFECj_5Br_eg5MyX9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Indians @ AquaSox Indians @ AquaSox

Follow on MiLB First Pitch  https //stza.co/+vOcS-2b

Shop  https //stza.co/+vOcS-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ AquaSox
END:VALARM
DTSTART:20180718T020500Z
DTEND:20180718T050500Z
UID:u_GaGP-ZFECj_5Br_eg5MyX9@stanza.co
SUMMARY:Indians @ AquaSox
DESCRIPTION:Indians @ AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vOcS-2b\n\nShop: https://stza.co/+vOcS-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ AquaSox
<2018-07-18 Wed 13:05-16:05>
:PROPERTIES:
:ID:       zeRRc3G1L5hdvEpCfjnc0Ng5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians @ AquaSox Indians @ AquaSox

Follow on MiLB First Pitch  https //stza.co/+vOcT-1z

Shop  https //stza.co/+vOcT-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ AquaSox
END:VALARM
DTSTART:20180718T180500Z
DTEND:20180718T210500Z
UID:zeRRc3G1L5hdvEpCfjnc0Ng5@stanza.co
SUMMARY:Indians @ AquaSox
DESCRIPTION:Indians @ AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vOcT-1z\n\nShop: https://stza.co/+vOcT-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ Volcanoes
<2018-07-19 Thu>--<2018-07-18 Wed>
:PROPERTIES:
:ID:       lZiappIKbgG1vuhBYuEnQldg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians @ Volcanoes Indians @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vOd0-1n

Shop  https //stza.co/+vOd0-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180719
DTEND;VALUE=DATE:20180719
UID:lZiappIKbgG1vuhBYuEnQldg@stanza.co
SUMMARY:Indians @ Volcanoes
DESCRIPTION:Indians @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vOd0-1n\n\nShop: https://stza.co/+vOd0-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ Volcanoes
<2018-07-20 Fri>--<2018-07-19 Thu>
:PROPERTIES:
:ID:       _2GJhOfLXIZENAIEFihoDny_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Indians @ Volcanoes Indians @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vOd1-1A

Shop  https //stza.co/+vOd1-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180720
DTEND;VALUE=DATE:20180720
UID:_2GJhOfLXIZENAIEFihoDny_@stanza.co
SUMMARY:Indians @ Volcanoes
DESCRIPTION:Indians @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vOd1-1A\n\nShop: https://stza.co/+vOd1-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ Volcanoes
<2018-07-21 Sat>--<2018-07-20 Fri>
:PROPERTIES:
:ID:       Ekfks9k10mKD_hh8qVJiYJGk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians @ Volcanoes Indians @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vOd2-1w

Shop  https //stza.co/+vOd2-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180721
DTEND;VALUE=DATE:20180721
UID:Ekfks9k10mKD_hh8qVJiYJGk@stanza.co
SUMMARY:Indians @ Volcanoes
DESCRIPTION:Indians @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vOd2-1w\n\nShop: https://stza.co/+vOd2-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ Volcanoes
<2018-07-22 Sun>--<2018-07-21 Sat>
:PROPERTIES:
:ID:       MI_ygCPmlrnORl1UghkIhaVF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians @ Volcanoes Indians @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vOd3-3

Shop  https //stza.co/+vOd3-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180722
DTEND;VALUE=DATE:20180722
UID:MI_ygCPmlrnORl1UghkIhaVF@stanza.co
SUMMARY:Indians @ Volcanoes
DESCRIPTION:Indians @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vOd3-3\n\nShop: https://stza.co/+vOd3-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ Volcanoes
<2018-07-23 Mon>--<2018-07-22 Sun>
:PROPERTIES:
:ID:       4cTMrpFfQjK1pVseG63VseTj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Indians @ Volcanoes Indians @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vOd4-2A

Shop  https //stza.co/+vOd4-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180723
DTEND;VALUE=DATE:20180723
UID:4cTMrpFfQjK1pVseG63VseTj@stanza.co
SUMMARY:Indians @ Volcanoes
DESCRIPTION:Indians @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vOd4-2A\n\nShop: https://stza.co/+vOd4-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. Dust Devils
<2018-07-24 Tue 20:30-23:30>
:PROPERTIES:
:ID:       Q4VZEp8X_yE9t2yqysXJKhDG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians vs. Dust Devils Indians vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+xCbG-1N

Shop  https //stza.co/+xCbG-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. Dust Devils
END:VALARM
DTSTART:20180725T013000Z
DTEND:20180725T043000Z
UID:Q4VZEp8X_yE9t2yqysXJKhDG@stanza.co
SUMMARY:Indians vs. Dust Devils
DESCRIPTION:Indians vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+xCbG-1N\n\nShop: https://stza.co/+xCbG-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. Dust Devils
<2018-07-25 Wed 20:30-23:30>
:PROPERTIES:
:ID:       6K_hgSPEp-YOZ95QqS7IvScp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians vs. Dust Devils Indians vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+xCbL-23

Shop  https //stza.co/+xCbL-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. Dust Devils
END:VALARM
DTSTART:20180726T013000Z
DTEND:20180726T043000Z
UID:6K_hgSPEp-YOZ95QqS7IvScp@stanza.co
SUMMARY:Indians vs. Dust Devils
DESCRIPTION:Indians vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+xCbL-23\n\nShop: https://stza.co/+xCbL-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. Dust Devils
<2018-07-26 Thu 20:30-23:30>
:PROPERTIES:
:ID:       Zeem5tVztvXPNJgQl98blAWE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Indians vs. Dust Devils Indians vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+xCbP-3f

Shop  https //stza.co/+xCbP-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. Dust Devils
END:VALARM
DTSTART:20180727T013000Z
DTEND:20180727T043000Z
UID:Zeem5tVztvXPNJgQl98blAWE@stanza.co
SUMMARY:Indians vs. Dust Devils
DESCRIPTION:Indians vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+xCbP-3f\n\nShop: https://stza.co/+xCbP-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. Hops
<2018-07-27 Fri 20:30-23:30>
:PROPERTIES:
:ID:       pli7cGXUZ0stu1tYvCOJXDw5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians vs. Hops Indians vs. Hops

Follow on MiLB First Pitch  https //stza.co/+xCbT-w

Shop  https //stza.co/+xCbT-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. Hops
END:VALARM
DTSTART:20180728T013000Z
DTEND:20180728T043000Z
UID:pli7cGXUZ0stu1tYvCOJXDw5@stanza.co
SUMMARY:Indians vs. Hops
DESCRIPTION:Indians vs. Hops\n\nFollow on MiLB First Pitch: https://stza.co/+xCbT-w\n\nShop: https://stza.co/+xCbT-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. Hops
<2018-07-28 Sat 20:30-23:30>
:PROPERTIES:
:ID:       cBeMaAOhVn65VogtXEIPMHZe@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians vs. Hops Indians vs. Hops

Follow on MiLB First Pitch  https //stza.co/+xCbY-S

Shop  https //stza.co/+xCbY-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. Hops
END:VALARM
DTSTART:20180729T013000Z
DTEND:20180729T043000Z
UID:cBeMaAOhVn65VogtXEIPMHZe@stanza.co
SUMMARY:Indians vs. Hops
DESCRIPTION:Indians vs. Hops\n\nFollow on MiLB First Pitch: https://stza.co/+xCbY-S\n\nShop: https://stza.co/+xCbY-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. Hops
<2018-07-29 Sun 17:30-20:30>
:PROPERTIES:
:ID:       Iix7DKtSUwPBGOUVTvLANPcP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Indians vs. Hops Indians vs. Hops

Follow on MiLB First Pitch  https //stza.co/+xCc0-h

Shop  https //stza.co/+xCc0-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. Hops
END:VALARM
DTSTART:20180729T223000Z
DTEND:20180730T013000Z
UID:Iix7DKtSUwPBGOUVTvLANPcP@stanza.co
SUMMARY:Indians vs. Hops
DESCRIPTION:Indians vs. Hops\n\nFollow on MiLB First Pitch: https://stza.co/+xCc0-h\n\nShop: https://stza.co/+xCc0-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. Hops
<2018-07-30 Mon 20:30-23:30>
:PROPERTIES:
:ID:       RrT3Pdmaz8vCGJQQ9ZFM7HNH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians vs. Hops Indians vs. Hops

Follow on MiLB First Pitch  https //stza.co/+xCc3-I

Shop  https //stza.co/+xCc3-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. Hops
END:VALARM
DTSTART:20180731T013000Z
DTEND:20180731T043000Z
UID:RrT3Pdmaz8vCGJQQ9ZFM7HNH@stanza.co
SUMMARY:Indians vs. Hops
DESCRIPTION:Indians vs. Hops\n\nFollow on MiLB First Pitch: https://stza.co/+xCc3-I\n\nShop: https://stza.co/+xCc3-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. Hops
<2018-07-31 Tue 20:30-23:30>
:PROPERTIES:
:ID:       MfwhfXEJyHe2pQND0u_jvGms@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians vs. Hops Indians vs. Hops

Follow on MiLB First Pitch  https //stza.co/+xCc7-W

Shop  https //stza.co/+xCc7-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. Hops
END:VALARM
DTSTART:20180801T013000Z
DTEND:20180801T043000Z
UID:MfwhfXEJyHe2pQND0u_jvGms@stanza.co
SUMMARY:Indians vs. Hops
DESCRIPTION:Indians vs. Hops\n\nFollow on MiLB First Pitch: https://stza.co/+xCc7-W\n\nShop: https://stza.co/+xCc7-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ Emeralds
<2018-08-01 Wed 21:05>--<2018-08-02 Thu 00:05>
:PROPERTIES:
:ID:       SzeUJSM2gtV4Pk7paKyfT0At@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Indians @ Emeralds Indians @ Emeralds

Follow on MiLB First Pitch  https //stza.co/+xWPt-2k

Shop  https //stza.co/+xWPt-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ Emeralds
END:VALARM
DTSTART:20180802T020500Z
DTEND:20180802T050500Z
UID:SzeUJSM2gtV4Pk7paKyfT0At@stanza.co
SUMMARY:Indians @ Emeralds
DESCRIPTION:Indians @ Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xWPt-2k\n\nShop: https://stza.co/+xWPt-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ Emeralds
<2018-08-02 Thu 21:05>--<2018-08-03 Fri 00:05>
:PROPERTIES:
:ID:       A-03E54TRxkPg8ToSIXWgkUb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians @ Emeralds Indians @ Emeralds

Follow on MiLB First Pitch  https //stza.co/+xWPu-2

Shop  https //stza.co/+xWPu-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ Emeralds
END:VALARM
DTSTART:20180803T020500Z
DTEND:20180803T050500Z
UID:A-03E54TRxkPg8ToSIXWgkUb@stanza.co
SUMMARY:Indians @ Emeralds
DESCRIPTION:Indians @ Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xWPu-2\n\nShop: https://stza.co/+xWPu-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ Emeralds
<2018-08-03 Fri 21:05>--<2018-08-04 Sat 00:05>
:PROPERTIES:
:ID:       jzN75zaxcUwAjGxsl2NzHMFH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians @ Emeralds Indians @ Emeralds

Follow on MiLB First Pitch  https //stza.co/+xWPv-1I

Shop  https //stza.co/+xWPv-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ Emeralds
END:VALARM
DTSTART:20180804T020500Z
DTEND:20180804T050500Z
UID:jzN75zaxcUwAjGxsl2NzHMFH@stanza.co
SUMMARY:Indians @ Emeralds
DESCRIPTION:Indians @ Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xWPv-1I\n\nShop: https://stza.co/+xWPv-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ Emeralds
<2018-08-04 Sat 21:05>--<2018-08-05 Sun 00:05>
:PROPERTIES:
:ID:       IKX_HuMaTpDGjUqwtMjVBkq2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Indians @ Emeralds Indians @ Emeralds

Follow on MiLB First Pitch  https //stza.co/+xWPw-h

Shop  https //stza.co/+xWPw-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ Emeralds
END:VALARM
DTSTART:20180805T020500Z
DTEND:20180805T050500Z
UID:IKX_HuMaTpDGjUqwtMjVBkq2@stanza.co
SUMMARY:Indians @ Emeralds
DESCRIPTION:Indians @ Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xWPw-h\n\nShop: https://stza.co/+xWPw-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ Emeralds
<2018-08-05 Sun 19:05-22:05>
:PROPERTIES:
:ID:       4S3mQiv267_hKSA6BHTVootg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians @ Emeralds Indians @ Emeralds

Follow on MiLB First Pitch  https //stza.co/+xWPx-10

Shop  https //stza.co/+xWPx-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ Emeralds
END:VALARM
DTSTART:20180806T000500Z
DTEND:20180806T030500Z
UID:4S3mQiv267_hKSA6BHTVootg@stanza.co
SUMMARY:Indians @ Emeralds
DESCRIPTION:Indians @ Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xWPx-10\n\nShop: https://stza.co/+xWPx-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ Hawks
<2018-08-09 Thu 20:15-23:15>
:PROPERTIES:
:ID:       nf2Y_n4z8tvLGtABccvRxGgi@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians @ Hawks Indians @ Hawks

Follow on MiLB First Pitch  https //stza.co/+xCab-2z

Shop  https //stza.co/+xCab-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ Hawks
END:VALARM
DTSTART:20180810T011500Z
DTEND:20180810T041500Z
UID:nf2Y_n4z8tvLGtABccvRxGgi@stanza.co
SUMMARY:Indians @ Hawks
DESCRIPTION:Indians @ Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xCab-2z\n\nShop: https://stza.co/+xCab-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ Hawks
<2018-08-10 Fri 20:15-23:15>
:PROPERTIES:
:ID:       aI4cTwrYc97XphXQ86-QBHtB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Indians @ Hawks Indians @ Hawks

Follow on MiLB First Pitch  https //stza.co/+xCac-3T

Shop  https //stza.co/+xCac-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ Hawks
END:VALARM
DTSTART:20180811T011500Z
DTEND:20180811T041500Z
UID:aI4cTwrYc97XphXQ86-QBHtB@stanza.co
SUMMARY:Indians @ Hawks
DESCRIPTION:Indians @ Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xCac-3T\n\nShop: https://stza.co/+xCac-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ Hawks
<2018-08-11 Sat 20:15-23:15>
:PROPERTIES:
:ID:       -Ceb3G-lnHdEDfHDcA9bS1RB@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians @ Hawks Indians @ Hawks

Follow on MiLB First Pitch  https //stza.co/+xCah-38

Shop  https //stza.co/+xCah-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ Hawks
END:VALARM
DTSTART:20180812T011500Z
DTEND:20180812T041500Z
UID:-Ceb3G-lnHdEDfHDcA9bS1RB@stanza.co
SUMMARY:Indians @ Hawks
DESCRIPTION:Indians @ Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xCah-38\n\nShop: https://stza.co/+xCah-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ Hawks
<2018-08-12 Sun 18:15-21:15>
:PROPERTIES:
:ID:       rcfr7gGueIZ15lKGr1KxE18E@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians @ Hawks Indians @ Hawks

Follow on MiLB First Pitch  https //stza.co/+xCam-b

Shop  https //stza.co/+xCam-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ Hawks
END:VALARM
DTSTART:20180812T231500Z
DTEND:20180813T021500Z
UID:rcfr7gGueIZ15lKGr1KxE18E@stanza.co
SUMMARY:Indians @ Hawks
DESCRIPTION:Indians @ Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xCam-b\n\nShop: https://stza.co/+xCam-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ Hawks
<2018-08-13 Mon 20:15-23:15>
:PROPERTIES:
:ID:       kfyJNCAcDxnVtmOZ0H8vsJNQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Indians @ Hawks Indians @ Hawks

Follow on MiLB First Pitch  https //stza.co/+xCan-P

Shop  https //stza.co/+xCan-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ Hawks
END:VALARM
DTSTART:20180814T011500Z
DTEND:20180814T041500Z
UID:kfyJNCAcDxnVtmOZ0H8vsJNQ@stanza.co
SUMMARY:Indians @ Hawks
DESCRIPTION:Indians @ Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xCan-P\n\nShop: https://stza.co/+xCan-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. AquaSox
<2018-08-14 Tue 20:30-23:30>
:PROPERTIES:
:ID:       TUUKslgsATW5Jc4lieXtn-6A@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians vs. AquaSox Indians vs. AquaSox

Follow on MiLB First Pitch  https //stza.co/+xCcb-2$

Shop  https //stza.co/+xCcb-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. AquaSox
END:VALARM
DTSTART:20180815T013000Z
DTEND:20180815T043000Z
UID:TUUKslgsATW5Jc4lieXtn-6A@stanza.co
SUMMARY:Indians vs. AquaSox
DESCRIPTION:Indians vs. AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+xCcb-2$\n\nShop: https://stza.co/+xCcb-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. AquaSox
<2018-08-15 Wed 20:30-23:30>
:PROPERTIES:
:ID:       UFMfAWLftc1ASFjfjzSh3TCg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians vs. AquaSox Indians vs. AquaSox

Follow on MiLB First Pitch  https //stza.co/+xCce-3x

Shop  https //stza.co/+xCce-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. AquaSox
END:VALARM
DTSTART:20180816T013000Z
DTEND:20180816T043000Z
UID:UFMfAWLftc1ASFjfjzSh3TCg@stanza.co
SUMMARY:Indians vs. AquaSox
DESCRIPTION:Indians vs. AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+xCce-3x\n\nShop: https://stza.co/+xCce-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. AquaSox
<2018-08-16 Thu 20:30-23:30>
:PROPERTIES:
:ID:       QCr7CaF2z3aV8vWkIfQFEF18@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Indians vs. AquaSox Indians vs. AquaSox

Follow on MiLB First Pitch  https //stza.co/+xCch-2z

Shop  https //stza.co/+xCch-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. AquaSox
END:VALARM
DTSTART:20180817T013000Z
DTEND:20180817T043000Z
UID:QCr7CaF2z3aV8vWkIfQFEF18@stanza.co
SUMMARY:Indians vs. AquaSox
DESCRIPTION:Indians vs. AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+xCch-2z\n\nShop: https://stza.co/+xCch-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ Canadians
<2018-08-17 Fri 21:05>--<2018-08-18 Sat 00:05>
:PROPERTIES:
:ID:       iVVv2vdbvOP94pDZS3uSwYxo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians @ Canadians Indians @ Canadians

Follow on MiLB First Pitch  https //stza.co/+xXVe-1z

Shop  https //stza.co/+xXVe-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ Canadians
END:VALARM
DTSTART:20180818T020500Z
DTEND:20180818T050500Z
UID:iVVv2vdbvOP94pDZS3uSwYxo@stanza.co
SUMMARY:Indians @ Canadians
DESCRIPTION:Indians @ Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xXVe-1z\n\nShop: https://stza.co/+xXVe-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ Canadians
<2018-08-18 Sat 21:05>--<2018-08-19 Sun 00:05>
:PROPERTIES:
:ID:       H-2nMtbYi0WGs2AgbtJOUV9o@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians @ Canadians Indians @ Canadians

Follow on MiLB First Pitch  https //stza.co/+xXVf-2P

Shop  https //stza.co/+xXVf-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ Canadians
END:VALARM
DTSTART:20180819T020500Z
DTEND:20180819T050500Z
UID:H-2nMtbYi0WGs2AgbtJOUV9o@stanza.co
SUMMARY:Indians @ Canadians
DESCRIPTION:Indians @ Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xXVf-2P\n\nShop: https://stza.co/+xXVf-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ Canadians
<2018-08-19 Sun 15:05-18:05>
:PROPERTIES:
:ID:       3xtLBvuGeDMtX0KJUIBPTQD_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Indians @ Canadians Indians @ Canadians

Follow on MiLB First Pitch  https //stza.co/+xXVg-3H

Shop  https //stza.co/+xXVg-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ Canadians
END:VALARM
DTSTART:20180819T200500Z
DTEND:20180819T230500Z
UID:3xtLBvuGeDMtX0KJUIBPTQD_@stanza.co
SUMMARY:Indians @ Canadians
DESCRIPTION:Indians @ Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xXVg-3H\n\nShop: https://stza.co/+xXVg-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ AquaSox
<2018-08-20 Mon 21:05>--<2018-08-21 Tue 00:05>
:PROPERTIES:
:ID:       U9shwcYhnoFotjjrS0OOQKVW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians @ AquaSox Indians @ AquaSox

Follow on MiLB First Pitch  https //stza.co/+vOcU-1W

Shop  https //stza.co/+vOcU-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ AquaSox
END:VALARM
DTSTART:20180821T020500Z
DTEND:20180821T050500Z
UID:U9shwcYhnoFotjjrS0OOQKVW@stanza.co
SUMMARY:Indians @ AquaSox
DESCRIPTION:Indians @ AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vOcU-1W\n\nShop: https://stza.co/+vOcU-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ AquaSox
<2018-08-21 Tue 21:05>--<2018-08-22 Wed 00:05>
:PROPERTIES:
:ID:       X81j64VXdKLebgZYzDpT86p4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians @ AquaSox Indians @ AquaSox

Follow on MiLB First Pitch  https //stza.co/+vOcV-1U

Shop  https //stza.co/+vOcV-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ AquaSox
END:VALARM
DTSTART:20180822T020500Z
DTEND:20180822T050500Z
UID:X81j64VXdKLebgZYzDpT86p4@stanza.co
SUMMARY:Indians @ AquaSox
DESCRIPTION:Indians @ AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vOcV-1U\n\nShop: https://stza.co/+vOcV-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ AquaSox
<2018-08-22 Wed 21:05>--<2018-08-23 Thu 00:05>
:PROPERTIES:
:ID:       GRXJAZNjnhyDUwYqGMuYS9kF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Indians @ AquaSox Indians @ AquaSox

Follow on MiLB First Pitch  https //stza.co/+vOcW-z

Shop  https //stza.co/+vOcW-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ AquaSox
END:VALARM
DTSTART:20180823T020500Z
DTEND:20180823T050500Z
UID:GRXJAZNjnhyDUwYqGMuYS9kF@stanza.co
SUMMARY:Indians @ AquaSox
DESCRIPTION:Indians @ AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vOcW-z\n\nShop: https://stza.co/+vOcW-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. Volcanoes
<2018-08-23 Thu 20:30-23:30>
:PROPERTIES:
:ID:       mbErNn2zAoYT89TYJxLwzbp4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians vs. Volcanoes Indians vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+xCck-d

Shop  https //stza.co/+xCck-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. Volcanoes
END:VALARM
DTSTART:20180824T013000Z
DTEND:20180824T043000Z
UID:mbErNn2zAoYT89TYJxLwzbp4@stanza.co
SUMMARY:Indians vs. Volcanoes
DESCRIPTION:Indians vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+xCck-d\n\nShop: https://stza.co/+xCck-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. Volcanoes
<2018-08-24 Fri 20:30-23:30>
:PROPERTIES:
:ID:       a-YRwsJA8mLmTYM1ZG5HvrdZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians vs. Volcanoes Indians vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+xCco-11

Shop  https //stza.co/+xCco-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. Volcanoes
END:VALARM
DTSTART:20180825T013000Z
DTEND:20180825T043000Z
UID:a-YRwsJA8mLmTYM1ZG5HvrdZ@stanza.co
SUMMARY:Indians vs. Volcanoes
DESCRIPTION:Indians vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+xCco-11\n\nShop: https://stza.co/+xCco-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. Volcanoes
<2018-08-25 Sat 20:30-23:30>
:PROPERTIES:
:ID:       VfmpKeN1S9F9KKViolfHhEfr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Indians vs. Volcanoes Indians vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+xCcv-z

Shop  https //stza.co/+xCcv-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. Volcanoes
END:VALARM
DTSTART:20180826T013000Z
DTEND:20180826T043000Z
UID:VfmpKeN1S9F9KKViolfHhEfr@stanza.co
SUMMARY:Indians vs. Volcanoes
DESCRIPTION:Indians vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+xCcv-z\n\nShop: https://stza.co/+xCcv-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. Volcanoes
<2018-08-26 Sun 17:30-20:30>
:PROPERTIES:
:ID:       umc9dxHkbNvLddnljmCTL8Xw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians vs. Volcanoes Indians vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+xCcy-2C

Shop  https //stza.co/+xCcy-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. Volcanoes
END:VALARM
DTSTART:20180826T223000Z
DTEND:20180827T013000Z
UID:umc9dxHkbNvLddnljmCTL8Xw@stanza.co
SUMMARY:Indians vs. Volcanoes
DESCRIPTION:Indians vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+xCcy-2C\n\nShop: https://stza.co/+xCcy-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. Volcanoes
<2018-08-27 Mon 20:30-23:30>
:PROPERTIES:
:ID:       nhu1HV7wX9sOuWN9np47efkM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians vs. Volcanoes Indians vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+xBmu-2x

Shop  https //stza.co/+xBmu-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. Volcanoes
END:VALARM
DTSTART:20180828T013000Z
DTEND:20180828T043000Z
UID:nhu1HV7wX9sOuWN9np47efkM@stanza.co
SUMMARY:Indians vs. Volcanoes
DESCRIPTION:Indians vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+xBmu-2x\n\nShop: https://stza.co/+xBmu-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ Dust Devils
<2018-08-29 Wed 21:15>--<2018-08-30 Thu 00:15>
:PROPERTIES:
:ID:       H9_2zTcZBYpjqV61CS_PbpZX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Indians @ Dust Devils Indians @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vOek-5

Shop  https //stza.co/+vOek-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ Dust Devils
END:VALARM
DTSTART:20180830T021500Z
DTEND:20180830T051500Z
UID:H9_2zTcZBYpjqV61CS_PbpZX@stanza.co
SUMMARY:Indians @ Dust Devils
DESCRIPTION:Indians @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vOek-5\n\nShop: https://stza.co/+vOek-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ Dust Devils
<2018-08-30 Thu 21:15>--<2018-08-31 Fri 00:15>
:PROPERTIES:
:ID:       mtsZSFtFpQWv7RZtPCPpct9G@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians @ Dust Devils Indians @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vOel-1I

Shop  https //stza.co/+vOel-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ Dust Devils
END:VALARM
DTSTART:20180831T021500Z
DTEND:20180831T051500Z
UID:mtsZSFtFpQWv7RZtPCPpct9G@stanza.co
SUMMARY:Indians @ Dust Devils
DESCRIPTION:Indians @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vOel-1I\n\nShop: https://stza.co/+vOel-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians @ Dust Devils
<2018-08-31 Fri 21:15>--<2018-09-01 Sat 00:15>
:PROPERTIES:
:ID:       mphxedKmgoBIF6cDgNdHLJbf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians @ Dust Devils Indians @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vOem-34

Shop  https //stza.co/+vOem-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Indians @ Dust Devils
END:VALARM
DTSTART:20180901T021500Z
DTEND:20180901T051500Z
UID:mphxedKmgoBIF6cDgNdHLJbf@stanza.co
SUMMARY:Indians @ Dust Devils
DESCRIPTION:Indians @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vOem-34\n\nShop: https://stza.co/+vOem-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. Canadians
<2018-09-01 Sat 20:30-23:30>
:PROPERTIES:
:ID:       QdDFqRcgem_j0KtwglvrH6jx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Indians vs. Canadians Indians vs. Canadians

Follow on MiLB First Pitch  https //stza.co/+xBmz-1q

Shop  https //stza.co/+xBmz-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. Canadians
END:VALARM
DTSTART:20180902T013000Z
DTEND:20180902T043000Z
UID:QdDFqRcgem_j0KtwglvrH6jx@stanza.co
SUMMARY:Indians vs. Canadians
DESCRIPTION:Indians vs. Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xBmz-1q\n\nShop: https://stza.co/+xBmz-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. Canadians
<2018-09-02 Sun 17:30-20:30>
:PROPERTIES:
:ID:       kLbpHuWN_5zIZehJ604CHnFl@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians vs. Canadians Indians vs. Canadians

Follow on MiLB First Pitch  https //stza.co/+xBmD-27

Shop  https //stza.co/+xBmD-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. Canadians
END:VALARM
DTSTART:20180902T223000Z
DTEND:20180903T013000Z
UID:kLbpHuWN_5zIZehJ604CHnFl@stanza.co
SUMMARY:Indians vs. Canadians
DESCRIPTION:Indians vs. Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xBmD-27\n\nShop: https://stza.co/+xBmD-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
* Indians vs. Canadians
<2018-09-03 Mon 20:30-23:30>
:PROPERTIES:
:ID:       CSJHlf_8DoY1NIwzeZnyerjG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Indians vs. Canadians Indians vs. Canadians

Follow on MiLB First Pitch  https //stza.co/+xBmH-a

Shop  https //stza.co/+xBmH-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Indians vs. Canadians
END:VALARM
DTSTART:20180904T013000Z
DTEND:20180904T043000Z
UID:CSJHlf_8DoY1NIwzeZnyerjG@stanza.co
SUMMARY:Indians vs. Canadians
DESCRIPTION:Indians vs. Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xBmH-a\n\nShop: https://stza.co/+xBmH-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144558Z
LAST-MODIFIED:20180213T144558Z
TRANSP:OPAQUE
END:VEVENT
