#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Scrappers vs. Black Bears
<2018-06-15 Fri>--<2018-06-14 Thu>
:PROPERTIES:
:ID:       eOPb3BljxpF9IbEyim9EJYvd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Black Bears Scrappers vs. Black Bears

Follow on MiLB First Pitch  https //stza.co/+xMqr-1b

Shop  https //stza.co/+xMqr-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Black Bears
END:VALARM
DTSTART;VALUE=DATE:20180615
DTEND;VALUE=DATE:20180615
UID:eOPb3BljxpF9IbEyim9EJYvd@stanza.co
SUMMARY:Scrappers vs. Black Bears
DESCRIPTION:Scrappers vs. Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xMqr-1b\n\nShop: https://stza.co/+xMqr-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Black Bears
<2018-06-16 Sat>--<2018-06-15 Fri>
:PROPERTIES:
:ID:       H78QQXSxq6vhTqZWUoGxxzQi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Black Bears Scrappers vs. Black Bears

Follow on MiLB First Pitch  https //stza.co/+xMqu-1W

Shop  https //stza.co/+xMqu-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Black Bears
END:VALARM
DTSTART;VALUE=DATE:20180616
DTEND;VALUE=DATE:20180616
UID:H78QQXSxq6vhTqZWUoGxxzQi@stanza.co
SUMMARY:Scrappers vs. Black Bears
DESCRIPTION:Scrappers vs. Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xMqu-1W\n\nShop: https://stza.co/+xMqu-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Black Bears
<2018-06-17 Sun>--<2018-06-16 Sat>
:PROPERTIES:
:ID:       y76vXW7PdELtxfrIhDRwufqg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Black Bears Scrappers vs. Black Bears

Follow on MiLB First Pitch  https //stza.co/+xMqv-2c

Shop  https //stza.co/+xMqv-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Black Bears
END:VALARM
DTSTART;VALUE=DATE:20180617
DTEND;VALUE=DATE:20180617
UID:y76vXW7PdELtxfrIhDRwufqg@stanza.co
SUMMARY:Scrappers vs. Black Bears
DESCRIPTION:Scrappers vs. Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xMqv-2c\n\nShop: https://stza.co/+xMqv-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Spikes
<2018-06-18 Mon>--<2018-06-17 Sun>
:PROPERTIES:
:ID:       F1sJJUmaKDYh9Q2zGzHxOVTt@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers @ Spikes Scrappers @ Spikes

Follow on MiLB First Pitch  https //stza.co/+xMrD-2g

Shop  https //stza.co/+xMrD-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Spikes
END:VALARM
DTSTART;VALUE=DATE:20180618
DTEND;VALUE=DATE:20180618
UID:F1sJJUmaKDYh9Q2zGzHxOVTt@stanza.co
SUMMARY:Scrappers @ Spikes
DESCRIPTION:Scrappers @ Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMrD-2g\n\nShop: https://stza.co/+xMrD-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Spikes
<2018-06-19 Tue>--<2018-06-18 Mon>
:PROPERTIES:
:ID:       1na2d2FCywsSIxmftt9agnzu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Scrappers @ Spikes Scrappers @ Spikes

Follow on MiLB First Pitch  https //stza.co/+xMrE-3A

Shop  https //stza.co/+xMrE-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Spikes
END:VALARM
DTSTART;VALUE=DATE:20180619
DTEND;VALUE=DATE:20180619
UID:1na2d2FCywsSIxmftt9agnzu@stanza.co
SUMMARY:Scrappers @ Spikes
DESCRIPTION:Scrappers @ Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMrE-3A\n\nShop: https://stza.co/+xMrE-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Spikes
<2018-06-20 Wed>--<2018-06-19 Tue>
:PROPERTIES:
:ID:       0Q1zxv-2WnKYc6Km_KERzakY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers @ Spikes Scrappers @ Spikes

Follow on MiLB First Pitch  https //stza.co/+xMrF-3F

Shop  https //stza.co/+xMrF-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Spikes
END:VALARM
DTSTART;VALUE=DATE:20180620
DTEND;VALUE=DATE:20180620
UID:0Q1zxv-2WnKYc6Km_KERzakY@stanza.co
SUMMARY:Scrappers @ Spikes
DESCRIPTION:Scrappers @ Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMrF-3F\n\nShop: https://stza.co/+xMrF-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Doubledays
<2018-06-21 Thu>--<2018-06-20 Wed>
:PROPERTIES:
:ID:       sN-wC-b272DBHEbIk1jwTAc7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Doubledays Scrappers vs. Doubledays

Follow on MiLB First Pitch  https //stza.co/+xMqy-2P

Shop  https //stza.co/+xMqy-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Doubledays
END:VALARM
DTSTART;VALUE=DATE:20180621
DTEND;VALUE=DATE:20180621
UID:sN-wC-b272DBHEbIk1jwTAc7@stanza.co
SUMMARY:Scrappers vs. Doubledays
DESCRIPTION:Scrappers vs. Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xMqy-2P\n\nShop: https://stza.co/+xMqy-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Doubledays
<2018-06-22 Fri>--<2018-06-21 Thu>
:PROPERTIES:
:ID:       lk3XwnjkaLpgxelmsQ0mdp6r@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Doubledays Scrappers vs. Doubledays

Follow on MiLB First Pitch  https //stza.co/+xMqA-g

Shop  https //stza.co/+xMqA-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Doubledays
END:VALARM
DTSTART;VALUE=DATE:20180622
DTEND;VALUE=DATE:20180622
UID:lk3XwnjkaLpgxelmsQ0mdp6r@stanza.co
SUMMARY:Scrappers vs. Doubledays
DESCRIPTION:Scrappers vs. Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xMqA-g\n\nShop: https://stza.co/+xMqA-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Doubledays
<2018-06-23 Sat>--<2018-06-22 Fri>
:PROPERTIES:
:ID:       3eIv55Dex0foJ0IvifGotzNK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Doubledays Scrappers vs. Doubledays

Follow on MiLB First Pitch  https //stza.co/+xMqB-1u

Shop  https //stza.co/+xMqB-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Doubledays
END:VALARM
DTSTART;VALUE=DATE:20180623
DTEND;VALUE=DATE:20180623
UID:3eIv55Dex0foJ0IvifGotzNK@stanza.co
SUMMARY:Scrappers vs. Doubledays
DESCRIPTION:Scrappers vs. Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xMqB-1u\n\nShop: https://stza.co/+xMqB-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Crosscutters
<2018-06-24 Sun>--<2018-06-23 Sat>
:PROPERTIES:
:ID:       lYGfeeTz3kZ2GrnAjwD07Xa-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Crosscutters Scrappers vs. Crosscutters

Follow on MiLB First Pitch  https //stza.co/+xMqE-1t

Shop  https //stza.co/+xMqE-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Crosscutters
END:VALARM
DTSTART;VALUE=DATE:20180624
DTEND;VALUE=DATE:20180624
UID:lYGfeeTz3kZ2GrnAjwD07Xa-@stanza.co
SUMMARY:Scrappers vs. Crosscutters
DESCRIPTION:Scrappers vs. Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+xMqE-1t\n\nShop: https://stza.co/+xMqE-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Crosscutters
<2018-06-25 Mon>--<2018-06-24 Sun>
:PROPERTIES:
:ID:       QvfssfdTDg-7uWKDJuz3tV15@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Crosscutters Scrappers vs. Crosscutters

Follow on MiLB First Pitch  https //stza.co/+xMqG-28

Shop  https //stza.co/+xMqG-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Crosscutters
END:VALARM
DTSTART;VALUE=DATE:20180625
DTEND;VALUE=DATE:20180625
UID:QvfssfdTDg-7uWKDJuz3tV15@stanza.co
SUMMARY:Scrappers vs. Crosscutters
DESCRIPTION:Scrappers vs. Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+xMqG-28\n\nShop: https://stza.co/+xMqG-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Crosscutters
<2018-06-26 Tue>--<2018-06-25 Mon>
:PROPERTIES:
:ID:       h-jZIQi9_QgEQSM-ukoKgl3L@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Crosscutters Scrappers vs. Crosscutters

Follow on MiLB First Pitch  https //stza.co/+xMqH-Z

Shop  https //stza.co/+xMqH-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Crosscutters
END:VALARM
DTSTART;VALUE=DATE:20180626
DTEND;VALUE=DATE:20180626
UID:h-jZIQi9_QgEQSM-ukoKgl3L@stanza.co
SUMMARY:Scrappers vs. Crosscutters
DESCRIPTION:Scrappers vs. Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+xMqH-Z\n\nShop: https://stza.co/+xMqH-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Black Bears
<2018-06-28 Thu 18:05-21:05>
:PROPERTIES:
:ID:       ib6YJyaUdqXDGqSESt-_60Um@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers @ Black Bears Scrappers @ Black Bears

Follow on MiLB First Pitch  https //stza.co/+xW02-3a

Shop  https //stza.co/+xW02-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Black Bears
END:VALARM
DTSTART:20180628T230500Z
DTEND:20180629T020500Z
UID:ib6YJyaUdqXDGqSESt-_60Um@stanza.co
SUMMARY:Scrappers @ Black Bears
DESCRIPTION:Scrappers @ Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xW02-3a\n\nShop: https://stza.co/+xW02-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Black Bears
<2018-06-29 Fri 18:05-21:05>
:PROPERTIES:
:ID:       LIaih52pzyCA-bXKdulaltQm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Scrappers @ Black Bears Scrappers @ Black Bears

Follow on MiLB First Pitch  https //stza.co/+xW03-2U

Shop  https //stza.co/+xW03-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Black Bears
END:VALARM
DTSTART:20180629T230500Z
DTEND:20180630T020500Z
UID:LIaih52pzyCA-bXKdulaltQm@stanza.co
SUMMARY:Scrappers @ Black Bears
DESCRIPTION:Scrappers @ Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xW03-2U\n\nShop: https://stza.co/+xW03-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Black Bears
<2018-06-30 Sat 18:05-21:05>
:PROPERTIES:
:ID:       vbR5tYbr-AzOr8inqHBcVHAQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers @ Black Bears Scrappers @ Black Bears

Follow on MiLB First Pitch  https //stza.co/+xW04-_

Shop  https //stza.co/+xW04-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Black Bears
END:VALARM
DTSTART:20180630T230500Z
DTEND:20180701T020500Z
UID:vbR5tYbr-AzOr8inqHBcVHAQ@stanza.co
SUMMARY:Scrappers @ Black Bears
DESCRIPTION:Scrappers @ Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xW04-_\n\nShop: https://stza.co/+xW04-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Spikes
<2018-07-01 Sun>--<2018-06-30 Sat>
:PROPERTIES:
:ID:       0jAcV-i3VScGbycs35BXBLXy@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers @ Spikes Scrappers @ Spikes

Follow on MiLB First Pitch  https //stza.co/+xMrG-2m

Shop  https //stza.co/+xMrG-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Spikes
END:VALARM
DTSTART;VALUE=DATE:20180701
DTEND;VALUE=DATE:20180701
UID:0jAcV-i3VScGbycs35BXBLXy@stanza.co
SUMMARY:Scrappers @ Spikes
DESCRIPTION:Scrappers @ Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMrG-2m\n\nShop: https://stza.co/+xMrG-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Spikes
<2018-07-02 Mon>--<2018-07-01 Sun>
:PROPERTIES:
:ID:       jRMYksRNBDuV-bBcZdiyEuG1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Scrappers @ Spikes Scrappers @ Spikes

Follow on MiLB First Pitch  https //stza.co/+xMrH-2R

Shop  https //stza.co/+xMrH-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Spikes
END:VALARM
DTSTART;VALUE=DATE:20180702
DTEND;VALUE=DATE:20180702
UID:jRMYksRNBDuV-bBcZdiyEuG1@stanza.co
SUMMARY:Scrappers @ Spikes
DESCRIPTION:Scrappers @ Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMrH-2R\n\nShop: https://stza.co/+xMrH-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Spikes
<2018-07-03 Tue>--<2018-07-02 Mon>
:PROPERTIES:
:ID:       jYEHe8ZYoAPxyUroX1pdnBlv@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers @ Spikes Scrappers @ Spikes

Follow on MiLB First Pitch  https //stza.co/+xMrI-1F

Shop  https //stza.co/+xMrI-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Spikes
END:VALARM
DTSTART;VALUE=DATE:20180703
DTEND;VALUE=DATE:20180703
UID:jYEHe8ZYoAPxyUroX1pdnBlv@stanza.co
SUMMARY:Scrappers @ Spikes
DESCRIPTION:Scrappers @ Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMrI-1F\n\nShop: https://stza.co/+xMrI-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Muckdogs
<2018-07-04 Wed>--<2018-07-03 Tue>
:PROPERTIES:
:ID:       YvfdypuFqQDq848NO0KdVnpZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Muckdogs Scrappers vs. Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMqK-l

Shop  https //stza.co/+xMqK-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180704
DTEND;VALUE=DATE:20180704
UID:YvfdypuFqQDq848NO0KdVnpZ@stanza.co
SUMMARY:Scrappers vs. Muckdogs
DESCRIPTION:Scrappers vs. Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMqK-l\n\nShop: https://stza.co/+xMqK-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Muckdogs
<2018-07-05 Thu>--<2018-07-04 Wed>
:PROPERTIES:
:ID:       VFOvcEN1R0Tnxm8rhei-qkn1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Muckdogs Scrappers vs. Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMqM-3L

Shop  https //stza.co/+xMqM-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180705
DTEND;VALUE=DATE:20180705
UID:VFOvcEN1R0Tnxm8rhei-qkn1@stanza.co
SUMMARY:Scrappers vs. Muckdogs
DESCRIPTION:Scrappers vs. Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMqM-3L\n\nShop: https://stza.co/+xMqM-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Muckdogs
<2018-07-06 Fri>--<2018-07-05 Thu>
:PROPERTIES:
:ID:       aALuJYntO4zjVy_ESWAaf_WO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Muckdogs Scrappers vs. Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMqO-2Z

Shop  https //stza.co/+xMqO-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180706
DTEND;VALUE=DATE:20180706
UID:aALuJYntO4zjVy_ESWAaf_WO@stanza.co
SUMMARY:Scrappers vs. Muckdogs
DESCRIPTION:Scrappers vs. Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMqO-2Z\n\nShop: https://stza.co/+xMqO-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Crosscutters
<2018-07-07 Sat>--<2018-07-06 Fri>
:PROPERTIES:
:ID:       R_O0t2XsXVLGXN-Ez6cG0Bgk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Crosscutters Scrappers vs. Crosscutters

Follow on MiLB First Pitch  https //stza.co/+xMqQ-3H

Shop  https //stza.co/+xMqQ-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Crosscutters
END:VALARM
DTSTART;VALUE=DATE:20180707
DTEND;VALUE=DATE:20180707
UID:R_O0t2XsXVLGXN-Ez6cG0Bgk@stanza.co
SUMMARY:Scrappers vs. Crosscutters
DESCRIPTION:Scrappers vs. Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+xMqQ-3H\n\nShop: https://stza.co/+xMqQ-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Crosscutters
<2018-07-08 Sun>--<2018-07-07 Sat>
:PROPERTIES:
:ID:       TAIzGJY6mGnBHBJpQpxVAlt8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Crosscutters Scrappers vs. Crosscutters

Follow on MiLB First Pitch  https //stza.co/+xMqR-v

Shop  https //stza.co/+xMqR-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Crosscutters
END:VALARM
DTSTART;VALUE=DATE:20180708
DTEND;VALUE=DATE:20180708
UID:TAIzGJY6mGnBHBJpQpxVAlt8@stanza.co
SUMMARY:Scrappers vs. Crosscutters
DESCRIPTION:Scrappers vs. Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+xMqR-v\n\nShop: https://stza.co/+xMqR-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Crosscutters
<2018-07-09 Mon>--<2018-07-08 Sun>
:PROPERTIES:
:ID:       gOUlUIuu-oitia6wSGn4rHOS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Crosscutters Scrappers vs. Crosscutters

Follow on MiLB First Pitch  https //stza.co/+xMqU-c

Shop  https //stza.co/+xMqU-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Crosscutters
END:VALARM
DTSTART;VALUE=DATE:20180709
DTEND;VALUE=DATE:20180709
UID:gOUlUIuu-oitia6wSGn4rHOS@stanza.co
SUMMARY:Scrappers vs. Crosscutters
DESCRIPTION:Scrappers vs. Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+xMqU-c\n\nShop: https://stza.co/+xMqU-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Yankees
<2018-07-11 Wed>--<2018-07-10 Tue>
:PROPERTIES:
:ID:       6BwHSrqgKDefCljp5l6U_490@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers @ Yankees Scrappers @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xMrJ-3r

Shop  https //stza.co/+xMrJ-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180711
DTEND;VALUE=DATE:20180711
UID:6BwHSrqgKDefCljp5l6U_490@stanza.co
SUMMARY:Scrappers @ Yankees
DESCRIPTION:Scrappers @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMrJ-3r\n\nShop: https://stza.co/+xMrJ-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Yankees
<2018-07-12 Thu>--<2018-07-11 Wed>
:PROPERTIES:
:ID:       rrRI3pRqUlJgu1vTOMIAPyRJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Scrappers @ Yankees Scrappers @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xMrK-29

Shop  https //stza.co/+xMrK-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180712
DTEND;VALUE=DATE:20180712
UID:rrRI3pRqUlJgu1vTOMIAPyRJ@stanza.co
SUMMARY:Scrappers @ Yankees
DESCRIPTION:Scrappers @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMrK-29\n\nShop: https://stza.co/+xMrK-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Yankees
<2018-07-13 Fri>--<2018-07-12 Thu>
:PROPERTIES:
:ID:       zbCZRfzHB9PqdXIoe4udQ1g-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers @ Yankees Scrappers @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xMrL-3F

Shop  https //stza.co/+xMrL-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180713
DTEND;VALUE=DATE:20180713
UID:zbCZRfzHB9PqdXIoe4udQ1g-@stanza.co
SUMMARY:Scrappers @ Yankees
DESCRIPTION:Scrappers @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMrL-3F\n\nShop: https://stza.co/+xMrL-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Renegades
<2018-07-14 Sat>--<2018-07-13 Fri>
:PROPERTIES:
:ID:       -k_7qBtnCBMlvDyiSQKx9-Ee@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Renegades Scrappers vs. Renegades

Follow on MiLB First Pitch  https //stza.co/+xMqV-L

Shop  https //stza.co/+xMqV-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Renegades
END:VALARM
DTSTART;VALUE=DATE:20180714
DTEND;VALUE=DATE:20180714
UID:-k_7qBtnCBMlvDyiSQKx9-Ee@stanza.co
SUMMARY:Scrappers vs. Renegades
DESCRIPTION:Scrappers vs. Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xMqV-L\n\nShop: https://stza.co/+xMqV-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Renegades
<2018-07-15 Sun>--<2018-07-14 Sat>
:PROPERTIES:
:ID:       tvRSabqYOi7U_C_bn7s_l-pr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Renegades Scrappers vs. Renegades

Follow on MiLB First Pitch  https //stza.co/+xMqY-1o

Shop  https //stza.co/+xMqY-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Renegades
END:VALARM
DTSTART;VALUE=DATE:20180715
DTEND;VALUE=DATE:20180715
UID:tvRSabqYOi7U_C_bn7s_l-pr@stanza.co
SUMMARY:Scrappers vs. Renegades
DESCRIPTION:Scrappers vs. Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xMqY-1o\n\nShop: https://stza.co/+xMqY-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Renegades
<2018-07-16 Mon>--<2018-07-15 Sun>
:PROPERTIES:
:ID:       6l1GNkKRB22J_Nh2OzmWWjzu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Renegades Scrappers vs. Renegades

Follow on MiLB First Pitch  https //stza.co/+xMq_-36

Shop  https //stza.co/+xMq_-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Renegades
END:VALARM
DTSTART;VALUE=DATE:20180716
DTEND;VALUE=DATE:20180716
UID:6l1GNkKRB22J_Nh2OzmWWjzu@stanza.co
SUMMARY:Scrappers vs. Renegades
DESCRIPTION:Scrappers vs. Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xMq_-36\n\nShop: https://stza.co/+xMq_-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Doubledays
<2018-07-17 Tue 17:30-20:30>
:PROPERTIES:
:ID:       WG6hf5frXgnNAleHgLXSCfnV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers @ Doubledays Scrappers @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xV$Y-B

Shop  https //stza.co/+xV$Y-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Doubledays
END:VALARM
DTSTART:20180717T223000Z
DTEND:20180718T013000Z
UID:WG6hf5frXgnNAleHgLXSCfnV@stanza.co
SUMMARY:Scrappers @ Doubledays
DESCRIPTION:Scrappers @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xV$Y-B\n\nShop: https://stza.co/+xV$Y-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Doubledays
<2018-07-18 Wed 17:30-20:30>
:PROPERTIES:
:ID:       NJJm6aF65XaY5LnXbzHMvIeA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Scrappers @ Doubledays Scrappers @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xV$Z-y

Shop  https //stza.co/+xV$Z-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Doubledays
END:VALARM
DTSTART:20180718T223000Z
DTEND:20180719T013000Z
UID:NJJm6aF65XaY5LnXbzHMvIeA@stanza.co
SUMMARY:Scrappers @ Doubledays
DESCRIPTION:Scrappers @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xV$Z-y\n\nShop: https://stza.co/+xV$Z-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Doubledays
<2018-07-19 Thu 17:30-20:30>
:PROPERTIES:
:ID:       aq4CAEt_a3eebcbbL2IZhoa4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers @ Doubledays Scrappers @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xV$_-1k

Shop  https //stza.co/+xV$_-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Doubledays
END:VALARM
DTSTART:20180719T223000Z
DTEND:20180720T013000Z
UID:aq4CAEt_a3eebcbbL2IZhoa4@stanza.co
SUMMARY:Scrappers @ Doubledays
DESCRIPTION:Scrappers @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xV$_-1k\n\nShop: https://stza.co/+xV$_-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Muckdogs
<2018-07-20 Fri>--<2018-07-19 Thu>
:PROPERTIES:
:ID:       k3QS5WRjDrZZymXxhNNxVL6B@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers @ Muckdogs Scrappers @ Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMql-3N

Shop  https //stza.co/+xMql-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180720
DTEND;VALUE=DATE:20180720
UID:k3QS5WRjDrZZymXxhNNxVL6B@stanza.co
SUMMARY:Scrappers @ Muckdogs
DESCRIPTION:Scrappers @ Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMql-3N\n\nShop: https://stza.co/+xMql-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Muckdogs
<2018-07-21 Sat>--<2018-07-20 Fri>
:PROPERTIES:
:ID:       bcP43OlVV4g-uBWUOaplyl6v@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Scrappers @ Muckdogs Scrappers @ Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMqm-2H

Shop  https //stza.co/+xMqm-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180721
DTEND;VALUE=DATE:20180721
UID:bcP43OlVV4g-uBWUOaplyl6v@stanza.co
SUMMARY:Scrappers @ Muckdogs
DESCRIPTION:Scrappers @ Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMqm-2H\n\nShop: https://stza.co/+xMqm-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Muckdogs
<2018-07-22 Sun>--<2018-07-21 Sat>
:PROPERTIES:
:ID:       A_dCeeynDR8G2g9_SKaAHxK4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers @ Muckdogs Scrappers @ Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMqn-i

Shop  https //stza.co/+xMqn-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180722
DTEND;VALUE=DATE:20180722
UID:A_dCeeynDR8G2g9_SKaAHxK4@stanza.co
SUMMARY:Scrappers @ Muckdogs
DESCRIPTION:Scrappers @ Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMqn-i\n\nShop: https://stza.co/+xMqn-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Cyclones
<2018-07-24 Tue>--<2018-07-23 Mon>
:PROPERTIES:
:ID:       1IF47CaAEixfxYIabu5FoZIf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Cyclones Scrappers vs. Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMr0-L

Shop  https //stza.co/+xMr0-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180724
DTEND;VALUE=DATE:20180724
UID:1IF47CaAEixfxYIabu5FoZIf@stanza.co
SUMMARY:Scrappers vs. Cyclones
DESCRIPTION:Scrappers vs. Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMr0-L\n\nShop: https://stza.co/+xMr0-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Cyclones
<2018-07-25 Wed>--<2018-07-24 Tue>
:PROPERTIES:
:ID:       KUy_oWC4QXU5TKEDxQ8EdN2q@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Cyclones Scrappers vs. Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMr2-2B

Shop  https //stza.co/+xMr2-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180725
DTEND;VALUE=DATE:20180725
UID:KUy_oWC4QXU5TKEDxQ8EdN2q@stanza.co
SUMMARY:Scrappers vs. Cyclones
DESCRIPTION:Scrappers vs. Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMr2-2B\n\nShop: https://stza.co/+xMr2-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Cyclones
<2018-07-26 Thu>--<2018-07-25 Wed>
:PROPERTIES:
:ID:       XBXsx5R31f_SMKGNtsELpVwf@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Cyclones Scrappers vs. Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMr4-1l

Shop  https //stza.co/+xMr4-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180726
DTEND;VALUE=DATE:20180726
UID:XBXsx5R31f_SMKGNtsELpVwf@stanza.co
SUMMARY:Scrappers vs. Cyclones
DESCRIPTION:Scrappers vs. Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMr4-1l\n\nShop: https://stza.co/+xMr4-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ IronBirds
<2018-07-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       NEYqEt2hd43fn2W9hFtznD7U@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers @ IronBirds Scrappers @ IronBirds

Follow on MiLB First Pitch  https //stza.co/+xXU9-3C

Shop  https //stza.co/+xXU9-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ IronBirds
END:VALARM
DTSTART:20180727T230500Z
DTEND:20180728T020500Z
UID:NEYqEt2hd43fn2W9hFtznD7U@stanza.co
SUMMARY:Scrappers @ IronBirds
DESCRIPTION:Scrappers @ IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xXU9-3C\n\nShop: https://stza.co/+xXU9-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ IronBirds
<2018-07-28 Sat 17:05-20:05>
:PROPERTIES:
:ID:       69ro3tMXQSkYzwgTd2Y82dmD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Scrappers @ IronBirds Scrappers @ IronBirds

Follow on MiLB First Pitch  https //stza.co/+xXUb-2O

Shop  https //stza.co/+xXUb-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ IronBirds
END:VALARM
DTSTART:20180728T220500Z
DTEND:20180729T010500Z
UID:69ro3tMXQSkYzwgTd2Y82dmD@stanza.co
SUMMARY:Scrappers @ IronBirds
DESCRIPTION:Scrappers @ IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xXUb-2O\n\nShop: https://stza.co/+xXUb-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ IronBirds
<2018-07-29 Sun 15:05-18:05>
:PROPERTIES:
:ID:       PuhSjjcmg0_3jKYQK_s6RsY8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers @ IronBirds Scrappers @ IronBirds

Follow on MiLB First Pitch  https //stza.co/+xXUd-29

Shop  https //stza.co/+xXUd-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ IronBirds
END:VALARM
DTSTART:20180729T200500Z
DTEND:20180729T230500Z
UID:PuhSjjcmg0_3jKYQK_s6RsY8@stanza.co
SUMMARY:Scrappers @ IronBirds
DESCRIPTION:Scrappers @ IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xXUd-29\n\nShop: https://stza.co/+xXUd-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Crosscutters
<2018-07-30 Mon>--<2018-07-29 Sun>
:PROPERTIES:
:ID:       MfiOM5UvkXT3No2fsFvuv1ds@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Crosscutters Scrappers vs. Crosscutters

Follow on MiLB First Pitch  https //stza.co/+xMr5-31

Shop  https //stza.co/+xMr5-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Crosscutters
END:VALARM
DTSTART;VALUE=DATE:20180730
DTEND;VALUE=DATE:20180730
UID:MfiOM5UvkXT3No2fsFvuv1ds@stanza.co
SUMMARY:Scrappers vs. Crosscutters
DESCRIPTION:Scrappers vs. Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+xMr5-31\n\nShop: https://stza.co/+xMr5-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Crosscutters
<2018-07-31 Tue>--<2018-07-30 Mon>
:PROPERTIES:
:ID:       y0td-pMDAxvoLEyw5yp7VxAR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Crosscutters Scrappers vs. Crosscutters

Follow on MiLB First Pitch  https //stza.co/+xMr7-18

Shop  https //stza.co/+xMr7-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Crosscutters
END:VALARM
DTSTART;VALUE=DATE:20180731
DTEND;VALUE=DATE:20180731
UID:y0td-pMDAxvoLEyw5yp7VxAR@stanza.co
SUMMARY:Scrappers vs. Crosscutters
DESCRIPTION:Scrappers vs. Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+xMr7-18\n\nShop: https://stza.co/+xMr7-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Crosscutters
<2018-08-01 Wed>--<2018-07-31 Tue>
:PROPERTIES:
:ID:       1I8UlGClfh1GHfk6jXyGNpuD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Crosscutters Scrappers vs. Crosscutters

Follow on MiLB First Pitch  https //stza.co/+xMra-6

Shop  https //stza.co/+xMra-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Crosscutters
END:VALARM
DTSTART;VALUE=DATE:20180801
DTEND;VALUE=DATE:20180801
UID:1I8UlGClfh1GHfk6jXyGNpuD@stanza.co
SUMMARY:Scrappers vs. Crosscutters
DESCRIPTION:Scrappers vs. Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+xMra-6\n\nShop: https://stza.co/+xMra-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Muckdogs
<2018-08-02 Thu>--<2018-08-01 Wed>
:PROPERTIES:
:ID:       82U-8_5nAS3Fuu-6Biv3TboV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers @ Muckdogs Scrappers @ Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMqo-2d

Shop  https //stza.co/+xMqo-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180802
DTEND;VALUE=DATE:20180802
UID:82U-8_5nAS3Fuu-6Biv3TboV@stanza.co
SUMMARY:Scrappers @ Muckdogs
DESCRIPTION:Scrappers @ Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMqo-2d\n\nShop: https://stza.co/+xMqo-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Muckdogs
<2018-08-03 Fri>--<2018-08-02 Thu>
:PROPERTIES:
:ID:       PiIeGkzbIZ82TcQ3n9Yqh8rI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Scrappers @ Muckdogs Scrappers @ Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMqp-2$

Shop  https //stza.co/+xMqp-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180803
DTEND;VALUE=DATE:20180803
UID:PiIeGkzbIZ82TcQ3n9Yqh8rI@stanza.co
SUMMARY:Scrappers @ Muckdogs
DESCRIPTION:Scrappers @ Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMqp-2$\n\nShop: https://stza.co/+xMqp-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Muckdogs
<2018-08-04 Sat>--<2018-08-03 Fri>
:PROPERTIES:
:ID:       yDustxvewUeXHnCQAuA1xlJu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers @ Muckdogs Scrappers @ Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMqq-1C

Shop  https //stza.co/+xMqq-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180804
DTEND;VALUE=DATE:20180804
UID:yDustxvewUeXHnCQAuA1xlJu@stanza.co
SUMMARY:Scrappers @ Muckdogs
DESCRIPTION:Scrappers @ Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMqq-1C\n\nShop: https://stza.co/+xMqq-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Spikes
<2018-08-05 Sun>--<2018-08-04 Sat>
:PROPERTIES:
:ID:       UdDHRmy5CxAXfP8X6iuBRhUA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Spikes Scrappers vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+xMrc-3

Shop  https //stza.co/+xMrc-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Spikes
END:VALARM
DTSTART;VALUE=DATE:20180805
DTEND;VALUE=DATE:20180805
UID:UdDHRmy5CxAXfP8X6iuBRhUA@stanza.co
SUMMARY:Scrappers vs. Spikes
DESCRIPTION:Scrappers vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMrc-3\n\nShop: https://stza.co/+xMrc-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Spikes
<2018-08-06 Mon>--<2018-08-05 Sun>
:PROPERTIES:
:ID:       4ZjzcuUgjPLwf8sDWnkQ6Cy4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Spikes Scrappers vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+xMrd-3U

Shop  https //stza.co/+xMrd-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Spikes
END:VALARM
DTSTART;VALUE=DATE:20180806
DTEND;VALUE=DATE:20180806
UID:4ZjzcuUgjPLwf8sDWnkQ6Cy4@stanza.co
SUMMARY:Scrappers vs. Spikes
DESCRIPTION:Scrappers vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMrd-3U\n\nShop: https://stza.co/+xMrd-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Spikes
<2018-08-07 Tue>--<2018-08-06 Mon>
:PROPERTIES:
:ID:       uDhbMBCPg7rwhGMGY8rG08P3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Spikes Scrappers vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+xMrf-3U

Shop  https //stza.co/+xMrf-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Spikes
END:VALARM
DTSTART;VALUE=DATE:20180807
DTEND;VALUE=DATE:20180807
UID:uDhbMBCPg7rwhGMGY8rG08P3@stanza.co
SUMMARY:Scrappers vs. Spikes
DESCRIPTION:Scrappers vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMrf-3U\n\nShop: https://stza.co/+xMrf-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Crosscutters
<2018-08-08 Wed 18:05-21:05>
:PROPERTIES:
:ID:       4dfk5AIke4YwJELOhMFz5WCV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers @ Crosscutters Scrappers @ Crosscutters

Follow on MiLB First Pitch  https //stza.co/+x$6b-b

Shop  https //stza.co/+x$6b-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Crosscutters
END:VALARM
DTSTART:20180808T230500Z
DTEND:20180809T020500Z
UID:4dfk5AIke4YwJELOhMFz5WCV@stanza.co
SUMMARY:Scrappers @ Crosscutters
DESCRIPTION:Scrappers @ Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+x$6b-b\n\nShop: https://stza.co/+x$6b-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Crosscutters
<2018-08-09 Thu 18:05-21:05>
:PROPERTIES:
:ID:       04vBBU4IX2bYLTNrZSFCuw0i@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Scrappers @ Crosscutters Scrappers @ Crosscutters

Follow on MiLB First Pitch  https //stza.co/+x$6c-B

Shop  https //stza.co/+x$6c-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Crosscutters
END:VALARM
DTSTART:20180809T230500Z
DTEND:20180810T020500Z
UID:04vBBU4IX2bYLTNrZSFCuw0i@stanza.co
SUMMARY:Scrappers @ Crosscutters
DESCRIPTION:Scrappers @ Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+x$6c-B\n\nShop: https://stza.co/+x$6c-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Crosscutters
<2018-08-10 Fri 18:05-21:05>
:PROPERTIES:
:ID:       QERWGfztZ5m6pvmhMuA1z6cJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers @ Crosscutters Scrappers @ Crosscutters

Follow on MiLB First Pitch  https //stza.co/+x$6d-1B

Shop  https //stza.co/+x$6d-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Crosscutters
END:VALARM
DTSTART:20180810T230500Z
DTEND:20180811T020500Z
UID:QERWGfztZ5m6pvmhMuA1z6cJ@stanza.co
SUMMARY:Scrappers @ Crosscutters
DESCRIPTION:Scrappers @ Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+x$6d-1B\n\nShop: https://stza.co/+x$6d-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Black Bears
<2018-08-11 Sat 18:05-21:05>
:PROPERTIES:
:ID:       FQvR7OjInKxzOG3cFdDXXl0k@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers @ Black Bears Scrappers @ Black Bears

Follow on MiLB First Pitch  https //stza.co/+xW05-1d

Shop  https //stza.co/+xW05-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Black Bears
END:VALARM
DTSTART:20180811T230500Z
DTEND:20180812T020500Z
UID:FQvR7OjInKxzOG3cFdDXXl0k@stanza.co
SUMMARY:Scrappers @ Black Bears
DESCRIPTION:Scrappers @ Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xW05-1d\n\nShop: https://stza.co/+xW05-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Black Bears
<2018-08-12 Sun 15:05-18:05>
:PROPERTIES:
:ID:       AEwKQDmIZ-QR6lDE_nl4LTCQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Scrappers @ Black Bears Scrappers @ Black Bears

Follow on MiLB First Pitch  https //stza.co/+xW06-f

Shop  https //stza.co/+xW06-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Black Bears
END:VALARM
DTSTART:20180812T200500Z
DTEND:20180812T230500Z
UID:AEwKQDmIZ-QR6lDE_nl4LTCQ@stanza.co
SUMMARY:Scrappers @ Black Bears
DESCRIPTION:Scrappers @ Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xW06-f\n\nShop: https://stza.co/+xW06-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Doubledays
<2018-08-15 Wed>--<2018-08-14 Tue>
:PROPERTIES:
:ID:       zvv-aFbufo0tXop5P2ypGzk3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Doubledays Scrappers vs. Doubledays

Follow on MiLB First Pitch  https //stza.co/+xMrh-4

Shop  https //stza.co/+xMrh-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Doubledays
END:VALARM
DTSTART;VALUE=DATE:20180815
DTEND;VALUE=DATE:20180815
UID:zvv-aFbufo0tXop5P2ypGzk3@stanza.co
SUMMARY:Scrappers vs. Doubledays
DESCRIPTION:Scrappers vs. Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xMrh-4\n\nShop: https://stza.co/+xMrh-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Doubledays
<2018-08-16 Thu>--<2018-08-15 Wed>
:PROPERTIES:
:ID:       u-0ZL0V-4eZhYYxlMPh9p0-s@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Doubledays Scrappers vs. Doubledays

Follow on MiLB First Pitch  https //stza.co/+xMrj-3Q

Shop  https //stza.co/+xMrj-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Doubledays
END:VALARM
DTSTART;VALUE=DATE:20180816
DTEND;VALUE=DATE:20180816
UID:u-0ZL0V-4eZhYYxlMPh9p0-s@stanza.co
SUMMARY:Scrappers vs. Doubledays
DESCRIPTION:Scrappers vs. Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xMrj-3Q\n\nShop: https://stza.co/+xMrj-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Spikes
<2018-08-17 Fri>--<2018-08-16 Thu>
:PROPERTIES:
:ID:       GeHIVF6aDJwbnVVMqhKBF3U9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Spikes Scrappers vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+xMrl-2o

Shop  https //stza.co/+xMrl-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Spikes
END:VALARM
DTSTART;VALUE=DATE:20180817
DTEND;VALUE=DATE:20180817
UID:GeHIVF6aDJwbnVVMqhKBF3U9@stanza.co
SUMMARY:Scrappers vs. Spikes
DESCRIPTION:Scrappers vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMrl-2o\n\nShop: https://stza.co/+xMrl-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Spikes
<2018-08-18 Sat>--<2018-08-17 Fri>
:PROPERTIES:
:ID:       i2ara5sacKTxMqUUSYQALVf2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Spikes Scrappers vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+xMrn-3b

Shop  https //stza.co/+xMrn-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Spikes
END:VALARM
DTSTART;VALUE=DATE:20180818
DTEND;VALUE=DATE:20180818
UID:i2ara5sacKTxMqUUSYQALVf2@stanza.co
SUMMARY:Scrappers vs. Spikes
DESCRIPTION:Scrappers vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMrn-3b\n\nShop: https://stza.co/+xMrn-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Spikes
<2018-08-19 Sun>--<2018-08-18 Sat>
:PROPERTIES:
:ID:       9VAPRulQjk3cE1GHQ-8ZdBbQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Spikes Scrappers vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+xMrp-2G

Shop  https //stza.co/+xMrp-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Spikes
END:VALARM
DTSTART;VALUE=DATE:20180819
DTEND;VALUE=DATE:20180819
UID:9VAPRulQjk3cE1GHQ-8ZdBbQ@stanza.co
SUMMARY:Scrappers vs. Spikes
DESCRIPTION:Scrappers vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMrp-2G\n\nShop: https://stza.co/+xMrp-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Doubledays
<2018-08-20 Mon 17:30-20:30>
:PROPERTIES:
:ID:       7mnL1ajH363gPCkiZFWLvNUz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Scrappers @ Doubledays Scrappers @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xV$$-2R

Shop  https //stza.co/+xV$$-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Doubledays
END:VALARM
DTSTART:20180820T223000Z
DTEND:20180821T013000Z
UID:7mnL1ajH363gPCkiZFWLvNUz@stanza.co
SUMMARY:Scrappers @ Doubledays
DESCRIPTION:Scrappers @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xV$$-2R\n\nShop: https://stza.co/+xV$$-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Doubledays
<2018-08-21 Tue 17:30-20:30>
:PROPERTIES:
:ID:       FnEoyD0lq7WHjtME7o1ES6S3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers @ Doubledays Scrappers @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xW00-e

Shop  https //stza.co/+xW00-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Doubledays
END:VALARM
DTSTART:20180821T223000Z
DTEND:20180822T013000Z
UID:FnEoyD0lq7WHjtME7o1ES6S3@stanza.co
SUMMARY:Scrappers @ Doubledays
DESCRIPTION:Scrappers @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xW00-e\n\nShop: https://stza.co/+xW00-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Doubledays
<2018-08-22 Wed 17:30-20:30>
:PROPERTIES:
:ID:       _0zZoZsLHWlqHao3ea6dqztL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers @ Doubledays Scrappers @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xW01-3

Shop  https //stza.co/+xW01-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Doubledays
END:VALARM
DTSTART:20180822T223000Z
DTEND:20180823T013000Z
UID:_0zZoZsLHWlqHao3ea6dqztL@stanza.co
SUMMARY:Scrappers @ Doubledays
DESCRIPTION:Scrappers @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xW01-3\n\nShop: https://stza.co/+xW01-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Black Bears
<2018-08-23 Thu>--<2018-08-22 Wed>
:PROPERTIES:
:ID:       xYv36BWQ6uQe-GxkUdmt2snh@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Black Bears Scrappers vs. Black Bears

Follow on MiLB First Pitch  https //stza.co/+xMrs-1$

Shop  https //stza.co/+xMrs-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Black Bears
END:VALARM
DTSTART;VALUE=DATE:20180823
DTEND;VALUE=DATE:20180823
UID:xYv36BWQ6uQe-GxkUdmt2snh@stanza.co
SUMMARY:Scrappers vs. Black Bears
DESCRIPTION:Scrappers vs. Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xMrs-1$\n\nShop: https://stza.co/+xMrs-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Black Bears
<2018-08-24 Fri>--<2018-08-23 Thu>
:PROPERTIES:
:ID:       oXmps81sc7-nEbED45N4K3OR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Black Bears Scrappers vs. Black Bears

Follow on MiLB First Pitch  https //stza.co/+xMru-14

Shop  https //stza.co/+xMru-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Black Bears
END:VALARM
DTSTART;VALUE=DATE:20180824
DTEND;VALUE=DATE:20180824
UID:oXmps81sc7-nEbED45N4K3OR@stanza.co
SUMMARY:Scrappers vs. Black Bears
DESCRIPTION:Scrappers vs. Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xMru-14\n\nShop: https://stza.co/+xMru-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Black Bears
<2018-08-25 Sat>--<2018-08-24 Fri>
:PROPERTIES:
:ID:       JZmfjM8kJBDJC9cMA1rYXoMX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Black Bears Scrappers vs. Black Bears

Follow on MiLB First Pitch  https //stza.co/+xMrv-30

Shop  https //stza.co/+xMrv-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Black Bears
END:VALARM
DTSTART;VALUE=DATE:20180825
DTEND;VALUE=DATE:20180825
UID:JZmfjM8kJBDJC9cMA1rYXoMX@stanza.co
SUMMARY:Scrappers vs. Black Bears
DESCRIPTION:Scrappers vs. Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xMrv-30\n\nShop: https://stza.co/+xMrv-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Crosscutters
<2018-08-26 Sun 18:05-21:05>
:PROPERTIES:
:ID:       Y_lOrvPls0bfii5WZobnv1-w@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Scrappers @ Crosscutters Scrappers @ Crosscutters

Follow on MiLB First Pitch  https //stza.co/+x$6e-3_

Shop  https //stza.co/+x$6e-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Crosscutters
END:VALARM
DTSTART:20180826T230500Z
DTEND:20180827T020500Z
UID:Y_lOrvPls0bfii5WZobnv1-w@stanza.co
SUMMARY:Scrappers @ Crosscutters
DESCRIPTION:Scrappers @ Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+x$6e-3_\n\nShop: https://stza.co/+x$6e-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Crosscutters
<2018-08-27 Mon 18:05-21:05>
:PROPERTIES:
:ID:       b444asMEEkymBL0Q1X7xPxSm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers @ Crosscutters Scrappers @ Crosscutters

Follow on MiLB First Pitch  https //stza.co/+x$6f-1u

Shop  https //stza.co/+x$6f-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Crosscutters
END:VALARM
DTSTART:20180827T230500Z
DTEND:20180828T020500Z
UID:b444asMEEkymBL0Q1X7xPxSm@stanza.co
SUMMARY:Scrappers @ Crosscutters
DESCRIPTION:Scrappers @ Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+x$6f-1u\n\nShop: https://stza.co/+x$6f-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Crosscutters
<2018-08-28 Tue 18:05-21:05>
:PROPERTIES:
:ID:       7prNq9-4Q21rg2Z5RPMzOwAG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers @ Crosscutters Scrappers @ Crosscutters

Follow on MiLB First Pitch  https //stza.co/+x$6g-1e

Shop  https //stza.co/+x$6g-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Crosscutters
END:VALARM
DTSTART:20180828T230500Z
DTEND:20180829T020500Z
UID:7prNq9-4Q21rg2Z5RPMzOwAG@stanza.co
SUMMARY:Scrappers @ Crosscutters
DESCRIPTION:Scrappers @ Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+x$6g-1e\n\nShop: https://stza.co/+x$6g-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Muckdogs
<2018-08-29 Wed>--<2018-08-28 Tue>
:PROPERTIES:
:ID:       eujJcuYkAcpWElaEEaCfiAW9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Muckdogs Scrappers vs. Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMrx-2x

Shop  https //stza.co/+xMrx-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180829
DTEND;VALUE=DATE:20180829
UID:eujJcuYkAcpWElaEEaCfiAW9@stanza.co
SUMMARY:Scrappers vs. Muckdogs
DESCRIPTION:Scrappers vs. Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMrx-2x\n\nShop: https://stza.co/+xMrx-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Muckdogs
<2018-08-30 Thu>--<2018-08-29 Wed>
:PROPERTIES:
:ID:       PKqF8rkeQzf7riTyUE45zI4-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Muckdogs Scrappers vs. Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMrA-2f

Shop  https //stza.co/+xMrA-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180830
DTEND;VALUE=DATE:20180830
UID:PKqF8rkeQzf7riTyUE45zI4-@stanza.co
SUMMARY:Scrappers vs. Muckdogs
DESCRIPTION:Scrappers vs. Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMrA-2f\n\nShop: https://stza.co/+xMrA-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers vs. Muckdogs
<2018-08-31 Fri>--<2018-08-30 Thu>
:PROPERTIES:
:ID:       y08lAAckHB0rk1mNxPtriaxa@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers vs. Muckdogs Scrappers vs. Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMrC-3N

Shop  https //stza.co/+xMrC-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Scrappers vs. Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180831
DTEND;VALUE=DATE:20180831
UID:y08lAAckHB0rk1mNxPtriaxa@stanza.co
SUMMARY:Scrappers vs. Muckdogs
DESCRIPTION:Scrappers vs. Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMrC-3N\n\nShop: https://stza.co/+xMrC-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Black Bears
<2018-09-01 Sat 18:05-21:05>
:PROPERTIES:
:ID:       GSrEcRYyM9U8tAvWA2frJPOD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Scrappers @ Black Bears Scrappers @ Black Bears

Follow on MiLB First Pitch  https //stza.co/+xW07-3v

Shop  https //stza.co/+xW07-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Black Bears
END:VALARM
DTSTART:20180901T230500Z
DTEND:20180902T020500Z
UID:GSrEcRYyM9U8tAvWA2frJPOD@stanza.co
SUMMARY:Scrappers @ Black Bears
DESCRIPTION:Scrappers @ Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xW07-3v\n\nShop: https://stza.co/+xW07-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Black Bears
<2018-09-02 Sun 15:05-18:05>
:PROPERTIES:
:ID:       xd8jhTfIoG7x79IvkeO7yil9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers @ Black Bears Scrappers @ Black Bears

Follow on MiLB First Pitch  https //stza.co/+xW08-1f

Shop  https //stza.co/+xW08-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Black Bears
END:VALARM
DTSTART:20180902T200500Z
DTEND:20180902T230500Z
UID:xd8jhTfIoG7x79IvkeO7yil9@stanza.co
SUMMARY:Scrappers @ Black Bears
DESCRIPTION:Scrappers @ Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xW08-1f\n\nShop: https://stza.co/+xW08-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Scrappers @ Black Bears
<2018-09-03 Mon 12:05-15:05>
:PROPERTIES:
:ID:       -pmCYXyVIENCzH2neyzqO5Zo@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Scrappers @ Black Bears Scrappers @ Black Bears

Follow on MiLB First Pitch  https //stza.co/+xW09-33

Shop  https //stza.co/+xW09-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Scrappers @ Black Bears
END:VALARM
DTSTART:20180903T170500Z
DTEND:20180903T200500Z
UID:-pmCYXyVIENCzH2neyzqO5Zo@stanza.co
SUMMARY:Scrappers @ Black Bears
DESCRIPTION:Scrappers @ Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xW09-33\n\nShop: https://stza.co/+xW09-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
