#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* JetHawks vs. Nuts
<2018-04-05 Thu 20:35-23:35>
:PROPERTIES:
:ID:       yHma29e8Q216ouh6RVTgK92T@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Nuts JetHawks vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+vf6M-3T

Shop  https //stza.co/+vf6M-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Nuts
END:VALARM
DTSTART:20180406T013500Z
DTEND:20180406T043500Z
UID:yHma29e8Q216ouh6RVTgK92T@stanza.co
SUMMARY:JetHawks vs. Nuts
DESCRIPTION:JetHawks vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+vf6M-3T\n\nShop: https://stza.co/+vf6M-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Nuts
<2018-04-06 Fri 20:35-23:35>
:PROPERTIES:
:ID:       Kq9lI469dN3KW_R46O3OC-78@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Nuts JetHawks vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+vf6W-o

Shop  https //stza.co/+vf6W-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Nuts
END:VALARM
DTSTART:20180407T013500Z
DTEND:20180407T043500Z
UID:Kq9lI469dN3KW_R46O3OC-78@stanza.co
SUMMARY:JetHawks vs. Nuts
DESCRIPTION:JetHawks vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+vf6W-o\n\nShop: https://stza.co/+vf6W-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Nuts
<2018-04-07 Sat 20:05-23:05>
:PROPERTIES:
:ID:       1J3YwZI6n2-fRBRGA2V5SErS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Nuts JetHawks vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+vf7e-3H

Shop  https //stza.co/+vf7e-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Nuts
END:VALARM
DTSTART:20180408T010500Z
DTEND:20180408T040500Z
UID:1J3YwZI6n2-fRBRGA2V5SErS@stanza.co
SUMMARY:JetHawks vs. Nuts
DESCRIPTION:JetHawks vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+vf7e-3H\n\nShop: https://stza.co/+vf7e-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Nuts
<2018-04-08 Sun>--<2018-04-07 Sat>
:PROPERTIES:
:ID:       _gVfj22bOyFq8Auv8nAScZyU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Nuts JetHawks vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+vf7v-2x

Shop  https //stza.co/+vf7v-2S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Nuts
END:VALARM
DTSTART;VALUE=DATE:20180408
DTEND;VALUE=DATE:20180408
UID:_gVfj22bOyFq8Auv8nAScZyU@stanza.co
SUMMARY:JetHawks vs. Nuts
DESCRIPTION:JetHawks vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+vf7v-2x\n\nShop: https://stza.co/+vf7v-2S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Giants
<2018-04-09 Mon 20:35-23:35>
:PROPERTIES:
:ID:       ghZ00uatcNGeL0bB5dg8DNag@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Giants JetHawks vs. Giants

Follow on MiLB First Pitch  https //stza.co/+vf7N-39

Shop  https //stza.co/+vf7N-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Giants
END:VALARM
DTSTART:20180410T013500Z
DTEND:20180410T043500Z
UID:ghZ00uatcNGeL0bB5dg8DNag@stanza.co
SUMMARY:JetHawks vs. Giants
DESCRIPTION:JetHawks vs. Giants\n\nFollow on MiLB First Pitch: https://stza.co/+vf7N-39\n\nShop: https://stza.co/+vf7N-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Giants
<2018-04-10 Tue 20:35-23:35>
:PROPERTIES:
:ID:       iYF-7xr0xILrGgUNZIMlQXrF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Giants JetHawks vs. Giants

Follow on MiLB First Pitch  https //stza.co/+vf7X-p

Shop  https //stza.co/+vf7X-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Giants
END:VALARM
DTSTART:20180411T013500Z
DTEND:20180411T043500Z
UID:iYF-7xr0xILrGgUNZIMlQXrF@stanza.co
SUMMARY:JetHawks vs. Giants
DESCRIPTION:JetHawks vs. Giants\n\nFollow on MiLB First Pitch: https://stza.co/+vf7X-p\n\nShop: https://stza.co/+vf7X-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Giants
<2018-04-11 Wed 20:35-23:35>
:PROPERTIES:
:ID:       3Lr8hD57Ur82Bq2WB4cMt8mn@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Giants JetHawks vs. Giants

Follow on MiLB First Pitch  https //stza.co/+vf81-2v

Shop  https //stza.co/+vf81-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Giants
END:VALARM
DTSTART:20180412T013500Z
DTEND:20180412T043500Z
UID:3Lr8hD57Ur82Bq2WB4cMt8mn@stanza.co
SUMMARY:JetHawks vs. Giants
DESCRIPTION:JetHawks vs. Giants\n\nFollow on MiLB First Pitch: https://stza.co/+vf81-2v\n\nShop: https://stza.co/+vf81-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Storm
<2018-04-12 Thu 21:00>--<2018-04-13 Fri 00:00>
:PROPERTIES:
:ID:       56UzfPgF_fjO_YS1vw1deUwx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks @ Storm JetHawks @ Storm

Follow on MiLB First Pitch  https //stza.co/+xAOr-2n

Shop  https //stza.co/+xAOr-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Storm
END:VALARM
DTSTART:20180413T020000Z
DTEND:20180413T050000Z
UID:56UzfPgF_fjO_YS1vw1deUwx@stanza.co
SUMMARY:JetHawks @ Storm
DESCRIPTION:JetHawks @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xAOr-2n\n\nShop: https://stza.co/+xAOr-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Storm
<2018-04-13 Fri 21:00>--<2018-04-14 Sat 00:00>
:PROPERTIES:
:ID:       YZaOroK1wBvuQchvVTh1UY4n@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Storm JetHawks @ Storm

Follow on MiLB First Pitch  https //stza.co/+xAOs-2R

Shop  https //stza.co/+xAOs-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Storm
END:VALARM
DTSTART:20180414T020000Z
DTEND:20180414T050000Z
UID:YZaOroK1wBvuQchvVTh1UY4n@stanza.co
SUMMARY:JetHawks @ Storm
DESCRIPTION:JetHawks @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xAOs-2R\n\nShop: https://stza.co/+xAOs-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Storm
<2018-04-14 Sat 20:00-23:00>
:PROPERTIES:
:ID:       qKsKnkkVKuhD9uj63yuL2So1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Storm JetHawks @ Storm

Follow on MiLB First Pitch  https //stza.co/+xAOt-X

Shop  https //stza.co/+xAOt-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Storm
END:VALARM
DTSTART:20180415T010000Z
DTEND:20180415T040000Z
UID:qKsKnkkVKuhD9uj63yuL2So1@stanza.co
SUMMARY:JetHawks @ Storm
DESCRIPTION:JetHawks @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xAOt-X\n\nShop: https://stza.co/+xAOt-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Storm
<2018-04-15 Sun>--<2018-04-14 Sat>
:PROPERTIES:
:ID:       pcXPfuzTbw_M63r47OeIgu34@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks @ Storm JetHawks @ Storm

Follow on MiLB First Pitch  https //stza.co/+vf63-3q

Shop  https //stza.co/+vf63-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Storm
END:VALARM
DTSTART;VALUE=DATE:20180415
DTEND;VALUE=DATE:20180415
UID:pcXPfuzTbw_M63r47OeIgu34@stanza.co
SUMMARY:JetHawks @ Storm
DESCRIPTION:JetHawks @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+vf63-3q\n\nShop: https://stza.co/+vf63-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Quakes
<2018-04-16 Mon 20:35-23:35>
:PROPERTIES:
:ID:       DpsB1p9Xh8QRju2v-UpufJjV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Quakes JetHawks vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+vf8b-a

Shop  https //stza.co/+vf8b-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Quakes
END:VALARM
DTSTART:20180417T013500Z
DTEND:20180417T043500Z
UID:DpsB1p9Xh8QRju2v-UpufJjV@stanza.co
SUMMARY:JetHawks vs. Quakes
DESCRIPTION:JetHawks vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+vf8b-a\n\nShop: https://stza.co/+vf8b-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Quakes
<2018-04-17 Tue 20:35-23:35>
:PROPERTIES:
:ID:       5MyOa8H5GdN-dLH4uXaCgPsB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Quakes JetHawks vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+vf8i-r

Shop  https //stza.co/+vf8i-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Quakes
END:VALARM
DTSTART:20180418T013500Z
DTEND:20180418T043500Z
UID:5MyOa8H5GdN-dLH4uXaCgPsB@stanza.co
SUMMARY:JetHawks vs. Quakes
DESCRIPTION:JetHawks vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+vf8i-r\n\nShop: https://stza.co/+vf8i-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Quakes
<2018-04-18 Wed 20:35-23:35>
:PROPERTIES:
:ID:       KayBjphOi92xQVbqAPoUXr_D@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Quakes JetHawks vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+vf8s-X

Shop  https //stza.co/+vf8s-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Quakes
END:VALARM
DTSTART:20180419T013500Z
DTEND:20180419T043500Z
UID:KayBjphOi92xQVbqAPoUXr_D@stanza.co
SUMMARY:JetHawks vs. Quakes
DESCRIPTION:JetHawks vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+vf8s-X\n\nShop: https://stza.co/+vf8s-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ 66ers
<2018-04-19 Thu 21:05>--<2018-04-20 Fri 00:05>
:PROPERTIES:
:ID:       xg6UQWupMgFtW1D5PaWYtJIW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ 66ers JetHawks @ 66ers

Follow on MiLB First Pitch  https //stza.co/+y0BS-1a

Shop  https //stza.co/+y0BS-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ 66ers
END:VALARM
DTSTART:20180420T020500Z
DTEND:20180420T050500Z
UID:xg6UQWupMgFtW1D5PaWYtJIW@stanza.co
SUMMARY:JetHawks @ 66ers
DESCRIPTION:JetHawks @ 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+y0BS-1a\n\nShop: https://stza.co/+y0BS-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ 66ers
<2018-04-20 Fri 21:05>--<2018-04-21 Sat 00:05>
:PROPERTIES:
:ID:       PVw7GYIRRlHJ4KbFK4EtVpjJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ 66ers JetHawks @ 66ers

Follow on MiLB First Pitch  https //stza.co/+y0BT-1O

Shop  https //stza.co/+y0BT-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ 66ers
END:VALARM
DTSTART:20180421T020500Z
DTEND:20180421T050500Z
UID:PVw7GYIRRlHJ4KbFK4EtVpjJ@stanza.co
SUMMARY:JetHawks @ 66ers
DESCRIPTION:JetHawks @ 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+y0BT-1O\n\nShop: https://stza.co/+y0BT-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ 66ers
<2018-04-21 Sat 20:05-23:05>
:PROPERTIES:
:ID:       FoWQinmiHBRKSU97koF8GJQt@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks @ 66ers JetHawks @ 66ers

Follow on MiLB First Pitch  https //stza.co/+y0BU-2H

Shop  https //stza.co/+y0BU-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ 66ers
END:VALARM
DTSTART:20180422T010500Z
DTEND:20180422T040500Z
UID:FoWQinmiHBRKSU97koF8GJQt@stanza.co
SUMMARY:JetHawks @ 66ers
DESCRIPTION:JetHawks @ 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+y0BU-2H\n\nShop: https://stza.co/+y0BU-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ 66ers
<2018-04-22 Sun 16:05-19:05>
:PROPERTIES:
:ID:       p6xBgNWrtwGh2skjA7bgFmlX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ 66ers JetHawks @ 66ers

Follow on MiLB First Pitch  https //stza.co/+y0BV-3j

Shop  https //stza.co/+y0BV-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ 66ers
END:VALARM
DTSTART:20180422T210500Z
DTEND:20180423T000500Z
UID:p6xBgNWrtwGh2skjA7bgFmlX@stanza.co
SUMMARY:JetHawks @ 66ers
DESCRIPTION:JetHawks @ 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+y0BV-3j\n\nShop: https://stza.co/+y0BV-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Rawhide
<2018-04-24 Tue>--<2018-04-23 Mon>
:PROPERTIES:
:ID:       RVnTiM7Z0a4E7oKh7x8RbaRr@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Rawhide JetHawks @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vLZB-3p

Shop  https //stza.co/+vLZB-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180424
DTEND;VALUE=DATE:20180424
UID:RVnTiM7Z0a4E7oKh7x8RbaRr@stanza.co
SUMMARY:JetHawks @ Rawhide
DESCRIPTION:JetHawks @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vLZB-3p\n\nShop: https://stza.co/+vLZB-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Rawhide
<2018-04-25 Wed>--<2018-04-24 Tue>
:PROPERTIES:
:ID:       F4aWmGknWHrWWIiMeyUyBmtR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks @ Rawhide JetHawks @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vLZC-2C

Shop  https //stza.co/+vLZC-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180425
DTEND;VALUE=DATE:20180425
UID:F4aWmGknWHrWWIiMeyUyBmtR@stanza.co
SUMMARY:JetHawks @ Rawhide
DESCRIPTION:JetHawks @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vLZC-2C\n\nShop: https://stza.co/+vLZC-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Rawhide
<2018-04-26 Thu>--<2018-04-25 Wed>
:PROPERTIES:
:ID:       kTgYnuZvUUHVAll3G21WH9Yr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Rawhide JetHawks @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vLZD-32

Shop  https //stza.co/+vLZD-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180426
DTEND;VALUE=DATE:20180426
UID:kTgYnuZvUUHVAll3G21WH9Yr@stanza.co
SUMMARY:JetHawks @ Rawhide
DESCRIPTION:JetHawks @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vLZD-32\n\nShop: https://stza.co/+vLZD-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Quakes
<2018-04-27 Fri 20:35-23:35>
:PROPERTIES:
:ID:       Lfjh_bQoXtmQlW4nLp7vMdFp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Quakes JetHawks vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+vf8J-33

Shop  https //stza.co/+vf8J-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Quakes
END:VALARM
DTSTART:20180428T013500Z
DTEND:20180428T043500Z
UID:Lfjh_bQoXtmQlW4nLp7vMdFp@stanza.co
SUMMARY:JetHawks vs. Quakes
DESCRIPTION:JetHawks vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+vf8J-33\n\nShop: https://stza.co/+vf8J-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Quakes
<2018-04-28 Sat 20:05-23:05>
:PROPERTIES:
:ID:       5AalsWsA8YBOUt1a3wcME2iz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Quakes JetHawks vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+vf8S-2n

Shop  https //stza.co/+vf8S-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Quakes
END:VALARM
DTSTART:20180429T010500Z
DTEND:20180429T040500Z
UID:5AalsWsA8YBOUt1a3wcME2iz@stanza.co
SUMMARY:JetHawks vs. Quakes
DESCRIPTION:JetHawks vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+vf8S-2n\n\nShop: https://stza.co/+vf8S-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Quakes
<2018-04-29 Sun>--<2018-04-28 Sat>
:PROPERTIES:
:ID:       UAwO2yIaSTgGaUl60RZEnp-E@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Quakes JetHawks vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+vf90-1g

Shop  https //stza.co/+vf90-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Quakes
END:VALARM
DTSTART;VALUE=DATE:20180429
DTEND;VALUE=DATE:20180429
UID:UAwO2yIaSTgGaUl60RZEnp-E@stanza.co
SUMMARY:JetHawks vs. Quakes
DESCRIPTION:JetHawks vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+vf90-1g\n\nShop: https://stza.co/+vf90-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Ports
<2018-04-30 Mon 21:10>--<2018-05-01 Tue 00:10>
:PROPERTIES:
:ID:       fFc649iSbJGnaB79dG_LUMHP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Ports JetHawks @ Ports

Follow on MiLB First Pitch  https //stza.co/+vLZp-1A

Shop  https //stza.co/+vLZp-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Ports
END:VALARM
DTSTART:20180501T021000Z
DTEND:20180501T051000Z
UID:fFc649iSbJGnaB79dG_LUMHP@stanza.co
SUMMARY:JetHawks @ Ports
DESCRIPTION:JetHawks @ Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vLZp-1A\n\nShop: https://stza.co/+vLZp-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Ports
<2018-05-01 Tue 21:10>--<2018-05-02 Wed 00:10>
:PROPERTIES:
:ID:       -p5MBF51-9Np3ndOGo42fXn1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks @ Ports JetHawks @ Ports

Follow on MiLB First Pitch  https //stza.co/+vLZq-2P

Shop  https //stza.co/+vLZq-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Ports
END:VALARM
DTSTART:20180502T021000Z
DTEND:20180502T051000Z
UID:-p5MBF51-9Np3ndOGo42fXn1@stanza.co
SUMMARY:JetHawks @ Ports
DESCRIPTION:JetHawks @ Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vLZq-2P\n\nShop: https://stza.co/+vLZq-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Ports
<2018-05-02 Wed 21:10>--<2018-05-03 Thu 00:10>
:PROPERTIES:
:ID:       Vfmy5Nl6-1i2t5xvQ9BiDsJc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Ports JetHawks @ Ports

Follow on MiLB First Pitch  https //stza.co/+vLZr-1l

Shop  https //stza.co/+vLZr-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Ports
END:VALARM
DTSTART:20180503T021000Z
DTEND:20180503T051000Z
UID:Vfmy5Nl6-1i2t5xvQ9BiDsJc@stanza.co
SUMMARY:JetHawks @ Ports
DESCRIPTION:JetHawks @ Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vLZr-1l\n\nShop: https://stza.co/+vLZr-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Ports
<2018-05-03 Thu 13:10-16:10>
:PROPERTIES:
:ID:       oYOdqOqnn6_CZk9aCwoGFVD7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Ports JetHawks @ Ports

Follow on MiLB First Pitch  https //stza.co/+vLZs-3a

Shop  https //stza.co/+vLZs-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Ports
END:VALARM
DTSTART:20180503T181000Z
DTEND:20180503T211000Z
UID:oYOdqOqnn6_CZk9aCwoGFVD7@stanza.co
SUMMARY:JetHawks @ Ports
DESCRIPTION:JetHawks @ Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vLZs-3a\n\nShop: https://stza.co/+vLZs-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Giants
<2018-05-04 Fri 20:35-23:35>
:PROPERTIES:
:ID:       yiy7aWTt0wtZ2ZhYz-2PMTdh@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Giants JetHawks vs. Giants

Follow on MiLB First Pitch  https //stza.co/+vf9b-w

Shop  https //stza.co/+vf9b-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Giants
END:VALARM
DTSTART:20180505T013500Z
DTEND:20180505T043500Z
UID:yiy7aWTt0wtZ2ZhYz-2PMTdh@stanza.co
SUMMARY:JetHawks vs. Giants
DESCRIPTION:JetHawks vs. Giants\n\nFollow on MiLB First Pitch: https://stza.co/+vf9b-w\n\nShop: https://stza.co/+vf9b-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Giants
<2018-05-05 Sat 20:05-23:05>
:PROPERTIES:
:ID:       Tw3QFUou2f72-Xf5qgqljmIZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Giants JetHawks vs. Giants

Follow on MiLB First Pitch  https //stza.co/+vf9j-35

Shop  https //stza.co/+vf9j-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Giants
END:VALARM
DTSTART:20180506T010500Z
DTEND:20180506T040500Z
UID:Tw3QFUou2f72-Xf5qgqljmIZ@stanza.co
SUMMARY:JetHawks vs. Giants
DESCRIPTION:JetHawks vs. Giants\n\nFollow on MiLB First Pitch: https://stza.co/+vf9j-35\n\nShop: https://stza.co/+vf9j-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Giants
<2018-05-06 Sun>--<2018-05-05 Sat>
:PROPERTIES:
:ID:       zyL6iErtAdn7dabB5FEs11jg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Giants JetHawks vs. Giants

Follow on MiLB First Pitch  https //stza.co/+vf9q-1q

Shop  https //stza.co/+vf9q-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Giants
END:VALARM
DTSTART;VALUE=DATE:20180506
DTEND;VALUE=DATE:20180506
UID:zyL6iErtAdn7dabB5FEs11jg@stanza.co
SUMMARY:JetHawks vs. Giants
DESCRIPTION:JetHawks vs. Giants\n\nFollow on MiLB First Pitch: https://stza.co/+vf9q-1q\n\nShop: https://stza.co/+vf9q-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. 66ers
<2018-05-08 Tue 20:35-23:35>
:PROPERTIES:
:ID:       pi7rDEkplpmOJeB8MrNdyQs9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks vs. 66ers JetHawks vs. 66ers

Follow on MiLB First Pitch  https //stza.co/+vf9z-2u

Shop  https //stza.co/+vf9z-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. 66ers
END:VALARM
DTSTART:20180509T013500Z
DTEND:20180509T043500Z
UID:pi7rDEkplpmOJeB8MrNdyQs9@stanza.co
SUMMARY:JetHawks vs. 66ers
DESCRIPTION:JetHawks vs. 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+vf9z-2u\n\nShop: https://stza.co/+vf9z-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. 66ers
<2018-05-09 Wed 20:35-23:35>
:PROPERTIES:
:ID:       MoYheADMwE873p3fDYv3vLie@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. 66ers JetHawks vs. 66ers

Follow on MiLB First Pitch  https //stza.co/+vf9J-3D

Shop  https //stza.co/+vf9J-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. 66ers
END:VALARM
DTSTART:20180510T013500Z
DTEND:20180510T043500Z
UID:MoYheADMwE873p3fDYv3vLie@stanza.co
SUMMARY:JetHawks vs. 66ers
DESCRIPTION:JetHawks vs. 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+vf9J-3D\n\nShop: https://stza.co/+vf9J-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. 66ers
<2018-05-10 Thu 20:35-23:35>
:PROPERTIES:
:ID:       8ZvVVigUSVYlZAOi7BiOsT6w@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. 66ers JetHawks vs. 66ers

Follow on MiLB First Pitch  https //stza.co/+vf9S-2r

Shop  https //stza.co/+vf9S-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. 66ers
END:VALARM
DTSTART:20180511T013500Z
DTEND:20180511T043500Z
UID:8ZvVVigUSVYlZAOi7BiOsT6w@stanza.co
SUMMARY:JetHawks vs. 66ers
DESCRIPTION:JetHawks vs. 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+vf9S-2r\n\nShop: https://stza.co/+vf9S-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Giants
<2018-05-11 Fri 21:00>--<2018-05-12 Sat 00:00>
:PROPERTIES:
:ID:       dOcIga_lZuJa9E5UxfG6rKv4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks @ Giants JetHawks @ Giants

Follow on MiLB First Pitch  https //stza.co/+xEVV-2k

Shop  https //stza.co/+xEVV-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Giants
END:VALARM
DTSTART:20180512T020000Z
DTEND:20180512T050000Z
UID:dOcIga_lZuJa9E5UxfG6rKv4@stanza.co
SUMMARY:JetHawks @ Giants
DESCRIPTION:JetHawks @ Giants\n\nFollow on MiLB First Pitch: https://stza.co/+xEVV-2k\n\nShop: https://stza.co/+xEVV-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Giants
<2018-05-12 Sat 19:00-22:00>
:PROPERTIES:
:ID:       DgoykfiUxUpvXbN3cGT4RTXL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Giants JetHawks @ Giants

Follow on MiLB First Pitch  https //stza.co/+xEVW-3X

Shop  https //stza.co/+xEVW-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Giants
END:VALARM
DTSTART:20180513T000000Z
DTEND:20180513T030000Z
UID:DgoykfiUxUpvXbN3cGT4RTXL@stanza.co
SUMMARY:JetHawks @ Giants
DESCRIPTION:JetHawks @ Giants\n\nFollow on MiLB First Pitch: https://stza.co/+xEVW-3X\n\nShop: https://stza.co/+xEVW-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Giants
<2018-05-13 Sun 15:00-18:00>
:PROPERTIES:
:ID:       5zpRVkzfmk_yfhSWXUKe8gNR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Giants JetHawks @ Giants

Follow on MiLB First Pitch  https //stza.co/+xEVX-1B

Shop  https //stza.co/+xEVX-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Giants
END:VALARM
DTSTART:20180513T200000Z
DTEND:20180513T230000Z
UID:5zpRVkzfmk_yfhSWXUKe8gNR@stanza.co
SUMMARY:JetHawks @ Giants
DESCRIPTION:JetHawks @ Giants\n\nFollow on MiLB First Pitch: https://stza.co/+xEVX-1B\n\nShop: https://stza.co/+xEVX-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Giants
<2018-05-14 Mon 20:30-23:30>
:PROPERTIES:
:ID:       xY7drUGFekbnRBifZQDzZQ-6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks @ Giants JetHawks @ Giants

Follow on MiLB First Pitch  https //stza.co/+xEVY-A

Shop  https //stza.co/+xEVY-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Giants
END:VALARM
DTSTART:20180515T013000Z
DTEND:20180515T043000Z
UID:xY7drUGFekbnRBifZQDzZQ-6@stanza.co
SUMMARY:JetHawks @ Giants
DESCRIPTION:JetHawks @ Giants\n\nFollow on MiLB First Pitch: https://stza.co/+xEVY-A\n\nShop: https://stza.co/+xEVY-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Rawhide
<2018-05-15 Tue 20:35-23:35>
:PROPERTIES:
:ID:       ugh-Uc7RLEGvaEyQyfWYJvVZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Rawhide JetHawks vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+vf9Z-1y

Shop  https //stza.co/+vf9Z-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Rawhide
END:VALARM
DTSTART:20180516T013500Z
DTEND:20180516T043500Z
UID:ugh-Uc7RLEGvaEyQyfWYJvVZ@stanza.co
SUMMARY:JetHawks vs. Rawhide
DESCRIPTION:JetHawks vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vf9Z-1y\n\nShop: https://stza.co/+vf9Z-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Rawhide
<2018-05-16 Wed 20:35-23:35>
:PROPERTIES:
:ID:       o4tGxJj_bpiJAtkKKc-nIYM4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Rawhide JetHawks vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+vfaa-1v

Shop  https //stza.co/+vfaa-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Rawhide
END:VALARM
DTSTART:20180517T013500Z
DTEND:20180517T043500Z
UID:o4tGxJj_bpiJAtkKKc-nIYM4@stanza.co
SUMMARY:JetHawks vs. Rawhide
DESCRIPTION:JetHawks vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vfaa-1v\n\nShop: https://stza.co/+vfaa-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Rawhide
<2018-05-17 Thu 20:35-23:35>
:PROPERTIES:
:ID:       1Pzo-16DAzSemo3qr79yzc07@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Rawhide JetHawks vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+vfam-3a

Shop  https //stza.co/+vfam-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Rawhide
END:VALARM
DTSTART:20180518T013500Z
DTEND:20180518T043500Z
UID:1Pzo-16DAzSemo3qr79yzc07@stanza.co
SUMMARY:JetHawks vs. Rawhide
DESCRIPTION:JetHawks vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vfam-3a\n\nShop: https://stza.co/+vfam-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ 66ers
<2018-05-18 Fri 21:05>--<2018-05-19 Sat 00:05>
:PROPERTIES:
:ID:       TrTbSUX4NuekotU1RbNnwrgE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ 66ers JetHawks @ 66ers

Follow on MiLB First Pitch  https //stza.co/+y0BW-U

Shop  https //stza.co/+y0BW-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ 66ers
END:VALARM
DTSTART:20180519T020500Z
DTEND:20180519T050500Z
UID:TrTbSUX4NuekotU1RbNnwrgE@stanza.co
SUMMARY:JetHawks @ 66ers
DESCRIPTION:JetHawks @ 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+y0BW-U\n\nShop: https://stza.co/+y0BW-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ 66ers
<2018-05-19 Sat 20:05-23:05>
:PROPERTIES:
:ID:       ScMJQ8dHBHmMocp5jX-fQmsa@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ 66ers JetHawks @ 66ers

Follow on MiLB First Pitch  https //stza.co/+y0BX-1i

Shop  https //stza.co/+y0BX-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ 66ers
END:VALARM
DTSTART:20180520T010500Z
DTEND:20180520T040500Z
UID:ScMJQ8dHBHmMocp5jX-fQmsa@stanza.co
SUMMARY:JetHawks @ 66ers
DESCRIPTION:JetHawks @ 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+y0BX-1i\n\nShop: https://stza.co/+y0BX-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ 66ers
<2018-05-20 Sun 16:05-19:05>
:PROPERTIES:
:ID:       6IEP0y8VrgoxqLoYF2uYY95H@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks @ 66ers JetHawks @ 66ers

Follow on MiLB First Pitch  https //stza.co/+y0BY-1W

Shop  https //stza.co/+y0BY-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ 66ers
END:VALARM
DTSTART:20180520T210500Z
DTEND:20180521T000500Z
UID:6IEP0y8VrgoxqLoYF2uYY95H@stanza.co
SUMMARY:JetHawks @ 66ers
DESCRIPTION:JetHawks @ 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+y0BY-1W\n\nShop: https://stza.co/+y0BY-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Storm
<2018-05-22 Tue 20:00-23:00>
:PROPERTIES:
:ID:       m1x6qEbdGi0Yj7ijzQKDaZO_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Storm JetHawks @ Storm

Follow on MiLB First Pitch  https //stza.co/+xAOu-k

Shop  https //stza.co/+xAOu-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Storm
END:VALARM
DTSTART:20180523T010000Z
DTEND:20180523T040000Z
UID:m1x6qEbdGi0Yj7ijzQKDaZO_@stanza.co
SUMMARY:JetHawks @ Storm
DESCRIPTION:JetHawks @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xAOu-k\n\nShop: https://stza.co/+xAOu-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Storm
<2018-05-23 Wed 20:00-23:00>
:PROPERTIES:
:ID:       Rlelyktqm0H9t0tiWnaFbtfr@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Storm JetHawks @ Storm

Follow on MiLB First Pitch  https //stza.co/+xAOv-2I

Shop  https //stza.co/+xAOv-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Storm
END:VALARM
DTSTART:20180524T010000Z
DTEND:20180524T040000Z
UID:Rlelyktqm0H9t0tiWnaFbtfr@stanza.co
SUMMARY:JetHawks @ Storm
DESCRIPTION:JetHawks @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xAOv-2I\n\nShop: https://stza.co/+xAOv-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Storm
<2018-05-24 Thu 21:00>--<2018-05-25 Fri 00:00>
:PROPERTIES:
:ID:       13YbUy9E8rymVEWzkTEFu_au@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks @ Storm JetHawks @ Storm

Follow on MiLB First Pitch  https //stza.co/+xAOw-39

Shop  https //stza.co/+xAOw-2S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Storm
END:VALARM
DTSTART:20180525T020000Z
DTEND:20180525T050000Z
UID:13YbUy9E8rymVEWzkTEFu_au@stanza.co
SUMMARY:JetHawks @ Storm
DESCRIPTION:JetHawks @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xAOw-39\n\nShop: https://stza.co/+xAOw-2S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Ports
<2018-05-25 Fri 20:35-23:35>
:PROPERTIES:
:ID:       5BzN3Clbchi6fh7xRea7lRjo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Ports JetHawks vs. Ports

Follow on MiLB First Pitch  https //stza.co/+vfaz-N

Shop  https //stza.co/+vfaz-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Ports
END:VALARM
DTSTART:20180526T013500Z
DTEND:20180526T043500Z
UID:5BzN3Clbchi6fh7xRea7lRjo@stanza.co
SUMMARY:JetHawks vs. Ports
DESCRIPTION:JetHawks vs. Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vfaz-N\n\nShop: https://stza.co/+vfaz-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Ports
<2018-05-26 Sat 20:05-23:05>
:PROPERTIES:
:ID:       Ux77U-FzPhz76RO-rnq4FYjV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Ports JetHawks vs. Ports

Follow on MiLB First Pitch  https //stza.co/+vfaZ-28

Shop  https //stza.co/+vfaZ-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Ports
END:VALARM
DTSTART:20180527T010500Z
DTEND:20180527T040500Z
UID:Ux77U-FzPhz76RO-rnq4FYjV@stanza.co
SUMMARY:JetHawks vs. Ports
DESCRIPTION:JetHawks vs. Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vfaZ-28\n\nShop: https://stza.co/+vfaZ-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Ports
<2018-05-27 Sun>--<2018-05-26 Sat>
:PROPERTIES:
:ID:       ogzbHaJk_rUza29UCNHLaOxE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Ports JetHawks vs. Ports

Follow on MiLB First Pitch  https //stza.co/+vfbr-1_

Shop  https //stza.co/+vfbr-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Ports
END:VALARM
DTSTART;VALUE=DATE:20180527
DTEND;VALUE=DATE:20180527
UID:ogzbHaJk_rUza29UCNHLaOxE@stanza.co
SUMMARY:JetHawks vs. Ports
DESCRIPTION:JetHawks vs. Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vfbr-1_\n\nShop: https://stza.co/+vfbr-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. 66ers
<2018-05-28 Mon 16:05-19:05>
:PROPERTIES:
:ID:       spOO9EbnA6Dy1rjGYRNSJwe9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. 66ers JetHawks vs. 66ers

Follow on MiLB First Pitch  https //stza.co/+vfbO-1X

Shop  https //stza.co/+vfbO-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. 66ers
END:VALARM
DTSTART:20180528T210500Z
DTEND:20180529T000500Z
UID:spOO9EbnA6Dy1rjGYRNSJwe9@stanza.co
SUMMARY:JetHawks vs. 66ers
DESCRIPTION:JetHawks vs. 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+vfbO-1X\n\nShop: https://stza.co/+vfbO-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. 66ers
<2018-05-29 Tue 20:35-23:35>
:PROPERTIES:
:ID:       tYuAilN5vFWENAfH9XZT21kj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. 66ers JetHawks vs. 66ers

Follow on MiLB First Pitch  https //stza.co/+vfbV-2x

Shop  https //stza.co/+vfbV-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. 66ers
END:VALARM
DTSTART:20180530T013500Z
DTEND:20180530T043500Z
UID:tYuAilN5vFWENAfH9XZT21kj@stanza.co
SUMMARY:JetHawks vs. 66ers
DESCRIPTION:JetHawks vs. 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+vfbV-2x\n\nShop: https://stza.co/+vfbV-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. 66ers
<2018-05-30 Wed 20:35-23:35>
:PROPERTIES:
:ID:       gU5WMrWpwMkdbr2u24FPokCT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks vs. 66ers JetHawks vs. 66ers

Follow on MiLB First Pitch  https //stza.co/+vfc0-1I

Shop  https //stza.co/+vfc0-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. 66ers
END:VALARM
DTSTART:20180531T013500Z
DTEND:20180531T043500Z
UID:gU5WMrWpwMkdbr2u24FPokCT@stanza.co
SUMMARY:JetHawks vs. 66ers
DESCRIPTION:JetHawks vs. 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+vfc0-1I\n\nShop: https://stza.co/+vfc0-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. 66ers
<2018-05-31 Thu 20:35-23:35>
:PROPERTIES:
:ID:       BcnSr2yJoHFXyB292T17CHDC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. 66ers JetHawks vs. 66ers

Follow on MiLB First Pitch  https //stza.co/+vfc7-p

Shop  https //stza.co/+vfc7-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. 66ers
END:VALARM
DTSTART:20180601T013500Z
DTEND:20180601T043500Z
UID:BcnSr2yJoHFXyB292T17CHDC@stanza.co
SUMMARY:JetHawks vs. 66ers
DESCRIPTION:JetHawks vs. 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+vfc7-p\n\nShop: https://stza.co/+vfc7-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Quakes
<2018-06-01 Fri 21:05>--<2018-06-02 Sat 00:05>
:PROPERTIES:
:ID:       ecpwatNbV2VdfVQ6JUkwcQJh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Quakes JetHawks @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xAOI-3q

Shop  https //stza.co/+xAOI-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Quakes
END:VALARM
DTSTART:20180602T020500Z
DTEND:20180602T050500Z
UID:ecpwatNbV2VdfVQ6JUkwcQJh@stanza.co
SUMMARY:JetHawks @ Quakes
DESCRIPTION:JetHawks @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xAOI-3q\n\nShop: https://stza.co/+xAOI-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Quakes
<2018-06-02 Sat 21:05>--<2018-06-03 Sun 00:05>
:PROPERTIES:
:ID:       o-Rf0NTmf7jgMhAn1rS8AWUH@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks @ Quakes JetHawks @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xAOK-18

Shop  https //stza.co/+xAOK-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Quakes
END:VALARM
DTSTART:20180603T020500Z
DTEND:20180603T050500Z
UID:o-Rf0NTmf7jgMhAn1rS8AWUH@stanza.co
SUMMARY:JetHawks @ Quakes
DESCRIPTION:JetHawks @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xAOK-18\n\nShop: https://stza.co/+xAOK-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Quakes
<2018-06-03 Sun 16:05-19:05>
:PROPERTIES:
:ID:       ceh1FCByRya2i0GB4H10wT0c@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Quakes JetHawks @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xAOM-3p

Shop  https //stza.co/+xAOM-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Quakes
END:VALARM
DTSTART:20180603T210500Z
DTEND:20180604T000500Z
UID:ceh1FCByRya2i0GB4H10wT0c@stanza.co
SUMMARY:JetHawks @ Quakes
DESCRIPTION:JetHawks @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xAOM-3p\n\nShop: https://stza.co/+xAOM-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Quakes
<2018-06-05 Tue 20:35-23:35>
:PROPERTIES:
:ID:       u2z0wplBCUZ-fXOZDqw9Lfz-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Quakes JetHawks vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+vfcj-2_

Shop  https //stza.co/+vfcj-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Quakes
END:VALARM
DTSTART:20180606T013500Z
DTEND:20180606T043500Z
UID:u2z0wplBCUZ-fXOZDqw9Lfz-@stanza.co
SUMMARY:JetHawks vs. Quakes
DESCRIPTION:JetHawks vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+vfcj-2_\n\nShop: https://stza.co/+vfcj-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Quakes
<2018-06-06 Wed 20:35-23:35>
:PROPERTIES:
:ID:       M5QYC-CROFerZ_liK6t_CgRM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Quakes JetHawks vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+vfcw-2G

Shop  https //stza.co/+vfcw-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Quakes
END:VALARM
DTSTART:20180607T013500Z
DTEND:20180607T043500Z
UID:M5QYC-CROFerZ_liK6t_CgRM@stanza.co
SUMMARY:JetHawks vs. Quakes
DESCRIPTION:JetHawks vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+vfcw-2G\n\nShop: https://stza.co/+vfcw-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Quakes
<2018-06-07 Thu 20:35-23:35>
:PROPERTIES:
:ID:       bEjIjC8XfYnAxt1j-lhOMDjd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Quakes JetHawks vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+vfcC-2S

Shop  https //stza.co/+vfcC-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Quakes
END:VALARM
DTSTART:20180608T013500Z
DTEND:20180608T043500Z
UID:bEjIjC8XfYnAxt1j-lhOMDjd@stanza.co
SUMMARY:JetHawks vs. Quakes
DESCRIPTION:JetHawks vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+vfcC-2S\n\nShop: https://stza.co/+vfcC-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Storm
<2018-06-08 Fri 20:35-23:35>
:PROPERTIES:
:ID:       yFjIsrnn16Dc4Qe8R8a103Qb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Storm JetHawks vs. Storm

Follow on MiLB First Pitch  https //stza.co/+vfcO-1g

Shop  https //stza.co/+vfcO-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Storm
END:VALARM
DTSTART:20180609T013500Z
DTEND:20180609T043500Z
UID:yFjIsrnn16Dc4Qe8R8a103Qb@stanza.co
SUMMARY:JetHawks vs. Storm
DESCRIPTION:JetHawks vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+vfcO-1g\n\nShop: https://stza.co/+vfcO-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Storm
<2018-06-09 Sat 20:05-23:05>
:PROPERTIES:
:ID:       Asog2TClXKfwaNHYClUeuBuK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Storm JetHawks vs. Storm

Follow on MiLB First Pitch  https //stza.co/+vfcS-r

Shop  https //stza.co/+vfcS-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Storm
END:VALARM
DTSTART:20180610T010500Z
DTEND:20180610T040500Z
UID:Asog2TClXKfwaNHYClUeuBuK@stanza.co
SUMMARY:JetHawks vs. Storm
DESCRIPTION:JetHawks vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+vfcS-r\n\nShop: https://stza.co/+vfcS-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Storm
<2018-06-10 Sun>--<2018-06-09 Sat>
:PROPERTIES:
:ID:       6sFHRiYS3Tdo5YGCBsRxfRER@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Storm JetHawks vs. Storm

Follow on MiLB First Pitch  https //stza.co/+vfcZ-Y

Shop  https //stza.co/+vfcZ-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Storm
END:VALARM
DTSTART;VALUE=DATE:20180610
DTEND;VALUE=DATE:20180610
UID:6sFHRiYS3Tdo5YGCBsRxfRER@stanza.co
SUMMARY:JetHawks vs. Storm
DESCRIPTION:JetHawks vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+vfcZ-Y\n\nShop: https://stza.co/+vfcZ-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ 66ers
<2018-06-11 Mon 21:05>--<2018-06-12 Tue 00:05>
:PROPERTIES:
:ID:       8MzukC096uEHDYgp5EUx0Awf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ 66ers JetHawks @ 66ers

Follow on MiLB First Pitch  https //stza.co/+y0BZ-2F

Shop  https //stza.co/+y0BZ-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ 66ers
END:VALARM
DTSTART:20180612T020500Z
DTEND:20180612T050500Z
UID:8MzukC096uEHDYgp5EUx0Awf@stanza.co
SUMMARY:JetHawks @ 66ers
DESCRIPTION:JetHawks @ 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+y0BZ-2F\n\nShop: https://stza.co/+y0BZ-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ 66ers
<2018-06-12 Tue 21:05>--<2018-06-13 Wed 00:05>
:PROPERTIES:
:ID:       ebR1ua4nbitebRhalQprQu7s@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks @ 66ers JetHawks @ 66ers

Follow on MiLB First Pitch  https //stza.co/+y0B_-r

Shop  https //stza.co/+y0B_-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ 66ers
END:VALARM
DTSTART:20180613T020500Z
DTEND:20180613T050500Z
UID:ebR1ua4nbitebRhalQprQu7s@stanza.co
SUMMARY:JetHawks @ 66ers
DESCRIPTION:JetHawks @ 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+y0B_-r\n\nShop: https://stza.co/+y0B_-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ 66ers
<2018-06-13 Wed 21:05>--<2018-06-14 Thu 00:05>
:PROPERTIES:
:ID:       okk6sztiS6Hb1Upkp9b6hkO3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ 66ers JetHawks @ 66ers

Follow on MiLB First Pitch  https //stza.co/+y0B$-1z

Shop  https //stza.co/+y0B$-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ 66ers
END:VALARM
DTSTART:20180614T020500Z
DTEND:20180614T050500Z
UID:okk6sztiS6Hb1Upkp9b6hkO3@stanza.co
SUMMARY:JetHawks @ 66ers
DESCRIPTION:JetHawks @ 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+y0B$-1z\n\nShop: https://stza.co/+y0B$-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ 66ers
<2018-06-14 Thu 21:05>--<2018-06-15 Fri 00:05>
:PROPERTIES:
:ID:       5R67KX95iaVdxuQftcbokTBY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ 66ers JetHawks @ 66ers

Follow on MiLB First Pitch  https //stza.co/+y0C0-x

Shop  https //stza.co/+y0C0-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ 66ers
END:VALARM
DTSTART:20180615T020500Z
DTEND:20180615T050500Z
UID:5R67KX95iaVdxuQftcbokTBY@stanza.co
SUMMARY:JetHawks @ 66ers
DESCRIPTION:JetHawks @ 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+y0C0-x\n\nShop: https://stza.co/+y0C0-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Storm
<2018-06-15 Fri 21:00>--<2018-06-16 Sat 00:00>
:PROPERTIES:
:ID:       2Y8eDwCPa6tl0uBZuXAWSgP_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks @ Storm JetHawks @ Storm

Follow on MiLB First Pitch  https //stza.co/+xAOx-1l

Shop  https //stza.co/+xAOx-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Storm
END:VALARM
DTSTART:20180616T020000Z
DTEND:20180616T050000Z
UID:2Y8eDwCPa6tl0uBZuXAWSgP_@stanza.co
SUMMARY:JetHawks @ Storm
DESCRIPTION:JetHawks @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xAOx-1l\n\nShop: https://stza.co/+xAOx-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Storm
<2018-06-16 Sat 20:00-23:00>
:PROPERTIES:
:ID:       8rt_vThkD9I7xVvLRR2QoZ2I@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Storm JetHawks @ Storm

Follow on MiLB First Pitch  https //stza.co/+xAOy-1f

Shop  https //stza.co/+xAOy-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Storm
END:VALARM
DTSTART:20180617T010000Z
DTEND:20180617T040000Z
UID:8rt_vThkD9I7xVvLRR2QoZ2I@stanza.co
SUMMARY:JetHawks @ Storm
DESCRIPTION:JetHawks @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xAOy-1f\n\nShop: https://stza.co/+xAOy-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Storm
<2018-06-17 Sun>--<2018-06-16 Sat>
:PROPERTIES:
:ID:       Fye4V-TenHwOd8RhEnigna_h@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Storm JetHawks @ Storm

Follow on MiLB First Pitch  https //stza.co/+vf6s-1i

Shop  https //stza.co/+vf6s-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Storm
END:VALARM
DTSTART;VALUE=DATE:20180617
DTEND;VALUE=DATE:20180617
UID:Fye4V-TenHwOd8RhEnigna_h@stanza.co
SUMMARY:JetHawks @ Storm
DESCRIPTION:JetHawks @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+vf6s-1i\n\nShop: https://stza.co/+vf6s-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. 66ers
<2018-06-21 Thu 20:35-23:35>
:PROPERTIES:
:ID:       5GO_sFeCK_9VgbGhRHAei7Gi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks vs. 66ers JetHawks vs. 66ers

Follow on MiLB First Pitch  https //stza.co/+vfd6-2d

Shop  https //stza.co/+vfd6-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. 66ers
END:VALARM
DTSTART:20180622T013500Z
DTEND:20180622T043500Z
UID:5GO_sFeCK_9VgbGhRHAei7Gi@stanza.co
SUMMARY:JetHawks vs. 66ers
DESCRIPTION:JetHawks vs. 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+vfd6-2d\n\nShop: https://stza.co/+vfd6-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. 66ers
<2018-06-22 Fri 20:35-23:35>
:PROPERTIES:
:ID:       1EzwS9OXdTIHFyt1Y3_AUSmn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. 66ers JetHawks vs. 66ers

Follow on MiLB First Pitch  https //stza.co/+vfdd-3F

Shop  https //stza.co/+vfdd-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. 66ers
END:VALARM
DTSTART:20180623T013500Z
DTEND:20180623T043500Z
UID:1EzwS9OXdTIHFyt1Y3_AUSmn@stanza.co
SUMMARY:JetHawks vs. 66ers
DESCRIPTION:JetHawks vs. 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+vfdd-3F\n\nShop: https://stza.co/+vfdd-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. 66ers
<2018-06-23 Sat 20:05-23:05>
:PROPERTIES:
:ID:       4xQHROTaN_aKVgsrpnRlRYii@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. 66ers JetHawks vs. 66ers

Follow on MiLB First Pitch  https //stza.co/+vfdl-27

Shop  https //stza.co/+vfdl-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. 66ers
END:VALARM
DTSTART:20180624T010500Z
DTEND:20180624T040500Z
UID:4xQHROTaN_aKVgsrpnRlRYii@stanza.co
SUMMARY:JetHawks vs. 66ers
DESCRIPTION:JetHawks vs. 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+vfdl-27\n\nShop: https://stza.co/+vfdl-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. 66ers
<2018-06-24 Sun>--<2018-06-23 Sat>
:PROPERTIES:
:ID:       E3Gvv3d8U58RHJuxxZQuvfHQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks vs. 66ers JetHawks vs. 66ers

Follow on MiLB First Pitch  https //stza.co/+vfdu-39

Shop  https //stza.co/+vfdu-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. 66ers
END:VALARM
DTSTART;VALUE=DATE:20180624
DTEND;VALUE=DATE:20180624
UID:E3Gvv3d8U58RHJuxxZQuvfHQ@stanza.co
SUMMARY:JetHawks vs. 66ers
DESCRIPTION:JetHawks vs. 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+vfdu-39\n\nShop: https://stza.co/+vfdu-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Nuts
<2018-06-25 Mon 21:05>--<2018-06-26 Tue 00:05>
:PROPERTIES:
:ID:       QkopOW6KuGpxTqep-TlFZMDU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Nuts JetHawks @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xAOC-1T

Shop  https //stza.co/+xAOC-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Nuts
END:VALARM
DTSTART:20180626T020500Z
DTEND:20180626T050500Z
UID:QkopOW6KuGpxTqep-TlFZMDU@stanza.co
SUMMARY:JetHawks @ Nuts
DESCRIPTION:JetHawks @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xAOC-1T\n\nShop: https://stza.co/+xAOC-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Nuts
<2018-06-26 Tue 21:05>--<2018-06-27 Wed 00:05>
:PROPERTIES:
:ID:       i72SMQAgKtKNJ4n2mHFxR3Dq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Nuts JetHawks @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xAOE-1F

Shop  https //stza.co/+xAOE-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Nuts
END:VALARM
DTSTART:20180627T020500Z
DTEND:20180627T050500Z
UID:i72SMQAgKtKNJ4n2mHFxR3Dq@stanza.co
SUMMARY:JetHawks @ Nuts
DESCRIPTION:JetHawks @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xAOE-1F\n\nShop: https://stza.co/+xAOE-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Nuts
<2018-06-27 Wed 21:05>--<2018-06-28 Thu 00:05>
:PROPERTIES:
:ID:       F2z1IH7IPePBpMPmpITaM5wI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks @ Nuts JetHawks @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xAOF-21

Shop  https //stza.co/+xAOF-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Nuts
END:VALARM
DTSTART:20180628T020500Z
DTEND:20180628T050500Z
UID:F2z1IH7IPePBpMPmpITaM5wI@stanza.co
SUMMARY:JetHawks @ Nuts
DESCRIPTION:JetHawks @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xAOF-21\n\nShop: https://stza.co/+xAOF-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Nuts
<2018-06-28 Thu 21:05>--<2018-06-29 Fri 00:05>
:PROPERTIES:
:ID:       YRTnJE-ZbXw-T32TVlDQfR4M@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Nuts JetHawks @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xAOG-3s

Shop  https //stza.co/+xAOG-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Nuts
END:VALARM
DTSTART:20180629T020500Z
DTEND:20180629T050500Z
UID:YRTnJE-ZbXw-T32TVlDQfR4M@stanza.co
SUMMARY:JetHawks @ Nuts
DESCRIPTION:JetHawks @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xAOG-3s\n\nShop: https://stza.co/+xAOG-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Ports
<2018-06-29 Fri 21:10>--<2018-06-30 Sat 00:10>
:PROPERTIES:
:ID:       atcUJ8NoqW5XNRuh8RLsr0yM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Ports JetHawks @ Ports

Follow on MiLB First Pitch  https //stza.co/+vLZt-1n

Shop  https //stza.co/+vLZt-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Ports
END:VALARM
DTSTART:20180630T021000Z
DTEND:20180630T051000Z
UID:atcUJ8NoqW5XNRuh8RLsr0yM@stanza.co
SUMMARY:JetHawks @ Ports
DESCRIPTION:JetHawks @ Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vLZt-1n\n\nShop: https://stza.co/+vLZt-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Ports
<2018-06-30 Sat 21:10>--<2018-07-01 Sun 00:10>
:PROPERTIES:
:ID:       Y1fVDkVD5y6KD-a2GzVQFcFZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks @ Ports JetHawks @ Ports

Follow on MiLB First Pitch  https //stza.co/+vLZu-2J

Shop  https //stza.co/+vLZu-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Ports
END:VALARM
DTSTART:20180701T021000Z
DTEND:20180701T051000Z
UID:Y1fVDkVD5y6KD-a2GzVQFcFZ@stanza.co
SUMMARY:JetHawks @ Ports
DESCRIPTION:JetHawks @ Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vLZu-2J\n\nShop: https://stza.co/+vLZu-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Ports
<2018-07-01 Sun 20:10-23:10>
:PROPERTIES:
:ID:       k-A_ekBhOG2gJV-7thmI1zQ6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Ports JetHawks @ Ports

Follow on MiLB First Pitch  https //stza.co/+vLZv-3_

Shop  https //stza.co/+vLZv-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Ports
END:VALARM
DTSTART:20180702T011000Z
DTEND:20180702T041000Z
UID:k-A_ekBhOG2gJV-7thmI1zQ6@stanza.co
SUMMARY:JetHawks @ Ports
DESCRIPTION:JetHawks @ Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vLZv-3_\n\nShop: https://stza.co/+vLZv-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Ports
<2018-07-02 Mon 21:10>--<2018-07-03 Tue 00:10>
:PROPERTIES:
:ID:       FOU8YHRacLkXAT6bKqBQRRB5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Ports JetHawks @ Ports

Follow on MiLB First Pitch  https //stza.co/+vLZw-2_

Shop  https //stza.co/+vLZw-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Ports
END:VALARM
DTSTART:20180703T021000Z
DTEND:20180703T051000Z
UID:FOU8YHRacLkXAT6bKqBQRRB5@stanza.co
SUMMARY:JetHawks @ Ports
DESCRIPTION:JetHawks @ Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vLZw-2_\n\nShop: https://stza.co/+vLZw-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Ports
<2018-07-03 Tue 20:30-23:30>
:PROPERTIES:
:ID:       aHV-7kdoJLzOxCPMdVJJRhHu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks @ Ports JetHawks @ Ports

Follow on MiLB First Pitch  https //stza.co/+vLZx-1s

Shop  https //stza.co/+vLZx-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Ports
END:VALARM
DTSTART:20180704T013000Z
DTEND:20180704T043000Z
UID:aHV-7kdoJLzOxCPMdVJJRhHu@stanza.co
SUMMARY:JetHawks @ Ports
DESCRIPTION:JetHawks @ Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vLZx-1s\n\nShop: https://stza.co/+vLZx-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Nuts
<2018-07-04 Wed 20:35-23:35>
:PROPERTIES:
:ID:       sZvSGK_ifBVvfSTP9juXnpTr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Nuts JetHawks vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+vfdD-1g

Shop  https //stza.co/+vfdD-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Nuts
END:VALARM
DTSTART:20180705T013500Z
DTEND:20180705T043500Z
UID:sZvSGK_ifBVvfSTP9juXnpTr@stanza.co
SUMMARY:JetHawks vs. Nuts
DESCRIPTION:JetHawks vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+vfdD-1g\n\nShop: https://stza.co/+vfdD-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Nuts
<2018-07-05 Thu 20:35-23:35>
:PROPERTIES:
:ID:       f4vtCV1lqKYNa8CZKcJM6OcM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Nuts JetHawks vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+vfe3-3m

Shop  https //stza.co/+vfe3-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Nuts
END:VALARM
DTSTART:20180706T013500Z
DTEND:20180706T043500Z
UID:f4vtCV1lqKYNa8CZKcJM6OcM@stanza.co
SUMMARY:JetHawks vs. Nuts
DESCRIPTION:JetHawks vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+vfe3-3m\n\nShop: https://stza.co/+vfe3-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Nuts
<2018-07-06 Fri 20:35-23:35>
:PROPERTIES:
:ID:       kyiAFHR8lV_8J2F-PNzDdjFQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Nuts JetHawks vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+vfez-o

Shop  https //stza.co/+vfez-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Nuts
END:VALARM
DTSTART:20180707T013500Z
DTEND:20180707T043500Z
UID:kyiAFHR8lV_8J2F-PNzDdjFQ@stanza.co
SUMMARY:JetHawks vs. Nuts
DESCRIPTION:JetHawks vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+vfez-o\n\nShop: https://stza.co/+vfez-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Nuts
<2018-07-07 Sat 20:05-23:05>
:PROPERTIES:
:ID:       9E5yCIF9XoaO667EtORAQSu1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Nuts JetHawks vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+vfe$-2H

Shop  https //stza.co/+vfe$-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Nuts
END:VALARM
DTSTART:20180708T010500Z
DTEND:20180708T040500Z
UID:9E5yCIF9XoaO667EtORAQSu1@stanza.co
SUMMARY:JetHawks vs. Nuts
DESCRIPTION:JetHawks vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+vfe$-2H\n\nShop: https://stza.co/+vfe$-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Nuts
<2018-07-08 Sun>--<2018-07-07 Sat>
:PROPERTIES:
:ID:       pRG4zkrILbsOU7r1uYld5N9o@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Nuts JetHawks vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+vffe-2S

Shop  https //stza.co/+vffe-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Nuts
END:VALARM
DTSTART;VALUE=DATE:20180708
DTEND;VALUE=DATE:20180708
UID:pRG4zkrILbsOU7r1uYld5N9o@stanza.co
SUMMARY:JetHawks vs. Nuts
DESCRIPTION:JetHawks vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+vffe-2S\n\nShop: https://stza.co/+vffe-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Quakes
<2018-07-09 Mon 21:05>--<2018-07-10 Tue 00:05>
:PROPERTIES:
:ID:       xyL1szOMc706PAplUdA45_NQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks @ Quakes JetHawks @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xAON-5

Shop  https //stza.co/+xAON-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Quakes
END:VALARM
DTSTART:20180710T020500Z
DTEND:20180710T050500Z
UID:xyL1szOMc706PAplUdA45_NQ@stanza.co
SUMMARY:JetHawks @ Quakes
DESCRIPTION:JetHawks @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xAON-5\n\nShop: https://stza.co/+xAON-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Quakes
<2018-07-10 Tue 21:05>--<2018-07-11 Wed 00:05>
:PROPERTIES:
:ID:       HqdBM4osBCphUcj5wS3jkIn0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Quakes JetHawks @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xAOO-3o

Shop  https //stza.co/+xAOO-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Quakes
END:VALARM
DTSTART:20180711T020500Z
DTEND:20180711T050500Z
UID:HqdBM4osBCphUcj5wS3jkIn0@stanza.co
SUMMARY:JetHawks @ Quakes
DESCRIPTION:JetHawks @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xAOO-3o\n\nShop: https://stza.co/+xAOO-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Quakes
<2018-07-11 Wed 21:05>--<2018-07-12 Thu 00:05>
:PROPERTIES:
:ID:       Avw84RRetHd2bkxNrX1Mfh3P@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Quakes JetHawks @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xAOP-2P

Shop  https //stza.co/+xAOP-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Quakes
END:VALARM
DTSTART:20180712T020500Z
DTEND:20180712T050500Z
UID:Avw84RRetHd2bkxNrX1Mfh3P@stanza.co
SUMMARY:JetHawks @ Quakes
DESCRIPTION:JetHawks @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xAOP-2P\n\nShop: https://stza.co/+xAOP-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Quakes
<2018-07-12 Thu 21:05>--<2018-07-13 Fri 00:05>
:PROPERTIES:
:ID:       M5RgYZf4-XlpZFK49-hNuuHm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks @ Quakes JetHawks @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xAOQ-1q

Shop  https //stza.co/+xAOQ-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Quakes
END:VALARM
DTSTART:20180713T020500Z
DTEND:20180713T050500Z
UID:M5RgYZf4-XlpZFK49-hNuuHm@stanza.co
SUMMARY:JetHawks @ Quakes
DESCRIPTION:JetHawks @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xAOQ-1q\n\nShop: https://stza.co/+xAOQ-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Storm
<2018-07-13 Fri 20:35-23:35>
:PROPERTIES:
:ID:       DYK0Gm54jdqCsz6JeNfGZeq3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Storm JetHawks vs. Storm

Follow on MiLB First Pitch  https //stza.co/+vffx-3v

Shop  https //stza.co/+vffx-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Storm
END:VALARM
DTSTART:20180714T013500Z
DTEND:20180714T043500Z
UID:DYK0Gm54jdqCsz6JeNfGZeq3@stanza.co
SUMMARY:JetHawks vs. Storm
DESCRIPTION:JetHawks vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+vffx-3v\n\nShop: https://stza.co/+vffx-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Storm
<2018-07-14 Sat 20:05-23:05>
:PROPERTIES:
:ID:       wwXHJpAs5cdz9u9vQNWPXufK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Storm JetHawks vs. Storm

Follow on MiLB First Pitch  https //stza.co/+vffA-22

Shop  https //stza.co/+vffA-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Storm
END:VALARM
DTSTART:20180715T010500Z
DTEND:20180715T040500Z
UID:wwXHJpAs5cdz9u9vQNWPXufK@stanza.co
SUMMARY:JetHawks vs. Storm
DESCRIPTION:JetHawks vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+vffA-22\n\nShop: https://stza.co/+vffA-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Storm
<2018-07-15 Sun>--<2018-07-14 Sat>
:PROPERTIES:
:ID:       aBGpsPdYaerEkILL8IiuMC0Z@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Storm JetHawks vs. Storm

Follow on MiLB First Pitch  https //stza.co/+vffJ-2N

Shop  https //stza.co/+vffJ-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Storm
END:VALARM
DTSTART;VALUE=DATE:20180715
DTEND;VALUE=DATE:20180715
UID:aBGpsPdYaerEkILL8IiuMC0Z@stanza.co
SUMMARY:JetHawks vs. Storm
DESCRIPTION:JetHawks vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+vffJ-2N\n\nShop: https://stza.co/+vffJ-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Storm
<2018-07-16 Mon 20:35-23:35>
:PROPERTIES:
:ID:       HzwBe19jkultrYpYkSsig18H@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Storm JetHawks vs. Storm

Follow on MiLB First Pitch  https //stza.co/+vffO-3Y

Shop  https //stza.co/+vffO-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Storm
END:VALARM
DTSTART:20180717T013500Z
DTEND:20180717T043500Z
UID:HzwBe19jkultrYpYkSsig18H@stanza.co
SUMMARY:JetHawks vs. Storm
DESCRIPTION:JetHawks vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+vffO-3Y\n\nShop: https://stza.co/+vffO-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Ports
<2018-07-18 Wed 21:10>--<2018-07-19 Thu 00:10>
:PROPERTIES:
:ID:       Yv_6WzujYoH0CNKxHXEBQpVl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Ports JetHawks @ Ports

Follow on MiLB First Pitch  https //stza.co/+vLZy-2$

Shop  https //stza.co/+vLZy-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Ports
END:VALARM
DTSTART:20180719T021000Z
DTEND:20180719T051000Z
UID:Yv_6WzujYoH0CNKxHXEBQpVl@stanza.co
SUMMARY:JetHawks @ Ports
DESCRIPTION:JetHawks @ Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vLZy-2$\n\nShop: https://stza.co/+vLZy-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Ports
<2018-07-19 Thu 21:10>--<2018-07-20 Fri 00:10>
:PROPERTIES:
:ID:       dAL0FzFHeFl7zwZI_joii5jQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks @ Ports JetHawks @ Ports

Follow on MiLB First Pitch  https //stza.co/+vLZz-31

Shop  https //stza.co/+vLZz-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Ports
END:VALARM
DTSTART:20180720T021000Z
DTEND:20180720T051000Z
UID:dAL0FzFHeFl7zwZI_joii5jQ@stanza.co
SUMMARY:JetHawks @ Ports
DESCRIPTION:JetHawks @ Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vLZz-31\n\nShop: https://stza.co/+vLZz-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Ports
<2018-07-20 Fri 21:10>--<2018-07-21 Sat 00:10>
:PROPERTIES:
:ID:       ddbcne1FDcgJdTZVpPxzqpoR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Ports JetHawks @ Ports

Follow on MiLB First Pitch  https //stza.co/+vLZA-P

Shop  https //stza.co/+vLZA-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Ports
END:VALARM
DTSTART:20180721T021000Z
DTEND:20180721T051000Z
UID:ddbcne1FDcgJdTZVpPxzqpoR@stanza.co
SUMMARY:JetHawks @ Ports
DESCRIPTION:JetHawks @ Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vLZA-P\n\nShop: https://stza.co/+vLZA-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Rawhide
<2018-07-21 Sat>--<2018-07-20 Fri>
:PROPERTIES:
:ID:       PQdiNgBs4BX_lOyxPPFxPjVR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Rawhide JetHawks @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vLZE-1v

Shop  https //stza.co/+vLZE-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180721
DTEND;VALUE=DATE:20180721
UID:PQdiNgBs4BX_lOyxPPFxPjVR@stanza.co
SUMMARY:JetHawks @ Rawhide
DESCRIPTION:JetHawks @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vLZE-1v\n\nShop: https://stza.co/+vLZE-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Rawhide
<2018-07-22 Sun>--<2018-07-21 Sat>
:PROPERTIES:
:ID:       1oLFufDzSq41O0jgkCiX56JO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks @ Rawhide JetHawks @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vLZF-3A

Shop  https //stza.co/+vLZF-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180722
DTEND;VALUE=DATE:20180722
UID:1oLFufDzSq41O0jgkCiX56JO@stanza.co
SUMMARY:JetHawks @ Rawhide
DESCRIPTION:JetHawks @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vLZF-3A\n\nShop: https://stza.co/+vLZF-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Rawhide
<2018-07-23 Mon>--<2018-07-22 Sun>
:PROPERTIES:
:ID:       71Ba_XMYgVEWY77czv-_oNNd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Rawhide JetHawks @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vLZG-2p

Shop  https //stza.co/+vLZG-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180723
DTEND;VALUE=DATE:20180723
UID:71Ba_XMYgVEWY77czv-_oNNd@stanza.co
SUMMARY:JetHawks @ Rawhide
DESCRIPTION:JetHawks @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vLZG-2p\n\nShop: https://stza.co/+vLZG-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Storm
<2018-07-24 Tue 20:35-23:35>
:PROPERTIES:
:ID:       Sb8DYpRZzlMczGYngbawKykj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Storm JetHawks vs. Storm

Follow on MiLB First Pitch  https //stza.co/+vffS-3K

Shop  https //stza.co/+vffS-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Storm
END:VALARM
DTSTART:20180725T013500Z
DTEND:20180725T043500Z
UID:Sb8DYpRZzlMczGYngbawKykj@stanza.co
SUMMARY:JetHawks vs. Storm
DESCRIPTION:JetHawks vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+vffS-3K\n\nShop: https://stza.co/+vffS-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Storm
<2018-07-25 Wed 20:35-23:35>
:PROPERTIES:
:ID:       1bSL_MRzoXnXUk_ZMOaZp6g_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Storm JetHawks vs. Storm

Follow on MiLB First Pitch  https //stza.co/+vff_-1U

Shop  https //stza.co/+vff_-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Storm
END:VALARM
DTSTART:20180726T013500Z
DTEND:20180726T043500Z
UID:1bSL_MRzoXnXUk_ZMOaZp6g_@stanza.co
SUMMARY:JetHawks vs. Storm
DESCRIPTION:JetHawks vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+vff_-1U\n\nShop: https://stza.co/+vff_-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Storm
<2018-07-26 Thu 20:35-23:35>
:PROPERTIES:
:ID:       1ziMkQujBwYcl-p6_vYqEysJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Storm JetHawks vs. Storm

Follow on MiLB First Pitch  https //stza.co/+vfg2-2B

Shop  https //stza.co/+vfg2-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Storm
END:VALARM
DTSTART:20180727T013500Z
DTEND:20180727T043500Z
UID:1ziMkQujBwYcl-p6_vYqEysJ@stanza.co
SUMMARY:JetHawks vs. Storm
DESCRIPTION:JetHawks vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+vfg2-2B\n\nShop: https://stza.co/+vfg2-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Rawhide
<2018-07-27 Fri 20:35-23:35>
:PROPERTIES:
:ID:       Dgmk5HP-GGqzOPm9AqKhZmfO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Rawhide JetHawks vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+vfg7-3b

Shop  https //stza.co/+vfg7-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Rawhide
END:VALARM
DTSTART:20180728T013500Z
DTEND:20180728T043500Z
UID:Dgmk5HP-GGqzOPm9AqKhZmfO@stanza.co
SUMMARY:JetHawks vs. Rawhide
DESCRIPTION:JetHawks vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vfg7-3b\n\nShop: https://stza.co/+vfg7-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Rawhide
<2018-07-28 Sat 20:05-23:05>
:PROPERTIES:
:ID:       bshUaAktj08H5jlLqSrtXP8k@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Rawhide JetHawks vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+vfgf-3M

Shop  https //stza.co/+vfgf-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Rawhide
END:VALARM
DTSTART:20180729T010500Z
DTEND:20180729T040500Z
UID:bshUaAktj08H5jlLqSrtXP8k@stanza.co
SUMMARY:JetHawks vs. Rawhide
DESCRIPTION:JetHawks vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vfgf-3M\n\nShop: https://stza.co/+vfgf-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Rawhide
<2018-07-29 Sun>--<2018-07-28 Sat>
:PROPERTIES:
:ID:       Ru1c3bDSUb6W77QwWVAJtTrd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Rawhide JetHawks vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+vfgm-2z

Shop  https //stza.co/+vfgm-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180729
DTEND;VALUE=DATE:20180729
UID:Ru1c3bDSUb6W77QwWVAJtTrd@stanza.co
SUMMARY:JetHawks vs. Rawhide
DESCRIPTION:JetHawks vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vfgm-2z\n\nShop: https://stza.co/+vfgm-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ 66ers
<2018-07-31 Tue 21:05>--<2018-08-01 Wed 00:05>
:PROPERTIES:
:ID:       H4AUZpDfl5HDW9Ne0hbM-3oH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ 66ers JetHawks @ 66ers

Follow on MiLB First Pitch  https //stza.co/+y0C2-38

Shop  https //stza.co/+y0C2-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ 66ers
END:VALARM
DTSTART:20180801T020500Z
DTEND:20180801T050500Z
UID:H4AUZpDfl5HDW9Ne0hbM-3oH@stanza.co
SUMMARY:JetHawks @ 66ers
DESCRIPTION:JetHawks @ 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+y0C2-38\n\nShop: https://stza.co/+y0C2-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ 66ers
<2018-08-01 Wed 21:05>--<2018-08-02 Thu 00:05>
:PROPERTIES:
:ID:       xqsjEwd4VCpaE3vJIDvTbR_m@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks @ 66ers JetHawks @ 66ers

Follow on MiLB First Pitch  https //stza.co/+y0C3-i

Shop  https //stza.co/+y0C3-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ 66ers
END:VALARM
DTSTART:20180802T020500Z
DTEND:20180802T050500Z
UID:xqsjEwd4VCpaE3vJIDvTbR_m@stanza.co
SUMMARY:JetHawks @ 66ers
DESCRIPTION:JetHawks @ 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+y0C3-i\n\nShop: https://stza.co/+y0C3-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ 66ers
<2018-08-02 Thu 21:05>--<2018-08-03 Fri 00:05>
:PROPERTIES:
:ID:       kwvU7uFN5wI2KsSCfF9SfDNN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ 66ers JetHawks @ 66ers

Follow on MiLB First Pitch  https //stza.co/+y0C4-l

Shop  https //stza.co/+y0C4-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ 66ers
END:VALARM
DTSTART:20180803T020500Z
DTEND:20180803T050500Z
UID:kwvU7uFN5wI2KsSCfF9SfDNN@stanza.co
SUMMARY:JetHawks @ 66ers
DESCRIPTION:JetHawks @ 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+y0C4-l\n\nShop: https://stza.co/+y0C4-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Quakes
<2018-08-03 Fri 20:35-23:35>
:PROPERTIES:
:ID:       yOWD5aj0apWYwPTr0gN1ADiM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Quakes JetHawks vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+vfgt-1q

Shop  https //stza.co/+vfgt-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Quakes
END:VALARM
DTSTART:20180804T013500Z
DTEND:20180804T043500Z
UID:yOWD5aj0apWYwPTr0gN1ADiM@stanza.co
SUMMARY:JetHawks vs. Quakes
DESCRIPTION:JetHawks vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+vfgt-1q\n\nShop: https://stza.co/+vfgt-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Quakes
<2018-08-04 Sat 20:05-23:05>
:PROPERTIES:
:ID:       DOmScfWN4AJtjvawaY52c0mP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Quakes JetHawks vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+vfgB-32

Shop  https //stza.co/+vfgB-3_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Quakes
END:VALARM
DTSTART:20180805T010500Z
DTEND:20180805T040500Z
UID:DOmScfWN4AJtjvawaY52c0mP@stanza.co
SUMMARY:JetHawks vs. Quakes
DESCRIPTION:JetHawks vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+vfgB-32\n\nShop: https://stza.co/+vfgB-3_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Quakes
<2018-08-05 Sun>--<2018-08-04 Sat>
:PROPERTIES:
:ID:       gvw2fhKpVE40TrBVyF6DrjMF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Quakes JetHawks vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+vfgM-2g

Shop  https //stza.co/+vfgM-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Quakes
END:VALARM
DTSTART;VALUE=DATE:20180805
DTEND;VALUE=DATE:20180805
UID:gvw2fhKpVE40TrBVyF6DrjMF@stanza.co
SUMMARY:JetHawks vs. Quakes
DESCRIPTION:JetHawks vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+vfgM-2g\n\nShop: https://stza.co/+vfgM-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. 66ers
<2018-08-07 Tue 20:35-23:35>
:PROPERTIES:
:ID:       YoxQsoEyMRbj91Plu_YsIGkC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. 66ers JetHawks vs. 66ers

Follow on MiLB First Pitch  https //stza.co/+vfgT-1q

Shop  https //stza.co/+vfgT-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. 66ers
END:VALARM
DTSTART:20180808T013500Z
DTEND:20180808T043500Z
UID:YoxQsoEyMRbj91Plu_YsIGkC@stanza.co
SUMMARY:JetHawks vs. 66ers
DESCRIPTION:JetHawks vs. 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+vfgT-1q\n\nShop: https://stza.co/+vfgT-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. 66ers
<2018-08-08 Wed 20:35-23:35>
:PROPERTIES:
:ID:       XqMU30Vu-LJCBzbJsKMPIjo_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks vs. 66ers JetHawks vs. 66ers

Follow on MiLB First Pitch  https //stza.co/+vfh0-i

Shop  https //stza.co/+vfh0-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. 66ers
END:VALARM
DTSTART:20180809T013500Z
DTEND:20180809T043500Z
UID:XqMU30Vu-LJCBzbJsKMPIjo_@stanza.co
SUMMARY:JetHawks vs. 66ers
DESCRIPTION:JetHawks vs. 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+vfh0-i\n\nShop: https://stza.co/+vfh0-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. 66ers
<2018-08-09 Thu 20:35-23:35>
:PROPERTIES:
:ID:       9T-7Yp0JgWj_uBpCG5srUDfQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. 66ers JetHawks vs. 66ers

Follow on MiLB First Pitch  https //stza.co/+vfh5-3p

Shop  https //stza.co/+vfh5-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. 66ers
END:VALARM
DTSTART:20180810T013500Z
DTEND:20180810T043500Z
UID:9T-7Yp0JgWj_uBpCG5srUDfQ@stanza.co
SUMMARY:JetHawks vs. 66ers
DESCRIPTION:JetHawks vs. 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+vfh5-3p\n\nShop: https://stza.co/+vfh5-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Quakes
<2018-08-10 Fri 21:05>--<2018-08-11 Sat 00:05>
:PROPERTIES:
:ID:       vmlkJvaG-PLK7Y6gIAaVDCgE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Quakes JetHawks @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xAOS-2C

Shop  https //stza.co/+xAOS-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Quakes
END:VALARM
DTSTART:20180811T020500Z
DTEND:20180811T050500Z
UID:vmlkJvaG-PLK7Y6gIAaVDCgE@stanza.co
SUMMARY:JetHawks @ Quakes
DESCRIPTION:JetHawks @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xAOS-2C\n\nShop: https://stza.co/+xAOS-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Quakes
<2018-08-11 Sat 21:05>--<2018-08-12 Sun 00:05>
:PROPERTIES:
:ID:       iq4nbgSXsvmEthq7-DQIWVlO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks @ Quakes JetHawks @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xAOT-F

Shop  https //stza.co/+xAOT-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Quakes
END:VALARM
DTSTART:20180812T020500Z
DTEND:20180812T050500Z
UID:iq4nbgSXsvmEthq7-DQIWVlO@stanza.co
SUMMARY:JetHawks @ Quakes
DESCRIPTION:JetHawks @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xAOT-F\n\nShop: https://stza.co/+xAOT-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Quakes
<2018-08-12 Sun 16:05-19:05>
:PROPERTIES:
:ID:       lTH02FpdnYBi8Q8BE8_ztRkV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Quakes JetHawks @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xAOU-C

Shop  https //stza.co/+xAOU-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Quakes
END:VALARM
DTSTART:20180812T210500Z
DTEND:20180813T000500Z
UID:lTH02FpdnYBi8Q8BE8_ztRkV@stanza.co
SUMMARY:JetHawks @ Quakes
DESCRIPTION:JetHawks @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xAOU-C\n\nShop: https://stza.co/+xAOU-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Ports
<2018-08-14 Tue 20:35-23:35>
:PROPERTIES:
:ID:       c8rGsg1ppYvERGd2StZyfgam@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Ports JetHawks vs. Ports

Follow on MiLB First Pitch  https //stza.co/+vfhc-20

Shop  https //stza.co/+vfhc-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Ports
END:VALARM
DTSTART:20180815T013500Z
DTEND:20180815T043500Z
UID:c8rGsg1ppYvERGd2StZyfgam@stanza.co
SUMMARY:JetHawks vs. Ports
DESCRIPTION:JetHawks vs. Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vfhc-20\n\nShop: https://stza.co/+vfhc-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Ports
<2018-08-15 Wed 20:35-23:35>
:PROPERTIES:
:ID:       VYn3-VphRnCItVMjQh32CtaJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Ports JetHawks vs. Ports

Follow on MiLB First Pitch  https //stza.co/+vfhs-x

Shop  https //stza.co/+vfhs-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Ports
END:VALARM
DTSTART:20180816T013500Z
DTEND:20180816T043500Z
UID:VYn3-VphRnCItVMjQh32CtaJ@stanza.co
SUMMARY:JetHawks vs. Ports
DESCRIPTION:JetHawks vs. Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vfhs-x\n\nShop: https://stza.co/+vfhs-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Ports
<2018-08-16 Thu 20:35-23:35>
:PROPERTIES:
:ID:       VZXVVvL9AyM3kiAVzXs5MD5G@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Ports JetHawks vs. Ports

Follow on MiLB First Pitch  https //stza.co/+vfhL-36

Shop  https //stza.co/+vfhL-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Ports
END:VALARM
DTSTART:20180817T013500Z
DTEND:20180817T043500Z
UID:VZXVVvL9AyM3kiAVzXs5MD5G@stanza.co
SUMMARY:JetHawks vs. Ports
DESCRIPTION:JetHawks vs. Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vfhL-36\n\nShop: https://stza.co/+vfhL-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Giants
<2018-08-17 Fri 21:00>--<2018-08-18 Sat 00:00>
:PROPERTIES:
:ID:       0Y7AQ0TomoJ__2cAB6RV5BVf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Giants JetHawks @ Giants

Follow on MiLB First Pitch  https //stza.co/+xEVZ-1K

Shop  https //stza.co/+xEVZ-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Giants
END:VALARM
DTSTART:20180818T020000Z
DTEND:20180818T050000Z
UID:0Y7AQ0TomoJ__2cAB6RV5BVf@stanza.co
SUMMARY:JetHawks @ Giants
DESCRIPTION:JetHawks @ Giants\n\nFollow on MiLB First Pitch: https://stza.co/+xEVZ-1K\n\nShop: https://stza.co/+xEVZ-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Giants
<2018-08-18 Sat 19:00-22:00>
:PROPERTIES:
:ID:       QzDxQv_kfJyyjDrCZIEGahR2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks @ Giants JetHawks @ Giants

Follow on MiLB First Pitch  https //stza.co/+xEV_-1o

Shop  https //stza.co/+xEV_-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Giants
END:VALARM
DTSTART:20180819T000000Z
DTEND:20180819T030000Z
UID:QzDxQv_kfJyyjDrCZIEGahR2@stanza.co
SUMMARY:JetHawks @ Giants
DESCRIPTION:JetHawks @ Giants\n\nFollow on MiLB First Pitch: https://stza.co/+xEV_-1o\n\nShop: https://stza.co/+xEV_-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Giants
<2018-08-19 Sun 19:00-22:00>
:PROPERTIES:
:ID:       f3UNUGbqiyPtdfCf1cx6vBym@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Giants JetHawks @ Giants

Follow on MiLB First Pitch  https //stza.co/+xEV$-F

Shop  https //stza.co/+xEV$-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Giants
END:VALARM
DTSTART:20180820T000000Z
DTEND:20180820T030000Z
UID:f3UNUGbqiyPtdfCf1cx6vBym@stanza.co
SUMMARY:JetHawks @ Giants
DESCRIPTION:JetHawks @ Giants\n\nFollow on MiLB First Pitch: https://stza.co/+xEV$-F\n\nShop: https://stza.co/+xEV$-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Quakes
<2018-08-21 Tue 21:05>--<2018-08-22 Wed 00:05>
:PROPERTIES:
:ID:       6EXhE0ptnWApIyVRB75Rr0DB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Quakes JetHawks @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xzQ0-Z

Shop  https //stza.co/+xzQ0-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Quakes
END:VALARM
DTSTART:20180822T020500Z
DTEND:20180822T050500Z
UID:6EXhE0ptnWApIyVRB75Rr0DB@stanza.co
SUMMARY:JetHawks @ Quakes
DESCRIPTION:JetHawks @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xzQ0-Z\n\nShop: https://stza.co/+xzQ0-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Quakes
<2018-08-22 Wed 21:05>--<2018-08-23 Thu 00:05>
:PROPERTIES:
:ID:       KwYV_75ziUWTGE9iC1BSWHWD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks @ Quakes JetHawks @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xzQ1-Q

Shop  https //stza.co/+xzQ1-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Quakes
END:VALARM
DTSTART:20180823T020500Z
DTEND:20180823T050500Z
UID:KwYV_75ziUWTGE9iC1BSWHWD@stanza.co
SUMMARY:JetHawks @ Quakes
DESCRIPTION:JetHawks @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xzQ1-Q\n\nShop: https://stza.co/+xzQ1-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Quakes
<2018-08-23 Thu 21:05>--<2018-08-24 Fri 00:05>
:PROPERTIES:
:ID:       PkffgzvAUe-FLD4AEXsZ0-cI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Quakes JetHawks @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xzQ2-2Y

Shop  https //stza.co/+xzQ2-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Quakes
END:VALARM
DTSTART:20180824T020500Z
DTEND:20180824T050500Z
UID:PkffgzvAUe-FLD4AEXsZ0-cI@stanza.co
SUMMARY:JetHawks @ Quakes
DESCRIPTION:JetHawks @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xzQ2-2Y\n\nShop: https://stza.co/+xzQ2-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Storm
<2018-08-24 Fri 20:35-23:35>
:PROPERTIES:
:ID:       e5xhJPYVQgLaCSs0JkM0ypPd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Storm JetHawks vs. Storm

Follow on MiLB First Pitch  https //stza.co/+vfi3-3q

Shop  https //stza.co/+vfi3-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Storm
END:VALARM
DTSTART:20180825T013500Z
DTEND:20180825T043500Z
UID:e5xhJPYVQgLaCSs0JkM0ypPd@stanza.co
SUMMARY:JetHawks vs. Storm
DESCRIPTION:JetHawks vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+vfi3-3q\n\nShop: https://stza.co/+vfi3-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Storm
<2018-08-25 Sat 20:05-23:05>
:PROPERTIES:
:ID:       O5cBhbu6ztQBYaPC4VpuZr4H@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Storm JetHawks vs. Storm

Follow on MiLB First Pitch  https //stza.co/+vfi9-32

Shop  https //stza.co/+vfi9-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Storm
END:VALARM
DTSTART:20180826T010500Z
DTEND:20180826T040500Z
UID:O5cBhbu6ztQBYaPC4VpuZr4H@stanza.co
SUMMARY:JetHawks vs. Storm
DESCRIPTION:JetHawks vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+vfi9-32\n\nShop: https://stza.co/+vfi9-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Storm
<2018-08-26 Sun>--<2018-08-25 Sat>
:PROPERTIES:
:ID:       VnLRRWGNIb-5nFBzRWJBxbYi@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Storm JetHawks vs. Storm

Follow on MiLB First Pitch  https //stza.co/+vfie-j

Shop  https //stza.co/+vfie-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Storm
END:VALARM
DTSTART;VALUE=DATE:20180826
DTEND;VALUE=DATE:20180826
UID:VnLRRWGNIb-5nFBzRWJBxbYi@stanza.co
SUMMARY:JetHawks vs. Storm
DESCRIPTION:JetHawks vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+vfie-j\n\nShop: https://stza.co/+vfie-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Storm
<2018-08-27 Mon 20:35-23:35>
:PROPERTIES:
:ID:       7yREFiE-IGR_Cgbm0enVKV_R@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Storm JetHawks vs. Storm

Follow on MiLB First Pitch  https //stza.co/+vfin-2a

Shop  https //stza.co/+vfin-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Storm
END:VALARM
DTSTART:20180828T013500Z
DTEND:20180828T043500Z
UID:7yREFiE-IGR_Cgbm0enVKV_R@stanza.co
SUMMARY:JetHawks vs. Storm
DESCRIPTION:JetHawks vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+vfin-2a\n\nShop: https://stza.co/+vfin-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Quakes
<2018-08-28 Tue 20:35-23:35>
:PROPERTIES:
:ID:       2eR9XdiNDI2hO5cSMoLaXXkj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Quakes JetHawks vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+vfiu-3

Shop  https //stza.co/+vfiu-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Quakes
END:VALARM
DTSTART:20180829T013500Z
DTEND:20180829T043500Z
UID:2eR9XdiNDI2hO5cSMoLaXXkj@stanza.co
SUMMARY:JetHawks vs. Quakes
DESCRIPTION:JetHawks vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+vfiu-3\n\nShop: https://stza.co/+vfiu-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Quakes
<2018-08-29 Wed 20:35-23:35>
:PROPERTIES:
:ID:       duiRJMnphbCIyo2F4nRcACt8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Quakes JetHawks vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+vfiE-u

Shop  https //stza.co/+vfiE-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Quakes
END:VALARM
DTSTART:20180830T013500Z
DTEND:20180830T043500Z
UID:duiRJMnphbCIyo2F4nRcACt8@stanza.co
SUMMARY:JetHawks vs. Quakes
DESCRIPTION:JetHawks vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+vfiE-u\n\nShop: https://stza.co/+vfiE-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks vs. Quakes
<2018-08-30 Thu 20:35-23:35>
:PROPERTIES:
:ID:       t7tgZFKSx_dzfIXGnWHV28eV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks vs. Quakes JetHawks vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+vfiQ-1d

Shop  https //stza.co/+vfiQ-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:JetHawks vs. Quakes
END:VALARM
DTSTART:20180831T013500Z
DTEND:20180831T043500Z
UID:t7tgZFKSx_dzfIXGnWHV28eV@stanza.co
SUMMARY:JetHawks vs. Quakes
DESCRIPTION:JetHawks vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+vfiQ-1d\n\nShop: https://stza.co/+vfiQ-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Storm
<2018-08-31 Fri 21:00>--<2018-09-01 Sat 00:00>
:PROPERTIES:
:ID:       bkLwdxESd25ddj4yXpuIhNIe@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks @ Storm JetHawks @ Storm

Follow on MiLB First Pitch  https //stza.co/+xAOz-1g

Shop  https //stza.co/+xAOz-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Storm
END:VALARM
DTSTART:20180901T020000Z
DTEND:20180901T050000Z
UID:bkLwdxESd25ddj4yXpuIhNIe@stanza.co
SUMMARY:JetHawks @ Storm
DESCRIPTION:JetHawks @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xAOz-1g\n\nShop: https://stza.co/+xAOz-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Storm
<2018-09-01 Sat 20:00-23:00>
:PROPERTIES:
:ID:       Mlfzer095lPyOYWAxNOcY8l_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Storm JetHawks @ Storm

Follow on MiLB First Pitch  https //stza.co/+xAOA-e

Shop  https //stza.co/+xAOA-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Storm
END:VALARM
DTSTART:20180902T010000Z
DTEND:20180902T040000Z
UID:Mlfzer095lPyOYWAxNOcY8l_@stanza.co
SUMMARY:JetHawks @ Storm
DESCRIPTION:JetHawks @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xAOA-e\n\nShop: https://stza.co/+xAOA-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Storm
<2018-09-02 Sun>--<2018-09-01 Sat>
:PROPERTIES:
:ID:       e5g9y78jshY2aR_ezuRZeOR-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

JetHawks @ Storm JetHawks @ Storm

Follow on MiLB First Pitch  https //stza.co/+vf6D-29

Shop  https //stza.co/+vf6D-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Storm
END:VALARM
DTSTART;VALUE=DATE:20180902
DTEND;VALUE=DATE:20180902
UID:e5g9y78jshY2aR_ezuRZeOR-@stanza.co
SUMMARY:JetHawks @ Storm
DESCRIPTION:JetHawks @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+vf6D-29\n\nShop: https://stza.co/+vf6D-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
* JetHawks @ Storm
<2018-09-03 Mon 20:00-23:00>
:PROPERTIES:
:ID:       Dv9AVx1r1hv4wGYBsE-7OJUi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

JetHawks @ Storm JetHawks @ Storm

Follow on MiLB First Pitch  https //stza.co/+xAOB-5

Shop  https //stza.co/+xAOB-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:JetHawks @ Storm
END:VALARM
DTSTART:20180904T010000Z
DTEND:20180904T040000Z
UID:Dv9AVx1r1hv4wGYBsE-7OJUi@stanza.co
SUMMARY:JetHawks @ Storm
DESCRIPTION:JetHawks @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xAOB-5\n\nShop: https://stza.co/+xAOB-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144540Z
LAST-MODIFIED:20180213T144540Z
TRANSP:OPAQUE
END:VEVENT
