#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Threshers vs. Blue Jays
<2018-04-05 Thu 18:00-21:00>
:PROPERTIES:
:ID:       ZvKPgjmtKahtKvHYIiGeq1YC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Blue Jays Threshers vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xB9f-1c

Shop  https //stza.co/+xB9f-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Blue Jays
END:VALARM
DTSTART:20180405T230000Z
DTEND:20180406T020000Z
UID:ZvKPgjmtKahtKvHYIiGeq1YC@stanza.co
SUMMARY:Threshers vs. Blue Jays
DESCRIPTION:Threshers vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xB9f-1c\n\nShop: https://stza.co/+xB9f-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Blue Jays
<2018-04-06 Fri 17:15-20:15>
:PROPERTIES:
:ID:       zXtnuw9rtR2Vofk_Mm23oguE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers vs. Blue Jays Threshers vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xB9j-2z

Shop  https //stza.co/+xB9j-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Blue Jays
END:VALARM
DTSTART:20180406T221500Z
DTEND:20180407T011500Z
UID:zXtnuw9rtR2Vofk_Mm23oguE@stanza.co
SUMMARY:Threshers vs. Blue Jays
DESCRIPTION:Threshers vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xB9j-2z\n\nShop: https://stza.co/+xB9j-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Blue Jays
<2018-04-07 Sat 17:30-20:30>
:PROPERTIES:
:ID:       -ZJ8Ty58YYAX1DozXrWApB0z@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Blue Jays Threshers @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+y0Gg-14

Shop  https //stza.co/+y0Gg-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Blue Jays
END:VALARM
DTSTART:20180407T223000Z
DTEND:20180408T013000Z
UID:-ZJ8Ty58YYAX1DozXrWApB0z@stanza.co
SUMMARY:Threshers @ Blue Jays
DESCRIPTION:Threshers @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+y0Gg-14\n\nShop: https://stza.co/+y0Gg-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Blue Jays
<2018-04-08 Sun 12:00-15:00>
:PROPERTIES:
:ID:       OCuLs-7ZR-BT6Dx6iTTgafK1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Blue Jays Threshers @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+y0Gh-B

Shop  https //stza.co/+y0Gh-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Blue Jays
END:VALARM
DTSTART:20180408T170000Z
DTEND:20180408T200000Z
UID:OCuLs-7ZR-BT6Dx6iTTgafK1@stanza.co
SUMMARY:Threshers @ Blue Jays
DESCRIPTION:Threshers @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+y0Gh-B\n\nShop: https://stza.co/+y0Gh-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Hammerheads
<2018-04-09 Mon 18:00-21:00>
:PROPERTIES:
:ID:       RBJbn6sVbeOV7qPDLZ9cPFZY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers vs. Hammerheads Threshers vs. Hammerheads

Follow on MiLB First Pitch  https //stza.co/+xB9n-21

Shop  https //stza.co/+xB9n-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Hammerheads
END:VALARM
DTSTART:20180409T230000Z
DTEND:20180410T020000Z
UID:RBJbn6sVbeOV7qPDLZ9cPFZY@stanza.co
SUMMARY:Threshers vs. Hammerheads
DESCRIPTION:Threshers vs. Hammerheads\n\nFollow on MiLB First Pitch: https://stza.co/+xB9n-21\n\nShop: https://stza.co/+xB9n-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Hammerheads
<2018-04-10 Tue 18:00-21:00>
:PROPERTIES:
:ID:       6OG8J97mf5haGK0hhnIYvCGN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Hammerheads Threshers vs. Hammerheads

Follow on MiLB First Pitch  https //stza.co/+xB9r-1L

Shop  https //stza.co/+xB9r-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Hammerheads
END:VALARM
DTSTART:20180410T230000Z
DTEND:20180411T020000Z
UID:6OG8J97mf5haGK0hhnIYvCGN@stanza.co
SUMMARY:Threshers vs. Hammerheads
DESCRIPTION:Threshers vs. Hammerheads\n\nFollow on MiLB First Pitch: https://stza.co/+xB9r-1L\n\nShop: https://stza.co/+xB9r-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Hammerheads
<2018-04-11 Wed 11:00-14:00>
:PROPERTIES:
:ID:       4-s_3L6T5img3aWrhcm7ybNJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Hammerheads Threshers vs. Hammerheads

Follow on MiLB First Pitch  https //stza.co/+xB9v-O

Shop  https //stza.co/+xB9v-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Hammerheads
END:VALARM
DTSTART:20180411T160000Z
DTEND:20180411T190000Z
UID:4-s_3L6T5img3aWrhcm7ybNJ@stanza.co
SUMMARY:Threshers vs. Hammerheads
DESCRIPTION:Threshers vs. Hammerheads\n\nFollow on MiLB First Pitch: https://stza.co/+xB9v-O\n\nShop: https://stza.co/+xB9v-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Hammerheads
<2018-04-12 Thu 18:00-21:00>
:PROPERTIES:
:ID:       WHT_iOBuQhsDcZJH1zsSvI1L@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers vs. Hammerheads Threshers vs. Hammerheads

Follow on MiLB First Pitch  https //stza.co/+xB9y-J

Shop  https //stza.co/+xB9y-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Hammerheads
END:VALARM
DTSTART:20180412T230000Z
DTEND:20180413T020000Z
UID:WHT_iOBuQhsDcZJH1zsSvI1L@stanza.co
SUMMARY:Threshers vs. Hammerheads
DESCRIPTION:Threshers vs. Hammerheads\n\nFollow on MiLB First Pitch: https://stza.co/+xB9y-J\n\nShop: https://stza.co/+xB9y-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Marauders
<2018-04-13 Fri 17:15-20:15>
:PROPERTIES:
:ID:       SLrxUSU2Ehe-uv1ggP9fnSZz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Marauders Threshers vs. Marauders

Follow on MiLB First Pitch  https //stza.co/+xB9A-3E

Shop  https //stza.co/+xB9A-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Marauders
END:VALARM
DTSTART:20180413T221500Z
DTEND:20180414T011500Z
UID:SLrxUSU2Ehe-uv1ggP9fnSZz@stanza.co
SUMMARY:Threshers vs. Marauders
DESCRIPTION:Threshers vs. Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+xB9A-3E\n\nShop: https://stza.co/+xB9A-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Marauders
<2018-04-14 Sat 17:15-20:15>
:PROPERTIES:
:ID:       4QiZRlkSNEFabwJrYtZQ4uXG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Marauders Threshers vs. Marauders

Follow on MiLB First Pitch  https //stza.co/+xB9F-2e

Shop  https //stza.co/+xB9F-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Marauders
END:VALARM
DTSTART:20180414T221500Z
DTEND:20180415T011500Z
UID:4QiZRlkSNEFabwJrYtZQ4uXG@stanza.co
SUMMARY:Threshers vs. Marauders
DESCRIPTION:Threshers vs. Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+xB9F-2e\n\nShop: https://stza.co/+xB9F-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Marauders
<2018-04-15 Sun 12:00-15:00>
:PROPERTIES:
:ID:       0qraC1rA5vkpkJjG-cV3Fup5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers vs. Marauders Threshers vs. Marauders

Follow on MiLB First Pitch  https //stza.co/+xB9I-31

Shop  https //stza.co/+xB9I-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Marauders
END:VALARM
DTSTART:20180415T170000Z
DTEND:20180415T200000Z
UID:0qraC1rA5vkpkJjG-cV3Fup5@stanza.co
SUMMARY:Threshers vs. Marauders
DESCRIPTION:Threshers vs. Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+xB9I-31\n\nShop: https://stza.co/+xB9I-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Stone Crabs
<2018-04-17 Tue 17:35-20:35>
:PROPERTIES:
:ID:       Ze2JRA0Whk2Sm9s8uCOgCqFS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Stone Crabs Threshers @ Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+wYm7-$

Shop  https //stza.co/+wYm7-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Stone Crabs
END:VALARM
DTSTART:20180417T223500Z
DTEND:20180418T013500Z
UID:Ze2JRA0Whk2Sm9s8uCOgCqFS@stanza.co
SUMMARY:Threshers @ Stone Crabs
DESCRIPTION:Threshers @ Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+wYm7-$\n\nShop: https://stza.co/+wYm7-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Stone Crabs
<2018-04-18 Wed 17:35-20:35>
:PROPERTIES:
:ID:       GsBbLqFwa78ZEgrAwzFjYgb6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Stone Crabs Threshers @ Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+wYm8-2n

Shop  https //stza.co/+wYm8-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Stone Crabs
END:VALARM
DTSTART:20180418T223500Z
DTEND:20180419T013500Z
UID:GsBbLqFwa78ZEgrAwzFjYgb6@stanza.co
SUMMARY:Threshers @ Stone Crabs
DESCRIPTION:Threshers @ Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+wYm8-2n\n\nShop: https://stza.co/+wYm8-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Stone Crabs
<2018-04-19 Thu 17:35-20:35>
:PROPERTIES:
:ID:       xZEPByNQFSoPVdie27HMiMjC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers @ Stone Crabs Threshers @ Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+wYm9-3S

Shop  https //stza.co/+wYm9-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Stone Crabs
END:VALARM
DTSTART:20180419T223500Z
DTEND:20180420T013500Z
UID:xZEPByNQFSoPVdie27HMiMjC@stanza.co
SUMMARY:Threshers @ Stone Crabs
DESCRIPTION:Threshers @ Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+wYm9-3S\n\nShop: https://stza.co/+wYm9-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Tarpons
<2018-04-20 Fri>--<2018-04-19 Thu>
:PROPERTIES:
:ID:       bBTZdCIYi1gR701VrYOMiNJ_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Tarpons Threshers @ Tarpons

Follow on MiLB First Pitch  https //stza.co/+vMhh-31

Shop  https //stza.co/+vMhh-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Tarpons
END:VALARM
DTSTART;VALUE=DATE:20180420
DTEND;VALUE=DATE:20180420
UID:bBTZdCIYi1gR701VrYOMiNJ_@stanza.co
SUMMARY:Threshers @ Tarpons
DESCRIPTION:Threshers @ Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+vMhh-31\n\nShop: https://stza.co/+vMhh-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Tarpons
<2018-04-21 Sat>--<2018-04-20 Fri>
:PROPERTIES:
:ID:       klT0K-b6qmdwoNMMnc7p8eXa@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Tarpons Threshers @ Tarpons

Follow on MiLB First Pitch  https //stza.co/+vMhi-i

Shop  https //stza.co/+vMhi-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Tarpons
END:VALARM
DTSTART;VALUE=DATE:20180421
DTEND;VALUE=DATE:20180421
UID:klT0K-b6qmdwoNMMnc7p8eXa@stanza.co
SUMMARY:Threshers @ Tarpons
DESCRIPTION:Threshers @ Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+vMhi-i\n\nShop: https://stza.co/+vMhi-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Tarpons
<2018-04-22 Sun>--<2018-04-21 Sat>
:PROPERTIES:
:ID:       4J5fl2hwAY58ka0jWKg92Xhe@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers @ Tarpons Threshers @ Tarpons

Follow on MiLB First Pitch  https //stza.co/+vMhj-x

Shop  https //stza.co/+vMhj-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Tarpons
END:VALARM
DTSTART;VALUE=DATE:20180422
DTEND;VALUE=DATE:20180422
UID:4J5fl2hwAY58ka0jWKg92Xhe@stanza.co
SUMMARY:Threshers @ Tarpons
DESCRIPTION:Threshers @ Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+vMhj-x\n\nShop: https://stza.co/+vMhj-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Miracle
<2018-04-23 Mon 18:00-21:00>
:PROPERTIES:
:ID:       Edg9tpjjyTyFXxrA5kCIJ1Nt@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Miracle Threshers vs. Miracle

Follow on MiLB First Pitch  https //stza.co/+xB9N-1S

Shop  https //stza.co/+xB9N-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Miracle
END:VALARM
DTSTART:20180423T230000Z
DTEND:20180424T020000Z
UID:Edg9tpjjyTyFXxrA5kCIJ1Nt@stanza.co
SUMMARY:Threshers vs. Miracle
DESCRIPTION:Threshers vs. Miracle\n\nFollow on MiLB First Pitch: https://stza.co/+xB9N-1S\n\nShop: https://stza.co/+xB9N-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Miracle
<2018-04-24 Tue 18:00-21:00>
:PROPERTIES:
:ID:       M4L69x2HH-qfvFmk-xYTq8L1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Miracle Threshers vs. Miracle

Follow on MiLB First Pitch  https //stza.co/+xB9R-x

Shop  https //stza.co/+xB9R-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Miracle
END:VALARM
DTSTART:20180424T230000Z
DTEND:20180425T020000Z
UID:M4L69x2HH-qfvFmk-xYTq8L1@stanza.co
SUMMARY:Threshers vs. Miracle
DESCRIPTION:Threshers vs. Miracle\n\nFollow on MiLB First Pitch: https://stza.co/+xB9R-x\n\nShop: https://stza.co/+xB9R-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Miracle
<2018-04-25 Wed 11:00-14:00>
:PROPERTIES:
:ID:       j_FQOboQJbIvxO_lMwnI1mwY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers vs. Miracle Threshers vs. Miracle

Follow on MiLB First Pitch  https //stza.co/+xB9U-24

Shop  https //stza.co/+xB9U-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Miracle
END:VALARM
DTSTART:20180425T160000Z
DTEND:20180425T190000Z
UID:j_FQOboQJbIvxO_lMwnI1mwY@stanza.co
SUMMARY:Threshers vs. Miracle
DESCRIPTION:Threshers vs. Miracle\n\nFollow on MiLB First Pitch: https://stza.co/+xB9U-24\n\nShop: https://stza.co/+xB9U-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Blue Jays
<2018-04-26 Thu 17:30-20:30>
:PROPERTIES:
:ID:       gY80O1aCcYN75gjH2sWema0O@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Blue Jays Threshers @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+y0Gi-1a

Shop  https //stza.co/+y0Gi-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Blue Jays
END:VALARM
DTSTART:20180426T223000Z
DTEND:20180427T013000Z
UID:gY80O1aCcYN75gjH2sWema0O@stanza.co
SUMMARY:Threshers @ Blue Jays
DESCRIPTION:Threshers @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+y0Gi-1a\n\nShop: https://stza.co/+y0Gi-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Blue Jays
<2018-04-27 Fri 17:30-20:30>
:PROPERTIES:
:ID:       XSAb7DKt94UbgKTe45Ail5cO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Blue Jays Threshers @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+y0Gj-3I

Shop  https //stza.co/+y0Gj-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Blue Jays
END:VALARM
DTSTART:20180427T223000Z
DTEND:20180428T013000Z
UID:XSAb7DKt94UbgKTe45Ail5cO@stanza.co
SUMMARY:Threshers @ Blue Jays
DESCRIPTION:Threshers @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+y0Gj-3I\n\nShop: https://stza.co/+y0Gj-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Blue Jays
<2018-04-28 Sat 17:30-20:30>
:PROPERTIES:
:ID:       Kxp4Kw5u7UjX-ntNj02RNqiK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers @ Blue Jays Threshers @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+y0Gk-7

Shop  https //stza.co/+y0Gk-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Blue Jays
END:VALARM
DTSTART:20180428T223000Z
DTEND:20180429T013000Z
UID:Kxp4Kw5u7UjX-ntNj02RNqiK@stanza.co
SUMMARY:Threshers @ Blue Jays
DESCRIPTION:Threshers @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+y0Gk-7\n\nShop: https://stza.co/+y0Gk-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Blue Jays
<2018-04-29 Sun 12:00-15:00>
:PROPERTIES:
:ID:       6quKrdRSzjVS_DPk2dk6eQAs@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Blue Jays Threshers @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+y0Gl-22

Shop  https //stza.co/+y0Gl-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Blue Jays
END:VALARM
DTSTART:20180429T170000Z
DTEND:20180429T200000Z
UID:6quKrdRSzjVS_DPk2dk6eQAs@stanza.co
SUMMARY:Threshers @ Blue Jays
DESCRIPTION:Threshers @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+y0Gl-22\n\nShop: https://stza.co/+y0Gl-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Flying Tigers
<2018-05-01 Tue 18:00-21:00>
:PROPERTIES:
:ID:       z8ISVF1HS70ZA5cfV5FSCP9w@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Flying Tigers Threshers vs. Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+xB9_-34

Shop  https //stza.co/+xB9_-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Flying Tigers
END:VALARM
DTSTART:20180501T230000Z
DTEND:20180502T020000Z
UID:z8ISVF1HS70ZA5cfV5FSCP9w@stanza.co
SUMMARY:Threshers vs. Flying Tigers
DESCRIPTION:Threshers vs. Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xB9_-34\n\nShop: https://stza.co/+xB9_-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Flying Tigers
<2018-05-02 Wed 11:00-14:00>
:PROPERTIES:
:ID:       Sno4S4ObljZIGqeRW9p2taVE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers vs. Flying Tigers Threshers vs. Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+xBa0-2J

Shop  https //stza.co/+xBa0-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Flying Tigers
END:VALARM
DTSTART:20180502T160000Z
DTEND:20180502T190000Z
UID:Sno4S4ObljZIGqeRW9p2taVE@stanza.co
SUMMARY:Threshers vs. Flying Tigers
DESCRIPTION:Threshers vs. Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xBa0-2J\n\nShop: https://stza.co/+xBa0-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Flying Tigers
<2018-05-03 Thu 17:30-20:30>
:PROPERTIES:
:ID:       w-tFpllrCkzhxObtSiiFp5yN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Flying Tigers Threshers @ Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+wKM6-1Z

Shop  https //stza.co/+wKM6-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Flying Tigers
END:VALARM
DTSTART:20180503T223000Z
DTEND:20180504T013000Z
UID:w-tFpllrCkzhxObtSiiFp5yN@stanza.co
SUMMARY:Threshers @ Flying Tigers
DESCRIPTION:Threshers @ Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+wKM6-1Z\n\nShop: https://stza.co/+wKM6-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Blue Jays
<2018-05-04 Fri 17:15-20:15>
:PROPERTIES:
:ID:       r41LwPAzlEoXUCcLh-q9t8F-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Blue Jays Threshers vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xBa5-L

Shop  https //stza.co/+xBa5-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Blue Jays
END:VALARM
DTSTART:20180504T221500Z
DTEND:20180505T011500Z
UID:r41LwPAzlEoXUCcLh-q9t8F-@stanza.co
SUMMARY:Threshers vs. Blue Jays
DESCRIPTION:Threshers vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xBa5-L\n\nShop: https://stza.co/+xBa5-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Blue Jays
<2018-05-05 Sat 17:15-20:15>
:PROPERTIES:
:ID:       fprcoV3rrQWulEU-Hdhiw9n9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers vs. Blue Jays Threshers vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xBaa-33

Shop  https //stza.co/+xBaa-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Blue Jays
END:VALARM
DTSTART:20180505T221500Z
DTEND:20180506T011500Z
UID:fprcoV3rrQWulEU-Hdhiw9n9@stanza.co
SUMMARY:Threshers vs. Blue Jays
DESCRIPTION:Threshers vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xBaa-33\n\nShop: https://stza.co/+xBaa-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Blue Jays
<2018-05-06 Sun 12:00-15:00>
:PROPERTIES:
:ID:       Dx1H-XUpj54lu86XPLuSLSk_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Blue Jays Threshers vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xBad-1H

Shop  https //stza.co/+xBad-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Blue Jays
END:VALARM
DTSTART:20180506T170000Z
DTEND:20180506T200000Z
UID:Dx1H-XUpj54lu86XPLuSLSk_@stanza.co
SUMMARY:Threshers vs. Blue Jays
DESCRIPTION:Threshers vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xBad-1H\n\nShop: https://stza.co/+xBad-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Flying Tigers
<2018-05-07 Mon 17:30-20:30>
:PROPERTIES:
:ID:       dBfuhELvncelhKFfvfB5DBG5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Flying Tigers Threshers @ Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+wKM7-6

Shop  https //stza.co/+wKM7-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Flying Tigers
END:VALARM
DTSTART:20180507T223000Z
DTEND:20180508T013000Z
UID:dBfuhELvncelhKFfvfB5DBG5@stanza.co
SUMMARY:Threshers @ Flying Tigers
DESCRIPTION:Threshers @ Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+wKM7-6\n\nShop: https://stza.co/+wKM7-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Flying Tigers
<2018-05-08 Tue 09:30-12:30>
:PROPERTIES:
:ID:       vowBmxYImKhl3_0qu852YlCY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers @ Flying Tigers Threshers @ Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+wKM8-2

Shop  https //stza.co/+wKM8-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Flying Tigers
END:VALARM
DTSTART:20180508T143000Z
DTEND:20180508T173000Z
UID:vowBmxYImKhl3_0qu852YlCY@stanza.co
SUMMARY:Threshers @ Flying Tigers
DESCRIPTION:Threshers @ Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+wKM8-2\n\nShop: https://stza.co/+wKM8-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Flying Tigers
<2018-05-09 Wed 17:30-20:30>
:PROPERTIES:
:ID:       PAlgiqnY-8LbZW-wIsRdpMAs@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Flying Tigers Threshers @ Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+wKM9-34

Shop  https //stza.co/+wKM9-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Flying Tigers
END:VALARM
DTSTART:20180509T223000Z
DTEND:20180510T013000Z
UID:PAlgiqnY-8LbZW-wIsRdpMAs@stanza.co
SUMMARY:Threshers @ Flying Tigers
DESCRIPTION:Threshers @ Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+wKM9-34\n\nShop: https://stza.co/+wKM9-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Tortugas
<2018-05-10 Thu 18:00-21:00>
:PROPERTIES:
:ID:       5OtkEleqWvtdtlHruVZJMiwK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Tortugas Threshers vs. Tortugas

Follow on MiLB First Pitch  https //stza.co/+xBai-3

Shop  https //stza.co/+xBai-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Tortugas
END:VALARM
DTSTART:20180510T230000Z
DTEND:20180511T020000Z
UID:5OtkEleqWvtdtlHruVZJMiwK@stanza.co
SUMMARY:Threshers vs. Tortugas
DESCRIPTION:Threshers vs. Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+xBai-3\n\nShop: https://stza.co/+xBai-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Tortugas
<2018-05-11 Fri 17:15-20:15>
:PROPERTIES:
:ID:       Lqsd3tJYxLwJ58Qe37vddtmO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers vs. Tortugas Threshers vs. Tortugas

Follow on MiLB First Pitch  https //stza.co/+xBal-h

Shop  https //stza.co/+xBal-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Tortugas
END:VALARM
DTSTART:20180511T221500Z
DTEND:20180512T011500Z
UID:Lqsd3tJYxLwJ58Qe37vddtmO@stanza.co
SUMMARY:Threshers vs. Tortugas
DESCRIPTION:Threshers vs. Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+xBal-h\n\nShop: https://stza.co/+xBal-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Tortugas
<2018-05-12 Sat 17:15-20:15>
:PROPERTIES:
:ID:       n2DCe2n38VV-iidlftfX3Qwp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Tortugas Threshers vs. Tortugas

Follow on MiLB First Pitch  https //stza.co/+xBap-1a

Shop  https //stza.co/+xBap-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Tortugas
END:VALARM
DTSTART:20180512T221500Z
DTEND:20180513T011500Z
UID:n2DCe2n38VV-iidlftfX3Qwp@stanza.co
SUMMARY:Threshers vs. Tortugas
DESCRIPTION:Threshers vs. Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+xBap-1a\n\nShop: https://stza.co/+xBap-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Cardinals
<2018-05-14 Mon 18:00-21:00>
:PROPERTIES:
:ID:       _3GbwulZ3YxZne3Pviwr3b5b@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Cardinals Threshers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xBat-2R

Shop  https //stza.co/+xBat-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Cardinals
END:VALARM
DTSTART:20180514T230000Z
DTEND:20180515T020000Z
UID:_3GbwulZ3YxZne3Pviwr3b5b@stanza.co
SUMMARY:Threshers vs. Cardinals
DESCRIPTION:Threshers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xBat-2R\n\nShop: https://stza.co/+xBat-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Cardinals
<2018-05-15 Tue 18:00-21:00>
:PROPERTIES:
:ID:       qQZSKaNfePTtOk0FsKVk2psk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers vs. Cardinals Threshers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xBay-P

Shop  https //stza.co/+xBay-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Cardinals
END:VALARM
DTSTART:20180515T230000Z
DTEND:20180516T020000Z
UID:qQZSKaNfePTtOk0FsKVk2psk@stanza.co
SUMMARY:Threshers vs. Cardinals
DESCRIPTION:Threshers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xBay-P\n\nShop: https://stza.co/+xBay-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Cardinals
<2018-05-16 Wed 09:30-12:30>
:PROPERTIES:
:ID:       GbXhxqqoCTE_lcPZVZcUSyNJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Cardinals Threshers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xBaC-3h

Shop  https //stza.co/+xBaC-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Cardinals
END:VALARM
DTSTART:20180516T143000Z
DTEND:20180516T173000Z
UID:GbXhxqqoCTE_lcPZVZcUSyNJ@stanza.co
SUMMARY:Threshers vs. Cardinals
DESCRIPTION:Threshers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xBaC-3h\n\nShop: https://stza.co/+xBaC-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Cardinals
<2018-05-17 Thu 18:00-21:00>
:PROPERTIES:
:ID:       kvFX7HFx9l8YQfBQ1_xiCIAi@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Cardinals Threshers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xBaF-2F

Shop  https //stza.co/+xBaF-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Cardinals
END:VALARM
DTSTART:20180517T230000Z
DTEND:20180518T020000Z
UID:kvFX7HFx9l8YQfBQ1_xiCIAi@stanza.co
SUMMARY:Threshers vs. Cardinals
DESCRIPTION:Threshers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xBaF-2F\n\nShop: https://stza.co/+xBaF-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Fire Frogs
<2018-05-18 Fri 17:31-20:31>
:PROPERTIES:
:ID:       BrplPJiJIBYzwo7vFZx4NUpW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers @ Fire Frogs Threshers @ Fire Frogs

Buy tickets here  https //stza.co/~xWKx

Follow on MiLB First Pitch  https //stza.co/+xWKx-3x

Shop  https //stza.co/+xWKx-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Fire Frogs
END:VALARM
DTSTART:20180518T223100Z
DTEND:20180519T013100Z
UID:BrplPJiJIBYzwo7vFZx4NUpW@stanza.co
SUMMARY:Threshers @ Fire Frogs
DESCRIPTION:Threshers @ Fire Frogs\n\nBuy tickets here: https://stza.co/~xWKx\n\nFollow on MiLB First Pitch: https://stza.co/+xWKx-3x\n\nShop: https://stza.co/+xWKx-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Fire Frogs
<2018-05-19 Sat 16:00-19:00>
:PROPERTIES:
:ID:       -DAsDYNA4RJYKPjfnKWzYW5o@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Fire Frogs Threshers @ Fire Frogs

Buy tickets here  https //stza.co/~xWKy

Follow on MiLB First Pitch  https //stza.co/+xWKy-9

Shop  https //stza.co/+xWKy-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Fire Frogs
END:VALARM
DTSTART:20180519T210000Z
DTEND:20180520T000000Z
UID:-DAsDYNA4RJYKPjfnKWzYW5o@stanza.co
SUMMARY:Threshers @ Fire Frogs
DESCRIPTION:Threshers @ Fire Frogs\n\nBuy tickets here: https://stza.co/~xWKy\n\nFollow on MiLB First Pitch: https://stza.co/+xWKy-9\n\nShop: https://stza.co/+xWKy-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Fire Frogs
<2018-05-20 Sun 10:00-13:00>
:PROPERTIES:
:ID:       X3XMSQ8O1qo0VgsFXT2_sLmH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Fire Frogs Threshers @ Fire Frogs

Buy tickets here  https //stza.co/~xWKz

Follow on MiLB First Pitch  https //stza.co/+xWKz-1t

Shop  https //stza.co/+xWKz-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Fire Frogs
END:VALARM
DTSTART:20180520T150000Z
DTEND:20180520T180000Z
UID:X3XMSQ8O1qo0VgsFXT2_sLmH@stanza.co
SUMMARY:Threshers @ Fire Frogs
DESCRIPTION:Threshers @ Fire Frogs\n\nBuy tickets here: https://stza.co/~xWKz\n\nFollow on MiLB First Pitch: https://stza.co/+xWKz-1t\n\nShop: https://stza.co/+xWKz-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Mets
<2018-05-21 Mon 17:30-20:30>
:PROPERTIES:
:ID:       oPTLS-0vabzGyLF3ruSuZbpb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers @ Mets Threshers @ Mets

Follow on MiLB First Pitch  https //stza.co/+vMhb-W

Shop  https //stza.co/+vMhb-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Mets
END:VALARM
DTSTART:20180521T223000Z
DTEND:20180522T013000Z
UID:oPTLS-0vabzGyLF3ruSuZbpb@stanza.co
SUMMARY:Threshers @ Mets
DESCRIPTION:Threshers @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+vMhb-W\n\nShop: https://stza.co/+vMhb-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Mets
<2018-05-22 Tue 17:30-20:30>
:PROPERTIES:
:ID:       VmQEZ2282qk0tBHiWAG6Y_jS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Mets Threshers @ Mets

Follow on MiLB First Pitch  https //stza.co/+vMhc-1_

Shop  https //stza.co/+vMhc-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Mets
END:VALARM
DTSTART:20180522T223000Z
DTEND:20180523T013000Z
UID:VmQEZ2282qk0tBHiWAG6Y_jS@stanza.co
SUMMARY:Threshers @ Mets
DESCRIPTION:Threshers @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+vMhc-1_\n\nShop: https://stza.co/+vMhc-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Mets
<2018-05-23 Wed 17:30-20:30>
:PROPERTIES:
:ID:       rxfRccdTQMtBm4qgE5oVUaHD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Mets Threshers @ Mets

Follow on MiLB First Pitch  https //stza.co/+vMhd-3x

Shop  https //stza.co/+vMhd-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Mets
END:VALARM
DTSTART:20180523T223000Z
DTEND:20180524T013000Z
UID:rxfRccdTQMtBm4qgE5oVUaHD@stanza.co
SUMMARY:Threshers @ Mets
DESCRIPTION:Threshers @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+vMhd-3x\n\nShop: https://stza.co/+vMhd-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Cardinals
<2018-05-24 Thu>--<2018-05-23 Wed>
:PROPERTIES:
:ID:       pEiZDm4_yUV3SYzcHFJR4g2m@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers @ Cardinals Threshers @ Cardinals

Buy tickets here  https //stza.co/~vMh7

Follow on MiLB First Pitch  https //stza.co/+vMh7-K

Shop  https //stza.co/+vMh7-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180524
DTEND;VALUE=DATE:20180524
UID:pEiZDm4_yUV3SYzcHFJR4g2m@stanza.co
SUMMARY:Threshers @ Cardinals
DESCRIPTION:Threshers @ Cardinals\n\nBuy tickets here: https://stza.co/~vMh7\n\nFollow on MiLB First Pitch: https://stza.co/+vMh7-K\n\nShop: https://stza.co/+vMh7-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Cardinals
<2018-05-25 Fri>--<2018-05-24 Thu>
:PROPERTIES:
:ID:       9vO1m0aE4Vm4OzMsTeAJSN7I@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Cardinals Threshers @ Cardinals

Buy tickets here  https //stza.co/~vMh8

Follow on MiLB First Pitch  https //stza.co/+vMh8-3j

Shop  https //stza.co/+vMh8-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180525
DTEND;VALUE=DATE:20180525
UID:9vO1m0aE4Vm4OzMsTeAJSN7I@stanza.co
SUMMARY:Threshers @ Cardinals
DESCRIPTION:Threshers @ Cardinals\n\nBuy tickets here: https://stza.co/~vMh8\n\nFollow on MiLB First Pitch: https://stza.co/+vMh8-3j\n\nShop: https://stza.co/+vMh8-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Cardinals
<2018-05-26 Sat>--<2018-05-25 Fri>
:PROPERTIES:
:ID:       OzW1-vHqZOeuFV2ut56C3gqx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Cardinals Threshers @ Cardinals

Buy tickets here  https //stza.co/~vMh9

Follow on MiLB First Pitch  https //stza.co/+vMh9-2

Shop  https //stza.co/+vMh9-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180526
DTEND;VALUE=DATE:20180526
UID:OzW1-vHqZOeuFV2ut56C3gqx@stanza.co
SUMMARY:Threshers @ Cardinals
DESCRIPTION:Threshers @ Cardinals\n\nBuy tickets here: https://stza.co/~vMh9\n\nFollow on MiLB First Pitch: https://stza.co/+vMh9-2\n\nShop: https://stza.co/+vMh9-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Cardinals
<2018-05-27 Sun>--<2018-05-26 Sat>
:PROPERTIES:
:ID:       IU5yYLHdszxWAHqhw6IqrK9J@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers @ Cardinals Threshers @ Cardinals

Buy tickets here  https //stza.co/~vMha

Follow on MiLB First Pitch  https //stza.co/+vMha-3u

Shop  https //stza.co/+vMha-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180527
DTEND;VALUE=DATE:20180527
UID:IU5yYLHdszxWAHqhw6IqrK9J@stanza.co
SUMMARY:Threshers @ Cardinals
DESCRIPTION:Threshers @ Cardinals\n\nBuy tickets here: https://stza.co/~vMha\n\nFollow on MiLB First Pitch: https://stza.co/+vMha-3u\n\nShop: https://stza.co/+vMha-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Miracle
<2018-05-29 Tue 18:00-21:00>
:PROPERTIES:
:ID:       IXMmMS0tuXAy-wC266YkfMZY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Miracle Threshers vs. Miracle

Follow on MiLB First Pitch  https //stza.co/+xBaH-1g

Shop  https //stza.co/+xBaH-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Miracle
END:VALARM
DTSTART:20180529T230000Z
DTEND:20180530T020000Z
UID:IXMmMS0tuXAy-wC266YkfMZY@stanza.co
SUMMARY:Threshers vs. Miracle
DESCRIPTION:Threshers vs. Miracle\n\nFollow on MiLB First Pitch: https://stza.co/+xBaH-1g\n\nShop: https://stza.co/+xBaH-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Miracle
<2018-05-30 Wed 11:00-14:00>
:PROPERTIES:
:ID:       y3OBbhT4aViWSbKZVJhV7dke@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Miracle Threshers vs. Miracle

Follow on MiLB First Pitch  https //stza.co/+xBaJ-18

Shop  https //stza.co/+xBaJ-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Miracle
END:VALARM
DTSTART:20180530T160000Z
DTEND:20180530T190000Z
UID:y3OBbhT4aViWSbKZVJhV7dke@stanza.co
SUMMARY:Threshers vs. Miracle
DESCRIPTION:Threshers vs. Miracle\n\nFollow on MiLB First Pitch: https://stza.co/+xBaJ-18\n\nShop: https://stza.co/+xBaJ-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Miracle
<2018-05-31 Thu 18:00-21:00>
:PROPERTIES:
:ID:       bzw8lqLDUwDOKDxGWJvIJZD_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers vs. Miracle Threshers vs. Miracle

Follow on MiLB First Pitch  https //stza.co/+xBaL-1l

Shop  https //stza.co/+xBaL-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Miracle
END:VALARM
DTSTART:20180531T230000Z
DTEND:20180601T020000Z
UID:bzw8lqLDUwDOKDxGWJvIJZD_@stanza.co
SUMMARY:Threshers vs. Miracle
DESCRIPTION:Threshers vs. Miracle\n\nFollow on MiLB First Pitch: https://stza.co/+xBaL-1l\n\nShop: https://stza.co/+xBaL-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Fire Frogs
<2018-06-01 Fri 17:15-20:15>
:PROPERTIES:
:ID:       W--y-1Jrovq4xLxsmwXZq0qI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Fire Frogs Threshers vs. Fire Frogs

Follow on MiLB First Pitch  https //stza.co/+xBaN-V

Shop  https //stza.co/+xBaN-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Fire Frogs
END:VALARM
DTSTART:20180601T221500Z
DTEND:20180602T011500Z
UID:W--y-1Jrovq4xLxsmwXZq0qI@stanza.co
SUMMARY:Threshers vs. Fire Frogs
DESCRIPTION:Threshers vs. Fire Frogs\n\nFollow on MiLB First Pitch: https://stza.co/+xBaN-V\n\nShop: https://stza.co/+xBaN-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Fire Frogs
<2018-06-02 Sat 17:15-20:15>
:PROPERTIES:
:ID:       XUq8ZTgRsewQvEfh8FgYqBB1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Fire Frogs Threshers vs. Fire Frogs

Follow on MiLB First Pitch  https //stza.co/+xBaQ-v

Shop  https //stza.co/+xBaQ-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Fire Frogs
END:VALARM
DTSTART:20180602T221500Z
DTEND:20180603T011500Z
UID:XUq8ZTgRsewQvEfh8FgYqBB1@stanza.co
SUMMARY:Threshers vs. Fire Frogs
DESCRIPTION:Threshers vs. Fire Frogs\n\nFollow on MiLB First Pitch: https://stza.co/+xBaQ-v\n\nShop: https://stza.co/+xBaQ-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Fire Frogs
<2018-06-03 Sun 12:00-15:00>
:PROPERTIES:
:ID:       OwEmoipxBX2z-l2zfgYeBXrd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers vs. Fire Frogs Threshers vs. Fire Frogs

Follow on MiLB First Pitch  https //stza.co/+xBaR-3L

Shop  https //stza.co/+xBaR-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Fire Frogs
END:VALARM
DTSTART:20180603T170000Z
DTEND:20180603T200000Z
UID:OwEmoipxBX2z-l2zfgYeBXrd@stanza.co
SUMMARY:Threshers vs. Fire Frogs
DESCRIPTION:Threshers vs. Fire Frogs\n\nFollow on MiLB First Pitch: https://stza.co/+xBaR-3L\n\nShop: https://stza.co/+xBaR-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Tortugas
<2018-06-04 Mon 18:05-21:05>
:PROPERTIES:
:ID:       1ebex8rdF47_--vbd6YzLOf9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Tortugas Threshers @ Tortugas

Follow on MiLB First Pitch  https //stza.co/+vMgv-1P

Shop  https //stza.co/+vMgv-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Tortugas
END:VALARM
DTSTART:20180604T230500Z
DTEND:20180605T020500Z
UID:1ebex8rdF47_--vbd6YzLOf9@stanza.co
SUMMARY:Threshers @ Tortugas
DESCRIPTION:Threshers @ Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+vMgv-1P\n\nShop: https://stza.co/+vMgv-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Tortugas
<2018-06-05 Tue 18:05-21:05>
:PROPERTIES:
:ID:       xe8RS0i7Vxcbo33SV0Zvirtc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Tortugas Threshers @ Tortugas

Follow on MiLB First Pitch  https //stza.co/+vMgw-b

Shop  https //stza.co/+vMgw-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Tortugas
END:VALARM
DTSTART:20180605T230500Z
DTEND:20180606T020500Z
UID:xe8RS0i7Vxcbo33SV0Zvirtc@stanza.co
SUMMARY:Threshers @ Tortugas
DESCRIPTION:Threshers @ Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+vMgw-b\n\nShop: https://stza.co/+vMgw-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Tortugas
<2018-06-06 Wed 18:05-21:05>
:PROPERTIES:
:ID:       PKxQ9j4Me0-XbT1Hgsq5QbzG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers @ Tortugas Threshers @ Tortugas

Follow on MiLB First Pitch  https //stza.co/+vMgx-2J

Shop  https //stza.co/+vMgx-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Tortugas
END:VALARM
DTSTART:20180606T230500Z
DTEND:20180607T020500Z
UID:PKxQ9j4Me0-XbT1Hgsq5QbzG@stanza.co
SUMMARY:Threshers @ Tortugas
DESCRIPTION:Threshers @ Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+vMgx-2J\n\nShop: https://stza.co/+vMgx-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Tortugas
<2018-06-07 Thu 18:05-21:05>
:PROPERTIES:
:ID:       iEnpK03K3uqod6LpPmYJZMx0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Tortugas Threshers @ Tortugas

Follow on MiLB First Pitch  https //stza.co/+vMgy-n

Shop  https //stza.co/+vMgy-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Tortugas
END:VALARM
DTSTART:20180607T230500Z
DTEND:20180608T020500Z
UID:iEnpK03K3uqod6LpPmYJZMx0@stanza.co
SUMMARY:Threshers @ Tortugas
DESCRIPTION:Threshers @ Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+vMgy-n\n\nShop: https://stza.co/+vMgy-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Stone Crabs
<2018-06-08 Fri 17:35-20:35>
:PROPERTIES:
:ID:       6CkXB_EGpVwR2q8DRyWeiysK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Stone Crabs Threshers @ Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+wYma-3r

Shop  https //stza.co/+wYma-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Stone Crabs
END:VALARM
DTSTART:20180608T223500Z
DTEND:20180609T013500Z
UID:6CkXB_EGpVwR2q8DRyWeiysK@stanza.co
SUMMARY:Threshers @ Stone Crabs
DESCRIPTION:Threshers @ Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+wYma-3r\n\nShop: https://stza.co/+wYma-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Stone Crabs
<2018-06-09 Sat 17:05-20:05>
:PROPERTIES:
:ID:       fMdGjHj9tgP3Z3PpG3vMRA7q@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers @ Stone Crabs Threshers @ Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+wYmb-2K

Shop  https //stza.co/+wYmb-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Stone Crabs
END:VALARM
DTSTART:20180609T220500Z
DTEND:20180610T010500Z
UID:fMdGjHj9tgP3Z3PpG3vMRA7q@stanza.co
SUMMARY:Threshers @ Stone Crabs
DESCRIPTION:Threshers @ Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+wYmb-2K\n\nShop: https://stza.co/+wYmb-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Stone Crabs
<2018-06-10 Sun 11:35-14:35>
:PROPERTIES:
:ID:       C62opJXg_j-sz_JooUu2d1R4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Stone Crabs Threshers @ Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+wYmc-T

Shop  https //stza.co/+wYmc-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Stone Crabs
END:VALARM
DTSTART:20180610T163500Z
DTEND:20180610T193500Z
UID:C62opJXg_j-sz_JooUu2d1R4@stanza.co
SUMMARY:Threshers @ Stone Crabs
DESCRIPTION:Threshers @ Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+wYmc-T\n\nShop: https://stza.co/+wYmc-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Tarpons
<2018-06-11 Mon 18:00-21:00>
:PROPERTIES:
:ID:       VBpVbuXdzce2EozNh84GeE7R@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Tarpons Threshers vs. Tarpons

Follow on MiLB First Pitch  https //stza.co/+xBaT-3j

Shop  https //stza.co/+xBaT-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Tarpons
END:VALARM
DTSTART:20180611T230000Z
DTEND:20180612T020000Z
UID:VBpVbuXdzce2EozNh84GeE7R@stanza.co
SUMMARY:Threshers vs. Tarpons
DESCRIPTION:Threshers vs. Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+xBaT-3j\n\nShop: https://stza.co/+xBaT-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Tarpons
<2018-06-12 Tue 18:00-21:00>
:PROPERTIES:
:ID:       QUv5JlIU8EYvnZd9J4GAbApj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers vs. Tarpons Threshers vs. Tarpons

Follow on MiLB First Pitch  https //stza.co/+xBaW-o

Shop  https //stza.co/+xBaW-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Tarpons
END:VALARM
DTSTART:20180612T230000Z
DTEND:20180613T020000Z
UID:QUv5JlIU8EYvnZd9J4GAbApj@stanza.co
SUMMARY:Threshers vs. Tarpons
DESCRIPTION:Threshers vs. Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+xBaW-o\n\nShop: https://stza.co/+xBaW-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Tarpons
<2018-06-13 Wed 09:30-12:30>
:PROPERTIES:
:ID:       A_PVJGx-GhDXw1HXKj2mrJvP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Tarpons Threshers vs. Tarpons

Follow on MiLB First Pitch  https //stza.co/+xBaY-1U

Shop  https //stza.co/+xBaY-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Tarpons
END:VALARM
DTSTART:20180613T143000Z
DTEND:20180613T173000Z
UID:A_PVJGx-GhDXw1HXKj2mrJvP@stanza.co
SUMMARY:Threshers vs. Tarpons
DESCRIPTION:Threshers vs. Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+xBaY-1U\n\nShop: https://stza.co/+xBaY-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Tarpons
<2018-06-14 Thu 18:00-21:00>
:PROPERTIES:
:ID:       kSEhhTU1FyTOxzSiOU7_io72@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Tarpons Threshers vs. Tarpons

Follow on MiLB First Pitch  https //stza.co/+xBa_-3K

Shop  https //stza.co/+xBa_-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Tarpons
END:VALARM
DTSTART:20180614T230000Z
DTEND:20180615T020000Z
UID:kSEhhTU1FyTOxzSiOU7_io72@stanza.co
SUMMARY:Threshers vs. Tarpons
DESCRIPTION:Threshers vs. Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+xBa_-3K\n\nShop: https://stza.co/+xBa_-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Marauders
<2018-06-18 Mon 17:30-20:30>
:PROPERTIES:
:ID:       GqCP_rhSQLD27XXId1X5Qk8s@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers @ Marauders Threshers @ Marauders

Follow on MiLB First Pitch  https //stza.co/+vMe7-V

Shop  https //stza.co/+vMe7-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Marauders
END:VALARM
DTSTART:20180618T223000Z
DTEND:20180619T013000Z
UID:GqCP_rhSQLD27XXId1X5Qk8s@stanza.co
SUMMARY:Threshers @ Marauders
DESCRIPTION:Threshers @ Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMe7-V\n\nShop: https://stza.co/+vMe7-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Marauders
<2018-06-19 Tue 17:30-20:30>
:PROPERTIES:
:ID:       afdSQikPIIlmDelFVpk7rwoM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Marauders Threshers @ Marauders

Follow on MiLB First Pitch  https //stza.co/+vMe8-3Z

Shop  https //stza.co/+vMe8-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Marauders
END:VALARM
DTSTART:20180619T223000Z
DTEND:20180620T013000Z
UID:afdSQikPIIlmDelFVpk7rwoM@stanza.co
SUMMARY:Threshers @ Marauders
DESCRIPTION:Threshers @ Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMe8-3Z\n\nShop: https://stza.co/+vMe8-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Marauders
<2018-06-20 Wed 09:30-12:30>
:PROPERTIES:
:ID:       yKhmq9dQs7hALLJeO-odVUwF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Marauders Threshers @ Marauders

Follow on MiLB First Pitch  https //stza.co/+vMe9-3C

Shop  https //stza.co/+vMe9-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Marauders
END:VALARM
DTSTART:20180620T143000Z
DTEND:20180620T173000Z
UID:yKhmq9dQs7hALLJeO-odVUwF@stanza.co
SUMMARY:Threshers @ Marauders
DESCRIPTION:Threshers @ Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMe9-3C\n\nShop: https://stza.co/+vMe9-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Blue Jays
<2018-06-21 Thu 18:00-21:00>
:PROPERTIES:
:ID:       lW_KfR9e65Lr0_UrUHWtpEDk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers vs. Blue Jays Threshers vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xBb0-N

Shop  https //stza.co/+xBb0-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Blue Jays
END:VALARM
DTSTART:20180621T230000Z
DTEND:20180622T020000Z
UID:lW_KfR9e65Lr0_UrUHWtpEDk@stanza.co
SUMMARY:Threshers vs. Blue Jays
DESCRIPTION:Threshers vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xBb0-N\n\nShop: https://stza.co/+xBb0-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Blue Jays
<2018-06-22 Fri 17:15-20:15>
:PROPERTIES:
:ID:       b3onC90_OlvdL4ADw1ise_Cz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Blue Jays Threshers vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xBb1-3u

Shop  https //stza.co/+xBb1-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Blue Jays
END:VALARM
DTSTART:20180622T221500Z
DTEND:20180623T011500Z
UID:b3onC90_OlvdL4ADw1ise_Cz@stanza.co
SUMMARY:Threshers vs. Blue Jays
DESCRIPTION:Threshers vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xBb1-3u\n\nShop: https://stza.co/+xBb1-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Blue Jays
<2018-06-23 Sat 17:15-20:15>
:PROPERTIES:
:ID:       pnGZwOG--eLXs81JHalPU3pa@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Blue Jays Threshers vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xBb4-S

Shop  https //stza.co/+xBb4-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Blue Jays
END:VALARM
DTSTART:20180623T221500Z
DTEND:20180624T011500Z
UID:pnGZwOG--eLXs81JHalPU3pa@stanza.co
SUMMARY:Threshers vs. Blue Jays
DESCRIPTION:Threshers vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xBb4-S\n\nShop: https://stza.co/+xBb4-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Blue Jays
<2018-06-24 Sun 12:00-15:00>
:PROPERTIES:
:ID:       X8iEqWIvpNs7rTrRs0zupGFi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers vs. Blue Jays Threshers vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xBb6-2O

Shop  https //stza.co/+xBb6-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Blue Jays
END:VALARM
DTSTART:20180624T170000Z
DTEND:20180624T200000Z
UID:X8iEqWIvpNs7rTrRs0zupGFi@stanza.co
SUMMARY:Threshers vs. Blue Jays
DESCRIPTION:Threshers vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xBb6-2O\n\nShop: https://stza.co/+xBb6-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Tortugas
<2018-06-26 Tue 18:05-21:05>
:PROPERTIES:
:ID:       IRugLQZs27rcjHsUHUGX0VtW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Tortugas Threshers @ Tortugas

Follow on MiLB First Pitch  https //stza.co/+vMgz-3l

Shop  https //stza.co/+vMgz-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Tortugas
END:VALARM
DTSTART:20180626T230500Z
DTEND:20180627T020500Z
UID:IRugLQZs27rcjHsUHUGX0VtW@stanza.co
SUMMARY:Threshers @ Tortugas
DESCRIPTION:Threshers @ Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+vMgz-3l\n\nShop: https://stza.co/+vMgz-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Tortugas
<2018-06-27 Wed 09:35-12:35>
:PROPERTIES:
:ID:       oJMXWKf9b2dswKPRDOamhrdx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Tortugas Threshers @ Tortugas

Follow on MiLB First Pitch  https //stza.co/+vMgA-2f

Shop  https //stza.co/+vMgA-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Tortugas
END:VALARM
DTSTART:20180627T143500Z
DTEND:20180627T173500Z
UID:oJMXWKf9b2dswKPRDOamhrdx@stanza.co
SUMMARY:Threshers @ Tortugas
DESCRIPTION:Threshers @ Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+vMgA-2f\n\nShop: https://stza.co/+vMgA-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Tortugas
<2018-06-28 Thu 18:05-21:05>
:PROPERTIES:
:ID:       ioWcCiZcNYE67VM3jRF1iCap@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers @ Tortugas Threshers @ Tortugas

Follow on MiLB First Pitch  https //stza.co/+vMgB-2C

Shop  https //stza.co/+vMgB-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Tortugas
END:VALARM
DTSTART:20180628T230500Z
DTEND:20180629T020500Z
UID:ioWcCiZcNYE67VM3jRF1iCap@stanza.co
SUMMARY:Threshers @ Tortugas
DESCRIPTION:Threshers @ Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+vMgB-2C\n\nShop: https://stza.co/+vMgB-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Mets
<2018-06-29 Fri 17:15-20:15>
:PROPERTIES:
:ID:       Et-tNpN4geCYksCMH0JleknQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Mets Threshers vs. Mets

Follow on MiLB First Pitch  https //stza.co/+xBb7-15

Shop  https //stza.co/+xBb7-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Mets
END:VALARM
DTSTART:20180629T221500Z
DTEND:20180630T011500Z
UID:Et-tNpN4geCYksCMH0JleknQ@stanza.co
SUMMARY:Threshers vs. Mets
DESCRIPTION:Threshers vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xBb7-15\n\nShop: https://stza.co/+xBb7-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Mets
<2018-06-30 Sat 17:15-20:15>
:PROPERTIES:
:ID:       PgzMED-Mzf13WrGI-1R8VlK4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Mets Threshers vs. Mets

Follow on MiLB First Pitch  https //stza.co/+xBba-1X

Shop  https //stza.co/+xBba-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Mets
END:VALARM
DTSTART:20180630T221500Z
DTEND:20180701T011500Z
UID:PgzMED-Mzf13WrGI-1R8VlK4@stanza.co
SUMMARY:Threshers vs. Mets
DESCRIPTION:Threshers vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xBba-1X\n\nShop: https://stza.co/+xBba-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Mets
<2018-07-01 Sun 12:00-15:00>
:PROPERTIES:
:ID:       E1O-jx03DMTYSWRPX1ka8A9o@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers vs. Mets Threshers vs. Mets

Follow on MiLB First Pitch  https //stza.co/+xBbc-V

Shop  https //stza.co/+xBbc-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Mets
END:VALARM
DTSTART:20180701T170000Z
DTEND:20180701T200000Z
UID:E1O-jx03DMTYSWRPX1ka8A9o@stanza.co
SUMMARY:Threshers vs. Mets
DESCRIPTION:Threshers vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xBbc-V\n\nShop: https://stza.co/+xBbc-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Flying Tigers
<2018-07-02 Mon 18:00-21:00>
:PROPERTIES:
:ID:       v7EOPEB4ing0ZFMHohL26Wb0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Flying Tigers Threshers vs. Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+xBbd-s

Shop  https //stza.co/+xBbd-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Flying Tigers
END:VALARM
DTSTART:20180702T230000Z
DTEND:20180703T020000Z
UID:v7EOPEB4ing0ZFMHohL26Wb0@stanza.co
SUMMARY:Threshers vs. Flying Tigers
DESCRIPTION:Threshers vs. Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xBbd-s\n\nShop: https://stza.co/+xBbd-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Flying Tigers
<2018-07-03 Tue 18:00-21:00>
:PROPERTIES:
:ID:       ePj4oSBt_HDRyCTyO2v3eCqj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Flying Tigers Threshers vs. Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+xBbf-3C

Shop  https //stza.co/+xBbf-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Flying Tigers
END:VALARM
DTSTART:20180703T230000Z
DTEND:20180704T020000Z
UID:ePj4oSBt_HDRyCTyO2v3eCqj@stanza.co
SUMMARY:Threshers vs. Flying Tigers
DESCRIPTION:Threshers vs. Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xBbf-3C\n\nShop: https://stza.co/+xBbf-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Tarpons
<2018-07-04 Wed>--<2018-07-03 Tue>
:PROPERTIES:
:ID:       b9BGSh6q2wByXnDlgZNla2CK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers @ Tarpons Threshers @ Tarpons

Follow on MiLB First Pitch  https //stza.co/+vMhk-T

Shop  https //stza.co/+vMhk-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Tarpons
END:VALARM
DTSTART;VALUE=DATE:20180704
DTEND;VALUE=DATE:20180704
UID:b9BGSh6q2wByXnDlgZNla2CK@stanza.co
SUMMARY:Threshers @ Tarpons
DESCRIPTION:Threshers @ Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+vMhk-T\n\nShop: https://stza.co/+vMhk-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Tarpons
<2018-07-05 Thu>--<2018-07-04 Wed>
:PROPERTIES:
:ID:       hdFEKqWCqBKG1UwDEEfXubvD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Tarpons Threshers @ Tarpons

Follow on MiLB First Pitch  https //stza.co/+vMhl-p

Shop  https //stza.co/+vMhl-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Tarpons
END:VALARM
DTSTART;VALUE=DATE:20180705
DTEND;VALUE=DATE:20180705
UID:hdFEKqWCqBKG1UwDEEfXubvD@stanza.co
SUMMARY:Threshers @ Tarpons
DESCRIPTION:Threshers @ Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+vMhl-p\n\nShop: https://stza.co/+vMhl-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Stone Crabs
<2018-07-06 Fri 17:15-20:15>
:PROPERTIES:
:ID:       jmtfgDzVQxi0cz2jHYrO6_Xv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Stone Crabs Threshers vs. Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+xBbh-1t

Shop  https //stza.co/+xBbh-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Stone Crabs
END:VALARM
DTSTART:20180706T221500Z
DTEND:20180707T011500Z
UID:jmtfgDzVQxi0cz2jHYrO6_Xv@stanza.co
SUMMARY:Threshers vs. Stone Crabs
DESCRIPTION:Threshers vs. Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+xBbh-1t\n\nShop: https://stza.co/+xBbh-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Stone Crabs
<2018-07-07 Sat 17:15-20:15>
:PROPERTIES:
:ID:       Ixx6R6zjcifF0paOFYC-peGG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers vs. Stone Crabs Threshers vs. Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+xBbl-1$

Shop  https //stza.co/+xBbl-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Stone Crabs
END:VALARM
DTSTART:20180707T221500Z
DTEND:20180708T011500Z
UID:Ixx6R6zjcifF0paOFYC-peGG@stanza.co
SUMMARY:Threshers vs. Stone Crabs
DESCRIPTION:Threshers vs. Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+xBbl-1$\n\nShop: https://stza.co/+xBbl-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Stone Crabs
<2018-07-08 Sun 12:00-15:00>
:PROPERTIES:
:ID:       mdDK5CYabyVdTyGE3PtoUXt4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Stone Crabs Threshers vs. Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+xBbr-2U

Shop  https //stza.co/+xBbr-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Stone Crabs
END:VALARM
DTSTART:20180708T170000Z
DTEND:20180708T200000Z
UID:mdDK5CYabyVdTyGE3PtoUXt4@stanza.co
SUMMARY:Threshers vs. Stone Crabs
DESCRIPTION:Threshers vs. Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+xBbr-2U\n\nShop: https://stza.co/+xBbr-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Blue Jays
<2018-07-09 Mon 17:30-20:30>
:PROPERTIES:
:ID:       qpnoOnnd0hpGdnWL5mEwL-iu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Blue Jays Threshers @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+y0Gm-1c

Shop  https //stza.co/+y0Gm-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Blue Jays
END:VALARM
DTSTART:20180709T223000Z
DTEND:20180710T013000Z
UID:qpnoOnnd0hpGdnWL5mEwL-iu@stanza.co
SUMMARY:Threshers @ Blue Jays
DESCRIPTION:Threshers @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+y0Gm-1c\n\nShop: https://stza.co/+y0Gm-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Blue Jays
<2018-07-10 Tue 17:30-20:30>
:PROPERTIES:
:ID:       rmo3wxCDWoYHIYlWtERgV3sd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers @ Blue Jays Threshers @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+y0Gn-Z

Shop  https //stza.co/+y0Gn-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Blue Jays
END:VALARM
DTSTART:20180710T223000Z
DTEND:20180711T013000Z
UID:rmo3wxCDWoYHIYlWtERgV3sd@stanza.co
SUMMARY:Threshers @ Blue Jays
DESCRIPTION:Threshers @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+y0Gn-Z\n\nShop: https://stza.co/+y0Gn-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Blue Jays
<2018-07-11 Wed 17:30-20:30>
:PROPERTIES:
:ID:       aKztpS4m6wjGSYIH-GYLWigh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Blue Jays Threshers @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+y0Go-q

Shop  https //stza.co/+y0Go-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Blue Jays
END:VALARM
DTSTART:20180711T223000Z
DTEND:20180712T013000Z
UID:aKztpS4m6wjGSYIH-GYLWigh@stanza.co
SUMMARY:Threshers @ Blue Jays
DESCRIPTION:Threshers @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+y0Go-q\n\nShop: https://stza.co/+y0Go-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Blue Jays
<2018-07-12 Thu 17:30-20:30>
:PROPERTIES:
:ID:       P5nATPotHySIDFU04I3KK5LI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Blue Jays Threshers @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+y0Gp-3v

Shop  https //stza.co/+y0Gp-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Blue Jays
END:VALARM
DTSTART:20180712T223000Z
DTEND:20180713T013000Z
UID:P5nATPotHySIDFU04I3KK5LI@stanza.co
SUMMARY:Threshers @ Blue Jays
DESCRIPTION:Threshers @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+y0Gp-3v\n\nShop: https://stza.co/+y0Gp-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Fire Frogs
<2018-07-13 Fri 17:31-20:31>
:PROPERTIES:
:ID:       qpG7w1OcUuXeboVL5Fq0KTWY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers @ Fire Frogs Threshers @ Fire Frogs

Buy tickets here  https //stza.co/~xWKA

Follow on MiLB First Pitch  https //stza.co/+xWKA-r

Shop  https //stza.co/+xWKA-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Fire Frogs
END:VALARM
DTSTART:20180713T223100Z
DTEND:20180714T013100Z
UID:qpG7w1OcUuXeboVL5Fq0KTWY@stanza.co
SUMMARY:Threshers @ Fire Frogs
DESCRIPTION:Threshers @ Fire Frogs\n\nBuy tickets here: https://stza.co/~xWKA\n\nFollow on MiLB First Pitch: https://stza.co/+xWKA-r\n\nShop: https://stza.co/+xWKA-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Fire Frogs
<2018-07-14 Sat 17:31-20:31>
:PROPERTIES:
:ID:       7iC5Q_qRB36BXT-qPvpP88Nq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Fire Frogs Threshers @ Fire Frogs

Buy tickets here  https //stza.co/~xWKB

Follow on MiLB First Pitch  https //stza.co/+xWKB-1t

Shop  https //stza.co/+xWKB-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Fire Frogs
END:VALARM
DTSTART:20180714T223100Z
DTEND:20180715T013100Z
UID:7iC5Q_qRB36BXT-qPvpP88Nq@stanza.co
SUMMARY:Threshers @ Fire Frogs
DESCRIPTION:Threshers @ Fire Frogs\n\nBuy tickets here: https://stza.co/~xWKB\n\nFollow on MiLB First Pitch: https://stza.co/+xWKB-1t\n\nShop: https://stza.co/+xWKB-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Fire Frogs
<2018-07-15 Sun 10:00-13:00>
:PROPERTIES:
:ID:       cTc1XejjDp0cNKR8WOKbWPIQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Fire Frogs Threshers @ Fire Frogs

Buy tickets here  https //stza.co/~xWKC

Follow on MiLB First Pitch  https //stza.co/+xWKC-3Y

Shop  https //stza.co/+xWKC-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Fire Frogs
END:VALARM
DTSTART:20180715T150000Z
DTEND:20180715T180000Z
UID:cTc1XejjDp0cNKR8WOKbWPIQ@stanza.co
SUMMARY:Threshers @ Fire Frogs
DESCRIPTION:Threshers @ Fire Frogs\n\nBuy tickets here: https://stza.co/~xWKC\n\nFollow on MiLB First Pitch: https://stza.co/+xWKC-3Y\n\nShop: https://stza.co/+xWKC-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Tortugas
<2018-07-16 Mon 18:00-21:00>
:PROPERTIES:
:ID:       1XRF1TJ3hXL__oN2f5ubyE67@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers vs. Tortugas Threshers vs. Tortugas

Follow on MiLB First Pitch  https //stza.co/+xBbu-1L

Shop  https //stza.co/+xBbu-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Tortugas
END:VALARM
DTSTART:20180716T230000Z
DTEND:20180717T020000Z
UID:1XRF1TJ3hXL__oN2f5ubyE67@stanza.co
SUMMARY:Threshers vs. Tortugas
DESCRIPTION:Threshers vs. Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+xBbu-1L\n\nShop: https://stza.co/+xBbu-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Tortugas
<2018-07-17 Tue 18:00-21:00>
:PROPERTIES:
:ID:       67mE2jMrLOWKFcLkddtWnKwe@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Tortugas Threshers vs. Tortugas

Follow on MiLB First Pitch  https //stza.co/+xBby-3x

Shop  https //stza.co/+xBby-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Tortugas
END:VALARM
DTSTART:20180717T230000Z
DTEND:20180718T020000Z
UID:67mE2jMrLOWKFcLkddtWnKwe@stanza.co
SUMMARY:Threshers vs. Tortugas
DESCRIPTION:Threshers vs. Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+xBby-3x\n\nShop: https://stza.co/+xBby-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Tortugas
<2018-07-18 Wed 18:00-21:00>
:PROPERTIES:
:ID:       CB_I_FU1FZaL83uoM6cdnWnv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Tortugas Threshers vs. Tortugas

Follow on MiLB First Pitch  https //stza.co/+xBbD-R

Shop  https //stza.co/+xBbD-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Tortugas
END:VALARM
DTSTART:20180718T230000Z
DTEND:20180719T020000Z
UID:CB_I_FU1FZaL83uoM6cdnWnv@stanza.co
SUMMARY:Threshers vs. Tortugas
DESCRIPTION:Threshers vs. Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+xBbD-R\n\nShop: https://stza.co/+xBbD-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Fire Frogs
<2018-07-19 Thu 18:00-21:00>
:PROPERTIES:
:ID:       8OWaomy6swN2f2PNpLa4PgQp@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers vs. Fire Frogs Threshers vs. Fire Frogs

Follow on MiLB First Pitch  https //stza.co/+xBbG-19

Shop  https //stza.co/+xBbG-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Fire Frogs
END:VALARM
DTSTART:20180719T230000Z
DTEND:20180720T020000Z
UID:8OWaomy6swN2f2PNpLa4PgQp@stanza.co
SUMMARY:Threshers vs. Fire Frogs
DESCRIPTION:Threshers vs. Fire Frogs\n\nFollow on MiLB First Pitch: https://stza.co/+xBbG-19\n\nShop: https://stza.co/+xBbG-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Fire Frogs
<2018-07-20 Fri 17:15-20:15>
:PROPERTIES:
:ID:       VJ3yFeqT_SP5Rm8qKwH-o6mu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Fire Frogs Threshers vs. Fire Frogs

Follow on MiLB First Pitch  https //stza.co/+xBbL-1O

Shop  https //stza.co/+xBbL-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Fire Frogs
END:VALARM
DTSTART:20180720T221500Z
DTEND:20180721T011500Z
UID:VJ3yFeqT_SP5Rm8qKwH-o6mu@stanza.co
SUMMARY:Threshers vs. Fire Frogs
DESCRIPTION:Threshers vs. Fire Frogs\n\nFollow on MiLB First Pitch: https://stza.co/+xBbL-1O\n\nShop: https://stza.co/+xBbL-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Fire Frogs
<2018-07-21 Sat 17:15-20:15>
:PROPERTIES:
:ID:       aZki6c6ZHr3sSLHBzWBZkMME@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Fire Frogs Threshers vs. Fire Frogs

Follow on MiLB First Pitch  https //stza.co/+xBbR-3H

Shop  https //stza.co/+xBbR-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Fire Frogs
END:VALARM
DTSTART:20180721T221500Z
DTEND:20180722T011500Z
UID:aZki6c6ZHr3sSLHBzWBZkMME@stanza.co
SUMMARY:Threshers vs. Fire Frogs
DESCRIPTION:Threshers vs. Fire Frogs\n\nFollow on MiLB First Pitch: https://stza.co/+xBbR-3H\n\nShop: https://stza.co/+xBbR-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Mets
<2018-07-23 Mon 17:30-20:30>
:PROPERTIES:
:ID:       vzzZ-o9zPUmNIyvj2SskvKiI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers @ Mets Threshers @ Mets

Follow on MiLB First Pitch  https //stza.co/+vMhe-j

Shop  https //stza.co/+vMhe-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Mets
END:VALARM
DTSTART:20180723T223000Z
DTEND:20180724T013000Z
UID:vzzZ-o9zPUmNIyvj2SskvKiI@stanza.co
SUMMARY:Threshers @ Mets
DESCRIPTION:Threshers @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+vMhe-j\n\nShop: https://stza.co/+vMhe-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Mets
<2018-07-24 Tue 17:30-20:30>
:PROPERTIES:
:ID:       79_xKw7AWXTadm30Sqeg_Bdy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Mets Threshers @ Mets

Follow on MiLB First Pitch  https //stza.co/+vMhf-10

Shop  https //stza.co/+vMhf-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Mets
END:VALARM
DTSTART:20180724T223000Z
DTEND:20180725T013000Z
UID:79_xKw7AWXTadm30Sqeg_Bdy@stanza.co
SUMMARY:Threshers @ Mets
DESCRIPTION:Threshers @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+vMhf-10\n\nShop: https://stza.co/+vMhf-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Mets
<2018-07-25 Wed 09:30-12:30>
:PROPERTIES:
:ID:       7b0qWBgEBwKiaUuNaR9G809f@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Mets Threshers @ Mets

Follow on MiLB First Pitch  https //stza.co/+vMhg-25

Shop  https //stza.co/+vMhg-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Mets
END:VALARM
DTSTART:20180725T143000Z
DTEND:20180725T173000Z
UID:7b0qWBgEBwKiaUuNaR9G809f@stanza.co
SUMMARY:Threshers @ Mets
DESCRIPTION:Threshers @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+vMhg-25\n\nShop: https://stza.co/+vMhg-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Flying Tigers
<2018-07-26 Thu 18:00-21:00>
:PROPERTIES:
:ID:       cPlbDUBffc0eFH0hH26g22uT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers vs. Flying Tigers Threshers vs. Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+xBbU-3r

Shop  https //stza.co/+xBbU-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Flying Tigers
END:VALARM
DTSTART:20180726T230000Z
DTEND:20180727T020000Z
UID:cPlbDUBffc0eFH0hH26g22uT@stanza.co
SUMMARY:Threshers vs. Flying Tigers
DESCRIPTION:Threshers vs. Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xBbU-3r\n\nShop: https://stza.co/+xBbU-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Flying Tigers
<2018-07-27 Fri 17:30-20:30>
:PROPERTIES:
:ID:       21tVNXLEkHcQhG01FnWPs738@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Flying Tigers Threshers @ Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+wKMa-2V

Shop  https //stza.co/+wKMa-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Flying Tigers
END:VALARM
DTSTART:20180727T223000Z
DTEND:20180728T013000Z
UID:21tVNXLEkHcQhG01FnWPs738@stanza.co
SUMMARY:Threshers @ Flying Tigers
DESCRIPTION:Threshers @ Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+wKMa-2V\n\nShop: https://stza.co/+wKMa-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Flying Tigers
<2018-07-28 Sat 17:00-20:00>
:PROPERTIES:
:ID:       tnWDWWzQBlODwhDStxZ9xYL9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Flying Tigers Threshers @ Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+wKMb-2s

Shop  https //stza.co/+wKMb-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Flying Tigers
END:VALARM
DTSTART:20180728T220000Z
DTEND:20180729T010000Z
UID:tnWDWWzQBlODwhDStxZ9xYL9@stanza.co
SUMMARY:Threshers @ Flying Tigers
DESCRIPTION:Threshers @ Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+wKMb-2s\n\nShop: https://stza.co/+wKMb-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Flying Tigers
<2018-07-29 Sun 12:00-15:00>
:PROPERTIES:
:ID:       WVOOgNI2YR5OaPkGS6B3nDDI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers @ Flying Tigers Threshers @ Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+wKMc-2k

Shop  https //stza.co/+wKMc-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Flying Tigers
END:VALARM
DTSTART:20180729T170000Z
DTEND:20180729T200000Z
UID:WVOOgNI2YR5OaPkGS6B3nDDI@stanza.co
SUMMARY:Threshers @ Flying Tigers
DESCRIPTION:Threshers @ Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+wKMc-2k\n\nShop: https://stza.co/+wKMc-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Tarpons
<2018-07-31 Tue 18:00-21:00>
:PROPERTIES:
:ID:       -IrcchE-hEaP4-JK02ruznjT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Tarpons Threshers vs. Tarpons

Follow on MiLB First Pitch  https //stza.co/+xBbY-2Y

Shop  https //stza.co/+xBbY-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Tarpons
END:VALARM
DTSTART:20180731T230000Z
DTEND:20180801T020000Z
UID:-IrcchE-hEaP4-JK02ruznjT@stanza.co
SUMMARY:Threshers vs. Tarpons
DESCRIPTION:Threshers vs. Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+xBbY-2Y\n\nShop: https://stza.co/+xBbY-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Tarpons
<2018-08-01 Wed 18:00-21:00>
:PROPERTIES:
:ID:       ltH_0kCzUNvfThtGNezo_wk8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Tarpons Threshers vs. Tarpons

Follow on MiLB First Pitch  https //stza.co/+xBb$-1Y

Shop  https //stza.co/+xBb$-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Tarpons
END:VALARM
DTSTART:20180801T230000Z
DTEND:20180802T020000Z
UID:ltH_0kCzUNvfThtGNezo_wk8@stanza.co
SUMMARY:Threshers vs. Tarpons
DESCRIPTION:Threshers vs. Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+xBb$-1Y\n\nShop: https://stza.co/+xBb$-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Tarpons
<2018-08-02 Thu 18:00-21:00>
:PROPERTIES:
:ID:       J0IU3wKkTZ5MOUrpQpA6e5N7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers vs. Tarpons Threshers vs. Tarpons

Follow on MiLB First Pitch  https //stza.co/+xBc4-u

Shop  https //stza.co/+xBc4-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Tarpons
END:VALARM
DTSTART:20180802T230000Z
DTEND:20180803T020000Z
UID:J0IU3wKkTZ5MOUrpQpA6e5N7@stanza.co
SUMMARY:Threshers vs. Tarpons
DESCRIPTION:Threshers vs. Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+xBc4-u\n\nShop: https://stza.co/+xBc4-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Marauders
<2018-08-03 Fri 17:30-20:30>
:PROPERTIES:
:ID:       w2Uf80MM5GeE0bpMhlI8FWv6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Marauders Threshers @ Marauders

Follow on MiLB First Pitch  https //stza.co/+vMea-N

Shop  https //stza.co/+vMea-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Marauders
END:VALARM
DTSTART:20180803T223000Z
DTEND:20180804T013000Z
UID:w2Uf80MM5GeE0bpMhlI8FWv6@stanza.co
SUMMARY:Threshers @ Marauders
DESCRIPTION:Threshers @ Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMea-N\n\nShop: https://stza.co/+vMea-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Marauders
<2018-08-04 Sat 17:30-20:30>
:PROPERTIES:
:ID:       oWnMSFfpVxUpUjSt5x8UJ9Mo@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Marauders Threshers @ Marauders

Follow on MiLB First Pitch  https //stza.co/+vMeb-38

Shop  https //stza.co/+vMeb-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Marauders
END:VALARM
DTSTART:20180804T223000Z
DTEND:20180805T013000Z
UID:oWnMSFfpVxUpUjSt5x8UJ9Mo@stanza.co
SUMMARY:Threshers @ Marauders
DESCRIPTION:Threshers @ Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMeb-38\n\nShop: https://stza.co/+vMeb-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Marauders
<2018-08-05 Sun 12:00-15:00>
:PROPERTIES:
:ID:       9nTnT1weZfP9X06kztytNj1F@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers @ Marauders Threshers @ Marauders

Follow on MiLB First Pitch  https //stza.co/+vMec-u

Shop  https //stza.co/+vMec-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Marauders
END:VALARM
DTSTART:20180805T170000Z
DTEND:20180805T200000Z
UID:9nTnT1weZfP9X06kztytNj1F@stanza.co
SUMMARY:Threshers @ Marauders
DESCRIPTION:Threshers @ Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMec-u\n\nShop: https://stza.co/+vMec-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Tarpons
<2018-08-06 Mon>--<2018-08-05 Sun>
:PROPERTIES:
:ID:       ib7A_m_lGYzyW8v6wW4P9j7t@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Tarpons Threshers @ Tarpons

Follow on MiLB First Pitch  https //stza.co/+vMhm-22

Shop  https //stza.co/+vMhm-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Tarpons
END:VALARM
DTSTART;VALUE=DATE:20180806
DTEND;VALUE=DATE:20180806
UID:ib7A_m_lGYzyW8v6wW4P9j7t@stanza.co
SUMMARY:Threshers @ Tarpons
DESCRIPTION:Threshers @ Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+vMhm-22\n\nShop: https://stza.co/+vMhm-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Tarpons
<2018-08-07 Tue>--<2018-08-06 Mon>
:PROPERTIES:
:ID:       MPzL4yryatxJUKR_zdyrkmGH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Tarpons Threshers @ Tarpons

Follow on MiLB First Pitch  https //stza.co/+viIV-3s

Shop  https //stza.co/+viIV-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Tarpons
END:VALARM
DTSTART;VALUE=DATE:20180807
DTEND;VALUE=DATE:20180807
UID:MPzL4yryatxJUKR_zdyrkmGH@stanza.co
SUMMARY:Threshers @ Tarpons
DESCRIPTION:Threshers @ Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+viIV-3s\n\nShop: https://stza.co/+viIV-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Tarpons
<2018-08-08 Wed>--<2018-08-07 Tue>
:PROPERTIES:
:ID:       yOxrXfS7TnvMdv96y2N4ncgO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers @ Tarpons Threshers @ Tarpons

Follow on MiLB First Pitch  https //stza.co/+vhH2-F

Shop  https //stza.co/+vhH2-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Tarpons
END:VALARM
DTSTART;VALUE=DATE:20180808
DTEND;VALUE=DATE:20180808
UID:yOxrXfS7TnvMdv96y2N4ncgO@stanza.co
SUMMARY:Threshers @ Tarpons
DESCRIPTION:Threshers @ Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+vhH2-F\n\nShop: https://stza.co/+vhH2-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Mets
<2018-08-09 Thu 18:00-21:00>
:PROPERTIES:
:ID:       sNp9CyHY9L0bQPZR7EJV2lMC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Mets Threshers vs. Mets

Follow on MiLB First Pitch  https //stza.co/+xBc7-14

Shop  https //stza.co/+xBc7-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Mets
END:VALARM
DTSTART:20180809T230000Z
DTEND:20180810T020000Z
UID:sNp9CyHY9L0bQPZR7EJV2lMC@stanza.co
SUMMARY:Threshers vs. Mets
DESCRIPTION:Threshers vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xBc7-14\n\nShop: https://stza.co/+xBc7-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Mets
<2018-08-10 Fri 17:15-20:15>
:PROPERTIES:
:ID:       C3YHsDSojwSzDGm1D1lU1uKa@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Mets Threshers vs. Mets

Follow on MiLB First Pitch  https //stza.co/+xBca-1B

Shop  https //stza.co/+xBca-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Mets
END:VALARM
DTSTART:20180810T221500Z
DTEND:20180811T011500Z
UID:C3YHsDSojwSzDGm1D1lU1uKa@stanza.co
SUMMARY:Threshers vs. Mets
DESCRIPTION:Threshers vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xBca-1B\n\nShop: https://stza.co/+xBca-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Mets
<2018-08-11 Sat 17:15-20:15>
:PROPERTIES:
:ID:       VnL7ZXEx9F-K7Yx4-Ul7jU91@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers vs. Mets Threshers vs. Mets

Follow on MiLB First Pitch  https //stza.co/+xBcc-3t

Shop  https //stza.co/+xBcc-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Mets
END:VALARM
DTSTART:20180811T221500Z
DTEND:20180812T011500Z
UID:VnL7ZXEx9F-K7Yx4-Ul7jU91@stanza.co
SUMMARY:Threshers vs. Mets
DESCRIPTION:Threshers vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xBcc-3t\n\nShop: https://stza.co/+xBcc-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Mets
<2018-08-12 Sun 12:00-15:00>
:PROPERTIES:
:ID:       mRS50pGTzeOgV-fUQ6xr4tdd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Mets Threshers vs. Mets

Follow on MiLB First Pitch  https //stza.co/+xBce-2y

Shop  https //stza.co/+xBce-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Mets
END:VALARM
DTSTART:20180812T170000Z
DTEND:20180812T200000Z
UID:mRS50pGTzeOgV-fUQ6xr4tdd@stanza.co
SUMMARY:Threshers vs. Mets
DESCRIPTION:Threshers vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xBce-2y\n\nShop: https://stza.co/+xBce-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Marauders
<2018-08-13 Mon 18:00-21:00>
:PROPERTIES:
:ID:       2grFeaOuiCUduG0rna6NITgb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Marauders Threshers vs. Marauders

Follow on MiLB First Pitch  https //stza.co/+xBcg-3d

Shop  https //stza.co/+xBcg-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Marauders
END:VALARM
DTSTART:20180813T230000Z
DTEND:20180814T020000Z
UID:2grFeaOuiCUduG0rna6NITgb@stanza.co
SUMMARY:Threshers vs. Marauders
DESCRIPTION:Threshers vs. Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+xBcg-3d\n\nShop: https://stza.co/+xBcg-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Marauders
<2018-08-14 Tue 18:00-21:00>
:PROPERTIES:
:ID:       8sjNoeGfLz4IjeOHowfB9m4A@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers vs. Marauders Threshers vs. Marauders

Follow on MiLB First Pitch  https //stza.co/+xBch-1r

Shop  https //stza.co/+xBch-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Marauders
END:VALARM
DTSTART:20180814T230000Z
DTEND:20180815T020000Z
UID:8sjNoeGfLz4IjeOHowfB9m4A@stanza.co
SUMMARY:Threshers vs. Marauders
DESCRIPTION:Threshers vs. Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+xBch-1r\n\nShop: https://stza.co/+xBch-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Marauders
<2018-08-15 Wed 18:00-21:00>
:PROPERTIES:
:ID:       2m0DDq84E6B_Czq63gDwvVN7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Marauders Threshers vs. Marauders

Follow on MiLB First Pitch  https //stza.co/+xBck-20

Shop  https //stza.co/+xBck-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Marauders
END:VALARM
DTSTART:20180815T230000Z
DTEND:20180816T020000Z
UID:2m0DDq84E6B_Czq63gDwvVN7@stanza.co
SUMMARY:Threshers vs. Marauders
DESCRIPTION:Threshers vs. Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+xBck-20\n\nShop: https://stza.co/+xBck-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Marauders
<2018-08-16 Thu 18:00-21:00>
:PROPERTIES:
:ID:       3z0co3oDKNqPlmsk2IpNwJyj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Marauders Threshers vs. Marauders

Follow on MiLB First Pitch  https //stza.co/+xBcm-M

Shop  https //stza.co/+xBcm-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Marauders
END:VALARM
DTSTART:20180816T230000Z
DTEND:20180817T020000Z
UID:3z0co3oDKNqPlmsk2IpNwJyj@stanza.co
SUMMARY:Threshers vs. Marauders
DESCRIPTION:Threshers vs. Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+xBcm-M\n\nShop: https://stza.co/+xBcm-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Miracle
<2018-08-17 Fri 18:00-21:00>
:PROPERTIES:
:ID:       GBZ9cLuHlS7InB167g12aCsB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers @ Miracle Threshers @ Miracle

Follow on MiLB First Pitch  https //stza.co/+xMan-J

Shop  https //stza.co/+xMan-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Miracle
END:VALARM
DTSTART:20180817T230000Z
DTEND:20180818T020000Z
UID:GBZ9cLuHlS7InB167g12aCsB@stanza.co
SUMMARY:Threshers @ Miracle
DESCRIPTION:Threshers @ Miracle\n\nFollow on MiLB First Pitch: https://stza.co/+xMan-J\n\nShop: https://stza.co/+xMan-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Miracle
<2018-08-18 Sat 17:00-20:00>
:PROPERTIES:
:ID:       moBhBEuPBEqXvxOVii0Ny9_4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Miracle Threshers @ Miracle

Follow on MiLB First Pitch  https //stza.co/+xMao-o

Shop  https //stza.co/+xMao-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Miracle
END:VALARM
DTSTART:20180818T220000Z
DTEND:20180819T010000Z
UID:moBhBEuPBEqXvxOVii0Ny9_4@stanza.co
SUMMARY:Threshers @ Miracle
DESCRIPTION:Threshers @ Miracle\n\nFollow on MiLB First Pitch: https://stza.co/+xMao-o\n\nShop: https://stza.co/+xMao-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Miracle
<2018-08-19 Sun 15:00-18:00>
:PROPERTIES:
:ID:       gSLUKjJaaCe8IGFMer1NjtF7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Miracle Threshers @ Miracle

Follow on MiLB First Pitch  https //stza.co/+xMap-p

Shop  https //stza.co/+xMap-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Miracle
END:VALARM
DTSTART:20180819T200000Z
DTEND:20180819T230000Z
UID:gSLUKjJaaCe8IGFMer1NjtF7@stanza.co
SUMMARY:Threshers @ Miracle
DESCRIPTION:Threshers @ Miracle\n\nFollow on MiLB First Pitch: https://stza.co/+xMap-p\n\nShop: https://stza.co/+xMap-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Blue Jays
<2018-08-21 Tue 18:00-21:00>
:PROPERTIES:
:ID:       yTZCDQQzHmTaHwonAfq52WpZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers vs. Blue Jays Threshers vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xBco-3I

Shop  https //stza.co/+xBco-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Blue Jays
END:VALARM
DTSTART:20180821T230000Z
DTEND:20180822T020000Z
UID:yTZCDQQzHmTaHwonAfq52WpZ@stanza.co
SUMMARY:Threshers vs. Blue Jays
DESCRIPTION:Threshers vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xBco-3I\n\nShop: https://stza.co/+xBco-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Blue Jays
<2018-08-22 Wed 18:00-21:00>
:PROPERTIES:
:ID:       OZVr4uEwBcF_6lDnEM3cmJ-v@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Blue Jays Threshers vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xBcp-6

Shop  https //stza.co/+xBcp-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Blue Jays
END:VALARM
DTSTART:20180822T230000Z
DTEND:20180823T020000Z
UID:OZVr4uEwBcF_6lDnEM3cmJ-v@stanza.co
SUMMARY:Threshers vs. Blue Jays
DESCRIPTION:Threshers vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xBcp-6\n\nShop: https://stza.co/+xBcp-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Blue Jays
<2018-08-23 Thu 18:00-21:00>
:PROPERTIES:
:ID:       QBkfJaPg8lPrZGnNsf149sgW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Blue Jays Threshers vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xBcs-1D

Shop  https //stza.co/+xBcs-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Blue Jays
END:VALARM
DTSTART:20180823T230000Z
DTEND:20180824T020000Z
UID:QBkfJaPg8lPrZGnNsf149sgW@stanza.co
SUMMARY:Threshers vs. Blue Jays
DESCRIPTION:Threshers vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xBcs-1D\n\nShop: https://stza.co/+xBcs-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Stone Crabs
<2018-08-24 Fri 17:15-20:15>
:PROPERTIES:
:ID:       ia8OtV5G3PFxDykeP3KXxeiH@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers vs. Stone Crabs Threshers vs. Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+xBcu-J

Shop  https //stza.co/+xBcu-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Stone Crabs
END:VALARM
DTSTART:20180824T221500Z
DTEND:20180825T011500Z
UID:ia8OtV5G3PFxDykeP3KXxeiH@stanza.co
SUMMARY:Threshers vs. Stone Crabs
DESCRIPTION:Threshers vs. Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+xBcu-J\n\nShop: https://stza.co/+xBcu-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Stone Crabs
<2018-08-25 Sat 17:15-20:15>
:PROPERTIES:
:ID:       S3gfAZMW3kN7E8vucMrBx0Ec@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Stone Crabs Threshers vs. Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+xBcw-y

Shop  https //stza.co/+xBcw-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Stone Crabs
END:VALARM
DTSTART:20180825T221500Z
DTEND:20180826T011500Z
UID:S3gfAZMW3kN7E8vucMrBx0Ec@stanza.co
SUMMARY:Threshers vs. Stone Crabs
DESCRIPTION:Threshers vs. Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+xBcw-y\n\nShop: https://stza.co/+xBcw-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers vs. Stone Crabs
<2018-08-26 Sun 12:00-15:00>
:PROPERTIES:
:ID:       XfLG1F2983tBRbSn5fXzukiF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers vs. Stone Crabs Threshers vs. Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+xBcx-k

Shop  https //stza.co/+xBcx-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Threshers vs. Stone Crabs
END:VALARM
DTSTART:20180826T170000Z
DTEND:20180826T200000Z
UID:XfLG1F2983tBRbSn5fXzukiF@stanza.co
SUMMARY:Threshers vs. Stone Crabs
DESCRIPTION:Threshers vs. Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+xBcx-k\n\nShop: https://stza.co/+xBcx-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Hammerheads
<2018-08-27 Mon>--<2018-08-26 Sun>
:PROPERTIES:
:ID:       nALRksK8BzIhY5MyuBKdHZ-n@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers @ Hammerheads Threshers @ Hammerheads

Buy tickets here  https //stza.co/~vMgY

Follow on MiLB First Pitch  https //stza.co/+vMgY-G

Shop  https //stza.co/+vMgY-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Hammerheads
END:VALARM
DTSTART;VALUE=DATE:20180827
DTEND;VALUE=DATE:20180827
UID:nALRksK8BzIhY5MyuBKdHZ-n@stanza.co
SUMMARY:Threshers @ Hammerheads
DESCRIPTION:Threshers @ Hammerheads\n\nBuy tickets here: https://stza.co/~vMgY\n\nFollow on MiLB First Pitch: https://stza.co/+vMgY-G\n\nShop: https://stza.co/+vMgY-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Hammerheads
<2018-08-28 Tue>--<2018-08-27 Mon>
:PROPERTIES:
:ID:       ayF4ZdcL5JKFadda9taiVDz1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Hammerheads Threshers @ Hammerheads

Buy tickets here  https //stza.co/~vMgZ

Follow on MiLB First Pitch  https //stza.co/+vMgZ-1t

Shop  https //stza.co/+vMgZ-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Hammerheads
END:VALARM
DTSTART;VALUE=DATE:20180828
DTEND;VALUE=DATE:20180828
UID:ayF4ZdcL5JKFadda9taiVDz1@stanza.co
SUMMARY:Threshers @ Hammerheads
DESCRIPTION:Threshers @ Hammerheads\n\nBuy tickets here: https://stza.co/~vMgZ\n\nFollow on MiLB First Pitch: https://stza.co/+vMgZ-1t\n\nShop: https://stza.co/+vMgZ-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Hammerheads
<2018-08-29 Wed>--<2018-08-28 Tue>
:PROPERTIES:
:ID:       Y939EoRlLHJ_lx6TBQNuSYiz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Hammerheads Threshers @ Hammerheads

Buy tickets here  https //stza.co/~vMg_

Follow on MiLB First Pitch  https //stza.co/+vMg_-2C

Shop  https //stza.co/+vMg_-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Hammerheads
END:VALARM
DTSTART;VALUE=DATE:20180829
DTEND;VALUE=DATE:20180829
UID:Y939EoRlLHJ_lx6TBQNuSYiz@stanza.co
SUMMARY:Threshers @ Hammerheads
DESCRIPTION:Threshers @ Hammerheads\n\nBuy tickets here: https://stza.co/~vMg_\n\nFollow on MiLB First Pitch: https://stza.co/+vMg_-2C\n\nShop: https://stza.co/+vMg_-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Hammerheads
<2018-08-30 Thu>--<2018-08-29 Wed>
:PROPERTIES:
:ID:       fEuCZotbAeedbZTr5Wt5nlsr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers @ Hammerheads Threshers @ Hammerheads

Buy tickets here  https //stza.co/~vMg$

Follow on MiLB First Pitch  https //stza.co/+vMg$-32

Shop  https //stza.co/+vMg$-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Hammerheads
END:VALARM
DTSTART;VALUE=DATE:20180830
DTEND;VALUE=DATE:20180830
UID:fEuCZotbAeedbZTr5Wt5nlsr@stanza.co
SUMMARY:Threshers @ Hammerheads
DESCRIPTION:Threshers @ Hammerheads\n\nBuy tickets here: https://stza.co/~vMg$\n\nFollow on MiLB First Pitch: https://stza.co/+vMg$-32\n\nShop: https://stza.co/+vMg$-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Miracle
<2018-08-31 Fri 18:00-21:00>
:PROPERTIES:
:ID:       x5C6SPkJ8bPcvoK_lMCp1GVE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Miracle Threshers @ Miracle

Follow on MiLB First Pitch  https //stza.co/+xMaq-2p

Shop  https //stza.co/+xMaq-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Miracle
END:VALARM
DTSTART:20180831T230000Z
DTEND:20180901T020000Z
UID:x5C6SPkJ8bPcvoK_lMCp1GVE@stanza.co
SUMMARY:Threshers @ Miracle
DESCRIPTION:Threshers @ Miracle\n\nFollow on MiLB First Pitch: https://stza.co/+xMaq-2p\n\nShop: https://stza.co/+xMaq-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Miracle
<2018-09-01 Sat 17:00-20:00>
:PROPERTIES:
:ID:       FZYK7muW_gwsWqdULdDuIAj8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Threshers @ Miracle Threshers @ Miracle

Follow on MiLB First Pitch  https //stza.co/+xMar-2B

Shop  https //stza.co/+xMar-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Miracle
END:VALARM
DTSTART:20180901T220000Z
DTEND:20180902T010000Z
UID:FZYK7muW_gwsWqdULdDuIAj8@stanza.co
SUMMARY:Threshers @ Miracle
DESCRIPTION:Threshers @ Miracle\n\nFollow on MiLB First Pitch: https://stza.co/+xMar-2B\n\nShop: https://stza.co/+xMar-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
* Threshers @ Miracle
<2018-09-02 Sun 11:00-14:00>
:PROPERTIES:
:ID:       HKE0Sk4wIBwMfCCNBSkftnjz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Threshers @ Miracle Threshers @ Miracle

Follow on MiLB First Pitch  https //stza.co/+xMas-1r

Shop  https //stza.co/+xMas-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Threshers @ Miracle
END:VALARM
DTSTART:20180902T160000Z
DTEND:20180902T190000Z
UID:HKE0Sk4wIBwMfCCNBSkftnjz@stanza.co
SUMMARY:Threshers @ Miracle
DESCRIPTION:Threshers @ Miracle\n\nFollow on MiLB First Pitch: https://stza.co/+xMas-1r\n\nShop: https://stza.co/+xMas-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144514Z
LAST-MODIFIED:20180213T144514Z
TRANSP:OPAQUE
END:VEVENT
