#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Dragons @ Hot Rods
<2018-04-05 Thu 18:35-21:35>
:PROPERTIES:
:ID:       RW9rIdr_dzF1utoBCXTYqym0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Hot Rods Dragons @ Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vM_A-3b

Shop  https //stza.co/+vM_A-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Hot Rods
END:VALARM
DTSTART:20180405T233500Z
DTEND:20180406T023500Z
UID:RW9rIdr_dzF1utoBCXTYqym0@stanza.co
SUMMARY:Dragons @ Hot Rods
DESCRIPTION:Dragons @ Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vM_A-3b\n\nShop: https://stza.co/+vM_A-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Hot Rods
<2018-04-06 Fri 18:35-21:35>
:PROPERTIES:
:ID:       WD725XvFx9v-qVaDIKX0T0bd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons @ Hot Rods Dragons @ Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vM_B-G

Shop  https //stza.co/+vM_B-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Hot Rods
END:VALARM
DTSTART:20180406T233500Z
DTEND:20180407T023500Z
UID:WD725XvFx9v-qVaDIKX0T0bd@stanza.co
SUMMARY:Dragons @ Hot Rods
DESCRIPTION:Dragons @ Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vM_B-G\n\nShop: https://stza.co/+vM_B-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Hot Rods
<2018-04-07 Sat 18:00-21:00>
:PROPERTIES:
:ID:       v2kEk-1bFhkudtEyvfapCVOo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Hot Rods Dragons vs. Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vM_Q-A

Shop  https //stza.co/+vM_Q-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Hot Rods
END:VALARM
DTSTART:20180407T230000Z
DTEND:20180408T020000Z
UID:v2kEk-1bFhkudtEyvfapCVOo@stanza.co
SUMMARY:Dragons vs. Hot Rods
DESCRIPTION:Dragons vs. Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vM_Q-A\n\nShop: https://stza.co/+vM_Q-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Hot Rods
<2018-04-08 Sun 13:00-16:00>
:PROPERTIES:
:ID:       noCAyWsHkIF7B6bkAPZSEPpT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Hot Rods Dragons vs. Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vM_S-2x

Shop  https //stza.co/+vM_S-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Hot Rods
END:VALARM
DTSTART:20180408T180000Z
DTEND:20180408T210000Z
UID:noCAyWsHkIF7B6bkAPZSEPpT@stanza.co
SUMMARY:Dragons vs. Hot Rods
DESCRIPTION:Dragons vs. Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vM_S-2x\n\nShop: https://stza.co/+vM_S-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Captains
<2018-04-09 Mon 18:00-21:00>
:PROPERTIES:
:ID:       dAfqXxvPp9v8fiJ81NZ7QkNe@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons vs. Captains Dragons vs. Captains

Follow on MiLB First Pitch  https //stza.co/+vM_T-O

Shop  https //stza.co/+vM_T-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Captains
END:VALARM
DTSTART:20180409T230000Z
DTEND:20180410T020000Z
UID:dAfqXxvPp9v8fiJ81NZ7QkNe@stanza.co
SUMMARY:Dragons vs. Captains
DESCRIPTION:Dragons vs. Captains\n\nFollow on MiLB First Pitch: https://stza.co/+vM_T-O\n\nShop: https://stza.co/+vM_T-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Captains
<2018-04-10 Tue 18:00-21:00>
:PROPERTIES:
:ID:       JVSwdYRsFo_knl3O2AQwhmJm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Captains Dragons vs. Captains

Follow on MiLB First Pitch  https //stza.co/+vM_W-2I

Shop  https //stza.co/+vM_W-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Captains
END:VALARM
DTSTART:20180410T230000Z
DTEND:20180411T020000Z
UID:JVSwdYRsFo_knl3O2AQwhmJm@stanza.co
SUMMARY:Dragons vs. Captains
DESCRIPTION:Dragons vs. Captains\n\nFollow on MiLB First Pitch: https://stza.co/+vM_W-2I\n\nShop: https://stza.co/+vM_W-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Captains
<2018-04-11 Wed 18:00-21:00>
:PROPERTIES:
:ID:       8K3CSwDR7nOVt3P13EUbrxxG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Captains Dragons vs. Captains

Follow on MiLB First Pitch  https //stza.co/+vM_Y-2o

Shop  https //stza.co/+vM_Y-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Captains
END:VALARM
DTSTART:20180411T230000Z
DTEND:20180412T020000Z
UID:8K3CSwDR7nOVt3P13EUbrxxG@stanza.co
SUMMARY:Dragons vs. Captains
DESCRIPTION:Dragons vs. Captains\n\nFollow on MiLB First Pitch: https://stza.co/+vM_Y-2o\n\nShop: https://stza.co/+vM_Y-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Captains
<2018-04-12 Thu 18:00-21:00>
:PROPERTIES:
:ID:       -cLCbm_csQ-Ql7fVYkqUKH52@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons vs. Captains Dragons vs. Captains

Follow on MiLB First Pitch  https //stza.co/+vM__-3p

Shop  https //stza.co/+vM__-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Captains
END:VALARM
DTSTART:20180412T230000Z
DTEND:20180413T020000Z
UID:-cLCbm_csQ-Ql7fVYkqUKH52@stanza.co
SUMMARY:Dragons vs. Captains
DESCRIPTION:Dragons vs. Captains\n\nFollow on MiLB First Pitch: https://stza.co/+vM__-3p\n\nShop: https://stza.co/+vM__-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Loons
<2018-04-13 Fri 17:05-20:05>
:PROPERTIES:
:ID:       pk5mPhXkkb0u8ZgVZyGoJJ21@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Loons Dragons @ Loons

Follow on MiLB First Pitch  https //stza.co/+vN15-3f

Shop  https //stza.co/+vN15-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Loons
END:VALARM
DTSTART:20180413T220500Z
DTEND:20180414T010500Z
UID:pk5mPhXkkb0u8ZgVZyGoJJ21@stanza.co
SUMMARY:Dragons @ Loons
DESCRIPTION:Dragons @ Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vN15-3f\n\nShop: https://stza.co/+vN15-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Loons
<2018-04-14 Sat 13:05-16:05>
:PROPERTIES:
:ID:       _enHq59doaxMht63aqlTaYy1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Loons Dragons @ Loons

Follow on MiLB First Pitch  https //stza.co/+vN16-l

Shop  https //stza.co/+vN16-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Loons
END:VALARM
DTSTART:20180414T180500Z
DTEND:20180414T210500Z
UID:_enHq59doaxMht63aqlTaYy1@stanza.co
SUMMARY:Dragons @ Loons
DESCRIPTION:Dragons @ Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vN16-l\n\nShop: https://stza.co/+vN16-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Loons
<2018-04-15 Sun 13:05-16:05>
:PROPERTIES:
:ID:       5nvGAwbyQxBVmRYb2NE3F8-J@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons @ Loons Dragons @ Loons

Follow on MiLB First Pitch  https //stza.co/+vN17-3v

Shop  https //stza.co/+vN17-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Loons
END:VALARM
DTSTART:20180415T180500Z
DTEND:20180415T210500Z
UID:5nvGAwbyQxBVmRYb2NE3F8-J@stanza.co
SUMMARY:Dragons @ Loons
DESCRIPTION:Dragons @ Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vN17-3v\n\nShop: https://stza.co/+vN17-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Cubs
<2018-04-17 Tue 18:00-21:00>
:PROPERTIES:
:ID:       8I64ocuV9hT5UyRrc-OmXUM4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Cubs Dragons vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+vM$0-1P

Shop  https //stza.co/+vM$0-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Cubs
END:VALARM
DTSTART:20180417T230000Z
DTEND:20180418T020000Z
UID:8I64ocuV9hT5UyRrc-OmXUM4@stanza.co
SUMMARY:Dragons vs. Cubs
DESCRIPTION:Dragons vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vM$0-1P\n\nShop: https://stza.co/+vM$0-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Cubs
<2018-04-18 Wed 18:00-21:00>
:PROPERTIES:
:ID:       OFoYff9Pb_ofjYBpHL-i6wyE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Cubs Dragons vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+vM$1-2M

Shop  https //stza.co/+vM$1-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Cubs
END:VALARM
DTSTART:20180418T230000Z
DTEND:20180419T020000Z
UID:OFoYff9Pb_ofjYBpHL-i6wyE@stanza.co
SUMMARY:Dragons vs. Cubs
DESCRIPTION:Dragons vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vM$1-2M\n\nShop: https://stza.co/+vM$1-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Cubs
<2018-04-19 Thu 18:00-21:00>
:PROPERTIES:
:ID:       AIwq3HONBzoe10PQGEpOZYLL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons vs. Cubs Dragons vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+vM$4-32

Shop  https //stza.co/+vM$4-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Cubs
END:VALARM
DTSTART:20180419T230000Z
DTEND:20180420T020000Z
UID:AIwq3HONBzoe10PQGEpOZYLL@stanza.co
SUMMARY:Dragons vs. Cubs
DESCRIPTION:Dragons vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vM$4-32\n\nShop: https://stza.co/+vM$4-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ TinCaps
<2018-04-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       hdwu0K79048rGPQ46zBWB2vc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ TinCaps Dragons @ TinCaps

Follow on MiLB First Pitch  https //stza.co/+vN0$-3O

Shop  https //stza.co/+vN0$-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ TinCaps
END:VALARM
DTSTART:20180420T230500Z
DTEND:20180421T020500Z
UID:hdwu0K79048rGPQ46zBWB2vc@stanza.co
SUMMARY:Dragons @ TinCaps
DESCRIPTION:Dragons @ TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+vN0$-3O\n\nShop: https://stza.co/+vN0$-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ TinCaps
<2018-04-21 Sat 12:05-15:05>
:PROPERTIES:
:ID:       _VM54HW7tkEwcXZQJcJAuUuW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ TinCaps Dragons @ TinCaps

Follow on MiLB First Pitch  https //stza.co/+xBrf-3l

Shop  https //stza.co/+xBrf-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ TinCaps
END:VALARM
DTSTART:20180421T170500Z
DTEND:20180421T200500Z
UID:_VM54HW7tkEwcXZQJcJAuUuW@stanza.co
SUMMARY:Dragons @ TinCaps
DESCRIPTION:Dragons @ TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+xBrf-3l\n\nShop: https://stza.co/+xBrf-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ TinCaps
<2018-04-22 Sun 12:05-15:05>
:PROPERTIES:
:ID:       xt0LIA553Qh1BZV_gnsfynnG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons @ TinCaps Dragons @ TinCaps

Follow on MiLB First Pitch  https //stza.co/+vN11-3r

Shop  https //stza.co/+vN11-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ TinCaps
END:VALARM
DTSTART:20180422T170500Z
DTEND:20180422T200500Z
UID:xt0LIA553Qh1BZV_gnsfynnG@stanza.co
SUMMARY:Dragons @ TinCaps
DESCRIPTION:Dragons @ TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+vN11-3r\n\nShop: https://stza.co/+vN11-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Lugnuts
<2018-04-23 Mon 18:05-21:05>
:PROPERTIES:
:ID:       pDFREyKshSnWmBEQWk-MVb8e@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Lugnuts Dragons @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vN1l-1f

Shop  https //stza.co/+vN1l-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Lugnuts
END:VALARM
DTSTART:20180423T230500Z
DTEND:20180424T020500Z
UID:pDFREyKshSnWmBEQWk-MVb8e@stanza.co
SUMMARY:Dragons @ Lugnuts
DESCRIPTION:Dragons @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vN1l-1f\n\nShop: https://stza.co/+vN1l-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Lugnuts
<2018-04-24 Tue 18:05-21:05>
:PROPERTIES:
:ID:       5MnLd2Z94gq_nEd44vO5fDlW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Lugnuts Dragons @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vN1m-1N

Shop  https //stza.co/+vN1m-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Lugnuts
END:VALARM
DTSTART:20180424T230500Z
DTEND:20180425T020500Z
UID:5MnLd2Z94gq_nEd44vO5fDlW@stanza.co
SUMMARY:Dragons @ Lugnuts
DESCRIPTION:Dragons @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vN1m-1N\n\nShop: https://stza.co/+vN1m-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Lugnuts
<2018-04-25 Wed 18:05-21:05>
:PROPERTIES:
:ID:       mNlmVmNLwYhv_nF_QNBCtEWP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons @ Lugnuts Dragons @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vN1n-1V

Shop  https //stza.co/+vN1n-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Lugnuts
END:VALARM
DTSTART:20180425T230500Z
DTEND:20180426T020500Z
UID:mNlmVmNLwYhv_nF_QNBCtEWP@stanza.co
SUMMARY:Dragons @ Lugnuts
DESCRIPTION:Dragons @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vN1n-1V\n\nShop: https://stza.co/+vN1n-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Lugnuts
<2018-04-26 Thu 18:05-21:05>
:PROPERTIES:
:ID:       2boBSWAi9H3OinUd2t79NqG6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Lugnuts Dragons @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vN1o-36

Shop  https //stza.co/+vN1o-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Lugnuts
END:VALARM
DTSTART:20180426T230500Z
DTEND:20180427T020500Z
UID:2boBSWAi9H3OinUd2t79NqG6@stanza.co
SUMMARY:Dragons @ Lugnuts
DESCRIPTION:Dragons @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vN1o-36\n\nShop: https://stza.co/+vN1o-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. TinCaps
<2018-04-27 Fri 18:00-21:00>
:PROPERTIES:
:ID:       4-KRproWq31DwdriT9hOoBnq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. TinCaps Dragons vs. TinCaps

Follow on MiLB First Pitch  https //stza.co/+vM$6-3P

Shop  https //stza.co/+vM$6-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. TinCaps
END:VALARM
DTSTART:20180427T230000Z
DTEND:20180428T020000Z
UID:4-KRproWq31DwdriT9hOoBnq@stanza.co
SUMMARY:Dragons vs. TinCaps
DESCRIPTION:Dragons vs. TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+vM$6-3P\n\nShop: https://stza.co/+vM$6-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. TinCaps
<2018-04-28 Sat 18:00-21:00>
:PROPERTIES:
:ID:       jKwL12aq8FAPSbLylnw6V13Z@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons vs. TinCaps Dragons vs. TinCaps

Follow on MiLB First Pitch  https //stza.co/+vM$8-K

Shop  https //stza.co/+vM$8-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. TinCaps
END:VALARM
DTSTART:20180428T230000Z
DTEND:20180429T020000Z
UID:jKwL12aq8FAPSbLylnw6V13Z@stanza.co
SUMMARY:Dragons vs. TinCaps
DESCRIPTION:Dragons vs. TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+vM$8-K\n\nShop: https://stza.co/+vM$8-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. TinCaps
<2018-04-29 Sun 13:00-16:00>
:PROPERTIES:
:ID:       GVHTT7QV7STOG-o7eQxrbQjh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. TinCaps Dragons vs. TinCaps

Follow on MiLB First Pitch  https //stza.co/+vM$9-u

Shop  https //stza.co/+vM$9-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. TinCaps
END:VALARM
DTSTART:20180429T180000Z
DTEND:20180429T210000Z
UID:GVHTT7QV7STOG-o7eQxrbQjh@stanza.co
SUMMARY:Dragons vs. TinCaps
DESCRIPTION:Dragons vs. TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+vM$9-u\n\nShop: https://stza.co/+vM$9-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Bees
<2018-05-01 Tue 18:30-21:30>
:PROPERTIES:
:ID:       OPqoP-HuZf2FXlbG8KAzbS-5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Bees Dragons @ Bees

Follow on MiLB First Pitch  https //stza.co/+xBr2-2U

Shop  https //stza.co/+xBr2-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Bees
END:VALARM
DTSTART:20180501T233000Z
DTEND:20180502T023000Z
UID:OPqoP-HuZf2FXlbG8KAzbS-5@stanza.co
SUMMARY:Dragons @ Bees
DESCRIPTION:Dragons @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xBr2-2U\n\nShop: https://stza.co/+xBr2-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Bees
<2018-05-02 Wed 18:30-21:30>
:PROPERTIES:
:ID:       rABb9robzG8qgzFDNqNODZIW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons @ Bees Dragons @ Bees

Follow on MiLB First Pitch  https //stza.co/+xBr3-3_

Shop  https //stza.co/+xBr3-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Bees
END:VALARM
DTSTART:20180502T233000Z
DTEND:20180503T023000Z
UID:rABb9robzG8qgzFDNqNODZIW@stanza.co
SUMMARY:Dragons @ Bees
DESCRIPTION:Dragons @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xBr3-3_\n\nShop: https://stza.co/+xBr3-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Bees
<2018-05-03 Thu 11:30-14:30>
:PROPERTIES:
:ID:       RozMIG0t9t5q702j9XirKLt3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Bees Dragons @ Bees

Follow on MiLB First Pitch  https //stza.co/+xBr4-2

Shop  https //stza.co/+xBr4-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Bees
END:VALARM
DTSTART:20180503T163000Z
DTEND:20180503T193000Z
UID:RozMIG0t9t5q702j9XirKLt3@stanza.co
SUMMARY:Dragons @ Bees
DESCRIPTION:Dragons @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xBr4-2\n\nShop: https://stza.co/+xBr4-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ LumberKings
<2018-05-04 Fri 18:30-21:30>
:PROPERTIES:
:ID:       y1iFKrIHM-NqeB12dPpzzX82@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ LumberKings Dragons @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vM_M-1J

Shop  https //stza.co/+vM_M-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ LumberKings
END:VALARM
DTSTART:20180504T233000Z
DTEND:20180505T023000Z
UID:y1iFKrIHM-NqeB12dPpzzX82@stanza.co
SUMMARY:Dragons @ LumberKings
DESCRIPTION:Dragons @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vM_M-1J\n\nShop: https://stza.co/+vM_M-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ LumberKings
<2018-05-05 Sat 18:30-21:30>
:PROPERTIES:
:ID:       mrM8g4JKkAO5GYCfFQejLdcT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons @ LumberKings Dragons @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vM_N-3L

Shop  https //stza.co/+vM_N-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ LumberKings
END:VALARM
DTSTART:20180505T233000Z
DTEND:20180506T023000Z
UID:mrM8g4JKkAO5GYCfFQejLdcT@stanza.co
SUMMARY:Dragons @ LumberKings
DESCRIPTION:Dragons @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vM_N-3L\n\nShop: https://stza.co/+vM_N-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ LumberKings
<2018-05-06 Sun 14:00-17:00>
:PROPERTIES:
:ID:       A075vKWLS7wun3AF03YEcW8d@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ LumberKings Dragons @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vM_O-1y

Shop  https //stza.co/+vM_O-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ LumberKings
END:VALARM
DTSTART:20180506T190000Z
DTEND:20180506T220000Z
UID:A075vKWLS7wun3AF03YEcW8d@stanza.co
SUMMARY:Dragons @ LumberKings
DESCRIPTION:Dragons @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vM_O-1y\n\nShop: https://stza.co/+vM_O-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Kernels
<2018-05-07 Mon 18:00-21:00>
:PROPERTIES:
:ID:       0_kKNY_J9ZcZCESaIpk5--RA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Kernels Dragons vs. Kernels

Follow on MiLB First Pitch  https //stza.co/+vM$b-28

Shop  https //stza.co/+vM$b-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Kernels
END:VALARM
DTSTART:20180507T230000Z
DTEND:20180508T020000Z
UID:0_kKNY_J9ZcZCESaIpk5--RA@stanza.co
SUMMARY:Dragons vs. Kernels
DESCRIPTION:Dragons vs. Kernels\n\nFollow on MiLB First Pitch: https://stza.co/+vM$b-28\n\nShop: https://stza.co/+vM$b-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Kernels
<2018-05-08 Tue 18:00-21:00>
:PROPERTIES:
:ID:       WwdVz_PwVtWFqy2PgjoK2p1Q@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons vs. Kernels Dragons vs. Kernels

Follow on MiLB First Pitch  https //stza.co/+vM$e-9

Shop  https //stza.co/+vM$e-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Kernels
END:VALARM
DTSTART:20180508T230000Z
DTEND:20180509T020000Z
UID:WwdVz_PwVtWFqy2PgjoK2p1Q@stanza.co
SUMMARY:Dragons vs. Kernels
DESCRIPTION:Dragons vs. Kernels\n\nFollow on MiLB First Pitch: https://stza.co/+vM$e-9\n\nShop: https://stza.co/+vM$e-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Kernels
<2018-05-09 Wed 18:00-21:00>
:PROPERTIES:
:ID:       3ioSMgNyTNdP3YnyjlbOX-M8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Kernels Dragons vs. Kernels

Follow on MiLB First Pitch  https //stza.co/+vM$f-1S

Shop  https //stza.co/+vM$f-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Kernels
END:VALARM
DTSTART:20180509T230000Z
DTEND:20180510T020000Z
UID:3ioSMgNyTNdP3YnyjlbOX-M8@stanza.co
SUMMARY:Dragons vs. Kernels
DESCRIPTION:Dragons vs. Kernels\n\nFollow on MiLB First Pitch: https://stza.co/+vM$f-1S\n\nShop: https://stza.co/+vM$f-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Chiefs
<2018-05-10 Thu 18:00-21:00>
:PROPERTIES:
:ID:       o_TtWyHYuwM3PgRjmfxhJ_Ca@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Chiefs Dragons vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+vM$i-3C

Shop  https //stza.co/+vM$i-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Chiefs
END:VALARM
DTSTART:20180510T230000Z
DTEND:20180511T020000Z
UID:o_TtWyHYuwM3PgRjmfxhJ_Ca@stanza.co
SUMMARY:Dragons vs. Chiefs
DESCRIPTION:Dragons vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+vM$i-3C\n\nShop: https://stza.co/+vM$i-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Chiefs
<2018-05-11 Fri 18:00-21:00>
:PROPERTIES:
:ID:       eA8WwhYN6xCIKGwZSawlOYCz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons vs. Chiefs Dragons vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+vM$j-1x

Shop  https //stza.co/+vM$j-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Chiefs
END:VALARM
DTSTART:20180511T230000Z
DTEND:20180512T020000Z
UID:eA8WwhYN6xCIKGwZSawlOYCz@stanza.co
SUMMARY:Dragons vs. Chiefs
DESCRIPTION:Dragons vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+vM$j-1x\n\nShop: https://stza.co/+vM$j-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Chiefs
<2018-05-12 Sat 18:00-21:00>
:PROPERTIES:
:ID:       _wVY167-Hp3Fli9bGHFlSXb5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Chiefs Dragons vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+vM$l-1x

Shop  https //stza.co/+vM$l-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Chiefs
END:VALARM
DTSTART:20180512T230000Z
DTEND:20180513T020000Z
UID:_wVY167-Hp3Fli9bGHFlSXb5@stanza.co
SUMMARY:Dragons vs. Chiefs
DESCRIPTION:Dragons vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+vM$l-1x\n\nShop: https://stza.co/+vM$l-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Lugnuts
<2018-05-14 Mon 18:05-21:05>
:PROPERTIES:
:ID:       nQzfQnUYjOOicqbKmHjalfcQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Lugnuts Dragons @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vN1p-3Z

Shop  https //stza.co/+vN1p-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Lugnuts
END:VALARM
DTSTART:20180514T230500Z
DTEND:20180515T020500Z
UID:nQzfQnUYjOOicqbKmHjalfcQ@stanza.co
SUMMARY:Dragons @ Lugnuts
DESCRIPTION:Dragons @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vN1p-3Z\n\nShop: https://stza.co/+vN1p-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Lugnuts
<2018-05-15 Tue 09:35-12:35>
:PROPERTIES:
:ID:       00NypClZx8lYZVTFr11dcxdX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons @ Lugnuts Dragons @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vN1q-_

Shop  https //stza.co/+vN1q-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Lugnuts
END:VALARM
DTSTART:20180515T143500Z
DTEND:20180515T173500Z
UID:00NypClZx8lYZVTFr11dcxdX@stanza.co
SUMMARY:Dragons @ Lugnuts
DESCRIPTION:Dragons @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vN1q-_\n\nShop: https://stza.co/+vN1q-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Lugnuts
<2018-05-16 Wed 18:05-21:05>
:PROPERTIES:
:ID:       c9K2cyAR63VmEhefYIrUbko1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Lugnuts Dragons @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vN1r-q

Shop  https //stza.co/+vN1r-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Lugnuts
END:VALARM
DTSTART:20180516T230500Z
DTEND:20180517T020500Z
UID:c9K2cyAR63VmEhefYIrUbko1@stanza.co
SUMMARY:Dragons @ Lugnuts
DESCRIPTION:Dragons @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vN1r-q\n\nShop: https://stza.co/+vN1r-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Lugnuts
<2018-05-17 Thu 18:05-21:05>
:PROPERTIES:
:ID:       ve85gwUNWaVLuHWisiZqRiHj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Lugnuts Dragons @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vN1s-d

Shop  https //stza.co/+vN1s-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Lugnuts
END:VALARM
DTSTART:20180517T230500Z
DTEND:20180518T020500Z
UID:ve85gwUNWaVLuHWisiZqRiHj@stanza.co
SUMMARY:Dragons @ Lugnuts
DESCRIPTION:Dragons @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vN1s-d\n\nShop: https://stza.co/+vN1s-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Loons
<2018-05-18 Fri 18:00-21:00>
:PROPERTIES:
:ID:       bTOCNtT2zibLaIbkVqeQRITa@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons vs. Loons Dragons vs. Loons

Follow on MiLB First Pitch  https //stza.co/+vM$o-2h

Shop  https //stza.co/+vM$o-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Loons
END:VALARM
DTSTART:20180518T230000Z
DTEND:20180519T020000Z
UID:bTOCNtT2zibLaIbkVqeQRITa@stanza.co
SUMMARY:Dragons vs. Loons
DESCRIPTION:Dragons vs. Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vM$o-2h\n\nShop: https://stza.co/+vM$o-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Loons
<2018-05-19 Sat 18:00-21:00>
:PROPERTIES:
:ID:       xjzhLkKU5rMdq9hefVGPF_48@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Loons Dragons vs. Loons

Follow on MiLB First Pitch  https //stza.co/+vM$q-2c

Shop  https //stza.co/+vM$q-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Loons
END:VALARM
DTSTART:20180519T230000Z
DTEND:20180520T020000Z
UID:xjzhLkKU5rMdq9hefVGPF_48@stanza.co
SUMMARY:Dragons vs. Loons
DESCRIPTION:Dragons vs. Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vM$q-2c\n\nShop: https://stza.co/+vM$q-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Loons
<2018-05-20 Sun 13:00-16:00>
:PROPERTIES:
:ID:       n76fu5Mn0Ofn_yL4dziOOwfK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Loons Dragons vs. Loons

Follow on MiLB First Pitch  https //stza.co/+vM$r-A

Shop  https //stza.co/+vM$r-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Loons
END:VALARM
DTSTART:20180520T180000Z
DTEND:20180520T210000Z
UID:n76fu5Mn0Ofn_yL4dziOOwfK@stanza.co
SUMMARY:Dragons vs. Loons
DESCRIPTION:Dragons vs. Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vM$r-A\n\nShop: https://stza.co/+vM$r-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Captains
<2018-05-21 Mon 18:00-21:00>
:PROPERTIES:
:ID:       cGrUIigVZMkFoYbY7oWa6xJ_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons vs. Captains Dragons vs. Captains

Follow on MiLB First Pitch  https //stza.co/+vM$t-3K

Shop  https //stza.co/+vM$t-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Captains
END:VALARM
DTSTART:20180521T230000Z
DTEND:20180522T020000Z
UID:cGrUIigVZMkFoYbY7oWa6xJ_@stanza.co
SUMMARY:Dragons vs. Captains
DESCRIPTION:Dragons vs. Captains\n\nFollow on MiLB First Pitch: https://stza.co/+vM$t-3K\n\nShop: https://stza.co/+vM$t-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Captains
<2018-05-22 Tue 18:00-21:00>
:PROPERTIES:
:ID:       XCRG2huF1XPfZsZ1nen5QTw_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Captains Dragons vs. Captains

Follow on MiLB First Pitch  https //stza.co/+vM$w-1E

Shop  https //stza.co/+vM$w-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Captains
END:VALARM
DTSTART:20180522T230000Z
DTEND:20180523T020000Z
UID:XCRG2huF1XPfZsZ1nen5QTw_@stanza.co
SUMMARY:Dragons vs. Captains
DESCRIPTION:Dragons vs. Captains\n\nFollow on MiLB First Pitch: https://stza.co/+vM$w-1E\n\nShop: https://stza.co/+vM$w-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Captains
<2018-05-23 Wed 18:00-21:00>
:PROPERTIES:
:ID:       9nHhMbEJ9tDq8LQIQHyJmQF8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Captains Dragons vs. Captains

Follow on MiLB First Pitch  https //stza.co/+vM$x-18

Shop  https //stza.co/+vM$x-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Captains
END:VALARM
DTSTART:20180523T230000Z
DTEND:20180524T020000Z
UID:9nHhMbEJ9tDq8LQIQHyJmQF8@stanza.co
SUMMARY:Dragons vs. Captains
DESCRIPTION:Dragons vs. Captains\n\nFollow on MiLB First Pitch: https://stza.co/+vM$x-18\n\nShop: https://stza.co/+vM$x-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Captains
<2018-05-24 Thu 18:00-21:00>
:PROPERTIES:
:ID:       hKR7wqkj1kg6xEDDBXUiL3rB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons vs. Captains Dragons vs. Captains

Follow on MiLB First Pitch  https //stza.co/+vM$A-1b

Shop  https //stza.co/+vM$A-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Captains
END:VALARM
DTSTART:20180524T230000Z
DTEND:20180525T020000Z
UID:hKR7wqkj1kg6xEDDBXUiL3rB@stanza.co
SUMMARY:Dragons vs. Captains
DESCRIPTION:Dragons vs. Captains\n\nFollow on MiLB First Pitch: https://stza.co/+vM$A-1b\n\nShop: https://stza.co/+vM$A-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Hot Rods
<2018-05-25 Fri 18:35-21:35>
:PROPERTIES:
:ID:       etCXh3Nr4HK0l-6hHeHpyRuL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Hot Rods Dragons @ Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vM_C-9

Shop  https //stza.co/+vM_C-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Hot Rods
END:VALARM
DTSTART:20180525T233500Z
DTEND:20180526T023500Z
UID:etCXh3Nr4HK0l-6hHeHpyRuL@stanza.co
SUMMARY:Dragons @ Hot Rods
DESCRIPTION:Dragons @ Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vM_C-9\n\nShop: https://stza.co/+vM_C-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Hot Rods
<2018-05-26 Sat 18:35-21:35>
:PROPERTIES:
:ID:       xaq3S_IpQdhDA8joFPP-WXON@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Hot Rods Dragons @ Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vM_D-1_

Shop  https //stza.co/+vM_D-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Hot Rods
END:VALARM
DTSTART:20180526T233500Z
DTEND:20180527T023500Z
UID:xaq3S_IpQdhDA8joFPP-WXON@stanza.co
SUMMARY:Dragons @ Hot Rods
DESCRIPTION:Dragons @ Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vM_D-1_\n\nShop: https://stza.co/+vM_D-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Hot Rods
<2018-05-27 Sun 18:35-21:35>
:PROPERTIES:
:ID:       7vvz2UkpW-Sh0NSv31WclMTa@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons @ Hot Rods Dragons @ Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vM_E-1y

Shop  https //stza.co/+vM_E-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Hot Rods
END:VALARM
DTSTART:20180527T233500Z
DTEND:20180528T023500Z
UID:7vvz2UkpW-Sh0NSv31WclMTa@stanza.co
SUMMARY:Dragons @ Hot Rods
DESCRIPTION:Dragons @ Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vM_E-1y\n\nShop: https://stza.co/+vM_E-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Hot Rods
<2018-05-28 Mon 12:05-15:05>
:PROPERTIES:
:ID:       jN_DSNlsPQONQBs9KWKEVJUU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Hot Rods Dragons @ Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vM_F-1K

Shop  https //stza.co/+vM_F-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Hot Rods
END:VALARM
DTSTART:20180528T170500Z
DTEND:20180528T200500Z
UID:jN_DSNlsPQONQBs9KWKEVJUU@stanza.co
SUMMARY:Dragons @ Hot Rods
DESCRIPTION:Dragons @ Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vM_F-1K\n\nShop: https://stza.co/+vM_F-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Whitecaps
<2018-05-29 Tue 18:00-21:00>
:PROPERTIES:
:ID:       wMRTnfaPSKdDXL3TtQoSwyj8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Whitecaps Dragons vs. Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vM$C-x

Shop  https //stza.co/+vM$C-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Whitecaps
END:VALARM
DTSTART:20180529T230000Z
DTEND:20180530T020000Z
UID:wMRTnfaPSKdDXL3TtQoSwyj8@stanza.co
SUMMARY:Dragons vs. Whitecaps
DESCRIPTION:Dragons vs. Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vM$C-x\n\nShop: https://stza.co/+vM$C-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Whitecaps
<2018-05-30 Wed 18:00-21:00>
:PROPERTIES:
:ID:       BoZsZ4KcFb5eg4G1jhW52rbS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons vs. Whitecaps Dragons vs. Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vM$E-1t

Shop  https //stza.co/+vM$E-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Whitecaps
END:VALARM
DTSTART:20180530T230000Z
DTEND:20180531T020000Z
UID:BoZsZ4KcFb5eg4G1jhW52rbS@stanza.co
SUMMARY:Dragons vs. Whitecaps
DESCRIPTION:Dragons vs. Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vM$E-1t\n\nShop: https://stza.co/+vM$E-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Whitecaps
<2018-05-31 Thu 18:00-21:00>
:PROPERTIES:
:ID:       pSxer76ADj9e7QiZV0NfUToK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Whitecaps Dragons vs. Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vM$F-2y

Shop  https //stza.co/+vM$F-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Whitecaps
END:VALARM
DTSTART:20180531T230000Z
DTEND:20180601T020000Z
UID:pSxer76ADj9e7QiZV0NfUToK@stanza.co
SUMMARY:Dragons vs. Whitecaps
DESCRIPTION:Dragons vs. Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vM$F-2y\n\nShop: https://stza.co/+vM$F-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Lugnuts
<2018-06-01 Fri 18:00-21:00>
:PROPERTIES:
:ID:       WDVfr8J0U9i7uQ0k3B4SEZ8k@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Lugnuts Dragons vs. Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vM$I-w

Shop  https //stza.co/+vM$I-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Lugnuts
END:VALARM
DTSTART:20180601T230000Z
DTEND:20180602T020000Z
UID:WDVfr8J0U9i7uQ0k3B4SEZ8k@stanza.co
SUMMARY:Dragons vs. Lugnuts
DESCRIPTION:Dragons vs. Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vM$I-w\n\nShop: https://stza.co/+vM$I-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Lugnuts
<2018-06-02 Sat 18:00-21:00>
:PROPERTIES:
:ID:       gDc3-z6qK2oe4yvCNrQRKzRV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons vs. Lugnuts Dragons vs. Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vM$K-29

Shop  https //stza.co/+vM$K-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Lugnuts
END:VALARM
DTSTART:20180602T230000Z
DTEND:20180603T020000Z
UID:gDc3-z6qK2oe4yvCNrQRKzRV@stanza.co
SUMMARY:Dragons vs. Lugnuts
DESCRIPTION:Dragons vs. Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vM$K-29\n\nShop: https://stza.co/+vM$K-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Lugnuts
<2018-06-03 Sun 13:00-16:00>
:PROPERTIES:
:ID:       o-EkUFA8ENO6RYFseVsWw-1Z@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Lugnuts Dragons vs. Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vM$L-r

Shop  https //stza.co/+vM$L-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Lugnuts
END:VALARM
DTSTART:20180603T180000Z
DTEND:20180603T210000Z
UID:o-EkUFA8ENO6RYFseVsWw-1Z@stanza.co
SUMMARY:Dragons vs. Lugnuts
DESCRIPTION:Dragons vs. Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vM$L-r\n\nShop: https://stza.co/+vM$L-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Captains
<2018-06-05 Tue 18:00-21:00>
:PROPERTIES:
:ID:       NG0k3Ue4LmqelB0_YflcYu_a@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Captains Dragons @ Captains

Follow on MiLB First Pitch  https //stza.co/+xBri-2Z

Shop  https //stza.co/+xBri-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Captains
END:VALARM
DTSTART:20180605T230000Z
DTEND:20180606T020000Z
UID:NG0k3Ue4LmqelB0_YflcYu_a@stanza.co
SUMMARY:Dragons @ Captains
DESCRIPTION:Dragons @ Captains\n\nFollow on MiLB First Pitch: https://stza.co/+xBri-2Z\n\nShop: https://stza.co/+xBri-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Captains
<2018-06-06 Wed 18:00-21:00>
:PROPERTIES:
:ID:       qMzEc-Z0eTenRxJKz2vfzASP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons @ Captains Dragons @ Captains

Follow on MiLB First Pitch  https //stza.co/+xBrj-3L

Shop  https //stza.co/+xBrj-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Captains
END:VALARM
DTSTART:20180606T230000Z
DTEND:20180607T020000Z
UID:qMzEc-Z0eTenRxJKz2vfzASP@stanza.co
SUMMARY:Dragons @ Captains
DESCRIPTION:Dragons @ Captains\n\nFollow on MiLB First Pitch: https://stza.co/+xBrj-3L\n\nShop: https://stza.co/+xBrj-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Captains
<2018-06-07 Thu 18:00-21:00>
:PROPERTIES:
:ID:       QE9Y7ypGnAW--4_GzCIaHg9w@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Captains Dragons @ Captains

Follow on MiLB First Pitch  https //stza.co/+xBrm-T

Shop  https //stza.co/+xBrm-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Captains
END:VALARM
DTSTART:20180607T230000Z
DTEND:20180608T020000Z
UID:QE9Y7ypGnAW--4_GzCIaHg9w@stanza.co
SUMMARY:Dragons @ Captains
DESCRIPTION:Dragons @ Captains\n\nFollow on MiLB First Pitch: https://stza.co/+xBrm-T\n\nShop: https://stza.co/+xBrm-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Hot Rods
<2018-06-08 Fri 18:00-21:00>
:PROPERTIES:
:ID:       EkQ3ub8x9ZADEsgUbOGS5Kem@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Hot Rods Dragons vs. Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vM$O-8

Shop  https //stza.co/+vM$O-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Hot Rods
END:VALARM
DTSTART:20180608T230000Z
DTEND:20180609T020000Z
UID:EkQ3ub8x9ZADEsgUbOGS5Kem@stanza.co
SUMMARY:Dragons vs. Hot Rods
DESCRIPTION:Dragons vs. Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vM$O-8\n\nShop: https://stza.co/+vM$O-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Hot Rods
<2018-06-09 Sat 18:00-21:00>
:PROPERTIES:
:ID:       CUXP11syTKbJeNxKqyOqYPrD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons vs. Hot Rods Dragons vs. Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vM$Q-20

Shop  https //stza.co/+vM$Q-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Hot Rods
END:VALARM
DTSTART:20180609T230000Z
DTEND:20180610T020000Z
UID:CUXP11syTKbJeNxKqyOqYPrD@stanza.co
SUMMARY:Dragons vs. Hot Rods
DESCRIPTION:Dragons vs. Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vM$Q-20\n\nShop: https://stza.co/+vM$Q-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Hot Rods
<2018-06-10 Sun 13:00-16:00>
:PROPERTIES:
:ID:       RZMBfUEA5WUVWc1dpaSv0__U@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Hot Rods Dragons vs. Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vM$R-2e

Shop  https //stza.co/+vM$R-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Hot Rods
END:VALARM
DTSTART:20180610T180000Z
DTEND:20180610T210000Z
UID:RZMBfUEA5WUVWc1dpaSv0__U@stanza.co
SUMMARY:Dragons vs. Hot Rods
DESCRIPTION:Dragons vs. Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vM$R-2e\n\nShop: https://stza.co/+vM$R-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Hot Rods
<2018-06-11 Mon 18:00-21:00>
:PROPERTIES:
:ID:       ozTbbXLu0ZJILPt7y_bI-0Ph@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Hot Rods Dragons vs. Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vM$U-2c

Shop  https //stza.co/+vM$U-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Hot Rods
END:VALARM
DTSTART:20180611T230000Z
DTEND:20180612T020000Z
UID:ozTbbXLu0ZJILPt7y_bI-0Ph@stanza.co
SUMMARY:Dragons vs. Hot Rods
DESCRIPTION:Dragons vs. Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vM$U-2c\n\nShop: https://stza.co/+vM$U-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Cubs
<2018-06-12 Tue 18:05-21:05>
:PROPERTIES:
:ID:       Yx1Ms_ArVDEeNOZ7FbxLHnOg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons @ Cubs Dragons @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vN1w-31

Shop  https //stza.co/+vN1w-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Cubs
END:VALARM
DTSTART:20180612T230500Z
DTEND:20180613T020500Z
UID:Yx1Ms_ArVDEeNOZ7FbxLHnOg@stanza.co
SUMMARY:Dragons @ Cubs
DESCRIPTION:Dragons @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vN1w-31\n\nShop: https://stza.co/+vN1w-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Cubs
<2018-06-13 Wed 18:05-21:05>
:PROPERTIES:
:ID:       ODJMjhizPvS1dnkClX9NnkQr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Cubs Dragons @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vN1x-3R

Shop  https //stza.co/+vN1x-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Cubs
END:VALARM
DTSTART:20180613T230500Z
DTEND:20180614T020500Z
UID:ODJMjhizPvS1dnkClX9NnkQr@stanza.co
SUMMARY:Dragons @ Cubs
DESCRIPTION:Dragons @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vN1x-3R\n\nShop: https://stza.co/+vN1x-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Cubs
<2018-06-14 Thu 18:05-21:05>
:PROPERTIES:
:ID:       LIWFSQyRhH1abCqCb8n_m1Mz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Cubs Dragons @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vN1y-2l

Shop  https //stza.co/+vN1y-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Cubs
END:VALARM
DTSTART:20180614T230500Z
DTEND:20180615T020500Z
UID:LIWFSQyRhH1abCqCb8n_m1Mz@stanza.co
SUMMARY:Dragons @ Cubs
DESCRIPTION:Dragons @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vN1y-2l\n\nShop: https://stza.co/+vN1y-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Whitecaps
<2018-06-15 Fri 18:05-21:05>
:PROPERTIES:
:ID:       H15NV1iTJOZn0x9pD_yh8gnm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons @ Whitecaps Dragons @ Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vN1D-b

Shop  https //stza.co/+vN1D-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Whitecaps
END:VALARM
DTSTART:20180615T230500Z
DTEND:20180616T020500Z
UID:H15NV1iTJOZn0x9pD_yh8gnm@stanza.co
SUMMARY:Dragons @ Whitecaps
DESCRIPTION:Dragons @ Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vN1D-b\n\nShop: https://stza.co/+vN1D-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Whitecaps
<2018-06-16 Sat 18:05-21:05>
:PROPERTIES:
:ID:       aI5hNlbwdjlbeuLBMSy9AhSj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Whitecaps Dragons @ Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vN1E-3p

Shop  https //stza.co/+vN1E-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Whitecaps
END:VALARM
DTSTART:20180616T230500Z
DTEND:20180617T020500Z
UID:aI5hNlbwdjlbeuLBMSy9AhSj@stanza.co
SUMMARY:Dragons @ Whitecaps
DESCRIPTION:Dragons @ Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vN1E-3p\n\nShop: https://stza.co/+vN1E-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Whitecaps
<2018-06-17 Sun 13:00-16:00>
:PROPERTIES:
:ID:       0bHpXwarYmawg-l5WkJYisG8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Whitecaps Dragons @ Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vN1F-3i

Shop  https //stza.co/+vN1F-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Whitecaps
END:VALARM
DTSTART:20180617T180000Z
DTEND:20180617T210000Z
UID:0bHpXwarYmawg-l5WkJYisG8@stanza.co
SUMMARY:Dragons @ Whitecaps
DESCRIPTION:Dragons @ Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vN1F-3i\n\nShop: https://stza.co/+vN1F-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Cubs
<2018-06-21 Thu 18:00-21:00>
:PROPERTIES:
:ID:       jshHUncNKgL3S4_F5uZGtOI2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons vs. Cubs Dragons vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+vM$W-3_

Shop  https //stza.co/+vM$W-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Cubs
END:VALARM
DTSTART:20180621T230000Z
DTEND:20180622T020000Z
UID:jshHUncNKgL3S4_F5uZGtOI2@stanza.co
SUMMARY:Dragons vs. Cubs
DESCRIPTION:Dragons vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vM$W-3_\n\nShop: https://stza.co/+vM$W-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Cubs
<2018-06-22 Fri 18:00-21:00>
:PROPERTIES:
:ID:       GGWdd1sj9yu9by4oiqCHtyXp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Cubs Dragons vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+vM$Y-1w

Shop  https //stza.co/+vM$Y-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Cubs
END:VALARM
DTSTART:20180622T230000Z
DTEND:20180623T020000Z
UID:GGWdd1sj9yu9by4oiqCHtyXp@stanza.co
SUMMARY:Dragons vs. Cubs
DESCRIPTION:Dragons vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vM$Y-1w\n\nShop: https://stza.co/+vM$Y-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Cubs
<2018-06-23 Sat 18:00-21:00>
:PROPERTIES:
:ID:       tBlWeD_0HyhrmWS89uf6aGYd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Cubs Dragons vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+vM$Z-22

Shop  https //stza.co/+vM$Z-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Cubs
END:VALARM
DTSTART:20180623T230000Z
DTEND:20180624T020000Z
UID:tBlWeD_0HyhrmWS89uf6aGYd@stanza.co
SUMMARY:Dragons vs. Cubs
DESCRIPTION:Dragons vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vM$Z-22\n\nShop: https://stza.co/+vM$Z-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Cubs
<2018-06-24 Sun 13:00-16:00>
:PROPERTIES:
:ID:       K6lKFs-poHOnTAvJqZYd9Qkp@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons vs. Cubs Dragons vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+vM$$-4

Shop  https //stza.co/+vM$$-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Cubs
END:VALARM
DTSTART:20180624T180000Z
DTEND:20180624T210000Z
UID:K6lKFs-poHOnTAvJqZYd9Qkp@stanza.co
SUMMARY:Dragons vs. Cubs
DESCRIPTION:Dragons vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vM$$-4\n\nShop: https://stza.co/+vM$$-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Loons
<2018-06-25 Mon 18:00-21:00>
:PROPERTIES:
:ID:       sj4HsoTUGxVSpZAMRSTQB2Ec@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Loons Dragons vs. Loons

Follow on MiLB First Pitch  https //stza.co/+vN02-2G

Shop  https //stza.co/+vN02-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Loons
END:VALARM
DTSTART:20180625T230000Z
DTEND:20180626T020000Z
UID:sj4HsoTUGxVSpZAMRSTQB2Ec@stanza.co
SUMMARY:Dragons vs. Loons
DESCRIPTION:Dragons vs. Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vN02-2G\n\nShop: https://stza.co/+vN02-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Loons
<2018-06-26 Tue 18:00-21:00>
:PROPERTIES:
:ID:       66T6ruC6wDiSnKRvj3NXXoAc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Loons Dragons vs. Loons

Follow on MiLB First Pitch  https //stza.co/+vN03-k

Shop  https //stza.co/+vN03-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Loons
END:VALARM
DTSTART:20180626T230000Z
DTEND:20180627T020000Z
UID:66T6ruC6wDiSnKRvj3NXXoAc@stanza.co
SUMMARY:Dragons vs. Loons
DESCRIPTION:Dragons vs. Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vN03-k\n\nShop: https://stza.co/+vN03-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Loons
<2018-06-27 Wed 18:00-21:00>
:PROPERTIES:
:ID:       IrOVZ3_zk26zS0WKfTsYBDZW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons vs. Loons Dragons vs. Loons

Follow on MiLB First Pitch  https //stza.co/+vN05-O

Shop  https //stza.co/+vN05-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Loons
END:VALARM
DTSTART:20180627T230000Z
DTEND:20180628T020000Z
UID:IrOVZ3_zk26zS0WKfTsYBDZW@stanza.co
SUMMARY:Dragons vs. Loons
DESCRIPTION:Dragons vs. Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vN05-O\n\nShop: https://stza.co/+vN05-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Cubs
<2018-06-28 Thu 18:05-21:05>
:PROPERTIES:
:ID:       zp7Rr-xH_Da1n4nkjHLctpto@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Cubs Dragons @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vN1z-1o

Shop  https //stza.co/+vN1z-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Cubs
END:VALARM
DTSTART:20180628T230500Z
DTEND:20180629T020500Z
UID:zp7Rr-xH_Da1n4nkjHLctpto@stanza.co
SUMMARY:Dragons @ Cubs
DESCRIPTION:Dragons @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vN1z-1o\n\nShop: https://stza.co/+vN1z-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Cubs
<2018-06-29 Fri 18:35-21:35>
:PROPERTIES:
:ID:       VXa2EH2YRvzhp3cisawqXY0B@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Cubs Dragons @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vN1A-3I

Shop  https //stza.co/+vN1A-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Cubs
END:VALARM
DTSTART:20180629T233500Z
DTEND:20180630T023500Z
UID:VXa2EH2YRvzhp3cisawqXY0B@stanza.co
SUMMARY:Dragons @ Cubs
DESCRIPTION:Dragons @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vN1A-3I\n\nShop: https://stza.co/+vN1A-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Cubs
<2018-06-30 Sat 18:05-21:05>
:PROPERTIES:
:ID:       hBJnfFXv478J5Agl3R_w8bun@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons @ Cubs Dragons @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vN1B-1F

Shop  https //stza.co/+vN1B-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Cubs
END:VALARM
DTSTART:20180630T230500Z
DTEND:20180701T020500Z
UID:hBJnfFXv478J5Agl3R_w8bun@stanza.co
SUMMARY:Dragons @ Cubs
DESCRIPTION:Dragons @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vN1B-1F\n\nShop: https://stza.co/+vN1B-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Cubs
<2018-07-01 Sun 13:05-16:05>
:PROPERTIES:
:ID:       l1y6fvI7uDziGtUKXx78AKUn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Cubs Dragons @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vN1C-3K

Shop  https //stza.co/+vN1C-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Cubs
END:VALARM
DTSTART:20180701T180500Z
DTEND:20180701T210500Z
UID:l1y6fvI7uDziGtUKXx78AKUn@stanza.co
SUMMARY:Dragons @ Cubs
DESCRIPTION:Dragons @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vN1C-3K\n\nShop: https://stza.co/+vN1C-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Captains
<2018-07-02 Mon 18:00-21:00>
:PROPERTIES:
:ID:       5WWdYcSzgg2sdR1smk0C1urV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Captains Dragons @ Captains

Follow on MiLB First Pitch  https //stza.co/+xBrn-p

Shop  https //stza.co/+xBrn-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Captains
END:VALARM
DTSTART:20180702T230000Z
DTEND:20180703T020000Z
UID:5WWdYcSzgg2sdR1smk0C1urV@stanza.co
SUMMARY:Dragons @ Captains
DESCRIPTION:Dragons @ Captains\n\nFollow on MiLB First Pitch: https://stza.co/+xBrn-p\n\nShop: https://stza.co/+xBrn-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Captains
<2018-07-03 Tue 18:00-21:00>
:PROPERTIES:
:ID:       i7HQXUx9_vwBtB_6wiQV8VOA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons @ Captains Dragons @ Captains

Follow on MiLB First Pitch  https //stza.co/+xBrq-2T

Shop  https //stza.co/+xBrq-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Captains
END:VALARM
DTSTART:20180703T230000Z
DTEND:20180704T020000Z
UID:i7HQXUx9_vwBtB_6wiQV8VOA@stanza.co
SUMMARY:Dragons @ Captains
DESCRIPTION:Dragons @ Captains\n\nFollow on MiLB First Pitch: https://stza.co/+xBrq-2T\n\nShop: https://stza.co/+xBrq-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Captains
<2018-07-04 Wed 18:00-21:00>
:PROPERTIES:
:ID:       cJHZ05nXEt7zcVqW23LXqy1q@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Captains Dragons vs. Captains

Follow on MiLB First Pitch  https //stza.co/+vN07-1p

Shop  https //stza.co/+vN07-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Captains
END:VALARM
DTSTART:20180704T230000Z
DTEND:20180705T020000Z
UID:cJHZ05nXEt7zcVqW23LXqy1q@stanza.co
SUMMARY:Dragons vs. Captains
DESCRIPTION:Dragons vs. Captains\n\nFollow on MiLB First Pitch: https://stza.co/+vN07-1p\n\nShop: https://stza.co/+vN07-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Captains
<2018-07-05 Thu 18:00-21:00>
:PROPERTIES:
:ID:       xFNbTvzFpp2XxJew1r97SQgh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Captains Dragons vs. Captains

Follow on MiLB First Pitch  https //stza.co/+vN09-q

Shop  https //stza.co/+vN09-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Captains
END:VALARM
DTSTART:20180705T230000Z
DTEND:20180706T020000Z
UID:xFNbTvzFpp2XxJew1r97SQgh@stanza.co
SUMMARY:Dragons vs. Captains
DESCRIPTION:Dragons vs. Captains\n\nFollow on MiLB First Pitch: https://stza.co/+vN09-q\n\nShop: https://stza.co/+vN09-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Loons
<2018-07-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       qLR6DY7mOwcjvhWWklF4VLpK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons @ Loons Dragons @ Loons

Follow on MiLB First Pitch  https //stza.co/+vN18-3m

Shop  https //stza.co/+vN18-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Loons
END:VALARM
DTSTART:20180706T230500Z
DTEND:20180707T020500Z
UID:qLR6DY7mOwcjvhWWklF4VLpK@stanza.co
SUMMARY:Dragons @ Loons
DESCRIPTION:Dragons @ Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vN18-3m\n\nShop: https://stza.co/+vN18-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Loons
<2018-07-07 Sat 18:05-21:05>
:PROPERTIES:
:ID:       MUKSt_KGceHQ3iIG2Thmgt-O@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Loons Dragons @ Loons

Follow on MiLB First Pitch  https //stza.co/+vN19-29

Shop  https //stza.co/+vN19-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Loons
END:VALARM
DTSTART:20180707T230500Z
DTEND:20180708T020500Z
UID:MUKSt_KGceHQ3iIG2Thmgt-O@stanza.co
SUMMARY:Dragons @ Loons
DESCRIPTION:Dragons @ Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vN19-29\n\nShop: https://stza.co/+vN19-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Loons
<2018-07-08 Sun 13:05-16:05>
:PROPERTIES:
:ID:       aME6yjoo8Cwon3KytyZMsSMZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Loons Dragons @ Loons

Follow on MiLB First Pitch  https //stza.co/+vN1a-1A

Shop  https //stza.co/+vN1a-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Loons
END:VALARM
DTSTART:20180708T180500Z
DTEND:20180708T210500Z
UID:aME6yjoo8Cwon3KytyZMsSMZ@stanza.co
SUMMARY:Dragons @ Loons
DESCRIPTION:Dragons @ Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vN1a-1A\n\nShop: https://stza.co/+vN1a-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Loons
<2018-07-09 Mon 18:05-21:05>
:PROPERTIES:
:ID:       XHfDSvu0OXa7Qt7TkgwtZedj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons @ Loons Dragons @ Loons

Follow on MiLB First Pitch  https //stza.co/+vN1b-1K

Shop  https //stza.co/+vN1b-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Loons
END:VALARM
DTSTART:20180709T230500Z
DTEND:20180710T020500Z
UID:XHfDSvu0OXa7Qt7TkgwtZedj@stanza.co
SUMMARY:Dragons @ Loons
DESCRIPTION:Dragons @ Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vN1b-1K\n\nShop: https://stza.co/+vN1b-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. River Bandits
<2018-07-11 Wed 18:00-21:00>
:PROPERTIES:
:ID:       OescVnige3c2kzUIS4W-Yrnx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. River Bandits Dragons vs. River Bandits

Follow on MiLB First Pitch  https //stza.co/+vN0b-3N

Shop  https //stza.co/+vN0b-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. River Bandits
END:VALARM
DTSTART:20180711T230000Z
DTEND:20180712T020000Z
UID:OescVnige3c2kzUIS4W-Yrnx@stanza.co
SUMMARY:Dragons vs. River Bandits
DESCRIPTION:Dragons vs. River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+vN0b-3N\n\nShop: https://stza.co/+vN0b-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. River Bandits
<2018-07-12 Thu 18:00-21:00>
:PROPERTIES:
:ID:       l2XppsWjxyQxwzuBXvx155m_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. River Bandits Dragons vs. River Bandits

Follow on MiLB First Pitch  https //stza.co/+vN0d-1p

Shop  https //stza.co/+vN0d-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. River Bandits
END:VALARM
DTSTART:20180712T230000Z
DTEND:20180713T020000Z
UID:l2XppsWjxyQxwzuBXvx155m_@stanza.co
SUMMARY:Dragons vs. River Bandits
DESCRIPTION:Dragons vs. River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+vN0d-1p\n\nShop: https://stza.co/+vN0d-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. River Bandits
<2018-07-13 Fri 18:00-21:00>
:PROPERTIES:
:ID:       pHLoylwOh8uPPyIxWLbFISeU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons vs. River Bandits Dragons vs. River Bandits

Follow on MiLB First Pitch  https //stza.co/+vN0f-3h

Shop  https //stza.co/+vN0f-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. River Bandits
END:VALARM
DTSTART:20180713T230000Z
DTEND:20180714T020000Z
UID:pHLoylwOh8uPPyIxWLbFISeU@stanza.co
SUMMARY:Dragons vs. River Bandits
DESCRIPTION:Dragons vs. River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+vN0f-3h\n\nShop: https://stza.co/+vN0f-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Cougars
<2018-07-14 Sat 18:00-21:00>
:PROPERTIES:
:ID:       LJjMmsmVyDHGXLklj4u0Dm3n@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Cougars Dragons vs. Cougars

Follow on MiLB First Pitch  https //stza.co/+vN0i-21

Shop  https //stza.co/+vN0i-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Cougars
END:VALARM
DTSTART:20180714T230000Z
DTEND:20180715T020000Z
UID:LJjMmsmVyDHGXLklj4u0Dm3n@stanza.co
SUMMARY:Dragons vs. Cougars
DESCRIPTION:Dragons vs. Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+vN0i-21\n\nShop: https://stza.co/+vN0i-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Cougars
<2018-07-15 Sun 13:00-16:00>
:PROPERTIES:
:ID:       pFALMUUWn30Zmr-TLWAyn9ZW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Cougars Dragons vs. Cougars

Follow on MiLB First Pitch  https //stza.co/+vN0k-m

Shop  https //stza.co/+vN0k-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Cougars
END:VALARM
DTSTART:20180715T180000Z
DTEND:20180715T210000Z
UID:pFALMUUWn30Zmr-TLWAyn9ZW@stanza.co
SUMMARY:Dragons vs. Cougars
DESCRIPTION:Dragons vs. Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+vN0k-m\n\nShop: https://stza.co/+vN0k-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Cougars
<2018-07-16 Mon 18:00-21:00>
:PROPERTIES:
:ID:       6qD8AHNZ8Ar5jx-KbSinu3tO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons vs. Cougars Dragons vs. Cougars

Follow on MiLB First Pitch  https //stza.co/+vN0m-2p

Shop  https //stza.co/+vN0m-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Cougars
END:VALARM
DTSTART:20180716T230000Z
DTEND:20180717T020000Z
UID:6qD8AHNZ8Ar5jx-KbSinu3tO@stanza.co
SUMMARY:Dragons vs. Cougars
DESCRIPTION:Dragons vs. Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+vN0m-2p\n\nShop: https://stza.co/+vN0m-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Timber Rattlers
<2018-07-18 Wed 19:05-22:05>
:PROPERTIES:
:ID:       emLQgKg9WlfBoFPJYg_s0RzN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Timber Rattlers Dragons @ Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+vq7u-3C

Shop  https //stza.co/+vq7u-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Timber Rattlers
END:VALARM
DTSTART:20180719T000500Z
DTEND:20180719T030500Z
UID:emLQgKg9WlfBoFPJYg_s0RzN@stanza.co
SUMMARY:Dragons @ Timber Rattlers
DESCRIPTION:Dragons @ Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+vq7u-3C\n\nShop: https://stza.co/+vq7u-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Timber Rattlers
<2018-07-19 Thu 19:05-22:05>
:PROPERTIES:
:ID:       28-cV2-CVmxoGF_iLcyXvWrb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Timber Rattlers Dragons @ Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+vq7v-2N

Shop  https //stza.co/+vq7v-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Timber Rattlers
END:VALARM
DTSTART:20180720T000500Z
DTEND:20180720T030500Z
UID:28-cV2-CVmxoGF_iLcyXvWrb@stanza.co
SUMMARY:Dragons @ Timber Rattlers
DESCRIPTION:Dragons @ Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+vq7v-2N\n\nShop: https://stza.co/+vq7v-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Timber Rattlers
<2018-07-20 Fri 19:05-22:05>
:PROPERTIES:
:ID:       xDC6F__OYIarmGAmxbZkC4ff@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons @ Timber Rattlers Dragons @ Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+vq7w-3D

Shop  https //stza.co/+vq7w-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Timber Rattlers
END:VALARM
DTSTART:20180721T000500Z
DTEND:20180721T030500Z
UID:xDC6F__OYIarmGAmxbZkC4ff@stanza.co
SUMMARY:Dragons @ Timber Rattlers
DESCRIPTION:Dragons @ Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+vq7w-3D\n\nShop: https://stza.co/+vq7w-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Snappers
<2018-07-21 Sat 19:00-22:00>
:PROPERTIES:
:ID:       dBBRYmQjFRPHKznndTHF8u_U@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Snappers Dragons @ Snappers

Follow on MiLB First Pitch  https //stza.co/+wSLU-h

Shop  https //stza.co/+wSLU-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Snappers
END:VALARM
DTSTART:20180722T000000Z
DTEND:20180722T030000Z
UID:dBBRYmQjFRPHKznndTHF8u_U@stanza.co
SUMMARY:Dragons @ Snappers
DESCRIPTION:Dragons @ Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wSLU-h\n\nShop: https://stza.co/+wSLU-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Snappers
<2018-07-22 Sun 14:00-17:00>
:PROPERTIES:
:ID:       7hFH2nKQM4MqEyP3INUtqfLK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Snappers Dragons @ Snappers

Follow on MiLB First Pitch  https //stza.co/+wSLV-d

Shop  https //stza.co/+wSLV-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Snappers
END:VALARM
DTSTART:20180722T190000Z
DTEND:20180722T220000Z
UID:7hFH2nKQM4MqEyP3INUtqfLK@stanza.co
SUMMARY:Dragons @ Snappers
DESCRIPTION:Dragons @ Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wSLV-d\n\nShop: https://stza.co/+wSLV-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Snappers
<2018-07-23 Mon 12:00-15:00>
:PROPERTIES:
:ID:       qLY-P118zr6UBJtTFEuUUhiw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons @ Snappers Dragons @ Snappers

Follow on MiLB First Pitch  https //stza.co/+wSLX-3v

Shop  https //stza.co/+wSLX-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Snappers
END:VALARM
DTSTART:20180723T170000Z
DTEND:20180723T200000Z
UID:qLY-P118zr6UBJtTFEuUUhiw@stanza.co
SUMMARY:Dragons @ Snappers
DESCRIPTION:Dragons @ Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wSLX-3v\n\nShop: https://stza.co/+wSLX-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. TinCaps
<2018-07-25 Wed 18:00-21:00>
:PROPERTIES:
:ID:       PSQPrtyl9e-0SQs9jKRfya8o@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. TinCaps Dragons vs. TinCaps

Follow on MiLB First Pitch  https //stza.co/+vN0o-2U

Shop  https //stza.co/+vN0o-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. TinCaps
END:VALARM
DTSTART:20180725T230000Z
DTEND:20180726T020000Z
UID:PSQPrtyl9e-0SQs9jKRfya8o@stanza.co
SUMMARY:Dragons vs. TinCaps
DESCRIPTION:Dragons vs. TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+vN0o-2U\n\nShop: https://stza.co/+vN0o-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. TinCaps
<2018-07-26 Thu 18:00-21:00>
:PROPERTIES:
:ID:       vJ8lAC1ecswPmssQX8Abj1vM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. TinCaps Dragons vs. TinCaps

Follow on MiLB First Pitch  https //stza.co/+vN0q-2

Shop  https //stza.co/+vN0q-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. TinCaps
END:VALARM
DTSTART:20180726T230000Z
DTEND:20180727T020000Z
UID:vJ8lAC1ecswPmssQX8Abj1vM@stanza.co
SUMMARY:Dragons vs. TinCaps
DESCRIPTION:Dragons vs. TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+vN0q-2\n\nShop: https://stza.co/+vN0q-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. TinCaps
<2018-07-27 Fri 18:00-21:00>
:PROPERTIES:
:ID:       CNHV4giQONGZcDpae7ASR9X8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons vs. TinCaps Dragons vs. TinCaps

Follow on MiLB First Pitch  https //stza.co/+vN0s-22

Shop  https //stza.co/+vN0s-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. TinCaps
END:VALARM
DTSTART:20180727T230000Z
DTEND:20180728T020000Z
UID:CNHV4giQONGZcDpae7ASR9X8@stanza.co
SUMMARY:Dragons vs. TinCaps
DESCRIPTION:Dragons vs. TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+vN0s-22\n\nShop: https://stza.co/+vN0s-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Lugnuts
<2018-07-28 Sat 18:00-21:00>
:PROPERTIES:
:ID:       RwBItFS3G3G_XX1gyZtS8zqr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Lugnuts Dragons vs. Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vN0t-3N

Shop  https //stza.co/+vN0t-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Lugnuts
END:VALARM
DTSTART:20180728T230000Z
DTEND:20180729T020000Z
UID:RwBItFS3G3G_XX1gyZtS8zqr@stanza.co
SUMMARY:Dragons vs. Lugnuts
DESCRIPTION:Dragons vs. Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vN0t-3N\n\nShop: https://stza.co/+vN0t-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Lugnuts
<2018-07-29 Sun 13:00-16:00>
:PROPERTIES:
:ID:       t5pdtEJWPL_MlGJkXOWRajLl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Lugnuts Dragons vs. Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vN0w-3w

Shop  https //stza.co/+vN0w-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Lugnuts
END:VALARM
DTSTART:20180729T180000Z
DTEND:20180729T210000Z
UID:t5pdtEJWPL_MlGJkXOWRajLl@stanza.co
SUMMARY:Dragons vs. Lugnuts
DESCRIPTION:Dragons vs. Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vN0w-3w\n\nShop: https://stza.co/+vN0w-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Lugnuts
<2018-07-30 Mon 18:00-21:00>
:PROPERTIES:
:ID:       jnU_zoE2k8RWg0PeScFxwvbM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons vs. Lugnuts Dragons vs. Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vN0y-1C

Shop  https //stza.co/+vN0y-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Lugnuts
END:VALARM
DTSTART:20180730T230000Z
DTEND:20180731T020000Z
UID:jnU_zoE2k8RWg0PeScFxwvbM@stanza.co
SUMMARY:Dragons vs. Lugnuts
DESCRIPTION:Dragons vs. Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vN0y-1C\n\nShop: https://stza.co/+vN0y-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Lugnuts
<2018-07-31 Tue 18:00-21:00>
:PROPERTIES:
:ID:       aIXk8kGkhI3A9lbXJYerclEC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Lugnuts Dragons vs. Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vN0A-J

Shop  https //stza.co/+vN0A-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Lugnuts
END:VALARM
DTSTART:20180731T230000Z
DTEND:20180801T020000Z
UID:aIXk8kGkhI3A9lbXJYerclEC@stanza.co
SUMMARY:Dragons vs. Lugnuts
DESCRIPTION:Dragons vs. Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vN0A-J\n\nShop: https://stza.co/+vN0A-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ TinCaps
<2018-08-01 Wed 18:05-21:05>
:PROPERTIES:
:ID:       Tk_YUKOOasvM6zCrQo2LWAEu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ TinCaps Dragons @ TinCaps

Follow on MiLB First Pitch  https //stza.co/+vN12-1O

Shop  https //stza.co/+vN12-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ TinCaps
END:VALARM
DTSTART:20180801T230500Z
DTEND:20180802T020500Z
UID:Tk_YUKOOasvM6zCrQo2LWAEu@stanza.co
SUMMARY:Dragons @ TinCaps
DESCRIPTION:Dragons @ TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+vN12-1O\n\nShop: https://stza.co/+vN12-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ TinCaps
<2018-08-02 Thu 18:05-21:05>
:PROPERTIES:
:ID:       JO0BF6s0kFJbQC3YR2N1wORk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons @ TinCaps Dragons @ TinCaps

Follow on MiLB First Pitch  https //stza.co/+vN13-1A

Shop  https //stza.co/+vN13-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ TinCaps
END:VALARM
DTSTART:20180802T230500Z
DTEND:20180803T020500Z
UID:JO0BF6s0kFJbQC3YR2N1wORk@stanza.co
SUMMARY:Dragons @ TinCaps
DESCRIPTION:Dragons @ TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+vN13-1A\n\nShop: https://stza.co/+vN13-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ TinCaps
<2018-08-03 Fri 18:05-21:05>
:PROPERTIES:
:ID:       uCf8wtwT6PHd19mPo9QfqwF5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ TinCaps Dragons @ TinCaps

Follow on MiLB First Pitch  https //stza.co/+vN14-23

Shop  https //stza.co/+vN14-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ TinCaps
END:VALARM
DTSTART:20180803T230500Z
DTEND:20180804T020500Z
UID:uCf8wtwT6PHd19mPo9QfqwF5@stanza.co
SUMMARY:Dragons @ TinCaps
DESCRIPTION:Dragons @ TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+vN14-23\n\nShop: https://stza.co/+vN14-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Whitecaps
<2018-08-04 Sat 18:05-21:05>
:PROPERTIES:
:ID:       TJTDe0dvowKN0FzhgksVur-V@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Whitecaps Dragons @ Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vN1G-2w

Shop  https //stza.co/+vN1G-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Whitecaps
END:VALARM
DTSTART:20180804T230500Z
DTEND:20180805T020500Z
UID:TJTDe0dvowKN0FzhgksVur-V@stanza.co
SUMMARY:Dragons @ Whitecaps
DESCRIPTION:Dragons @ Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vN1G-2w\n\nShop: https://stza.co/+vN1G-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Whitecaps
<2018-08-05 Sun 13:00-16:00>
:PROPERTIES:
:ID:       eVLaYizk0tM7MmCeoTrgTzsL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons @ Whitecaps Dragons @ Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vN1H-3m

Shop  https //stza.co/+vN1H-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Whitecaps
END:VALARM
DTSTART:20180805T180000Z
DTEND:20180805T210000Z
UID:eVLaYizk0tM7MmCeoTrgTzsL@stanza.co
SUMMARY:Dragons @ Whitecaps
DESCRIPTION:Dragons @ Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vN1H-3m\n\nShop: https://stza.co/+vN1H-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Whitecaps
<2018-08-06 Mon 18:05-21:05>
:PROPERTIES:
:ID:       tPr41OwcPYE6jksR7sRpOfix@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Whitecaps Dragons @ Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vN1I-m

Shop  https //stza.co/+vN1I-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Whitecaps
END:VALARM
DTSTART:20180806T230500Z
DTEND:20180807T020500Z
UID:tPr41OwcPYE6jksR7sRpOfix@stanza.co
SUMMARY:Dragons @ Whitecaps
DESCRIPTION:Dragons @ Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vN1I-m\n\nShop: https://stza.co/+vN1I-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Lugnuts
<2018-08-08 Wed 18:05-21:05>
:PROPERTIES:
:ID:       wICty286YuNmQyrGLl6Sfwlf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Lugnuts Dragons @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vN1t-2l

Shop  https //stza.co/+vN1t-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Lugnuts
END:VALARM
DTSTART:20180808T230500Z
DTEND:20180809T020500Z
UID:wICty286YuNmQyrGLl6Sfwlf@stanza.co
SUMMARY:Dragons @ Lugnuts
DESCRIPTION:Dragons @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vN1t-2l\n\nShop: https://stza.co/+vN1t-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Lugnuts
<2018-08-09 Thu 18:05-21:05>
:PROPERTIES:
:ID:       U9u-1AgGj0greS1Oa5U56JAI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons @ Lugnuts Dragons @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vN1u-r

Shop  https //stza.co/+vN1u-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Lugnuts
END:VALARM
DTSTART:20180809T230500Z
DTEND:20180810T020500Z
UID:U9u-1AgGj0greS1Oa5U56JAI@stanza.co
SUMMARY:Dragons @ Lugnuts
DESCRIPTION:Dragons @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vN1u-r\n\nShop: https://stza.co/+vN1u-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Lugnuts
<2018-08-10 Fri 18:05-21:05>
:PROPERTIES:
:ID:       ZdmDoiAPX5W48nPYB5Z5Zzko@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Lugnuts Dragons @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vN1v-t

Shop  https //stza.co/+vN1v-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Lugnuts
END:VALARM
DTSTART:20180810T230500Z
DTEND:20180811T020500Z
UID:ZdmDoiAPX5W48nPYB5Z5Zzko@stanza.co
SUMMARY:Dragons @ Lugnuts
DESCRIPTION:Dragons @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vN1v-t\n\nShop: https://stza.co/+vN1v-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Loons
<2018-08-11 Sat 18:05-21:05>
:PROPERTIES:
:ID:       vkPOYbGxa3xCcGCYK0izK4xr@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Loons Dragons @ Loons

Follow on MiLB First Pitch  https //stza.co/+vN1c-Q

Shop  https //stza.co/+vN1c-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Loons
END:VALARM
DTSTART:20180811T230500Z
DTEND:20180812T020500Z
UID:vkPOYbGxa3xCcGCYK0izK4xr@stanza.co
SUMMARY:Dragons @ Loons
DESCRIPTION:Dragons @ Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vN1c-Q\n\nShop: https://stza.co/+vN1c-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Loons
<2018-08-12 Sun 13:05-16:05>
:PROPERTIES:
:ID:       1Ytu3KQKWQV6ixnwVqJD88YO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons @ Loons Dragons @ Loons

Follow on MiLB First Pitch  https //stza.co/+vN1d-q

Shop  https //stza.co/+vN1d-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Loons
END:VALARM
DTSTART:20180812T180500Z
DTEND:20180812T210500Z
UID:1Ytu3KQKWQV6ixnwVqJD88YO@stanza.co
SUMMARY:Dragons @ Loons
DESCRIPTION:Dragons @ Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vN1d-q\n\nShop: https://stza.co/+vN1d-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Loons
<2018-08-13 Mon 18:05-21:05>
:PROPERTIES:
:ID:       5GTKEcSDkxLpAMb9iE5kzfbF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Loons Dragons @ Loons

Follow on MiLB First Pitch  https //stza.co/+vN1e-B

Shop  https //stza.co/+vN1e-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Loons
END:VALARM
DTSTART:20180813T230500Z
DTEND:20180814T020500Z
UID:5GTKEcSDkxLpAMb9iE5kzfbF@stanza.co
SUMMARY:Dragons @ Loons
DESCRIPTION:Dragons @ Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vN1e-B\n\nShop: https://stza.co/+vN1e-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Loons
<2018-08-14 Tue 18:05-21:05>
:PROPERTIES:
:ID:       slusXu0iiw-dqu7kvYavWi_G@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Loons Dragons @ Loons

Follow on MiLB First Pitch  https //stza.co/+vN1f-2e

Shop  https //stza.co/+vN1f-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Loons
END:VALARM
DTSTART:20180814T230500Z
DTEND:20180815T020500Z
UID:slusXu0iiw-dqu7kvYavWi_G@stanza.co
SUMMARY:Dragons @ Loons
DESCRIPTION:Dragons @ Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vN1f-2e\n\nShop: https://stza.co/+vN1f-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Captains
<2018-08-15 Wed 18:00-21:00>
:PROPERTIES:
:ID:       U3jPM7icVC0F1sb7vgsNj7Gw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons vs. Captains Dragons vs. Captains

Follow on MiLB First Pitch  https //stza.co/+vN0C-R

Shop  https //stza.co/+vN0C-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Captains
END:VALARM
DTSTART:20180815T230000Z
DTEND:20180816T020000Z
UID:U3jPM7icVC0F1sb7vgsNj7Gw@stanza.co
SUMMARY:Dragons vs. Captains
DESCRIPTION:Dragons vs. Captains\n\nFollow on MiLB First Pitch: https://stza.co/+vN0C-R\n\nShop: https://stza.co/+vN0C-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Captains
<2018-08-16 Thu 18:00-21:00>
:PROPERTIES:
:ID:       cVvZEFcl2HLHkuQj3mRymio3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Captains Dragons vs. Captains

Follow on MiLB First Pitch  https //stza.co/+vN0D-V

Shop  https //stza.co/+vN0D-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Captains
END:VALARM
DTSTART:20180816T230000Z
DTEND:20180817T020000Z
UID:cVvZEFcl2HLHkuQj3mRymio3@stanza.co
SUMMARY:Dragons vs. Captains
DESCRIPTION:Dragons vs. Captains\n\nFollow on MiLB First Pitch: https://stza.co/+vN0D-V\n\nShop: https://stza.co/+vN0D-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Captains
<2018-08-17 Fri 18:00-21:00>
:PROPERTIES:
:ID:       nq2YVbi_-952vSzAUql7DT1w@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Captains Dragons vs. Captains

Follow on MiLB First Pitch  https //stza.co/+vN0G-1p

Shop  https //stza.co/+vN0G-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Captains
END:VALARM
DTSTART:20180817T230000Z
DTEND:20180818T020000Z
UID:nq2YVbi_-952vSzAUql7DT1w@stanza.co
SUMMARY:Dragons vs. Captains
DESCRIPTION:Dragons vs. Captains\n\nFollow on MiLB First Pitch: https://stza.co/+vN0G-1p\n\nShop: https://stza.co/+vN0G-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Hot Rods
<2018-08-18 Sat 18:00-21:00>
:PROPERTIES:
:ID:       KhQneSPd8j0G6ISN9bWpYFYA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons vs. Hot Rods Dragons vs. Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vN0H-1y

Shop  https //stza.co/+vN0H-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Hot Rods
END:VALARM
DTSTART:20180818T230000Z
DTEND:20180819T020000Z
UID:KhQneSPd8j0G6ISN9bWpYFYA@stanza.co
SUMMARY:Dragons vs. Hot Rods
DESCRIPTION:Dragons vs. Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vN0H-1y\n\nShop: https://stza.co/+vN0H-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Hot Rods
<2018-08-19 Sun 13:00-16:00>
:PROPERTIES:
:ID:       ycMcr73ih_zIJ86QyxHtO0pU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Hot Rods Dragons vs. Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vN0J-2L

Shop  https //stza.co/+vN0J-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Hot Rods
END:VALARM
DTSTART:20180819T180000Z
DTEND:20180819T210000Z
UID:ycMcr73ih_zIJ86QyxHtO0pU@stanza.co
SUMMARY:Dragons vs. Hot Rods
DESCRIPTION:Dragons vs. Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vN0J-2L\n\nShop: https://stza.co/+vN0J-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Hot Rods
<2018-08-20 Mon 18:00-21:00>
:PROPERTIES:
:ID:       SioTQa53UcHUnJtJthzY97Wl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Hot Rods Dragons vs. Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vN0M-1B

Shop  https //stza.co/+vN0M-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Hot Rods
END:VALARM
DTSTART:20180820T230000Z
DTEND:20180821T020000Z
UID:SioTQa53UcHUnJtJthzY97Wl@stanza.co
SUMMARY:Dragons vs. Hot Rods
DESCRIPTION:Dragons vs. Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vN0M-1B\n\nShop: https://stza.co/+vN0M-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Whitecaps
<2018-08-21 Tue 18:05-21:05>
:PROPERTIES:
:ID:       ExGNqgKhiN30j3mpAGLjXaa9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons @ Whitecaps Dragons @ Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vq7r-p

Shop  https //stza.co/+vq7r-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Whitecaps
END:VALARM
DTSTART:20180821T230500Z
DTEND:20180822T020500Z
UID:ExGNqgKhiN30j3mpAGLjXaa9@stanza.co
SUMMARY:Dragons @ Whitecaps
DESCRIPTION:Dragons @ Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vq7r-p\n\nShop: https://stza.co/+vq7r-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Whitecaps
<2018-08-22 Wed 18:05-21:05>
:PROPERTIES:
:ID:       fMN2jTw9JpC2mDJh-fr6k5t-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Whitecaps Dragons @ Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vq7s-1k

Shop  https //stza.co/+vq7s-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Whitecaps
END:VALARM
DTSTART:20180822T230500Z
DTEND:20180823T020500Z
UID:fMN2jTw9JpC2mDJh-fr6k5t-@stanza.co
SUMMARY:Dragons @ Whitecaps
DESCRIPTION:Dragons @ Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vq7s-1k\n\nShop: https://stza.co/+vq7s-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Whitecaps
<2018-08-23 Thu 18:05-21:05>
:PROPERTIES:
:ID:       ZpoE1PMQa9sSH1ZVNpOvTdkv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Whitecaps Dragons @ Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vq7t-A

Shop  https //stza.co/+vq7t-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Whitecaps
END:VALARM
DTSTART:20180823T230500Z
DTEND:20180824T020500Z
UID:ZpoE1PMQa9sSH1ZVNpOvTdkv@stanza.co
SUMMARY:Dragons @ Whitecaps
DESCRIPTION:Dragons @ Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vq7t-A\n\nShop: https://stza.co/+vq7t-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Lugnuts
<2018-08-24 Fri 18:00-21:00>
:PROPERTIES:
:ID:       uN8J20b4jBCYbgZiVD-HM68w@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons vs. Lugnuts Dragons vs. Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vN0N-1z

Shop  https //stza.co/+vN0N-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Lugnuts
END:VALARM
DTSTART:20180824T230000Z
DTEND:20180825T020000Z
UID:uN8J20b4jBCYbgZiVD-HM68w@stanza.co
SUMMARY:Dragons vs. Lugnuts
DESCRIPTION:Dragons vs. Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vN0N-1z\n\nShop: https://stza.co/+vN0N-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Lugnuts
<2018-08-25 Sat 18:00-21:00>
:PROPERTIES:
:ID:       0OUipAvoiGgB1ZiFzQBjxV0G@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Lugnuts Dragons vs. Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vN0Q-w

Shop  https //stza.co/+vN0Q-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Lugnuts
END:VALARM
DTSTART:20180825T230000Z
DTEND:20180826T020000Z
UID:0OUipAvoiGgB1ZiFzQBjxV0G@stanza.co
SUMMARY:Dragons vs. Lugnuts
DESCRIPTION:Dragons vs. Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vN0Q-w\n\nShop: https://stza.co/+vN0Q-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Lugnuts
<2018-08-26 Sun 13:00-16:00>
:PROPERTIES:
:ID:       MjkHzHM8C31-rYf8mRUyz5eu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Lugnuts Dragons vs. Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vN0S-2Z

Shop  https //stza.co/+vN0S-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Lugnuts
END:VALARM
DTSTART:20180826T180000Z
DTEND:20180826T210000Z
UID:MjkHzHM8C31-rYf8mRUyz5eu@stanza.co
SUMMARY:Dragons vs. Lugnuts
DESCRIPTION:Dragons vs. Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vN0S-2Z\n\nShop: https://stza.co/+vN0S-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Lugnuts
<2018-08-27 Mon 18:00-21:00>
:PROPERTIES:
:ID:       Y58TWlAMsOxRKekxVyExaYY8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons vs. Lugnuts Dragons vs. Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vN0T-3q

Shop  https //stza.co/+vN0T-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Lugnuts
END:VALARM
DTSTART:20180827T230000Z
DTEND:20180828T020000Z
UID:Y58TWlAMsOxRKekxVyExaYY8@stanza.co
SUMMARY:Dragons vs. Lugnuts
DESCRIPTION:Dragons vs. Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vN0T-3q\n\nShop: https://stza.co/+vN0T-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Whitecaps
<2018-08-29 Wed 18:00-21:00>
:PROPERTIES:
:ID:       Y6t6SI6u_6C1WR3c01h7zGun@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Whitecaps Dragons vs. Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vN0V-3G

Shop  https //stza.co/+vN0V-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Whitecaps
END:VALARM
DTSTART:20180829T230000Z
DTEND:20180830T020000Z
UID:Y6t6SI6u_6C1WR3c01h7zGun@stanza.co
SUMMARY:Dragons vs. Whitecaps
DESCRIPTION:Dragons vs. Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vN0V-3G\n\nShop: https://stza.co/+vN0V-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Whitecaps
<2018-08-30 Thu 18:00-21:00>
:PROPERTIES:
:ID:       54hM9AzqQH7Nt9_hchAMLgdP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons vs. Whitecaps Dragons vs. Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vN0Y-1_

Shop  https //stza.co/+vN0Y-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Whitecaps
END:VALARM
DTSTART:20180830T230000Z
DTEND:20180831T020000Z
UID:54hM9AzqQH7Nt9_hchAMLgdP@stanza.co
SUMMARY:Dragons vs. Whitecaps
DESCRIPTION:Dragons vs. Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vN0Y-1_\n\nShop: https://stza.co/+vN0Y-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons vs. Whitecaps
<2018-08-31 Fri 18:00-21:00>
:PROPERTIES:
:ID:       pouBxgXeyn6w8XAWwRtvla4u@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons vs. Whitecaps Dragons vs. Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vN0Z-e

Shop  https //stza.co/+vN0Z-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dragons vs. Whitecaps
END:VALARM
DTSTART:20180831T230000Z
DTEND:20180901T020000Z
UID:pouBxgXeyn6w8XAWwRtvla4u@stanza.co
SUMMARY:Dragons vs. Whitecaps
DESCRIPTION:Dragons vs. Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vN0Z-e\n\nShop: https://stza.co/+vN0Z-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Hot Rods
<2018-09-01 Sat 18:35-21:35>
:PROPERTIES:
:ID:       nuWO38DB8IyBVRLimK4KFTcl@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Hot Rods Dragons @ Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vM_G-3S

Shop  https //stza.co/+vM_G-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Hot Rods
END:VALARM
DTSTART:20180901T233500Z
DTEND:20180902T023500Z
UID:nuWO38DB8IyBVRLimK4KFTcl@stanza.co
SUMMARY:Dragons @ Hot Rods
DESCRIPTION:Dragons @ Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vM_G-3S\n\nShop: https://stza.co/+vM_G-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Hot Rods
<2018-09-02 Sun 18:35-21:35>
:PROPERTIES:
:ID:       JqvfG_KAR19Sm565B-72isKm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dragons @ Hot Rods Dragons @ Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vM_H-1Y

Shop  https //stza.co/+vM_H-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Hot Rods
END:VALARM
DTSTART:20180902T233500Z
DTEND:20180903T023500Z
UID:JqvfG_KAR19Sm565B-72isKm@stanza.co
SUMMARY:Dragons @ Hot Rods
DESCRIPTION:Dragons @ Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vM_H-1Y\n\nShop: https://stza.co/+vM_H-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Dragons @ Hot Rods
<2018-09-03 Mon 12:05-15:05>
:PROPERTIES:
:ID:       fwrsB4xwCGiLn7DbNuJRwsDm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dragons @ Hot Rods Dragons @ Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vM_I-2m

Shop  https //stza.co/+vM_I-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dragons @ Hot Rods
END:VALARM
DTSTART:20180903T170500Z
DTEND:20180903T200500Z
UID:fwrsB4xwCGiLn7DbNuJRwsDm@stanza.co
SUMMARY:Dragons @ Hot Rods
DESCRIPTION:Dragons @ Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vM_I-2m\n\nShop: https://stza.co/+vM_I-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
