#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Dodgers @ Cubs
<2018-04-05 Thu 15:08-18:08>
:PROPERTIES:
:ID:       7ebL2tGlLP1LWa-LDpXBJyd8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Cubs Dodgers @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKOg-2$

Shop  https //stza.co/+vKOg-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Cubs
END:VALARM
DTSTART:20180405T200800Z
DTEND:20180405T230800Z
UID:7ebL2tGlLP1LWa-LDpXBJyd8@stanza.co
SUMMARY:Dodgers @ Cubs
DESCRIPTION:Dodgers @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKOg-2$\n\nShop: https://stza.co/+vKOg-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Cubs
<2018-04-06 Fri 19:08-22:08>
:PROPERTIES:
:ID:       91UmjVanu3U4SAEjFT83vqDM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers @ Cubs Dodgers @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKOh-1M

Shop  https //stza.co/+vKOh-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Cubs
END:VALARM
DTSTART:20180407T000800Z
DTEND:20180407T030800Z
UID:91UmjVanu3U4SAEjFT83vqDM@stanza.co
SUMMARY:Dodgers @ Cubs
DESCRIPTION:Dodgers @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKOh-1M\n\nShop: https://stza.co/+vKOh-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Cubs
<2018-04-07 Sat 19:08-22:08>
:PROPERTIES:
:ID:       r08dNXRPpwUVWpf9PAuJsG7s@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Cubs Dodgers @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKOi-1V

Shop  https //stza.co/+vKOi-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Cubs
END:VALARM
DTSTART:20180408T000800Z
DTEND:20180408T030800Z
UID:r08dNXRPpwUVWpf9PAuJsG7s@stanza.co
SUMMARY:Dodgers @ Cubs
DESCRIPTION:Dodgers @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKOi-1V\n\nShop: https://stza.co/+vKOi-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Cubs
<2018-04-08 Sun 13:08-16:08>
:PROPERTIES:
:ID:       nGW1Nkt1SFOpA6L6X_SHaFjP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Cubs Dodgers @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKOj-3L

Shop  https //stza.co/+vKOj-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Cubs
END:VALARM
DTSTART:20180408T180800Z
DTEND:20180408T210800Z
UID:nGW1Nkt1SFOpA6L6X_SHaFjP@stanza.co
SUMMARY:Dodgers @ Cubs
DESCRIPTION:Dodgers @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKOj-3L\n\nShop: https://stza.co/+vKOj-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Cubs
<2018-04-09 Mon 12:08-15:08>
:PROPERTIES:
:ID:       RrJGKh6WWkTuX0ytmKz-ebzq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers @ Cubs Dodgers @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKOk-1C

Shop  https //stza.co/+vKOk-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Cubs
END:VALARM
DTSTART:20180409T170800Z
DTEND:20180409T200800Z
UID:RrJGKh6WWkTuX0ytmKz-ebzq@stanza.co
SUMMARY:Dodgers @ Cubs
DESCRIPTION:Dodgers @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKOk-1C\n\nShop: https://stza.co/+vKOk-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Express
<2018-04-10 Tue 19:05-22:05>
:PROPERTIES:
:ID:       NJCZNyeKmynLtBZUKQGcIqwg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Express Dodgers vs. Express

Follow on MiLB First Pitch  https //stza.co/+v$MR-M

Shop  https //stza.co/+v$MR-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Express
END:VALARM
DTSTART:20180411T000500Z
DTEND:20180411T030500Z
UID:NJCZNyeKmynLtBZUKQGcIqwg@stanza.co
SUMMARY:Dodgers vs. Express
DESCRIPTION:Dodgers vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+v$MR-M\n\nShop: https://stza.co/+v$MR-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Express
<2018-04-11 Wed 19:05-22:05>
:PROPERTIES:
:ID:       VZck3duAoNkmzu9c5kElciD_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Express Dodgers vs. Express

Follow on MiLB First Pitch  https //stza.co/+v$MU-3p

Shop  https //stza.co/+v$MU-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Express
END:VALARM
DTSTART:20180412T000500Z
DTEND:20180412T030500Z
UID:VZck3duAoNkmzu9c5kElciD_@stanza.co
SUMMARY:Dodgers vs. Express
DESCRIPTION:Dodgers vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+v$MU-3p\n\nShop: https://stza.co/+v$MU-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Express
<2018-04-12 Thu 19:05-22:05>
:PROPERTIES:
:ID:       seSBcDl2vl59muXKH8BFeTrn@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Express Dodgers vs. Express

Follow on MiLB First Pitch  https //stza.co/+v$MV-1F

Shop  https //stza.co/+v$MV-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Express
END:VALARM
DTSTART:20180413T000500Z
DTEND:20180413T030500Z
UID:seSBcDl2vl59muXKH8BFeTrn@stanza.co
SUMMARY:Dodgers vs. Express
DESCRIPTION:Dodgers vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+v$MV-1F\n\nShop: https://stza.co/+v$MV-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Baby Cakes
<2018-04-13 Fri 19:05-22:05>
:PROPERTIES:
:ID:       37yvfvS61MEwtpRaVFnsKqb0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Baby Cakes Dodgers vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+v$MX-z

Shop  https //stza.co/+v$MX-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Baby Cakes
END:VALARM
DTSTART:20180414T000500Z
DTEND:20180414T030500Z
UID:37yvfvS61MEwtpRaVFnsKqb0@stanza.co
SUMMARY:Dodgers vs. Baby Cakes
DESCRIPTION:Dodgers vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+v$MX-z\n\nShop: https://stza.co/+v$MX-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Baby Cakes
<2018-04-14 Sat 19:05-22:05>
:PROPERTIES:
:ID:       WqE1_gj9k-SF9xBohT0R4epL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Baby Cakes Dodgers vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+v$M_-M

Shop  https //stza.co/+v$M_-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Baby Cakes
END:VALARM
DTSTART:20180415T000500Z
DTEND:20180415T030500Z
UID:WqE1_gj9k-SF9xBohT0R4epL@stanza.co
SUMMARY:Dodgers vs. Baby Cakes
DESCRIPTION:Dodgers vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+v$M_-M\n\nShop: https://stza.co/+v$M_-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Baby Cakes
<2018-04-15 Sun 14:05-17:05>
:PROPERTIES:
:ID:       _DVtPyFKbd9u54XpNUXBg8c1@stanza.co
:LOCATION: Chaparral Energy Family Sundays
:STATUS:   CONFIRMED
:END:

Dodgers vs. Baby Cakes 



Follow on MiLB First Pitch  https //stza.co/+v$M$-3z

Shop  https //stza.co/+v$M$-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Baby Cakes
END:VALARM
DTSTART:20180415T190500Z
DTEND:20180415T220500Z
UID:_DVtPyFKbd9u54XpNUXBg8c1@stanza.co
SUMMARY:Dodgers vs. Baby Cakes
DESCRIPTION:\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+v$M$-3z\n\nShop: https://stza.co/+v$M$-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Chaparral Energy Family Sundays
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Baby Cakes
<2018-04-16 Mon 19:05-22:05>
:PROPERTIES:
:ID:       iBie1ib10DaUBJL45-mGxhBJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Baby Cakes Dodgers vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+v$N1-2s

Shop  https //stza.co/+v$N1-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Baby Cakes
END:VALARM
DTSTART:20180417T000500Z
DTEND:20180417T030500Z
UID:iBie1ib10DaUBJL45-mGxhBJ@stanza.co
SUMMARY:Dodgers vs. Baby Cakes
DESCRIPTION:Dodgers vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+v$N1-2s\n\nShop: https://stza.co/+v$N1-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Express
<2018-04-17 Tue 19:05-22:05>
:PROPERTIES:
:ID:       pCaRHAnZQSvzvzxW36NfIs1-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Express Dodgers @ Express

Follow on MiLB First Pitch  https //stza.co/+v3dN-2o

Shop  https //stza.co/+v3dN-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Express
END:VALARM
DTSTART:20180418T000500Z
DTEND:20180418T030500Z
UID:pCaRHAnZQSvzvzxW36NfIs1-@stanza.co
SUMMARY:Dodgers @ Express
DESCRIPTION:Dodgers @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+v3dN-2o\n\nShop: https://stza.co/+v3dN-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Express
<2018-04-18 Wed 11:35-14:35>
:PROPERTIES:
:ID:       VeJAvzOijNOHZ4yAmPSJSMcW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Express Dodgers @ Express

Follow on MiLB First Pitch  https //stza.co/+v3dO-1D

Shop  https //stza.co/+v3dO-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Express
END:VALARM
DTSTART:20180418T163500Z
DTEND:20180418T193500Z
UID:VeJAvzOijNOHZ4yAmPSJSMcW@stanza.co
SUMMARY:Dodgers @ Express
DESCRIPTION:Dodgers @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+v3dO-1D\n\nShop: https://stza.co/+v3dO-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Express
<2018-04-19 Thu 19:05-22:05>
:PROPERTIES:
:ID:       r2rOm68xVjaR4XCB3N8G7Xzy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers @ Express Dodgers @ Express

Follow on MiLB First Pitch  https //stza.co/+v3dP-2g

Shop  https //stza.co/+v3dP-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Express
END:VALARM
DTSTART:20180420T000500Z
DTEND:20180420T030500Z
UID:r2rOm68xVjaR4XCB3N8G7Xzy@stanza.co
SUMMARY:Dodgers @ Express
DESCRIPTION:Dodgers @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+v3dP-2g\n\nShop: https://stza.co/+v3dP-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Express
<2018-04-20 Fri 19:05-22:05>
:PROPERTIES:
:ID:       FPVS-xDPEoNJ4DLvCm3pKPXw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Express Dodgers @ Express

Follow on MiLB First Pitch  https //stza.co/+v3dQ-2Y

Shop  https //stza.co/+v3dQ-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Express
END:VALARM
DTSTART:20180421T000500Z
DTEND:20180421T030500Z
UID:FPVS-xDPEoNJ4DLvCm3pKPXw@stanza.co
SUMMARY:Dodgers @ Express
DESCRIPTION:Dodgers @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+v3dQ-2Y\n\nShop: https://stza.co/+v3dQ-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Baby Cakes
<2018-04-21 Sat 18:00-21:00>
:PROPERTIES:
:ID:       vBtHA_PWQzCm2iKW1cp2lieu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Baby Cakes Dodgers @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whM7-2j

Shop  https //stza.co/+whM7-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Baby Cakes
END:VALARM
DTSTART:20180421T230000Z
DTEND:20180422T020000Z
UID:vBtHA_PWQzCm2iKW1cp2lieu@stanza.co
SUMMARY:Dodgers @ Baby Cakes
DESCRIPTION:Dodgers @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whM7-2j\n\nShop: https://stza.co/+whM7-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Baby Cakes
<2018-04-22 Sun 13:00-16:00>
:PROPERTIES:
:ID:       pE7QvKzybIA-wVVM3awebUGA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers @ Baby Cakes Dodgers @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whM8-1V

Shop  https //stza.co/+whM8-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Baby Cakes
END:VALARM
DTSTART:20180422T180000Z
DTEND:20180422T210000Z
UID:pE7QvKzybIA-wVVM3awebUGA@stanza.co
SUMMARY:Dodgers @ Baby Cakes
DESCRIPTION:Dodgers @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whM8-1V\n\nShop: https://stza.co/+whM8-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Baby Cakes
<2018-04-23 Mon 11:00-14:00>
:PROPERTIES:
:ID:       w0PBD2OGUIMesciWp3J1w8cY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Baby Cakes Dodgers @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whMa-3h

Shop  https //stza.co/+whMa-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Baby Cakes
END:VALARM
DTSTART:20180423T160000Z
DTEND:20180423T190000Z
UID:w0PBD2OGUIMesciWp3J1w8cY@stanza.co
SUMMARY:Dodgers @ Baby Cakes
DESCRIPTION:Dodgers @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whMa-3h\n\nShop: https://stza.co/+whMa-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Cubs
<2018-04-25 Wed 19:05-22:05>
:PROPERTIES:
:ID:       kdlFPKXrrfjTnOpH1RibZEJH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Cubs Dodgers vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+v$N4-s

Shop  https //stza.co/+v$N4-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Cubs
END:VALARM
DTSTART:20180426T000500Z
DTEND:20180426T030500Z
UID:kdlFPKXrrfjTnOpH1RibZEJH@stanza.co
SUMMARY:Dodgers vs. Cubs
DESCRIPTION:Dodgers vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+v$N4-s\n\nShop: https://stza.co/+v$N4-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Cubs
<2018-04-26 Thu 19:05-22:05>
:PROPERTIES:
:ID:       Y36kDAgZi2jqs8o0DA_4_PrV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Cubs Dodgers vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+v$N6-1E

Shop  https //stza.co/+v$N6-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Cubs
END:VALARM
DTSTART:20180427T000500Z
DTEND:20180427T030500Z
UID:Y36kDAgZi2jqs8o0DA_4_PrV@stanza.co
SUMMARY:Dodgers vs. Cubs
DESCRIPTION:Dodgers vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+v$N6-1E\n\nShop: https://stza.co/+v$N6-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Cubs
<2018-04-27 Fri 19:05-22:05>
:PROPERTIES:
:ID:       tEgkEM7bgkfmq3iQf9d7xM_S@stanza.co
:LOCATION: Celebrate the start of the weekend with our Friday Night Fireworks after the game!
:STATUS:   CONFIRMED
:END:

Dodgers vs. Cubs 



Follow on MiLB First Pitch  https //stza.co/+v$N7-1q

Shop  https //stza.co/+v$N7-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Cubs
END:VALARM
DTSTART:20180428T000500Z
DTEND:20180428T030500Z
UID:tEgkEM7bgkfmq3iQf9d7xM_S@stanza.co
SUMMARY:Dodgers vs. Cubs
DESCRIPTION:\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+v$N7-1q\n\nShop: https://stza.co/+v$N7-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Celebrate the start of the weekend with our Friday Night Fireworks after the game!
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Cubs
<2018-04-28 Sat 19:05-22:05>
:PROPERTIES:
:ID:       UowxFJh0CL_2yIGV2X1HkFe5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Cubs Dodgers vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+v$Na-39

Shop  https //stza.co/+v$Na-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Cubs
END:VALARM
DTSTART:20180429T000500Z
DTEND:20180429T030500Z
UID:UowxFJh0CL_2yIGV2X1HkFe5@stanza.co
SUMMARY:Dodgers vs. Cubs
DESCRIPTION:Dodgers vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+v$Na-39\n\nShop: https://stza.co/+v$Na-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Cubs
<2018-04-29 Sun 14:05-17:05>
:PROPERTIES:
:ID:       yFNbZf5grqFd6cqPL0_tzrBs@stanza.co
:LOCATION: Chaparral Energy Family Sundays
:STATUS:   CONFIRMED
:END:

Dodgers vs. Cubs 



Follow on MiLB First Pitch  https //stza.co/+v$Nc-2v

Shop  https //stza.co/+v$Nc-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Cubs
END:VALARM
DTSTART:20180429T190500Z
DTEND:20180429T220500Z
UID:yFNbZf5grqFd6cqPL0_tzrBs@stanza.co
SUMMARY:Dodgers vs. Cubs
DESCRIPTION:\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+v$Nc-2v\n\nShop: https://stza.co/+v$Nc-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Chaparral Energy Family Sundays
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Redbirds
<2018-04-30 Mon 18:35-21:35>
:PROPERTIES:
:ID:       EFq85iX73Ytz3jKGHhvXJZQd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Redbirds Dodgers @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmIk-3l

Shop  https //stza.co/+wmIk-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Redbirds
END:VALARM
DTSTART:20180430T233500Z
DTEND:20180501T023500Z
UID:EFq85iX73Ytz3jKGHhvXJZQd@stanza.co
SUMMARY:Dodgers @ Redbirds
DESCRIPTION:Dodgers @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmIk-3l\n\nShop: https://stza.co/+wmIk-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Redbirds
<2018-05-01 Tue 18:35-21:35>
:PROPERTIES:
:ID:       ni26WxF16dtPqyph-WOx7J4b@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers @ Redbirds Dodgers @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmIl-13

Shop  https //stza.co/+wmIl-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Redbirds
END:VALARM
DTSTART:20180501T233500Z
DTEND:20180502T023500Z
UID:ni26WxF16dtPqyph-WOx7J4b@stanza.co
SUMMARY:Dodgers @ Redbirds
DESCRIPTION:Dodgers @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmIl-13\n\nShop: https://stza.co/+wmIl-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Redbirds
<2018-05-02 Wed 18:35-21:35>
:PROPERTIES:
:ID:       _3TymHgHLMRsBBCxxXMPCQy9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Redbirds Dodgers @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmIm-D

Shop  https //stza.co/+wmIm-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Redbirds
END:VALARM
DTSTART:20180502T233500Z
DTEND:20180503T023500Z
UID:_3TymHgHLMRsBBCxxXMPCQy9@stanza.co
SUMMARY:Dodgers @ Redbirds
DESCRIPTION:Dodgers @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmIm-D\n\nShop: https://stza.co/+wmIm-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Redbirds
<2018-05-03 Thu 19:05-22:05>
:PROPERTIES:
:ID:       ehXJmMtKdQH22i1gAgyeSM_2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Redbirds Dodgers @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmIn-2b

Shop  https //stza.co/+wmIn-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Redbirds
END:VALARM
DTSTART:20180504T000500Z
DTEND:20180504T030500Z
UID:ehXJmMtKdQH22i1gAgyeSM_2@stanza.co
SUMMARY:Dodgers @ Redbirds
DESCRIPTION:Dodgers @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmIn-2b\n\nShop: https://stza.co/+wmIn-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Sky Sox
<2018-05-04 Fri 19:05-22:05>
:PROPERTIES:
:ID:       3ClFc211q-ljfcRFLGNhkAiU@stanza.co
:LOCATION: Celebrate the start of the weekend with our Friday Night Fireworks after the game!
:STATUS:   CONFIRMED
:END:

Dodgers vs. Sky Sox 



Follow on MiLB First Pitch  https //stza.co/+v$Ne-1r

Shop  https //stza.co/+v$Ne-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Sky Sox
END:VALARM
DTSTART:20180505T000500Z
DTEND:20180505T030500Z
UID:3ClFc211q-ljfcRFLGNhkAiU@stanza.co
SUMMARY:Dodgers vs. Sky Sox
DESCRIPTION:\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+v$Ne-1r\n\nShop: https://stza.co/+v$Ne-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Celebrate the start of the weekend with our Friday Night Fireworks after the game!
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Sky Sox
<2018-05-05 Sat 19:05-22:05>
:PROPERTIES:
:ID:       bDeumSrV7G2SBCgOMpzTuikL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Sky Sox Dodgers vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+v$Nf-3z

Shop  https //stza.co/+v$Nf-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Sky Sox
END:VALARM
DTSTART:20180506T000500Z
DTEND:20180506T030500Z
UID:bDeumSrV7G2SBCgOMpzTuikL@stanza.co
SUMMARY:Dodgers vs. Sky Sox
DESCRIPTION:Dodgers vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+v$Nf-3z\n\nShop: https://stza.co/+v$Nf-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Sky Sox
<2018-05-06 Sun 14:05-17:05>
:PROPERTIES:
:ID:       Nm4Il0QU0_iTi-LNI7JY1HXo@stanza.co
:LOCATION: Chaparral Energy Family Sundays
:STATUS:   CONFIRMED
:END:

Dodgers vs. Sky Sox 



Follow on MiLB First Pitch  https //stza.co/+v$Ni-2w

Shop  https //stza.co/+v$Ni-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Sky Sox
END:VALARM
DTSTART:20180506T190500Z
DTEND:20180506T220500Z
UID:Nm4Il0QU0_iTi-LNI7JY1HXo@stanza.co
SUMMARY:Dodgers vs. Sky Sox
DESCRIPTION:\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+v$Ni-2w\n\nShop: https://stza.co/+v$Ni-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Chaparral Energy Family Sundays
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Sky Sox
<2018-05-07 Mon 11:05-14:05>
:PROPERTIES:
:ID:       SlquBBUBDlxM2e3nOhUtaeok@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Sky Sox Dodgers vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+v$Nk-2W

Shop  https //stza.co/+v$Nk-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Sky Sox
END:VALARM
DTSTART:20180507T160500Z
DTEND:20180507T190500Z
UID:SlquBBUBDlxM2e3nOhUtaeok@stanza.co
SUMMARY:Dodgers vs. Sky Sox
DESCRIPTION:Dodgers vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+v$Nk-2W\n\nShop: https://stza.co/+v$Nk-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Redbirds
<2018-05-08 Tue 19:05-22:05>
:PROPERTIES:
:ID:       ge9X1eCZzNRsRzRB07PmZJR0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Redbirds Dodgers vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+v$Nl-p

Shop  https //stza.co/+v$Nl-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Redbirds
END:VALARM
DTSTART:20180509T000500Z
DTEND:20180509T030500Z
UID:ge9X1eCZzNRsRzRB07PmZJR0@stanza.co
SUMMARY:Dodgers vs. Redbirds
DESCRIPTION:Dodgers vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+v$Nl-p\n\nShop: https://stza.co/+v$Nl-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Redbirds
<2018-05-09 Wed 11:05-14:05>
:PROPERTIES:
:ID:       8bDtF8lZ6a6jwn4EBiuSFpdy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Redbirds Dodgers vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+v$Nn-1b

Shop  https //stza.co/+v$Nn-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Redbirds
END:VALARM
DTSTART:20180509T160500Z
DTEND:20180509T190500Z
UID:8bDtF8lZ6a6jwn4EBiuSFpdy@stanza.co
SUMMARY:Dodgers vs. Redbirds
DESCRIPTION:Dodgers vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+v$Nn-1b\n\nShop: https://stza.co/+v$Nn-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Redbirds
<2018-05-10 Thu 19:05-22:05>
:PROPERTIES:
:ID:       FY6eMAnVxY1tL9f1WsPKR3wF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Redbirds Dodgers vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+v$Np-W

Shop  https //stza.co/+v$Np-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Redbirds
END:VALARM
DTSTART:20180511T000500Z
DTEND:20180511T030500Z
UID:FY6eMAnVxY1tL9f1WsPKR3wF@stanza.co
SUMMARY:Dodgers vs. Redbirds
DESCRIPTION:Dodgers vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+v$Np-W\n\nShop: https://stza.co/+v$Np-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Redbirds
<2018-05-11 Fri 19:05-22:05>
:PROPERTIES:
:ID:       Bs1KYG28mpTw5Vxg-5nXUwCR@stanza.co
:LOCATION: Celebrate the start of the weekend with our Friday Night Fireworks after the game!
:STATUS:   CONFIRMED
:END:

Dodgers vs. Redbirds 



Follow on MiLB First Pitch  https //stza.co/+v$Ns-1l

Shop  https //stza.co/+v$Ns-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Redbirds
END:VALARM
DTSTART:20180512T000500Z
DTEND:20180512T030500Z
UID:Bs1KYG28mpTw5Vxg-5nXUwCR@stanza.co
SUMMARY:Dodgers vs. Redbirds
DESCRIPTION:\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+v$Ns-1l\n\nShop: https://stza.co/+v$Ns-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Celebrate the start of the weekend with our Friday Night Fireworks after the game!
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Sky Sox
<2018-05-12 Sat 19:00-22:00>
:PROPERTIES:
:ID:       Vj9sc2MCrf6f9T5Jwyve2MTG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Sky Sox Dodgers @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmIc-35

Shop  https //stza.co/+wmIc-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Sky Sox
END:VALARM
DTSTART:20180513T000000Z
DTEND:20180513T030000Z
UID:Vj9sc2MCrf6f9T5Jwyve2MTG@stanza.co
SUMMARY:Dodgers @ Sky Sox
DESCRIPTION:Dodgers @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmIc-35\n\nShop: https://stza.co/+wmIc-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Sky Sox
<2018-05-13 Sun 14:30-17:30>
:PROPERTIES:
:ID:       hOGvlhJW8emApwMzLXggTw0_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers @ Sky Sox Dodgers @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmId-39

Shop  https //stza.co/+wmId-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Sky Sox
END:VALARM
DTSTART:20180513T193000Z
DTEND:20180513T223000Z
UID:hOGvlhJW8emApwMzLXggTw0_@stanza.co
SUMMARY:Dodgers @ Sky Sox
DESCRIPTION:Dodgers @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmId-39\n\nShop: https://stza.co/+wmId-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Sky Sox
<2018-05-14 Mon 19:40-22:40>
:PROPERTIES:
:ID:       orcH7WJnm6H5ZlJ5Kmrn5To2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Sky Sox Dodgers @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmIe-p

Shop  https //stza.co/+wmIe-2S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Sky Sox
END:VALARM
DTSTART:20180515T004000Z
DTEND:20180515T034000Z
UID:orcH7WJnm6H5ZlJ5Kmrn5To2@stanza.co
SUMMARY:Dodgers @ Sky Sox
DESCRIPTION:Dodgers @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmIe-p\n\nShop: https://stza.co/+wmIe-2S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Sky Sox
<2018-05-15 Tue 19:40-22:40>
:PROPERTIES:
:ID:       pc0kHdi7sLs8Yv3XeTTpmWxg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Sky Sox Dodgers @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmIf-2A

Shop  https //stza.co/+wmIf-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Sky Sox
END:VALARM
DTSTART:20180516T004000Z
DTEND:20180516T034000Z
UID:pc0kHdi7sLs8Yv3XeTTpmWxg@stanza.co
SUMMARY:Dodgers @ Sky Sox
DESCRIPTION:Dodgers @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmIf-2A\n\nShop: https://stza.co/+wmIf-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Sounds
<2018-05-17 Thu 19:05-22:05>
:PROPERTIES:
:ID:       LHrSH9k7qvA3uFE1rImjVGDi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Sounds Dodgers vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+v$Nu-3Z

Shop  https //stza.co/+v$Nu-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Sounds
END:VALARM
DTSTART:20180518T000500Z
DTEND:20180518T030500Z
UID:LHrSH9k7qvA3uFE1rImjVGDi@stanza.co
SUMMARY:Dodgers vs. Sounds
DESCRIPTION:Dodgers vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+v$Nu-3Z\n\nShop: https://stza.co/+v$Nu-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Sounds
<2018-05-18 Fri 19:05-22:05>
:PROPERTIES:
:ID:       QSO3ISSLSNeeAjACL_NjDndq@stanza.co
:LOCATION: Celebrate the start of the weekend with our Friday Night Fireworks after the game!
:STATUS:   CONFIRMED
:END:

Dodgers vs. Sounds 



Follow on MiLB First Pitch  https //stza.co/+v$Nw-3G

Shop  https //stza.co/+v$Nw-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Sounds
END:VALARM
DTSTART:20180519T000500Z
DTEND:20180519T030500Z
UID:QSO3ISSLSNeeAjACL_NjDndq@stanza.co
SUMMARY:Dodgers vs. Sounds
DESCRIPTION:\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+v$Nw-3G\n\nShop: https://stza.co/+v$Nw-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Celebrate the start of the weekend with our Friday Night Fireworks after the game!
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Sounds
<2018-05-19 Sat 19:05-22:05>
:PROPERTIES:
:ID:       vDQ4wcu8dXl7BcZ5BhcZBBei@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Sounds Dodgers vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+v$Ny-3G

Shop  https //stza.co/+v$Ny-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Sounds
END:VALARM
DTSTART:20180520T000500Z
DTEND:20180520T030500Z
UID:vDQ4wcu8dXl7BcZ5BhcZBBei@stanza.co
SUMMARY:Dodgers vs. Sounds
DESCRIPTION:Dodgers vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+v$Ny-3G\n\nShop: https://stza.co/+v$Ny-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Sounds
<2018-05-20 Sun 14:05-17:05>
:PROPERTIES:
:ID:       n1JyOxGQLdtjFCflqcUJ27On@stanza.co
:LOCATION: Chaparral Energy Family Sundays
:STATUS:   CONFIRMED
:END:

Dodgers vs. Sounds 



Follow on MiLB First Pitch  https //stza.co/+v$NA-y

Shop  https //stza.co/+v$NA-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Sounds
END:VALARM
DTSTART:20180520T190500Z
DTEND:20180520T220500Z
UID:n1JyOxGQLdtjFCflqcUJ27On@stanza.co
SUMMARY:Dodgers vs. Sounds
DESCRIPTION:\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+v$NA-y\n\nShop: https://stza.co/+v$NA-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Chaparral Energy Family Sundays
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Redbirds
<2018-05-21 Mon 18:35-21:35>
:PROPERTIES:
:ID:       FvLSxhNcXL7zVQf52yGosSY5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Redbirds Dodgers @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmIo-2f

Shop  https //stza.co/+wmIo-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Redbirds
END:VALARM
DTSTART:20180521T233500Z
DTEND:20180522T023500Z
UID:FvLSxhNcXL7zVQf52yGosSY5@stanza.co
SUMMARY:Dodgers @ Redbirds
DESCRIPTION:Dodgers @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmIo-2f\n\nShop: https://stza.co/+wmIo-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Redbirds
<2018-05-22 Tue 11:05-14:05>
:PROPERTIES:
:ID:       fcNvzn9URm4bdcXoiN_oN0ZH@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers @ Redbirds Dodgers @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmIp-28

Shop  https //stza.co/+wmIp-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Redbirds
END:VALARM
DTSTART:20180522T160500Z
DTEND:20180522T190500Z
UID:fcNvzn9URm4bdcXoiN_oN0ZH@stanza.co
SUMMARY:Dodgers @ Redbirds
DESCRIPTION:Dodgers @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmIp-28\n\nShop: https://stza.co/+wmIp-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Redbirds
<2018-05-23 Wed 18:35-21:35>
:PROPERTIES:
:ID:       EsJxa1pZkFhjvaFYWJ9pBoKA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Redbirds Dodgers @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmIq-1C

Shop  https //stza.co/+wmIq-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Redbirds
END:VALARM
DTSTART:20180523T233500Z
DTEND:20180524T023500Z
UID:EsJxa1pZkFhjvaFYWJ9pBoKA@stanza.co
SUMMARY:Dodgers @ Redbirds
DESCRIPTION:Dodgers @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmIq-1C\n\nShop: https://stza.co/+wmIq-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Redbirds
<2018-05-24 Thu 19:05-22:05>
:PROPERTIES:
:ID:       tyEdF6KimB4R-Ao1i8hX8VnJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Redbirds Dodgers @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmIr-p

Shop  https //stza.co/+wmIr-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Redbirds
END:VALARM
DTSTART:20180525T000500Z
DTEND:20180525T030500Z
UID:tyEdF6KimB4R-Ao1i8hX8VnJ@stanza.co
SUMMARY:Dodgers @ Redbirds
DESCRIPTION:Dodgers @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmIr-p\n\nShop: https://stza.co/+wmIr-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Sounds
<2018-05-25 Fri 18:35-21:35>
:PROPERTIES:
:ID:       PnuKQVndNw15ky_r4KbGPth3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers @ Sounds Dodgers @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whL_-Z

Shop  https //stza.co/+whL_-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Sounds
END:VALARM
DTSTART:20180525T233500Z
DTEND:20180526T023500Z
UID:PnuKQVndNw15ky_r4KbGPth3@stanza.co
SUMMARY:Dodgers @ Sounds
DESCRIPTION:Dodgers @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whL_-Z\n\nShop: https://stza.co/+whL_-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Sounds
<2018-05-26 Sat 18:35-21:35>
:PROPERTIES:
:ID:       SE-P98zPSf0iGw6ELC3Ij0N7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Sounds Dodgers @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whM0-3C

Shop  https //stza.co/+whM0-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Sounds
END:VALARM
DTSTART:20180526T233500Z
DTEND:20180527T023500Z
UID:SE-P98zPSf0iGw6ELC3Ij0N7@stanza.co
SUMMARY:Dodgers @ Sounds
DESCRIPTION:Dodgers @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whM0-3C\n\nShop: https://stza.co/+whM0-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Sounds
<2018-05-27 Sun 18:35-21:35>
:PROPERTIES:
:ID:       YxFEZFYQ04tspsRmj4OArWsh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Sounds Dodgers @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whM1-2g

Shop  https //stza.co/+whM1-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Sounds
END:VALARM
DTSTART:20180527T233500Z
DTEND:20180528T023500Z
UID:YxFEZFYQ04tspsRmj4OArWsh@stanza.co
SUMMARY:Dodgers @ Sounds
DESCRIPTION:Dodgers @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whM1-2g\n\nShop: https://stza.co/+whM1-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Sounds
<2018-05-28 Mon 12:05-15:05>
:PROPERTIES:
:ID:       p4S7CLJezbpO9CHBIKq7_WF9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers @ Sounds Dodgers @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whM2-3v

Shop  https //stza.co/+whM2-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Sounds
END:VALARM
DTSTART:20180528T170500Z
DTEND:20180528T200500Z
UID:p4S7CLJezbpO9CHBIKq7_WF9@stanza.co
SUMMARY:Dodgers @ Sounds
DESCRIPTION:Dodgers @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whM2-3v\n\nShop: https://stza.co/+whM2-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Sounds
<2018-05-29 Tue 18:35-21:35>
:PROPERTIES:
:ID:       7vjxZqhfkSPhy5DDHtUmRh15@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Sounds Dodgers @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whM3-30

Shop  https //stza.co/+whM3-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Sounds
END:VALARM
DTSTART:20180529T233500Z
DTEND:20180530T023500Z
UID:7vjxZqhfkSPhy5DDHtUmRh15@stanza.co
SUMMARY:Dodgers @ Sounds
DESCRIPTION:Dodgers @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whM3-30\n\nShop: https://stza.co/+whM3-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Storm Chasers
<2018-05-30 Wed 19:05-22:05>
:PROPERTIES:
:ID:       VQMUnT09rgujFGynxBHgiyUA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Storm Chasers Dodgers vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+v$NC-G

Shop  https //stza.co/+v$NC-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Storm Chasers
END:VALARM
DTSTART:20180531T000500Z
DTEND:20180531T030500Z
UID:VQMUnT09rgujFGynxBHgiyUA@stanza.co
SUMMARY:Dodgers vs. Storm Chasers
DESCRIPTION:Dodgers vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+v$NC-G\n\nShop: https://stza.co/+v$NC-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Storm Chasers
<2018-05-31 Thu 19:05-22:05>
:PROPERTIES:
:ID:       4EDJGtz1N3vrpwHWfxu2jkbK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Storm Chasers Dodgers vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+v$ND-9

Shop  https //stza.co/+v$ND-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Storm Chasers
END:VALARM
DTSTART:20180601T000500Z
DTEND:20180601T030500Z
UID:4EDJGtz1N3vrpwHWfxu2jkbK@stanza.co
SUMMARY:Dodgers vs. Storm Chasers
DESCRIPTION:Dodgers vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+v$ND-9\n\nShop: https://stza.co/+v$ND-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Storm Chasers
<2018-06-01 Fri 19:05-22:05>
:PROPERTIES:
:ID:       ksUzH2TCrZIyhIRJFtP_baSX@stanza.co
:LOCATION: Celebrate the start of the weekend with our Friday Night Fireworks after the game!
:STATUS:   CONFIRMED
:END:

Dodgers vs. Storm Chasers 



Follow on MiLB First Pitch  https //stza.co/+v$NF-1H

Shop  https //stza.co/+v$NF-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Storm Chasers
END:VALARM
DTSTART:20180602T000500Z
DTEND:20180602T030500Z
UID:ksUzH2TCrZIyhIRJFtP_baSX@stanza.co
SUMMARY:Dodgers vs. Storm Chasers
DESCRIPTION:\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+v$NF-1H\n\nShop: https://stza.co/+v$NF-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Celebrate the start of the weekend with our Friday Night Fireworks after the game!
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Storm Chasers
<2018-06-02 Sat 19:05-22:05>
:PROPERTIES:
:ID:       VyidE8ToHlKjktHIkC5feg1z@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Storm Chasers Dodgers vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+v$NH-2

Shop  https //stza.co/+v$NH-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Storm Chasers
END:VALARM
DTSTART:20180603T000500Z
DTEND:20180603T030500Z
UID:VyidE8ToHlKjktHIkC5feg1z@stanza.co
SUMMARY:Dodgers vs. Storm Chasers
DESCRIPTION:Dodgers vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+v$NH-2\n\nShop: https://stza.co/+v$NH-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Storm Chasers
<2018-06-03 Sun 14:05-17:05>
:PROPERTIES:
:ID:       hKTAbLgshdNu14jix1lhPcfW@stanza.co
:LOCATION: Chaparral Energy Family Sundays
:STATUS:   CONFIRMED
:END:

Dodgers vs. Storm Chasers 



Follow on MiLB First Pitch  https //stza.co/+v$NJ-29

Shop  https //stza.co/+v$NJ-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Storm Chasers
END:VALARM
DTSTART:20180603T190500Z
DTEND:20180603T220500Z
UID:hKTAbLgshdNu14jix1lhPcfW@stanza.co
SUMMARY:Dodgers vs. Storm Chasers
DESCRIPTION:\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+v$NJ-29\n\nShop: https://stza.co/+v$NJ-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Chaparral Energy Family Sundays
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ River Cats
<2018-06-05 Tue 21:05>--<2018-06-06 Wed 00:05>
:PROPERTIES:
:ID:       TcYesQIz6ifYzl5y5lO7Qqi5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ River Cats Dodgers @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjDu-1p

Shop  https //stza.co/+wjDu-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ River Cats
END:VALARM
DTSTART:20180606T020500Z
DTEND:20180606T050500Z
UID:TcYesQIz6ifYzl5y5lO7Qqi5@stanza.co
SUMMARY:Dodgers @ River Cats
DESCRIPTION:Dodgers @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjDu-1p\n\nShop: https://stza.co/+wjDu-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ River Cats
<2018-06-06 Wed 21:05>--<2018-06-07 Thu 00:05>
:PROPERTIES:
:ID:       gbTlcK-p3dUl7wWPHq1pUZIa@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers @ River Cats Dodgers @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjDv-2h

Shop  https //stza.co/+wjDv-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ River Cats
END:VALARM
DTSTART:20180607T020500Z
DTEND:20180607T050500Z
UID:gbTlcK-p3dUl7wWPHq1pUZIa@stanza.co
SUMMARY:Dodgers @ River Cats
DESCRIPTION:Dodgers @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjDv-2h\n\nShop: https://stza.co/+wjDv-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ River Cats
<2018-06-07 Thu 21:05>--<2018-06-08 Fri 00:05>
:PROPERTIES:
:ID:       DiKMGtlGvQx2scp1jnxKSD2_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ River Cats Dodgers @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjDw-E

Shop  https //stza.co/+wjDw-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ River Cats
END:VALARM
DTSTART:20180608T020500Z
DTEND:20180608T050500Z
UID:DiKMGtlGvQx2scp1jnxKSD2_@stanza.co
SUMMARY:Dodgers @ River Cats
DESCRIPTION:Dodgers @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjDw-E\n\nShop: https://stza.co/+wjDw-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Grizzlies
<2018-06-08 Fri 21:05>--<2018-06-09 Sat 00:05>
:PROPERTIES:
:ID:       6wLLUBj--4vQn-sm3OMr-Bvc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Grizzlies Dodgers @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjDk-1O

Shop  https //stza.co/+wjDk-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Grizzlies
END:VALARM
DTSTART:20180609T020500Z
DTEND:20180609T050500Z
UID:6wLLUBj--4vQn-sm3OMr-Bvc@stanza.co
SUMMARY:Dodgers @ Grizzlies
DESCRIPTION:Dodgers @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjDk-1O\n\nShop: https://stza.co/+wjDk-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Grizzlies
<2018-06-09 Sat 21:05>--<2018-06-10 Sun 00:05>
:PROPERTIES:
:ID:       8u_-16N1obbpvnj0bNFoK5Iy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers @ Grizzlies Dodgers @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjDl-1v

Shop  https //stza.co/+wjDl-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Grizzlies
END:VALARM
DTSTART:20180610T020500Z
DTEND:20180610T050500Z
UID:8u_-16N1obbpvnj0bNFoK5Iy@stanza.co
SUMMARY:Dodgers @ Grizzlies
DESCRIPTION:Dodgers @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjDl-1v\n\nShop: https://stza.co/+wjDl-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Grizzlies
<2018-06-10 Sun 19:05-22:05>
:PROPERTIES:
:ID:       gga7G_Uekm7swmVWBRjaX8Z0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Grizzlies Dodgers @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjDm-26

Shop  https //stza.co/+wjDm-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Grizzlies
END:VALARM
DTSTART:20180611T000500Z
DTEND:20180611T030500Z
UID:gga7G_Uekm7swmVWBRjaX8Z0@stanza.co
SUMMARY:Dodgers @ Grizzlies
DESCRIPTION:Dodgers @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjDm-26\n\nShop: https://stza.co/+wjDm-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Grizzlies
<2018-06-11 Mon 21:05>--<2018-06-12 Tue 00:05>
:PROPERTIES:
:ID:       QeuTVF1ufqLfQAjyxT-IdaCG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Grizzlies Dodgers @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjDn-p

Shop  https //stza.co/+wjDn-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Grizzlies
END:VALARM
DTSTART:20180612T020500Z
DTEND:20180612T050500Z
UID:QeuTVF1ufqLfQAjyxT-IdaCG@stanza.co
SUMMARY:Dodgers @ Grizzlies
DESCRIPTION:Dodgers @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjDn-p\n\nShop: https://stza.co/+wjDn-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Bees
<2018-06-13 Wed 19:05-22:05>
:PROPERTIES:
:ID:       c_mlgASI8EU3cMeiVWoxOIYo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Bees Dodgers vs. Bees

Follow on MiLB First Pitch  https //stza.co/+v$NM-30

Shop  https //stza.co/+v$NM-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Bees
END:VALARM
DTSTART:20180614T000500Z
DTEND:20180614T030500Z
UID:c_mlgASI8EU3cMeiVWoxOIYo@stanza.co
SUMMARY:Dodgers vs. Bees
DESCRIPTION:Dodgers vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+v$NM-30\n\nShop: https://stza.co/+v$NM-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Bees
<2018-06-14 Thu 19:05-22:05>
:PROPERTIES:
:ID:       grA8m6j71Z8p3SFkhQv8Yz5s@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Bees Dodgers vs. Bees

Follow on MiLB First Pitch  https //stza.co/+v$NN-1r

Shop  https //stza.co/+v$NN-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Bees
END:VALARM
DTSTART:20180615T000500Z
DTEND:20180615T030500Z
UID:grA8m6j71Z8p3SFkhQv8Yz5s@stanza.co
SUMMARY:Dodgers vs. Bees
DESCRIPTION:Dodgers vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+v$NN-1r\n\nShop: https://stza.co/+v$NN-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Bees
<2018-06-15 Fri 19:05-22:05>
:PROPERTIES:
:ID:       OmVNgSZfB8sDV7yEYYg3tbVj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Bees Dodgers vs. Bees

Follow on MiLB First Pitch  https //stza.co/+v$NQ-1g

Shop  https //stza.co/+v$NQ-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Bees
END:VALARM
DTSTART:20180616T000500Z
DTEND:20180616T030500Z
UID:OmVNgSZfB8sDV7yEYYg3tbVj@stanza.co
SUMMARY:Dodgers vs. Bees
DESCRIPTION:Dodgers vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+v$NQ-1g\n\nShop: https://stza.co/+v$NQ-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. 51s
<2018-06-16 Sat 19:05-22:05>
:PROPERTIES:
:ID:       XXeunHzGujr8fsUYFByEhqGh@stanza.co
:LOCATION: INTEGRIS Home Run for Life
:STATUS:   CONFIRMED
:END:

Dodgers vs. 51s 



Follow on MiLB First Pitch  https //stza.co/+v$NR-u

Shop  https //stza.co/+v$NR-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. 51s
END:VALARM
DTSTART:20180617T000500Z
DTEND:20180617T030500Z
UID:XXeunHzGujr8fsUYFByEhqGh@stanza.co
SUMMARY:Dodgers vs. 51s
DESCRIPTION:\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+v$NR-u\n\nShop: https://stza.co/+v$NR-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:INTEGRIS Home Run for Life
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. 51s
<2018-06-17 Sun 18:05-21:05>
:PROPERTIES:
:ID:       QvVdQH3Hjajhtigi7rMTp9_C@stanza.co
:LOCATION: Chaparral Energy Family Sundays
:STATUS:   CONFIRMED
:END:

Dodgers vs. 51s 



Follow on MiLB First Pitch  https //stza.co/+v$NU-2Z

Shop  https //stza.co/+v$NU-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. 51s
END:VALARM
DTSTART:20180617T230500Z
DTEND:20180618T020500Z
UID:QvVdQH3Hjajhtigi7rMTp9_C@stanza.co
SUMMARY:Dodgers vs. 51s
DESCRIPTION:\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+v$NU-2Z\n\nShop: https://stza.co/+v$NU-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Chaparral Energy Family Sundays
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. 51s
<2018-06-18 Mon 19:05-22:05>
:PROPERTIES:
:ID:       caincsrZDXrU5xHQgkDU7Yp5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers vs. 51s Dodgers vs. 51s

Follow on MiLB First Pitch  https //stza.co/+v$NW-16

Shop  https //stza.co/+v$NW-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. 51s
END:VALARM
DTSTART:20180619T000500Z
DTEND:20180619T030500Z
UID:caincsrZDXrU5xHQgkDU7Yp5@stanza.co
SUMMARY:Dodgers vs. 51s
DESCRIPTION:Dodgers vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+v$NW-16\n\nShop: https://stza.co/+v$NW-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. 51s
<2018-06-19 Tue 11:05-14:05>
:PROPERTIES:
:ID:       vCWCO3vszXSmJGi5fqJ6GxRb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers vs. 51s Dodgers vs. 51s

Follow on MiLB First Pitch  https //stza.co/+v$NY-1u

Shop  https //stza.co/+v$NY-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. 51s
END:VALARM
DTSTART:20180619T160500Z
DTEND:20180619T190500Z
UID:vCWCO3vszXSmJGi5fqJ6GxRb@stanza.co
SUMMARY:Dodgers vs. 51s
DESCRIPTION:Dodgers vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+v$NY-1u\n\nShop: https://stza.co/+v$NY-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Storm Chasers
<2018-06-21 Thu 19:05-22:05>
:PROPERTIES:
:ID:       Lhx_DNwECAtEtLjxC7-Hkua4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Storm Chasers Dodgers @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whMh-2F

Shop  https //stza.co/+whMh-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Storm Chasers
END:VALARM
DTSTART:20180622T000500Z
DTEND:20180622T030500Z
UID:Lhx_DNwECAtEtLjxC7-Hkua4@stanza.co
SUMMARY:Dodgers @ Storm Chasers
DESCRIPTION:Dodgers @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whMh-2F\n\nShop: https://stza.co/+whMh-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Storm Chasers
<2018-06-22 Fri 19:05-22:05>
:PROPERTIES:
:ID:       gffY9e4GgKjAoF6QBoYvmzXK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers @ Storm Chasers Dodgers @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whMi-1n

Shop  https //stza.co/+whMi-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Storm Chasers
END:VALARM
DTSTART:20180623T000500Z
DTEND:20180623T030500Z
UID:gffY9e4GgKjAoF6QBoYvmzXK@stanza.co
SUMMARY:Dodgers @ Storm Chasers
DESCRIPTION:Dodgers @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whMi-1n\n\nShop: https://stza.co/+whMi-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Storm Chasers
<2018-06-23 Sat 19:05-22:05>
:PROPERTIES:
:ID:       irtbEYOIAG5IK_ZWXb6eijCd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Storm Chasers Dodgers @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whMj-1r

Shop  https //stza.co/+whMj-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Storm Chasers
END:VALARM
DTSTART:20180624T000500Z
DTEND:20180624T030500Z
UID:irtbEYOIAG5IK_ZWXb6eijCd@stanza.co
SUMMARY:Dodgers @ Storm Chasers
DESCRIPTION:Dodgers @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whMj-1r\n\nShop: https://stza.co/+whMj-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Storm Chasers
<2018-06-24 Sun 14:05-17:05>
:PROPERTIES:
:ID:       QG8dOj-kXmRJcsAFfS92qKGj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Storm Chasers Dodgers @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whMk-1U

Shop  https //stza.co/+whMk-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Storm Chasers
END:VALARM
DTSTART:20180624T190500Z
DTEND:20180624T220500Z
UID:QG8dOj-kXmRJcsAFfS92qKGj@stanza.co
SUMMARY:Dodgers @ Storm Chasers
DESCRIPTION:Dodgers @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whMk-1U\n\nShop: https://stza.co/+whMk-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Sounds
<2018-06-25 Mon 19:05-22:05>
:PROPERTIES:
:ID:       eyPXuM-7dbKoIciE70mf4714@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Sounds Dodgers vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+v$N_-35

Shop  https //stza.co/+v$N_-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Sounds
END:VALARM
DTSTART:20180626T000500Z
DTEND:20180626T030500Z
UID:eyPXuM-7dbKoIciE70mf4714@stanza.co
SUMMARY:Dodgers vs. Sounds
DESCRIPTION:Dodgers vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+v$N_-35\n\nShop: https://stza.co/+v$N_-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Sounds
<2018-06-26 Tue 19:05-22:05>
:PROPERTIES:
:ID:       Q-ujVqvkPi5l-yUNJsHz25eq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Sounds Dodgers vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+v$N$-U

Shop  https //stza.co/+v$N$-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Sounds
END:VALARM
DTSTART:20180627T000500Z
DTEND:20180627T030500Z
UID:Q-ujVqvkPi5l-yUNJsHz25eq@stanza.co
SUMMARY:Dodgers vs. Sounds
DESCRIPTION:Dodgers vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+v$N$-U\n\nShop: https://stza.co/+v$N$-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Sounds
<2018-06-27 Wed 19:05-22:05>
:PROPERTIES:
:ID:       zz-lUnkNmmYiD5m6TA8ciP3H@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Sounds Dodgers vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+v$O2-1z

Shop  https //stza.co/+v$O2-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Sounds
END:VALARM
DTSTART:20180628T000500Z
DTEND:20180628T030500Z
UID:zz-lUnkNmmYiD5m6TA8ciP3H@stanza.co
SUMMARY:Dodgers vs. Sounds
DESCRIPTION:Dodgers vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+v$O2-1z\n\nShop: https://stza.co/+v$O2-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Sounds
<2018-06-28 Thu 19:05-22:05>
:PROPERTIES:
:ID:       P8ed9ILWbSmnbg9Ie9EU9p_V@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Sounds Dodgers vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+v$O4-i

Shop  https //stza.co/+v$O4-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Sounds
END:VALARM
DTSTART:20180629T000500Z
DTEND:20180629T030500Z
UID:P8ed9ILWbSmnbg9Ie9EU9p_V@stanza.co
SUMMARY:Dodgers vs. Sounds
DESCRIPTION:Dodgers vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+v$O4-i\n\nShop: https://stza.co/+v$O4-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Baby Cakes
<2018-06-29 Fri 19:00-22:00>
:PROPERTIES:
:ID:       TEfEVHwMUbTy-jzX24rfbezJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Baby Cakes Dodgers @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whMb-l

Shop  https //stza.co/+whMb-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Baby Cakes
END:VALARM
DTSTART:20180630T000000Z
DTEND:20180630T030000Z
UID:TEfEVHwMUbTy-jzX24rfbezJ@stanza.co
SUMMARY:Dodgers @ Baby Cakes
DESCRIPTION:Dodgers @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whMb-l\n\nShop: https://stza.co/+whMb-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Baby Cakes
<2018-06-30 Sat 18:00-21:00>
:PROPERTIES:
:ID:       ugO4UiwaRTyThJtGuZn77swP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Baby Cakes Dodgers @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whMc-2c

Shop  https //stza.co/+whMc-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Baby Cakes
END:VALARM
DTSTART:20180630T230000Z
DTEND:20180701T020000Z
UID:ugO4UiwaRTyThJtGuZn77swP@stanza.co
SUMMARY:Dodgers @ Baby Cakes
DESCRIPTION:Dodgers @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whMc-2c\n\nShop: https://stza.co/+whMc-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Baby Cakes
<2018-07-01 Sun 13:00-16:00>
:PROPERTIES:
:ID:       G74VuMPXJc6sOgt5vPT9j31X@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers @ Baby Cakes Dodgers @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whMd-11

Shop  https //stza.co/+whMd-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Baby Cakes
END:VALARM
DTSTART:20180701T180000Z
DTEND:20180701T210000Z
UID:G74VuMPXJc6sOgt5vPT9j31X@stanza.co
SUMMARY:Dodgers @ Baby Cakes
DESCRIPTION:Dodgers @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whMd-11\n\nShop: https://stza.co/+whMd-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Baby Cakes
<2018-07-02 Mon 19:00-22:00>
:PROPERTIES:
:ID:       0y5bOezU_YkXUtsh70NTI0gJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Baby Cakes Dodgers @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whMe-2w

Shop  https //stza.co/+whMe-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Baby Cakes
END:VALARM
DTSTART:20180703T000000Z
DTEND:20180703T030000Z
UID:0y5bOezU_YkXUtsh70NTI0gJ@stanza.co
SUMMARY:Dodgers @ Baby Cakes
DESCRIPTION:Dodgers @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whMe-2w\n\nShop: https://stza.co/+whMe-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Baby Cakes
<2018-07-03 Tue 19:00-22:00>
:PROPERTIES:
:ID:       o-jJRHYAXn7u-Gg9DAoDZQtQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Baby Cakes Dodgers @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whMg-3u

Shop  https //stza.co/+whMg-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Baby Cakes
END:VALARM
DTSTART:20180704T000000Z
DTEND:20180704T030000Z
UID:o-jJRHYAXn7u-Gg9DAoDZQtQ@stanza.co
SUMMARY:Dodgers @ Baby Cakes
DESCRIPTION:Dodgers @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whMg-3u\n\nShop: https://stza.co/+whMg-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Express
<2018-07-04 Wed 19:05-22:05>
:PROPERTIES:
:ID:       O3m3b6sWE8ejqv3e79SWjk9Q@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Express Dodgers vs. Express

Follow on MiLB First Pitch  https //stza.co/+v$O5-10

Shop  https //stza.co/+v$O5-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Express
END:VALARM
DTSTART:20180705T000500Z
DTEND:20180705T030500Z
UID:O3m3b6sWE8ejqv3e79SWjk9Q@stanza.co
SUMMARY:Dodgers vs. Express
DESCRIPTION:Dodgers vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+v$O5-10\n\nShop: https://stza.co/+v$O5-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Express
<2018-07-05 Thu 19:05-22:05>
:PROPERTIES:
:ID:       YDcxRNm9_YFDWHJSm4w4nVi_@stanza.co
:LOCATION: $2 Thursdays
:STATUS:   CONFIRMED
:END:

Dodgers vs. Express 



Follow on MiLB First Pitch  https //stza.co/+v$O8-1i

Shop  https //stza.co/+v$O8-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Express
END:VALARM
DTSTART:20180706T000500Z
DTEND:20180706T030500Z
UID:YDcxRNm9_YFDWHJSm4w4nVi_@stanza.co
SUMMARY:Dodgers vs. Express
DESCRIPTION:\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+v$O8-1i\n\nShop: https://stza.co/+v$O8-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:$2 Thursdays
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Express
<2018-07-06 Fri 19:05-22:05>
:PROPERTIES:
:ID:       skFhtXv8pOK1e2CwtCHc_Xbl@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Express Dodgers vs. Express

Follow on MiLB First Pitch  https //stza.co/+v$Oa-3r

Shop  https //stza.co/+v$Oa-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Express
END:VALARM
DTSTART:20180707T000500Z
DTEND:20180707T030500Z
UID:skFhtXv8pOK1e2CwtCHc_Xbl@stanza.co
SUMMARY:Dodgers vs. Express
DESCRIPTION:Dodgers vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+v$Oa-3r\n\nShop: https://stza.co/+v$Oa-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Express
<2018-07-07 Sat 19:05-22:05>
:PROPERTIES:
:ID:       KIrk205hZdu05ks6K0yDibHl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Express Dodgers vs. Express

Follow on MiLB First Pitch  https //stza.co/+v$Ob-2M

Shop  https //stza.co/+v$Ob-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Express
END:VALARM
DTSTART:20180708T000500Z
DTEND:20180708T030500Z
UID:KIrk205hZdu05ks6K0yDibHl@stanza.co
SUMMARY:Dodgers vs. Express
DESCRIPTION:Dodgers vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+v$Ob-2M\n\nShop: https://stza.co/+v$Ob-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Express
<2018-07-08 Sun 13:05-16:05>
:PROPERTIES:
:ID:       1uiIraghTivoJoB8cEbpiHDo@stanza.co
:LOCATION: Chaparral Energy Family Sundays
:STATUS:   CONFIRMED
:END:

Dodgers vs. Express 



Follow on MiLB First Pitch  https //stza.co/+v$Od-2f

Shop  https //stza.co/+v$Od-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Express
END:VALARM
DTSTART:20180708T180500Z
DTEND:20180708T210500Z
UID:1uiIraghTivoJoB8cEbpiHDo@stanza.co
SUMMARY:Dodgers vs. Express
DESCRIPTION:\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+v$Od-2f\n\nShop: https://stza.co/+v$Od-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Chaparral Energy Family Sundays
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Express
<2018-07-12 Thu 19:05-22:05>
:PROPERTIES:
:ID:       0f2tnur9HA35iGhioVKlCe46@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers @ Express Dodgers @ Express

Follow on MiLB First Pitch  https //stza.co/+v3dR-3R

Shop  https //stza.co/+v3dR-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Express
END:VALARM
DTSTART:20180713T000500Z
DTEND:20180713T030500Z
UID:0f2tnur9HA35iGhioVKlCe46@stanza.co
SUMMARY:Dodgers @ Express
DESCRIPTION:Dodgers @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+v3dR-3R\n\nShop: https://stza.co/+v3dR-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Express
<2018-07-13 Fri 19:05-22:05>
:PROPERTIES:
:ID:       DNX_dWaN05PqKTY_jR4vxnH9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Express Dodgers @ Express

Follow on MiLB First Pitch  https //stza.co/+v3dS-11

Shop  https //stza.co/+v3dS-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Express
END:VALARM
DTSTART:20180714T000500Z
DTEND:20180714T030500Z
UID:DNX_dWaN05PqKTY_jR4vxnH9@stanza.co
SUMMARY:Dodgers @ Express
DESCRIPTION:Dodgers @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+v3dS-11\n\nShop: https://stza.co/+v3dS-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Express
<2018-07-14 Sat 18:05-21:05>
:PROPERTIES:
:ID:       k9wxF5b71bclwOuiTBisCYJi@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Express Dodgers @ Express

Follow on MiLB First Pitch  https //stza.co/+v3dT-1p

Shop  https //stza.co/+v3dT-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Express
END:VALARM
DTSTART:20180714T230500Z
DTEND:20180715T020500Z
UID:k9wxF5b71bclwOuiTBisCYJi@stanza.co
SUMMARY:Dodgers @ Express
DESCRIPTION:Dodgers @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+v3dT-1p\n\nShop: https://stza.co/+v3dT-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Express
<2018-07-15 Sun 18:05-21:05>
:PROPERTIES:
:ID:       fs69G6RksrGYOm3QdF9P55Cn@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers @ Express Dodgers @ Express

Follow on MiLB First Pitch  https //stza.co/+v3dU-2n

Shop  https //stza.co/+v3dU-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Express
END:VALARM
DTSTART:20180715T230500Z
DTEND:20180716T020500Z
UID:fs69G6RksrGYOm3QdF9P55Cn@stanza.co
SUMMARY:Dodgers @ Express
DESCRIPTION:Dodgers @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+v3dU-2n\n\nShop: https://stza.co/+v3dU-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Baby Cakes
<2018-07-16 Mon 19:05-22:05>
:PROPERTIES:
:ID:       JwhmBru-Su2driISm_97rcUS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Baby Cakes Dodgers vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+v$Og-Y

Shop  https //stza.co/+v$Og-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Baby Cakes
END:VALARM
DTSTART:20180717T000500Z
DTEND:20180717T030500Z
UID:JwhmBru-Su2driISm_97rcUS@stanza.co
SUMMARY:Dodgers vs. Baby Cakes
DESCRIPTION:Dodgers vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+v$Og-Y\n\nShop: https://stza.co/+v$Og-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Baby Cakes
<2018-07-17 Tue 19:05-22:05>
:PROPERTIES:
:ID:       ebmlNHM-_PA6BAFrUf1VG1Rq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Baby Cakes Dodgers vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+v$Oi-2I

Shop  https //stza.co/+v$Oi-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Baby Cakes
END:VALARM
DTSTART:20180718T000500Z
DTEND:20180718T030500Z
UID:ebmlNHM-_PA6BAFrUf1VG1Rq@stanza.co
SUMMARY:Dodgers vs. Baby Cakes
DESCRIPTION:Dodgers vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+v$Oi-2I\n\nShop: https://stza.co/+v$Oi-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Baby Cakes
<2018-07-18 Wed 19:05-22:05>
:PROPERTIES:
:ID:       y3nGD1geqJ9Z2gPGAkSUdhNT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Baby Cakes Dodgers vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+v$Ok-2r

Shop  https //stza.co/+v$Ok-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Baby Cakes
END:VALARM
DTSTART:20180719T000500Z
DTEND:20180719T030500Z
UID:y3nGD1geqJ9Z2gPGAkSUdhNT@stanza.co
SUMMARY:Dodgers vs. Baby Cakes
DESCRIPTION:Dodgers vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+v$Ok-2r\n\nShop: https://stza.co/+v$Ok-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Baby Cakes
<2018-07-19 Thu 19:05-22:05>
:PROPERTIES:
:ID:       u0A7FlN_xbeaXC-MolqdEory@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Baby Cakes Dodgers vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+v$Om-2W

Shop  https //stza.co/+v$Om-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Baby Cakes
END:VALARM
DTSTART:20180720T000500Z
DTEND:20180720T030500Z
UID:u0A7FlN_xbeaXC-MolqdEory@stanza.co
SUMMARY:Dodgers vs. Baby Cakes
DESCRIPTION:Dodgers vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+v$Om-2W\n\nShop: https://stza.co/+v$Om-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Sounds
<2018-07-20 Fri 19:05-22:05>
:PROPERTIES:
:ID:       2EuI-lnjz_zrQa9SmEuESE_n@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Sounds Dodgers @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whM4-25

Shop  https //stza.co/+whM4-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Sounds
END:VALARM
DTSTART:20180721T000500Z
DTEND:20180721T030500Z
UID:2EuI-lnjz_zrQa9SmEuESE_n@stanza.co
SUMMARY:Dodgers @ Sounds
DESCRIPTION:Dodgers @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whM4-25\n\nShop: https://stza.co/+whM4-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Sounds
<2018-07-21 Sat 19:05-22:05>
:PROPERTIES:
:ID:       k6fx5ydr8_Ran3wUNhkkFra8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers @ Sounds Dodgers @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whM5-1M

Shop  https //stza.co/+whM5-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Sounds
END:VALARM
DTSTART:20180722T000500Z
DTEND:20180722T030500Z
UID:k6fx5ydr8_Ran3wUNhkkFra8@stanza.co
SUMMARY:Dodgers @ Sounds
DESCRIPTION:Dodgers @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whM5-1M\n\nShop: https://stza.co/+whM5-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Sounds
<2018-07-22 Sun 18:15-21:15>
:PROPERTIES:
:ID:       m1G5laOIgsn_eX_tTsSGkUoG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Sounds Dodgers @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whM6-2t

Shop  https //stza.co/+whM6-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Sounds
END:VALARM
DTSTART:20180722T231500Z
DTEND:20180723T021500Z
UID:m1G5laOIgsn_eX_tTsSGkUoG@stanza.co
SUMMARY:Dodgers @ Sounds
DESCRIPTION:Dodgers @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whM6-2t\n\nShop: https://stza.co/+whM6-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Isotopes
<2018-07-24 Tue 19:05-22:05>
:PROPERTIES:
:ID:       GHSesyYuEZB2cpu6rvKdddl2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Isotopes Dodgers vs. Isotopes

Follow on MiLB First Pitch  https //stza.co/+v$On-j

Shop  https //stza.co/+v$On-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Isotopes
END:VALARM
DTSTART:20180725T000500Z
DTEND:20180725T030500Z
UID:GHSesyYuEZB2cpu6rvKdddl2@stanza.co
SUMMARY:Dodgers vs. Isotopes
DESCRIPTION:Dodgers vs. Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+v$On-j\n\nShop: https://stza.co/+v$On-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Isotopes
<2018-07-25 Wed 19:05-22:05>
:PROPERTIES:
:ID:       TUHDjT6SRAkuHxAxBswekSJc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Isotopes Dodgers vs. Isotopes

Follow on MiLB First Pitch  https //stza.co/+v$Oq-2E

Shop  https //stza.co/+v$Oq-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Isotopes
END:VALARM
DTSTART:20180726T000500Z
DTEND:20180726T030500Z
UID:TUHDjT6SRAkuHxAxBswekSJc@stanza.co
SUMMARY:Dodgers vs. Isotopes
DESCRIPTION:Dodgers vs. Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+v$Oq-2E\n\nShop: https://stza.co/+v$Oq-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Isotopes
<2018-07-26 Thu 19:05-22:05>
:PROPERTIES:
:ID:       BxpV-lre7sta5k5_T-4u6NBN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Isotopes Dodgers vs. Isotopes

Follow on MiLB First Pitch  https //stza.co/+v$Os-2Y

Shop  https //stza.co/+v$Os-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Isotopes
END:VALARM
DTSTART:20180727T000500Z
DTEND:20180727T030500Z
UID:BxpV-lre7sta5k5_T-4u6NBN@stanza.co
SUMMARY:Dodgers vs. Isotopes
DESCRIPTION:Dodgers vs. Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+v$Os-2Y\n\nShop: https://stza.co/+v$Os-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Chihuahuas
<2018-07-27 Fri 19:05-22:05>
:PROPERTIES:
:ID:       LWquk7spYG9kU2dy2aoIkJH8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Chihuahuas Dodgers vs. Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+v$Ou-w

Shop  https //stza.co/+v$Ou-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Chihuahuas
END:VALARM
DTSTART:20180728T000500Z
DTEND:20180728T030500Z
UID:LWquk7spYG9kU2dy2aoIkJH8@stanza.co
SUMMARY:Dodgers vs. Chihuahuas
DESCRIPTION:Dodgers vs. Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+v$Ou-w\n\nShop: https://stza.co/+v$Ou-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Chihuahuas
<2018-07-28 Sat 19:05-22:05>
:PROPERTIES:
:ID:       oViD0OAuQ-aomk5IIfne9cbk@stanza.co
:LOCATION: INTEGRIS Home Run for Life
:STATUS:   CONFIRMED
:END:

Dodgers vs. Chihuahuas 



Follow on MiLB First Pitch  https //stza.co/+v$Ow-8

Shop  https //stza.co/+v$Ow-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Chihuahuas
END:VALARM
DTSTART:20180729T000500Z
DTEND:20180729T030500Z
UID:oViD0OAuQ-aomk5IIfne9cbk@stanza.co
SUMMARY:Dodgers vs. Chihuahuas
DESCRIPTION:\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+v$Ow-8\n\nShop: https://stza.co/+v$Ow-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:INTEGRIS Home Run for Life
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Chihuahuas
<2018-07-29 Sun 18:05-21:05>
:PROPERTIES:
:ID:       Dhh9MUYST8VWZlSod5HcPTev@stanza.co
:LOCATION: Chaparral Energy Family Sundays
:STATUS:   CONFIRMED
:END:

Dodgers vs. Chihuahuas 



Follow on MiLB First Pitch  https //stza.co/+v$Oy-1Y

Shop  https //stza.co/+v$Oy-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Chihuahuas
END:VALARM
DTSTART:20180729T230500Z
DTEND:20180730T020500Z
UID:Dhh9MUYST8VWZlSod5HcPTev@stanza.co
SUMMARY:Dodgers vs. Chihuahuas
DESCRIPTION:\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+v$Oy-1Y\n\nShop: https://stza.co/+v$Oy-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Chaparral Energy Family Sundays
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Chihuahuas
<2018-07-30 Mon 19:05-22:05>
:PROPERTIES:
:ID:       XYtqcOhvfuckDeNSrYVFwq8L@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Chihuahuas Dodgers vs. Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+v$OA-26

Shop  https //stza.co/+v$OA-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Chihuahuas
END:VALARM
DTSTART:20180731T000500Z
DTEND:20180731T030500Z
UID:XYtqcOhvfuckDeNSrYVFwq8L@stanza.co
SUMMARY:Dodgers vs. Chihuahuas
DESCRIPTION:Dodgers vs. Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+v$OA-26\n\nShop: https://stza.co/+v$OA-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Rainiers
<2018-08-01 Wed 21:05>--<2018-08-02 Thu 00:05>
:PROPERTIES:
:ID:       DweVl32zRastU97eb-J3BXnV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Rainiers Dodgers @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjDy-Y

Shop  https //stza.co/+wjDy-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Rainiers
END:VALARM
DTSTART:20180802T020500Z
DTEND:20180802T050500Z
UID:DweVl32zRastU97eb-J3BXnV@stanza.co
SUMMARY:Dodgers @ Rainiers
DESCRIPTION:Dodgers @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjDy-Y\n\nShop: https://stza.co/+wjDy-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Rainiers
<2018-08-02 Thu 21:05>--<2018-08-03 Fri 00:05>
:PROPERTIES:
:ID:       jfT0IYxRI4h-jPPrXf1W72Uv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Rainiers Dodgers @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjDz-19

Shop  https //stza.co/+wjDz-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Rainiers
END:VALARM
DTSTART:20180803T020500Z
DTEND:20180803T050500Z
UID:jfT0IYxRI4h-jPPrXf1W72Uv@stanza.co
SUMMARY:Dodgers @ Rainiers
DESCRIPTION:Dodgers @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjDz-19\n\nShop: https://stza.co/+wjDz-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Rainiers
<2018-08-03 Fri 21:05>--<2018-08-04 Sat 00:05>
:PROPERTIES:
:ID:       eXFiMEcsvylyEWgUxanTbJzR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers @ Rainiers Dodgers @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjDA-m

Shop  https //stza.co/+wjDA-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Rainiers
END:VALARM
DTSTART:20180804T020500Z
DTEND:20180804T050500Z
UID:eXFiMEcsvylyEWgUxanTbJzR@stanza.co
SUMMARY:Dodgers @ Rainiers
DESCRIPTION:Dodgers @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjDA-m\n\nShop: https://stza.co/+wjDA-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Aces
<2018-08-04 Sat 21:05>--<2018-08-05 Sun 00:05>
:PROPERTIES:
:ID:       0zrS1a2abcOaSlyWGPV3Jdqp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Aces Dodgers @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjDq-3P

Shop  https //stza.co/+wjDq-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Aces
END:VALARM
DTSTART:20180805T020500Z
DTEND:20180805T050500Z
UID:0zrS1a2abcOaSlyWGPV3Jdqp@stanza.co
SUMMARY:Dodgers @ Aces
DESCRIPTION:Dodgers @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjDq-3P\n\nShop: https://stza.co/+wjDq-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Aces
<2018-08-05 Sun 15:05-18:05>
:PROPERTIES:
:ID:       OHiNLG4IvzIoUdNLHnVWduaQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Aces Dodgers @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjDr-2f

Shop  https //stza.co/+wjDr-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Aces
END:VALARM
DTSTART:20180805T200500Z
DTEND:20180805T230500Z
UID:OHiNLG4IvzIoUdNLHnVWduaQ@stanza.co
SUMMARY:Dodgers @ Aces
DESCRIPTION:Dodgers @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjDr-2f\n\nShop: https://stza.co/+wjDr-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Aces
<2018-08-06 Mon 21:05>--<2018-08-07 Tue 00:05>
:PROPERTIES:
:ID:       beGjMyqHBcya0EYRiDgr8dSD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers @ Aces Dodgers @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjDs-3v

Shop  https //stza.co/+wjDs-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Aces
END:VALARM
DTSTART:20180807T020500Z
DTEND:20180807T050500Z
UID:beGjMyqHBcya0EYRiDgr8dSD@stanza.co
SUMMARY:Dodgers @ Aces
DESCRIPTION:Dodgers @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjDs-3v\n\nShop: https://stza.co/+wjDs-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Aces
<2018-08-07 Tue 21:05>--<2018-08-08 Wed 00:05>
:PROPERTIES:
:ID:       eHdmKSAjvu7i2Pc2Dx6UwchX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Aces Dodgers @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjDt-2H

Shop  https //stza.co/+wjDt-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Aces
END:VALARM
DTSTART:20180808T020500Z
DTEND:20180808T050500Z
UID:eHdmKSAjvu7i2Pc2Dx6UwchX@stanza.co
SUMMARY:Dodgers @ Aces
DESCRIPTION:Dodgers @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjDt-2H\n\nShop: https://stza.co/+wjDt-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Redbirds
<2018-08-09 Thu 19:05-22:05>
:PROPERTIES:
:ID:       xnGGnf4vjMwlvQKwaeSU1w5Y@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Redbirds Dodgers vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+v$OB-2M

Shop  https //stza.co/+v$OB-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Redbirds
END:VALARM
DTSTART:20180810T000500Z
DTEND:20180810T030500Z
UID:xnGGnf4vjMwlvQKwaeSU1w5Y@stanza.co
SUMMARY:Dodgers vs. Redbirds
DESCRIPTION:Dodgers vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+v$OB-2M\n\nShop: https://stza.co/+v$OB-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Redbirds
<2018-08-10 Fri 19:05-22:05>
:PROPERTIES:
:ID:       4TWwTykkP6vWJ0uN_mGGDEV0@stanza.co
:LOCATION: Celebrate the start of the weekend with our Friday Night Fireworks after the game!
:STATUS:   CONFIRMED
:END:

Dodgers vs. Redbirds 



Follow on MiLB First Pitch  https //stza.co/+v$OE-5

Shop  https //stza.co/+v$OE-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Redbirds
END:VALARM
DTSTART:20180811T000500Z
DTEND:20180811T030500Z
UID:4TWwTykkP6vWJ0uN_mGGDEV0@stanza.co
SUMMARY:Dodgers vs. Redbirds
DESCRIPTION:\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+v$OE-5\n\nShop: https://stza.co/+v$OE-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Celebrate the start of the weekend with our Friday Night Fireworks after the game!
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Redbirds
<2018-08-11 Sat 19:05-22:05>
:PROPERTIES:
:ID:       PrXoOYkyyLqIW7MPiMYAXKeQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Redbirds Dodgers vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+v$OF-1T

Shop  https //stza.co/+v$OF-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Redbirds
END:VALARM
DTSTART:20180812T000500Z
DTEND:20180812T030500Z
UID:PrXoOYkyyLqIW7MPiMYAXKeQ@stanza.co
SUMMARY:Dodgers vs. Redbirds
DESCRIPTION:Dodgers vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+v$OF-1T\n\nShop: https://stza.co/+v$OF-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Redbirds
<2018-08-12 Sun 18:05-21:05>
:PROPERTIES:
:ID:       mUM23xeSa96s-G7w3y84skou@stanza.co
:LOCATION: Chaparral Energy Family Sundays
:STATUS:   CONFIRMED
:END:

Dodgers vs. Redbirds 



Follow on MiLB First Pitch  https //stza.co/+v$OI-w

Shop  https //stza.co/+v$OI-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Redbirds
END:VALARM
DTSTART:20180812T230500Z
DTEND:20180813T020500Z
UID:mUM23xeSa96s-G7w3y84skou@stanza.co
SUMMARY:Dodgers vs. Redbirds
DESCRIPTION:\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+v$OI-w\n\nShop: https://stza.co/+v$OI-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Chaparral Energy Family Sundays
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Storm Chasers
<2018-08-13 Mon 19:05-22:05>
:PROPERTIES:
:ID:       o32Kmr3NPpGGVdjHWWJmcF1m@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Storm Chasers Dodgers @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whMl-5

Shop  https //stza.co/+whMl-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Storm Chasers
END:VALARM
DTSTART:20180814T000500Z
DTEND:20180814T030500Z
UID:o32Kmr3NPpGGVdjHWWJmcF1m@stanza.co
SUMMARY:Dodgers @ Storm Chasers
DESCRIPTION:Dodgers @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whMl-5\n\nShop: https://stza.co/+whMl-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Storm Chasers
<2018-08-14 Tue 19:05-22:05>
:PROPERTIES:
:ID:       4Tk-Gw9OtD37bP5a7h0cvu8M@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Storm Chasers Dodgers @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whMm-2k

Shop  https //stza.co/+whMm-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Storm Chasers
END:VALARM
DTSTART:20180815T000500Z
DTEND:20180815T030500Z
UID:4Tk-Gw9OtD37bP5a7h0cvu8M@stanza.co
SUMMARY:Dodgers @ Storm Chasers
DESCRIPTION:Dodgers @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whMm-2k\n\nShop: https://stza.co/+whMm-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Storm Chasers
<2018-08-15 Wed 19:05-22:05>
:PROPERTIES:
:ID:       p7swMkievzAQANyPp7LlMShE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers @ Storm Chasers Dodgers @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whMn-1N

Shop  https //stza.co/+whMn-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Storm Chasers
END:VALARM
DTSTART:20180816T000500Z
DTEND:20180816T030500Z
UID:p7swMkievzAQANyPp7LlMShE@stanza.co
SUMMARY:Dodgers @ Storm Chasers
DESCRIPTION:Dodgers @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whMn-1N\n\nShop: https://stza.co/+whMn-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Storm Chasers
<2018-08-16 Thu 19:05-22:05>
:PROPERTIES:
:ID:       E9dbeX46rQRYgZd89QGzwsDI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Storm Chasers Dodgers @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whMo-1$

Shop  https //stza.co/+whMo-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Storm Chasers
END:VALARM
DTSTART:20180817T000500Z
DTEND:20180817T030500Z
UID:E9dbeX46rQRYgZd89QGzwsDI@stanza.co
SUMMARY:Dodgers @ Storm Chasers
DESCRIPTION:Dodgers @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whMo-1$\n\nShop: https://stza.co/+whMo-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Cubs
<2018-08-17 Fri 19:05-22:05>
:PROPERTIES:
:ID:       0_cf0I-7mTFjPl2jxYEqmbEY@stanza.co
:LOCATION: Celebrate the start of the weekend with our Friday Night Fireworks after the game!
:STATUS:   CONFIRMED
:END:

Dodgers vs. Cubs 



Follow on MiLB First Pitch  https //stza.co/+v$OJ-3q

Shop  https //stza.co/+v$OJ-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Cubs
END:VALARM
DTSTART:20180818T000500Z
DTEND:20180818T030500Z
UID:0_cf0I-7mTFjPl2jxYEqmbEY@stanza.co
SUMMARY:Dodgers vs. Cubs
DESCRIPTION:\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+v$OJ-3q\n\nShop: https://stza.co/+v$OJ-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Celebrate the start of the weekend with our Friday Night Fireworks after the game!
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Cubs
<2018-08-18 Sat 19:05-22:05>
:PROPERTIES:
:ID:       s6VOlpPLr2VAEvxII1xNRKcZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Cubs Dodgers vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+v$OM-j

Shop  https //stza.co/+v$OM-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Cubs
END:VALARM
DTSTART:20180819T000500Z
DTEND:20180819T030500Z
UID:s6VOlpPLr2VAEvxII1xNRKcZ@stanza.co
SUMMARY:Dodgers vs. Cubs
DESCRIPTION:Dodgers vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+v$OM-j\n\nShop: https://stza.co/+v$OM-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Cubs
<2018-08-19 Sun 18:05-21:05>
:PROPERTIES:
:ID:       GzEfW1Wfcnta7vapHWmqH6_L@stanza.co
:LOCATION: Chaparral Energy Family Sundays
:STATUS:   CONFIRMED
:END:

Dodgers vs. Cubs 



Follow on MiLB First Pitch  https //stza.co/+v$OO-7

Shop  https //stza.co/+v$OO-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Cubs
END:VALARM
DTSTART:20180819T230500Z
DTEND:20180820T020500Z
UID:GzEfW1Wfcnta7vapHWmqH6_L@stanza.co
SUMMARY:Dodgers vs. Cubs
DESCRIPTION:\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+v$OO-7\n\nShop: https://stza.co/+v$OO-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Chaparral Energy Family Sundays
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Storm Chasers
<2018-08-21 Tue 19:05-22:05>
:PROPERTIES:
:ID:       2mmG2urqloLkNoiFnKN367ej@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Storm Chasers Dodgers vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+v$OQ-g

Shop  https //stza.co/+v$OQ-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Storm Chasers
END:VALARM
DTSTART:20180822T000500Z
DTEND:20180822T030500Z
UID:2mmG2urqloLkNoiFnKN367ej@stanza.co
SUMMARY:Dodgers vs. Storm Chasers
DESCRIPTION:Dodgers vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+v$OQ-g\n\nShop: https://stza.co/+v$OQ-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Storm Chasers
<2018-08-22 Wed 19:05-22:05>
:PROPERTIES:
:ID:       5OwOOW3HAkpEm9pwEnS7mpOz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Storm Chasers Dodgers vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+v$OS-2m

Shop  https //stza.co/+v$OS-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Storm Chasers
END:VALARM
DTSTART:20180823T000500Z
DTEND:20180823T030500Z
UID:5OwOOW3HAkpEm9pwEnS7mpOz@stanza.co
SUMMARY:Dodgers vs. Storm Chasers
DESCRIPTION:Dodgers vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+v$OS-2m\n\nShop: https://stza.co/+v$OS-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Storm Chasers
<2018-08-23 Thu 19:05-22:05>
:PROPERTIES:
:ID:       IbRv8MJhoGBpINkvyHdsaUSz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Storm Chasers Dodgers vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+v$OT-2w

Shop  https //stza.co/+v$OT-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Storm Chasers
END:VALARM
DTSTART:20180824T000500Z
DTEND:20180824T030500Z
UID:IbRv8MJhoGBpINkvyHdsaUSz@stanza.co
SUMMARY:Dodgers vs. Storm Chasers
DESCRIPTION:Dodgers vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+v$OT-2w\n\nShop: https://stza.co/+v$OT-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Sky Sox
<2018-08-24 Fri 19:05-22:05>
:PROPERTIES:
:ID:       1xE1-HyfJA02vXCs96K-fbn8@stanza.co
:LOCATION: Celebrate the start of the weekend with our Friday Night Fireworks after the game!
:STATUS:   CONFIRMED
:END:

Dodgers vs. Sky Sox 





Follow on MiLB First Pitch  https //stza.co/+v$OV-1Q

Shop  https //stza.co/+v$OV-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Sky Sox
END:VALARM
DTSTART:20180825T000500Z
DTEND:20180825T030500Z
UID:1xE1-HyfJA02vXCs96K-fbn8@stanza.co
SUMMARY:Dodgers vs. Sky Sox
DESCRIPTION:\n\n\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+v$OV-1Q\n\nShop: https://stza.co/+v$OV-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Celebrate the start of the weekend with our Friday Night Fireworks after the game!
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Sky Sox
<2018-08-25 Sat 19:05-22:05>
:PROPERTIES:
:ID:       HHEN2fsrtsIay3u56KIwQror@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Sky Sox Dodgers vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+v$OY-2s

Shop  https //stza.co/+v$OY-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Sky Sox
END:VALARM
DTSTART:20180826T000500Z
DTEND:20180826T030500Z
UID:HHEN2fsrtsIay3u56KIwQror@stanza.co
SUMMARY:Dodgers vs. Sky Sox
DESCRIPTION:Dodgers vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+v$OY-2s\n\nShop: https://stza.co/+v$OY-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Sky Sox
<2018-08-26 Sun 18:05-21:05>
:PROPERTIES:
:ID:       64wBsqZMzag2cBJqYGvXu12J@stanza.co
:LOCATION: Chaparral Energy Family Sundays
:STATUS:   CONFIRMED
:END:

Dodgers vs. Sky Sox 



Follow on MiLB First Pitch  https //stza.co/+v$OZ-2r

Shop  https //stza.co/+v$OZ-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Sky Sox
END:VALARM
DTSTART:20180826T230500Z
DTEND:20180827T020500Z
UID:64wBsqZMzag2cBJqYGvXu12J@stanza.co
SUMMARY:Dodgers vs. Sky Sox
DESCRIPTION:\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+v$OZ-2r\n\nShop: https://stza.co/+v$OZ-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Chaparral Energy Family Sundays
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers vs. Sky Sox
<2018-08-27 Mon 19:05-22:05>
:PROPERTIES:
:ID:       XFY9KoxbNj-zYpF4enFsRJ8t@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers vs. Sky Sox Dodgers vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+v$P0-11

Shop  https //stza.co/+v$P0-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Dodgers vs. Sky Sox
END:VALARM
DTSTART:20180828T000500Z
DTEND:20180828T030500Z
UID:XFY9KoxbNj-zYpF4enFsRJ8t@stanza.co
SUMMARY:Dodgers vs. Sky Sox
DESCRIPTION:Dodgers vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+v$P0-11\n\nShop: https://stza.co/+v$P0-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Cubs
<2018-08-28 Tue 19:08-22:08>
:PROPERTIES:
:ID:       oj0HcWQhaqejvTh_S6wyRCB6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Cubs Dodgers @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKOl-3t

Shop  https //stza.co/+vKOl-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Cubs
END:VALARM
DTSTART:20180829T000800Z
DTEND:20180829T030800Z
UID:oj0HcWQhaqejvTh_S6wyRCB6@stanza.co
SUMMARY:Dodgers @ Cubs
DESCRIPTION:Dodgers @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKOl-3t\n\nShop: https://stza.co/+vKOl-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Cubs
<2018-08-29 Wed 19:08-22:08>
:PROPERTIES:
:ID:       MBzfkncscuI2fXpoYKAT414c@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers @ Cubs Dodgers @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKOm-29

Shop  https //stza.co/+vKOm-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Cubs
END:VALARM
DTSTART:20180830T000800Z
DTEND:20180830T030800Z
UID:MBzfkncscuI2fXpoYKAT414c@stanza.co
SUMMARY:Dodgers @ Cubs
DESCRIPTION:Dodgers @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKOm-29\n\nShop: https://stza.co/+vKOm-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Cubs
<2018-08-30 Thu 12:08-15:08>
:PROPERTIES:
:ID:       4GlIF_ZtGfPf2x0ng3e80IIr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Cubs Dodgers @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKOn-12

Shop  https //stza.co/+vKOn-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Cubs
END:VALARM
DTSTART:20180830T170800Z
DTEND:20180830T200800Z
UID:4GlIF_ZtGfPf2x0ng3e80IIr@stanza.co
SUMMARY:Dodgers @ Cubs
DESCRIPTION:Dodgers @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKOn-12\n\nShop: https://stza.co/+vKOn-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Sky Sox
<2018-08-31 Fri 19:40-22:40>
:PROPERTIES:
:ID:       2ixACas406nNQ6lGXmI9rRMH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Sky Sox Dodgers @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmIg-2Y

Shop  https //stza.co/+wmIg-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Sky Sox
END:VALARM
DTSTART:20180901T004000Z
DTEND:20180901T034000Z
UID:2ixACas406nNQ6lGXmI9rRMH@stanza.co
SUMMARY:Dodgers @ Sky Sox
DESCRIPTION:Dodgers @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmIg-2Y\n\nShop: https://stza.co/+wmIg-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Sky Sox
<2018-09-01 Sat 19:00-22:00>
:PROPERTIES:
:ID:       W1BqOFwIibnZtsPbw3SRytqz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Dodgers @ Sky Sox Dodgers @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmIh-2y

Shop  https //stza.co/+wmIh-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Sky Sox
END:VALARM
DTSTART:20180902T000000Z
DTEND:20180902T030000Z
UID:W1BqOFwIibnZtsPbw3SRytqz@stanza.co
SUMMARY:Dodgers @ Sky Sox
DESCRIPTION:Dodgers @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmIh-2y\n\nShop: https://stza.co/+wmIh-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Sky Sox
<2018-09-02 Sun 18:00-21:00>
:PROPERTIES:
:ID:       Km_z9S8yYRBpn78owZogOCz9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Sky Sox Dodgers @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmIi-2s

Shop  https //stza.co/+wmIi-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Sky Sox
END:VALARM
DTSTART:20180902T230000Z
DTEND:20180903T020000Z
UID:Km_z9S8yYRBpn78owZogOCz9@stanza.co
SUMMARY:Dodgers @ Sky Sox
DESCRIPTION:Dodgers @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmIi-2s\n\nShop: https://stza.co/+wmIi-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Dodgers @ Sky Sox
<2018-09-03 Mon 14:00-17:00>
:PROPERTIES:
:ID:       6ss183wBTxsoa35d3AkWY3PM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Dodgers @ Sky Sox Dodgers @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmIj-29

Shop  https //stza.co/+wmIj-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Dodgers @ Sky Sox
END:VALARM
DTSTART:20180903T190000Z
DTEND:20180903T220000Z
UID:6ss183wBTxsoa35d3AkWY3PM@stanza.co
SUMMARY:Dodgers @ Sky Sox
DESCRIPTION:Dodgers @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmIj-29\n\nShop: https://stza.co/+wmIj-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
