#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Emeralds vs. Canadians
<2018-06-15 Fri 21:05>--<2018-06-16 Sat 00:05>
:PROPERTIES:
:ID:       94WRzCIn3OCg4N2ajLw4gUvr@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Canadians Emeralds vs. Canadians

Follow on MiLB First Pitch  https //stza.co/+xWO3-q

Shop  https //stza.co/+xWO3-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Canadians
END:VALARM
DTSTART:20180616T020500Z
DTEND:20180616T050500Z
UID:94WRzCIn3OCg4N2ajLw4gUvr@stanza.co
SUMMARY:Emeralds vs. Canadians
DESCRIPTION:Emeralds vs. Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xWO3-q\n\nShop: https://stza.co/+xWO3-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. Canadians
<2018-06-16 Sat 21:05>--<2018-06-17 Sun 00:05>
:PROPERTIES:
:ID:       fR43cGjmhLjEa3T_OOH8Fcsl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Canadians Emeralds vs. Canadians

Follow on MiLB First Pitch  https //stza.co/+xWO5-1W

Shop  https //stza.co/+xWO5-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Canadians
END:VALARM
DTSTART:20180617T020500Z
DTEND:20180617T050500Z
UID:fR43cGjmhLjEa3T_OOH8Fcsl@stanza.co
SUMMARY:Emeralds vs. Canadians
DESCRIPTION:Emeralds vs. Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xWO5-1W\n\nShop: https://stza.co/+xWO5-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. Canadians
<2018-06-17 Sun 19:05-22:05>
:PROPERTIES:
:ID:       BYQWd0fpiy-hbZz2Hmn3e4r2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Canadians Emeralds vs. Canadians

Follow on MiLB First Pitch  https //stza.co/+xWO7-1r

Shop  https //stza.co/+xWO7-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Canadians
END:VALARM
DTSTART:20180618T000500Z
DTEND:20180618T030500Z
UID:BYQWd0fpiy-hbZz2Hmn3e4r2@stanza.co
SUMMARY:Emeralds vs. Canadians
DESCRIPTION:Emeralds vs. Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xWO7-1r\n\nShop: https://stza.co/+xWO7-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. Canadians
<2018-06-18 Mon 21:05>--<2018-06-19 Tue 00:05>
:PROPERTIES:
:ID:       UY6wEYXYRUCBAP5dSD_mp8Pz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Canadians Emeralds vs. Canadians

Follow on MiLB First Pitch  https //stza.co/+xWOa-1x

Shop  https //stza.co/+xWOa-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Canadians
END:VALARM
DTSTART:20180619T020500Z
DTEND:20180619T050500Z
UID:UY6wEYXYRUCBAP5dSD_mp8Pz@stanza.co
SUMMARY:Emeralds vs. Canadians
DESCRIPTION:Emeralds vs. Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xWOa-1x\n\nShop: https://stza.co/+xWOa-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. Canadians
<2018-06-19 Tue 21:05>--<2018-06-20 Wed 00:05>
:PROPERTIES:
:ID:       hwos9BOSyeO0MSqkzUZ1S2ca@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Canadians Emeralds vs. Canadians

Follow on MiLB First Pitch  https //stza.co/+xWOc-2x

Shop  https //stza.co/+xWOc-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Canadians
END:VALARM
DTSTART:20180620T020500Z
DTEND:20180620T050500Z
UID:hwos9BOSyeO0MSqkzUZ1S2ca@stanza.co
SUMMARY:Emeralds vs. Canadians
DESCRIPTION:Emeralds vs. Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xWOc-2x\n\nShop: https://stza.co/+xWOc-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Hops
<2018-06-20 Wed 21:05>--<2018-06-21 Thu 00:05>
:PROPERTIES:
:ID:       YxD9eq5TYRHN2MAtKPbspLkk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds @ Hops Emeralds @ Hops

Follow on MiLB First Pitch  https //stza.co/+vO6Z-2D

Shop  https //stza.co/+vO6Z-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Hops
END:VALARM
DTSTART:20180621T020500Z
DTEND:20180621T050500Z
UID:YxD9eq5TYRHN2MAtKPbspLkk@stanza.co
SUMMARY:Emeralds @ Hops
DESCRIPTION:Emeralds @ Hops\n\nFollow on MiLB First Pitch: https://stza.co/+vO6Z-2D\n\nShop: https://stza.co/+vO6Z-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Hops
<2018-06-21 Thu 21:05>--<2018-06-22 Fri 00:05>
:PROPERTIES:
:ID:       LT3R1sWRVN-wmKtcAZ78AGow@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds @ Hops Emeralds @ Hops

Follow on MiLB First Pitch  https //stza.co/+vO6_-2T

Shop  https //stza.co/+vO6_-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Hops
END:VALARM
DTSTART:20180622T020500Z
DTEND:20180622T050500Z
UID:LT3R1sWRVN-wmKtcAZ78AGow@stanza.co
SUMMARY:Emeralds @ Hops
DESCRIPTION:Emeralds @ Hops\n\nFollow on MiLB First Pitch: https://stza.co/+vO6_-2T\n\nShop: https://stza.co/+vO6_-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Hops
<2018-06-22 Fri 21:05>--<2018-06-23 Sat 00:05>
:PROPERTIES:
:ID:       KpLlQRMAqvaP0ybvA-hjglXm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Emeralds @ Hops Emeralds @ Hops

Follow on MiLB First Pitch  https //stza.co/+vO6$-w

Shop  https //stza.co/+vO6$-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Hops
END:VALARM
DTSTART:20180623T020500Z
DTEND:20180623T050500Z
UID:KpLlQRMAqvaP0ybvA-hjglXm@stanza.co
SUMMARY:Emeralds @ Hops
DESCRIPTION:Emeralds @ Hops\n\nFollow on MiLB First Pitch: https://stza.co/+vO6$-w\n\nShop: https://stza.co/+vO6$-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. Hawks
<2018-06-23 Sat 21:05>--<2018-06-24 Sun 00:05>
:PROPERTIES:
:ID:       uFv9UEnCFnDLQYO1sYm5AcVi@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Hawks Emeralds vs. Hawks

Follow on MiLB First Pitch  https //stza.co/+xWOd-q

Shop  https //stza.co/+xWOd-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Hawks
END:VALARM
DTSTART:20180624T020500Z
DTEND:20180624T050500Z
UID:uFv9UEnCFnDLQYO1sYm5AcVi@stanza.co
SUMMARY:Emeralds vs. Hawks
DESCRIPTION:Emeralds vs. Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xWOd-q\n\nShop: https://stza.co/+xWOd-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. Hawks
<2018-06-24 Sun 21:05>--<2018-06-25 Mon 00:05>
:PROPERTIES:
:ID:       p3gIhOPh7JhVf1-2nVuhnQ7U@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Hawks Emeralds vs. Hawks

Follow on MiLB First Pitch  https //stza.co/+xWOg-3C

Shop  https //stza.co/+xWOg-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Hawks
END:VALARM
DTSTART:20180625T020500Z
DTEND:20180625T050500Z
UID:p3gIhOPh7JhVf1-2nVuhnQ7U@stanza.co
SUMMARY:Emeralds vs. Hawks
DESCRIPTION:Emeralds vs. Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xWOg-3C\n\nShop: https://stza.co/+xWOg-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. Hawks
<2018-06-25 Mon 21:05>--<2018-06-26 Tue 00:05>
:PROPERTIES:
:ID:       rdMB2wGDaVXUuhCUP43sC7n7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Hawks Emeralds vs. Hawks

Follow on MiLB First Pitch  https //stza.co/+xWOh-24

Shop  https //stza.co/+xWOh-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Hawks
END:VALARM
DTSTART:20180626T020500Z
DTEND:20180626T050500Z
UID:rdMB2wGDaVXUuhCUP43sC7n7@stanza.co
SUMMARY:Emeralds vs. Hawks
DESCRIPTION:Emeralds vs. Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xWOh-24\n\nShop: https://stza.co/+xWOh-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Volcanoes
<2018-06-26 Tue>--<2018-06-25 Mon>
:PROPERTIES:
:ID:       sJJiD986QleFwLu2tb53uI5Z@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds @ Volcanoes Emeralds @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vO73-3G

Shop  https //stza.co/+vO73-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180626
DTEND;VALUE=DATE:20180626
UID:sJJiD986QleFwLu2tb53uI5Z@stanza.co
SUMMARY:Emeralds @ Volcanoes
DESCRIPTION:Emeralds @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vO73-3G\n\nShop: https://stza.co/+vO73-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Volcanoes
<2018-06-27 Wed>--<2018-06-26 Tue>
:PROPERTIES:
:ID:       eegTusFZQdn16m639BL6aSAK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds @ Volcanoes Emeralds @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vO74-2w

Shop  https //stza.co/+vO74-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180627
DTEND;VALUE=DATE:20180627
UID:eegTusFZQdn16m639BL6aSAK@stanza.co
SUMMARY:Emeralds @ Volcanoes
DESCRIPTION:Emeralds @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vO74-2w\n\nShop: https://stza.co/+vO74-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Volcanoes
<2018-06-28 Thu>--<2018-06-27 Wed>
:PROPERTIES:
:ID:       SqvqRklf0c0CaNdt1cObUdD8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Emeralds @ Volcanoes Emeralds @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vO75-2d

Shop  https //stza.co/+vO75-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180628
DTEND;VALUE=DATE:20180628
UID:SqvqRklf0c0CaNdt1cObUdD8@stanza.co
SUMMARY:Emeralds @ Volcanoes
DESCRIPTION:Emeralds @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vO75-2d\n\nShop: https://stza.co/+vO75-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. AquaSox
<2018-06-29 Fri 21:05>--<2018-06-30 Sat 00:05>
:PROPERTIES:
:ID:       GCOKQ9tr1BqWUR9z5wT2XOgV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds vs. AquaSox Emeralds vs. AquaSox

Follow on MiLB First Pitch  https //stza.co/+xWOk-3x

Shop  https //stza.co/+xWOk-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. AquaSox
END:VALARM
DTSTART:20180630T020500Z
DTEND:20180630T050500Z
UID:GCOKQ9tr1BqWUR9z5wT2XOgV@stanza.co
SUMMARY:Emeralds vs. AquaSox
DESCRIPTION:Emeralds vs. AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+xWOk-3x\n\nShop: https://stza.co/+xWOk-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. AquaSox
<2018-07-01 Sun>--<2018-06-30 Sat>
:PROPERTIES:
:ID:       -TnBjLlCjuLcU3hinOAxtHEO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Emeralds vs. AquaSox Emeralds vs. AquaSox

Follow on MiLB First Pitch  https //stza.co/+vO60-7

Shop  https //stza.co/+vO60-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. AquaSox
END:VALARM
DTSTART;VALUE=DATE:20180701
DTEND;VALUE=DATE:20180701
UID:-TnBjLlCjuLcU3hinOAxtHEO@stanza.co
SUMMARY:Emeralds vs. AquaSox
DESCRIPTION:Emeralds vs. AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vO60-7\n\nShop: https://stza.co/+vO60-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. AquaSox
<2018-07-01 Sun 18:05-21:05>
:PROPERTIES:
:ID:       gEi2-P2BhRkddjFtGp3TsTNg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds vs. AquaSox Emeralds vs. AquaSox

Follow on MiLB First Pitch  https //stza.co/+xWOm-21

Shop  https //stza.co/+xWOm-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. AquaSox
END:VALARM
DTSTART:20180701T230500Z
DTEND:20180702T020500Z
UID:gEi2-P2BhRkddjFtGp3TsTNg@stanza.co
SUMMARY:Emeralds vs. AquaSox
DESCRIPTION:Emeralds vs. AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+xWOm-21\n\nShop: https://stza.co/+xWOm-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. AquaSox
<2018-07-02 Mon 21:05>--<2018-07-03 Tue 00:05>
:PROPERTIES:
:ID:       YnuCa24Q3EV-vQ4CKVYmONKS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds vs. AquaSox Emeralds vs. AquaSox

Follow on MiLB First Pitch  https //stza.co/+xWOn-1m

Shop  https //stza.co/+xWOn-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. AquaSox
END:VALARM
DTSTART:20180703T020500Z
DTEND:20180703T050500Z
UID:YnuCa24Q3EV-vQ4CKVYmONKS@stanza.co
SUMMARY:Emeralds vs. AquaSox
DESCRIPTION:Emeralds vs. AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+xWOn-1m\n\nShop: https://stza.co/+xWOn-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. AquaSox
<2018-07-03 Tue 21:05>--<2018-07-04 Wed 00:05>
:PROPERTIES:
:ID:       xt7EEQnfvPFNlTWz1kxfBRYg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds vs. AquaSox Emeralds vs. AquaSox

Follow on MiLB First Pitch  https //stza.co/+xWOq-2L

Shop  https //stza.co/+xWOq-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. AquaSox
END:VALARM
DTSTART:20180704T020500Z
DTEND:20180704T050500Z
UID:xt7EEQnfvPFNlTWz1kxfBRYg@stanza.co
SUMMARY:Emeralds vs. AquaSox
DESCRIPTION:Emeralds vs. AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+xWOq-2L\n\nShop: https://stza.co/+xWOq-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Hawks
<2018-07-04 Wed 20:15-23:15>
:PROPERTIES:
:ID:       mRALz6lmbxgNRrQrEcwqtYe3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Emeralds @ Hawks Emeralds @ Hawks

Follow on MiLB First Pitch  https //stza.co/+xC66-2P

Shop  https //stza.co/+xC66-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Hawks
END:VALARM
DTSTART:20180705T011500Z
DTEND:20180705T041500Z
UID:mRALz6lmbxgNRrQrEcwqtYe3@stanza.co
SUMMARY:Emeralds @ Hawks
DESCRIPTION:Emeralds @ Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xC66-2P\n\nShop: https://stza.co/+xC66-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Hawks
<2018-07-05 Thu 20:15-23:15>
:PROPERTIES:
:ID:       9qLEHqGo_KhwBWnfToLKMaVr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds @ Hawks Emeralds @ Hawks

Follow on MiLB First Pitch  https //stza.co/+xC6b-2V

Shop  https //stza.co/+xC6b-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Hawks
END:VALARM
DTSTART:20180706T011500Z
DTEND:20180706T041500Z
UID:9qLEHqGo_KhwBWnfToLKMaVr@stanza.co
SUMMARY:Emeralds @ Hawks
DESCRIPTION:Emeralds @ Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xC6b-2V\n\nShop: https://stza.co/+xC6b-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Hawks
<2018-07-06 Fri 20:15-23:15>
:PROPERTIES:
:ID:       0kaiky-2iLH6uJNIhfiYgLMU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds @ Hawks Emeralds @ Hawks

Follow on MiLB First Pitch  https //stza.co/+xC6g-2K

Shop  https //stza.co/+xC6g-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Hawks
END:VALARM
DTSTART:20180707T011500Z
DTEND:20180707T041500Z
UID:0kaiky-2iLH6uJNIhfiYgLMU@stanza.co
SUMMARY:Emeralds @ Hawks
DESCRIPTION:Emeralds @ Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xC6g-2K\n\nShop: https://stza.co/+xC6g-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. Hops
<2018-07-07 Sat 21:05>--<2018-07-08 Sun 00:05>
:PROPERTIES:
:ID:       L_zH2BsAdnNIuSdiN96DSUJi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Hops Emeralds vs. Hops

Follow on MiLB First Pitch  https //stza.co/+xWOr-2v

Shop  https //stza.co/+xWOr-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Hops
END:VALARM
DTSTART:20180708T020500Z
DTEND:20180708T050500Z
UID:L_zH2BsAdnNIuSdiN96DSUJi@stanza.co
SUMMARY:Emeralds vs. Hops
DESCRIPTION:Emeralds vs. Hops\n\nFollow on MiLB First Pitch: https://stza.co/+xWOr-2v\n\nShop: https://stza.co/+xWOr-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. Hops
<2018-07-08 Sun 19:05-22:05>
:PROPERTIES:
:ID:       CSViJqBKTCZNXz8rX13DCvta@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Hops Emeralds vs. Hops

Follow on MiLB First Pitch  https //stza.co/+xWOu-15

Shop  https //stza.co/+xWOu-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Hops
END:VALARM
DTSTART:20180709T000500Z
DTEND:20180709T030500Z
UID:CSViJqBKTCZNXz8rX13DCvta@stanza.co
SUMMARY:Emeralds vs. Hops
DESCRIPTION:Emeralds vs. Hops\n\nFollow on MiLB First Pitch: https://stza.co/+xWOu-15\n\nShop: https://stza.co/+xWOu-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. Hops
<2018-07-09 Mon 21:05>--<2018-07-10 Tue 00:05>
:PROPERTIES:
:ID:       JgRxk2ItE5mL9fU2SXT3Z6zT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Hops Emeralds vs. Hops

Follow on MiLB First Pitch  https //stza.co/+xWOw-

Shop  https //stza.co/+xWOw-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Hops
END:VALARM
DTSTART:20180710T020500Z
DTEND:20180710T050500Z
UID:JgRxk2ItE5mL9fU2SXT3Z6zT@stanza.co
SUMMARY:Emeralds vs. Hops
DESCRIPTION:Emeralds vs. Hops\n\nFollow on MiLB First Pitch: https://stza.co/+xWOw-\n\nShop: https://stza.co/+xWOw-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Indians
<2018-07-11 Wed 20:30-23:30>
:PROPERTIES:
:ID:       DELuUk-e94iyJRbhhZYUXXvu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Emeralds @ Indians Emeralds @ Indians

Follow on MiLB First Pitch  https //stza.co/+xC6q-s

Shop  https //stza.co/+xC6q-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Indians
END:VALARM
DTSTART:20180712T013000Z
DTEND:20180712T043000Z
UID:DELuUk-e94iyJRbhhZYUXXvu@stanza.co
SUMMARY:Emeralds @ Indians
DESCRIPTION:Emeralds @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xC6q-s\n\nShop: https://stza.co/+xC6q-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Indians
<2018-07-12 Thu 20:30-23:30>
:PROPERTIES:
:ID:       SleHQ75VjtePRqFPW5MQYpFQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds @ Indians Emeralds @ Indians

Follow on MiLB First Pitch  https //stza.co/+xC6r-2s

Shop  https //stza.co/+xC6r-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Indians
END:VALARM
DTSTART:20180713T013000Z
DTEND:20180713T043000Z
UID:SleHQ75VjtePRqFPW5MQYpFQ@stanza.co
SUMMARY:Emeralds @ Indians
DESCRIPTION:Emeralds @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xC6r-2s\n\nShop: https://stza.co/+xC6r-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Indians
<2018-07-13 Fri 20:30-23:30>
:PROPERTIES:
:ID:       dC-aLsT7Uc2KcnDjFxDoqQG-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds @ Indians Emeralds @ Indians

Follow on MiLB First Pitch  https //stza.co/+xC6s-g

Shop  https //stza.co/+xC6s-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Indians
END:VALARM
DTSTART:20180714T013000Z
DTEND:20180714T043000Z
UID:dC-aLsT7Uc2KcnDjFxDoqQG-@stanza.co
SUMMARY:Emeralds @ Indians
DESCRIPTION:Emeralds @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xC6s-g\n\nShop: https://stza.co/+xC6s-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Indians
<2018-07-14 Sat 20:30-23:30>
:PROPERTIES:
:ID:       VyO1gFhru-a3jvB_655eF2Kr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Emeralds @ Indians Emeralds @ Indians

Follow on MiLB First Pitch  https //stza.co/+xC6t-w

Shop  https //stza.co/+xC6t-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Indians
END:VALARM
DTSTART:20180715T013000Z
DTEND:20180715T043000Z
UID:VyO1gFhru-a3jvB_655eF2Kr@stanza.co
SUMMARY:Emeralds @ Indians
DESCRIPTION:Emeralds @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xC6t-w\n\nShop: https://stza.co/+xC6t-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Indians
<2018-07-15 Sun 17:30-20:30>
:PROPERTIES:
:ID:       8FUGV8PrKRL1T_onNoA_xYs2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds @ Indians Emeralds @ Indians

Follow on MiLB First Pitch  https //stza.co/+xC6u-2Q

Shop  https //stza.co/+xC6u-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Indians
END:VALARM
DTSTART:20180715T223000Z
DTEND:20180716T013000Z
UID:8FUGV8PrKRL1T_onNoA_xYs2@stanza.co
SUMMARY:Emeralds @ Indians
DESCRIPTION:Emeralds @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xC6u-2Q\n\nShop: https://stza.co/+xC6u-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. Volcanoes
<2018-07-16 Mon 21:05>--<2018-07-17 Tue 00:05>
:PROPERTIES:
:ID:       1sit7dmfW6aidCbji3T2Vtnl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Volcanoes Emeralds vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+xWOx-13

Shop  https //stza.co/+xWOx-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Volcanoes
END:VALARM
DTSTART:20180717T020500Z
DTEND:20180717T050500Z
UID:1sit7dmfW6aidCbji3T2Vtnl@stanza.co
SUMMARY:Emeralds vs. Volcanoes
DESCRIPTION:Emeralds vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+xWOx-13\n\nShop: https://stza.co/+xWOx-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. Volcanoes
<2018-07-17 Tue 21:05>--<2018-07-18 Wed 00:05>
:PROPERTIES:
:ID:       sZPWfONxM6T28VfqFuKxivQR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Volcanoes Emeralds vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+xWOA-2r

Shop  https //stza.co/+xWOA-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Volcanoes
END:VALARM
DTSTART:20180718T020500Z
DTEND:20180718T050500Z
UID:sZPWfONxM6T28VfqFuKxivQR@stanza.co
SUMMARY:Emeralds vs. Volcanoes
DESCRIPTION:Emeralds vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+xWOA-2r\n\nShop: https://stza.co/+xWOA-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. Volcanoes
<2018-07-18 Wed 21:05>--<2018-07-19 Thu 00:05>
:PROPERTIES:
:ID:       mVuYM-R0BRqNKV-Vk8-a6712@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Volcanoes Emeralds vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+xWOB-2a

Shop  https //stza.co/+xWOB-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Volcanoes
END:VALARM
DTSTART:20180719T020500Z
DTEND:20180719T050500Z
UID:mVuYM-R0BRqNKV-Vk8-a6712@stanza.co
SUMMARY:Emeralds vs. Volcanoes
DESCRIPTION:Emeralds vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+xWOB-2a\n\nShop: https://stza.co/+xWOB-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Dust Devils
<2018-07-19 Thu 21:15>--<2018-07-20 Fri 00:15>
:PROPERTIES:
:ID:       ao5PBn00neHM2JpsK4hHtWH3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds @ Dust Devils Emeralds @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vO7e-R

Shop  https //stza.co/+vO7e-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Dust Devils
END:VALARM
DTSTART:20180720T021500Z
DTEND:20180720T051500Z
UID:ao5PBn00neHM2JpsK4hHtWH3@stanza.co
SUMMARY:Emeralds @ Dust Devils
DESCRIPTION:Emeralds @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vO7e-R\n\nShop: https://stza.co/+vO7e-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Dust Devils
<2018-07-20 Fri 21:15>--<2018-07-21 Sat 00:15>
:PROPERTIES:
:ID:       FlMATawbQfLZ7KaSb_7cty2y@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Emeralds @ Dust Devils Emeralds @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vO7f-3e

Shop  https //stza.co/+vO7f-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Dust Devils
END:VALARM
DTSTART:20180721T021500Z
DTEND:20180721T051500Z
UID:FlMATawbQfLZ7KaSb_7cty2y@stanza.co
SUMMARY:Emeralds @ Dust Devils
DESCRIPTION:Emeralds @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vO7f-3e\n\nShop: https://stza.co/+vO7f-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Dust Devils
<2018-07-21 Sat 21:15>--<2018-07-22 Sun 00:15>
:PROPERTIES:
:ID:       VM-Upnmj75zkUYuI3pyPbNBn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds @ Dust Devils Emeralds @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vO7g-3t

Shop  https //stza.co/+vO7g-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Dust Devils
END:VALARM
DTSTART:20180722T021500Z
DTEND:20180722T051500Z
UID:VM-Upnmj75zkUYuI3pyPbNBn@stanza.co
SUMMARY:Emeralds @ Dust Devils
DESCRIPTION:Emeralds @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vO7g-3t\n\nShop: https://stza.co/+vO7g-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Dust Devils
<2018-07-22 Sun 21:15>--<2018-07-23 Mon 00:15>
:PROPERTIES:
:ID:       CIUctDm6XwPWbH-KBV4sJb7o@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds @ Dust Devils Emeralds @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vO7h-1t

Shop  https //stza.co/+vO7h-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Dust Devils
END:VALARM
DTSTART:20180723T021500Z
DTEND:20180723T051500Z
UID:CIUctDm6XwPWbH-KBV4sJb7o@stanza.co
SUMMARY:Emeralds @ Dust Devils
DESCRIPTION:Emeralds @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vO7h-1t\n\nShop: https://stza.co/+vO7h-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Dust Devils
<2018-07-23 Mon 21:15>--<2018-07-24 Tue 00:15>
:PROPERTIES:
:ID:       xJBOtg4loR7b5AIFuM57Qa-o@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Emeralds @ Dust Devils Emeralds @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vO7i-2q

Shop  https //stza.co/+vO7i-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Dust Devils
END:VALARM
DTSTART:20180724T021500Z
DTEND:20180724T051500Z
UID:xJBOtg4loR7b5AIFuM57Qa-o@stanza.co
SUMMARY:Emeralds @ Dust Devils
DESCRIPTION:Emeralds @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vO7i-2q\n\nShop: https://stza.co/+vO7i-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. Volcanoes
<2018-07-24 Tue 21:05>--<2018-07-25 Wed 00:05>
:PROPERTIES:
:ID:       3gRJhoRtPy3DY1BMSvCPK-2c@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Volcanoes Emeralds vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+xWOD-1m

Shop  https //stza.co/+xWOD-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Volcanoes
END:VALARM
DTSTART:20180725T020500Z
DTEND:20180725T050500Z
UID:3gRJhoRtPy3DY1BMSvCPK-2c@stanza.co
SUMMARY:Emeralds vs. Volcanoes
DESCRIPTION:Emeralds vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+xWOD-1m\n\nShop: https://stza.co/+xWOD-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. Volcanoes
<2018-07-25 Wed 21:05>--<2018-07-26 Thu 00:05>
:PROPERTIES:
:ID:       L5IySDrLUQc_9l0xWiYORgIE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Volcanoes Emeralds vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+xWOG-9

Shop  https //stza.co/+xWOG-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Volcanoes
END:VALARM
DTSTART:20180726T020500Z
DTEND:20180726T050500Z
UID:L5IySDrLUQc_9l0xWiYORgIE@stanza.co
SUMMARY:Emeralds vs. Volcanoes
DESCRIPTION:Emeralds vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+xWOG-9\n\nShop: https://stza.co/+xWOG-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. Volcanoes
<2018-07-26 Thu 21:05>--<2018-07-27 Fri 00:05>
:PROPERTIES:
:ID:       0yuhQx1IP_7kpUm6Hojj0gbF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Volcanoes Emeralds vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+xWOI-j

Shop  https //stza.co/+xWOI-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Volcanoes
END:VALARM
DTSTART:20180727T020500Z
DTEND:20180727T050500Z
UID:0yuhQx1IP_7kpUm6Hojj0gbF@stanza.co
SUMMARY:Emeralds vs. Volcanoes
DESCRIPTION:Emeralds vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+xWOI-j\n\nShop: https://stza.co/+xWOI-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Canadians
<2018-07-27 Fri 21:05>--<2018-07-28 Sat 00:05>
:PROPERTIES:
:ID:       EutgYJVP3kxE5F8JQaNpJ0o5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds @ Canadians Emeralds @ Canadians

Follow on MiLB First Pitch  https //stza.co/+xXUG-3Z

Shop  https //stza.co/+xXUG-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Canadians
END:VALARM
DTSTART:20180728T020500Z
DTEND:20180728T050500Z
UID:EutgYJVP3kxE5F8JQaNpJ0o5@stanza.co
SUMMARY:Emeralds @ Canadians
DESCRIPTION:Emeralds @ Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xXUG-3Z\n\nShop: https://stza.co/+xXUG-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Canadians
<2018-07-28 Sat 21:05>--<2018-07-29 Sun 00:05>
:PROPERTIES:
:ID:       NzOtrsBj1bqZzJTgPaCqeePS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds @ Canadians Emeralds @ Canadians

Follow on MiLB First Pitch  https //stza.co/+xXUI-35

Shop  https //stza.co/+xXUI-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Canadians
END:VALARM
DTSTART:20180729T020500Z
DTEND:20180729T050500Z
UID:NzOtrsBj1bqZzJTgPaCqeePS@stanza.co
SUMMARY:Emeralds @ Canadians
DESCRIPTION:Emeralds @ Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xXUI-35\n\nShop: https://stza.co/+xXUI-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Canadians
<2018-07-29 Sun 15:05-18:05>
:PROPERTIES:
:ID:       3nwqY1UDr_nz1Bb-bZH433AI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Emeralds @ Canadians Emeralds @ Canadians

Follow on MiLB First Pitch  https //stza.co/+xXUJ-1I

Shop  https //stza.co/+xXUJ-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Canadians
END:VALARM
DTSTART:20180729T200500Z
DTEND:20180729T230500Z
UID:3nwqY1UDr_nz1Bb-bZH433AI@stanza.co
SUMMARY:Emeralds @ Canadians
DESCRIPTION:Emeralds @ Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xXUJ-1I\n\nShop: https://stza.co/+xXUJ-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Canadians
<2018-07-30 Mon 21:05>--<2018-07-31 Tue 00:05>
:PROPERTIES:
:ID:       1BI73sjuOhq3P5OCxgFX5yx5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds @ Canadians Emeralds @ Canadians

Follow on MiLB First Pitch  https //stza.co/+xXUK-1t

Shop  https //stza.co/+xXUK-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Canadians
END:VALARM
DTSTART:20180731T020500Z
DTEND:20180731T050500Z
UID:1BI73sjuOhq3P5OCxgFX5yx5@stanza.co
SUMMARY:Emeralds @ Canadians
DESCRIPTION:Emeralds @ Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xXUK-1t\n\nShop: https://stza.co/+xXUK-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Canadians
<2018-07-31 Tue 21:05>--<2018-08-01 Wed 00:05>
:PROPERTIES:
:ID:       KOvw_Gp-5oWsJCsPcZVZ2Hjg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds @ Canadians Emeralds @ Canadians

Follow on MiLB First Pitch  https //stza.co/+xXUL-V

Shop  https //stza.co/+xXUL-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Canadians
END:VALARM
DTSTART:20180801T020500Z
DTEND:20180801T050500Z
UID:KOvw_Gp-5oWsJCsPcZVZ2Hjg@stanza.co
SUMMARY:Emeralds @ Canadians
DESCRIPTION:Emeralds @ Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xXUL-V\n\nShop: https://stza.co/+xXUL-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. Indians
<2018-08-01 Wed 21:05>--<2018-08-02 Thu 00:05>
:PROPERTIES:
:ID:       2R_-LbpsW8EE3s2tKGM3B8Qx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Indians Emeralds vs. Indians

Follow on MiLB First Pitch  https //stza.co/+xWOK-1Q

Shop  https //stza.co/+xWOK-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Indians
END:VALARM
DTSTART:20180802T020500Z
DTEND:20180802T050500Z
UID:2R_-LbpsW8EE3s2tKGM3B8Qx@stanza.co
SUMMARY:Emeralds vs. Indians
DESCRIPTION:Emeralds vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xWOK-1Q\n\nShop: https://stza.co/+xWOK-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. Indians
<2018-08-02 Thu 21:05>--<2018-08-03 Fri 00:05>
:PROPERTIES:
:ID:       C2323JlmmEel9MWn3FP9d8OK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Indians Emeralds vs. Indians

Follow on MiLB First Pitch  https //stza.co/+xWOL-2

Shop  https //stza.co/+xWOL-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Indians
END:VALARM
DTSTART:20180803T020500Z
DTEND:20180803T050500Z
UID:C2323JlmmEel9MWn3FP9d8OK@stanza.co
SUMMARY:Emeralds vs. Indians
DESCRIPTION:Emeralds vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xWOL-2\n\nShop: https://stza.co/+xWOL-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. Indians
<2018-08-03 Fri 21:05>--<2018-08-04 Sat 00:05>
:PROPERTIES:
:ID:       IONnQzrgA9KKIE-aPFNGSen4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Indians Emeralds vs. Indians

Follow on MiLB First Pitch  https //stza.co/+xWON-1l

Shop  https //stza.co/+xWON-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Indians
END:VALARM
DTSTART:20180804T020500Z
DTEND:20180804T050500Z
UID:IONnQzrgA9KKIE-aPFNGSen4@stanza.co
SUMMARY:Emeralds vs. Indians
DESCRIPTION:Emeralds vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xWON-1l\n\nShop: https://stza.co/+xWON-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. Indians
<2018-08-04 Sat 21:05>--<2018-08-05 Sun 00:05>
:PROPERTIES:
:ID:       kDGDtZlMojbB43QwZcnl3ExU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Indians Emeralds vs. Indians

Follow on MiLB First Pitch  https //stza.co/+xWOP-3R

Shop  https //stza.co/+xWOP-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Indians
END:VALARM
DTSTART:20180805T020500Z
DTEND:20180805T050500Z
UID:kDGDtZlMojbB43QwZcnl3ExU@stanza.co
SUMMARY:Emeralds vs. Indians
DESCRIPTION:Emeralds vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xWOP-3R\n\nShop: https://stza.co/+xWOP-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. Indians
<2018-08-05 Sun 19:05-22:05>
:PROPERTIES:
:ID:       QjC6GmdfxEK6QuDgprvpo-vg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Indians Emeralds vs. Indians

Follow on MiLB First Pitch  https //stza.co/+xWOS-4

Shop  https //stza.co/+xWOS-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Indians
END:VALARM
DTSTART:20180806T000500Z
DTEND:20180806T030500Z
UID:QjC6GmdfxEK6QuDgprvpo-vg@stanza.co
SUMMARY:Emeralds vs. Indians
DESCRIPTION:Emeralds vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xWOS-4\n\nShop: https://stza.co/+xWOS-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ AquaSox
<2018-08-09 Thu 21:05>--<2018-08-10 Fri 00:05>
:PROPERTIES:
:ID:       RDovG8iOULDBYWdR1rEGz68d@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds @ AquaSox Emeralds @ AquaSox

Follow on MiLB First Pitch  https //stza.co/+vO6U-2$

Shop  https //stza.co/+vO6U-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ AquaSox
END:VALARM
DTSTART:20180810T020500Z
DTEND:20180810T050500Z
UID:RDovG8iOULDBYWdR1rEGz68d@stanza.co
SUMMARY:Emeralds @ AquaSox
DESCRIPTION:Emeralds @ AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vO6U-2$\n\nShop: https://stza.co/+vO6U-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ AquaSox
<2018-08-10 Fri 21:05>--<2018-08-11 Sat 00:05>
:PROPERTIES:
:ID:       SXrGWNcyspru_c8LaY66A7bz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Emeralds @ AquaSox Emeralds @ AquaSox

Follow on MiLB First Pitch  https //stza.co/+vO6V-1b

Shop  https //stza.co/+vO6V-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ AquaSox
END:VALARM
DTSTART:20180811T020500Z
DTEND:20180811T050500Z
UID:SXrGWNcyspru_c8LaY66A7bz@stanza.co
SUMMARY:Emeralds @ AquaSox
DESCRIPTION:Emeralds @ AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vO6V-1b\n\nShop: https://stza.co/+vO6V-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ AquaSox
<2018-08-11 Sat 21:05>--<2018-08-12 Sun 00:05>
:PROPERTIES:
:ID:       GgrEcAl4bDevWTYk_N2ZlKLe@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds @ AquaSox Emeralds @ AquaSox

Follow on MiLB First Pitch  https //stza.co/+vO6W-3k

Shop  https //stza.co/+vO6W-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ AquaSox
END:VALARM
DTSTART:20180812T020500Z
DTEND:20180812T050500Z
UID:GgrEcAl4bDevWTYk_N2ZlKLe@stanza.co
SUMMARY:Emeralds @ AquaSox
DESCRIPTION:Emeralds @ AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vO6W-3k\n\nShop: https://stza.co/+vO6W-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ AquaSox
<2018-08-12 Sun 18:05-21:05>
:PROPERTIES:
:ID:       9fOy95Ll0YT-O_je0O4F3FvK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds @ AquaSox Emeralds @ AquaSox

Follow on MiLB First Pitch  https //stza.co/+vO6X-2W

Shop  https //stza.co/+vO6X-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ AquaSox
END:VALARM
DTSTART:20180812T230500Z
DTEND:20180813T020500Z
UID:9fOy95Ll0YT-O_je0O4F3FvK@stanza.co
SUMMARY:Emeralds @ AquaSox
DESCRIPTION:Emeralds @ AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vO6X-2W\n\nShop: https://stza.co/+vO6X-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ AquaSox
<2018-08-13 Mon 21:05>--<2018-08-14 Tue 00:05>
:PROPERTIES:
:ID:       k5MDy01GFslMhFmPIQmhXO7A@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Emeralds @ AquaSox Emeralds @ AquaSox

Follow on MiLB First Pitch  https //stza.co/+vO6Y-1V

Shop  https //stza.co/+vO6Y-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ AquaSox
END:VALARM
DTSTART:20180814T020500Z
DTEND:20180814T050500Z
UID:k5MDy01GFslMhFmPIQmhXO7A@stanza.co
SUMMARY:Emeralds @ AquaSox
DESCRIPTION:Emeralds @ AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vO6Y-1V\n\nShop: https://stza.co/+vO6Y-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. Hops
<2018-08-14 Tue 21:05>--<2018-08-15 Wed 00:05>
:PROPERTIES:
:ID:       3JjekAQ1uFqnwwRfUOhEFL0I@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Hops Emeralds vs. Hops

Follow on MiLB First Pitch  https //stza.co/+xWOU-17

Shop  https //stza.co/+xWOU-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Hops
END:VALARM
DTSTART:20180815T020500Z
DTEND:20180815T050500Z
UID:3JjekAQ1uFqnwwRfUOhEFL0I@stanza.co
SUMMARY:Emeralds vs. Hops
DESCRIPTION:Emeralds vs. Hops\n\nFollow on MiLB First Pitch: https://stza.co/+xWOU-17\n\nShop: https://stza.co/+xWOU-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. Hops
<2018-08-15 Wed 21:05>--<2018-08-16 Thu 00:05>
:PROPERTIES:
:ID:       zlonhsLVERA2eGisnFPhXcPh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Hops Emeralds vs. Hops

Follow on MiLB First Pitch  https //stza.co/+xWOW-12

Shop  https //stza.co/+xWOW-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Hops
END:VALARM
DTSTART:20180816T020500Z
DTEND:20180816T050500Z
UID:zlonhsLVERA2eGisnFPhXcPh@stanza.co
SUMMARY:Emeralds vs. Hops
DESCRIPTION:Emeralds vs. Hops\n\nFollow on MiLB First Pitch: https://stza.co/+xWOW-12\n\nShop: https://stza.co/+xWOW-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. Hops
<2018-08-16 Thu 21:05>--<2018-08-17 Fri 00:05>
:PROPERTIES:
:ID:       3bgrG4n7VZZ1X5rI9vLVlcTI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Hops Emeralds vs. Hops

Follow on MiLB First Pitch  https //stza.co/+xWOX-23

Shop  https //stza.co/+xWOX-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Hops
END:VALARM
DTSTART:20180817T020500Z
DTEND:20180817T050500Z
UID:3bgrG4n7VZZ1X5rI9vLVlcTI@stanza.co
SUMMARY:Emeralds vs. Hops
DESCRIPTION:Emeralds vs. Hops\n\nFollow on MiLB First Pitch: https://stza.co/+xWOX-23\n\nShop: https://stza.co/+xWOX-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. Hawks
<2018-08-17 Fri 21:05>--<2018-08-18 Sat 00:05>
:PROPERTIES:
:ID:       F74sYsYh5QyV9ycrjAFPA-mB@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Hawks Emeralds vs. Hawks

Follow on MiLB First Pitch  https //stza.co/+xWO_-n

Shop  https //stza.co/+xWO_-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Hawks
END:VALARM
DTSTART:20180818T020500Z
DTEND:20180818T050500Z
UID:F74sYsYh5QyV9ycrjAFPA-mB@stanza.co
SUMMARY:Emeralds vs. Hawks
DESCRIPTION:Emeralds vs. Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xWO_-n\n\nShop: https://stza.co/+xWO_-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. Hawks
<2018-08-18 Sat 21:05>--<2018-08-19 Sun 00:05>
:PROPERTIES:
:ID:       QntowRbK5ex_CnGPbX9gOLV-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Hawks Emeralds vs. Hawks

Follow on MiLB First Pitch  https //stza.co/+xWP0-f

Shop  https //stza.co/+xWP0-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Hawks
END:VALARM
DTSTART:20180819T020500Z
DTEND:20180819T050500Z
UID:QntowRbK5ex_CnGPbX9gOLV-@stanza.co
SUMMARY:Emeralds vs. Hawks
DESCRIPTION:Emeralds vs. Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xWP0-f\n\nShop: https://stza.co/+xWP0-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. Hawks
<2018-08-19 Sun 19:05-22:05>
:PROPERTIES:
:ID:       TyWHH3tjMzilgFZ9YJJw-qad@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Hawks Emeralds vs. Hawks

Follow on MiLB First Pitch  https //stza.co/+xWP2-N

Shop  https //stza.co/+xWP2-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Hawks
END:VALARM
DTSTART:20180820T000500Z
DTEND:20180820T030500Z
UID:TyWHH3tjMzilgFZ9YJJw-qad@stanza.co
SUMMARY:Emeralds vs. Hawks
DESCRIPTION:Emeralds vs. Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xWP2-N\n\nShop: https://stza.co/+xWP2-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Hops
<2018-08-20 Mon 21:05>--<2018-08-21 Tue 00:05>
:PROPERTIES:
:ID:       akQyO5J-d5ZkhO5gph2EfBsw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds @ Hops Emeralds @ Hops

Follow on MiLB First Pitch  https //stza.co/+vO70-1

Shop  https //stza.co/+vO70-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Hops
END:VALARM
DTSTART:20180821T020500Z
DTEND:20180821T050500Z
UID:akQyO5J-d5ZkhO5gph2EfBsw@stanza.co
SUMMARY:Emeralds @ Hops
DESCRIPTION:Emeralds @ Hops\n\nFollow on MiLB First Pitch: https://stza.co/+vO70-1\n\nShop: https://stza.co/+vO70-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Hops
<2018-08-21 Tue 21:05>--<2018-08-22 Wed 00:05>
:PROPERTIES:
:ID:       UPqz09MsOQ4BBa9r75HxLLQt@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds @ Hops Emeralds @ Hops

Follow on MiLB First Pitch  https //stza.co/+vO71-3r

Shop  https //stza.co/+vO71-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Hops
END:VALARM
DTSTART:20180822T020500Z
DTEND:20180822T050500Z
UID:UPqz09MsOQ4BBa9r75HxLLQt@stanza.co
SUMMARY:Emeralds @ Hops
DESCRIPTION:Emeralds @ Hops\n\nFollow on MiLB First Pitch: https://stza.co/+vO71-3r\n\nShop: https://stza.co/+vO71-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Hops
<2018-08-22 Wed 21:05>--<2018-08-23 Thu 00:05>
:PROPERTIES:
:ID:       iDn15s4CxmmbWvhfD0cWkPgv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Emeralds @ Hops Emeralds @ Hops

Follow on MiLB First Pitch  https //stza.co/+vO72-2t

Shop  https //stza.co/+vO72-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Hops
END:VALARM
DTSTART:20180823T020500Z
DTEND:20180823T050500Z
UID:iDn15s4CxmmbWvhfD0cWkPgv@stanza.co
SUMMARY:Emeralds @ Hops
DESCRIPTION:Emeralds @ Hops\n\nFollow on MiLB First Pitch: https://stza.co/+vO72-2t\n\nShop: https://stza.co/+vO72-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. Dust Devils
<2018-08-23 Thu 21:05>--<2018-08-24 Fri 00:05>
:PROPERTIES:
:ID:       3FG71DGcBeKq4b-qmOwtazA1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Dust Devils Emeralds vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+xWP3-V

Shop  https //stza.co/+xWP3-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Dust Devils
END:VALARM
DTSTART:20180824T020500Z
DTEND:20180824T050500Z
UID:3FG71DGcBeKq4b-qmOwtazA1@stanza.co
SUMMARY:Emeralds vs. Dust Devils
DESCRIPTION:Emeralds vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+xWP3-V\n\nShop: https://stza.co/+xWP3-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. Dust Devils
<2018-08-24 Fri 21:05>--<2018-08-25 Sat 00:05>
:PROPERTIES:
:ID:       Ujfa3bv9pBAMx93dxyjcM9Ot@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Dust Devils Emeralds vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+xWP6-34

Shop  https //stza.co/+xWP6-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Dust Devils
END:VALARM
DTSTART:20180825T020500Z
DTEND:20180825T050500Z
UID:Ujfa3bv9pBAMx93dxyjcM9Ot@stanza.co
SUMMARY:Emeralds vs. Dust Devils
DESCRIPTION:Emeralds vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+xWP6-34\n\nShop: https://stza.co/+xWP6-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. Dust Devils
<2018-08-25 Sat 21:05>--<2018-08-26 Sun 00:05>
:PROPERTIES:
:ID:       rbAQ0YPpO4AL2siN55R4R8fo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Dust Devils Emeralds vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+xWP8-Z

Shop  https //stza.co/+xWP8-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Dust Devils
END:VALARM
DTSTART:20180826T020500Z
DTEND:20180826T050500Z
UID:rbAQ0YPpO4AL2siN55R4R8fo@stanza.co
SUMMARY:Emeralds vs. Dust Devils
DESCRIPTION:Emeralds vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+xWP8-Z\n\nShop: https://stza.co/+xWP8-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. Dust Devils
<2018-08-26 Sun 19:05-22:05>
:PROPERTIES:
:ID:       UqV7lIFoSltpqlogWOl5tv3H@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Dust Devils Emeralds vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+xWPa-22

Shop  https //stza.co/+xWPa-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Dust Devils
END:VALARM
DTSTART:20180827T000500Z
DTEND:20180827T030500Z
UID:UqV7lIFoSltpqlogWOl5tv3H@stanza.co
SUMMARY:Emeralds vs. Dust Devils
DESCRIPTION:Emeralds vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+xWPa-22\n\nShop: https://stza.co/+xWPa-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds vs. Dust Devils
<2018-08-27 Mon 21:05>--<2018-08-28 Tue 00:05>
:PROPERTIES:
:ID:       KaM1dVoqIRDvkRUzVpj7mWdl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds vs. Dust Devils Emeralds vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+xWPc-2g

Shop  https //stza.co/+xWPc-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Emeralds vs. Dust Devils
END:VALARM
DTSTART:20180828T020500Z
DTEND:20180828T050500Z
UID:KaM1dVoqIRDvkRUzVpj7mWdl@stanza.co
SUMMARY:Emeralds vs. Dust Devils
DESCRIPTION:Emeralds vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+xWPc-2g\n\nShop: https://stza.co/+xWPc-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Volcanoes
<2018-08-29 Wed>--<2018-08-28 Tue>
:PROPERTIES:
:ID:       LDDPyw7nsQeEChLp4mvS92bc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Emeralds @ Volcanoes Emeralds @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vO76-1u

Shop  https //stza.co/+vO76-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180829
DTEND;VALUE=DATE:20180829
UID:LDDPyw7nsQeEChLp4mvS92bc@stanza.co
SUMMARY:Emeralds @ Volcanoes
DESCRIPTION:Emeralds @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vO76-1u\n\nShop: https://stza.co/+vO76-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Volcanoes
<2018-08-30 Thu>--<2018-08-29 Wed>
:PROPERTIES:
:ID:       WWGfzOelq9T02G4iLW60FE_I@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds @ Volcanoes Emeralds @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vO77-15

Shop  https //stza.co/+vO77-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180830
DTEND;VALUE=DATE:20180830
UID:WWGfzOelq9T02G4iLW60FE_I@stanza.co
SUMMARY:Emeralds @ Volcanoes
DESCRIPTION:Emeralds @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vO77-15\n\nShop: https://stza.co/+vO77-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Volcanoes
<2018-08-31 Fri>--<2018-08-30 Thu>
:PROPERTIES:
:ID:       D5z4uQF-ktPz7wSHed5mOh-F@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds @ Volcanoes Emeralds @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vO78-2Q

Shop  https //stza.co/+vO78-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180831
DTEND;VALUE=DATE:20180831
UID:D5z4uQF-ktPz7wSHed5mOh-F@stanza.co
SUMMARY:Emeralds @ Volcanoes
DESCRIPTION:Emeralds @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vO78-2Q\n\nShop: https://stza.co/+vO78-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Hawks
<2018-09-01 Sat 20:15-23:15>
:PROPERTIES:
:ID:       1hSvjp4W2gtjYX9MIV0gsxPh@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Emeralds @ Hawks Emeralds @ Hawks

Follow on MiLB First Pitch  https //stza.co/+xC6l-2Z

Shop  https //stza.co/+xC6l-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Hawks
END:VALARM
DTSTART:20180902T011500Z
DTEND:20180902T041500Z
UID:1hSvjp4W2gtjYX9MIV0gsxPh@stanza.co
SUMMARY:Emeralds @ Hawks
DESCRIPTION:Emeralds @ Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xC6l-2Z\n\nShop: https://stza.co/+xC6l-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Hawks
<2018-09-02 Sun 20:15-23:15>
:PROPERTIES:
:ID:       A95oUIIBPZPcFD4UdafRzjNt@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds @ Hawks Emeralds @ Hawks

Follow on MiLB First Pitch  https //stza.co/+xC6m-g

Shop  https //stza.co/+xC6m-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Hawks
END:VALARM
DTSTART:20180903T011500Z
DTEND:20180903T041500Z
UID:A95oUIIBPZPcFD4UdafRzjNt@stanza.co
SUMMARY:Emeralds @ Hawks
DESCRIPTION:Emeralds @ Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xC6m-g\n\nShop: https://stza.co/+xC6m-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* Emeralds @ Hawks
<2018-09-03 Mon 18:15-21:15>
:PROPERTIES:
:ID:       SjmNUtyVL6m4jPEC36GwnM2G@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Emeralds @ Hawks Emeralds @ Hawks

Follow on MiLB First Pitch  https //stza.co/+xC6p-3S

Shop  https //stza.co/+xC6p-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Emeralds @ Hawks
END:VALARM
DTSTART:20180903T231500Z
DTEND:20180904T021500Z
UID:SjmNUtyVL6m4jPEC36GwnM2G@stanza.co
SUMMARY:Emeralds @ Hawks
DESCRIPTION:Emeralds @ Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xC6p-3S\n\nShop: https://stza.co/+xC6p-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
