#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Keys @ Pelicans
<2018-04-05 Thu>--<2018-04-04 Wed>
:PROPERTIES:
:ID:       Dbl7LWwU92MxElKUW2Yn2MRX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Pelicans Keys @ Pelicans

Follow on MiLB First Pitch  https //stza.co/+w0to-1H

Shop  https //stza.co/+w0to-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Pelicans
END:VALARM
DTSTART;VALUE=DATE:20180405
DTEND;VALUE=DATE:20180405
UID:Dbl7LWwU92MxElKUW2Yn2MRX@stanza.co
SUMMARY:Keys @ Pelicans
DESCRIPTION:Keys @ Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+w0to-1H\n\nShop: https://stza.co/+w0to-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Pelicans
<2018-04-06 Fri>--<2018-04-05 Thu>
:PROPERTIES:
:ID:       e1mrysB0cf6G9INj2_MtyCi6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys @ Pelicans Keys @ Pelicans

Follow on MiLB First Pitch  https //stza.co/+w0tp-f

Shop  https //stza.co/+w0tp-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Pelicans
END:VALARM
DTSTART;VALUE=DATE:20180406
DTEND;VALUE=DATE:20180406
UID:e1mrysB0cf6G9INj2_MtyCi6@stanza.co
SUMMARY:Keys @ Pelicans
DESCRIPTION:Keys @ Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+w0tp-f\n\nShop: https://stza.co/+w0tp-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Pelicans
<2018-04-07 Sat>--<2018-04-06 Fri>
:PROPERTIES:
:ID:       d8TE7OkBzwp2TW6Ef30c-wsx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Pelicans Keys @ Pelicans

Follow on MiLB First Pitch  https //stza.co/+w0tq-3D

Shop  https //stza.co/+w0tq-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Pelicans
END:VALARM
DTSTART;VALUE=DATE:20180407
DTEND;VALUE=DATE:20180407
UID:d8TE7OkBzwp2TW6Ef30c-wsx@stanza.co
SUMMARY:Keys @ Pelicans
DESCRIPTION:Keys @ Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+w0tq-3D\n\nShop: https://stza.co/+w0tq-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Pelicans
<2018-04-08 Sun>--<2018-04-07 Sat>
:PROPERTIES:
:ID:       tXammGvhkUVlPwHsRP4dNM4B@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Pelicans Keys @ Pelicans

Follow on MiLB First Pitch  https //stza.co/+w0tr-2E

Shop  https //stza.co/+w0tr-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Pelicans
END:VALARM
DTSTART;VALUE=DATE:20180408
DTEND;VALUE=DATE:20180408
UID:tXammGvhkUVlPwHsRP4dNM4B@stanza.co
SUMMARY:Keys @ Pelicans
DESCRIPTION:Keys @ Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+w0tr-2E\n\nShop: https://stza.co/+w0tr-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Mudcats
<2018-04-09 Mon 18:00-21:00>
:PROPERTIES:
:ID:       CMPmkBpoqJG3sNLRHvgGjzCe@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys @ Mudcats Keys @ Mudcats

Buy tickets here  https //stza.co/~w0qQ

Follow on MiLB First Pitch  https //stza.co/+w0qQ-2U

Shop  https //stza.co/+w0qQ-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Mudcats
END:VALARM
DTSTART:20180409T230000Z
DTEND:20180410T020000Z
UID:CMPmkBpoqJG3sNLRHvgGjzCe@stanza.co
SUMMARY:Keys @ Mudcats
DESCRIPTION:Keys @ Mudcats\n\nBuy tickets here: https://stza.co/~w0qQ\n\nFollow on MiLB First Pitch: https://stza.co/+w0qQ-2U\n\nShop: https://stza.co/+w0qQ-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Mudcats
<2018-04-10 Tue 18:00-21:00>
:PROPERTIES:
:ID:       0crb92tehMxEzhhXHmywirPh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Mudcats Keys @ Mudcats

Buy tickets here  https //stza.co/~w0qR

Follow on MiLB First Pitch  https //stza.co/+w0qR-2q

Shop  https //stza.co/+w0qR-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Mudcats
END:VALARM
DTSTART:20180410T230000Z
DTEND:20180411T020000Z
UID:0crb92tehMxEzhhXHmywirPh@stanza.co
SUMMARY:Keys @ Mudcats
DESCRIPTION:Keys @ Mudcats\n\nBuy tickets here: https://stza.co/~w0qR\n\nFollow on MiLB First Pitch: https://stza.co/+w0qR-2q\n\nShop: https://stza.co/+w0qR-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Mudcats
<2018-04-11 Wed 10:00-13:00>
:PROPERTIES:
:ID:       uIwe3T6kXczjIcTSwJohrASY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Mudcats Keys @ Mudcats

Buy tickets here  https //stza.co/~w0qS

Follow on MiLB First Pitch  https //stza.co/+w0qS-3c

Shop  https //stza.co/+w0qS-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Mudcats
END:VALARM
DTSTART:20180411T150000Z
DTEND:20180411T180000Z
UID:uIwe3T6kXczjIcTSwJohrASY@stanza.co
SUMMARY:Keys @ Mudcats
DESCRIPTION:Keys @ Mudcats\n\nBuy tickets here: https://stza.co/~w0qS\n\nFollow on MiLB First Pitch: https://stza.co/+w0qS-3c\n\nShop: https://stza.co/+w0qS-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Nationals
<2018-04-12 Thu 18:00-21:00>
:PROPERTIES:
:ID:       TM7TyYkjuA6i_Eh8YpqVktnn@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys vs. Nationals Keys vs. Nationals

Follow on MiLB First Pitch  https //stza.co/+wi7g-1D

Shop  https //stza.co/+wi7g-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Nationals
END:VALARM
DTSTART:20180412T230000Z
DTEND:20180413T020000Z
UID:TM7TyYkjuA6i_Eh8YpqVktnn@stanza.co
SUMMARY:Keys vs. Nationals
DESCRIPTION:Keys vs. Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+wi7g-1D\n\nShop: https://stza.co/+wi7g-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Nationals
<2018-04-13 Fri 18:00-21:00>
:PROPERTIES:
:ID:       jtU-_WcGLWW86e-CDx7sryzr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Nationals Keys vs. Nationals

Follow on MiLB First Pitch  https //stza.co/+wi7i-E

Shop  https //stza.co/+wi7i-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Nationals
END:VALARM
DTSTART:20180413T230000Z
DTEND:20180414T020000Z
UID:jtU-_WcGLWW86e-CDx7sryzr@stanza.co
SUMMARY:Keys vs. Nationals
DESCRIPTION:Keys vs. Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+wi7i-E\n\nShop: https://stza.co/+wi7i-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Nationals
<2018-04-14 Sat 13:00-16:00>
:PROPERTIES:
:ID:       iKMH1hJyGZsGIl9gNziSo1H3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Nationals Keys vs. Nationals

Follow on MiLB First Pitch  https //stza.co/+wi7l-1J

Shop  https //stza.co/+wi7l-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Nationals
END:VALARM
DTSTART:20180414T180000Z
DTEND:20180414T210000Z
UID:iKMH1hJyGZsGIl9gNziSo1H3@stanza.co
SUMMARY:Keys vs. Nationals
DESCRIPTION:Keys vs. Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+wi7l-1J\n\nShop: https://stza.co/+wi7l-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Nationals
<2018-04-15 Sun 13:00-16:00>
:PROPERTIES:
:ID:       5ZdGFQ_cA-RWvkFfHBJ8uRNJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys vs. Nationals Keys vs. Nationals

Follow on MiLB First Pitch  https //stza.co/+wi7n-32

Shop  https //stza.co/+wi7n-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Nationals
END:VALARM
DTSTART:20180415T180000Z
DTEND:20180415T210000Z
UID:5ZdGFQ_cA-RWvkFfHBJ8uRNJ@stanza.co
SUMMARY:Keys vs. Nationals
DESCRIPTION:Keys vs. Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+wi7n-32\n\nShop: https://stza.co/+wi7n-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Hillcats
<2018-04-16 Mon 17:30-20:30>
:PROPERTIES:
:ID:       adOedX-p6_xi0Eh13K2MA1rQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Hillcats Keys @ Hillcats

Buy tickets here  https //stza.co/~y3Tu

Follow on MiLB First Pitch  https //stza.co/+y3Tu-2_

Shop  https //stza.co/+y3Tu-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Hillcats
END:VALARM
DTSTART:20180416T223000Z
DTEND:20180417T013000Z
UID:adOedX-p6_xi0Eh13K2MA1rQ@stanza.co
SUMMARY:Keys @ Hillcats
DESCRIPTION:Keys @ Hillcats\n\nBuy tickets here: https://stza.co/~y3Tu\n\nFollow on MiLB First Pitch: https://stza.co/+y3Tu-2_\n\nShop: https://stza.co/+y3Tu-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Hillcats
<2018-04-17 Tue 17:30-20:30>
:PROPERTIES:
:ID:       hYrsJbXV4nCBGsMd0C6alZmc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Hillcats Keys @ Hillcats

Buy tickets here  https //stza.co/~y3Tv

Follow on MiLB First Pitch  https //stza.co/+y3Tv-2K

Shop  https //stza.co/+y3Tv-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Hillcats
END:VALARM
DTSTART:20180417T223000Z
DTEND:20180418T013000Z
UID:hYrsJbXV4nCBGsMd0C6alZmc@stanza.co
SUMMARY:Keys @ Hillcats
DESCRIPTION:Keys @ Hillcats\n\nBuy tickets here: https://stza.co/~y3Tv\n\nFollow on MiLB First Pitch: https://stza.co/+y3Tv-2K\n\nShop: https://stza.co/+y3Tv-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Hillcats
<2018-04-18 Wed 10:00-13:00>
:PROPERTIES:
:ID:       eG6kQKVexXM8RkcpvVgloiYj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys @ Hillcats Keys @ Hillcats

Buy tickets here  https //stza.co/~y3Tw

Follow on MiLB First Pitch  https //stza.co/+y3Tw-F

Shop  https //stza.co/+y3Tw-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Hillcats
END:VALARM
DTSTART:20180418T150000Z
DTEND:20180418T180000Z
UID:eG6kQKVexXM8RkcpvVgloiYj@stanza.co
SUMMARY:Keys @ Hillcats
DESCRIPTION:Keys @ Hillcats\n\nBuy tickets here: https://stza.co/~y3Tw\n\nFollow on MiLB First Pitch: https://stza.co/+y3Tw-F\n\nShop: https://stza.co/+y3Tw-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Blue Rocks
<2018-04-19 Thu 18:00-21:00>
:PROPERTIES:
:ID:       NQr0wl6hRsW7Oi_cFJoWaIxj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Blue Rocks Keys vs. Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+wi7q-1z

Shop  https //stza.co/+wi7q-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Blue Rocks
END:VALARM
DTSTART:20180419T230000Z
DTEND:20180420T020000Z
UID:NQr0wl6hRsW7Oi_cFJoWaIxj@stanza.co
SUMMARY:Keys vs. Blue Rocks
DESCRIPTION:Keys vs. Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+wi7q-1z\n\nShop: https://stza.co/+wi7q-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Blue Rocks
<2018-04-20 Fri 18:00-21:00>
:PROPERTIES:
:ID:       jwrAIMD_ck5l0Iu69v7dxeZs@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Blue Rocks Keys vs. Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+wi7t-d

Shop  https //stza.co/+wi7t-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Blue Rocks
END:VALARM
DTSTART:20180420T230000Z
DTEND:20180421T020000Z
UID:jwrAIMD_ck5l0Iu69v7dxeZs@stanza.co
SUMMARY:Keys vs. Blue Rocks
DESCRIPTION:Keys vs. Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+wi7t-d\n\nShop: https://stza.co/+wi7t-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Blue Rocks
<2018-04-21 Sat 13:00-16:00>
:PROPERTIES:
:ID:       C_-32EwsHdxNNJX-M3Fv4Plt@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys vs. Blue Rocks Keys vs. Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+wi7u-3_

Shop  https //stza.co/+wi7u-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Blue Rocks
END:VALARM
DTSTART:20180421T180000Z
DTEND:20180421T210000Z
UID:C_-32EwsHdxNNJX-M3Fv4Plt@stanza.co
SUMMARY:Keys vs. Blue Rocks
DESCRIPTION:Keys vs. Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+wi7u-3_\n\nShop: https://stza.co/+wi7u-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Blue Rocks
<2018-04-22 Sun 13:00-16:00>
:PROPERTIES:
:ID:       u2OCRJSDWV2nWOaDCw0El3YU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Blue Rocks Keys vs. Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+wi7w-l

Shop  https //stza.co/+wi7w-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Blue Rocks
END:VALARM
DTSTART:20180422T180000Z
DTEND:20180422T210000Z
UID:u2OCRJSDWV2nWOaDCw0El3YU@stanza.co
SUMMARY:Keys vs. Blue Rocks
DESCRIPTION:Keys vs. Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+wi7w-l\n\nShop: https://stza.co/+wi7w-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Red Sox
<2018-04-24 Tue>--<2018-04-23 Mon>
:PROPERTIES:
:ID:       Km4xfeD0gLlj0WBm4O4yYbmk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Red Sox Keys @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0tG-y

Shop  https //stza.co/+w0tG-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180424
DTEND;VALUE=DATE:20180424
UID:Km4xfeD0gLlj0WBm4O4yYbmk@stanza.co
SUMMARY:Keys @ Red Sox
DESCRIPTION:Keys @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0tG-y\n\nShop: https://stza.co/+w0tG-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Red Sox
<2018-04-25 Wed>--<2018-04-24 Tue>
:PROPERTIES:
:ID:       2nJ9kf4k2EepFV-hSK76_TJc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys @ Red Sox Keys @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0tH-1c

Shop  https //stza.co/+w0tH-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180425
DTEND;VALUE=DATE:20180425
UID:2nJ9kf4k2EepFV-hSK76_TJc@stanza.co
SUMMARY:Keys @ Red Sox
DESCRIPTION:Keys @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0tH-1c\n\nShop: https://stza.co/+w0tH-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Red Sox
<2018-04-26 Thu>--<2018-04-25 Wed>
:PROPERTIES:
:ID:       QO7I_rQ7a24t0ek8em3sZxBF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Red Sox Keys @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0tI-l

Shop  https //stza.co/+w0tI-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180426
DTEND;VALUE=DATE:20180426
UID:QO7I_rQ7a24t0ek8em3sZxBF@stanza.co
SUMMARY:Keys @ Red Sox
DESCRIPTION:Keys @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0tI-l\n\nShop: https://stza.co/+w0tI-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Astros
<2018-04-27 Fri 18:00-21:00>
:PROPERTIES:
:ID:       A0dDCkjG8m_qDqeBsPuMGAIs@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Astros Keys @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM95-B

Shop  https //stza.co/+xM95-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Astros
END:VALARM
DTSTART:20180427T230000Z
DTEND:20180428T020000Z
UID:A0dDCkjG8m_qDqeBsPuMGAIs@stanza.co
SUMMARY:Keys @ Astros
DESCRIPTION:Keys @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM95-B\n\nShop: https://stza.co/+xM95-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Astros
<2018-04-28 Sat 17:00-20:00>
:PROPERTIES:
:ID:       L16eXeFPjqIDuaLhDbuiaM6B@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys @ Astros Keys @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM96-1l

Shop  https //stza.co/+xM96-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Astros
END:VALARM
DTSTART:20180428T220000Z
DTEND:20180429T010000Z
UID:L16eXeFPjqIDuaLhDbuiaM6B@stanza.co
SUMMARY:Keys @ Astros
DESCRIPTION:Keys @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM96-1l\n\nShop: https://stza.co/+xM96-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Astros
<2018-04-29 Sun 13:00-16:00>
:PROPERTIES:
:ID:       FH6mQK9wq9jqczBjUxFZIMao@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Astros Keys @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM97-F

Shop  https //stza.co/+xM97-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Astros
END:VALARM
DTSTART:20180429T180000Z
DTEND:20180429T210000Z
UID:FH6mQK9wq9jqczBjUxFZIMao@stanza.co
SUMMARY:Keys @ Astros
DESCRIPTION:Keys @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM97-F\n\nShop: https://stza.co/+xM97-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Red Sox
<2018-05-01 Tue 18:00-21:00>
:PROPERTIES:
:ID:       fl3dqhBdYXV8Y1r3PifiTZdf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Red Sox Keys vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+wi7z-15

Shop  https //stza.co/+wi7z-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Red Sox
END:VALARM
DTSTART:20180501T230000Z
DTEND:20180502T020000Z
UID:fl3dqhBdYXV8Y1r3PifiTZdf@stanza.co
SUMMARY:Keys vs. Red Sox
DESCRIPTION:Keys vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wi7z-15\n\nShop: https://stza.co/+wi7z-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Red Sox
<2018-05-02 Wed 18:00-21:00>
:PROPERTIES:
:ID:       wE5fX8roRBvzGeiQVNbJJRrc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys vs. Red Sox Keys vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+wi7B-3W

Shop  https //stza.co/+wi7B-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Red Sox
END:VALARM
DTSTART:20180502T230000Z
DTEND:20180503T020000Z
UID:wE5fX8roRBvzGeiQVNbJJRrc@stanza.co
SUMMARY:Keys vs. Red Sox
DESCRIPTION:Keys vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wi7B-3W\n\nShop: https://stza.co/+wi7B-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Red Sox
<2018-05-03 Thu 10:00-13:00>
:PROPERTIES:
:ID:       UkSms3Gpcgag3Ib2LFCyn6-2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Red Sox Keys vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+wi7C-1t

Shop  https //stza.co/+wi7C-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Red Sox
END:VALARM
DTSTART:20180503T150000Z
DTEND:20180503T180000Z
UID:UkSms3Gpcgag3Ib2LFCyn6-2@stanza.co
SUMMARY:Keys vs. Red Sox
DESCRIPTION:Keys vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wi7C-1t\n\nShop: https://stza.co/+wi7C-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Blue Rocks
<2018-05-04 Fri 18:05-21:05>
:PROPERTIES:
:ID:       9Vs-hk_-fPJDpjckj57tk1PH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Blue Rocks Keys @ Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+wX8e-2g

Shop  https //stza.co/+wX8e-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Blue Rocks
END:VALARM
DTSTART:20180504T230500Z
DTEND:20180505T020500Z
UID:9Vs-hk_-fPJDpjckj57tk1PH@stanza.co
SUMMARY:Keys @ Blue Rocks
DESCRIPTION:Keys @ Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+wX8e-2g\n\nShop: https://stza.co/+wX8e-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Blue Rocks
<2018-05-05 Sat 17:05-20:05>
:PROPERTIES:
:ID:       ckjW06dVqpj21gFwLwt1ji8E@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys @ Blue Rocks Keys @ Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+wX8f-1a

Shop  https //stza.co/+wX8f-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Blue Rocks
END:VALARM
DTSTART:20180505T220500Z
DTEND:20180506T010500Z
UID:ckjW06dVqpj21gFwLwt1ji8E@stanza.co
SUMMARY:Keys @ Blue Rocks
DESCRIPTION:Keys @ Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+wX8f-1a\n\nShop: https://stza.co/+wX8f-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Blue Rocks
<2018-05-06 Sun 12:35-15:35>
:PROPERTIES:
:ID:       Oar2HJVn7o2DimnW03fUEwwA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Blue Rocks Keys @ Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+wX8g-2v

Shop  https //stza.co/+wX8g-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Blue Rocks
END:VALARM
DTSTART:20180506T173500Z
DTEND:20180506T203500Z
UID:Oar2HJVn7o2DimnW03fUEwwA@stanza.co
SUMMARY:Keys @ Blue Rocks
DESCRIPTION:Keys @ Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+wX8g-2v\n\nShop: https://stza.co/+wX8g-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Hillcats
<2018-05-07 Mon 18:00-21:00>
:PROPERTIES:
:ID:       SQVm-QjwsT9Qt7p7fXaq-xp9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Hillcats Keys vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+wi7E-1_

Shop  https //stza.co/+wi7E-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Hillcats
END:VALARM
DTSTART:20180507T230000Z
DTEND:20180508T020000Z
UID:SQVm-QjwsT9Qt7p7fXaq-xp9@stanza.co
SUMMARY:Keys vs. Hillcats
DESCRIPTION:Keys vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+wi7E-1_\n\nShop: https://stza.co/+wi7E-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Hillcats
<2018-05-08 Tue 18:00-21:00>
:PROPERTIES:
:ID:       zVtkqjyAvRsB25Ck8jRxq__d@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys vs. Hillcats Keys vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+wi7G-u

Shop  https //stza.co/+wi7G-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Hillcats
END:VALARM
DTSTART:20180508T230000Z
DTEND:20180509T020000Z
UID:zVtkqjyAvRsB25Ck8jRxq__d@stanza.co
SUMMARY:Keys vs. Hillcats
DESCRIPTION:Keys vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+wi7G-u\n\nShop: https://stza.co/+wi7G-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Hillcats
<2018-05-09 Wed 10:00-13:00>
:PROPERTIES:
:ID:       Y0OGmB-IFSYYmfSG4f0T61Vu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Hillcats Keys vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+wi7I-K

Shop  https //stza.co/+wi7I-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Hillcats
END:VALARM
DTSTART:20180509T150000Z
DTEND:20180509T180000Z
UID:Y0OGmB-IFSYYmfSG4f0T61Vu@stanza.co
SUMMARY:Keys vs. Hillcats
DESCRIPTION:Keys vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+wi7I-K\n\nShop: https://stza.co/+wi7I-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Nationals
<2018-05-10 Thu 18:00-21:00>
:PROPERTIES:
:ID:       zwFyZUbeVJXBQW8Y13Rv216G@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Nationals Keys vs. Nationals

Follow on MiLB First Pitch  https //stza.co/+wi7L-1

Shop  https //stza.co/+wi7L-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Nationals
END:VALARM
DTSTART:20180510T230000Z
DTEND:20180511T020000Z
UID:zwFyZUbeVJXBQW8Y13Rv216G@stanza.co
SUMMARY:Keys vs. Nationals
DESCRIPTION:Keys vs. Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+wi7L-1\n\nShop: https://stza.co/+wi7L-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Nationals
<2018-05-11 Fri 18:00-21:00>
:PROPERTIES:
:ID:       OF4t2lHt4beLgeg2Mtoz1DBf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys vs. Nationals Keys vs. Nationals

Follow on MiLB First Pitch  https //stza.co/+wi7N-d

Shop  https //stza.co/+wi7N-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Nationals
END:VALARM
DTSTART:20180511T230000Z
DTEND:20180512T020000Z
UID:OF4t2lHt4beLgeg2Mtoz1DBf@stanza.co
SUMMARY:Keys vs. Nationals
DESCRIPTION:Keys vs. Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+wi7N-d\n\nShop: https://stza.co/+wi7N-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Nationals
<2018-05-12 Sat 17:00-20:00>
:PROPERTIES:
:ID:       DT166khx5vbg0JWvg6eiwt-8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Nationals Keys vs. Nationals

Follow on MiLB First Pitch  https //stza.co/+wi7P-2j

Shop  https //stza.co/+wi7P-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Nationals
END:VALARM
DTSTART:20180512T220000Z
DTEND:20180513T010000Z
UID:DT166khx5vbg0JWvg6eiwt-8@stanza.co
SUMMARY:Keys vs. Nationals
DESCRIPTION:Keys vs. Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+wi7P-2j\n\nShop: https://stza.co/+wi7P-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Nationals
<2018-05-13 Sun 13:00-16:00>
:PROPERTIES:
:ID:       L0O1Ys1vZBEkCZqb3x_XhNN7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Nationals Keys vs. Nationals

Follow on MiLB First Pitch  https //stza.co/+wi7R-j

Shop  https //stza.co/+wi7R-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Nationals
END:VALARM
DTSTART:20180513T180000Z
DTEND:20180513T210000Z
UID:L0O1Ys1vZBEkCZqb3x_XhNN7@stanza.co
SUMMARY:Keys vs. Nationals
DESCRIPTION:Keys vs. Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+wi7R-j\n\nShop: https://stza.co/+wi7R-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Hillcats
<2018-05-15 Tue 17:30-20:30>
:PROPERTIES:
:ID:       qfp9o4PUqLtpGNvALGVlGOte@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys @ Hillcats Keys @ Hillcats

Buy tickets here  https //stza.co/~y3Tx

Follow on MiLB First Pitch  https //stza.co/+y3Tx-1N

Shop  https //stza.co/+y3Tx-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Hillcats
END:VALARM
DTSTART:20180515T223000Z
DTEND:20180516T013000Z
UID:qfp9o4PUqLtpGNvALGVlGOte@stanza.co
SUMMARY:Keys @ Hillcats
DESCRIPTION:Keys @ Hillcats\n\nBuy tickets here: https://stza.co/~y3Tx\n\nFollow on MiLB First Pitch: https://stza.co/+y3Tx-1N\n\nShop: https://stza.co/+y3Tx-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Hillcats
<2018-05-16 Wed 17:30-20:30>
:PROPERTIES:
:ID:       e-EeF9IsregPuhqYvN_a7K5A@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Hillcats Keys @ Hillcats

Buy tickets here  https //stza.co/~y3Ty

Follow on MiLB First Pitch  https //stza.co/+y3Ty-J

Shop  https //stza.co/+y3Ty-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Hillcats
END:VALARM
DTSTART:20180516T223000Z
DTEND:20180517T013000Z
UID:e-EeF9IsregPuhqYvN_a7K5A@stanza.co
SUMMARY:Keys @ Hillcats
DESCRIPTION:Keys @ Hillcats\n\nBuy tickets here: https://stza.co/~y3Ty\n\nFollow on MiLB First Pitch: https://stza.co/+y3Ty-J\n\nShop: https://stza.co/+y3Ty-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Hillcats
<2018-05-17 Thu 17:30-20:30>
:PROPERTIES:
:ID:       ZRQWfIfbNsVzWzjc6b5PBveN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Hillcats Keys @ Hillcats

Buy tickets here  https //stza.co/~y3Tz

Follow on MiLB First Pitch  https //stza.co/+y3Tz-12

Shop  https //stza.co/+y3Tz-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Hillcats
END:VALARM
DTSTART:20180517T223000Z
DTEND:20180518T013000Z
UID:ZRQWfIfbNsVzWzjc6b5PBveN@stanza.co
SUMMARY:Keys @ Hillcats
DESCRIPTION:Keys @ Hillcats\n\nBuy tickets here: https://stza.co/~y3Tz\n\nFollow on MiLB First Pitch: https://stza.co/+y3Tz-12\n\nShop: https://stza.co/+y3Tz-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Pelicans
<2018-05-18 Fri 18:00-21:00>
:PROPERTIES:
:ID:       DmeYcFrWGFz1YMWPbkq-45rT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys vs. Pelicans Keys vs. Pelicans

Follow on MiLB First Pitch  https //stza.co/+wi7S-2r

Shop  https //stza.co/+wi7S-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Pelicans
END:VALARM
DTSTART:20180518T230000Z
DTEND:20180519T020000Z
UID:DmeYcFrWGFz1YMWPbkq-45rT@stanza.co
SUMMARY:Keys vs. Pelicans
DESCRIPTION:Keys vs. Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+wi7S-2r\n\nShop: https://stza.co/+wi7S-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Pelicans
<2018-05-19 Sat 17:00-20:00>
:PROPERTIES:
:ID:       Hlk-J9MhQ-1r9OSUap5LhJ1j@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Pelicans Keys vs. Pelicans

Follow on MiLB First Pitch  https //stza.co/+wi7V-m

Shop  https //stza.co/+wi7V-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Pelicans
END:VALARM
DTSTART:20180519T220000Z
DTEND:20180520T010000Z
UID:Hlk-J9MhQ-1r9OSUap5LhJ1j@stanza.co
SUMMARY:Keys vs. Pelicans
DESCRIPTION:Keys vs. Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+wi7V-m\n\nShop: https://stza.co/+wi7V-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Pelicans
<2018-05-20 Sun 13:00-16:00>
:PROPERTIES:
:ID:       oJrk-Mkl-BA6YOwleV5qbZdR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Pelicans Keys vs. Pelicans

Follow on MiLB First Pitch  https //stza.co/+wi7X-2a

Shop  https //stza.co/+wi7X-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Pelicans
END:VALARM
DTSTART:20180520T180000Z
DTEND:20180520T210000Z
UID:oJrk-Mkl-BA6YOwleV5qbZdR@stanza.co
SUMMARY:Keys vs. Pelicans
DESCRIPTION:Keys vs. Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+wi7X-2a\n\nShop: https://stza.co/+wi7X-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Red Sox
<2018-05-21 Mon 18:00-21:00>
:PROPERTIES:
:ID:       P0S6jvXq6Yd5ZrHz2vVnn4gq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys vs. Red Sox Keys vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+wi7_-1t

Shop  https //stza.co/+wi7_-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Red Sox
END:VALARM
DTSTART:20180521T230000Z
DTEND:20180522T020000Z
UID:P0S6jvXq6Yd5ZrHz2vVnn4gq@stanza.co
SUMMARY:Keys vs. Red Sox
DESCRIPTION:Keys vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wi7_-1t\n\nShop: https://stza.co/+wi7_-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Red Sox
<2018-05-22 Tue 18:00-21:00>
:PROPERTIES:
:ID:       Al2EmChvzSLVAVCdzA5JGuYQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Red Sox Keys vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+wi80-1o

Shop  https //stza.co/+wi80-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Red Sox
END:VALARM
DTSTART:20180522T230000Z
DTEND:20180523T020000Z
UID:Al2EmChvzSLVAVCdzA5JGuYQ@stanza.co
SUMMARY:Keys vs. Red Sox
DESCRIPTION:Keys vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wi80-1o\n\nShop: https://stza.co/+wi80-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Red Sox
<2018-05-23 Wed 18:00-21:00>
:PROPERTIES:
:ID:       WOluOeUN74dplWKWsiNu2Gkr@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Red Sox Keys vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+wi81-3F

Shop  https //stza.co/+wi81-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Red Sox
END:VALARM
DTSTART:20180523T230000Z
DTEND:20180524T020000Z
UID:WOluOeUN74dplWKWsiNu2Gkr@stanza.co
SUMMARY:Keys vs. Red Sox
DESCRIPTION:Keys vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wi81-3F\n\nShop: https://stza.co/+wi81-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Red Sox
<2018-05-24 Thu 10:00-13:00>
:PROPERTIES:
:ID:       J8aQygvGiq70DBtl3BQMRPMW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys vs. Red Sox Keys vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+wi84-3K

Shop  https //stza.co/+wi84-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Red Sox
END:VALARM
DTSTART:20180524T150000Z
DTEND:20180524T180000Z
UID:J8aQygvGiq70DBtl3BQMRPMW@stanza.co
SUMMARY:Keys vs. Red Sox
DESCRIPTION:Keys vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wi84-3K\n\nShop: https://stza.co/+wi84-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Wood Ducks
<2018-05-25 Fri 18:00-21:00>
:PROPERTIES:
:ID:       9Jkcf4koMFqYBuCLQ3qKU66V@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Wood Ducks Keys @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0qY-1a

Shop  https //stza.co/+w0qY-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Wood Ducks
END:VALARM
DTSTART:20180525T230000Z
DTEND:20180526T020000Z
UID:9Jkcf4koMFqYBuCLQ3qKU66V@stanza.co
SUMMARY:Keys @ Wood Ducks
DESCRIPTION:Keys @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0qY-1a\n\nShop: https://stza.co/+w0qY-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Wood Ducks
<2018-05-26 Sat 17:00-20:00>
:PROPERTIES:
:ID:       W2fTA8U39sFPkZPjSLolE2Fd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Wood Ducks Keys @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0qZ-U

Shop  https //stza.co/+w0qZ-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Wood Ducks
END:VALARM
DTSTART:20180526T220000Z
DTEND:20180527T010000Z
UID:W2fTA8U39sFPkZPjSLolE2Fd@stanza.co
SUMMARY:Keys @ Wood Ducks
DESCRIPTION:Keys @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0qZ-U\n\nShop: https://stza.co/+w0qZ-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Wood Ducks
<2018-05-27 Sun 13:00-16:00>
:PROPERTIES:
:ID:       WIFpNImQhEQgfoOGRfBt1x4o@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys @ Wood Ducks Keys @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0q_-2I

Shop  https //stza.co/+w0q_-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Wood Ducks
END:VALARM
DTSTART:20180527T180000Z
DTEND:20180527T210000Z
UID:WIFpNImQhEQgfoOGRfBt1x4o@stanza.co
SUMMARY:Keys @ Wood Ducks
DESCRIPTION:Keys @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0q_-2I\n\nShop: https://stza.co/+w0q_-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Wood Ducks
<2018-05-28 Mon 15:00-18:00>
:PROPERTIES:
:ID:       c53uu-1zKpu27BovGi3KnAa9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Wood Ducks Keys @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0q$-2_

Shop  https //stza.co/+w0q$-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Wood Ducks
END:VALARM
DTSTART:20180528T200000Z
DTEND:20180528T230000Z
UID:c53uu-1zKpu27BovGi3KnAa9@stanza.co
SUMMARY:Keys @ Wood Ducks
DESCRIPTION:Keys @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0q$-2_\n\nShop: https://stza.co/+w0q$-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Blue Rocks
<2018-05-29 Tue 17:35-20:35>
:PROPERTIES:
:ID:       F3vt6Z4yLfEFV1SmpmRfAp9R@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Blue Rocks Keys @ Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+wX8h-b

Shop  https //stza.co/+wX8h-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Blue Rocks
END:VALARM
DTSTART:20180529T223500Z
DTEND:20180530T013500Z
UID:F3vt6Z4yLfEFV1SmpmRfAp9R@stanza.co
SUMMARY:Keys @ Blue Rocks
DESCRIPTION:Keys @ Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+wX8h-b\n\nShop: https://stza.co/+wX8h-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Blue Rocks
<2018-05-30 Wed 17:35-20:35>
:PROPERTIES:
:ID:       37Al5iq1sAyO7DC80fdmBn9t@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys @ Blue Rocks Keys @ Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+wX8i-2s

Shop  https //stza.co/+wX8i-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Blue Rocks
END:VALARM
DTSTART:20180530T223500Z
DTEND:20180531T013500Z
UID:37Al5iq1sAyO7DC80fdmBn9t@stanza.co
SUMMARY:Keys @ Blue Rocks
DESCRIPTION:Keys @ Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+wX8i-2s\n\nShop: https://stza.co/+wX8i-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Blue Rocks
<2018-05-31 Thu 17:35-20:35>
:PROPERTIES:
:ID:       X7kME89Bymoxl7232WtwF3X2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Blue Rocks Keys @ Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+wX8j-1f

Shop  https //stza.co/+wX8j-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Blue Rocks
END:VALARM
DTSTART:20180531T223500Z
DTEND:20180601T013500Z
UID:X7kME89Bymoxl7232WtwF3X2@stanza.co
SUMMARY:Keys @ Blue Rocks
DESCRIPTION:Keys @ Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+wX8j-1f\n\nShop: https://stza.co/+wX8j-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Hillcats
<2018-06-01 Fri 18:00-21:00>
:PROPERTIES:
:ID:       coRIfV22e_6zzGraS2JLOuhV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Hillcats Keys vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+wi86-t

Shop  https //stza.co/+wi86-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Hillcats
END:VALARM
DTSTART:20180601T230000Z
DTEND:20180602T020000Z
UID:coRIfV22e_6zzGraS2JLOuhV@stanza.co
SUMMARY:Keys vs. Hillcats
DESCRIPTION:Keys vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+wi86-t\n\nShop: https://stza.co/+wi86-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Hillcats
<2018-06-02 Sat 17:00-20:00>
:PROPERTIES:
:ID:       Dlh1XcKveUVvDKjh16t_1xFN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys vs. Hillcats Keys vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+wi87-3z

Shop  https //stza.co/+wi87-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Hillcats
END:VALARM
DTSTART:20180602T220000Z
DTEND:20180603T010000Z
UID:Dlh1XcKveUVvDKjh16t_1xFN@stanza.co
SUMMARY:Keys vs. Hillcats
DESCRIPTION:Keys vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+wi87-3z\n\nShop: https://stza.co/+wi87-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Hillcats
<2018-06-03 Sun 13:00-16:00>
:PROPERTIES:
:ID:       Ztwt0xFX69c7AtBLXUSRpsvh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Hillcats Keys vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+wi89-3l

Shop  https //stza.co/+wi89-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Hillcats
END:VALARM
DTSTART:20180603T180000Z
DTEND:20180603T210000Z
UID:Ztwt0xFX69c7AtBLXUSRpsvh@stanza.co
SUMMARY:Keys vs. Hillcats
DESCRIPTION:Keys vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+wi89-3l\n\nShop: https://stza.co/+wi89-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Nationals
<2018-06-05 Tue 18:05-21:05>
:PROPERTIES:
:ID:       PLZdmxyRvhGKgYvdM29VRyC_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Nationals Keys @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xB4K-2A

Shop  https //stza.co/+xB4K-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Nationals
END:VALARM
DTSTART:20180605T230500Z
DTEND:20180606T020500Z
UID:PLZdmxyRvhGKgYvdM29VRyC_@stanza.co
SUMMARY:Keys @ Nationals
DESCRIPTION:Keys @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xB4K-2A\n\nShop: https://stza.co/+xB4K-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Nationals
<2018-06-06 Wed 18:05-21:05>
:PROPERTIES:
:ID:       eyLVhWTI5ZmE9MFBMz96ZLvI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys @ Nationals Keys @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xA2J-3c

Shop  https //stza.co/+xA2J-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Nationals
END:VALARM
DTSTART:20180606T230500Z
DTEND:20180607T020500Z
UID:eyLVhWTI5ZmE9MFBMz96ZLvI@stanza.co
SUMMARY:Keys @ Nationals
DESCRIPTION:Keys @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xA2J-3c\n\nShop: https://stza.co/+xA2J-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Nationals
<2018-06-07 Thu 18:05-21:05>
:PROPERTIES:
:ID:       iqPRAkF7sWxkQ7Fp4RmNT5uh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Nationals Keys @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xA2K-1p

Shop  https //stza.co/+xA2K-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Nationals
END:VALARM
DTSTART:20180607T230500Z
DTEND:20180608T020500Z
UID:iqPRAkF7sWxkQ7Fp4RmNT5uh@stanza.co
SUMMARY:Keys @ Nationals
DESCRIPTION:Keys @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xA2K-1p\n\nShop: https://stza.co/+xA2K-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Blue Rocks
<2018-06-08 Fri 18:05-21:05>
:PROPERTIES:
:ID:       V11BI5CExy9ApkNGtrrczsSe@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Blue Rocks Keys @ Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+wX8k-X

Shop  https //stza.co/+wX8k-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Blue Rocks
END:VALARM
DTSTART:20180608T230500Z
DTEND:20180609T020500Z
UID:V11BI5CExy9ApkNGtrrczsSe@stanza.co
SUMMARY:Keys @ Blue Rocks
DESCRIPTION:Keys @ Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+wX8k-X\n\nShop: https://stza.co/+wX8k-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Blue Rocks
<2018-06-09 Sat 17:05-20:05>
:PROPERTIES:
:ID:       nF4cTpsySdDDo1IxQ945yMFP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys @ Blue Rocks Keys @ Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+wX8l-1M

Shop  https //stza.co/+wX8l-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Blue Rocks
END:VALARM
DTSTART:20180609T220500Z
DTEND:20180610T010500Z
UID:nF4cTpsySdDDo1IxQ945yMFP@stanza.co
SUMMARY:Keys @ Blue Rocks
DESCRIPTION:Keys @ Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+wX8l-1M\n\nShop: https://stza.co/+wX8l-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Blue Rocks
<2018-06-10 Sun 12:35-15:35>
:PROPERTIES:
:ID:       fyVbpWXZn9Y8IK-hWqzb1tGv@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Blue Rocks Keys @ Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+wX8n-9

Shop  https //stza.co/+wX8n-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Blue Rocks
END:VALARM
DTSTART:20180610T173500Z
DTEND:20180610T203500Z
UID:fyVbpWXZn9Y8IK-hWqzb1tGv@stanza.co
SUMMARY:Keys @ Blue Rocks
DESCRIPTION:Keys @ Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+wX8n-9\n\nShop: https://stza.co/+wX8n-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Hillcats
<2018-06-11 Mon 18:00-21:00>
:PROPERTIES:
:ID:       BHoHWNXmesxSDGHpM_tIzO3M@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Hillcats Keys vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+wi8i-1a

Shop  https //stza.co/+wi8i-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Hillcats
END:VALARM
DTSTART:20180611T230000Z
DTEND:20180612T020000Z
UID:BHoHWNXmesxSDGHpM_tIzO3M@stanza.co
SUMMARY:Keys vs. Hillcats
DESCRIPTION:Keys vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+wi8i-1a\n\nShop: https://stza.co/+wi8i-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Hillcats
<2018-06-12 Tue 18:00-21:00>
:PROPERTIES:
:ID:       iBsCVFwf1Yr1aIoIwszYtrty@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys vs. Hillcats Keys vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+wi8k-a

Shop  https //stza.co/+wi8k-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Hillcats
END:VALARM
DTSTART:20180612T230000Z
DTEND:20180613T020000Z
UID:iBsCVFwf1Yr1aIoIwszYtrty@stanza.co
SUMMARY:Keys vs. Hillcats
DESCRIPTION:Keys vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+wi8k-a\n\nShop: https://stza.co/+wi8k-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Hillcats
<2018-06-13 Wed 18:00-21:00>
:PROPERTIES:
:ID:       -4BfcpISiNDZR8EptMlBtJGs@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Hillcats Keys vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+wi8n-2w

Shop  https //stza.co/+wi8n-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Hillcats
END:VALARM
DTSTART:20180613T230000Z
DTEND:20180614T020000Z
UID:-4BfcpISiNDZR8EptMlBtJGs@stanza.co
SUMMARY:Keys vs. Hillcats
DESCRIPTION:Keys vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+wi8n-2w\n\nShop: https://stza.co/+wi8n-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Wood Ducks
<2018-06-14 Thu 18:00-21:00>
:PROPERTIES:
:ID:       J3G0aBLGtTpQj3fqNdef9Wbb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Wood Ducks Keys vs. Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+wi8p-2b

Shop  https //stza.co/+wi8p-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Wood Ducks
END:VALARM
DTSTART:20180614T230000Z
DTEND:20180615T020000Z
UID:J3G0aBLGtTpQj3fqNdef9Wbb@stanza.co
SUMMARY:Keys vs. Wood Ducks
DESCRIPTION:Keys vs. Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+wi8p-2b\n\nShop: https://stza.co/+wi8p-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Wood Ducks
<2018-06-15 Fri 18:00-21:00>
:PROPERTIES:
:ID:       TYAAZX63gHPPfpz-PSeuF_KY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys vs. Wood Ducks Keys vs. Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+wi8r-A

Shop  https //stza.co/+wi8r-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Wood Ducks
END:VALARM
DTSTART:20180615T230000Z
DTEND:20180616T020000Z
UID:TYAAZX63gHPPfpz-PSeuF_KY@stanza.co
SUMMARY:Keys vs. Wood Ducks
DESCRIPTION:Keys vs. Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+wi8r-A\n\nShop: https://stza.co/+wi8r-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Wood Ducks
<2018-06-16 Sat 17:00-20:00>
:PROPERTIES:
:ID:       DD8d9o1E1xvBGKwtlNV8T-va@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Wood Ducks Keys vs. Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+wi8s-2H

Shop  https //stza.co/+wi8s-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Wood Ducks
END:VALARM
DTSTART:20180616T220000Z
DTEND:20180617T010000Z
UID:DD8d9o1E1xvBGKwtlNV8T-va@stanza.co
SUMMARY:Keys vs. Wood Ducks
DESCRIPTION:Keys vs. Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+wi8s-2H\n\nShop: https://stza.co/+wi8s-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Wood Ducks
<2018-06-17 Sun 13:00-16:00>
:PROPERTIES:
:ID:       bFNWW-JExDDdmSyTXMj7DoK-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Wood Ducks Keys vs. Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+wi8v-3y

Shop  https //stza.co/+wi8v-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Wood Ducks
END:VALARM
DTSTART:20180617T180000Z
DTEND:20180617T210000Z
UID:bFNWW-JExDDdmSyTXMj7DoK-@stanza.co
SUMMARY:Keys vs. Wood Ducks
DESCRIPTION:Keys vs. Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+wi8v-3y\n\nShop: https://stza.co/+wi8v-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Red Sox
<2018-06-21 Thu>--<2018-06-20 Wed>
:PROPERTIES:
:ID:       -umovBNQD6Pcm4JOmOwa7upn@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys @ Red Sox Keys @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0tJ-1z

Shop  https //stza.co/+w0tJ-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180621
DTEND;VALUE=DATE:20180621
UID:-umovBNQD6Pcm4JOmOwa7upn@stanza.co
SUMMARY:Keys @ Red Sox
DESCRIPTION:Keys @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0tJ-1z\n\nShop: https://stza.co/+w0tJ-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Red Sox
<2018-06-22 Fri>--<2018-06-21 Thu>
:PROPERTIES:
:ID:       kGcgMIaGyA-dbtqqet_i3AT-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Red Sox Keys @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0tK-39

Shop  https //stza.co/+w0tK-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180622
DTEND;VALUE=DATE:20180622
UID:kGcgMIaGyA-dbtqqet_i3AT-@stanza.co
SUMMARY:Keys @ Red Sox
DESCRIPTION:Keys @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0tK-39\n\nShop: https://stza.co/+w0tK-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Red Sox
<2018-06-23 Sat>--<2018-06-22 Fri>
:PROPERTIES:
:ID:       1L1LZfLldR0_koZl2zrLcaNm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Red Sox Keys @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0tL-1X

Shop  https //stza.co/+w0tL-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180623
DTEND;VALUE=DATE:20180623
UID:1L1LZfLldR0_koZl2zrLcaNm@stanza.co
SUMMARY:Keys @ Red Sox
DESCRIPTION:Keys @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0tL-1X\n\nShop: https://stza.co/+w0tL-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Red Sox
<2018-06-24 Sun>--<2018-06-23 Sat>
:PROPERTIES:
:ID:       joH26gD4Q9CmA-JEF5Y6HjTk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys @ Red Sox Keys @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0tM-2J

Shop  https //stza.co/+w0tM-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180624
DTEND;VALUE=DATE:20180624
UID:joH26gD4Q9CmA-JEF5Y6HjTk@stanza.co
SUMMARY:Keys @ Red Sox
DESCRIPTION:Keys @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0tM-2J\n\nShop: https://stza.co/+w0tM-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Dash
<2018-06-25 Mon 18:00-21:00>
:PROPERTIES:
:ID:       Rx0-5i3Bgc5vzg4MWPNIU1Uk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Dash Keys vs. Dash

Follow on MiLB First Pitch  https //stza.co/+wi8x-2C

Shop  https //stza.co/+wi8x-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Dash
END:VALARM
DTSTART:20180625T230000Z
DTEND:20180626T020000Z
UID:Rx0-5i3Bgc5vzg4MWPNIU1Uk@stanza.co
SUMMARY:Keys vs. Dash
DESCRIPTION:Keys vs. Dash\n\nFollow on MiLB First Pitch: https://stza.co/+wi8x-2C\n\nShop: https://stza.co/+wi8x-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Dash
<2018-06-26 Tue 18:00-21:00>
:PROPERTIES:
:ID:       j9G9IrHCsNP7PS1VSRFh1aO3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Dash Keys vs. Dash

Follow on MiLB First Pitch  https //stza.co/+wi8z-1l

Shop  https //stza.co/+wi8z-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Dash
END:VALARM
DTSTART:20180626T230000Z
DTEND:20180627T020000Z
UID:j9G9IrHCsNP7PS1VSRFh1aO3@stanza.co
SUMMARY:Keys vs. Dash
DESCRIPTION:Keys vs. Dash\n\nFollow on MiLB First Pitch: https://stza.co/+wi8z-1l\n\nShop: https://stza.co/+wi8z-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Dash
<2018-06-27 Wed 18:00-21:00>
:PROPERTIES:
:ID:       jRwWSJ748LVGwQELe1-2Ne6N@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys vs. Dash Keys vs. Dash

Follow on MiLB First Pitch  https //stza.co/+wi8A-3x

Shop  https //stza.co/+wi8A-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Dash
END:VALARM
DTSTART:20180627T230000Z
DTEND:20180628T020000Z
UID:jRwWSJ748LVGwQELe1-2Ne6N@stanza.co
SUMMARY:Keys vs. Dash
DESCRIPTION:Keys vs. Dash\n\nFollow on MiLB First Pitch: https://stza.co/+wi8A-3x\n\nShop: https://stza.co/+wi8A-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Dash
<2018-06-28 Thu 18:00-21:00>
:PROPERTIES:
:ID:       -Q62UmZ_wXhle3_RcXb1jueW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Dash Keys vs. Dash

Follow on MiLB First Pitch  https //stza.co/+wi8C-2e

Shop  https //stza.co/+wi8C-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Dash
END:VALARM
DTSTART:20180628T230000Z
DTEND:20180629T020000Z
UID:-Q62UmZ_wXhle3_RcXb1jueW@stanza.co
SUMMARY:Keys vs. Dash
DESCRIPTION:Keys vs. Dash\n\nFollow on MiLB First Pitch: https://stza.co/+wi8C-2e\n\nShop: https://stza.co/+wi8C-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Dash
<2018-06-29 Fri 18:00-21:00>
:PROPERTIES:
:ID:       -z8cKD342J_nmFSxeXGzFSAV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Dash Keys vs. Dash

Follow on MiLB First Pitch  https //stza.co/+wi8F-2j

Shop  https //stza.co/+wi8F-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Dash
END:VALARM
DTSTART:20180629T230000Z
DTEND:20180630T020000Z
UID:-z8cKD342J_nmFSxeXGzFSAV@stanza.co
SUMMARY:Keys vs. Dash
DESCRIPTION:Keys vs. Dash\n\nFollow on MiLB First Pitch: https://stza.co/+wi8F-2j\n\nShop: https://stza.co/+wi8F-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Hillcats
<2018-06-30 Sat 17:00-20:00>
:PROPERTIES:
:ID:       5Qstbiso_FjdXgZw0dAxvreN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys vs. Hillcats Keys vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+wi8G-2O

Shop  https //stza.co/+wi8G-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Hillcats
END:VALARM
DTSTART:20180630T220000Z
DTEND:20180701T010000Z
UID:5Qstbiso_FjdXgZw0dAxvreN@stanza.co
SUMMARY:Keys vs. Hillcats
DESCRIPTION:Keys vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+wi8G-2O\n\nShop: https://stza.co/+wi8G-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Hillcats
<2018-07-01 Sun 13:00-16:00>
:PROPERTIES:
:ID:       XvKW4x3lccM1FCv4Wm04Q4qS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Hillcats Keys vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+wi8I-1Q

Shop  https //stza.co/+wi8I-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Hillcats
END:VALARM
DTSTART:20180701T180000Z
DTEND:20180701T210000Z
UID:XvKW4x3lccM1FCv4Wm04Q4qS@stanza.co
SUMMARY:Keys vs. Hillcats
DESCRIPTION:Keys vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+wi8I-1Q\n\nShop: https://stza.co/+wi8I-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Hillcats
<2018-07-02 Mon 18:00-21:00>
:PROPERTIES:
:ID:       NCyT7ieeTJuLtQ7ZsY095NkA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Hillcats Keys vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+wi8K-Y

Shop  https //stza.co/+wi8K-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Hillcats
END:VALARM
DTSTART:20180702T230000Z
DTEND:20180703T020000Z
UID:NCyT7ieeTJuLtQ7ZsY095NkA@stanza.co
SUMMARY:Keys vs. Hillcats
DESCRIPTION:Keys vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+wi8K-Y\n\nShop: https://stza.co/+wi8K-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Hillcats
<2018-07-03 Tue 18:00-21:00>
:PROPERTIES:
:ID:       9qrTKii3fKAi28DmsKDYJIqG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys vs. Hillcats Keys vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+wi8M-34

Shop  https //stza.co/+wi8M-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Hillcats
END:VALARM
DTSTART:20180703T230000Z
DTEND:20180704T020000Z
UID:9qrTKii3fKAi28DmsKDYJIqG@stanza.co
SUMMARY:Keys vs. Hillcats
DESCRIPTION:Keys vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+wi8M-34\n\nShop: https://stza.co/+wi8M-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Mudcats
<2018-07-04 Wed 18:00-21:00>
:PROPERTIES:
:ID:       52TaIDLb1gpTnMSHjhQUQYEJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Mudcats Keys @ Mudcats

Buy tickets here  https //stza.co/~w0qT

Follow on MiLB First Pitch  https //stza.co/+w0qT-3A

Shop  https //stza.co/+w0qT-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Mudcats
END:VALARM
DTSTART:20180704T230000Z
DTEND:20180705T020000Z
UID:52TaIDLb1gpTnMSHjhQUQYEJ@stanza.co
SUMMARY:Keys @ Mudcats
DESCRIPTION:Keys @ Mudcats\n\nBuy tickets here: https://stza.co/~w0qT\n\nFollow on MiLB First Pitch: https://stza.co/+w0qT-3A\n\nShop: https://stza.co/+w0qT-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Mudcats
<2018-07-05 Thu 18:00-21:00>
:PROPERTIES:
:ID:       juCuxdKl12ehQtFaAqkihRF9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Mudcats Keys @ Mudcats

Buy tickets here  https //stza.co/~w0qU

Follow on MiLB First Pitch  https //stza.co/+w0qU-3N

Shop  https //stza.co/+w0qU-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Mudcats
END:VALARM
DTSTART:20180705T230000Z
DTEND:20180706T020000Z
UID:juCuxdKl12ehQtFaAqkihRF9@stanza.co
SUMMARY:Keys @ Mudcats
DESCRIPTION:Keys @ Mudcats\n\nBuy tickets here: https://stza.co/~w0qU\n\nFollow on MiLB First Pitch: https://stza.co/+w0qU-3N\n\nShop: https://stza.co/+w0qU-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Mudcats
<2018-07-06 Fri 18:00-21:00>
:PROPERTIES:
:ID:       LkB1N3gtVOZ-iaJX1uge7bV-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys @ Mudcats Keys @ Mudcats

Buy tickets here  https //stza.co/~w0qV

Follow on MiLB First Pitch  https //stza.co/+w0qV-o

Shop  https //stza.co/+w0qV-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Mudcats
END:VALARM
DTSTART:20180706T230000Z
DTEND:20180707T020000Z
UID:LkB1N3gtVOZ-iaJX1uge7bV-@stanza.co
SUMMARY:Keys @ Mudcats
DESCRIPTION:Keys @ Mudcats\n\nBuy tickets here: https://stza.co/~w0qV\n\nFollow on MiLB First Pitch: https://stza.co/+w0qV-o\n\nShop: https://stza.co/+w0qV-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Mudcats
<2018-07-07 Sat 16:00-19:00>
:PROPERTIES:
:ID:       IhtxNgI7aDI0KToO0G4lYUts@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Mudcats Keys @ Mudcats

Buy tickets here  https //stza.co/~w0qW

Follow on MiLB First Pitch  https //stza.co/+w0qW-2D

Shop  https //stza.co/+w0qW-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Mudcats
END:VALARM
DTSTART:20180707T210000Z
DTEND:20180708T000000Z
UID:IhtxNgI7aDI0KToO0G4lYUts@stanza.co
SUMMARY:Keys @ Mudcats
DESCRIPTION:Keys @ Mudcats\n\nBuy tickets here: https://stza.co/~w0qW\n\nFollow on MiLB First Pitch: https://stza.co/+w0qW-2D\n\nShop: https://stza.co/+w0qW-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Mudcats
<2018-07-08 Sun 13:00-16:00>
:PROPERTIES:
:ID:       vDO_8G81pqNiwqZCSU_kisAz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Mudcats Keys @ Mudcats

Buy tickets here  https //stza.co/~w0qX

Follow on MiLB First Pitch  https //stza.co/+w0qX-1X

Shop  https //stza.co/+w0qX-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Mudcats
END:VALARM
DTSTART:20180708T180000Z
DTEND:20180708T210000Z
UID:vDO_8G81pqNiwqZCSU_kisAz@stanza.co
SUMMARY:Keys @ Mudcats
DESCRIPTION:Keys @ Mudcats\n\nBuy tickets here: https://stza.co/~w0qX\n\nFollow on MiLB First Pitch: https://stza.co/+w0qX-1X\n\nShop: https://stza.co/+w0qX-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Blue Rocks
<2018-07-09 Mon 18:00-21:00>
:PROPERTIES:
:ID:       MdXECIot0K8k7JWTbz_tDNcC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys vs. Blue Rocks Keys vs. Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+wi8O-3Z

Shop  https //stza.co/+wi8O-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Blue Rocks
END:VALARM
DTSTART:20180709T230000Z
DTEND:20180710T020000Z
UID:MdXECIot0K8k7JWTbz_tDNcC@stanza.co
SUMMARY:Keys vs. Blue Rocks
DESCRIPTION:Keys vs. Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+wi8O-3Z\n\nShop: https://stza.co/+wi8O-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Blue Rocks
<2018-07-10 Tue 18:00-21:00>
:PROPERTIES:
:ID:       3W7uucDSJ9Ukjb6bEqe8VbS4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Blue Rocks Keys vs. Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+wi8R-32

Shop  https //stza.co/+wi8R-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Blue Rocks
END:VALARM
DTSTART:20180710T230000Z
DTEND:20180711T020000Z
UID:3W7uucDSJ9Ukjb6bEqe8VbS4@stanza.co
SUMMARY:Keys vs. Blue Rocks
DESCRIPTION:Keys vs. Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+wi8R-32\n\nShop: https://stza.co/+wi8R-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Blue Rocks
<2018-07-11 Wed 18:00-21:00>
:PROPERTIES:
:ID:       iIPRvgpGEghBfJIMt7gs-NtO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Blue Rocks Keys vs. Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+wi8T-1P

Shop  https //stza.co/+wi8T-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Blue Rocks
END:VALARM
DTSTART:20180711T230000Z
DTEND:20180712T020000Z
UID:iIPRvgpGEghBfJIMt7gs-NtO@stanza.co
SUMMARY:Keys vs. Blue Rocks
DESCRIPTION:Keys vs. Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+wi8T-1P\n\nShop: https://stza.co/+wi8T-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Blue Rocks
<2018-07-12 Thu 18:00-21:00>
:PROPERTIES:
:ID:       UnKLxux4v6qkSewbMdlGypUO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys vs. Blue Rocks Keys vs. Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+wi8V-2F

Shop  https //stza.co/+wi8V-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Blue Rocks
END:VALARM
DTSTART:20180712T230000Z
DTEND:20180713T020000Z
UID:UnKLxux4v6qkSewbMdlGypUO@stanza.co
SUMMARY:Keys vs. Blue Rocks
DESCRIPTION:Keys vs. Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+wi8V-2F\n\nShop: https://stza.co/+wi8V-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Nationals
<2018-07-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       mbZ7ME6e5X1EHzAXNSx456KB@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Nationals Keys @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xA2O-16

Shop  https //stza.co/+xA2O-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Nationals
END:VALARM
DTSTART:20180713T230500Z
DTEND:20180714T020500Z
UID:mbZ7ME6e5X1EHzAXNSx456KB@stanza.co
SUMMARY:Keys @ Nationals
DESCRIPTION:Keys @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xA2O-16\n\nShop: https://stza.co/+xA2O-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Nationals
<2018-07-14 Sat 17:35-20:35>
:PROPERTIES:
:ID:       zE60-Hu54lGXnJzZA1Xmel4x@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Nationals Keys @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xA2P-3R

Shop  https //stza.co/+xA2P-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Nationals
END:VALARM
DTSTART:20180714T223500Z
DTEND:20180715T013500Z
UID:zE60-Hu54lGXnJzZA1Xmel4x@stanza.co
SUMMARY:Keys @ Nationals
DESCRIPTION:Keys @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xA2P-3R\n\nShop: https://stza.co/+xA2P-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Nationals
<2018-07-15 Sun 12:05-15:05>
:PROPERTIES:
:ID:       gcHUH5NMx5plX-y848TTdQ9s@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys @ Nationals Keys @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xA2Q-2H

Shop  https //stza.co/+xA2Q-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Nationals
END:VALARM
DTSTART:20180715T170500Z
DTEND:20180715T200500Z
UID:gcHUH5NMx5plX-y848TTdQ9s@stanza.co
SUMMARY:Keys @ Nationals
DESCRIPTION:Keys @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xA2Q-2H\n\nShop: https://stza.co/+xA2Q-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Nationals
<2018-07-16 Mon 11:05-14:05>
:PROPERTIES:
:ID:       9Tm8lO0vFaU3KkpmeEKahY1m@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Nationals Keys @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xA2R-3m

Shop  https //stza.co/+xA2R-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Nationals
END:VALARM
DTSTART:20180716T160500Z
DTEND:20180716T190500Z
UID:9Tm8lO0vFaU3KkpmeEKahY1m@stanza.co
SUMMARY:Keys @ Nationals
DESCRIPTION:Keys @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xA2R-3m\n\nShop: https://stza.co/+xA2R-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Wood Ducks
<2018-07-18 Wed 18:00-21:00>
:PROPERTIES:
:ID:       eyJtf4C4ZLzNQ0KBnQBm6JH1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Wood Ducks Keys vs. Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+wi8X-l

Shop  https //stza.co/+wi8X-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Wood Ducks
END:VALARM
DTSTART:20180718T230000Z
DTEND:20180719T020000Z
UID:eyJtf4C4ZLzNQ0KBnQBm6JH1@stanza.co
SUMMARY:Keys vs. Wood Ducks
DESCRIPTION:Keys vs. Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+wi8X-l\n\nShop: https://stza.co/+wi8X-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Wood Ducks
<2018-07-19 Thu 18:00-21:00>
:PROPERTIES:
:ID:       cKd8I6NB3ZUwv2hfL3txmA0l@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys vs. Wood Ducks Keys vs. Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+wi8Y-2D

Shop  https //stza.co/+wi8Y-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Wood Ducks
END:VALARM
DTSTART:20180719T230000Z
DTEND:20180720T020000Z
UID:cKd8I6NB3ZUwv2hfL3txmA0l@stanza.co
SUMMARY:Keys vs. Wood Ducks
DESCRIPTION:Keys vs. Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+wi8Y-2D\n\nShop: https://stza.co/+wi8Y-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Wood Ducks
<2018-07-20 Fri 18:00-21:00>
:PROPERTIES:
:ID:       O78jv1D4GdiB7iNqSaqjF8Of@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Wood Ducks Keys vs. Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+wi91-3N

Shop  https //stza.co/+wi91-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Wood Ducks
END:VALARM
DTSTART:20180720T230000Z
DTEND:20180721T020000Z
UID:O78jv1D4GdiB7iNqSaqjF8Of@stanza.co
SUMMARY:Keys vs. Wood Ducks
DESCRIPTION:Keys vs. Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+wi91-3N\n\nShop: https://stza.co/+wi91-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Blue Rocks
<2018-07-21 Sat 17:00-20:00>
:PROPERTIES:
:ID:       MSE9U51JibnwnqITyx-oY-Ob@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Blue Rocks Keys vs. Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+wi92-3P

Shop  https //stza.co/+wi92-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Blue Rocks
END:VALARM
DTSTART:20180721T220000Z
DTEND:20180722T010000Z
UID:MSE9U51JibnwnqITyx-oY-Ob@stanza.co
SUMMARY:Keys vs. Blue Rocks
DESCRIPTION:Keys vs. Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+wi92-3P\n\nShop: https://stza.co/+wi92-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Blue Rocks
<2018-07-22 Sun 13:00-16:00>
:PROPERTIES:
:ID:       BS-MhItQ39juvy5XLba5wked@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys vs. Blue Rocks Keys vs. Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+wi95-r

Shop  https //stza.co/+wi95-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Blue Rocks
END:VALARM
DTSTART:20180722T180000Z
DTEND:20180722T210000Z
UID:BS-MhItQ39juvy5XLba5wked@stanza.co
SUMMARY:Keys vs. Blue Rocks
DESCRIPTION:Keys vs. Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+wi95-r\n\nShop: https://stza.co/+wi95-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Blue Rocks
<2018-07-23 Mon 13:00-16:00>
:PROPERTIES:
:ID:       Ye51fa2MXV-aYysjlUG8BliE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Blue Rocks Keys vs. Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+wi98-K

Shop  https //stza.co/+wi98-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Blue Rocks
END:VALARM
DTSTART:20180723T180000Z
DTEND:20180723T210000Z
UID:Ye51fa2MXV-aYysjlUG8BliE@stanza.co
SUMMARY:Keys vs. Blue Rocks
DESCRIPTION:Keys vs. Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+wi98-K\n\nShop: https://stza.co/+wi98-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Dash
<2018-07-24 Tue 18:00-21:00>
:PROPERTIES:
:ID:       0YKIDvZfr0N6S_teprudYXf0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Dash Keys @ Dash

Buy tickets here  https //stza.co/~w0u0

Follow on MiLB First Pitch  https //stza.co/+w0u0-3p

Shop  https //stza.co/+w0u0-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Dash
END:VALARM
DTSTART:20180724T230000Z
DTEND:20180725T020000Z
UID:0YKIDvZfr0N6S_teprudYXf0@stanza.co
SUMMARY:Keys @ Dash
DESCRIPTION:Keys @ Dash\n\nBuy tickets here: https://stza.co/~w0u0\n\nFollow on MiLB First Pitch: https://stza.co/+w0u0-3p\n\nShop: https://stza.co/+w0u0-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Dash
<2018-07-25 Wed 10:00-13:00>
:PROPERTIES:
:ID:       laIcLlTIvEwT8ROAV4cSQZpc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys @ Dash Keys @ Dash

Buy tickets here  https //stza.co/~w0u1

Follow on MiLB First Pitch  https //stza.co/+w0u1-34

Shop  https //stza.co/+w0u1-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Dash
END:VALARM
DTSTART:20180725T150000Z
DTEND:20180725T180000Z
UID:laIcLlTIvEwT8ROAV4cSQZpc@stanza.co
SUMMARY:Keys @ Dash
DESCRIPTION:Keys @ Dash\n\nBuy tickets here: https://stza.co/~w0u1\n\nFollow on MiLB First Pitch: https://stza.co/+w0u1-34\n\nShop: https://stza.co/+w0u1-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Dash
<2018-07-26 Thu 18:00-21:00>
:PROPERTIES:
:ID:       tOopsXuzDl_B-nNRSGFfTpNC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Dash Keys @ Dash

Buy tickets here  https //stza.co/~w0u2

Follow on MiLB First Pitch  https //stza.co/+w0u2-33

Shop  https //stza.co/+w0u2-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Dash
END:VALARM
DTSTART:20180726T230000Z
DTEND:20180727T020000Z
UID:tOopsXuzDl_B-nNRSGFfTpNC@stanza.co
SUMMARY:Keys @ Dash
DESCRIPTION:Keys @ Dash\n\nBuy tickets here: https://stza.co/~w0u2\n\nFollow on MiLB First Pitch: https://stza.co/+w0u2-33\n\nShop: https://stza.co/+w0u2-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Wood Ducks
<2018-07-27 Fri 18:00-21:00>
:PROPERTIES:
:ID:       mtfyw5M_Zfda5ISbLKNfLsA8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Wood Ducks Keys @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0r0-3o

Shop  https //stza.co/+w0r0-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Wood Ducks
END:VALARM
DTSTART:20180727T230000Z
DTEND:20180728T020000Z
UID:mtfyw5M_Zfda5ISbLKNfLsA8@stanza.co
SUMMARY:Keys @ Wood Ducks
DESCRIPTION:Keys @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0r0-3o\n\nShop: https://stza.co/+w0r0-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Wood Ducks
<2018-07-28 Sat 17:00-20:00>
:PROPERTIES:
:ID:       lvmUHDvEYvrg7__q-eNCVpsU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys @ Wood Ducks Keys @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0r1-3w

Shop  https //stza.co/+w0r1-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Wood Ducks
END:VALARM
DTSTART:20180728T220000Z
DTEND:20180729T010000Z
UID:lvmUHDvEYvrg7__q-eNCVpsU@stanza.co
SUMMARY:Keys @ Wood Ducks
DESCRIPTION:Keys @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0r1-3w\n\nShop: https://stza.co/+w0r1-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Wood Ducks
<2018-07-29 Sun 15:00-18:00>
:PROPERTIES:
:ID:       GCJc01k-diF5RUnOdWVFg4hn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Wood Ducks Keys @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0r2-3k

Shop  https //stza.co/+w0r2-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Wood Ducks
END:VALARM
DTSTART:20180729T200000Z
DTEND:20180729T230000Z
UID:GCJc01k-diF5RUnOdWVFg4hn@stanza.co
SUMMARY:Keys @ Wood Ducks
DESCRIPTION:Keys @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0r2-3k\n\nShop: https://stza.co/+w0r2-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Nationals
<2018-07-31 Tue 18:00-21:00>
:PROPERTIES:
:ID:       2unlq4OdrzsrE2J60aTxvfgG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Nationals Keys vs. Nationals

Follow on MiLB First Pitch  https //stza.co/+wi9a-2O

Shop  https //stza.co/+wi9a-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Nationals
END:VALARM
DTSTART:20180731T230000Z
DTEND:20180801T020000Z
UID:2unlq4OdrzsrE2J60aTxvfgG@stanza.co
SUMMARY:Keys vs. Nationals
DESCRIPTION:Keys vs. Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+wi9a-2O\n\nShop: https://stza.co/+wi9a-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Nationals
<2018-08-01 Wed 18:00-21:00>
:PROPERTIES:
:ID:       wKU_D9kF1xRWYXcFYc3Vw4MR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys vs. Nationals Keys vs. Nationals

Follow on MiLB First Pitch  https //stza.co/+wi9c-3b

Shop  https //stza.co/+wi9c-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Nationals
END:VALARM
DTSTART:20180801T230000Z
DTEND:20180802T020000Z
UID:wKU_D9kF1xRWYXcFYc3Vw4MR@stanza.co
SUMMARY:Keys vs. Nationals
DESCRIPTION:Keys vs. Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+wi9c-3b\n\nShop: https://stza.co/+wi9c-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Nationals
<2018-08-02 Thu 11:00-14:00>
:PROPERTIES:
:ID:       k_tVzogegKGP01lIoTyq4UnP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Nationals Keys vs. Nationals

Follow on MiLB First Pitch  https //stza.co/+wi9d-1d

Shop  https //stza.co/+wi9d-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Nationals
END:VALARM
DTSTART:20180802T160000Z
DTEND:20180802T190000Z
UID:k_tVzogegKGP01lIoTyq4UnP@stanza.co
SUMMARY:Keys vs. Nationals
DESCRIPTION:Keys vs. Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+wi9d-1d\n\nShop: https://stza.co/+wi9d-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Blue Rocks
<2018-08-03 Fri 18:05-21:05>
:PROPERTIES:
:ID:       fCLF5XrA285A2TKnNiGQ2pdE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Blue Rocks Keys @ Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+wX8o-2Y

Shop  https //stza.co/+wX8o-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Blue Rocks
END:VALARM
DTSTART:20180803T230500Z
DTEND:20180804T020500Z
UID:fCLF5XrA285A2TKnNiGQ2pdE@stanza.co
SUMMARY:Keys @ Blue Rocks
DESCRIPTION:Keys @ Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+wX8o-2Y\n\nShop: https://stza.co/+wX8o-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Blue Rocks
<2018-08-04 Sat 17:05-20:05>
:PROPERTIES:
:ID:       P6tkVUgnSYuHnQ2ThfrJXPl_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys @ Blue Rocks Keys @ Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+wX8p-18

Shop  https //stza.co/+wX8p-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Blue Rocks
END:VALARM
DTSTART:20180804T220500Z
DTEND:20180805T010500Z
UID:P6tkVUgnSYuHnQ2ThfrJXPl_@stanza.co
SUMMARY:Keys @ Blue Rocks
DESCRIPTION:Keys @ Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+wX8p-18\n\nShop: https://stza.co/+wX8p-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Blue Rocks
<2018-08-05 Sun 12:35-15:35>
:PROPERTIES:
:ID:       Kz3QORGbFzevpXiXsSU-Mmet@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Blue Rocks Keys @ Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+wX8q-2f

Shop  https //stza.co/+wX8q-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Blue Rocks
END:VALARM
DTSTART:20180805T173500Z
DTEND:20180805T203500Z
UID:Kz3QORGbFzevpXiXsSU-Mmet@stanza.co
SUMMARY:Keys @ Blue Rocks
DESCRIPTION:Keys @ Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+wX8q-2f\n\nShop: https://stza.co/+wX8q-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Nationals
<2018-08-07 Tue 18:05-21:05>
:PROPERTIES:
:ID:       jVAm0JqajEq7DYNxW9y2gYaf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Nationals Keys @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xA2S-1R

Shop  https //stza.co/+xA2S-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Nationals
END:VALARM
DTSTART:20180807T230500Z
DTEND:20180808T020500Z
UID:jVAm0JqajEq7DYNxW9y2gYaf@stanza.co
SUMMARY:Keys @ Nationals
DESCRIPTION:Keys @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xA2S-1R\n\nShop: https://stza.co/+xA2S-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Nationals
<2018-08-08 Wed 18:05-21:05>
:PROPERTIES:
:ID:       roIESussgiXhR0ohtrw6s9wF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys @ Nationals Keys @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xA2T-3Q

Shop  https //stza.co/+xA2T-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Nationals
END:VALARM
DTSTART:20180808T230500Z
DTEND:20180809T020500Z
UID:roIESussgiXhR0ohtrw6s9wF@stanza.co
SUMMARY:Keys @ Nationals
DESCRIPTION:Keys @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xA2T-3Q\n\nShop: https://stza.co/+xA2T-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Nationals
<2018-08-09 Thu 11:05-14:05>
:PROPERTIES:
:ID:       SPbI0h6kL9RF64OrHCoP6iiX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Nationals Keys @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xA2U-1O

Shop  https //stza.co/+xA2U-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Nationals
END:VALARM
DTSTART:20180809T160500Z
DTEND:20180809T190500Z
UID:SPbI0h6kL9RF64OrHCoP6iiX@stanza.co
SUMMARY:Keys @ Nationals
DESCRIPTION:Keys @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xA2U-1O\n\nShop: https://stza.co/+xA2U-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Astros
<2018-08-10 Fri 18:00-21:00>
:PROPERTIES:
:ID:       kp9BOd0n3RxY-GBWijVEhhWm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Astros Keys vs. Astros

Follow on MiLB First Pitch  https //stza.co/+wi9g-2_

Shop  https //stza.co/+wi9g-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Astros
END:VALARM
DTSTART:20180810T230000Z
DTEND:20180811T020000Z
UID:kp9BOd0n3RxY-GBWijVEhhWm@stanza.co
SUMMARY:Keys vs. Astros
DESCRIPTION:Keys vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+wi9g-2_\n\nShop: https://stza.co/+wi9g-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Astros
<2018-08-11 Sat 17:00-20:00>
:PROPERTIES:
:ID:       A_pfiE1Ljs_SO7gSexEP37az@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys vs. Astros Keys vs. Astros

Follow on MiLB First Pitch  https //stza.co/+wi9i-3t

Shop  https //stza.co/+wi9i-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Astros
END:VALARM
DTSTART:20180811T220000Z
DTEND:20180812T010000Z
UID:A_pfiE1Ljs_SO7gSexEP37az@stanza.co
SUMMARY:Keys vs. Astros
DESCRIPTION:Keys vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+wi9i-3t\n\nShop: https://stza.co/+wi9i-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Astros
<2018-08-12 Sun 13:00-16:00>
:PROPERTIES:
:ID:       EBysn4ZWW-dXvYkfVwfRYi5s@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Astros Keys vs. Astros

Follow on MiLB First Pitch  https //stza.co/+wi9j-K

Shop  https //stza.co/+wi9j-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Astros
END:VALARM
DTSTART:20180812T180000Z
DTEND:20180812T210000Z
UID:EBysn4ZWW-dXvYkfVwfRYi5s@stanza.co
SUMMARY:Keys vs. Astros
DESCRIPTION:Keys vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+wi9j-K\n\nShop: https://stza.co/+wi9j-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Red Sox
<2018-08-14 Tue 18:00-21:00>
:PROPERTIES:
:ID:       uuU5dwBPk5rzdErunleuDVHC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Red Sox Keys vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+wi9m-1l

Shop  https //stza.co/+wi9m-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Red Sox
END:VALARM
DTSTART:20180814T230000Z
DTEND:20180815T020000Z
UID:uuU5dwBPk5rzdErunleuDVHC@stanza.co
SUMMARY:Keys vs. Red Sox
DESCRIPTION:Keys vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wi9m-1l\n\nShop: https://stza.co/+wi9m-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Red Sox
<2018-08-15 Wed 18:00-21:00>
:PROPERTIES:
:ID:       F8TrWxEnA7PNQC-Vc82xCV6S@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys vs. Red Sox Keys vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+wi9o-23

Shop  https //stza.co/+wi9o-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Red Sox
END:VALARM
DTSTART:20180815T230000Z
DTEND:20180816T020000Z
UID:F8TrWxEnA7PNQC-Vc82xCV6S@stanza.co
SUMMARY:Keys vs. Red Sox
DESCRIPTION:Keys vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wi9o-23\n\nShop: https://stza.co/+wi9o-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Red Sox
<2018-08-16 Thu 18:00-21:00>
:PROPERTIES:
:ID:       uXhaRiA4NMbCW9Z4dfrYnACA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Red Sox Keys vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+wi9q-2s

Shop  https //stza.co/+wi9q-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Red Sox
END:VALARM
DTSTART:20180816T230000Z
DTEND:20180817T020000Z
UID:uXhaRiA4NMbCW9Z4dfrYnACA@stanza.co
SUMMARY:Keys vs. Red Sox
DESCRIPTION:Keys vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wi9q-2s\n\nShop: https://stza.co/+wi9q-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Hillcats
<2018-08-17 Fri 17:30-20:30>
:PROPERTIES:
:ID:       poey-mLqCrpHWEsdh46pMvAp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Hillcats Keys @ Hillcats

Buy tickets here  https //stza.co/~y3TA

Follow on MiLB First Pitch  https //stza.co/+y3TA-h

Shop  https //stza.co/+y3TA-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Hillcats
END:VALARM
DTSTART:20180817T223000Z
DTEND:20180818T013000Z
UID:poey-mLqCrpHWEsdh46pMvAp@stanza.co
SUMMARY:Keys @ Hillcats
DESCRIPTION:Keys @ Hillcats\n\nBuy tickets here: https://stza.co/~y3TA\n\nFollow on MiLB First Pitch: https://stza.co/+y3TA-h\n\nShop: https://stza.co/+y3TA-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Hillcats
<2018-08-18 Sat 17:00-20:00>
:PROPERTIES:
:ID:       5d4E53_LHhTH3ATkivFozgv9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys @ Hillcats Keys @ Hillcats

Buy tickets here  https //stza.co/~y3TB

Follow on MiLB First Pitch  https //stza.co/+y3TB-1P

Shop  https //stza.co/+y3TB-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Hillcats
END:VALARM
DTSTART:20180818T220000Z
DTEND:20180819T010000Z
UID:5d4E53_LHhTH3ATkivFozgv9@stanza.co
SUMMARY:Keys @ Hillcats
DESCRIPTION:Keys @ Hillcats\n\nBuy tickets here: https://stza.co/~y3TB\n\nFollow on MiLB First Pitch: https://stza.co/+y3TB-1P\n\nShop: https://stza.co/+y3TB-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Hillcats
<2018-08-19 Sun 16:00-19:00>
:PROPERTIES:
:ID:       QGO6Jj9ttuHH1yZD8t6K-wEG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Hillcats Keys @ Hillcats

Buy tickets here  https //stza.co/~y3TC

Follow on MiLB First Pitch  https //stza.co/+y3TC-C

Shop  https //stza.co/+y3TC-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Hillcats
END:VALARM
DTSTART:20180819T210000Z
DTEND:20180820T000000Z
UID:QGO6Jj9ttuHH1yZD8t6K-wEG@stanza.co
SUMMARY:Keys @ Hillcats
DESCRIPTION:Keys @ Hillcats\n\nBuy tickets here: https://stza.co/~y3TC\n\nFollow on MiLB First Pitch: https://stza.co/+y3TC-C\n\nShop: https://stza.co/+y3TC-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Red Sox
<2018-08-21 Tue>--<2018-08-20 Mon>
:PROPERTIES:
:ID:       4_VHvl7zGKpRw1uCXFAGs9vU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Red Sox Keys @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0tN-2J

Shop  https //stza.co/+w0tN-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180821
DTEND;VALUE=DATE:20180821
UID:4_VHvl7zGKpRw1uCXFAGs9vU@stanza.co
SUMMARY:Keys @ Red Sox
DESCRIPTION:Keys @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0tN-2J\n\nShop: https://stza.co/+w0tN-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Red Sox
<2018-08-22 Wed>--<2018-08-21 Tue>
:PROPERTIES:
:ID:       Vi-LpsPjYM9Iq8zzD0kdgSHU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys @ Red Sox Keys @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0tO-c

Shop  https //stza.co/+w0tO-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180822
DTEND;VALUE=DATE:20180822
UID:Vi-LpsPjYM9Iq8zzD0kdgSHU@stanza.co
SUMMARY:Keys @ Red Sox
DESCRIPTION:Keys @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0tO-c\n\nShop: https://stza.co/+w0tO-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Red Sox
<2018-08-23 Thu>--<2018-08-22 Wed>
:PROPERTIES:
:ID:       GicW1_2jwCpPJMRF5b6G5shi@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Red Sox Keys @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0tP-2y

Shop  https //stza.co/+w0tP-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180823
DTEND;VALUE=DATE:20180823
UID:GicW1_2jwCpPJMRF5b6G5shi@stanza.co
SUMMARY:Keys @ Red Sox
DESCRIPTION:Keys @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0tP-2y\n\nShop: https://stza.co/+w0tP-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Mudcats
<2018-08-24 Fri 18:00-21:00>
:PROPERTIES:
:ID:       eB50SegM4XfWEoWGDlT6w1OB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Mudcats Keys vs. Mudcats

Follow on MiLB First Pitch  https //stza.co/+wi9t-2h

Shop  https //stza.co/+wi9t-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Mudcats
END:VALARM
DTSTART:20180824T230000Z
DTEND:20180825T020000Z
UID:eB50SegM4XfWEoWGDlT6w1OB@stanza.co
SUMMARY:Keys vs. Mudcats
DESCRIPTION:Keys vs. Mudcats\n\nFollow on MiLB First Pitch: https://stza.co/+wi9t-2h\n\nShop: https://stza.co/+wi9t-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Mudcats
<2018-08-25 Sat 17:00-20:00>
:PROPERTIES:
:ID:       JKGCI9Gs4i4E-HKwzwXCwPlo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys vs. Mudcats Keys vs. Mudcats

Follow on MiLB First Pitch  https //stza.co/+wi9v-2L

Shop  https //stza.co/+wi9v-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Mudcats
END:VALARM
DTSTART:20180825T220000Z
DTEND:20180826T010000Z
UID:JKGCI9Gs4i4E-HKwzwXCwPlo@stanza.co
SUMMARY:Keys vs. Mudcats
DESCRIPTION:Keys vs. Mudcats\n\nFollow on MiLB First Pitch: https://stza.co/+wi9v-2L\n\nShop: https://stza.co/+wi9v-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Mudcats
<2018-08-26 Sun 13:00-16:00>
:PROPERTIES:
:ID:       bLyE-eY516QqOT7GFZwWvsd8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Mudcats Keys vs. Mudcats

Follow on MiLB First Pitch  https //stza.co/+wi9w-3M

Shop  https //stza.co/+wi9w-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Mudcats
END:VALARM
DTSTART:20180826T180000Z
DTEND:20180826T210000Z
UID:bLyE-eY516QqOT7GFZwWvsd8@stanza.co
SUMMARY:Keys vs. Mudcats
DESCRIPTION:Keys vs. Mudcats\n\nFollow on MiLB First Pitch: https://stza.co/+wi9w-3M\n\nShop: https://stza.co/+wi9w-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Nationals
<2018-08-27 Mon 18:05-21:05>
:PROPERTIES:
:ID:       T-hHkwU25XxnPwnZfL5UQZsY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Nationals Keys @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xA2W-3i

Shop  https //stza.co/+xA2W-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Nationals
END:VALARM
DTSTART:20180827T230500Z
DTEND:20180828T020500Z
UID:T-hHkwU25XxnPwnZfL5UQZsY@stanza.co
SUMMARY:Keys @ Nationals
DESCRIPTION:Keys @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xA2W-3i\n\nShop: https://stza.co/+xA2W-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Nationals
<2018-08-28 Tue 18:05-21:05>
:PROPERTIES:
:ID:       Jq7SWit9Wdo0whK44X5XwpC1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys @ Nationals Keys @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xA2X-1w

Shop  https //stza.co/+xA2X-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Nationals
END:VALARM
DTSTART:20180828T230500Z
DTEND:20180829T020500Z
UID:Jq7SWit9Wdo0whK44X5XwpC1@stanza.co
SUMMARY:Keys @ Nationals
DESCRIPTION:Keys @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xA2X-1w\n\nShop: https://stza.co/+xA2X-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Nationals
<2018-08-29 Wed 18:05-21:05>
:PROPERTIES:
:ID:       MWjGgEz8GnxepUUet08pI8vm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Nationals Keys @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xA2Y-1k

Shop  https //stza.co/+xA2Y-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Nationals
END:VALARM
DTSTART:20180829T230500Z
DTEND:20180830T020500Z
UID:MWjGgEz8GnxepUUet08pI8vm@stanza.co
SUMMARY:Keys @ Nationals
DESCRIPTION:Keys @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xA2Y-1k\n\nShop: https://stza.co/+xA2Y-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys @ Nationals
<2018-08-30 Thu 18:05-21:05>
:PROPERTIES:
:ID:       QFVtSdonsMxCr3hpgeXJYvMu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys @ Nationals Keys @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xA2Z-

Shop  https //stza.co/+xA2Z-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Keys @ Nationals
END:VALARM
DTSTART:20180830T230500Z
DTEND:20180831T020500Z
UID:QFVtSdonsMxCr3hpgeXJYvMu@stanza.co
SUMMARY:Keys @ Nationals
DESCRIPTION:Keys @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xA2Z-\n\nShop: https://stza.co/+xA2Z-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Pelicans
<2018-08-31 Fri 18:00-21:00>
:PROPERTIES:
:ID:       a5ATDhxGzvV44WQJSO03KHfB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys vs. Pelicans Keys vs. Pelicans

Follow on MiLB First Pitch  https //stza.co/+wi9z-u

Shop  https //stza.co/+wi9z-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Pelicans
END:VALARM
DTSTART:20180831T230000Z
DTEND:20180901T020000Z
UID:a5ATDhxGzvV44WQJSO03KHfB@stanza.co
SUMMARY:Keys vs. Pelicans
DESCRIPTION:Keys vs. Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+wi9z-u\n\nShop: https://stza.co/+wi9z-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Pelicans
<2018-09-01 Sat 17:00-20:00>
:PROPERTIES:
:ID:       Xa3WZA20smV-8PFrjnhP40Jh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Pelicans Keys vs. Pelicans

Follow on MiLB First Pitch  https //stza.co/+wi9C-R

Shop  https //stza.co/+wi9C-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Pelicans
END:VALARM
DTSTART:20180901T220000Z
DTEND:20180902T010000Z
UID:Xa3WZA20smV-8PFrjnhP40Jh@stanza.co
SUMMARY:Keys vs. Pelicans
DESCRIPTION:Keys vs. Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+wi9C-R\n\nShop: https://stza.co/+wi9C-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Pelicans
<2018-09-02 Sun 17:00-20:00>
:PROPERTIES:
:ID:       UKdRxDQqXUBlO8iEdevRPBkf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Keys vs. Pelicans Keys vs. Pelicans

Follow on MiLB First Pitch  https //stza.co/+wi9D-b

Shop  https //stza.co/+wi9D-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Pelicans
END:VALARM
DTSTART:20180902T220000Z
DTEND:20180903T010000Z
UID:UKdRxDQqXUBlO8iEdevRPBkf@stanza.co
SUMMARY:Keys vs. Pelicans
DESCRIPTION:Keys vs. Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+wi9D-b\n\nShop: https://stza.co/+wi9D-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
* Keys vs. Pelicans
<2018-09-03 Mon 13:00-16:00>
:PROPERTIES:
:ID:       yUa1UfQDZSx0YqAjeAY0xW1o@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Keys vs. Pelicans Keys vs. Pelicans

Follow on MiLB First Pitch  https //stza.co/+wi9G-17

Shop  https //stza.co/+wi9G-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Keys vs. Pelicans
END:VALARM
DTSTART:20180903T180000Z
DTEND:20180903T210000Z
UID:yUa1UfQDZSx0YqAjeAY0xW1o@stanza.co
SUMMARY:Keys vs. Pelicans
DESCRIPTION:Keys vs. Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+wi9G-17\n\nShop: https://stza.co/+wi9G-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144526Z
LAST-MODIFIED:20180213T144526Z
TRANSP:OPAQUE
END:VEVENT
