#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Captains vs. TinCaps
<2018-04-05 Thu 17:30-20:30>
:PROPERTIES:
:ID:       QO9FDRk1RO3QqJRGRO_qLlK3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. TinCaps Captains vs. TinCaps

Follow on MiLB First Pitch  https //stza.co/+xAAd-33

Shop  https //stza.co/+xAAd-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. TinCaps
END:VALARM
DTSTART:20180405T223000Z
DTEND:20180406T013000Z
UID:QO9FDRk1RO3QqJRGRO_qLlK3@stanza.co
SUMMARY:Captains vs. TinCaps
DESCRIPTION:Captains vs. TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+xAAd-33\n\nShop: https://stza.co/+xAAd-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. TinCaps
<2018-04-06 Fri 17:30-20:30>
:PROPERTIES:
:ID:       5fMhDwLgpwoBX1QnXFMRa1G6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains vs. TinCaps Captains vs. TinCaps

Follow on MiLB First Pitch  https //stza.co/+xAAg-2o

Shop  https //stza.co/+xAAg-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. TinCaps
END:VALARM
DTSTART:20180406T223000Z
DTEND:20180407T013000Z
UID:5fMhDwLgpwoBX1QnXFMRa1G6@stanza.co
SUMMARY:Captains vs. TinCaps
DESCRIPTION:Captains vs. TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+xAAg-2o\n\nShop: https://stza.co/+xAAg-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ TinCaps
<2018-04-07 Sat 17:05-20:05>
:PROPERTIES:
:ID:       Py3HELKe6fXQeVb3d4k0INMo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ TinCaps Captains @ TinCaps

Buy tickets here  https //stza.co/~vN8Y

Follow on MiLB First Pitch  https //stza.co/+vN8Y-8

Shop  https //stza.co/+vN8Y-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ TinCaps
END:VALARM
DTSTART:20180407T220500Z
DTEND:20180408T010500Z
UID:Py3HELKe6fXQeVb3d4k0INMo@stanza.co
SUMMARY:Captains @ TinCaps
DESCRIPTION:Captains @ TinCaps\n\nBuy tickets here: https://stza.co/~vN8Y\n\nFollow on MiLB First Pitch: https://stza.co/+vN8Y-8\n\nShop: https://stza.co/+vN8Y-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ TinCaps
<2018-04-08 Sun 14:05-17:05>
:PROPERTIES:
:ID:       K8YIqwn8Veepq_ynxyphRTtU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ TinCaps Captains @ TinCaps

Follow on MiLB First Pitch  https //stza.co/+vN8Z-2K

Shop  https //stza.co/+vN8Z-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ TinCaps
END:VALARM
DTSTART:20180408T190500Z
DTEND:20180408T220500Z
UID:K8YIqwn8Veepq_ynxyphRTtU@stanza.co
SUMMARY:Captains @ TinCaps
DESCRIPTION:Captains @ TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+vN8Z-2K\n\nShop: https://stza.co/+vN8Z-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Dragons
<2018-04-09 Mon 18:00-21:00>
:PROPERTIES:
:ID:       PjDpR8ajss_THkmx2Schd6ct@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains @ Dragons Captains @ Dragons

Follow on MiLB First Pitch  https //stza.co/+vrEO-27

Shop  https //stza.co/+vrEO-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Dragons
END:VALARM
DTSTART:20180409T230000Z
DTEND:20180410T020000Z
UID:PjDpR8ajss_THkmx2Schd6ct@stanza.co
SUMMARY:Captains @ Dragons
DESCRIPTION:Captains @ Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+vrEO-27\n\nShop: https://stza.co/+vrEO-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Dragons
<2018-04-10 Tue 18:00-21:00>
:PROPERTIES:
:ID:       xZAXj4zG7-br0vjO-MqYluc7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Dragons Captains @ Dragons

Follow on MiLB First Pitch  https //stza.co/+vrER-1r

Shop  https //stza.co/+vrER-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Dragons
END:VALARM
DTSTART:20180410T230000Z
DTEND:20180411T020000Z
UID:xZAXj4zG7-br0vjO-MqYluc7@stanza.co
SUMMARY:Captains @ Dragons
DESCRIPTION:Captains @ Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+vrER-1r\n\nShop: https://stza.co/+vrER-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Dragons
<2018-04-11 Wed 18:00-21:00>
:PROPERTIES:
:ID:       2kOfbtu_6W-u-tMJDQc3Pd-V@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Dragons Captains @ Dragons

Follow on MiLB First Pitch  https //stza.co/+vrEY-24

Shop  https //stza.co/+vrEY-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Dragons
END:VALARM
DTSTART:20180411T230000Z
DTEND:20180412T020000Z
UID:2kOfbtu_6W-u-tMJDQc3Pd-V@stanza.co
SUMMARY:Captains @ Dragons
DESCRIPTION:Captains @ Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+vrEY-24\n\nShop: https://stza.co/+vrEY-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Dragons
<2018-04-12 Thu 18:00-21:00>
:PROPERTIES:
:ID:       NZ_fX9CH6APgwqRwaR8RjVlr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains @ Dragons Captains @ Dragons

Follow on MiLB First Pitch  https //stza.co/+vrF1-1v

Shop  https //stza.co/+vrF1-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Dragons
END:VALARM
DTSTART:20180412T230000Z
DTEND:20180413T020000Z
UID:NZ_fX9CH6APgwqRwaR8RjVlr@stanza.co
SUMMARY:Captains @ Dragons
DESCRIPTION:Captains @ Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+vrF1-1v\n\nShop: https://stza.co/+vrF1-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Cubs
<2018-04-13 Fri 17:30-20:30>
:PROPERTIES:
:ID:       vDT8_U55Rd8VIzpRa7iUwZ_4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Cubs Captains vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+xAAi-2f

Shop  https //stza.co/+xAAi-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Cubs
END:VALARM
DTSTART:20180413T223000Z
DTEND:20180414T013000Z
UID:vDT8_U55Rd8VIzpRa7iUwZ_4@stanza.co
SUMMARY:Captains vs. Cubs
DESCRIPTION:Captains vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+xAAi-2f\n\nShop: https://stza.co/+xAAi-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Cubs
<2018-04-14 Sat 15:00-18:00>
:PROPERTIES:
:ID:       COZktFF0hPlIfTDq0TuTPxlQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Cubs Captains vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+xAAk-16

Shop  https //stza.co/+xAAk-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Cubs
END:VALARM
DTSTART:20180414T200000Z
DTEND:20180414T230000Z
UID:COZktFF0hPlIfTDq0TuTPxlQ@stanza.co
SUMMARY:Captains vs. Cubs
DESCRIPTION:Captains vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+xAAk-16\n\nShop: https://stza.co/+xAAk-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Cubs
<2018-04-15 Sun 12:30-15:30>
:PROPERTIES:
:ID:       Ck6STLO_m9W3qwrMG9fJjAM_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains vs. Cubs Captains vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+xAAn-2N

Shop  https //stza.co/+xAAn-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Cubs
END:VALARM
DTSTART:20180415T173000Z
DTEND:20180415T203000Z
UID:Ck6STLO_m9W3qwrMG9fJjAM_@stanza.co
SUMMARY:Captains vs. Cubs
DESCRIPTION:Captains vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+xAAn-2N\n\nShop: https://stza.co/+xAAn-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Lugnuts
<2018-04-17 Tue 18:05-21:05>
:PROPERTIES:
:ID:       xHHemInvkxBmoSjwvGk7DrG4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Lugnuts Captains @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vrY7-2O

Shop  https //stza.co/+vrY7-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Lugnuts
END:VALARM
DTSTART:20180417T230500Z
DTEND:20180418T020500Z
UID:xHHemInvkxBmoSjwvGk7DrG4@stanza.co
SUMMARY:Captains @ Lugnuts
DESCRIPTION:Captains @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vrY7-2O\n\nShop: https://stza.co/+vrY7-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Lugnuts
<2018-04-18 Wed 18:05-21:05>
:PROPERTIES:
:ID:       xmuMrpgjE3HlnWuuMt2MLjDa@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Lugnuts Captains @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vrYp-3v

Shop  https //stza.co/+vrYp-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Lugnuts
END:VALARM
DTSTART:20180418T230500Z
DTEND:20180419T020500Z
UID:xmuMrpgjE3HlnWuuMt2MLjDa@stanza.co
SUMMARY:Captains @ Lugnuts
DESCRIPTION:Captains @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vrYp-3v\n\nShop: https://stza.co/+vrYp-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Lugnuts
<2018-04-19 Thu 18:05-21:05>
:PROPERTIES:
:ID:       HOHNMldEB37pTurU1Hrhb052@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains @ Lugnuts Captains @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vrYE-1r

Shop  https //stza.co/+vrYE-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Lugnuts
END:VALARM
DTSTART:20180419T230500Z
DTEND:20180420T020500Z
UID:HOHNMldEB37pTurU1Hrhb052@stanza.co
SUMMARY:Captains @ Lugnuts
DESCRIPTION:Captains @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vrYE-1r\n\nShop: https://stza.co/+vrYE-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Hot Rods
<2018-04-20 Fri 17:30-20:30>
:PROPERTIES:
:ID:       _m368AZoK-wBynpDxXabfxnz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Hot Rods Captains vs. Hot Rods

Follow on MiLB First Pitch  https //stza.co/+xAAp-1e

Shop  https //stza.co/+xAAp-3_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Hot Rods
END:VALARM
DTSTART:20180420T223000Z
DTEND:20180421T013000Z
UID:_m368AZoK-wBynpDxXabfxnz@stanza.co
SUMMARY:Captains vs. Hot Rods
DESCRIPTION:Captains vs. Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+xAAp-1e\n\nShop: https://stza.co/+xAAp-3_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Hot Rods
<2018-04-21 Sat 17:30-20:30>
:PROPERTIES:
:ID:       SeGvQgHIuVbqqhfAr_Z5wokd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Hot Rods Captains vs. Hot Rods

Follow on MiLB First Pitch  https //stza.co/+xAAr-2v

Shop  https //stza.co/+xAAr-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Hot Rods
END:VALARM
DTSTART:20180421T223000Z
DTEND:20180422T013000Z
UID:SeGvQgHIuVbqqhfAr_Z5wokd@stanza.co
SUMMARY:Captains vs. Hot Rods
DESCRIPTION:Captains vs. Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+xAAr-2v\n\nShop: https://stza.co/+xAAr-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Hot Rods
<2018-04-22 Sun 12:30-15:30>
:PROPERTIES:
:ID:       -CMvip0EWG83FmRtAO-w_eM7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains vs. Hot Rods Captains vs. Hot Rods

Follow on MiLB First Pitch  https //stza.co/+xAAu-f

Shop  https //stza.co/+xAAu-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Hot Rods
END:VALARM
DTSTART:20180422T173000Z
DTEND:20180422T203000Z
UID:-CMvip0EWG83FmRtAO-w_eM7@stanza.co
SUMMARY:Captains vs. Hot Rods
DESCRIPTION:Captains vs. Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+xAAu-f\n\nShop: https://stza.co/+xAAu-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Whitecaps
<2018-04-23 Mon 17:30-20:30>
:PROPERTIES:
:ID:       FoTTakJUP0nc0tjn_gzma75N@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Whitecaps Captains vs. Whitecaps

Follow on MiLB First Pitch  https //stza.co/+xAAy-1g

Shop  https //stza.co/+xAAy-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Whitecaps
END:VALARM
DTSTART:20180423T223000Z
DTEND:20180424T013000Z
UID:FoTTakJUP0nc0tjn_gzma75N@stanza.co
SUMMARY:Captains vs. Whitecaps
DESCRIPTION:Captains vs. Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+xAAy-1g\n\nShop: https://stza.co/+xAAy-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Whitecaps
<2018-04-24 Tue 17:30-20:30>
:PROPERTIES:
:ID:       1F9nvS6PFHuebxuwI2zcg5nX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Whitecaps Captains vs. Whitecaps

Follow on MiLB First Pitch  https //stza.co/+xAAA-22

Shop  https //stza.co/+xAAA-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Whitecaps
END:VALARM
DTSTART:20180424T223000Z
DTEND:20180425T013000Z
UID:1F9nvS6PFHuebxuwI2zcg5nX@stanza.co
SUMMARY:Captains vs. Whitecaps
DESCRIPTION:Captains vs. Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+xAAA-22\n\nShop: https://stza.co/+xAAA-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Whitecaps
<2018-04-25 Wed 17:30-20:30>
:PROPERTIES:
:ID:       Qg0PiuiBi_fv6qPTcmLCg8_j@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains vs. Whitecaps Captains vs. Whitecaps

Follow on MiLB First Pitch  https //stza.co/+xAAC-R

Shop  https //stza.co/+xAAC-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Whitecaps
END:VALARM
DTSTART:20180425T223000Z
DTEND:20180426T013000Z
UID:Qg0PiuiBi_fv6qPTcmLCg8_j@stanza.co
SUMMARY:Captains vs. Whitecaps
DESCRIPTION:Captains vs. Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+xAAC-R\n\nShop: https://stza.co/+xAAC-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Whitecaps
<2018-04-26 Thu 11:00-14:00>
:PROPERTIES:
:ID:       oNiVsHLOX1_KQCYKgdtZ0fEd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Whitecaps Captains vs. Whitecaps

Follow on MiLB First Pitch  https //stza.co/+xAAE-

Shop  https //stza.co/+xAAE-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Whitecaps
END:VALARM
DTSTART:20180426T160000Z
DTEND:20180426T190000Z
UID:oNiVsHLOX1_KQCYKgdtZ0fEd@stanza.co
SUMMARY:Captains vs. Whitecaps
DESCRIPTION:Captains vs. Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+xAAE-\n\nShop: https://stza.co/+xAAE-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Hot Rods
<2018-04-27 Fri 18:35-21:35>
:PROPERTIES:
:ID:       hPIThzKCbp4mTyRZt4gHPcg4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Hot Rods Captains @ Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vN8K-q

Shop  https //stza.co/+vN8K-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Hot Rods
END:VALARM
DTSTART:20180427T233500Z
DTEND:20180428T023500Z
UID:hPIThzKCbp4mTyRZt4gHPcg4@stanza.co
SUMMARY:Captains @ Hot Rods
DESCRIPTION:Captains @ Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vN8K-q\n\nShop: https://stza.co/+vN8K-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Hot Rods
<2018-04-28 Sat 18:35-21:35>
:PROPERTIES:
:ID:       JsX7ZiQIgV-yGFuzoztnn0nt@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains @ Hot Rods Captains @ Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vN8L-2H

Shop  https //stza.co/+vN8L-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Hot Rods
END:VALARM
DTSTART:20180428T233500Z
DTEND:20180429T023500Z
UID:JsX7ZiQIgV-yGFuzoztnn0nt@stanza.co
SUMMARY:Captains @ Hot Rods
DESCRIPTION:Captains @ Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vN8L-2H\n\nShop: https://stza.co/+vN8L-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Hot Rods
<2018-04-29 Sun 14:05-17:05>
:PROPERTIES:
:ID:       7dQvXjz27Ib0Fak8163mq5Ws@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Hot Rods Captains @ Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vN8M-_

Shop  https //stza.co/+vN8M-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Hot Rods
END:VALARM
DTSTART:20180429T190500Z
DTEND:20180429T220500Z
UID:7dQvXjz27Ib0Fak8163mq5Ws@stanza.co
SUMMARY:Captains @ Hot Rods
DESCRIPTION:Captains @ Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vN8M-_\n\nShop: https://stza.co/+vN8M-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Timber Rattlers
<2018-05-01 Tue 17:30-20:30>
:PROPERTIES:
:ID:       3RHsvKC45eEGRg0FUfT068g3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Timber Rattlers Captains vs. Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+xAAG-X

Shop  https //stza.co/+xAAG-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Timber Rattlers
END:VALARM
DTSTART:20180501T223000Z
DTEND:20180502T013000Z
UID:3RHsvKC45eEGRg0FUfT068g3@stanza.co
SUMMARY:Captains vs. Timber Rattlers
DESCRIPTION:Captains vs. Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+xAAG-X\n\nShop: https://stza.co/+xAAG-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Timber Rattlers
<2018-05-02 Wed 10:00-13:00>
:PROPERTIES:
:ID:       Emp2gsjBNBdgqaBKCN8XKo0m@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains vs. Timber Rattlers Captains vs. Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+xAAJ-y

Shop  https //stza.co/+xAAJ-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Timber Rattlers
END:VALARM
DTSTART:20180502T150000Z
DTEND:20180502T180000Z
UID:Emp2gsjBNBdgqaBKCN8XKo0m@stanza.co
SUMMARY:Captains vs. Timber Rattlers
DESCRIPTION:Captains vs. Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+xAAJ-y\n\nShop: https://stza.co/+xAAJ-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Timber Rattlers
<2018-05-03 Thu 17:30-20:30>
:PROPERTIES:
:ID:       q4GYAqOmRHWPCDRoutVajri_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Timber Rattlers Captains vs. Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+xAAM-1h

Shop  https //stza.co/+xAAM-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Timber Rattlers
END:VALARM
DTSTART:20180503T223000Z
DTEND:20180504T013000Z
UID:q4GYAqOmRHWPCDRoutVajri_@stanza.co
SUMMARY:Captains vs. Timber Rattlers
DESCRIPTION:Captains vs. Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+xAAM-1h\n\nShop: https://stza.co/+xAAM-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Snappers
<2018-05-04 Fri 17:30-20:30>
:PROPERTIES:
:ID:       HoRyuYkiom36pIV4ksl_ULn5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Snappers Captains vs. Snappers

Follow on MiLB First Pitch  https //stza.co/+xAAP-Q

Shop  https //stza.co/+xAAP-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Snappers
END:VALARM
DTSTART:20180504T223000Z
DTEND:20180505T013000Z
UID:HoRyuYkiom36pIV4ksl_ULn5@stanza.co
SUMMARY:Captains vs. Snappers
DESCRIPTION:Captains vs. Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+xAAP-Q\n\nShop: https://stza.co/+xAAP-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Snappers
<2018-05-05 Sat 17:30-20:30>
:PROPERTIES:
:ID:       ndm1kNdXCplwqSgOgTBPIstB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains vs. Snappers Captains vs. Snappers

Follow on MiLB First Pitch  https //stza.co/+xAAQ-H

Shop  https //stza.co/+xAAQ-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Snappers
END:VALARM
DTSTART:20180505T223000Z
DTEND:20180506T013000Z
UID:ndm1kNdXCplwqSgOgTBPIstB@stanza.co
SUMMARY:Captains vs. Snappers
DESCRIPTION:Captains vs. Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+xAAQ-H\n\nShop: https://stza.co/+xAAQ-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Snappers
<2018-05-06 Sun 12:30-15:30>
:PROPERTIES:
:ID:       j3tN15uHhLJ1HFmVVzzQNAeg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Snappers Captains vs. Snappers

Follow on MiLB First Pitch  https //stza.co/+xAAU-g

Shop  https //stza.co/+xAAU-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Snappers
END:VALARM
DTSTART:20180506T173000Z
DTEND:20180506T203000Z
UID:j3tN15uHhLJ1HFmVVzzQNAeg@stanza.co
SUMMARY:Captains vs. Snappers
DESCRIPTION:Captains vs. Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+xAAU-g\n\nShop: https://stza.co/+xAAU-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Cougars
<2018-05-07 Mon 18:30-21:30>
:PROPERTIES:
:ID:       2pIaWRGm95_KR0_5GC7rmfUf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Cougars Captains @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xAA8-1i

Shop  https //stza.co/+xAA8-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Cougars
END:VALARM
DTSTART:20180507T233000Z
DTEND:20180508T023000Z
UID:2pIaWRGm95_KR0_5GC7rmfUf@stanza.co
SUMMARY:Captains @ Cougars
DESCRIPTION:Captains @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xAA8-1i\n\nShop: https://stza.co/+xAA8-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Cougars
<2018-05-08 Tue 12:00-15:00>
:PROPERTIES:
:ID:       UPKjjs38nriHZg_6UswQdaRo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains @ Cougars Captains @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xAA9-p

Shop  https //stza.co/+xAA9-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Cougars
END:VALARM
DTSTART:20180508T170000Z
DTEND:20180508T200000Z
UID:UPKjjs38nriHZg_6UswQdaRo@stanza.co
SUMMARY:Captains @ Cougars
DESCRIPTION:Captains @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xAA9-p\n\nShop: https://stza.co/+xAA9-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Cougars
<2018-05-09 Wed 11:00-14:00>
:PROPERTIES:
:ID:       kCz_8aH79KRHHRgT89V-v8Je@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Cougars Captains @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xAAc-1v

Shop  https //stza.co/+xAAc-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Cougars
END:VALARM
DTSTART:20180509T160000Z
DTEND:20180509T190000Z
UID:kCz_8aH79KRHHRgT89V-v8Je@stanza.co
SUMMARY:Captains @ Cougars
DESCRIPTION:Captains @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xAAc-1v\n\nShop: https://stza.co/+xAAc-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ River Bandits
<2018-05-10 Thu 18:35-21:35>
:PROPERTIES:
:ID:       DnGfaXlfzHBr9TVBRZRVmARx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ River Bandits Captains @ River Bandits

Follow on MiLB First Pitch  https //stza.co/+wxpu-1b

Shop  https //stza.co/+wxpu-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ River Bandits
END:VALARM
DTSTART:20180510T233500Z
DTEND:20180511T023500Z
UID:DnGfaXlfzHBr9TVBRZRVmARx@stanza.co
SUMMARY:Captains @ River Bandits
DESCRIPTION:Captains @ River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wxpu-1b\n\nShop: https://stza.co/+wxpu-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ River Bandits
<2018-05-11 Fri 18:35-21:35>
:PROPERTIES:
:ID:       TWaU9gYVza9vaauxuQBEkd1d@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains @ River Bandits Captains @ River Bandits

Follow on MiLB First Pitch  https //stza.co/+wxpv-2k

Shop  https //stza.co/+wxpv-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ River Bandits
END:VALARM
DTSTART:20180511T233500Z
DTEND:20180512T023500Z
UID:TWaU9gYVza9vaauxuQBEkd1d@stanza.co
SUMMARY:Captains @ River Bandits
DESCRIPTION:Captains @ River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wxpv-2k\n\nShop: https://stza.co/+wxpv-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ River Bandits
<2018-05-12 Sat 18:35-21:35>
:PROPERTIES:
:ID:       -Fajfkvlel4le2GaRxC1bh-y@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ River Bandits Captains @ River Bandits

Follow on MiLB First Pitch  https //stza.co/+wxpw-i

Shop  https //stza.co/+wxpw-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ River Bandits
END:VALARM
DTSTART:20180512T233500Z
DTEND:20180513T023500Z
UID:-Fajfkvlel4le2GaRxC1bh-y@stanza.co
SUMMARY:Captains @ River Bandits
DESCRIPTION:Captains @ River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wxpw-i\n\nShop: https://stza.co/+wxpw-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Cubs
<2018-05-14 Mon 17:30-20:30>
:PROPERTIES:
:ID:       jeVtHmRd71oAH4Lkl6f0g9yi@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Cubs Captains vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+xAAW-1o

Shop  https //stza.co/+xAAW-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Cubs
END:VALARM
DTSTART:20180514T223000Z
DTEND:20180515T013000Z
UID:jeVtHmRd71oAH4Lkl6f0g9yi@stanza.co
SUMMARY:Captains vs. Cubs
DESCRIPTION:Captains vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+xAAW-1o\n\nShop: https://stza.co/+xAAW-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Cubs
<2018-05-15 Tue 17:30-20:30>
:PROPERTIES:
:ID:       udzpTAqbsIBSm5gxiVKe-8SF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains vs. Cubs Captains vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+xAAY-a

Shop  https //stza.co/+xAAY-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Cubs
END:VALARM
DTSTART:20180515T223000Z
DTEND:20180516T013000Z
UID:udzpTAqbsIBSm5gxiVKe-8SF@stanza.co
SUMMARY:Captains vs. Cubs
DESCRIPTION:Captains vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+xAAY-a\n\nShop: https://stza.co/+xAAY-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Cubs
<2018-05-16 Wed 17:30-20:30>
:PROPERTIES:
:ID:       Tz8SG4ZaR_FF_QWGSSJI8TFO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Cubs Captains vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+xAA$-Y

Shop  https //stza.co/+xAA$-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Cubs
END:VALARM
DTSTART:20180516T223000Z
DTEND:20180517T013000Z
UID:Tz8SG4ZaR_FF_QWGSSJI8TFO@stanza.co
SUMMARY:Captains vs. Cubs
DESCRIPTION:Captains vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+xAA$-Y\n\nShop: https://stza.co/+xAA$-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Cubs
<2018-05-17 Thu 10:00-13:00>
:PROPERTIES:
:ID:       VXtIlhtdqASN00IiPxg62ylL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Cubs Captains vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+xAB3-3V

Shop  https //stza.co/+xAB3-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Cubs
END:VALARM
DTSTART:20180517T150000Z
DTEND:20180517T180000Z
UID:VXtIlhtdqASN00IiPxg62ylL@stanza.co
SUMMARY:Captains vs. Cubs
DESCRIPTION:Captains vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+xAB3-3V\n\nShop: https://stza.co/+xAB3-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Whitecaps
<2018-05-18 Fri 18:05-21:05>
:PROPERTIES:
:ID:       8-HJ1RubnucjQ-UOeh_m1ffG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains @ Whitecaps Captains @ Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vs2k-3L

Shop  https //stza.co/+vs2k-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Whitecaps
END:VALARM
DTSTART:20180518T230500Z
DTEND:20180519T020500Z
UID:8-HJ1RubnucjQ-UOeh_m1ffG@stanza.co
SUMMARY:Captains @ Whitecaps
DESCRIPTION:Captains @ Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vs2k-3L\n\nShop: https://stza.co/+vs2k-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Whitecaps
<2018-05-19 Sat 18:05-21:05>
:PROPERTIES:
:ID:       Hwx4L0mVfYZ65d7yn6qKgp0u@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Whitecaps Captains @ Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vs2t-3D

Shop  https //stza.co/+vs2t-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Whitecaps
END:VALARM
DTSTART:20180519T230500Z
DTEND:20180520T020500Z
UID:Hwx4L0mVfYZ65d7yn6qKgp0u@stanza.co
SUMMARY:Captains @ Whitecaps
DESCRIPTION:Captains @ Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vs2t-3D\n\nShop: https://stza.co/+vs2t-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Whitecaps
<2018-05-20 Sun 13:00-16:00>
:PROPERTIES:
:ID:       qbgBa4VCIK1MpThHtUpjhdF3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Whitecaps Captains @ Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vs2K-36

Shop  https //stza.co/+vs2K-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Whitecaps
END:VALARM
DTSTART:20180520T180000Z
DTEND:20180520T210000Z
UID:qbgBa4VCIK1MpThHtUpjhdF3@stanza.co
SUMMARY:Captains @ Whitecaps
DESCRIPTION:Captains @ Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vs2K-36\n\nShop: https://stza.co/+vs2K-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Dragons
<2018-05-21 Mon 18:00-21:00>
:PROPERTIES:
:ID:       auSW1Sw7Jg_2TRyBjc16h4ns@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains @ Dragons Captains @ Dragons

Follow on MiLB First Pitch  https //stza.co/+vrFa-3O

Shop  https //stza.co/+vrFa-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Dragons
END:VALARM
DTSTART:20180521T230000Z
DTEND:20180522T020000Z
UID:auSW1Sw7Jg_2TRyBjc16h4ns@stanza.co
SUMMARY:Captains @ Dragons
DESCRIPTION:Captains @ Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+vrFa-3O\n\nShop: https://stza.co/+vrFa-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Dragons
<2018-05-22 Tue 18:00-21:00>
:PROPERTIES:
:ID:       _G2k4y97ykYq0mQjnTJ4o5B5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Dragons Captains @ Dragons

Follow on MiLB First Pitch  https //stza.co/+vrFg-2l

Shop  https //stza.co/+vrFg-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Dragons
END:VALARM
DTSTART:20180522T230000Z
DTEND:20180523T020000Z
UID:_G2k4y97ykYq0mQjnTJ4o5B5@stanza.co
SUMMARY:Captains @ Dragons
DESCRIPTION:Captains @ Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+vrFg-2l\n\nShop: https://stza.co/+vrFg-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Dragons
<2018-05-23 Wed 18:00-21:00>
:PROPERTIES:
:ID:       1yjFE9JKwwypKsdmvk0UsJVS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Dragons Captains @ Dragons

Follow on MiLB First Pitch  https //stza.co/+vrFj-1n

Shop  https //stza.co/+vrFj-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Dragons
END:VALARM
DTSTART:20180523T230000Z
DTEND:20180524T020000Z
UID:1yjFE9JKwwypKsdmvk0UsJVS@stanza.co
SUMMARY:Captains @ Dragons
DESCRIPTION:Captains @ Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+vrFj-1n\n\nShop: https://stza.co/+vrFj-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Dragons
<2018-05-24 Thu 18:00-21:00>
:PROPERTIES:
:ID:       hJMMUIVOpfA1QZPBMzJWNDUO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains @ Dragons Captains @ Dragons

Follow on MiLB First Pitch  https //stza.co/+vrFs-39

Shop  https //stza.co/+vrFs-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Dragons
END:VALARM
DTSTART:20180524T230000Z
DTEND:20180525T020000Z
UID:hJMMUIVOpfA1QZPBMzJWNDUO@stanza.co
SUMMARY:Captains @ Dragons
DESCRIPTION:Captains @ Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+vrFs-39\n\nShop: https://stza.co/+vrFs-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Loons
<2018-05-25 Fri 17:30-20:30>
:PROPERTIES:
:ID:       jWC2K2Ifuo0-MpsdSJD8MuiM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Loons Captains vs. Loons

Follow on MiLB First Pitch  https //stza.co/+xAB5-1d

Shop  https //stza.co/+xAB5-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Loons
END:VALARM
DTSTART:20180525T223000Z
DTEND:20180526T013000Z
UID:jWC2K2Ifuo0-MpsdSJD8MuiM@stanza.co
SUMMARY:Captains vs. Loons
DESCRIPTION:Captains vs. Loons\n\nFollow on MiLB First Pitch: https://stza.co/+xAB5-1d\n\nShop: https://stza.co/+xAB5-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Loons
<2018-05-26 Sat 17:30-20:30>
:PROPERTIES:
:ID:       _l56Gz5Nc6e3uBpIVPVUZbiK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Loons Captains vs. Loons

Follow on MiLB First Pitch  https //stza.co/+xAB6-2_

Shop  https //stza.co/+xAB6-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Loons
END:VALARM
DTSTART:20180526T223000Z
DTEND:20180527T013000Z
UID:_l56Gz5Nc6e3uBpIVPVUZbiK@stanza.co
SUMMARY:Captains vs. Loons
DESCRIPTION:Captains vs. Loons\n\nFollow on MiLB First Pitch: https://stza.co/+xAB6-2_\n\nShop: https://stza.co/+xAB6-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Loons
<2018-05-27 Sun 12:30-15:30>
:PROPERTIES:
:ID:       lNj4gaoY77uvqQN2QD98-_4y@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains vs. Loons Captains vs. Loons

Follow on MiLB First Pitch  https //stza.co/+xAB8-B

Shop  https //stza.co/+xAB8-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Loons
END:VALARM
DTSTART:20180527T173000Z
DTEND:20180527T203000Z
UID:lNj4gaoY77uvqQN2QD98-_4y@stanza.co
SUMMARY:Captains vs. Loons
DESCRIPTION:Captains vs. Loons\n\nFollow on MiLB First Pitch: https://stza.co/+xAB8-B\n\nShop: https://stza.co/+xAB8-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Loons
<2018-05-28 Mon 12:00-15:00>
:PROPERTIES:
:ID:       maVhVTwkFOBsQO6M_Yr8md7Q@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Loons Captains vs. Loons

Follow on MiLB First Pitch  https //stza.co/+xABb-2w

Shop  https //stza.co/+xABb-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Loons
END:VALARM
DTSTART:20180528T170000Z
DTEND:20180528T200000Z
UID:maVhVTwkFOBsQO6M_Yr8md7Q@stanza.co
SUMMARY:Captains vs. Loons
DESCRIPTION:Captains vs. Loons\n\nFollow on MiLB First Pitch: https://stza.co/+xABb-2w\n\nShop: https://stza.co/+xABb-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Lugnuts
<2018-05-29 Tue 18:05-21:05>
:PROPERTIES:
:ID:       -D8XtyCmT2gc-P0r6ia-cUPN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Lugnuts Captains @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vrYW-25

Shop  https //stza.co/+vrYW-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Lugnuts
END:VALARM
DTSTART:20180529T230500Z
DTEND:20180530T020500Z
UID:-D8XtyCmT2gc-P0r6ia-cUPN@stanza.co
SUMMARY:Captains @ Lugnuts
DESCRIPTION:Captains @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vrYW-25\n\nShop: https://stza.co/+vrYW-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Lugnuts
<2018-05-30 Wed 09:35-12:35>
:PROPERTIES:
:ID:       VY9rpOqfZu3zskvvdBhcl3W5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains @ Lugnuts Captains @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vrZ9-36

Shop  https //stza.co/+vrZ9-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Lugnuts
END:VALARM
DTSTART:20180530T143500Z
DTEND:20180530T173500Z
UID:VY9rpOqfZu3zskvvdBhcl3W5@stanza.co
SUMMARY:Captains @ Lugnuts
DESCRIPTION:Captains @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vrZ9-36\n\nShop: https://stza.co/+vrZ9-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Lugnuts
<2018-05-31 Thu 18:05-21:05>
:PROPERTIES:
:ID:       Jgh_8yFGtiILP3MryaU-XMTu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Lugnuts Captains @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vrZw-1H

Shop  https //stza.co/+vrZw-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Lugnuts
END:VALARM
DTSTART:20180531T230500Z
DTEND:20180601T020500Z
UID:Jgh_8yFGtiILP3MryaU-XMTu@stanza.co
SUMMARY:Captains @ Lugnuts
DESCRIPTION:Captains @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vrZw-1H\n\nShop: https://stza.co/+vrZw-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Cubs
<2018-06-01 Fri 18:35-21:35>
:PROPERTIES:
:ID:       M5upM5RRBz1ABRtSuahVGbsQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Cubs Captains @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vs0F-1G

Shop  https //stza.co/+vs0F-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Cubs
END:VALARM
DTSTART:20180601T233500Z
DTEND:20180602T023500Z
UID:M5upM5RRBz1ABRtSuahVGbsQ@stanza.co
SUMMARY:Captains @ Cubs
DESCRIPTION:Captains @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vs0F-1G\n\nShop: https://stza.co/+vs0F-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Cubs
<2018-06-02 Sat 18:05-21:05>
:PROPERTIES:
:ID:       0xb9W7oqW2UkvL9SjKbas1C3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains @ Cubs Captains @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vs10-1H

Shop  https //stza.co/+vs10-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Cubs
END:VALARM
DTSTART:20180602T230500Z
DTEND:20180603T020500Z
UID:0xb9W7oqW2UkvL9SjKbas1C3@stanza.co
SUMMARY:Captains @ Cubs
DESCRIPTION:Captains @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vs10-1H\n\nShop: https://stza.co/+vs10-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Cubs
<2018-06-03 Sun 13:05-16:05>
:PROPERTIES:
:ID:       dxzLxZqmtfBcobT3hGBD8bf2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Cubs Captains @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vs1c-2k

Shop  https //stza.co/+vs1c-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Cubs
END:VALARM
DTSTART:20180603T180500Z
DTEND:20180603T210500Z
UID:dxzLxZqmtfBcobT3hGBD8bf2@stanza.co
SUMMARY:Captains @ Cubs
DESCRIPTION:Captains @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vs1c-2k\n\nShop: https://stza.co/+vs1c-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Dragons
<2018-06-05 Tue 18:00-21:00>
:PROPERTIES:
:ID:       P04kkufZrnfNlfXjcpUDV8Ew@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Dragons Captains vs. Dragons

Follow on MiLB First Pitch  https //stza.co/+xABe-1c

Shop  https //stza.co/+xABe-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Dragons
END:VALARM
DTSTART:20180605T230000Z
DTEND:20180606T020000Z
UID:P04kkufZrnfNlfXjcpUDV8Ew@stanza.co
SUMMARY:Captains vs. Dragons
DESCRIPTION:Captains vs. Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+xABe-1c\n\nShop: https://stza.co/+xABe-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Dragons
<2018-06-06 Wed 18:00-21:00>
:PROPERTIES:
:ID:       6bKkBN5qx3mhvX3DtKp1ZAka@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains vs. Dragons Captains vs. Dragons

Follow on MiLB First Pitch  https //stza.co/+xABg-t

Shop  https //stza.co/+xABg-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Dragons
END:VALARM
DTSTART:20180606T230000Z
DTEND:20180607T020000Z
UID:6bKkBN5qx3mhvX3DtKp1ZAka@stanza.co
SUMMARY:Captains vs. Dragons
DESCRIPTION:Captains vs. Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+xABg-t\n\nShop: https://stza.co/+xABg-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Dragons
<2018-06-07 Thu 18:00-21:00>
:PROPERTIES:
:ID:       X92cN8VPIVgrMStrYL4pO-xK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Dragons Captains vs. Dragons

Follow on MiLB First Pitch  https //stza.co/+xABi-k

Shop  https //stza.co/+xABi-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Dragons
END:VALARM
DTSTART:20180607T230000Z
DTEND:20180608T020000Z
UID:X92cN8VPIVgrMStrYL4pO-xK@stanza.co
SUMMARY:Captains vs. Dragons
DESCRIPTION:Captains vs. Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+xABi-k\n\nShop: https://stza.co/+xABi-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Loons
<2018-06-08 Fri 18:05-21:05>
:PROPERTIES:
:ID:       xsGHN-2RM9uQ6eO6VfiTfcw1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Loons Captains @ Loons

Follow on MiLB First Pitch  https //stza.co/+vrGs-34

Shop  https //stza.co/+vrGs-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Loons
END:VALARM
DTSTART:20180608T230500Z
DTEND:20180609T020500Z
UID:xsGHN-2RM9uQ6eO6VfiTfcw1@stanza.co
SUMMARY:Captains @ Loons
DESCRIPTION:Captains @ Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vrGs-34\n\nShop: https://stza.co/+vrGs-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Loons
<2018-06-09 Sat 18:05-21:05>
:PROPERTIES:
:ID:       gLmaRWi347svCveWaKWAi6Sq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains @ Loons Captains @ Loons

Follow on MiLB First Pitch  https //stza.co/+vrGx-

Shop  https //stza.co/+vrGx-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Loons
END:VALARM
DTSTART:20180609T230500Z
DTEND:20180610T020500Z
UID:gLmaRWi347svCveWaKWAi6Sq@stanza.co
SUMMARY:Captains @ Loons
DESCRIPTION:Captains @ Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vrGx-\n\nShop: https://stza.co/+vrGx-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Loons
<2018-06-10 Sun 13:05-16:05>
:PROPERTIES:
:ID:       3I3bWSoURGpkOfTnDzK7R3r4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Loons Captains @ Loons

Follow on MiLB First Pitch  https //stza.co/+vrGC-2s

Shop  https //stza.co/+vrGC-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Loons
END:VALARM
DTSTART:20180610T180500Z
DTEND:20180610T210500Z
UID:3I3bWSoURGpkOfTnDzK7R3r4@stanza.co
SUMMARY:Captains @ Loons
DESCRIPTION:Captains @ Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vrGC-2s\n\nShop: https://stza.co/+vrGC-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Loons
<2018-06-11 Mon 18:05-21:05>
:PROPERTIES:
:ID:       2O__ohJ5yDEPvMeV1iO5OiZc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Loons Captains @ Loons

Follow on MiLB First Pitch  https //stza.co/+vrGL-30

Shop  https //stza.co/+vrGL-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Loons
END:VALARM
DTSTART:20180611T230500Z
DTEND:20180612T020500Z
UID:2O__ohJ5yDEPvMeV1iO5OiZc@stanza.co
SUMMARY:Captains @ Loons
DESCRIPTION:Captains @ Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vrGL-30\n\nShop: https://stza.co/+vrGL-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Lugnuts
<2018-06-12 Tue 18:00-21:00>
:PROPERTIES:
:ID:       M6yh0dQOQ6x9aFrQb2tA4HPE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains vs. Lugnuts Captains vs. Lugnuts

Follow on MiLB First Pitch  https //stza.co/+xABk-s

Shop  https //stza.co/+xABk-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Lugnuts
END:VALARM
DTSTART:20180612T230000Z
DTEND:20180613T020000Z
UID:M6yh0dQOQ6x9aFrQb2tA4HPE@stanza.co
SUMMARY:Captains vs. Lugnuts
DESCRIPTION:Captains vs. Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+xABk-s\n\nShop: https://stza.co/+xABk-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Lugnuts
<2018-06-13 Wed 11:00-14:00>
:PROPERTIES:
:ID:       o4Vb2rMVZsEmSVGm7Hsc2o4q@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Lugnuts Captains vs. Lugnuts

Follow on MiLB First Pitch  https //stza.co/+xABo-1x

Shop  https //stza.co/+xABo-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Lugnuts
END:VALARM
DTSTART:20180613T160000Z
DTEND:20180613T190000Z
UID:o4Vb2rMVZsEmSVGm7Hsc2o4q@stanza.co
SUMMARY:Captains vs. Lugnuts
DESCRIPTION:Captains vs. Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+xABo-1x\n\nShop: https://stza.co/+xABo-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Lugnuts
<2018-06-14 Thu 18:00-21:00>
:PROPERTIES:
:ID:       BNGtQwM5ErftO0pUG82nQFgy@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Lugnuts Captains vs. Lugnuts

Follow on MiLB First Pitch  https //stza.co/+xABr-2d

Shop  https //stza.co/+xABr-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Lugnuts
END:VALARM
DTSTART:20180614T230000Z
DTEND:20180615T020000Z
UID:BNGtQwM5ErftO0pUG82nQFgy@stanza.co
SUMMARY:Captains vs. Lugnuts
DESCRIPTION:Captains vs. Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+xABr-2d\n\nShop: https://stza.co/+xABr-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Hot Rods
<2018-06-15 Fri 18:00-21:00>
:PROPERTIES:
:ID:       fuyavK7QnIXQKXL9P6-QllGw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains vs. Hot Rods Captains vs. Hot Rods

Follow on MiLB First Pitch  https //stza.co/+xABs-1F

Shop  https //stza.co/+xABs-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Hot Rods
END:VALARM
DTSTART:20180615T230000Z
DTEND:20180616T020000Z
UID:fuyavK7QnIXQKXL9P6-QllGw@stanza.co
SUMMARY:Captains vs. Hot Rods
DESCRIPTION:Captains vs. Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+xABs-1F\n\nShop: https://stza.co/+xABs-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Hot Rods
<2018-06-16 Sat 18:00-21:00>
:PROPERTIES:
:ID:       B6Bn_FCLgHieibshkj-YDUa2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Hot Rods Captains vs. Hot Rods

Follow on MiLB First Pitch  https //stza.co/+xABu-1h

Shop  https //stza.co/+xABu-1J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Hot Rods
END:VALARM
DTSTART:20180616T230000Z
DTEND:20180617T020000Z
UID:B6Bn_FCLgHieibshkj-YDUa2@stanza.co
SUMMARY:Captains vs. Hot Rods
DESCRIPTION:Captains vs. Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+xABu-1h\n\nShop: https://stza.co/+xABu-1J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Hot Rods
<2018-06-17 Sun 15:00-18:00>
:PROPERTIES:
:ID:       wCfmWlR_a9UZWzNzy_iDiH5r@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Hot Rods Captains vs. Hot Rods

Follow on MiLB First Pitch  https //stza.co/+xABz-3v

Shop  https //stza.co/+xABz-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Hot Rods
END:VALARM
DTSTART:20180617T200000Z
DTEND:20180617T230000Z
UID:wCfmWlR_a9UZWzNzy_iDiH5r@stanza.co
SUMMARY:Captains vs. Hot Rods
DESCRIPTION:Captains vs. Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+xABz-3v\n\nShop: https://stza.co/+xABz-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Hot Rods
<2018-06-21 Thu 18:35-21:35>
:PROPERTIES:
:ID:       N8EJ6FCu08fo8E9S2t3Q_Rwe@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains @ Hot Rods Captains @ Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vN8N-j

Shop  https //stza.co/+vN8N-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Hot Rods
END:VALARM
DTSTART:20180621T233500Z
DTEND:20180622T023500Z
UID:N8EJ6FCu08fo8E9S2t3Q_Rwe@stanza.co
SUMMARY:Captains @ Hot Rods
DESCRIPTION:Captains @ Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vN8N-j\n\nShop: https://stza.co/+vN8N-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Hot Rods
<2018-06-22 Fri 18:35-21:35>
:PROPERTIES:
:ID:       RYzYAgpHuox7MGHcwgG3rP_g@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Hot Rods Captains @ Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vN8O-1S

Shop  https //stza.co/+vN8O-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Hot Rods
END:VALARM
DTSTART:20180622T233500Z
DTEND:20180623T023500Z
UID:RYzYAgpHuox7MGHcwgG3rP_g@stanza.co
SUMMARY:Captains @ Hot Rods
DESCRIPTION:Captains @ Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vN8O-1S\n\nShop: https://stza.co/+vN8O-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Hot Rods
<2018-06-23 Sat 18:35-21:35>
:PROPERTIES:
:ID:       ZoPW2FLXXU95HHyAh8rnUFn5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Hot Rods Captains @ Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vN8P-1R

Shop  https //stza.co/+vN8P-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Hot Rods
END:VALARM
DTSTART:20180623T233500Z
DTEND:20180624T023500Z
UID:ZoPW2FLXXU95HHyAh8rnUFn5@stanza.co
SUMMARY:Captains @ Hot Rods
DESCRIPTION:Captains @ Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vN8P-1R\n\nShop: https://stza.co/+vN8P-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Hot Rods
<2018-06-24 Sun 14:05-17:05>
:PROPERTIES:
:ID:       6BMbL1L2l32BEiFHuhMhkH__@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains @ Hot Rods Captains @ Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vN8Q-R

Shop  https //stza.co/+vN8Q-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Hot Rods
END:VALARM
DTSTART:20180624T190500Z
DTEND:20180624T220500Z
UID:6BMbL1L2l32BEiFHuhMhkH__@stanza.co
SUMMARY:Captains @ Hot Rods
DESCRIPTION:Captains @ Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vN8Q-R\n\nShop: https://stza.co/+vN8Q-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Lugnuts
<2018-06-25 Mon 18:05-21:05>
:PROPERTIES:
:ID:       C1ETwbWyyMWFSrSwky7qv8l1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Lugnuts Captains @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vrZQ-2O

Shop  https //stza.co/+vrZQ-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Lugnuts
END:VALARM
DTSTART:20180625T230500Z
DTEND:20180626T020500Z
UID:C1ETwbWyyMWFSrSwky7qv8l1@stanza.co
SUMMARY:Captains @ Lugnuts
DESCRIPTION:Captains @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vrZQ-2O\n\nShop: https://stza.co/+vrZQ-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Lugnuts
<2018-06-26 Tue 18:05-21:05>
:PROPERTIES:
:ID:       Lzsa92er4urFXLz4f8-8hWhm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Lugnuts Captains @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vr_6-1Q

Shop  https //stza.co/+vr_6-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Lugnuts
END:VALARM
DTSTART:20180626T230500Z
DTEND:20180627T020500Z
UID:Lzsa92er4urFXLz4f8-8hWhm@stanza.co
SUMMARY:Captains @ Lugnuts
DESCRIPTION:Captains @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vr_6-1Q\n\nShop: https://stza.co/+vr_6-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Lugnuts
<2018-06-27 Wed 11:05-14:05>
:PROPERTIES:
:ID:       OCd1Ok7AR1UwoQAxjmEQwYlt@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains @ Lugnuts Captains @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vr_n-3M

Shop  https //stza.co/+vr_n-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Lugnuts
END:VALARM
DTSTART:20180627T160500Z
DTEND:20180627T190500Z
UID:OCd1Ok7AR1UwoQAxjmEQwYlt@stanza.co
SUMMARY:Captains @ Lugnuts
DESCRIPTION:Captains @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vr_n-3M\n\nShop: https://stza.co/+vr_n-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. TinCaps
<2018-06-28 Thu 18:00-21:00>
:PROPERTIES:
:ID:       2FpI6x4-ifVgoBYia2VDuL0K@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. TinCaps Captains vs. TinCaps

Follow on MiLB First Pitch  https //stza.co/+xABB-2i

Shop  https //stza.co/+xABB-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. TinCaps
END:VALARM
DTSTART:20180628T230000Z
DTEND:20180629T020000Z
UID:2FpI6x4-ifVgoBYia2VDuL0K@stanza.co
SUMMARY:Captains vs. TinCaps
DESCRIPTION:Captains vs. TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+xABB-2i\n\nShop: https://stza.co/+xABB-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. TinCaps
<2018-06-29 Fri 18:00-21:00>
:PROPERTIES:
:ID:       ePx8sXHszZn8tqYcp_vzLela@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. TinCaps Captains vs. TinCaps

Follow on MiLB First Pitch  https //stza.co/+xABC-1g

Shop  https //stza.co/+xABC-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. TinCaps
END:VALARM
DTSTART:20180629T230000Z
DTEND:20180630T020000Z
UID:ePx8sXHszZn8tqYcp_vzLela@stanza.co
SUMMARY:Captains vs. TinCaps
DESCRIPTION:Captains vs. TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+xABC-1g\n\nShop: https://stza.co/+xABC-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. TinCaps
<2018-06-30 Sat 18:00-21:00>
:PROPERTIES:
:ID:       IBf03bXUgv8avXNS_QLuAnnn@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains vs. TinCaps Captains vs. TinCaps

Follow on MiLB First Pitch  https //stza.co/+xABF-w

Shop  https //stza.co/+xABF-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. TinCaps
END:VALARM
DTSTART:20180630T230000Z
DTEND:20180701T020000Z
UID:IBf03bXUgv8avXNS_QLuAnnn@stanza.co
SUMMARY:Captains vs. TinCaps
DESCRIPTION:Captains vs. TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+xABF-w\n\nShop: https://stza.co/+xABF-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. TinCaps
<2018-07-01 Sun 15:00-18:00>
:PROPERTIES:
:ID:       E4NFDskuFsXpTRS6ycndtRrF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. TinCaps Captains vs. TinCaps

Follow on MiLB First Pitch  https //stza.co/+xABI-1j

Shop  https //stza.co/+xABI-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. TinCaps
END:VALARM
DTSTART:20180701T200000Z
DTEND:20180701T230000Z
UID:E4NFDskuFsXpTRS6ycndtRrF@stanza.co
SUMMARY:Captains vs. TinCaps
DESCRIPTION:Captains vs. TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+xABI-1j\n\nShop: https://stza.co/+xABI-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Dragons
<2018-07-02 Mon 18:00-21:00>
:PROPERTIES:
:ID:       OvARSmaR3-YU3rUqsMp8oyyM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Dragons Captains vs. Dragons

Follow on MiLB First Pitch  https //stza.co/+xABL-E

Shop  https //stza.co/+xABL-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Dragons
END:VALARM
DTSTART:20180702T230000Z
DTEND:20180703T020000Z
UID:OvARSmaR3-YU3rUqsMp8oyyM@stanza.co
SUMMARY:Captains vs. Dragons
DESCRIPTION:Captains vs. Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+xABL-E\n\nShop: https://stza.co/+xABL-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Dragons
<2018-07-03 Tue 18:00-21:00>
:PROPERTIES:
:ID:       ZLfBuUU97Dqlfx0JtS-7kPLc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains vs. Dragons Captains vs. Dragons

Follow on MiLB First Pitch  https //stza.co/+xABO-1r

Shop  https //stza.co/+xABO-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Dragons
END:VALARM
DTSTART:20180703T230000Z
DTEND:20180704T020000Z
UID:ZLfBuUU97Dqlfx0JtS-7kPLc@stanza.co
SUMMARY:Captains vs. Dragons
DESCRIPTION:Captains vs. Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+xABO-1r\n\nShop: https://stza.co/+xABO-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Dragons
<2018-07-04 Wed 18:00-21:00>
:PROPERTIES:
:ID:       NcN55YEG_Kkn5ZLugajUsx_v@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Dragons Captains @ Dragons

Follow on MiLB First Pitch  https //stza.co/+vrFy-2E

Shop  https //stza.co/+vrFy-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Dragons
END:VALARM
DTSTART:20180704T230000Z
DTEND:20180705T020000Z
UID:NcN55YEG_Kkn5ZLugajUsx_v@stanza.co
SUMMARY:Captains @ Dragons
DESCRIPTION:Captains @ Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+vrFy-2E\n\nShop: https://stza.co/+vrFy-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Dragons
<2018-07-05 Thu 18:00-21:00>
:PROPERTIES:
:ID:       7JEj4bb6cCzgucFsMTZqcv5b@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Dragons Captains @ Dragons

Follow on MiLB First Pitch  https //stza.co/+vrFD-q

Shop  https //stza.co/+vrFD-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Dragons
END:VALARM
DTSTART:20180705T230000Z
DTEND:20180706T020000Z
UID:7JEj4bb6cCzgucFsMTZqcv5b@stanza.co
SUMMARY:Captains @ Dragons
DESCRIPTION:Captains @ Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+vrFD-q\n\nShop: https://stza.co/+vrFD-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Whitecaps
<2018-07-06 Fri 18:00-21:00>
:PROPERTIES:
:ID:       0qiHAFepIkcaRu9BJaTAvqwZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains vs. Whitecaps Captains vs. Whitecaps

Follow on MiLB First Pitch  https //stza.co/+xABQ-B

Shop  https //stza.co/+xABQ-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Whitecaps
END:VALARM
DTSTART:20180706T230000Z
DTEND:20180707T020000Z
UID:0qiHAFepIkcaRu9BJaTAvqwZ@stanza.co
SUMMARY:Captains vs. Whitecaps
DESCRIPTION:Captains vs. Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+xABQ-B\n\nShop: https://stza.co/+xABQ-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Whitecaps
<2018-07-07 Sat 18:00-21:00>
:PROPERTIES:
:ID:       jTbYj5U-dH1XuiiyaRIPVORn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Whitecaps Captains vs. Whitecaps

Follow on MiLB First Pitch  https //stza.co/+xABS-2_

Shop  https //stza.co/+xABS-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Whitecaps
END:VALARM
DTSTART:20180707T230000Z
DTEND:20180708T020000Z
UID:jTbYj5U-dH1XuiiyaRIPVORn@stanza.co
SUMMARY:Captains vs. Whitecaps
DESCRIPTION:Captains vs. Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+xABS-2_\n\nShop: https://stza.co/+xABS-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Whitecaps
<2018-07-08 Sun 12:30-15:30>
:PROPERTIES:
:ID:       E33HrlosM_fFA1pfvcyfLaXl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Whitecaps Captains vs. Whitecaps

Follow on MiLB First Pitch  https //stza.co/+xABW-2h

Shop  https //stza.co/+xABW-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Whitecaps
END:VALARM
DTSTART:20180708T173000Z
DTEND:20180708T203000Z
UID:E33HrlosM_fFA1pfvcyfLaXl@stanza.co
SUMMARY:Captains vs. Whitecaps
DESCRIPTION:Captains vs. Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+xABW-2h\n\nShop: https://stza.co/+xABW-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Whitecaps
<2018-07-09 Mon 18:00-21:00>
:PROPERTIES:
:ID:       mAfWX5INFRvBzWOh3nadjGTl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains vs. Whitecaps Captains vs. Whitecaps

Follow on MiLB First Pitch  https //stza.co/+xABZ-c

Shop  https //stza.co/+xABZ-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Whitecaps
END:VALARM
DTSTART:20180709T230000Z
DTEND:20180710T020000Z
UID:mAfWX5INFRvBzWOh3nadjGTl@stanza.co
SUMMARY:Captains vs. Whitecaps
DESCRIPTION:Captains vs. Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+xABZ-c\n\nShop: https://stza.co/+xABZ-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Chiefs
<2018-07-11 Wed 19:00-22:00>
:PROPERTIES:
:ID:       lDorIRfJXrbyq_sOgI76TNVX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Chiefs Captains @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xACY-2U

Shop  https //stza.co/+xACY-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Chiefs
END:VALARM
DTSTART:20180712T000000Z
DTEND:20180712T030000Z
UID:lDorIRfJXrbyq_sOgI76TNVX@stanza.co
SUMMARY:Captains @ Chiefs
DESCRIPTION:Captains @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xACY-2U\n\nShop: https://stza.co/+xACY-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Chiefs
<2018-07-12 Thu 19:00-22:00>
:PROPERTIES:
:ID:       g7jk7dVG51x-kTvgll4AbALb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Chiefs Captains @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xAC_-1r

Shop  https //stza.co/+xAC_-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Chiefs
END:VALARM
DTSTART:20180713T000000Z
DTEND:20180713T030000Z
UID:g7jk7dVG51x-kTvgll4AbALb@stanza.co
SUMMARY:Captains @ Chiefs
DESCRIPTION:Captains @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xAC_-1r\n\nShop: https://stza.co/+xAC_-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Chiefs
<2018-07-13 Fri 19:00-22:00>
:PROPERTIES:
:ID:       oUpIWR0YYmxfzxcEtWzbuYyj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains @ Chiefs Captains @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xAC$-2D

Shop  https //stza.co/+xAC$-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Chiefs
END:VALARM
DTSTART:20180714T000000Z
DTEND:20180714T030000Z
UID:oUpIWR0YYmxfzxcEtWzbuYyj@stanza.co
SUMMARY:Captains @ Chiefs
DESCRIPTION:Captains @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xAC$-2D\n\nShop: https://stza.co/+xAC$-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Kernels
<2018-07-14 Sat 18:35-21:35>
:PROPERTIES:
:ID:       GCneco-vqx6h07erYNQ18w0a@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Kernels Captains @ Kernels

Buy tickets here  https //stza.co/~vN8V

Follow on MiLB First Pitch  https //stza.co/+vN8V-u

Shop  https //stza.co/+vN8V-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Kernels
END:VALARM
DTSTART:20180714T233500Z
DTEND:20180715T023500Z
UID:GCneco-vqx6h07erYNQ18w0a@stanza.co
SUMMARY:Captains @ Kernels
DESCRIPTION:Captains @ Kernels\n\nBuy tickets here: https://stza.co/~vN8V\n\nFollow on MiLB First Pitch: https://stza.co/+vN8V-u\n\nShop: https://stza.co/+vN8V-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Kernels
<2018-07-15 Sun 14:05-17:05>
:PROPERTIES:
:ID:       aYgXfto_92an1xwbekG7sT4m@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Kernels Captains @ Kernels

Buy tickets here  https //stza.co/~vN8W

Follow on MiLB First Pitch  https //stza.co/+vN8W-3N

Shop  https //stza.co/+vN8W-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Kernels
END:VALARM
DTSTART:20180715T190500Z
DTEND:20180715T220500Z
UID:aYgXfto_92an1xwbekG7sT4m@stanza.co
SUMMARY:Captains @ Kernels
DESCRIPTION:Captains @ Kernels\n\nBuy tickets here: https://stza.co/~vN8W\n\nFollow on MiLB First Pitch: https://stza.co/+vN8W-3N\n\nShop: https://stza.co/+vN8W-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Kernels
<2018-07-16 Mon 11:05-14:05>
:PROPERTIES:
:ID:       u-Gl3-OnhQCk7tNu3C2OQxgT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains @ Kernels Captains @ Kernels

Buy tickets here  https //stza.co/~vN8X

Follow on MiLB First Pitch  https //stza.co/+vN8X-3I

Shop  https //stza.co/+vN8X-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Kernels
END:VALARM
DTSTART:20180716T160500Z
DTEND:20180716T190500Z
UID:u-Gl3-OnhQCk7tNu3C2OQxgT@stanza.co
SUMMARY:Captains @ Kernels
DESCRIPTION:Captains @ Kernels\n\nBuy tickets here: https://stza.co/~vN8X\n\nFollow on MiLB First Pitch: https://stza.co/+vN8X-3I\n\nShop: https://stza.co/+vN8X-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. LumberKings
<2018-07-18 Wed 18:00-21:00>
:PROPERTIES:
:ID:       ATaQVkictTZqgk4YJJ6LI6cO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. LumberKings Captains vs. LumberKings

Follow on MiLB First Pitch  https //stza.co/+xAB_-1e

Shop  https //stza.co/+xAB_-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. LumberKings
END:VALARM
DTSTART:20180718T230000Z
DTEND:20180719T020000Z
UID:ATaQVkictTZqgk4YJJ6LI6cO@stanza.co
SUMMARY:Captains vs. LumberKings
DESCRIPTION:Captains vs. LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+xAB_-1e\n\nShop: https://stza.co/+xAB_-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. LumberKings
<2018-07-19 Thu 10:00-13:00>
:PROPERTIES:
:ID:       QqOzZnImrMg5LqpNy_0llTxX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. LumberKings Captains vs. LumberKings

Follow on MiLB First Pitch  https //stza.co/+xAC0-2s

Shop  https //stza.co/+xAC0-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. LumberKings
END:VALARM
DTSTART:20180719T150000Z
DTEND:20180719T180000Z
UID:QqOzZnImrMg5LqpNy_0llTxX@stanza.co
SUMMARY:Captains vs. LumberKings
DESCRIPTION:Captains vs. LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+xAC0-2s\n\nShop: https://stza.co/+xAC0-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. LumberKings
<2018-07-20 Fri 18:00-21:00>
:PROPERTIES:
:ID:       c6qeFTTDmatyV0UEnjGETuYQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains vs. LumberKings Captains vs. LumberKings

Follow on MiLB First Pitch  https //stza.co/+xAC2-B

Shop  https //stza.co/+xAC2-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. LumberKings
END:VALARM
DTSTART:20180720T230000Z
DTEND:20180721T020000Z
UID:c6qeFTTDmatyV0UEnjGETuYQ@stanza.co
SUMMARY:Captains vs. LumberKings
DESCRIPTION:Captains vs. LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+xAC2-B\n\nShop: https://stza.co/+xAC2-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Bees
<2018-07-21 Sat 18:00-21:00>
:PROPERTIES:
:ID:       vrxVoSWfzumVos3TXscXGQen@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Bees Captains vs. Bees

Follow on MiLB First Pitch  https //stza.co/+xAC7-Z

Shop  https //stza.co/+xAC7-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Bees
END:VALARM
DTSTART:20180721T230000Z
DTEND:20180722T020000Z
UID:vrxVoSWfzumVos3TXscXGQen@stanza.co
SUMMARY:Captains vs. Bees
DESCRIPTION:Captains vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xAC7-Z\n\nShop: https://stza.co/+xAC7-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Bees
<2018-07-22 Sun 15:00-18:00>
:PROPERTIES:
:ID:       hlEndIhOPc9-Cqrj173HxWPb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Bees Captains vs. Bees

Follow on MiLB First Pitch  https //stza.co/+xAC8-u

Shop  https //stza.co/+xAC8-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Bees
END:VALARM
DTSTART:20180722T200000Z
DTEND:20180722T230000Z
UID:hlEndIhOPc9-Cqrj173HxWPb@stanza.co
SUMMARY:Captains vs. Bees
DESCRIPTION:Captains vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xAC8-u\n\nShop: https://stza.co/+xAC8-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Bees
<2018-07-23 Mon 18:00-21:00>
:PROPERTIES:
:ID:       7bXEaiCkKrI46mabMo5aSiip@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains vs. Bees Captains vs. Bees

Follow on MiLB First Pitch  https //stza.co/+xACa-3Z

Shop  https //stza.co/+xACa-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Bees
END:VALARM
DTSTART:20180723T230000Z
DTEND:20180724T020000Z
UID:7bXEaiCkKrI46mabMo5aSiip@stanza.co
SUMMARY:Captains vs. Bees
DESCRIPTION:Captains vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xACa-3Z\n\nShop: https://stza.co/+xACa-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Whitecaps
<2018-07-25 Wed 18:05-21:05>
:PROPERTIES:
:ID:       RWBLXOdD6L9HQ4BiJiow8jXM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Whitecaps Captains @ Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vs2X-2l

Shop  https //stza.co/+vs2X-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Whitecaps
END:VALARM
DTSTART:20180725T230500Z
DTEND:20180726T020500Z
UID:RWBLXOdD6L9HQ4BiJiow8jXM@stanza.co
SUMMARY:Captains @ Whitecaps
DESCRIPTION:Captains @ Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vs2X-2l\n\nShop: https://stza.co/+vs2X-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Whitecaps
<2018-07-26 Thu 18:05-21:05>
:PROPERTIES:
:ID:       NRhB5gVUUjdynU-xr59FqGJ-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Whitecaps Captains @ Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vs38-N

Shop  https //stza.co/+vs38-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Whitecaps
END:VALARM
DTSTART:20180726T230500Z
DTEND:20180727T020500Z
UID:NRhB5gVUUjdynU-xr59FqGJ-@stanza.co
SUMMARY:Captains @ Whitecaps
DESCRIPTION:Captains @ Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vs38-N\n\nShop: https://stza.co/+vs38-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Whitecaps
<2018-07-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       eiGnBxzrwgfarWw55gcyTyK1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains @ Whitecaps Captains @ Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vN9h-1W

Shop  https //stza.co/+vN9h-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Whitecaps
END:VALARM
DTSTART:20180727T230500Z
DTEND:20180728T020500Z
UID:eiGnBxzrwgfarWw55gcyTyK1@stanza.co
SUMMARY:Captains @ Whitecaps
DESCRIPTION:Captains @ Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vN9h-1W\n\nShop: https://stza.co/+vN9h-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Loons
<2018-07-28 Sat 18:00-21:00>
:PROPERTIES:
:ID:       _srxNuWsWn3FjaoqR8m6gkTT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Loons Captains vs. Loons

Follow on MiLB First Pitch  https //stza.co/+xACd-3

Shop  https //stza.co/+xACd-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Loons
END:VALARM
DTSTART:20180728T230000Z
DTEND:20180729T020000Z
UID:_srxNuWsWn3FjaoqR8m6gkTT@stanza.co
SUMMARY:Captains vs. Loons
DESCRIPTION:Captains vs. Loons\n\nFollow on MiLB First Pitch: https://stza.co/+xACd-3\n\nShop: https://stza.co/+xACd-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Loons
<2018-07-29 Sun 18:00-21:00>
:PROPERTIES:
:ID:       MzQ6UpnE1VC1ZaLtX-FdrZVA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Loons Captains vs. Loons

Follow on MiLB First Pitch  https //stza.co/+xACh-1e

Shop  https //stza.co/+xACh-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Loons
END:VALARM
DTSTART:20180729T230000Z
DTEND:20180730T020000Z
UID:MzQ6UpnE1VC1ZaLtX-FdrZVA@stanza.co
SUMMARY:Captains vs. Loons
DESCRIPTION:Captains vs. Loons\n\nFollow on MiLB First Pitch: https://stza.co/+xACh-1e\n\nShop: https://stza.co/+xACh-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Loons
<2018-07-30 Mon 18:00-21:00>
:PROPERTIES:
:ID:       mNonsbYzy8on9q0nM-V4YRj3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains vs. Loons Captains vs. Loons

Follow on MiLB First Pitch  https //stza.co/+xACi-1t

Shop  https //stza.co/+xACi-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Loons
END:VALARM
DTSTART:20180730T230000Z
DTEND:20180731T020000Z
UID:mNonsbYzy8on9q0nM-V4YRj3@stanza.co
SUMMARY:Captains vs. Loons
DESCRIPTION:Captains vs. Loons\n\nFollow on MiLB First Pitch: https://stza.co/+xACi-1t\n\nShop: https://stza.co/+xACi-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Loons
<2018-07-31 Tue 10:00-13:00>
:PROPERTIES:
:ID:       L67UCA_jpBadJyt69vyC0CV1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Loons Captains vs. Loons

Follow on MiLB First Pitch  https //stza.co/+xACk-3Z

Shop  https //stza.co/+xACk-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Loons
END:VALARM
DTSTART:20180731T150000Z
DTEND:20180731T180000Z
UID:L67UCA_jpBadJyt69vyC0CV1@stanza.co
SUMMARY:Captains vs. Loons
DESCRIPTION:Captains vs. Loons\n\nFollow on MiLB First Pitch: https://stza.co/+xACk-3Z\n\nShop: https://stza.co/+xACk-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Hot Rods
<2018-08-01 Wed 18:00-21:00>
:PROPERTIES:
:ID:       8w6kYHnnZMYaXQBjovzHTpY_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Hot Rods Captains vs. Hot Rods

Follow on MiLB First Pitch  https //stza.co/+xACm-2c

Shop  https //stza.co/+xACm-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Hot Rods
END:VALARM
DTSTART:20180801T230000Z
DTEND:20180802T020000Z
UID:8w6kYHnnZMYaXQBjovzHTpY_@stanza.co
SUMMARY:Captains vs. Hot Rods
DESCRIPTION:Captains vs. Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+xACm-2c\n\nShop: https://stza.co/+xACm-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Hot Rods
<2018-08-02 Thu 18:00-21:00>
:PROPERTIES:
:ID:       6cDcVgTni4qX6BQm8iaQXrBP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains vs. Hot Rods Captains vs. Hot Rods

Follow on MiLB First Pitch  https //stza.co/+xACo-2V

Shop  https //stza.co/+xACo-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Hot Rods
END:VALARM
DTSTART:20180802T230000Z
DTEND:20180803T020000Z
UID:6cDcVgTni4qX6BQm8iaQXrBP@stanza.co
SUMMARY:Captains vs. Hot Rods
DESCRIPTION:Captains vs. Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+xACo-2V\n\nShop: https://stza.co/+xACo-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Hot Rods
<2018-08-03 Fri 18:00-21:00>
:PROPERTIES:
:ID:       NQUb7O2MfKFwVDvA35KPSH9Q@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Hot Rods Captains vs. Hot Rods

Follow on MiLB First Pitch  https //stza.co/+xACs-3C

Shop  https //stza.co/+xACs-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Hot Rods
END:VALARM
DTSTART:20180803T230000Z
DTEND:20180804T020000Z
UID:NQUb7O2MfKFwVDvA35KPSH9Q@stanza.co
SUMMARY:Captains vs. Hot Rods
DESCRIPTION:Captains vs. Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+xACs-3C\n\nShop: https://stza.co/+xACs-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Loons
<2018-08-04 Sat 18:05-21:05>
:PROPERTIES:
:ID:       8cVQ9fh_MHSuyQCbFj1SMSN3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Loons Captains @ Loons

Follow on MiLB First Pitch  https //stza.co/+vrGR-2A

Shop  https //stza.co/+vrGR-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Loons
END:VALARM
DTSTART:20180804T230500Z
DTEND:20180805T020500Z
UID:8cVQ9fh_MHSuyQCbFj1SMSN3@stanza.co
SUMMARY:Captains @ Loons
DESCRIPTION:Captains @ Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vrGR-2A\n\nShop: https://stza.co/+vrGR-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Loons
<2018-08-05 Sun 13:05-16:05>
:PROPERTIES:
:ID:       1UJFLJYEJ_oQD5-eD2KNg6tW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains @ Loons Captains @ Loons

Follow on MiLB First Pitch  https //stza.co/+vrGX-1d

Shop  https //stza.co/+vrGX-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Loons
END:VALARM
DTSTART:20180805T180500Z
DTEND:20180805T210500Z
UID:1UJFLJYEJ_oQD5-eD2KNg6tW@stanza.co
SUMMARY:Captains @ Loons
DESCRIPTION:Captains @ Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vrGX-1d\n\nShop: https://stza.co/+vrGX-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Loons
<2018-08-06 Mon 18:05-21:05>
:PROPERTIES:
:ID:       _6LLpIz9_8-aCl7uUszuVq1u@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Loons Captains @ Loons

Follow on MiLB First Pitch  https //stza.co/+vrH2-1i

Shop  https //stza.co/+vrH2-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Loons
END:VALARM
DTSTART:20180806T230500Z
DTEND:20180807T020500Z
UID:_6LLpIz9_8-aCl7uUszuVq1u@stanza.co
SUMMARY:Captains @ Loons
DESCRIPTION:Captains @ Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vrH2-1i\n\nShop: https://stza.co/+vrH2-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. TinCaps
<2018-08-08 Wed 18:00-21:00>
:PROPERTIES:
:ID:       b6kx3uWxAbQnHKSWcumqsC6a@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. TinCaps Captains vs. TinCaps

Follow on MiLB First Pitch  https //stza.co/+xACu-2V

Shop  https //stza.co/+xACu-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. TinCaps
END:VALARM
DTSTART:20180808T230000Z
DTEND:20180809T020000Z
UID:b6kx3uWxAbQnHKSWcumqsC6a@stanza.co
SUMMARY:Captains vs. TinCaps
DESCRIPTION:Captains vs. TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+xACu-2V\n\nShop: https://stza.co/+xACu-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. TinCaps
<2018-08-09 Thu 18:00-21:00>
:PROPERTIES:
:ID:       Uyg5q_Gfw9bOgjhxh6KtbT_X@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains vs. TinCaps Captains vs. TinCaps

Follow on MiLB First Pitch  https //stza.co/+xACw-3V

Shop  https //stza.co/+xACw-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. TinCaps
END:VALARM
DTSTART:20180809T230000Z
DTEND:20180810T020000Z
UID:Uyg5q_Gfw9bOgjhxh6KtbT_X@stanza.co
SUMMARY:Captains vs. TinCaps
DESCRIPTION:Captains vs. TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+xACw-3V\n\nShop: https://stza.co/+xACw-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. TinCaps
<2018-08-10 Fri 18:00-21:00>
:PROPERTIES:
:ID:       Zjk_u4BSWJk8VQ_nsJHPqSdi@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. TinCaps Captains vs. TinCaps

Follow on MiLB First Pitch  https //stza.co/+xACz-u

Shop  https //stza.co/+xACz-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. TinCaps
END:VALARM
DTSTART:20180810T230000Z
DTEND:20180811T020000Z
UID:Zjk_u4BSWJk8VQ_nsJHPqSdi@stanza.co
SUMMARY:Captains vs. TinCaps
DESCRIPTION:Captains vs. TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+xACz-u\n\nShop: https://stza.co/+xACz-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Cubs
<2018-08-11 Sat 18:05-21:05>
:PROPERTIES:
:ID:       X5Pbcq7fht4ZWNHKVyAdWqpz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Cubs Captains @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vs1q-2T

Shop  https //stza.co/+vs1q-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Cubs
END:VALARM
DTSTART:20180811T230500Z
DTEND:20180812T020500Z
UID:X5Pbcq7fht4ZWNHKVyAdWqpz@stanza.co
SUMMARY:Captains @ Cubs
DESCRIPTION:Captains @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vs1q-2T\n\nShop: https://stza.co/+vs1q-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Cubs
<2018-08-12 Sun 13:05-16:05>
:PROPERTIES:
:ID:       2gw4nt-qvrq4nev2Y2ncn9mH@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains @ Cubs Captains @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vs1E-17

Shop  https //stza.co/+vs1E-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Cubs
END:VALARM
DTSTART:20180812T180500Z
DTEND:20180812T210500Z
UID:2gw4nt-qvrq4nev2Y2ncn9mH@stanza.co
SUMMARY:Captains @ Cubs
DESCRIPTION:Captains @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vs1E-17\n\nShop: https://stza.co/+vs1E-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Cubs
<2018-08-13 Mon 18:05-21:05>
:PROPERTIES:
:ID:       NsdyjB1Y4NnwgpRAnyEvebMO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Cubs Captains @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vs1T-2s

Shop  https //stza.co/+vs1T-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Cubs
END:VALARM
DTSTART:20180813T230500Z
DTEND:20180814T020500Z
UID:NsdyjB1Y4NnwgpRAnyEvebMO@stanza.co
SUMMARY:Captains @ Cubs
DESCRIPTION:Captains @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vs1T-2s\n\nShop: https://stza.co/+vs1T-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Cubs
<2018-08-14 Tue 18:05-21:05>
:PROPERTIES:
:ID:       VJYhf3Wir9sU5uR_-bSaa3PC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Cubs Captains @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vs23-E

Shop  https //stza.co/+vs23-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Cubs
END:VALARM
DTSTART:20180814T230500Z
DTEND:20180815T020500Z
UID:VJYhf3Wir9sU5uR_-bSaa3PC@stanza.co
SUMMARY:Captains @ Cubs
DESCRIPTION:Captains @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vs23-E\n\nShop: https://stza.co/+vs23-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Dragons
<2018-08-15 Wed 18:00-21:00>
:PROPERTIES:
:ID:       e-jwC-frrj7jug6fGIOZym23@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains @ Dragons Captains @ Dragons

Follow on MiLB First Pitch  https //stza.co/+vrFJ-1X

Shop  https //stza.co/+vrFJ-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Dragons
END:VALARM
DTSTART:20180815T230000Z
DTEND:20180816T020000Z
UID:e-jwC-frrj7jug6fGIOZym23@stanza.co
SUMMARY:Captains @ Dragons
DESCRIPTION:Captains @ Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+vrFJ-1X\n\nShop: https://stza.co/+vrFJ-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Dragons
<2018-08-16 Thu 18:00-21:00>
:PROPERTIES:
:ID:       EILCM_bvvH0xMGrt8ORLd8-A@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Dragons Captains @ Dragons

Follow on MiLB First Pitch  https //stza.co/+vrFQ-4

Shop  https //stza.co/+vrFQ-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Dragons
END:VALARM
DTSTART:20180816T230000Z
DTEND:20180817T020000Z
UID:EILCM_bvvH0xMGrt8ORLd8-A@stanza.co
SUMMARY:Captains @ Dragons
DESCRIPTION:Captains @ Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+vrFQ-4\n\nShop: https://stza.co/+vrFQ-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Dragons
<2018-08-17 Fri 18:00-21:00>
:PROPERTIES:
:ID:       tLSa-jFa4eNrewa7swINYPXJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Dragons Captains @ Dragons

Follow on MiLB First Pitch  https //stza.co/+vrFU-2g

Shop  https //stza.co/+vrFU-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Dragons
END:VALARM
DTSTART:20180817T230000Z
DTEND:20180818T020000Z
UID:tLSa-jFa4eNrewa7swINYPXJ@stanza.co
SUMMARY:Captains @ Dragons
DESCRIPTION:Captains @ Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+vrFU-2g\n\nShop: https://stza.co/+vrFU-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Whitecaps
<2018-08-18 Sat 18:00-21:00>
:PROPERTIES:
:ID:       74U7czFWaGHqcyMg23Z5uZfT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains vs. Whitecaps Captains vs. Whitecaps

Follow on MiLB First Pitch  https //stza.co/+xACB-28

Shop  https //stza.co/+xACB-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Whitecaps
END:VALARM
DTSTART:20180818T230000Z
DTEND:20180819T020000Z
UID:74U7czFWaGHqcyMg23Z5uZfT@stanza.co
SUMMARY:Captains vs. Whitecaps
DESCRIPTION:Captains vs. Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+xACB-28\n\nShop: https://stza.co/+xACB-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Whitecaps
<2018-08-19 Sun 18:00-21:00>
:PROPERTIES:
:ID:       ul4s1gfmx2mlTIAG8lZP0mjV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Whitecaps Captains vs. Whitecaps

Follow on MiLB First Pitch  https //stza.co/+xACF-2l

Shop  https //stza.co/+xACF-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Whitecaps
END:VALARM
DTSTART:20180819T230000Z
DTEND:20180820T020000Z
UID:ul4s1gfmx2mlTIAG8lZP0mjV@stanza.co
SUMMARY:Captains vs. Whitecaps
DESCRIPTION:Captains vs. Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+xACF-2l\n\nShop: https://stza.co/+xACF-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Whitecaps
<2018-08-20 Mon 18:00-21:00>
:PROPERTIES:
:ID:       B7t2OXerImXC23S-3PyHxbZz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Whitecaps Captains vs. Whitecaps

Follow on MiLB First Pitch  https //stza.co/+xACH-1u

Shop  https //stza.co/+xACH-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Whitecaps
END:VALARM
DTSTART:20180820T230000Z
DTEND:20180821T020000Z
UID:B7t2OXerImXC23S-3PyHxbZz@stanza.co
SUMMARY:Captains vs. Whitecaps
DESCRIPTION:Captains vs. Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+xACH-1u\n\nShop: https://stza.co/+xACH-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Cubs
<2018-08-21 Tue 18:00-21:00>
:PROPERTIES:
:ID:       x4m-CJgCAe4cN1SqBvotHjAe@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains vs. Cubs Captains vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+xACJ-19

Shop  https //stza.co/+xACJ-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Cubs
END:VALARM
DTSTART:20180821T230000Z
DTEND:20180822T020000Z
UID:x4m-CJgCAe4cN1SqBvotHjAe@stanza.co
SUMMARY:Captains vs. Cubs
DESCRIPTION:Captains vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+xACJ-19\n\nShop: https://stza.co/+xACJ-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Cubs
<2018-08-22 Wed 18:00-21:00>
:PROPERTIES:
:ID:       IPEBqxHvLE-Rhdc7qgWDQVYg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Cubs Captains vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+xACL-1T

Shop  https //stza.co/+xACL-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Cubs
END:VALARM
DTSTART:20180822T230000Z
DTEND:20180823T020000Z
UID:IPEBqxHvLE-Rhdc7qgWDQVYg@stanza.co
SUMMARY:Captains vs. Cubs
DESCRIPTION:Captains vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+xACL-1T\n\nShop: https://stza.co/+xACL-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Cubs
<2018-08-23 Thu 18:00-21:00>
:PROPERTIES:
:ID:       mv6RDnojCcbBr15ll1bp8Ty-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Cubs Captains vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+xACO-3O

Shop  https //stza.co/+xACO-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Cubs
END:VALARM
DTSTART:20180823T230000Z
DTEND:20180824T020000Z
UID:mv6RDnojCcbBr15ll1bp8Ty-@stanza.co
SUMMARY:Captains vs. Cubs
DESCRIPTION:Captains vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+xACO-3O\n\nShop: https://stza.co/+xACO-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Hot Rods
<2018-08-24 Fri 18:35-21:35>
:PROPERTIES:
:ID:       HjdUhOsC94SjjtTLXf2L3Igz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains @ Hot Rods Captains @ Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vN8R-1_

Shop  https //stza.co/+vN8R-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Hot Rods
END:VALARM
DTSTART:20180824T233500Z
DTEND:20180825T023500Z
UID:HjdUhOsC94SjjtTLXf2L3Igz@stanza.co
SUMMARY:Captains @ Hot Rods
DESCRIPTION:Captains @ Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vN8R-1_\n\nShop: https://stza.co/+vN8R-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Hot Rods
<2018-08-25 Sat 18:35-21:35>
:PROPERTIES:
:ID:       mJmJMd-YLJm3DBAniyN3u7It@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Hot Rods Captains @ Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vN8S-i

Shop  https //stza.co/+vN8S-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Hot Rods
END:VALARM
DTSTART:20180825T233500Z
DTEND:20180826T023500Z
UID:mJmJMd-YLJm3DBAniyN3u7It@stanza.co
SUMMARY:Captains @ Hot Rods
DESCRIPTION:Captains @ Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vN8S-i\n\nShop: https://stza.co/+vN8S-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Hot Rods
<2018-08-26 Sun 14:05-17:05>
:PROPERTIES:
:ID:       2nmxES4ZsW_jHTzC0T7gEy_3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ Hot Rods Captains @ Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vN8T-1v

Shop  https //stza.co/+vN8T-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Hot Rods
END:VALARM
DTSTART:20180826T190500Z
DTEND:20180826T220500Z
UID:2nmxES4ZsW_jHTzC0T7gEy_3@stanza.co
SUMMARY:Captains @ Hot Rods
DESCRIPTION:Captains @ Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vN8T-1v\n\nShop: https://stza.co/+vN8T-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ Hot Rods
<2018-08-27 Mon 12:05-15:05>
:PROPERTIES:
:ID:       pS__moe3bFBEOsERPXCxB00E@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains @ Hot Rods Captains @ Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vN8U-1r

Shop  https //stza.co/+vN8U-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ Hot Rods
END:VALARM
DTSTART:20180827T170500Z
DTEND:20180827T200500Z
UID:pS__moe3bFBEOsERPXCxB00E@stanza.co
SUMMARY:Captains @ Hot Rods
DESCRIPTION:Captains @ Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vN8U-1r\n\nShop: https://stza.co/+vN8U-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ TinCaps
<2018-08-29 Wed 18:05-21:05>
:PROPERTIES:
:ID:       NWHTCTaPKugWHheRbmMWJj5Q@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ TinCaps Captains @ TinCaps

Follow on MiLB First Pitch  https //stza.co/+vN8_-2j

Shop  https //stza.co/+vN8_-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ TinCaps
END:VALARM
DTSTART:20180829T230500Z
DTEND:20180830T020500Z
UID:NWHTCTaPKugWHheRbmMWJj5Q@stanza.co
SUMMARY:Captains @ TinCaps
DESCRIPTION:Captains @ TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+vN8_-2j\n\nShop: https://stza.co/+vN8_-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ TinCaps
<2018-08-30 Thu 18:05-21:05>
:PROPERTIES:
:ID:       W33RFCOhpNAOjrkoh0eEKBHz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains @ TinCaps Captains @ TinCaps

Follow on MiLB First Pitch  https //stza.co/+vN8$-1k

Shop  https //stza.co/+vN8$-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ TinCaps
END:VALARM
DTSTART:20180830T230500Z
DTEND:20180831T020500Z
UID:W33RFCOhpNAOjrkoh0eEKBHz@stanza.co
SUMMARY:Captains @ TinCaps
DESCRIPTION:Captains @ TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+vN8$-1k\n\nShop: https://stza.co/+vN8$-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains @ TinCaps
<2018-08-31 Fri 18:05-21:05>
:PROPERTIES:
:ID:       t19uGvnvuZk6UCDd7cTOcCH5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains @ TinCaps Captains @ TinCaps

Follow on MiLB First Pitch  https //stza.co/+vN90-1e

Shop  https //stza.co/+vN90-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Captains @ TinCaps
END:VALARM
DTSTART:20180831T230500Z
DTEND:20180901T020500Z
UID:t19uGvnvuZk6UCDd7cTOcCH5@stanza.co
SUMMARY:Captains @ TinCaps
DESCRIPTION:Captains @ TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+vN90-1e\n\nShop: https://stza.co/+vN90-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Lugnuts
<2018-09-01 Sat 18:00-21:00>
:PROPERTIES:
:ID:       0Qefs6Eq2YZattqbPQO8CqKB@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Lugnuts Captains vs. Lugnuts

Follow on MiLB First Pitch  https //stza.co/+xACR-3e

Shop  https //stza.co/+xACR-3_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Lugnuts
END:VALARM
DTSTART:20180901T230000Z
DTEND:20180902T020000Z
UID:0Qefs6Eq2YZattqbPQO8CqKB@stanza.co
SUMMARY:Captains vs. Lugnuts
DESCRIPTION:Captains vs. Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+xACR-3e\n\nShop: https://stza.co/+xACR-3_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Lugnuts
<2018-09-02 Sun 12:30-15:30>
:PROPERTIES:
:ID:       ZYXLWIbmvWcAdcX9mVAcmZvM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Captains vs. Lugnuts Captains vs. Lugnuts

Follow on MiLB First Pitch  https //stza.co/+xACS-3a

Shop  https //stza.co/+xACS-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Lugnuts
END:VALARM
DTSTART:20180902T173000Z
DTEND:20180902T203000Z
UID:ZYXLWIbmvWcAdcX9mVAcmZvM@stanza.co
SUMMARY:Captains vs. Lugnuts
DESCRIPTION:Captains vs. Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+xACS-3a\n\nShop: https://stza.co/+xACS-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
* Captains vs. Lugnuts
<2018-09-03 Mon 12:00-15:00>
:PROPERTIES:
:ID:       m_1rgBOzPIL9Q72Hg5K8Nm4E@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Captains vs. Lugnuts Captains vs. Lugnuts

Follow on MiLB First Pitch  https //stza.co/+xACV-o

Shop  https //stza.co/+xACV-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Captains vs. Lugnuts
END:VALARM
DTSTART:20180903T170000Z
DTEND:20180903T200000Z
UID:m_1rgBOzPIL9Q72Hg5K8Nm4E@stanza.co
SUMMARY:Captains vs. Lugnuts
DESCRIPTION:Captains vs. Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+xACV-o\n\nShop: https://stza.co/+xACV-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144538Z
LAST-MODIFIED:20180213T144538Z
TRANSP:OPAQUE
END:VEVENT
