#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Curve vs. RubberDucks
<2018-04-05 Thu 17:00-20:00>
:PROPERTIES:
:ID:       F_V94MHeEYssP-2cdORxfU8K@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. RubberDucks Curve vs. RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vL4U-o

Shop  https //stza.co/+vL4U-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. RubberDucks
END:VALARM
DTSTART:20180405T220000Z
DTEND:20180406T010000Z
UID:F_V94MHeEYssP-2cdORxfU8K@stanza.co
SUMMARY:Curve vs. RubberDucks
DESCRIPTION:Curve vs. RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vL4U-o\n\nShop: https://stza.co/+vL4U-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. RubberDucks
<2018-04-06 Fri 17:00-20:00>
:PROPERTIES:
:ID:       yob908qOXO9BLTh7fgLRvGND@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve vs. RubberDucks Curve vs. RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vL4V-3S

Shop  https //stza.co/+vL4V-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. RubberDucks
END:VALARM
DTSTART:20180406T220000Z
DTEND:20180407T010000Z
UID:yob908qOXO9BLTh7fgLRvGND@stanza.co
SUMMARY:Curve vs. RubberDucks
DESCRIPTION:Curve vs. RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vL4V-3S\n\nShop: https://stza.co/+vL4V-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. RubberDucks
<2018-04-07 Sat 15:00-18:00>
:PROPERTIES:
:ID:       3f4WYuZi2D9Fp7pvzkDfzav-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. RubberDucks Curve vs. RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vL4X-3

Shop  https //stza.co/+vL4X-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. RubberDucks
END:VALARM
DTSTART:20180407T200000Z
DTEND:20180407T230000Z
UID:3f4WYuZi2D9Fp7pvzkDfzav-@stanza.co
SUMMARY:Curve vs. RubberDucks
DESCRIPTION:Curve vs. RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vL4X-3\n\nShop: https://stza.co/+vL4X-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. RubberDucks
<2018-04-08 Sun 13:00-16:00>
:PROPERTIES:
:ID:       q3D9GQSekSF0_5lmNW7ZBZqO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. RubberDucks Curve vs. RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vL4Z-17

Shop  https //stza.co/+vL4Z-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. RubberDucks
END:VALARM
DTSTART:20180408T180000Z
DTEND:20180408T210000Z
UID:q3D9GQSekSF0_5lmNW7ZBZqO@stanza.co
SUMMARY:Curve vs. RubberDucks
DESCRIPTION:Curve vs. RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vL4Z-17\n\nShop: https://stza.co/+vL4Z-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Senators
<2018-04-09 Mon 17:00-20:00>
:PROPERTIES:
:ID:       zXzgOygVMQMwXrJNTj0H8V_u@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve vs. Senators Curve vs. Senators

Follow on MiLB First Pitch  https //stza.co/+vL50-31

Shop  https //stza.co/+vL50-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Senators
END:VALARM
DTSTART:20180409T220000Z
DTEND:20180410T010000Z
UID:zXzgOygVMQMwXrJNTj0H8V_u@stanza.co
SUMMARY:Curve vs. Senators
DESCRIPTION:Curve vs. Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vL50-31\n\nShop: https://stza.co/+vL50-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Senators
<2018-04-10 Tue 17:00-20:00>
:PROPERTIES:
:ID:       kN07lUmb4uP_X--jss_Ym1Rw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. Senators Curve vs. Senators

Follow on MiLB First Pitch  https //stza.co/+vL52-10

Shop  https //stza.co/+vL52-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Senators
END:VALARM
DTSTART:20180410T220000Z
DTEND:20180411T010000Z
UID:kN07lUmb4uP_X--jss_Ym1Rw@stanza.co
SUMMARY:Curve vs. Senators
DESCRIPTION:Curve vs. Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vL52-10\n\nShop: https://stza.co/+vL52-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Senators
<2018-04-11 Wed 17:00-20:00>
:PROPERTIES:
:ID:       B8mPnwX5pQ983YcxW3nQMtYc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. Senators Curve vs. Senators

Follow on MiLB First Pitch  https //stza.co/+vL54-1Y

Shop  https //stza.co/+vL54-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Senators
END:VALARM
DTSTART:20180411T220000Z
DTEND:20180412T010000Z
UID:B8mPnwX5pQ983YcxW3nQMtYc@stanza.co
SUMMARY:Curve vs. Senators
DESCRIPTION:Curve vs. Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vL54-1Y\n\nShop: https://stza.co/+vL54-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ SeaWolves
<2018-04-13 Fri 17:05-20:05>
:PROPERTIES:
:ID:       ICKSQ6uZmsEJCSb1VReBZ_fB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve @ SeaWolves Curve @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vL7f-1_

Shop  https //stza.co/+vL7f-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ SeaWolves
END:VALARM
DTSTART:20180413T220500Z
DTEND:20180414T010500Z
UID:ICKSQ6uZmsEJCSb1VReBZ_fB@stanza.co
SUMMARY:Curve @ SeaWolves
DESCRIPTION:Curve @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vL7f-1_\n\nShop: https://stza.co/+vL7f-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ SeaWolves
<2018-04-14 Sat 12:35-15:35>
:PROPERTIES:
:ID:       wbmiCGNY_4X5XPFE_OctZqEX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ SeaWolves Curve @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vL7g-3E

Shop  https //stza.co/+vL7g-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ SeaWolves
END:VALARM
DTSTART:20180414T173500Z
DTEND:20180414T203500Z
UID:wbmiCGNY_4X5XPFE_OctZqEX@stanza.co
SUMMARY:Curve @ SeaWolves
DESCRIPTION:Curve @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vL7g-3E\n\nShop: https://stza.co/+vL7g-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ SeaWolves
<2018-04-15 Sun 12:35-15:35>
:PROPERTIES:
:ID:       u2sl932I0BwoiSFt-h8YhpAo@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ SeaWolves Curve @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vL7h-2P

Shop  https //stza.co/+vL7h-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ SeaWolves
END:VALARM
DTSTART:20180415T173500Z
DTEND:20180415T203500Z
UID:u2sl932I0BwoiSFt-h8YhpAo@stanza.co
SUMMARY:Curve @ SeaWolves
DESCRIPTION:Curve @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vL7h-2P\n\nShop: https://stza.co/+vL7h-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ RubberDucks
<2018-04-16 Mon 17:35-20:35>
:PROPERTIES:
:ID:       DHFXyxCqFsZ7t-Sy9kUUoS-0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve @ RubberDucks Curve @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vL4H-1X

Shop  https //stza.co/+vL4H-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ RubberDucks
END:VALARM
DTSTART:20180416T223500Z
DTEND:20180417T013500Z
UID:DHFXyxCqFsZ7t-Sy9kUUoS-0@stanza.co
SUMMARY:Curve @ RubberDucks
DESCRIPTION:Curve @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vL4H-1X\n\nShop: https://stza.co/+vL4H-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ RubberDucks
<2018-04-17 Tue 17:35-20:35>
:PROPERTIES:
:ID:       rtMe0DOqQcsEFNkAdH2AkoDn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ RubberDucks Curve @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vL4I-3L

Shop  https //stza.co/+vL4I-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ RubberDucks
END:VALARM
DTSTART:20180417T223500Z
DTEND:20180418T013500Z
UID:rtMe0DOqQcsEFNkAdH2AkoDn@stanza.co
SUMMARY:Curve @ RubberDucks
DESCRIPTION:Curve @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vL4I-3L\n\nShop: https://stza.co/+vL4I-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ RubberDucks
<2018-04-18 Wed 17:35-20:35>
:PROPERTIES:
:ID:       nsyBoq19PlBB3pEwWU5YXFur@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ RubberDucks Curve @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vL4J-2x

Shop  https //stza.co/+vL4J-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ RubberDucks
END:VALARM
DTSTART:20180418T223500Z
DTEND:20180419T013500Z
UID:nsyBoq19PlBB3pEwWU5YXFur@stanza.co
SUMMARY:Curve @ RubberDucks
DESCRIPTION:Curve @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vL4J-2x\n\nShop: https://stza.co/+vL4J-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ RubberDucks
<2018-04-19 Thu 17:35-20:35>
:PROPERTIES:
:ID:       xXrdOMEBovZD7pttLSM3gM1o@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve @ RubberDucks Curve @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vL4K-3L

Shop  https //stza.co/+vL4K-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ RubberDucks
END:VALARM
DTSTART:20180419T223500Z
DTEND:20180420T013500Z
UID:xXrdOMEBovZD7pttLSM3gM1o@stanza.co
SUMMARY:Curve @ RubberDucks
DESCRIPTION:Curve @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vL4K-3L\n\nShop: https://stza.co/+vL4K-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Flying Squirrels
<2018-04-20 Fri 17:00-20:00>
:PROPERTIES:
:ID:       CPGMuLMSVyiWJyvHMHadDBzS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. Flying Squirrels Curve vs. Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vL56-p

Shop  https //stza.co/+vL56-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Flying Squirrels
END:VALARM
DTSTART:20180420T220000Z
DTEND:20180421T010000Z
UID:CPGMuLMSVyiWJyvHMHadDBzS@stanza.co
SUMMARY:Curve vs. Flying Squirrels
DESCRIPTION:Curve vs. Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vL56-p\n\nShop: https://stza.co/+vL56-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Flying Squirrels
<2018-04-21 Sat 15:00-18:00>
:PROPERTIES:
:ID:       RxduXKRXSs0CFAxK5E7_Oa_r@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. Flying Squirrels Curve vs. Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vL57-1I

Shop  https //stza.co/+vL57-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Flying Squirrels
END:VALARM
DTSTART:20180421T200000Z
DTEND:20180421T230000Z
UID:RxduXKRXSs0CFAxK5E7_Oa_r@stanza.co
SUMMARY:Curve vs. Flying Squirrels
DESCRIPTION:Curve vs. Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vL57-1I\n\nShop: https://stza.co/+vL57-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Flying Squirrels
<2018-04-22 Sun 13:00-16:00>
:PROPERTIES:
:ID:       HP9wxAMnDZ4djE3iM5t-n15Y@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve vs. Flying Squirrels Curve vs. Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vL5a-1C

Shop  https //stza.co/+vL5a-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Flying Squirrels
END:VALARM
DTSTART:20180422T180000Z
DTEND:20180422T210000Z
UID:HP9wxAMnDZ4djE3iM5t-n15Y@stanza.co
SUMMARY:Curve vs. Flying Squirrels
DESCRIPTION:Curve vs. Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vL5a-1C\n\nShop: https://stza.co/+vL5a-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. SeaWolves
<2018-04-23 Mon 17:00-20:00>
:PROPERTIES:
:ID:       ovcXiwd_6LFIXrjnkz4QPS_v@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. SeaWolves Curve vs. SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vL5c-f

Shop  https //stza.co/+vL5c-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. SeaWolves
END:VALARM
DTSTART:20180423T220000Z
DTEND:20180424T010000Z
UID:ovcXiwd_6LFIXrjnkz4QPS_v@stanza.co
SUMMARY:Curve vs. SeaWolves
DESCRIPTION:Curve vs. SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vL5c-f\n\nShop: https://stza.co/+vL5c-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. SeaWolves
<2018-04-24 Tue 17:00-20:00>
:PROPERTIES:
:ID:       p2fdCi_svJCbLUAS20SmdwOE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. SeaWolves Curve vs. SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vL5d-1p

Shop  https //stza.co/+vL5d-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. SeaWolves
END:VALARM
DTSTART:20180424T220000Z
DTEND:20180425T010000Z
UID:p2fdCi_svJCbLUAS20SmdwOE@stanza.co
SUMMARY:Curve vs. SeaWolves
DESCRIPTION:Curve vs. SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vL5d-1p\n\nShop: https://stza.co/+vL5d-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. SeaWolves
<2018-04-25 Wed 09:30-12:30>
:PROPERTIES:
:ID:       408XAf8c6G6r_XVTkQGqJ0AC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve vs. SeaWolves Curve vs. SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vL5g-2V

Shop  https //stza.co/+vL5g-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. SeaWolves
END:VALARM
DTSTART:20180425T143000Z
DTEND:20180425T173000Z
UID:408XAf8c6G6r_XVTkQGqJ0AC@stanza.co
SUMMARY:Curve vs. SeaWolves
DESCRIPTION:Curve vs. SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vL5g-2V\n\nShop: https://stza.co/+vL5g-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Senators
<2018-04-27 Fri 18:00-21:00>
:PROPERTIES:
:ID:       NrZlBCc76kuCfPd00e6Oq_hE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Senators Curve @ Senators

Follow on MiLB First Pitch  https //stza.co/+vL7p-1Z

Shop  https //stza.co/+vL7p-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Senators
END:VALARM
DTSTART:20180427T230000Z
DTEND:20180428T020000Z
UID:NrZlBCc76kuCfPd00e6Oq_hE@stanza.co
SUMMARY:Curve @ Senators
DESCRIPTION:Curve @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vL7p-1Z\n\nShop: https://stza.co/+vL7p-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Senators
<2018-04-28 Sat 17:00-20:00>
:PROPERTIES:
:ID:       ejGTvDKN1UHcnzH78M2o_IBO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Senators Curve @ Senators

Follow on MiLB First Pitch  https //stza.co/+vL7q-2O

Shop  https //stza.co/+vL7q-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Senators
END:VALARM
DTSTART:20180428T220000Z
DTEND:20180429T010000Z
UID:ejGTvDKN1UHcnzH78M2o_IBO@stanza.co
SUMMARY:Curve @ Senators
DESCRIPTION:Curve @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vL7q-2O\n\nShop: https://stza.co/+vL7q-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Senators
<2018-04-29 Sun 12:30-15:30>
:PROPERTIES:
:ID:       m09PNxjotZvk9WRRyxIEhtOW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve @ Senators Curve @ Senators

Follow on MiLB First Pitch  https //stza.co/+vL7r-V

Shop  https //stza.co/+vL7r-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Senators
END:VALARM
DTSTART:20180429T173000Z
DTEND:20180429T203000Z
UID:m09PNxjotZvk9WRRyxIEhtOW@stanza.co
SUMMARY:Curve @ Senators
DESCRIPTION:Curve @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vL7r-V\n\nShop: https://stza.co/+vL7r-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Flying Squirrels
<2018-04-30 Mon 17:35-20:35>
:PROPERTIES:
:ID:       FTieMyKk-bmcun-Y4q-3he4l@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Flying Squirrels Curve @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+v6Tw-1Q

Shop  https //stza.co/+v6Tw-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Flying Squirrels
END:VALARM
DTSTART:20180430T223500Z
DTEND:20180501T013500Z
UID:FTieMyKk-bmcun-Y4q-3he4l@stanza.co
SUMMARY:Curve @ Flying Squirrels
DESCRIPTION:Curve @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+v6Tw-1Q\n\nShop: https://stza.co/+v6Tw-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Flying Squirrels
<2018-05-01 Tue 17:35-20:35>
:PROPERTIES:
:ID:       1q3HSrxaH4ayVIXQY2JMUIZF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Flying Squirrels Curve @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+v6TO-1v

Shop  https //stza.co/+v6TO-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Flying Squirrels
END:VALARM
DTSTART:20180501T223500Z
DTEND:20180502T013500Z
UID:1q3HSrxaH4ayVIXQY2JMUIZF@stanza.co
SUMMARY:Curve @ Flying Squirrels
DESCRIPTION:Curve @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+v6TO-1v\n\nShop: https://stza.co/+v6TO-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Flying Squirrels
<2018-05-02 Wed 09:35-12:35>
:PROPERTIES:
:ID:       nv1QqaW9JhD2i9CU9CVMcAPw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve @ Flying Squirrels Curve @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+v6U8-1A

Shop  https //stza.co/+v6U8-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Flying Squirrels
END:VALARM
DTSTART:20180502T143500Z
DTEND:20180502T173500Z
UID:nv1QqaW9JhD2i9CU9CVMcAPw@stanza.co
SUMMARY:Curve @ Flying Squirrels
DESCRIPTION:Curve @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+v6U8-1A\n\nShop: https://stza.co/+v6U8-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. SeaWolves
<2018-05-03 Thu 17:00-20:00>
:PROPERTIES:
:ID:       4ky_Uld-45sBvHWS_-MCFwha@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. SeaWolves Curve vs. SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vL5h-18

Shop  https //stza.co/+vL5h-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. SeaWolves
END:VALARM
DTSTART:20180503T220000Z
DTEND:20180504T010000Z
UID:4ky_Uld-45sBvHWS_-MCFwha@stanza.co
SUMMARY:Curve vs. SeaWolves
DESCRIPTION:Curve vs. SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vL5h-18\n\nShop: https://stza.co/+vL5h-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. SeaWolves
<2018-05-04 Fri 17:00-20:00>
:PROPERTIES:
:ID:       3QYLenudqHvFvL2v1aZKrmX8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. SeaWolves Curve vs. SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vL5j-3S

Shop  https //stza.co/+vL5j-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. SeaWolves
END:VALARM
DTSTART:20180504T220000Z
DTEND:20180505T010000Z
UID:3QYLenudqHvFvL2v1aZKrmX8@stanza.co
SUMMARY:Curve vs. SeaWolves
DESCRIPTION:Curve vs. SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vL5j-3S\n\nShop: https://stza.co/+vL5j-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. SeaWolves
<2018-05-05 Sat 15:00-18:00>
:PROPERTIES:
:ID:       da14gne6NTSFaTOpjk4nRoQf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve vs. SeaWolves Curve vs. SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vL5m-z

Shop  https //stza.co/+vL5m-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. SeaWolves
END:VALARM
DTSTART:20180505T200000Z
DTEND:20180505T230000Z
UID:da14gne6NTSFaTOpjk4nRoQf@stanza.co
SUMMARY:Curve vs. SeaWolves
DESCRIPTION:Curve vs. SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vL5m-z\n\nShop: https://stza.co/+vL5m-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. SeaWolves
<2018-05-06 Sun 13:00-16:00>
:PROPERTIES:
:ID:       ZL_iNzn_cFMov2KDZd-cDS9U@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. SeaWolves Curve vs. SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vL5n-3i

Shop  https //stza.co/+vL5n-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. SeaWolves
END:VALARM
DTSTART:20180506T180000Z
DTEND:20180506T210000Z
UID:ZL_iNzn_cFMov2KDZd-cDS9U@stanza.co
SUMMARY:Curve vs. SeaWolves
DESCRIPTION:Curve vs. SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vL5n-3i\n\nShop: https://stza.co/+vL5n-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Baysox
<2018-05-07 Mon 17:00-20:00>
:PROPERTIES:
:ID:       girs1Fh4tKLW59f4EASj54Oh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. Baysox Curve vs. Baysox

Follow on MiLB First Pitch  https //stza.co/+vL5p-u

Shop  https //stza.co/+vL5p-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Baysox
END:VALARM
DTSTART:20180507T220000Z
DTEND:20180508T010000Z
UID:girs1Fh4tKLW59f4EASj54Oh@stanza.co
SUMMARY:Curve vs. Baysox
DESCRIPTION:Curve vs. Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vL5p-u\n\nShop: https://stza.co/+vL5p-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Baysox
<2018-05-08 Tue 17:00-20:00>
:PROPERTIES:
:ID:       iMz0V7TIyQTcu2OdhpcN5B9S@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve vs. Baysox Curve vs. Baysox

Follow on MiLB First Pitch  https //stza.co/+vL5r-p

Shop  https //stza.co/+vL5r-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Baysox
END:VALARM
DTSTART:20180508T220000Z
DTEND:20180509T010000Z
UID:iMz0V7TIyQTcu2OdhpcN5B9S@stanza.co
SUMMARY:Curve vs. Baysox
DESCRIPTION:Curve vs. Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vL5r-p\n\nShop: https://stza.co/+vL5r-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Baysox
<2018-05-09 Wed 09:30-12:30>
:PROPERTIES:
:ID:       VZDrFCfF4Dbbxatd8vybBfP7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. Baysox Curve vs. Baysox

Follow on MiLB First Pitch  https //stza.co/+vL5u-J

Shop  https //stza.co/+vL5u-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Baysox
END:VALARM
DTSTART:20180509T143000Z
DTEND:20180509T173000Z
UID:VZDrFCfF4Dbbxatd8vybBfP7@stanza.co
SUMMARY:Curve vs. Baysox
DESCRIPTION:Curve vs. Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vL5u-J\n\nShop: https://stza.co/+vL5u-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Fightin Phils
<2018-05-10 Thu 17:35-20:35>
:PROPERTIES:
:ID:       dgdBABMxRpa4HqZPcJqyoeZ2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Fightin Phils Curve @ Fightin Phils

Buy tickets here  https //stza.co/~vL7I

Follow on MiLB First Pitch  https //stza.co/+vL7I-2O

Shop  https //stza.co/+vL7I-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Fightin Phils
END:VALARM
DTSTART:20180510T223500Z
DTEND:20180511T013500Z
UID:dgdBABMxRpa4HqZPcJqyoeZ2@stanza.co
SUMMARY:Curve @ Fightin Phils
DESCRIPTION:Curve @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vL7I\n\nFollow on MiLB First Pitch: https://stza.co/+vL7I-2O\n\nShop: https://stza.co/+vL7I-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Fightin Phils
<2018-05-11 Fri 18:05-21:05>
:PROPERTIES:
:ID:       UWMVkF0JC36q3aJd4f5QBGz2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve @ Fightin Phils Curve @ Fightin Phils

Buy tickets here  https //stza.co/~vL7J

Follow on MiLB First Pitch  https //stza.co/+vL7J-X

Shop  https //stza.co/+vL7J-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Fightin Phils
END:VALARM
DTSTART:20180511T230500Z
DTEND:20180512T020500Z
UID:UWMVkF0JC36q3aJd4f5QBGz2@stanza.co
SUMMARY:Curve @ Fightin Phils
DESCRIPTION:Curve @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vL7J\n\nFollow on MiLB First Pitch: https://stza.co/+vL7J-X\n\nShop: https://stza.co/+vL7J-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Fightin Phils
<2018-05-12 Sat 17:05-20:05>
:PROPERTIES:
:ID:       BA6r-wDNs5elGZrcXsvLWcgI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Fightin Phils Curve @ Fightin Phils

Buy tickets here  https //stza.co/~vL7K

Follow on MiLB First Pitch  https //stza.co/+vL7K-39

Shop  https //stza.co/+vL7K-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Fightin Phils
END:VALARM
DTSTART:20180512T220500Z
DTEND:20180513T010500Z
UID:BA6r-wDNs5elGZrcXsvLWcgI@stanza.co
SUMMARY:Curve @ Fightin Phils
DESCRIPTION:Curve @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vL7K\n\nFollow on MiLB First Pitch: https://stza.co/+vL7K-39\n\nShop: https://stza.co/+vL7K-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Fightin Phils
<2018-05-13 Sun 13:05-16:05>
:PROPERTIES:
:ID:       FMW13_3KZO5AxaecrzCcUPYE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Fightin Phils Curve @ Fightin Phils

Buy tickets here  https //stza.co/~vL7L

Follow on MiLB First Pitch  https //stza.co/+vL7L-3D

Shop  https //stza.co/+vL7L-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Fightin Phils
END:VALARM
DTSTART:20180513T180500Z
DTEND:20180513T210500Z
UID:FMW13_3KZO5AxaecrzCcUPYE@stanza.co
SUMMARY:Curve @ Fightin Phils
DESCRIPTION:Curve @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vL7L\n\nFollow on MiLB First Pitch: https://stza.co/+vL7L-3D\n\nShop: https://stza.co/+vL7L-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Flying Squirrels
<2018-05-14 Mon 17:00-20:00>
:PROPERTIES:
:ID:       VUae9HeChVjKXR3OKR7FvvdW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve vs. Flying Squirrels Curve vs. Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vL5v-3f

Shop  https //stza.co/+vL5v-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Flying Squirrels
END:VALARM
DTSTART:20180514T220000Z
DTEND:20180515T010000Z
UID:VUae9HeChVjKXR3OKR7FvvdW@stanza.co
SUMMARY:Curve vs. Flying Squirrels
DESCRIPTION:Curve vs. Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vL5v-3f\n\nShop: https://stza.co/+vL5v-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Flying Squirrels
<2018-05-15 Tue 17:00-20:00>
:PROPERTIES:
:ID:       LFPW0S21DUUfO_8y7N6aI1sL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. Flying Squirrels Curve vs. Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vL5y-13

Shop  https //stza.co/+vL5y-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Flying Squirrels
END:VALARM
DTSTART:20180515T220000Z
DTEND:20180516T010000Z
UID:LFPW0S21DUUfO_8y7N6aI1sL@stanza.co
SUMMARY:Curve vs. Flying Squirrels
DESCRIPTION:Curve vs. Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vL5y-13\n\nShop: https://stza.co/+vL5y-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Flying Squirrels
<2018-05-16 Wed 17:00-20:00>
:PROPERTIES:
:ID:       mxXfn_wrcAxcrEBosqM5DAbE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. Flying Squirrels Curve vs. Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vL5z-27

Shop  https //stza.co/+vL5z-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Flying Squirrels
END:VALARM
DTSTART:20180516T220000Z
DTEND:20180517T010000Z
UID:mxXfn_wrcAxcrEBosqM5DAbE@stanza.co
SUMMARY:Curve vs. Flying Squirrels
DESCRIPTION:Curve vs. Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vL5z-27\n\nShop: https://stza.co/+vL5z-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Sea Dogs
<2018-05-17 Thu 17:00-20:00>
:PROPERTIES:
:ID:       3OjilHAZaz1Nf7idh4VzcbCS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve vs. Sea Dogs Curve vs. Sea Dogs

Follow on MiLB First Pitch  https //stza.co/+vL5B-Y

Shop  https //stza.co/+vL5B-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Sea Dogs
END:VALARM
DTSTART:20180517T220000Z
DTEND:20180518T010000Z
UID:3OjilHAZaz1Nf7idh4VzcbCS@stanza.co
SUMMARY:Curve vs. Sea Dogs
DESCRIPTION:Curve vs. Sea Dogs\n\nFollow on MiLB First Pitch: https://stza.co/+vL5B-Y\n\nShop: https://stza.co/+vL5B-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Sea Dogs
<2018-05-18 Fri 17:00-20:00>
:PROPERTIES:
:ID:       mRMXYRUBmZCGdkSRltRU-lGX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. Sea Dogs Curve vs. Sea Dogs

Follow on MiLB First Pitch  https //stza.co/+vL5E-9

Shop  https //stza.co/+vL5E-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Sea Dogs
END:VALARM
DTSTART:20180518T220000Z
DTEND:20180519T010000Z
UID:mRMXYRUBmZCGdkSRltRU-lGX@stanza.co
SUMMARY:Curve vs. Sea Dogs
DESCRIPTION:Curve vs. Sea Dogs\n\nFollow on MiLB First Pitch: https://stza.co/+vL5E-9\n\nShop: https://stza.co/+vL5E-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Sea Dogs
<2018-05-19 Sat 17:00-20:00>
:PROPERTIES:
:ID:       PrPO_tD8-VXrBjIZo7tioaPM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. Sea Dogs Curve vs. Sea Dogs

Follow on MiLB First Pitch  https //stza.co/+vL5G-1t

Shop  https //stza.co/+vL5G-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Sea Dogs
END:VALARM
DTSTART:20180519T220000Z
DTEND:20180520T010000Z
UID:PrPO_tD8-VXrBjIZo7tioaPM@stanza.co
SUMMARY:Curve vs. Sea Dogs
DESCRIPTION:Curve vs. Sea Dogs\n\nFollow on MiLB First Pitch: https://stza.co/+vL5G-1t\n\nShop: https://stza.co/+vL5G-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Sea Dogs
<2018-05-20 Sun 13:00-16:00>
:PROPERTIES:
:ID:       SJE00E758swnm8W1h9eo1n95@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve vs. Sea Dogs Curve vs. Sea Dogs

Follow on MiLB First Pitch  https //stza.co/+vL5H-1x

Shop  https //stza.co/+vL5H-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Sea Dogs
END:VALARM
DTSTART:20180520T180000Z
DTEND:20180520T210000Z
UID:SJE00E758swnm8W1h9eo1n95@stanza.co
SUMMARY:Curve vs. Sea Dogs
DESCRIPTION:Curve vs. Sea Dogs\n\nFollow on MiLB First Pitch: https://stza.co/+vL5H-1x\n\nShop: https://stza.co/+vL5H-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Baysox
<2018-05-22 Tue 17:35-20:35>
:PROPERTIES:
:ID:       rbsN41VZeButCG9doRL_vWzl@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Baysox Curve @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vL78-2n

Shop  https //stza.co/+vL78-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Baysox
END:VALARM
DTSTART:20180522T223500Z
DTEND:20180523T013500Z
UID:rbsN41VZeButCG9doRL_vWzl@stanza.co
SUMMARY:Curve @ Baysox
DESCRIPTION:Curve @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vL78-2n\n\nShop: https://stza.co/+vL78-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Baysox
<2018-05-23 Wed 17:35-20:35>
:PROPERTIES:
:ID:       9FR-Rh4jn7AGS0F0ZFjbljcB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Baysox Curve @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vL79-3I

Shop  https //stza.co/+vL79-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Baysox
END:VALARM
DTSTART:20180523T223500Z
DTEND:20180524T013500Z
UID:9FR-Rh4jn7AGS0F0ZFjbljcB@stanza.co
SUMMARY:Curve @ Baysox
DESCRIPTION:Curve @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vL79-3I\n\nShop: https://stza.co/+vL79-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Baysox
<2018-05-24 Thu 10:05-13:05>
:PROPERTIES:
:ID:       xzC5Ychx2wiuDESZJTFzIKTN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve @ Baysox Curve @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vL7a-3G

Shop  https //stza.co/+vL7a-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Baysox
END:VALARM
DTSTART:20180524T150500Z
DTEND:20180524T180500Z
UID:xzC5Ychx2wiuDESZJTFzIKTN@stanza.co
SUMMARY:Curve @ Baysox
DESCRIPTION:Curve @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vL7a-3G\n\nShop: https://stza.co/+vL7a-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Senators
<2018-05-25 Fri 18:00-21:00>
:PROPERTIES:
:ID:       FQXnjDVUY7a6lpLVuEDOfx6D@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Senators Curve @ Senators

Follow on MiLB First Pitch  https //stza.co/+vL7s-R

Shop  https //stza.co/+vL7s-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Senators
END:VALARM
DTSTART:20180525T230000Z
DTEND:20180526T020000Z
UID:FQXnjDVUY7a6lpLVuEDOfx6D@stanza.co
SUMMARY:Curve @ Senators
DESCRIPTION:Curve @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vL7s-R\n\nShop: https://stza.co/+vL7s-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Senators
<2018-05-26 Sat 17:00-20:00>
:PROPERTIES:
:ID:       nulIsQxbjbptZjANf2UFQ7ju@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Senators Curve @ Senators

Follow on MiLB First Pitch  https //stza.co/+vL7t-2G

Shop  https //stza.co/+vL7t-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Senators
END:VALARM
DTSTART:20180526T220000Z
DTEND:20180527T010000Z
UID:nulIsQxbjbptZjANf2UFQ7ju@stanza.co
SUMMARY:Curve @ Senators
DESCRIPTION:Curve @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vL7t-2G\n\nShop: https://stza.co/+vL7t-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Senators
<2018-05-27 Sun 17:30-20:30>
:PROPERTIES:
:ID:       zG4ByoKt3tX3jiBdDA6LPVHV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve @ Senators Curve @ Senators

Follow on MiLB First Pitch  https //stza.co/+vL7u-1Y

Shop  https //stza.co/+vL7u-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Senators
END:VALARM
DTSTART:20180527T223000Z
DTEND:20180528T013000Z
UID:zG4ByoKt3tX3jiBdDA6LPVHV@stanza.co
SUMMARY:Curve @ Senators
DESCRIPTION:Curve @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vL7u-1Y\n\nShop: https://stza.co/+vL7u-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Senators
<2018-05-28 Mon 11:00-14:00>
:PROPERTIES:
:ID:       yTV0dl09kvzo1cQaOtFLoOR1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Senators Curve @ Senators

Follow on MiLB First Pitch  https //stza.co/+vL7v-1I

Shop  https //stza.co/+vL7v-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Senators
END:VALARM
DTSTART:20180528T160000Z
DTEND:20180528T190000Z
UID:yTV0dl09kvzo1cQaOtFLoOR1@stanza.co
SUMMARY:Curve @ Senators
DESCRIPTION:Curve @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vL7v-1I\n\nShop: https://stza.co/+vL7v-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. RubberDucks
<2018-05-29 Tue 17:00-20:00>
:PROPERTIES:
:ID:       NyRNrq-f9py5QcjH4I_o38r3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. RubberDucks Curve vs. RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vL5J-3k

Shop  https //stza.co/+vL5J-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. RubberDucks
END:VALARM
DTSTART:20180529T220000Z
DTEND:20180530T010000Z
UID:NyRNrq-f9py5QcjH4I_o38r3@stanza.co
SUMMARY:Curve vs. RubberDucks
DESCRIPTION:Curve vs. RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vL5J-3k\n\nShop: https://stza.co/+vL5J-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. RubberDucks
<2018-05-30 Wed 17:00-20:00>
:PROPERTIES:
:ID:       nLjHfDXMvA4PGxPbCuqPkdlu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve vs. RubberDucks Curve vs. RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vL5L-3J

Shop  https //stza.co/+vL5L-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. RubberDucks
END:VALARM
DTSTART:20180530T220000Z
DTEND:20180531T010000Z
UID:nLjHfDXMvA4PGxPbCuqPkdlu@stanza.co
SUMMARY:Curve vs. RubberDucks
DESCRIPTION:Curve vs. RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vL5L-3J\n\nShop: https://stza.co/+vL5L-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. RubberDucks
<2018-05-31 Thu 09:30-12:30>
:PROPERTIES:
:ID:       m3-C0rIBINgmtRKYZ8qp76-E@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. RubberDucks Curve vs. RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vL5N-3h

Shop  https //stza.co/+vL5N-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. RubberDucks
END:VALARM
DTSTART:20180531T143000Z
DTEND:20180531T173000Z
UID:m3-C0rIBINgmtRKYZ8qp76-E@stanza.co
SUMMARY:Curve vs. RubberDucks
DESCRIPTION:Curve vs. RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vL5N-3h\n\nShop: https://stza.co/+vL5N-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Yard Goats
<2018-06-01 Fri 18:05-21:05>
:PROPERTIES:
:ID:       WKL1UYc9S_l0DTbP7iyoRs9X@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Yard Goats Curve @ Yard Goats

Buy tickets here  https //stza.co/~vL7z

Follow on MiLB First Pitch  https //stza.co/+vL7z-W

Shop  https //stza.co/+vL7z-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Yard Goats
END:VALARM
DTSTART:20180601T230500Z
DTEND:20180602T020500Z
UID:WKL1UYc9S_l0DTbP7iyoRs9X@stanza.co
SUMMARY:Curve @ Yard Goats
DESCRIPTION:Curve @ Yard Goats\n\nBuy tickets here: https://stza.co/~vL7z\n\nFollow on MiLB First Pitch: https://stza.co/+vL7z-W\n\nShop: https://stza.co/+vL7z-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Yard Goats
<2018-06-02 Sat 17:05-20:05>
:PROPERTIES:
:ID:       _Yu-bqxPuWHrGhz3VHJoysjF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve @ Yard Goats Curve @ Yard Goats

Buy tickets here  https //stza.co/~vL7A

Follow on MiLB First Pitch  https //stza.co/+vL7A-W

Shop  https //stza.co/+vL7A-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Yard Goats
END:VALARM
DTSTART:20180602T220500Z
DTEND:20180603T010500Z
UID:_Yu-bqxPuWHrGhz3VHJoysjF@stanza.co
SUMMARY:Curve @ Yard Goats
DESCRIPTION:Curve @ Yard Goats\n\nBuy tickets here: https://stza.co/~vL7A\n\nFollow on MiLB First Pitch: https://stza.co/+vL7A-W\n\nShop: https://stza.co/+vL7A-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Yard Goats
<2018-06-03 Sun 12:05-15:05>
:PROPERTIES:
:ID:       0PKUX3UOMVt5N70zBwFdK33e@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Yard Goats Curve @ Yard Goats

Buy tickets here  https //stza.co/~vL7B

Follow on MiLB First Pitch  https //stza.co/+vL7B-K

Shop  https //stza.co/+vL7B-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Yard Goats
END:VALARM
DTSTART:20180603T170500Z
DTEND:20180603T200500Z
UID:0PKUX3UOMVt5N70zBwFdK33e@stanza.co
SUMMARY:Curve @ Yard Goats
DESCRIPTION:Curve @ Yard Goats\n\nBuy tickets here: https://stza.co/~vL7B\n\nFollow on MiLB First Pitch: https://stza.co/+vL7B-K\n\nShop: https://stza.co/+vL7B-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Fightin Phils
<2018-06-05 Tue 18:00-21:00>
:PROPERTIES:
:ID:       Lj6mTFzzadyy0P_w5Ld1qaDR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. Fightin Phils Curve vs. Fightin Phils

Follow on MiLB First Pitch  https //stza.co/+vL5Q-2f

Shop  https //stza.co/+vL5Q-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Fightin Phils
END:VALARM
DTSTART:20180605T230000Z
DTEND:20180606T020000Z
UID:Lj6mTFzzadyy0P_w5Ld1qaDR@stanza.co
SUMMARY:Curve vs. Fightin Phils
DESCRIPTION:Curve vs. Fightin Phils\n\nFollow on MiLB First Pitch: https://stza.co/+vL5Q-2f\n\nShop: https://stza.co/+vL5Q-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Fightin Phils
<2018-06-06 Wed 18:00-21:00>
:PROPERTIES:
:ID:       Z0H9ZsOhH1i4z0k_b8IaALZL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve vs. Fightin Phils Curve vs. Fightin Phils

Follow on MiLB First Pitch  https //stza.co/+vL5R-8

Shop  https //stza.co/+vL5R-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Fightin Phils
END:VALARM
DTSTART:20180606T230000Z
DTEND:20180607T020000Z
UID:Z0H9ZsOhH1i4z0k_b8IaALZL@stanza.co
SUMMARY:Curve vs. Fightin Phils
DESCRIPTION:Curve vs. Fightin Phils\n\nFollow on MiLB First Pitch: https://stza.co/+vL5R-8\n\nShop: https://stza.co/+vL5R-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Fightin Phils
<2018-06-07 Thu 18:00-21:00>
:PROPERTIES:
:ID:       VDD5OzZfsz2b3c-_UEdKWZTE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. Fightin Phils Curve vs. Fightin Phils

Follow on MiLB First Pitch  https //stza.co/+vL5U-25

Shop  https //stza.co/+vL5U-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Fightin Phils
END:VALARM
DTSTART:20180607T230000Z
DTEND:20180608T020000Z
UID:VDD5OzZfsz2b3c-_UEdKWZTE@stanza.co
SUMMARY:Curve vs. Fightin Phils
DESCRIPTION:Curve vs. Fightin Phils\n\nFollow on MiLB First Pitch: https://stza.co/+vL5U-25\n\nShop: https://stza.co/+vL5U-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Yard Goats
<2018-06-08 Fri 18:00-21:00>
:PROPERTIES:
:ID:       Cmr8PyErMMOrc9dsmScxxTXz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. Yard Goats Curve vs. Yard Goats

Follow on MiLB First Pitch  https //stza.co/+vL5V-1w

Shop  https //stza.co/+vL5V-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Yard Goats
END:VALARM
DTSTART:20180608T230000Z
DTEND:20180609T020000Z
UID:Cmr8PyErMMOrc9dsmScxxTXz@stanza.co
SUMMARY:Curve vs. Yard Goats
DESCRIPTION:Curve vs. Yard Goats\n\nFollow on MiLB First Pitch: https://stza.co/+vL5V-1w\n\nShop: https://stza.co/+vL5V-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Yard Goats
<2018-06-09 Sat 17:00-20:00>
:PROPERTIES:
:ID:       z07ejx2zfz6_iNBoO062UrKP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve vs. Yard Goats Curve vs. Yard Goats

Follow on MiLB First Pitch  https //stza.co/+vL5Y-3G

Shop  https //stza.co/+vL5Y-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Yard Goats
END:VALARM
DTSTART:20180609T220000Z
DTEND:20180610T010000Z
UID:z07ejx2zfz6_iNBoO062UrKP@stanza.co
SUMMARY:Curve vs. Yard Goats
DESCRIPTION:Curve vs. Yard Goats\n\nFollow on MiLB First Pitch: https://stza.co/+vL5Y-3G\n\nShop: https://stza.co/+vL5Y-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Yard Goats
<2018-06-10 Sun 13:00-16:00>
:PROPERTIES:
:ID:       0-uatG_CQOTsaQNKvsEh1nS9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. Yard Goats Curve vs. Yard Goats

Follow on MiLB First Pitch  https //stza.co/+vL5_-2Y

Shop  https //stza.co/+vL5_-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Yard Goats
END:VALARM
DTSTART:20180610T180000Z
DTEND:20180610T210000Z
UID:0-uatG_CQOTsaQNKvsEh1nS9@stanza.co
SUMMARY:Curve vs. Yard Goats
DESCRIPTION:Curve vs. Yard Goats\n\nFollow on MiLB First Pitch: https://stza.co/+vL5_-2Y\n\nShop: https://stza.co/+vL5_-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Rumble Ponies
<2018-06-12 Tue 17:35-20:35>
:PROPERTIES:
:ID:       eLE2F7xnGfgqbLKcu1-edGgV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Rumble Ponies Curve @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vL73-2z

Shop  https //stza.co/+vL73-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Rumble Ponies
END:VALARM
DTSTART:20180612T223500Z
DTEND:20180613T013500Z
UID:eLE2F7xnGfgqbLKcu1-edGgV@stanza.co
SUMMARY:Curve @ Rumble Ponies
DESCRIPTION:Curve @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vL73-2z\n\nShop: https://stza.co/+vL73-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Rumble Ponies
<2018-06-13 Wed 17:35-20:35>
:PROPERTIES:
:ID:       hbiwC_RiVsQvp3QAocam4QOm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve @ Rumble Ponies Curve @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vL74-x

Shop  https //stza.co/+vL74-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Rumble Ponies
END:VALARM
DTSTART:20180613T223500Z
DTEND:20180614T013500Z
UID:hbiwC_RiVsQvp3QAocam4QOm@stanza.co
SUMMARY:Curve @ Rumble Ponies
DESCRIPTION:Curve @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vL74-x\n\nShop: https://stza.co/+vL74-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Rumble Ponies
<2018-06-14 Thu 09:35-12:35>
:PROPERTIES:
:ID:       b8TC5oM2roO3kmozEQI3vykM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Rumble Ponies Curve @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vL75-p

Shop  https //stza.co/+vL75-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Rumble Ponies
END:VALARM
DTSTART:20180614T143500Z
DTEND:20180614T173500Z
UID:b8TC5oM2roO3kmozEQI3vykM@stanza.co
SUMMARY:Curve @ Rumble Ponies
DESCRIPTION:Curve @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vL75-p\n\nShop: https://stza.co/+vL75-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Fisher Cats
<2018-06-15 Fri 18:00-21:00>
:PROPERTIES:
:ID:       LmBbL4yF0zX0fAELJnkddGTl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. Fisher Cats Curve vs. Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vL5$-3H

Shop  https //stza.co/+vL5$-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Fisher Cats
END:VALARM
DTSTART:20180615T230000Z
DTEND:20180616T020000Z
UID:LmBbL4yF0zX0fAELJnkddGTl@stanza.co
SUMMARY:Curve vs. Fisher Cats
DESCRIPTION:Curve vs. Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vL5$-3H\n\nShop: https://stza.co/+vL5$-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Fisher Cats
<2018-06-16 Sat 17:00-20:00>
:PROPERTIES:
:ID:       RyrHXLBDd3HkXpaHYzlb8xYU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve vs. Fisher Cats Curve vs. Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vL62-1u

Shop  https //stza.co/+vL62-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Fisher Cats
END:VALARM
DTSTART:20180616T220000Z
DTEND:20180617T010000Z
UID:RyrHXLBDd3HkXpaHYzlb8xYU@stanza.co
SUMMARY:Curve vs. Fisher Cats
DESCRIPTION:Curve vs. Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vL62-1u\n\nShop: https://stza.co/+vL62-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Fisher Cats
<2018-06-17 Sun 17:00-20:00>
:PROPERTIES:
:ID:       Ve_dqFna6pewHYubFw1hy7vc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. Fisher Cats Curve vs. Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vL64-2k

Shop  https //stza.co/+vL64-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Fisher Cats
END:VALARM
DTSTART:20180617T220000Z
DTEND:20180618T010000Z
UID:Ve_dqFna6pewHYubFw1hy7vc@stanza.co
SUMMARY:Curve vs. Fisher Cats
DESCRIPTION:Curve vs. Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vL64-2k\n\nShop: https://stza.co/+vL64-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Flying Squirrels
<2018-06-19 Tue 17:35-20:35>
:PROPERTIES:
:ID:       5bIlX2Njf78xHmAMPlQrcMbD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Flying Squirrels Curve @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+v6Up-r

Shop  https //stza.co/+v6Up-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Flying Squirrels
END:VALARM
DTSTART:20180619T223500Z
DTEND:20180620T013500Z
UID:5bIlX2Njf78xHmAMPlQrcMbD@stanza.co
SUMMARY:Curve @ Flying Squirrels
DESCRIPTION:Curve @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+v6Up-r\n\nShop: https://stza.co/+v6Up-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Flying Squirrels
<2018-06-20 Wed 17:35-20:35>
:PROPERTIES:
:ID:       Rmgk8elZgh53OTs9zF9IZS1O@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve @ Flying Squirrels Curve @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+v6UE-2D

Shop  https //stza.co/+v6UE-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Flying Squirrels
END:VALARM
DTSTART:20180620T223500Z
DTEND:20180621T013500Z
UID:Rmgk8elZgh53OTs9zF9IZS1O@stanza.co
SUMMARY:Curve @ Flying Squirrels
DESCRIPTION:Curve @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+v6UE-2D\n\nShop: https://stza.co/+v6UE-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Flying Squirrels
<2018-06-21 Thu 17:35-20:35>
:PROPERTIES:
:ID:       pzHiG4pDiWnfPK26vsC6-EjK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Flying Squirrels Curve @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+v6UT-Y

Shop  https //stza.co/+v6UT-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Flying Squirrels
END:VALARM
DTSTART:20180621T223500Z
DTEND:20180622T013500Z
UID:pzHiG4pDiWnfPK26vsC6-EjK@stanza.co
SUMMARY:Curve @ Flying Squirrels
DESCRIPTION:Curve @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+v6UT-Y\n\nShop: https://stza.co/+v6UT-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ SeaWolves
<2018-06-22 Fri 18:05-21:05>
:PROPERTIES:
:ID:       M4tBWKdwcV2h24dpj4TxFk1E@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ SeaWolves Curve @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vL7i-2W

Shop  https //stza.co/+vL7i-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ SeaWolves
END:VALARM
DTSTART:20180622T230500Z
DTEND:20180623T020500Z
UID:M4tBWKdwcV2h24dpj4TxFk1E@stanza.co
SUMMARY:Curve @ SeaWolves
DESCRIPTION:Curve @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vL7i-2W\n\nShop: https://stza.co/+vL7i-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ SeaWolves
<2018-06-23 Sat 18:05-21:05>
:PROPERTIES:
:ID:       pgbyiFF2PZrbGu3icSNANwhL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve @ SeaWolves Curve @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vL7j-3m

Shop  https //stza.co/+vL7j-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ SeaWolves
END:VALARM
DTSTART:20180623T230500Z
DTEND:20180624T020500Z
UID:pgbyiFF2PZrbGu3icSNANwhL@stanza.co
SUMMARY:Curve @ SeaWolves
DESCRIPTION:Curve @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vL7j-3m\n\nShop: https://stza.co/+vL7j-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ SeaWolves
<2018-06-24 Sun 12:35-15:35>
:PROPERTIES:
:ID:       YivwbK0AIZHH6k2ORPyAxI0P@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ SeaWolves Curve @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vL7k-2W

Shop  https //stza.co/+vL7k-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ SeaWolves
END:VALARM
DTSTART:20180624T173500Z
DTEND:20180624T203500Z
UID:YivwbK0AIZHH6k2ORPyAxI0P@stanza.co
SUMMARY:Curve @ SeaWolves
DESCRIPTION:Curve @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vL7k-2W\n\nShop: https://stza.co/+vL7k-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Senators
<2018-06-25 Mon 18:00-21:00>
:PROPERTIES:
:ID:       nbkxKPbk9pT0JBUy6ZftVnyO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. Senators Curve vs. Senators

Follow on MiLB First Pitch  https //stza.co/+vL65-z

Shop  https //stza.co/+vL65-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Senators
END:VALARM
DTSTART:20180625T230000Z
DTEND:20180626T020000Z
UID:nbkxKPbk9pT0JBUy6ZftVnyO@stanza.co
SUMMARY:Curve vs. Senators
DESCRIPTION:Curve vs. Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vL65-z\n\nShop: https://stza.co/+vL65-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Senators
<2018-06-26 Tue 18:00-21:00>
:PROPERTIES:
:ID:       1aGodhWcikUnDjGaHUTZ4YUV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve vs. Senators Curve vs. Senators

Follow on MiLB First Pitch  https //stza.co/+vL68-7

Shop  https //stza.co/+vL68-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Senators
END:VALARM
DTSTART:20180626T230000Z
DTEND:20180627T020000Z
UID:1aGodhWcikUnDjGaHUTZ4YUV@stanza.co
SUMMARY:Curve vs. Senators
DESCRIPTION:Curve vs. Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vL68-7\n\nShop: https://stza.co/+vL68-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Senators
<2018-06-27 Wed 18:00-21:00>
:PROPERTIES:
:ID:       ZJwmsa9Gg5HrQFCS3mFmIEP4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. Senators Curve vs. Senators

Follow on MiLB First Pitch  https //stza.co/+vL6a-3I

Shop  https //stza.co/+vL6a-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Senators
END:VALARM
DTSTART:20180627T230000Z
DTEND:20180628T020000Z
UID:ZJwmsa9Gg5HrQFCS3mFmIEP4@stanza.co
SUMMARY:Curve vs. Senators
DESCRIPTION:Curve vs. Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vL6a-3I\n\nShop: https://stza.co/+vL6a-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Senators
<2018-06-28 Thu 18:00-21:00>
:PROPERTIES:
:ID:       qDV4KQF-qjuVn3z7tuNbYmoJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. Senators Curve vs. Senators

Follow on MiLB First Pitch  https //stza.co/+vL6c-1Q

Shop  https //stza.co/+vL6c-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Senators
END:VALARM
DTSTART:20180628T230000Z
DTEND:20180629T020000Z
UID:qDV4KQF-qjuVn3z7tuNbYmoJ@stanza.co
SUMMARY:Curve vs. Senators
DESCRIPTION:Curve vs. Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vL6c-1Q\n\nShop: https://stza.co/+vL6c-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ RubberDucks
<2018-06-29 Fri 18:05-21:05>
:PROPERTIES:
:ID:       6N5y9kBMT3DcNb4dPoBBEnhh@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve @ RubberDucks Curve @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vL4L-2y

Shop  https //stza.co/+vL4L-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ RubberDucks
END:VALARM
DTSTART:20180629T230500Z
DTEND:20180630T020500Z
UID:6N5y9kBMT3DcNb4dPoBBEnhh@stanza.co
SUMMARY:Curve @ RubberDucks
DESCRIPTION:Curve @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vL4L-2y\n\nShop: https://stza.co/+vL4L-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ RubberDucks
<2018-06-30 Sat 18:05-21:05>
:PROPERTIES:
:ID:       Whu93E3GgJL2Xane8rc2LsGd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ RubberDucks Curve @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vL4M-3o

Shop  https //stza.co/+vL4M-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ RubberDucks
END:VALARM
DTSTART:20180630T230500Z
DTEND:20180701T020500Z
UID:Whu93E3GgJL2Xane8rc2LsGd@stanza.co
SUMMARY:Curve @ RubberDucks
DESCRIPTION:Curve @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vL4M-3o\n\nShop: https://stza.co/+vL4M-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ RubberDucks
<2018-07-01 Sun 13:05-16:05>
:PROPERTIES:
:ID:       5D2YsfPa3oflD-hstdRni8uG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ RubberDucks Curve @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vL4N-p

Shop  https //stza.co/+vL4N-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ RubberDucks
END:VALARM
DTSTART:20180701T180500Z
DTEND:20180701T210500Z
UID:5D2YsfPa3oflD-hstdRni8uG@stanza.co
SUMMARY:Curve @ RubberDucks
DESCRIPTION:Curve @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vL4N-p\n\nShop: https://stza.co/+vL4N-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ RubberDucks
<2018-07-02 Mon 18:05-21:05>
:PROPERTIES:
:ID:       avyZYjKSAoTKFgZxoPiJICUI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve @ RubberDucks Curve @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vL4O-w

Shop  https //stza.co/+vL4O-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ RubberDucks
END:VALARM
DTSTART:20180702T230500Z
DTEND:20180703T020500Z
UID:avyZYjKSAoTKFgZxoPiJICUI@stanza.co
SUMMARY:Curve @ RubberDucks
DESCRIPTION:Curve @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vL4O-w\n\nShop: https://stza.co/+vL4O-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ RubberDucks
<2018-07-03 Tue 18:05-21:05>
:PROPERTIES:
:ID:       JencAGtLsI9uWMs3fFARD4H1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ RubberDucks Curve @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vL4P-S

Shop  https //stza.co/+vL4P-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ RubberDucks
END:VALARM
DTSTART:20180703T230500Z
DTEND:20180704T020500Z
UID:JencAGtLsI9uWMs3fFARD4H1@stanza.co
SUMMARY:Curve @ RubberDucks
DESCRIPTION:Curve @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vL4P-S\n\nShop: https://stza.co/+vL4P-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Thunder
<2018-07-04 Wed 18:00-21:00>
:PROPERTIES:
:ID:       Kyf4yK7PBctKWL72ul7ov2So@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. Thunder Curve vs. Thunder

Follow on MiLB First Pitch  https //stza.co/+vL6e-1Q

Shop  https //stza.co/+vL6e-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Thunder
END:VALARM
DTSTART:20180704T230000Z
DTEND:20180705T020000Z
UID:Kyf4yK7PBctKWL72ul7ov2So@stanza.co
SUMMARY:Curve vs. Thunder
DESCRIPTION:Curve vs. Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vL6e-1Q\n\nShop: https://stza.co/+vL6e-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Thunder
<2018-07-05 Thu 18:00-21:00>
:PROPERTIES:
:ID:       FPQB4PPfiauFplwe1nUig--j@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve vs. Thunder Curve vs. Thunder

Follow on MiLB First Pitch  https //stza.co/+vL6g-3c

Shop  https //stza.co/+vL6g-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Thunder
END:VALARM
DTSTART:20180705T230000Z
DTEND:20180706T020000Z
UID:FPQB4PPfiauFplwe1nUig--j@stanza.co
SUMMARY:Curve vs. Thunder
DESCRIPTION:Curve vs. Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vL6g-3c\n\nShop: https://stza.co/+vL6g-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Thunder
<2018-07-06 Fri 18:00-21:00>
:PROPERTIES:
:ID:       L4hYF75wBWTWTKxFNisruUj5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. Thunder Curve vs. Thunder

Follow on MiLB First Pitch  https //stza.co/+vL6h-1D

Shop  https //stza.co/+vL6h-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Thunder
END:VALARM
DTSTART:20180706T230000Z
DTEND:20180707T020000Z
UID:L4hYF75wBWTWTKxFNisruUj5@stanza.co
SUMMARY:Curve vs. Thunder
DESCRIPTION:Curve vs. Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vL6h-1D\n\nShop: https://stza.co/+vL6h-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Thunder
<2018-07-07 Sat 17:00-20:00>
:PROPERTIES:
:ID:       SDRFVbrOrcekqYtjNIaI25kf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. Thunder Curve vs. Thunder

Follow on MiLB First Pitch  https //stza.co/+vL6k-2v

Shop  https //stza.co/+vL6k-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Thunder
END:VALARM
DTSTART:20180707T220000Z
DTEND:20180708T010000Z
UID:SDRFVbrOrcekqYtjNIaI25kf@stanza.co
SUMMARY:Curve vs. Thunder
DESCRIPTION:Curve vs. Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vL6k-2v\n\nShop: https://stza.co/+vL6k-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Thunder
<2018-07-08 Sun 13:00-16:00>
:PROPERTIES:
:ID:       GAGsSW5xMw6Y0J_Cr_rbgWSI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve vs. Thunder Curve vs. Thunder

Follow on MiLB First Pitch  https //stza.co/+vL6l-e

Shop  https //stza.co/+vL6l-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Thunder
END:VALARM
DTSTART:20180708T180000Z
DTEND:20180708T210000Z
UID:GAGsSW5xMw6Y0J_Cr_rbgWSI@stanza.co
SUMMARY:Curve vs. Thunder
DESCRIPTION:Curve vs. Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vL6l-e\n\nShop: https://stza.co/+vL6l-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ SeaWolves
<2018-07-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       QyMak07J24rA_859vJXs7714@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ SeaWolves Curve @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vL7l-2b

Shop  https //stza.co/+vL7l-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ SeaWolves
END:VALARM
DTSTART:20180712T230500Z
DTEND:20180713T020500Z
UID:QyMak07J24rA_859vJXs7714@stanza.co
SUMMARY:Curve @ SeaWolves
DESCRIPTION:Curve @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vL7l-2b\n\nShop: https://stza.co/+vL7l-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ SeaWolves
<2018-07-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       xo0tRFlBOmz0vzItLW-Nj6kp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ SeaWolves Curve @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vL7m-X

Shop  https //stza.co/+vL7m-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ SeaWolves
END:VALARM
DTSTART:20180713T230500Z
DTEND:20180714T020500Z
UID:xo0tRFlBOmz0vzItLW-Nj6kp@stanza.co
SUMMARY:Curve @ SeaWolves
DESCRIPTION:Curve @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vL7m-X\n\nShop: https://stza.co/+vL7m-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ SeaWolves
<2018-07-14 Sat 18:05-21:05>
:PROPERTIES:
:ID:       NEbj-r8A73gb2ovId_Pd_Ab2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve @ SeaWolves Curve @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vL7n-1l

Shop  https //stza.co/+vL7n-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ SeaWolves
END:VALARM
DTSTART:20180714T230500Z
DTEND:20180715T020500Z
UID:NEbj-r8A73gb2ovId_Pd_Ab2@stanza.co
SUMMARY:Curve @ SeaWolves
DESCRIPTION:Curve @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vL7n-1l\n\nShop: https://stza.co/+vL7n-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ SeaWolves
<2018-07-15 Sun 12:35-15:35>
:PROPERTIES:
:ID:       iIt5yBzyD_iXmkcpmiHBcOww@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ SeaWolves Curve @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vL7o-2V

Shop  https //stza.co/+vL7o-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ SeaWolves
END:VALARM
DTSTART:20180715T173500Z
DTEND:20180715T203500Z
UID:iIt5yBzyD_iXmkcpmiHBcOww@stanza.co
SUMMARY:Curve @ SeaWolves
DESCRIPTION:Curve @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vL7o-2V\n\nShop: https://stza.co/+vL7o-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Baysox
<2018-07-16 Mon 18:00-21:00>
:PROPERTIES:
:ID:       AWBg04wPvlQPYdXHtC3TGWNH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. Baysox Curve vs. Baysox

Follow on MiLB First Pitch  https //stza.co/+vL6n-1s

Shop  https //stza.co/+vL6n-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Baysox
END:VALARM
DTSTART:20180716T230000Z
DTEND:20180717T020000Z
UID:AWBg04wPvlQPYdXHtC3TGWNH@stanza.co
SUMMARY:Curve vs. Baysox
DESCRIPTION:Curve vs. Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vL6n-1s\n\nShop: https://stza.co/+vL6n-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Baysox
<2018-07-17 Tue 18:00-21:00>
:PROPERTIES:
:ID:       rpIzi7CdTuZfDw4EV4avjPQs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve vs. Baysox Curve vs. Baysox

Follow on MiLB First Pitch  https //stza.co/+vL6p-3q

Shop  https //stza.co/+vL6p-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Baysox
END:VALARM
DTSTART:20180717T230000Z
DTEND:20180718T020000Z
UID:rpIzi7CdTuZfDw4EV4avjPQs@stanza.co
SUMMARY:Curve vs. Baysox
DESCRIPTION:Curve vs. Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vL6p-3q\n\nShop: https://stza.co/+vL6p-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Baysox
<2018-07-18 Wed 11:00-14:00>
:PROPERTIES:
:ID:       1kauw7LVsCDsaYueJ5Jo94Da@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. Baysox Curve vs. Baysox

Follow on MiLB First Pitch  https //stza.co/+vL6s-3y

Shop  https //stza.co/+vL6s-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Baysox
END:VALARM
DTSTART:20180718T160000Z
DTEND:20180718T190000Z
UID:1kauw7LVsCDsaYueJ5Jo94Da@stanza.co
SUMMARY:Curve vs. Baysox
DESCRIPTION:Curve vs. Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vL6s-3y\n\nShop: https://stza.co/+vL6s-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Fightin Phils
<2018-07-19 Thu 18:05-21:05>
:PROPERTIES:
:ID:       h6SwMt4l8OiACl4ID69IILtz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Fightin Phils Curve @ Fightin Phils

Buy tickets here  https //stza.co/~vL7M

Follow on MiLB First Pitch  https //stza.co/+vL7M-I

Shop  https //stza.co/+vL7M-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Fightin Phils
END:VALARM
DTSTART:20180719T230500Z
DTEND:20180720T020500Z
UID:h6SwMt4l8OiACl4ID69IILtz@stanza.co
SUMMARY:Curve @ Fightin Phils
DESCRIPTION:Curve @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vL7M\n\nFollow on MiLB First Pitch: https://stza.co/+vL7M-I\n\nShop: https://stza.co/+vL7M-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Fightin Phils
<2018-07-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       2uQ8-HfUhMNyzosXRQsiyhUi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve @ Fightin Phils Curve @ Fightin Phils

Buy tickets here  https //stza.co/~vL7N

Follow on MiLB First Pitch  https //stza.co/+vL7N-2L

Shop  https //stza.co/+vL7N-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Fightin Phils
END:VALARM
DTSTART:20180720T230500Z
DTEND:20180721T020500Z
UID:2uQ8-HfUhMNyzosXRQsiyhUi@stanza.co
SUMMARY:Curve @ Fightin Phils
DESCRIPTION:Curve @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vL7N\n\nFollow on MiLB First Pitch: https://stza.co/+vL7N-2L\n\nShop: https://stza.co/+vL7N-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Fightin Phils
<2018-07-21 Sat 17:35-20:35>
:PROPERTIES:
:ID:       D2QVqGxqXl-XEwnm3KrRjYlc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Fightin Phils Curve @ Fightin Phils

Buy tickets here  https //stza.co/~vL7O

Follow on MiLB First Pitch  https //stza.co/+vL7O-W

Shop  https //stza.co/+vL7O-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Fightin Phils
END:VALARM
DTSTART:20180721T223500Z
DTEND:20180722T013500Z
UID:D2QVqGxqXl-XEwnm3KrRjYlc@stanza.co
SUMMARY:Curve @ Fightin Phils
DESCRIPTION:Curve @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vL7O\n\nFollow on MiLB First Pitch: https://stza.co/+vL7O-W\n\nShop: https://stza.co/+vL7O-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Fightin Phils
<2018-07-22 Sun 16:05-19:05>
:PROPERTIES:
:ID:       UHztoAIkFLIYS156T7sDs9Us@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Fightin Phils Curve @ Fightin Phils

Buy tickets here  https //stza.co/~vL7P

Follow on MiLB First Pitch  https //stza.co/+vL7P-3W

Shop  https //stza.co/+vL7P-1J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Fightin Phils
END:VALARM
DTSTART:20180722T210500Z
DTEND:20180723T000500Z
UID:UHztoAIkFLIYS156T7sDs9Us@stanza.co
SUMMARY:Curve @ Fightin Phils
DESCRIPTION:Curve @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vL7P\n\nFollow on MiLB First Pitch: https://stza.co/+vL7P-3W\n\nShop: https://stza.co/+vL7P-1J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ RubberDucks
<2018-07-23 Mon 18:05-21:05>
:PROPERTIES:
:ID:       joT1vgiXDxVrD9ftu7i-c9mf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve @ RubberDucks Curve @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vL4Q-3E

Shop  https //stza.co/+vL4Q-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ RubberDucks
END:VALARM
DTSTART:20180723T230500Z
DTEND:20180724T020500Z
UID:joT1vgiXDxVrD9ftu7i-c9mf@stanza.co
SUMMARY:Curve @ RubberDucks
DESCRIPTION:Curve @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vL4Q-3E\n\nShop: https://stza.co/+vL4Q-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ RubberDucks
<2018-07-24 Tue 18:05-21:05>
:PROPERTIES:
:ID:       Q9DLHfJmbSvI2pLy6F7QxRhu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ RubberDucks Curve @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vL4R-17

Shop  https //stza.co/+vL4R-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ RubberDucks
END:VALARM
DTSTART:20180724T230500Z
DTEND:20180725T020500Z
UID:Q9DLHfJmbSvI2pLy6F7QxRhu@stanza.co
SUMMARY:Curve @ RubberDucks
DESCRIPTION:Curve @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vL4R-17\n\nShop: https://stza.co/+vL4R-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ RubberDucks
<2018-07-25 Wed 11:05-14:05>
:PROPERTIES:
:ID:       dHsXjsGGebobBFEnIPFNG1i9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ RubberDucks Curve @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vL4S-2H

Shop  https //stza.co/+vL4S-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ RubberDucks
END:VALARM
DTSTART:20180725T160500Z
DTEND:20180725T190500Z
UID:dHsXjsGGebobBFEnIPFNG1i9@stanza.co
SUMMARY:Curve @ RubberDucks
DESCRIPTION:Curve @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vL4S-2H\n\nShop: https://stza.co/+vL4S-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Rumble Ponies
<2018-07-26 Thu 18:00-21:00>
:PROPERTIES:
:ID:       iZgEKkL-4ZgmA8jFPs4RhCVz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve vs. Rumble Ponies Curve vs. Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vL6t-3h

Shop  https //stza.co/+vL6t-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Rumble Ponies
END:VALARM
DTSTART:20180726T230000Z
DTEND:20180727T020000Z
UID:iZgEKkL-4ZgmA8jFPs4RhCVz@stanza.co
SUMMARY:Curve vs. Rumble Ponies
DESCRIPTION:Curve vs. Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vL6t-3h\n\nShop: https://stza.co/+vL6t-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Rumble Ponies
<2018-07-27 Fri 18:00-21:00>
:PROPERTIES:
:ID:       rsHJAZf31wAfxUQIzkTRFfTA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. Rumble Ponies Curve vs. Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vL6w-t

Shop  https //stza.co/+vL6w-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Rumble Ponies
END:VALARM
DTSTART:20180727T230000Z
DTEND:20180728T020000Z
UID:rsHJAZf31wAfxUQIzkTRFfTA@stanza.co
SUMMARY:Curve vs. Rumble Ponies
DESCRIPTION:Curve vs. Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vL6w-t\n\nShop: https://stza.co/+vL6w-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Rumble Ponies
<2018-07-28 Sat 17:00-20:00>
:PROPERTIES:
:ID:       74NUOvhTPyRsOkr1959gG-Rd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. Rumble Ponies Curve vs. Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vL6y-1F

Shop  https //stza.co/+vL6y-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Rumble Ponies
END:VALARM
DTSTART:20180728T220000Z
DTEND:20180729T010000Z
UID:74NUOvhTPyRsOkr1959gG-Rd@stanza.co
SUMMARY:Curve vs. Rumble Ponies
DESCRIPTION:Curve vs. Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vL6y-1F\n\nShop: https://stza.co/+vL6y-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Rumble Ponies
<2018-07-29 Sun 13:00-16:00>
:PROPERTIES:
:ID:       ztsb5GpBMMKt7DSGv3vrcE-i@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve vs. Rumble Ponies Curve vs. Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vL6A-22

Shop  https //stza.co/+vL6A-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Rumble Ponies
END:VALARM
DTSTART:20180729T180000Z
DTEND:20180729T210000Z
UID:ztsb5GpBMMKt7DSGv3vrcE-i@stanza.co
SUMMARY:Curve vs. Rumble Ponies
DESCRIPTION:Curve vs. Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vL6A-22\n\nShop: https://stza.co/+vL6A-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Senators
<2018-07-31 Tue 17:30-20:30>
:PROPERTIES:
:ID:       WtrzX5PS8OXOp7-KWtZcWzNF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Senators Curve @ Senators

Follow on MiLB First Pitch  https //stza.co/+vL7w-1B

Shop  https //stza.co/+vL7w-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Senators
END:VALARM
DTSTART:20180731T223000Z
DTEND:20180801T013000Z
UID:WtrzX5PS8OXOp7-KWtZcWzNF@stanza.co
SUMMARY:Curve @ Senators
DESCRIPTION:Curve @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vL7w-1B\n\nShop: https://stza.co/+vL7w-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Senators
<2018-08-01 Wed 17:30-20:30>
:PROPERTIES:
:ID:       J8idqmLo-qRvNz5JnaQ4BaNY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Senators Curve @ Senators

Follow on MiLB First Pitch  https //stza.co/+vL7x-_

Shop  https //stza.co/+vL7x-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Senators
END:VALARM
DTSTART:20180801T223000Z
DTEND:20180802T013000Z
UID:J8idqmLo-qRvNz5JnaQ4BaNY@stanza.co
SUMMARY:Curve @ Senators
DESCRIPTION:Curve @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vL7x-_\n\nShop: https://stza.co/+vL7x-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Senators
<2018-08-02 Thu 18:00-21:00>
:PROPERTIES:
:ID:       n2vzUSZ2TJ-PdRrclm8u_mll@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve @ Senators Curve @ Senators

Follow on MiLB First Pitch  https //stza.co/+vL7y-s

Shop  https //stza.co/+vL7y-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Senators
END:VALARM
DTSTART:20180802T230000Z
DTEND:20180803T020000Z
UID:n2vzUSZ2TJ-PdRrclm8u_mll@stanza.co
SUMMARY:Curve @ Senators
DESCRIPTION:Curve @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vL7y-s\n\nShop: https://stza.co/+vL7y-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. RubberDucks
<2018-08-03 Fri 18:00-21:00>
:PROPERTIES:
:ID:       X1ovsIc8eCSVEDhRonpiOO03@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. RubberDucks Curve vs. RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vL6C-3Q

Shop  https //stza.co/+vL6C-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. RubberDucks
END:VALARM
DTSTART:20180803T230000Z
DTEND:20180804T020000Z
UID:X1ovsIc8eCSVEDhRonpiOO03@stanza.co
SUMMARY:Curve vs. RubberDucks
DESCRIPTION:Curve vs. RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vL6C-3Q\n\nShop: https://stza.co/+vL6C-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. RubberDucks
<2018-08-04 Sat 17:00-20:00>
:PROPERTIES:
:ID:       sEJl8VkOlrj2AQ7FvNp79iva@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. RubberDucks Curve vs. RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vL6D-9

Shop  https //stza.co/+vL6D-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. RubberDucks
END:VALARM
DTSTART:20180804T220000Z
DTEND:20180805T010000Z
UID:sEJl8VkOlrj2AQ7FvNp79iva@stanza.co
SUMMARY:Curve vs. RubberDucks
DESCRIPTION:Curve vs. RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vL6D-9\n\nShop: https://stza.co/+vL6D-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. RubberDucks
<2018-08-05 Sun 17:00-20:00>
:PROPERTIES:
:ID:       nCdEExiu7ntDbSBtQqJDINoE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve vs. RubberDucks Curve vs. RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vL6G-3m

Shop  https //stza.co/+vL6G-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. RubberDucks
END:VALARM
DTSTART:20180805T220000Z
DTEND:20180806T010000Z
UID:nCdEExiu7ntDbSBtQqJDINoE@stanza.co
SUMMARY:Curve vs. RubberDucks
DESCRIPTION:Curve vs. RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vL6G-3m\n\nShop: https://stza.co/+vL6G-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Thunder
<2018-08-07 Tue 18:00-21:00>
:PROPERTIES:
:ID:       NWpbuRN5oXW9vNUgL5ltb_NN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Thunder Curve @ Thunder

Follow on MiLB First Pitch  https //stza.co/+v6Vd-1I

Shop  https //stza.co/+v6Vd-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Thunder
END:VALARM
DTSTART:20180807T230000Z
DTEND:20180808T020000Z
UID:NWpbuRN5oXW9vNUgL5ltb_NN@stanza.co
SUMMARY:Curve @ Thunder
DESCRIPTION:Curve @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+v6Vd-1I\n\nShop: https://stza.co/+v6Vd-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Thunder
<2018-08-08 Wed 11:00-14:00>
:PROPERTIES:
:ID:       D4-eZKTDt0gBS2T-EjEPiB87@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Thunder Curve @ Thunder

Follow on MiLB First Pitch  https //stza.co/+v6Vw-1y

Shop  https //stza.co/+v6Vw-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Thunder
END:VALARM
DTSTART:20180808T160000Z
DTEND:20180808T190000Z
UID:D4-eZKTDt0gBS2T-EjEPiB87@stanza.co
SUMMARY:Curve @ Thunder
DESCRIPTION:Curve @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+v6Vw-1y\n\nShop: https://stza.co/+v6Vw-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Thunder
<2018-08-09 Thu 18:00-21:00>
:PROPERTIES:
:ID:       GfsV5zck3zdt5UXktwiOeIys@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve @ Thunder Curve @ Thunder

Follow on MiLB First Pitch  https //stza.co/+v6VK-1z

Shop  https //stza.co/+v6VK-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Thunder
END:VALARM
DTSTART:20180809T230000Z
DTEND:20180810T020000Z
UID:GfsV5zck3zdt5UXktwiOeIys@stanza.co
SUMMARY:Curve @ Thunder
DESCRIPTION:Curve @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+v6VK-1z\n\nShop: https://stza.co/+v6VK-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. SeaWolves
<2018-08-10 Fri 18:00-21:00>
:PROPERTIES:
:ID:       Ih_Rk6kus6g39jb9DqkEx6Y_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. SeaWolves Curve vs. SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vL6I-3l

Shop  https //stza.co/+vL6I-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. SeaWolves
END:VALARM
DTSTART:20180810T230000Z
DTEND:20180811T020000Z
UID:Ih_Rk6kus6g39jb9DqkEx6Y_@stanza.co
SUMMARY:Curve vs. SeaWolves
DESCRIPTION:Curve vs. SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vL6I-3l\n\nShop: https://stza.co/+vL6I-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. SeaWolves
<2018-08-11 Sat 17:00-20:00>
:PROPERTIES:
:ID:       un_dr_5SseFKZRoYEXI4T0k6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. SeaWolves Curve vs. SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vL6J-I

Shop  https //stza.co/+vL6J-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. SeaWolves
END:VALARM
DTSTART:20180811T220000Z
DTEND:20180812T010000Z
UID:un_dr_5SseFKZRoYEXI4T0k6@stanza.co
SUMMARY:Curve vs. SeaWolves
DESCRIPTION:Curve vs. SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vL6J-I\n\nShop: https://stza.co/+vL6J-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. SeaWolves
<2018-08-12 Sun 17:00-20:00>
:PROPERTIES:
:ID:       im25app16uw4IsP0TguujXHR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve vs. SeaWolves Curve vs. SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vL6M-2i

Shop  https //stza.co/+vL6M-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. SeaWolves
END:VALARM
DTSTART:20180812T220000Z
DTEND:20180813T010000Z
UID:im25app16uw4IsP0TguujXHR@stanza.co
SUMMARY:Curve vs. SeaWolves
DESCRIPTION:Curve vs. SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vL6M-2i\n\nShop: https://stza.co/+vL6M-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Fisher Cats
<2018-08-14 Tue 18:05-21:05>
:PROPERTIES:
:ID:       vf6yrCJxxizxSgKgidzqy1Us@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Fisher Cats Curve @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vL7C-26

Shop  https //stza.co/+vL7C-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Fisher Cats
END:VALARM
DTSTART:20180814T230500Z
DTEND:20180815T020500Z
UID:vf6yrCJxxizxSgKgidzqy1Us@stanza.co
SUMMARY:Curve @ Fisher Cats
DESCRIPTION:Curve @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vL7C-26\n\nShop: https://stza.co/+vL7C-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Fisher Cats
<2018-08-15 Wed 18:05-21:05>
:PROPERTIES:
:ID:       W3nt-BsrVB25cXQSyTAXL7is@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Fisher Cats Curve @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vL7D-2F

Shop  https //stza.co/+vL7D-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Fisher Cats
END:VALARM
DTSTART:20180815T230500Z
DTEND:20180816T020500Z
UID:W3nt-BsrVB25cXQSyTAXL7is@stanza.co
SUMMARY:Curve @ Fisher Cats
DESCRIPTION:Curve @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vL7D-2F\n\nShop: https://stza.co/+vL7D-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Fisher Cats
<2018-08-16 Thu 18:05-21:05>
:PROPERTIES:
:ID:       EifB7i1xvGSD0w017SuFnqGw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve @ Fisher Cats Curve @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vL7E-19

Shop  https //stza.co/+vL7E-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Fisher Cats
END:VALARM
DTSTART:20180816T230500Z
DTEND:20180817T020500Z
UID:EifB7i1xvGSD0w017SuFnqGw@stanza.co
SUMMARY:Curve @ Fisher Cats
DESCRIPTION:Curve @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vL7E-19\n\nShop: https://stza.co/+vL7E-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Sea Dogs
<2018-08-17 Fri 18:00-21:00>
:PROPERTIES:
:ID:       OPXtYWY7zfVYtikK15Ie1k3P@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Sea Dogs Curve @ Sea Dogs

Buy tickets here  https //stza.co/~vL7F

Follow on MiLB First Pitch  https //stza.co/+vL7F-2C

Shop  https //stza.co/+vL7F-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Sea Dogs
END:VALARM
DTSTART:20180817T230000Z
DTEND:20180818T020000Z
UID:OPXtYWY7zfVYtikK15Ie1k3P@stanza.co
SUMMARY:Curve @ Sea Dogs
DESCRIPTION:Curve @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vL7F\n\nFollow on MiLB First Pitch: https://stza.co/+vL7F-2C\n\nShop: https://stza.co/+vL7F-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Sea Dogs
<2018-08-18 Sat 17:00-20:00>
:PROPERTIES:
:ID:       hXptHCeIMUSYaRFVw7-_RtvT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Sea Dogs Curve @ Sea Dogs

Buy tickets here  https //stza.co/~vL7G

Follow on MiLB First Pitch  https //stza.co/+vL7G-C

Shop  https //stza.co/+vL7G-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Sea Dogs
END:VALARM
DTSTART:20180818T220000Z
DTEND:20180819T010000Z
UID:hXptHCeIMUSYaRFVw7-_RtvT@stanza.co
SUMMARY:Curve @ Sea Dogs
DESCRIPTION:Curve @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vL7G\n\nFollow on MiLB First Pitch: https://stza.co/+vL7G-C\n\nShop: https://stza.co/+vL7G-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Sea Dogs
<2018-08-19 Sun 12:00-15:00>
:PROPERTIES:
:ID:       CoFNwDqkX23W2xHyuWmwuqEP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve @ Sea Dogs Curve @ Sea Dogs

Buy tickets here  https //stza.co/~vL7H

Follow on MiLB First Pitch  https //stza.co/+vL7H-1e

Shop  https //stza.co/+vL7H-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Sea Dogs
END:VALARM
DTSTART:20180819T170000Z
DTEND:20180819T200000Z
UID:CoFNwDqkX23W2xHyuWmwuqEP@stanza.co
SUMMARY:Curve @ Sea Dogs
DESCRIPTION:Curve @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vL7H\n\nFollow on MiLB First Pitch: https://stza.co/+vL7H-1e\n\nShop: https://stza.co/+vL7H-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Rumble Ponies
<2018-08-20 Mon 17:35-20:35>
:PROPERTIES:
:ID:       sGBCLh-YF-K4Zreoj1PbEsrJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Rumble Ponies Curve @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vL76-1n

Shop  https //stza.co/+vL76-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Rumble Ponies
END:VALARM
DTSTART:20180820T223500Z
DTEND:20180821T013500Z
UID:sGBCLh-YF-K4Zreoj1PbEsrJ@stanza.co
SUMMARY:Curve @ Rumble Ponies
DESCRIPTION:Curve @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vL76-1n\n\nShop: https://stza.co/+vL76-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Rumble Ponies
<2018-08-21 Tue 17:35-20:35>
:PROPERTIES:
:ID:       VUnvR4x7d_dTj_og0tPMwIzb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Rumble Ponies Curve @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vL77-1t

Shop  https //stza.co/+vL77-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Rumble Ponies
END:VALARM
DTSTART:20180821T223500Z
DTEND:20180822T013500Z
UID:VUnvR4x7d_dTj_og0tPMwIzb@stanza.co
SUMMARY:Curve @ Rumble Ponies
DESCRIPTION:Curve @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vL77-1t\n\nShop: https://stza.co/+vL77-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Senators
<2018-08-22 Wed 17:00-20:00>
:PROPERTIES:
:ID:       LDHKc6dJyC0dhqRSIiaczUSd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve vs. Senators Curve vs. Senators

Follow on MiLB First Pitch  https //stza.co/+vL6O-1v

Shop  https //stza.co/+vL6O-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Senators
END:VALARM
DTSTART:20180822T220000Z
DTEND:20180823T010000Z
UID:LDHKc6dJyC0dhqRSIiaczUSd@stanza.co
SUMMARY:Curve vs. Senators
DESCRIPTION:Curve vs. Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vL6O-1v\n\nShop: https://stza.co/+vL6O-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Senators
<2018-08-23 Thu 17:00-20:00>
:PROPERTIES:
:ID:       hKbhqVSCYLAc-8wKZf5SyYMk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. Senators Curve vs. Senators

Follow on MiLB First Pitch  https //stza.co/+vL6Q-6

Shop  https //stza.co/+vL6Q-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Senators
END:VALARM
DTSTART:20180823T220000Z
DTEND:20180824T010000Z
UID:hKbhqVSCYLAc-8wKZf5SyYMk@stanza.co
SUMMARY:Curve vs. Senators
DESCRIPTION:Curve vs. Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vL6Q-6\n\nShop: https://stza.co/+vL6Q-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Flying Squirrels
<2018-08-24 Fri 17:00-20:00>
:PROPERTIES:
:ID:       jHoxaYxNeTuhu4GKpOIyJaMI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. Flying Squirrels Curve vs. Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vL6S-3e

Shop  https //stza.co/+vL6S-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Flying Squirrels
END:VALARM
DTSTART:20180824T220000Z
DTEND:20180825T010000Z
UID:jHoxaYxNeTuhu4GKpOIyJaMI@stanza.co
SUMMARY:Curve vs. Flying Squirrels
DESCRIPTION:Curve vs. Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vL6S-3e\n\nShop: https://stza.co/+vL6S-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Flying Squirrels
<2018-08-25 Sat 17:00-20:00>
:PROPERTIES:
:ID:       Ywi_KQmc60V4Kzt_QgkTAAin@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve vs. Flying Squirrels Curve vs. Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vL6T-v

Shop  https //stza.co/+vL6T-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Flying Squirrels
END:VALARM
DTSTART:20180825T220000Z
DTEND:20180826T010000Z
UID:Ywi_KQmc60V4Kzt_QgkTAAin@stanza.co
SUMMARY:Curve vs. Flying Squirrels
DESCRIPTION:Curve vs. Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vL6T-v\n\nShop: https://stza.co/+vL6T-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Flying Squirrels
<2018-08-26 Sun 17:00-20:00>
:PROPERTIES:
:ID:       UfFtJM2vGWMVW8QQIjsBQcei@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. Flying Squirrels Curve vs. Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vL6W-R

Shop  https //stza.co/+vL6W-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Flying Squirrels
END:VALARM
DTSTART:20180826T220000Z
DTEND:20180827T010000Z
UID:UfFtJM2vGWMVW8QQIjsBQcei@stanza.co
SUMMARY:Curve vs. Flying Squirrels
DESCRIPTION:Curve vs. Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vL6W-R\n\nShop: https://stza.co/+vL6W-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Thunder
<2018-08-27 Mon 17:00-20:00>
:PROPERTIES:
:ID:       9F5kJOpMUvlh9wO1KadwrR0U@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. Thunder Curve vs. Thunder

Follow on MiLB First Pitch  https //stza.co/+vL6Y-3E

Shop  https //stza.co/+vL6Y-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Thunder
END:VALARM
DTSTART:20180827T220000Z
DTEND:20180828T010000Z
UID:9F5kJOpMUvlh9wO1KadwrR0U@stanza.co
SUMMARY:Curve vs. Thunder
DESCRIPTION:Curve vs. Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vL6Y-3E\n\nShop: https://stza.co/+vL6Y-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Thunder
<2018-08-28 Tue 17:00-20:00>
:PROPERTIES:
:ID:       IXYZopcb3DJifmTpaL5-iiK5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve vs. Thunder Curve vs. Thunder

Follow on MiLB First Pitch  https //stza.co/+vL6_-2l

Shop  https //stza.co/+vL6_-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Thunder
END:VALARM
DTSTART:20180828T220000Z
DTEND:20180829T010000Z
UID:IXYZopcb3DJifmTpaL5-iiK5@stanza.co
SUMMARY:Curve vs. Thunder
DESCRIPTION:Curve vs. Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vL6_-2l\n\nShop: https://stza.co/+vL6_-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Thunder
<2018-08-29 Wed 17:00-20:00>
:PROPERTIES:
:ID:       qFiq8TbCoZBcQ7klb3KijCfF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. Thunder Curve vs. Thunder

Follow on MiLB First Pitch  https //stza.co/+vL70-3R

Shop  https //stza.co/+vL70-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Thunder
END:VALARM
DTSTART:20180829T220000Z
DTEND:20180830T010000Z
UID:qFiq8TbCoZBcQ7klb3KijCfF@stanza.co
SUMMARY:Curve vs. Thunder
DESCRIPTION:Curve vs. Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vL70-3R\n\nShop: https://stza.co/+vL70-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve vs. Thunder
<2018-08-30 Thu 17:00-20:00>
:PROPERTIES:
:ID:       PS-TMhx-G-M-fqpxDw8itHhF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve vs. Thunder Curve vs. Thunder

Follow on MiLB First Pitch  https //stza.co/+vL71-1j

Shop  https //stza.co/+vL71-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Curve vs. Thunder
END:VALARM
DTSTART:20180830T220000Z
DTEND:20180831T010000Z
UID:PS-TMhx-G-M-fqpxDw8itHhF@stanza.co
SUMMARY:Curve vs. Thunder
DESCRIPTION:Curve vs. Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vL71-1j\n\nShop: https://stza.co/+vL71-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Baysox
<2018-08-31 Fri 18:05-21:05>
:PROPERTIES:
:ID:       oci4cUHHkqXzU0HKS8GX89cL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve @ Baysox Curve @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vL7b-11

Shop  https //stza.co/+vL7b-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Baysox
END:VALARM
DTSTART:20180831T230500Z
DTEND:20180901T020500Z
UID:oci4cUHHkqXzU0HKS8GX89cL@stanza.co
SUMMARY:Curve @ Baysox
DESCRIPTION:Curve @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vL7b-11\n\nShop: https://stza.co/+vL7b-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Baysox
<2018-09-01 Sat 17:35-20:35>
:PROPERTIES:
:ID:       iTqgCtpRBp5h8Ja1MBQr7Tip@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Baysox Curve @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vL7c-3e

Shop  https //stza.co/+vL7c-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Baysox
END:VALARM
DTSTART:20180901T223500Z
DTEND:20180902T013500Z
UID:iTqgCtpRBp5h8Ja1MBQr7Tip@stanza.co
SUMMARY:Curve @ Baysox
DESCRIPTION:Curve @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vL7c-3e\n\nShop: https://stza.co/+vL7c-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Baysox
<2018-09-02 Sun 12:35-15:35>
:PROPERTIES:
:ID:       3V95g7rN0ToaMEbcrYKqFzrb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Curve @ Baysox Curve @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vL7d-n

Shop  https //stza.co/+vL7d-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Baysox
END:VALARM
DTSTART:20180902T173500Z
DTEND:20180902T203500Z
UID:3V95g7rN0ToaMEbcrYKqFzrb@stanza.co
SUMMARY:Curve @ Baysox
DESCRIPTION:Curve @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vL7d-n\n\nShop: https://stza.co/+vL7d-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Curve @ Baysox
<2018-09-03 Mon 12:35-15:35>
:PROPERTIES:
:ID:       s4O6pEbxgK13EzmC_KEWIN3V@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Curve @ Baysox Curve @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vL7e-_

Shop  https //stza.co/+vL7e-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Curve @ Baysox
END:VALARM
DTSTART:20180903T173500Z
DTEND:20180903T203500Z
UID:s4O6pEbxgK13EzmC_KEWIN3V@stanza.co
SUMMARY:Curve @ Baysox
DESCRIPTION:Curve @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vL7e-_\n\nShop: https://stza.co/+vL7e-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
