#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Naturals vs. Hooks
<2018-04-05 Thu 18:25-21:25>
:PROPERTIES:
:ID:       rx9PnBNOGDH-WMjVF9m_eKL-@stanza.co
:LOCATION: Opening Night Fireworks Spectacular
:STATUS:   CONFIRMED
:END:

Naturals vs. Hooks Enjoy a post-game Fireworks Spectacular following the Naturals game against the Hooks on Opening Night at Arvest Ballpark.

The first 1500 fans through the gate will receive a Naturals 2018 Magnet Schedule courtesy of Freddy's Frozen Custard & Steakburgers on Opening Night at Arvest Ballpark.

Follow on MiLB First Pitch  https //stza.co/+wi0M-p

Shop  https //stza.co/+wi0M-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Hooks
END:VALARM
DTSTART:20180405T232500Z
DTEND:20180406T022500Z
UID:rx9PnBNOGDH-WMjVF9m_eKL-@stanza.co
SUMMARY:Naturals vs. Hooks
DESCRIPTION:Enjoy a post-game Fireworks Spectacular following the Naturals game against the Hooks on Opening Night at Arvest Ballpark.\n\nThe first 1500 fans through the gate will receive a Naturals 2018 Magnet Schedule courtesy of Freddy's Frozen Custard & Steakburgers on Opening Night at Arvest Ballpark.\n\nFollow on MiLB First Pitch: https://stza.co/+wi0M-p\n\nShop: https://stza.co/+wi0M-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Opening Night Fireworks Spectacular
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Hooks
<2018-04-06 Fri 19:05-22:05>
:PROPERTIES:
:ID:       ceUh4d6d87LZcAQaedf6E_eo@stanza.co
:LOCATION: Fireworks Friday
:STATUS:   CONFIRMED
:END:

Naturals vs. Hooks Naturals fans will enjoy a post-game Fireworks Spectacular following every Friday home game during the season.

Follow on MiLB First Pitch  https //stza.co/+wi0O-7

Shop  https //stza.co/+wi0O-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Hooks
END:VALARM
DTSTART:20180407T000500Z
DTEND:20180407T030500Z
UID:ceUh4d6d87LZcAQaedf6E_eo@stanza.co
SUMMARY:Naturals vs. Hooks
DESCRIPTION:Naturals fans will enjoy a post-game Fireworks Spectacular following every Friday home game during the season.\n\nFollow on MiLB First Pitch: https://stza.co/+wi0O-7\n\nShop: https://stza.co/+wi0O-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Friday
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Hooks
<2018-04-07 Sat 18:05-21:05>
:PROPERTIES:
:ID:       DYtP63y8gfi4myShPjOBmwC8@stanza.co
:LOCATION: Arvest Ballpark Calendar Giveaway
:STATUS:   CONFIRMED
:END:

Naturals vs. Hooks The first 1500 fans in attendance will receive an Arvest Ballpark Calendar Giveaway courtesy of TCBY.

Fans arriving early will enjoy half price specials on over 70 alcoholic beverages in the Bullpen Craft Beer Bar, located down the 1st base concourse, from 4 35 p.m. until 5 35 p.m.

Follow on MiLB First Pitch  https //stza.co/+wi0R-1U

Shop  https //stza.co/+wi0R-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Hooks
END:VALARM
DTSTART:20180407T230500Z
DTEND:20180408T020500Z
UID:DYtP63y8gfi4myShPjOBmwC8@stanza.co
SUMMARY:Naturals vs. Hooks
DESCRIPTION:The first 1500 fans in attendance will receive an Arvest Ballpark Calendar Giveaway courtesy of TCBY.\n\nFans arriving early will enjoy half price specials on over 70 alcoholic beverages in the Bullpen Craft Beer Bar, located down the 1st base concourse, from 4:35 p.m. until 5:35 p.m.\n\nFollow on MiLB First Pitch: https://stza.co/+wi0R-1U\n\nShop: https://stza.co/+wi0R-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Arvest Ballpark Calendar Giveaway
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Missions
<2018-04-08 Sun 16:05-19:05>
:PROPERTIES:
:ID:       ZtXgEGIri3WFIOZJMjptI-aB@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Naturals vs. Missions Kids 12 & under will receive a voucher for a free hot dog, chips, and 12 oz. soda as they enter the gates at every Sunday home game at Arvest Ballpark. 

Young Naturals fans will enjoy Mercy Kids Run the Bases following every Sunday home game at Arvest Ballpark - Except for Sunday, June 17

Follow on MiLB First Pitch  https //stza.co/+wi0S-1G

Shop  https //stza.co/+wi0S-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Missions
END:VALARM
DTSTART:20180408T210500Z
DTEND:20180409T000500Z
UID:ZtXgEGIri3WFIOZJMjptI-aB@stanza.co
SUMMARY:Naturals vs. Missions
DESCRIPTION:Kids 12 & under will receive a voucher for a free hot dog, chips, and 12 oz. soda as they enter the gates at every Sunday home game at Arvest Ballpark. \n\nYoung Naturals fans will enjoy Mercy Kids Run the Bases following every Sunday home game at Arvest Ballpark - Except for Sunday, June 17\n\nFollow on MiLB First Pitch: https://stza.co/+wi0S-1G\n\nShop: https://stza.co/+wi0S-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Missions
<2018-04-09 Mon 19:05-22:05>
:PROPERTIES:
:ID:       bT_axI_Xm1xh6QAVdOORjL1s@stanza.co
:LOCATION: Monday Night Lights
:STATUS:   CONFIRMED
:END:

Naturals vs. Missions Ozarks Electric Cooperative customers will receive $5 Dugout Premium Tickets at the Arvest Ballpark Box Office for every Monday night home game - Except for Monday, July 2. Must show proof of being an Ozarks Electric Cooperative customer.

Fans will enjoy $1 Hot Dogs at the concessions stands courtesy of Tyson Foods, Inc. every Monday night - except for Monday, July 2.

Fans young and old will have the opportunity to play Indigo Sky Baseball Bingo every Monday night - except for Monday, July  2 - at Arvest Ballpark for a chance to win great prizes. Max. of 5 winners per game - prizes by Indigo Sky Casino.

Follow on MiLB First Pitch  https //stza.co/+wi0U-c

Shop  https //stza.co/+wi0U-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Missions
END:VALARM
DTSTART:20180410T000500Z
DTEND:20180410T030500Z
UID:bT_axI_Xm1xh6QAVdOORjL1s@stanza.co
SUMMARY:Naturals vs. Missions
DESCRIPTION:Ozarks Electric Cooperative customers will receive $5 Dugout Premium Tickets at the Arvest Ballpark Box Office for every Monday night home game - Except for Monday, July 2. Must show proof of being an Ozarks Electric Cooperative customer.\n\nFans will enjoy $1 Hot Dogs at the concessions stands courtesy of Tyson Foods, Inc. every Monday night - except for Monday, July 2.\n\nFans young and old will have the opportunity to play Indigo Sky Baseball Bingo every Monday night - except for Monday, July  2 - at Arvest Ballpark for a chance to win great prizes. Max. of 5 winners per game - prizes by Indigo Sky Casino.\n\nFollow on MiLB First Pitch: https://stza.co/+wi0U-c\n\nShop: https://stza.co/+wi0U-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Monday Night Lights
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Missions
<2018-04-10 Tue 11:05-14:05>
:PROPERTIES:
:ID:       AlLxLIUriUhQmCs8vT_sdjth@stanza.co
:LOCATION: Education Day Game
:STATUS:   CONFIRMED
:END:

Naturals vs. Missions Education Day Games by SWEPCO are some of the most popular Field Trips around as each game features discounted tickets for all students, teachers, and chaperones as well as Title 1 tickets for schools that apply.

Follow on MiLB First Pitch  https //stza.co/+wi0X-2x

Shop  https //stza.co/+wi0X-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Missions
END:VALARM
DTSTART:20180410T160500Z
DTEND:20180410T190500Z
UID:AlLxLIUriUhQmCs8vT_sdjth@stanza.co
SUMMARY:Naturals vs. Missions
DESCRIPTION:Education Day Games by SWEPCO are some of the most popular Field Trips around as each game features discounted tickets for all students, teachers, and chaperones as well as Title 1 tickets for schools that apply.\n\nFollow on MiLB First Pitch: https://stza.co/+wi0X-2x\n\nShop: https://stza.co/+wi0X-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Education Day Game
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Hooks
<2018-04-12 Thu 19:05-22:05>
:PROPERTIES:
:ID:       Ofh5c9tqN8D0bjt850s-gYe0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Hooks Naturals @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHT-T

Shop  https //stza.co/+xzHT-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Hooks
END:VALARM
DTSTART:20180413T000500Z
DTEND:20180413T030500Z
UID:Ofh5c9tqN8D0bjt850s-gYe0@stanza.co
SUMMARY:Naturals @ Hooks
DESCRIPTION:Naturals @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHT-T\n\nShop: https://stza.co/+xzHT-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Hooks
<2018-04-13 Fri 19:05-22:05>
:PROPERTIES:
:ID:       T81sDPy4tlWfyZWHne35b_8K@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Naturals @ Hooks Naturals @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHU-1n

Shop  https //stza.co/+xzHU-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Hooks
END:VALARM
DTSTART:20180414T000500Z
DTEND:20180414T030500Z
UID:T81sDPy4tlWfyZWHne35b_8K@stanza.co
SUMMARY:Naturals @ Hooks
DESCRIPTION:Naturals @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHU-1n\n\nShop: https://stza.co/+xzHU-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Hooks
<2018-04-14 Sat 19:05-22:05>
:PROPERTIES:
:ID:       -ZBHdHabLo0PBz6lSXnqEB6d@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Hooks Naturals @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHW-l

Shop  https //stza.co/+xzHW-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Hooks
END:VALARM
DTSTART:20180415T000500Z
DTEND:20180415T030500Z
UID:-ZBHdHabLo0PBz6lSXnqEB6d@stanza.co
SUMMARY:Naturals @ Hooks
DESCRIPTION:Naturals @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHW-l\n\nShop: https://stza.co/+xzHW-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Missions
<2018-04-15 Sun 14:05-17:05>
:PROPERTIES:
:ID:       z5zJUTYt9ukvJnxCJ_nwkgHu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Missions Naturals @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMvf-3F

Shop  https //stza.co/+wMvf-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Missions
END:VALARM
DTSTART:20180415T190500Z
DTEND:20180415T220500Z
UID:z5zJUTYt9ukvJnxCJ_nwkgHu@stanza.co
SUMMARY:Naturals @ Missions
DESCRIPTION:Naturals @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMvf-3F\n\nShop: https://stza.co/+wMvf-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Missions
<2018-04-16 Mon 11:05-14:05>
:PROPERTIES:
:ID:       rv0pPEekPTABkCz45F8x4vln@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Naturals @ Missions Naturals @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMvg-4

Shop  https //stza.co/+wMvg-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Missions
END:VALARM
DTSTART:20180416T160500Z
DTEND:20180416T190500Z
UID:rv0pPEekPTABkCz45F8x4vln@stanza.co
SUMMARY:Naturals @ Missions
DESCRIPTION:Naturals @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMvg-4\n\nShop: https://stza.co/+wMvg-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Missions
<2018-04-17 Tue 19:05-22:05>
:PROPERTIES:
:ID:       pAKr0xxreZrXM6oqlFMpWjYO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Missions Naturals @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMvh-6

Shop  https //stza.co/+wMvh-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Missions
END:VALARM
DTSTART:20180418T000500Z
DTEND:20180418T030500Z
UID:pAKr0xxreZrXM6oqlFMpWjYO@stanza.co
SUMMARY:Naturals @ Missions
DESCRIPTION:Naturals @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMvh-6\n\nShop: https://stza.co/+wMvh-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Drillers
<2018-04-19 Thu 19:05-22:05>
:PROPERTIES:
:ID:       hUBG4Z77jHajmS9RqoogN0PC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals vs. Drillers Naturals vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+wi0Y-17

Shop  https //stza.co/+wi0Y-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Drillers
END:VALARM
DTSTART:20180420T000500Z
DTEND:20180420T030500Z
UID:hUBG4Z77jHajmS9RqoogN0PC@stanza.co
SUMMARY:Naturals vs. Drillers
DESCRIPTION:Naturals vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+wi0Y-17\n\nShop: https://stza.co/+wi0Y-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Drillers
<2018-04-20 Fri 19:05-22:05>
:PROPERTIES:
:ID:       XDIfF82TuwEfqPx_GjZDPiFo@stanza.co
:LOCATION: Fireworks Friday
:STATUS:   CONFIRMED
:END:

Naturals vs. Drillers 





Follow on MiLB First Pitch  https //stza.co/+wi0$-2Y

Shop  https //stza.co/+wi0$-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Drillers
END:VALARM
DTSTART:20180421T000500Z
DTEND:20180421T030500Z
UID:XDIfF82TuwEfqPx_GjZDPiFo@stanza.co
SUMMARY:Naturals vs. Drillers
DESCRIPTION:\n\n\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+wi0$-2Y\n\nShop: https://stza.co/+wi0$-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Friday
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Drillers
<2018-04-21 Sat 19:05-22:05>
:PROPERTIES:
:ID:       O8Dap2bwwBeYNlG-BOs-6pcp@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Naturals @ Drillers Naturals @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w06M-3Q

Shop  https //stza.co/+w06M-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Drillers
END:VALARM
DTSTART:20180422T000500Z
DTEND:20180422T030500Z
UID:O8Dap2bwwBeYNlG-BOs-6pcp@stanza.co
SUMMARY:Naturals @ Drillers
DESCRIPTION:Naturals @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w06M-3Q\n\nShop: https://stza.co/+w06M-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Drillers
<2018-04-22 Sun 13:05-16:05>
:PROPERTIES:
:ID:       bDItrO853K3LJLzfeE5Gp7EV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Drillers Naturals @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w06N-W

Shop  https //stza.co/+w06N-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Drillers
END:VALARM
DTSTART:20180422T180500Z
DTEND:20180422T210500Z
UID:bDItrO853K3LJLzfeE5Gp7EV@stanza.co
SUMMARY:Naturals @ Drillers
DESCRIPTION:Naturals @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w06N-W\n\nShop: https://stza.co/+w06N-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Cardinals
<2018-04-23 Mon 18:30-21:30>
:PROPERTIES:
:ID:       FoWslKSdnPQVLLb0nr2caQyP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Cardinals Naturals @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPNi-S

Shop  https //stza.co/+wPNi-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Cardinals
END:VALARM
DTSTART:20180423T233000Z
DTEND:20180424T023000Z
UID:FoWslKSdnPQVLLb0nr2caQyP@stanza.co
SUMMARY:Naturals @ Cardinals
DESCRIPTION:Naturals @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPNi-S\n\nShop: https://stza.co/+wPNi-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Cardinals
<2018-04-24 Tue 18:30-21:30>
:PROPERTIES:
:ID:       34s5E5TrtmIwLFx5gLONQJKr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Naturals @ Cardinals Naturals @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPNj-6

Shop  https //stza.co/+wPNj-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Cardinals
END:VALARM
DTSTART:20180424T233000Z
DTEND:20180425T023000Z
UID:34s5E5TrtmIwLFx5gLONQJKr@stanza.co
SUMMARY:Naturals @ Cardinals
DESCRIPTION:Naturals @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPNj-6\n\nShop: https://stza.co/+wPNj-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Cardinals
<2018-04-25 Wed 11:10-14:10>
:PROPERTIES:
:ID:       typl4aua5zE8P6WhlvAxnKAJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Cardinals Naturals @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPNk-3G

Shop  https //stza.co/+wPNk-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Cardinals
END:VALARM
DTSTART:20180425T161000Z
DTEND:20180425T191000Z
UID:typl4aua5zE8P6WhlvAxnKAJ@stanza.co
SUMMARY:Naturals @ Cardinals
DESCRIPTION:Naturals @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPNk-3G\n\nShop: https://stza.co/+wPNk-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Cardinals
<2018-04-26 Thu 19:10-22:10>
:PROPERTIES:
:ID:       GX3MUNgxuDcbzezNP8gFVvKp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Cardinals Naturals @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPNl-2I

Shop  https //stza.co/+wPNl-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Cardinals
END:VALARM
DTSTART:20180427T001000Z
DTEND:20180427T031000Z
UID:GX3MUNgxuDcbzezNP8gFVvKp@stanza.co
SUMMARY:Naturals @ Cardinals
DESCRIPTION:Naturals @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPNl-2I\n\nShop: https://stza.co/+wPNl-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Drillers
<2018-04-27 Fri 19:05-22:05>
:PROPERTIES:
:ID:       EE7nCczBOkeYAbYKhTO_U8xn@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Naturals @ Drillers Naturals @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w06O-2v

Shop  https //stza.co/+w06O-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Drillers
END:VALARM
DTSTART:20180428T000500Z
DTEND:20180428T030500Z
UID:EE7nCczBOkeYAbYKhTO_U8xn@stanza.co
SUMMARY:Naturals @ Drillers
DESCRIPTION:Naturals @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w06O-2v\n\nShop: https://stza.co/+w06O-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Drillers
<2018-04-28 Sat 18:05-21:05>
:PROPERTIES:
:ID:       NORBjL0AxV3GE15_MNT3ibMA@stanza.co
:LOCATION: Post-Game Fireworks Spectacular
:STATUS:   CONFIRMED
:END:

Naturals vs. Drillers 

Fans arriving early will enjoy half price specials on over 70 alcoholic beverages in the Bullpen Craft Beer Bar, located down the 1st base concourse, from 4 35 p.m. until 5 35 p.m.

Follow on MiLB First Pitch  https //stza.co/+wi11-U

Shop  https //stza.co/+wi11-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Drillers
END:VALARM
DTSTART:20180428T230500Z
DTEND:20180429T020500Z
UID:NORBjL0AxV3GE15_MNT3ibMA@stanza.co
SUMMARY:Naturals vs. Drillers
DESCRIPTION:\n\nFans arriving early will enjoy half price specials on over 70 alcoholic beverages in the Bullpen Craft Beer Bar, located down the 1st base concourse, from 4:35 p.m. until 5:35 p.m.\n\nFollow on MiLB First Pitch: https://stza.co/+wi11-U\n\nShop: https://stza.co/+wi11-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Post-Game Fireworks Spectacular
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Drillers
<2018-04-29 Sun 14:05-17:05>
:PROPERTIES:
:ID:       sEUzH4z-EiiOH7M7hv5wGgYR@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Naturals vs. Drillers 



Young Naturals fans will enjoy Mercy Kids Run the Bases following every Sunday home game at Arvest Ballpark - Except for Sunday, June 17

Follow on MiLB First Pitch  https //stza.co/+wi13-2Y

Shop  https //stza.co/+wi13-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Drillers
END:VALARM
DTSTART:20180429T190500Z
DTEND:20180429T220500Z
UID:sEUzH4z-EiiOH7M7hv5wGgYR@stanza.co
SUMMARY:Naturals vs. Drillers
DESCRIPTION:\n\n\n\nYoung Naturals fans will enjoy Mercy Kids Run the Bases following every Sunday home game at Arvest Ballpark - Except for Sunday, June 17\n\nFollow on MiLB First Pitch: https://stza.co/+wi13-2Y\n\nShop: https://stza.co/+wi13-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Drillers
<2018-04-30 Mon 11:05-14:05>
:PROPERTIES:
:ID:       eGOhSBKK8ViMlPxiIrlfM-fX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Drillers Naturals @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w06P-2g

Shop  https //stza.co/+w06P-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Drillers
END:VALARM
DTSTART:20180430T160500Z
DTEND:20180430T190500Z
UID:eGOhSBKK8ViMlPxiIrlfM-fX@stanza.co
SUMMARY:Naturals @ Drillers
DESCRIPTION:Naturals @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w06P-2g\n\nShop: https://stza.co/+w06P-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Cardinals
<2018-05-01 Tue 19:05-22:05>
:PROPERTIES:
:ID:       _qbWatLUAmX1g9QXlt5YfHbz@stanza.co
:LOCATION: Two for Tuesday
:STATUS:   CONFIRMED
:END:

Naturals vs. Cardinals Arvest Bank customers will enjoy $5 Dugout Premium tickets to every Tuesday night home game at Arvest Ballpark - except on Tuesday, July 3 - must show proof of being an Arvest customer at the Arvest Ballpark Box Office. In addition, the Naturals will offer numerous 2-for-1 specials throughout the ballpark.

Fans will enjoy Johnsonville Buck-A-Brats on Tuesday nights at Arvest Ballpark, with the exception of Tuesday, July 3, where $1 brats will be offered at designated spots along the concourse throughout the game.

Follow on MiLB First Pitch  https //stza.co/+wi15-2y

Shop  https //stza.co/+wi15-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Cardinals
END:VALARM
DTSTART:20180502T000500Z
DTEND:20180502T030500Z
UID:_qbWatLUAmX1g9QXlt5YfHbz@stanza.co
SUMMARY:Naturals vs. Cardinals
DESCRIPTION:Arvest Bank customers will enjoy $5 Dugout Premium tickets to every Tuesday night home game at Arvest Ballpark - except on Tuesday, July 3 - must show proof of being an Arvest customer at the Arvest Ballpark Box Office. In addition, the Naturals will offer numerous 2-for-1 specials throughout the ballpark.\n\nFans will enjoy Johnsonville Buck-A-Brats on Tuesday nights at Arvest Ballpark, with the exception of Tuesday, July 3, where $1 brats will be offered at designated spots along the concourse throughout the game.\n\nFollow on MiLB First Pitch: https://stza.co/+wi15-2y\n\nShop: https://stza.co/+wi15-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Two for Tuesday
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Cardinals
<2018-05-02 Wed 11:05-14:05>
:PROPERTIES:
:ID:       Yw6EER3eCHtXRJMvwCtN8QUc@stanza.co
:LOCATION: Education Day Game
:STATUS:   CONFIRMED
:END:

Naturals vs. Cardinals Education Day Games by SWEPCO are some of the most popular Field Trips around as each game features discounted tickets for all students, teachers, and chaperones as well as Title 1 tickets for schools that apply.

Follow on MiLB First Pitch  https //stza.co/+wi16-36

Shop  https //stza.co/+wi16-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Cardinals
END:VALARM
DTSTART:20180502T160500Z
DTEND:20180502T190500Z
UID:Yw6EER3eCHtXRJMvwCtN8QUc@stanza.co
SUMMARY:Naturals vs. Cardinals
DESCRIPTION:Education Day Games by SWEPCO are some of the most popular Field Trips around as each game features discounted tickets for all students, teachers, and chaperones as well as Title 1 tickets for schools that apply.\n\nFollow on MiLB First Pitch: https://stza.co/+wi16-36\n\nShop: https://stza.co/+wi16-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Education Day Game
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Cardinals
<2018-05-03 Thu 19:05-22:05>
:PROPERTIES:
:ID:       9KilMvpdDQnblBYrPyvDXU-x@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals vs. Cardinals Naturals vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+wi18-t

Shop  https //stza.co/+wi18-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Cardinals
END:VALARM
DTSTART:20180504T000500Z
DTEND:20180504T030500Z
UID:9KilMvpdDQnblBYrPyvDXU-x@stanza.co
SUMMARY:Naturals vs. Cardinals
DESCRIPTION:Naturals vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wi18-t\n\nShop: https://stza.co/+wi18-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Cardinals
<2018-05-04 Fri 19:05-22:05>
:PROPERTIES:
:ID:       -_ha0kzLDyvVXRz0JIRH3nT8@stanza.co
:LOCATION: May the force be with you! Come check out Stars Wars Night at the park
:STATUS:   CONFIRMED
:END:

Naturals vs. Cardinals 

May the Fourth be with you at Arvest Ballpark for Star Wars Night presented by The Northwest Company. The Naturals will be wearing special Star Wars jerseys while a TBD amount of Star Wars characters will be on hand to interact with fans during the game.



Follow on MiLB First Pitch  https //stza.co/+wi1b-K

Shop  https //stza.co/+wi1b-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Cardinals
END:VALARM
DTSTART:20180505T000500Z
DTEND:20180505T030500Z
UID:-_ha0kzLDyvVXRz0JIRH3nT8@stanza.co
SUMMARY:Naturals vs. Cardinals
DESCRIPTION:\n\nMay the Fourth be with you at Arvest Ballpark for Star Wars Night presented by The Northwest Company. The Naturals will be wearing special Star Wars jerseys while a TBD amount of Star Wars characters will be on hand to interact with fans during the game.\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+wi1b-K\n\nShop: https://stza.co/+wi1b-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:May the force be with you! Come check out Stars Wars Night at the park
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Travelers
<2018-05-05 Sat 17:30-20:30>
:PROPERTIES:
:ID:       LEoSoXVPmq4LRQdNsU-mnc5U@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Naturals @ Travelers Naturals @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w03K-3j

Shop  https //stza.co/+w03K-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Travelers
END:VALARM
DTSTART:20180505T223000Z
DTEND:20180506T013000Z
UID:LEoSoXVPmq4LRQdNsU-mnc5U@stanza.co
SUMMARY:Naturals @ Travelers
DESCRIPTION:Naturals @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w03K-3j\n\nShop: https://stza.co/+w03K-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Travelers
<2018-05-06 Sun 14:10-17:10>
:PROPERTIES:
:ID:       tlwsuXEQkcEiv8qz8C74U8yS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Travelers Naturals @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w03L-2t

Shop  https //stza.co/+w03L-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Travelers
END:VALARM
DTSTART:20180506T191000Z
DTEND:20180506T221000Z
UID:tlwsuXEQkcEiv8qz8C74U8yS@stanza.co
SUMMARY:Naturals @ Travelers
DESCRIPTION:Naturals @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w03L-2t\n\nShop: https://stza.co/+w03L-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Travelers
<2018-05-07 Mon 19:10-22:10>
:PROPERTIES:
:ID:       f9ESp3wOcY7UvTBPDroaIWoP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Travelers Naturals @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w03M-3g

Shop  https //stza.co/+w03M-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Travelers
END:VALARM
DTSTART:20180508T001000Z
DTEND:20180508T031000Z
UID:f9ESp3wOcY7UvTBPDroaIWoP@stanza.co
SUMMARY:Naturals @ Travelers
DESCRIPTION:Naturals @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w03M-3g\n\nShop: https://stza.co/+w03M-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Travelers
<2018-05-08 Tue 19:10-22:10>
:PROPERTIES:
:ID:       9L2xx81_2Truh01Ktv3v5mp0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Naturals @ Travelers Naturals @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w03N-W

Shop  https //stza.co/+w03N-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Travelers
END:VALARM
DTSTART:20180509T001000Z
DTEND:20180509T031000Z
UID:9L2xx81_2Truh01Ktv3v5mp0@stanza.co
SUMMARY:Naturals @ Travelers
DESCRIPTION:Naturals @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w03N-W\n\nShop: https://stza.co/+w03N-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Drillers
<2018-05-10 Thu 19:05-22:05>
:PROPERTIES:
:ID:       c5fBkpvZeN45z14oHuKUIMAw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals vs. Drillers Naturals vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+wi1c-I

Shop  https //stza.co/+wi1c-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Drillers
END:VALARM
DTSTART:20180511T000500Z
DTEND:20180511T030500Z
UID:c5fBkpvZeN45z14oHuKUIMAw@stanza.co
SUMMARY:Naturals vs. Drillers
DESCRIPTION:Naturals vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+wi1c-I\n\nShop: https://stza.co/+wi1c-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Drillers
<2018-05-11 Fri 19:15-22:15>
:PROPERTIES:
:ID:       0Eypg0GgmQJfBCONQRE6zXtr@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals vs. Drillers Naturals vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+wi1e-N

Shop  https //stza.co/+wi1e-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Drillers
END:VALARM
DTSTART:20180512T001500Z
DTEND:20180512T031500Z
UID:0Eypg0GgmQJfBCONQRE6zXtr@stanza.co
SUMMARY:Naturals vs. Drillers
DESCRIPTION:Naturals vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+wi1e-N\n\nShop: https://stza.co/+wi1e-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Drillers
<2018-05-12 Sat 18:05-21:05>
:PROPERTIES:
:ID:       4w5YHz-peWjc7jnSruc255pT@stanza.co
:LOCATION: Mike Moustakas Career Highlights Bobblehead
:STATUS:   CONFIRMED
:END:

Naturals vs. Drillers 

Fans arriving early will enjoy half price specials on over 70 alcoholic beverages in the Bullpen Craft Beer Bar, located down the 1st base concourse, from 4 35 p.m. until 5 35 p.m.



Follow on MiLB First Pitch  https //stza.co/+wi1h-2d

Shop  https //stza.co/+wi1h-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Drillers
END:VALARM
DTSTART:20180512T230500Z
DTEND:20180513T020500Z
UID:4w5YHz-peWjc7jnSruc255pT@stanza.co
SUMMARY:Naturals vs. Drillers
DESCRIPTION:\n\nFans arriving early will enjoy half price specials on over 70 alcoholic beverages in the Bullpen Craft Beer Bar, located down the 1st base concourse, from 4:35 p.m. until 5:35 p.m.\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+wi1h-2d\n\nShop: https://stza.co/+wi1h-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Mike Moustakas Career Highlights Bobblehead
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Drillers
<2018-05-13 Sun 14:05-17:05>
:PROPERTIES:
:ID:       dW9QulFMydSJ2osjV9NFuC5C@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Naturals vs. Drillers 



Young Naturals fans will enjoy Mercy Kids Run the Bases following every Sunday home game at Arvest Ballpark - Except for Sunday, June 17

Follow on MiLB First Pitch  https //stza.co/+wi1k-n

Shop  https //stza.co/+wi1k-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Drillers
END:VALARM
DTSTART:20180513T190500Z
DTEND:20180513T220500Z
UID:dW9QulFMydSJ2osjV9NFuC5C@stanza.co
SUMMARY:Naturals vs. Drillers
DESCRIPTION:\n\n\n\nYoung Naturals fans will enjoy Mercy Kids Run the Bases following every Sunday home game at Arvest Ballpark - Except for Sunday, June 17\n\nFollow on MiLB First Pitch: https://stza.co/+wi1k-n\n\nShop: https://stza.co/+wi1k-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Travelers
<2018-05-14 Mon 19:05-22:05>
:PROPERTIES:
:ID:       -wRHRn4Rb4BGavcBljf1bwn0@stanza.co
:LOCATION: Monday Night Lights
:STATUS:   CONFIRMED
:END:

Naturals vs. Travelers Ozarks Electric Cooperative customers will receive $5 Dugout Premium Tickets at the Arvest Ballpark Box Office for every Monday night home game - Except for Monday, July 2. Must show proof of being an Ozarks Electric Cooperative customer.

Fans will enjoy $1 Hot Dogs at the concessions stands courtesy of Tyson Foods, Inc. every Monday night - except for Monday, July 2.

Fans young and old will have the opportunity to play Indigo Sky Baseball Bingo every Monday night - except for Monday, July  2 - at Arvest Ballpark for a chance to win great prizes. Max. of 5 winners per game - prizes by Indigo Sky Casino.

Follow on MiLB First Pitch  https //stza.co/+wi1m-C

Shop  https //stza.co/+wi1m-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Travelers
END:VALARM
DTSTART:20180515T000500Z
DTEND:20180515T030500Z
UID:-wRHRn4Rb4BGavcBljf1bwn0@stanza.co
SUMMARY:Naturals vs. Travelers
DESCRIPTION:Ozarks Electric Cooperative customers will receive $5 Dugout Premium Tickets at the Arvest Ballpark Box Office for every Monday night home game - Except for Monday, July 2. Must show proof of being an Ozarks Electric Cooperative customer.\n\nFans will enjoy $1 Hot Dogs at the concessions stands courtesy of Tyson Foods, Inc. every Monday night - except for Monday, July 2.\n\nFans young and old will have the opportunity to play Indigo Sky Baseball Bingo every Monday night - except for Monday, July  2 - at Arvest Ballpark for a chance to win great prizes. Max. of 5 winners per game - prizes by Indigo Sky Casino.\n\nFollow on MiLB First Pitch: https://stza.co/+wi1m-C\n\nShop: https://stza.co/+wi1m-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Monday Night Lights
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Travelers
<2018-05-15 Tue 19:05-22:05>
:PROPERTIES:
:ID:       KZsIVb3cTjEW8CBrQE-zfwP6@stanza.co
:LOCATION: Two for Tuesday
:STATUS:   CONFIRMED
:END:

Naturals vs. Travelers Arvest Bank customers will enjoy $5 Dugout Premium tickets to every Tuesday night home game at Arvest Ballpark - except on Tuesday, July 3 - must show proof of being an Arvest customer at the Arvest Ballpark Box Office. In addition, the Naturals will offer numerous 2-for-1 specials throughout the ballpark.

Fans will enjoy Johnsonville Buck-A-Brats on Tuesday nights at Arvest Ballpark, with the exception of Tuesday, July 3, where $1 brats will be offered at designated spots along the concourse throughout the game.

Follow on MiLB First Pitch  https //stza.co/+wi1n-r

Shop  https //stza.co/+wi1n-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Travelers
END:VALARM
DTSTART:20180516T000500Z
DTEND:20180516T030500Z
UID:KZsIVb3cTjEW8CBrQE-zfwP6@stanza.co
SUMMARY:Naturals vs. Travelers
DESCRIPTION:Arvest Bank customers will enjoy $5 Dugout Premium tickets to every Tuesday night home game at Arvest Ballpark - except on Tuesday, July 3 - must show proof of being an Arvest customer at the Arvest Ballpark Box Office. In addition, the Naturals will offer numerous 2-for-1 specials throughout the ballpark.\n\nFans will enjoy Johnsonville Buck-A-Brats on Tuesday nights at Arvest Ballpark, with the exception of Tuesday, July 3, where $1 brats will be offered at designated spots along the concourse throughout the game.\n\nFollow on MiLB First Pitch: https://stza.co/+wi1n-r\n\nShop: https://stza.co/+wi1n-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Two for Tuesday
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Travelers
<2018-05-16 Wed 11:05-14:05>
:PROPERTIES:
:ID:       9ZvMnTvZsm8VGjTpbG7aGvVM@stanza.co
:LOCATION: Education Day Game
:STATUS:   CONFIRMED
:END:

Naturals vs. Travelers Education Day Games by SWEPCO are some of the most popular Field Trips around as each game features discounted tickets for all students, teachers, and chaperones as well as Title 1 tickets for schools that apply.

Follow on MiLB First Pitch  https //stza.co/+wi1q-1C

Shop  https //stza.co/+wi1q-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Travelers
END:VALARM
DTSTART:20180516T160500Z
DTEND:20180516T190500Z
UID:9ZvMnTvZsm8VGjTpbG7aGvVM@stanza.co
SUMMARY:Naturals vs. Travelers
DESCRIPTION:Education Day Games by SWEPCO are some of the most popular Field Trips around as each game features discounted tickets for all students, teachers, and chaperones as well as Title 1 tickets for schools that apply.\n\nFollow on MiLB First Pitch: https://stza.co/+wi1q-1C\n\nShop: https://stza.co/+wi1q-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Education Day Game
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Travelers
<2018-05-17 Thu 19:05-22:05>
:PROPERTIES:
:ID:       LWH0nL24J2qJg2flFD-sc4SU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Naturals vs. Travelers Naturals vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+wi1s-2K

Shop  https //stza.co/+wi1s-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Travelers
END:VALARM
DTSTART:20180518T000500Z
DTEND:20180518T030500Z
UID:LWH0nL24J2qJg2flFD-sc4SU@stanza.co
SUMMARY:Naturals vs. Travelers
DESCRIPTION:Naturals vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+wi1s-2K\n\nShop: https://stza.co/+wi1s-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Cardinals
<2018-05-18 Fri 19:10-22:10>
:PROPERTIES:
:ID:       03kBRe3eKFLmiqD2yxXW-cMm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Cardinals Naturals @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPNm-3

Shop  https //stza.co/+wPNm-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Cardinals
END:VALARM
DTSTART:20180519T001000Z
DTEND:20180519T031000Z
UID:03kBRe3eKFLmiqD2yxXW-cMm@stanza.co
SUMMARY:Naturals @ Cardinals
DESCRIPTION:Naturals @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPNm-3\n\nShop: https://stza.co/+wPNm-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Cardinals
<2018-05-19 Sat 18:10-21:10>
:PROPERTIES:
:ID:       wELdfrH0H6ODSkoSxLJHp4qt@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Cardinals Naturals @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPNn-3f

Shop  https //stza.co/+wPNn-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Cardinals
END:VALARM
DTSTART:20180519T231000Z
DTEND:20180520T021000Z
UID:wELdfrH0H6ODSkoSxLJHp4qt@stanza.co
SUMMARY:Naturals @ Cardinals
DESCRIPTION:Naturals @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPNn-3f\n\nShop: https://stza.co/+wPNn-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Cardinals
<2018-05-20 Sun 16:10-19:10>
:PROPERTIES:
:ID:       p7iztHFQnVqH8UQxlDoWvqRg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Naturals @ Cardinals Naturals @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPNo-1h

Shop  https //stza.co/+wPNo-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Cardinals
END:VALARM
DTSTART:20180520T211000Z
DTEND:20180521T001000Z
UID:p7iztHFQnVqH8UQxlDoWvqRg@stanza.co
SUMMARY:Naturals @ Cardinals
DESCRIPTION:Naturals @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPNo-1h\n\nShop: https://stza.co/+wPNo-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Cardinals
<2018-05-21 Mon 11:10-14:10>
:PROPERTIES:
:ID:       6kSSRpo4ROkgPjShVIn9JGZj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Cardinals Naturals @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPNp-h

Shop  https //stza.co/+wPNp-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Cardinals
END:VALARM
DTSTART:20180521T161000Z
DTEND:20180521T191000Z
UID:6kSSRpo4ROkgPjShVIn9JGZj@stanza.co
SUMMARY:Naturals @ Cardinals
DESCRIPTION:Naturals @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPNp-h\n\nShop: https://stza.co/+wPNp-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. RoughRiders
<2018-05-22 Tue 19:05-22:05>
:PROPERTIES:
:ID:       s491HtLfUsFlwE5p6YEfuySa@stanza.co
:LOCATION: Two for Tuesday
:STATUS:   CONFIRMED
:END:

Naturals vs. RoughRiders Arvest Bank customers will enjoy $5 Dugout Premium tickets to every Tuesday night home game at Arvest Ballpark - except on Tuesday, July 3 - must show proof of being an Arvest customer at the Arvest Ballpark Box Office. In addition, the Naturals will offer numerous 2-for-1 specials throughout the ballpark.

Fans will enjoy Johnsonville Buck-A-Brats on Tuesday nights at Arvest Ballpark, with the exception of Tuesday, July 3, where $1 brats will be offered at designated spots along the concourse throughout the game.

Follow on MiLB First Pitch  https //stza.co/+wi1u-1U

Shop  https //stza.co/+wi1u-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. RoughRiders
END:VALARM
DTSTART:20180523T000500Z
DTEND:20180523T030500Z
UID:s491HtLfUsFlwE5p6YEfuySa@stanza.co
SUMMARY:Naturals vs. RoughRiders
DESCRIPTION:Arvest Bank customers will enjoy $5 Dugout Premium tickets to every Tuesday night home game at Arvest Ballpark - except on Tuesday, July 3 - must show proof of being an Arvest customer at the Arvest Ballpark Box Office. In addition, the Naturals will offer numerous 2-for-1 specials throughout the ballpark.\n\nFans will enjoy Johnsonville Buck-A-Brats on Tuesday nights at Arvest Ballpark, with the exception of Tuesday, July 3, where $1 brats will be offered at designated spots along the concourse throughout the game.\n\nFollow on MiLB First Pitch: https://stza.co/+wi1u-1U\n\nShop: https://stza.co/+wi1u-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Two for Tuesday
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. RoughRiders
<2018-05-23 Wed 19:05-22:05>
:PROPERTIES:
:ID:       PZ8-d4WLJnceRX3hg-Rmtix7@stanza.co
:LOCATION: What's It? Wednesday
:STATUS:   CONFIRMED
:END:

Naturals vs. RoughRiders Test out your skills with What's It? Wednesday trivia questions on the videoboard throughout the game for a chance at winning great prizes. In addition, fans can follow along on our social media throughout the day for even more chances to win.

Follow on MiLB First Pitch  https //stza.co/+wi1w-1D

Shop  https //stza.co/+wi1w-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. RoughRiders
END:VALARM
DTSTART:20180524T000500Z
DTEND:20180524T030500Z
UID:PZ8-d4WLJnceRX3hg-Rmtix7@stanza.co
SUMMARY:Naturals vs. RoughRiders
DESCRIPTION:Test out your skills with What's It? Wednesday trivia questions on the videoboard throughout the game for a chance at winning great prizes. In addition, fans can follow along on our social media throughout the day for even more chances to win.\n\nFollow on MiLB First Pitch: https://stza.co/+wi1w-1D\n\nShop: https://stza.co/+wi1w-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:What's It? Wednesday
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. RoughRiders
<2018-05-24 Thu 19:05-22:05>
:PROPERTIES:
:ID:       LmHObJtxAdo8jVSC42kI22SO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals vs. RoughRiders Naturals vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wi1y-3

Shop  https //stza.co/+wi1y-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. RoughRiders
END:VALARM
DTSTART:20180525T000500Z
DTEND:20180525T030500Z
UID:LmHObJtxAdo8jVSC42kI22SO@stanza.co
SUMMARY:Naturals vs. RoughRiders
DESCRIPTION:Naturals vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wi1y-3\n\nShop: https://stza.co/+wi1y-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. RockHounds
<2018-05-25 Fri 19:05-22:05>
:PROPERTIES:
:ID:       _odY1M9Iu5omOIhxpv15ejBi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Naturals vs. RockHounds Naturals vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+wi1A-a

Shop  https //stza.co/+wi1A-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. RockHounds
END:VALARM
DTSTART:20180526T000500Z
DTEND:20180526T030500Z
UID:_odY1M9Iu5omOIhxpv15ejBi@stanza.co
SUMMARY:Naturals vs. RockHounds
DESCRIPTION:Naturals vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wi1A-a\n\nShop: https://stza.co/+wi1A-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. RockHounds
<2018-05-26 Sat 18:05-21:05>
:PROPERTIES:
:ID:       mZ9ZP-h--kbmH9j0Me1tv3do@stanza.co
:LOCATION: Naturals Dri-Fit T-Shirt Giveaway
:STATUS:   CONFIRMED
:END:

Naturals vs. RockHounds The first 1500 fans through the gates on Saturday will receive a Naturals Dri-Fit T-Shirt courtesy of Gorilla Glue.

Fans arriving early will enjoy half price specials on over 70 alcoholic beverages in the Bullpen Craft Beer Bar, located down the 1st base concourse, from 4 35 p.m. until 5 35 p.m.

Follow on MiLB First Pitch  https //stza.co/+wi1B-2G

Shop  https //stza.co/+wi1B-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. RockHounds
END:VALARM
DTSTART:20180526T230500Z
DTEND:20180527T020500Z
UID:mZ9ZP-h--kbmH9j0Me1tv3do@stanza.co
SUMMARY:Naturals vs. RockHounds
DESCRIPTION:The first 1500 fans through the gates on Saturday will receive a Naturals Dri-Fit T-Shirt courtesy of Gorilla Glue.\n\nFans arriving early will enjoy half price specials on over 70 alcoholic beverages in the Bullpen Craft Beer Bar, located down the 1st base concourse, from 4:35 p.m. until 5:35 p.m.\n\nFollow on MiLB First Pitch: https://stza.co/+wi1B-2G\n\nShop: https://stza.co/+wi1B-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Naturals Dri-Fit T-Shirt Giveaway
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. RockHounds
<2018-05-27 Sun 18:35-21:35>
:PROPERTIES:
:ID:       bINWXcMIQAkCy3wLtRKH9yGx@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Naturals vs. RockHounds 



Young Naturals fans will enjoy Mercy Kids Run the Bases following every Sunday home game at Arvest Ballpark - Except for Sunday, June 17

Follow on MiLB First Pitch  https //stza.co/+wi1E-1

Shop  https //stza.co/+wi1E-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. RockHounds
END:VALARM
DTSTART:20180527T233500Z
DTEND:20180528T023500Z
UID:bINWXcMIQAkCy3wLtRKH9yGx@stanza.co
SUMMARY:Naturals vs. RockHounds
DESCRIPTION:\n\n\n\nYoung Naturals fans will enjoy Mercy Kids Run the Bases following every Sunday home game at Arvest Ballpark - Except for Sunday, June 17\n\nFollow on MiLB First Pitch: https://stza.co/+wi1E-1\n\nShop: https://stza.co/+wi1E-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ RoughRiders
<2018-05-29 Tue 19:05-22:05>
:PROPERTIES:
:ID:       Zt8_eDum-hIL1r3S9Hoj4dzf@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ RoughRiders Naturals @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYbn-1k

Shop  https //stza.co/+wYbn-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ RoughRiders
END:VALARM
DTSTART:20180530T000500Z
DTEND:20180530T030500Z
UID:Zt8_eDum-hIL1r3S9Hoj4dzf@stanza.co
SUMMARY:Naturals @ RoughRiders
DESCRIPTION:Naturals @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYbn-1k\n\nShop: https://stza.co/+wYbn-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ RoughRiders
<2018-05-30 Wed 19:05-22:05>
:PROPERTIES:
:ID:       iXvsVkLBy7KpC3I5os45HQ3r@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ RoughRiders Naturals @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYbo-$

Shop  https //stza.co/+wYbo-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ RoughRiders
END:VALARM
DTSTART:20180531T000500Z
DTEND:20180531T030500Z
UID:iXvsVkLBy7KpC3I5os45HQ3r@stanza.co
SUMMARY:Naturals @ RoughRiders
DESCRIPTION:Naturals @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYbo-$\n\nShop: https://stza.co/+wYbo-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ RoughRiders
<2018-05-31 Thu 19:05-22:05>
:PROPERTIES:
:ID:       _IVYtEEOJx_lS_CS9xoEvZ59@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Naturals @ RoughRiders Naturals @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYbp-22

Shop  https //stza.co/+wYbp-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ RoughRiders
END:VALARM
DTSTART:20180601T000500Z
DTEND:20180601T030500Z
UID:_IVYtEEOJx_lS_CS9xoEvZ59@stanza.co
SUMMARY:Naturals @ RoughRiders
DESCRIPTION:Naturals @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYbp-22\n\nShop: https://stza.co/+wYbp-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ RockHounds
<2018-06-01 Fri 19:00-22:00>
:PROPERTIES:
:ID:       zmDWZ0U0nC8PDskuBQZ9oOnc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ RockHounds Naturals @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX4$-3F

Shop  https //stza.co/+wX4$-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ RockHounds
END:VALARM
DTSTART:20180602T000000Z
DTEND:20180602T030000Z
UID:zmDWZ0U0nC8PDskuBQZ9oOnc@stanza.co
SUMMARY:Naturals @ RockHounds
DESCRIPTION:Naturals @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX4$-3F\n\nShop: https://stza.co/+wX4$-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ RockHounds
<2018-06-02 Sat 19:00-22:00>
:PROPERTIES:
:ID:       bZPmylMuk0FpgrTpTmUcXahA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ RockHounds Naturals @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX50-1L

Shop  https //stza.co/+wX50-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ RockHounds
END:VALARM
DTSTART:20180603T000000Z
DTEND:20180603T030000Z
UID:bZPmylMuk0FpgrTpTmUcXahA@stanza.co
SUMMARY:Naturals @ RockHounds
DESCRIPTION:Naturals @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX50-1L\n\nShop: https://stza.co/+wX50-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ RockHounds
<2018-06-03 Sun 14:00-17:00>
:PROPERTIES:
:ID:       iSuNkmYIdYptPGgwaobuE8S0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Naturals @ RockHounds Naturals @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX51-3h

Shop  https //stza.co/+wX51-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ RockHounds
END:VALARM
DTSTART:20180603T190000Z
DTEND:20180603T220000Z
UID:iSuNkmYIdYptPGgwaobuE8S0@stanza.co
SUMMARY:Naturals @ RockHounds
DESCRIPTION:Naturals @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX51-3h\n\nShop: https://stza.co/+wX51-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Cardinals
<2018-06-05 Tue 19:05-22:05>
:PROPERTIES:
:ID:       7OayHN42F-I5CuegjJq40EE8@stanza.co
:LOCATION: Two for Tuesday
:STATUS:   CONFIRMED
:END:

Naturals vs. Cardinals Arvest Bank customers will enjoy $5 Dugout Premium tickets to every Tuesday night home game at Arvest Ballpark - except on Tuesday, July 3 - must show proof of being an Arvest customer at the Arvest Ballpark Box Office. In addition, the Naturals will offer numerous 2-for-1 specials throughout the ballpark.

Fans will enjoy Johnsonville Buck-A-Brats on Tuesday nights at Arvest Ballpark, with the exception of Tuesday, July 3, where $1 brats will be offered at designated spots along the concourse throughout the game.

Follow on MiLB First Pitch  https //stza.co/+wi1F-2G

Shop  https //stza.co/+wi1F-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Cardinals
END:VALARM
DTSTART:20180606T000500Z
DTEND:20180606T030500Z
UID:7OayHN42F-I5CuegjJq40EE8@stanza.co
SUMMARY:Naturals vs. Cardinals
DESCRIPTION:Arvest Bank customers will enjoy $5 Dugout Premium tickets to every Tuesday night home game at Arvest Ballpark - except on Tuesday, July 3 - must show proof of being an Arvest customer at the Arvest Ballpark Box Office. In addition, the Naturals will offer numerous 2-for-1 specials throughout the ballpark.\n\nFans will enjoy Johnsonville Buck-A-Brats on Tuesday nights at Arvest Ballpark, with the exception of Tuesday, July 3, where $1 brats will be offered at designated spots along the concourse throughout the game.\n\nFollow on MiLB First Pitch: https://stza.co/+wi1F-2G\n\nShop: https://stza.co/+wi1F-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Two for Tuesday
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Cardinals
<2018-06-06 Wed 19:05-22:05>
:PROPERTIES:
:ID:       eELNU0uU6iRGT6H2lEmKxV37@stanza.co
:LOCATION: What's It? Wednesday
:STATUS:   CONFIRMED
:END:

Naturals vs. Cardinals Test out your skills with What's It? Wednesday trivia questions on the videoboard throughout the game for a chance at winning great prizes. In addition, fans can follow along on our social media throughout the day for even more chances to win.

Follow on MiLB First Pitch  https //stza.co/+wi1I-3

Shop  https //stza.co/+wi1I-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Cardinals
END:VALARM
DTSTART:20180607T000500Z
DTEND:20180607T030500Z
UID:eELNU0uU6iRGT6H2lEmKxV37@stanza.co
SUMMARY:Naturals vs. Cardinals
DESCRIPTION:Test out your skills with What's It? Wednesday trivia questions on the videoboard throughout the game for a chance at winning great prizes. In addition, fans can follow along on our social media throughout the day for even more chances to win.\n\nFollow on MiLB First Pitch: https://stza.co/+wi1I-3\n\nShop: https://stza.co/+wi1I-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:What's It? Wednesday
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Cardinals
<2018-06-07 Thu 19:05-22:05>
:PROPERTIES:
:ID:       LksNRlfSS-m3kC8XkUNw-Huc@stanza.co
:LOCATION: Commemorative Ceramic Stein Giveaway
:STATUS:   CONFIRMED
:END:

Naturals vs. Cardinals The first 1000 fans in attendance will receive a Naturals Commemorative Ceramic Stein courtesy of Foghorn's.



Follow on MiLB First Pitch  https //stza.co/+wi1K-1x

Shop  https //stza.co/+wi1K-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Cardinals
END:VALARM
DTSTART:20180608T000500Z
DTEND:20180608T030500Z
UID:LksNRlfSS-m3kC8XkUNw-Huc@stanza.co
SUMMARY:Naturals vs. Cardinals
DESCRIPTION:The first 1000 fans in attendance will receive a Naturals Commemorative Ceramic Stein courtesy of Foghorn's.\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+wi1K-1x\n\nShop: https://stza.co/+wi1K-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Commemorative Ceramic Stein Giveaway
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Cardinals
<2018-06-08 Fri 19:05-22:05>
:PROPERTIES:
:ID:       MgfewnSD4XEW-j625nJNP7y1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals vs. Cardinals Naturals vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+wi1M-2e

Shop  https //stza.co/+wi1M-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Cardinals
END:VALARM
DTSTART:20180609T000500Z
DTEND:20180609T030500Z
UID:MgfewnSD4XEW-j625nJNP7y1@stanza.co
SUMMARY:Naturals vs. Cardinals
DESCRIPTION:Naturals vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wi1M-2e\n\nShop: https://stza.co/+wi1M-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Travelers
<2018-06-09 Sat 18:10-21:10>
:PROPERTIES:
:ID:       8BWZ61pLtDXejcS4UMntuQWf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Travelers Naturals @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w03O-3l

Shop  https //stza.co/+w03O-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Travelers
END:VALARM
DTSTART:20180609T231000Z
DTEND:20180610T021000Z
UID:8BWZ61pLtDXejcS4UMntuQWf@stanza.co
SUMMARY:Naturals @ Travelers
DESCRIPTION:Naturals @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w03O-3l\n\nShop: https://stza.co/+w03O-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Travelers
<2018-06-10 Sun 14:10-17:10>
:PROPERTIES:
:ID:       w74ydnyh-PW13iRMZEM3ixgp@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Naturals @ Travelers Naturals @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w03P-1A

Shop  https //stza.co/+w03P-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Travelers
END:VALARM
DTSTART:20180610T191000Z
DTEND:20180610T221000Z
UID:w74ydnyh-PW13iRMZEM3ixgp@stanza.co
SUMMARY:Naturals @ Travelers
DESCRIPTION:Naturals @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w03P-1A\n\nShop: https://stza.co/+w03P-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Travelers
<2018-06-11 Mon 19:10-22:10>
:PROPERTIES:
:ID:       EFb1h6JPhUiaPJEOXuWwuhbU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Travelers Naturals @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w03Q-8

Shop  https //stza.co/+w03Q-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Travelers
END:VALARM
DTSTART:20180612T001000Z
DTEND:20180612T031000Z
UID:EFb1h6JPhUiaPJEOXuWwuhbU@stanza.co
SUMMARY:Naturals @ Travelers
DESCRIPTION:Naturals @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w03Q-8\n\nShop: https://stza.co/+w03Q-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Travelers
<2018-06-12 Tue 19:10-22:10>
:PROPERTIES:
:ID:       aDPiIU3cPVZDRBSmStWnZJFk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Travelers Naturals @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w03R-L

Shop  https //stza.co/+w03R-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Travelers
END:VALARM
DTSTART:20180613T001000Z
DTEND:20180613T031000Z
UID:aDPiIU3cPVZDRBSmStWnZJFk@stanza.co
SUMMARY:Naturals @ Travelers
DESCRIPTION:Naturals @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w03R-L\n\nShop: https://stza.co/+w03R-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Drillers
<2018-06-13 Wed 19:05-22:05>
:PROPERTIES:
:ID:       Oa5vMV7IMIf__zK0B3eBuC5h@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Naturals @ Drillers Naturals @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w06Q-R

Shop  https //stza.co/+w06Q-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Drillers
END:VALARM
DTSTART:20180614T000500Z
DTEND:20180614T030500Z
UID:Oa5vMV7IMIf__zK0B3eBuC5h@stanza.co
SUMMARY:Naturals @ Drillers
DESCRIPTION:Naturals @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w06Q-R\n\nShop: https://stza.co/+w06Q-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Drillers
<2018-06-14 Thu 19:05-22:05>
:PROPERTIES:
:ID:       EwCQjnRIqnLxCJON1xs8_JVx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Drillers Naturals @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w06R-1H

Shop  https //stza.co/+w06R-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Drillers
END:VALARM
DTSTART:20180615T000500Z
DTEND:20180615T030500Z
UID:EwCQjnRIqnLxCJON1xs8_JVx@stanza.co
SUMMARY:Naturals @ Drillers
DESCRIPTION:Naturals @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w06R-1H\n\nShop: https://stza.co/+w06R-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Drillers
<2018-06-15 Fri 19:05-22:05>
:PROPERTIES:
:ID:       6TaXLgSZvP22le14inEyGgSv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Drillers Naturals @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w06S-y

Shop  https //stza.co/+w06S-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Drillers
END:VALARM
DTSTART:20180616T000500Z
DTEND:20180616T030500Z
UID:6TaXLgSZvP22le14inEyGgSv@stanza.co
SUMMARY:Naturals @ Drillers
DESCRIPTION:Naturals @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w06S-y\n\nShop: https://stza.co/+w06S-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Drillers
<2018-06-16 Sat 19:05-22:05>
:PROPERTIES:
:ID:       MqtYDA0nVhYbOsst6kb45PxZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Naturals @ Drillers Naturals @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w06T-1g

Shop  https //stza.co/+w06T-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Drillers
END:VALARM
DTSTART:20180617T000500Z
DTEND:20180617T030500Z
UID:MqtYDA0nVhYbOsst6kb45PxZ@stanza.co
SUMMARY:Naturals @ Drillers
DESCRIPTION:Naturals @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w06T-1g\n\nShop: https://stza.co/+w06T-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Travelers
<2018-06-17 Sun 14:05-17:05>
:PROPERTIES:
:ID:       qtky2_ooSbhwDqUI--5MEAXS@stanza.co
:LOCATION: Father's Day Grilling Apron Giveaway
:STATUS:   CONFIRMED
:END:

Naturals vs. Travelers The first 1000 Dads in attendance will receive a Father's Day Grilling Apron courtesy of Bush's.



Join us for a special Father's Day game of catch as all families are invited onto the outfield following the game for a Post-Game Catch on the Field by Mercy Kids. Fans must bring their own gloves and balls.  

Follow on MiLB First Pitch  https //stza.co/+wi1O-2Q

Shop  https //stza.co/+wi1O-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Travelers
END:VALARM
DTSTART:20180617T190500Z
DTEND:20180617T220500Z
UID:qtky2_ooSbhwDqUI--5MEAXS@stanza.co
SUMMARY:Naturals vs. Travelers
DESCRIPTION:The first 1000 Dads in attendance will receive a Father's Day Grilling Apron courtesy of Bush's.\n\n\n\nJoin us for a special Father's Day game of catch as all families are invited onto the outfield following the game for a Post-Game Catch on the Field by Mercy Kids. Fans must bring their own gloves and balls.  \n\nFollow on MiLB First Pitch: https://stza.co/+wi1O-2Q\n\nShop: https://stza.co/+wi1O-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Father's Day Grilling Apron Giveaway
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Travelers
<2018-06-18 Mon 19:05-22:05>
:PROPERTIES:
:ID:       WN7Q3msAN4-CsCEbV-2hOmal@stanza.co
:LOCATION: Monday Night Lights
:STATUS:   CONFIRMED
:END:

Naturals vs. Travelers Ozarks Electric Cooperative customers will receive $5 Dugout Premium Tickets at the Arvest Ballpark Box Office for every Monday night home game - Except for Monday, July 2. Must show proof of being an Ozarks Electric Cooperative customer.

Fans will enjoy $1 Hot Dogs at the concessions stands courtesy of Tyson Foods, Inc. every Monday night - except for Monday, July 2.

Fans young and old will have the opportunity to play Indigo Sky Baseball Bingo every Monday night - except for Monday, July  2 - at Arvest Ballpark for a chance to win great prizes. Max. of 5 winners per game - prizes by Indigo Sky Casino.

Follow on MiLB First Pitch  https //stza.co/+wi1Q-2l

Shop  https //stza.co/+wi1Q-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Travelers
END:VALARM
DTSTART:20180619T000500Z
DTEND:20180619T030500Z
UID:WN7Q3msAN4-CsCEbV-2hOmal@stanza.co
SUMMARY:Naturals vs. Travelers
DESCRIPTION:Ozarks Electric Cooperative customers will receive $5 Dugout Premium Tickets at the Arvest Ballpark Box Office for every Monday night home game - Except for Monday, July 2. Must show proof of being an Ozarks Electric Cooperative customer.\n\nFans will enjoy $1 Hot Dogs at the concessions stands courtesy of Tyson Foods, Inc. every Monday night - except for Monday, July 2.\n\nFans young and old will have the opportunity to play Indigo Sky Baseball Bingo every Monday night - except for Monday, July  2 - at Arvest Ballpark for a chance to win great prizes. Max. of 5 winners per game - prizes by Indigo Sky Casino.\n\nFollow on MiLB First Pitch: https://stza.co/+wi1Q-2l\n\nShop: https://stza.co/+wi1Q-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Monday Night Lights
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Travelers
<2018-06-19 Tue 19:05-22:05>
:PROPERTIES:
:ID:       ZF21tQVeK1Hjpzaf1XFEIph9@stanza.co
:LOCATION: Two for Tuesday
:STATUS:   CONFIRMED
:END:

Naturals vs. Travelers Arvest Bank customers will enjoy $5 Dugout Premium tickets to every Tuesday night home game at Arvest Ballpark - except on Tuesday, July 3 - must show proof of being an Arvest customer at the Arvest Ballpark Box Office. In addition, the Naturals will offer numerous 2-for-1 specials throughout the ballpark.

Fans will enjoy Johnsonville Buck-A-Brats on Tuesday nights at Arvest Ballpark, with the exception of Tuesday, July 3, where $1 brats will be offered at designated spots along the concourse throughout the game.

Follow on MiLB First Pitch  https //stza.co/+wi1R-1c

Shop  https //stza.co/+wi1R-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Travelers
END:VALARM
DTSTART:20180620T000500Z
DTEND:20180620T030500Z
UID:ZF21tQVeK1Hjpzaf1XFEIph9@stanza.co
SUMMARY:Naturals vs. Travelers
DESCRIPTION:Arvest Bank customers will enjoy $5 Dugout Premium tickets to every Tuesday night home game at Arvest Ballpark - except on Tuesday, July 3 - must show proof of being an Arvest customer at the Arvest Ballpark Box Office. In addition, the Naturals will offer numerous 2-for-1 specials throughout the ballpark.\n\nFans will enjoy Johnsonville Buck-A-Brats on Tuesday nights at Arvest Ballpark, with the exception of Tuesday, July 3, where $1 brats will be offered at designated spots along the concourse throughout the game.\n\nFollow on MiLB First Pitch: https://stza.co/+wi1R-1c\n\nShop: https://stza.co/+wi1R-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Two for Tuesday
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Travelers
<2018-06-20 Wed 12:05-15:05>
:PROPERTIES:
:ID:       G95wcm9gi0DrTEUPv8yTSUkJ@stanza.co
:LOCATION: Matinee Baseball at Arvest Ballpark
:STATUS:   CONFIRMED
:END:

Naturals vs. Travelers Take an extended lunch break for some Matinee Baseball at Arvest Ballpark as the Naturals will take on the Arkansas Travelers at 12 05 p.m. on June 20.

Summer Camps from throughout Northwest Arkansas and the surrounding communities can enjoy discounted tickets for their campers and counselors to enjoy a matinee baseball game at Arvest Ballpark.

Follow on MiLB First Pitch  https //stza.co/+wi1T-1d

Shop  https //stza.co/+wi1T-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Travelers
END:VALARM
DTSTART:20180620T170500Z
DTEND:20180620T200500Z
UID:G95wcm9gi0DrTEUPv8yTSUkJ@stanza.co
SUMMARY:Naturals vs. Travelers
DESCRIPTION:Take an extended lunch break for some Matinee Baseball at Arvest Ballpark as the Naturals will take on the Arkansas Travelers at 12:05 p.m. on June 20.\n\nSummer Camps from throughout Northwest Arkansas and the surrounding communities can enjoy discounted tickets for their campers and counselors to enjoy a matinee baseball game at Arvest Ballpark.\n\nFollow on MiLB First Pitch: https://stza.co/+wi1T-1d\n\nShop: https://stza.co/+wi1T-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Matinee Baseball at Arvest Ballpark
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Drillers
<2018-06-21 Thu 19:05-22:05>
:PROPERTIES:
:ID:       LFYykGcz6wnMWX0yMOzpyqz8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Drillers Naturals @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w06U-1p

Shop  https //stza.co/+w06U-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Drillers
END:VALARM
DTSTART:20180622T000500Z
DTEND:20180622T030500Z
UID:LFYykGcz6wnMWX0yMOzpyqz8@stanza.co
SUMMARY:Naturals @ Drillers
DESCRIPTION:Naturals @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w06U-1p\n\nShop: https://stza.co/+w06U-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Drillers
<2018-06-22 Fri 19:05-22:05>
:PROPERTIES:
:ID:       j-DR0RzclpoDCu-6MIFxgHor@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Drillers Naturals @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w06V-1g

Shop  https //stza.co/+w06V-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Drillers
END:VALARM
DTSTART:20180623T000500Z
DTEND:20180623T030500Z
UID:j-DR0RzclpoDCu-6MIFxgHor@stanza.co
SUMMARY:Naturals @ Drillers
DESCRIPTION:Naturals @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w06V-1g\n\nShop: https://stza.co/+w06V-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Drillers
<2018-06-23 Sat 19:05-22:05>
:PROPERTIES:
:ID:       tg0ysjwox9_xAUVw-KEtQvA6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Naturals @ Drillers Naturals @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w06W-3o

Shop  https //stza.co/+w06W-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Drillers
END:VALARM
DTSTART:20180624T000500Z
DTEND:20180624T030500Z
UID:tg0ysjwox9_xAUVw-KEtQvA6@stanza.co
SUMMARY:Naturals @ Drillers
DESCRIPTION:Naturals @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w06W-3o\n\nShop: https://stza.co/+w06W-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Drillers
<2018-06-24 Sun 13:05-16:05>
:PROPERTIES:
:ID:       17HK9RL7SY1CzY1k3TSby0SG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Drillers Naturals @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w06X-1b

Shop  https //stza.co/+w06X-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Drillers
END:VALARM
DTSTART:20180624T180500Z
DTEND:20180624T210500Z
UID:17HK9RL7SY1CzY1k3TSby0SG@stanza.co
SUMMARY:Naturals @ Drillers
DESCRIPTION:Naturals @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w06X-1b\n\nShop: https://stza.co/+w06X-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Missions
<2018-06-28 Thu 19:05-22:05>
:PROPERTIES:
:ID:       Hqk7MnG7r2yZGOCGkigAkQoY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals vs. Missions Naturals vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wi1V-3T

Shop  https //stza.co/+wi1V-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Missions
END:VALARM
DTSTART:20180629T000500Z
DTEND:20180629T030500Z
UID:Hqk7MnG7r2yZGOCGkigAkQoY@stanza.co
SUMMARY:Naturals vs. Missions
DESCRIPTION:Naturals vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wi1V-3T\n\nShop: https://stza.co/+wi1V-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Missions
<2018-06-29 Fri 19:05-22:05>
:PROPERTIES:
:ID:       bISi4nqdGy_CdI1FAz0lvId5@stanza.co
:LOCATION: Fireworks Friday
:STATUS:   CONFIRMED
:END:

Naturals vs. Missions 



Follow on MiLB First Pitch  https //stza.co/+wi1X-c

Shop  https //stza.co/+wi1X-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Missions
END:VALARM
DTSTART:20180630T000500Z
DTEND:20180630T030500Z
UID:bISi4nqdGy_CdI1FAz0lvId5@stanza.co
SUMMARY:Naturals vs. Missions
DESCRIPTION:\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+wi1X-c\n\nShop: https://stza.co/+wi1X-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Friday
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Missions
<2018-06-30 Sat 18:05-21:05>
:PROPERTIES:
:ID:       Gkg9loQ3Qjyjm0_zxEw4F4ZU@stanza.co
:LOCATION: Throwback Jersey Giveaway
:STATUS:   CONFIRMED
:END:

Naturals vs. Missions The first 2000 fans in attendance on Saturday night will receive a Throwback Naturals Batting Practice Jersey courtesy of Tyson Foods, Inc. 

Fans arriving early will enjoy half price specials on over 70 alcoholic beverages in the Bullpen Craft Beer Bar, located down the 1st base concourse, from 4 35 p.m. until 5 35 p.m.



Follow on MiLB First Pitch  https //stza.co/+wi1_-1G

Shop  https //stza.co/+wi1_-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Missions
END:VALARM
DTSTART:20180630T230500Z
DTEND:20180701T020500Z
UID:Gkg9loQ3Qjyjm0_zxEw4F4ZU@stanza.co
SUMMARY:Naturals vs. Missions
DESCRIPTION:The first 2000 fans in attendance on Saturday night will receive a Throwback Naturals Batting Practice Jersey courtesy of Tyson Foods, Inc. \n\nFans arriving early will enjoy half price specials on over 70 alcoholic beverages in the Bullpen Craft Beer Bar, located down the 1st base concourse, from 4:35 p.m. until 5:35 p.m.\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+wi1_-1G\n\nShop: https://stza.co/+wi1_-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Throwback Jersey Giveaway
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Hooks
<2018-07-01 Sun 16:05-19:05>
:PROPERTIES:
:ID:       9uXqtUAoDKOqF0vpcUMdRjuG@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Naturals vs. Hooks The first 1000 fans through the gates on Sunday night will receive an Emoji T-Shirt courtesy of Coca-Cola.



Young Naturals fans will enjoy Mercy Kids Run the Bases following every Sunday home game at Arvest Ballpark - Except for Sunday, June 17

Follow on MiLB First Pitch  https //stza.co/+wi20-3l

Shop  https //stza.co/+wi20-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Hooks
END:VALARM
DTSTART:20180701T210500Z
DTEND:20180702T000500Z
UID:9uXqtUAoDKOqF0vpcUMdRjuG@stanza.co
SUMMARY:Naturals vs. Hooks
DESCRIPTION:The first 1000 fans through the gates on Sunday night will receive an Emoji T-Shirt courtesy of Coca-Cola.\n\n\n\nYoung Naturals fans will enjoy Mercy Kids Run the Bases following every Sunday home game at Arvest Ballpark - Except for Sunday, June 17\n\nFollow on MiLB First Pitch: https://stza.co/+wi20-3l\n\nShop: https://stza.co/+wi20-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Hooks
<2018-07-02 Mon 18:35-21:35>
:PROPERTIES:
:ID:       me9keSDgIqm3pM0AqqwMzsVN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Naturals vs. Hooks Naturals vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wi21-w

Shop  https //stza.co/+wi21-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Hooks
END:VALARM
DTSTART:20180702T233500Z
DTEND:20180703T023500Z
UID:me9keSDgIqm3pM0AqqwMzsVN@stanza.co
SUMMARY:Naturals vs. Hooks
DESCRIPTION:Naturals vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wi21-w\n\nShop: https://stza.co/+wi21-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Hooks
<2018-07-03 Tue 18:35-21:35>
:PROPERTIES:
:ID:       FpkZxJzeRztekncZV_64G6JL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals vs. Hooks Naturals vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wi25-1I

Shop  https //stza.co/+wi25-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Hooks
END:VALARM
DTSTART:20180703T233500Z
DTEND:20180704T023500Z
UID:FpkZxJzeRztekncZV_64G6JL@stanza.co
SUMMARY:Naturals vs. Hooks
DESCRIPTION:Naturals vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wi25-1I\n\nShop: https://stza.co/+wi25-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Missions
<2018-07-04 Wed 17:05-20:05>
:PROPERTIES:
:ID:       wc5gSjvIWmjUltrAtvvhO5gL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Missions Naturals @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMvi-2$

Shop  https //stza.co/+wMvi-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Missions
END:VALARM
DTSTART:20180704T220500Z
DTEND:20180705T010500Z
UID:wc5gSjvIWmjUltrAtvvhO5gL@stanza.co
SUMMARY:Naturals @ Missions
DESCRIPTION:Naturals @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMvi-2$\n\nShop: https://stza.co/+wMvi-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Missions
<2018-07-05 Thu 19:05-22:05>
:PROPERTIES:
:ID:       pTbq7I2Dz3xjFqEmQWndQrYo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Naturals @ Missions Naturals @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMvj-12

Shop  https //stza.co/+wMvj-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Missions
END:VALARM
DTSTART:20180706T000500Z
DTEND:20180706T030500Z
UID:pTbq7I2Dz3xjFqEmQWndQrYo@stanza.co
SUMMARY:Naturals @ Missions
DESCRIPTION:Naturals @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMvj-12\n\nShop: https://stza.co/+wMvj-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Missions
<2018-07-06 Fri 19:05-22:05>
:PROPERTIES:
:ID:       axR_UwGyRdHA89o9KCZqfklM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Missions Naturals @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMvl-F

Shop  https //stza.co/+wMvl-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Missions
END:VALARM
DTSTART:20180707T000500Z
DTEND:20180707T030500Z
UID:axR_UwGyRdHA89o9KCZqfklM@stanza.co
SUMMARY:Naturals @ Missions
DESCRIPTION:Naturals @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMvl-F\n\nShop: https://stza.co/+wMvl-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Hooks
<2018-07-07 Sat 19:05-22:05>
:PROPERTIES:
:ID:       4fjkF4G0Wq5ko0g7fTvISeD3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Hooks Naturals @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHX-2q

Shop  https //stza.co/+xzHX-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Hooks
END:VALARM
DTSTART:20180708T000500Z
DTEND:20180708T030500Z
UID:4fjkF4G0Wq5ko0g7fTvISeD3@stanza.co
SUMMARY:Naturals @ Hooks
DESCRIPTION:Naturals @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHX-2q\n\nShop: https://stza.co/+xzHX-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Hooks
<2018-07-08 Sun 18:05-21:05>
:PROPERTIES:
:ID:       fvzelnCVoheRNfDYnkylVSoy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Naturals @ Hooks Naturals @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHY-1E

Shop  https //stza.co/+xzHY-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Hooks
END:VALARM
DTSTART:20180708T230500Z
DTEND:20180709T020500Z
UID:fvzelnCVoheRNfDYnkylVSoy@stanza.co
SUMMARY:Naturals @ Hooks
DESCRIPTION:Naturals @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHY-1E\n\nShop: https://stza.co/+xzHY-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Hooks
<2018-07-09 Mon 19:05-22:05>
:PROPERTIES:
:ID:       obW6eoesgLryGnzF8yy4bmSU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Hooks Naturals @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHZ-A

Shop  https //stza.co/+xzHZ-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Hooks
END:VALARM
DTSTART:20180710T000500Z
DTEND:20180710T030500Z
UID:obW6eoesgLryGnzF8yy4bmSU@stanza.co
SUMMARY:Naturals @ Hooks
DESCRIPTION:Naturals @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHZ-A\n\nShop: https://stza.co/+xzHZ-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Drillers
<2018-07-11 Wed 19:05-22:05>
:PROPERTIES:
:ID:       zzXPn6DK3TIqbK8bwQOwAfXG@stanza.co
:LOCATION: What's It? Wednesday
:STATUS:   CONFIRMED
:END:

Naturals vs. Drillers Test out your skills with What's It? Wednesday trivia questions on the videoboard throughout the game for a chance at winning great prizes. In addition, fans can follow along on our social media throughout the day for even more chances to win.

Follow on MiLB First Pitch  https //stza.co/+wi26-3b

Shop  https //stza.co/+wi26-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Drillers
END:VALARM
DTSTART:20180712T000500Z
DTEND:20180712T030500Z
UID:zzXPn6DK3TIqbK8bwQOwAfXG@stanza.co
SUMMARY:Naturals vs. Drillers
DESCRIPTION:Test out your skills with What's It? Wednesday trivia questions on the videoboard throughout the game for a chance at winning great prizes. In addition, fans can follow along on our social media throughout the day for even more chances to win.\n\nFollow on MiLB First Pitch: https://stza.co/+wi26-3b\n\nShop: https://stza.co/+wi26-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:What's It? Wednesday
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Drillers
<2018-07-12 Thu 19:05-22:05>
:PROPERTIES:
:ID:       7UtGlnSsCCfeIgzFXY79NMKw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals vs. Drillers Naturals vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+wi29-2$

Shop  https //stza.co/+wi29-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Drillers
END:VALARM
DTSTART:20180713T000500Z
DTEND:20180713T030500Z
UID:7UtGlnSsCCfeIgzFXY79NMKw@stanza.co
SUMMARY:Naturals vs. Drillers
DESCRIPTION:Naturals vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+wi29-2$\n\nShop: https://stza.co/+wi29-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Drillers
<2018-07-13 Fri 19:05-22:05>
:PROPERTIES:
:ID:       UdgMLa1MLhM2JgkMq3vMP13m@stanza.co
:LOCATION: Fireworks Friday
:STATUS:   CONFIRMED
:END:

Naturals vs. Drillers 



Follow on MiLB First Pitch  https //stza.co/+wi2c-1w

Shop  https //stza.co/+wi2c-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Drillers
END:VALARM
DTSTART:20180714T000500Z
DTEND:20180714T030500Z
UID:UdgMLa1MLhM2JgkMq3vMP13m@stanza.co
SUMMARY:Naturals vs. Drillers
DESCRIPTION:\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+wi2c-1w\n\nShop: https://stza.co/+wi2c-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Friday
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Drillers
<2018-07-14 Sat 18:05-21:05>
:PROPERTIES:
:ID:       L9yI6UKJrWDJUj5NPbVxwLHg@stanza.co
:LOCATION: Naturals Replica Home Jersey Giveaway
:STATUS:   CONFIRMED
:END:

Naturals vs. Drillers The first 2000 fans in attendance will receive a Naturals Replica Home Jersey Giveaway courtesy of Arvest.

Fans arriving early will enjoy half price specials on over 70 alcoholic beverages in the Bullpen Craft Beer Bar, located down the 1st base concourse, from 4 35 p.m. until 5 35 p.m.

Follow on MiLB First Pitch  https //stza.co/+wi2f-H

Shop  https //stza.co/+wi2f-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Drillers
END:VALARM
DTSTART:20180714T230500Z
DTEND:20180715T020500Z
UID:L9yI6UKJrWDJUj5NPbVxwLHg@stanza.co
SUMMARY:Naturals vs. Drillers
DESCRIPTION:The first 2000 fans in attendance will receive a Naturals Replica Home Jersey Giveaway courtesy of Arvest.\n\nFans arriving early will enjoy half price specials on over 70 alcoholic beverages in the Bullpen Craft Beer Bar, located down the 1st base concourse, from 4:35 p.m. until 5:35 p.m.\n\nFollow on MiLB First Pitch: https://stza.co/+wi2f-H\n\nShop: https://stza.co/+wi2f-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Naturals Replica Home Jersey Giveaway
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Cardinals
<2018-07-15 Sun 18:10-21:10>
:PROPERTIES:
:ID:       Dy1vLjfoMN0V_AgAcnmPVVyl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Naturals @ Cardinals Naturals @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPNq-r

Shop  https //stza.co/+wPNq-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Cardinals
END:VALARM
DTSTART:20180715T231000Z
DTEND:20180716T021000Z
UID:Dy1vLjfoMN0V_AgAcnmPVVyl@stanza.co
SUMMARY:Naturals @ Cardinals
DESCRIPTION:Naturals @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPNq-r\n\nShop: https://stza.co/+wPNq-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Cardinals
<2018-07-16 Mon 18:30-21:30>
:PROPERTIES:
:ID:       tisZKAFbHp8x8hsCD6doG7-l@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Cardinals Naturals @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPNr-1M

Shop  https //stza.co/+wPNr-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Cardinals
END:VALARM
DTSTART:20180716T233000Z
DTEND:20180717T023000Z
UID:tisZKAFbHp8x8hsCD6doG7-l@stanza.co
SUMMARY:Naturals @ Cardinals
DESCRIPTION:Naturals @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPNr-1M\n\nShop: https://stza.co/+wPNr-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Cardinals
<2018-07-17 Tue 18:30-21:30>
:PROPERTIES:
:ID:       jZcozhQz94HU-mDI8l69yFg0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Cardinals Naturals @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPNt-3_

Shop  https //stza.co/+wPNt-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Cardinals
END:VALARM
DTSTART:20180717T233000Z
DTEND:20180718T023000Z
UID:jZcozhQz94HU-mDI8l69yFg0@stanza.co
SUMMARY:Naturals @ Cardinals
DESCRIPTION:Naturals @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPNt-3_\n\nShop: https://stza.co/+wPNt-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Cardinals
<2018-07-18 Wed 18:30-21:30>
:PROPERTIES:
:ID:       3HeaRf6A02iYJS1SgUw627ly@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Naturals @ Cardinals Naturals @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPNu-3b

Shop  https //stza.co/+wPNu-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Cardinals
END:VALARM
DTSTART:20180718T233000Z
DTEND:20180719T023000Z
UID:3HeaRf6A02iYJS1SgUw627ly@stanza.co
SUMMARY:Naturals @ Cardinals
DESCRIPTION:Naturals @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPNu-3b\n\nShop: https://stza.co/+wPNu-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Drillers
<2018-07-19 Thu 19:05-22:05>
:PROPERTIES:
:ID:       5zRDyBLZY31Heq2zCMWLTtA9@stanza.co
:LOCATION: Bucket Hat Giveaway
:STATUS:   CONFIRMED
:END:

Naturals vs. Drillers The first 1000 fans in attendance on Thursday night will receive a Naturals Bucket Hat courtesy of Foghorn's.



Follow on MiLB First Pitch  https //stza.co/+wi2g-3T

Shop  https //stza.co/+wi2g-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Drillers
END:VALARM
DTSTART:20180720T000500Z
DTEND:20180720T030500Z
UID:5zRDyBLZY31Heq2zCMWLTtA9@stanza.co
SUMMARY:Naturals vs. Drillers
DESCRIPTION:The first 1000 fans in attendance on Thursday night will receive a Naturals Bucket Hat courtesy of Foghorn's.\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+wi2g-3T\n\nShop: https://stza.co/+wi2g-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Bucket Hat Giveaway
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Drillers
<2018-07-20 Fri 19:05-22:05>
:PROPERTIES:
:ID:       epZlqmiyQBWRJE9x8Peeo837@stanza.co
:LOCATION: Fireworks Friday
:STATUS:   CONFIRMED
:END:

Naturals vs. Drillers 



Follow on MiLB First Pitch  https //stza.co/+wi2i-g

Shop  https //stza.co/+wi2i-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Drillers
END:VALARM
DTSTART:20180721T000500Z
DTEND:20180721T030500Z
UID:epZlqmiyQBWRJE9x8Peeo837@stanza.co
SUMMARY:Naturals vs. Drillers
DESCRIPTION:\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+wi2i-g\n\nShop: https://stza.co/+wi2i-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Friday
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Drillers
<2018-07-21 Sat 18:05-21:05>
:PROPERTIES:
:ID:       pWl76oZq97NdV6C4lAiyOlZN@stanza.co
:LOCATION: Princess & Cowboy Night
:STATUS:   CONFIRMED
:END:

Naturals vs. Drillers 

Fans arriving early will enjoy half price specials on over 70 alcoholic beverages in the Bullpen Craft Beer Bar, located down the 1st base concourse, from 4 35 p.m. until 5 35 p.m.

Follow on MiLB First Pitch  https //stza.co/+wi2k-1n

Shop  https //stza.co/+wi2k-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Drillers
END:VALARM
DTSTART:20180721T230500Z
DTEND:20180722T020500Z
UID:pWl76oZq97NdV6C4lAiyOlZN@stanza.co
SUMMARY:Naturals vs. Drillers
DESCRIPTION:\n\nFans arriving early will enjoy half price specials on over 70 alcoholic beverages in the Bullpen Craft Beer Bar, located down the 1st base concourse, from 4:35 p.m. until 5:35 p.m.\n\nFollow on MiLB First Pitch: https://stza.co/+wi2k-1n\n\nShop: https://stza.co/+wi2k-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Princess & Cowboy Night
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Drillers
<2018-07-22 Sun 14:05-17:05>
:PROPERTIES:
:ID:       SGizncTMtjKxy1ounO5SG0kE@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Naturals vs. Drillers 



Young Naturals fans will enjoy Mercy Kids Run the Bases following every Sunday home game at Arvest Ballpark - Except for Sunday, June 17

Follow on MiLB First Pitch  https //stza.co/+wi2n-1$

Shop  https //stza.co/+wi2n-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Drillers
END:VALARM
DTSTART:20180722T190500Z
DTEND:20180722T220500Z
UID:SGizncTMtjKxy1ounO5SG0kE@stanza.co
SUMMARY:Naturals vs. Drillers
DESCRIPTION:\n\n\n\nYoung Naturals fans will enjoy Mercy Kids Run the Bases following every Sunday home game at Arvest Ballpark - Except for Sunday, June 17\n\nFollow on MiLB First Pitch: https://stza.co/+wi2n-1$\n\nShop: https://stza.co/+wi2n-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Travelers
<2018-07-23 Mon 19:05-22:05>
:PROPERTIES:
:ID:       gOg9vQc9PH0TEim4LTWZPJYf@stanza.co
:LOCATION: Monday Night Lights
:STATUS:   CONFIRMED
:END:

Naturals vs. Travelers Ozarks Electric Cooperative customers will receive $5 Dugout Premium Tickets at the Arvest Ballpark Box Office for every Monday night home game - Except for Monday, July 2. Must show proof of being an Ozarks Electric Cooperative customer.

Fans will enjoy $1 Hot Dogs at the concessions stands courtesy of Tyson Foods, Inc. every Monday night - except for Monday, July 2.

Fans young and old will have the opportunity to play Indigo Sky Baseball Bingo every Monday night - except for Monday, July  2 - at Arvest Ballpark for a chance to win great prizes. Max. of 5 winners per game - prizes by Indigo Sky Casino.

Follow on MiLB First Pitch  https //stza.co/+wi2o-2k

Shop  https //stza.co/+wi2o-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Travelers
END:VALARM
DTSTART:20180724T000500Z
DTEND:20180724T030500Z
UID:gOg9vQc9PH0TEim4LTWZPJYf@stanza.co
SUMMARY:Naturals vs. Travelers
DESCRIPTION:Ozarks Electric Cooperative customers will receive $5 Dugout Premium Tickets at the Arvest Ballpark Box Office for every Monday night home game - Except for Monday, July 2. Must show proof of being an Ozarks Electric Cooperative customer.\n\nFans will enjoy $1 Hot Dogs at the concessions stands courtesy of Tyson Foods, Inc. every Monday night - except for Monday, July 2.\n\nFans young and old will have the opportunity to play Indigo Sky Baseball Bingo every Monday night - except for Monday, July  2 - at Arvest Ballpark for a chance to win great prizes. Max. of 5 winners per game - prizes by Indigo Sky Casino.\n\nFollow on MiLB First Pitch: https://stza.co/+wi2o-2k\n\nShop: https://stza.co/+wi2o-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Monday Night Lights
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Travelers
<2018-07-24 Tue 19:05-22:05>
:PROPERTIES:
:ID:       3mYQYfaLVHlA9iTHcImjONhp@stanza.co
:LOCATION: Two for Tuesday
:STATUS:   CONFIRMED
:END:

Naturals vs. Travelers Arvest Bank customers will enjoy $5 Dugout Premium tickets to every Tuesday night home game at Arvest Ballpark - except on Tuesday, July 3 - must show proof of being an Arvest customer at the Arvest Ballpark Box Office. In addition, the Naturals will offer numerous 2-for-1 specials throughout the ballpark.

Fans will enjoy Johnsonville Buck-A-Brats on Tuesday nights at Arvest Ballpark, with the exception of Tuesday, July 3, where $1 brats will be offered at designated spots along the concourse throughout the game.

Follow on MiLB First Pitch  https //stza.co/+wi2q-2m

Shop  https //stza.co/+wi2q-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Travelers
END:VALARM
DTSTART:20180725T000500Z
DTEND:20180725T030500Z
UID:3mYQYfaLVHlA9iTHcImjONhp@stanza.co
SUMMARY:Naturals vs. Travelers
DESCRIPTION:Arvest Bank customers will enjoy $5 Dugout Premium tickets to every Tuesday night home game at Arvest Ballpark - except on Tuesday, July 3 - must show proof of being an Arvest customer at the Arvest Ballpark Box Office. In addition, the Naturals will offer numerous 2-for-1 specials throughout the ballpark.\n\nFans will enjoy Johnsonville Buck-A-Brats on Tuesday nights at Arvest Ballpark, with the exception of Tuesday, July 3, where $1 brats will be offered at designated spots along the concourse throughout the game.\n\nFollow on MiLB First Pitch: https://stza.co/+wi2q-2m\n\nShop: https://stza.co/+wi2q-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Two for Tuesday
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Travelers
<2018-07-25 Wed 19:05-22:05>
:PROPERTIES:
:ID:       90BpeCfgD1bF3g3k7ZgEUMiW@stanza.co
:LOCATION: What's It? Wednesday
:STATUS:   CONFIRMED
:END:

Naturals vs. Travelers Test out your skills with What's It? Wednesday trivia questions on the videoboard throughout the game for a chance at winning great prizes. In addition, fans can follow along on our social media throughout the day for even more chances to win.

Follow on MiLB First Pitch  https //stza.co/+wi2s-3d

Shop  https //stza.co/+wi2s-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Travelers
END:VALARM
DTSTART:20180726T000500Z
DTEND:20180726T030500Z
UID:90BpeCfgD1bF3g3k7ZgEUMiW@stanza.co
SUMMARY:Naturals vs. Travelers
DESCRIPTION:Test out your skills with What's It? Wednesday trivia questions on the videoboard throughout the game for a chance at winning great prizes. In addition, fans can follow along on our social media throughout the day for even more chances to win.\n\nFollow on MiLB First Pitch: https://stza.co/+wi2s-3d\n\nShop: https://stza.co/+wi2s-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:What's It? Wednesday
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Cardinals
<2018-07-26 Thu 19:10-22:10>
:PROPERTIES:
:ID:       50yTCeCUbQMIqAKdfAamwV6_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Cardinals Naturals @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPNv-1U

Shop  https //stza.co/+wPNv-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Cardinals
END:VALARM
DTSTART:20180727T001000Z
DTEND:20180727T031000Z
UID:50yTCeCUbQMIqAKdfAamwV6_@stanza.co
SUMMARY:Naturals @ Cardinals
DESCRIPTION:Naturals @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPNv-1U\n\nShop: https://stza.co/+wPNv-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Cardinals
<2018-07-27 Fri 19:10-22:10>
:PROPERTIES:
:ID:       xEb1bdo9k7phufYyGiHLrxQN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Cardinals Naturals @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPNw-2T

Shop  https //stza.co/+wPNw-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Cardinals
END:VALARM
DTSTART:20180728T001000Z
DTEND:20180728T031000Z
UID:xEb1bdo9k7phufYyGiHLrxQN@stanza.co
SUMMARY:Naturals @ Cardinals
DESCRIPTION:Naturals @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPNw-2T\n\nShop: https://stza.co/+wPNw-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Cardinals
<2018-07-28 Sat 18:10-21:10>
:PROPERTIES:
:ID:       YKaSrMSZDA2VNaO0e_q_TvaI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Naturals @ Cardinals Naturals @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPNx-18

Shop  https //stza.co/+wPNx-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Cardinals
END:VALARM
DTSTART:20180728T231000Z
DTEND:20180729T021000Z
UID:YKaSrMSZDA2VNaO0e_q_TvaI@stanza.co
SUMMARY:Naturals @ Cardinals
DESCRIPTION:Naturals @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPNx-18\n\nShop: https://stza.co/+wPNx-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Cardinals
<2018-07-29 Sun 18:10-21:10>
:PROPERTIES:
:ID:       Ur5KdmNPd1YxGuY5mnzjKKjH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Cardinals Naturals @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPNy-2J

Shop  https //stza.co/+wPNy-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Cardinals
END:VALARM
DTSTART:20180729T231000Z
DTEND:20180730T021000Z
UID:Ur5KdmNPd1YxGuY5mnzjKKjH@stanza.co
SUMMARY:Naturals @ Cardinals
DESCRIPTION:Naturals @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPNy-2J\n\nShop: https://stza.co/+wPNy-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Travelers
<2018-07-30 Mon 19:10-22:10>
:PROPERTIES:
:ID:       HwfGEkwylWChucnUPsSPX-tQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Travelers Naturals @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w03S-34

Shop  https //stza.co/+w03S-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Travelers
END:VALARM
DTSTART:20180731T001000Z
DTEND:20180731T031000Z
UID:HwfGEkwylWChucnUPsSPX-tQ@stanza.co
SUMMARY:Naturals @ Travelers
DESCRIPTION:Naturals @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w03S-34\n\nShop: https://stza.co/+w03S-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Travelers
<2018-07-31 Tue 19:10-22:10>
:PROPERTIES:
:ID:       5LsHpPYzD-QhmvhBQo43v44h@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Naturals @ Travelers Naturals @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w03T-3v

Shop  https //stza.co/+w03T-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Travelers
END:VALARM
DTSTART:20180801T001000Z
DTEND:20180801T031000Z
UID:5LsHpPYzD-QhmvhBQo43v44h@stanza.co
SUMMARY:Naturals @ Travelers
DESCRIPTION:Naturals @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w03T-3v\n\nShop: https://stza.co/+w03T-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Travelers
<2018-08-01 Wed 19:10-22:10>
:PROPERTIES:
:ID:       qsEIHaIfmTeBmnZoPXMoYyF1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Travelers Naturals @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w03U-

Shop  https //stza.co/+w03U-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Travelers
END:VALARM
DTSTART:20180802T001000Z
DTEND:20180802T031000Z
UID:qsEIHaIfmTeBmnZoPXMoYyF1@stanza.co
SUMMARY:Naturals @ Travelers
DESCRIPTION:Naturals @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w03U-\n\nShop: https://stza.co/+w03U-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Cardinals
<2018-08-02 Thu 19:05-22:05>
:PROPERTIES:
:ID:       lrkesVOoI4kGqd6mABv6HiG2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals vs. Cardinals Naturals vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+wi2u-3z

Shop  https //stza.co/+wi2u-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Cardinals
END:VALARM
DTSTART:20180803T000500Z
DTEND:20180803T030500Z
UID:lrkesVOoI4kGqd6mABv6HiG2@stanza.co
SUMMARY:Naturals vs. Cardinals
DESCRIPTION:Naturals vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wi2u-3z\n\nShop: https://stza.co/+wi2u-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Cardinals
<2018-08-03 Fri 19:05-22:05>
:PROPERTIES:
:ID:       W_qvSCAMTaLHbK_9X3La1qYF@stanza.co
:LOCATION: Fireworks Friday
:STATUS:   CONFIRMED
:END:

Naturals vs. Cardinals 



Follow on MiLB First Pitch  https //stza.co/+wi2x-p

Shop  https //stza.co/+wi2x-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Cardinals
END:VALARM
DTSTART:20180804T000500Z
DTEND:20180804T030500Z
UID:W_qvSCAMTaLHbK_9X3La1qYF@stanza.co
SUMMARY:Naturals vs. Cardinals
DESCRIPTION:\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+wi2x-p\n\nShop: https://stza.co/+wi2x-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Friday
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Cardinals
<2018-08-04 Sat 18:05-21:05>
:PROPERTIES:
:ID:       XAdRXqx10kFr0Mi4G2rB_dHa@stanza.co
:LOCATION: Salvy Splash Bobblehead Giveaway
:STATUS:   CONFIRMED
:END:

Naturals vs. Cardinals 

Fans arriving early will enjoy half price specials on over 70 alcoholic beverages in the Bullpen Craft Beer Bar, located down the 1st base concourse, from 4 35 p.m. until 5 35 p.m.

Follow on MiLB First Pitch  https //stza.co/+wi2A-2b

Shop  https //stza.co/+wi2A-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Cardinals
END:VALARM
DTSTART:20180804T230500Z
DTEND:20180805T020500Z
UID:XAdRXqx10kFr0Mi4G2rB_dHa@stanza.co
SUMMARY:Naturals vs. Cardinals
DESCRIPTION:\n\nFans arriving early will enjoy half price specials on over 70 alcoholic beverages in the Bullpen Craft Beer Bar, located down the 1st base concourse, from 4:35 p.m. until 5:35 p.m.\n\nFollow on MiLB First Pitch: https://stza.co/+wi2A-2b\n\nShop: https://stza.co/+wi2A-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Salvy Splash Bobblehead Giveaway
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Cardinals
<2018-08-05 Sun 14:05-17:05>
:PROPERTIES:
:ID:       gb8PU-py-qE4qzBDjg3npO19@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Naturals vs. Cardinals 



Young Naturals fans will enjoy Mercy Kids Run the Bases following every Sunday home game at Arvest Ballpark - Except for Sunday, June 17

Follow on MiLB First Pitch  https //stza.co/+wi2B-X

Shop  https //stza.co/+wi2B-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Cardinals
END:VALARM
DTSTART:20180805T190500Z
DTEND:20180805T220500Z
UID:gb8PU-py-qE4qzBDjg3npO19@stanza.co
SUMMARY:Naturals vs. Cardinals
DESCRIPTION:\n\n\n\nYoung Naturals fans will enjoy Mercy Kids Run the Bases following every Sunday home game at Arvest Ballpark - Except for Sunday, June 17\n\nFollow on MiLB First Pitch: https://stza.co/+wi2B-X\n\nShop: https://stza.co/+wi2B-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. RockHounds
<2018-08-07 Tue 19:05-22:05>
:PROPERTIES:
:ID:       lpLG46kP8S6W9_pt7vBu9X77@stanza.co
:LOCATION: Two for Tuesday
:STATUS:   CONFIRMED
:END:

Naturals vs. RockHounds Arvest Bank customers will enjoy $5 Dugout Premium tickets to every Tuesday night home game at Arvest Ballpark - except on Tuesday, July 3 - must show proof of being an Arvest customer at the Arvest Ballpark Box Office. In addition, the Naturals will offer numerous 2-for-1 specials throughout the ballpark.

Fans will enjoy Johnsonville Buck-A-Brats on Tuesday nights at Arvest Ballpark, with the exception of Tuesday, July 3, where $1 brats will be offered at designated spots along the concourse throughout the game.

Follow on MiLB First Pitch  https //stza.co/+wi2D-1

Shop  https //stza.co/+wi2D-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. RockHounds
END:VALARM
DTSTART:20180808T000500Z
DTEND:20180808T030500Z
UID:lpLG46kP8S6W9_pt7vBu9X77@stanza.co
SUMMARY:Naturals vs. RockHounds
DESCRIPTION:Arvest Bank customers will enjoy $5 Dugout Premium tickets to every Tuesday night home game at Arvest Ballpark - except on Tuesday, July 3 - must show proof of being an Arvest customer at the Arvest Ballpark Box Office. In addition, the Naturals will offer numerous 2-for-1 specials throughout the ballpark.\n\nFans will enjoy Johnsonville Buck-A-Brats on Tuesday nights at Arvest Ballpark, with the exception of Tuesday, July 3, where $1 brats will be offered at designated spots along the concourse throughout the game.\n\nFollow on MiLB First Pitch: https://stza.co/+wi2D-1\n\nShop: https://stza.co/+wi2D-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Two for Tuesday
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. RockHounds
<2018-08-08 Wed 19:05-22:05>
:PROPERTIES:
:ID:       cDcxW_yzAGPvmaD-TiWyCsOR@stanza.co
:LOCATION: What's It? Wednesday
:STATUS:   CONFIRMED
:END:

Naturals vs. RockHounds Test out your skills with What's It? Wednesday trivia questions on the videoboard throughout the game for a chance at winning great prizes. In addition, fans can follow along on our social media throughout the day for even more chances to win.

Follow on MiLB First Pitch  https //stza.co/+wi2F-16

Shop  https //stza.co/+wi2F-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. RockHounds
END:VALARM
DTSTART:20180809T000500Z
DTEND:20180809T030500Z
UID:cDcxW_yzAGPvmaD-TiWyCsOR@stanza.co
SUMMARY:Naturals vs. RockHounds
DESCRIPTION:Test out your skills with What's It? Wednesday trivia questions on the videoboard throughout the game for a chance at winning great prizes. In addition, fans can follow along on our social media throughout the day for even more chances to win.\n\nFollow on MiLB First Pitch: https://stza.co/+wi2F-16\n\nShop: https://stza.co/+wi2F-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:What's It? Wednesday
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. RockHounds
<2018-08-09 Thu 19:05-22:05>
:PROPERTIES:
:ID:       spHtwBVGeH3hUbc2zpFW7Y6B@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Naturals vs. RockHounds Naturals vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+wi2H-s

Shop  https //stza.co/+wi2H-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. RockHounds
END:VALARM
DTSTART:20180810T000500Z
DTEND:20180810T030500Z
UID:spHtwBVGeH3hUbc2zpFW7Y6B@stanza.co
SUMMARY:Naturals vs. RockHounds
DESCRIPTION:Naturals vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wi2H-s\n\nShop: https://stza.co/+wi2H-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. RoughRiders
<2018-08-10 Fri 19:15-22:15>
:PROPERTIES:
:ID:       z15vW1FCN-B1bMhHOjrbR5LB@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals vs. RoughRiders Naturals vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wi2L-1V

Shop  https //stza.co/+wi2L-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. RoughRiders
END:VALARM
DTSTART:20180811T001500Z
DTEND:20180811T031500Z
UID:z15vW1FCN-B1bMhHOjrbR5LB@stanza.co
SUMMARY:Naturals vs. RoughRiders
DESCRIPTION:Naturals vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wi2L-1V\n\nShop: https://stza.co/+wi2L-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. RoughRiders
<2018-08-11 Sat 18:05-21:05>
:PROPERTIES:
:ID:       7vtwh4Pd8XoneDrmB3c7N0B3@stanza.co
:LOCATION: Camouflage Jersey Giveaway
:STATUS:   CONFIRMED
:END:

Naturals vs. RoughRiders The first 2000 fans in attendance will receive a Naturals Camouflage Jersey Giveaway as they enter the gates.

Fans arriving early will enjoy half price specials on over 70 alcoholic beverages in the Bullpen Craft Beer Bar, located down the 1st base concourse, from 4 35 p.m. until 5 35 p.m.

Follow on MiLB First Pitch  https //stza.co/+wi2N-L

Shop  https //stza.co/+wi2N-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. RoughRiders
END:VALARM
DTSTART:20180811T230500Z
DTEND:20180812T020500Z
UID:7vtwh4Pd8XoneDrmB3c7N0B3@stanza.co
SUMMARY:Naturals vs. RoughRiders
DESCRIPTION:The first 2000 fans in attendance will receive a Naturals Camouflage Jersey Giveaway as they enter the gates.\n\nFans arriving early will enjoy half price specials on over 70 alcoholic beverages in the Bullpen Craft Beer Bar, located down the 1st base concourse, from 4:35 p.m. until 5:35 p.m.\n\nFollow on MiLB First Pitch: https://stza.co/+wi2N-L\n\nShop: https://stza.co/+wi2N-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Camouflage Jersey Giveaway
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. RoughRiders
<2018-08-12 Sun 14:05-17:05>
:PROPERTIES:
:ID:       o_cTP3Qu_x83ctIzjKRWYW6S@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Naturals vs. RoughRiders The first 1000 fans in attendance on KIDS EAT FREE Family Sunday will receive a Naturals Water Bottle courtesy of Red Vines and Sour Punch. Plus ALL kids 12 & under will receive a voucher for a FREE hot dog, chips, and 12 oz. soda.



Young Naturals fans will enjoy Mercy Kids Run the Bases following every Sunday home game at Arvest Ballpark - Except for Sunday, June 17

Follow on MiLB First Pitch  https //stza.co/+wi2P-f

Shop  https //stza.co/+wi2P-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. RoughRiders
END:VALARM
DTSTART:20180812T190500Z
DTEND:20180812T220500Z
UID:o_cTP3Qu_x83ctIzjKRWYW6S@stanza.co
SUMMARY:Naturals vs. RoughRiders
DESCRIPTION:The first 1000 fans in attendance on KIDS EAT FREE Family Sunday will receive a Naturals Water Bottle courtesy of Red Vines and Sour Punch. Plus ALL kids 12 & under will receive a voucher for a FREE hot dog, chips, and 12 oz. soda.\n\n\n\nYoung Naturals fans will enjoy Mercy Kids Run the Bases following every Sunday home game at Arvest Ballpark - Except for Sunday, June 17\n\nFollow on MiLB First Pitch: https://stza.co/+wi2P-f\n\nShop: https://stza.co/+wi2P-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ RockHounds
<2018-08-14 Tue 18:30-21:30>
:PROPERTIES:
:ID:       iGg3MLXWsJmQcvIlSTr9Tfvk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ RockHounds Naturals @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX52-32

Shop  https //stza.co/+wX52-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ RockHounds
END:VALARM
DTSTART:20180814T233000Z
DTEND:20180815T023000Z
UID:iGg3MLXWsJmQcvIlSTr9Tfvk@stanza.co
SUMMARY:Naturals @ RockHounds
DESCRIPTION:Naturals @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX52-32\n\nShop: https://stza.co/+wX52-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ RockHounds
<2018-08-15 Wed 18:30-21:30>
:PROPERTIES:
:ID:       _O_oNgL_UAvvFjfQ6mwi2KpJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Naturals @ RockHounds Naturals @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX54-3O

Shop  https //stza.co/+wX54-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ RockHounds
END:VALARM
DTSTART:20180815T233000Z
DTEND:20180816T023000Z
UID:_O_oNgL_UAvvFjfQ6mwi2KpJ@stanza.co
SUMMARY:Naturals @ RockHounds
DESCRIPTION:Naturals @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX54-3O\n\nShop: https://stza.co/+wX54-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ RockHounds
<2018-08-16 Thu 19:00-22:00>
:PROPERTIES:
:ID:       WIgiWwOT-TV6Ooax-AathUlj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ RockHounds Naturals @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX55-3g

Shop  https //stza.co/+wX55-3_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ RockHounds
END:VALARM
DTSTART:20180817T000000Z
DTEND:20180817T030000Z
UID:WIgiWwOT-TV6Ooax-AathUlj@stanza.co
SUMMARY:Naturals @ RockHounds
DESCRIPTION:Naturals @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX55-3g\n\nShop: https://stza.co/+wX55-3_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ RoughRiders
<2018-08-17 Fri 19:05-22:05>
:PROPERTIES:
:ID:       kAFwzR5eWOzLkYrdmWoksuZ5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ RoughRiders Naturals @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYbq-1r

Shop  https //stza.co/+wYbq-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ RoughRiders
END:VALARM
DTSTART:20180818T000500Z
DTEND:20180818T030500Z
UID:kAFwzR5eWOzLkYrdmWoksuZ5@stanza.co
SUMMARY:Naturals @ RoughRiders
DESCRIPTION:Naturals @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYbq-1r\n\nShop: https://stza.co/+wYbq-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ RoughRiders
<2018-08-18 Sat 19:05-22:05>
:PROPERTIES:
:ID:       Df6rmI2Ns5seRJhhHBhFk55u@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Naturals @ RoughRiders Naturals @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYbr-M

Shop  https //stza.co/+wYbr-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ RoughRiders
END:VALARM
DTSTART:20180819T000500Z
DTEND:20180819T030500Z
UID:Df6rmI2Ns5seRJhhHBhFk55u@stanza.co
SUMMARY:Naturals @ RoughRiders
DESCRIPTION:Naturals @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYbr-M\n\nShop: https://stza.co/+wYbr-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ RoughRiders
<2018-08-19 Sun 19:05-22:05>
:PROPERTIES:
:ID:       GMyZi3eOIXQn_QQAuQ1J9nkC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ RoughRiders Naturals @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYbs-b

Shop  https //stza.co/+wYbs-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ RoughRiders
END:VALARM
DTSTART:20180820T000500Z
DTEND:20180820T030500Z
UID:GMyZi3eOIXQn_QQAuQ1J9nkC@stanza.co
SUMMARY:Naturals @ RoughRiders
DESCRIPTION:Naturals @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYbs-b\n\nShop: https://stza.co/+wYbs-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Cardinals
<2018-08-21 Tue 19:05-22:05>
:PROPERTIES:
:ID:       O_3to8t8AfsG3tG1LgosEYaO@stanza.co
:LOCATION: Two for Tuesday
:STATUS:   CONFIRMED
:END:

Naturals vs. Cardinals Arvest Bank customers will enjoy $5 Dugout Premium tickets to every Tuesday night home game at Arvest Ballpark - except on Tuesday, July 3 - must show proof of being an Arvest customer at the Arvest Ballpark Box Office. In addition, the Naturals will offer numerous 2-for-1 specials throughout the ballpark.

Fans will enjoy Johnsonville Buck-A-Brats on Tuesday nights at Arvest Ballpark, with the exception of Tuesday, July 3, where $1 brats will be offered at designated spots along the concourse throughout the game.

Follow on MiLB First Pitch  https //stza.co/+wi2S-2m

Shop  https //stza.co/+wi2S-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Cardinals
END:VALARM
DTSTART:20180822T000500Z
DTEND:20180822T030500Z
UID:O_3to8t8AfsG3tG1LgosEYaO@stanza.co
SUMMARY:Naturals vs. Cardinals
DESCRIPTION:Arvest Bank customers will enjoy $5 Dugout Premium tickets to every Tuesday night home game at Arvest Ballpark - except on Tuesday, July 3 - must show proof of being an Arvest customer at the Arvest Ballpark Box Office. In addition, the Naturals will offer numerous 2-for-1 specials throughout the ballpark.\n\nFans will enjoy Johnsonville Buck-A-Brats on Tuesday nights at Arvest Ballpark, with the exception of Tuesday, July 3, where $1 brats will be offered at designated spots along the concourse throughout the game.\n\nFollow on MiLB First Pitch: https://stza.co/+wi2S-2m\n\nShop: https://stza.co/+wi2S-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Two for Tuesday
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Cardinals
<2018-08-22 Wed 19:05-22:05>
:PROPERTIES:
:ID:       QIviKsbUw2jyujLMi14Tfq5D@stanza.co
:LOCATION: What's It? Wednesday
:STATUS:   CONFIRMED
:END:

Naturals vs. Cardinals Test out your skills with What's It? Wednesday trivia questions on the videoboard throughout the game for a chance at winning great prizes. In addition, fans can follow along on our social media throughout the day for even more chances to win.

Follow on MiLB First Pitch  https //stza.co/+wi2U-v

Shop  https //stza.co/+wi2U-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Cardinals
END:VALARM
DTSTART:20180823T000500Z
DTEND:20180823T030500Z
UID:QIviKsbUw2jyujLMi14Tfq5D@stanza.co
SUMMARY:Naturals vs. Cardinals
DESCRIPTION:Test out your skills with What's It? Wednesday trivia questions on the videoboard throughout the game for a chance at winning great prizes. In addition, fans can follow along on our social media throughout the day for even more chances to win.\n\nFollow on MiLB First Pitch: https://stza.co/+wi2U-v\n\nShop: https://stza.co/+wi2U-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:What's It? Wednesday
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Cardinals
<2018-08-23 Thu 19:05-22:05>
:PROPERTIES:
:ID:       m-8xd7Y-T7yDFXOLA96uZZFK@stanza.co
:LOCATION: TBD Giveaway
:STATUS:   CONFIRMED
:END:

Naturals vs. Cardinals 



Follow on MiLB First Pitch  https //stza.co/+wi2V-U

Shop  https //stza.co/+wi2V-1J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Cardinals
END:VALARM
DTSTART:20180824T000500Z
DTEND:20180824T030500Z
UID:m-8xd7Y-T7yDFXOLA96uZZFK@stanza.co
SUMMARY:Naturals vs. Cardinals
DESCRIPTION:\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+wi2V-U\n\nShop: https://stza.co/+wi2V-1J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:TBD Giveaway
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Cardinals
<2018-08-24 Fri 19:05-22:05>
:PROPERTIES:
:ID:       84hxg4zLo-3EM0c9LVAsJzuS@stanza.co
:LOCATION: Fireworks Friday
:STATUS:   CONFIRMED
:END:

Naturals vs. Cardinals 





Follow on MiLB First Pitch  https //stza.co/+wi2Y-3N

Shop  https //stza.co/+wi2Y-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Cardinals
END:VALARM
DTSTART:20180825T000500Z
DTEND:20180825T030500Z
UID:84hxg4zLo-3EM0c9LVAsJzuS@stanza.co
SUMMARY:Naturals vs. Cardinals
DESCRIPTION:\n\n\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+wi2Y-3N\n\nShop: https://stza.co/+wi2Y-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Friday
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Travelers
<2018-08-25 Sat 18:10-21:10>
:PROPERTIES:
:ID:       Jd3c_WKhfLO1ljvoaoMMeTnC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Travelers Naturals @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w03V-11

Shop  https //stza.co/+w03V-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Travelers
END:VALARM
DTSTART:20180825T231000Z
DTEND:20180826T021000Z
UID:Jd3c_WKhfLO1ljvoaoMMeTnC@stanza.co
SUMMARY:Naturals @ Travelers
DESCRIPTION:Naturals @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w03V-11\n\nShop: https://stza.co/+w03V-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Travelers
<2018-08-26 Sun 14:10-17:10>
:PROPERTIES:
:ID:       -6btCtYvLNjZEtjelVU1YsWW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Naturals @ Travelers Naturals @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w03W-I

Shop  https //stza.co/+w03W-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Travelers
END:VALARM
DTSTART:20180826T191000Z
DTEND:20180826T221000Z
UID:-6btCtYvLNjZEtjelVU1YsWW@stanza.co
SUMMARY:Naturals @ Travelers
DESCRIPTION:Naturals @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w03W-I\n\nShop: https://stza.co/+w03W-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Travelers
<2018-08-27 Mon 19:10-22:10>
:PROPERTIES:
:ID:       qhSnpC79p0jDJuf4azouE-Cc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Travelers Naturals @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w03X-33

Shop  https //stza.co/+w03X-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Travelers
END:VALARM
DTSTART:20180828T001000Z
DTEND:20180828T031000Z
UID:qhSnpC79p0jDJuf4azouE-Cc@stanza.co
SUMMARY:Naturals @ Travelers
DESCRIPTION:Naturals @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w03X-33\n\nShop: https://stza.co/+w03X-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Drillers
<2018-08-28 Tue 19:05-22:05>
:PROPERTIES:
:ID:       EMR7z4bggKW0IE-aSfGoyRf9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Drillers Naturals @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w06Y-1s

Shop  https //stza.co/+w06Y-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Drillers
END:VALARM
DTSTART:20180829T000500Z
DTEND:20180829T030500Z
UID:EMR7z4bggKW0IE-aSfGoyRf9@stanza.co
SUMMARY:Naturals @ Drillers
DESCRIPTION:Naturals @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w06Y-1s\n\nShop: https://stza.co/+w06Y-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Drillers
<2018-08-29 Wed 19:05-22:05>
:PROPERTIES:
:ID:       6ZWFVNyVcAB8_OVNoUYmYRct@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Naturals @ Drillers Naturals @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w06Z-1P

Shop  https //stza.co/+w06Z-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Drillers
END:VALARM
DTSTART:20180830T000500Z
DTEND:20180830T030500Z
UID:6ZWFVNyVcAB8_OVNoUYmYRct@stanza.co
SUMMARY:Naturals @ Drillers
DESCRIPTION:Naturals @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w06Z-1P\n\nShop: https://stza.co/+w06Z-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Drillers
<2018-08-30 Thu 19:05-22:05>
:PROPERTIES:
:ID:       bz0rQEIzfsQ2pSfl3A-KPjHu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Drillers Naturals @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w06_-Q

Shop  https //stza.co/+w06_-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Drillers
END:VALARM
DTSTART:20180831T000500Z
DTEND:20180831T030500Z
UID:bz0rQEIzfsQ2pSfl3A-KPjHu@stanza.co
SUMMARY:Naturals @ Drillers
DESCRIPTION:Naturals @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w06_-Q\n\nShop: https://stza.co/+w06_-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals @ Drillers
<2018-08-31 Fri 19:05-22:05>
:PROPERTIES:
:ID:       zp2lbUzl8dAbpHO_Nkjx9gR2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Naturals @ Drillers Naturals @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w06$-m

Shop  https //stza.co/+w06$-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Naturals @ Drillers
END:VALARM
DTSTART:20180901T000500Z
DTEND:20180901T030500Z
UID:zp2lbUzl8dAbpHO_Nkjx9gR2@stanza.co
SUMMARY:Naturals @ Drillers
DESCRIPTION:Naturals @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w06$-m\n\nShop: https://stza.co/+w06$-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Travelers
<2018-09-01 Sat 18:05-21:05>
:PROPERTIES:
:ID:       l7cfBYvZN9tSH89Or9Ae4fGq@stanza.co
:LOCATION: Naturals Cap Giveaway
:STATUS:   CONFIRMED
:END:

Naturals vs. Travelers The first 2000 fans will receive a Naturals Cap Giveaway courtesy of OzarksGO as they enter the gates.

Fans arriving early will enjoy half price specials on over 70 alcoholic beverages in the Bullpen Craft Beer Bar, located down the 1st base concourse, from 4 35 p.m. until 5 35 p.m.



Follow on MiLB First Pitch  https //stza.co/+wi2$-2x

Shop  https //stza.co/+wi2$-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Travelers
END:VALARM
DTSTART:20180901T230500Z
DTEND:20180902T020500Z
UID:l7cfBYvZN9tSH89Or9Ae4fGq@stanza.co
SUMMARY:Naturals vs. Travelers
DESCRIPTION:The first 2000 fans will receive a Naturals Cap Giveaway courtesy of OzarksGO as they enter the gates.\n\nFans arriving early will enjoy half price specials on over 70 alcoholic beverages in the Bullpen Craft Beer Bar, located down the 1st base concourse, from 4:35 p.m. until 5:35 p.m.\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+wi2$-2x\n\nShop: https://stza.co/+wi2$-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Naturals Cap Giveaway
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Travelers
<2018-09-02 Sun 18:05-21:05>
:PROPERTIES:
:ID:       Q37g-9SM2KfiOOpv-ydGfRuB@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Naturals vs. Travelers 



Young Naturals fans will enjoy Mercy Kids Run the Bases following every Sunday home game at Arvest Ballpark - Except for Sunday, June 17



Follow on MiLB First Pitch  https //stza.co/+wi31-2H

Shop  https //stza.co/+wi31-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Travelers
END:VALARM
DTSTART:20180902T230500Z
DTEND:20180903T020500Z
UID:Q37g-9SM2KfiOOpv-ydGfRuB@stanza.co
SUMMARY:Naturals vs. Travelers
DESCRIPTION:\n\n\n\nYoung Naturals fans will enjoy Mercy Kids Run the Bases following every Sunday home game at Arvest Ballpark - Except for Sunday, June 17\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+wi31-2H\n\nShop: https://stza.co/+wi31-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Naturals vs. Travelers
<2018-09-03 Mon 13:05-16:05>
:PROPERTIES:
:ID:       CU8RxSHrVTQ6zDC9k8xc-WvE@stanza.co
:LOCATION: Unused Ticket Day
:STATUS:   CONFIRMED
:END:

Naturals vs. Travelers 

Fans will enjoy $1 Hot Dogs at the concessions stands courtesy of Tyson Foods, Inc. every Monday night - except for Monday, July 2.

Fans young and old will have the opportunity to play Indigo Sky Baseball Bingo every Monday night - except for Monday, July  2 - at Arvest Ballpark for a chance to win great prizes. Max. of 5 winners per game - prizes by Indigo Sky Casino.



Follow on MiLB First Pitch  https //stza.co/+wi33-13

Shop  https //stza.co/+wi33-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Naturals vs. Travelers
END:VALARM
DTSTART:20180903T180500Z
DTEND:20180903T210500Z
UID:CU8RxSHrVTQ6zDC9k8xc-WvE@stanza.co
SUMMARY:Naturals vs. Travelers
DESCRIPTION:\n\nFans will enjoy $1 Hot Dogs at the concessions stands courtesy of Tyson Foods, Inc. every Monday night - except for Monday, July 2.\n\nFans young and old will have the opportunity to play Indigo Sky Baseball Bingo every Monday night - except for Monday, July  2 - at Arvest Ballpark for a chance to win great prizes. Max. of 5 winners per game - prizes by Indigo Sky Casino.\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+wi33-13\n\nShop: https://stza.co/+wi33-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Unused Ticket Day
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
