#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* BlueClaws @ Intimidators
<2018-04-05 Thu 17:35-20:35>
:PROPERTIES:
:ID:       3yEgKINFKFkXA5tEIeeRrHuk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Intimidators BlueClaws @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIFx-3e

Shop  https //stza.co/+wIFx-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Intimidators
END:VALARM
DTSTART:20180405T223500Z
DTEND:20180406T013500Z
UID:3yEgKINFKFkXA5tEIeeRrHuk@stanza.co
SUMMARY:BlueClaws @ Intimidators
DESCRIPTION:BlueClaws @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIFx-3e\n\nShop: https://stza.co/+wIFx-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Intimidators
<2018-04-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       auvlj6ilVLx6vL8K_A0B0mcy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Intimidators BlueClaws @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIFy-j

Shop  https //stza.co/+wIFy-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Intimidators
END:VALARM
DTSTART:20180406T230500Z
DTEND:20180407T020500Z
UID:auvlj6ilVLx6vL8K_A0B0mcy@stanza.co
SUMMARY:BlueClaws @ Intimidators
DESCRIPTION:BlueClaws @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIFy-j\n\nShop: https://stza.co/+wIFy-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Intimidators
<2018-04-07 Sat 18:05-21:05>
:PROPERTIES:
:ID:       0z_5ONOoZQqyEgF11ihFnsef@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Intimidators BlueClaws @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIFz-2P

Shop  https //stza.co/+wIFz-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Intimidators
END:VALARM
DTSTART:20180407T230500Z
DTEND:20180408T020500Z
UID:0z_5ONOoZQqyEgF11ihFnsef@stanza.co
SUMMARY:BlueClaws @ Intimidators
DESCRIPTION:BlueClaws @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIFz-2P\n\nShop: https://stza.co/+wIFz-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Intimidators
<2018-04-08 Sun 14:35-17:35>
:PROPERTIES:
:ID:       NK1p-zH0rFUF9n_MnF3OcME1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Intimidators BlueClaws @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIFA-3L

Shop  https //stza.co/+wIFA-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Intimidators
END:VALARM
DTSTART:20180408T193500Z
DTEND:20180408T223500Z
UID:NK1p-zH0rFUF9n_MnF3OcME1@stanza.co
SUMMARY:BlueClaws @ Intimidators
DESCRIPTION:BlueClaws @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIFA-3L\n\nShop: https://stza.co/+wIFA-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Power
<2018-04-09 Mon 18:05-21:05>
:PROPERTIES:
:ID:       tNtvnPIoAPmaFH4mnf7lOpbl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Power BlueClaws @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ4a-2Z

Shop  https //stza.co/+xJ4a-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Power
END:VALARM
DTSTART:20180409T230500Z
DTEND:20180410T020500Z
UID:tNtvnPIoAPmaFH4mnf7lOpbl@stanza.co
SUMMARY:BlueClaws @ Power
DESCRIPTION:BlueClaws @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ4a-2Z\n\nShop: https://stza.co/+xJ4a-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Power
<2018-04-10 Tue 18:05-21:05>
:PROPERTIES:
:ID:       YM2z_gu42CGew5iYWxokZNge@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Power BlueClaws @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ4b-1N

Shop  https //stza.co/+xJ4b-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Power
END:VALARM
DTSTART:20180410T230500Z
DTEND:20180411T020500Z
UID:YM2z_gu42CGew5iYWxokZNge@stanza.co
SUMMARY:BlueClaws @ Power
DESCRIPTION:BlueClaws @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ4b-1N\n\nShop: https://stza.co/+xJ4b-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Power
<2018-04-11 Wed 09:35-12:35>
:PROPERTIES:
:ID:       BVgJINidhWkPxtNDdaz_XSk2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Power BlueClaws @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ4c-3U

Shop  https //stza.co/+xJ4c-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Power
END:VALARM
DTSTART:20180411T143500Z
DTEND:20180411T173500Z
UID:BVgJINidhWkPxtNDdaz_XSk2@stanza.co
SUMMARY:BlueClaws @ Power
DESCRIPTION:BlueClaws @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ4c-3U\n\nShop: https://stza.co/+xJ4c-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Shorebirds
<2018-04-12 Thu 17:35-20:35>
:PROPERTIES:
:ID:       abMu96v7c5CzTQavkciQW0M1@stanza.co
:LOCATION: Thirsty Thursday
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Shorebirds Dollar beer and soda plus great wings as part of Thirsty Thursday, every Thursday at FirstEnergy Park. 

Follow on MiLB First Pitch  https //stza.co/+vNTG-38

Shop  https //stza.co/+vNTG-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Shorebirds
END:VALARM
DTSTART:20180412T223500Z
DTEND:20180413T013500Z
UID:abMu96v7c5CzTQavkciQW0M1@stanza.co
SUMMARY:BlueClaws vs. Shorebirds
DESCRIPTION:Dollar beer and soda plus great wings as part of Thirsty Thursday, every Thursday at FirstEnergy Park. \n\nFollow on MiLB First Pitch: https://stza.co/+vNTG-38\n\nShop: https://stza.co/+vNTG-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursday
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Shorebirds
<2018-04-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       nxilT89RaDJarzthgFDkmGbm@stanza.co
:LOCATION: Fireworks Spectacular
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Shorebirds The BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. 

Follow on MiLB First Pitch  https //stza.co/+vNTJ-2v

Shop  https //stza.co/+vNTJ-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Shorebirds
END:VALARM
DTSTART:20180413T230500Z
DTEND:20180414T020500Z
UID:nxilT89RaDJarzthgFDkmGbm@stanza.co
SUMMARY:BlueClaws vs. Shorebirds
DESCRIPTION:The BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. \n\nFollow on MiLB First Pitch: https://stza.co/+vNTJ-2v\n\nShop: https://stza.co/+vNTJ-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Spectacular
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Shorebirds
<2018-04-14 Sat 15:05-18:05>
:PROPERTIES:
:ID:       j8RKxHQiTl1kgux34_vwVK9D@stanza.co
:LOCATION: Magnet Schedules
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Shorebirds The first 1,000 fans receive a BlueClaws Magnet Schedule thanks to Horizon Blue Cross Blue Shield of New Jersey.

Follow on MiLB First Pitch  https //stza.co/+vNTK-1J

Shop  https //stza.co/+vNTK-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Shorebirds
END:VALARM
DTSTART:20180414T200500Z
DTEND:20180414T230500Z
UID:j8RKxHQiTl1kgux34_vwVK9D@stanza.co
SUMMARY:BlueClaws vs. Shorebirds
DESCRIPTION:The first 1,000 fans receive a BlueClaws Magnet Schedule thanks to Horizon Blue Cross Blue Shield of New Jersey.\n\nFollow on MiLB First Pitch: https://stza.co/+vNTK-1J\n\nShop: https://stza.co/+vNTK-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Magnet Schedules
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Shorebirds
<2018-04-15 Sun 12:05-15:05>
:PROPERTIES:
:ID:       8x2A7zTH_uoBoG1iTsthVej6@stanza.co
:LOCATION: Bring the family to the park for our Kids Eat Free game
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Shorebirds The first 1,000 fans receive a BlueClaws Magnet Schedule thanks to Horizon Blue Cross Blue Shield of New Jersey.

Kids Eat Free at every Sunday BlueClaws home game thanks to ShopRite. Kids 12 and under receive a hot dog, chips and soda. 

Follow on MiLB First Pitch  https //stza.co/+vNTM-2c

Shop  https //stza.co/+vNTM-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Shorebirds
END:VALARM
DTSTART:20180415T170500Z
DTEND:20180415T200500Z
UID:8x2A7zTH_uoBoG1iTsthVej6@stanza.co
SUMMARY:BlueClaws vs. Shorebirds
DESCRIPTION:The first 1,000 fans receive a BlueClaws Magnet Schedule thanks to Horizon Blue Cross Blue Shield of New Jersey.\n\nKids Eat Free at every Sunday BlueClaws home game thanks to ShopRite. Kids 12 and under receive a hot dog, chips and soda. \n\nFollow on MiLB First Pitch: https://stza.co/+vNTM-2c\n\nShop: https://stza.co/+vNTM-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Bring the family to the park for our Kids Eat Free game
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Grasshoppers
<2018-04-16 Mon 17:35-20:35>
:PROPERTIES:
:ID:       zHPOoveqJvyYBa9eaHuARxit@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Grasshoppers BlueClaws vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+vNTP-1B

Shop  https //stza.co/+vNTP-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Grasshoppers
END:VALARM
DTSTART:20180416T223500Z
DTEND:20180417T013500Z
UID:zHPOoveqJvyYBa9eaHuARxit@stanza.co
SUMMARY:BlueClaws vs. Grasshoppers
DESCRIPTION:BlueClaws vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+vNTP-1B\n\nShop: https://stza.co/+vNTP-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Grasshoppers
<2018-04-17 Tue 17:35-20:35>
:PROPERTIES:
:ID:       iKGNbqrn8TRfXkXkfTz5ANlM@stanza.co
:LOCATION: Silver Sluggers Tuesday
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Grasshoppers It's Silver Sluggers Tuesday, where member of the BlueClaws Silver Sluggers Club eat free and receive a hot dog, bag of chips, and a soda. 

Follow on MiLB First Pitch  https //stza.co/+vNTQ-24

Shop  https //stza.co/+vNTQ-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Grasshoppers
END:VALARM
DTSTART:20180417T223500Z
DTEND:20180418T013500Z
UID:iKGNbqrn8TRfXkXkfTz5ANlM@stanza.co
SUMMARY:BlueClaws vs. Grasshoppers
DESCRIPTION:It's Silver Sluggers Tuesday, where member of the BlueClaws Silver Sluggers Club eat free and receive a hot dog, bag of chips, and a soda. \n\nFollow on MiLB First Pitch: https://stza.co/+vNTQ-24\n\nShop: https://stza.co/+vNTQ-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Silver Sluggers Tuesday
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Grasshoppers
<2018-04-18 Wed 17:35-20:35>
:PROPERTIES:
:ID:       3cw_dbVX6yyWFiZ5MdQR23eT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Grasshoppers BlueClaws vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+vNTT-2w

Shop  https //stza.co/+vNTT-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Grasshoppers
END:VALARM
DTSTART:20180418T223500Z
DTEND:20180419T013500Z
UID:3cw_dbVX6yyWFiZ5MdQR23eT@stanza.co
SUMMARY:BlueClaws vs. Grasshoppers
DESCRIPTION:BlueClaws vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+vNTT-2w\n\nShop: https://stza.co/+vNTT-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Shorebirds
<2018-04-19 Thu 18:05-21:05>
:PROPERTIES:
:ID:       qYux-5nJ1eMALbx_s4sGQ_R0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Shorebirds BlueClaws @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHSs-28

Shop  https //stza.co/+wHSs-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Shorebirds
END:VALARM
DTSTART:20180419T230500Z
DTEND:20180420T020500Z
UID:qYux-5nJ1eMALbx_s4sGQ_R0@stanza.co
SUMMARY:BlueClaws @ Shorebirds
DESCRIPTION:BlueClaws @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHSs-28\n\nShop: https://stza.co/+wHSs-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Shorebirds
<2018-04-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       hNKY2LWelMHrzQofX8B4kOUd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Shorebirds BlueClaws @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHSt-18

Shop  https //stza.co/+wHSt-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Shorebirds
END:VALARM
DTSTART:20180420T230500Z
DTEND:20180421T020500Z
UID:hNKY2LWelMHrzQofX8B4kOUd@stanza.co
SUMMARY:BlueClaws @ Shorebirds
DESCRIPTION:BlueClaws @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHSt-18\n\nShop: https://stza.co/+wHSt-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Shorebirds
<2018-04-21 Sat 18:05-21:05>
:PROPERTIES:
:ID:       8cmhl_MoGLAfXDBBIQu-mmO4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Shorebirds BlueClaws @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHSu-2l

Shop  https //stza.co/+wHSu-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Shorebirds
END:VALARM
DTSTART:20180421T230500Z
DTEND:20180422T020500Z
UID:8cmhl_MoGLAfXDBBIQu-mmO4@stanza.co
SUMMARY:BlueClaws @ Shorebirds
DESCRIPTION:BlueClaws @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHSu-2l\n\nShop: https://stza.co/+wHSu-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Shorebirds
<2018-04-22 Sun 13:05-16:05>
:PROPERTIES:
:ID:       CkYleu2M-E6WmNd_V8059bjW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Shorebirds BlueClaws @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHSv-d

Shop  https //stza.co/+wHSv-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Shorebirds
END:VALARM
DTSTART:20180422T180500Z
DTEND:20180422T210500Z
UID:CkYleu2M-E6WmNd_V8059bjW@stanza.co
SUMMARY:BlueClaws @ Shorebirds
DESCRIPTION:BlueClaws @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHSv-d\n\nShop: https://stza.co/+wHSv-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Suns
<2018-04-23 Mon 17:05-20:05>
:PROPERTIES:
:ID:       hf3ZROWmRHdMRUBU4js5u53C@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Suns BlueClaws @ Suns

Follow on MiLB First Pitch  https //stza.co/+xGG1-2c

Shop  https //stza.co/+xGG1-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Suns
END:VALARM
DTSTART:20180423T220500Z
DTEND:20180424T010500Z
UID:hf3ZROWmRHdMRUBU4js5u53C@stanza.co
SUMMARY:BlueClaws @ Suns
DESCRIPTION:BlueClaws @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xGG1-2c\n\nShop: https://stza.co/+xGG1-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Suns
<2018-04-24 Tue 17:05-20:05>
:PROPERTIES:
:ID:       pMw9HVKQosPHJpnnnpU4eWRd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Suns BlueClaws @ Suns

Follow on MiLB First Pitch  https //stza.co/+xGG2-c

Shop  https //stza.co/+xGG2-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Suns
END:VALARM
DTSTART:20180424T220500Z
DTEND:20180425T010500Z
UID:pMw9HVKQosPHJpnnnpU4eWRd@stanza.co
SUMMARY:BlueClaws @ Suns
DESCRIPTION:BlueClaws @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xGG2-c\n\nShop: https://stza.co/+xGG2-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Suns
<2018-04-25 Wed 17:05-20:05>
:PROPERTIES:
:ID:       WpEDg_UxzGQhnErgNFYpTZFc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Suns BlueClaws @ Suns

Follow on MiLB First Pitch  https //stza.co/+xGG3-2d

Shop  https //stza.co/+xGG3-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Suns
END:VALARM
DTSTART:20180425T220500Z
DTEND:20180426T010500Z
UID:WpEDg_UxzGQhnErgNFYpTZFc@stanza.co
SUMMARY:BlueClaws @ Suns
DESCRIPTION:BlueClaws @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xGG3-2d\n\nShop: https://stza.co/+xGG3-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Suns
<2018-04-26 Thu 17:05-20:05>
:PROPERTIES:
:ID:       0q2I_TC6sS-FyuQlPKZmcbsr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Suns BlueClaws @ Suns

Follow on MiLB First Pitch  https //stza.co/+xF87-2_

Shop  https //stza.co/+xF87-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Suns
END:VALARM
DTSTART:20180426T220500Z
DTEND:20180427T010500Z
UID:0q2I_TC6sS-FyuQlPKZmcbsr@stanza.co
SUMMARY:BlueClaws @ Suns
DESCRIPTION:BlueClaws @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xF87-2_\n\nShop: https://stza.co/+xF87-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Intimidators
<2018-04-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       0Wa8wjWIG-USLnnYKVByt0_H@stanza.co
:LOCATION: Stranger Things Night With Retro Trucker Hats
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Intimidators The BlueClaws are hosting their first Stranger Things Night, which includes a Retro Trucker Hat for the first 1,500 fans.

The BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. 

Follow on MiLB First Pitch  https //stza.co/+vNTV-1t

Shop  https //stza.co/+vNTV-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Intimidators
END:VALARM
DTSTART:20180427T230500Z
DTEND:20180428T020500Z
UID:0Wa8wjWIG-USLnnYKVByt0_H@stanza.co
SUMMARY:BlueClaws vs. Intimidators
DESCRIPTION:The BlueClaws are hosting their first Stranger Things Night, which includes a Retro Trucker Hat for the first 1,500 fans.\n\nThe BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. \n\nFollow on MiLB First Pitch: https://stza.co/+vNTV-1t\n\nShop: https://stza.co/+vNTV-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stranger Things Night With Retro Trucker Hats
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Intimidators
<2018-04-28 Sat 15:05-18:05>
:PROPERTIES:
:ID:       a2HFyNP5nEqPHiAx_g5zXfej@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Intimidators BlueClaws vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+vNTX-1Y

Shop  https //stza.co/+vNTX-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Intimidators
END:VALARM
DTSTART:20180428T200500Z
DTEND:20180428T230500Z
UID:a2HFyNP5nEqPHiAx_g5zXfej@stanza.co
SUMMARY:BlueClaws vs. Intimidators
DESCRIPTION:BlueClaws vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+vNTX-1Y\n\nShop: https://stza.co/+vNTX-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Intimidators
<2018-04-29 Sun 12:05-15:05>
:PROPERTIES:
:ID:       lhcUw-NxNzP3XzXxuBXbLk2P@stanza.co
:LOCATION: Bring the family to the park for our Kids Eat Free game
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Intimidators Kids Eat Free at every Sunday BlueClaws home game thanks to ShopRite. Kids 12 and under receive a hot dog, chips and soda. 

Follow on MiLB First Pitch  https //stza.co/+vNTY-2w

Shop  https //stza.co/+vNTY-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Intimidators
END:VALARM
DTSTART:20180429T170500Z
DTEND:20180429T200500Z
UID:lhcUw-NxNzP3XzXxuBXbLk2P@stanza.co
SUMMARY:BlueClaws vs. Intimidators
DESCRIPTION:Kids Eat Free at every Sunday BlueClaws home game thanks to ShopRite. Kids 12 and under receive a hot dog, chips and soda. \n\nFollow on MiLB First Pitch: https://stza.co/+vNTY-2w\n\nShop: https://stza.co/+vNTY-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Bring the family to the park for our Kids Eat Free game
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Braves
<2018-05-01 Tue 18:00-21:00>
:PROPERTIES:
:ID:       mMxfkayC_VbxbqmdJYvGlqTh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Braves BlueClaws @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNVS-1R

Shop  https //stza.co/+vNVS-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Braves
END:VALARM
DTSTART:20180501T230000Z
DTEND:20180502T020000Z
UID:mMxfkayC_VbxbqmdJYvGlqTh@stanza.co
SUMMARY:BlueClaws @ Braves
DESCRIPTION:BlueClaws @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNVS-1R\n\nShop: https://stza.co/+vNVS-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Braves
<2018-05-02 Wed 18:00-21:00>
:PROPERTIES:
:ID:       tHMLmMnN_idUwF6CMhhJRhnl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Braves BlueClaws @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNVT-1c

Shop  https //stza.co/+vNVT-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Braves
END:VALARM
DTSTART:20180502T230000Z
DTEND:20180503T020000Z
UID:tHMLmMnN_idUwF6CMhhJRhnl@stanza.co
SUMMARY:BlueClaws @ Braves
DESCRIPTION:BlueClaws @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNVT-1c\n\nShop: https://stza.co/+vNVT-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Braves
<2018-05-03 Thu 09:30-12:30>
:PROPERTIES:
:ID:       T4bfBXngP28Kf7HohqpRrxL0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Braves BlueClaws @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNVU-3f

Shop  https //stza.co/+vNVU-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Braves
END:VALARM
DTSTART:20180503T143000Z
DTEND:20180503T173000Z
UID:T4bfBXngP28Kf7HohqpRrxL0@stanza.co
SUMMARY:BlueClaws @ Braves
DESCRIPTION:BlueClaws @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNVU-3f\n\nShop: https://stza.co/+vNVU-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Fireflies
<2018-05-04 Fri 18:05-21:05>
:PROPERTIES:
:ID:       ryWgkhOjOduUCUDxB1SX6Ez7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Fireflies BlueClaws @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBXs-$

Shop  https //stza.co/+xBXs-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Fireflies
END:VALARM
DTSTART:20180504T230500Z
DTEND:20180505T020500Z
UID:ryWgkhOjOduUCUDxB1SX6Ez7@stanza.co
SUMMARY:BlueClaws @ Fireflies
DESCRIPTION:BlueClaws @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBXs-$\n\nShop: https://stza.co/+xBXs-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Fireflies
<2018-05-05 Sat 17:05-20:05>
:PROPERTIES:
:ID:       gpdJ1L8jexBlnt_IGKGdT7cr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Fireflies BlueClaws @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBXy-t

Shop  https //stza.co/+xBXy-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Fireflies
END:VALARM
DTSTART:20180505T220500Z
DTEND:20180506T010500Z
UID:gpdJ1L8jexBlnt_IGKGdT7cr@stanza.co
SUMMARY:BlueClaws @ Fireflies
DESCRIPTION:BlueClaws @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBXy-t\n\nShop: https://stza.co/+xBXy-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Fireflies
<2018-05-06 Sun 13:05-16:05>
:PROPERTIES:
:ID:       jzx4FddpegniTdaZKQMgk08-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Fireflies BlueClaws @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xWNV-n

Shop  https //stza.co/+xWNV-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Fireflies
END:VALARM
DTSTART:20180506T180500Z
DTEND:20180506T210500Z
UID:jzx4FddpegniTdaZKQMgk08-@stanza.co
SUMMARY:BlueClaws @ Fireflies
DESCRIPTION:BlueClaws @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xWNV-n\n\nShop: https://stza.co/+xWNV-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Fireflies
<2018-05-07 Mon 10:05-13:05>
:PROPERTIES:
:ID:       3gGJgzOOEsq8E1kdEEWAiIHg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Fireflies BlueClaws @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xWNW-S

Shop  https //stza.co/+xWNW-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Fireflies
END:VALARM
DTSTART:20180507T150500Z
DTEND:20180507T180500Z
UID:3gGJgzOOEsq8E1kdEEWAiIHg@stanza.co
SUMMARY:BlueClaws @ Fireflies
DESCRIPTION:BlueClaws @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xWNW-S\n\nShop: https://stza.co/+xWNW-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. RiverDogs
<2018-05-09 Wed 17:35-20:35>
:PROPERTIES:
:ID:       qzsVniFpHe2SECFwKII_WB37@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BlueClaws vs. RiverDogs BlueClaws vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNT$-1V

Shop  https //stza.co/+vNT$-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. RiverDogs
END:VALARM
DTSTART:20180509T223500Z
DTEND:20180510T013500Z
UID:qzsVniFpHe2SECFwKII_WB37@stanza.co
SUMMARY:BlueClaws vs. RiverDogs
DESCRIPTION:BlueClaws vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNT$-1V\n\nShop: https://stza.co/+vNT$-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. RiverDogs
<2018-05-10 Thu 17:35-20:35>
:PROPERTIES:
:ID:       CFG95ulKW9vk0rr0rt9nD0pn@stanza.co
:LOCATION: Thirsty Thursday
:STATUS:   CONFIRMED
:END:

BlueClaws vs. RiverDogs Dollar beer and soda plus great wings as part of Thirsty Thursday, every Thursday at FirstEnergy Park. 

Follow on MiLB First Pitch  https //stza.co/+vNU1-18

Shop  https //stza.co/+vNU1-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. RiverDogs
END:VALARM
DTSTART:20180510T223500Z
DTEND:20180511T013500Z
UID:CFG95ulKW9vk0rr0rt9nD0pn@stanza.co
SUMMARY:BlueClaws vs. RiverDogs
DESCRIPTION:Dollar beer and soda plus great wings as part of Thirsty Thursday, every Thursday at FirstEnergy Park. \n\nFollow on MiLB First Pitch: https://stza.co/+vNU1-18\n\nShop: https://stza.co/+vNU1-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursday
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. RiverDogs
<2018-05-11 Fri 18:05-21:05>
:PROPERTIES:
:ID:       39IDLpteKKudtqnEU1tPdmLg@stanza.co
:LOCATION: Jurassic Ballpark
:STATUS:   CONFIRMED
:END:

BlueClaws vs. RiverDogs The BlueClaws go back in time to the era of dinosaurs for Jurassic Ballpark Night.

The BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. 

Follow on MiLB First Pitch  https //stza.co/+vNU3-2q

Shop  https //stza.co/+vNU3-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. RiverDogs
END:VALARM
DTSTART:20180511T230500Z
DTEND:20180512T020500Z
UID:39IDLpteKKudtqnEU1tPdmLg@stanza.co
SUMMARY:BlueClaws vs. RiverDogs
DESCRIPTION:The BlueClaws go back in time to the era of dinosaurs for Jurassic Ballpark Night.\n\nThe BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. \n\nFollow on MiLB First Pitch: https://stza.co/+vNU3-2q\n\nShop: https://stza.co/+vNU3-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Jurassic Ballpark
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Power
<2018-05-12 Sat 15:05-18:05>
:PROPERTIES:
:ID:       LhOV0dWCkuzTWbToQjccdlBk@stanza.co
:LOCATION: Bark in the Park With Collapsible Dog Bowls
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Power The annual Bark in the Park celebration takes place today beginning at 1 pm on the Great Lawn. Plus, we have a special Platinum item, a Collapsible Dog Bowl. This item can be your free Mini Plan Gift. For more information on BlueClaws Mini Plans, visit BlueClaws.com/TicketPlans. 

Follow on MiLB First Pitch  https //stza.co/+vNU5-d

Shop  https //stza.co/+vNU5-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Power
END:VALARM
DTSTART:20180512T200500Z
DTEND:20180512T230500Z
UID:LhOV0dWCkuzTWbToQjccdlBk@stanza.co
SUMMARY:BlueClaws vs. Power
DESCRIPTION:The annual Bark in the Park celebration takes place today beginning at 1 pm on the Great Lawn. Plus, we have a special Platinum item, a Collapsible Dog Bowl. This item can be your free Mini Plan Gift. For more information on BlueClaws Mini Plans, visit BlueClaws.com/TicketPlans. \n\nFollow on MiLB First Pitch: https://stza.co/+vNU5-d\n\nShop: https://stza.co/+vNU5-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Bark in the Park With Collapsible Dog Bowls
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Power
<2018-05-13 Sun 12:05-15:05>
:PROPERTIES:
:ID:       9iTsk3FQ5wkUEr-3iX59VODu@stanza.co
:LOCATION: Bring the family to the park for our Kids Eat Free game
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Power Kids Eat Free at every Sunday BlueClaws home game thanks to ShopRite. Kids 12 and under receive a hot dog, chips and soda. 

Follow on MiLB First Pitch  https //stza.co/+vNU7-2c

Shop  https //stza.co/+vNU7-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Power
END:VALARM
DTSTART:20180513T170500Z
DTEND:20180513T200500Z
UID:9iTsk3FQ5wkUEr-3iX59VODu@stanza.co
SUMMARY:BlueClaws vs. Power
DESCRIPTION:Kids Eat Free at every Sunday BlueClaws home game thanks to ShopRite. Kids 12 and under receive a hot dog, chips and soda. \n\nFollow on MiLB First Pitch: https://stza.co/+vNU7-2c\n\nShop: https://stza.co/+vNU7-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Bring the family to the park for our Kids Eat Free game
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Power
<2018-05-14 Mon 17:35-20:35>
:PROPERTIES:
:ID:       PYo1LPTWllxilOzHtgea0cOa@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Power BlueClaws vs. Power

Follow on MiLB First Pitch  https //stza.co/+vNU9-W

Shop  https //stza.co/+vNU9-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Power
END:VALARM
DTSTART:20180514T223500Z
DTEND:20180515T013500Z
UID:PYo1LPTWllxilOzHtgea0cOa@stanza.co
SUMMARY:BlueClaws vs. Power
DESCRIPTION:BlueClaws vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+vNU9-W\n\nShop: https://stza.co/+vNU9-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Power
<2018-05-15 Tue 17:35-20:35>
:PROPERTIES:
:ID:       nA6OD32p2l43-8htwf3CxmoP@stanza.co
:LOCATION: Silver Sluggers Tuesday
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Power It's Silver Sluggers Tuesday, where member of the BlueClaws Silver Sluggers Club eat free and receive a hot dog, bag of chips, and a soda. 

Follow on MiLB First Pitch  https //stza.co/+vNUb-1Z

Shop  https //stza.co/+vNUb-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Power
END:VALARM
DTSTART:20180515T223500Z
DTEND:20180516T013500Z
UID:nA6OD32p2l43-8htwf3CxmoP@stanza.co
SUMMARY:BlueClaws vs. Power
DESCRIPTION:It's Silver Sluggers Tuesday, where member of the BlueClaws Silver Sluggers Club eat free and receive a hot dog, bag of chips, and a soda. \n\nFollow on MiLB First Pitch: https://stza.co/+vNUb-1Z\n\nShop: https://stza.co/+vNUb-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Silver Sluggers Tuesday
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Grasshoppers
<2018-05-17 Thu 18:00-21:00>
:PROPERTIES:
:ID:       Wj9x57cl-NfBaDUCmO7Do1v-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Grasshoppers BlueClaws @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizH-3e

Shop  https //stza.co/+wizH-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Grasshoppers
END:VALARM
DTSTART:20180517T230000Z
DTEND:20180518T020000Z
UID:Wj9x57cl-NfBaDUCmO7Do1v-@stanza.co
SUMMARY:BlueClaws @ Grasshoppers
DESCRIPTION:BlueClaws @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizH-3e\n\nShop: https://stza.co/+wizH-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Grasshoppers
<2018-05-18 Fri 18:00-21:00>
:PROPERTIES:
:ID:       7HwZFzpoNwcASx0fBH1Esxti@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Grasshoppers BlueClaws @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizI-3p

Shop  https //stza.co/+wizI-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Grasshoppers
END:VALARM
DTSTART:20180518T230000Z
DTEND:20180519T020000Z
UID:7HwZFzpoNwcASx0fBH1Esxti@stanza.co
SUMMARY:BlueClaws @ Grasshoppers
DESCRIPTION:BlueClaws @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizI-3p\n\nShop: https://stza.co/+wizI-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Grasshoppers
<2018-05-19 Sat 18:00-21:00>
:PROPERTIES:
:ID:       U1Dw1OjvdVw7kDfgeYzzKL5z@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Grasshoppers BlueClaws @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizJ-1g

Shop  https //stza.co/+wizJ-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Grasshoppers
END:VALARM
DTSTART:20180519T230000Z
DTEND:20180520T020000Z
UID:U1Dw1OjvdVw7kDfgeYzzKL5z@stanza.co
SUMMARY:BlueClaws @ Grasshoppers
DESCRIPTION:BlueClaws @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizJ-1g\n\nShop: https://stza.co/+wizJ-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Grasshoppers
<2018-05-20 Sun 13:00-16:00>
:PROPERTIES:
:ID:       lvC78nht5QQtKHWeTvZQQ2n-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Grasshoppers BlueClaws @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizK-20

Shop  https //stza.co/+wizK-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Grasshoppers
END:VALARM
DTSTART:20180520T180000Z
DTEND:20180520T210000Z
UID:lvC78nht5QQtKHWeTvZQQ2n-@stanza.co
SUMMARY:BlueClaws @ Grasshoppers
DESCRIPTION:BlueClaws @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizK-20\n\nShop: https://stza.co/+wizK-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Suns
<2018-05-21 Mon 17:35-20:35>
:PROPERTIES:
:ID:       bB4pxgmkyNxhCJr-gmQ8WB2w@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Suns BlueClaws vs. Suns

Follow on MiLB First Pitch  https //stza.co/+vNUd-1Y

Shop  https //stza.co/+vNUd-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Suns
END:VALARM
DTSTART:20180521T223500Z
DTEND:20180522T013500Z
UID:bB4pxgmkyNxhCJr-gmQ8WB2w@stanza.co
SUMMARY:BlueClaws vs. Suns
DESCRIPTION:BlueClaws vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+vNUd-1Y\n\nShop: https://stza.co/+vNUd-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Suns
<2018-05-22 Tue 17:35-20:35>
:PROPERTIES:
:ID:       y8m-o0eap3N5BIxypteFmOgx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Suns BlueClaws vs. Suns

Follow on MiLB First Pitch  https //stza.co/+vNUe-2x

Shop  https //stza.co/+vNUe-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Suns
END:VALARM
DTSTART:20180522T223500Z
DTEND:20180523T013500Z
UID:y8m-o0eap3N5BIxypteFmOgx@stanza.co
SUMMARY:BlueClaws vs. Suns
DESCRIPTION:BlueClaws vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+vNUe-2x\n\nShop: https://stza.co/+vNUe-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Suns
<2018-05-23 Wed 10:05-13:05>
:PROPERTIES:
:ID:       1gkeP4Vl6LN5BubCG1lHxPPG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Suns BlueClaws vs. Suns

Follow on MiLB First Pitch  https //stza.co/+vNUh-3V

Shop  https //stza.co/+vNUh-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Suns
END:VALARM
DTSTART:20180523T150500Z
DTEND:20180523T180500Z
UID:1gkeP4Vl6LN5BubCG1lHxPPG@stanza.co
SUMMARY:BlueClaws vs. Suns
DESCRIPTION:BlueClaws vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+vNUh-3V\n\nShop: https://stza.co/+vNUh-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Suns
<2018-05-24 Thu 17:35-20:35>
:PROPERTIES:
:ID:       -8zvecrha6ZXaS100C2Y4LiD@stanza.co
:LOCATION: Thirsty Thursday
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Suns Dollar beer and soda plus great wings as part of Thirsty Thursday, every Thursday at FirstEnergy Park. 

Follow on MiLB First Pitch  https //stza.co/+vNUj-18

Shop  https //stza.co/+vNUj-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Suns
END:VALARM
DTSTART:20180524T223500Z
DTEND:20180525T013500Z
UID:-8zvecrha6ZXaS100C2Y4LiD@stanza.co
SUMMARY:BlueClaws vs. Suns
DESCRIPTION:Dollar beer and soda plus great wings as part of Thirsty Thursday, every Thursday at FirstEnergy Park. \n\nFollow on MiLB First Pitch: https://stza.co/+vNUj-18\n\nShop: https://stza.co/+vNUj-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursday
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Shorebirds
<2018-05-25 Fri 18:05-21:05>
:PROPERTIES:
:ID:       g85f9l5utkLbRg_C0EuOnXme@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Shorebirds BlueClaws @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHSw-1h

Shop  https //stza.co/+wHSw-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Shorebirds
END:VALARM
DTSTART:20180525T230500Z
DTEND:20180526T020500Z
UID:g85f9l5utkLbRg_C0EuOnXme@stanza.co
SUMMARY:BlueClaws @ Shorebirds
DESCRIPTION:BlueClaws @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHSw-1h\n\nShop: https://stza.co/+wHSw-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Shorebirds
<2018-05-26 Sat 18:05-21:05>
:PROPERTIES:
:ID:       R7Kuy1xiNHXrBTduXW8YW6lz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Shorebirds BlueClaws @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHSx-2r

Shop  https //stza.co/+wHSx-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Shorebirds
END:VALARM
DTSTART:20180526T230500Z
DTEND:20180527T020500Z
UID:R7Kuy1xiNHXrBTduXW8YW6lz@stanza.co
SUMMARY:BlueClaws @ Shorebirds
DESCRIPTION:BlueClaws @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHSx-2r\n\nShop: https://stza.co/+wHSx-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Shorebirds
<2018-05-27 Sun 13:05-16:05>
:PROPERTIES:
:ID:       zTUCP2pn_f8vTZAnBUKDqlpw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Shorebirds BlueClaws @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHSy-1e

Shop  https //stza.co/+wHSy-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Shorebirds
END:VALARM
DTSTART:20180527T180500Z
DTEND:20180527T210500Z
UID:zTUCP2pn_f8vTZAnBUKDqlpw@stanza.co
SUMMARY:BlueClaws @ Shorebirds
DESCRIPTION:BlueClaws @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHSy-1e\n\nShop: https://stza.co/+wHSy-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Shorebirds
<2018-05-28 Mon 13:05-16:05>
:PROPERTIES:
:ID:       XmJ4460po5JqQxHSN6CM9AVL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Shorebirds BlueClaws @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHSz-1f

Shop  https //stza.co/+wHSz-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Shorebirds
END:VALARM
DTSTART:20180528T180500Z
DTEND:20180528T210500Z
UID:XmJ4460po5JqQxHSN6CM9AVL@stanza.co
SUMMARY:BlueClaws @ Shorebirds
DESCRIPTION:BlueClaws @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHSz-1f\n\nShop: https://stza.co/+wHSz-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Grasshoppers
<2018-05-29 Tue 17:35-20:35>
:PROPERTIES:
:ID:       69m66kc9KOM3ycwAzgh0tD7_@stanza.co
:LOCATION: Silver Sluggers Tuesday
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Grasshoppers It's Silver Sluggers Tuesday, where member of the BlueClaws Silver Sluggers Club eat free and receive a hot dog, bag of chips, and a soda. 

Follow on MiLB First Pitch  https //stza.co/+vNUl-19

Shop  https //stza.co/+vNUl-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Grasshoppers
END:VALARM
DTSTART:20180529T223500Z
DTEND:20180530T013500Z
UID:69m66kc9KOM3ycwAzgh0tD7_@stanza.co
SUMMARY:BlueClaws vs. Grasshoppers
DESCRIPTION:It's Silver Sluggers Tuesday, where member of the BlueClaws Silver Sluggers Club eat free and receive a hot dog, bag of chips, and a soda. \n\nFollow on MiLB First Pitch: https://stza.co/+vNUl-19\n\nShop: https://stza.co/+vNUl-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Silver Sluggers Tuesday
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Grasshoppers
<2018-05-30 Wed 10:05-13:05>
:PROPERTIES:
:ID:       HmU_Ed8BMk2mPTHt7zNL00iw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Grasshoppers BlueClaws vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+vNUn-1C

Shop  https //stza.co/+vNUn-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Grasshoppers
END:VALARM
DTSTART:20180530T150500Z
DTEND:20180530T180500Z
UID:HmU_Ed8BMk2mPTHt7zNL00iw@stanza.co
SUMMARY:BlueClaws vs. Grasshoppers
DESCRIPTION:BlueClaws vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+vNUn-1C\n\nShop: https://stza.co/+vNUn-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Grasshoppers
<2018-05-31 Thu 17:35-20:35>
:PROPERTIES:
:ID:       3G_cMpX0P5fAQdeqD58tuWm3@stanza.co
:LOCATION: Thirsty Thursday
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Grasshoppers Dollar beer and soda plus great wings as part of Thirsty Thursday, every Thursday at FirstEnergy Park. 

Follow on MiLB First Pitch  https //stza.co/+vNUo-2x

Shop  https //stza.co/+vNUo-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Grasshoppers
END:VALARM
DTSTART:20180531T223500Z
DTEND:20180601T013500Z
UID:3G_cMpX0P5fAQdeqD58tuWm3@stanza.co
SUMMARY:BlueClaws vs. Grasshoppers
DESCRIPTION:Dollar beer and soda plus great wings as part of Thirsty Thursday, every Thursday at FirstEnergy Park. \n\nFollow on MiLB First Pitch: https://stza.co/+vNUo-2x\n\nShop: https://stza.co/+vNUo-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursday
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Crawdads
<2018-06-01 Fri 18:05-21:05>
:PROPERTIES:
:ID:       5rtjt6Y1OKjjMUPU6swWFvNh@stanza.co
:LOCATION: Comic-Con Night With Player Selection Shirt
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Crawdads As part of BlueClaws Comic-Con Night, we'll welcome in special Marvel characters and we also have an 8-Bit Player Selection Shirt available too as a Platinum Ticket Option. This item can be your free Mini Plan Gift. For more information on BlueClaws Mini Plans, visit BlueClaws.com/TicketPlans.

The BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. 

Follow on MiLB First Pitch  https //stza.co/+vNUr-1s

Shop  https //stza.co/+vNUr-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Crawdads
END:VALARM
DTSTART:20180601T230500Z
DTEND:20180602T020500Z
UID:5rtjt6Y1OKjjMUPU6swWFvNh@stanza.co
SUMMARY:BlueClaws vs. Crawdads
DESCRIPTION:As part of BlueClaws Comic-Con Night, we'll welcome in special Marvel characters and we also have an 8-Bit Player Selection Shirt available too as a Platinum Ticket Option. This item can be your free Mini Plan Gift. For more information on BlueClaws Mini Plans, visit BlueClaws.com/TicketPlans.\n\nThe BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. \n\nFollow on MiLB First Pitch: https://stza.co/+vNUr-1s\n\nShop: https://stza.co/+vNUr-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Comic-Con Night With Player Selection Shirt
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Crawdads
<2018-06-02 Sat 18:05-21:05>
:PROPERTIES:
:ID:       fOBH38k8wFkqy9ilft5sDC42@stanza.co
:LOCATION: Battle of the Badges Night
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Crawdads Battle of the Badges Night is the BlueClaws combination of Firefighter Night and Law Enforcement Night. To bring out a group, contact Ryan Shaughnessy at 732-901-7000 ext 106.

The BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. 

Follow on MiLB First Pitch  https //stza.co/+vNUs-3w

Shop  https //stza.co/+vNUs-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Crawdads
END:VALARM
DTSTART:20180602T230500Z
DTEND:20180603T020500Z
UID:fOBH38k8wFkqy9ilft5sDC42@stanza.co
SUMMARY:BlueClaws vs. Crawdads
DESCRIPTION:Battle of the Badges Night is the BlueClaws combination of Firefighter Night and Law Enforcement Night. To bring out a group, contact Ryan Shaughnessy at 732-901-7000 ext 106.\n\nThe BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. \n\nFollow on MiLB First Pitch: https://stza.co/+vNUs-3w\n\nShop: https://stza.co/+vNUs-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Battle of the Badges Night
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Crawdads
<2018-06-03 Sun 12:05-15:05>
:PROPERTIES:
:ID:       o0M-vtXmsFSzCNO05jd4wj0f@stanza.co
:LOCATION: Bring the family to the park for our Kids Eat Free game
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Crawdads Kids Eat Free at every Sunday BlueClaws home game thanks to ShopRite. Kids 12 and under receive a hot dog, chips and soda. 

Follow on MiLB First Pitch  https //stza.co/+vNUv-1F

Shop  https //stza.co/+vNUv-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Crawdads
END:VALARM
DTSTART:20180603T170500Z
DTEND:20180603T200500Z
UID:o0M-vtXmsFSzCNO05jd4wj0f@stanza.co
SUMMARY:BlueClaws vs. Crawdads
DESCRIPTION:Kids Eat Free at every Sunday BlueClaws home game thanks to ShopRite. Kids 12 and under receive a hot dog, chips and soda. \n\nFollow on MiLB First Pitch: https://stza.co/+vNUv-1F\n\nShop: https://stza.co/+vNUv-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Bring the family to the park for our Kids Eat Free game
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Suns
<2018-06-05 Tue 18:05-21:05>
:PROPERTIES:
:ID:       fK8lwhsCOPda4Y7BHhGFzAcd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Suns BlueClaws @ Suns

Follow on MiLB First Pitch  https //stza.co/+xF88-1I

Shop  https //stza.co/+xF88-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Suns
END:VALARM
DTSTART:20180605T230500Z
DTEND:20180606T020500Z
UID:fK8lwhsCOPda4Y7BHhGFzAcd@stanza.co
SUMMARY:BlueClaws @ Suns
DESCRIPTION:BlueClaws @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xF88-1I\n\nShop: https://stza.co/+xF88-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Suns
<2018-06-06 Wed 18:05-21:05>
:PROPERTIES:
:ID:       3Z5QwR5VQj_Kmjy25DfwU1wo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Suns BlueClaws @ Suns

Follow on MiLB First Pitch  https //stza.co/+xF89-P

Shop  https //stza.co/+xF89-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Suns
END:VALARM
DTSTART:20180606T230500Z
DTEND:20180607T020500Z
UID:3Z5QwR5VQj_Kmjy25DfwU1wo@stanza.co
SUMMARY:BlueClaws @ Suns
DESCRIPTION:BlueClaws @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xF89-P\n\nShop: https://stza.co/+xF89-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Suns
<2018-06-07 Thu 18:05-21:05>
:PROPERTIES:
:ID:       jTi_NUlKf8fkf-VQ-CApHac3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Suns BlueClaws @ Suns

Follow on MiLB First Pitch  https //stza.co/+xF8a-d

Shop  https //stza.co/+xF8a-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Suns
END:VALARM
DTSTART:20180607T230500Z
DTEND:20180608T020500Z
UID:jTi_NUlKf8fkf-VQ-CApHac3@stanza.co
SUMMARY:BlueClaws @ Suns
DESCRIPTION:BlueClaws @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xF8a-d\n\nShop: https://stza.co/+xF8a-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Grasshoppers
<2018-06-08 Fri 18:00-21:00>
:PROPERTIES:
:ID:       kXHtWlLHdw9pj1An27OAZYZS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Grasshoppers BlueClaws @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizL-2v

Shop  https //stza.co/+wizL-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Grasshoppers
END:VALARM
DTSTART:20180608T230000Z
DTEND:20180609T020000Z
UID:kXHtWlLHdw9pj1An27OAZYZS@stanza.co
SUMMARY:BlueClaws @ Grasshoppers
DESCRIPTION:BlueClaws @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizL-2v\n\nShop: https://stza.co/+wizL-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Grasshoppers
<2018-06-09 Sat 18:00-21:00>
:PROPERTIES:
:ID:       uS5B7bzge8-K96i8AqcPt-E7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Grasshoppers BlueClaws @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizM-2L

Shop  https //stza.co/+wizM-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Grasshoppers
END:VALARM
DTSTART:20180609T230000Z
DTEND:20180610T020000Z
UID:uS5B7bzge8-K96i8AqcPt-E7@stanza.co
SUMMARY:BlueClaws @ Grasshoppers
DESCRIPTION:BlueClaws @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizM-2L\n\nShop: https://stza.co/+wizM-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Grasshoppers
<2018-06-10 Sun 13:00-16:00>
:PROPERTIES:
:ID:       Iqnyi0vFC6LLYgQrpGFx9VEt@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Grasshoppers BlueClaws @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizN-1j

Shop  https //stza.co/+wizN-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Grasshoppers
END:VALARM
DTSTART:20180610T180000Z
DTEND:20180610T210000Z
UID:Iqnyi0vFC6LLYgQrpGFx9VEt@stanza.co
SUMMARY:BlueClaws @ Grasshoppers
DESCRIPTION:BlueClaws @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizN-1j\n\nShop: https://stza.co/+wizN-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Suns
<2018-06-11 Mon 18:05-21:05>
:PROPERTIES:
:ID:       cSzqj3mx9puB0kTuTrlQWADj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Suns BlueClaws vs. Suns

Follow on MiLB First Pitch  https //stza.co/+vNUx-c

Shop  https //stza.co/+vNUx-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Suns
END:VALARM
DTSTART:20180611T230500Z
DTEND:20180612T020500Z
UID:cSzqj3mx9puB0kTuTrlQWADj@stanza.co
SUMMARY:BlueClaws vs. Suns
DESCRIPTION:BlueClaws vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+vNUx-c\n\nShop: https://stza.co/+vNUx-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Suns
<2018-06-12 Tue 18:05-21:05>
:PROPERTIES:
:ID:       rz0z1CimAh8khbDKt7FWvTY2@stanza.co
:LOCATION: Silver Sluggers Tuesday
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Suns It's Silver Sluggers Tuesday, where member of the BlueClaws Silver Sluggers Club eat free and receive a hot dog, bag of chips, and a soda. 

Follow on MiLB First Pitch  https //stza.co/+vNUy-3p

Shop  https //stza.co/+vNUy-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Suns
END:VALARM
DTSTART:20180612T230500Z
DTEND:20180613T020500Z
UID:rz0z1CimAh8khbDKt7FWvTY2@stanza.co
SUMMARY:BlueClaws vs. Suns
DESCRIPTION:It's Silver Sluggers Tuesday, where member of the BlueClaws Silver Sluggers Club eat free and receive a hot dog, bag of chips, and a soda. \n\nFollow on MiLB First Pitch: https://stza.co/+vNUy-3p\n\nShop: https://stza.co/+vNUy-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Silver Sluggers Tuesday
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Suns
<2018-06-13 Wed 18:05-21:05>
:PROPERTIES:
:ID:       1ufCpGf3Tik9ofuGlDSkd-Le@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Suns BlueClaws vs. Suns

Follow on MiLB First Pitch  https //stza.co/+vNUA-3Y

Shop  https //stza.co/+vNUA-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Suns
END:VALARM
DTSTART:20180613T230500Z
DTEND:20180614T020500Z
UID:1ufCpGf3Tik9ofuGlDSkd-Le@stanza.co
SUMMARY:BlueClaws vs. Suns
DESCRIPTION:BlueClaws vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+vNUA-3Y\n\nShop: https://stza.co/+vNUA-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Suns
<2018-06-14 Thu 18:05-21:05>
:PROPERTIES:
:ID:       suZb-dyXLITqtMRCDCGkQ-F3@stanza.co
:LOCATION: Military Appreciation Night with Troop Supply Drive
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Suns It's Military Appreciation Night and the BlueClaws will be collecting troop supplies as part of the annual Troop Supply Drive. 

Dollar beer and soda plus great wings as part of Thirsty Thursday, every Thursday at FirstEnergy Park. 

Follow on MiLB First Pitch  https //stza.co/+vNUC-_

Shop  https //stza.co/+vNUC-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Suns
END:VALARM
DTSTART:20180614T230500Z
DTEND:20180615T020500Z
UID:suZb-dyXLITqtMRCDCGkQ-F3@stanza.co
SUMMARY:BlueClaws vs. Suns
DESCRIPTION:It's Military Appreciation Night and the BlueClaws will be collecting troop supplies as part of the annual Troop Supply Drive. \n\nDollar beer and soda plus great wings as part of Thirsty Thursday, every Thursday at FirstEnergy Park. \n\nFollow on MiLB First Pitch: https://stza.co/+vNUC-_\n\nShop: https://stza.co/+vNUC-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Military Appreciation Night with Troop Supply Drive
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Crawdads
<2018-06-15 Fri 18:05-21:05>
:PROPERTIES:
:ID:       qJz0Ddae9kFiQyEf7CIp7t8m@stanza.co
:LOCATION: BlueClaws Christmas Vacation With Truckster Ornament
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Crawdads BlueClaws Christmas Vacation Night includes a special Platinum Item, a BlueClaws Truckster Christmas Ornament. This item can be your free Mini Plan Gift. For more information on BlueClaws Mini Plans, visit BlueClaws.com/TicketPlans. 

The BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. 

Follow on MiLB First Pitch  https //stza.co/+vNUF-1l

Shop  https //stza.co/+vNUF-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Crawdads
END:VALARM
DTSTART:20180615T230500Z
DTEND:20180616T020500Z
UID:qJz0Ddae9kFiQyEf7CIp7t8m@stanza.co
SUMMARY:BlueClaws vs. Crawdads
DESCRIPTION:BlueClaws Christmas Vacation Night includes a special Platinum Item, a BlueClaws Truckster Christmas Ornament. This item can be your free Mini Plan Gift. For more information on BlueClaws Mini Plans, visit BlueClaws.com/TicketPlans. \n\nThe BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. \n\nFollow on MiLB First Pitch: https://stza.co/+vNUF-1l\n\nShop: https://stza.co/+vNUF-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:BlueClaws Christmas Vacation With Truckster Ornament
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Crawdads
<2018-06-16 Sat 18:05-21:05>
:PROPERTIES:
:ID:       7-WIj8g9c8LaJQGqPR6-_3zH@stanza.co
:LOCATION: Fireworks Spectacular
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Crawdads The BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. 

Follow on MiLB First Pitch  https //stza.co/+vNUG-2o

Shop  https //stza.co/+vNUG-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Crawdads
END:VALARM
DTSTART:20180616T230500Z
DTEND:20180617T020500Z
UID:7-WIj8g9c8LaJQGqPR6-_3zH@stanza.co
SUMMARY:BlueClaws vs. Crawdads
DESCRIPTION:The BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. \n\nFollow on MiLB First Pitch: https://stza.co/+vNUG-2o\n\nShop: https://stza.co/+vNUG-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Spectacular
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Crawdads
<2018-06-17 Sun 12:05-15:05>
:PROPERTIES:
:ID:       fZOjo-TwR_uWipUChXqVCQLu@stanza.co
:LOCATION: Bring the family to the park for our Kids Eat Free game
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Crawdads It's Father's Day at FirstEnergy Park and that means after the game, fathers and their children can play catch on the field. Plus, the first 1,000 fans 18 & older receive a BlueClaws Father's Day T-Shirt. 

Kids Eat Free at every Sunday BlueClaws home game thanks to ShopRite. Kids 12 and under receive a hot dog, chips and soda. 

Follow on MiLB First Pitch  https //stza.co/+vNUJ-10

Shop  https //stza.co/+vNUJ-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Crawdads
END:VALARM
DTSTART:20180617T170500Z
DTEND:20180617T200500Z
UID:fZOjo-TwR_uWipUChXqVCQLu@stanza.co
SUMMARY:BlueClaws vs. Crawdads
DESCRIPTION:It's Father's Day at FirstEnergy Park and that means after the game, fathers and their children can play catch on the field. Plus, the first 1,000 fans 18 & older receive a BlueClaws Father's Day T-Shirt. \n\nKids Eat Free at every Sunday BlueClaws home game thanks to ShopRite. Kids 12 and under receive a hot dog, chips and soda. \n\nFollow on MiLB First Pitch: https://stza.co/+vNUJ-10\n\nShop: https://stza.co/+vNUJ-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Bring the family to the park for our Kids Eat Free game
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Fireflies
<2018-06-21 Thu 18:05-21:05>
:PROPERTIES:
:ID:       u_2MX7dVP-ByIfSTGv1QYv3P@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Fireflies BlueClaws @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBXN-13

Shop  https //stza.co/+xBXN-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Fireflies
END:VALARM
DTSTART:20180621T230500Z
DTEND:20180622T020500Z
UID:u_2MX7dVP-ByIfSTGv1QYv3P@stanza.co
SUMMARY:BlueClaws @ Fireflies
DESCRIPTION:BlueClaws @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBXN-13\n\nShop: https://stza.co/+xBXN-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Fireflies
<2018-06-22 Fri 18:05-21:05>
:PROPERTIES:
:ID:       VdCTy04yAR-oivPA75hQOOOe@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Fireflies BlueClaws @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBXS-1X

Shop  https //stza.co/+xBXS-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Fireflies
END:VALARM
DTSTART:20180622T230500Z
DTEND:20180623T020500Z
UID:VdCTy04yAR-oivPA75hQOOOe@stanza.co
SUMMARY:BlueClaws @ Fireflies
DESCRIPTION:BlueClaws @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBXS-1X\n\nShop: https://stza.co/+xBXS-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Fireflies
<2018-06-23 Sat 17:05-20:05>
:PROPERTIES:
:ID:       d1L8r0fsbo-nJ87KP2r6rcM1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Fireflies BlueClaws @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBXX-e

Shop  https //stza.co/+xBXX-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Fireflies
END:VALARM
DTSTART:20180623T220500Z
DTEND:20180624T010500Z
UID:d1L8r0fsbo-nJ87KP2r6rcM1@stanza.co
SUMMARY:BlueClaws @ Fireflies
DESCRIPTION:BlueClaws @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBXX-e\n\nShop: https://stza.co/+xBXX-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Power
<2018-06-24 Sun 13:05-16:05>
:PROPERTIES:
:ID:       _qTq9TcPjC87j9615xPbRvc-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Power BlueClaws @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ4d-1x

Shop  https //stza.co/+xJ4d-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Power
END:VALARM
DTSTART:20180624T180500Z
DTEND:20180624T210500Z
UID:_qTq9TcPjC87j9615xPbRvc-@stanza.co
SUMMARY:BlueClaws @ Power
DESCRIPTION:BlueClaws @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ4d-1x\n\nShop: https://stza.co/+xJ4d-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Power
<2018-06-25 Mon 18:05-21:05>
:PROPERTIES:
:ID:       HF2wBnVH0o42EcJpLr7x5L_2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Power BlueClaws @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ4e-1b

Shop  https //stza.co/+xJ4e-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Power
END:VALARM
DTSTART:20180625T230500Z
DTEND:20180626T020500Z
UID:HF2wBnVH0o42EcJpLr7x5L_2@stanza.co
SUMMARY:BlueClaws @ Power
DESCRIPTION:BlueClaws @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ4e-1b\n\nShop: https://stza.co/+xJ4e-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Power
<2018-06-26 Tue 18:05-21:05>
:PROPERTIES:
:ID:       8y4ItR1gjUlK-NU0uQO_UHme@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Power BlueClaws @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ4f-2V

Shop  https //stza.co/+xJ4f-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Power
END:VALARM
DTSTART:20180626T230500Z
DTEND:20180627T020500Z
UID:8y4ItR1gjUlK-NU0uQO_UHme@stanza.co
SUMMARY:BlueClaws @ Power
DESCRIPTION:BlueClaws @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ4f-2V\n\nShop: https://stza.co/+xJ4f-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Suns
<2018-06-27 Wed 18:05-21:05>
:PROPERTIES:
:ID:       kxLe4OY3iTAZvjcWN7lpUNVn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Suns BlueClaws vs. Suns

Follow on MiLB First Pitch  https //stza.co/+vNUL-

Shop  https //stza.co/+vNUL-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Suns
END:VALARM
DTSTART:20180627T230500Z
DTEND:20180628T020500Z
UID:kxLe4OY3iTAZvjcWN7lpUNVn@stanza.co
SUMMARY:BlueClaws vs. Suns
DESCRIPTION:BlueClaws vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+vNUL-\n\nShop: https://stza.co/+vNUL-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Suns
<2018-06-28 Thu 18:05-21:05>
:PROPERTIES:
:ID:       woec7AIGzhLkP4Lvja69EE0V@stanza.co
:LOCATION: Thirsty Thursday
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Suns Dollar beer and soda plus great wings as part of Thirsty Thursday, every Thursday at FirstEnergy Park. 

Follow on MiLB First Pitch  https //stza.co/+vNUN-33

Shop  https //stza.co/+vNUN-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Suns
END:VALARM
DTSTART:20180628T230500Z
DTEND:20180629T020500Z
UID:woec7AIGzhLkP4Lvja69EE0V@stanza.co
SUMMARY:BlueClaws vs. Suns
DESCRIPTION:Dollar beer and soda plus great wings as part of Thirsty Thursday, every Thursday at FirstEnergy Park. \n\nFollow on MiLB First Pitch: https://stza.co/+vNUN-33\n\nShop: https://stza.co/+vNUN-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursday
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Suns
<2018-06-29 Fri 18:05-21:05>
:PROPERTIES:
:ID:       HAPsLZuuiFIWeim86N34v224@stanza.co
:LOCATION: Star Wars Night With ChewBuster Bobble
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Suns It's Star Wars Night and we're celebrating with special character appearances and a ChewBuster Bobble, with friend, Platinum Ticket Item. This item can be your free Mini Plan Gift. For more information on BlueClaws Mini Plans, visit BlueClaws.com/TicketPlans. 

The BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. 

Follow on MiLB First Pitch  https //stza.co/+vNUO-1D

Shop  https //stza.co/+vNUO-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Suns
END:VALARM
DTSTART:20180629T230500Z
DTEND:20180630T020500Z
UID:HAPsLZuuiFIWeim86N34v224@stanza.co
SUMMARY:BlueClaws vs. Suns
DESCRIPTION:It's Star Wars Night and we're celebrating with special character appearances and a ChewBuster Bobble, with friend, Platinum Ticket Item. This item can be your free Mini Plan Gift. For more information on BlueClaws Mini Plans, visit BlueClaws.com/TicketPlans. \n\nThe BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. \n\nFollow on MiLB First Pitch: https://stza.co/+vNUO-1D\n\nShop: https://stza.co/+vNUO-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Star Wars Night With ChewBuster Bobble
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Shorebirds
<2018-06-30 Sat 18:05-21:05>
:PROPERTIES:
:ID:       6pIzytWIR7laU_SZvH67CNQz@stanza.co
:LOCATION: Fireworks Spectacular
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Shorebirds The BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. 

Follow on MiLB First Pitch  https //stza.co/+vNUQ-1e

Shop  https //stza.co/+vNUQ-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Shorebirds
END:VALARM
DTSTART:20180630T230500Z
DTEND:20180701T020500Z
UID:6pIzytWIR7laU_SZvH67CNQz@stanza.co
SUMMARY:BlueClaws vs. Shorebirds
DESCRIPTION:The BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. \n\nFollow on MiLB First Pitch: https://stza.co/+vNUQ-1e\n\nShop: https://stza.co/+vNUQ-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Spectacular
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Shorebirds
<2018-07-01 Sun 12:05-15:05>
:PROPERTIES:
:ID:       ut-8X7ofWFVSLXnjp6VpNGve@stanza.co
:LOCATION: Bring the family to the park for our Kids Eat Free game
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Shorebirds The BlueClaws Parrothead Party will include live music from the Parrotbeach Band, special promotions, and other fun.

Kids Eat Free at every Sunday BlueClaws home game thanks to ShopRite. Kids 12 and under receive a hot dog, chips and soda. 

Follow on MiLB First Pitch  https //stza.co/+vNUT-29

Shop  https //stza.co/+vNUT-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Shorebirds
END:VALARM
DTSTART:20180701T170500Z
DTEND:20180701T200500Z
UID:ut-8X7ofWFVSLXnjp6VpNGve@stanza.co
SUMMARY:BlueClaws vs. Shorebirds
DESCRIPTION:The BlueClaws Parrothead Party will include live music from the Parrotbeach Band, special promotions, and other fun.\n\nKids Eat Free at every Sunday BlueClaws home game thanks to ShopRite. Kids 12 and under receive a hot dog, chips and soda. \n\nFollow on MiLB First Pitch: https://stza.co/+vNUT-29\n\nShop: https://stza.co/+vNUT-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Bring the family to the park for our Kids Eat Free game
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Shorebirds
<2018-07-02 Mon 18:05-21:05>
:PROPERTIES:
:ID:       a7Uu0HIMVgXNYEF0xVM78R9n@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Shorebirds BlueClaws vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+vNUU-16

Shop  https //stza.co/+vNUU-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Shorebirds
END:VALARM
DTSTART:20180702T230500Z
DTEND:20180703T020500Z
UID:a7Uu0HIMVgXNYEF0xVM78R9n@stanza.co
SUMMARY:BlueClaws vs. Shorebirds
DESCRIPTION:BlueClaws vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+vNUU-16\n\nShop: https://stza.co/+vNUU-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Shorebirds
<2018-07-03 Tue 18:05-21:05>
:PROPERTIES:
:ID:       4vnTi47A9ADryq2wsf_StfSC@stanza.co
:LOCATION: Independence Day Fireworks Extravaganza
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Shorebirds It's our biggest fireworks show of the year! 

It's Silver Sluggers Tuesday, where member of the BlueClaws Silver Sluggers Club eat free and receive a hot dog, bag of chips, and a soda. 

Follow on MiLB First Pitch  https //stza.co/+vNUW-3d

Shop  https //stza.co/+vNUW-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Shorebirds
END:VALARM
DTSTART:20180703T230500Z
DTEND:20180704T020500Z
UID:4vnTi47A9ADryq2wsf_StfSC@stanza.co
SUMMARY:BlueClaws vs. Shorebirds
DESCRIPTION:It's our biggest fireworks show of the year! \n\nIt's Silver Sluggers Tuesday, where member of the BlueClaws Silver Sluggers Club eat free and receive a hot dog, bag of chips, and a soda. \n\nFollow on MiLB First Pitch: https://stza.co/+vNUW-3d\n\nShop: https://stza.co/+vNUW-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Independence Day Fireworks Extravaganza
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Grasshoppers
<2018-07-04 Wed 18:00-21:00>
:PROPERTIES:
:ID:       xw5yiUyhn4SL8jIBXrnEwa0c@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Grasshoppers BlueClaws @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizO-q

Shop  https //stza.co/+wizO-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Grasshoppers
END:VALARM
DTSTART:20180704T230000Z
DTEND:20180705T020000Z
UID:xw5yiUyhn4SL8jIBXrnEwa0c@stanza.co
SUMMARY:BlueClaws @ Grasshoppers
DESCRIPTION:BlueClaws @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizO-q\n\nShop: https://stza.co/+wizO-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Grasshoppers
<2018-07-05 Thu 18:00-21:00>
:PROPERTIES:
:ID:       TgdkYAIYPs9F4TmWPe4xWQTT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Grasshoppers BlueClaws @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizP-24

Shop  https //stza.co/+wizP-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Grasshoppers
END:VALARM
DTSTART:20180705T230000Z
DTEND:20180706T020000Z
UID:TgdkYAIYPs9F4TmWPe4xWQTT@stanza.co
SUMMARY:BlueClaws @ Grasshoppers
DESCRIPTION:BlueClaws @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizP-24\n\nShop: https://stza.co/+wizP-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Grasshoppers
<2018-07-06 Fri 18:00-21:00>
:PROPERTIES:
:ID:       LzSC6a3oY9LtqC4Uwd8Fd8dP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Grasshoppers BlueClaws @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizR-12

Shop  https //stza.co/+wizR-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Grasshoppers
END:VALARM
DTSTART:20180706T230000Z
DTEND:20180707T020000Z
UID:LzSC6a3oY9LtqC4Uwd8Fd8dP@stanza.co
SUMMARY:BlueClaws @ Grasshoppers
DESCRIPTION:BlueClaws @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizR-12\n\nShop: https://stza.co/+wizR-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Intimidators
<2018-07-07 Sat 18:05-21:05>
:PROPERTIES:
:ID:       o7wRCwVAj98K5FugpcH6F1Ha@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Intimidators BlueClaws @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIFB-3z

Shop  https //stza.co/+wIFB-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Intimidators
END:VALARM
DTSTART:20180707T230500Z
DTEND:20180708T020500Z
UID:o7wRCwVAj98K5FugpcH6F1Ha@stanza.co
SUMMARY:BlueClaws @ Intimidators
DESCRIPTION:BlueClaws @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIFB-3z\n\nShop: https://stza.co/+wIFB-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Intimidators
<2018-07-08 Sun 16:05-19:05>
:PROPERTIES:
:ID:       ffxsRQt8Fy0TWxH4rp8B17Qc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Intimidators BlueClaws @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIFC-3O

Shop  https //stza.co/+wIFC-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Intimidators
END:VALARM
DTSTART:20180708T210500Z
DTEND:20180709T000500Z
UID:ffxsRQt8Fy0TWxH4rp8B17Qc@stanza.co
SUMMARY:BlueClaws @ Intimidators
DESCRIPTION:BlueClaws @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIFC-3O\n\nShop: https://stza.co/+wIFC-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Intimidators
<2018-07-09 Mon 18:05-21:05>
:PROPERTIES:
:ID:       x5PbqtiR08f6eyvscc68szHM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Intimidators BlueClaws @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIFD-2Y

Shop  https //stza.co/+wIFD-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Intimidators
END:VALARM
DTSTART:20180709T230500Z
DTEND:20180710T020500Z
UID:x5PbqtiR08f6eyvscc68szHM@stanza.co
SUMMARY:BlueClaws @ Intimidators
DESCRIPTION:BlueClaws @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIFD-2Y\n\nShop: https://stza.co/+wIFD-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Tourists
<2018-07-11 Wed 18:05-21:05>
:PROPERTIES:
:ID:       8FnNnAEr0lb2ovmigVVOaLdf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Tourists BlueClaws vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+vNUY-1B

Shop  https //stza.co/+vNUY-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Tourists
END:VALARM
DTSTART:20180711T230500Z
DTEND:20180712T020500Z
UID:8FnNnAEr0lb2ovmigVVOaLdf@stanza.co
SUMMARY:BlueClaws vs. Tourists
DESCRIPTION:BlueClaws vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNUY-1B\n\nShop: https://stza.co/+vNUY-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Tourists
<2018-07-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       I9jHmftvYm6PEhX2PxQXRXBd@stanza.co
:LOCATION: Thirsty Thursday
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Tourists Dollar beer and soda plus great wings as part of Thirsty Thursday, every Thursday at FirstEnergy Park. 

Follow on MiLB First Pitch  https //stza.co/+vNU$-S

Shop  https //stza.co/+vNU$-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Tourists
END:VALARM
DTSTART:20180712T230500Z
DTEND:20180713T020500Z
UID:I9jHmftvYm6PEhX2PxQXRXBd@stanza.co
SUMMARY:BlueClaws vs. Tourists
DESCRIPTION:Dollar beer and soda plus great wings as part of Thirsty Thursday, every Thursday at FirstEnergy Park. \n\nFollow on MiLB First Pitch: https://stza.co/+vNU$-S\n\nShop: https://stza.co/+vNU$-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursday
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Tourists
<2018-07-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       uYK9c574xBKAFDgwlGZn_2uh@stanza.co
:LOCATION: Harry Potter Night with Glow In The Dark Pillowcase
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Tourists As part of Harry Potter Night, we have a special Platinum Item, a Harry Potter Glow In The Dark Pillowcase. This item can be your free Mini Plan Gift. For more information on BlueClaws Mini Plans, visit BlueClaws.com/TicketPlans. 

The BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. 

Follow on MiLB First Pitch  https //stza.co/+vNV0-3Y

Shop  https //stza.co/+vNV0-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Tourists
END:VALARM
DTSTART:20180713T230500Z
DTEND:20180714T020500Z
UID:uYK9c574xBKAFDgwlGZn_2uh@stanza.co
SUMMARY:BlueClaws vs. Tourists
DESCRIPTION:As part of Harry Potter Night, we have a special Platinum Item, a Harry Potter Glow In The Dark Pillowcase. This item can be your free Mini Plan Gift. For more information on BlueClaws Mini Plans, visit BlueClaws.com/TicketPlans. \n\nThe BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. \n\nFollow on MiLB First Pitch: https://stza.co/+vNV0-3Y\n\nShop: https://stza.co/+vNV0-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Harry Potter Night with Glow In The Dark Pillowcase
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Fireflies
<2018-07-14 Sat 18:05-21:05>
:PROPERTIES:
:ID:       gy5IkR3v0uVklqqBUWxbUo6X@stanza.co
:LOCATION: Country Night
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Fireflies Country Night includes live music, special promotions, and much more.

The BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. 

Follow on MiLB First Pitch  https //stza.co/+vNV3-A

Shop  https //stza.co/+vNV3-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Fireflies
END:VALARM
DTSTART:20180714T230500Z
DTEND:20180715T020500Z
UID:gy5IkR3v0uVklqqBUWxbUo6X@stanza.co
SUMMARY:BlueClaws vs. Fireflies
DESCRIPTION:Country Night includes live music, special promotions, and much more.\n\nThe BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. \n\nFollow on MiLB First Pitch: https://stza.co/+vNV3-A\n\nShop: https://stza.co/+vNV3-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Country Night
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Fireflies
<2018-07-15 Sun 12:05-15:05>
:PROPERTIES:
:ID:       NoRkgCnr0sVvZkPV2vuq9qMn@stanza.co
:LOCATION: Bring the family to the park for our Kids Eat Free game
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Fireflies Kids Eat Free at every Sunday BlueClaws home game thanks to ShopRite. Kids 12 and under receive a hot dog, chips and soda. 

Follow on MiLB First Pitch  https //stza.co/+vNV4-2c

Shop  https //stza.co/+vNV4-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Fireflies
END:VALARM
DTSTART:20180715T170500Z
DTEND:20180715T200500Z
UID:NoRkgCnr0sVvZkPV2vuq9qMn@stanza.co
SUMMARY:BlueClaws vs. Fireflies
DESCRIPTION:Kids Eat Free at every Sunday BlueClaws home game thanks to ShopRite. Kids 12 and under receive a hot dog, chips and soda. \n\nFollow on MiLB First Pitch: https://stza.co/+vNV4-2c\n\nShop: https://stza.co/+vNV4-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Bring the family to the park for our Kids Eat Free game
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Fireflies
<2018-07-16 Mon 18:05-21:05>
:PROPERTIES:
:ID:       EmNIY-ObHdVCZREhbjU1_mXP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Fireflies BlueClaws vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+vNV7-12

Shop  https //stza.co/+vNV7-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Fireflies
END:VALARM
DTSTART:20180716T230500Z
DTEND:20180717T020500Z
UID:EmNIY-ObHdVCZREhbjU1_mXP@stanza.co
SUMMARY:BlueClaws vs. Fireflies
DESCRIPTION:BlueClaws vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+vNV7-12\n\nShop: https://stza.co/+vNV7-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Fireflies
<2018-07-17 Tue 10:05-13:05>
:PROPERTIES:
:ID:       RN1dduG--Iiha-GDILg163Vx@stanza.co
:LOCATION: Silver Sluggers Tuesday
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Fireflies It's Silver Sluggers Tuesday, where member of the BlueClaws Silver Sluggers Club eat free and receive a hot dog, bag of chips, and a soda. 

Follow on MiLB First Pitch  https //stza.co/+vNV8-14

Shop  https //stza.co/+vNV8-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Fireflies
END:VALARM
DTSTART:20180717T150500Z
DTEND:20180717T180500Z
UID:RN1dduG--Iiha-GDILg163Vx@stanza.co
SUMMARY:BlueClaws vs. Fireflies
DESCRIPTION:It's Silver Sluggers Tuesday, where member of the BlueClaws Silver Sluggers Club eat free and receive a hot dog, bag of chips, and a soda. \n\nFollow on MiLB First Pitch: https://stza.co/+vNV8-14\n\nShop: https://stza.co/+vNV8-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Silver Sluggers Tuesday
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Suns
<2018-07-19 Thu 18:05-21:05>
:PROPERTIES:
:ID:       VGTJI-ajmzeyK_f_MsRiKerK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Suns BlueClaws @ Suns

Follow on MiLB First Pitch  https //stza.co/+xF8b-2b

Shop  https //stza.co/+xF8b-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Suns
END:VALARM
DTSTART:20180719T230500Z
DTEND:20180720T020500Z
UID:VGTJI-ajmzeyK_f_MsRiKerK@stanza.co
SUMMARY:BlueClaws @ Suns
DESCRIPTION:BlueClaws @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xF8b-2b\n\nShop: https://stza.co/+xF8b-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Suns
<2018-07-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       tfol8StSfyF5GGSosfHh4x3u@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Suns BlueClaws @ Suns

Follow on MiLB First Pitch  https //stza.co/+xF8c-2u

Shop  https //stza.co/+xF8c-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Suns
END:VALARM
DTSTART:20180720T230500Z
DTEND:20180721T020500Z
UID:tfol8StSfyF5GGSosfHh4x3u@stanza.co
SUMMARY:BlueClaws @ Suns
DESCRIPTION:BlueClaws @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xF8c-2u\n\nShop: https://stza.co/+xF8c-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Suns
<2018-07-21 Sat 17:05-20:05>
:PROPERTIES:
:ID:       upm7nV2kQ1gju05qI6u3N_rN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Suns BlueClaws @ Suns

Follow on MiLB First Pitch  https //stza.co/+xF8e-28

Shop  https //stza.co/+xF8e-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Suns
END:VALARM
DTSTART:20180721T220500Z
DTEND:20180722T010500Z
UID:upm7nV2kQ1gju05qI6u3N_rN@stanza.co
SUMMARY:BlueClaws @ Suns
DESCRIPTION:BlueClaws @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xF8e-28\n\nShop: https://stza.co/+xF8e-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Suns
<2018-07-22 Sun 13:05-16:05>
:PROPERTIES:
:ID:       abeADLZp4qUjSIeeda_gbDLE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Suns BlueClaws @ Suns

Follow on MiLB First Pitch  https //stza.co/+xF8g-1f

Shop  https //stza.co/+xF8g-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Suns
END:VALARM
DTSTART:20180722T180500Z
DTEND:20180722T210500Z
UID:abeADLZp4qUjSIeeda_gbDLE@stanza.co
SUMMARY:BlueClaws @ Suns
DESCRIPTION:BlueClaws @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xF8g-1f\n\nShop: https://stza.co/+xF8g-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Grasshoppers
<2018-07-23 Mon 18:05-21:05>
:PROPERTIES:
:ID:       YZnJx5brEQoBKwSaeJoYKFLD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Grasshoppers BlueClaws vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+vNVa-3U

Shop  https //stza.co/+vNVa-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Grasshoppers
END:VALARM
DTSTART:20180723T230500Z
DTEND:20180724T020500Z
UID:YZnJx5brEQoBKwSaeJoYKFLD@stanza.co
SUMMARY:BlueClaws vs. Grasshoppers
DESCRIPTION:BlueClaws vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+vNVa-3U\n\nShop: https://stza.co/+vNVa-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Grasshoppers
<2018-07-24 Tue 18:05-21:05>
:PROPERTIES:
:ID:       uRhajsnQDQxP41Bo4LMLZIqq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Grasshoppers BlueClaws vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+vNVd-u

Shop  https //stza.co/+vNVd-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Grasshoppers
END:VALARM
DTSTART:20180724T230500Z
DTEND:20180725T020500Z
UID:uRhajsnQDQxP41Bo4LMLZIqq@stanza.co
SUMMARY:BlueClaws vs. Grasshoppers
DESCRIPTION:BlueClaws vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+vNVd-u\n\nShop: https://stza.co/+vNVd-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Grasshoppers
<2018-07-25 Wed 10:05-13:05>
:PROPERTIES:
:ID:       tPzMOXE1b5cniwNz_JraXuDM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Grasshoppers BlueClaws vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+vNVe-2i

Shop  https //stza.co/+vNVe-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Grasshoppers
END:VALARM
DTSTART:20180725T150500Z
DTEND:20180725T180500Z
UID:tPzMOXE1b5cniwNz_JraXuDM@stanza.co
SUMMARY:BlueClaws vs. Grasshoppers
DESCRIPTION:BlueClaws vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+vNVe-2i\n\nShop: https://stza.co/+vNVe-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Grasshoppers
<2018-07-26 Thu 18:05-21:05>
:PROPERTIES:
:ID:       QD_ZGPIzAiRfKwQaXV0twRDS@stanza.co
:LOCATION: Thirsty Thursday
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Grasshoppers Dollar beer and soda plus great wings as part of Thirsty Thursday, every Thursday at FirstEnergy Park. 

Follow on MiLB First Pitch  https //stza.co/+vNVg-1A

Shop  https //stza.co/+vNVg-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Grasshoppers
END:VALARM
DTSTART:20180726T230500Z
DTEND:20180727T020500Z
UID:QD_ZGPIzAiRfKwQaXV0twRDS@stanza.co
SUMMARY:BlueClaws vs. Grasshoppers
DESCRIPTION:Dollar beer and soda plus great wings as part of Thirsty Thursday, every Thursday at FirstEnergy Park. \n\nFollow on MiLB First Pitch: https://stza.co/+vNVg-1A\n\nShop: https://stza.co/+vNVg-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursday
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Suns
<2018-07-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       dmw8e4Y82O_hjydwB8HfyWO5@stanza.co
:LOCATION: Italian Heritage Night
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Suns Food specials, promotions, music, and more highlight the annual Italian Heritage Night at FirstEnergy Park. 

The BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. 

Follow on MiLB First Pitch  https //stza.co/+vNVi-2k

Shop  https //stza.co/+vNVi-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Suns
END:VALARM
DTSTART:20180727T230500Z
DTEND:20180728T020500Z
UID:dmw8e4Y82O_hjydwB8HfyWO5@stanza.co
SUMMARY:BlueClaws vs. Suns
DESCRIPTION:Food specials, promotions, music, and more highlight the annual Italian Heritage Night at FirstEnergy Park. \n\nThe BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. \n\nFollow on MiLB First Pitch: https://stza.co/+vNVi-2k\n\nShop: https://stza.co/+vNVi-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Italian Heritage Night
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Suns
<2018-07-28 Sat 18:05-21:05>
:PROPERTIES:
:ID:       D2DjFEa_zx_ZbeDWpCqs1Ltu@stanza.co
:LOCATION: BruceClaws Night
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Suns The 11th annual Bruce Springsteen Appreciation Night includes live music, special promotions, and the annual Born to Run...For Beer event before the game - details to come.

The BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. 

Follow on MiLB First Pitch  https //stza.co/+vNVk-3N

Shop  https //stza.co/+vNVk-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Suns
END:VALARM
DTSTART:20180728T230500Z
DTEND:20180729T020500Z
UID:D2DjFEa_zx_ZbeDWpCqs1Ltu@stanza.co
SUMMARY:BlueClaws vs. Suns
DESCRIPTION:The 11th annual Bruce Springsteen Appreciation Night includes live music, special promotions, and the annual Born to Run...For Beer event before the game - details to come.\n\nThe BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. \n\nFollow on MiLB First Pitch: https://stza.co/+vNVk-3N\n\nShop: https://stza.co/+vNVk-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:BruceClaws Night
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Suns
<2018-07-29 Sun 12:05-15:05>
:PROPERTIES:
:ID:       FfEoo9gkZ1G1iQwH03pFQ61g@stanza.co
:LOCATION: Bring the family to the park for our Kids Eat Free game
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Suns Kids Eat Free at every Sunday BlueClaws home game thanks to ShopRite. Kids 12 and under receive a hot dog, chips and soda. 

Follow on MiLB First Pitch  https //stza.co/+vNVn-26

Shop  https //stza.co/+vNVn-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Suns
END:VALARM
DTSTART:20180729T170500Z
DTEND:20180729T200500Z
UID:FfEoo9gkZ1G1iQwH03pFQ61g@stanza.co
SUMMARY:BlueClaws vs. Suns
DESCRIPTION:Kids Eat Free at every Sunday BlueClaws home game thanks to ShopRite. Kids 12 and under receive a hot dog, chips and soda. \n\nFollow on MiLB First Pitch: https://stza.co/+vNVn-26\n\nShop: https://stza.co/+vNVn-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Bring the family to the park for our Kids Eat Free game
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Shorebirds
<2018-07-30 Mon 18:05-21:05>
:PROPERTIES:
:ID:       7vbSbc0PdkLpcqzQuyx-0FpE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Shorebirds BlueClaws @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHSA-1J

Shop  https //stza.co/+wHSA-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Shorebirds
END:VALARM
DTSTART:20180730T230500Z
DTEND:20180731T020500Z
UID:7vbSbc0PdkLpcqzQuyx-0FpE@stanza.co
SUMMARY:BlueClaws @ Shorebirds
DESCRIPTION:BlueClaws @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHSA-1J\n\nShop: https://stza.co/+wHSA-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Shorebirds
<2018-07-31 Tue 18:05-21:05>
:PROPERTIES:
:ID:       aGQR3Xa-hXg906-kNTAdbdTe@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Shorebirds BlueClaws @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHSB-2c

Shop  https //stza.co/+wHSB-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Shorebirds
END:VALARM
DTSTART:20180731T230500Z
DTEND:20180801T020500Z
UID:aGQR3Xa-hXg906-kNTAdbdTe@stanza.co
SUMMARY:BlueClaws @ Shorebirds
DESCRIPTION:BlueClaws @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHSB-2c\n\nShop: https://stza.co/+wHSB-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Shorebirds
<2018-08-01 Wed 18:05-21:05>
:PROPERTIES:
:ID:       eM_F6OMH1XIzMkCpw6wfg3sJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Shorebirds BlueClaws @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHRs-3L

Shop  https //stza.co/+wHRs-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Shorebirds
END:VALARM
DTSTART:20180801T230500Z
DTEND:20180802T020500Z
UID:eM_F6OMH1XIzMkCpw6wfg3sJ@stanza.co
SUMMARY:BlueClaws @ Shorebirds
DESCRIPTION:BlueClaws @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHRs-3L\n\nShop: https://stza.co/+wHRs-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Legends
<2018-08-02 Thu 18:05-21:05>
:PROPERTIES:
:ID:       xUz6JPTqbfbD3tpRBFMO15ZU@stanza.co
:LOCATION: Thirsty Thursday
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Legends Dollar beer and soda plus great wings as part of Thirsty Thursday, every Thursday at FirstEnergy Park. 

Follow on MiLB First Pitch  https //stza.co/+vNVp-31

Shop  https //stza.co/+vNVp-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Legends
END:VALARM
DTSTART:20180802T230500Z
DTEND:20180803T020500Z
UID:xUz6JPTqbfbD3tpRBFMO15ZU@stanza.co
SUMMARY:BlueClaws vs. Legends
DESCRIPTION:Dollar beer and soda plus great wings as part of Thirsty Thursday, every Thursday at FirstEnergy Park. \n\nFollow on MiLB First Pitch: https://stza.co/+vNVp-31\n\nShop: https://stza.co/+vNVp-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursday
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Legends
<2018-08-03 Fri 18:05-21:05>
:PROPERTIES:
:ID:       yM6uN5j483jha9GpHSKMManA@stanza.co
:LOCATION: Seven Kingdoms of Claws Night & Rhys Hoskins Dragon Bobble
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Legends In celebration of Seven Kingdoms of Claws Night, fans can receive a special Rhys Hoskins Dragon Bobble. This item can be your free Mini Plan Gift. For more information on BlueClaws Mini Plans, visit BlueClaws.com/TicketPlans. 

The BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. 

Follow on MiLB First Pitch  https //stza.co/+vNVq-3b

Shop  https //stza.co/+vNVq-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Legends
END:VALARM
DTSTART:20180803T230500Z
DTEND:20180804T020500Z
UID:yM6uN5j483jha9GpHSKMManA@stanza.co
SUMMARY:BlueClaws vs. Legends
DESCRIPTION:In celebration of Seven Kingdoms of Claws Night, fans can receive a special Rhys Hoskins Dragon Bobble. This item can be your free Mini Plan Gift. For more information on BlueClaws Mini Plans, visit BlueClaws.com/TicketPlans. \n\nThe BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. \n\nFollow on MiLB First Pitch: https://stza.co/+vNVq-3b\n\nShop: https://stza.co/+vNVq-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Seven Kingdoms of Claws Night & Rhys Hoskins Dragon Bobble
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Legends
<2018-08-04 Sat 18:05-21:05>
:PROPERTIES:
:ID:       669rL4SSSuCA8XC9C-74cEQc@stanza.co
:LOCATION: Irish Heritage Night & BlueClaws Irish Caps
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Legends It's Irish Heritage Night at FirstEnergy Park. The first 1,500 fans receive a BlueClaws Irish Cap. 

The BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. 

Follow on MiLB First Pitch  https //stza.co/+vNVs-1H

Shop  https //stza.co/+vNVs-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Legends
END:VALARM
DTSTART:20180804T230500Z
DTEND:20180805T020500Z
UID:669rL4SSSuCA8XC9C-74cEQc@stanza.co
SUMMARY:BlueClaws vs. Legends
DESCRIPTION:It's Irish Heritage Night at FirstEnergy Park. The first 1,500 fans receive a BlueClaws Irish Cap. \n\nThe BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. \n\nFollow on MiLB First Pitch: https://stza.co/+vNVs-1H\n\nShop: https://stza.co/+vNVs-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Irish Heritage Night & BlueClaws Irish Caps
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Legends
<2018-08-05 Sun 12:05-15:05>
:PROPERTIES:
:ID:       KBm65B9StThUVkaHlGmK-UBI@stanza.co
:LOCATION: Bring the family to the park for our Kids Eat Free game
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Legends Kids Eat Free at every Sunday BlueClaws home game thanks to ShopRite. Kids 12 and under receive a hot dog, chips and soda. 

Follow on MiLB First Pitch  https //stza.co/+vNVu-r

Shop  https //stza.co/+vNVu-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Legends
END:VALARM
DTSTART:20180805T170500Z
DTEND:20180805T200500Z
UID:KBm65B9StThUVkaHlGmK-UBI@stanza.co
SUMMARY:BlueClaws vs. Legends
DESCRIPTION:Kids Eat Free at every Sunday BlueClaws home game thanks to ShopRite. Kids 12 and under receive a hot dog, chips and soda. \n\nFollow on MiLB First Pitch: https://stza.co/+vNVu-r\n\nShop: https://stza.co/+vNVu-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Bring the family to the park for our Kids Eat Free game
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ RiverDogs
<2018-08-07 Tue 18:05-21:05>
:PROPERTIES:
:ID:       YhnGumO_7uuaR3ksDlLBk_SR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BlueClaws @ RiverDogs BlueClaws @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNSJ-1P

Shop  https //stza.co/+vNSJ-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ RiverDogs
END:VALARM
DTSTART:20180807T230500Z
DTEND:20180808T020500Z
UID:YhnGumO_7uuaR3ksDlLBk_SR@stanza.co
SUMMARY:BlueClaws @ RiverDogs
DESCRIPTION:BlueClaws @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNSJ-1P\n\nShop: https://stza.co/+vNSJ-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ RiverDogs
<2018-08-08 Wed 18:05-21:05>
:PROPERTIES:
:ID:       8LE2mKQ7WvUiinAZRjjtOhUt@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ RiverDogs BlueClaws @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNSK-d

Shop  https //stza.co/+vNSK-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ RiverDogs
END:VALARM
DTSTART:20180808T230500Z
DTEND:20180809T020500Z
UID:8LE2mKQ7WvUiinAZRjjtOhUt@stanza.co
SUMMARY:BlueClaws @ RiverDogs
DESCRIPTION:BlueClaws @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNSK-d\n\nShop: https://stza.co/+vNSK-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ RiverDogs
<2018-08-09 Thu 18:05-21:05>
:PROPERTIES:
:ID:       odvq0nMSBOX0PvmZ-OHSp054@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ RiverDogs BlueClaws @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNSL-14

Shop  https //stza.co/+vNSL-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ RiverDogs
END:VALARM
DTSTART:20180809T230500Z
DTEND:20180810T020500Z
UID:odvq0nMSBOX0PvmZ-OHSp054@stanza.co
SUMMARY:BlueClaws @ RiverDogs
DESCRIPTION:BlueClaws @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNSL-14\n\nShop: https://stza.co/+vNSL-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Crawdads
<2018-08-10 Fri 18:00-21:00>
:PROPERTIES:
:ID:       12_JxK0joIf1izSWqBD3pIO7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Crawdads BlueClaws @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0QW-3W

Shop  https //stza.co/+w0QW-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Crawdads
END:VALARM
DTSTART:20180810T230000Z
DTEND:20180811T020000Z
UID:12_JxK0joIf1izSWqBD3pIO7@stanza.co
SUMMARY:BlueClaws @ Crawdads
DESCRIPTION:BlueClaws @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0QW-3W\n\nShop: https://stza.co/+w0QW-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Crawdads
<2018-08-11 Sat 18:00-21:00>
:PROPERTIES:
:ID:       5VRhOuPWj8kp-KBSxiAu2-6x@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Crawdads BlueClaws @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+xB7d-k

Shop  https //stza.co/+xB7d-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Crawdads
END:VALARM
DTSTART:20180811T230000Z
DTEND:20180812T020000Z
UID:5VRhOuPWj8kp-KBSxiAu2-6x@stanza.co
SUMMARY:BlueClaws @ Crawdads
DESCRIPTION:BlueClaws @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+xB7d-k\n\nShop: https://stza.co/+xB7d-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Crawdads
<2018-08-12 Sun 16:00-19:00>
:PROPERTIES:
:ID:       _OFHswLw3FgxlseZrgJHmpYb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Crawdads BlueClaws @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0QY-3h

Shop  https //stza.co/+w0QY-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Crawdads
END:VALARM
DTSTART:20180812T210000Z
DTEND:20180813T000000Z
UID:_OFHswLw3FgxlseZrgJHmpYb@stanza.co
SUMMARY:BlueClaws @ Crawdads
DESCRIPTION:BlueClaws @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0QY-3h\n\nShop: https://stza.co/+w0QY-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Crawdads
<2018-08-13 Mon 11:00-14:00>
:PROPERTIES:
:ID:       KvcGgTtrjasA3eXxR3zHSFQ_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Crawdads BlueClaws @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0QZ-2t

Shop  https //stza.co/+w0QZ-2S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Crawdads
END:VALARM
DTSTART:20180813T160000Z
DTEND:20180813T190000Z
UID:KvcGgTtrjasA3eXxR3zHSFQ_@stanza.co
SUMMARY:BlueClaws @ Crawdads
DESCRIPTION:BlueClaws @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0QZ-2t\n\nShop: https://stza.co/+w0QZ-2S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Braves
<2018-08-15 Wed 18:05-21:05>
:PROPERTIES:
:ID:       4jyEB73es55BwPIucjgphrMP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Braves BlueClaws vs. Braves

Follow on MiLB First Pitch  https //stza.co/+vNVw-2z

Shop  https //stza.co/+vNVw-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Braves
END:VALARM
DTSTART:20180815T230500Z
DTEND:20180816T020500Z
UID:4jyEB73es55BwPIucjgphrMP@stanza.co
SUMMARY:BlueClaws vs. Braves
DESCRIPTION:BlueClaws vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNVw-2z\n\nShop: https://stza.co/+vNVw-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Braves
<2018-08-16 Thu 18:05-21:05>
:PROPERTIES:
:ID:       XD3sG6lr5XEmRz4Zhjdhf_6_@stanza.co
:LOCATION: Ladies Night & Tote Bags
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Braves It's Ladies Night with special promotions and games throughout the night. Plus, the first 1,500 fans receive a BlueClaws Ladies Night Tote Bag. 

Dollar beer and soda plus great wings as part of Thirsty Thursday, every Thursday at FirstEnergy Park. 

Follow on MiLB First Pitch  https //stza.co/+vNVy-1_

Shop  https //stza.co/+vNVy-1w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Braves
END:VALARM
DTSTART:20180816T230500Z
DTEND:20180817T020500Z
UID:XD3sG6lr5XEmRz4Zhjdhf_6_@stanza.co
SUMMARY:BlueClaws vs. Braves
DESCRIPTION:It's Ladies Night with special promotions and games throughout the night. Plus, the first 1,500 fans receive a BlueClaws Ladies Night Tote Bag. \n\nDollar beer and soda plus great wings as part of Thirsty Thursday, every Thursday at FirstEnergy Park. \n\nFollow on MiLB First Pitch: https://stza.co/+vNVy-1_\n\nShop: https://stza.co/+vNVy-1w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ladies Night & Tote Bags
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Braves
<2018-08-17 Fri 18:05-21:05>
:PROPERTIES:
:ID:       5rZGomIpJlVoK9r8br2HkUgz@stanza.co
:LOCATION: Fireworks Spectacular
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Braves The BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. 

Follow on MiLB First Pitch  https //stza.co/+vNVB-1c

Shop  https //stza.co/+vNVB-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Braves
END:VALARM
DTSTART:20180817T230500Z
DTEND:20180818T020500Z
UID:5rZGomIpJlVoK9r8br2HkUgz@stanza.co
SUMMARY:BlueClaws vs. Braves
DESCRIPTION:The BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. \n\nFollow on MiLB First Pitch: https://stza.co/+vNVB-1c\n\nShop: https://stza.co/+vNVB-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Spectacular
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Legends
<2018-08-18 Sat 18:05-21:05>
:PROPERTIES:
:ID:       3PWi5YJanCSV7KXUvcDGkEEF@stanza.co
:LOCATION: Beatles Night
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Legends Beatles Night will include live music, special promotions, and more, capped by post-game fireworks. 

The BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. 

Follow on MiLB First Pitch  https //stza.co/+vNVD-3D

Shop  https //stza.co/+vNVD-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Legends
END:VALARM
DTSTART:20180818T230500Z
DTEND:20180819T020500Z
UID:3PWi5YJanCSV7KXUvcDGkEEF@stanza.co
SUMMARY:BlueClaws vs. Legends
DESCRIPTION:Beatles Night will include live music, special promotions, and more, capped by post-game fireworks. \n\nThe BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. \n\nFollow on MiLB First Pitch: https://stza.co/+vNVD-3D\n\nShop: https://stza.co/+vNVD-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Beatles Night
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Legends
<2018-08-19 Sun 12:05-15:05>
:PROPERTIES:
:ID:       KgWJvJGMcjawCwq6dpTDct4H@stanza.co
:LOCATION: Bring the family to the park for our Kids Eat Free game
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Legends Kids Eat Free at every Sunday BlueClaws home game thanks to ShopRite. Kids 12 and under receive a hot dog, chips and soda. 

Follow on MiLB First Pitch  https //stza.co/+vNVF-3l

Shop  https //stza.co/+vNVF-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Legends
END:VALARM
DTSTART:20180819T170500Z
DTEND:20180819T200500Z
UID:KgWJvJGMcjawCwq6dpTDct4H@stanza.co
SUMMARY:BlueClaws vs. Legends
DESCRIPTION:Kids Eat Free at every Sunday BlueClaws home game thanks to ShopRite. Kids 12 and under receive a hot dog, chips and soda. \n\nFollow on MiLB First Pitch: https://stza.co/+vNVF-3l\n\nShop: https://stza.co/+vNVF-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Bring the family to the park for our Kids Eat Free game
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Legends
<2018-08-20 Mon 18:05-21:05>
:PROPERTIES:
:ID:       nc66xqDeC7hRR5cKd5xzT2eK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Legends BlueClaws vs. Legends

Follow on MiLB First Pitch  https //stza.co/+vNVH-3g

Shop  https //stza.co/+vNVH-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Legends
END:VALARM
DTSTART:20180820T230500Z
DTEND:20180821T020500Z
UID:nc66xqDeC7hRR5cKd5xzT2eK@stanza.co
SUMMARY:BlueClaws vs. Legends
DESCRIPTION:BlueClaws vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+vNVH-3g\n\nShop: https://stza.co/+vNVH-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Legends
<2018-08-21 Tue 18:05-21:05>
:PROPERTIES:
:ID:       lCjyRqRvvjId0NDqoRIRTVBX@stanza.co
:LOCATION: Silver Sluggers Tuesday
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Legends It's Silver Sluggers Tuesday, where member of the BlueClaws Silver Sluggers Club eat free and receive a hot dog, bag of chips, and a soda. 

Follow on MiLB First Pitch  https //stza.co/+vNVJ-1U

Shop  https //stza.co/+vNVJ-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Legends
END:VALARM
DTSTART:20180821T230500Z
DTEND:20180822T020500Z
UID:lCjyRqRvvjId0NDqoRIRTVBX@stanza.co
SUMMARY:BlueClaws vs. Legends
DESCRIPTION:It's Silver Sluggers Tuesday, where member of the BlueClaws Silver Sluggers Club eat free and receive a hot dog, bag of chips, and a soda. \n\nFollow on MiLB First Pitch: https://stza.co/+vNVJ-1U\n\nShop: https://stza.co/+vNVJ-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Silver Sluggers Tuesday
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Crawdads
<2018-08-23 Thu 18:00-21:00>
:PROPERTIES:
:ID:       uSof18lZjRDbn1vIa5T8dFI1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Crawdads BlueClaws @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0Q_-1m

Shop  https //stza.co/+w0Q_-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Crawdads
END:VALARM
DTSTART:20180823T230000Z
DTEND:20180824T020000Z
UID:uSof18lZjRDbn1vIa5T8dFI1@stanza.co
SUMMARY:BlueClaws @ Crawdads
DESCRIPTION:BlueClaws @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0Q_-1m\n\nShop: https://stza.co/+w0Q_-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Crawdads
<2018-08-24 Fri 18:00-21:00>
:PROPERTIES:
:ID:       7o4jokleBoVxMDHOae0Hd1xA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Crawdads BlueClaws @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0Q$-z

Shop  https //stza.co/+w0Q$-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Crawdads
END:VALARM
DTSTART:20180824T230000Z
DTEND:20180825T020000Z
UID:7o4jokleBoVxMDHOae0Hd1xA@stanza.co
SUMMARY:BlueClaws @ Crawdads
DESCRIPTION:BlueClaws @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0Q$-z\n\nShop: https://stza.co/+w0Q$-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Crawdads
<2018-08-25 Sat 18:00-21:00>
:PROPERTIES:
:ID:       4GlOIIq1_HxTRwpnTmC6fbwS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Crawdads BlueClaws @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0R0-X

Shop  https //stza.co/+w0R0-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Crawdads
END:VALARM
DTSTART:20180825T230000Z
DTEND:20180826T020000Z
UID:4GlOIIq1_HxTRwpnTmC6fbwS@stanza.co
SUMMARY:BlueClaws @ Crawdads
DESCRIPTION:BlueClaws @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0R0-X\n\nShop: https://stza.co/+w0R0-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Crawdads
<2018-08-26 Sun 16:00-19:00>
:PROPERTIES:
:ID:       gBc_nmgYeNnBy3vQig3Vgr5W@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Crawdads BlueClaws @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0R1-2g

Shop  https //stza.co/+w0R1-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Crawdads
END:VALARM
DTSTART:20180826T210000Z
DTEND:20180827T000000Z
UID:gBc_nmgYeNnBy3vQig3Vgr5W@stanza.co
SUMMARY:BlueClaws @ Crawdads
DESCRIPTION:BlueClaws @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0R1-2g\n\nShop: https://stza.co/+w0R1-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Grasshoppers
<2018-08-27 Mon 18:00-21:00>
:PROPERTIES:
:ID:       6DW3n_a1ZCBed1ndFleZk7Iw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Grasshoppers BlueClaws @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizS-37

Shop  https //stza.co/+wizS-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Grasshoppers
END:VALARM
DTSTART:20180827T230000Z
DTEND:20180828T020000Z
UID:6DW3n_a1ZCBed1ndFleZk7Iw@stanza.co
SUMMARY:BlueClaws @ Grasshoppers
DESCRIPTION:BlueClaws @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizS-37\n\nShop: https://stza.co/+wizS-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Grasshoppers
<2018-08-28 Tue 18:00-21:00>
:PROPERTIES:
:ID:       oXCRB-UfQ-tymELjpUsQvccH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Grasshoppers BlueClaws @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizT-7

Shop  https //stza.co/+wizT-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Grasshoppers
END:VALARM
DTSTART:20180828T230000Z
DTEND:20180829T020000Z
UID:oXCRB-UfQ-tymELjpUsQvccH@stanza.co
SUMMARY:BlueClaws @ Grasshoppers
DESCRIPTION:BlueClaws @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizT-7\n\nShop: https://stza.co/+wizT-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Grasshoppers
<2018-08-29 Wed 18:00-21:00>
:PROPERTIES:
:ID:       9-iaVIFagX5zXf0R6N0hoLQv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Grasshoppers BlueClaws @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizU-f

Shop  https //stza.co/+wizU-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Grasshoppers
END:VALARM
DTSTART:20180829T230000Z
DTEND:20180830T020000Z
UID:9-iaVIFagX5zXf0R6N0hoLQv@stanza.co
SUMMARY:BlueClaws @ Grasshoppers
DESCRIPTION:BlueClaws @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizU-f\n\nShop: https://stza.co/+wizU-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws @ Grasshoppers
<2018-08-30 Thu 18:00-21:00>
:PROPERTIES:
:ID:       G8ztLFgX9PnPUMN0JmbcJNr4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws @ Grasshoppers BlueClaws @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizV-25

Shop  https //stza.co/+wizV-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BlueClaws @ Grasshoppers
END:VALARM
DTSTART:20180830T230000Z
DTEND:20180831T020000Z
UID:G8ztLFgX9PnPUMN0JmbcJNr4@stanza.co
SUMMARY:BlueClaws @ Grasshoppers
DESCRIPTION:BlueClaws @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizV-25\n\nShop: https://stza.co/+wizV-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Shorebirds
<2018-08-31 Fri 18:05-21:05>
:PROPERTIES:
:ID:       TTIwxYBzs4bwGJJCNbyMPjw2@stanza.co
:LOCATION: Augtoberfest & Beer Steins
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Shorebirds It's BlueClaws Augtoberfest Night with beer and food specials. Plus, the first 1,500 adults 21 & older receive a special commemorative BlueClaws Beer Stein. 

The BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. 

Follow on MiLB First Pitch  https //stza.co/+vNVL-3N

Shop  https //stza.co/+vNVL-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Shorebirds
END:VALARM
DTSTART:20180831T230500Z
DTEND:20180901T020500Z
UID:TTIwxYBzs4bwGJJCNbyMPjw2@stanza.co
SUMMARY:BlueClaws vs. Shorebirds
DESCRIPTION:It's BlueClaws Augtoberfest Night with beer and food specials. Plus, the first 1,500 adults 21 & older receive a special commemorative BlueClaws Beer Stein. \n\nThe BlueClaws have the biggest, brightest, most colorful fireworks shows at the Shore after each Friday and select Saturday home games. \n\nFollow on MiLB First Pitch: https://stza.co/+vNVL-3N\n\nShop: https://stza.co/+vNVL-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Augtoberfest & Beer Steins
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Shorebirds
<2018-09-01 Sat 18:05-21:05>
:PROPERTIES:
:ID:       t37yPM28eRoGNg--jjjtGjfN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Shorebirds BlueClaws vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+vNVN-3h

Shop  https //stza.co/+vNVN-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Shorebirds
END:VALARM
DTSTART:20180901T230500Z
DTEND:20180902T020500Z
UID:t37yPM28eRoGNg--jjjtGjfN@stanza.co
SUMMARY:BlueClaws vs. Shorebirds
DESCRIPTION:BlueClaws vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+vNVN-3h\n\nShop: https://stza.co/+vNVN-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Shorebirds
<2018-09-02 Sun 18:05-21:05>
:PROPERTIES:
:ID:       xJpOoob2N2pXI266hCw53KF7@stanza.co
:LOCATION: Bring the family to the park for our Kids Eat Free game
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Shorebirds Kids Eat Free at every Sunday BlueClaws home game thanks to ShopRite. Kids 12 and under receive a hot dog, chips and soda. 

Follow on MiLB First Pitch  https //stza.co/+vNVP-1P

Shop  https //stza.co/+vNVP-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Shorebirds
END:VALARM
DTSTART:20180902T230500Z
DTEND:20180903T020500Z
UID:xJpOoob2N2pXI266hCw53KF7@stanza.co
SUMMARY:BlueClaws vs. Shorebirds
DESCRIPTION:Kids Eat Free at every Sunday BlueClaws home game thanks to ShopRite. Kids 12 and under receive a hot dog, chips and soda. \n\nFollow on MiLB First Pitch: https://stza.co/+vNVP-1P\n\nShop: https://stza.co/+vNVP-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Bring the family to the park for our Kids Eat Free game
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
* BlueClaws vs. Shorebirds
<2018-09-03 Mon 12:05-15:05>
:PROPERTIES:
:ID:       FB2G5-L8Ywxr70Y2cqfpHAW_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BlueClaws vs. Shorebirds BlueClaws vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+vNVQ-3O

Shop  https //stza.co/+vNVQ-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BlueClaws vs. Shorebirds
END:VALARM
DTSTART:20180903T170500Z
DTEND:20180903T200500Z
UID:FB2G5-L8Ywxr70Y2cqfpHAW_@stanza.co
SUMMARY:BlueClaws vs. Shorebirds
DESCRIPTION:BlueClaws vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+vNVQ-3O\n\nShop: https://stza.co/+vNVQ-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144539Z
LAST-MODIFIED:20180213T144539Z
TRANSP:OPAQUE
END:VEVENT
