#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Mudcats vs. Dash
<2018-04-05 Thu 18:00-21:00>
:PROPERTIES:
:ID:       FM8AfvZKuOWGAmKg6uqZ68RN@stanza.co
:LOCATION: Opening Night
:STATUS:   CONFIRMED
:END:

Mudcats vs. Dash Come and join the Mudcats as we kick off our 28th season in Zebulon!

Make sure you come for our annual Magnet Schedule giveaway to the first 5,000 fans through the gate.

Sit back and enjoy a Mudcats game with some cold ones with 1/2 price draft beers and $1-12oz Coca-Cola fountain products.

Buy tickets here  https //stza.co/~w0kt

Follow on MiLB First Pitch  https //stza.co/+w0kt-1b

Shop  https //stza.co/+w0kt-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Dash
END:VALARM
DTSTART:20180405T230000Z
DTEND:20180406T020000Z
UID:FM8AfvZKuOWGAmKg6uqZ68RN@stanza.co
SUMMARY:Mudcats vs. Dash
DESCRIPTION:Come and join the Mudcats as we kick off our 28th season in Zebulon!\n\nMake sure you come for our annual Magnet Schedule giveaway to the first 5,000 fans through the gate.\n\nSit back and enjoy a Mudcats game with some cold ones with 1/2 price draft beers and $1-12oz Coca-Cola fountain products.\n\nBuy tickets here: https://stza.co/~w0kt\n\nFollow on MiLB First Pitch: https://stza.co/+w0kt-1b\n\nShop: https://stza.co/+w0kt-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Opening Night
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Dash
<2018-04-06 Fri 18:00-21:00>
:PROPERTIES:
:ID:       -2ZqvuYKczSjO8COPVWDPVA3@stanza.co
:LOCATION: Celebrate the start of the weekend with our Friday Night Fireworks after the game!
:STATUS:   CONFIRMED
:END:

Mudcats vs. Dash Stay after the game and enjoy fireworks shows after every Friday home game.

Make sure you come for our annual Magnet Schedule giveaway to the first 5,000 fans through the gate.

Come join the Mudcats during Opening Weekend of the 2018 season.

Buy tickets here  https //stza.co/~w0kv

Follow on MiLB First Pitch  https //stza.co/+w0kv-1S

Shop  https //stza.co/+w0kv-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Dash
END:VALARM
DTSTART:20180406T230000Z
DTEND:20180407T020000Z
UID:-2ZqvuYKczSjO8COPVWDPVA3@stanza.co
SUMMARY:Mudcats vs. Dash
DESCRIPTION:Stay after the game and enjoy fireworks shows after every Friday home game.\n\nMake sure you come for our annual Magnet Schedule giveaway to the first 5,000 fans through the gate.\n\nCome join the Mudcats during Opening Weekend of the 2018 season.\n\nBuy tickets here: https://stza.co/~w0kv\n\nFollow on MiLB First Pitch: https://stza.co/+w0kv-1S\n\nShop: https://stza.co/+w0kv-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Celebrate the start of the weekend with our Friday Night Fireworks after the game!
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Dash
<2018-04-07 Sat 16:00-19:00>
:PROPERTIES:
:ID:       peq3q-jZ4DWl-1Hm9unv-7WO@stanza.co
:LOCATION: Magnet Schedule Giveaway
:STATUS:   CONFIRMED
:END:

Mudcats vs. Dash Make sure you come for our annual Magnet Schedule giveaway to the first 5,000 fans through the gate.

Come join the Mudcats during Opening Weekend of the 2018 season.

Buy tickets here  https //stza.co/~w0kw

Follow on MiLB First Pitch  https //stza.co/+w0kw-_

Shop  https //stza.co/+w0kw-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Dash
END:VALARM
DTSTART:20180407T210000Z
DTEND:20180408T000000Z
UID:peq3q-jZ4DWl-1Hm9unv-7WO@stanza.co
SUMMARY:Mudcats vs. Dash
DESCRIPTION:Make sure you come for our annual Magnet Schedule giveaway to the first 5,000 fans through the gate.\n\nCome join the Mudcats during Opening Weekend of the 2018 season.\n\nBuy tickets here: https://stza.co/~w0kw\n\nFollow on MiLB First Pitch: https://stza.co/+w0kw-_\n\nShop: https://stza.co/+w0kw-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Magnet Schedule Giveaway
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Dash
<2018-04-08 Sun 13:00-16:00>
:PROPERTIES:
:ID:       LZF0povn_9067VDIVCj4QDtw@stanza.co
:LOCATION: Magnet Schedule Giveaway
:STATUS:   CONFIRMED
:END:

Mudcats vs. Dash Make sure you come for our annual Magnet Schedule giveaway to the first 5,000 fans through the gate.

Each kid that is part of the Muddy's Buddies Kids Club gets one free box seat ticket to every Sunday home game, excluding May 27th.  All-Star Members receive 1 Free Speed Pitch Pass & 1 Free Spin on the Prize Wheel by presenting their membership cards.

Come join the Mudcats during Opening Weekend of the 2018 season.

Buy tickets here  https //stza.co/~w0kz

Follow on MiLB First Pitch  https //stza.co/+w0kz-2N

Shop  https //stza.co/+w0kz-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Dash
END:VALARM
DTSTART:20180408T180000Z
DTEND:20180408T210000Z
UID:LZF0povn_9067VDIVCj4QDtw@stanza.co
SUMMARY:Mudcats vs. Dash
DESCRIPTION:Make sure you come for our annual Magnet Schedule giveaway to the first 5,000 fans through the gate.\n\nEach kid that is part of the Muddy's Buddies Kids Club gets one free box seat ticket to every Sunday home game, excluding May 27th.  All-Star Members receive 1 Free Speed Pitch Pass & 1 Free Spin on the Prize Wheel by presenting their membership cards.\n\nCome join the Mudcats during Opening Weekend of the 2018 season.\n\nBuy tickets here: https://stza.co/~w0kz\n\nFollow on MiLB First Pitch: https://stza.co/+w0kz-2N\n\nShop: https://stza.co/+w0kz-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Magnet Schedule Giveaway
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Keys
<2018-04-09 Mon 18:00-21:00>
:PROPERTIES:
:ID:       ASvWZ1v_Tw2nac-fzWcV85A-@stanza.co
:LOCATION: Marked Down Monday
:STATUS:   CONFIRMED
:END:

Mudcats vs. Keys Every Monday in 2018 is a Marked Down Monday.  All Box Seat tickets are just $8, either online or at the Five County Stadium Box Office.  Parking will also be free every Monday Night.  Marked Down Mondays also feature reduced price concession items to satisfy everyone's appetite.

Buy tickets here  https //stza.co/~w0kA

Follow on MiLB First Pitch  https //stza.co/+w0kA-1U

Shop  https //stza.co/+w0kA-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Keys
END:VALARM
DTSTART:20180409T230000Z
DTEND:20180410T020000Z
UID:ASvWZ1v_Tw2nac-fzWcV85A-@stanza.co
SUMMARY:Mudcats vs. Keys
DESCRIPTION:Every Monday in 2018 is a Marked Down Monday.  All Box Seat tickets are just $8, either online or at the Five County Stadium Box Office.  Parking will also be free every Monday Night.  Marked Down Mondays also feature reduced price concession items to satisfy everyone's appetite.\n\nBuy tickets here: https://stza.co/~w0kA\n\nFollow on MiLB First Pitch: https://stza.co/+w0kA-1U\n\nShop: https://stza.co/+w0kA-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Marked Down Monday
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Keys
<2018-04-10 Tue 18:00-21:00>
:PROPERTIES:
:ID:       4TW9dWxui0BR1oJDnU1E4xtB@stanza.co
:LOCATION: Taco Tuesday
:STATUS:   CONFIRMED
:END:

Mudcats vs. Keys Fans can enjoy themselves with $1 tacos at the Taco Stand on the concourse.

Buy tickets here  https //stza.co/~w0kC

Follow on MiLB First Pitch  https //stza.co/+w0kC-1T

Shop  https //stza.co/+w0kC-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Keys
END:VALARM
DTSTART:20180410T230000Z
DTEND:20180411T020000Z
UID:4TW9dWxui0BR1oJDnU1E4xtB@stanza.co
SUMMARY:Mudcats vs. Keys
DESCRIPTION:Fans can enjoy themselves with $1 tacos at the Taco Stand on the concourse.\n\nBuy tickets here: https://stza.co/~w0kC\n\nFollow on MiLB First Pitch: https://stza.co/+w0kC-1T\n\nShop: https://stza.co/+w0kC-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Taco Tuesday
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Keys
<2018-04-11 Wed 10:00-13:00>
:PROPERTIES:
:ID:       Fj8XSCeHB0vTBiA2Fg109dUz@stanza.co
:LOCATION: Education Day
:STATUS:   CONFIRMED
:END:

Mudcats vs. Keys The Carolina Mudcats would like to invite your school to enjoy a day of exciting Minor League Baseball, learning, and an experience like no other! Education Day is scheduled for students of all ages. 

Come out to a special 11am start time.

Buy tickets here  https //stza.co/~w0kF

Follow on MiLB First Pitch  https //stza.co/+w0kF-2b

Shop  https //stza.co/+w0kF-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Keys
END:VALARM
DTSTART:20180411T150000Z
DTEND:20180411T180000Z
UID:Fj8XSCeHB0vTBiA2Fg109dUz@stanza.co
SUMMARY:Mudcats vs. Keys
DESCRIPTION:The Carolina Mudcats would like to invite your school to enjoy a day of exciting Minor League Baseball, learning, and an experience like no other! Education Day is scheduled for students of all ages. \n\nCome out to a special 11am start time.\n\nBuy tickets here: https://stza.co/~w0kF\n\nFollow on MiLB First Pitch: https://stza.co/+w0kF-2b\n\nShop: https://stza.co/+w0kF-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Education Day
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Dash
<2018-04-12 Thu 18:00-21:00>
:PROPERTIES:
:ID:       cqMbmQmOpKMxshkUE__9DYmq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Dash Mudcats @ Dash

Buy tickets here  https //stza.co/~w0nl

Follow on MiLB First Pitch  https //stza.co/+w0nl-2w

Shop  https //stza.co/+w0nl-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Dash
END:VALARM
DTSTART:20180412T230000Z
DTEND:20180413T020000Z
UID:cqMbmQmOpKMxshkUE__9DYmq@stanza.co
SUMMARY:Mudcats @ Dash
DESCRIPTION:Mudcats @ Dash\n\nBuy tickets here: https://stza.co/~w0nl\n\nFollow on MiLB First Pitch: https://stza.co/+w0nl-2w\n\nShop: https://stza.co/+w0nl-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Dash
<2018-04-13 Fri 18:00-21:00>
:PROPERTIES:
:ID:       sYBOebcMdHb9NfzPv1n89en_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mudcats @ Dash Mudcats @ Dash

Buy tickets here  https //stza.co/~w0nm

Follow on MiLB First Pitch  https //stza.co/+w0nm-e

Shop  https //stza.co/+w0nm-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Dash
END:VALARM
DTSTART:20180413T230000Z
DTEND:20180414T020000Z
UID:sYBOebcMdHb9NfzPv1n89en_@stanza.co
SUMMARY:Mudcats @ Dash
DESCRIPTION:Mudcats @ Dash\n\nBuy tickets here: https://stza.co/~w0nm\n\nFollow on MiLB First Pitch: https://stza.co/+w0nm-e\n\nShop: https://stza.co/+w0nm-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Dash
<2018-04-14 Sat 17:00-20:00>
:PROPERTIES:
:ID:       7vuRo0AYzCvhC5vVcEtRK-MZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Dash Mudcats @ Dash

Buy tickets here  https //stza.co/~w0nn

Follow on MiLB First Pitch  https //stza.co/+w0nn-d

Shop  https //stza.co/+w0nn-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Dash
END:VALARM
DTSTART:20180414T220000Z
DTEND:20180415T010000Z
UID:7vuRo0AYzCvhC5vVcEtRK-MZ@stanza.co
SUMMARY:Mudcats @ Dash
DESCRIPTION:Mudcats @ Dash\n\nBuy tickets here: https://stza.co/~w0nn\n\nFollow on MiLB First Pitch: https://stza.co/+w0nn-d\n\nShop: https://stza.co/+w0nn-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Dash
<2018-04-15 Sun 13:00-16:00>
:PROPERTIES:
:ID:       RLjpoVJuaPwcWI8b24x-A_p6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Dash Mudcats @ Dash

Buy tickets here  https //stza.co/~w0no

Follow on MiLB First Pitch  https //stza.co/+w0no-37

Shop  https //stza.co/+w0no-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Dash
END:VALARM
DTSTART:20180415T180000Z
DTEND:20180415T210000Z
UID:RLjpoVJuaPwcWI8b24x-A_p6@stanza.co
SUMMARY:Mudcats @ Dash
DESCRIPTION:Mudcats @ Dash\n\nBuy tickets here: https://stza.co/~w0no\n\nFollow on MiLB First Pitch: https://stza.co/+w0no-37\n\nShop: https://stza.co/+w0no-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Blue Rocks
<2018-04-16 Mon 17:35-20:35>
:PROPERTIES:
:ID:       qKLM7e9RN0h9Ax3IBnHOjfWd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mudcats @ Blue Rocks Mudcats @ Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+wX7s-3L

Shop  https //stza.co/+wX7s-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Blue Rocks
END:VALARM
DTSTART:20180416T223500Z
DTEND:20180417T013500Z
UID:qKLM7e9RN0h9Ax3IBnHOjfWd@stanza.co
SUMMARY:Mudcats @ Blue Rocks
DESCRIPTION:Mudcats @ Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+wX7s-3L\n\nShop: https://stza.co/+wX7s-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Blue Rocks
<2018-04-17 Tue 17:35-20:35>
:PROPERTIES:
:ID:       MhYA1jkmqTGLuB9W7FaaMfL6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Blue Rocks Mudcats @ Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+wX7t-1k

Shop  https //stza.co/+wX7t-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Blue Rocks
END:VALARM
DTSTART:20180417T223500Z
DTEND:20180418T013500Z
UID:MhYA1jkmqTGLuB9W7FaaMfL6@stanza.co
SUMMARY:Mudcats @ Blue Rocks
DESCRIPTION:Mudcats @ Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+wX7t-1k\n\nShop: https://stza.co/+wX7t-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Blue Rocks
<2018-04-18 Wed 09:35-12:35>
:PROPERTIES:
:ID:       m_F1XLmBbgLxyq6mDKQnzNx1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Blue Rocks Mudcats @ Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+wX7u-1t

Shop  https //stza.co/+wX7u-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Blue Rocks
END:VALARM
DTSTART:20180418T143500Z
DTEND:20180418T173500Z
UID:m_F1XLmBbgLxyq6mDKQnzNx1@stanza.co
SUMMARY:Mudcats @ Blue Rocks
DESCRIPTION:Mudcats @ Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+wX7u-1t\n\nShop: https://stza.co/+wX7u-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Astros
<2018-04-19 Thu 18:00-21:00>
:PROPERTIES:
:ID:       LXd3_wxiOfXU9zCyOjeskuAu@stanza.co
:LOCATION: Thirsty Thursday
:STATUS:   CONFIRMED
:END:

Mudcats vs. Astros Sit back and enjoy a Mudcats game with some cold ones with 1/2 price draft beers and $1-12oz Coca-Cola fountain products.

Buy tickets here  https //stza.co/~w0kH

Follow on MiLB First Pitch  https //stza.co/+w0kH-3m

Shop  https //stza.co/+w0kH-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Astros
END:VALARM
DTSTART:20180419T230000Z
DTEND:20180420T020000Z
UID:LXd3_wxiOfXU9zCyOjeskuAu@stanza.co
SUMMARY:Mudcats vs. Astros
DESCRIPTION:Sit back and enjoy a Mudcats game with some cold ones with 1/2 price draft beers and $1-12oz Coca-Cola fountain products.\n\nBuy tickets here: https://stza.co/~w0kH\n\nFollow on MiLB First Pitch: https://stza.co/+w0kH-3m\n\nShop: https://stza.co/+w0kH-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursday
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Astros
<2018-04-20 Fri 18:00-21:00>
:PROPERTIES:
:ID:       u1DqrmbylEE0cSKV4HxDEJCU@stanza.co
:LOCATION: Celebrate the start of the weekend with our Friday Night Fireworks after the game!
:STATUS:   CONFIRMED
:END:

Mudcats vs. Astros Stay after the game and enjoy fireworks shows after every Friday home game.

Buy tickets here  https //stza.co/~w0kI

Follow on MiLB First Pitch  https //stza.co/+w0kI-3i

Shop  https //stza.co/+w0kI-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Astros
END:VALARM
DTSTART:20180420T230000Z
DTEND:20180421T020000Z
UID:u1DqrmbylEE0cSKV4HxDEJCU@stanza.co
SUMMARY:Mudcats vs. Astros
DESCRIPTION:Stay after the game and enjoy fireworks shows after every Friday home game.\n\nBuy tickets here: https://stza.co/~w0kI\n\nFollow on MiLB First Pitch: https://stza.co/+w0kI-3i\n\nShop: https://stza.co/+w0kI-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Celebrate the start of the weekend with our Friday Night Fireworks after the game!
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Astros
<2018-04-21 Sat 16:00-19:00>
:PROPERTIES:
:ID:       YQm5p8IOqt5jl1vee8DJCiUB@stanza.co
:LOCATION: May the force be with you! Come check out Stars Wars Night at the park
:STATUS:   CONFIRMED
:END:

Mudcats vs. Astros From a Ballpark far, far away the Mudcats are set for our annual Star Wars Night with a specialty themed jersey that will be auctioned off and the net proceeds benefiting the JDRF Triangle/Eastern NC Chapter.

Also, make sure you get your one of a kind Mudcats beard which will be given out to the first 1200 kids in the ball park that night.

Buy tickets here  https //stza.co/~w0kL

Follow on MiLB First Pitch  https //stza.co/+w0kL-V

Shop  https //stza.co/+w0kL-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Astros
END:VALARM
DTSTART:20180421T210000Z
DTEND:20180422T000000Z
UID:YQm5p8IOqt5jl1vee8DJCiUB@stanza.co
SUMMARY:Mudcats vs. Astros
DESCRIPTION:From a Ballpark far, far away the Mudcats are set for our annual Star Wars Night with a specialty themed jersey that will be auctioned off and the net proceeds benefiting the JDRF Triangle/Eastern NC Chapter.\n\nAlso, make sure you get your one of a kind Mudcats beard which will be given out to the first 1200 kids in the ball park that night.\n\nBuy tickets here: https://stza.co/~w0kL\n\nFollow on MiLB First Pitch: https://stza.co/+w0kL-V\n\nShop: https://stza.co/+w0kL-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:May the force be with you! Come check out Stars Wars Night at the park
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Astros
<2018-04-22 Sun 13:00-16:00>
:PROPERTIES:
:ID:       mZXtL926y9iVm275c8M83on2@stanza.co
:LOCATION: Muddy's Buddies Kids Club Sunday
:STATUS:   CONFIRMED
:END:

Mudcats vs. Astros Each kid that is part of the Muddy's Buddies Kids Club gets one free box seat ticket to every Sunday home game, excluding May 27th.  All-Star Members receive 1 Free Speed Pitch Pass & 1 Free Spin on the Prize Wheel by presenting their membership cards.

Buy tickets here  https //stza.co/~w0kN

Follow on MiLB First Pitch  https //stza.co/+w0kN-3G

Shop  https //stza.co/+w0kN-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Astros
END:VALARM
DTSTART:20180422T180000Z
DTEND:20180422T210000Z
UID:mZXtL926y9iVm275c8M83on2@stanza.co
SUMMARY:Mudcats vs. Astros
DESCRIPTION:Each kid that is part of the Muddy's Buddies Kids Club gets one free box seat ticket to every Sunday home game, excluding May 27th.  All-Star Members receive 1 Free Speed Pitch Pass & 1 Free Spin on the Prize Wheel by presenting their membership cards.\n\nBuy tickets here: https://stza.co/~w0kN\n\nFollow on MiLB First Pitch: https://stza.co/+w0kN-3G\n\nShop: https://stza.co/+w0kN-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Muddy's Buddies Kids Club Sunday
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Pelicans
<2018-04-24 Tue 18:00-21:00>
:PROPERTIES:
:ID:       4FMpgBiGg8NWulKtYwCxhUBH@stanza.co
:LOCATION: Taco Tuesday
:STATUS:   CONFIRMED
:END:

Mudcats vs. Pelicans Fans can enjoy themselves with $1 tacos at the Taco Stand on the concourse.

Buy tickets here  https //stza.co/~w0kO

Follow on MiLB First Pitch  https //stza.co/+w0kO-2K

Shop  https //stza.co/+w0kO-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Pelicans
END:VALARM
DTSTART:20180424T230000Z
DTEND:20180425T020000Z
UID:4FMpgBiGg8NWulKtYwCxhUBH@stanza.co
SUMMARY:Mudcats vs. Pelicans
DESCRIPTION:Fans can enjoy themselves with $1 tacos at the Taco Stand on the concourse.\n\nBuy tickets here: https://stza.co/~w0kO\n\nFollow on MiLB First Pitch: https://stza.co/+w0kO-2K\n\nShop: https://stza.co/+w0kO-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Taco Tuesday
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Pelicans
<2018-04-25 Wed 10:00-13:00>
:PROPERTIES:
:ID:       v0nt_U0RvhMWnXbfELFRTPIU@stanza.co
:LOCATION: Education Day
:STATUS:   CONFIRMED
:END:

Mudcats vs. Pelicans The Carolina Mudcats would like to invite your school to enjoy a day of exciting Minor League Baseball, learning, and an experience like no other! Education Day is scheduled for students of all ages.

Come out to a special 11am start time.

Buy tickets here  https //stza.co/~xVX9

Follow on MiLB First Pitch  https //stza.co/+xVX9-11

Shop  https //stza.co/+xVX9-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Pelicans
END:VALARM
DTSTART:20180425T150000Z
DTEND:20180425T180000Z
UID:v0nt_U0RvhMWnXbfELFRTPIU@stanza.co
SUMMARY:Mudcats vs. Pelicans
DESCRIPTION:The Carolina Mudcats would like to invite your school to enjoy a day of exciting Minor League Baseball, learning, and an experience like no other! Education Day is scheduled for students of all ages.\n\nCome out to a special 11am start time.\n\nBuy tickets here: https://stza.co/~xVX9\n\nFollow on MiLB First Pitch: https://stza.co/+xVX9-11\n\nShop: https://stza.co/+xVX9-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Education Day
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Pelicans
<2018-04-26 Thu 18:00-21:00>
:PROPERTIES:
:ID:       LrP_yM1WrhcVkW1ljWGavkfe@stanza.co
:LOCATION: Thirsty Thursday
:STATUS:   CONFIRMED
:END:

Mudcats vs. Pelicans Sit back and enjoy a Mudcats game with some cold ones with 1/2 price draft beers and $1-12oz Coca-Cola fountain products.

Buy tickets here  https //stza.co/~w0kS

Follow on MiLB First Pitch  https //stza.co/+w0kS-G

Shop  https //stza.co/+w0kS-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Pelicans
END:VALARM
DTSTART:20180426T230000Z
DTEND:20180427T020000Z
UID:LrP_yM1WrhcVkW1ljWGavkfe@stanza.co
SUMMARY:Mudcats vs. Pelicans
DESCRIPTION:Sit back and enjoy a Mudcats game with some cold ones with 1/2 price draft beers and $1-12oz Coca-Cola fountain products.\n\nBuy tickets here: https://stza.co/~w0kS\n\nFollow on MiLB First Pitch: https://stza.co/+w0kS-G\n\nShop: https://stza.co/+w0kS-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursday
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Wood Ducks
<2018-04-27 Fri 18:00-21:00>
:PROPERTIES:
:ID:       m1ZI7wWCi2CIOrVPKNhVRmg_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mudcats @ Wood Ducks Mudcats @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0mF-3e

Shop  https //stza.co/+w0mF-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Wood Ducks
END:VALARM
DTSTART:20180427T230000Z
DTEND:20180428T020000Z
UID:m1ZI7wWCi2CIOrVPKNhVRmg_@stanza.co
SUMMARY:Mudcats @ Wood Ducks
DESCRIPTION:Mudcats @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0mF-3e\n\nShop: https://stza.co/+w0mF-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Wood Ducks
<2018-04-28 Sat 17:00-20:00>
:PROPERTIES:
:ID:       JgrTMuHmivWQE8HOpJQVaMkF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Wood Ducks Mudcats @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0mG-o

Shop  https //stza.co/+w0mG-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Wood Ducks
END:VALARM
DTSTART:20180428T220000Z
DTEND:20180429T010000Z
UID:JgrTMuHmivWQE8HOpJQVaMkF@stanza.co
SUMMARY:Mudcats @ Wood Ducks
DESCRIPTION:Mudcats @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0mG-o\n\nShop: https://stza.co/+w0mG-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Wood Ducks
<2018-04-29 Sun 13:00-16:00>
:PROPERTIES:
:ID:       myvrFSgXs_d6wkBqzgBNPbc9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Wood Ducks Mudcats @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0mI-8

Shop  https //stza.co/+w0mI-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Wood Ducks
END:VALARM
DTSTART:20180429T180000Z
DTEND:20180429T210000Z
UID:myvrFSgXs_d6wkBqzgBNPbc9@stanza.co
SUMMARY:Mudcats @ Wood Ducks
DESCRIPTION:Mudcats @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0mI-8\n\nShop: https://stza.co/+w0mI-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Pelicans
<2018-05-01 Tue>--<2018-04-30 Mon>
:PROPERTIES:
:ID:       yqZ5X3s83SG4zlWUBxfIzwCn@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mudcats @ Pelicans Mudcats @ Pelicans

Follow on MiLB First Pitch  https //stza.co/+w0mY-k

Shop  https //stza.co/+w0mY-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Pelicans
END:VALARM
DTSTART;VALUE=DATE:20180501
DTEND;VALUE=DATE:20180501
UID:yqZ5X3s83SG4zlWUBxfIzwCn@stanza.co
SUMMARY:Mudcats @ Pelicans
DESCRIPTION:Mudcats @ Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+w0mY-k\n\nShop: https://stza.co/+w0mY-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Pelicans
<2018-05-02 Wed>--<2018-05-01 Tue>
:PROPERTIES:
:ID:       WccvXneYdGin6EYb5seq3Sv0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Pelicans Mudcats @ Pelicans

Follow on MiLB First Pitch  https //stza.co/+w0mZ-3V

Shop  https //stza.co/+w0mZ-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Pelicans
END:VALARM
DTSTART;VALUE=DATE:20180502
DTEND;VALUE=DATE:20180502
UID:WccvXneYdGin6EYb5seq3Sv0@stanza.co
SUMMARY:Mudcats @ Pelicans
DESCRIPTION:Mudcats @ Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+w0mZ-3V\n\nShop: https://stza.co/+w0mZ-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Pelicans
<2018-05-03 Thu>--<2018-05-02 Wed>
:PROPERTIES:
:ID:       V29CnRVKRm9K7XrX74XLF_88@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Pelicans Mudcats @ Pelicans

Follow on MiLB First Pitch  https //stza.co/+w0m_-1r

Shop  https //stza.co/+w0m_-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Pelicans
END:VALARM
DTSTART;VALUE=DATE:20180503
DTEND;VALUE=DATE:20180503
UID:V29CnRVKRm9K7XrX74XLF_88@stanza.co
SUMMARY:Mudcats @ Pelicans
DESCRIPTION:Mudcats @ Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+w0m_-1r\n\nShop: https://stza.co/+w0m_-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Wood Ducks
<2018-05-04 Fri 18:00-21:00>
:PROPERTIES:
:ID:       ijHVgoWx8toc3c9tg_E_qs-d@stanza.co
:LOCATION: Celebrate the start of the weekend with our Friday Night Fireworks after the game!
:STATUS:   CONFIRMED
:END:

Mudcats vs. Wood Ducks Stay after the game and enjoy fireworks shows after every Friday home game.

Join the Mudcats for the annual Boy Scout Campout at Five County Stadium.  Watch the game against the Down East Wood Ducks followed by Friday Night Fireworks.  After the fireworks, a movie will be shown on the Mudzilla Videoboard.  Then the scouts will retire to their tents for the night.

Buy tickets here  https //stza.co/~w0kU

Follow on MiLB First Pitch  https //stza.co/+w0kU-1a

Shop  https //stza.co/+w0kU-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Wood Ducks
END:VALARM
DTSTART:20180504T230000Z
DTEND:20180505T020000Z
UID:ijHVgoWx8toc3c9tg_E_qs-d@stanza.co
SUMMARY:Mudcats vs. Wood Ducks
DESCRIPTION:Stay after the game and enjoy fireworks shows after every Friday home game.\n\nJoin the Mudcats for the annual Boy Scout Campout at Five County Stadium.  Watch the game against the Down East Wood Ducks followed by Friday Night Fireworks.  After the fireworks, a movie will be shown on the Mudzilla Videoboard.  Then the scouts will retire to their tents for the night.\n\nBuy tickets here: https://stza.co/~w0kU\n\nFollow on MiLB First Pitch: https://stza.co/+w0kU-1a\n\nShop: https://stza.co/+w0kU-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Celebrate the start of the weekend with our Friday Night Fireworks after the game!
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Wood Ducks
<2018-05-05 Sat 16:00-19:00>
:PROPERTIES:
:ID:       imF2ntsa7yR1JjcYgix7YJsk@stanza.co
:LOCATION: Royal Gathering Night
:STATUS:   CONFIRMED
:END:

Mudcats vs. Wood Ducks Hear ye, Hear ye. The Mudcats cordially invite you the fans to a royal gathering in preparation to the royal wedding in England. Join us as the Mudcats of Carolina take on the Wood Ducks of Down East.

After the game the Mudcats will be giving away Bud Light Pint glasses for fans 21 and older as they exit the Stadium. Dilly, Dilly!

Buy tickets here  https //stza.co/~w0kX

Follow on MiLB First Pitch  https //stza.co/+w0kX-1x

Shop  https //stza.co/+w0kX-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Wood Ducks
END:VALARM
DTSTART:20180505T210000Z
DTEND:20180506T000000Z
UID:imF2ntsa7yR1JjcYgix7YJsk@stanza.co
SUMMARY:Mudcats vs. Wood Ducks
DESCRIPTION:Hear ye, Hear ye. The Mudcats cordially invite you the fans to a royal gathering in preparation to the royal wedding in England. Join us as the Mudcats of Carolina take on the Wood Ducks of Down East.\n\nAfter the game the Mudcats will be giving away Bud Light Pint glasses for fans 21 and older as they exit the Stadium. Dilly, Dilly!\n\nBuy tickets here: https://stza.co/~w0kX\n\nFollow on MiLB First Pitch: https://stza.co/+w0kX-1x\n\nShop: https://stza.co/+w0kX-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Royal Gathering Night
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Wood Ducks
<2018-05-06 Sun 13:00-16:00>
:PROPERTIES:
:ID:       pXfRtagGPQdBzmgpwIjs4C2s@stanza.co
:LOCATION: Muddy's Buddies Kids Club Sunday
:STATUS:   CONFIRMED
:END:

Mudcats vs. Wood Ducks Each kid that is part of the Muddy's Buddies Kids Club gets one free box seat ticket to every Sunday home game, excluding May 27th.  All-Star Members receive 1 Free Speed Pitch Pass & 1 Free Spin on the Prize Wheel by presenting their membership cards.

Buy tickets here  https //stza.co/~w0kZ

Follow on MiLB First Pitch  https //stza.co/+w0kZ-3N

Shop  https //stza.co/+w0kZ-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Wood Ducks
END:VALARM
DTSTART:20180506T180000Z
DTEND:20180506T210000Z
UID:pXfRtagGPQdBzmgpwIjs4C2s@stanza.co
SUMMARY:Mudcats vs. Wood Ducks
DESCRIPTION:Each kid that is part of the Muddy's Buddies Kids Club gets one free box seat ticket to every Sunday home game, excluding May 27th.  All-Star Members receive 1 Free Speed Pitch Pass & 1 Free Spin on the Prize Wheel by presenting their membership cards.\n\nBuy tickets here: https://stza.co/~w0kZ\n\nFollow on MiLB First Pitch: https://stza.co/+w0kZ-3N\n\nShop: https://stza.co/+w0kZ-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Muddy's Buddies Kids Club Sunday
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Astros
<2018-05-07 Mon 18:00-21:00>
:PROPERTIES:
:ID:       HijTsWl3e1TiXG9WzjgGaVJz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mudcats @ Astros Mudcats @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM8C-1Q

Shop  https //stza.co/+xM8C-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Astros
END:VALARM
DTSTART:20180507T230000Z
DTEND:20180508T020000Z
UID:HijTsWl3e1TiXG9WzjgGaVJz@stanza.co
SUMMARY:Mudcats @ Astros
DESCRIPTION:Mudcats @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM8C-1Q\n\nShop: https://stza.co/+xM8C-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Astros
<2018-05-08 Tue 18:00-21:00>
:PROPERTIES:
:ID:       So7m51lUFOKr6WAPRCTJoB2H@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Astros Mudcats @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM8D-1P

Shop  https //stza.co/+xM8D-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Astros
END:VALARM
DTSTART:20180508T230000Z
DTEND:20180509T020000Z
UID:So7m51lUFOKr6WAPRCTJoB2H@stanza.co
SUMMARY:Mudcats @ Astros
DESCRIPTION:Mudcats @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM8D-1P\n\nShop: https://stza.co/+xM8D-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Astros
<2018-05-09 Wed 18:00-21:00>
:PROPERTIES:
:ID:       L08Xs-GKTGieNRvoXPO1bgFh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Astros Mudcats @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM8E-5

Shop  https //stza.co/+xM8E-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Astros
END:VALARM
DTSTART:20180509T230000Z
DTEND:20180510T020000Z
UID:L08Xs-GKTGieNRvoXPO1bgFh@stanza.co
SUMMARY:Mudcats @ Astros
DESCRIPTION:Mudcats @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM8E-5\n\nShop: https://stza.co/+xM8E-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Blue Rocks
<2018-05-10 Thu 18:00-21:00>
:PROPERTIES:
:ID:       n9niwS1FrQng8ocj34Zphttj@stanza.co
:LOCATION: Thirsty Thursday
:STATUS:   CONFIRMED
:END:

Mudcats vs. Blue Rocks Sit back and enjoy a Mudcats game with some cold ones with 1/2 price draft beers and $1-12oz Coca-Cola fountain products.

Buy tickets here  https //stza.co/~w0k$

Follow on MiLB First Pitch  https //stza.co/+w0k$-26

Shop  https //stza.co/+w0k$-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Blue Rocks
END:VALARM
DTSTART:20180510T230000Z
DTEND:20180511T020000Z
UID:n9niwS1FrQng8ocj34Zphttj@stanza.co
SUMMARY:Mudcats vs. Blue Rocks
DESCRIPTION:Sit back and enjoy a Mudcats game with some cold ones with 1/2 price draft beers and $1-12oz Coca-Cola fountain products.\n\nBuy tickets here: https://stza.co/~w0k$\n\nFollow on MiLB First Pitch: https://stza.co/+w0k$-26\n\nShop: https://stza.co/+w0k$-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursday
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Blue Rocks
<2018-05-11 Fri 18:00-21:00>
:PROPERTIES:
:ID:       ket_eBmvqoEOUeypcSkfZcNS@stanza.co
:LOCATION: Celebrate the start of the weekend with our Friday Night Fireworks after the game!
:STATUS:   CONFIRMED
:END:

Mudcats vs. Blue Rocks Stay after the game and enjoy fireworks shows after every Friday home game.

It's a new era in Mudcats history as we enter our first year under the new ownership of the Milwaukee Brewers. The Mudcats players will celebrate this new era in franchise history with a specialty themed Brewers jersey presented by Walmart that will be auctioned off with the net proceeds benefiting the Children's Miracle Network.

Buy tickets here  https //stza.co/~w0l1

Follow on MiLB First Pitch  https //stza.co/+w0l1-L

Shop  https //stza.co/+w0l1-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Blue Rocks
END:VALARM
DTSTART:20180511T230000Z
DTEND:20180512T020000Z
UID:ket_eBmvqoEOUeypcSkfZcNS@stanza.co
SUMMARY:Mudcats vs. Blue Rocks
DESCRIPTION:Stay after the game and enjoy fireworks shows after every Friday home game.\n\nIt's a new era in Mudcats history as we enter our first year under the new ownership of the Milwaukee Brewers. The Mudcats players will celebrate this new era in franchise history with a specialty themed Brewers jersey presented by Walmart that will be auctioned off with the net proceeds benefiting the Children's Miracle Network.\n\nBuy tickets here: https://stza.co/~w0l1\n\nFollow on MiLB First Pitch: https://stza.co/+w0l1-L\n\nShop: https://stza.co/+w0l1-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Celebrate the start of the weekend with our Friday Night Fireworks after the game!
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Blue Rocks
<2018-05-12 Sat 16:00-19:00>
:PROPERTIES:
:ID:       bIQ4uEjbz3d5eljVqX5_WgEM@stanza.co
:LOCATION: Brewers Weekend
:STATUS:   CONFIRMED
:END:

Mudcats vs. Blue Rocks It's a new era in Mudcats history as we enter our first year under the new ownership of the Milwaukee Brewers. The Mudcats players will celebrate this new era in franchise history with a specialty themed Brewers jersey presented by Walmart that will be auctioned off with the net proceeds benefiting the Children's Miracle Network.

Also, the first 1,200 fans 15 and over will receive a one a kind Mudcats and Brewers themed shirt! 

Buy tickets here  https //stza.co/~w0l3

Follow on MiLB First Pitch  https //stza.co/+w0l3-2O

Shop  https //stza.co/+w0l3-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Blue Rocks
END:VALARM
DTSTART:20180512T210000Z
DTEND:20180513T000000Z
UID:bIQ4uEjbz3d5eljVqX5_WgEM@stanza.co
SUMMARY:Mudcats vs. Blue Rocks
DESCRIPTION:It's a new era in Mudcats history as we enter our first year under the new ownership of the Milwaukee Brewers. The Mudcats players will celebrate this new era in franchise history with a specialty themed Brewers jersey presented by Walmart that will be auctioned off with the net proceeds benefiting the Children's Miracle Network.\n\nAlso, the first 1,200 fans 15 and over will receive a one a kind Mudcats and Brewers themed shirt! \n\nBuy tickets here: https://stza.co/~w0l3\n\nFollow on MiLB First Pitch: https://stza.co/+w0l3-2O\n\nShop: https://stza.co/+w0l3-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Brewers Weekend
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Blue Rocks
<2018-05-13 Sun 13:00-16:00>
:PROPERTIES:
:ID:       8aC1j7X1TPpD8mwRaEA8FEuG@stanza.co
:LOCATION: Brewers Weekend
:STATUS:   CONFIRMED
:END:

Mudcats vs. Blue Rocks It's a new era in Mudcats history as we enter our first year under the new ownership of the Milwaukee Brewers. The Mudcats players will celebrate this new era in franchise history with a specialty themed Brewers jersey presented by Walmart that will be auctioned off with the net proceeds benefiting the Children's Miracle Network.

There is no place better place to take your mom then a game at Five County Stadium! The first 300 moms through the gates will receive a Mudcats prize.

Each kid that is part of the Muddy's Buddies Kids Club gets one free box seat ticket to every Sunday home game, excluding May 27th.  All-Star Members receive 1 Free Speed Pitch Pass & 1 Free Spin on the Prize Wheel by presenting their membership cards.

Buy tickets here  https //stza.co/~w0l4

Follow on MiLB First Pitch  https //stza.co/+w0l4-1R

Shop  https //stza.co/+w0l4-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Blue Rocks
END:VALARM
DTSTART:20180513T180000Z
DTEND:20180513T210000Z
UID:8aC1j7X1TPpD8mwRaEA8FEuG@stanza.co
SUMMARY:Mudcats vs. Blue Rocks
DESCRIPTION:It's a new era in Mudcats history as we enter our first year under the new ownership of the Milwaukee Brewers. The Mudcats players will celebrate this new era in franchise history with a specialty themed Brewers jersey presented by Walmart that will be auctioned off with the net proceeds benefiting the Children's Miracle Network.\n\nThere is no place better place to take your mom then a game at Five County Stadium! The first 300 moms through the gates will receive a Mudcats prize.\n\nEach kid that is part of the Muddy's Buddies Kids Club gets one free box seat ticket to every Sunday home game, excluding May 27th.  All-Star Members receive 1 Free Speed Pitch Pass & 1 Free Spin on the Prize Wheel by presenting their membership cards.\n\nBuy tickets here: https://stza.co/~w0l4\n\nFollow on MiLB First Pitch: https://stza.co/+w0l4-1R\n\nShop: https://stza.co/+w0l4-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Brewers Weekend
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Wood Ducks
<2018-05-15 Tue 18:00-21:00>
:PROPERTIES:
:ID:       nGosXtVG7o7VQyKTl-n2KPLj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mudcats @ Wood Ducks Mudcats @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0mJ-13

Shop  https //stza.co/+w0mJ-1w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Wood Ducks
END:VALARM
DTSTART:20180515T230000Z
DTEND:20180516T020000Z
UID:nGosXtVG7o7VQyKTl-n2KPLj@stanza.co
SUMMARY:Mudcats @ Wood Ducks
DESCRIPTION:Mudcats @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0mJ-13\n\nShop: https://stza.co/+w0mJ-1w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Wood Ducks
<2018-05-16 Wed 18:00-21:00>
:PROPERTIES:
:ID:       UtSEydwKn-YAHK1AoEIF62Xy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Wood Ducks Mudcats @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0mK-3

Shop  https //stza.co/+w0mK-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Wood Ducks
END:VALARM
DTSTART:20180516T230000Z
DTEND:20180517T020000Z
UID:UtSEydwKn-YAHK1AoEIF62Xy@stanza.co
SUMMARY:Mudcats @ Wood Ducks
DESCRIPTION:Mudcats @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0mK-3\n\nShop: https://stza.co/+w0mK-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Wood Ducks
<2018-05-17 Thu 18:00-21:00>
:PROPERTIES:
:ID:       92wafhXIJFQ3absi8B01EKCE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Wood Ducks Mudcats @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0mL-1s

Shop  https //stza.co/+w0mL-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Wood Ducks
END:VALARM
DTSTART:20180517T230000Z
DTEND:20180518T020000Z
UID:92wafhXIJFQ3absi8B01EKCE@stanza.co
SUMMARY:Mudcats @ Wood Ducks
DESCRIPTION:Mudcats @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0mL-1s\n\nShop: https://stza.co/+w0mL-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Astros
<2018-05-18 Fri 18:00-21:00>
:PROPERTIES:
:ID:       x6WQG_p_4SJ0Ca9SGDQZ5X5U@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mudcats @ Astros Mudcats @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM8F-1s

Shop  https //stza.co/+xM8F-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Astros
END:VALARM
DTSTART:20180518T230000Z
DTEND:20180519T020000Z
UID:x6WQG_p_4SJ0Ca9SGDQZ5X5U@stanza.co
SUMMARY:Mudcats @ Astros
DESCRIPTION:Mudcats @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM8F-1s\n\nShop: https://stza.co/+xM8F-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Astros
<2018-05-19 Sat 17:00-20:00>
:PROPERTIES:
:ID:       _Mm85nzD7QqZTQkH-5i9zG8m@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Astros Mudcats @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM8G-3E

Shop  https //stza.co/+xM8G-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Astros
END:VALARM
DTSTART:20180519T220000Z
DTEND:20180520T010000Z
UID:_Mm85nzD7QqZTQkH-5i9zG8m@stanza.co
SUMMARY:Mudcats @ Astros
DESCRIPTION:Mudcats @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM8G-3E\n\nShop: https://stza.co/+xM8G-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Astros
<2018-05-20 Sun 13:00-16:00>
:PROPERTIES:
:ID:       Z996vvjhrB2mBcu0vBLGrOna@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Astros Mudcats @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM8H-3n

Shop  https //stza.co/+xM8H-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Astros
END:VALARM
DTSTART:20180520T180000Z
DTEND:20180520T210000Z
UID:Z996vvjhrB2mBcu0vBLGrOna@stanza.co
SUMMARY:Mudcats @ Astros
DESCRIPTION:Mudcats @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM8H-3n\n\nShop: https://stza.co/+xM8H-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Wood Ducks
<2018-05-21 Mon 18:00-21:00>
:PROPERTIES:
:ID:       -n_zi1ouIKv2Z-IhxaYw-Hh3@stanza.co
:LOCATION: Marked Down Monday
:STATUS:   CONFIRMED
:END:

Mudcats vs. Wood Ducks Every Monday in 2018 is a Marked Down Monday.  All Box Seat tickets are just $8, either online or at the Five County Stadium Box Office.  Parking will also be free every Monday Night.  Marked Down Mondays also feature reduced price concession items to satisfy everyone's appetite.

Buy tickets here  https //stza.co/~w0l6

Follow on MiLB First Pitch  https //stza.co/+w0l6-1c

Shop  https //stza.co/+w0l6-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Wood Ducks
END:VALARM
DTSTART:20180521T230000Z
DTEND:20180522T020000Z
UID:-n_zi1ouIKv2Z-IhxaYw-Hh3@stanza.co
SUMMARY:Mudcats vs. Wood Ducks
DESCRIPTION:Every Monday in 2018 is a Marked Down Monday.  All Box Seat tickets are just $8, either online or at the Five County Stadium Box Office.  Parking will also be free every Monday Night.  Marked Down Mondays also feature reduced price concession items to satisfy everyone's appetite.\n\nBuy tickets here: https://stza.co/~w0l6\n\nFollow on MiLB First Pitch: https://stza.co/+w0l6-1c\n\nShop: https://stza.co/+w0l6-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Marked Down Monday
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Wood Ducks
<2018-05-22 Tue 18:00-21:00>
:PROPERTIES:
:ID:       a9q_JDsdgOkiHjdv3TIFKdGo@stanza.co
:LOCATION: Taco Tuesday
:STATUS:   CONFIRMED
:END:

Mudcats vs. Wood Ducks Fans can enjoy themselves with $1 tacos at the Taco Stand on the concourse.

Buy tickets here  https //stza.co/~w0l9

Follow on MiLB First Pitch  https //stza.co/+w0l9-2j

Shop  https //stza.co/+w0l9-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Wood Ducks
END:VALARM
DTSTART:20180522T230000Z
DTEND:20180523T020000Z
UID:a9q_JDsdgOkiHjdv3TIFKdGo@stanza.co
SUMMARY:Mudcats vs. Wood Ducks
DESCRIPTION:Fans can enjoy themselves with $1 tacos at the Taco Stand on the concourse.\n\nBuy tickets here: https://stza.co/~w0l9\n\nFollow on MiLB First Pitch: https://stza.co/+w0l9-2j\n\nShop: https://stza.co/+w0l9-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Taco Tuesday
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Wood Ducks
<2018-05-23 Wed 10:00-13:00>
:PROPERTIES:
:ID:       z1sRIhILvo_6FXLnfBIpNtw9@stanza.co
:LOCATION: Education Day
:STATUS:   CONFIRMED
:END:

Mudcats vs. Wood Ducks The Carolina Mudcats would like to invite your school to enjoy a day of exciting Minor League Baseball, learning, and an experience like no other! Education Day is scheduled for students of all ages.

Come out to a special 11am start time.

Buy tickets here  https //stza.co/~w0lb

Follow on MiLB First Pitch  https //stza.co/+w0lb-2x

Shop  https //stza.co/+w0lb-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Wood Ducks
END:VALARM
DTSTART:20180523T150000Z
DTEND:20180523T180000Z
UID:z1sRIhILvo_6FXLnfBIpNtw9@stanza.co
SUMMARY:Mudcats vs. Wood Ducks
DESCRIPTION:The Carolina Mudcats would like to invite your school to enjoy a day of exciting Minor League Baseball, learning, and an experience like no other! Education Day is scheduled for students of all ages.\n\nCome out to a special 11am start time.\n\nBuy tickets here: https://stza.co/~w0lb\n\nFollow on MiLB First Pitch: https://stza.co/+w0lb-2x\n\nShop: https://stza.co/+w0lb-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Education Day
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Wood Ducks
<2018-05-24 Thu 18:00-21:00>
:PROPERTIES:
:ID:       RJDFb1ZRHkSCb-fh7ZqFLkBq@stanza.co
:LOCATION: Thirsty Thursday
:STATUS:   CONFIRMED
:END:

Mudcats vs. Wood Ducks Sit back and enjoy a Mudcats game with some cold ones with 1/2 price draft beers and $1-12oz Coca-Cola fountain products.

Buy tickets here  https //stza.co/~w0ld

Follow on MiLB First Pitch  https //stza.co/+w0ld-1d

Shop  https //stza.co/+w0ld-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Wood Ducks
END:VALARM
DTSTART:20180524T230000Z
DTEND:20180525T020000Z
UID:RJDFb1ZRHkSCb-fh7ZqFLkBq@stanza.co
SUMMARY:Mudcats vs. Wood Ducks
DESCRIPTION:Sit back and enjoy a Mudcats game with some cold ones with 1/2 price draft beers and $1-12oz Coca-Cola fountain products.\n\nBuy tickets here: https://stza.co/~w0ld\n\nFollow on MiLB First Pitch: https://stza.co/+w0ld-1d\n\nShop: https://stza.co/+w0ld-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursday
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Pelicans
<2018-05-25 Fri 18:00-21:00>
:PROPERTIES:
:ID:       buFtuRSnR2tODueeM__DV2pO@stanza.co
:LOCATION: Celebrate the start of the weekend with our Friday Night Fireworks after the game!
:STATUS:   CONFIRMED
:END:

Mudcats vs. Pelicans Stay after the game and enjoy fireworks shows after every Friday home game.

Buy tickets here  https //stza.co/~w0le

Follow on MiLB First Pitch  https //stza.co/+w0le-2t

Shop  https //stza.co/+w0le-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Pelicans
END:VALARM
DTSTART:20180525T230000Z
DTEND:20180526T020000Z
UID:buFtuRSnR2tODueeM__DV2pO@stanza.co
SUMMARY:Mudcats vs. Pelicans
DESCRIPTION:Stay after the game and enjoy fireworks shows after every Friday home game.\n\nBuy tickets here: https://stza.co/~w0le\n\nFollow on MiLB First Pitch: https://stza.co/+w0le-2t\n\nShop: https://stza.co/+w0le-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Celebrate the start of the weekend with our Friday Night Fireworks after the game!
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Pelicans
<2018-05-26 Sat 16:00-19:00>
:PROPERTIES:
:ID:       9vsLSqy7DHbihdZyzh4D3kDR@stanza.co
:LOCATION: First Responder's Night
:STATUS:   CONFIRMED
:END:

Mudcats vs. Pelicans Join the Mudcats in thanking and recognizing all our local First Responders. Kids will have the opportunity to interact with Fire and Police demonstrations on the concourse pregame.

Buy tickets here  https //stza.co/~w0lh

Follow on MiLB First Pitch  https //stza.co/+w0lh-1B

Shop  https //stza.co/+w0lh-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Pelicans
END:VALARM
DTSTART:20180526T210000Z
DTEND:20180527T000000Z
UID:9vsLSqy7DHbihdZyzh4D3kDR@stanza.co
SUMMARY:Mudcats vs. Pelicans
DESCRIPTION:Join the Mudcats in thanking and recognizing all our local First Responders. Kids will have the opportunity to interact with Fire and Police demonstrations on the concourse pregame.\n\nBuy tickets here: https://stza.co/~w0lh\n\nFollow on MiLB First Pitch: https://stza.co/+w0lh-1B\n\nShop: https://stza.co/+w0lh-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:First Responder's Night
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Pelicans
<2018-05-27 Sun 17:00-20:00>
:PROPERTIES:
:ID:       l8k477GLdDFbFo2rRbMuXSu6@stanza.co
:LOCATION: Special 6pm Start Time
:STATUS:   CONFIRMED
:END:

Mudcats vs. Pelicans Come out to a special 6pm start time.

Stay after the game and enjoy a fireworks show to celebrate Memorial Day.

Buy tickets here  https //stza.co/~w0li

Follow on MiLB First Pitch  https //stza.co/+w0li-F

Shop  https //stza.co/+w0li-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Pelicans
END:VALARM
DTSTART:20180527T220000Z
DTEND:20180528T010000Z
UID:l8k477GLdDFbFo2rRbMuXSu6@stanza.co
SUMMARY:Mudcats vs. Pelicans
DESCRIPTION:Come out to a special 6pm start time.\n\nStay after the game and enjoy a fireworks show to celebrate Memorial Day.\n\nBuy tickets here: https://stza.co/~w0li\n\nFollow on MiLB First Pitch: https://stza.co/+w0li-F\n\nShop: https://stza.co/+w0li-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Special 6pm Start Time
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Pelicans
<2018-05-28 Mon 11:00-14:00>
:PROPERTIES:
:ID:       Ul-3rEcRBJiw8woKfW4PgSAE@stanza.co
:LOCATION: Memorial Day
:STATUS:   CONFIRMED
:END:

Mudcats vs. Pelicans Help us honor those who have made the ultimate sacrifice. The Mudcats will wear a patriotic themed jersey with the net proceeds benefiting Hire Heroes USA.

Come out to a special 12pm start time.

Buy tickets here  https //stza.co/~w0ll

Follow on MiLB First Pitch  https //stza.co/+w0ll-1M

Shop  https //stza.co/+w0ll-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Pelicans
END:VALARM
DTSTART:20180528T160000Z
DTEND:20180528T190000Z
UID:Ul-3rEcRBJiw8woKfW4PgSAE@stanza.co
SUMMARY:Mudcats vs. Pelicans
DESCRIPTION:Help us honor those who have made the ultimate sacrifice. The Mudcats will wear a patriotic themed jersey with the net proceeds benefiting Hire Heroes USA.\n\nCome out to a special 12pm start time.\n\nBuy tickets here: https://stza.co/~w0ll\n\nFollow on MiLB First Pitch: https://stza.co/+w0ll-1M\n\nShop: https://stza.co/+w0ll-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Memorial Day
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Hillcats
<2018-05-29 Tue 17:30-20:30>
:PROPERTIES:
:ID:       ZihJURAWAXEyROxmrpHeD3jt@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mudcats @ Hillcats Mudcats @ Hillcats

Buy tickets here  https //stza.co/~y3Th

Follow on MiLB First Pitch  https //stza.co/+y3Th-l

Shop  https //stza.co/+y3Th-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Hillcats
END:VALARM
DTSTART:20180529T223000Z
DTEND:20180530T013000Z
UID:ZihJURAWAXEyROxmrpHeD3jt@stanza.co
SUMMARY:Mudcats @ Hillcats
DESCRIPTION:Mudcats @ Hillcats\n\nBuy tickets here: https://stza.co/~y3Th\n\nFollow on MiLB First Pitch: https://stza.co/+y3Th-l\n\nShop: https://stza.co/+y3Th-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Hillcats
<2018-05-30 Wed 17:30-20:30>
:PROPERTIES:
:ID:       Jau6vL3G1wdQdzV7AwhRl-tI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Hillcats Mudcats @ Hillcats

Buy tickets here  https //stza.co/~y3Ti

Follow on MiLB First Pitch  https //stza.co/+y3Ti-3i

Shop  https //stza.co/+y3Ti-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Hillcats
END:VALARM
DTSTART:20180530T223000Z
DTEND:20180531T013000Z
UID:Jau6vL3G1wdQdzV7AwhRl-tI@stanza.co
SUMMARY:Mudcats @ Hillcats
DESCRIPTION:Mudcats @ Hillcats\n\nBuy tickets here: https://stza.co/~y3Ti\n\nFollow on MiLB First Pitch: https://stza.co/+y3Ti-3i\n\nShop: https://stza.co/+y3Ti-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Hillcats
<2018-05-31 Thu 17:30-20:30>
:PROPERTIES:
:ID:       8cjhlpyXJ1S_T2Jalvrp9fwI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Hillcats Mudcats @ Hillcats

Buy tickets here  https //stza.co/~y3Tj

Follow on MiLB First Pitch  https //stza.co/+y3Tj-3C

Shop  https //stza.co/+y3Tj-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Hillcats
END:VALARM
DTSTART:20180531T223000Z
DTEND:20180601T013000Z
UID:8cjhlpyXJ1S_T2Jalvrp9fwI@stanza.co
SUMMARY:Mudcats @ Hillcats
DESCRIPTION:Mudcats @ Hillcats\n\nBuy tickets here: https://stza.co/~y3Tj\n\nFollow on MiLB First Pitch: https://stza.co/+y3Tj-3C\n\nShop: https://stza.co/+y3Tj-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Dash
<2018-06-01 Fri 18:00-21:00>
:PROPERTIES:
:ID:       uMFShRyzolO2s28PXDWLOax1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mudcats @ Dash Mudcats @ Dash

Buy tickets here  https //stza.co/~w0np

Follow on MiLB First Pitch  https //stza.co/+w0np-Z

Shop  https //stza.co/+w0np-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Dash
END:VALARM
DTSTART:20180601T230000Z
DTEND:20180602T020000Z
UID:uMFShRyzolO2s28PXDWLOax1@stanza.co
SUMMARY:Mudcats @ Dash
DESCRIPTION:Mudcats @ Dash\n\nBuy tickets here: https://stza.co/~w0np\n\nFollow on MiLB First Pitch: https://stza.co/+w0np-Z\n\nShop: https://stza.co/+w0np-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Dash
<2018-06-02 Sat 17:00-20:00>
:PROPERTIES:
:ID:       A3FtXssMO6JZ0dBQWu88LNj4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Dash Mudcats @ Dash

Buy tickets here  https //stza.co/~w0nq

Follow on MiLB First Pitch  https //stza.co/+w0nq-2z

Shop  https //stza.co/+w0nq-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Dash
END:VALARM
DTSTART:20180602T220000Z
DTEND:20180603T010000Z
UID:A3FtXssMO6JZ0dBQWu88LNj4@stanza.co
SUMMARY:Mudcats @ Dash
DESCRIPTION:Mudcats @ Dash\n\nBuy tickets here: https://stza.co/~w0nq\n\nFollow on MiLB First Pitch: https://stza.co/+w0nq-2z\n\nShop: https://stza.co/+w0nq-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Dash
<2018-06-03 Sun 13:00-16:00>
:PROPERTIES:
:ID:       Ey3uz1jo5ntIGYsqXJst2_20@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Dash Mudcats @ Dash

Buy tickets here  https //stza.co/~w0nr

Follow on MiLB First Pitch  https //stza.co/+w0nr-3j

Shop  https //stza.co/+w0nr-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Dash
END:VALARM
DTSTART:20180603T180000Z
DTEND:20180603T210000Z
UID:Ey3uz1jo5ntIGYsqXJst2_20@stanza.co
SUMMARY:Mudcats @ Dash
DESCRIPTION:Mudcats @ Dash\n\nBuy tickets here: https://stza.co/~w0nr\n\nFollow on MiLB First Pitch: https://stza.co/+w0nr-3j\n\nShop: https://stza.co/+w0nr-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Wood Ducks
<2018-06-05 Tue 18:00-21:00>
:PROPERTIES:
:ID:       F12Ei5ST92uMEbeJSAOgwFV6@stanza.co
:LOCATION: Taco Tuesday
:STATUS:   CONFIRMED
:END:

Mudcats vs. Wood Ducks Fans can enjoy themselves with $1 tacos at the Taco Stand on the concourse.

Buy tickets here  https //stza.co/~w0ln

Follow on MiLB First Pitch  https //stza.co/+w0ln-2e

Shop  https //stza.co/+w0ln-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Wood Ducks
END:VALARM
DTSTART:20180605T230000Z
DTEND:20180606T020000Z
UID:F12Ei5ST92uMEbeJSAOgwFV6@stanza.co
SUMMARY:Mudcats vs. Wood Ducks
DESCRIPTION:Fans can enjoy themselves with $1 tacos at the Taco Stand on the concourse.\n\nBuy tickets here: https://stza.co/~w0ln\n\nFollow on MiLB First Pitch: https://stza.co/+w0ln-2e\n\nShop: https://stza.co/+w0ln-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Taco Tuesday
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Wood Ducks
<2018-06-06 Wed 18:00-21:00>
:PROPERTIES:
:ID:       5WbSPouU5dC7h21vwYYsCwwh@stanza.co
:LOCATION: Dollar Dog Day
:STATUS:   CONFIRMED
:END:

Mudcats vs. Wood Ducks Mudcat fans can enjoy $1 Bright Leaf Hot Dog at all concession locations.

Buy tickets here  https //stza.co/~w0lo

Follow on MiLB First Pitch  https //stza.co/+w0lo-J

Shop  https //stza.co/+w0lo-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Wood Ducks
END:VALARM
DTSTART:20180606T230000Z
DTEND:20180607T020000Z
UID:5WbSPouU5dC7h21vwYYsCwwh@stanza.co
SUMMARY:Mudcats vs. Wood Ducks
DESCRIPTION:Mudcat fans can enjoy $1 Bright Leaf Hot Dog at all concession locations.\n\nBuy tickets here: https://stza.co/~w0lo\n\nFollow on MiLB First Pitch: https://stza.co/+w0lo-J\n\nShop: https://stza.co/+w0lo-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dollar Dog Day
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Wood Ducks
<2018-06-07 Thu 18:00-21:00>
:PROPERTIES:
:ID:       pIy331q4XxGNvlpPZFmbhknp@stanza.co
:LOCATION: Thirsty Thursday
:STATUS:   CONFIRMED
:END:

Mudcats vs. Wood Ducks Sit back and enjoy a Mudcats game with some cold ones with 1/2 price draft beers and $1-12oz Coca-Cola fountain products.

Buy tickets here  https //stza.co/~w0lr

Follow on MiLB First Pitch  https //stza.co/+w0lr-3i

Shop  https //stza.co/+w0lr-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Wood Ducks
END:VALARM
DTSTART:20180607T230000Z
DTEND:20180608T020000Z
UID:pIy331q4XxGNvlpPZFmbhknp@stanza.co
SUMMARY:Mudcats vs. Wood Ducks
DESCRIPTION:Sit back and enjoy a Mudcats game with some cold ones with 1/2 price draft beers and $1-12oz Coca-Cola fountain products.\n\nBuy tickets here: https://stza.co/~w0lr\n\nFollow on MiLB First Pitch: https://stza.co/+w0lr-3i\n\nShop: https://stza.co/+w0lr-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursday
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Dash
<2018-06-08 Fri 18:00-21:00>
:PROPERTIES:
:ID:       ZppLoy9xYVz-13F8wyxsCONo@stanza.co
:LOCATION: Celebrate the start of the weekend with our Friday Night Fireworks after the game!
:STATUS:   CONFIRMED
:END:

Mudcats vs. Dash Stay after the game and enjoy fireworks shows after every Friday home game.

Join the Mudcats for the annual Girl Scout Overnight at Five County Stadium.  Watch the game against the Winston-Salem Dash followed by Friday Night Fireworks.  After the fireworks, a movie will be shown on the Mudzilla Videoboard.  Then the scouts will retire to their tents for the night.

Buy tickets here  https //stza.co/~w0lu

Follow on MiLB First Pitch  https //stza.co/+w0lu-3M

Shop  https //stza.co/+w0lu-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Dash
END:VALARM
DTSTART:20180608T230000Z
DTEND:20180609T020000Z
UID:ZppLoy9xYVz-13F8wyxsCONo@stanza.co
SUMMARY:Mudcats vs. Dash
DESCRIPTION:Stay after the game and enjoy fireworks shows after every Friday home game.\n\nJoin the Mudcats for the annual Girl Scout Overnight at Five County Stadium.  Watch the game against the Winston-Salem Dash followed by Friday Night Fireworks.  After the fireworks, a movie will be shown on the Mudzilla Videoboard.  Then the scouts will retire to their tents for the night.\n\nBuy tickets here: https://stza.co/~w0lu\n\nFollow on MiLB First Pitch: https://stza.co/+w0lu-3M\n\nShop: https://stza.co/+w0lu-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Celebrate the start of the weekend with our Friday Night Fireworks after the game!
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Dash
<2018-06-09 Sat 16:00-19:00>
:PROPERTIES:
:ID:       oA2n5zkTsmWNMUyvI-G0RBcK@stanza.co
:LOCATION: Gamer Night
:STATUS:   CONFIRMED
:END:

Mudcats vs. Dash Gamers of all ages will have a chance to win a free gaming console courtesy of the Mudcats on Gamer Night scheduled for Saturday, June 9 at Five County Stadium. The Mudcats' Gamer Night giveaway will include three PlayStation4 consoles, three Xbox One consoles and one  Xbox One X.

Buy tickets here  https //stza.co/~w0lw

Follow on MiLB First Pitch  https //stza.co/+w0lw-3S

Shop  https //stza.co/+w0lw-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Dash
END:VALARM
DTSTART:20180609T210000Z
DTEND:20180610T000000Z
UID:oA2n5zkTsmWNMUyvI-G0RBcK@stanza.co
SUMMARY:Mudcats vs. Dash
DESCRIPTION:Gamers of all ages will have a chance to win a free gaming console courtesy of the Mudcats on Gamer Night scheduled for Saturday, June 9 at Five County Stadium. The Mudcats' Gamer Night giveaway will include three PlayStation4 consoles, three Xbox One consoles and one  Xbox One X.\n\nBuy tickets here: https://stza.co/~w0lw\n\nFollow on MiLB First Pitch: https://stza.co/+w0lw-3S\n\nShop: https://stza.co/+w0lw-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Gamer Night
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Dash
<2018-06-10 Sun 13:00-16:00>
:PROPERTIES:
:ID:       VSdxT1BaRcvEcKWuqiA_L22-@stanza.co
:LOCATION: Bark in the Park
:STATUS:   CONFIRMED
:END:

Mudcats vs. Dash Its part one of our 2018 Bark in the Park series presented by Dirty Dogs Spa. Nothing beats Baseball and Dogs, so bring your four legged friend to the ballpark for just $5. 

Each kid that is part of the Muddy's Buddies Kids Club gets one free box seat ticket to every Sunday home game, excluding May 27th.  All-Star Members receive 1 Free Speed Pitch Pass & 1 Free Spin on the Prize Wheel by presenting their membership cards.

Buy tickets here  https //stza.co/~w0lx

Follow on MiLB First Pitch  https //stza.co/+w0lx-1d

Shop  https //stza.co/+w0lx-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Dash
END:VALARM
DTSTART:20180610T180000Z
DTEND:20180610T210000Z
UID:VSdxT1BaRcvEcKWuqiA_L22-@stanza.co
SUMMARY:Mudcats vs. Dash
DESCRIPTION:Its part one of our 2018 Bark in the Park series presented by Dirty Dogs Spa. Nothing beats Baseball and Dogs, so bring your four legged friend to the ballpark for just $5. \n\nEach kid that is part of the Muddy's Buddies Kids Club gets one free box seat ticket to every Sunday home game, excluding May 27th.  All-Star Members receive 1 Free Speed Pitch Pass & 1 Free Spin on the Prize Wheel by presenting their membership cards.\n\nBuy tickets here: https://stza.co/~w0lx\n\nFollow on MiLB First Pitch: https://stza.co/+w0lx-1d\n\nShop: https://stza.co/+w0lx-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Bark in the Park
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Astros
<2018-06-11 Mon 18:00-21:00>
:PROPERTIES:
:ID:       vlRoShlNqDFM-1mBNmBA3XmQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mudcats @ Astros Mudcats @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM8I-g

Shop  https //stza.co/+xM8I-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Astros
END:VALARM
DTSTART:20180611T230000Z
DTEND:20180612T020000Z
UID:vlRoShlNqDFM-1mBNmBA3XmQ@stanza.co
SUMMARY:Mudcats @ Astros
DESCRIPTION:Mudcats @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM8I-g\n\nShop: https://stza.co/+xM8I-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Astros
<2018-06-12 Tue 18:00-21:00>
:PROPERTIES:
:ID:       nBzQPrrxIpvley3JktPBn6Fr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Astros Mudcats @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM8J-3K

Shop  https //stza.co/+xM8J-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Astros
END:VALARM
DTSTART:20180612T230000Z
DTEND:20180613T020000Z
UID:nBzQPrrxIpvley3JktPBn6Fr@stanza.co
SUMMARY:Mudcats @ Astros
DESCRIPTION:Mudcats @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM8J-3K\n\nShop: https://stza.co/+xM8J-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Astros
<2018-06-13 Wed 18:00-21:00>
:PROPERTIES:
:ID:       HjGJEQtWkPz_eBct-e_FdxiR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Astros Mudcats @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM8K-2n

Shop  https //stza.co/+xM8K-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Astros
END:VALARM
DTSTART:20180613T230000Z
DTEND:20180614T020000Z
UID:HjGJEQtWkPz_eBct-e_FdxiR@stanza.co
SUMMARY:Mudcats @ Astros
DESCRIPTION:Mudcats @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM8K-2n\n\nShop: https://stza.co/+xM8K-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Pelicans
<2018-06-14 Thu>--<2018-06-13 Wed>
:PROPERTIES:
:ID:       MZHg7LVqV52Ijzjh7AF_JYVr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mudcats @ Pelicans Mudcats @ Pelicans

Follow on MiLB First Pitch  https //stza.co/+w0m$-3T

Shop  https //stza.co/+w0m$-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Pelicans
END:VALARM
DTSTART;VALUE=DATE:20180614
DTEND;VALUE=DATE:20180614
UID:MZHg7LVqV52Ijzjh7AF_JYVr@stanza.co
SUMMARY:Mudcats @ Pelicans
DESCRIPTION:Mudcats @ Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+w0m$-3T\n\nShop: https://stza.co/+w0m$-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Pelicans
<2018-06-15 Fri>--<2018-06-14 Thu>
:PROPERTIES:
:ID:       n_meKWs1ICjAK76Hlv83Y_YI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Pelicans Mudcats @ Pelicans

Follow on MiLB First Pitch  https //stza.co/+w0n0-J

Shop  https //stza.co/+w0n0-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Pelicans
END:VALARM
DTSTART;VALUE=DATE:20180615
DTEND;VALUE=DATE:20180615
UID:n_meKWs1ICjAK76Hlv83Y_YI@stanza.co
SUMMARY:Mudcats @ Pelicans
DESCRIPTION:Mudcats @ Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+w0n0-J\n\nShop: https://stza.co/+w0n0-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Pelicans
<2018-06-16 Sat>--<2018-06-15 Fri>
:PROPERTIES:
:ID:       r8Q6QOOEuW07VK7bYxnZkTcN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Pelicans Mudcats @ Pelicans

Follow on MiLB First Pitch  https //stza.co/+w0n1-2v

Shop  https //stza.co/+w0n1-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Pelicans
END:VALARM
DTSTART;VALUE=DATE:20180616
DTEND;VALUE=DATE:20180616
UID:r8Q6QOOEuW07VK7bYxnZkTcN@stanza.co
SUMMARY:Mudcats @ Pelicans
DESCRIPTION:Mudcats @ Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+w0n1-2v\n\nShop: https://stza.co/+w0n1-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Pelicans
<2018-06-17 Sun>--<2018-06-16 Sat>
:PROPERTIES:
:ID:       q28kqAx376MYxCJb294GijCV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mudcats @ Pelicans Mudcats @ Pelicans

Follow on MiLB First Pitch  https //stza.co/+w0n2-3k

Shop  https //stza.co/+w0n2-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Pelicans
END:VALARM
DTSTART;VALUE=DATE:20180617
DTEND;VALUE=DATE:20180617
UID:q28kqAx376MYxCJb294GijCV@stanza.co
SUMMARY:Mudcats @ Pelicans
DESCRIPTION:Mudcats @ Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+w0n2-3k\n\nShop: https://stza.co/+w0n2-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Astros
<2018-06-21 Thu 18:00-21:00>
:PROPERTIES:
:ID:       ifeo5TJcyo09kMhq9ukvFWUu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Astros Mudcats @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM8L-2f

Shop  https //stza.co/+xM8L-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Astros
END:VALARM
DTSTART:20180621T230000Z
DTEND:20180622T020000Z
UID:ifeo5TJcyo09kMhq9ukvFWUu@stanza.co
SUMMARY:Mudcats @ Astros
DESCRIPTION:Mudcats @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM8L-2f\n\nShop: https://stza.co/+xM8L-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Astros
<2018-06-22 Fri 18:00-21:00>
:PROPERTIES:
:ID:       Xthwf6VJJ45xxhVhVBrYqKNq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Astros Mudcats @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM8M-2a

Shop  https //stza.co/+xM8M-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Astros
END:VALARM
DTSTART:20180622T230000Z
DTEND:20180623T020000Z
UID:Xthwf6VJJ45xxhVhVBrYqKNq@stanza.co
SUMMARY:Mudcats @ Astros
DESCRIPTION:Mudcats @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM8M-2a\n\nShop: https://stza.co/+xM8M-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Astros
<2018-06-23 Sat 16:00-19:00>
:PROPERTIES:
:ID:       2H6HDbAfpx5oD_-aIy_Jq96c@stanza.co
:LOCATION: Honky Tonk Night
:STATUS:   CONFIRMED
:END:

Mudcats vs. Astros It will be a honky-tonking good time at Five County Stadium when the Mudcats go full country with Honky Tonk Night.

Also, the first 1,200 fans ages 15 and older will receive a free Mudcats themed cowboy hat as they arrive through the Five County Stadium gates.

Buy tickets here  https //stza.co/~w0lA

Follow on MiLB First Pitch  https //stza.co/+w0lA-23

Shop  https //stza.co/+w0lA-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Astros
END:VALARM
DTSTART:20180623T210000Z
DTEND:20180624T000000Z
UID:2H6HDbAfpx5oD_-aIy_Jq96c@stanza.co
SUMMARY:Mudcats vs. Astros
DESCRIPTION:It will be a honky-tonking good time at Five County Stadium when the Mudcats go full country with Honky Tonk Night.\n\nAlso, the first 1,200 fans ages 15 and older will receive a free Mudcats themed cowboy hat as they arrive through the Five County Stadium gates.\n\nBuy tickets here: https://stza.co/~w0lA\n\nFollow on MiLB First Pitch: https://stza.co/+w0lA-23\n\nShop: https://stza.co/+w0lA-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Honky Tonk Night
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Astros
<2018-06-24 Sun 13:00-16:00>
:PROPERTIES:
:ID:       tlma2ZKoXmGPqXyoyuq0Qt1j@stanza.co
:LOCATION: Muddy's Buddies Kids Club Sunday
:STATUS:   CONFIRMED
:END:

Mudcats vs. Astros Each kid that is part of the Muddy's Buddies Kids Club gets one free box seat ticket to every Sunday home game, excluding May 27th.  All-Star Members receive 1 Free Speed Pitch Pass & 1 Free Spin on the Prize Wheel by presenting their membership cards.

Buy tickets here  https //stza.co/~w0lB

Follow on MiLB First Pitch  https //stza.co/+w0lB-1w

Shop  https //stza.co/+w0lB-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Astros
END:VALARM
DTSTART:20180624T180000Z
DTEND:20180624T210000Z
UID:tlma2ZKoXmGPqXyoyuq0Qt1j@stanza.co
SUMMARY:Mudcats vs. Astros
DESCRIPTION:Each kid that is part of the Muddy's Buddies Kids Club gets one free box seat ticket to every Sunday home game, excluding May 27th.  All-Star Members receive 1 Free Speed Pitch Pass & 1 Free Spin on the Prize Wheel by presenting their membership cards.\n\nBuy tickets here: https://stza.co/~w0lB\n\nFollow on MiLB First Pitch: https://stza.co/+w0lB-1w\n\nShop: https://stza.co/+w0lB-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Muddy's Buddies Kids Club Sunday
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Red Sox
<2018-06-26 Tue>--<2018-06-25 Mon>
:PROPERTIES:
:ID:       gDqLwk6jgWvjV859qkz1by3_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mudcats @ Red Sox Mudcats @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0na-3m

Shop  https //stza.co/+w0na-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180626
DTEND;VALUE=DATE:20180626
UID:gDqLwk6jgWvjV859qkz1by3_@stanza.co
SUMMARY:Mudcats @ Red Sox
DESCRIPTION:Mudcats @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0na-3m\n\nShop: https://stza.co/+w0na-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Red Sox
<2018-06-27 Wed>--<2018-06-26 Tue>
:PROPERTIES:
:ID:       brijeon7zUx5t0nFdtz-LOYG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Red Sox Mudcats @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0nb-1X

Shop  https //stza.co/+w0nb-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180627
DTEND;VALUE=DATE:20180627
UID:brijeon7zUx5t0nFdtz-LOYG@stanza.co
SUMMARY:Mudcats @ Red Sox
DESCRIPTION:Mudcats @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0nb-1X\n\nShop: https://stza.co/+w0nb-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Red Sox
<2018-06-28 Thu>--<2018-06-27 Wed>
:PROPERTIES:
:ID:       TvjIT_HSq4EYIJqPEEEiYyIx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Red Sox Mudcats @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0nc-F

Shop  https //stza.co/+w0nc-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180628
DTEND;VALUE=DATE:20180628
UID:TvjIT_HSq4EYIJqPEEEiYyIx@stanza.co
SUMMARY:Mudcats @ Red Sox
DESCRIPTION:Mudcats @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0nc-F\n\nShop: https://stza.co/+w0nc-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Red Sox
<2018-06-29 Fri>--<2018-06-28 Thu>
:PROPERTIES:
:ID:       K11niK9SMdj42sDym_6dg7z1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mudcats @ Red Sox Mudcats @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0nd-1f

Shop  https //stza.co/+w0nd-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180629
DTEND;VALUE=DATE:20180629
UID:K11niK9SMdj42sDym_6dg7z1@stanza.co
SUMMARY:Mudcats @ Red Sox
DESCRIPTION:Mudcats @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0nd-1f\n\nShop: https://stza.co/+w0nd-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Astros
<2018-06-30 Sat 17:00-20:00>
:PROPERTIES:
:ID:       jgHg5kXcnoUwde-EoKFNUD5O@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Astros Mudcats @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM8N-3

Shop  https //stza.co/+xM8N-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Astros
END:VALARM
DTSTART:20180630T220000Z
DTEND:20180701T010000Z
UID:jgHg5kXcnoUwde-EoKFNUD5O@stanza.co
SUMMARY:Mudcats @ Astros
DESCRIPTION:Mudcats @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM8N-3\n\nShop: https://stza.co/+xM8N-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Astros
<2018-07-01 Sun 13:00-16:00>
:PROPERTIES:
:ID:       yC_2qQV_X09nX-QfzlwHQZYK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Astros Mudcats @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM8O-2y

Shop  https //stza.co/+xM8O-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Astros
END:VALARM
DTSTART:20180701T180000Z
DTEND:20180701T210000Z
UID:yC_2qQV_X09nX-QfzlwHQZYK@stanza.co
SUMMARY:Mudcats @ Astros
DESCRIPTION:Mudcats @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM8O-2y\n\nShop: https://stza.co/+xM8O-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Astros
<2018-07-02 Mon 18:00-21:00>
:PROPERTIES:
:ID:       eTG4CzeZCMuIRiYpBy-dwutG@stanza.co
:LOCATION: Marked Down Monday
:STATUS:   CONFIRMED
:END:

Mudcats vs. Astros Every Monday in 2018 is a Marked Down Monday.  All Box Seat tickets are just $8, either online or at the Five County Stadium Box Office.  Parking will also be free every Monday Night.  Marked Down Mondays also feature reduced price concession items to satisfy everyone's appetite.

Buy tickets here  https //stza.co/~w0lD

Follow on MiLB First Pitch  https //stza.co/+w0lD-1z

Shop  https //stza.co/+w0lD-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Astros
END:VALARM
DTSTART:20180702T230000Z
DTEND:20180703T020000Z
UID:eTG4CzeZCMuIRiYpBy-dwutG@stanza.co
SUMMARY:Mudcats vs. Astros
DESCRIPTION:Every Monday in 2018 is a Marked Down Monday.  All Box Seat tickets are just $8, either online or at the Five County Stadium Box Office.  Parking will also be free every Monday Night.  Marked Down Mondays also feature reduced price concession items to satisfy everyone's appetite.\n\nBuy tickets here: https://stza.co/~w0lD\n\nFollow on MiLB First Pitch: https://stza.co/+w0lD-1z\n\nShop: https://stza.co/+w0lD-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Marked Down Monday
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Astros
<2018-07-03 Tue 18:00-21:00>
:PROPERTIES:
:ID:       ri7S0Z1wtMYNmHvkbJ4r9rlY@stanza.co
:LOCATION: Mudcats for America Series
:STATUS:   CONFIRMED
:END:

Mudcats vs. Astros The Mudcats kick off night 1 of our celebration of America's Independence. The Mudcats will wear a patriotic themed jersey with the net proceeds benefiting Hire Heroes USA.  Also, make sure you stay afterwards for a fantastic fireworks extravaganza! 

Buy tickets here  https //stza.co/~w0lF

Follow on MiLB First Pitch  https //stza.co/+w0lF-3A

Shop  https //stza.co/+w0lF-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Astros
END:VALARM
DTSTART:20180703T230000Z
DTEND:20180704T020000Z
UID:ri7S0Z1wtMYNmHvkbJ4r9rlY@stanza.co
SUMMARY:Mudcats vs. Astros
DESCRIPTION:The Mudcats kick off night 1 of our celebration of America's Independence. The Mudcats will wear a patriotic themed jersey with the net proceeds benefiting Hire Heroes USA.  Also, make sure you stay afterwards for a fantastic fireworks extravaganza! \n\nBuy tickets here: https://stza.co/~w0lF\n\nFollow on MiLB First Pitch: https://stza.co/+w0lF-3A\n\nShop: https://stza.co/+w0lF-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Mudcats for America Series
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Keys
<2018-07-04 Wed 18:00-21:00>
:PROPERTIES:
:ID:       QBBIGVS-ocEorVbzmf_Pp8gL@stanza.co
:LOCATION: Mudcats for America Series
:STATUS:   CONFIRMED
:END:

Mudcats vs. Keys It's Independence Day at Five County Stadium! Nothing gets more American than baseball and fireworks! The Mudcats will wear a patriotic themed jersey with the net proceeds benefiting Hire Heroes USA.  Also, make sure you stay afterwards for a fantastic post-game fireworks extravaganza!

Buy tickets here  https //stza.co/~w0lH

Follow on MiLB First Pitch  https //stza.co/+w0lH-X

Shop  https //stza.co/+w0lH-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Keys
END:VALARM
DTSTART:20180704T230000Z
DTEND:20180705T020000Z
UID:QBBIGVS-ocEorVbzmf_Pp8gL@stanza.co
SUMMARY:Mudcats vs. Keys
DESCRIPTION:It's Independence Day at Five County Stadium! Nothing gets more American than baseball and fireworks! The Mudcats will wear a patriotic themed jersey with the net proceeds benefiting Hire Heroes USA.  Also, make sure you stay afterwards for a fantastic post-game fireworks extravaganza!\n\nBuy tickets here: https://stza.co/~w0lH\n\nFollow on MiLB First Pitch: https://stza.co/+w0lH-X\n\nShop: https://stza.co/+w0lH-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Mudcats for America Series
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Keys
<2018-07-05 Thu 18:00-21:00>
:PROPERTIES:
:ID:       Cs00On8bX_LkdC8dhvIVo5HJ@stanza.co
:LOCATION: Thirsty Thursday
:STATUS:   CONFIRMED
:END:

Mudcats vs. Keys Sit back and enjoy a Mudcats game with some cold ones with 1/2 price draft beers and $1-12oz Coca-Cola fountain products.

Buy tickets here  https //stza.co/~w0lK

Follow on MiLB First Pitch  https //stza.co/+w0lK-3R

Shop  https //stza.co/+w0lK-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Keys
END:VALARM
DTSTART:20180705T230000Z
DTEND:20180706T020000Z
UID:Cs00On8bX_LkdC8dhvIVo5HJ@stanza.co
SUMMARY:Mudcats vs. Keys
DESCRIPTION:Sit back and enjoy a Mudcats game with some cold ones with 1/2 price draft beers and $1-12oz Coca-Cola fountain products.\n\nBuy tickets here: https://stza.co/~w0lK\n\nFollow on MiLB First Pitch: https://stza.co/+w0lK-3R\n\nShop: https://stza.co/+w0lK-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursday
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Keys
<2018-07-06 Fri 18:00-21:00>
:PROPERTIES:
:ID:       _gJGpieHxJAts7whN0cQCUuO@stanza.co
:LOCATION: Celebrate the start of the weekend with our Friday Night Fireworks after the game!
:STATUS:   CONFIRMED
:END:

Mudcats vs. Keys Stay after the game and enjoy fireworks shows after every Friday home game.

Buy tickets here  https //stza.co/~w0lL

Follow on MiLB First Pitch  https //stza.co/+w0lL-1$

Shop  https //stza.co/+w0lL-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Keys
END:VALARM
DTSTART:20180706T230000Z
DTEND:20180707T020000Z
UID:_gJGpieHxJAts7whN0cQCUuO@stanza.co
SUMMARY:Mudcats vs. Keys
DESCRIPTION:Stay after the game and enjoy fireworks shows after every Friday home game.\n\nBuy tickets here: https://stza.co/~w0lL\n\nFollow on MiLB First Pitch: https://stza.co/+w0lL-1$\n\nShop: https://stza.co/+w0lL-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Celebrate the start of the weekend with our Friday Night Fireworks after the game!
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Keys
<2018-07-07 Sat 16:00-19:00>
:PROPERTIES:
:ID:       onv2zt04WJa7ZQ8U56Fxw2N_@stanza.co
:LOCATION: Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats vs. Keys Mudcats vs. Keys

Buy tickets here  https //stza.co/~w0lO

Follow on MiLB First Pitch  https //stza.co/+w0lO-1W

Shop  https //stza.co/+w0lO-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Keys
END:VALARM
DTSTART:20180707T210000Z
DTEND:20180708T000000Z
UID:onv2zt04WJa7ZQ8U56Fxw2N_@stanza.co
SUMMARY:Mudcats vs. Keys
DESCRIPTION:Mudcats vs. Keys\n\nBuy tickets here: https://stza.co/~w0lO\n\nFollow on MiLB First Pitch: https://stza.co/+w0lO-1W\n\nShop: https://stza.co/+w0lO-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Keys
<2018-07-08 Sun 13:00-16:00>
:PROPERTIES:
:ID:       Tj8ZYtW_9zN9oNNypdxZYuTO@stanza.co
:LOCATION: Muddy's Buddies Kids Club Sunday
:STATUS:   CONFIRMED
:END:

Mudcats vs. Keys Each kid that is part of the Muddy's Buddies Kids Club gets one free box seat ticket to every Sunday home game, excluding May 27th.  All-Star Members receive 1 Free Speed Pitch Pass & 1 Free Spin on the Prize Wheel by presenting their membership cards.

Buy tickets here  https //stza.co/~w0lQ

Follow on MiLB First Pitch  https //stza.co/+w0lQ-K

Shop  https //stza.co/+w0lQ-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Keys
END:VALARM
DTSTART:20180708T180000Z
DTEND:20180708T210000Z
UID:Tj8ZYtW_9zN9oNNypdxZYuTO@stanza.co
SUMMARY:Mudcats vs. Keys
DESCRIPTION:Each kid that is part of the Muddy's Buddies Kids Club gets one free box seat ticket to every Sunday home game, excluding May 27th.  All-Star Members receive 1 Free Speed Pitch Pass & 1 Free Spin on the Prize Wheel by presenting their membership cards.\n\nBuy tickets here: https://stza.co/~w0lQ\n\nFollow on MiLB First Pitch: https://stza.co/+w0lQ-K\n\nShop: https://stza.co/+w0lQ-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Muddy's Buddies Kids Club Sunday
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Pelicans
<2018-07-09 Mon>--<2018-07-08 Sun>
:PROPERTIES:
:ID:       r12nR-UyrWY__TmsyqIeT7NR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mudcats @ Pelicans Mudcats @ Pelicans

Follow on MiLB First Pitch  https //stza.co/+w0n3-b

Shop  https //stza.co/+w0n3-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Pelicans
END:VALARM
DTSTART;VALUE=DATE:20180709
DTEND;VALUE=DATE:20180709
UID:r12nR-UyrWY__TmsyqIeT7NR@stanza.co
SUMMARY:Mudcats @ Pelicans
DESCRIPTION:Mudcats @ Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+w0n3-b\n\nShop: https://stza.co/+w0n3-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Pelicans
<2018-07-10 Tue>--<2018-07-09 Mon>
:PROPERTIES:
:ID:       U-c8mrMlc4p37ilKULUnriPQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Pelicans Mudcats @ Pelicans

Follow on MiLB First Pitch  https //stza.co/+w0n4-1D

Shop  https //stza.co/+w0n4-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Pelicans
END:VALARM
DTSTART;VALUE=DATE:20180710
DTEND;VALUE=DATE:20180710
UID:U-c8mrMlc4p37ilKULUnriPQ@stanza.co
SUMMARY:Mudcats @ Pelicans
DESCRIPTION:Mudcats @ Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+w0n4-1D\n\nShop: https://stza.co/+w0n4-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Pelicans
<2018-07-11 Wed>--<2018-07-10 Tue>
:PROPERTIES:
:ID:       65DSr_aIV0TNDv9CWanwGE7C@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Pelicans Mudcats @ Pelicans

Follow on MiLB First Pitch  https //stza.co/+w0n5-2v

Shop  https //stza.co/+w0n5-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Pelicans
END:VALARM
DTSTART;VALUE=DATE:20180711
DTEND;VALUE=DATE:20180711
UID:65DSr_aIV0TNDv9CWanwGE7C@stanza.co
SUMMARY:Mudcats @ Pelicans
DESCRIPTION:Mudcats @ Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+w0n5-2v\n\nShop: https://stza.co/+w0n5-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Pelicans
<2018-07-12 Thu>--<2018-07-11 Wed>
:PROPERTIES:
:ID:       Kd8jf61q62QeWtxE6MFdUbZL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mudcats @ Pelicans Mudcats @ Pelicans

Follow on MiLB First Pitch  https //stza.co/+w0n6-1q

Shop  https //stza.co/+w0n6-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Pelicans
END:VALARM
DTSTART;VALUE=DATE:20180712
DTEND;VALUE=DATE:20180712
UID:Kd8jf61q62QeWtxE6MFdUbZL@stanza.co
SUMMARY:Mudcats @ Pelicans
DESCRIPTION:Mudcats @ Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+w0n6-1q\n\nShop: https://stza.co/+w0n6-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Hillcats
<2018-07-13 Fri 18:00-21:00>
:PROPERTIES:
:ID:       qC6exz1Mtd55UrsdLkmJ-kxV@stanza.co
:LOCATION: Celebrate the start of the weekend with our Friday Night Fireworks after the game!
:STATUS:   CONFIRMED
:END:

Mudcats vs. Hillcats Stay after the game and enjoy fireworks shows after every Friday home game.

The Layman's League has once again partnered with us to promote a day to help the Children's Home. During the game there will be bins set up at the stadium for people to bring paper/cleaning products for the Children's Home.

Buy tickets here  https //stza.co/~w0lS

Follow on MiLB First Pitch  https //stza.co/+w0lS-32

Shop  https //stza.co/+w0lS-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Hillcats
END:VALARM
DTSTART:20180713T230000Z
DTEND:20180714T020000Z
UID:qC6exz1Mtd55UrsdLkmJ-kxV@stanza.co
SUMMARY:Mudcats vs. Hillcats
DESCRIPTION:Stay after the game and enjoy fireworks shows after every Friday home game.\n\nThe Layman's League has once again partnered with us to promote a day to help the Children's Home. During the game there will be bins set up at the stadium for people to bring paper/cleaning products for the Children's Home.\n\nBuy tickets here: https://stza.co/~w0lS\n\nFollow on MiLB First Pitch: https://stza.co/+w0lS-32\n\nShop: https://stza.co/+w0lS-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Celebrate the start of the weekend with our Friday Night Fireworks after the game!
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Hillcats
<2018-07-14 Sat 16:00-19:00>
:PROPERTIES:
:ID:       911TAYM9URFSDN4z32IKwONo@stanza.co
:LOCATION: Battle of the Sauce Nights
:STATUS:   CONFIRMED
:END:

Mudcats vs. Hillcats It's time to end the debate! Which sauce is better, East Carolina BBQ sauce or West Carolina BBQ sauce? Fans will have a chance to vote on which sauce is better to determine the winner! 

Also, we will be giving away a one-of-a-kind Budweiser BBQ Mitt to the first 1,200 fans 21 and older that walk through the gates.

Buy tickets here  https //stza.co/~w0lU

Follow on MiLB First Pitch  https //stza.co/+w0lU-2Y

Shop  https //stza.co/+w0lU-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Hillcats
END:VALARM
DTSTART:20180714T210000Z
DTEND:20180715T000000Z
UID:911TAYM9URFSDN4z32IKwONo@stanza.co
SUMMARY:Mudcats vs. Hillcats
DESCRIPTION:It's time to end the debate! Which sauce is better, East Carolina BBQ sauce or West Carolina BBQ sauce? Fans will have a chance to vote on which sauce is better to determine the winner! \n\nAlso, we will be giving away a one-of-a-kind Budweiser BBQ Mitt to the first 1,200 fans 21 and older that walk through the gates.\n\nBuy tickets here: https://stza.co/~w0lU\n\nFollow on MiLB First Pitch: https://stza.co/+w0lU-2Y\n\nShop: https://stza.co/+w0lU-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Battle of the Sauce Nights
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Hillcats
<2018-07-15 Sun 13:00-16:00>
:PROPERTIES:
:ID:       jeve_UK2kGLW-KSHFAq7-scL@stanza.co
:LOCATION: Muddy's Buddies Kids Club Sunday
:STATUS:   CONFIRMED
:END:

Mudcats vs. Hillcats Each kid that is part of the Muddy's Buddies Kids Club gets one free box seat ticket to every Sunday home game, excluding May 27th.  All-Star Members receive 1 Free Speed Pitch Pass & 1 Free Spin on the Prize Wheel by presenting their membership cards.

Buy tickets here  https //stza.co/~w0lW

Follow on MiLB First Pitch  https //stza.co/+w0lW-u

Shop  https //stza.co/+w0lW-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Hillcats
END:VALARM
DTSTART:20180715T180000Z
DTEND:20180715T210000Z
UID:jeve_UK2kGLW-KSHFAq7-scL@stanza.co
SUMMARY:Mudcats vs. Hillcats
DESCRIPTION:Each kid that is part of the Muddy's Buddies Kids Club gets one free box seat ticket to every Sunday home game, excluding May 27th.  All-Star Members receive 1 Free Speed Pitch Pass & 1 Free Spin on the Prize Wheel by presenting their membership cards.\n\nBuy tickets here: https://stza.co/~w0lW\n\nFollow on MiLB First Pitch: https://stza.co/+w0lW-u\n\nShop: https://stza.co/+w0lW-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Muddy's Buddies Kids Club Sunday
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Hillcats
<2018-07-16 Mon 18:00-21:00>
:PROPERTIES:
:ID:       W8XSBDflu2Dobv3q6jfQh2oK@stanza.co
:LOCATION: Marked Down Monday
:STATUS:   CONFIRMED
:END:

Mudcats vs. Hillcats Every Monday in 2018 is a Marked Down Monday.  All Box Seat tickets are just $8, either online or at the Five County Stadium Box Office.  Parking will also be free every Monday Night.  Marked Down Mondays also feature reduced price concession items to satisfy everyone's appetite.

Buy tickets here  https //stza.co/~w0lY

Follow on MiLB First Pitch  https //stza.co/+w0lY-k

Shop  https //stza.co/+w0lY-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Hillcats
END:VALARM
DTSTART:20180716T230000Z
DTEND:20180717T020000Z
UID:W8XSBDflu2Dobv3q6jfQh2oK@stanza.co
SUMMARY:Mudcats vs. Hillcats
DESCRIPTION:Every Monday in 2018 is a Marked Down Monday.  All Box Seat tickets are just $8, either online or at the Five County Stadium Box Office.  Parking will also be free every Monday Night.  Marked Down Mondays also feature reduced price concession items to satisfy everyone's appetite.\n\nBuy tickets here: https://stza.co/~w0lY\n\nFollow on MiLB First Pitch: https://stza.co/+w0lY-k\n\nShop: https://stza.co/+w0lY-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Marked Down Monday
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Dash
<2018-07-18 Wed 18:00-21:00>
:PROPERTIES:
:ID:       2wydVaxzotjzdfWWMLlipWxB@stanza.co
:LOCATION: Dollar Dog Day
:STATUS:   CONFIRMED
:END:

Mudcats vs. Dash Mudcat fans can enjoy $1 Bright Leaf Hot Dog at all concession locations.

Buy tickets here  https //stza.co/~w0l_

Follow on MiLB First Pitch  https //stza.co/+w0l_-2h

Shop  https //stza.co/+w0l_-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Dash
END:VALARM
DTSTART:20180718T230000Z
DTEND:20180719T020000Z
UID:2wydVaxzotjzdfWWMLlipWxB@stanza.co
SUMMARY:Mudcats vs. Dash
DESCRIPTION:Mudcat fans can enjoy $1 Bright Leaf Hot Dog at all concession locations.\n\nBuy tickets here: https://stza.co/~w0l_\n\nFollow on MiLB First Pitch: https://stza.co/+w0l_-2h\n\nShop: https://stza.co/+w0l_-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dollar Dog Day
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Dash
<2018-07-19 Thu 18:00-21:00>
:PROPERTIES:
:ID:       4hEEkjLQYK6lD09SYFrG8RTK@stanza.co
:LOCATION: Thirsty Thursday
:STATUS:   CONFIRMED
:END:

Mudcats vs. Dash Sit back and enjoy a Mudcats game with some cold ones with 1/2 price draft beers and $1-12oz Coca-Cola fountain products.

Buy tickets here  https //stza.co/~w0l$

Follow on MiLB First Pitch  https //stza.co/+w0l$-3T

Shop  https //stza.co/+w0l$-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Dash
END:VALARM
DTSTART:20180719T230000Z
DTEND:20180720T020000Z
UID:4hEEkjLQYK6lD09SYFrG8RTK@stanza.co
SUMMARY:Mudcats vs. Dash
DESCRIPTION:Sit back and enjoy a Mudcats game with some cold ones with 1/2 price draft beers and $1-12oz Coca-Cola fountain products.\n\nBuy tickets here: https://stza.co/~w0l$\n\nFollow on MiLB First Pitch: https://stza.co/+w0l$-3T\n\nShop: https://stza.co/+w0l$-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursday
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Dash
<2018-07-20 Fri 18:00-21:00>
:PROPERTIES:
:ID:       cJJatTeCbqnAHpZxkfZBNsqP@stanza.co
:LOCATION: Celebrate the start of the weekend with our Friday Night Fireworks after the game!
:STATUS:   CONFIRMED
:END:

Mudcats vs. Dash Stay after the game and enjoy fireworks shows after every Friday home game.

It's SANTA! That's right the we are bringing a piece of the north pole to Five County Stadium where Santa Claus will be in the house giving away Mudcats gifts for all the good boys and girls in attendance.

Buy tickets here  https //stza.co/~w0m1

Follow on MiLB First Pitch  https //stza.co/+w0m1-1V

Shop  https //stza.co/+w0m1-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Dash
END:VALARM
DTSTART:20180720T230000Z
DTEND:20180721T020000Z
UID:cJJatTeCbqnAHpZxkfZBNsqP@stanza.co
SUMMARY:Mudcats vs. Dash
DESCRIPTION:Stay after the game and enjoy fireworks shows after every Friday home game.\n\nIt's SANTA! That's right the we are bringing a piece of the north pole to Five County Stadium where Santa Claus will be in the house giving away Mudcats gifts for all the good boys and girls in attendance.\n\nBuy tickets here: https://stza.co/~w0m1\n\nFollow on MiLB First Pitch: https://stza.co/+w0m1-1V\n\nShop: https://stza.co/+w0m1-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Celebrate the start of the weekend with our Friday Night Fireworks after the game!
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Hillcats
<2018-07-21 Sat 17:00-20:00>
:PROPERTIES:
:ID:       rlzGH3TTocvFP2Bm02DkLpQJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Hillcats Mudcats @ Hillcats

Buy tickets here  https //stza.co/~y3Tk

Follow on MiLB First Pitch  https //stza.co/+y3Tk-y

Shop  https //stza.co/+y3Tk-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Hillcats
END:VALARM
DTSTART:20180721T220000Z
DTEND:20180722T010000Z
UID:rlzGH3TTocvFP2Bm02DkLpQJ@stanza.co
SUMMARY:Mudcats @ Hillcats
DESCRIPTION:Mudcats @ Hillcats\n\nBuy tickets here: https://stza.co/~y3Tk\n\nFollow on MiLB First Pitch: https://stza.co/+y3Tk-y\n\nShop: https://stza.co/+y3Tk-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Hillcats
<2018-07-22 Sun 16:00-19:00>
:PROPERTIES:
:ID:       ES34GzKwtZSReWDgrqRAoygX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Hillcats Mudcats @ Hillcats

Buy tickets here  https //stza.co/~y3Tl

Follow on MiLB First Pitch  https //stza.co/+y3Tl-M

Shop  https //stza.co/+y3Tl-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Hillcats
END:VALARM
DTSTART:20180722T210000Z
DTEND:20180723T000000Z
UID:ES34GzKwtZSReWDgrqRAoygX@stanza.co
SUMMARY:Mudcats @ Hillcats
DESCRIPTION:Mudcats @ Hillcats\n\nBuy tickets here: https://stza.co/~y3Tl\n\nFollow on MiLB First Pitch: https://stza.co/+y3Tl-M\n\nShop: https://stza.co/+y3Tl-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Hillcats
<2018-07-23 Mon 17:30-20:30>
:PROPERTIES:
:ID:       ZWWY7vFD00BQygQ2hSaagCOC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mudcats @ Hillcats Mudcats @ Hillcats

Buy tickets here  https //stza.co/~y3Tm

Follow on MiLB First Pitch  https //stza.co/+y3Tm-1B

Shop  https //stza.co/+y3Tm-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Hillcats
END:VALARM
DTSTART:20180723T223000Z
DTEND:20180724T013000Z
UID:ZWWY7vFD00BQygQ2hSaagCOC@stanza.co
SUMMARY:Mudcats @ Hillcats
DESCRIPTION:Mudcats @ Hillcats\n\nBuy tickets here: https://stza.co/~y3Tm\n\nFollow on MiLB First Pitch: https://stza.co/+y3Tm-1B\n\nShop: https://stza.co/+y3Tm-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Pelicans
<2018-07-24 Tue 18:00-21:00>
:PROPERTIES:
:ID:       u0sJUFirvQtf-ss4bdwffUBf@stanza.co
:LOCATION: Taco Tuesday
:STATUS:   CONFIRMED
:END:

Mudcats vs. Pelicans Fans can enjoy themselves with $1 tacos at the Taco Stand on the concourse.

Buy tickets here  https //stza.co/~w0m3

Follow on MiLB First Pitch  https //stza.co/+w0m3-1s

Shop  https //stza.co/+w0m3-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Pelicans
END:VALARM
DTSTART:20180724T230000Z
DTEND:20180725T020000Z
UID:u0sJUFirvQtf-ss4bdwffUBf@stanza.co
SUMMARY:Mudcats vs. Pelicans
DESCRIPTION:Fans can enjoy themselves with $1 tacos at the Taco Stand on the concourse.\n\nBuy tickets here: https://stza.co/~w0m3\n\nFollow on MiLB First Pitch: https://stza.co/+w0m3-1s\n\nShop: https://stza.co/+w0m3-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Taco Tuesday
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Pelicans
<2018-07-25 Wed 10:00-13:00>
:PROPERTIES:
:ID:       t8lpttQbvermznHNH-QJJJeS@stanza.co
:LOCATION: Super Splash Day
:STATUS:   CONFIRMED
:END:

Mudcats vs. Pelicans The Carolina Mudcats would like to invite your camp to enjoy a day of exciting Minor League Baseball, wet n' wild fun and an experience like no other!  Camp-Splash Day is scheduled for students of all ages. 

Come out to a special 11am start time.

Buy tickets here  https //stza.co/~w0m6

Follow on MiLB First Pitch  https //stza.co/+w0m6-2o

Shop  https //stza.co/+w0m6-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Pelicans
END:VALARM
DTSTART:20180725T150000Z
DTEND:20180725T180000Z
UID:t8lpttQbvermznHNH-QJJJeS@stanza.co
SUMMARY:Mudcats vs. Pelicans
DESCRIPTION:The Carolina Mudcats would like to invite your camp to enjoy a day of exciting Minor League Baseball, wet n' wild fun and an experience like no other!  Camp-Splash Day is scheduled for students of all ages. \n\nCome out to a special 11am start time.\n\nBuy tickets here: https://stza.co/~w0m6\n\nFollow on MiLB First Pitch: https://stza.co/+w0m6-2o\n\nShop: https://stza.co/+w0m6-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Super Splash Day
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Pelicans
<2018-07-26 Thu 18:00-21:00>
:PROPERTIES:
:ID:       yb8zXnmPFUvD_NFR28czP3Bu@stanza.co
:LOCATION: Thirsty Thursday
:STATUS:   CONFIRMED
:END:

Mudcats vs. Pelicans Sit back and enjoy a Mudcats game with some cold ones with 1/2 price draft beers and $1-12oz Coca-Cola fountain products.

Its part one of our 2018 Bark in the Park series presented by Dirty Dogs Spa. Nothing beats Baseball and Dogs, so bring your four legged friend to the ballpark for just $5. 

Buy tickets here  https //stza.co/~w0m8

Follow on MiLB First Pitch  https //stza.co/+w0m8-T

Shop  https //stza.co/+w0m8-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Pelicans
END:VALARM
DTSTART:20180726T230000Z
DTEND:20180727T020000Z
UID:yb8zXnmPFUvD_NFR28czP3Bu@stanza.co
SUMMARY:Mudcats vs. Pelicans
DESCRIPTION:Sit back and enjoy a Mudcats game with some cold ones with 1/2 price draft beers and $1-12oz Coca-Cola fountain products.\n\nIts part one of our 2018 Bark in the Park series presented by Dirty Dogs Spa. Nothing beats Baseball and Dogs, so bring your four legged friend to the ballpark for just $5. \n\nBuy tickets here: https://stza.co/~w0m8\n\nFollow on MiLB First Pitch: https://stza.co/+w0m8-T\n\nShop: https://stza.co/+w0m8-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursday
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Nationals
<2018-07-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       rkbsGqGdAxkCU2gIQ_0ek3R-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Nationals Mudcats @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xA28-2q

Shop  https //stza.co/+xA28-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Nationals
END:VALARM
DTSTART:20180727T230500Z
DTEND:20180728T020500Z
UID:rkbsGqGdAxkCU2gIQ_0ek3R-@stanza.co
SUMMARY:Mudcats @ Nationals
DESCRIPTION:Mudcats @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xA28-2q\n\nShop: https://stza.co/+xA28-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Nationals
<2018-07-28 Sat 17:35-20:35>
:PROPERTIES:
:ID:       Z_MtbGBQIIGBjigM5uvmazw-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Nationals Mudcats @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xA29-12

Shop  https //stza.co/+xA29-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Nationals
END:VALARM
DTSTART:20180728T223500Z
DTEND:20180729T013500Z
UID:Z_MtbGBQIIGBjigM5uvmazw-@stanza.co
SUMMARY:Mudcats @ Nationals
DESCRIPTION:Mudcats @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xA29-12\n\nShop: https://stza.co/+xA29-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Nationals
<2018-07-29 Sun 12:05-15:05>
:PROPERTIES:
:ID:       bi9fj2fFrptNgBURW5J9O00B@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mudcats @ Nationals Mudcats @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xA2b-3B

Shop  https //stza.co/+xA2b-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Nationals
END:VALARM
DTSTART:20180729T170500Z
DTEND:20180729T200500Z
UID:bi9fj2fFrptNgBURW5J9O00B@stanza.co
SUMMARY:Mudcats @ Nationals
DESCRIPTION:Mudcats @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xA2b-3B\n\nShop: https://stza.co/+xA2b-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Dash
<2018-07-31 Tue 18:00-21:00>
:PROPERTIES:
:ID:       w1XWbJUC6xfPh35vB62tTGPk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Dash Mudcats @ Dash

Buy tickets here  https //stza.co/~w0ns

Follow on MiLB First Pitch  https //stza.co/+w0ns-3B

Shop  https //stza.co/+w0ns-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Dash
END:VALARM
DTSTART:20180731T230000Z
DTEND:20180801T020000Z
UID:w1XWbJUC6xfPh35vB62tTGPk@stanza.co
SUMMARY:Mudcats @ Dash
DESCRIPTION:Mudcats @ Dash\n\nBuy tickets here: https://stza.co/~w0ns\n\nFollow on MiLB First Pitch: https://stza.co/+w0ns-3B\n\nShop: https://stza.co/+w0ns-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Dash
<2018-08-01 Wed 18:00-21:00>
:PROPERTIES:
:ID:       SukayM6GSew6OW-J5gxPWDhg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Dash Mudcats @ Dash

Buy tickets here  https //stza.co/~w0nt

Follow on MiLB First Pitch  https //stza.co/+w0nt-3d

Shop  https //stza.co/+w0nt-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Dash
END:VALARM
DTSTART:20180801T230000Z
DTEND:20180802T020000Z
UID:SukayM6GSew6OW-J5gxPWDhg@stanza.co
SUMMARY:Mudcats @ Dash
DESCRIPTION:Mudcats @ Dash\n\nBuy tickets here: https://stza.co/~w0nt\n\nFollow on MiLB First Pitch: https://stza.co/+w0nt-3d\n\nShop: https://stza.co/+w0nt-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Dash
<2018-08-02 Thu 18:00-21:00>
:PROPERTIES:
:ID:       gFChrQoy2Zgb7PXQgNd3H6Pv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mudcats @ Dash Mudcats @ Dash

Buy tickets here  https //stza.co/~w0nu

Follow on MiLB First Pitch  https //stza.co/+w0nu-1S

Shop  https //stza.co/+w0nu-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Dash
END:VALARM
DTSTART:20180802T230000Z
DTEND:20180803T020000Z
UID:gFChrQoy2Zgb7PXQgNd3H6Pv@stanza.co
SUMMARY:Mudcats @ Dash
DESCRIPTION:Mudcats @ Dash\n\nBuy tickets here: https://stza.co/~w0nu\n\nFollow on MiLB First Pitch: https://stza.co/+w0nu-1S\n\nShop: https://stza.co/+w0nu-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Red Sox
<2018-08-03 Fri 18:00-21:00>
:PROPERTIES:
:ID:       EuLfTz4NgYFUpV98zQ-gaYLa@stanza.co
:LOCATION: Celebrate the start of the weekend with our Friday Night Fireworks after the game!
:STATUS:   CONFIRMED
:END:

Mudcats vs. Red Sox Stay after the game and enjoy fireworks shows after every Friday home game.

Come out celebrate Muddy the Mudcat's birthday with a bunch of his mascot friends.

Buy tickets here  https //stza.co/~w0m9

Follow on MiLB First Pitch  https //stza.co/+w0m9-1o

Shop  https //stza.co/+w0m9-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Red Sox
END:VALARM
DTSTART:20180803T230000Z
DTEND:20180804T020000Z
UID:EuLfTz4NgYFUpV98zQ-gaYLa@stanza.co
SUMMARY:Mudcats vs. Red Sox
DESCRIPTION:Stay after the game and enjoy fireworks shows after every Friday home game.\n\nCome out celebrate Muddy the Mudcat's birthday with a bunch of his mascot friends.\n\nBuy tickets here: https://stza.co/~w0m9\n\nFollow on MiLB First Pitch: https://stza.co/+w0m9-1o\n\nShop: https://stza.co/+w0m9-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Celebrate the start of the weekend with our Friday Night Fireworks after the game!
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Red Sox
<2018-08-04 Sat 16:00-19:00>
:PROPERTIES:
:ID:       f0yTA8LSdg0ahiQbC54ROQcr@stanza.co
:LOCATION: Rock N' Roll Tribute Night
:STATUS:   CONFIRMED
:END:

Mudcats vs. Red Sox Join the Mudcats as we will be rocking out all night to the greatest hits in Rock N' Roll history! The Mudcats will wear a Rock N' Roll Themed Jersey with the net proceeds benefiting a local charity.

Also, the first 1,200 kids age 14 and under will receive a free souvenir Mudcats' themed aviator sun glasses!

Buy tickets here  https //stza.co/~w0mc

Follow on MiLB First Pitch  https //stza.co/+w0mc-Z

Shop  https //stza.co/+w0mc-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Red Sox
END:VALARM
DTSTART:20180804T210000Z
DTEND:20180805T000000Z
UID:f0yTA8LSdg0ahiQbC54ROQcr@stanza.co
SUMMARY:Mudcats vs. Red Sox
DESCRIPTION:Join the Mudcats as we will be rocking out all night to the greatest hits in Rock N' Roll history! The Mudcats will wear a Rock N' Roll Themed Jersey with the net proceeds benefiting a local charity.\n\nAlso, the first 1,200 kids age 14 and under will receive a free souvenir Mudcats' themed aviator sun glasses!\n\nBuy tickets here: https://stza.co/~w0mc\n\nFollow on MiLB First Pitch: https://stza.co/+w0mc-Z\n\nShop: https://stza.co/+w0mc-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Rock N' Roll Tribute Night
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Red Sox
<2018-08-05 Sun 13:00-16:00>
:PROPERTIES:
:ID:       ZtnWUOPBz0Q1V3djGaEx4KrV@stanza.co
:LOCATION: Muddy's Buddies Kids Club Sunday
:STATUS:   CONFIRMED
:END:

Mudcats vs. Red Sox Each kid that is part of the Muddy's Buddies Kids Club gets one free box seat ticket to every Sunday home game, excluding May 27th.  All-Star Members receive 1 Free Speed Pitch Pass & 1 Free Spin on the Prize Wheel by presenting their membership cards.

Buy tickets here  https //stza.co/~w0md

Follow on MiLB First Pitch  https //stza.co/+w0md-1a

Shop  https //stza.co/+w0md-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Red Sox
END:VALARM
DTSTART:20180805T180000Z
DTEND:20180805T210000Z
UID:ZtnWUOPBz0Q1V3djGaEx4KrV@stanza.co
SUMMARY:Mudcats vs. Red Sox
DESCRIPTION:Each kid that is part of the Muddy's Buddies Kids Club gets one free box seat ticket to every Sunday home game, excluding May 27th.  All-Star Members receive 1 Free Speed Pitch Pass & 1 Free Spin on the Prize Wheel by presenting their membership cards.\n\nBuy tickets here: https://stza.co/~w0md\n\nFollow on MiLB First Pitch: https://stza.co/+w0md-1a\n\nShop: https://stza.co/+w0md-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Muddy's Buddies Kids Club Sunday
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Hillcats
<2018-08-06 Mon 18:00-21:00>
:PROPERTIES:
:ID:       c83av4rVCBbuf6bEAzurbLuw@stanza.co
:LOCATION: Marked Down Monday
:STATUS:   CONFIRMED
:END:

Mudcats vs. Hillcats Every Monday in 2018 is a Marked Down Monday.  All Box Seat tickets are just $8, either online or at the Five County Stadium Box Office.  Parking will also be free every Monday Night.  Marked Down Mondays also feature reduced price concession items to satisfy everyone's appetite.

Buy tickets here  https //stza.co/~w0mg

Follow on MiLB First Pitch  https //stza.co/+w0mg-1w

Shop  https //stza.co/+w0mg-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Hillcats
END:VALARM
DTSTART:20180806T230000Z
DTEND:20180807T020000Z
UID:c83av4rVCBbuf6bEAzurbLuw@stanza.co
SUMMARY:Mudcats vs. Hillcats
DESCRIPTION:Every Monday in 2018 is a Marked Down Monday.  All Box Seat tickets are just $8, either online or at the Five County Stadium Box Office.  Parking will also be free every Monday Night.  Marked Down Mondays also feature reduced price concession items to satisfy everyone's appetite.\n\nBuy tickets here: https://stza.co/~w0mg\n\nFollow on MiLB First Pitch: https://stza.co/+w0mg-1w\n\nShop: https://stza.co/+w0mg-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Marked Down Monday
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Hillcats
<2018-08-07 Tue 18:00-21:00>
:PROPERTIES:
:ID:       SYdQ4DW2E98AMJyklTFuECDv@stanza.co
:LOCATION: Taco Tuesday
:STATUS:   CONFIRMED
:END:

Mudcats vs. Hillcats Fans can enjoy themselves with $1 tacos at the Taco Stand on the concourse.

Buy tickets here  https //stza.co/~w0mi

Follow on MiLB First Pitch  https //stza.co/+w0mi-j

Shop  https //stza.co/+w0mi-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Hillcats
END:VALARM
DTSTART:20180807T230000Z
DTEND:20180808T020000Z
UID:SYdQ4DW2E98AMJyklTFuECDv@stanza.co
SUMMARY:Mudcats vs. Hillcats
DESCRIPTION:Fans can enjoy themselves with $1 tacos at the Taco Stand on the concourse.\n\nBuy tickets here: https://stza.co/~w0mi\n\nFollow on MiLB First Pitch: https://stza.co/+w0mi-j\n\nShop: https://stza.co/+w0mi-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Taco Tuesday
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Hillcats
<2018-08-08 Wed 18:00-21:00>
:PROPERTIES:
:ID:       HyMRqBJr6R2Bpyn6UnYLhW79@stanza.co
:LOCATION: Dollar Dog Day
:STATUS:   CONFIRMED
:END:

Mudcats vs. Hillcats Mudcat fans can enjoy $1 Bright Leaf Hot Dog at all concession locations.

Buy tickets here  https //stza.co/~w0mk

Follow on MiLB First Pitch  https //stza.co/+w0mk-1E

Shop  https //stza.co/+w0mk-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Hillcats
END:VALARM
DTSTART:20180808T230000Z
DTEND:20180809T020000Z
UID:HyMRqBJr6R2Bpyn6UnYLhW79@stanza.co
SUMMARY:Mudcats vs. Hillcats
DESCRIPTION:Mudcat fans can enjoy $1 Bright Leaf Hot Dog at all concession locations.\n\nBuy tickets here: https://stza.co/~w0mk\n\nFollow on MiLB First Pitch: https://stza.co/+w0mk-1E\n\nShop: https://stza.co/+w0mk-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dollar Dog Day
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Red Sox
<2018-08-10 Fri>--<2018-08-09 Thu>
:PROPERTIES:
:ID:       n_tR-44-Pd__i4S4gpt3B85Q@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Red Sox Mudcats @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0ne-1w

Shop  https //stza.co/+w0ne-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180810
DTEND;VALUE=DATE:20180810
UID:n_tR-44-Pd__i4S4gpt3B85Q@stanza.co
SUMMARY:Mudcats @ Red Sox
DESCRIPTION:Mudcats @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0ne-1w\n\nShop: https://stza.co/+w0ne-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Red Sox
<2018-08-11 Sat>--<2018-08-10 Fri>
:PROPERTIES:
:ID:       bwFEcHOpbbRQ-7xo72ysSJSL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Red Sox Mudcats @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0nf-l

Shop  https //stza.co/+w0nf-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180811
DTEND;VALUE=DATE:20180811
UID:bwFEcHOpbbRQ-7xo72ysSJSL@stanza.co
SUMMARY:Mudcats @ Red Sox
DESCRIPTION:Mudcats @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0nf-l\n\nShop: https://stza.co/+w0nf-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Red Sox
<2018-08-12 Sun>--<2018-08-11 Sat>
:PROPERTIES:
:ID:       CMU5p797J8QnkiidmZ5FQevP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mudcats @ Red Sox Mudcats @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0ng-2z

Shop  https //stza.co/+w0ng-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180812
DTEND;VALUE=DATE:20180812
UID:CMU5p797J8QnkiidmZ5FQevP@stanza.co
SUMMARY:Mudcats @ Red Sox
DESCRIPTION:Mudcats @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0ng-2z\n\nShop: https://stza.co/+w0ng-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Red Sox
<2018-08-13 Mon>--<2018-08-12 Sun>
:PROPERTIES:
:ID:       U-ml4Igf4zTc77alnefiaZMc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Red Sox Mudcats @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0nh-3l

Shop  https //stza.co/+w0nh-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180813
DTEND;VALUE=DATE:20180813
UID:U-ml4Igf4zTc77alnefiaZMc@stanza.co
SUMMARY:Mudcats @ Red Sox
DESCRIPTION:Mudcats @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0nh-3l\n\nShop: https://stza.co/+w0nh-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Wood Ducks
<2018-08-14 Tue 18:00-21:00>
:PROPERTIES:
:ID:       _aSlvNjDOhod6UJRbrBIVyqb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Wood Ducks Mudcats @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0mM-I

Shop  https //stza.co/+w0mM-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Wood Ducks
END:VALARM
DTSTART:20180814T230000Z
DTEND:20180815T020000Z
UID:_aSlvNjDOhod6UJRbrBIVyqb@stanza.co
SUMMARY:Mudcats @ Wood Ducks
DESCRIPTION:Mudcats @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0mM-I\n\nShop: https://stza.co/+w0mM-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Wood Ducks
<2018-08-15 Wed 18:00-21:00>
:PROPERTIES:
:ID:       d7BjIL9ZAgpX2fit_XPXjFx5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mudcats @ Wood Ducks Mudcats @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0mN-1E

Shop  https //stza.co/+w0mN-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Wood Ducks
END:VALARM
DTSTART:20180815T230000Z
DTEND:20180816T020000Z
UID:d7BjIL9ZAgpX2fit_XPXjFx5@stanza.co
SUMMARY:Mudcats @ Wood Ducks
DESCRIPTION:Mudcats @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0mN-1E\n\nShop: https://stza.co/+w0mN-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Wood Ducks
<2018-08-16 Thu 18:00-21:00>
:PROPERTIES:
:ID:       L2yoUflR374O9Pr_t4xM87LC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Wood Ducks Mudcats @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0mO-5

Shop  https //stza.co/+w0mO-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Wood Ducks
END:VALARM
DTSTART:20180816T230000Z
DTEND:20180817T020000Z
UID:L2yoUflR374O9Pr_t4xM87LC@stanza.co
SUMMARY:Mudcats @ Wood Ducks
DESCRIPTION:Mudcats @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0mO-5\n\nShop: https://stza.co/+w0mO-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Nationals
<2018-08-17 Fri 18:00-21:00>
:PROPERTIES:
:ID:       tWezbUMfWQHNit833f1DU-KY@stanza.co
:LOCATION: Celebrate the start of the weekend with our Friday Night Fireworks after the game!
:STATUS:   CONFIRMED
:END:

Mudcats vs. Nationals Stay after the game and enjoy fireworks shows after every Friday home game.

Buy tickets here  https //stza.co/~w0mm

Follow on MiLB First Pitch  https //stza.co/+w0mm-26

Shop  https //stza.co/+w0mm-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Nationals
END:VALARM
DTSTART:20180817T230000Z
DTEND:20180818T020000Z
UID:tWezbUMfWQHNit833f1DU-KY@stanza.co
SUMMARY:Mudcats vs. Nationals
DESCRIPTION:Stay after the game and enjoy fireworks shows after every Friday home game.\n\nBuy tickets here: https://stza.co/~w0mm\n\nFollow on MiLB First Pitch: https://stza.co/+w0mm-26\n\nShop: https://stza.co/+w0mm-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Celebrate the start of the weekend with our Friday Night Fireworks after the game!
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Nationals
<2018-08-18 Sat 16:00-19:00>
:PROPERTIES:
:ID:       KAHpJfnMXdKrP7EJXIkJYdQ3@stanza.co
:LOCATION: Mudcats Mania Wrestling Night
:STATUS:   CONFIRMED
:END:

Mudcats vs. Nationals Are you ready to rumble? Join the Mudcats as we celebrate wrestling here at Five County Stadium! 

Also, the first 1,200 kids age 13 and under in attendance will receive a free souvenir wrestling mask at Five County Stadium.

Buy tickets here  https //stza.co/~w0mn

Follow on MiLB First Pitch  https //stza.co/+w0mn-1a

Shop  https //stza.co/+w0mn-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Nationals
END:VALARM
DTSTART:20180818T210000Z
DTEND:20180819T000000Z
UID:KAHpJfnMXdKrP7EJXIkJYdQ3@stanza.co
SUMMARY:Mudcats vs. Nationals
DESCRIPTION:Are you ready to rumble? Join the Mudcats as we celebrate wrestling here at Five County Stadium! \n\nAlso, the first 1,200 kids age 13 and under in attendance will receive a free souvenir wrestling mask at Five County Stadium.\n\nBuy tickets here: https://stza.co/~w0mn\n\nFollow on MiLB First Pitch: https://stza.co/+w0mn-1a\n\nShop: https://stza.co/+w0mn-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Mudcats Mania Wrestling Night
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Nationals
<2018-08-19 Sun 13:00-16:00>
:PROPERTIES:
:ID:       qP4ayNwy8yXuSpYE-8Q5gbux@stanza.co
:LOCATION: Muddy's Buddies Kids Club Sunday
:STATUS:   CONFIRMED
:END:

Mudcats vs. Nationals Each kid that is part of the Muddy's Buddies Kids Club gets one free box seat ticket to every Sunday home game, excluding May 27th.  All-Star Members receive 1 Free Speed Pitch Pass & 1 Free Spin on the Prize Wheel by presenting their membership cards.

Buy tickets here  https //stza.co/~w0mq

Follow on MiLB First Pitch  https //stza.co/+w0mq-3M

Shop  https //stza.co/+w0mq-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Nationals
END:VALARM
DTSTART:20180819T180000Z
DTEND:20180819T210000Z
UID:qP4ayNwy8yXuSpYE-8Q5gbux@stanza.co
SUMMARY:Mudcats vs. Nationals
DESCRIPTION:Each kid that is part of the Muddy's Buddies Kids Club gets one free box seat ticket to every Sunday home game, excluding May 27th.  All-Star Members receive 1 Free Speed Pitch Pass & 1 Free Spin on the Prize Wheel by presenting their membership cards.\n\nBuy tickets here: https://stza.co/~w0mq\n\nFollow on MiLB First Pitch: https://stza.co/+w0mq-3M\n\nShop: https://stza.co/+w0mq-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Muddy's Buddies Kids Club Sunday
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Astros
<2018-08-21 Tue 18:00-21:00>
:PROPERTIES:
:ID:       HyvGTeSMuy16BudGWHoGPi-B@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Astros Mudcats @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM8P-1c

Shop  https //stza.co/+xM8P-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Astros
END:VALARM
DTSTART:20180821T230000Z
DTEND:20180822T020000Z
UID:HyvGTeSMuy16BudGWHoGPi-B@stanza.co
SUMMARY:Mudcats @ Astros
DESCRIPTION:Mudcats @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM8P-1c\n\nShop: https://stza.co/+xM8P-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Astros
<2018-08-22 Wed 18:00-21:00>
:PROPERTIES:
:ID:       0-rvOR3gDLVSCsM-1jYGvAX4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mudcats @ Astros Mudcats @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM8Q-1B

Shop  https //stza.co/+xM8Q-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Astros
END:VALARM
DTSTART:20180822T230000Z
DTEND:20180823T020000Z
UID:0-rvOR3gDLVSCsM-1jYGvAX4@stanza.co
SUMMARY:Mudcats @ Astros
DESCRIPTION:Mudcats @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM8Q-1B\n\nShop: https://stza.co/+xM8Q-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Astros
<2018-08-23 Thu 18:00-21:00>
:PROPERTIES:
:ID:       9SYtRBrraznYBQfkeoos99Ah@stanza.co
:LOCATION: Thirsty Thursday
:STATUS:   CONFIRMED
:END:

Mudcats vs. Astros Sit back and enjoy a Mudcats game with some cold ones with 1/2 price draft beers and $1-12oz Coca-Cola fountain products.

Buy tickets here  https //stza.co/~w0ms

Follow on MiLB First Pitch  https //stza.co/+w0ms-J

Shop  https //stza.co/+w0ms-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Astros
END:VALARM
DTSTART:20180823T230000Z
DTEND:20180824T020000Z
UID:9SYtRBrraznYBQfkeoos99Ah@stanza.co
SUMMARY:Mudcats vs. Astros
DESCRIPTION:Sit back and enjoy a Mudcats game with some cold ones with 1/2 price draft beers and $1-12oz Coca-Cola fountain products.\n\nBuy tickets here: https://stza.co/~w0ms\n\nFollow on MiLB First Pitch: https://stza.co/+w0ms-J\n\nShop: https://stza.co/+w0ms-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursday
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Keys
<2018-08-24 Fri 18:00-21:00>
:PROPERTIES:
:ID:       TSrBOz9nW9CnO2OKGQbQunvY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Keys Mudcats @ Keys

Follow on MiLB First Pitch  https //stza.co/+wi6D-3x

Shop  https //stza.co/+wi6D-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Keys
END:VALARM
DTSTART:20180824T230000Z
DTEND:20180825T020000Z
UID:TSrBOz9nW9CnO2OKGQbQunvY@stanza.co
SUMMARY:Mudcats @ Keys
DESCRIPTION:Mudcats @ Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wi6D-3x\n\nShop: https://stza.co/+wi6D-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Keys
<2018-08-25 Sat 17:00-20:00>
:PROPERTIES:
:ID:       j5Vdxy-aowTIDh5_eJZWBrFV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Keys Mudcats @ Keys

Follow on MiLB First Pitch  https //stza.co/+wi6E-19

Shop  https //stza.co/+wi6E-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Keys
END:VALARM
DTSTART:20180825T220000Z
DTEND:20180826T010000Z
UID:j5Vdxy-aowTIDh5_eJZWBrFV@stanza.co
SUMMARY:Mudcats @ Keys
DESCRIPTION:Mudcats @ Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wi6E-19\n\nShop: https://stza.co/+wi6E-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Keys
<2018-08-26 Sun 13:00-16:00>
:PROPERTIES:
:ID:       Ze5G2llMk1vn01RON1Zg8sHc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Mudcats @ Keys Mudcats @ Keys

Follow on MiLB First Pitch  https //stza.co/+wi6H-1C

Shop  https //stza.co/+wi6H-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Keys
END:VALARM
DTSTART:20180826T180000Z
DTEND:20180826T210000Z
UID:Ze5G2llMk1vn01RON1Zg8sHc@stanza.co
SUMMARY:Mudcats @ Keys
DESCRIPTION:Mudcats @ Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wi6H-1C\n\nShop: https://stza.co/+wi6H-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Wood Ducks
<2018-08-27 Mon 18:00-21:00>
:PROPERTIES:
:ID:       pcL41pHbdccrn3bHstVxPCa0@stanza.co
:LOCATION: Marked Down Monday
:STATUS:   CONFIRMED
:END:

Mudcats vs. Wood Ducks Every Monday in 2018 is a Marked Down Monday.  All Box Seat tickets are just $8, either online or at the Five County Stadium Box Office.  Parking will also be free every Monday Night.  Marked Down Mondays also feature reduced price concession items to satisfy everyone's appetite.

Buy tickets here  https //stza.co/~w0mu

Follow on MiLB First Pitch  https //stza.co/+w0mu-3l

Shop  https //stza.co/+w0mu-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Wood Ducks
END:VALARM
DTSTART:20180827T230000Z
DTEND:20180828T020000Z
UID:pcL41pHbdccrn3bHstVxPCa0@stanza.co
SUMMARY:Mudcats vs. Wood Ducks
DESCRIPTION:Every Monday in 2018 is a Marked Down Monday.  All Box Seat tickets are just $8, either online or at the Five County Stadium Box Office.  Parking will also be free every Monday Night.  Marked Down Mondays also feature reduced price concession items to satisfy everyone's appetite.\n\nBuy tickets here: https://stza.co/~w0mu\n\nFollow on MiLB First Pitch: https://stza.co/+w0mu-3l\n\nShop: https://stza.co/+w0mu-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Marked Down Monday
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Wood Ducks
<2018-08-28 Tue 18:00-21:00>
:PROPERTIES:
:ID:       frxNXkSEGrsr0DiE-8nlZm4M@stanza.co
:LOCATION: Taco Tuesday
:STATUS:   CONFIRMED
:END:

Mudcats vs. Wood Ducks Fans can enjoy themselves with $1 tacos at the Taco Stand on the concourse.

Buy tickets here  https //stza.co/~w0mv

Follow on MiLB First Pitch  https //stza.co/+w0mv-q

Shop  https //stza.co/+w0mv-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Wood Ducks
END:VALARM
DTSTART:20180828T230000Z
DTEND:20180829T020000Z
UID:frxNXkSEGrsr0DiE-8nlZm4M@stanza.co
SUMMARY:Mudcats vs. Wood Ducks
DESCRIPTION:Fans can enjoy themselves with $1 tacos at the Taco Stand on the concourse.\n\nBuy tickets here: https://stza.co/~w0mv\n\nFollow on MiLB First Pitch: https://stza.co/+w0mv-q\n\nShop: https://stza.co/+w0mv-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Taco Tuesday
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Wood Ducks
<2018-08-29 Wed 18:00-21:00>
:PROPERTIES:
:ID:       WJgKK3E4o34uAgd77JHegxa3@stanza.co
:LOCATION: Dollar Dog Day
:STATUS:   CONFIRMED
:END:

Mudcats vs. Wood Ducks Mudcat fans can enjoy $1 Bright Leaf Hot Dog at all concession locations.

Buy tickets here  https //stza.co/~w0my

Follow on MiLB First Pitch  https //stza.co/+w0my-$

Shop  https //stza.co/+w0my-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Wood Ducks
END:VALARM
DTSTART:20180829T230000Z
DTEND:20180830T020000Z
UID:WJgKK3E4o34uAgd77JHegxa3@stanza.co
SUMMARY:Mudcats vs. Wood Ducks
DESCRIPTION:Mudcat fans can enjoy $1 Bright Leaf Hot Dog at all concession locations.\n\nBuy tickets here: https://stza.co/~w0my\n\nFollow on MiLB First Pitch: https://stza.co/+w0my-$\n\nShop: https://stza.co/+w0my-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dollar Dog Day
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Wood Ducks
<2018-08-30 Thu 18:00-21:00>
:PROPERTIES:
:ID:       k2FrRHdbMqmQpITzkei23OIO@stanza.co
:LOCATION: Thirsty Thursday
:STATUS:   CONFIRMED
:END:

Mudcats vs. Wood Ducks Sit back and enjoy a Mudcats game with some cold ones with 1/2 price draft beers and $1-12oz Coca-Cola fountain products.

Buy tickets here  https //stza.co/~w0mA

Follow on MiLB First Pitch  https //stza.co/+w0mA-1G

Shop  https //stza.co/+w0mA-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Wood Ducks
END:VALARM
DTSTART:20180830T230000Z
DTEND:20180831T020000Z
UID:k2FrRHdbMqmQpITzkei23OIO@stanza.co
SUMMARY:Mudcats vs. Wood Ducks
DESCRIPTION:Sit back and enjoy a Mudcats game with some cold ones with 1/2 price draft beers and $1-12oz Coca-Cola fountain products.\n\nBuy tickets here: https://stza.co/~w0mA\n\nFollow on MiLB First Pitch: https://stza.co/+w0mA-1G\n\nShop: https://stza.co/+w0mA-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursday
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Astros
<2018-08-31 Fri 18:00-21:00>
:PROPERTIES:
:ID:       2EeTknNDnJrqoyFm3E7bSxAv@stanza.co
:LOCATION: Celebrate the start of the weekend with our Friday Night Fireworks after the game!
:STATUS:   CONFIRMED
:END:

Mudcats vs. Astros Stay after the game and enjoy fireworks shows after every Friday home game.

Join us as we salute our nation's military with our annual Military Appreciation Night. The Mudcats will wear a patriotic themed jersey with the net proceeds benefiting Hire Heroes USA.

Buy tickets here  https //stza.co/~w0mC

Follow on MiLB First Pitch  https //stza.co/+w0mC-P

Shop  https //stza.co/+w0mC-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Astros
END:VALARM
DTSTART:20180831T230000Z
DTEND:20180901T020000Z
UID:2EeTknNDnJrqoyFm3E7bSxAv@stanza.co
SUMMARY:Mudcats vs. Astros
DESCRIPTION:Stay after the game and enjoy fireworks shows after every Friday home game.\n\nJoin us as we salute our nation's military with our annual Military Appreciation Night. The Mudcats will wear a patriotic themed jersey with the net proceeds benefiting Hire Heroes USA.\n\nBuy tickets here: https://stza.co/~w0mC\n\nFollow on MiLB First Pitch: https://stza.co/+w0mC-P\n\nShop: https://stza.co/+w0mC-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Celebrate the start of the weekend with our Friday Night Fireworks after the game!
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats vs. Astros
<2018-09-01 Sat 17:00-20:00>
:PROPERTIES:
:ID:       541vtzZYGGEq0pnf62qkE-OB@stanza.co
:LOCATION: Fan Appreciation Day
:STATUS:   CONFIRMED
:END:

Mudcats vs. Astros It's the 2018 season finale at Five County Stadium! The Mudcats will be celebrating you the fans with our annual jersey off our backs campaign. 

Following the game is our final fireworks extravaganza of the season! 

Buy tickets here  https //stza.co/~w0mD

Follow on MiLB First Pitch  https //stza.co/+w0mD-27

Shop  https //stza.co/+w0mD-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Mudcats vs. Astros
END:VALARM
DTSTART:20180901T220000Z
DTEND:20180902T010000Z
UID:541vtzZYGGEq0pnf62qkE-OB@stanza.co
SUMMARY:Mudcats vs. Astros
DESCRIPTION:It's the 2018 season finale at Five County Stadium! The Mudcats will be celebrating you the fans with our annual jersey off our backs campaign. \n\nFollowing the game is our final fireworks extravaganza of the season! \n\nBuy tickets here: https://stza.co/~w0mD\n\nFollow on MiLB First Pitch: https://stza.co/+w0mD-27\n\nShop: https://stza.co/+w0mD-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fan Appreciation Day
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Astros
<2018-09-02 Sun 13:00-16:00>
:PROPERTIES:
:ID:       olX5qUz-wqrvn76psbxSdsBz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Astros Mudcats @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM8R-24

Shop  https //stza.co/+xM8R-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Astros
END:VALARM
DTSTART:20180902T180000Z
DTEND:20180902T210000Z
UID:olX5qUz-wqrvn76psbxSdsBz@stanza.co
SUMMARY:Mudcats @ Astros
DESCRIPTION:Mudcats @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM8R-24\n\nShop: https://stza.co/+xM8R-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Mudcats @ Astros
<2018-09-03 Mon 10:00-13:00>
:PROPERTIES:
:ID:       kEb3bQrSYQvyFI6HNeXWmN9m@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Mudcats @ Astros Mudcats @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM8S-j

Shop  https //stza.co/+xM8S-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Mudcats @ Astros
END:VALARM
DTSTART:20180903T150000Z
DTEND:20180903T180000Z
UID:kEb3bQrSYQvyFI6HNeXWmN9m@stanza.co
SUMMARY:Mudcats @ Astros
DESCRIPTION:Mudcats @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM8S-j\n\nShop: https://stza.co/+xM8S-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
